### ISSUE TITLE
Events Page VRMS API Implementation 

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#1010]
### Overview
We need to have the Events page more dynamic through the API so that this page can be accurate in a live time manner. 

### Action Items
- [ ] Have the days of the week & times be generated dynamically using the VRMS API.

### Resources/Instructions
[Events Page](https://www.hackforla.org/events)

**Comment by drubgrubby** [comment]
@ahdithebomb - We, the developers, are a little unsure of what you asking here.  It appears that the times are already being pulled from VRMS, and dynamically changing the time based on the person's location.  How much more dynamic are we trying to make it?

**Comment by drubgrubby** [comment]
@ahdithebomb - Is this issue the same as https://github.com/hackforla/website/issues/1042 ?

**Comment by ahdithebomb** [comment]
> @ahdithebomb - Is this issue the same as #1042 ?

Yes it is

**Comment by akibrhast** [comment]
Should this issue be closed? Given that this is the same #1042 , which has already been addressed and closed.
@ahdithebomb
