### ISSUE TITLE
Make Partner On Project Cards Hyperlinks

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1013]
### Overview
On project pages make listed partners as active hyperlinks so that visitors can more easily check out our partners

### Action Items
- [ ] Get signed off from product
- [ ] Figure out pages that need to be updated
- [ ] Update Markdown files and update logic to show up to page cards as links
- [ ] Update logic so that page partner show up as hyperlinks, if links are provided

#### Suggestions
Set it up the same way we have leadership set up. Have link open in  a new tab.
![image](https://user-images.githubusercontent.com/32349001/107158004-4a065e00-6955-11eb-9795-0a2f69501645.png)

### Resources/Instructions
- [Project Template](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)
- [Project Card](https://github.com/hackforla/website/blob/gh-pages/_includes/project-card.html)
- [Projects Page Html](https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html)

**Comment by akibrhast** [comment]
Waiting for approval by Product and happy to get working on it !

**Comment by ExperimentsInHonesty** [comment]
Replaced by #1053
