### ISSUE TITLE
Update the Civic Tech Structure project with a link to their overview (one sheet)

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/website#1023]
### Overview
We need to add a link to the Overview for the Civic Tech Structure to its project.md file

### Action Items
- [x] Add link to Overview document in card.
- [x] Confirm that it is showing up at the bottom
- [x] Add a screenshot to this issue in the comments
- [x] Confirm user acceptance testing at https://github.com/hackforla/product-management/issues/63

### Resources/Instructions
Civic Tech Structure Overview: https://github.com/hackforla/product-management/blob/master/project-one-sheets/Civic-Tech-Structure-Product-One-Sheet.pdf
Project card: _projects/civic-tech-structure.md

What it should look like when you get it done
![Screen Shot 2021-02-02 at 9 19 29 PM](https://user-images.githubusercontent.com/37763229/106702000-79574c80-659c-11eb-8d0c-0934d51d1e9e.png)

**Comment by pascuas** [comment]
<img width="960" alt="Screen Shot 2021-04-20 at 10 18 17 AM" src="https://user-images.githubusercontent.com/59798280/115438078-ce7d2480-a1c1-11eb-9d5b-8c656887576a.png">

**Comment by Lol-Whut** [comment]
closing this since merge didn't auto close :)
