### ISSUE TITLE
Create a Standard Website Page Template for Wiki

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1027]
### Dependency

#1534

### Overview
We need to create a template for new pages on the HfLA site so that new developers on the team can have an easier time building pages. This template wiki will be linked to in another bigger wiki about building new pages.

### Action Items
- [x] Research standard HTML structure of pages on the HfLA website (there is a wide variety, but find common elements)
- [x] Draft standard HTML page template
- [x] Create a wiki with the standard page template (similar to this [project.md template wiki](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file))
- [x] Add notes on the bottom of the wiki explaining different parts of the template (for anything that isn't self-explanatory)
- [x] Add Design System documentation

### Resources/Instructions
[Template of a project.md file wiki](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)

**Comment by ItsLaszlo** [comment]
Progress: working on an [outline](https://docs.google.com/document/d/194hhPbQwWwjZOKYBP17U4F1hvTxHTyHEQVC6Xx5ekmI/edit?usp=sharing) 
Blockers: none yet
ETA: TBD

**Comment by ItsLaszlo** [comment]
Progress: will set up a time this week with Danielle to discuss the template 
Blockers: none yet
ETA: TBD

**Comment by ItsLaszlo** [comment]
Progress: Met with Danielle and template now needs to be reviewed by the other devs
Blockers: none yet
ETA: TBD

**Comment by ItsLaszlo** [comment]
As this is done make another issue to update the wiki once #1138 is completed.

**Comment by ItsLaszlo** [comment]
Current wiki: https://github.com/hackforla/website/wiki/How-to-create-a-page-on-Hack-for-LA-website

**Comment by akibrhast** [comment]
@martham0 The instructions linked above are pretty spot on! Thank you for making that wiki! 
It's done then right? Can we close/resolve this?

**Comment by ItsLaszlo** [comment]
Progress: needs to be reviewed by developers
Blockers: none
ETA: 3/9/20
wiki link:
https://github.com/hackforla/website/wiki/How-to-create-a-page-on-Hack-for-LA-website

**Comment by tarang100** [comment]
Please provide status update

**Comment by ItsLaszlo** [comment]
Progress: Completed and linked in resources and website architecture
wiki link:
https://github.com/hackforla/website/wiki/How-to-create-a-page-on-Hack-for-LA-website

**Comment by ItsLaszlo** [comment]
> @martham0 The instructions linked above are pretty spot on! Thank you for making that wiki!
> It's done then right? Can we close/resolve this?

The issue must be kept open for @daniellex0. She has a couple of things to add to it regarding the standardization of classes and components.

**Comment by daniellex0** [comment]
Progress: Working on this (adding more reusable component information to this wiki)

Next Steps: Should be able to finish this week

**Comment by daniellex0** [comment]
Progress: Continuing to work on reusable component information for this wiki- now that page cards are standardized I can move forward.

Next Steps: Finish draft and give devs for review

ETA: 3/30

**Comment by daniellex0** [comment]
Progress: Working on Design System documentation this week, and planning to finish this developer-facing documentation this week.

Next Steps: Finish draft and give devs for review

ETA: 3/30

**Comment by akibrhast** [comment]
@daniellex0 Where do I find the drafts for review?

**Comment by akibrhast** [comment]
I might be wrong , but is this issue related to this https://github.com/hackforla/website/issues/1416 ?

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 What are the next steps for this issue?
