### ISSUE TITLE
Slack message upon win form completed

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1028]
### Overview
Every time that someone sends in a win, we have to approve it. Can you figure out how to send our slack channel a message every time that someone fills out the win form?

### Action Items
- [x] get acquainted with the google form and sheets linked below
- [x] figure out how to do an action every time that a form is submitted
- [x] figure out how to communicate with our slack
- [x] consult with bonnie once you have a working plan

### Resources/Instructions

- [wins-page google docs folder](https://drive.google.com/drive/folders/1Yglu0ehQQu2hhjd0Rf6AS1sPlNvPHnay)
- [google form](https://docs.google.com/forms/d/1RhgDlPikDz63hoIDYQag8pUZwYtKq-ZpGG46mhVOrL0/edit)
- [form responses on google sheet](https://docs.google.com/spreadsheets/d/1tj6eQlVLFgmskoXouVt87POxYVwR1yWT2vOSQEPyDtg/edit?usp=drive_web&ouid=104151125916189543453)

**Comment by akibrhast** [comment]
## Tentative Additional Resources
- https://github.com/markfguerra/google-forms-to-slack
- https://zapier.com/apps/google-forms/integrations/slack/
- https://medium.com/@01010111/using-google-forms-to-submit-github-issues-efdb5f876b

**Comment by akibrhast** [comment]
Since the wins submission upon approval seems to be saved under `_data/wins_data.json` and since Slack GitHub app is already part of the Hack ForLA.

We could follow this path 
---
On Submit Wins Google Form -> [Create New Github Issue With Label(role:adminstrative)(winsSubmisison)](https://medium.com/@01010111/using-google-forms-to-submit-github-issues-efdb5f876b) -> [In slack subscribe to the hackLA website repo with the aforementioned labels
](https://github.com/integrations/slack#creating-a-filter) -> If ticket is approved a GitHub action should run that would get the data from the ticket and put it wins_data.json

**Comment by akibrhast** [comment]
This is the output of a quick test of  subscribing to hackforla/website via slack

![image](https://user-images.githubusercontent.com/32349001/107866621-c4951900-6e40-11eb-8e68-9956307ea4e1.png)

**Comment by akibrhast** [comment]
Upon further testing I am now able to create a GitHub issue with labels and assignees via google forms, and get Notified on slack if and only if the issue created has a label of "winsSubmission" . All other notifications are disabled for slack, but I wont be sure how well they are working until tomorrow morning when there will be a bunch of pull requests and merges.

The following AppsScript needs to be added to the google form | [Step-By-Step-Guide](https://medium.com/@01010111/using-google-forms-to-submit-github-issues-efdb5f876b)
```
var token = "<hackforla_personal_access_token>";
var handle = "hackforla";
var repo = "website";
function onFormSubmit(e)
{
 
    var title = e.values[1];
    var body = e.values[2];
    var payload = {
        "title": title,
        "body": body,
        "labels":["winsSubmission","role: administrative"],
        "assignees":["ExperimentsInHonesty","drubgrubby"]
    };
 
    var options = {
        "method": "POST",
        "contentType": "application/json",
        "payload": JSON.stringify(payload)
    };
   var response = UrlFetchApp.fetch("https://api.github.com/repos/"+handle+"/"+repo+"/issues?access_token="+token, options);
}
```
---
![image](https://user-images.githubusercontent.com/32349001/107868461-856fc380-6e52-11eb-89c4-3d6c8289b86a.png)

@ExperimentsInHonesty Awaiting Consultation :D

**Comment by akibrhast** [comment]
@ExperimentsInHonesty Just wanted to reconfirm what you said last time in our meeting. If I am not mistaken you said 'I already have a solution for that' in regards to getting a notification on slack when the google sheet adds a new row to it. I believe the solution involved using Zapier ? I was looking into Zapier and I believe only someone with admin rights on the slack channel can add the new if this then that zapier condition needed for the sheets update notification.

**Comment by josiehandeveloper** [comment]
@ExperimentsInHonesty Should we use Zapier or Google Apps Script? 
Akib said that he already has feasible solutions using Google Apps Script

**Comment by Sihemgourou** [comment]
@akibrhast Bonnie said Google Apps Script is fine.

**Comment by akibrhast** [comment]
This feature has now been implemented. Below is the link to the google app script and the functions that makes this work

- https://script.google.com/home/projects/1jySuEtxGfrQpuX1zinjH7sGlqevEnakVx9hGTaCnx-z0K6dQTwRVGMlI/edit
```javascript
function createIssue(e){
 
    let title = "Review Needed - New Wins Form Submission";
    let body = "A new wins form submission has just been created. Please navigate to the link below to review it.<br><br>- [Wins Submission Google Sheet](https://docs.google.com/spreadsheets/d/1tj6eQlVLFgmskoXouVt87POxYVwR1yWT2vOSQEPyDtg/edit?resourcekey#gid=1106372497)";
    let payload = {
        "title": title,
        "body": body,
        "labels":["new-win-submission","role: administrative"], // new-win-submission
    };
 
    let options = {
        "method": "POST",
        'headers' : {
          'Accept' : 'application/vnd.github.v3+json',
          'ContentType' : 'application/json',
          'Authorization' : `token ${TOKEN}`
        },
        "payload": JSON.stringify(payload),
    };

    let response = UrlFetchApp.fetch(`https://api.github.com/repos/hackforla/website/issues`, options);

    let data = JSON.parse(response.getContentText())

    addIssueToAProjectBoardColumn(data.id, GithubProjectColumKey["Links/Questions/InReview"])
}

function addIssueToAProjectBoardColumn(issueID,columnID){

    let payload = {
        "id": parseInt(issueID),
        "content_id": parseInt(issueID),
        "content_type": "Issue", // new-win-submission
    };

    let options = {
        "method": "POST",
        'headers' : {
          'Accept' : 'application/vnd.github.inertia-preview+json',
          'Authorization' : `token ${TOKEN}`
        },
        "payload": JSON.stringify(payload),
        "muteHttpExceptions":true
    };
    let response = UrlFetchApp.fetch(`https://api.github.com/projects/columns/${columnID}/cards`, options);

}

```
