### ISSUE TITLE
Make a linkedin api call to grab linked in photos 

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1029]
### Dependency
- [x] https://github.com/hackforla/website/issues/1076

### Overview
Create a linked in scraper to grab a linked in photo given someone's linked in profile, for the wins page

### Action Items
- [ ] write a LinkedIn scraper
- [x] figure out what is the best way to save the LinkedIn photos
- [ ] create a GitHub action to execute it

### Resources/Instructions
[LinkedIn Profile Scraper](https://github.com/jvandenaardweg/linkedin-profile-scraper)
[Data Scraping With GitHub Actions](https://github.com/sw-yx/gh-action-data-scraping)

**Comment by akibrhast** [comment]
@jbubar 

>  use linkedin photos on wins page
  - I think this action item should to be separated into its own ticket with #1029 linked as a dependency/blocker. It also has the potential to be labeled as a  "Good First Issue". What do you think?

>  figure out what is the best way to save the linkedin photos
 - What about saving it as `_data/linkedin_data.json`  ?
 - ``` {
    {
      id: <linkedin_id>,
      image: <linkedin_image_url> 
    } ```
---
To scrape the page we are going to need their linkedin id/url/username. Currently the wins page submission form provides an optional field for the url. But then it has two other fields which are none optional. I.e. This would allow a submission to state that they allow the use of the linked profile picture but not provide a linkedin url. Which might through conditionals that are using the wins-data.json file off.(Also the same question is asked twice?)
![image](https://user-images.githubusercontent.com/32349001/107865329-323a4880-6e33-11eb-9f9d-06d6924ee45b.png)

I was thinking the form could be reworked such that a non-optional LinkedIn URL input is shown only if the users answers yes to "Could we use your linkedin profile picture next to your story?"

**Comment by jbubar** [comment]
@akibrhast That is great thinking! Yes, Yes, and Yes!!  I think you are right on all of the above. I like the idea of having a linkedin_data.json file, and separating out the issue of connecting it to the wins page. I think this would be a medium sized issue. And I agree with your idea to rework the form. Which one of those things would you like to do?

**Comment by akibrhast** [comment]
:alien: :alien: :alien: @ahdithebomb @IAgbaje @pawan92 @tarang100 :alien: :alien: :alien:
1. After looking into writing a scraper for a person's LinkedIn photo. I have discovered that it will not be possible to write an anonymous scraper for LinkedIn. LinkedIn has made impossible to crawl through their site unless you are logged in.
2. As such I believe we are going to have to create a hackforla LinkedIn account for the bot to scrape(it’s something Bonnie needs to do I believe)
3. If setting up a bot LinkedIn account is not too difficult, I’d like to take this issue on now.  Otherwise, I’ll add it as a dependency to this issue.

**Comment by akibrhast** [comment]
> @akibrhast That is great thinking! Yes, Yes, and Yes!! I think you are right on all of the above. I like the idea of having a linkedin_data.json file, and separating out the issue of connecting it to the wins page. I think this would be a medium sized issue. And I agree with your idea to rework the form. Which one of those things would you like to do?

@jbubar If you could please take care of separating ' use linkedin photos on wins page' into it's own issue and adding this as a dependency that would be awesome!

Once we have a both linkedin account I would like to take care of the scraper and the github actions

**Comment by akibrhast** [comment]
## Update
According to @ahdithebomb 
> I believe this is in line with a letter we are aiming to write to LinkedIn for access for their API

**Comment by ExperimentsInHonesty** [comment]
This is not possible and is a violation of their terms of service.
