### ISSUE TITLE
Filtering dropdowns on wins page

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1030]
### Overview
create buttons to filter by Role and Team
![Screen Shot 2021-02-09 at 7 04 16 PM](https://user-images.githubusercontent.com/53061723/107458784-a0b49900-6b09-11eb-8a52-de374066b6fc.png)

### Action Items
- [ ] 

### Resources/Instructions
[figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0)
[project page](https://www.hackforla.org/#projects)

**Comment by akibrhast** [comment]
![branchProgress](https://user-images.githubusercontent.com/32349001/107578008-2e9f8b00-6bc1-11eb-975f-99e36731a5a7.gif)

## Progress Update
If you look at the gif , you will noticed that the url changes based on the selection.

## Need Information (What should the URL look like if the items in the query string have spaces?)
Currently they look like
```
role=Business%20Analyst,Development,PM&team=VRMS,HackforLA%20Website,Home%20Unite%20Us,311%20Data
```
But the project filter in the home page does something like this
```
looking=Business+Analyst&technologies=Code+Climate
```
The first one is replacing spaces with '%20' the second one is replacing spaces with "+"
Should I follow the second one?


@jbubar

**Comment by jbubar** [comment]
![Uploading ezgif.com-gif-maker (7).gif…]()

**Comment by jbubar** [comment]
It is up to you! I noticed the project page uses a '+' also. I am not sure why. I think the %20 makes more sense, otherwise you might get results that you are not looking for. 
But at the same time consistency is really important. 
I would live to hear your thoughts

**Comment by akibrhast** [comment]
Based on [this](https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20) and also due to the need of staying consistent. I am thinking we should just use '+' . Also based on really any other sides with query parameters , amazon,facebook,google,youtube ... they all seem to be using '+' for spaces in the query parameter .

**Comment by akibrhast** [comment]
The following gif demonstrates the changes made in the pull request
![issue#1030](https://user-images.githubusercontent.com/32349001/107864039-bdf9a800-6e26-11eb-88fd-07c8af3e3daf.gif)
