### ISSUE TITLE
Update Project Profile: Engage

### ISSUE THREAD

**Issue by tarang100** [hackforla/website#1033]
### Overview
As a product manager, I need to make sure that all the projects that are listed on the HfLA website are up to date so that my customers(visitors) can get an accurate picture of each of the projects.

### Project card
https://www.hackforla.org/projects/engage

### Action Items
Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
- [x] title
- [x] description
- [x] image
- [x] leadership
   - [x] Member Name
   - [x] Role
   - [x] Slack Member ID
   - [x] Github Handle
- [ ] links
  - [x] Github
  - [x] Slack
  - [x] Test Site
  - [x] Demo Site
  - [x] Site
  - [x] Overview: https://github.com/hackforla/product-management/issues/65 
  - [ ] wiki
- [x] looking
- [x] technologies
- [x] location
- [x] partner
- [x] tools
- [x] status

[Issue](https://github.com/hackla-engage/start-here/issues/11) for Logo Creation

**Comment by BryonPm** [comment]
@ExperimentsInHonesty Please refer to this issue for Engage page update. It contains all updated page content and references all other issues within the comment stream.

**Comment by Aveline-art** [comment]
> 
> 
> Need to update:
> 
> Meetings: All Team Members Sunday 4 PM PST; Wednesday 6 PST
> Product Manager Meeting Wednesday 5PM PST
> 
> Leadership - Remove Teddy and update to the following
> 
> Name: Bonnie Wolfe
> Role: Agile Coach
> Slack: UE1UG1YFP
> Github: ExperimentsInHonesty
> 
> Name: Ryan Mayott
> Role: UI/UX Designer
> slack: U01L3BJ3QSW
> github: rmayott
> 
> Name: Bryon Hart
> Role: Product Manager
> Slack: U01GHT3EMNZ
> Github: BryonPm
> 
> Name: Eli Selkin
> Role: Backend Architect and Technology Lead
> Slack: U0611PL2D
> Github: eselkin
> 
> Slack: #engage
> 
> Technologies: React, Node.js, PostgreSQL, MongoDB
> 
> Test Site - smstaging.engage.town
> 
> Looking - UX Program Designer, Product Manager (**remove UX designers; nlp engineers**)
> 
> Wiki - https://github.com/hackla-engage/start-here/wiki
> 
> Partner: **remove - city of santa monica** Various Los Angeles Neighborhood Councils
> 
> Description:
> Engage facilitates and streamlines the preparation of meeting agendas, getting word out to the local residents and compiling feedback from the public.
> Engage is a platform to help connect residents (and other stakeholders) to local government. Instead of requiring constituents to be present at meetings, which presents a host of challenges: work schedules, childcare, accessibility, fear that their voice would not be heard, or not understanding the meeting agenda.
> 
> **No change needed:**
> 
>     * Title
> 
>     * Github
> 
>     * Location
> 
>     * Status
> 
>     * Tools
> 
>     * Site
> 
>     * Demo site (no site to show)
> 
> 
> [Engage Logo 600x400 ](https://drive.google.com/file/d/14FGF6Bcp3LyRw56yDAo6AGPASCn4roJD/view?usp=sharing)

@BryonPm Attached to the bottom of the changes summary (see above) is a google link to the Engage Logo. Should it appear in any of these places:

- the project page ([link](https://www.hackforla.org/#projects))
- the engage project page ([link](https://www.hackforla.org/projects/engage))
- another page on the hackforla website (please specify)
- none of the above


Also, what is the duration for each of the three meeting times: 

1. All Team Members Sunday 4 PM PST
2. All Team Members Wednesday 6 PST
3. Product Manager Meeting Wednesday 5PM PST

Thank you!

**Comment by BryonPm** [comment]
@Aveline-art Please apply the logo to the project page. We will decide on the photo for the Engage Project Page within the next week. 

Meeting times are an hour in duration. 

All Team Members Sunday 4 PM-5PM PST
All Team Members Wednesday 6-7PM PST
Product Manager Meeting Wednesday 5PM-6PM PST

Please let me know if you have any other concerns. 

Best,
Bryon

**Comment by BryonPm** [comment]
@glenflorendo Please replace existing website text with: 

Engage is a civic participation platform that makes it easier for constituents to offer their feedback on policy issues that local Councils are considering. Engage aims to increase access for community stakeholders who are unable to attend public meetings or may otherwise feel unheard by their local government. 

The team will provide you with an alternative Hero image to resolve fade issue. 
ETA:1 Week or less

**Comment by jbubar** [comment]
@kathyfregoso @BryonPm The link to the Site, & Test Site provided in this issue are not working on my computer. 


<details>
    <summary>screenshot of error</summary>

![Screen Shot 2021-06-06 at 12 07 58 PM](https://user-images.githubusercontent.com/53061723/120937009-d8021380-c6bf-11eb-9e3d-45d6be2446ee.png)

</details>

**Comment by Sihemgourou** [comment]
@kathyfregoso @BryonPm Could you provide the right links please ?

**Comment by BryonPm** [comment]
@eselkin Please provide a time update for the site error message if possible.

**Comment by ExperimentsInHonesty** [comment]
The link to the wiki is correct, but the team has no content there now.  So please comment it out for now.
