### ISSUE TITLE
Standardize Events Page (SCSS)

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1041]
## Note! 
(from @akibrhast) : Since this issue is a placeholder issue on the path to standardize the events page. Do not close this issue until all the issue referencing this issue is closed.

### Overview
We need to standardize the Events page so that it is has visual consistency with the rest of the HfLA website and our design system.

### Action Items

Front-End Development

- [ ] Review the SCSS fixes on the [Events page file on Figma ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94)(on the bottom, in large orange box)
- [ ] Implement all of the fixes on the Events page's .scss file (_sass > components > _events.scss) and the few in its HTML file

### Resources/Instructions
[Events page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94) (edits on the bottom in large orange box)
[Current Events page](https://www.hackforla.org/events)

*The notes/scss edits I provided will hopefully help standardize the current Events page and get it closer to the mockup version. If any of my SCSS suggestions are ineffective, please feel free to figure something else out to get the right look. Also for some of the issues I could not find quick solutions, so those will need to be figured out. Please let me know if you have any questions.

**Comment by TeddyTelanoff** [comment]
![image](https://user-images.githubusercontent.com/29633838/108151984-d3700b80-708c-11eb-9d8c-ee56add1a4d2.png)

This part of the figma is not very clear, @daniellex0  can you please fix it?

**Comment by shaswa** [comment]
@akibrhast, @daniellex0 This seems like an issue that contains other issues. Usually we use a feature labelled e.g. `Feature: - Events Page`
Is this issue necessary?

**Comment by shaswa** [comment]
I've added the label `Feature - Events Page` to all the referenced issue.

**Comment by akibrhast** [comment]
After discussion on 3/21/2021 . This issue is now being closed because it has been broken down into smaller issues with the label `Feature - Events Page`.
