### ISSUE TITLE
Automate days of week in Events Page schedule - via VRMS

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1042]
### Overview
We need to automate the days of the week in the Events Page schedule, so that visitors in different time zones can view the accurate day attached to meeting times. 

The meeting times are already automatically displayed in their time zone (using VRMS data), but the days of week are currently just hard-coded into the page.

### Action Items

- [ ] Research using VRMS data to automate the schedule display by time zone 
   - [ ] Examine how the [Events Page](https://www.hackforla.org/events) schedule times are currently automated via VRMS
- [ ] Implement automation of the Events page schedule's days of week based on viewer's time zone

### Resources/Instructions
- Read **projectmeetings.html** section of [Site Architecture wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture#files) for information about how the similar [Project Team Meetings](https://www.hackforla.org/project-meetings) page pulls this information from VRMS
- [Events Page](https://www.hackforla.org/events)

*FYI the SCSS of the page is currently being standardized in another issue, but that shouldn't affect the work in this issue

<img width="427" alt="Screen Shot 2021-02-13 at 11 25 23 PM" src="https://user-images.githubusercontent.com/67400366/107871088-51e16900-6e53-11eb-9e98-e942526bf1c1.png">

**Comment by drubgrubby** [comment]
@daniellex0 - In looking at this issue we are not sure exactly what the problem is.  Yes, it is true that the days of the week are in the code in their fullness, but those are used to make the headings for each day of the week in the listing. 

Is the problem that the wrong meeting times are showing up in the wrong days of the week?  
Is there an issue that we are not seeing? 

Inquiring minds want to know.

**Comment by daniellex0** [comment]
@drubgrubby Yes the issue is closer to the former- that the wrong meeting day is showing up with the wrong times if the viewer is in a different time zone, especially in a different country. Monday night for us is Tuesday morning for someone in Europe, etc. This change was requested by @ExperimentsInHonesty

**Comment by drubgrubby** [comment]
@daniellex0 - The following two screen shots are from time-zones that are 12 hours apart. I don't see any evidence that the schedules are showing in the wrong day. It seems that the meetings are being moved into the correct day. I may be wrong; maybe I'm not seeing it.   

Do we have screen shots of the problem that we are trying to fix?  

<img width="421" alt="Screen Shot 2021-02-16 at 10 13 34 AM" src="https://user-images.githubusercontent.com/68244054/108104253-ec060480-703f-11eb-9e22-991357619f55.png">
<img width="453" alt="Screen Shot 2021-02-16 at 10 12 04 PM" src="https://user-images.githubusercontent.com/68244054/108104261-ee685e80-703f-11eb-9f8e-b4dcd0dda0e9.png">

That said, there does seem to be a problem with the meeting times, which I'm guessing is related to a daylight saving time calculation.  

@evancchen - The meeting times seem not to be making the correct calculation.  The time zone that is 12 hours ahead in the above screenshot is showing that the meeting time is only 11 hours ahead.  I'd guess that it has something to do with a daylight saving time calculation.  Can you please see if you can figure out (and correct) that issue? 

Also, the font for MONDAY is larger than the other days (at least on Firefox).  Can you correct that?

**Comment by daniellex0** [comment]
@drubgrubby @evancchen I'm about to talk with Bonnie, so I'll try to bring this up! 

Edit: Sorry the meeting is rescheduled for tomorrow, but I'll hopefully have an answer then.

**Comment by daniellex0** [comment]
Btw @evancchen maybe cross reference any changes you make with the Project Meetings page to see if the same changes should be made there too

**Comment by daniellex0** [comment]
Btw @evancchen maybe cross reference any changes you make with the [Project Meetings](https://www.hackforla.org/project-meetings) page to see if the same changes should be made there too

**Comment by daniellex0** [comment]
@drubgrubby @evancchen I'm not sure I updated you guys on this- Bonnie didn't realize the meeting times automatically jump down to the correct day, so you guys are right- the main problem in this issue is not an actual problem after all. But I'm glad it led to finding that bug!

**Comment by pawan92** [comment]
@evancchen Can you please add the labels for status?
Please refer to https://github.com/hackforla/website/wiki/Instructions-for-adding-Status-Labels-to-issues for understanding on how to add the status labels
