### ISSUE TITLE
Alphabetize the Homepage project filter categories

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1043]
### Overview
We need to organize the Homepage project filter categories in alphabetical order so that users can have an easier time finding the categories they are looking for.

### Action Items

- [x] Research how the project filter on the homepage works + how the order of its categories is currently set by examining the code
- [x] Alphabetize all of the project filter categories

### Resources/Instructions
[Hack for LA Homepage](https://www.hackforla.org/#)
[current-projects.html file](https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects.html) with filter

Example with no alphabetical order:

<img width="823" alt="Screen Shot 2021-02-13 at 11 40 54 PM" src="https://user-images.githubusercontent.com/67400366/107871338-5018a500-6e55-11eb-9fb1-325f65801f58.png">

**Comment by akibrhast** [comment]
![image](https://user-images.githubusercontent.com/32349001/108141946-c7874800-7092-11eb-9678-51deba066a97.png)
