### ISSUE TITLE
Standardize Project Meetings Page (SCSS)

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1044]
### Overview
We need to standardize the Project Meetings page so that it is has visual consistency with the rest of the HfLA website and our design system.

### Action Items
- [ ] Review the SCSS fixes on the [Project Team Meetings page file on Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=925%3A0) (to the right, in large orange box)
- [ ]  Implement all of the fixes on the Project Team Meetings page's .scss file (_sass / components / _project-meetings.scss) and the few in its HTML file

### Resources/Instructions
[Project Meetings Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=925%3A0) (notes to the right, in large orange box)
[Current Project Meetings page](https://www.hackforla.org/project-meetings)

*The notes/scss edits I provided will hopefully help standardize the current Project Meetings page (mostly the header) and get it closer to the mockup version. Please let me know if you have any questions.

**Comment by daniellex0** [comment]
> ![image](https://user-images.githubusercontent.com/29633838/108151984-d3700b80-708c-11eb-9d8c-ee56add1a4d2.png)
> 
> This part of the figma is not very clear, @daniellex0  can you please fix it?
> 
> _Originally posted by @TeddyTelanoff in https://github.com/hackforla/website/issues/1041#issuecomment-780271549_

So sorry @TeddyTelanoff , I just finally fixed this! Let me know if there are any other issues

**Comment by daniellex0** [comment]
(Just FYI @TeddyTelanoff since you might get an alert, I deleted your comment about this on the Events page issue to avoid confusion)

**Comment by pawan92** [comment]
@TeddyTelanoff Can you please add the labels for status?
Please refer to https://github.com/hackforla/website/wiki/Instructions-for-adding-Status-Labels-to-issues for understanding on how to add the status labels

**Comment by jbubar** [comment]
Teddy and I are going to go over this together tomorrow at 3pm

**Comment by kevinreber** [comment]
### Progress
Added all styling listed in Figma mock up.

### Blockers
There are some extra styles being applied that aren't mentioned in the Figma mock up. Consulting with @daniellex0 to see if these styles should be removed/modified.

<details>

<summary>Screenshots</summary>

Current

![image](https://user-images.githubusercontent.com/42260999/111890931-6f05dc00-89ab-11eb-944d-794fe114f74f.png)

Figma Mockup

![image](https://user-images.githubusercontent.com/42260999/111891206-5f3bc700-89ae-11eb-93d5-5d33672398c8.png)


</details>

### Availability
Wednesday Night, Thursday & Friday

### ETA
End of week

**Comment by kevinreber** [comment]
Progress
Received feedback from design, will have time to add updates later this week.

Blockers
Studying

Availability
evenings

ETA
End of week

**Comment by kevinreber** [comment]
### Progress
Added styling to match [Join Page](https://www.hackforla.org/join) styling. 
Waiting for feedback from design.

<details>

<summary>Desktop</summary>

Before
<img src="https://user-images.githubusercontent.com/42260999/113494144-72fd2800-949a-11eb-9867-f6b4112755fd.png" width="700px" />

After
<img src="https://user-images.githubusercontent.com/42260999/113493956-fe75b980-9498-11eb-97a6-90503d535dab.png " width="700px"/>

</details>

<details>

<summary>Tablet</summary>

Before
<img src="https://user-images.githubusercontent.com/42260999/113494169-b788c380-949a-11eb-8603-d49b529615c3.png" width="500px" />

After
<img src="https://user-images.githubusercontent.com/42260999/113493973-14837a00-9499-11eb-9b59-f416f0eb912c.png" width="500px" />

</details>

<details>

<summary>Mobile</summary>

Before
<img src="https://user-images.githubusercontent.com/42260999/113494161-a2139980-949a-11eb-8d77-f9d15e22cd18.png" width="300px" />

After
<img src="https://user-images.githubusercontent.com/42260999/113493982-206f3c00-9499-11eb-8782-d17cb7ec5658.png" width="300px" />

</details>

### Blockers
Studying/Renovating

### Availability
Evenings

### ETA
End of week

**Comment by daniellex0** [comment]
Thanks for adding the screenshots! Sent notes on Slack about making the image max-width 240px and fitting the heading on one line
