### ISSUE TITLE
Update Partner Information on HfLA Website: Heart

### ISSUE THREAD

**Issue by tarang100** [hackforla/website#1048]
### Overview
We need to update the Project Card for Heart to provide accurate information about the project's Partners. This will ensure correct information dissemination to all HfLA stakeholders

### Action Items
- [ ] Remove "LA City Attorney’s Homeless Engagement and Response Team" from the partner list for Heart
- [ ] Add "LA City & County Attorney’s Homeless Engagement and Response Team" to the partner list for Heart
- [ ] Create a pull request
- [ ] Ask someone in the Development or PM team to review the pull request
- [ ] Commit changes and close issue

### Resources/Instructions
[Profile Project Card for Heart](https://www.hackforla.org/projects/heart)
Screenshot of the current partner for reference

![image](https://user-images.githubusercontent.com/75314672/107877591-5a897c00-6ef3-11eb-8603-1ee2a6abceaf.png)

**Comment by kellydinneen** [comment]
@tarang100 Can I do this? Would be my first HfLA contribution
