### ISSUE TITLE
Creating Labels to Streamline the Weekly Team Meetings

### ISSUE THREAD

**Issue by tarang100** [hackforla/website#1054]
### Overview
We need to create labels that highlight the current status of an issue to help streamline the weekly team meetings by permitting quick filtering of the Project Board. We have discussed and decided to prioritize issues based on the following possible statuses

Please only **use one label at a time** and update **before the weekly meeting**. 

1. Blockers: The person assigned the issue has gone as far as possible. They need a response from someone else before work can continue on this issue. This is not the same as a dependency.
2. Dependency: This is the same as a blocker but a dependency label is added when another issue is blocking the completion or starting of this issue.
3. Help Wanted: Internal assistance is required to make progress but it is unclear who needs to help.
4. Update Added: No blockers and update is ready for review by Team Leads.
5. Needs Update: No update has been provided, needs to an update in order to be reviewed.
6. User Acceptance Testing: Ready to be tested after review

### Action Items
- [x] Create Labels for the following statuses
   - [x] Has Update
   - [x] Needs Update
   - [x] Blockers
   - [x] User Acceptance Testing
   - [x] Help Wanted
   - [x] Dependency
- [ ] Sensitize the team to utilize the above-mentioned labels while updating their respective issues
- [ ] Check and ensure that all Issues in the "In Progress" column have been appropriately labeled before the weekly team meetings
- [ ] If any issue is missing a status label, request the respective assignees to update the issue with the most relevant status label

### Resources/Instructions
[HfLA Website Project Board](https://github.com/hackforla/website/projects/7)

**Comment by drubgrubby** [comment]
Greetings team.  I have a couple of questions about the specific labels: 

1) What is the difference between status 1 and 2?
2) Often people put in their updates that they have a blocker, but the blocker is that they didn't have enough time to work on the issue.  How can we distinguish between blockers that we should look at during the meeting, and blockers that we don't need to look at during the meeting?  
3) Who is going to use status 4?  If we're counting on the person working on the issue to add the labels before each meeting, it seems unlikely that they would go to the trouble to put a status on it, but not bother to add an update.  Is this something that the project managers are going to add each week before the meeting? If so, what about changing it to "update requested". Then the project managers can request an update as a comment, and set this label, and when the person adds the update they can change the label to the correct one. Seems like a small semantic change, but also makes more sense to me.

**Comment by ahdithebomb** [comment]
@drubgrubby 

**1. & 2.** All blockers need to be looked at during the meeting to discuss time constraints and possibly redelegate the issue depending on the deadline. 

 **3.** See this [explanation](https://github.com/hackforla/website/wiki/Instructions-for-adding-Status-Labels-to-issues), let us know if you have any other questions.

**Comment by tarang100** [comment]
There is a dependency on this issue as mentioned in #918. Need to check with Bonnie during the weekly PM Meeting about the next steps and if releasing the dependency is possible.

**Comment by tarang100** [comment]
Re-explain all the Status labels to the development team

**Comment by shaswa** [comment]
Please provide updates to:
- Progress
- Blockers
- Availability
- ETA 
- and [use appropriate labels](https://github.com/hackforla/website/wiki/Instructions-for-adding-Status-Labels-to-issues)
