### ISSUE TITLE
Update Project Profile:  The LA TDM Calculator

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1056]
### Overview
We are removing "(https://ladot.lacity.org/)" from The LA TDM Calculator. Refer #1053 

### Action Items
- [x] Remove the the linked URL from LA TDM Calculator
- [x] Adding a link to the links section
```
- name: Overview
    url: https://github.com/hackforla/product-management/blob/master/project-one-sheets/TDM-Calculator-Product-One-Sheet.pdf
```

### Resources/Instructions
- https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md
- ![image](https://user-images.githubusercontent.com/32349001/107981322-d6390680-6f8f-11eb-8a38-6e958025f400.png)

**Comment by csseu** [comment]
Hi, new member here.
- I edited and submitted as a pull request. Not sure if I was supposed to check off the boxes.
- Do we need to open similar issues for Railstats and Jobs for Hope and put them on the board? I'm not sure what the community culture here is regarding decisions like this, so I haven't done it, but would be happy to open those if desired.
