### ISSUE TITLE
connect the wins form to a google sheet

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1061]
### Dependency
Creating the wins form: #1060

### Overview
We want the new wins form to output its values to a google sheet so that site managers can review and approve them

### Action Items
- [ ] follow the tutorial below to create a google sheet that gets inputs from the new google sheet

### Resources/Instructions
[tutorial](https://medium.com/@dmccoy/how-to-submit-an-html-form-to-google-sheets-without-google-forms-b833952cc175)

**Comment by erikaBell** [comment]
@jbubar Is this still needed or outdated?

**Comment by erikaBell** [comment]
@jbubar Can I close this???
