### ISSUE TITLE
Align news items evenly in About Us page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1063]
### Overview
We need to align the news articles in the bottom of the new [About Us page ](https://www.hackforla.org/about-us )more evenly (similar to the Figma mockup) so that the page keeps its visual consistency 

### Action Items
- [ ] Review Figma file of About Us page (final design in green rectangle on the bottom)
- [ ] Make the website design more similar to the Figma- more evenly aligned if possible

### Resources/Instructions
[About Us page](https://www.hackforla.org/about-us)
[Figma (About Us file)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692)

<img width="791" alt="Screen Shot 2021-02-16 at 10 57 47 AM" src="https://user-images.githubusercontent.com/67400366/108150308-58592600-7089-11eb-8a7a-c4fe3320d645.png">

**Comment by evancchen** [comment]
![image](https://user-images.githubusercontent.com/62812734/112081001-2df30080-8b40-11eb-9a95-553c62ce90cf.png)
This is figma

![image](https://user-images.githubusercontent.com/62812734/112081031-3e0ae000-8b40-11eb-8c93-c97237114965.png)
This is from the hackforla site

I can't see the difference

**Comment by daniellex0** [comment]
Website version-

<img width="739" alt="Screen Shot 2021-03-23 at 1 26 20 AM" src="https://user-images.githubusercontent.com/67400366/112117203-54349280-8b78-11eb-9a52-5615cfc34007.png">

Figma version-

<img width="775" alt="Screen Shot 2021-03-23 at 1 28 03 AM" src="https://user-images.githubusercontent.com/67400366/112117219-5860b000-8b78-11eb-9dca-c9bb4b04aef0.png">

The logo images are not a priority so I can move that to another issue, but most importantly the text is not aligned- I know it may seem nit-picky, but once you see it you can't unsee! It looks messy..
