### ISSUE TITLE
Align platform items evenly in About Us page 

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1064]
### Overview
We need to align the colorful platform items on the second page card from the top, left column more evenly to keep visual consistency on the About Us page

### Action Items
- [ ] Review Figma file of About Us page (final design in green rectangle on the bottom)
- [ ] Make the website design more similar to the Figma- more evenly aligned if possible

### Resources/Instructions
[About Us page](https://www.hackforla.org/about-us)
[Figma (About Us file)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692)

<img width="350" alt="Screen Shot 2021-02-16 at 5 44 39 PM" src="https://user-images.githubusercontent.com/67400366/108144591-dbc14a00-707e-11eb-8978-a85e08c6a352.png">

**Comment by danyc23** [comment]
Progress: Still doing some fixes.
Blockers: Haven't find any blockers yet.
ETA:  3/2/2021.

**Comment by danyc23** [comment]
These are the changes made. attached a preview of the tablet and desktop views.

<details>
<summary>Tablet View</summary>
<img src="https://user-images.githubusercontent.com/42159475/110193780-dc7e0e00-7dea-11eb-86da-267ef211db33.png">
</details>

<details>
<summary>Desktop View</summary>
<img src ="https://user-images.githubusercontent.com/42159475/110193761-bc4e4f00-7dea-11eb-9bde-0aa43562b0d0.png">
</details>
