### ISSUE TITLE
Refactor the wins page code to be cleaner

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1066]
### Overview
I learned from akib about the html template element which can be used to significantly reduce the amount of code needed for the wins page

### Action Items
- [x] rewrite the makeCards function to populate a template rather than all the creating elements and appending children that is going on
- [x] make sure that it continues to work with the see more functionality, including the measuring of the div's height.

### Resources/Instructions
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template

**Comment by akibrhast** [comment]
## Update
1. Ensure See More button works correctly
2. Revers wins hero href for google forms

**Comment by jbubar** [comment]
progress: updated PR
