### ISSUE TITLE
Bug: github images do not show up on overlay

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1067]
### Overview
For the wins page the github images do not show up on overlay 
![Screen Shot 2021-02-16 at 5 59 49 PM](https://user-images.githubusercontent.com/53061723/108145729-c6e5b600-7080-11eb-973b-8950feeb0b9a.png)

### Action Items
- [ ] you know what to do

**Comment by danyc23** [comment]
Blockers: Still trying to figure out how to approach it.
Availability: three nights a week.
ETA: 03/18/2021
