### ISSUE TITLE
Refactor the wins page to get its data from the new _wins-data

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1070]
### dependency 
Create a new github action that will eventually replace the wins page github action: #1069
### Overview
Refactor the code to pull from the new wins data

### Action Items
- [ ] rewrite the code to pull from the new wins data
- [ ] clean up the code and delete lines that are not being used
- [ ] delete the old github action
- [ ] delete the old wins data

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

**Comment by erikaBell** [comment]
@jbubar @akibrhast should this be closed after what we did today?

**Comment by jbubar** [comment]
Not yet. But maybe it should be reworded

**Comment by akibrhast** [comment]
I think it should be closed,.

None of the action items in this issue is relevant anymore. Even the dependency isn't relevant anymore. 

Because of the aforementioned reasons this issue should be closed.
