### ISSUE TITLE
Refactor <span> elements on current projects dropdown menus to <label> elements

### ISSUE THREAD

**Issue by dmcneary** [hackforla/website#1071]
### Overview 
Currently, the dropdown menus on the "Current Projects" section of the homepage require a user to click directly on the checkbox. If each checkbox input element is wrapped in a label element, a user can also click on the text to select the checkbox.

### Details 
Here's a screenshot of the relevant code:

![image](https://user-images.githubusercontent.com/43227293/108152286-92c4c200-708d-11eb-9f43-27152568035a.png)

- [x] On line 159, a span element is created to describe the checkbox. This can be changed to a label element. May want to also change the variable name.
- [x] Line 163 can use the textContent node property rather than innerHTML
- [x] Line 193 should be changed if the variable name is changed.
- [ ] Line 192 should append to the new label element instead of the div element variable 'content.'

### Resources  
[Label element on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label)

> Associating a <label> with an <input> element offers some major advantages:
>  - The label text is not only visually associated with its corresponding text input; it is programmatically associated with it too. This means that, for example, a screen reader will read out the label when the user is focused on the form input, making it easier for an assistive technology user to understand what data should be entered.
> - You can click the associated label to focus/activate the input, as well as the input itself. This increased hit area provides an advantage to anyone trying to activate the input, including those using a touch-screen device.

**Comment by averdin2** [comment]
- I changed the span to be a label.
- I also had to make some other changes like removing id from the label and giving it to the checkbox instead.
- Below is a gif with the working label so users can click label by clicking on text and checkbox. Also implemented with the filter tags.

![label_click](https://user-images.githubusercontent.com/10714770/114460095-2e5a4680-9b96-11eb-92f0-cea7b8dc7ab9.gif)
