### ISSUE TITLE
New HfLA PM Meeting time coordination 

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#1074]
### Overview
The weekly meeting needs to be adjusted so that a new time can be finalized among all necessary stakeholders. 

### Action Items
- [x] @tarang100, @IAgbaje, and Swaroop need to coordinate a time that works best for all 3 
- [x] Inform @ExperimentsInHonesty which time slots work best and have her choose one 
- [ ] Finalize a time slot and send an invite 

### Resources/Instructions
~~[Lettuce Meet](https://lettucemeet.com/)~~
[When2Meet](https://www.when2meet.com/?11160695-KGcXa)

**Comment by tarang100** [comment]
The Lettuce Meet for the weekly HfLA Website PM Meeting has been set up and the timings available have been shared by all 3 PMs. Link to the [Lettuce Meet](https://lettucemeet.com/l/AEvA6)

The only common time slot available for all 3 PMs is Wednesday, 10:30 AM - 12:30 PM PST. Need to check Bonnie's availability for this slot

**Comment by tarang100** [comment]
The following issue needs to be discussed during the upcoming weekly PM Meeting
https://github.com/hackforla/product-management/issues/67

**Comment by shaswa** [comment]
@ExperimentsInHonesty Due to technical difficulties with Lettuce Meet, we made a new poll in [When2Meet](https://www.when2meet.com/?11160695-KGcXa). It currently has the availability for me, Taranag, and Ibraheem.

**Comment by tarang100** [comment]
The new HfLA Website PM meeting time (Wednesday, 10:30 am PST) has been decided and confirmed with Bonnie. Calendar invite shared with Bonnie, Swaroop, and Femi.
