### ISSUE TITLE
Linkedin Letter for API Request 

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#1076]
### Overview
There needs to be a letter written so that LinkedIn can give us access to their API to be able to scrap photos directly from the website. 

### Action Items
- [x] Need to revise/complete the Existing Draft (refer to the Existing Draft)
- [ ] Get stats
  - [ ] Create spreadsheet
  - [ ] Review every linked in profile, populating spreadsheet with findings
  - [ ] Present findings
- [ ] Define strategy
- [ ] Revise Draft
- [ ] Send to LinkedIn

### Resources/Instructions
[Existing Draft](https://docs.google.com/document/d/1pik6q3m5nHJTUefhbhK48hfwSjffz4R9haEF-GtSMo4/edit)
[Original Issue](https://github.com/hackforla/website/issues/1029)
[LinkedIn Profile list](https://docs.google.com/spreadsheets/d/1dvdB6uZLmogcnCzCe54ZASuAecxwrm6SECG2g8Fl-DE/edit) to

**Comment by matthewlee626** [comment]
Revised a letter draft. Seeking comments at Sunday meeting.

**Comment by tarang100** [comment]
@matthewlee626 
Since this issue needs a review we have moved it to the Review column. In future if you have a draft or something similar please move it to the Review Column

**Comment by akibrhast** [comment]
@tarang100 Has this been reviewed yet? What was the decision on the review?

**Comment by qiqicodes** [comment]
We will review at the next meeting on Wednesday, March 24.

**Comment by ExperimentsInHonesty** [comment]
@qiqicodes 
Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by Sihemgourou** [comment]
@ExperimentsInHonesty could you please review the draft so that we can move on with this issue ?

**Comment by Sihemgourou** [comment]
Waiting for the wins page to be ready (mostly badges++)

**Comment by Sihemgourou** [comment]
I have to review the draft to validate it with Bonnie

**Comment by sobe-an** [comment]
Progress: Still reviewing and updating previous drafts.
Blockers: None
Availability: Will continue working on it today
ETA: I will clean up the new draft and notify the team by tomorrow 28/08/2021

**Comment by sobe-an** [comment]
@ExperimentsInHonesty Please see the new draft for review on the last page of the draft document.

**Comment by ExperimentsInHonesty** [comment]
awesome edits by Sobechukwu next steps, bonnie formatting and final edits, then assign shelton for review and making contact.

**Comment by ExperimentsInHonesty** [comment]
Created a [new spreadsheet](https://docs.google.com/spreadsheets/d/1dvdB6uZLmogcnCzCe54ZASuAecxwrm6SECG2g8Fl-DE/edit) to track 
who has a job after hfla
what the linkedin status of people who are on the wins is (do they have hfla, do they have new job listed)

**Comment by abdiaz2018** [comment]
ETA: end of day of 31st
availability: 6 hours

**Comment by EllenKellyb** [comment]
This task sounds interesting, is it still open to be worked on? I realize this is a business analyst role, but still interested.

**Comment by mademarc** [comment]
Progress: Gonna work on this issue and have it done by end of the week.  
Blockers: no blockers yet   
Availability: 3/23/2023 
ETA: 3/24/2023

**Comment by mademarc** [comment]
Availability: 3/29/2023
ETA: 3/31/2023

**Comment by EllenKellyb** [comment]
How do you get access to the draft on Google docs?

**Comment by ExperimentsInHonesty** [comment]
I am closing this issue as unplanned.  We will not be able to display people's LinkedIn profile pictures, the [LinkedIn API Terms of Service](https://www.linkedin.com/legal/l/api-terms-of-use) disallows it. So we need to revise the form to reflect that.  A new issue will get created.
