### ISSUE TITLE
Update project card: VRMS

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#1077]
### Overview
We need to update the VRMS project card so it reflects the changes in their project.  This will enable new and perspective team members to find the correct people on the leadership to connect with.

### Action Items
- [x] Add the following information to the project markdown file:
Leadership
Name: Khushboo Shah
Role: Product Manager
Team: VRMS
Slack ID: U01EW21842X
GitHub handle: khushbooshah-PM
- [x] review it locally and take a screen shot
- [x] add the screen shot to this issue in a comment
- [x] Update this issue asking for UAT by @ messaging the people assigned to it and proving a link to this issue's comment with your screenshot (clicking on the three dots above your comment will give you a link directly to the comment).  https://github.com/hackforla/product-management/issues/91

### Resources/Instructions
[project.md file](https://github.com/hackforla/website/blob/gh-pages/_projects/vrms.md)
location: _projects/vrms.md
Project Homepage: https://www.hackforla.org/projects/vrms

**Comment by averdin2** [comment]
Here are screenshots of the changes I made to the card:
![image](https://user-images.githubusercontent.com/10714770/112679906-f6c76c80-8e29-11eb-9227-82ae27e6d1e1.png)
![image](https://user-images.githubusercontent.com/10714770/112679993-1068b400-8e2a-11eb-90cd-f5813e7568a8.png)
Here is a screenshot of the change on my local site:
![image](https://user-images.githubusercontent.com/10714770/112687809-419ab180-8e35-11eb-9aec-9247f2289896.png)

**Comment by averdin2** [comment]
Here is a screenshot of the change on my local site:
![image](https://user-images.githubusercontent.com/10714770/112687809-419ab180-8e35-11eb-9aec-9247f2289896.png)
