### ISSUE TITLE
Create onboarding slideshow: Bonnie's onboarding presentation

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1079]
### Overview
We need to create a visually pleasing and organized onboarding slideshow. Slide deck should include HackforLA branding and main onboarding points, and will accompany Bonnie's zoom onboarding presentation, so that attendees can view information as they hear about it.

### Action Items
- [x] Review Bonnie's presentation notes (below)
- [x] Create detailed onboarding slideshow based on Bonnie's notes- for user self-onboarding option on [Getting Started page
](https://www.hackforla.org/getting-started)
- [x] Create simplified onboarding slideshow to accompany Bonnie's zoom presentation
- [x] Have Bonnie review slideshows
    - [x]  Make any necessary edits based on feedback
- [x] Get Bonnie's final approval

### Resources/Instructions
Onboarding Slideshow- https://docs.google.com/presentation/d/127UC7q5JOgc5oPev4bbEdydchany-rVBkPRn4w6DMek/edit

Slideshow should be based on Bonnie's onboarding presentation notes - https://docs.google.com/document/d/1k0HYLcEhqAWLliokM_FRfva-vRjz0uEgFRCeaNFZb1k/edit

**Comment by ashleylin1** [comment]
https://docs.google.com/presentation/d/1slYvN1bY8IhpwteMgQ7ZFYcKzVkUpzf7SBTuk10AOWk/edit?usp=sharing
Progress: 
- Added slides explaining Code for America organization, 
- separated slides for tools, technologies and framework
- added links and logos to the technologies
- still need to add community of practice readme links such as https://github.com/hackforla/UI-UX/blob/main/README.md 

Blockers: need to know what text to put for the Communities of Practice slide
Availability: Friday, Saturday, Sunday
ETA: 1 week

**Comment by daniellex0** [comment]
@ashleylin1 Text for Communities of Practice (slide #15) https://docs.google.com/presentation/d/12YxUxDE3yCSws4k6XxRjBqKN36K8QHGuH--QYiqs6rM/edit#slide=id.gc5eba6fabf_0_535

**Comment by ashleylin1** [comment]
Blockers: 
- need Bonnie's edited slide deck that she used for onboarding
- need folder of images to use on Google Drive

Availability: Friday, Saturday, Sunday
ETA: 1 week

**Comment by qiqicodes** [comment]
**Screenshots of Slack User Flow for Getting Started Info:**

1. Slack Welcome Page:
![HackforLA Slack - Welcome Page](https://user-images.githubusercontent.com/68657634/113520363-6c78ba00-9547-11eb-889f-e9e34a524f59.png)

2. Slack GreetBot:
![HackforLA Slack GreetBot Page Info Available for Two Weeks](https://user-images.githubusercontent.com/68657634/113520356-6387e880-9547-11eb-9765-6510d0a64722.png)

3. Accessing Slack GreetBot:
![HackforLA Slack Access Info via GreetBot](https://user-images.githubusercontent.com/68657634/113520370-70a4d780-9547-11eb-93d5-9a309795f53c.png)

**Comment by ashleylin1** [comment]
Progress: for the "What is HackforLA" slide, I...
- reviewed both slides with Bonnie and Danielle
- got feedback and changed the background so the logo fits within view
- reuploaded the logo and colors for the platform slide and its subsequent slides
- added icons to the communities of practice slide
- changed text-align and logo for all project slides
- changed color of dividing lines for all project slides to be lighter

Blockers: 
- need **editing permission** to Bonnie's onboarding slide deck to edit it
https://docs.google.com/presentation/d/127UC7q5JOgc5oPev4bbEdydchany-rVBkPRn4w6DMek/edit#slide=id.gc50dc3b32b_0_116
- need feedback on Olivia's "What is HackforLA" slide

Availability: Friday, Saturday, Sunday
ETA: 1 week

**Comment by daniellex0** [comment]
Sorry, I shouldn't have deleted that entire comment- just trying to separate this issue from [a new different issue for the "What is hack for LA" slide deck](https://github.com/hackforla/website/issues/1379)-

This was posted here previously by @ashleylin1 :

> Blockers: need editing permission to Bonnie's onboarding slide deck to edit it

> https://docs.google.com/presentation/d/127UC7q5JOgc5oPev4bbEdydchany-rVBkPRn4w6DMek/edit#slide=id.gc50dc3b32b_0_116

**Comment by daniellex0** [comment]
Notes from meeting with Bonnie:
- [x] Flip agenda items # 2 and # 3
- [x] Add a new slide under  "What technologies do we use?" titled "Resources for Requests and Concerns" that includes:
   - [x] # new-joiner-channel : introduce yourself, ask for help (how to join Community of Practice, etc.)
   - [x] # admin : reach out to leadership (types of issues: Code of Conduct, Github access and slack @ channel posting requests, etc
- [x] Add a new slide under that^ titled "Org Chart" with the triangle - Admin on top, Communities of Practice & Projects below
- [x] On Communities of Practice slide, add in the speaker notes this link to the CoPs Github page: https://github.com/hackforla/communities-of-practice
- [x] Add a slide right after the Communities of Practice slide:
   - [x] Title: Join your Community of Practice - maybe text that says "Follow the steps in your Community of Practice's Github Readme to join" (hopefully that makes sense to new people..)
- [x] Separate the "Next Steps" slide into two separate slides:
   - [x] title: Next Steps - with the text from the "Everyone" section (maybe as numbered bulletpoints), plus the slack screenshot 
   - [x] title: New Developers - with the text from the "New Developers" section

Community of Practice Readme screenshot:
![screencapture-github-hackforla-UI-UX-blob-main-README-md-2021-04-11-19_44_04](https://user-images.githubusercontent.com/67400366/114333972-72017180-9afe-11eb-835d-8f0d6fa31777.png)

**Comment by daniellex0** [comment]
Progress: Made changes to slideshow based on previous onboarding. 
Next steps: Interviewing users at onboarding for feedback about updated slideshow.
Blocks: None

**Comment by ashleylin1** [comment]
Progress: Made changes to the slideshow based on feedback from Bonnie and Danielle
Next steps: same as what Danielle reiterated above about interviewing users
Blockers: none
Availability: after 5/14
