### ISSUE TITLE
Wrap guide cards to the left in Toolkit page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1081]
### Overview
We need the bottom row of guide cards in the Toolkit page to be wrapped to the left, to bring it back to how it used to look before this page was standardized, and to conform with design standards.

### Action Items
- [x] Try to find a way to wrap the bottom row of guide cards to the left, instead of center, on the Toolkit page

### Resources/Instructions
[Toolkit page](https://www.hackforla.org/toolkit)

Bad: 

<img width="450" alt="Screen Shot 2021-02-21 at 9 34 20 AM" src="https://user-images.githubusercontent.com/67400366/108633325-88f1e480-7428-11eb-9f00-93c791907e9c.png">

Good:

<img width="450" alt="Screen Shot 2021-02-21 at 9 36 38 AM" src="https://user-images.githubusercontent.com/67400366/108633328-8db69880-7428-11eb-9a2b-d78df4863737.png">

**Comment by evancchen** [comment]
![image](https://user-images.githubusercontent.com/62812734/109079815-565c1c00-76b4-11eb-810b-e7b5bd1e5962.png)
Is this okay?

**Comment by daniellex0** [comment]
@evancchen yeah, that looks great!

**Comment by pawan92** [comment]
@evancchen Hey could we get an update on this and a status label?
progress:
blocker:
Availability:
ETA:

**Comment by evancchen** [comment]
Progress: Done
Blockers: none
