### ISSUE TITLE
Create Formatted Guide Pages Parse with Markdown

### ISSUE THREAD

**Issue by abenipa3** [hackforla/website#1086]
### Dependency 
After having a feasibility plan for how to create Markdown for Desktop (#1085) and Mobile (#1515), implement the formatted guide pages into Hack for LA's repo.

### Action Items

- [ ]  Implement the formatted guide pages into Hack for LA's repo.
- [ ] Create documentation on Guide Pages.

### Resources/Instructions
[Example of Markdown File of Role](https://github.com/hackforla/civic-opportunity/blob/master/roles-1/data-scientist.md)
Check the _layouts folder
https://jekyllrb.com/docs/step-by-step/04-layouts/
https://talk.jekyllrb.com/t/rendering-markdown-inside-an-html-include/4186/2
[Original issue for the guide](https://github.com/hackforla/website/issues/794)

**Comment by ExperimentsInHonesty** [comment]
@alyssabenipayo It looks like the issue that this was dependent on is now resolved.  Can we move this out of the icebox and into prioritized backlog or does it need info added?

**Comment by abenipa3** [comment]
@ExperimentsInHonesty ~More info needs to be added. We have one more issue that's dependent on this one (Mobile Version #1515).~ Update: This is actually a duplicate issue for #1515. We can close this.

~I've just edited the description for this issue.~ Thanks for catching this, Bonnie!
