### ISSUE TITLE
About-Us Page: Clicking on dropdowns in mobile view should change the hash-mark

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1090]
### Overview
Clicking on dropdowns in mobile view should change the hash-mark. Ensure that clicking on the dropdowns and the linked navigation changes the history state to respect the new hash-marks

### Action Items
 - [x] Clicking on dropdowns in mobile view should change the hash-mark.
 - [x] Clicking on currently only changes the hyperlink, It should also change the history state.

### Resources/Instructions
- Checkout how history state is replaces in the projects page and in the wins page for help in implementing this.

**Comment by drubgrubby** [comment]
@akibrhast - Please provide examples of what's not working and what it's user acceptance criteria should be.

**Comment by akibrhast** [comment]
@drubgrubby Notice how in the video when I click on the drop downs the hash tag in the URL does not change, in the manner it changes when you click on the side navigation which is available in desktop mode. This impedes direct linking to a particular section of the page by copying the url when in mobile.

![issue_1090](https://user-images.githubusercontent.com/32349001/109335292-d65ac100-782f-11eb-913c-1b75fb48e654.gif)

**Comment by akibrhast** [comment]
@drubgrubby Notice how in the video when I click on the drop downs the hash tag in the URL does not change, in the manner it changes when you click on the side navigation which is available in desktop mode. This impedes direct linking to a particular section of the page by copying the url when in mobile.

![issue_1090](https://user-images.githubusercontent.com/32349001/109336021-d1e2d800-7830-11eb-90b6-74fe1e46fa40.gif)
