### ISSUE TITLE
Update Project Profile: Jobs for Hope

### ISSUE THREAD

**Issue by csseu** [hackforla/website#1103]
Overview
We are removing "http://homeless.lacounty.gov/" from Jobs for Hope. Refer to #1053

Project card
https://github.com/hackforla/website/blob/gh-pages/_projects/jobs-for-hope.md

Action Items
- [ ]  Remove "; http://homeless.lacounty.gov/" from the Partner field

**Comment by ruqpyL2** [comment]
![HI](https://user-images.githubusercontent.com/23020878/108955894-ba82cf80-7623-11eb-905b-1118c3d4a9e5.png)

**Comment by csseu** [comment]
![HI](https://user-images.githubusercontent.com/23020878/108956028-f0c04f00-7623-11eb-85bd-0b46f26c1a21.png)
