### ISSUE TITLE
Style the new wins form to match Figma specifications

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1104]
### Dependency
- [x] Requires the completion of #1060 

### Overview
The new wins form needs to be styled to match figma specifications

### Action Items
- [ ] Style the form to match figma specifications

### Resources/Instructions
- [figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0)

- The new wins form is defined under wins/wins-share-form.html

- For the development need of styling the new wins form it can be accessed by :
   - 1st commenting out    
    ```html
    <a href='https://docs.google.com/forms/d/e/1FAIpQLSdF0MgS-M_Soi77qTp-MNfxMGqq85yqsHwvfHDngHAMyDQ8uQ/viewform'><button class='btn btn-primary btn-xl btn--wins'>Share your wins</button></a>
    ```
    - 2nd Uncommenting out
    ```html
    <a href='/share-your-wins'><button class='btn btn-primary btn-xl btn--wins'>Share your wins</button></a>
   ```
    and then navigating to `localhost:4000/share-your-wins` or clicking on the "Share your wins" button

**Comment by jbubar** [comment]
progress: did some styling, made some design decisions
blockers: some design decisions
ETA: by tuesday I will have another draft pr
availability: limited, in the evenings.

**Comment by jbubar** [comment]
https://github.com/hackforla/website/issues/1203#issuecomment-803635491

**Comment by jbubar** [comment]
Changed the draft pr to review. thanks Sihem for bringing this to my attention. sorry folks
#1314

**Comment by Sihemgourou** [comment]
Hey @jbubar , thanks for the update ! Could your link the PR to the issue ? 
Btw, are we going to use the Css form and leave the gform ?

**Comment by Sihemgourou** [comment]
Asked @jbubar to remove himself from this issue if he is not working on it

**Comment by jbubar** [comment]
This issue has been completed sorry that it was open
