### ISSUE TITLE
Dropdowns not centered

### ISSUE THREAD

**Issue by Treidexy** [hackforla/website#1107]
### Overview
On the 'Events' page, the dropdowns for "Meetup Events" & "Online Project Team Meetings" are not centered when viewport width is less then 768px.

### Action Items
a) Ask UI team for best way to solve this
or
b) If viewport width is less than 768px, center the dropdown menu's.

### Resources/Instructions

![image](https://user-images.githubusercontent.com/29633838/109079930-8d323200-76b4-11eb-9a2d-9a36099ccab3.png)

**Comment by jbubar** [comment]
@daniellex0 is there already an issue addressing this?

**Comment by daniellex0** [comment]
@jbubar I think @akibrhast mentioned there might be? Otherwise we should definitely keep this one

(I haven't made an issue for this, but Akib might have)

**Comment by akibrhast** [comment]
@jbubar @daniellex0  . I have not made an issue about it either.
So i guess this is the issue addressing this 😈
