### ISSUE TITLE
Standardize Events Page - Update tab title

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1109]
### Overview
Browser tab title is not up to date

### Action Items
- [x] If possible, please change the name of this page on the browser tab from Hack Nights to Events - Hack for LA

### Resources/Instructions
![image](https://user-images.githubusercontent.com/32349001/109089696-a9979400-76df-11eb-9103-510aeb047894.png)
#1041

**Comment by pawan92** [comment]
@akibrhast Could we get an update on this please and a status label?
Progress:
Blocker:
Availability:
ETA:

**Comment by akibrhast** [comment]
## Progress
Complete

## Blockers
None

## Availability
3 hours a week

## ETA
Done

@pawan92 My bad mate, I was under the impression that if a pull request is attached to an issue that is considered to be the update? Or do we still have to update after doing the pull request?
