### ISSUE TITLE
Improve Performance on images

### ISSUE THREAD

**Issue by abregorivas** [hackforla/website#111]
A lighthouse audit test recommended converting images to a next gen image and or to optimize images. We need to review our png and jpg images and improve the performance on our images.

Follow the guide at the following site. 
https://developers.google.com/web/tools/lighthouse/audits/webp
https://developers.google.com/web/tools/lighthouse/audits/optimize-images

Need the following:
- An explanation of the process taken to convert existing images to new format and the savings in image size. 
- The tool that was used
- The new images should be uploaded and the old ones should be removed.

**Comment by stu562** [comment]
There is a command line tool called cwebp
> cwebp is the most popular command line tool for converting images to the WebP format. Once installed, we can use it to convert images by passing in, among other options, a quality, input file, and output file.

> 

WebP | PNG | JPG | GIF
-- | -- | -- | --
Lossy compression | ✓ | ✓ | ✓ | ✗
Lossless compression | ✓ | ✓ | ✓ | ✓
Transparency | ✓ | ✓ | ✗ | ✓
Animation | ✓ | ✗ | ✗ | ✓



Around 25-30% savings
>  it was found that WebP lossy images were on average 30% smaller than JPGs and WebP lossless images were on average 25% smaller than PNG.

https://bitsofco.de/why-and-how-to-use-webp-images-today/

**Comment by seanholahan** [comment]
we can use Webp with the new html5 <picture> element so that there is a fallback for older/incompatible browsers that either don't support Webp, or the picture element (only one image is loaded). However when we are using images with the CSS Background Image, we would need to use JS to check for browser compatibility. If we specify multiple background images they will all be loaded. I know we are trying steer away from from using JS, so we could possibly replace the background images with picture elements, but I am not sure if that is best practice.

```
<picture class="project-tmb-img" > 
           <source srcset={{item.webp_image|absolute_url}}   type="image/webp">
           <source srcset={{item.image|absolute_url}}  type="image/jpeg">
           <img src={{item.image|absolute_url}} class="project-tmb-img" alt={{item.alt}}/>
</picture> 
```

**Comment by ExperimentsInHonesty** [comment]
This issue requires review by @thekaveman @ddrosario @ExperimentsInHonesty to determine next steps

**Comment by ExperimentsInHonesty** [comment]
@stu562 @seanholahan - Please update this issue with your latest findings.

**Comment by seanholahan** [comment]
So I ran audits on the site with next-gen(webp) formatted images and without,
using the webp results in a slightly lower performance score (by one to two points), with an increase of about .1s for most performance metrics. 

Seeing that using the <picture> element/webp results in a slightly worse score, I would not recommend going forward the <picture> element/webp image format. Yes, it does get rid of an optimization "opportunity" suggestion, but there is no improvement in the performance scoring.

Here are the performance details of both the audits ran. I audited both version while being hosted on my personal gh-pages deployment in hopes of getting a consistent evaluation. You can check out the webp version currently being hosted on my gh-pages website: https://seanholahan.github.io/HackForLAWebsite/

**With next Gen Images:** 
Performance score: 71
First Contentful Paint: 4.0s 
speed to index 4.0 s 
Time to Interactive: 5.2 s
First Meaningful paint: 4.0 s 
First CPU Idle: 4.2
Estimated Input Latency: 20ms

Opportunities

Eliminate render-blocking resources: 3.1s
minify JS: 1.35
pre connect to required origins .36s
defer offscreen images: .3
properly size images: .15

**WITHOUT next Gen Images:** 

Performance score: 72
First Contentful Paint: 3.9 s 
speed index 3.9 s 
Time to Interactive: 5.2 s
First Meaningful paint: 3.9 s 
First CPU Idle: 4.5
Estimated Input Latency: 10ms

Opportunities

Serve images in next-gen formats: 4.2s
Eliminate render-blocking resources: 2.95s
minify JS: 1.2
efficiently encode images: .75s
properly resize images: .15s

**Comment by ExperimentsInHonesty** [comment]
Closing this issue because suggested improvements from lighthouse will not result in increased performance.
