### ISSUE TITLE
Standardize Events Page - Update header section

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1110]
### Overview
The header section of the Events page needs to be edited to match site-wide standardization

### Action Items
- [x]  Follow the instructions for standardizing the Events page header in the [Events page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94) (bottom right, in orange rectangle section)

### Resources/Instructions
[Events page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94) (instructions for this issue in bottom right, in orange rectangle section)

<img width="400" alt="Screen Shot 2021-02-26 at 1 44 27 AM" src="https://user-images.githubusercontent.com/67400366/109283995-3c195f80-77d4-11eb-9345-c190ad186a5f.png">

#1041

**Comment by kevinreber** [comment]
### Progress
Just need to add some styles
### Blocker
None
### Availability
Tuesday Night
### ETA
Before Next Sunday's meeting

**Comment by kevinreber** [comment]
Progress
Added all styling from the instructions, but my results aren't matching the Figma mock up.

<details>

<summary>Current Progress</summary>

![image](https://user-images.githubusercontent.com/42260999/111061173-db865580-8456-11eb-9778-ee079f3936bb.png)

</details>

<details>

<summary>Mock up</summary>

![image](https://user-images.githubusercontent.com/42260999/111061222-17211f80-8457-11eb-8af6-49178f167903.png)


</details>

Blocker
Revisit CSS with the designers @daniellex0 

Availability
Monday night, Wednesday and Friday

ETA
End of next week
