### ISSUE TITLE
Standardize Events Page - Update Horizontal Cards and Mobile SCSS

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1115]
### Overview
The horizontal cards and some of the mobile scss in the Events page needs to be standardized to match other pages on the site

### Action Items
- [ ] Match horizontal cards and mobile scss of Events page with specs listed on the Figma file (in pink rectangle)

### Resources/Instructions
[Figma Events page file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94) (follow the instructions in the pink rectangle in bottom right)
[Events page](https://www.hackforla.org/events)

The instructions look like this:
<img width="400" alt="Screen Shot 2021-02-26 at 10 40 47 AM" src="https://user-images.githubusercontent.com/67400366/109341473-56c4f600-781f-11eb-85c6-2b8aa3ccf70b.png">

#1041

**Comment by akibrhast** [comment]
There was somework done as an attempt to address this issue in the PR linked. For anyone picking this up, you should use the details on the linked PR as resources.

**Comment by sena-ji** [comment]
Took a look at the PR resources! Super helpful notes and instructions. Made some of the changes but will not make a full PR until all changes are made.

So far completed: 
- Editing card font size, weight, and margin
- Added border radius and adjusted border radius

Will work on next time:
- How to make the 12px font on mobile to 1 rem
(Hopefully will get it done by Tuesday's meeting)

**Comment by qiqicodes** [comment]
@sena-ji Can you let us know your progress in regards to this issue? Thank you =]

Progress: 

Blockers: 

Availability: 

ETA:

**Comment by sena-ji** [comment]
@qiqicodes 
Progress: Same as last time. Need to get this part done: How to make the 12px font on mobile to 1 rem.
Blockers: Catching up with some work for school. Haven't been able to make progress on this issue.
Availability: Will finish up this issue by Wednesday 5/5 when I turn in my last school project.

**Comment by sena-ji** [comment]
- Finished editing card heading font size and font weight.
- Added border-radius to mini project cards
- Added forcer-radius to only top of mini project cards photos to match cards
- Made the 12px font in mobile version to 16px
- Adjusted the border radius for column-card-lg--events 
 **This change was already made previously**
