### ISSUE TITLE
Fix git documentation in contributing

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1118]
### Overview
Many people have been adding unnecessary files to their pull requests, @cnk recommended to change the wording on the [CONTRIBUTING.md file](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#step-6-work-on-an-issue-using-git)

In stead of suggesting for the contributors to use `git add .`, we should encourage them to add each file that they have changed, i.e. `git add wins.html`

### Action Items
- [ ] draft a revision to the CONTRIBUTING.md file
- [ ] get approval from the dev team
- [ ] make the changes 

### Resources/Instructions
- [CONTRIBUTING.md file](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#step-6-work-on-an-issue-using-git)
- [git add documentation](https://git-scm.com/docs/git-add)
- [git status documentation](https://git-scm.com/docs/git-status) ... I imagine that you will use this command in the rewrite :))

**Comment by drubgrubby** [comment]
@jbubar - What do you think about adding some text about how to remove something from staging after running git status if there's a file you don't want in your commit?

**Comment by thatguyish** [comment]
Please do not close pull request until @martham0 has made necessary changes.
