### ISSUE TITLE
Update Project Profile: LA TDM Calculator

### ISSUE THREAD

**Issue by VJ1285** [hackforla/website#1119]
### Overview
As a product manager of LA TDM Calculator, I want my project's details (title & one-sheet) to be up to date on the HackforLA website

### Project card
Url of the project Card: https://www.hackforla.org/projects/tdm-calculator

### Action Items

- [x] Team Leadership

   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title - Need to remove "The"
      - [ ] description - Need to update the one-page
      - [x] image
      - [x] leadership
      - [x] links
         - [x] Github
         - [x] Slack
         - [ ] Test Site
         - [ ] Demo Site
         - [ ] Site
      - [x] looking
      - [x] technologies
      - [x] location
      - [x] partner
      - [x] tools
      - [x] status

**Comment by ExperimentsInHonesty** [comment]
@VJ1285 There are other people on your team still not showing up on the leadership. What about Anam?  etc.

**Comment by ExperimentsInHonesty** [comment]
We need to add Site link to govcalc.org

**Comment by VJ1285** [comment]
@ExperimentsInHonesty - Please add the following person to the Project Leadership page
Name: Anam Shaikh
Role: UX Research Program Designer
Github handle: anamsha
Please also add her to the contributors as well

**Comment by VJ1285** [comment]
@ExperimentsInHonesty  - We need to add the following people to the contributors
Sanjana (Github handle: sanjana-ajit)
Jennifer (Github Handle: jchoum)
