### ISSUE TITLE
Standardize Events page: add section container without restricting banner

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1125]
### Overview
We want to add a section container (class `.content-section`) to the Events page body to keep this page consistent with other pages on the HfLA website.

This container ensures that the page has the standard 16px margin in mobile view. However, it adds the margin to the yellow covid warning banner as well, and we want that component to stay full-screen width if possible.

### Action Items
- [x] To stay consistent with other pages, add an additional class to the section tag that currently has class `.events-page`, and name it `.content-section` (standard scss is already attached to this class)
- [x] Figure out a way to keep the yellow covid alert banner full-screen width despite the new section container
   - [x] Research potential solutions- [this CSS tricks article](https://css-tricks.com/full-width-containers-limited-width-parents/) (although it looks a bit overly complicated), etc
   - [x] If there is no simple solution / it's overly complicated, remove the .content-section container and notify @daniellex0 

### Resources/Instructions
[Events page](https://www.hackforla.org/events)

This is how the banner looks with the `.content-section` class, without any edits (it should instead be full-width, without the purple margins on the sides):

<img width="319" alt="Screen Shot 2021-02-25 at 8 58 50 PM" src="https://user-images.githubusercontent.com/67400366/109344881-321f4d00-7824-11eb-8b4a-97bafa42b6f6.png">

**Comment by evancchen** [comment]
![image](https://user-images.githubusercontent.com/62812734/111714042-05040000-880e-11eb-89bd-c4acac57f684.png)
Is this ok?

**Comment by evancchen** [comment]
![image](https://user-images.githubusercontent.com/62812734/111714151-4ac0c880-880e-11eb-99c7-108b8125e1ef.png)
This is how it used to look

**Comment by daniellex0** [comment]
@evancchen Hi Evan, the yellow looks like it goes all the way to the edges of the screen, so that's good. The only issues are that the pink arrow and icon are a little too pushed up to the edges, the paragraph text is a little too crowded in the middle, and it looks like there is white area around the palm tree photo for some reason. 

It should look more like it looks on the site right now, so like this:

<img width="369" alt="Screen Shot 2021-03-21 at 2 35 02 AM" src="https://user-images.githubusercontent.com/67400366/111900235-a0ec6200-89ee-11eb-8ceb-b2cac45368d8.png">

I'm sorry, I know this issue is kind of a pain and won't really make a difference to the way the page looks- it's just for standardizing the CSS on all of the pages.

 If it's overly complicated, we could just leave out the .content-section class from this page for now and leave this issue in the ice box to be honest. 

So feel free to skip out on this issue and choose another one if you prefer!
