### ISSUE TITLE
Fix bug in Events page: collapsible column cards in desktop view

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1127]
### Overview
We need to remove the bug that is causing the Events page column cards to collapse when the top of them is clicked in desktop view (this should only be happening in mobile view), so that users don't accidentally collapse these cards on desktop if they click around.

### Action Items
- [x] Determine what is causing the Events page column cards to collapse in desktop view when the top of them is clicked
- [x] Implement fix for this bug

### Resources/Instructions
[Events page](https://www.hackforla.org/events)
For reference: the [About Us page](https://www.hackforla.org/about-us) also has collapsible cards in mobile, but that behavior doesn't transfer over to desktop

When the top of the column card is clicked on desktop view, this black arrow icon shows up to the right of the column card title:

<img width="400" alt="Screen Shot 2021-02-26 at 11 42 05 AM" src="https://user-images.githubusercontent.com/67400366/109348559-8973ec00-7829-11eb-9c6a-028b2e7a1cf1.png">

Then when it is clicked again, the column card collapses:

<img width="400" alt="Screen Shot 2021-02-26 at 11 42 13 AM" src="https://user-images.githubusercontent.com/67400366/109348573-8d077300-7829-11eb-9c5c-a264b7dc552d.png">

**Comment by akibrhast** [comment]
@daniellex0  This issue can be closed. It has been addressed in pull request #1147 which fixes #1106 . The current live site does not have the issue mentioned in the overview.
