### ISSUE TITLE
Set up Oauth for wins data google sheet

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1130]
### Overview
The wins data is currently in a spreadsheet that is visible to anyone with the link. Bonnie pointed out, that this is not ideal. In order to make this work we have to set up Oath. 

### Action Items
- [x] set up OAuth with through the developer console
- [x] Change sharing settings to restricted to test it locally 
- [x] change share settings back
- [x] change share settings to restricted after this is merged

### Resources/Instructions
[sheet](https://docs.google.com/spreadsheets/d/1tj6eQlVLFgmskoXouVt87POxYVwR1yWT2vOSQEPyDtg/edit#gid=1106372497)
[Oauth documentation from google](https://developers.google.com/identity/protocols/oauth2)
[Helpful article about connecting a team roster](https://betterprogramming.pub/make-a-team-roster-with-node-react-and-google-sheets-305b9f9ebbb1)
https://github.com/google/google-api-javascript-client/blob/master/docs/auth.md

**Comment by jbubar** [comment]
Currently setting up Oauth. On the second step of the google guideline, and I am trying to learn how it works along the way.
I will continue working on this tomorrow

**Comment by jbubar** [comment]
i am anticipating significant progress on this next week.
progress: found some great resources, with the help of akib and bonnie
blocker: this is new to me
availability: I will be a bit more available next week
ETA: 2 weeks

**Comment by jbubar** [comment]
Made some progress. Put a few hours into this test repo.. Looks promising.
I think I should have this done before next weeks meeting

**Comment by jbubar** [comment]
thanks @akibrhast for your help, and for taking this over. 

- [Tutorial I've been using](https://betterprogramming.pub/make-a-team-roster-with-node-react-and-google-sheets-305b9f9ebbb1)
- [working repo after following tutorial](https://github.com/jbubar/wins-backend-test)
- [Attempt to integrate with gh actions](https://github.com/jbubar/testGSheetRepo)

**Comment by akibrhast** [comment]
## Progress
Work in Progress

## Blockers
Awaiting closure on 
- https://github.com/hackforla/website/pull/1267
- https://github.com/hackforla/website/pull/1269

## Availability
Here and There

## ETA
Approximately not more than 2 weeks from when the above pull requests will be closed

**Comment by akibrhast** [comment]
## Progress
WIP
## Blockers
Needs permission to google cloud console from @ExperimentsInHonesty 
## Availability

## ETA

**Comment by qiqicodes** [comment]
@akibrhast Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by akibrhast** [comment]
Progress: None
Blockers: Vrms,civictechindex
ETA: 2 weeks?

**Comment by erikaBell** [comment]
- Figure out how to trigger google app script through a cron job, within the context of the app script
- Implement, said trigger, every 24hours and extract "TRUE" data from sheets & write to file in hack4la/website/_data/external/_wins-data.json

**Comment by qiqicodes** [comment]
@erikaBell Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by erikaBell** [comment]
FINISHED (-:

[Google App Script maintaining wins page data updates](https://script.google.com/u/1/home/projects/1jySuEtxGfrQpuX1zinjH7sGlqevEnakVx9hGTaCnx-z0K6dQTwRVGMlI/edit)
