### ISSUE TITLE
Fix "Getting started with Docker Link" in CONTRIBUTING.md

### ISSUE THREAD

**Issue by abenipa3** [hackforla/website#1131]
### Overview
Getting Started with Docker Link does not work.

### Action Items

- Fix Getting Started with Docker Link in CONTRIBUTING.md by replacing with new link (under resources listed below)

![image](https://user-images.githubusercontent.com/38295612/109406200-08514d80-792c-11eb-9548-32adbfdb855a.png)

### Resources/Instructions
[Contributing.md - Step 4 Setting Up Docker](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#step-4-setting-up-docker)

**Comment by ExperimentsInHonesty** [comment]
@alyssabenipayo Is this just subbing out the link or writing new instructions?

**Comment by abenipa3** [comment]
@ExperimentsInHonesty Hi, just subbing out the "Get Started with Docker" link. When I clicked on the link, it didn't work.

**Comment by ExperimentsInHonesty** [comment]
@alyssabenipayo thanks for the clarification. I have moved this to the prioritized backlog
