### ISSUE TITLE
Create New Page for Open Roles

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1135]
### Overview
We need to create a new page for open roles on HfLA teams, so that they are visible to the public.

### Action Items

Design
- [x] Reference onboarding research and design ideation for the open roles page (contact @daniellex0 )
- [x] Research and ideate more to determine best layout for open roles page. Reference other job board pages.
- [x] Design the open roles page

### Resources/Instructions
[View New Roles section (scroll to bottom)](https://docs.google.com/spreadsheets/d/1NjrbicVDyd8aTXfPXUAdlX2xg9F3Ez9VThj4EwG-ouw/edit#gid=0)

**Comment by daniellex0** [comment]
Progress: Finalizing desktop MVP designs, determining final schedule filter design, VRMS is in early steps of adjusting schedule data

Next Steps: Decide on schedule filter, finish MVP desktop design, start mobile design, and send to development

ETA: 2 weeks

**Comment by daniellex0** [comment]
Progress: Finalizing desktop MVP designs, ran some designs by users, determined final schedule filter design, VRMS is in early steps of adjusting schedule data

Next Steps: Finish MVP desktop design, start mobile design, and send to development

ETA: 2 weeks

**Comment by daniellex0** [comment]
Progress: Finalizing desktop MVP designs. Editing role description page header. Missed chance to run a/b testing with new volunteers at onboarding last week- will try this week.

Next Steps: Finish MVP desktop design, start mobile design, and send to development when we have the go-ahead from VRMS, etc.

ETA: 1 week

**Comment by daniellex0** [comment]
Progress: Ran a/b testing with volunteers at onboarding. Finalized desktop MVP designs. Started mobile designs.

Next Steps: Get approval for MVP desktop design, finish mobile design, and send to development when we have the go-ahead from VRMS, etc.

ETA: 1 week

**Comment by daniellex0** [comment]
Progress: Added text from a role listing on the UI/UX CoP roles boards

Next Steps: Get approval for MVP desktop design, finish mobile design, and send to development when we have the go-ahead from VRMS, etc.

ETA: 1 week

**Comment by daniellex0** [comment]
Progress: Finished up and got approval for MVP desktop designs

Next Steps: Finish mobile design, and now need to also design the backend CMS (content management system) for this

ETA: 2 weeks

**Comment by daniellex0** [comment]
Progress: Discussed CMS with developers and designed a rough draft

Next Steps: Finish mobile design and backend CMS 

ETA: 2 weeks

**Comment by daniellex0** [comment]
Progress: Discussed potential backend CMS with developers 

Next Steps: Hear from Bonnie about backend CMS. Finish mobile design and backend CMS

ETA: 2 weeks

**Comment by daniellex0** [comment]
Progress: Talked with Bonnie about backend CMS. Updated backend CMS

Next Steps: Determine direction of backend before moving forward

ETA: N/A

**Comment by daniellex0** [comment]
Progress: Continued working on backend CMS, learned more about direction of Roles page/Roles board.

Blockers: Limited time

Next Steps: Finish backend CMS design.

ETA: 6/2

**Comment by daniellex0** [comment]
Progress: Working on assigning dedicated designer(s) to roles page/project

Next Steps: Finish backend CMS design.

ETA: 1 week

**Comment by daniellex0** [comment]
Added Ingrid as designer for Civic Tech Jobs board

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 I would like to know who worked on the designs for this page?

**Comment by daniellex0** [comment]
Hi @ExperimentsInHonesty , this was a big page so it was all-hands-on-deck, the whole design team worked on it together

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 I need to know specific people because I will need to connect them with the people who are working on it now.

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 for context... I am having to explain myself all over again.
