### ISSUE TITLE
Increase ratio of image on project page for New Schools Today to 3:2

### ISSUE THREAD

**Issue by shaswa** [hackforla/website#1151]
### Overview
All  project images on the [hackforla homepage projects section](https://www.hackforla.org/#projects) should have a 3:2 ratio and a standard resolution of 600x400 pixels. 

Current Resolution: 640 x 480 pixels
Current Ratio: 2.67:2

### Action Items

- [x] Increase ratio of project image for New Schools Today to 3:2
- [x] Add the new image file (below in comments) to replace the old one on New School Today project card on HfLA homepage
- [x] Update Status on #1105 and put the new image in the comment

### Resources/Instructions
[Projects page](https://www.hackforla.org/#projects)
[Image](https://www.hackforla.org/assets/images/projects/new-schools-today.jpg)

**Comment by daniellex0** [comment]
New image file with correct specs:

![new-schools-today](https://user-images.githubusercontent.com/67400366/112747736-1666ae00-8f6c-11eb-877e-f92cfc927faf.jpg)
