### ISSUE TITLE
Increase resolution and ratio of image on project page for Hackforla.org Website

### ISSUE THREAD

**Issue by shaswa** [hackforla/website#1152]
### Overview
All  project images on the [hackforla homepage projects section](https://www.hackforla.org/#projects) should have a 3:2 ratio and a standard resolution of 600x400 pixels. 

Current Resolution: 411 x 325 pixels
Current Ratio: 2.5:2

### Action Items

UX/UI
- [x] Increase ratio of project image for Hackforla.org Website to 3:2
- [x] Increase resolution of project image for Hackforla.org to 600 x 400 pixels 

Front-End development
- [x] Add the new resized image (scroll to bottom of this issue) to the HackforLA.org Website project card on the homepage
- [x] Update Status on #1105 
- [x] release dependency on #1219 and put the image in that issue.

### Resources/Instructions
[Projects page](https://www.hackforla.org/#projects)

**Comment by daniellex0** [comment]
@shaswa @ExperimentsInHonesty just to confirm this is a UI issue, not a dev issue?

**Comment by shaswa** [comment]
@daniellex0  Thinking about it more this is a UX issue as the image itself doesn't conform to the standard resolution and ratio
https://www.hackforla.org/assets/images/projects/website.png

**Comment by daniellex0** [comment]
Is there the original version of this image somewhere so that I can send the higher resolution version, OR is there a preference for a different image we can use for the hackforla.org card?

**Comment by daniellex0** [comment]
UX team will look for new image for the hackforla.org project card and project page

**Comment by Oluwafemi-Jegede** [comment]
Hi @daniellex0 

Please provide update

Progress
Blockers
Availability
ETA

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 Please assign this to one of the designers to take care of.  This should be a quick fix.

**Comment by daniellex0** [comment]
New image to add to the "HackforLA.org Website" project card:

![hacknight-women](https://user-images.githubusercontent.com/67400366/114293373-6eacae00-9a4a-11eb-8d9a-380107083b20.png)

Ready for development

**Comment by RobertaFricker** [comment]
The website.png image has been updated to the image shown in this issue which is 600 x 400.  It has also been added to the Project Card per screenshot below:
![image](https://user-images.githubusercontent.com/81199122/114610501-d59db300-9c54-11eb-89e5-4bf13747f68e.png)
