### ISSUE TITLE
Change cursor on drop down of Win page

### ISSUE THREAD

**Issue by ItsLaszlo** [hackforla/website#1155]
### Overview
When using the dropdown filters the cursor change isn't accurate. It changes to ``cursor: pointer`` when hovering over anywhere in the dropdown except for the checkbox. On the checkbox, it turns back into a normal cursor. This can be a bit confusing for the user and implies they can select the category by clicking it rather than clicking the checkbox which isn't the case.

https://www.hackforla.org/wins
![Screen Shot 2021-03-02 at 6 43 59 PM](https://user-images.githubusercontent.com/69860036/109744519-4c8c5a00-7b87-11eb-84e7-40afdd5cae0d.png)
![Screen Shot 2021-03-02 at 6 44 07 PM](https://user-images.githubusercontent.com/69860036/109744525-4dbd8700-7b87-11eb-8d5a-cdf76344950a.png)

### Action Items

- [x] Have the cursor change to a pointer when hovering over the checkboxes
- [ ] Have the cursor revert back to normal when hovering over the rest of the drop-down

### Resources/Instructions

https://developer.mozilla.org/en-US/docs/Web/CSS/cursor

**Comment by trtincher** [comment]
Working on it. Was short on time last week.
ETA : Next Sunday, 03/28/21
