### ISSUE TITLE
Website User Experience - CTA improvements

### ISSUE THREAD

**Issue by S-Vairon** [hackforla/website#116]
**Adding direct CTA elements to the website**

The primary goal of the website being to have people attend a first meeting, to meet the group and understand what this is all about, helpful modifications would be:

- Replacing the top page newsletter subscription CTA by a direct, welcoming, invitation to attend next meetup. 

- Adding precise information about next meetups (place and date) on the top of the page would also be helpful for users.

**On Project Cards**

- Adding clickable information regarding next meeting on each specific project card.

- Adding clickable buttons in place of a text list of skills on each project. Clicking on a skill button would open a module with a list of all projects in need of that specific skill.

- Adding a list of the civic topics targeted - as clickable buttons, on each specific project card. Clicking on that link would open a module showing a list of all the projects working on the same civic topic.

**Showcasing finished projects: motivates newcomers**

- Finished projects should be showcased higher on the page, as it demonstrates clear results of the work accomplished by the teams. It's very positive! 

- Clicking on the card of the finished project could open a module with further details. It could show a video of the project, even a simple video with someone taking us through the different steps. (Also, video has a big impact on increasing traffic on the website (SEO))

**Showcasing members: also motivates newcomers**

- It would be useful to have a small presentation of members (a different one every week/month/quarter), just by giving a little testimony on what they worked on since they are part of HackforLA, what they enjoyed, learned, and accomplished. If members don't want to put up their picture, we can just use the first name as personification.

**Comment by alexandrastubbs** [comment]
Thank you for your contribution with the list above, @S-Vairon. All of these things have made it into our site iteration, some already live and some yet to come. We are closing this issue now.
