### ISSUE TITLE
Update Events Page - Left Column

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1164]
### Overview
We need to update the text and alignment on the left column of the Events page to 1. provide accurate/updated information, and 2. make it look better aligned visually

### Action Items
- [ ] Update the text of the Onboarding section (see below)
- [x] Adjust the size of the Happy Hour image to make it align better with the others (see images and potential fix below)

### Resources/Instructions
[Events Page](https://www.hackforla.org/events/)

Updated text for Onboarding section:

<img width="300" alt="Screen Shot 2021-03-06 at 8 06 37 PM" src="https://user-images.githubusercontent.com/67400366/110229068-89c05700-7ebb-11eb-9bec-32e0d8eeac07.png">

<br>

Alignment of Happy Hour section- currently looks like **left** one, but should look closer to the one on the **right**
(A fix for this might be giving the Happy Hour image its own separate class with a taller height):

<br> 

<img width="250" alt="Screen Shot 2021-03-06 at 8 23 30 PM" src="https://user-images.githubusercontent.com/67400366/110229183-72359e00-7ebc-11eb-866a-0ce75b2c56a8.png">   ..................>   <img width="243" alt="Screen Shot 2021-03-06 at 8 06 46 PM" src="https://user-images.githubusercontent.com/67400366/110229196-76fa5200-7ebc-11eb-97a7-259575252bf4.png">

**Comment by Lol-Whut** [comment]
The week got away with me, so I didn't get to work on this yet, but I'll either have it done by the Tuesday meeting or will let someone know if I have an issue (I don't anticipate any issues at this time).
