### ISSUE TITLE
Adjust file size of some homepage project card images 

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1165]
### Overview
We need to decrease the size of some of the newer homepage project card images because unnecessarily large PNG files can slow down page loading time (per our [image guide](https://docs.google.com/document/d/17AbUtj9aIA8G88O8AVJnyL1jz4cNQ3x740cmzO-2yzk/edit) PNG section)

The images should have a 3:2 ratio and a standard resolution of 600x400 pixels.

### Action Items

- [ ] Review the standard file size/dimensions of the correct project card images (for ex. Ballotnav, Food Oasis sizes are correct). The images should have a 3:2 ratio and a standard resolution of 600x400 pixels.
- [ ] Project card image sizes to decrease and standardize:
   - [ ] 100 Automations
   - [ ] Home Unite Us
   - [ ] VRMS
- [ ] Add the new standardized versions in comments in this issue below

Development
- [ ] Add the decreased/standardized images to their project cards
   - [ ]  (*note that only the homepage project card image file needs to be adjusted- *not* the large [project page](https://www.hackforla.org/projects/food-oasis) "splash" version image file)

### Resources/Instructions
[Homepage project cards](https://www.hackforla.org/#)

A project card image for reference:

<img width="423" alt="Screen Shot 2021-03-06 at 9 19 41 PM" src="https://user-images.githubusercontent.com/67400366/110229914-afe8f580-7ec1-11eb-9438-3d7419412ea7.png">

**Comment by qiqicodes** [comment]
@Linda-OC Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by Linda-OC** [comment]
Progress:  None yet
Blockers: Locating the code that needs to be changed
Availability: 4 hrs
ETA:  By  5/19

**Comment by mgodoy2023** [comment]
Here are the new project image files that have been adjusted to 600pixels x 400pixels. I set all of the resolutions to a standard 72dpi, as that is the standard used for online images. 

100 automations:
![100automations](https://user-images.githubusercontent.com/86011089/122809778-657a6180-d283-11eb-9e79-c6ede138a354.png)

Home Unite Us:
![home-heart](https://user-images.githubusercontent.com/86011089/123163489-9e067080-d426-11eb-88b7-dfe8ab061631.png)

VRMS:
![vrms](https://user-images.githubusercontent.com/86011089/122810012-affbde00-d283-11eb-8440-9e63afbda505.png)

**Comment by mgodoy2023** [comment]
Hi @daniellex0, please review these images and advise on next steps. Thank you!

**Comment by mgodoy2023** [comment]
Hi again @daniellex0, I updated the images in a [new pull request](https://github.com/hackforla/website/pull/1802#issue-674955386) and adjusted the Home Unite Us image the way you said to. Please review the images and let me know about any next steps. Thank you!

**Comment by Sihemgourou** [comment]
Hello @mgodoy2020 , why this issue is still open ? The PR seems closed

**Comment by Sihemgourou** [comment]
@mgodoy2023 why this issue is still open ? The PR seems closed
Please add uptades on this issue before taking another one (I unassigned you from [this one](https://github.com/hackforla/website/issues/1551) but Please feel free to take it back once you finish working on this issue.
