### ISSUE TITLE
Standardize Wins Page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1166]
### Overview
We need to standardize the Wins page to be more consistent with other pages on the HfLA site

### Action Items
- [x] Remove all CSS formatting from the heading ("Let's Celebrate Together!"). The h1 tag should already automatically give it the correct formatting
- [x] Add margin below the "Let's Celebrate Together!" heading- `margin-bottom: 56px` (in nested h1 class)
- [x] Header image: adjust the max-height of `.wins-hero` `img` class to 360px
- [x] Adjust color of `.wins__see-more-div` from red to $color-red (the HfLA pink color)

### Resources/Instructions
[Wins page](https://www.hackforla.org/wins)

Before:
<img width="450" alt="Screen Shot 2021-03-06 at 9 48 47 PM" src="https://user-images.githubusercontent.com/67400366/110230450-e9bbfb00-7ec5-11eb-8304-f0ddcfa48980.png">
<br>
After:
<img width="450" alt="Screen Shot 2021-03-06 at 9 48 40 PM" src="https://user-images.githubusercontent.com/67400366/110230443-e0cb2980-7ec5-11eb-8900-a837724c5a2a.png">
<br>
Before & after (red to pink):
<br>
<img width="128" alt="Screen Shot 2021-03-06 at 9 48 12 PM" src="https://user-images.githubusercontent.com/67400366/110230515-58995400-7ec6-11eb-922b-e1479ffbe9ec.png"><img width="152" alt="Screen Shot 2021-03-06 at 9 48 31 PM" src="https://user-images.githubusercontent.com/67400366/110230480-1f60e400-7ec6-11eb-93b9-e0ab832f2dcf.png">

**Comment by akibrhast** [comment]
> The h1 tag should already automatically give it the correct formatting - @daniellex0 

How is it automatically giving it the correct formatting?

**Comment by daniellex0** [comment]
@akibrhast From these scss files:

https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_typography.scss
https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_typography.scss
