### ISSUE TITLE
The cards under proiects/website url does not mention the timezone

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1171]
### Overview
Currently the hackforla project cards displaying the events meeting times does not state that the meetings times are being displayed in the users local time. This can cause confusion to people who are being onboarded, because the general assumption is since its hack4la all meeting times that are displayed are shown in PST.

### Action Items
- [ ] Discuss adding some kind of paragraph like this image that shows the user that the times displayed are in their local time zone
![image](https://user-images.githubusercontent.com/32349001/110251423-54b11480-7f4e-11eb-9b84-932635610a0b.png)

### Resources/Instructions
https://www.hackforla.org/projects/website
<details>
<summary>No Time Zone Specified in The Card</summary>

![image](https://user-images.githubusercontent.com/32349001/110251469-8d50ee00-7f4e-11eb-8bd1-717e233ea0f0.png)

</details>

**Comment by akibrhast** [comment]
@daniellex0 Is there something we can do about this?

**Comment by daniellex0** [comment]
@akibrhast Just to confirm, are the times displayed right now on the project pages automatically local? If so I can work on writing text about this to add. Thanks for noticing this!

**Comment by akibrhast** [comment]
@daniellex0 Yes They are automatically local. It was actually noticed by one of the new folks who recently got onboarded and it caused them confusion , because lacking any information the general assumption was the time is being shown in PST

**Comment by daniellex0** [comment]
@akibrhast Got it, great- ok I'll draft some language/design and post the update when I'm done on this issue 👍. Just assigned myself. When I'm done I'll change it to front-end label and put it back in prioritized backlog with instructions.

**Comment by daniellex0** [comment]
Progress: I have a new design on Figma for a few sections on the Project page including the missing timezone, and need to have @ExperimentsInHonesty approval first : https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=7891%3A0

Next steps: Get approval or edits

**Comment by akibrhast** [comment]
Confirming that the changes has been approved by @ExperimentsInHonesty . Removing help wanted label on it. Assigning myself to it.
