### ISSUE TITLE
Confirm every image has an alt attribute

### ISSUE THREAD

**Issue by kevinreber** [hackforla/website#1192]
### Overview
We need an `alt` attribute for accessibility purposes for each image. Some images throughout the site do not have `alt` attributes

### Action Items
- [x] Confirm every image has an `alt` attribute
- [x] Add appropriate descriptions for images without `alt` attributes

### Resources/Instructions
https://www.w3schools.com/tags/att_img_alt.asp

**Comment by qiqicodes** [comment]
Progress: Working through the html and md files.

Blockers: None.

Availability: Open on Sunday afternoon.

ETA: Desire to merge the edited alt by 3/30/21

**Comment by csseu** [comment]
Ooh, I just saw this issue after making https://github.com/hackforla/website/issues/1337 - should I delete that one?

**Comment by qiqicodes** [comment]
we can keep issue #1337, if I finish this issue before #1337 is fixed, I will close #1337.

**Comment by akibrhast** [comment]
Closing #1337. Because that is a duplicate.

**Comment by qiqicodes** [comment]
Added and edited alt text for all informative and decorative images, except the following:
1. Write for All Project Card
2. Building Survey Guide Page
3. Sitemap
4. About 
        - Sustainability SDG icons
        - Accomplishment Wins Card 
        - Donation Gif

**Comment by ExperimentsInHonesty** [comment]
1. mention rainbow because its a commonly referred to inclusivity symbol
2. skip
3. Making a markdown file that contains every page in an outline format with the status of the page in parenthesis after each name, and that would make it accessible.  Also the live pages (that are connected to the menu could be linked.  
4. X
    1. SDG Icons (go to the UN and grab their alt text)
    2. Describe sample card
    3. Describe what is happening so that someone who cannot see it could replicate action
