### ISSUE TITLE
Update Project Profile: 311-Data

### ISSUE THREAD

**Issue by tarang100** [hackforla/website#1196]
### Overview
The website team needs the 311-data project details to be up to date on the website

### Project card
https://github.com/hackforla/website/blob/gh-pages/_projects/311-data.md
### Action Items

- [ ] 311-data Team Leadership
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [ ] image
      - [ ] leadership
      - [x] links
         - [x] Github
         - [x] Slack
         - [ ] Test Site
         - [ ] Demo Site
         - [x] Site
      - [ ] looking
      - [x] technologies
      - [x] location
      - [x] partner
      - [x] tools
      - [x] status

### Resources/Instructions

Do not send details in any google docs, slide decks, etc.  Please annotate this issue via comments only.

**Comment by akibrhast** [comment]
@tarang100 The link provided in the issue is broken.

**Comment by captain-nimo** [comment]
Please Add the following leadership info:

Name: Mahmudul Hasan Robin
Role: Product Manager (Internal)
Slack ID: UEW1MNZHT

Name: Prasadh Palanichamy
Role: Product Manager (External)
Slack ID: U0143158U80

Name: Ahdithan Uthayakumar
Role: Product Manager (Revenue and Sustainability)
Slack ID: U01FDAPULJE

**Comment by tarang100** [comment]
@akibrhast I have updated the link and it is working now. Please refer to the comment by @captain-nimo for updates. Thanks!

**Comment by shaswa** [comment]
Please use the project image from [this issue](https://github.com/hackforla/311-data/issues/987) for the update
