### ISSUE TITLE
Add Filter Tags to Homepage project filters

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1201]
### Overview
We need to add filter tags below the homepage project filters so that users can immediately know which filters they selected, and can remove any filters easily. 

This also involves adjusting some of the current filter functionality (selected filter categories no longer turn pink- instead they display the number of filters selected in parentheses)

### Action Items
- [x] Review new design of filter tags in ['Homepage (WIP)' Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205) (**in purple rectangle**)
   - [x] For help with Figma functionality / a quick tutorial, reach out to @daniellex0 on this issue (or on slack)
- [x] Research how to add filter tags 
- [x] Add filter tags to homepage, following the Figma design
- [x] Keep selected filter categories white (instead of changing to pink, as they do now) (see Figma design)
- [x] Add # of filters selected per category in parentheses (see Figma design)
- [x] Make sure changes to homepage filters don't affect the Wins page filters
   - [x] If it does affect the Wins page filters, apply the filter tags above to the Wins page as well

### Resources/Instructions
[Homepage](https://www.hackforla.org/#)
[Figma design for homepage filter tags](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205) **(in purple rectangle)**
[Example of filter tags in Best Buy website](https://www.bestbuy.com/site/searchpage.jsp?_dyncharset=UTF-8&id=pcat17071&iht=y&keys=keys&ks=960&list=n&qp=brand_facet%3DBrand~Sony&sc=Global&st=tv&type=page&usc=All%20Categories)
[Wins page](https://www.hackforla.org/wins/)

<details>
<summary> New filter tag designs (click arrow)
</summary>
<br>

One filter selected:

<img width="500" alt="Screen Shot 2021-03-13 at 4 44 24 PM" src="https://user-images.githubusercontent.com/67400366/111053776-8f69ef80-841b-11eb-95f5-597122603239.png">

<br>
<br>

Multiple filters selected:

<img width="500" alt="Screen Shot 2021-03-13 at 4 44 19 PM" src="https://user-images.githubusercontent.com/67400366/111053781-94c73a00-841b-11eb-853d-0bd515dc4f58.png"></details>

So that you know what to look for- this is what the filter tags section in the purple rectangle looks like in the [Figma homepage file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205):

<img width="400" alt="Screen Shot 2021-03-13 at 4 31 49 PM" src="https://user-images.githubusercontent.com/67400366/111053765-79f4c580-841b-11eb-9d77-af5ddd3bdd59.png">

**Comment by Lol-Whut** [comment]
Call the new class filter-item

**Comment by akibrhast** [comment]
## Progress
Almost complete. Struggling with css

## Blockers
Awaiting Closure on
- https://github.com/hackforla/website/pull/1269
- https://github.com/hackforla/website/pull/1267

## Availability
Here and There

## ETA
Approximately a week from whenever the above PR's are closed

**Comment by erikaBell** [comment]
@daniellex0 the "(1)" "(2)" and "(5)" placement in the figma design, is the decision to "add" numbers together, under certain cases? 

i.e., my question comes up when imagining a scenario where an individual comes to the page, goes to the "Looking" dropdown menu, and decides to checkbox both "Development (12)" and "Content (4)".

"Looking" would then become:  "Looking (16)"

I'm assuming "Looking (12), (4), etc.." isn't desired

**Comment by akibrhast** [comment]
@erikaBell Its the number of items selected. 

> goes to the "Looking" dropdown menu, and decides to checkbox both "Development (12)" and "Content (4)".

Looking would then become : "Looking (2)"

**Comment by erikaBell** [comment]
@akibrhast Ah, thanks!

**Comment by erikaBell** [comment]
Progress update ~ 

Have added filter tags, & numbers per category in parentheses. 
Currently working on getting the URL params to be updated via removed filter tags & "clear all". 

<img width="1440" alt="add-filter-tags-issue-1201" src="https://user-images.githubusercontent.com/67438372/112758875-539b6200-8fa5-11eb-9e3f-9fd5d9cad9d3.png">

**Comment by erikaBell** [comment]
Progress Update: just need to work out a bug with one of the dropdown menus.
