### ISSUE TITLE
Events: times are in the wrong order

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1207]
### Overview
AM meeting times are showing up after PM meeting times

<details>
    <summary>example image</summary>

![Screen Shot 2021-03-15 at 1 33 42 PM](https://user-images.githubusercontent.com/53061723/111217688-12fa1c80-8593-11eb-9918-7bc0634deeb9.png)

</details>

### Action Items
- [ ] fix the bug. 

### Resources/Instructions
- /events/right-col-content.html
- evans pr that fixed this before... #1097

**Comment by drubgrubby** [comment]
Screenshot showing times PM before AM

![screencapture-hackforla-org-events-2021-03-15-14_48_36](https://user-images.githubusercontent.com/68244054/111226140-ef889f00-859d-11eb-8da4-65664242067c.png)
