### ISSUE TITLE
Add margin in footer

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#1216]
### Overview
We need to fix the bottom of padding in the HfLA website footer, currently the mobile view has extra bottom padding.

### Action Items
[ ]  Match bottom padding with top padding .main-footer class

Footer should look like this for mobile:
<img width="353" alt="Screen Shot 2021-03-16 at 8 44 16 PM" src="https://user-images.githubusercontent.com/68657634/111411796-6dc96c00-8698-11eb-9b32-6bfee9e31226.png">

Footer should look like this for desktop:
<img width="704" alt="Screen Shot 2021-03-16 at 7 56 18 PM" src="https://user-images.githubusercontent.com/68657634/111408481-95b5d100-8692-11eb-99da-6fabad19a3dd.png">

**Comment by ExperimentsInHonesty** [comment]
This issue got resolved during update of footer on another issue.  Verified by @Aveline-art
