### ISSUE TITLE
Update Project Profile: HackforLA Website

### ISSUE THREAD

**Issue by Oluwafemi-Jegede** [hackforla/website#1219]
### Dependency
#1152 replace the 600 x 400 image for the project card.

### Overview
As a product manager of HackforLA Website I want my project's details to be up to date on the HackforLA website

### Project card
https://github.com/hackforla/website/tree/gh-pages/_projects/website.md

### Action Items
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [ ] image
      - [ ] leadership
      - [x] links
         - [x] Github
         - [x] Slack
         - [x] Test Site - N/A
         - [x] Demo Site - N/A
         - [x] Site
      - [x] looking
      - [ ] technologies
      - [x] location
      - [x] partner
      - [ ] tools
      - [x] status

**Comment by Oluwafemi-Jegede** [comment]
600 x 400 image needs replacing:
[insert image here] #1152 

Name: Oluwafemi Jegede 
Role: Product Manager
Slack ID: https://hackforla.slack.com/team/U01GS3DN1R6

Technologies (please add):
- Github API
- Node

Tools (please add):
- Miro

**Comment by ExperimentsInHonesty** [comment]
@akibrhast can you review the technologies list from the project profile and indicate any we have missed.  I added GitHub API and Node (is the filter built on node?)

**Comment by akibrhast** [comment]
@ExperimentsInHonesty Which filter are you asking about ? the one on our homepage?
It's built with javascript.
But the hackforla website team is indeed using **node** as well as **github actions** and **google sheets api**

**Comment by RobertaFricker** [comment]
Updated dependency on Issue #1152 per the following link:
https://github.com/hackforla/website/issues/1152#issuecomment-819001504
