### ISSUE TITLE
Update Project Profile: Expunge Assist (formerly Record Clearance Project)

### ISSUE THREAD

**Issue by ggrrettcchhenn** [hackforla/website#1249]
### Overview
As a product manager of Expunge Assist I want my project's details to be up to date on the HackforLA website. We just changed our name and are working to rebrand across all platforms as Expunge Assist.

### Project card
https://www.hackforla.org/projects/record-clearance-project

### Action Items

- [x] Expunge Assist Team Leadership
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [x] leadership
      - [x] links
         - [x] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] looking
      - [x] technologies
      - [x] location
      - [x] partner
      - [x] tools
      - [x] status

**Comment by ExperimentsInHonesty** [comment]
Please Change:
- Title: Expunge Assist
- Description: Expunge Assist aims to help people in California with criminal records accomplish record clearance, expungement or reduction and subsequently a second chance as a part of society.

We work with verifiable non-profits, the government and partners to build digital tools that can affect changes in the lives of these justice impacted individuals.
-  image
 - leadership
 - looking
- Demo Site

**Comment by ggrrettcchhenn** [comment]
**Leadership Update:**

Member Name: Andan Eddy
Role: Product Manager
Slack Member ID: U01LE6TAXQR
Github Handle: Andan-Eddy
(please keep Myranda & Gretchen as PMs)

**Title:** Expunge Assist

**Description:** Expunge Assist aims to help people in California with criminal records accomplish record clearance, expungement or reduction and subsequently a second chance as a part of society.

We work with verifiable non-profits, the government and partners to build digital tools that can affect changes in the lives of these justice impacted individuals.

**Looking:** Marketing & Communications, Graphic Designer, UI Designer, Product Manager
(please remove all other open roles)

Image posted below.

**Comment by ggrrettcchhenn** [comment]
**Image:** 
![expunge-assist-hero](https://user-images.githubusercontent.com/27507664/113753923-89d29300-96c3-11eb-8f9a-8bbd33d37376.png)

**Comment by ExperimentsInHonesty** [comment]
@pascuas 
Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by pascuas** [comment]
@ExperimentsInHonesty 
1. Progress- Starting
2. Blockers - None
3. Availability - Mornings
4. ETA - Friday
