### ISSUE TITLE
Increase max-width of one subheading on Join Us page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1253]
### Overview
We need to increase the max-width of one subheading on the [Join Us page](https://www.hackforla.org/join-us) to keep it on one line instead of two, and stay consistent with the original design

### Action Items
- [ ] Adjust the max-width of the subheading **"How to help us continue to do impactful work"** on the "Help Us Keep the Lights on" card - it should have the same max-width of the paragraph above it

### Resources/Instructions
[Join Us page](https://www.hackforla.org/join-us)
[HfLA site architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

Click arrow below to view annotated screenshots:

<details>
<summary>View screenshots</summary>
<br>

**Subheading currently looks like this:**

<img width="600" alt="Screen Shot 2021-03-17 at 11 26 51 PM" src="https://user-images.githubusercontent.com/67400366/111582965-e0aa1400-8778-11eb-9b20-d1ca3232e44b.png">

<br>
<br>

**Subheading should look like this (one line):**

<img width="450" alt="Screen Shot 2021-03-17 at 11 28 51 PM" src="https://user-images.githubusercontent.com/67400366/111582979-e7388b80-8778-11eb-9fc1-75ac23879658.png">
</details>

**Comment by daniellex0** [comment]
Hey @akibrhast I don't think this is fixed?

<img width="350" alt="Screen Shot 2021-04-05 at 12 48 42 PM" src="https://user-images.githubusercontent.com/67400366/113619027-4ddcf680-960d-11eb-86d0-b04c18a15f31.png">

**Comment by akibrhast** [comment]
@daniellex0 
<details>
<summary>Image From Live Site</summary>

![image](https://user-images.githubusercontent.com/32349001/113629952-213cd500-9635-11eb-9d39-7e5de1b70107.png)

</details>

**Comment by daniellex0** [comment]
@akibrhast Sorry you're right, looks good now- I'm not sure why I was seeing the old version
