### ISSUE TITLE
Update donation gif on Join Us page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1254]
### Overview
We need to replace the current donation gif on the [Join Us page](https://www.hackforla.org/join-us) with the new version so that it looks cleaner / there isn't extra cut-off text on its right

### Action Items
- [ ] Replace current donation gif on [Join Us page](https://www.hackforla.org/join-us) with the new version (the new one is used on the bottom of the [About page](https://www.hackforla.org/about))
- [ ] Make sure the layout still looks good with the new gif

### Resources/Instructions
[Join Us page ](https://www.hackforla.org/join-us)
[About Us page](https://www.hackforla.org/about) (scroll to bottom for new gif)
[Hack for LA Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

Old version:

<img width="176" alt="Screen Shot 2021-03-17 at 11 46 17 PM" src="https://user-images.githubusercontent.com/67400366/111584702-721a8580-877b-11eb-8da8-f4549a412072.png">

New version:

<img width="185" alt="Screen Shot 2021-03-17 at 11 47 38 PM" src="https://user-images.githubusercontent.com/67400366/111584706-747cdf80-877b-11eb-890e-b7d3a5047b0e.png">

**Comment by kevinreber** [comment]
<details>

<summary>Before</summary>

![image](https://user-images.githubusercontent.com/42260999/111741275-7611da80-8843-11eb-9731-6b64715f8632.png)

</details>

<details>

<summary>After</summary>

![image](https://user-images.githubusercontent.com/42260999/111741315-8aee6e00-8843-11eb-8a1a-9e1408cdab52.png)

</details>
