### ISSUE TITLE
Add Join page to the nav bar 

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1257]
### Dependencies

These issues must be completed before the page can be added to the nav bar:

~~#1251~~   ,  ~~#1252~~  , ~~#1253~~  , ~~#1254~~ , ~~#1255~~ , #1256

### Overview
We need to add the Join page to the top nav bar of the Hack for LA website when the page is ready, so that users can access it

### Action Items
- [x] Research how to update the nav bar with a new link
- [x] Add Join page to the nav bar

### Resources/Instructions
[Join page](https://www.hackforla.org/join-us)
[Hack for LA site architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

**Comment by akibrhast** [comment]
## Progress
Done. Awaiting Review by @daniellex0 
## Blockers

## Availability

## ETA
