### ISSUE TITLE
Update issues in Ice-box with the appropriate dependency label

### ISSUE THREAD

**Issue by Oluwafemi-Jegede** [hackforla/website#1259]
### Overview

We need to tag all dependency related issues on the Ice-box of HfLA Website Project Board appropriately. 

### Action Items
* Review all issue on the Ice-box section, including their dependencies
* Apply appropriate tag to issue and update issue where need be
* Collate issues with little or no clarity for next team meeting

### Resources/Instructions
[Link to the Project Board for HackforLA Website repository](https://github.com/hackforla/website/projects/7)

**Comment by Oluwafemi-Jegede** [comment]
@ExperimentsInHonesty please help review the issue I just raised on the task assigned at yesterday's meeting

**Comment by tarang100** [comment]
@Oluwafemi-Jegede please provide an update

Update:
Blockers:
Availability:
ETA:

**Comment by Oluwafemi-Jegede** [comment]
Update: 

@ExperimentsInHonesty please review the issues I have gone through and updated on the ice-box 

[] #759 updated dependency tag on issue

[] #221 dependency issue on this, #242 have been closed, I think work can commence on this, and dependency tag has been removed

[] #583 dependency issue https://github.com/100Automations/futureautomations/issues/8 has been unclaimed for more than 6months, is this project still on?

[] #387 dependency issue https://github.com/hackforla/product-management/issues/18 still active on PM board

[] #1033 updated dependency tag on issue and dependency issue #1031 still active

[] #1061 dependency issue on this, #1060 I think work can commence on this, and dependency tag has been removed

[] #1070  dependency issue on this, #1069 I think work can commence on this, and dependency tag has been removed

[] #797 if there appears to be no issue attached to the **_privacy policy_** which is a dependency 


ETA: Task to be concluded before meeting on 25th May.
