### ISSUE TITLE
Cross Platform hacknight image standardization

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#126]
### Overview 

When you click our meetup link from the hfla site it takes you to a page that has our hero image for the overall meetup account, but no images for our individual hack nights.  We need to change that so the user experience is more consistent.

Current images being used on the website to represent the DTLA and Santa Monica hack nights are too small for use at meetup (see Requirements)

###  Requirements
Meetup.com requires images that are at least 1200 x 675 pixels.  Hackforla.org site uses 600x400.

### Action Item
Determine if we already have images we can use for our hacknights on both meeetup and the website that fit the requirements, and paste those image urls in the comments.  If there are not any images that fit the requirement, indicate that instead.

### Resources you can use:
https://jimthoburn.com/hackforla/
https://medium.com/hack-for-la/listen-first-hack-second-70865f478f30
https://twitter.com/hackforla
https://www.facebook.com/pg/hackforla/photos/?ref=page_internal

**Comment by ddrosario** [comment]
I found bigger versions of the DTLA and Santa Monica pictures. Are these pictures fine or would we want to use different images that are more related to Hack for LA?

Santa Monica [image](https://static.businessinsider.sg/2018/07/07/586e8e70ee14b6c7148b6a30.jpg)
La Kretz [image](https://pbs.twimg.com/media/DFA-wNpXgAA4oFO.jpg)

**Comment by ExperimentsInHonesty** [comment]
Bonnie to update meetup account with images from the hack nights.

**Comment by ExperimentsInHonesty** [comment]
The images on the meetup account have been updated.
