### ISSUE TITLE
Broken link on Events page

### ISSUE THREAD

**Issue by cnk** [hackforla/website#1264]
### Overview
We need to have the links on the events page work.  Currently its coded so that the link is on the same level as the page its coming from which is incorrect and causing the link not to work.

### Action Items
- [x] Fix the link on the events page (content comes from _data)
   - Currently the sends the user to: https://www.hackforla.org/events/getting-started
   - Needs to go to: http://hackforla.org/getting-started

### Resources
code that needs its link updated is located in our code at `_data/internal/events.yml`

<details>
<summary>Image of where link appears on the events page</summary>

![Screen Shot 2021-03-25 at 7 55 26 PM](https://user-images.githubusercontent.com/37763229/112570891-203db500-8da4-11eb-82c1-f1922890d655.png)

</details>

**Comment by averdin2** [comment]
The getting started link shown in the screenshot no longer redirects to the wrong link, but instead redirects to the correct link (http://hackforla.org/getting-started).
![image](https://user-images.githubusercontent.com/10714770/113069634-a166c480-9175-11eb-870e-97ce84fd9445.png)
After clicking the link:
![image](https://user-images.githubusercontent.com/10714770/113069714-d1ae6300-9175-11eb-9b91-2600f31b4bd3.png)
