### ISSUE TITLE
HELLOW THIS ISSUE WAS MADE IN SLACK

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1276]
---
name: 'Blank Issue '
about: 'Standard HackforLA issue template '
title: ''
labels: ''
assignees: ''

---

### Overview
REPLACE THIS TEXT - Clearly state the purpose of this issue in 2 sentences or less

### Action Items
REPLACE THIS TEXT - List the research to be done, or the steps to be completed.
Note: If the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

### Resources/Instructions
REPLACE THIS TEXT - Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc.

edit2 on this issue
edit 4 on this issue removing edit 1
edit 5 on this issue removing edit 3

**Comment by jbubar** [comment]
No way! How'd you do this?

**Comment by akibrhast** [comment]
@jbubar 
Type `/github` on the hfla site github notification channel to see commands
