### ISSUE TITLE
Events Page Load Time Slow

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1284]
### Overview
The events in the events page takes more than half a second to load on every single page refresh

### Action Items
- Cache api data to local storage, and ensure that dont call api on every page refresh unless needed

### Resources/Instructions
- `pages\events\right-col-content.html`
- Store the filtered and sorted object as a string in local storage. Also store the date/and time of the storage as a separate-key
    - if date-time key in storage(means object also in storage) retrieve date-time . Then call api, and see check if any `updateDate:` from api [NEWER THAN] date-time in local storage then do a refilter resort of the object
    - if any `updateDate:` from api is not newer than date-time in local storage.. then dont change dom

**Comment by akibrhast** [comment]
@danyc23  @trtincher @kevinreber Feel free to pick up/self assign on this issue if anyone of you is interested. First come first served.

**Comment by erikaBell** [comment]
In process of researching, understanding current code and testing methods.
