### ISSUE TITLE
Start a backend team

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1286]
### Overview
There are many things that have been placed on the back burner, and ways that we can improve our site functionality.

*** I created this issue so that we do not forget to go over it in the dev meeting... (like I forgot to go over it in the dev meeting today)

### Action Items
- [x] let the team know about the backend meeting and what it is for
- [x] come up with a time that works for everyone
- [ ] set up a google calendar invite for it

### Resources/Instructions
- https://www.when2meet.com/?11404328-vscQa

**Comment by tarang100** [comment]
The Product team would like to be involved in this meeting because we have a number of ideas around what the site could do that are backend related

**Comment by ExperimentsInHonesty** [comment]
@tarang100 @Oluwafemi-Jegede can either of you make Thursday at 7:30-8:30pm meeting with backend

**Comment by Oluwafemi-Jegede** [comment]
@ExperimentsInHonesty I am assuming the time above is EST, that would be 00:30am my time. I will be available but I will not be able to stay more than the stipulated time which is 1hour.

**Comment by Oluwafemi-Jegede** [comment]
> @tarang100 @Oluwafemi-Jegede can either of you make Thursday at 7:30-8:30pm meeting with backend

**Comment by akibrhast** [comment]
@jbubar I believe the meeting time has been consolidated to 7:30pm to 8:30pm on thursdays. What is the next step here ?

**Comment by erikaBell** [comment]
We did it, we made it. Confirming: 7:30 - 8:30 Thursdays (-;
