### ISSUE TITLE
Conduct post-onboarding interviews with new volunteers

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1289]
### Overview
We need to carry out the next round of post-onboarding interviews with new HfLA volunteers in order to continue collecting data about their experience with onboarding and the HfLA website.

### Action Items
- [x] Edit potential [interview questions](https://docs.google.com/document/d/1OCzo9joL61fGjRNSHhOv8z22rkRVnfvQhq5k1EdlaAQ/edit)
- [x] @daniellex0 determine logistics of attending now-high-security onboarding zoom- coordinate with Olivia and Tan
- [x] @ashleylin1 , Rosalyn, and @christina245 attend HfLA onboarding meeting Mon 3/22 and interview attendees
- [x] @Rosalyn-broddie , @alyssabenipayo and @christina245 will attend [HfLA onboarding meeting](https://www.meetup.com/hackforla/events/vrbnfsyccfbnc/) this Tue 3/30 at 6pm PDT and interview attendees
- [x] Determine if need to attend more onboarding sessions to gather more information
- [x] Synthesize results of interviews together (affinity mapping if appropriate)
- [x] Determine action items to address results of onboarding research

### Resources/Instructions
Interview questions- https://docs.google.com/document/d/1OCzo9joL61fGjRNSHhOv8z22rkRVnfvQhq5k1EdlaAQ/edit
Meetup event for onboarding- https://www.meetup.com/hackforla/events/pcrsfsyccfbdc/

**Comment by qiqicodes** [comment]
@Rosalyn-broddie Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by daniellex0** [comment]
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by Rosalyn-broddie** [comment]
1. Progress: We conducted a set of post-onboarding interviews during which we received input for in-progress features for the Roles page.  
2. Blocks: Waiting for Bonnie to return 
3. Availability: I can attend an upcoming onboarding session to interview volunteers 
4. ETA: We're looking to conduct more post-onboarding interviews to get input on some of our ideas for the homepage. We're also going to get more input on our onboarding sessions and slides

**Comment by qiqicodes** [comment]
@Rosalyn-broddie Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:
Availability:
ETA:

**Comment by Rosalyn-broddie** [comment]
Progress: Danielle and Hope conducted interviews with new volunteers to get feedback on the HFLA homepage wireframes (I wasn't feeling well and wasn't able to attend). We got feedback that has been incorporated into new iterations that will be shown to users outside of the HFLA organization and that aren't already familiar with the website.
Availability: I'll be available to hold interviews with people this week
ETA: If we get responses for interviews this week, we should have enough feedback to go into high fidelity mockups

**Comment by Sihemgourou** [comment]
@rohit-309
Please add update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by daniellex0** [comment]
This phase of UX Research has been completed
