### ISSUE TITLE
Create How-to Submit Pull Request (PR) in CONTRIBUTING.md

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#1290]
### Overview
Create How-to Submit Pull Request (PR) in CONTRIBUTING.md. 

### Action Items
- [ ] Put instruction in GitHub Wiki Page
- [ ] Link current issues
- [ ] Create new PR labels
- [ ] List all the necessary steps to guide volunteers to understand the proper PR workflow

### Reference Resources
https://github.com/codeforamerica/brigade-playbook/issues/119

**Comment by akibrhast** [comment]
instructions on how to submit a pull requests have been added to the new contrib file
