### ISSUE TITLE
Add badges to Wins page cards

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1313]
### Overview
Continuation of #1203

We need to add badges and explanatory text bubbles to the Wins page cards so that the "wins" users select in the survey can all show up on their wins cards (before they click "see more")

### Action Items
- [ ] Review the [Figma file for the Wins page badges](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) (in **blue rectangle**)
- [ ] Explore the work @jbubar has already done in #1203 to add the badges to the popup modal
- [ ] Research how to add text bubbles when users hover over badge icons
- [ ] Add badge icons to Wins page cards

### Resources/Instructions
[Wins page](https://www.hackforla.org/wins/)
[Figma file for the Wins page badges](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) (in **blue rectangle**)
[tool tip tutorial](https://www.w3schools.com/howto/howto_css_tooltip.asp)

**Comment by danyc23** [comment]
Blockers:  Haven't find any blockers yet.
Availability: Monday and Thursday.
ETA:  End of the week.

**Comment by jbubar** [comment]
@danyc23 any updates?
we can break this issue up into pieces to make it more manageable

**Comment by erikaBell** [comment]
@daniellex0 @jbubar are these badges in one of our folders, and I'm just not seeing it? or am I supposed to grab them from somewhere, and also not finding that?

**Comment by akibrhast** [comment]
@erikaBell 

> are these badges in one of our folders, and I'm just not seeing it?

I believe they are not in one of our folders.

> or am I supposed to grab them from somewhere, and also not finding that?

You are supposed to grab them from the figma design

<details>
<summary>How to export icons from figma</summary>

![image](https://user-images.githubusercontent.com/32349001/115130505-4d097480-9fbe-11eb-8834-a384741ce304.png)

</details>

Edit since these are icons. I would recommend to export them as .svg icons .

**Comment by daniellex0** [comment]
Sorry about the delay @erikaBell - if I'm not mistaken, I think @jbubar may have added some (or all) of these svg's already when he worked on the overlay/popup (but these might be on a draft branch of his only..)

**Comment by jbubar** [comment]
I did not. I did a draft pr for this before we had the final design.. So I might have all of these on a branch on my repo

**Comment by daniellex0** [comment]
@jbubar Got it, that might be good to share with @erikaBell if you still have it because it had the functionality of connecting icons with specific "wins" from the survey, right? Or even if not, whatever you had might help.. ok just found it, I'm thinking specifically of this PR- #1006

**Comment by jbubar** [comment]
@daniellex0 can we break this up into multiple issues?
can we put the overlay part into another issue? 
it is a pretty big issue. let me know what you think
