### ISSUE TITLE
Create project card: Access the Data

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#1315]
### Overview

We need to make a project card so that this Project's details show up on the HfLA website

### Action Items

- [ ] Development
   - [ ] Get details from Resources below
   - [ ] Create access-the-data.md file using details
   - [ ] Add images to appropriate assets folder

### Resources/Instructions
- [Details for Project Card](https://github.com/hackforla/access-the-data/issues/3)
- Folder where the access-the-data.md file goes:  _projects
- Folder where the images go: assets/images/projects/
- [Template of a project.md file](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)

**Comment by GLRJr** [comment]
Created .md file, added images to proper folder,new project card is showing on showing on home screen, needs identification number

**Comment by qiqicodes** [comment]
repo ID: 330800079

Identification ID is found here:
https://api.github.com/repos/hackforla/access-the-data

Next time, can we have the repo ID provided in the issue? Also the wiki link to how to get the repo ID?
