### ISSUE TITLE
Add Shared Housing project card to website

### ISSUE THREAD

**Issue by owenjoseph** [hackforla/website#132]
### Overview
From @ExperimentsInHonesty's [DTLA Team Project Manager Responsibilities](https://docs.google.com/document/d/1lmQXW_4KOC3HDGdA0-wgEqDJlROYdKzDslK2wrDLJbQ/edit?usp=sharing) doc:

> Provide collateral for the hackforla website (see project cards on the [hackforla.org](http://www.hackforla.org) website)

### Action Items
- [x] Gather items
  - [x] 600 x 400 image
  - [x] Name of project
  - [x] A blurb about your project
  - [x] Links (website, github, etc.)
  - [x] What you are looking for skills wise
  - [x] Partner(s)
  - [x] Location
- [ ] Add project Card to website

**Comment by ExperimentsInHonesty** [comment]
This project card is ready to be added to the hackforla website

**Comment by heylittlehouse** [comment]
I created a pull request to add this card here: #141
