### ISSUE TITLE
Change redirects to <a> tags

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1321]
### Overview
Currently when we click on some buttons which are referenced via the files listed below. It seems they were using a redirection layout.... If I may ask.. why are we not just doing `<a href='link' target="_blank">text</a>` for those files, like we are doing for other external links? There are a few other places where we are redirecting people but not using the redirection layout. So I was just asking why we are using it in some places and not other places.. ? I have asked both @cnk and @drubgrubby and they don't know/aren't sure.

Went over this in meeting on tuesday.

### Action Items
- [ ] Get Product Approval @ExperimentsInHonesty 
- [ ] Replace the links used in the above files as a direct link
- [ ] Open into a new tab "_targe='blank'"
- [ ] Delete the necessary above files

### Resources/Instructions
- calendar.md
- conduct.md
- github.md
- meetup.md
- slack.md
- donate.md

**Comment by ExperimentsInHonesty** [comment]
@akibrhast We are using the redirect to be able to have urls that we can give people during onboard or in meetup.  E.G.

https://hackforla.org/slack
https://hackforla.org/conduct

<details>
<summary>Screenshot of the Meetup which has some of the redirect links in it</summary>

![Screen Shot 2021-03-25 at 9 06 59 PM](https://user-images.githubusercontent.com/37763229/112575701-0f923c80-8dae-11eb-84fd-bfb3abaef76d.png)

</details>

Are we closing this issue?

**Comment by akibrhast** [comment]
closing this issue after my conversation with @ExperimentsInHonesty .
Because the redirections are used such that it gives one the ability to write url redirects like the below example

- https://www.hackforla.org/slack/  which then redirects to https://hackforla-slack.herokuapp.com/
