### ISSUE TITLE
Address Security Messages in Github

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#133]
### Overview
Github is sending security messages for libraries that are no longer in use.  We need to make them stop

### Action Items
@thekaveman will write Github and ask them how to resolve permanently.

**Comment by thekaveman** [comment]
Message sent to GitHub support.

**Comment by thekaveman** [comment]
GitHub responded!

> It seems the vulnerability scanning job processed an older version of the repository's manifest files. Those files were deleted from the repository before the scan took place, but our process hadn't removed them from the scan, which caused the alert to generate for a file that no longer exists in the repository.
>
> Running scans on deleted manifest files is a bug on our end, and we're currently working on its resolution.

They have indicated they resolved the issue for this repository, and they're working on a general bug fix.

**Comment by thekaveman** [comment]
Closing for now, seems to be resolved.
