### ISSUE TITLE
Adjust styling of Getting Started page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1335]
### Overview
We need to adjust the styling of the Getting Started page, especially in mobile, so that it is consistent with other pages on the site and user-friendly

### Action Items
- [ ] Make sure all of these changes below will apply to both versions of the Getting Started page - getting-started.html and getting-started-with-video.html ('with video' version will be brought back as soon as we have self-onboarding added back in)
- [ ] Make ALL of the links on this page open in new tabs
- [ ] Make all of the steps subheadings ("Step 1: Onboard", etc.):
   - [ ]  In desktop: 24px font (instead of 25px) - use rem units
   - [ ] In mobile: 20px font - use rem units
- [ ] mobile: the header paragraph (.header-p) text should be left-aligned
- [ ] In mobile: Make the font of the questions in the accordion ("How do I raise my hand on zoom?" etc.) **18px font** (instead of 20px) - use rem units (but this is ONLY in mobile- in desktop it should stay the same)
   - [ ] This will affect other accordions on the site, which is fine. Double check the [2FA guide](https://www.hackforla.org/guide-pages/2FA) accordion in mobile to make sure it still looks good

### Resources/Instructions
[Getting Started Page
](https://www.hackforla.org/getting-started)
[2FA guide](https://www.hackforla.org/guide-pages/2FA) (to make sure accordion still looks good in mobile when changes apply here)

**Comment by qaz6209031** [comment]
I want to work on this issue !

**Comment by qaz6209031** [comment]
When you mention that make all the links open in the new tab, does is include the links on the top (Events Projects Press Join us...

**Comment by qaz6209031** [comment]
How do I change the different style for mobile and web, right now I make changes on  _getting-started-page.scss, does that apply on both web and mobile?

Updated: problem solved, now I learned to use media query

**Comment by daniellex0** [comment]
> When you mention that make all the links open in the new tab, does is include the links on the top (Events Projects Press Join us...

Sorry about the delayed response- no, please don't change anything in the navigation bar

Btw @qaz6209031 please assign yourself (on the top right of this issue) when you want an issue to be yours- instead of commenting 🙂. (I just did it for you)

Also, please make sure your PR is approved and merged before you assign yourself another issue next time. 

Thanks!

PS good job figuring out media query :)
