### ISSUE TITLE
Add card for South LA's Wednesday meetup

### ISSUE THREAD

**Issue by gitklu** [hackforla/website#134]
### Overview
Create new card on website to represent South LA's Wednesday meetup

### Action Items
Gather these items and attach them to this issue.  Notify @ExperimentsInHonesty when completed

- [ ] 600 x 400 image of sip and sonder
- [ ] Location

### Resources/Instructions
see https://hackforla.org for how the other hack nights look

**Comment by matikin9** [comment]
@ExperimentsInHonesty 

**Image:**
![sip-and-sonder](https://user-images.githubusercontent.com/1873072/62898793-3439bd80-bd0b-11e9-9d2e-02e5c62599c0.jpg)

**Details:**
South LA
Wednesdays at 6:00pm

Sip & Sonder
108 S Market St.
Inglewood, CA 90301
