### ISSUE TITLE
Project Card Update - BallotNav

### ISSUE THREAD

**Issue by tarang100** [hackforla/website#1341]
### Overview
We need to replace the current project card image with the image provided in the comment below

### Action Items

- [x] Replace the current image in the project file with the new image
- [x] Let BallotNav know that their issue can be closed: https://github.com/hackforla/ballotnav/issues/389

### Resources/Instructions
Current text in the project file: /assets/images/projects/ballot-nav.png
Replace with: /assets/images/projects/ballotnav.jpg
Where to find the project file: _projects/ballot-nav.md

**Comment by ExperimentsInHonesty** [comment]
![ballotnav](https://user-images.githubusercontent.com/37763229/113187783-1ab1f600-920e-11eb-9f4e-4f2b967c06eb.jpg)
