### ISSUE TITLE
Project Card Update - Open Community Survey

### ISSUE THREAD

**Issue by tarang100** [hackforla/website#1342]
### Overview

We need to replace the current project card image

### Action Items

- [ ]  Replace the current image in the project file with the new image

### Resources/Instructions

_Folder with the image_: /assets/images/projects/open-community-survey.jpg
_Where to find the project file_: _projects/open-community-survey.md

**Comment by Lol-Whut** [comment]
Please use this image from the following comment as mentioned by @ExperimentsInHonesty: 
https://github.com/hackforla/community-survey-nc-websites/issues/16#issuecomment-811292122
![image](https://user-images.githubusercontent.com/40847248/115491993-92c87600-a226-11eb-8685-f2e71505c93b.png)
