### ISSUE TITLE
Update Project Profile: Undebate

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#1345]
### Overview
As a product manager of Undebate I want my project's details to be up to date on the HackforLA website

### Project card
https://github.com/hackforla/website/tree/gh-pages/_projects_undebate.md

### Action Items

- [x] remove
   - [x] looking for
   - [x] Location
- [x] Change
   - [x] Status: completed

**Comment by GLRJr** [comment]
I made the changes to the undebated.md file, however while those changes are seen on the project page they are not being reflected on the project cards displayed on the homepage. contact me on slack to let me know how to change those, I could not find it.

**Comment by RobertaFricker** [comment]
Please put your request in the hfla-site channel.
