### ISSUE TITLE
We need to consolidate our filter list for technologies

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#1346]
### Overview
We need to have there only be one of any given technology showing in the filter at a given time, so that people can find all the projects having to do with any one technology at time.

### Action Items
- [x] Look at this list (https://github.com/hackforla/engineering/issues/7#issuecomment-806297796)
- [x] Find any project that is listing the technologies on the list in a way other than the above and list below the changes that need to be made (e.g., if they are using React.js, change to React.
- [x] Any projects that have the following things listed as technologies needs to have these moved to tools instead
   - [x] Google Docs (1)
   - [x] Google Docs (Doc, Sheet, Slide, Forms) (1)
   - [x] Google Sheets (1)
   - [x] HackforLA.org guides (1)

**Comment by daniellex0** [comment]
I believe this issue was closed accidentally (it hasn't been done yet), so re-opening

**Comment by qiqicodes** [comment]
@wendywilhelm10 Can you let us know your progress in regards to this issue? Thank you =]

Progress: I think I know what I need to change, so going ahead with what I think is correct.
Blockers: I ask Danielle if what I think needs to change is indeed correct.  I though she wrote this issue but Bonnie did.  Waiting to hear verification from Danielle about my assumptions.
Availability: I have time to work on this.
ETA: Depends on when I hear about my assumptions.

**Comment by daniellex0** [comment]
@wendywilhelm10 just responded to your question on slack, sorry about the delay!
