### ISSUE TITLE
Create project card for 311-data

### ISSUE THREAD

**Issue by gitklu** [hackforla/website#137]
### Overview
Provide collateral for the HackforLA website

### Action Items
- [x]   Gather items
  - [x]  600 x 400 image
  - [x]  Name of project
  - [x]  A blurb about your project
  - [x]  Links (website, github, etc.)
  - [x]  What you are looking for skills wise
  - [x]  Partner(s)
  - [x]  Location
- [ ]   Add project Card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples

**Comment by heylittlehouse** [comment]
I created a pull request to add the card here: #142
