### ISSUE TITLE
Write documentations for how to review PR's

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1374]
### Overview
We need some documentation about how to review pull requests on this project.

### Action Items
- [x] create a new wiki page about how to review pull requests
- [x] include the information in the resources/instructions section below
- [x] include screen shots and anything necessary to make things excruciatingly clear
- [x] clarify what squash and merge is and tell them NOT to press that button :))

### Resources/Instructions
How to look at a pull request and gather important information.
- Check if it is branched off the contributor's forked repo
<details>
    <summary>correct example</summary>

![Screen Shot 2021-04-07 at 7 20 57 PM](https://user-images.githubusercontent.com/53061723/113960027-a6142400-97d8-11eb-83c1-9562e06dcc1a.png)

</details>

- go over the tabs at the top. (Conversation, Commits, Checks, Files changed) 
- conversation should have an issue linked to it. (i.e. Fixed #issue_number)
- check out the issue and gain an understanding of what is being asked
- look at the files changed

How to pull to computer and test it out
- git commands to pull changes to computer
- developer tools for how to look at mobile, tablet, and desktop

How to review
- show where to find the review button
- show how to make comments on specific lines
- how to be courteous and encouraging, yet straightforward (maybe add this??)
- approve the PR or ask for changes

**Comment by jbubar** [comment]
@akibrhast, and @qiqicodes could you review this issue?

**Comment by akibrhast** [comment]
LGTM.

**Comment by qiqicodes** [comment]
Reviewed and edited, LGTM

**Comment by Aveline-art** [comment]
@jbubar Hi! I've written some scribbles as a draft, but before I do too much work, I'd like to know more about this wiki.

1. How long/thorough do you expect it to be?
2. Who is the intended audience?

**Comment by Aveline-art** [comment]
Progress: Currently working on first draft. About 50% complete.
Blockers: Waiting for answers to questions pertinent to the first draft (see above). Otherwise will continue complete first draft.
Availability: Will work on this for at least 3 days for 2 hours each.
ETA: Anywhere between 1-3 weeks.
Pictures: Not available for now.

**Comment by jbubar** [comment]
> 1. How long/thorough do you expect it to be?
However thorough you think it deserves is the ultimate answer... but the main things that it needs is
1. how to inspect the pr
2. how to pull it to your machine and look at it on localhost
3. how to review
   - do not squash and merge
   - request changes/approve 
   - how to comment on specific lines of code

> 2. Who is the intended audience?

The intended audience is the new developers on the team. we want new developers to be reviewing pull requests.

... 
use lots of pictures

**Comment by josiehandeveloper** [comment]
Hey Ava I created this google doc for myself, but I'm sure it can help others and this write up 
[Writing Reviews](https://docs.google.com/document/d/1jWjqWlgrZlFneD1h74vn-aqFjvtZCT9BySFMbEIIKPU/edit?usp=sharing)

**Comment by Aveline-art** [comment]
@josiehandeveloper This looks great! Would you happen to be okay with me lifting these images into the wiki? I was just starting to collect and include them!

**Comment by josiehandeveloper** [comment]
Yeah! feel free to take images

**Comment by Aveline-art** [comment]
After a week, I have completed a [first draft](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests)! (Horray!) I've polished it as much as I can, so I would appreciate any feedback.

For the person reviewing this, (perhaps @jbubar or @averdin2 or someone else?), can you let me know your thoughts on the following:

1. Are there further steps I can take to improve conciseness, clarity, and organization?
2. Do the steps make sense for our culture?
3. Is the language too dry/not dry enough?
4. Are any of the images unclear or confusing?
5. Anything else?

**Comment by Aveline-art** [comment]
* Progress: First draft is finished. Will wait for feedback before planning my next steps.
* Availability: Tues, Thurs, Fri night. Sat all day.
* ETA: Within a week after feedback.

**Comment by Aveline-art** [comment]
@jbubar I have made my final edits to the new wiki. Let me know if any further changes are needed, and if not, you are ready to close this issue!

Note: I could not drag and drop the images so I've added them to a directory in the wiki repo. As far as I can tell, the directory is invisible in the Github interface, but is viewable in a local repo. Is this an appropriate location to store the images or is there another preferred location?

**Comment by akibrhast** [comment]
@Aveline-art in regards to images, have you tried this?
https://docs.github.com/en/communities/documenting-your-project-with-wikis/editing-wiki-content#adding-images

**Comment by Aveline-art** [comment]
@akibrhast Yes, that is how the images were added to the wiki.

**Comment by josiehandeveloper** [comment]
Best wiki article I've seen!!! 5 STARS A++
