### ISSUE TITLE
Add 'how to install git' in the CONTIBUTING.md file

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1375]
### Overview
We need a sentence or two on "how to install git" in the beginning of the CONTRIBUTING.md readme.
This could be a link to the wikipage or a few sentences.

### Action Items
- [ ] Add a few sentences on how to install git if the contributor has not yet installed it
- [ ] include necessary links

### Resources/Instructions
[git installation documentation](https://github.com/git-guides/install-git)

**Comment by jbubar** [comment]
@RobertaFricker would you be interested in taking on this issue?

**Comment by RobertaFricker** [comment]
@jbubar As we agreed, we'll meet tomorrow to discuss the details of adding this to the CONTRIBUTING.md area.  
The following changes below address "Add a few sentences on how to install git if the contributor has not yet installed it" and
"Include necessary links."
I think the CONTRIBUTING.md should have a link that links to the instructions below.
Please advise the next step, thanks.

### How to Install Git
The next step is to install Git for Windows to your local machine, go to:
https://git-scm.com/download/win.
Note:  git-scm is a popular and recommended resource for downloading Git for Windows. The advantage of downloading Git from git-scm is that your download automatically starts with the latest version of Git included with the recommended command prompt, Git Bash (see Git Bash section below)
(For MacOS and Linux Users)
Go to https://github.com/git-guides/install-git, to install Git on MacOS or Linux systems.  
Confirm Git is successfully installed by typing git version from the command line prompt.

**Comment by RobertaFricker** [comment]
This issue is now in Google docs, https://docs.google.com/document/d/1VNtAWP4yFfad1cqoXv3a8bTwlf6gUNemdbWK89i0jk0/edit?usp=sharing

**Comment by jbubar** [comment]
Is that google document complete? Maybe after bonnie and the team look over it we can link to it in the contributing.md file.

``` diff
## Using Git

This section discusses some tips and best practices for working with Git.
+ If you have not installed git on your machine please review [this guide for first-time developers](https://docs.google.com/document/d/1VNtAWP4yFfad1cqoXv3a8bTwlf6gUNemdbWK89i0jk0/edit?usp=sharing)

### Making changes, committing and pushing

1. Generally changes start on your local clone of your fork of this repository, in your own branch.
```

**Comment by erikaBell** [comment]
@RobertaFricker, thanks for this in-depth file that you wrote. It inspired Akib to make these changes, to the existing [Contribution page](https://github.com/akibrhast/website/blob/gh-pages/CONTRIBUTING.md). 

We were thinking we could refine your google doc to be a shared doc. for onboarding of all H4LA teams. 
We would love your opinion on improving our own documentation as well.

**Comment by qiqicodes** [comment]
This issue is similar to the following: 
https://github.com/hackforla/website/issues/1390#issue-855156065
