### ISSUE TITLE
Consolidate Raw Colors To Standardized Color Variables

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1378]
### Overview
 Currently there are quite a few places in the code base where raw colors are being used. These needs to be consolidated into variable names as much as possible such that we can have a dictionary of HFLA acceptable color variable names. An effort to do this has already been started by the design team as part of the HFLA [Design Systems](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) as well as by developers under the following [folder](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss)

### Action Items
<sub>Please ensure to tick of the checkboxes as you complete each task</sub>
- [x] A developer, Make a table of all the raw colors that are currently being used, the pages they are being used in and screenshots of rendered color on the site.
- [x] Post the table as a comment on this issue
- [x] Rope in someone from the design team to discuss naming conventions 
- [x] After the above steps has been completed make a PR that implements the above changes by removing all raw colors as necessary and replacing them with variable names
- [x] Complete the additional changes outline [here](https://github.com/hackforla/website/pull/1917#pullrequestreview-708614012)

### Resources
Parts of this issue had already been previously completed. The remaining steps are outlined above in unchecked action items. To see what has already been done, please see [this pull request](https://github.com/hackforla/website/pull/1917).

**Comment by qiqicodes** [comment]
@Lol-Whut Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by Lol-Whut** [comment]
Progress: Partway through assembling a list of all instances of raw colors (see link below for progress)
Blockers: Taking a while since we have several scss files
Availability: Much free-er this week!
ETA: Will finish assembling instances in next two days and loop in a designer to choose variable names; then will have a better understanding of how long it will take to cover the rest of the issue.
Link: https://docs.google.com/spreadsheets/d/1O5ooA7dcfi9iKITGTUN3uIe5dvToge3c-PaXJEO8fLc/edit?usp=sharing

Question: There are a few instances where we have a pre-existing variable for a raw color; should I fix those as I go or create a new issue?

**Comment by qiqicodes** [comment]
@Lol-Whut Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by qiqicodes** [comment]
> Progress: Partway through assembling a list of all instances of raw colors (see link below for progress)
> Blockers: Taking a while since we have several scss files
> Availability: Much free-er this week!
> ETA: Will finish assembling instances in next two days and loop in a designer to choose variable names; then will have a better understanding of how long it will take to cover the rest of the issue.
> Link: https://docs.google.com/spreadsheets/d/1O5ooA7dcfi9iKITGTUN3uIe5dvToge3c-PaXJEO8fLc/edit?usp=sharing
> 
> Question: There are a few instances where we have a pre-existing variable for a raw color; should I fix those as I go or create a new issue?

@Lol-Whut What do you have in mind for fixing the color variables? We can work together with the UI/UX team on naming the variables.

**Comment by jbubar** [comment]
@Lol-Whut Could you share your progress on this so that we can give it to a new contributor?

Thanks for your contributions

**Comment by Sihemgourou** [comment]
@jbubar, Is @pascuas still on this issue ?

**Comment by aliibsin** [comment]
@jbubar will reach out to @pascuas on slack to see if he's still working on this issue

**Comment by Sihemgourou** [comment]
Thanks ! And p'ease remove their assignments if they don't answer anymore :) 

If so, also put the issue back to the prioritized backlog

**Comment by pascuas** [comment]
@Sihemgourou my apologies! I am.

**Comment by Sihemgourou** [comment]
Perfect  ! 
Please add update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by pascuas** [comment]
Will reach out to a member to clarify what is needed for this issue.
Availability: Evenings this week.
ETA: End of week.

**Comment by daniellex0** [comment]
@pascuas Let me know if you'd like to meet about the colors btw! I can help clarify what the next steps are :)

**Comment by Sihemgourou** [comment]
@pascuas is actively working on this issue.

**Comment by pascuas** [comment]
1. Was able to get through some changes of variable names.
2. No blockers right now.
3. Will have more time this week.
4. Goal is by the end of the week.

**Comment by pascuas** [comment]
Just finished this earlier today and created a pull request.

**Comment by Aveline-art** [comment]
* Progress: Made the pull request. Am awaiting review.
* Blockers: The pull request needs someone from the design team to give input.
* Availability: Random time here and there
* ETA: Unsure, but will be done within a day after the design team gets back to me.

**Comment by Aveline-art** [comment]
* Progress: Done, except issues need to be made
* Blockers: None so far
* Availability: 2 hours
* ETA: By the end of today
