### ISSUE TITLE
Redesign the "What is Hack for LA" slideshow

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1379]
### Overview
We need to redesign and rework the "What is Hack for LA" slide deck to be more visually organized and appealing.

### Action Items
- [x] Discuss potential changes with Bonnie
- [x] make redesign changes to the slide deck

### Resources/Instructions
["What is Hack for LA" slide deck - edited version](https://docs.google.com/presentation/d/11tuskl2WL37Nz_xzFEa-5cHNFheAsSmm7XwTeC4BXzU/edit#slide=id.gce5c497f27_0_588)

**Comment by daniellex0** [comment]
@ashleylin1 update from 4/4:

> https://docs.google.com/presentation/d/11tuskl2WL37Nz_xzFEa-5cHNFheAsSmm7XwTeC4BXzU/edit?usp=sharing
> Progress: Edited all slides for Olivia's "What is HackforLA" slide

> need feedback on Olivia's "What is HackforLA" slide
> Availability: Friday, Saturday, Sunday
> ETA: 1 week

**Comment by daniellex0** [comment]
@ashleylin1 update from 4/5:

> Progress: for the "What is HackforLA" slide, I...

> reviewed both slides with Bonnie and Danielle
got feedback and changed the background so the logo fits within view
reuploaded the logo and colors for the platform slide and its subsequent slides
added icons to the communities of practice slide
changed text-align and logo for all project slides
changed color of dividing lines for all project slides to be lighter

> Blockers:
need feedback on Olivia's "What is HackforLA" slide
Availability: Friday, Saturday, Sunday
ETA: 1 week

**Comment by qiqicodes** [comment]
@ashleylin1 can you give us an update on your progress? Thank you =]

https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#step-8-status-updates

**Comment by ashleylin1** [comment]
Progress: 
- Made changes to the slideshow based on feedback from Bonnie and Danielle
- slide was shared with Olivia for feedback
- moved to UX/UI folder on Google Drive

Next steps: waiting to receive feedback 
Blockers: none
Availability: after 5/14

**Comment by qiqicodes** [comment]
@ashleylin1 Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by daniellex0** [comment]
This is completed- closing issue!
