### ISSUE TITLE
CONTRIBUTING.md needs info about Command Line Shells and Text Editors

### ISSUE THREAD

**Issue by RobertaFricker** [hackforla/website#1390]
### Overview
CONTRIBUTING.md file needs to include information regarding the requirement to use both a Command Line Shell and a Text Editor app.  The Text Editor app is required to create text files and perform Git merge and commit commands.

### Action Items
Add the following text under "Step 6: Work on an issue using git"

**Command Line Shell and Text Editor**

In order to work on an issue, you will need to use both a Command Line Shell such as Git Bash in addition to a Text Editor like VS Code to create Git commit and merge messages. 
The default Text Editor for Git is Vim for Mac, Linux, and Windows (if Windows has Git Bash installed) systems. Vim is designed to support the command line / terminal interface.
If you already have a Text Editor installed, Git Bash should default to it.  
In Git Bash type :
git config core.editor    or   grep editor ~/.gitconfig to view your current Text Editor.
If you want to select a different Text Editor, go to https://docs.github.com/en/github/getting-started-with-github/associating-text-editors-with-git for various recommended options.  This includes instructions for configuring your preferred Text Editor.

### Resources/Instructions
https://www.earthdatascience.org/workshops/setup-earth-analytics-python/text-editors-for-science-workflows/, sections "What is your Default Text Editor?" and "The Vim Text Editor"
https://docs.github.com/en/github/getting-started-with-github/associating-text-editors-with-git

**Comment by RobertaFricker** [comment]
This issue is now in Google docs, https://docs.google.com/document/d/1VNtAWP4yFfad1cqoXv3a8bTwlf6gUNemdbWK89i0jk0/edit?usp=sharing

**Comment by akibrhast** [comment]
This a start of restructuring the contributing . Feel free to use this and continue off of it. @averdin2 @RobertaFricker @alyssabenipayo @jbubar 
https://github.com/akibrhast/website/blob/gh-pages/CONTRIBUTING.md

**Comment by qiqicodes** [comment]
@daniellex0 @ruqpyL2 @qiqicodes are working on restructuring the wiki. Here is plan:
https://docs.google.com/spreadsheets/d/1ZfLAUfpxjblvfobdewQ0SkQ9I2HqheD56c5ogrcYdiA/edit#gid=534478216

@akibrhast Here is Akib's commit on CONTRIBUTING.md
https://github.com/akibrhast/website/blob/gh-pages/CONTRIBUTING.md

@RobertaFricker @averdin2 @alyssabenipayo @jbubar will meet for further documentation detail this week.

**Comment by abenipa3** [comment]
We reviewed the documentation up to the _Clone the forked repository_ section and drafted a pull request #1471 today

We plan to meet and continue reviewing next week.

**Comment by qiqicodes** [comment]
@averdin2 @alyssabenipayo @jbubar Let us know your progress in regards to the documentation, thank you =]

Progress:
Blockers:

**Comment by RobertaFricker** [comment]
@averdin2 @alyssabenipayo @jbubar 
I have removed myself from this assignment due to I've already put my document in Google docs for reference.  It contains all of the pertinent information that I feel is necessary to set up a successful development environment.  Here it is:
The Dev_Setup_Hackforla document is now in Google Docs share by everyone and here's the link:  https://docs.google.com/document/d/1VNtAWP4yFfad1cqoXv3a8bTwlf6gUNemdbWK89i0jk0/edit?usp=sharing, thanks.

**Comment by averdin2** [comment]
My updates to the Contributing doc: https://github.com/hackforla/website/pull/1471#issuecomment-831615556

**Comment by josiehandeveloper** [comment]
If you don't already have a text editor feel free to download VS Code

**Comment by averdin2** [comment]
In regards to this issue, we decided not to include anything regarding command-line shells at this time. I added a brief recommendation to use VS Code at the top of the contributing file. See the screenshot below for that specific update.

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/10714770/119273741-28a64680-bbc1-11eb-899e-f9a10b54cfd5.png)
</details>

**Comment by akibrhast** [comment]
@averdin2 @jbubar Can the linked PR be removed from draft mode and merged yet ... ?

**Comment by averdin2** [comment]
@akibrhast Yeah, I think it can be removed from draft and merged. I'll remove it from draft.

**Comment by jbubar** [comment]
There is a pr for this. awaiting review
