### ISSUE TITLE
Update the Join page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1392]
### Overview
We need to update the Join page so that it will be ready to go live

### Action Items
- [x] In the "Advise Us" page card, remove step 3 and replace step 2 with the text below (under Instructions)
- [x] Remove the links from all of the role titles in the "Volunteer with Us" page card (they are linked to filter results that are not up-to-date)

### Resources/Instructions
[Join page](https://www.hackforla.org/join)

Updated "How to get involved" section should look like this now (new step 2 with # admin bolded, no step 3):

**EDIT**: Sorry I know this is inconsistent with the screenshot below, but can both mentions of slack actually be capitalized (Slack)? It seems like it's supposed to be capitalized based on googling around..

<img width="583" alt="Screen Shot 2021-04-10 at 9 53 50 PM" src="https://user-images.githubusercontent.com/67400366/114293086-15dc1600-9a48-11eb-9840-0f66942395f4.png">

Updated "Volunteer with Us" page card should look like this now (no links):

<img width="609" alt="Screen Shot 2021-04-10 at 9 53 29 PM" src="https://user-images.githubusercontent.com/67400366/114293088-196f9d00-9a48-11eb-89b1-6542c4075de6.png">

**Comment by danyc23** [comment]
The requested changes are done.
 
![Screen Shot 2021-04-14 at 12 18 20 PM](https://user-images.githubusercontent.com/42159475/114767055-085eae80-9d1c-11eb-92e0-408d0bde5ce5.png)
