### ISSUE TITLE
Evenly align the Events page schedule times and days

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1393]
### Overview
We need to edit the Events page schedule to match the Figma file and to look more visually aligned

### Action Items
- [ ] View and follow the instructions/notes for editing the Events page schedule in the [Events page figma file, in a purple rectangle](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94)

### Resources/Instructions
[Events Page](https://www.hackforla.org/events)
[Figma- Events Page edit notes](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94) (find detailed notes in purple rectangle, on bottom right of file)

**Comment by qiqicodes** [comment]
@sanchece can you update us with your progress? Thank you =]

https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#step-8-status-updates
