### ISSUE TITLE
Update Project Profile: [Civic Opportunity]

### ISSUE THREAD

**Issue by Arjayellis** [hackforla/website#1395]
### Dependency
Review and updates from Project PM

### Overview
As a product manager of Civic Opportunity, I want my project's details to be up to date on the HackforLA website

### Project card
https://github.com/hackforla/website/tree/gh-pages/_projects/civic-opportunity.md

### Action Items
- [ ] Civic Opportunity Team Leadership
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [ ] leadership
      - [x] links
         - [x] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] looking
      - [ ] technologies
      - [x] location
      - [ ] partner
      - [ ] tools
      - [x] status

### Resources
![Civic Opportunity Project Logo](https://user-images.githubusercontent.com/78316116/114131827-278eb380-98b8-11eb-9562-a43007a3d3c6.png)

**Comment by Arjayellis** [comment]
Name: Randall Ellis
Role: Product Manager
Slack Member ID: U018TL37XJ6
GitHub Handle: Arjayellis

**Comment by alexilee** [comment]
Name: Alex Lee
Role: Product Manager
Slack Member ID: U01KDATDLLQ
GitHub: alexilee

**Comment by pawan92** [comment]
Name: Pawan Murthy
Role: Product Manager
Slack Member ID: U01FMQTN8MU
GitHub: pawan92

**Comment by ExperimentsInHonesty** [comment]
Remove partner

**Comment by ExperimentsInHonesty** [comment]
Tools: Wiki, Google Docs, Sheets, Forms, Zapier

**Comment by patrickm-tan** [comment]
Name: Patrick Tan
Role: UX Researcher
Slack Member ID: U01RW1C1CV8
GitHub: patrickm-tan

**Comment by theetank** [comment]
Name: Tania Khan
Role: UI/UX Designer 
Slack Member ID: U01LF2MSSHG
GitHub: TaniaKhan04

**Comment by JC789** [comment]
Name: Jayashree Chauhan
Role: UX Designer Researcher
Slack Member ID: U01NZPZ4Y2E
GitHub: JC789
