### ISSUE TITLE
UI/UX CoP & HfLA Site UX Meeting Agenda

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1402]
### Overview
The agenda for this week's discussion between Bonnie, Danielle, and Tan about the UI/UX Community of Practice and HackforLA.org website UI/UX work

#### Agenda

12:00-12:15pm
- Community of Practice meeting review
- New Volunteer Outreach

12:15-1:00pm
- Onboarding slideshow updates
- Guide annotation colors

**Comment by ExperimentsInHonesty** [comment]
This format for agendas is no longer used, closing issue
