### ISSUE TITLE
Add extra word in homepage header body text

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1414]
### Overview
We need to add the word "full" in the homepage header body text because since it was recently split into two paragraphs, the first line stands out more and comes off too blunt/critical of LA

### Action Items
- [x] Add the word "full" between "its" and "potential" in the homepage header body text (first paragraph)

### Resources/Instructions
[Homepage](https://www.hackforla.org/#)
[HfLA Site Architecture
](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

<img width="500" alt="Screen Shot 2021-04-18 at 3 29 48 AM" src="https://user-images.githubusercontent.com/67400366/115142636-bf4a7b00-9ff7-11eb-9e76-e2ac8a62f083.png">

**Comment by RobertaFricker** [comment]
Added the word "full" to _includes/hero.html page per screenshot below:
![image](https://user-images.githubusercontent.com/81199122/115767039-86930480-a35d-11eb-9f28-43f654f06ce5.png)
