### ISSUE TITLE
Adjust homepage filter tags

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1415]
### Overview
We need to adjust the homepage filter tags to make them more consistent with the original Figma design, make the 'looking' tags more understandable, make the font size more accessible, and standardize the class naming according to a discussion about this component's name at a recent dev meeting

### Action Items
- [x] Review the [Figma design for the filter tags (in purple rectangle towards the left)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205)
- [x] Change the " looking: " in the filter tags to " role: "  (i.e. instead of "Looking: PM" it should say "Role: PM." However, please don't change the "Looking" title in the filter dropdown itself
- [x] Make the margin between filter name and number of selected filters ( i.e. Status (2) ) same as in the Figma
- [x] Change the color of 'Clear All' to its color in Figma
- [x] Change the font size of the filter tags to their font size in Figma (make sure the text is still vertically centered on the tag)
- [x] Change the margin between the filter tags to same margin as Figma (or close)
- [ ] Change the CSS class name to '.filter-item' instead of .btn--current-projects-filter-tag (.filter-item name was voted/agreed on at a dev meeting, and this isn't technically a button in the design system). 
   - [ ] Figure out how to make this function similar to a button (clickable with pointer) without using button code. See for reference [Adidas filter tags](https://www.adidas.com/us/women-shoes) with similar functionality, but it's a div

### Resources/Instructions
- [Homepage](https://www.hackforla.org/#)
- [Figma design for the filter tags (in purple rectangle towards the left)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205)

<details>
<summary>Design</summary>
<br>
<img width="550" alt="Screen Shot 2021-04-18 at 4 07 47 AM" src="https://user-images.githubusercontent.com/67400366/115143366-ae036d80-9ffb-11eb-8e2c-76fc5783d497.png">
</details>

**Comment by akibrhast** [comment]
>  Change the " looking: " in the filter tags to " role: " (i.e. instead of "Looking: PM" it should say "Role: PM." However, please don't change the "Looking" title in the filter dropdown itself - @daniellex0 

' However, please don't change the "Looking" title in the filter dropdown itself '  ->  @daniellex0 I agree with your initial point about changing it to role. Since that would be consistent with what we have on wins page as well. I was wondering why we shouldn't change `Looking` to `Role` . Wouldn't that be more consistent across the entire site, and cause less confusion vs a mix between role,links in different places. .... ?

**Comment by Lol-Whut** [comment]
Leave "Looking" rather than switch to "Roles" (discussed in dev meeting on 4/20/2021)

**Comment by ExperimentsInHonesty** [comment]
@qiqicodes 
Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by qiqicodes** [comment]
Progress: Features added, filter list currently is missing due to having the same class name as item in filter list dropdown

Blockers: same name as filter list

Availability: Open Tuesday night and Saturday.

ETA: Merge PR with with functional checked items tonight

**Comment by akibrhast** [comment]
@qiqicodes to create new issues that addresses this

>  Change the CSS class name to '.filter-item' instead of .btn--current-projects-filter-tag (.filter-item name was voted/agreed on at a dev meeting, and this isn't technically a button in the design system).
>  Figure out how to make this function similar to a button (clickable with pointer) without using button code. See for reference Adidas filter tags with similar functionality, but it's a div

And remove the above item from this issue. This is going to clear up her blockers on the currently drafted PR
