### ISSUE TITLE
Finish dev documentation of Design System

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1416]
### Overview
We need to complete the developer-facing documentation of the design system so that developers can easily pickup how and when to utilize reusable components

### Action Items
- [x] Wiki files and check if the flow makes sense
   - [x] https://github.com/hackforla/website/wiki/Standardized-Components
   - [x] https://github.com/hackforla/website/wiki/How-to-create-a-page-on-Hack-for-LA-website
   - [x] https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture#styling-files
- [x] SCSS files - document clearer if needed
   - [x] https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_buttons.scss
   - [x] https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_cards.scss
   - [x] Color variable/components
   - [x] Typography class
- [x] Figure out how to link GitHub SCSS file to the corresponding Figma component
- [x] Create checklist
   - [x] https://docs.google.com/document/d/1jQ9C52jfLPztB3hky01W5za8eGydxP7lnudCR64eXkw/edit?usp=sharing
   - [x] Figure out what is redundant and the priority of what will be standardized in the near future
   - [x] https://github.com/hackforla/website/tree/gh-pages/_sass
- [x] Figma, Style Guide - Start Here, Dev
   - [x] https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3

### Resources/Instructions
[Design System on Figma
](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)[Standardized Components wiki](https://github.com/hackforla/website/wiki/Standardized-Components)
[How to create a new page wiki](https://github.com/hackforla/website/wiki/How-to-create-a-page-on-Hack-for-LA-website)

**Comment by daniellex0** [comment]
@daniellex0 , @qiqicodes , and @ruqpyL2 are working on this

**Comment by qiqicodes** [comment]
Progress: restructuring wiki navigation by categorizing. rewriting design component documents. 

Blockers: @daniellex0 @ruqpyL2 @qiqicodes are meeting this week. Loop in  @akibrhast when the meeting is happening. 

ETA: TBD

**Comment by qiqicodes** [comment]
Progress: trying out UI component libraries, such as storybook, styleguidist, etc... to see which one fits our needs best
Blockers: need to arrange a meeting to discuss the tradeoffs

**Comment by qiqicodes** [comment]
Progress: Same progress
Blockers: Likely we will meet next week to discuss the tradeoffs

**Comment by daniellex0** [comment]
Progress: Heard about different way to approach wiki reorganization from Bonnie, but waiting for buy-in from dev team. Still figuring out feasibility of Storybook/Styleguidist vs. dedicated web page for component documentation
Blockers: Busy week for everyone

**Comment by daniellex0** [comment]
Progress: Moving forward with wiki reorganization and reformat. Still determining whether to have dedicated web page for component documentation
Blockers: Limited time
Next steps: Meeting this week about stylebook, move forward with making updates to wiki

**Comment by daniellex0** [comment]
Progress: Figured out that can use expandable arrows for wiki sidebar organizations. Met about Storybook, which will be way too difficult to implement without React (let alone with). Dedicated web page for component documentation looking like best option right now.
Blockers: Limited time
Next steps: Move forward with making updates to wiki

**Comment by daniellex0** [comment]
Progress: Got approval for dedicated web page for component documentation, and got approval (with a few edits) from Bonnie and devs for wiki reorganization. 
Next steps: Implement updates to wiki. Design dedicated webpage for documenting components and have it developed.

**Comment by Sihemgourou** [comment]
Hey @daniellex0, should we start the implementation of the design system in the code base ? we can already start with the validated part right ?

**Comment by daniellex0** [comment]
Hey @Sihemgourou , some of it is already implemented! For example buttons and page cards, which are the most common reusable components throughout the site, are already standardized. The other big piece left is standardizing headings, and I discussed this with Akib yesterday about how to have developers help with that. But yes, there are some more pieces that need to be implemented 👍

**Comment by akibrhast** [comment]
@daniellex0 What is the next step that developers can take to help with that?

**Comment by Sihemgourou** [comment]
I am going to create an issue about that

**Comment by csseu** [comment]
1. Have all go-aheads now to finish wiki
2. My job
3. This weekend
4. This weekend

**Comment by Sihemgourou** [comment]
@ruqpyL2 this issue is about the design system, your answer is about the wiki, do you think the two issues are interdependent ?

**Comment by csseu** [comment]
Yes, at the start of the project we decided that wiki should clearly point
to the design system. Since the wiki is/was a hot mess, that would have
been difficult. So organizing the wiki was the first phase of making sure
folks could eventually find the design system.

**Comment by daniellex0** [comment]
Progress: Designing component library webpage that developers will be able to reference. Met with interested developers who will be able to help implement this. 
Blockers: None
Availability: flexible
ETA: 1 week (design portion of component library webpage)

**Comment by daniellex0** [comment]
Progress: Met with Kristin about component library webpage and she designed a great mockup for component layout. I will implement the design on the rest of the components and send the page to development. Will coordinate meeting with more interested developers on the team to discuss implementing the component library webpage.
Blockers: None
Availability: flexible
ETA: 3 days (design portion of component library webpage)

**Comment by daniellex0** [comment]
Progress: Met with developers on the team to discuss implementing the component library webpage and get feedback on designs. Am currently implementing edits and finalizing the design to send off to developers by tonight.
Blockers: None
Availability: flexible
ETA: today

**Comment by daniellex0** [comment]
Progress: Finished designing dedicated webpage for components and met with developers to discuss and get more feedback. Sarah is now in charge of implementing the designs, and once she builds the structure will assign others. Adam is in charge of assigning people to standardize components as she moves along.
Remaining step: I need to finish descriptions in component webpage, and wiki page encouraging to use the component library
Blockers: None
Availability: flexible
ETA: 7/22
