### ISSUE TITLE
How to grab images in liquid jekyll

### ISSUE THREAD

**Issue by erikaBell** [hackforla/website#1418]
### Overview
How to grab images from a folder, and iterate through them
How to take the image names and use it for alt text

### Action Items

- [ ] research how to do this in Liquid Jekyll
- [ ] implement this
 
### Resources/Instructions
[Jekyll Docs](https://jekyllrb.com/docs/)

Good points of contact for help: @akibrhast @erikaBell @jbubar 

_If you need to reach out_: sharing any useful documents you've come across while researching would be helpful for us. So please add them in a comment.

**Comment by akibrhast** [comment]
```
{% for image in site.static_files %}
    {% if image.path contains 'images/slider' %}
        <img src="{{ site.baseurl }}{{ image.path }}" alt="image" />
    {% endif %}
{% endfor %}
```
