### ISSUE TITLE
Add badges to the wins overlay

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1425]
### Dependency
#1313

### Overview
Redesign the win's page overlay to include the badges

### Action Items
- [ ] redesign the wins page overlay to match the figma (in blue rectangle)
- [ ] get the icons from the win icon object
- [ ] include the text of the win
- [ ] style it to look like the figma (in blue rectnagle)

### Resources/Instructions
[figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) (in blue rectangle)

**Comment by erikaBell** [comment]
Going smoothly. I've been combining this ticket with wins mobile page ticket, since it was closely related anyway. Just have one more thing to do for mobile view. Have reached out to @jbubar for a bit of direction and am waiting to hear back.
