### ISSUE TITLE
Program areas page: Fix design and alignment of project mini-card 

### ISSUE THREAD

**Issue by Lol-Whut** [hackforla/website#1426]
### Overview
Fix design and alignment of project mini-card such that it matches the Figma design

### Action Items
- [ ] Fix design and alignment of project mini-card (reference the Figma page)

### Resources/Instructions
Figma : https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website

**Comment by danyc23** [comment]
Blockers: Haven't find any blockers yet.
Availability: Monday and Thursday.
ETA: 27/04/2021.
