### ISSUE TITLE
Program areas: Add join a project section right above the footer 

### ISSUE THREAD

**Issue by Lol-Whut** [hackforla/website#1427]
### Overview
Add join a project section right above the footer on the Program Areas page as per figma specs

### Action Items
- [ ] Add join a project section right above the footer (reference the figma design linked below)

### Resources/Instructions
https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4452%3A21046
https://www.hackforla.org/program-areas.html

**Comment by averdin2** [comment]
@GLRJr The button in question is for the join us page

**Comment by qiqicodes** [comment]
@GLRJr Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by GLRJr** [comment]
I'm working o  this this today, I'll prolly have it finished by this
afternoon.

**Comment by GLRJr** [comment]
I need some help with this

Progress: all the parts are there, however, I'm having trouble converting the Figma css over to HTML

Blockers: I need help with Figma.

Availability: I can work on this anytime tomorrow before 7pm, or during the week after 5pm

ETA: if I can get unblocked this could be finished tomorrow.

Picture:
![image](https://user-images.githubusercontent.com/29311777/118383360-dad28280-b5b1-11eb-8c27-cbf11f2c1c13.png)

**Comment by wendywilhelm10** [comment]
How's your progress coming along?  @GLRJr

**Comment by GLRJr** [comment]
I need some help with this

Progress: I figured out the problems with the CSS but I'm having trouble with the font

Blockers: the font isn't the the same even tho the code is.

Availability: just contact me but anytime after 5

ETA:It will be done when ever the problem is solved

Picture:
![image](https://user-images.githubusercontent.com/29311777/119744281-82687400-be40-11eb-8b23-0136ff3fa98f.png)

**Comment by Sihemgourou** [comment]
@GLRJr Your PR seems to have an answer, did you check it ? 
Please add update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by GLRJr** [comment]
made suggested changes updating pull request for feedback
![image](https://user-images.githubusercontent.com/29311777/122477336-6312c180-cf7c-11eb-8f57-42b95dcaa549.png)

**Comment by jbubar** [comment]
We had to revert the pr. sorry Gary

**Comment by GLRJr** [comment]
All good, I just talked with Danielle and we made adjustmets the footer, so
the code is good to go. If you guys want to meet up and fix the merge let
me know

**Comment by GLRJr** [comment]
I created a new branch, moved my code over, here are screen shots of the new branch running in Docker:
![image](https://user-images.githubusercontent.com/29311777/125533773-49ae1067-6c48-4bba-94ef-706aa5b91dae.png)
![image](https://user-images.githubusercontent.com/29311777/125533916-06ef7089-df89-423a-a255-58641408be63.png)
