### ISSUE TITLE
Wins page: don't allow comma removal on "Other"

### ISSUE THREAD

**Issue by erikaBell** [hackforla/website#1439]
### Overview
The wins data needs to have all comma's `split`, except for answers under the "Other" category of the wins form.
PR #1437

<details>
<summary>Comma separation issues in the "Other" category</summary>

<img width="176" alt="Screen Shot 2021-04-23 at 8 51 50 AM" src="https://user-images.githubusercontent.com/67438372/115900167-7f7afd80-a414-11eb-939a-a139d82cfcd0.png">
<br>
<br>
<img width="250" alt="Screen Shot 2021-04-23 at 8 51 59 AM" src="https://user-images.githubusercontent.com/67438372/115900179-83a71b00-a414-11eb-8c30-1c9e4e5547f1.png">

</details>

### Action Items

- [ ] Keep comma's in tact for the string value received under "Other" in the [wins form ](https://docs.google.com/forms/d/e/1FAIpQLSdF0MgS-M_Soi77qTp-MNfxMGqq85yqsHwvfHDngHAMyDQ8uQ/viewform)<br>(e.g. `"...events, community, and projects"` _instead of_ `"...events"`        `"community"`        `"and projects"`)<br><br>
- [ ] Ensure that any comma's in a string value, outside of the "Other" category, continue to be split

### Resources/Instructions
Issue #1313 
Issue #1431
`wins.html `
`wins form and wins form data`
Figma Design, [refer to blue rectangle](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0)

People to contact if needed: @jbubar @erikaBell

**Comment by jamesberke** [comment]
I began work on this issue by creating a new local issue branch from the latest commit in the hackforla/wins-feature-1 branch. If anyone else has to contribute to a branch other than gh-pages, the easiest way to achieve this is finding the hash of the most recent commit in the desired branch and creating a new local branch based off that.

command line example: git checkout -b wins-comma-fixes 72f2cc45f48d8f94a8f5907309de845d6ba2c609

command line format: git checkout -b {NEW BRANCH NAME} {DESIRED COMMIT HASH}

**Comment by qiqicodes** [comment]
@jamesberke  Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by jamesberke** [comment]
Progress: Will be done by EOD 5/16/21
Blockers: Needed to pull from new branch to use the Icons
