### ISSUE TITLE
Implement a logging system for all hfla github actions

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1445]
### Overview
As a member of the website team, we need a system that allows us to track GitHub action logs for an extended amount of time, beyond GitHub's 90 day allowance.

### Action items

- [ ] Create some sort of system that allows logging of [Github actions logs](https://github.com/hackforla/website/actions) for an extended amount of time.
  - [ ] The logs should be stored in a .txt file in a directory called '/logs' which is added to .gitignore
  - [ ] The log needs to have a one to one correspondence with the GitHub actions logs. This means that all information logged by GitHub needs to also be logged in this system. (this includes time stamps and information about the triggers)
  - [ ] The only exception to the above is the code that is run. However, the name of the GitHub actions file should be in the log.

### Resources/Instructions
If you have trouble starting this project, you might start with implementing the log with a [GitHub action](https://docs.github.com/en/actions). The workflow_run trigger seems very promising if this is the route you want to take.

As this issue is fairly large, you might have a lot of trouble, so please reach out! Important things to keep in mind when designing this is that this is made for the team. Be conscious of how the logs are formed and formatted, so that they would be useful for the team! You might also want to improve upon the action items above (perhaps a way to clear the logs?). If you dare to challenge yourself, be sure to share that intention with the team! We love to hear your ideas.

#### Some useful links
[Keeping your GitHub Actions and workflows secure: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[Storing workflow data as artifacts](https://docs.github.com/en/actions/guides/storing-workflow-data-as-artifacts)
[GitHub GraphQL](https://docs.github.com/en/graphql)

**Comment by akibrhast** [comment]
To discuss with @Aveline-art

**Comment by Aveline-art** [comment]
Design/Research questions:
- [x] Where and how will the information be stored?
- [x] What ways are there to listen for the initiation or completion of a GitHub action?
- [x] What information has to be part of the log?
- [x] Who is the end user of the logging system?
- [x] What does the current logging system lack that this needs to address? Answer: The current logging system only preserve logs for the last 3 months. It should preserve logs for over that amount.

Design criteria:
**TBD.**

**Comment by akibrhast** [comment]
Discussed with @Aveline-art  and added details in the main body.

**Comment by ExperimentsInHonesty** [comment]
This issue needs a rewrite on the top, to be in the format of all our other issues
```
 ### Overview
 User story (as a ____ I need to do _____ for _____ reason)

### Action Items
- [ ] thing 1
- [ ] thing 2

### Resources/Instructions
Links that will be useful
```

**Comment by Zak234** [comment]
Still working on the Github action. Experimenting with Javascript and Graph Ql. Available basically anytime. ETA, hopefully one week.

**Comment by Zak234** [comment]
Talked with Ava and it was decided that this issue should be closed due to its complexity and lack of benefits from completion. In case of being opened in the future, using REST API to download job logs seemed to be the most promising avenue although large amount of data processing would need to be done to remove the Github action code from the logs and get the data in a more readable state.

**Comment by ExperimentsInHonesty** [comment]
Wiki related to this issue https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Not-Implemented
