### ISSUE TITLE
Create project card for the Not Today project.

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#145]
### Overview
Provide collateral for the HackforLA website

### Action Items
- [x]   Gather items
  - [x]  600 x 400 image - to be provided by @myastark 
  - [x]  Name of project
  - [x]  A blurb about your project
  - [x]  Links (website, github, etc.)
  - [x]  What you are looking for skills wise
  - [x]  Partner(s)
  - [x]  Location
- [x]   Add project Card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples

**Comment by ExperimentsInHonesty** [comment]
Name of Project: Not Today: Self-Defense Against Suicidal Thoughts
Project blub: NotToday is a mobile app for people who suffer from chronic suicidal ideation (thoughts).  It allows people to time-shift their desire to live across suicidal/non-suicidal dissociated mental states.
Link: Github https://github.com/hackforla
 What you are looking for skills wise: Flutter, Mobile Development UI/UX, Empathy and sensitivity with subject material and end users.
Partners: Seeking
Location: Santa Monica

**Comment by myastark** [comment]
![NotToday-Logo---D3 copy](https://user-images.githubusercontent.com/54009156/63809918-5bca8180-c8d8-11e9-815c-4695097e5658.png)

**Comment by ExperimentsInHonesty** [comment]
Alt text for image: person being supported art by c.w. moss

**Comment by ExperimentsInHonesty** [comment]
Turns out I put the wrong url for the Github link: https://github.com/hackforla/not-today

**Comment by ExperimentsInHonesty** [comment]
Also. I reverted the commit from the merge above because something else was wrong with it.  Going to review now.
