### ISSUE TITLE
Adjust Credits page header

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1452]
### Overview
We need to adjust the Credits page header to standardize it with the rest of the headers on the site

### Action Items
- [ ] Make the header image max-height 240px (instead of the current percentage max-width property it has)

### Resources/Instructions
[Credits page](https://www.hackforla.org/credits/)
[Site Architecture wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

**Comment by akibrhast** [comment]
@daniellex0 This is a duplicate of https://github.com/hackforla/website/issues/1459
I am closing this.
