### ISSUE TITLE
Add About page images/icons to Credits page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1456]
### Overview
We need to add the icons and vector image from the About page to the Credits page so that we are following the image use requirements 

### Action Items
- [x] Review the icons and vector image that need to be credited on the Figma file for the About page - they are all on the bottom of the page in a green rectangle to the left of the pink rectangle (final About page design) 
- [x] Add all of the credit information to the Credits page 

### Resources/Instructions
- [Figma file for the About page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692) - credit information is on bottom in green rectangle (to the left of large pink rectangle)
- [Credits page](https://www.hackforla.org/credits/)
- [credit.md template](https://github.com/hackforla/website/wiki/Template-of-a-credit.yml-file-(for-Credits-page))

<details>
<summary>Credits section to look for on Figma</summary>
<br>
<img width="200" alt="Screen Shot 2021-04-24 at 2 05 05 PM" src="https://user-images.githubusercontent.com/67400366/115972921-34411780-a506-11eb-9b03-291b8cf63947.png">
</details>

**Comment by qiqicodes** [comment]
@pascuas Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:
Availability:
ETA:

**Comment by pascuas** [comment]
@qiqicodes sorry for the delay. Just finished.
<img width="900" alt="Screen Shot 2021-05-31 at 1 26 41 PM" src="https://user-images.githubusercontent.com/59798280/120239877-1c029d80-c214-11eb-8165-a5490615c999.png">
<img width="895" alt="Screen Shot 2021-05-31 at 1 26 53 PM" src="https://user-images.githubusercontent.com/59798280/120239884-22911500-c214-11eb-9477-9804fe10c60d.png">
<img width="897" alt="Screen Shot 2021-05-31 at 1 27 12 PM" src="https://user-images.githubusercontent.com/59798280/120239888-245ad880-c214-11eb-9092-fc18ead5ed2a.png">
