### ISSUE TITLE
Adjust size of Credits page header illustration 

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1459]
### Overview
We need to adjust the size of the Credits page header illustration so that it is consistent with the Figma and other headers on the site

### Action Items
- [x] In desktop view of the Credits page, make the header illustration max-height 240px
- [x] In tablet and below, make the max-height 170px

### Resources/Instructions
[Credits page](https://www.hackforla.org/credits/)
[Site Architecture wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

**Comment by qaz6209031** [comment]
I will work on this issue

**Comment by qaz6209031** [comment]
Even thought I fix the issue, but the image size looks quite small in mobile, the height is only 29.91px 

![image](https://user-images.githubusercontent.com/44656685/116195704-6b225380-a6e7-11eb-94b8-d72754449c02.png)

**Comment by daniellex0** [comment]
Hey @qaz6209031 you're right, good catch- I will create a new issues for that. Thanks for notifying about this!

Also just FYI you already worked on a good second issue, so your next step is actually supposed to be work on a medium issue next- we're trying to save the good second issues for those that need one. All of this information is provided at the dev meetings Tue at 7pm PDT (tonight), so make sure to join so that you can know and follow our standards! It's ok now, but make sure to work on a medium issue next please 👍

**Comment by qaz6209031** [comment]
> Hey @qaz6209031 you're right, good catch- I will create a new issues for that. Thanks for notifying about this!
> 
> Also just FYI you already worked on a good second issue, so your next step is actually supposed to be work on a medium issue next- we're trying to save the good second issues for those that need one. All of this information is provided at the dev meetings Tue at 7pm PDT (tonight), so make sure to join so that you can know and follow our standards! It's ok now, but make sure to work on a medium issue next please 👍

Hello @DanielekPark I just made a new commit and the issue should be fixed
