### ISSUE TITLE
Standardize the Communities of Practice page mobile subheadings 

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1460]
### Overview
We need to adjust the subheadings (in mobile view) in the Communities of Practice page so that they are consistent with our design system

### Action Items
- [ ] Make the font size of the **mobile** subheadings in the Communities of Practice page 20px (instead of 22px)

### Resources/Instructions
[Communities of Practice page](https://www.hackforla.org/communities-of-practice)
[Site Architecture wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

These are the mobile subheadings:

<img width="399" alt="Screen Shot 2021-04-25 at 8 40 51 AM" src="https://user-images.githubusercontent.com/67400366/115999805-1628f500-a5a2-11eb-8e01-7da615ab24b5.png">

**Comment by qaz6209031** [comment]
I will work on this issue
