### ISSUE TITLE
Change mentions of "Hack Nights" in Credits page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1461]
### Overview
We need to change all mentions of "Hack Nights" in the Credits page to "Events," because that is the new name of that page

### Action Items
- [x] Review the Credits page and see where "Hack Nights" shows up under "Used In"
- [x] Change all mentions of "Hack Nights" in the Credits page to "Events" instead

### Resources/Instructions
[Credits page](https://www.hackforla.org/credits/)
[Site Architecture wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

**Comment by kceddinger** [comment]
After building my site locally, the order of the items differs from the live site although my gh-pages branch is even with hackforla/website repo.

Live site (4/26/21):
<img width="751" alt="live_site" src="https://user-images.githubusercontent.com/51894148/116148435-c297d380-a695-11eb-8c67-8ce580b9962b.png">

Local 4/26/21)
<img width="763" alt="local_with_update" src="https://user-images.githubusercontent.com/51894148/116148465-cd526880-a695-11eb-961b-7442b7965d9f.png">
