### ISSUE TITLE
Adjust Events page 'Our Locations' collapsed section in mobile view

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1462]
### Overview
We need to adjust the icons in the Events page's collapsed "Our Locations" section because it seems to have shifted partially or totally off-screen recently

### Action Items
- [ ] Review how the mobile version of the Events page's collapsed "Our Locations" section is supposed to look below and on the Figma (in red rectangle)
- [ ] Fix the collapsed "Our Locations" section so that it looks like the Figma again

### Resources/Instructions
[Events page](https://www.hackforla.org/events/)
[Figma mockup of Events page mobile view](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94) (in red rectangle)

<details>
<summary>Events page Locations collapsed section looks like this right now:</summary>
<br>
<img width="434" alt="Screen Shot 2021-04-25 at 8 57 54 AM" src="https://user-images.githubusercontent.com/67400366/116000302-7d47a900-a5a4-11eb-9b74-4179d0f32ef5.png">
</details>

<details>
<summary>Should look like this:</summary>
<br>
<img width="348" alt="Screen Shot 2021-04-25 at 8 55 09 AM" src="https://user-images.githubusercontent.com/67400366/116000297-7ae54f00-a5a4-11eb-8e14-6113a0ed6dc2.png">
</details>

**Comment by josiehandeveloper** [comment]
Here are the changes I made
<img width="283" alt="Screen Shot 2021-04-29 at 9 04 03 PM" src="https://user-images.githubusercontent.com/63170710/116647092-96e34a80-a92e-11eb-8337-da018227d92e.png">
