### ISSUE TITLE
Suggested Edits to the Getting Started Page

### ISSUE THREAD

**Issue by abenipa3** [hackforla/website#1469]
### Overview
Some information from the Getting Started Page needs clarification, so we created a Google Doc with suggested Edits.

### Action Items

- [ ] Review the suggested changes.
- [ ] Make any necessary changes.
- [ ] Create a new issue for the developers to implement the changes.

What did the father buffalo say to his child when he was on his way to school?
Bison

### Resources/Instructions
[Suggested Edits Document](https://docs.google.com/document/d/1asOea4JVGXy_0e3TnaNhekRwwJIxeDih93zvy9df1Ms/edit)

**Comment by daniellex0** [comment]
Update: We will discuss this in the design team- sorry about the delay, the homepage redesign is getting priority in discussions right now

**Comment by daniellex0** [comment]
Closing because we are working on this in issue #1619
