### ISSUE TITLE
Add documentation for if you don't see changes or delete the -I

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1477]
### Dependency
Talk about this in the dev meeting and edit the issue based on what is decided

### Overview
Recently, we added an incremental build flag to our jekyll serve command, This makes docker reload a whole lot faster, but it makes it so that people do not always see the changes that they made..

### Action Items
- [ ] add some documentation about deleting the generated _site folder and jekyll-metadata file
or
- [ ] delete the -I in the jekyll serve command in the docker-compose.yml file

### Resources/Instructions
REPLACE THIS TEXT - Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc.

**Comment by averdin2** [comment]
Bring this up during Sunday dev meeting

**Comment by jbubar** [comment]
@averdin2 @akibrhast @jbubar @erikaBell @Aveline-art @josiehandeveloper 
Please bring this up in the backend meeting.

**Comment by Sihemgourou** [comment]
Devs will work on contributing file instructions to maintain -I capabilities while helping new devs

**Comment by Sihemgourou** [comment]
@averdin2 
Please add update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by Sihemgourou** [comment]
~~@Aveline-art~~

@averdin2 
Please add update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by Sihemgourou** [comment]
@averdin2 could you choose a role label and then remove the label role missing please?

**Comment by Sihemgourou** [comment]
@jbubar @akibrhast have you heard from @averdin2 ?

**Comment by akibrhast** [comment]
@sayalikotkar Yes. He was on vacation and he will be back during tonights backend meeting

**Comment by averdin2** [comment]
Sorry about the delay on this. I will take care of this ASAP!

**Comment by averdin2** [comment]
I finished a first draft of the steps to fix this issue. I want to ask the team if there are other suggestions on where these steps should be placed, and if there is any additional info needed. Currently, I have these steps after the steps for starting and stopping Docker.

<details>
<summary>Screenshot of document changes</summary>

![image](https://user-images.githubusercontent.com/10714770/123550047-6d715000-d720-11eb-8ac1-d9fba2c083a3.png)
</details>

**Comment by averdin2** [comment]
Need to make an issue to potentially make a wiki article to explain why this issue occurs.

**Comment by averdin2** [comment]
Also, I need to move the contents I wrote from inside the Docker section into Working on an Issue section.
