### ISSUE TITLE
Update Toolkit Page subheadings

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1479]
### Overview
We need to update the 'Guides' and 'Resources' subheading sections (and their buttons) in the Toolkit page to better align the page, and accommodate upcoming changes to the mobile version of the filter banner.

### Action Items
- [x] Review images below (under arrows) to see how the updated page should look (or see the [Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967)- in pink rectangle)
- [x] Remove "(We made these!)" text after 'Guides' subheading
- [x] Evenly align both the buttons and subheadings ("Guides" and "External Resources") with the edges of the guide cards in all screen sizes, desktop through mobile, as seen in the screenshots below and Figma

### Resources/Instructions
[Toolkit page](https://www.hackforla.org/toolkit/)
[Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967)- in pink rectangle)

<details>
<summary>How it looks now:</summary>
<br>
<img width="1397" alt="Screen Shot 2021-04-27 at 6 45 45 PM" src="https://user-images.githubusercontent.com/67400366/116334252-be4ce280-a789-11eb-9004-c84db5a83a60.png">
</details>

<details>
<summary>How it should look:</summary>
<br>
<img width="745" alt="Screen Shot 2021-04-27 at 6 45 23 PM" src="https://user-images.githubusercontent.com/67400366/116334270-c3aa2d00-a789-11eb-896c-d50c7f7099e2.png">
</details>

**Comment by qiqicodes** [comment]
https://github.com/hackforla/website/pull/1491#issuecomment-834726437

@qaz6209031 Can you let us know your progress in regards to the PR linked to this issue? Thank you =]

Progress:
Blockers:

**Comment by wendywilhelm10** [comment]
An attempt to address this issue has been made in the pull request #1491.  The next person assigned to this issue please feel free to continue the work off of the changes applied in the above mentioned pull request.  The only changes that need to be applied as mentioned in the pull request.
https://github.com/hackforla/website/pull/1491#pullrequestreview-657438594

**Comment by ExperimentsInHonesty** [comment]
I moved this back to prioritized backlog because the changes still need to be made, however this can be made as two separate PRs, one to remove the "(We Made These!) text and another one to fix the button
