### ISSUE TITLE
Create project card for tdm-calculator

### ISSUE THREAD

**Issue by gitklu** [hackforla/website#148]
### Overview
Provide collateral for the HackforLA website

### Action Items
- [x]   Gather items
  - [x]  600 x 400 image
  - [x]  Name of project
  - [x]  A blurb about your project
  - [x]  Links (website, github, etc.)
  - [x]  What you are looking for skills wise
  - [x]  Partner(s)
  - [x]  Location
- [x]   Add project Card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples

**Comment by nekobox** [comment]
![TDM Card Image (600x400)](https://user-images.githubusercontent.com/14010934/63823404-9ba95d00-c908-11e9-9ed9-cc866bb2f668.jpg)

**Comment by nekobox** [comment]
**Name of Project**: LA TDM Calculator
**Blurb**: We’re building a TDM web calculator for LADOT. It scores proposed real estate developments in real-time and aims to discourage exceeding parking requirements to reduce the occurrence of single-occupancy trips to new developments.
**Links**: https://github.com/orgs/hackforla/teams/tdm-calculator (Github)
**Partner**: LA Department of Transportation (LADOT); https://ladot.lacity.org/
**Location**: Downtown LA

**Comment by ExperimentsInHonesty** [comment]
per Nichole : Alt image text: LA TDM Calculator Landing Page (Mock Up)
