### ISSUE TITLE
Fix arrow bug on About page

### ISSUE THREAD

**Issue by averdin2** [hackforla/website#1481]
### Overview
There seems to be a problem with how the card's accordion arrows are oriented when the page is resized from desktop to mobile. The accordion arrows seem to point the wrong way, but fix themselves as the accordion is closed and reopened. See the gif below for more details.

<details>
<summary>Gif</summary>

![about_page_accordion](https://user-images.githubusercontent.com/10714770/116322213-6c4b9300-a770-11eb-8342-ffdd0e9fd027.gif)
</details>

### Action Items
- [ ] Ensure that the accordion arrow points the right way when you change from desktop to mobile view

### Resources/Instructions
About Page: https://github.com/hackforla/website/blob/gh-pages/pages/about.html
About SCSS file: https://github.com/hackforla/website/blob/gh-pages/_sass/components/_about.scss
About JS file: https://github.com/hackforla/website/blob/gh-pages/assets/js/about.js

**Comment by qaz6209031** [comment]
Hello @averdin2 , I tried to reproduce the bug, but it seems ok for me. I used the exact screen size as you did. 

![Screen Recording 2021-04-28 at 7 03 23 PM](https://user-images.githubusercontent.com/44656685/116494096-fa00ae80-a854-11eb-942e-ddd6dbafecfb.gif)

**Comment by averdin2** [comment]
@qaz6209031 The problem should occur when you resize down from a desktop viewport into a mobile viewport. The issue is that the opened card has the arrow in the incorrect position.

**Comment by averdin2** [comment]
@qaz6209031 You should also now have permission to the repo so you can assign yourself this issue if you want to work on it. Feel free to reach out to me on Slack if you have any other questions.

**Comment by josiehandeveloper** [comment]
https://user-images.githubusercontent.com/63170710/116833944-cc777600-ab70-11eb-85f8-fb5283745818.mov

It seems that this issue is fixed already

**Comment by averdin2** [comment]
@josiehandeveloper Check the gif in the issue. This problem is specifically created when resizing from desktop into mobile view. Start in a desktop viewport and use the right navigation to go to any of the cards. Then resize the page and you should see the issue I am talking about. If you still have more questions, I can touch on it in Tuesday's meeting or you can reach out to me on Slack.

**Comment by josiehandeveloper** [comment]
https://user-images.githubusercontent.com/63170710/117080641-24d68100-acf3-11eb-9f01-94cabd93c7c3.mov

The issue seems like it's fixed! Whoo @averdin2
