### ISSUE TITLE
Change CSS class name for filter items

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#1483]
### Overview
Continuum of #1415 , currently the four items in the filter list dropdown has the class name of "filter-item". New class name is necessary before the class name "filter-item" is assigned to the filter tag.

### Action Items
 - [x] Change the CSS class name to '.filter-tag' instead of .btn--current-projects-filter-tag (.filter-item name was voted/agreed on at a dev meeting, and this isn't technically a button in the design system).
    - [x] Figure out how to make this function similar to a button (clickable with pointer) without using button code. See for reference [Adidas filter tags](https://www.adidas.com/us/women-shoes) with similar functionality, but it's a div

^^^open the link in an incognito tab^^^

### Resources/Instructions
- [Homepage](https://www.hackforla.org/#)
- [Figma design for the filter tags (in purple rectangle towards the left](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205)

**Comment by daniellex0** [comment]
Hey @qiqicodes , ok I think let's just keep the name of this ".filter-tag" because there is no point in renaming ".filter-item" everywhere it exists now in dropdowns, and ".filter-tag" does still make sense. But please do still change it from ".btn--current-projects-filter-tag" to just ".filter-item" and change it from button to div if possible :)

**Comment by qiqicodes** [comment]
@daniellex0, got it!

**Comment by qiqicodes** [comment]
Progress: filter-tag is assigned. Figuring out the CSS to make sure the div's look like the current button's

**Comment by qiqicodes** [comment]
Progress: The filter tags are buttons currently. Each filter tag appends directly after the unordered filter list. On Adidas website, their filter tags are populated within a div, and each filter tags are inside two divs, and each value of the filter tag is inside a span element. 

Blockers: Should we change the current filter buttons to the span inside divs? 

Availability: Open on Friday

ETA: Based on discussion.

**Comment by jbubar** [comment]
@averdin2 and qiqi are going to work on this during the week. The goal is to change the `<button>` tag to a non button tag
