### ISSUE TITLE
Adjust Step 4 of Getting Started page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1488]
### Overview
We need to adjust Step 4 of the Getting Started page to keep it up to date with current onboarding practices at HfLA

### Action Items
- [x] Review the changes to the Step 4 text in the annotated screenshot below
- [x] Replace "Project Lead" with **"Product Manager"** in # 1, per the screenshot
- [x] Replace "Admin a link to the Team Roster" with **"Product Manager your Github username"** (no link) in # 4, per the screenshot

### Resources/Instructions
[Getting Started Page](https://www.hackforla.org/getting-started)
[Hack for LA Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

<img width="957" alt="Screen Shot 2021-04-28 at 12 29 40 AM" src="https://user-images.githubusercontent.com/67400366/116365857-87db8b80-a7ba-11eb-999c-d2317a9bd1f5.png">

**Comment by wendywilhelm10** [comment]
Progress: I created a PR but there were conflicts I needed to resolve.  I resolved them and thought I pushed my changes to my repository but not sure they are there.
Blockers: My lack of Git/Github knowledge.  I need help with help to resolve conflict.  I know what the code should look like.
Availability: This does not require a lot of time to complete.
ETA: If I don't get help before next Tuesday, it will be complete in next Tuesday's meeting.
