### ISSUE TITLE
Fix alignment of News section in About page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1498]
### Overview
We need to fix the News section of the About page so that it is properly aligned and closer to how it looks in the original Figma design

### Action Items
- [x] Review the original [Figma design of the About page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692) with the correct News section alignment (in pink rectangle all the way on bottom of page)
- [x] Fix the alignment of the News section in the [About page](https://www.hackforla.org/about/#news) so that it is closer to the original Figma design

### Resources/Instructions
- [Original Figma design of About page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692) (all the way on bottom in pink rectangle)
- [About page](https://www.hackforla.org/about/#news)
- [HfLA Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

Click arrows:

<details>
<summary>How About page News section looks now:</summary>
<br>
<img width="858" alt="Screen Shot 2021-04-30 at 6 18 22 PM" src="https://user-images.githubusercontent.com/67400366/116766818-58f32e80-a9e1-11eb-9fb4-c50e52477287.png">
</details>

<details>
<summary>How About page News section looks on Figma:</summary>
<br>
<img width="721" alt="Screen Shot 2021-04-30 at 6 21 08 PM" src="https://user-images.githubusercontent.com/67400366/116766828-627c9680-a9e1-11eb-94c5-03052336e6f9.png">
</details>

**Comment by qiqicodes** [comment]
@evancchen Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by jamesberke** [comment]
@daniellex0 does this still need to be fixed? The history of this issue is a bit confusing to me. It's just an issue with the flex direction and justify content, so a super easy fix

**Comment by Sihemgourou** [comment]
@jamesberke yes, it needs to be fixed to match the figma :)

**Comment by aliibsin** [comment]
@jamesberke can you update us on your progress with this issue?

**Comment by Sihemgourou** [comment]
Sent a slack message to @jamesberke. Will be unassigned if no news until July 1st

**Comment by Sihemgourou** [comment]
@jamesberke is actively working on it. He will update the issue

**Comment by jamesberke** [comment]
1. Wrapped images and text in containers to fix the size of images and make them uniform. Also made the images display horizontally for tablet view to better fit the Figma design.
2. Vacation and Illness had me away from my computer for the past couple weeks
3. Full availability now, will be back to work
4. ETA is Today/Tomorrow

**Comment by Sihemgourou** [comment]
Remove @jamesberke from the issue if no updates until July 11

**Comment by ExperimentsInHonesty** [comment]
Hi James,  Please connect with one of the PMs when/if you return to the project.  Hope you are well

**Comment by ExperimentsInHonesty** [comment]
James did not come to Sunday meeting or update issue and had not been to meetings for about 2 weeks.  Unassigned and put back in the prioritized backlog.

**Comment by celinevalentine** [comment]
Start working on it tonight, ETA by Sunday, 25th.

**Comment by celinevalentine** [comment]
Does it matter if each of the three are placed exactly like in Figma?

**Comment by celinevalentine** [comment]
<img width="891" alt="Screen Shot 2021-07-25 at 12 17 05 AM" src="https://user-images.githubusercontent.com/52294389/126891065-d306eafd-49c9-46f7-be67-101296569079.png">

Is this alignment good enough?

**Comment by celinevalentine** [comment]
accidentally pushed to the wrong branch, now looking for solutions to fix this git issue before I submit PR

**Comment by adam-abundis** [comment]
@celinevalentine I added some lines and boxes (they are approximate) within the Figma design to show you the alignment. Ideally, you use the left/right margin on the whole section to achieve this. The boxes are more to show the space between each element. If have any more questions, feel free to reach out to me.

<details>
  <summary>Click here to see the figma design with my edits</summary>

![Screenshot 2021-07-26 065628](https://user-images.githubusercontent.com/21162229/127014524-fe354f21-c095-4984-baa5-b81e6c88d879.jpg)

</details>

**Comment by adam-abundis** [comment]
@celinevalentine Can you please provide an update on resolving the merge conflicts on your pull request/issue update? We do not want to accidentally remove you from this issue.

**Comment by macho-catt** [comment]
Celine informed me that she won't be able to finish the issue. Closing the attached PR and putting this back to the backlog. For the next person working on this, feel free to look at #2011

**Comment by Johnnie007** [comment]
Availability for this week 1/23 -1/30:
Tuesday & Thursday Evenings/Night EST
My estimated ETA for completing this issue:
45 mins

**Comment by SAUMILDHANKAR** [comment]
@Johnnie007 Please share your weekly progress report. Thanks.

**Comment by JessicaLucindaCheng** [comment]
@Johnnie007 Please provide a weekly progress report with the following:
```
- Progress: "What is the current status of your project? What have you completed and what is left to do?"
- Blockers: "Difficulties or errors encountered."
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"
```

**Comment by JessicaLucindaCheng** [comment]
Left a Slack message for Johnnie on Fri, Feb 25, 2022 about https://github.com/hackforla/website/issues/1498#issuecomment-1051406107.

**Comment by Johnnie007** [comment]
Going to unassign the issue. Completing a course, and I will be inactive for the next 5 weeks.

**Comment by 1anya1** [comment]
Availability for this week :
Wed - Friday:  3 hours/day
My estimated ETA for completing this issue:
Thursday 3/3/2022

**Comment by 1anya1** [comment]
Provide Update
1. Progress - working on css styling 
2. Blockers - family emergency
3. Availability - mon/ fri 3 hrs per day 
4. ETA - Tuesday March 7th
