### ISSUE TITLE
HFLA logo placement in the header is inconsistent depending on size of browser window

### ISSUE THREAD

**Issue by joshuazrobins** [hackforla/website#150]
### Overview
The Hack for LA logo (upper-left corner) in the header is placed inconsistently across differing browser window sizes. See the images below:

Mobile:
![image](https://user-images.githubusercontent.com/1521996/63897944-c8fb1700-c9ab-11e9-92d0-255d37914453.png)

Desktop:
![image](https://user-images.githubusercontent.com/1521996/63897950-cf898e80-c9ab-11e9-91e1-63fbe23ed63a.png)

### Action Items
Needs to be investigated and reproduced to determine cause.

### Resources/Instructions
TBD

**Comment by StephenVNelson** [comment]
@ExperimentsInHonesty @RyanCahela What's the update on this? Is it alright if I take it on?
