### ISSUE TITLE
Fix Expunge Assist image 

### ISSUE THREAD

**Issue by erikaBell** [hackforla/website#1500]
### Overview
Measurement issues with Expunge Assist image on front page & question to design team.

### Action Items

- [ ] Fix measurements on Expunge Assist photo
<details>
<summary>Measurement Issues</summary>

<img width="924" alt="Screen Shot 2021-04-30 at 10 48 16 AM" src="https://user-images.githubusercontent.com/67438372/116820031-cc9f5380-ab27-11eb-82e0-afcc608ff9c5.png">

</details>

- [ ] Should Expunge Assist photo having the project name _in_ the image its self? I ask because as far as I have seen, none of the other project cards do, and this creates a "doubling" of the project name when you enter the project

<details>
<summary>Now</summary>

<img width="959" alt="Screen Shot 2021-04-30 at 10 50 01 AM" src="https://user-images.githubusercontent.com/67438372/116820080-fb1d2e80-ab27-11eb-959c-f7a6c1ebc3e4.png">

</details>
<details>
<summary>Before</summary>

<img width="872" alt="Screen Shot 2021-04-30 at 10 50 08 AM" src="https://user-images.githubusercontent.com/67438372/116820091-07a18700-ab28-11eb-864c-7fed8905155b.png">

</details>

### Resources/Instructions
Related to PR #1493 & issue #1249 
Compare project cards on front page, plus compare the layout of the projects when "entered"
@Daniel

**Comment by daniellex0** [comment]
@ggrrettcchhenn can someone from your team please provide a new image with the correct measurements for Expunge Assist's project card and post it in a comment below? 

The one provided [in your original issue](https://github.com/hackforla/website/issues/1249) doesn't have the right standard measurements, as you can see in the screenshot below-

It should be **600x400 pixels**

Thank you!

<img width="852" alt="Screen Shot 2021-05-04 at 1 43 35 AM" src="https://user-images.githubusercontent.com/67400366/116979707-316ac300-ac7a-11eb-90fd-4c3fe019211c.png">

**Comment by ggrrettcchhenn** [comment]
sorry about this, I am connecting with our designers to get a better image to you for our project card.

**Comment by daniellex0** [comment]
@ggrrettcchhenn No worries, thank you!

**Comment by Sihemgourou** [comment]
Hello ! @ggrrettcchhenn 
Please add update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by ggrrettcchhenn** [comment]
![expungement-banner600x400](https://user-images.githubusercontent.com/27507664/121819463-0cd31500-cc42-11eb-8f21-afb65b0d0873.png)
sorry for the delay! we plan to update one more in line with our product branding in the coming weeks, but this one is the right dimensions for now and doesn't repeat our project name.

**Comment by Sihemgourou** [comment]
@ggrrettcchhenn will give us a temporary image :)

**Comment by Sihemgourou** [comment]
I'll bring it up at the next CoP

**Comment by ggrrettcchhenn** [comment]
@Sihemgourou We noticed that some other projects have one image for their preview card, and a second image as their project page header. Could we submit a hero image as well? what are the correct dimensions / requirements for the project page header image? thank you!

**Comment by ggrrettcchhenn** [comment]
hero image dimensions: 1500 x 700 px

**Comment by Sihemgourou** [comment]
Closing this issue after the creation of this issue https://github.com/hackforla/website/issues/1943
