### ISSUE TITLE
Add Toolkit page header illustration to Credits page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1505]
### Overview
We need to add the vector illustration from the [Toolkit page](https://www.hackforla.org/toolkit/) header to the [Credits](https://www.hackforla.org/credits/) page so that we are following the image use requirements

### Action Items
- [x] View the image credit information in the comment below (scroll down) 
- [x] Add the credit information to the Credits page

### Resources/Instructions
- [Credits page](https://www.hackforla.org/credits/)
- [credit.md template](https://github.com/hackforla/website/wiki/Template-of-a-credit.md-file-(for-Credits-page))

**Comment by daniellex0** [comment]
Name: Designer life

Used in: Toolkit

Artist: stories

Provider: Freepik

(original image link: https://www.freepik.com/free-vector/designer-life-concept-illustration_7118651.htm#page=6&position=43)

**Comment by jamesberke** [comment]
The toolkit page seems to be pulling this image from _includes/svg/toolkit-hero.svg but all other images on the credit page have a path through assets/images/... 

from what I can tell the _includes path will not work. Do we need to save this image in the assets/images folder? @averdin2

**Comment by averdin2** [comment]
@jamesberke That is a good question. I will bring it up during today's backend meeting briefly and get back to you on what to do.
