### ISSUE TITLE
Events page: prevent items from being "hidden"

### ISSUE THREAD

**Issue by erikaBell** [hackforla/website#1521]
### Overview
Starting at window size 1117 through to mobile view, event card items begin to get _hidden_. 

<details>
<summary>Event Card Items Hidden</summary>

<img width="590" alt="Screen Shot 2021-05-06 at 3 26 00 PM" src="https://user-images.githubusercontent.com/67438372/117373732-ae678980-ae80-11eb-88be-7acf9185b8c9.png">

</details>

### Action Items

- [ ] refer to [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94) design for how the event cards should look (blue rectangle) 
- [ ] refactor the code to prevent items in the `<div class="mini-projects">` containers from being hidden—both on the "Monday" and "Tuesday" card—, while maintaining the Figma design
  - if the design needs to be altered to work, reach out to @daniellex0 for direction
- [ ] ensure that mobile view does not break

### Resources/Instructions
[Figma Design (blue rectangle)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94)
@daniellex0

**Comment by qiqicodes** [comment]
@josiehandeveloper Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by josiehandeveloper** [comment]
Hi sorry for the delay @qiqicodes I'm working on it now
