### ISSUE TITLE
Rewrite Alt Text for yml files in "./_data/internal/credit" directory

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#1526]
### Overview
Audit and rewrite the alt text for yml files in "./_data/internal/credit" directory. "Image of" is not necessary.

### Action Items
- [x] remove "image of"
- [x] rewrite descriptive alt text accordingly for the following yml file
   - [x] act.yml
   - [x] brochure.yml
   - [x] building.yml
   - [x] business.yml
   - [x] button.yml
   - [x] calendar-time.yml
   - [x] check.yml
   - [x] commofpract.yml
   - [x] contact.yml
   - [x] delegate.yml
   - [x] design.yml
   - [x] designer-life.yml
   - [x] email.yml
   - [x] give.yml
   - [x] locations.yml
   - [x] meetings.yml
   - [x] meetup.yml
   - [x] office-worker.yml
   - [x] partnership.yml
   - [x] people.yml
   - [x] people2.yml
   - [x] photo-roaster.yml
   - [x] process.yml
   - [x] redo.yml
   - [x] resume.yml
   - [x] review.yml
   - [x] rocker.yml
   - [x] security.yml
   - [x] technology.yml
   - [x] video-conference.yml
   - [x] winner.yml

### Resources/Instructions
https://cliquestudios.com/alt-text/
[How to write effective alt tag for images](https://medium.com/nyc-design/how-to-write-effective-alt-tags-for-images-9f888f36992f)
[WebAIM](https://webaim.org/techniques/alttext/)

**Comment by jbubar** [comment]
I think we should make this into a million good first issues!

**Comment by qiqicodes** [comment]
https://github.com/hackforla/website/issues/1456#issue-866837802

More files will need to have alt text audit

**Comment by qiqicodes** [comment]
Progress: Tracking all icons and images from sources to better naming them.
Blocker: none
Availability: late Sunday afternoon

**Comment by qiqicodes** [comment]
Created 31 good first issues
