### ISSUE TITLE
Make wins' page modal overlay keyboard navigable

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#1531]
### Overview
Individual wins' card and wins' page modal overlay is not keyboard accessible.

### Action Items
- [x] make "...see more" tab-able 
- [ ] focus on modal overlay when displayed
- [x] make escape available to modal overlay  

### Resources/Instructions
[Accessible Links](https://www.htmldog.com/guides/html/advanced/links/)
[Creating an Accessible Modal Dialog](https://bitsofco.de/accessible-modal-dialog/)

**Comment by qiqicodes** [comment]
@grhhhh Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by grhhhh** [comment]
Progress: 
Fixed: Made esc key available on modal. Made "See more..." tab-able.
Blockers: Researching solutions to bring focus to modal.

**Comment by grhhhh** [comment]
I’m exploring possible solutions for trapping focus in the modal and could use some guidance:

-The inert property seems to be well liked in the a11y community, although it would require installing a polyfill package to support it. Implementation might look like writing a function that gives inert = true to all elements outside the modal while the modal is open. https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/inert

-Using a tabindex=“-1” attribute in a similar way to the inert property may be possible, however I’ve been unsuccessful in my attempt to implement this as a solution.

-Another solution would be to ‘trap’ the cursor focus inside of the modal as described in this article:
https://uxdesign.cc/how-to-trap-focus-inside-modal-to-make-it-ada-compliant-6a50f9a70700

**Comment by GLRJr** [comment]
@grhhhh Do you need more eyes on this? Akib mentioned that you and Jo went over this. If you still have questions about this feel free to back it back int the Dev team meeting column.

**Comment by Sihemgourou** [comment]
@grhhhh 
I noticed that your PR seems to be waiting on additional review, feel free to talk to the person responsible for the review OR to  reach out to the general channel to get this unstuck ;
