### ISSUE TITLE
Use Jekyll Doc or MkDocs for Hack for LA project documentation

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#1534]
### Dependencies 
- [x] #3636
- [ ] #2676 
- [x] #1416
This issue is a dependency for any other works related to the wiki. Some notes on our processes can be found in our drive in a folder titled Temporary Wiki.

### Overview
Currently our documentation is on [wiki's page](https://github.com/hackforla/website/wiki). Hack for LA use Jekyll to generate Hack for LA live site with GitHub pages. It would be nice to have a static site with search functionality for project documentation.

* [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/getting-started/) is a theme for [MkDocs](https://www.mkdocs.org/), a static site generator geared towards (technical) project documentation.

* [Jekyll Doc](https://idratherbewriting.com/documentation-theme-jekyll/index.html) is a documentation theme for [Jekyll](https://jekyllrb.com/). 

The Youth Justice Nav Project's documentation currently uses Material fo MkDocs.
* [Youth Justice Nav repo](https://github.com/hackforla/youthjusticenav-info/tree/main/docs)
* [Youth Justice Nav documentation static site](https://hackforla.github.io/youthjusticenav-info/Juvenile%20Hall/)

### Action Items
- [x] research the feasibility
- [ ] Create audit

### Resources/Instructions
* [Jekyll](https://jekyllrb.com/)
* [Jekyll Doc](https://idratherbewriting.com/documentation-theme-jekyll/index.html)
* [MkDocs](https://www.mkdocs.org/)
* [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/getting-started/) 
* [Youth Justice Nav repo](https://github.com/hackforla/youthjusticenav-info/tree/main/docs)
* [Youth Justice Nav documentation static site](https://hackforla.github.io/youthjusticenav-info/Juvenile%20Hall/)
* [MkDocs or Jekyll for Technical Documentation](https://blogs.sap.com/2020/07/24/mkdocs-or-jekyll-for-technical-documentation/)

[notes](https://docs.google.com/document/d/1Se4HW4Ab_UR7tgy9Ul8M0Rxev_wrL36rvPPGqYB93uU/edit)
[audit spreadsheet](https://docs.google.com/spreadsheets/d/1QzfMX3URWfpfeoun34jRm8oDOxXMAMMRvUDS05WLpNY/edit#gid=0)

**Comment by Sihemgourou** [comment]
Existing wiki site information architecture should be refined using the side menu before implementation of Jekyll doc wiki

**Comment by akibrhast** [comment]
Existing wiki site information architecture has been refined

**Comment by ExperimentsInHonesty** [comment]
Next steps:

- [ ] reorg the wiki
- [ ] and then make a new issue to have the wiki converted into mkdocs

**Comment by ExperimentsInHonesty** [comment]
Met with dev team and started working on it.  See top of issue for spreadsheet

**Comment by ExperimentsInHonesty** [comment]
- This issue has been replaced with https://github.com/hackforla/website/issues/3635
