### ISSUE TITLE
update the lodash depenency in /github-actions/github-data/package.json

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1538]
### overview
<details>
    <summary>github wants us to update our package.json file... it says it is high severity</summary>

![Screen Shot 2021-05-10 at 10 12 54 PM](https://user-images.githubusercontent.com/53061723/117762067-45b04200-b1dd-11eb-8d8d-a69326b5b869.png)

</details>

### action items
- [ ] change the version to 4.17.21?

https://github.com/hackforla/website/blob/348e6c8e9857182e07b9e409325d3712cb2d0a48/github-actions/github-data/package.json#L11

**Comment by akibrhast** [comment]
lodash updated. Closing this.
