### ISSUE TITLE
Adjust styling of Wins page with badges

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1548]
### Overview
We need to adjust the styling of the version of the Wins page with badges (not live yet) to make it more consistent with the original Figma design.

### Action Items
- [x] Access the "wins-feature-1" (not gh-pages) branch to view the Wins page with badges code 
- [x] Change the margin between the badges and the wins quote paragraphs to **1em** 0 0 6.5rem (instead of 2em 0 0 6.5rem)
- [x] Change "Team(s)" and "Role(s)" to gray (#767676) to be consistent with the original Figma design
- [x] Add 6px margin between the "Team(s)" and "Role(s)" lines to be consistent with the original Figma design

### Resources/Instructions
[Wins page](https://www.hackforla.org/wins/) (currently without the badges- need to access the "wins-feature-1" branch to see them)
[Figma Designs of Wins page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) (in blue rectangle)

What the Wins card should look more like with the changes:

Team(s) / Role(s):

<img width="262" alt="Screen Shot 2021-05-16 at 2 10 02 AM" src="https://user-images.githubusercontent.com/67400366/118391994-01151400-b5ec-11eb-8b84-92b48120f85f.png">

Badges margin:

<img width="350" alt="Screen Shot 2021-05-16 at 2 11 50 AM" src="https://user-images.githubusercontent.com/67400366/118392017-1f7b0f80-b5ec-11eb-8440-dbba48a90483.png">

**Comment by jbubar** [comment]
Guide for git 
https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch

**Comment by Sihemgourou** [comment]
@daniellex0 @wendywilhelm10 this issue seems done for me ! 
Please add update
1. Progress
2. Blockers
3. Availability
4. ETA
