### ISSUE TITLE
Add "See less" button and move "See more" button in mobile Wins page with badges

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1549]
### Overview
In the version of the Wins page with badges (not live yet), we need to move the "see more" button in the mobile Wins page to be consistent with the original Figma design, and we need to add a "see less" button to the mobile Wins page so that users can collapse back the Wins cards that they expanded.

### Action Items
- [x] Access the "wins-feature-1" (not gh-pages) branch to view the Wins page with badges code
- [x] Move the "see more" button in mobile to above the badges- to the same place where it currently is in the desktop wins cards (at the end of the quote paragraph)- see in the [Figma mobile design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) (in blue rectangle on the right)
- [x] Add a "see less" button below the badges in mobile, so that users can collapse a wins card back in mobile after the expanded it.
   - [x] See the "see less" button design in the [Figma mobile design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) (in blue rectangle on the right)

### Resources/Instructions
[Wins page](https://www.hackforla.org/wins/) (currently without the badges- need to access the "wins-feature-1" branch to see them)
[Figma design of Wins mobile page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) (in blue rectangle on the right)

'See more' button placement:

<img width="300" alt="Screen Shot 2021-05-16 at 2 28 53 AM" src="https://user-images.githubusercontent.com/67400366/118392425-88fc1d80-b5ee-11eb-8eb9-1724aae77b0f.png">

'See less' button:
<img width="308" alt="Screen Shot 2021-05-16 at 2 28 44 AM" src="https://user-images.githubusercontent.com/67400366/118392429-8ef1fe80-b5ee-11eb-9096-73dfb90329cd.png">

**Comment by jbubar** [comment]
guide for git https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch

**Comment by qiqicodes** [comment]
Progress: read the codebase for wins pages, figure out the responsible divs to make "see less" happen.
Blocker: none

**Comment by qiqicodes** [comment]
Progress: spoke with Danielle in regards to the consistency of the `...see more` feature on wins card. Figuring out the logics to incorporate the consistent wins card design.

- [ ] put `...` after the truncated wins card text
- [ ] put `see more` at the bottom right of each standard sized wins card
- [ ] put `see less` at the bottom right of each expanded wins card
Blocker: none

**Comment by Sihemgourou** [comment]
@qiqicodes 
Please add update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by qiqicodes** [comment]
Progress: Figuring out the css and logics to insert ellipsis (…) into HTML

- [ ] put `...` after the truncated wins card text

Blocker: none

**Comment by jbubar** [comment]
Took this on a few days ago, have not had the chance to work on it. Will get it done before next sunday

**Comment by jbubar** [comment]
progress: It is all working, just need to do the finishing touches.. @qiqi did most of the work, I just fixed the positions of see more, see less div.. got it disappearing based on the size of the text. 
blockers: The wins page is a bit of a mess.. feel the urge to clean it up
ETA: Tuesday
availability: noon - 4pm mon-sun

<details>
    <summary>mobile</summary>

![screencapture-localhost-4000-wins-2021-07-11-00_31_28](https://user-images.githubusercontent.com/53061723/125186567-defcd400-e1df-11eb-8675-3ce414fede6f.png)


</details>

<details>
    <summary>Desktop</summary>

![screencapture-localhost-4000-wins-2021-07-11-00_32_10](https://user-images.githubusercontent.com/53061723/125186570-e1f7c480-e1df-11eb-955d-bf7029bcf4cb.png)


</details>

Need to come up with a clever way to add elipses in mobile, and change is back to see more when resize back to desktop
