### ISSUE TITLE
Adjust styling of Wins page with badges in mobile

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1550]
### Overview
We need to adjust the styling of the version of the Wins page with badges (not live yet) in mobile to make it more consistent with the original Figma design.

### Action Items
- [ ] Access the "wins-feature-1" (not gh-pages) branch to view the Wins page with badges code
- [ ] Change the badge sizes in mobile collapsed cards:
   - [ ] In ".wins-badge-icon" class only in **mobile** and only in **collapsed cards** (before they're expanded with "see more"),  change "min-width", "max-width", "max-height" and "min-height" all to **1.4em** (instead of 1.7)
- [ ] Change the badge sizes only in **mobile** and only in **expanded** cards (after pressing "see more"):
   - [ ] In ".wins-badge-icon" class, change "min-width", "max-width", "max-height" and "min-height" all to **1em** 

### Resources/Instructions
[Wins page](https://www.hackforla.org/wins/) (currently without the badges- need to access the "wins-feature-1" branch to see them)
[Figma Designs of Wins page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) (in blue rectangle)

Collapsed card badges (1.4em):
<br>
<img width="260" alt="Screen Shot 2021-05-16 at 2 43 34 AM" src="https://user-images.githubusercontent.com/67400366/118392873-adf19000-b5f0-11eb-9ca1-c5c72b6d7f25.png">

Expanded card badges (1em):
<br>
<img width="281" alt="Screen Shot 2021-05-16 at 2 43 01 AM" src="https://user-images.githubusercontent.com/67400366/118392877-b2b64400-b5f0-11eb-8748-7348bd08a37f.png">

**Comment by jbubar** [comment]
guide for git https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch

**Comment by Linda-OC** [comment]
I pushed my changes, but it automatically merged to Hack for LA branch somehow....sorry.  Please find my changes in the commit that referenced this issue above.  If everything looks ok, could we close this issue?  Thank you! @jbubar @daniellex0  @erikaBell 
Worked with Akib on this and he said it is good to go!

**Comment by wendywilhelm10** [comment]
@jbubar will create a new issue to make sure the desktop wins icon is accurate.

**Comment by jbubar** [comment]
@averdin2 and I decided to revert the changes. I think there was a bit of confusion around what is being asked here. 

Please reach out to me or alex. 

@Linda-OC you were on the right track that we need to make some changes to the css, but we also need to make some changes to the HTML file.. This might require some JS! Yay

**Comment by Linda-OC** [comment]
Thank you!  I'll reach out to you and Alex on Slack and we can go from there.

**Comment by Sihemgourou** [comment]
@Linda-OC 
Please add update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by Linda-OC** [comment]
COLLAPSED (Before) - Icons in mobile were 1.7em
![2021-06-13 (8)](https://user-images.githubusercontent.com/67043889/121860601-b642f680-cc94-11eb-9641-f576737d1191.png)

COLLAPSED (After) - Icons in mobile are now 1.4em
![2021-06-13 (16)](https://user-images.githubusercontent.com/67043889/121860635-c2c74f00-cc94-11eb-859b-e1e7aa5f4838.png)

EXPANDED (Before)- Icons in mobile were 1.5em
![2021-06-13 (18)](https://user-images.githubusercontent.com/67043889/121860712-d5418880-cc94-11eb-9567-3362547c7e22.png)

EXPANDED (After) - Icons in mobile are now 1em
![2021-06-13 (12)](https://user-images.githubusercontent.com/67043889/121860750-df638700-cc94-11eb-8b3a-861847fa6e76.png)
