### ISSUE TITLE
Add an 'x' to exit out of the modal overlay on the Wins page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1552]
### Overview
We need to add an 'x' to the pop-up modal overlay on the Wins page so that users can have a second, clear option to escape it (other than clicking on the background- the only current option)

### Action Items

UX/UI Design
- [x] Review the current modal overlay design on the [Wins page](https://www.hackforla.org/) by clicking one of the pink "see more" buttons in desktop
- [x] Access the design of the Wins page overlay on [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) (in blue rectangle, second frame from the right)
- [x] Duplicate the Wins page overlay design, and edit your duplicate to add an 'x' to the top right of the overlay modal
   - [x] Get the 'x' icon from the Design System component library- in the Icons section (under Nav)
   - [x]  Figure out how to adjust the design in its current auto-layout (or undo the auto layout if it's easier)
   - [x] Figure out how to add the 'x' while still keeping the Linkedin Icon on the top right (perhaps the x can be above everything else)

Development
- [x] Develop/add the 'x' to the overlay modal so that users have the option to click the 'x' to escape the overlay (in addition to being able to click the background to do so, which is currently the only option)
   - [x] Use the final modal design in the [Wins page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) in bottom right (in orange rectangle)

### Resources/Instructions
[Wins page](https://www.hackforla.org/wins/) 
[Figma Designs of Wins page final modal overlay](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) (in orange rectangle)

Final modal overlay design in orange rectangle in [Wins page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0):

<img width="450" alt="Screen Shot 2021-06-10 at 8 07 37 PM" src="https://user-images.githubusercontent.com/67400366/121625267-fc475280-ca27-11eb-9498-cd53f3a1a12b.png">

**Comment by jbubar** [comment]
Guide for the git
https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch

**Comment by daniellex0** [comment]
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by SaashaG** [comment]
I believe this is completed. Let me know how it looks. 
![image](https://user-images.githubusercontent.com/83323065/120807127-9cc3e100-c515-11eb-9185-e1c7a8a1c795.png)

**Comment by daniellex0** [comment]
Final 'x' modal design agreed upon:

<img width="576" alt="Screen Shot 2021-06-10 at 8 08 10 PM" src="https://user-images.githubusercontent.com/67400366/121625074-9b1f7f00-ca27-11eb-93b0-fa94ab9eb73e.png">

**Comment by marcobarrera** [comment]
I've update the closing 'x' icon to the svg icon provided.

<img width="876" alt="Screen Shot 2021-06-29 at 5 16 35 PM" src="https://user-images.githubusercontent.com/24802803/123883606-41132a80-d8fe-11eb-8938-685751c1e196.png">
