### ISSUE TITLE
Change Alt Text for Building Image on Credit page

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#1560]
### Overview
Alt text for Building Image on Credit Page needs update.

### Action Items
- [ ] Change the alt attribute value to 'Team discussion concept illustration'

```diff
- alt: 'Image of Building'
+ alt: 'Team discussion concept illustration'
```

### Resources/Instructions
https://github.com/hackforla/website/blob/90a20d1e088b0a05a286af101f82135ad4774e39/_data/internal/credits/building.yml#L10

**Comment by Sihemgourou** [comment]
Hey @lorenzejay please put this issue in the in progress column as you are actively working on it :) Thanks !

**Comment by lorenzejay** [comment]
gotcha. done.
