### ISSUE TITLE
Change Alt Text for Button Image on Credit page

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#1562]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We want to provide updated alt text for the  `Button` Image so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [ ] Change the `alt` property value to 'Choosing between A, B, and C concept illustration' within `_data/internal/credits/button.yml`

**From**
`alt: 'Image of Button'`
**To:**
`alt: 'Choosing between A, B, and C concept illustration'`

#### File and Code links you will need to review this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/button.yml`

- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/90a20d1e088b0a05a286af101f82135ad4774e39/_data/internal/credits/button.yml#L10

**Comment by SAUMILDHANKAR** [comment]
This issue may be outdated or may conflict with the current audit in issue #2572. Moving it to the New Issue Approval column for further discussion.

**Comment by JessicaLucindaCheng** [comment]
From the Sun, Jan 30 meeting, we need to modify this issue once issue #2572 has been reviewed and approved by QA/UAT. Temporarily Moving this issue to development team meeting discussion items until tech leads can review it.

**Comment by JessicaLucindaCheng** [comment]
Since devs will be making follow up issue(s) for https://github.com/hackforla/website/issues/2572 and the alt text should actually be `alt=""`, I am closing this issue since it will become a duplicate.
