### ISSUE TITLE
Change Alt Text for Check Icon on Credit page

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#1564]
### Prerequisite
Please make sure you have read the **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue

### Overview
We want to provide updated alt text for the  `Check` icon so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the alt property value to 'Check Icon' within `_data/internal/credits/check.yml`

**From**
`alt: 'Image of Check'`
**To:**
`alt: 'Check Icon'`

#### File and Code links you will need to review this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/check.yml`

- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/90a20d1e088b0a05a286af101f82135ad4774e39/_data/internal/credits/check.yml#L10

**Comment by riddle015** [comment]
Availability for this week: 10
My estimated ETA for completing this issue: 1/23/2022

**Comment by SAUMILDHANKAR** [comment]
@hackforla/website-merge Since audit is currently going on in #2572, please let @IsaacDesigns (design lead) know about the changes.

**Comment by IsaacDesigns** [comment]
We've just finished the audit of the credits page and the only change is to the first header image.

**Comment by JessicaLucindaCheng** [comment]
Note about this issue: https://github.com/hackforla/website/pull/2714#issuecomment-1027656125
