### ISSUE TITLE
Change Alt Text for People Image on Credit page

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#1577]
### Overview
Alt text for People Image on Credit Page needs update.

### Action Items
- [ ] Change the alt attribute value to 'Team spirit concept illustration'

```diff
- alt: 'Image of People'
+ alt: 'Team spirit concept illustration'
```

### Resources/Instructions
https://github.com/hackforla/website/blob/90a20d1e088b0a05a286af101f82135ad4774e39/_data/internal/credits/people.yml#L10

**Comment by elpen84** [comment]
• Progress: Completed
• Blockers: none
• Availability: 10am - 4pm pst
• ETA: created pull request for review.
