### ISSUE TITLE
Change Alt Text for Review Icon on Credit page

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#1583]
### Overview
Alt text for Review Icon on Credit Page needs update.

### Action Items
- [ ] Change the alt attribute value to 'Review Icon'

```diff
- alt: 'Image of Review'
+ alt: 'Review Icon'
```

### Resources/Instructions
https://github.com/hackforla/website/blob/90a20d1e088b0a05a286af101f82135ad4774e39/_data/internal/credits/review.yml#L10

**Comment by jpandh** [comment]
- Issue changes made, need to open a pull request 
- Currently stuck on opening the pull request, following up at tomorrow's dev meeting
- ETA: within the next day
