### ISSUE TITLE
Change Alt Text for Security Icon on Credit page

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#1585]
### Overview
Alt text for Security Icon on Credit Page needs update.

### Action Items
- [x] Change the alt attribute value to 'Security Icon'

```diff
- alt: 'Image of Security'
+ alt: 'Security Icon'
```

### Resources/Instructions
https://github.com/hackforla/website/blob/90a20d1e088b0a05a286af101f82135ad4774e39/_data/internal/credits/secutiry.yml#L10

**Comment by Sihemgourou** [comment]
For product team : Title link is good
