### ISSUE TITLE
Vertically center the Homepage filter tags text

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1592]
### Overview
We need to vertically center the text on the homepage filter tags so that they match the original Figma design. They used to look correct, but some update apparently changed them recently.

### Action Items
- [x] View the filter tags on the [homepage](https://www.hackforla.org/#) (select any filter item and the pink tag will show up)
- [x] View the original homepage filter tags design in[ Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205) (in pink rectangle)
- [ ] Adjust the alignment of the homepage filter tags text so that they are properly vertically centered again

### Resources/Instructions
[Homepage](https://www.hackforla.org/#)
[Homepage Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205) (in pink rectangle)

How the filter tag currently looks (incorrect):
<img width="500" alt="Screen Shot 2021-05-19 at 1 23 52 PM" src="https://user-images.githubusercontent.com/67400366/118880102-54b28680-b8a6-11eb-8569-9f32759491b7.png">

How the filter tags look on Figma (correct):
<img width="350" alt="Screen Shot 2021-05-19 at 1 24 12 PM" src="https://user-images.githubusercontent.com/67400366/118880187-70b62800-b8a6-11eb-970f-dc97c65ee379.png">

**Comment by jamesberke** [comment]
@daniellex0 What native resolution is your screen? I can't seem to recreate this bug.

**Comment by daniellex0** [comment]
@jamesberke Mine is 2560 x 1600 , but it seems to be similar when I check different screen sizes in Inspect.. can you take a screenshot of how it looks on your screen?

**Comment by jamesberke** [comment]
@daniellex0 here's what it looks like for me

<img width="854" alt="Screen Shot 2021-05-23 at 11 21 10 AM" src="https://user-images.githubusercontent.com/58538332/119272166-88005880-bbb9-11eb-93ee-4cf431b8e885.png">

**Comment by qiqicodes** [comment]
This is what the filter tags look like on firefox mac 

<details>
<summary>Filter tag bug on Firefox Mac</summary>
<img src="https://user-images.githubusercontent.com/68657634/119272452-c64a4780-bbba-11eb-8cb5-5f66a7c19f2d.png">
</details>

**Comment by Aveline-art** [comment]
This is my page on Danielle's resolution. Shown on firefox on windows.

![screenshotilovescreenshots](https://user-images.githubusercontent.com/62368440/119272442-bd597600-bbba-11eb-9d21-3bd384070833.png)

**Comment by qiqicodes** [comment]
@jamesberke Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by jamesberke** [comment]
Progress: Identified the CSS that is not working and am looking for alternatives. 

Blockers: Found new issue with Firefox compatibility, but the css we are using should be compatible with modern firefox browsers so I need to do a little more digging to find what the issue is.
