### ISSUE TITLE
Match the Projects Page on Figma to the Homepage Projects layout

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1593]
### Overview
We need to make sure the Projects Page on Figma matches the Homepage projects layout so that the FIgma will match the final design of the page (since the project cards currently on the homepage will be moved to their own Projects page).

### Action Items
- [x] Review the layout of the [homepage](https://www.hackforla.org/) project cards and filter dropdowns
- [x] Match the layout of the project cards and dropdowns in the [Figma Projects page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=532%3A1454) design with the layout on the homepage 
   - [x] Replace the current desktop project cards/dropdowns layout of the projects page with the one to its left (see below) - but keep the header and footer as-is
   - [x] Add the correct mobile project cards and dropdowns layout to the mobile version of the Projects page (see below)
      - [x] Determine how to copy the mobile layout by viewing the homepage with Chrome "Inspect" in mobile view (right click > inspect)

### Resources/Instructions
[Homepage](https://www.hackforla.org/)
[Projects page Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=532%3A1454)

<img width="450" alt="Screen Shot 2021-05-19 at 11 18 01 PM" src="https://user-images.githubusercontent.com/67400366/118928964-c3b8cb00-b8f8-11eb-901d-aa3b78a4235e.png">

How mobile layout should be (screenshot from homepage in "Inspect")

<img width="378" alt="Screen Shot 2021-05-19 at 11 24 18 PM" src="https://user-images.githubusercontent.com/67400366/118929504-7721bf80-b8f9-11eb-9344-8e78bf44e7bb.png">

**Comment by daniellex0** [comment]
How to measure measurements in mobile with "inspect"-

Select both of these:
<img width="127" alt="Screen Shot 2021-05-19 at 11 28 33 PM" src="https://user-images.githubusercontent.com/67400366/118929973-08913180-b8fa-11eb-9a96-49aff5bcaff7.png">

And then you can measure to replicate the designs of the filter dropdowns in mobile:

<img width="378" alt="Screen Shot 2021-05-19 at 11 24 40 PM" src="https://user-images.githubusercontent.com/67400366/118929999-10e96c80-b8fa-11eb-8d76-428d02dd621f.png">

**Comment by SaashaG** [comment]
I am finished with this issue. Let me know if you have any comments..
![image](https://user-images.githubusercontent.com/83323065/119594051-14bd3900-bda9-11eb-91bb-2d2dc0b0e3cb.png)

**Comment by daniellex0** [comment]
Great job 👍 . Closing issue and sending to development.
