### ISSUE TITLE
Adjust margin in mobile Wins page header

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1594]
### Overview
We need to make the margin smaller between the heading and button in the Wins page in mobile, to make the header look less distorted.

### Action Items
- [x] Decrease the margin in the [Wins page](https://www.hackforla.org/wins/) header between the heading ("Let's celebrate together!) and button ("Share your wins") to **32px** (instead of 56px)

### Resources/Instructions
[Wins page](https://www.hackforla.org/wins/)
[Hack for LA site architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

How it looks now (incorrect):

<img width="367" alt="Screen Shot 2021-05-19 at 11 57 12 PM" src="https://user-images.githubusercontent.com/67400366/118933394-fe713200-b8fd-11eb-8dfc-9cd835ca7295.png">

How it should look (correct):

<img width="371" alt="Screen Shot 2021-05-19 at 11 57 26 PM" src="https://user-images.githubusercontent.com/67400366/118933417-03ce7c80-b8fe-11eb-95c4-478d054d26b8.png">

**Comment by Sihemgourou** [comment]
@daniellex0 
Please add update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by daniellex0** [comment]
Hey @Sihemgourou btw this issue is in the Prioritized Backlog and hasn't been assigned yet, so there's no update until someone self-assigns it :)

**Comment by jbubar** [comment]
IMPORTANT!! 
This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
