### ISSUE TITLE
Standardize Program Areas page header in mobile

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1596]
### Overview
We need to standardize the Program Areas page header in mobile to make it consistent with other pages and our design system.

### Action Items
- [x] Standardize the Program Areas page header in mobile (see annotated screenshot below)
   - [x] Decrease the margin between heading and top nav bar to 32px (2rem)- this should be done by just removing the margin-top: 2.25rem) - **only in mobile**
   - [x] Increase margin between heading and paragraph to 28px total - **only in mobile**
   - [x] Increase margin between header paragraph and illustration to 36px total - **only in mobile**
   - [x] Decrease the size of the header illustration to max-width 256px - **only in mobile**

### Resources/Instructions
[Program Areas page](https://www.hackforla.org/program-areas)

**How header looks now (incorrect)**

<img width="374" alt="Screen Shot 2021-05-20 at 12 54 29 AM" src="https://user-images.githubusercontent.com/67400366/118942933-0635d400-b908-11eb-9af6-db606acff1b5.png">

**How header should look (correct):**

<img width="377" alt="Screen Shot 2021-05-20 at 12 54 14 AM" src="https://user-images.githubusercontent.com/67400366/118943019-1a79d100-b908-11eb-903c-974b3749b2b2.png">

**Comment by Abel-Zambrano** [comment]
All changes are complete. I currently have 1 PR open and am waiting for it to be approved.

**Comment by jbubar** [comment]
@Abel-Zambrano 
please edit the css below tablet to look a bit more like this
```css
.program-areas-hero-svg {
    width: auto;
    height: auto;
    max-width: 70%;
}
```

This is also a good opportunity to see if you got the git stuff worked out

see also #1914 for the merged pr

**Comment by Abel-Zambrano** [comment]
@jbubar 
I just want to confirm the changes. The requested changes will put ".program-areas-hero-svg" at a max-width of 217.7px instead of the 256px that's requested, it also looks a bit smaller. Let me know if to continue with the changes, I just wanted to be sure. I added images below for reference. Thank you.
<img width="1179" alt="Screen Shot 2021-07-11 at 2 20 01 PM" src="https://user-images.githubusercontent.com/67209686/125210390-65eb9400-e254-11eb-87ed-399b01a22ac1.png">
<img width="1147" alt="Screen Shot 2021-07-11 at 2 23 06 PM" src="https://user-images.githubusercontent.com/67209686/125210395-697f1b00-e254-11eb-8cf4-8f1777d4a438.png">

**Comment by jbubar** [comment]
@Abel-Zambrano it is resizing based on the size of the screen, so if the screen is about 365px wide, then the picture will be about 256px, and if it is larger, it will be larger.. 

tbh, it looks like the figma is 80%, but danielle's picture in this issue it appears to be about 70%, so I think either would be fine.

**Comment by jbubar** [comment]
Wait... lets check in with @daniellex0  first
Danielle, do you like option 1 or 2? or something else?

<details>
    <summary>option 1: How it currently is </summary>

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/53061723/125211573-15783480-e25c-11eb-843b-f6654b8cfbba.gif)


</details>

<details>
    <summary>option 2: how it would look with max-width: percentage..</summary>

![ezgif com-gif-maker](https://user-images.githubusercontent.com/53061723/125211576-2163f680-e25c-11eb-93f8-68ceceef81ba.gif)


</details>

**Comment by daniellex0** [comment]
@jbubar Really sorry about the delay! Can you follow what other pages do (like [Join Us](https://www.hackforla.org/join))? Where there are basically two different sizes for the image?

**Comment by Abel-Zambrano** [comment]
@jbubar Do you want me to replicate what's on the "join us" page?
<h1>Join Us Page</h1>
<img width="945" alt="Screen Shot 2021-07-14 at 6 56 59 PM" src="https://user-images.githubusercontent.com/67209686/125715870-f5062cbe-3c96-4efd-8c46-08031386e506.png">
<h1>Program Areas Page w/edits matching Join Us Page</h1>
<img width="926" alt="Screen Shot 2021-07-14 at 7 05 34 PM" src="https://user-images.githubusercontent.com/67209686/125716621-e6f638a8-5998-4031-ad23-0fa773e2e5b2.png">
<h1>Program Areas Page - Currently</h1>
<img width="930" alt="Screen Shot 2021-07-14 at 6 58 02 PM" src="https://user-images.githubusercontent.com/67209686/125715967-97d96d75-9f0a-4813-866a-e49038ff08c7.png">

**Comment by jbubar** [comment]
@daniellex0 @Abel-Zambrano Yes Yes!!!
