### ISSUE TITLE
Standardize Credits page header in mobile 

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1598]
### Overview
We need to standardize the Program Areas page header in mobile to make it consistent with other pages and our design system.

### Action Items
- [x] Standardize the Credits page header in mobile (see annotated screenshot below)
   - [x] Decrease the "Credits" heading font size to 32px (convert to rem) **only in mobile sizes**
   - [x] Also (while you're at it)- increase the heading font size to 40px (convert to rem) **only in tablet sizes**
   - [x] Remove the padding surrounding the paragraph **only in mobile sizes**
   - [x] Decrease the margin between the heading and paragraph to 28px total **only in mobile sizes**
   - [x] Decrease the margin between the paragraph and illustration to 36px total **only in mobile sizes**

### Resources/Instructions
[Credits page](https://www.hackforla.org/credits/)

<img width="375" alt="Screen Shot 2021-05-20 at 1 49 36 AM" src="https://user-images.githubusercontent.com/67400366/118949511-2b2d4580-b90e-11eb-80f1-591eafa8003e.png">

**Comment by evancchen** [comment]
Progress: Still working on this issue
Blockers: None
