### ISSUE TITLE
Project Card "Status" Color Code mark

### ISSUE THREAD

**Issue by McRawly** [hackforla/website#160]
### Overview
Add styling and code for displaying a "Status" indicator as an overlay on the project card image.

![sample_overlay](https://user-images.githubusercontent.com/18178289/67347293-7c890f00-f4f6-11e9-962e-b3ffd11973da.png)

### Action Items

- [x] Add status to Project Cards (also a task for Issue #159 )
- [ ] Add status element to Current-Projects page cards (current-projects.html)
- [ ] Add status element to Projects page cards (projects.html?)
- [ ] Add styling for new element type

### Action Items
The document below documents the project statuses which will help with the first checked item above if this tasks is completed for this issue:
https://docs.google.com/spreadsheets/d/1wLKX0H-PX1U-dukOIVoueFicakDCvWaavCBJzdN-zsY/edit?usp=sharing
(View privilege only, request from PM on slack access to Google drive if you don't have modify privileges).

**Comment by sarL3y** [comment]
**First iteration:**
![Screenshot from 2019-10-28 23-05-11](https://user-images.githubusercontent.com/39248174/67826357-757b7700-fa89-11e9-9dcc-e33c04e8224b.png)
Feedback: The Status tag might be difficult to see over the image
Suggested changes: Move the tag to the right of the title, below the image

**Second iteration:**
![Screenshot from 2019-10-29 15-05-28](https://user-images.githubusercontent.com/39248174/67826224-10c01c80-fa89-11e9-8a25-84f2bd6ea6a8.png)
Feedback: The placement is good, but the colors need work

**Comment by KianBadie** [comment]
Screenshots of what the status indicators look like.

![Screenshot from 2019-11-22 19-52-03](https://user-images.githubusercontent.com/18221058/69472645-a043ad00-0d61-11ea-8388-4a8a8e1fa584.png)
![Screenshot from 2019-11-22 19-52-13](https://user-images.githubusercontent.com/18221058/69472650-a3d73400-0d61-11ea-8e44-e32712e9abcd.png)
