### ISSUE TITLE
Replicate mobile version of Getting Started page in Figma

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1600]
### Overview
We need to add a mobile version of the Getting Started page in Figma, because there is currently no mobile version on there (only desktop).

### Action Items
- [ ] Examine the current mobile version of the [Getting Started page](https://www.hackforla.org/getting-started) using Right click > "Inspect" in your browser to measure margins, font sizes, etc (ask @daniellex0 for guidance, and see more details in comment below- scroll down)
- [ ] Replicate the mobile design in the [Getting Started page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=13%3A0)
   - [ ] Use the mobile frame to the right of the purple rectangle.
   - [ ] Duplicate all elements from the desktop version of the page on Figma

### Resources/Instructions
[Getting Started page](https://www.hackforla.org/getting-started)
[Getting Started page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=13%3A0)

**Comment by daniellex0** [comment]
How to measure measurements in mobile with "inspect"-

Select both of these:
<img width="127" alt="Screen Shot 2021-05-19 at 11 28 33 PM" src="https://user-images.githubusercontent.com/67400366/118929973-08913180-b8fa-11eb-9a96-49aff5bcaff7.png">

And then you can measure specific elements of the page to replicate the designs of the Getting Started page in mobile:

<img width="283" alt="Screen Shot 2021-05-20 at 3 18 38 PM" src="https://user-images.githubusercontent.com/67400366/119055931-b0504300-b97e-11eb-9c2a-9bed16485e88.png">

**Comment by cherrijeong** [comment]
Progress: Marked area in red in [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=13%3A0)
Blockers: Getting started page possibly getting updated soon?

**Comment by qiqicodes** [comment]
@cherrijeong Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:
Availability:
ETA:

**Comment by cherrijeong** [comment]
@qiqicodes @daniellex0 

Progress: It's done and in a red marked area in [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=13%3A0) 
Blockers: The web version of the dropdowns on the very bottom (frequently asked questions) is not prototyped in Figma, so I kept them as dropdowns without content inside. If that needs to be laid out on Figma, I can come back to it. 
Availability:
ETA:

**Comment by cherrijeong** [comment]
Progress: Design's done--in a red marked area in [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=13%3A0)

**Comment by daniellex0** [comment]
Looks great, thanks Cherri!
