### ISSUE TITLE
What is needed for site backend

### ISSUE THREAD

**Issue by averdin2** [hackforla/website#1602]
### Overview
We need to determine the necessary technologies and costs for implementing a backend for the Hack for LA website. We also need to take into account the various functions that this backend would implement. For example, we have already discussed that we want a backend for creating a jobs page. 

We still need to discuss things like how teams would add jobs to this page and if we need user login. We also need to determine if there would be other functions for the backend other than the jobs page since we technically have a working platform for job postings. Would it be worth the effort just to implement a jobs page?

If any other action items are thought up, please add them to this comment.

### Action Items
- [x] Determine which technologies need to be used.
- [x] Determine the monetary costs of using these technologies.
- [ ] Determine all potential uses for having a dedicated backend.

### Resources/Instructions
REPLACE THIS TEXT - Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc.

**Comment by sayalikotkar** [comment]
Backend team:
Josh @jbubar 
Ava @Aveline-art 
Jo @josiehandeveloper 
Alex @averdin2 
Erica @erikaBell 
Akib @akibrhast

**Comment by sayalikotkar** [comment]
Update 05/29 - Josh will set up the google calendar for the team meeting on thursdays at 7 30 pm PDT and will open the issue to let the VRMS team know about the new meeting time @jbubar

**Comment by akibrhast** [comment]
###  Determine which technologies need to be used.

- Confirmed using react as front end with potentially redux
- Express as the backend
- Postgres as the database
- Ensure application is containerized with docker.

###  Determine the monetary costs of using these technologies.
- Currently negligible as we will be running on the free tiers.

**Comment by wendywilhelm10** [comment]
Bonnie said this is going to move to it's own project, separate repo, and it will have it's own team.  Currently the new project is on stand-by because it's looking for a PM.
