### ISSUE TITLE
Standardize Sitemap page header class

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1608]
### Overview
We need to standardize the Site Map page header class to make it consistent with other pages and our design system.

### Action Items
- [ ] Wrap standard ".header-container" class around Sitemap page header (instead of only the current ".header-container--sitemap" class)
   - [ ] leave any additional properties (flex-direction etc.) in that additional ".header-container--sitemap" class
   - [ ] See other pages that utilize these classes as an example- [Credits page](https://www.hackforla.org/credits/), etc.
   - [ ] Make sure the Site Map page still looks the same in mobile and desktop after changing classes

### Resources/Instructions
[Sitemap page](https://www.hackforla.org/sitemap/)

**Comment by sayalikotkar** [comment]
@grhhhh how can we help you? looks like this item got moved to links/questions/review but we are not clear why.
