### ISSUE TITLE
Conform "Not Today" logo image to proper aspect ratio and size

### ISSUE THREAD

**Issue by McRawly** [hackforla/website#161]
### Overview
Replace the "Not Today" project card with an image padded on each side to fit the square Not Today logo to the wide-aspect-ratio.

### Action Items

- [ ] Conform square logo to proper aspect ratio AND size.

See other project logo sizes for correct image size.

### Resources/Instructions
Good first issue.

**Comment by brentjayingram** [comment]
@alecg123 Can I work on this?

**Comment by McRawly** [comment]
@bingr001 yes, I've assigned you the task.

**Comment by brentjayingram** [comment]
I believe this was fixed with: https://github.com/hackforla/website/pull/166

**Comment by ExperimentsInHonesty** [comment]
Closed by pull request #166
