### ISSUE TITLE
Add and Automate meeting times in Communities of Practice page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1613]
### Overview
We need to add meeting times to the Communities of Practice page so that it is ready to share, and we need to try to automate those meetings time so that they don't need to be manually updated

### Action Items
- [x] Verify whether the meeting times in the Communities of Practice page can be automated (pull data from the same VRMS source as the schedule in the [Events page](https://www.hackforla.org/events/) and [Project pages](https://www.hackforla.org/projects/311-data))
- [x] Add meeting times to the Communities of Practice page

### Resources/Instructions
[Communities of Practice page](https://www.hackforla.org/communities-of-practice)
[Events page](https://www.hackforla.org/events/)

**Comment by wendywilhelm10** [comment]
Progress: I have made coding change.  Just need to create pull request.
Blockers: None
ETA: Will create pull request today.
