### ISSUE TITLE
Replace incorrect mini project cards in Program Areas page with correct ones

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1614]
### Overview
We need to replace the incorrect mini project cards in the Program Areas page with the correct ones, so that the page is ready to share.

### Action Items
- [x] Replace all of the mini project cards in the Program Areas page that are not consistent with the ones in the Program Areas [Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4452%3A21046), adding in the correct ones in their place

### Resources/Instructions
[Program Areas page](https://www.hackforla.org/program-areas)
[Program Areas Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4452%3A21046)

Figma file mini project cards (correct):
<img width="529" alt="Screen Shot 2021-05-30 at 2 43 35 AM" src="https://user-images.githubusercontent.com/67400366/120099564-fb8df280-c0f0-11eb-9c35-4f0e46ed4d8e.png">

Current Program Areas page mini project cards (incorrect)
<img width="600" alt="Screen Shot 2021-05-30 at 2 43 42 AM" src="https://user-images.githubusercontent.com/67400366/120099568-021c6a00-c0f1-11eb-9580-9abf0a900443.png">

**Comment by arghmatey** [comment]
@daniellex0 Hi Danielle! There are a few 'placeholder' mini project cards in the Figma file that require an image, but no such image exists in the repo. I found two placeholder image paths are currently being used on the page, but neither file actually exists in the repo: `/assets/images/projects/project-in-formation.png` and `/assets/images/projects/placeholder.jpg`. I'm wondering if you know where I can find the placeholder image to add, or if these cards are needed? Code example of placeholder card and screenshot of Figma file attached. 

```
id: 000000000 
name: #climate 
image: /assets/images/projects/project-in-formation.png 
alt: placeholder image 
link: 
```

<img width="547" alt="Screen Shot 2021-06-06 at 11 55 45 AM" src="https://user-images.githubusercontent.com/40401149/120937074-43e47c00-c6c0-11eb-9518-ee636f158608.png">


Thank you!

**Comment by arghmatey** [comment]
@daniellex0 Disregard my question! I was shown how to export images from Figma during the developers meeting today!

Thanks!

**Comment by daniellex0** [comment]
@arghmatey Got it, great!
