### ISSUE TITLE
Create a document to become dev team leadership

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1623]
### Overview
Need a roadmap to leadership, so that folks can move into different leadership roles in the org!

### Action Items
- [x] make a draft
- [x] discuss with leadership... Bonnie
- [x] Finalize google doc draft
- [x] Create a wiki article from draft
  - [x] Complete wiki article first draft
  - [x] Obtain feedback for first draft
  - [x] Complete wiki article second draft
  - [x] Obtain feedback for second draft
  - [x] Finalize wiki article
  - [x] Request that issue be closed

### Resources/Instructions
[google doc draft](https://docs.google.com/document/d/1fiFSfDClz3156Sp6aFyPcHM8Jq4h9PC7jZXtQhXhwi4/edit?usp=sharing)

**Comment by Aveline-art** [comment]
ToDo:

- [ ] Add some way to contact people regarding blockers to leadership
- [x] Get feedback from previous leads that had graduated from H4LA.
- [x] Check in with @Olivia-Chiong and see if this process follows the projects she manages
- [x] Contact other teams for their process, and training for interdisciplinary skills of new members prior to moving to other teams
- [x] Gain feedback during development meeting

**Comment by Aveline-art** [comment]
Possible technical features:

- Use github actions to track contributions (will this require a backend or a local file storage)?
- Pathways for various items such as a way to assign mentors or ways to assign larger issues
- How will people view their currently leadership "checklist"? Will it be part of the website? Or live elsewhere?

**Comment by GLRJr** [comment]
Please review the [google document](https://docs.google.com/document/d/1fiFSfDClz3156Sp6aFyPcHM8Jq4h9PC7jZXtQhXhwi4/edit)
add some comments and unassign yourself from this issue.
we want to create a very clear pathway to team leadership and beyond. And we would like your feedback.

**Comment by wendywilhelm10** [comment]
6/6/2021 - We will leave this on for a week to receive responses and then create an issue to add this information as a wiki.

**Comment by jbubar** [comment]
@KianBadie @cnk @drubgrubby  we would love your opinion on this issue.

**Comment by ghost** [comment]
Per Olivia at PM CoP meeting, I am adding the following suggestions for non-technical skills for dev leadership:
-Ability to teach others (code/processes), not in the formal sense, more like share knowledge
-Ability to communicate with non-tech

**Comment by natenateo** [comment]
What about a required reading list? I would suggest a scrum book, Annie Duke "How to Decide", Trout "Positioning: The Battle for Your Mind", and Peter Thiel "Zero to One".

**Comment by Aveline-art** [comment]
Suggestion:

Mentors should take a part in reviewing their mentee's first and second PR review.

**Comment by drubgrubby** [comment]
There's a ton of useful and important things on that document, and I think it will be really helpful for people who want to be team leaders.  

I think the challenge is separating what are actually "steps to leadership" from everything else so it's clear what people who want to be team leaders can work on.    A lot of things on that document - completing onboarding, doing increasingly difficult issues, learning to write an issue - seem to be things I would categorize as "steps to being a good team member". Obviously you have to do those first, but they don't feel like they are necessarily steps to leadership.   

Perhaps there's a phase 1 that's just all of the things that you want to accomplish to be a good team member.  If you're happy there, you can just keep coding away, but if you want to level up, you would do these additional steps to move to the next level, and so on (as the bullet points at the bottom suggest). 

I'm a simple person, so I would make a simple list, something like: 
- Do more and more complicated PR reviews.  (I'm not sure you can put a number on this; you keep doing it until the people "above you" aren't correcting your reviews) 
- Know the code base
- Mentor other team members
- Lead team meetings
- Have a knowledge of where the major issues stand, who is working on them, and how to help move them forward. 
- Become a resource for people who are stuck, either to help them, or direct them to help. 

Most of that is in the document, and I think a good edit will go a long way to making the steps clear.   

Maybe make it a little clearer as to what are the steps that are specifically for people who want to be team leaders.  
And then separately, what are tools, tips and techniques for accomplishing those steps.
And maybe make it clear that it's perfectly okay not to be a team leader, if that's not what you're after right now. 
Also that all leaders are different, and that good leaders use their unique qualities to become good leaders; don't try to imitate someone else, but be the leader that you have inside you.  

But really, there's just one step to website team leadership: saying yes when the current leadership moves on. I think this document will help prepare people for that moment.  

Nice work everyone!

**Comment by akibrhast** [comment]
I have made a wiki in regards to this, feel free to edit and comment on it.

https://github.com/hackforla/website/wiki/Becoming-A-Developer-Team-Lead-At-Hack-For-LA

**Comment by Aveline-art** [comment]
Agenda for Document Finalization Meeting, Friday, June 10, 2021 @ 6 PM PST (9 PM EST)

Below is the agenda for the emergency meeting. Several new points were identified and summarized during the Backend meeting on June 9th, detailed below. They are to be reviewed along with the [STEPS TO HFLA WEBSITE LEADERSHIP document ](https://docs.google.com/document/d/1fiFSfDClz3156Sp6aFyPcHM8Jq4h9PC7jZXtQhXhwi4/edit).

Once discussion is completed, work on the first draft of the leadership documentation can proceed.

- [x] Discuss above feedback on leadership document
- [x] Decide on whether there should be a Phase 1 (how to be a good team member) and Phase 2 (how to train yourself to become a leader) in our final wiki article
- [x] Decide on the which points in the google doc to include in final wiki article
- [x] Should these key points be included into our final wiki article? If so, where?
  - [x] Becoming a leader at HackForLA prepares you to be a junior developer in the working world
    - [x] Intro
    - [x] Phase 1
    - [x] Phase 2
  - [x] The ability to create projects from scratch is the hallmark of a mid-level developer
    - [x] Intro
    - [x] Phase 1
    - [x] Phase 2
  - [x] The leadership pipeline are steps to build one-self into a competent developer
    - [x] Intro
    - [x] Phase 1
    - [x] Phase 2
  - [x] A junior's PR reviews need to be consistently flawless (ie, seniors agree with your assessment) before becoming a leader
    - [x] Intro
    - [x] Phase 1
    - [x] Phase 2
  - [x] Becoming a leader requires drive and grit
    - [x] Intro
    - [x] Phase 1
    - [x] Phase 2
  - [x] Becoming adept at writing competent code requires competency in reviewing the code of others
    - [x] Intro
    - [x] Phase 1
    - [x] Phase 2
  - [x] A good coder must go through several checks when examining their own code: correctness in design and code, follows standards, and is readable and appropriately commented
    - [x] Intro
    - [x] Phase 1
    - [x] Phase 2
  - [x] The capabilities of a leader include: ability to mentor, interdisciplinary skills, and familiarity with the codebase
    - [x] Intro
    - [x] Phase 1
    - [x] Phase 2
  - [x] Mentors should take a part in reviewing their mentee's first and second PR review. 
    - [x] Intro
    - [x] Phase 1
    - [x] Phase 2

**Comment by akibrhast** [comment]
I have copy pasted the entirety of google docs into a wiki page
- https://github.com/hackforla/website/wiki/Being-A-Part-Of-Hack-For-LA-Team

We can use this during our meeting tonight to do markdown edits and finalizations
- https://stackedit.io/app#

**Comment by Aveline-art** [comment]
Eureka! 20 days later, this is done! ([link here](https://github.com/hackforla/website/wiki/Being-a-Part-of-the-Hack-For-LA-Team)). @akibrhast did a lot of work before I brushed up some of the points. If anyone can, we would love some feedback, comments, and correction on this draft. Feel free to @ anyone! I am overjoyed to finally have this done!

**Comment by akibrhast** [comment]
I believe this issue can now be closed.

**Comment by Sihemgourou** [comment]
Closed because now we move to getting feedback (see issue https://github.com/hackforla/website/issues/1749))
