### ISSUE TITLE
Add Margin to Homepage Sections

### ISSUE THREAD

**Issue by alecg123** [hackforla/website#163]
### Overview
On homepage, when one clicks the menu links and go to the subsections of the page, (ex: # projects) the browser brings the top of the screen to the start of the section and the menu bar consequently is displayed over the section heading text. 

### Action Items
- [ ] Add margin to proper elements (menu or sections) so this functionally looks good.

If guidance is needed, find a front end developer, as the issue creator is not sure of the proper approach. 

### Resources/Instructions
To see the issue, go to homepage, click a link in the menu and see how when the page jumps to the section, the text is covered.

**Comment by brentjayingram** [comment]
Can I work on this?
