### ISSUE TITLE
Figure out how to link to a guide pdf on Toolkit page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1635]
### Overview
We need to figure out how to link out to guide pdf's from the [Toolkit page](https://www.hackforla.org/toolkit/) guide cards, as an interim solution until all guide pages have their own webpages

### Action Items
- [ ] Figure out potential ways to link out to a pdf (without requiring users to download the pdf) from the [Toolkit page](https://www.hackforla.org/toolkit/) guide cards
   - [ ] Check out some potential options mentioned [here](https://webapps.stackexchange.com/questions/48061/can-i-trick-github-into-displaying-the-pdf-in-the-browser-instead-of-downloading#:~:text=You%20can%20host%20the%20file,you%20can%20see%20github%20pages.&text=Create%20a%20repo%20named%20USERNAME,to%20publish%20a%20User%20Page.) 
- [ ] List out potential options and examples for devs/Bonnie to choose from

### Resources/Instructions
[Toolkit page](https://www.hackforla.org/toolkit/)
[StackExchange discussion](https://webapps.stackexchange.com/questions/48061/can-i-trick-github-into-displaying-the-pdf-in-the-browser-instead-of-downloading#:~:text=You%20can%20host%20the%20file,you%20can%20see%20github%20pages.&text=Create%20a%20repo%20named%20USERNAME,to%20publish%20a%20User%20Page.)

**Comment by jamesberke** [comment]
@daniellex0 if this is a temporary solution I think the best way link the PDF's is to host them as static assets and use an <href> tag to link them. 

I did this on my portfolio site for my resume. If you want to see it's here [portfolio](https://www.jamesberke.dev)

**Comment by daniellex0** [comment]
@jamesberke Awesome, thank you for the head's up about this!!
