### ISSUE TITLE
Update Project Card on the HackforLA website [Shared Housing Project]

### ISSUE THREAD

**Issue by Rankazze** [hackforla/website#167]
### Overview
Provide collateral for the HackforLA website

### Action Items
 
  - [ ]  What you are looking for skills wise: please omit all positions/skills.  Now looking for Graphics Designer
  - [ ]  Partner(s) LA Family Housing
 - [ ]   Update project Card on website

### Resources/Instructions
See project cards on the hackforla.org website for examples

**Comment by ExperimentsInHonesty** [comment]
@McRawly Please assign this to one of the developers.  When its been completed, and pushed to the website, please @ me here so I can move it back to the project board for Shared Housing.

**Comment by StephenVNelson** [comment]
I am currently working on this.
