### ISSUE TITLE
Develop Projects Page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1671]
### Overview
We need to develop the Projects page so that our project cards can move there from the home page, and it can eventually be linked to from the homepage/top nav.

### Action Items
- [x] View Projects page design on [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=532%3A1454) (in blue rectangle)
- [x] Add the new header, basing the code off of design system-standardized page headers like the [Credits page](https://www.hackforla.org/credits/) header (using standard ".header-container" class, etc)
- [x] Duplicate all of the project cards and filter functionality from the [homepage](https://www.hackforla.org/#) onto the new Projects page 
   - [x] Don't change anything on the homepage- it will stay as-is until the homepage redesign is finished, and only then it will link out to the new projects page
- [x] Add new header image to [credits page](https://www.hackforla.org/credits/) (image credit info is in top right corner of blue rectangle in Projects page [Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=532%3A1454))

### Resources/Instructions
- Projects page design on [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=532%3A1454) (in blue rectangle)
- [HfLA site architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)
- [How to create a page on HfLA website](https://github.com/hackforla/website/wiki/How-to-create-a-page-on-Hack-for-LA-website)
- [Template of credit.yml](https://github.com/hackforla/website/wiki/Template-of-a-credit.yml-file-(for-Credits-page))
- [Credits page](https://www.hackforla.org/credits/)

**Comment by wendywilhelm10** [comment]
Progress: Started and have a couple of questions.
Blockers: Need some questions answered.
Availability: Open
ETA: Week or two

**Comment by Sihemgourou** [comment]
@wendywilhelm10  who do you need to answer the question ? Product, design, devs or others ?

**Comment by aliibsin** [comment]
@wendywilhelm10 could you please ask your question to the HfLA slack channel and @ the people you want to answer it? that way other people may be able to answer your question as well.

**Comment by wendywilhelm10** [comment]
Here are pictures from my branch for the requested changes:
![projects](https://user-images.githubusercontent.com/44912633/122323178-afb2ba00-cef4-11eb-815c-b4004a417bb2.PNG)
![credits_after](https://user-images.githubusercontent.com/44912633/122323190-b4776e00-cef4-11eb-92c6-26b72ed32809.PNG)
Here is the existing credits header part:
![credits_before](https://user-images.githubusercontent.com/44912633/122323223-bfca9980-cef4-11eb-8692-cd7096e1419b.PNG)

The question I have is about the size of the new picture for the new Projects page and the Credits page.  I copied the new picture from Figma and saved is as an svg file since other images were of the same type.  Is the image the correct size?  Did I copy it correctly from Figma?

**Comment by daniellex0** [comment]
@SaashaG worked on this so I'll let her respond :)

**Comment by SaashaG** [comment]
Hi. I think its safe to assume its the correct sized image, if you copied it from Figma.

**Comment by daniellex0** [comment]
@wendywilhelm10 Also Wendy as long as it has the same specs as Figma it should be right:

Mobile:

<img width="244" alt="Screen Shot 2021-06-19 at 10 01 35 PM" src="https://user-images.githubusercontent.com/67400366/122662713-f5b48b80-d149-11eb-99fc-a068b5ed83b9.png">

Desktop:

<img width="279" alt="Screen Shot 2021-06-19 at 10 01 28 PM" src="https://user-images.githubusercontent.com/67400366/122662714-f816e580-d149-11eb-816c-81858b8dcb48.png">

**Comment by wendywilhelm10** [comment]
Progress: Almost done.
Blockers: None.
Availability: Open
ETA: Day or two

**Comment by wendywilhelm10** [comment]
Progress: Created pull request and made minor change based on feedback.
Blockers: Discussion about one or two svg images.
Availability: Open
ETA: When decision is made about images.

**Comment by ExperimentsInHonesty** [comment]
@averdin2  mentioned that he provided additional guidance to @wendywilhelm10 on the PR on Tuesday 7/6.  Waiting for @wendywilhelm10 to update this issue with ETA

**Comment by ExperimentsInHonesty** [comment]
Please provide update
1. Progress: made most of changes noted in PR
2. Blockers: have one question on one change in PR
3. Availability: open
4. ETA: this week

**Comment by wendywilhelm10** [comment]
Progress: I incorporated changes into my changes and pushed back to GitHub.  Should be availabe for review again.
Blockers: None
Availability: available
ETA: Ready to reviewed again
