### ISSUE TITLE
Propose a new system for creation of issues regarding updates to Project Profile cards

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#1686]
### Overview 
Product Managers of the Hack for LA projects have indicated that the current system for updating their project cards on the website is cryptic, cumbersome, and error prone. Therefore, the development team has been in talks about a potential alternative.

For more information on our current process for updating cards, please see this related issue:
[#1680 Update Project Profile card instructions and process ](https://github.com/hackforla/website/issues/1680)

### Details 
Details to be added after below discussion concludes.

### Discussion items:
- [x] What about the current system is not working for the Project Managers? What is already working?
- [x] What can we propose to address current concerns?
- [x] Is our proposal feasible? In the short term?
- [x] understand what the process was for how the developer decided what to put for the catagories (they are very simialar to the actual catagories)
- [x] understand how did the PR get past the person reviewing it and what do we look for when we review changes on the project cards
- [x] figure out how to change our process so that the categories are adhered to.
   - [x] How might we ensure the the categories used are the ones that are approved?
   - [x] How might we automate as much of this as possible?

Once we have discussed the above points, we need to decide whether to:
- [x] Create a proposal and get feedback
OR
- [ ] Keep the current system

### Resources  
[#1680 Update Project Profile card instructions and process](https://github.com/hackforla/website/issues/1680)
[Current PM Template](https://github.com/hackforla/product-management/issues/new?assignees=&labels=documentation%2C+feature%3A+project+profile+card&template=update-project-profile---name-of-project-.md&title=Update+Project+Profile%3A+%5Bname+of+project%5D)
[Template of a project.md file](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)
[Directory housing current project.md files](https://github.com/hackforla/website/tree/gh-pages/_projects)
#### List of allowable categories
1. Business Analyst
2. Content
3. Data
4. Development
5. Ops
6. PM
7. QA
8. SEO/Marketing
9. UI/UX

Related issues : 
https://github.com/hackforla/product-management/issues/263
https://github.com/hackforla/product-management/issues/266
https://github.com/hackforla/website/issues/1343

**Comment by Aveline-art** [comment]
@daniellex0 Hi Danielle! This is the issue/discussion for the long term solution to addressing PM concerns regarding updating Project Profile cards. Feel free add anything to the discussion here or join us for the backend meeting. ~~We will review and revisit this topic starting next backend meeting.~~ June 6, 2021, @Aveline-art note: project evolved into a separate team.

**Comment by daniellex0** [comment]
Thank you so much for creating this issue @Aveline-art ! So I actually took a stab at drafting an issue because I discussed this with the PM's at their Community of Practice meeting, and they were asking for the new language asap. 

Everyone please feel free to add any thoughts/edits/etc- I sent it to Josh a few days ago but would love feedback from everyone (the PM's are also reviewing this apparently):

https://github.com/hackforla/product-management/issues/263

FYI it's written in a pretty confusing way because it addresses both the PM's that are updating their project info, and the brand new devs that get assigned these as their Good First Issue lol.

I also had a question about Github issues- a template issue for updating project info apparently exists on the PM Community of Practice Github repo too, and sometimes they create the issues on there. Is it possible for them to transfer an issue created on that repo, onto our repo? Or do they need to post the issue here? 

They don't have edit permissions in our repo so they can't add any labels or add them onto our Project board- which is why in the template issue above, I added instructions for the PM's to post on our Slack channel when as issue is ready to post, so that one of us can add the right labels/add it to the Project Board.

Obviously if there will be an automated way to do all of this in the future, that would be amazing. But in the meantime, a template issue that somehow addresses both PM's and brand new devs on the team will suffice I guess...?

**Comment by akibrhast** [comment]
> The solution is : add list of approved categories to project template file https://github.com/hackforla/website/wiki/Template-of-a-project.md-file
> - Developers should check looking for updates in that file. 
> - All of the items in the template file that have predefined arrays should have all of their values listed in the template file.
> - PM's should check all project cards changes against template.
> - Project cards update issue template 
> #### Original Source - https://github.com/hackforla/website/issues/1265#issuecomment-846598663 by @Sihemgourou 

---

> 06/06: Create new strike team, led by Sihem to reimagine the process of PMS adding & updating their project cards.
> 
> Team to work on this:
> Champion- Sihem
> Developers- @erikaBell (backend), Sarah (frontend)
> UX- ? (@daniellex0 to check in the UX/UI community of practice)
> Bonnie & Olivia
> PMs from the friday community of practice meeting
> #### Original Source - https://github.com/hackforla/website/issues/1265#issuecomment-855435299by @sayalikotkar

**Comment by daniellex0** [comment]
UX designers joining strike team meeting will be @daniellex0 and @ ryan curtis on Slack (from UX Community of Practice/Expunge Assist)

**Comment by Sihemgourou** [comment]
Related issues : 
https://github.com/hackforla/product-management/issues/263
https://github.com/hackforla/product-management/issues/266
https://github.com/hackforla/website/issues/1343

**Comment by Sihemgourou** [comment]
1. Progress : created a google form and checked it with Bonnie and other pms => we need to find a better way to navigate through the form (maybe use a different tool) https://forms.gle/ZrDPKYN3i8BCXj4a9
2. Blockers : none
3. Availability: 2h
4. ETA : 08/15

**Comment by ExperimentsInHonesty** [comment]
We created a new form that project leads use when updating their projects: [Project Profile Card review and update](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D)

It seems to be working pretty well.  The next step is to figure out how issue that the product fills out go through the approval process and gets turned into an issue for Devs.

We could do it as two separate processes with an issue template for the devs, but then the original author (the project lead) is no longer on the issue.  Which would be ok, if we had a checkbox for notifying them when its time for UAT (after the merge) or after its on dev (once we have a dev and prod).  

Adding this to the dev/PM agenda to discuss. Project Profile Card review and update

**Comment by ExperimentsInHonesty** [comment]
We need a template to use, where we can just delete the items we don't need


```
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The [Replace NAME OF PROJECT] project page needs to be updated to reflect accurate project information. 

### Action Items
- [ ] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/[Replace MD FILE NAME]` file and find the `partner` variable.
- [ ] Add the following partner
  - [ ] [Replace NAME OF PARTNER]
- [ ] Remove the following members and their information
  - [ ] [Replace NAME OF PERSON]
- [ ] Verify the changes by viewing the [Food Oasis project page](https://www.hackforla.org/projects/[Replace PAGE LOCATION) and the Food Oasis card on the [projects page](https://www.hackforla.org/projects/) on your local environment and include a screenshot with your pull request

### Resources
- [[Replace NAME OF PROJECT].md](https://github.com/hackforla/website/blob/gh-pages/_projects/[REPLACE MD FILE NAME.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

```

**Comment by ExperimentsInHonesty** [comment]
Until we have a wiki, we will need a link to the comment above at the bottom of this issue form template https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml

- I have created an ER to add that https://github.com/hackforla/website/issues/4778

**Comment by ExperimentsInHonesty** [comment]
We have made great progress on our processes for project changes and have reached the limit of what is feasible with this sites framework, and we will be closing this issue.  The next major step is product leads being able to make changes in VRMS and have leadership review and accept or reject them there.
