### ISSUE TITLE
Embedding Code for America donation box to HackForLa website

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#1687]
### Overview 
The [HackforLA Join Us page](https://www.hackforla.org/join) contains a section titled "Make a donation to Hack for LA". Within this section is a link to [Code For America's donation page](https://www.codeforamerica.org/donate/), where potential donors can submit their donation. This creates a two step process to donate to our parent organization. We propose that it might be more favorable to turn this into a one step process.

### Details 
Currently, we propose, at @daniellex0's behest, that we embed the [donation widget](https://donorbox.org/embed/codeforamerica) on the [Code For America's donation page](https://www.codeforamerica.org/donate/) into the "Make a donation to Hack for LA" section. This will allow users to donate directly rather than go through a link.

### Potential action items
- [ ] Receive permission from Code For America to embed their widget to our site
- [ ] Update the "Make a donation to Hack for LA" section with relevant information for potential donors from Code for America
- [ ] Get input from the design team on how the webpage should look

### Resources  
[HackforLA Join Us page](https://www.hackforla.org/join)
[Code For America's donation page](https://www.codeforamerica.org/donate/)
[donation widget](https://donorbox.org/embed/codeforamerica)

**Comment by daniellex0** [comment]
Thanks for creating this issue! I will say, this was brought up as an option by a PM - but they mentioned, and I agree, that Bonnie might not want this at all. So there is a big chance this will be a no-go, but it's good to double check just in case!

**Comment by Aveline-art** [comment]
### June 6, 2021

Closed due to feasibility issues and soon to be obsolete due to HackForLA 501(c)(3) designation with own private donation box.
