### ISSUE TITLE
Standardize technology name in Not Today project card

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1690]
### Overview
We need to standardize the name of a technology (React Native to just React) in the [Not Today](https://www.hackforla.org/projects/not-today) project description so that it is standardized and doesn't throw off the technology filter.

### Action Items
- [ ] Under technologies in the [Not Today](https://www.hackforla.org/projects/not-today) project description, change React Native to just **React**
   - [ ] Project file name: not-today.md

### Resources/Instructions
[Template of a project.md file](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)

**Comment by Sihemgourou** [comment]
@daniellex0 this needs to be included on the project card issue, we need to create a list of standardized technologies to avoid this type of issue from reiterating.

**Comment by Sihemgourou** [comment]
@alfredosumosav 
Please add update
1. Progress
2. Blockers
3. Availability
4. ETA
