### ISSUE TITLE
Update Project Membership - Hack for LA Website

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1691]
### Overview
We need to update the membership listing on the [Hack for LA Website project page ](https://www.hackforla.org/projects/website)

### Action Items
**All Hack for LA website team members:**

- [ ] Submit the following information in a new comment below:
- **name:** First Last
- **role:**
- **slack:** 'https://hackforla.slack.com/team/xxxxxx' **(see Slack note below)
- **github:** 'https://github.com/githubusername'

**Slack:
To find your Slack link, click on your slack username- this should give you a popup window with your user picture, name, and a link to "View full profile". Click on "View full profile". That pane gives you the options message, call, and more. Click on "more" and you should be shown "Copy member ID" followed by the actual id. This is the id you need to use in the slack url, e.g. https://app.slack.com/team/<member_id_here

Development
- [ ] Update the membership listings on [Hack for LA website's project page](https://www.hackforla.org/projects/website)

### Resources/Instructions
[Template of a project.md file](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)

**Comment by Sihemgourou** [comment]
Name : Sihem Gourou
Role : Product manager 
Slack : https://hackforla.slack.com/team/U021GM545UG
Github : https://github.com/Sihemgourou

**Comment by sayalikotkar** [comment]
Daneille will add a slack id column in the team roster & the team has to update their own slack ids in there
