### ISSUE TITLE
Standardize the Guide pages in mobile

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1692]
### Overview
We need to standardize the existing Guide pages while we wait for the future guide page updates to be implemented

### Action Items
- [ ] In the [2FA guide page](https://www.hackforla.org/guide-pages/2FA) **only in mobile**, adjust the margin around the page cards (here called "section containers") to margin: 0 0 7% 0 (instead of 2% 12%)
- [ ] This is for all screen sizes (mobile/desktop etc) - wrap a standard ".content-section" class around the body of the [Build a Survey guide](https://www.hackforla.org/guide-pages/survey-reporting-dashboard-guide) page
   - [ ] Follow the example of the ".content-section" class in the 2FA guide
- [ ] After the above step # 2 is finished, adjust the margin around the "section containers" to margin: 0 0 7% 0 (instead of 2% 12%) in the [Build a Survey guide](https://www.hackforla.org/guide-pages/survey-reporting-dashboard-guide) page (**only in mobile**)
- [ ] Try to make the accordion on the bottom of the [2FA guide page](https://www.hackforla.org/guide-pages/2FA) **in mobile** look more like the accordion on the bottom of the [Getting Started page](https://www.hackforla.org/getting-started) **in mobile** (the pink arrows aren't supposed to be so close to the lines)

### Resources/Instructions
[2FA guide](https://www.hackforla.org/guide-pages/2FA) page
[Build a Survey guide](https://www.hackforla.org/guide-pages/survey-reporting-dashboard-guide) page
[Getting Started page](https://www.hackforla.org/getting-started)

Mobile guide pages now (incorrect):

<img width="376" alt="Screen Shot 2021-06-06 at 12 27 11 AM" src="https://user-images.githubusercontent.com/67400366/120916364-0949f780-c65e-11eb-8dcd-11fd9ff6ca9c.png">

How mobile guide pages should look (correct):

<img width="377" alt="Screen Shot 2021-06-06 at 12 27 03 AM" src="https://user-images.githubusercontent.com/67400366/120916351-018a5300-c65e-11eb-8d21-37f4af8d0f97.png">

Accordion in 2FA guide (arrows too close to lines):

<img width="376" alt="Screen Shot 2021-06-06 at 12 21 00 AM" src="https://user-images.githubusercontent.com/67400366/120916307-c38d2f00-c65d-11eb-981c-47e41178d745.png">

Accordion in Getting Started page (correct):

<img width="370" alt="Screen Shot 2021-06-06 at 12 20 47 AM" src="https://user-images.githubusercontent.com/67400366/120916315-ca1ba680-c65d-11eb-8e7b-2281a592da8b.png">

**Comment by Abel-Zambrano** [comment]
IMPORTANT!! 
This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)

**Comment by ExperimentsInHonesty** [comment]
This work will not be done because we are changing from the current format to the new happen.
