### ISSUE TITLE
Adjust size of header CTA button on homepage

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1694]
### Overview
We need to adjust the size of the large header button on the homepage because now that the text is shorter ("Join Us"), the button isn't large enough/doesn't draw enough attention compared to the button below it.

### Action Items

- [x] A new standard button class  "**.btn-xl-long**"  should be added to the design system via [_buttons.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_buttons.scss) (similar to how we have a btn-md-narrow). 
- [x] The properties for it should be:

.btn-xl-long {  
height: 72px;  
padding: 0 80px;  
border-radius: 100px;  
font-size: 1.5rem;

  @media #{$bp-below-tablet} {    
height: 60px;    
padding: 0 70px;    
border-radius: 60px;    
font-size: 1.25rem;  }}

- [x] This new standard button class should be applied to the large [homepage](https://www.hackforla.org/#) Join Us CTA button (replacing .btn-xl)

### Resources/Instructions
[Homepage](https://www.hackforla.org/)
[_buttons.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_buttons.scss)
[HfLA Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)
[Standardized Components] (https://github.com/hackforla/website/wiki/Standardized-Components)

How button looks now (too small):

<img width="500" alt="Screen Shot 2021-06-06 at 12 56 15 AM" src="https://user-images.githubusercontent.com/67400366/120917134-43b59380-c662-11eb-81f3-2be15053ee6a.png">

How button should look:

<img width="500" alt="Screen Shot 2021-06-06 at 12 56 27 AM" src="https://user-images.githubusercontent.com/67400366/120917139-4adca180-c662-11eb-8759-96e68f7bf9ab.png">

**Comment by HiThereImCam** [comment]
@daniellex0 Hi Danielle, the "Share your wins" button in the wins-hero.html shares the btn-xl class. What would you like me to do with the "Share your wins" button?

**Comment by daniellex0** [comment]
@HiThereImCam oh shoot, good catch... hmm.. I'l ask about this as the UX meeting tomorrow, and will get back to you on this!

**Comment by HiThereImCam** [comment]
@daniellex0 Hi Danielle, any update on this?

**Comment by daniellex0** [comment]
Yes! I'd like there to be a new standard button size- "**.btn-xl-long**"  (similar to how we have a btn-md-narrow). 

The properties for it should be:

.btn-xl-long {  
height: 72px;  
padding: 0 80px;  
border-radius: 100px;  
font-size: 1.5rem;

  @media #{$bp-below-tablet} {    
height: 60px;    
padding: 0 70px;    
border-radius: 60px;    
font-size: 1.25rem;  }}

And that class should be applied to the homepage Join Us CTA button

Btw this new class should be added to [_buttons.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_buttons.scss)

Thank you for following up @HiThereImCam ! 

(Just updated the issue with all of this new information)

**Comment by Zak234** [comment]
Should the .btn xl-long class replace the xl class or just create a new .btn xl-long class and change the button from xl to xl-long?

**Comment by daniellex0** [comment]
@Zak234 the second option please! Not replace, but instead it will be an additional class. And the homepage Join Us button will then change from btn-xl to btn-xl-long. Thanks!

**Comment by Zak234** [comment]
Got it, thanks for the clarification!
