### ISSUE TITLE
Require the Wins page submissions include text

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1695]
### Overview
We need to require that submissions for the Wins page include text, so that we don't have any blank wins cards once the badge icons are implemented (for ex, Abigail Hipps' Wins card will be blank and only include one icon)

### Action Items
- [x] Find a way to require that the Wins page Google form submissions include text (not only checking off the checkboxes)

### Resources/Instructions
[Wins page](https://www.hackforla.org/wins/)

Example of a win card without any text (we should prevent these)

<img width="666" alt="Screen Shot 2021-06-06 at 1 07 54 AM" src="https://user-images.githubusercontent.com/67400366/120917409-ffc38e00-c663-11eb-9a14-72a0f65d9884.png">

**Comment by akibrhast** [comment]
Brief Overview has now been marked as required. This should fulfill the above requested requirement. @daniellex0 
![image](https://user-images.githubusercontent.com/32349001/121541078-f6745180-c9d4-11eb-9175-ea6ce358fd59.png)

**Comment by daniellex0** [comment]
@akibrhast Perfect, thank you!

**Comment by akibrhast** [comment]
Resolved!
