### ISSUE TITLE
Update mobile version of Events page in Figma

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1697]
### Overview
We need to update the mobile version of the [Events page on Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94) so that it is consistent with the website

### Action Items
- [x] Examine the current mobile version of the [Events page](https://www.hackforla.org/events/) using Right click > "Inspect" in your browser to measure margins, font sizes, etc (ask @daniellex0 for guidance, and see more details in comment below- scroll down)
   - [x] Another good option is to set the screen size to "iPhone X" in inspect, take a screenshot of the full section you are trying to replicate, past it to the Figma and set the width 375px (our standard mobile mockup size). Then design on top of the screenshot to ensure accurate sizes.
- [x] Make a duplicate of the  the mobile designs in the [Events page on Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94) (in red rectangle), and update the new copy of the designs so that they are as close as possible to the website

### Resources/Instructions
[Events page](https://www.hackforla.org/events/)
[Events page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=62%3A94)

**Comment by daniellex0** [comment]
How to measure measurements in mobile with "inspect"-

Select both of these:
<img width="127" alt="Screen Shot 2021-05-19 at 11 28 33 PM" src="https://user-images.githubusercontent.com/67400366/118929973-08913180-b8fa-11eb-9a96-49aff5bcaff7.png">

And then you can measure specific elements of a page in mobile by hovering over them and/or click on them and looking at the styles/css panel of inspect:

<img width="283" alt="Screen Shot 2021-05-20 at 3 18 38 PM" src="https://user-images.githubusercontent.com/67400366/119055931-b0504300-b97e-11eb-9c2a-9bed16485e88.png">

Ask @daniellex0 for any help with this

**Comment by daniellex0** [comment]
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
@kristine-eudey Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by kristine-eudey** [comment]
Issue completed, Figma file has been updated and now reflects current live Events page on mobile. 

[Events Page](https://www.hackforla.org/events/)
[Figma file - Events Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=12942%3A95065)
