### ISSUE TITLE
Replicate mobile version of Project page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1698]
### Overview
We need to add a mobile version of the Project page in Figma, because there is currently no mobile version on there (only desktop).

### Action Items
- [ ] Examine the current mobile version of the [Project page](https://www.hackforla.org/projects/100-automations) using Right click > "Inspect" in your browser to measure margins, font sizes, etc (ask @daniellex0 for guidance, and see more details in comment below- scroll down)
- [ ] Replicate the mobile design in the [Project page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=7891%3A0)
   - [ ] Use the mobile frame to the right of the pink rectangle.
   - [ ] Duplicate all elements from the desktop version of the page on Figma

### Resources/Instructions
[Project page](https://www.hackforla.org/projects/100-automations)
[Project page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=7891%3A0)

**Comment by daniellex0** [comment]
How to measure measurements in mobile with "inspect"-

Select both of these:
<img width="127" alt="Screen Shot 2021-05-19 at 11 28 33 PM" src="https://user-images.githubusercontent.com/67400366/118929973-08913180-b8fa-11eb-9a96-49aff5bcaff7.png">

And then you can measure specific elements of the page to replicate the designs of the Project page in mobile:

<img width="283" alt="Screen Shot 2021-05-20 at 3 18 38 PM" src="https://user-images.githubusercontent.com/67400366/119055931-b0504300-b97e-11eb-9c2a-9bed16485e88.png">

**Comment by Sihemgourou** [comment]
@ktlevesque19 @daniellex0 we discovered some problems with the live version of the page. Please don't replicate this on the figma mobile version. I am creating some issues to correct the bugs. 

<details>
<summary>bug getting started card</summary>

![Capture d’écran 2021-06-24 à 23 06 39](https://user-images.githubusercontent.com/55627107/123334580-9688b980-d543-11eb-9716-fa6e242618d4.png)

</details>

<details>
<summary>bug with the alignment</summary>

![Capture d’écran 2021-06-24 à 23 26 49](https://user-images.githubusercontent.com/55627107/123334872-0008c800-d544-11eb-9865-baf2057685a2.png)

</details>

**Comment by ktlevesque19** [comment]
1. Progress: About 80% done creating the mobile page
2. Blocks: Been busy this week, but am back on track. Also looks like the images used on the site are different than what's in the Figma document, not sure where to access the latest header image for instance. 
3. Availability: Will have some time tomorrow to finish up
4. ETA: EOD tomorrow, 6/29

**Comment by ktlevesque19** [comment]
Just finished this up! Didn't have access to the top image, but the rest is there.

<img width="189" alt="Screen Shot 2021-06-29 at 11 25 35 PM" src="https://user-images.githubusercontent.com/84823624/123912080-708f5a80-d931-11eb-8b99-4fdfdf4d284a.png">

**Comment by daniellex0** [comment]
This looks great, nice job!

@Sihemgourou FYI she left our the bugs from the replicated version- this was just so that we can have a mobile reference for the page on Figma)
