### ISSUE TITLE
GitHub action: Adding Issue Labels to Pull Requests

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#1707]
### Overview

We need to have the pr's automatically populated with the same labels as the related issue so that the same methodology that people use to pick issues to work on can be used for prs to review (pick the issue that matches your current level).

### Details
Pull requests range in complexity and scope, and potential reviewers currently have a hard time deciding which pull requests to review. Repopulating pull requests with the labels of the linked issue will help reviewers decide which request fit their comfort level and ability.

### Action Items
- [x] Create a Github action bot. Psudo-code is:
  - [x] Read the text of the first/original comment of the pull request
  - [x] From that text, find the linked issue
  - [x] Read or retrieve the labels from the linked issue
  - [x] Add the same labels to the pull request
- [ ] Non-exhaustive list of unit tests:
  - [x] Bot must run when a new PR is created OR... (read: not XOR)
  - [x] ...Bot must run when the first/original comment is edited
  - [x] Bot must not add labels when a linked issue does not exist
  - [x] Bot must not run when multiple linked issue exists
  - [x] Bot must add the exact same labels, no more, no less
  - [ ] Bot will not add the labels if the there is a linked pull request rather than a linked issue (**Note:** abandoned due to need for additional API call. Inefficient.)
  - [x] When the comment is updated, bot will erase existing labels, before re-adding labels
  - [x] [Proof it against dependencies should breaking changes every happen](https://docs.github.com/en/actions/learn-github-actions/finding-and-customizing-actions#using-release-management-for-your-custom-actions)
  - [x] [Do proper security handling](https://docs.github.com/en/actions/learn-github-actions/security-hardening-for-github-actions)
  - [x] Ensure logged output does not display sensitive information
  - [ ] Possible function awaiting approval from seniors: bot will add a comment to the pull request when a linked issue is not added or multiple issues are in the text

### Resources/Instructions
Don't know how to do GitHub actions? Start [here](https://docs.github.com/en/actions)!

**Comment by akibrhast** [comment]
>  Possible function awaiting approval from seniors: bot will add a comment to the pull request when a linked issue is not added or multiple issues are in the text

That is a good idea! But it should be its own issue and its own action. Something along the lines of:
- Create a github action called "request-linked-issue-on-pr.yml" that auto adds a comment[Please link an issue to this PR] to a PR if the PR has no linked pull request
- the trigger for the gh action should be  "On New PR creation + 20mins"

**Comment by Aveline-art** [comment]
* Progress: Event triggers are set up. Currently trying to extract Linked Issue number. github env does not log linked issues in comments. Will need to use regex to extract linked issue's value.
* Blockers: Weighing the pros and cons of two methods of reading first comments. Through API or a potentially buggy github native env?
* Availability: Sunday, Wednesday, Friday, Saturday.
* ETA: By Tuesday, at the latest.

Note to self:
* Ensure that when the issue number is not returned (no issue, or multiple issues), do not move onto the next script
* Ensure that if there are no labels, the script returns neatly, and do not move onto the next script
