### ISSUE TITLE
Clean up the website-write team

### ISSUE THREAD

**Issue by akibrhast** [hackforla/website#1709]
### Dependency
- #1343 

### Overview
The [website-write team](https://github.com/orgs/hackforla/teams/website-write/members) currently has too many inactive  members, or members who are no longer a part of hackforla. 

- Active Member: Someone who has made a contribution to the website repository or wiki within the last 3 months
- Contribution: Code Contribution, Comment Contribution, Wiki Edit Contributions

### Action Items
- [x] The member list needs to be manually trimmed such that it reflects current active members.

### Resources/Instructions
-  [website-write team](https://github.com/orgs/hackforla/teams/website-write/members)

**Comment by GLRJr** [comment]
During the weekly PM meeting team will deactivate inactive members.

**Comment by Sihemgourou** [comment]
Done.
