### ISSUE TITLE
wins-feature-1: Badges container penetrates background of fixed menu

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#1717]
### Overview
In our [wins-feature-1](https://github.com/hackforla/website/tree/wins-feature-1) branch of the website project, when the badges container is expanded in mobile (or when then .wins-page-tablet class is added), the container somehow "penetrates" the background of the menu. Below is a sample of such behavior: note that "I setup 2FA" appears on the fixed menu.

<details>
<summary>Image of bug</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/121758660-315eae00-cad7-11eb-8f75-bfae5b243a4b.png" width="" length="" />
<br>
</details>

This should not happen--the menu should remain solid throughout.

### Action Items
- [x] Reminder: [make sure your GitHub branches is organized correctly ](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [x] Recreate bug in your native machine
- [x] Discover why the bug happens
- [x] Resolve bug

### Resources/Instructions
[How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
[wins-feature-1 branch of website project](https://github.com/hackforla/website/tree/wins-feature-1)

**Comment by jbubar** [comment]
IMPORTANT!! 
This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)

**Comment by Abel-Zambrano** [comment]
IMPORTANT!! 
This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
