### ISSUE TITLE
Filter the technologies by categories

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#1728]
### Overview
As a prospect volunteer, I want to be able to filter the project by technologies.

### Action Items
Development
- [ ] Make sure to update the [technologie categorisation sheet](https://docs.google.com/spreadsheets/d/146oHxCjQrmzXnj6luRgdnFaBc-2pNEr2PCxfmmvLaZU/edit#gid=0) with what appear on the website listing
- [ ] Create the filter with the different categories in the sheet (ex: backend, frontend etc...)

### Resources/Instructions
https://docs.google.com/spreadsheets/d/146oHxCjQrmzXnj6luRgdnFaBc-2pNEr2PCxfmmvLaZU/edit#gid=0

**Comment by Aveline-art** [comment]
@janieche This looks to be a duplicate issue. The notes here might provide additional help for your issue.
