### ISSUE TITLE
Source copyright safe social media icons

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#173]
### Overview
Verify sourcing/copyright of social media icons. Two of them are currently out of date, and all of them might not be in license compliance

### Action Items
- [x] Perform online research to source social media icons to replace existing ones
- [x] Replace existing social media icons with new set
- [x] Upload revisions to site

### Branding Resources/Guidlines
G Suite folder for all [social media icons](https://drive.google.com/drive/folders/1JkbDq2agvTT2kykIUv9DoPBWYqmnFs6i?usp=sharing)
[Slack](https://brandfolder.com/slack/logos)
[Facebook app](https://en.facebookbrand.com/facebookapp/)
[Twitter](https://about.twitter.com/en_us/company/brand-resources.html)
[Medium](https://medium.design/logos-and-brand-guidelines-f1a01a733592)
[Github](https://github.com/logos)
[Meetup](https://www.meetup.com/media/)

**Comment by KianBadie** [comment]
The Facebook app and Github branding resources were only available in .esp or .png, which might have conflicted with the current way we implement the icons. I converted it to a .svg using an application called [inkscape](https://inkscape.org/). Is that ok?

As a result of the conversion, there is a lot of inkscape metadata in the .svg file, but it can be deleted without affecting the .svg itself.

**Comment by KianBadie** [comment]
Also, this is something I am confused about. According to the guidelines for the[ Facebook app branding resources](https://en.facebookbrand.com/facebookapp/assets/f-logo?audience=landing), it states:

> Don’t modify the "f" Logo in any way, such as by changing the design, scale or color. If you can’t use the correct color due to technical limitations, use black and white

Similar on the [Twitter Guidelines](https://about.twitter.com/en_us/company/brand-resources.html)

> When using the logo alongside other social icons to represent your presence on Twitter, you can use the logo in either blue or white, displayed at equal size and height to the other social media icons. When using the logo in white, the background color may be set in any color.

Does this create problems for us? Is it that big of a deal to change the color to match our current social media icon colors? I remember talking to @harishlingam about this, so sorry for the redundancy, but hopefully a written record here will be useful to others as well as help me remember.

Should we just display social media icons in their respective colors to make things easier? Or another idea, change the grey we are using to match the grey that these companies approve of, if they have overlapping approved colors?

After reading through the guidelines for each company, it seems like colors are a touchy issue for all of these companies.

**Comment by KianBadie** [comment]
Just for conversation sake, here's a preview of what the "original" colors would look like on the main nav bar.
![Screenshot from 2019-11-23 16-42-37](https://user-images.githubusercontent.com/18221058/69487525-5bc31a80-0e10-11ea-9fc0-f7264ce3d557.png)

**Comment by ExperimentsInHonesty** [comment]
I think it depends on where we are displaying the icons.  It sounds like we are using the icons appropriately on the home page (black and white).  But on the project pages, in the resource section it makes sense to use the color icons.

**Comment by KianBadie** [comment]
Hello @harishlingam and @ExperimentsInHonesty, I've finished reqorking/updating the social icons in the nav bar. There is one more social icon, which is the meetup one:

![Screenshot from 2019-11-27 17-17-42](https://user-images.githubusercontent.com/18221058/69769480-d5714600-1139-11ea-8327-bb891e5b7ada.png)

Would you like me to get a proper source for this icon as well? And in addition, would you like me to change it to the [swarm](https://help.meetup.com/hc/en-us/articles/360001655932-Meetup-Trademark-Guidelines) icon they have, to better match the theme of the other icons we have?

![Screenshot from 2019-11-27 17-18-58](https://user-images.githubusercontent.com/18221058/69769532-03568a80-113a-11ea-8f48-e21158e911cc.png)

**Comment by KianBadie** [comment]
What the updated social media icons look like.

Header:
![Screenshot from 2019-12-02 19-55-10](https://user-images.githubusercontent.com/18221058/70019308-b1e53b80-153d-11ea-9bc1-d460c85b9d0c.png)

Footer:
![Screenshot from 2019-12-02 19-55-03](https://user-images.githubusercontent.com/18221058/70019307-b14ca500-153d-11ea-8b75-a983b6adb6dc.png)

**Comment by ashlingam** [comment]
This looks great Kian! Look forward to seeing it on the site.
