### ISSUE TITLE
Update Sitemap page and add to footer

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1733]
### Overview
We need to officially update the HfLA website sitemap because it is outdated. 

### Action Items
Design
- [x] Explore the current sitemap iterations in the [Sitemap Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1558%3A13110) 
   - [x] Explore the 'legend' for differences between each type rectangle of
- [x] Update sitemap according to current website and the direction it's going in
   - [x] Keep it as vertical as possible to fit in [Sitemap page](https://www.hackforla.org/sitemap/) on HfLA site
   - [x] Run any questions by @daniellex0, design team and/or Bonnie
- [x] Get review and notes from  @daniellex0, design team and/or Bonnie

Development

- [x] Add new sitemap image to sitemap page. See image in comment at the bottom of this issue.
- [x] Add sitemap page link to footer (see placement in [footer file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3417%3A25) in Figma in pink rectangle)

### Resources/Instructions
[Sitemap Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1558%3A13110) 
[Sitemap page](https://www.hackforla.org/sitemap/)
https://github.com/hackforla/website/issues/963

**Comment by Sihemgourou** [comment]
@daniellex0 this issue has been without update for too long. Do you have news ?

**Comment by SaashaG** [comment]
Progress: In Progress
Blockers: Needed clarification on a couple of pages in order tp strategize design.
Availability: Open
ETA: Completion date still TBD, meeting Rosalyn this week to draft designs

**Comment by ExperimentsInHonesty** [comment]
@SaashaG @Rosalyn-broddie You can redesign it after you update it.  We need to be able to export the image so that we can launch the page on the website.  I understand its not the ideal design but it does work.  What needs to happen now, is for the image to be updated, it to be launched on the website and then users interviewed to find out what they would like improved.

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 @Sihemgourou Please see my comments here: https://github.com/hackforla/website/issues/1733#issuecomment-874395859

**Comment by SaashaG** [comment]
Thanks, we will work on updating.

**Comment by Rosalyn-broddie** [comment]
Progress: We're almost finished with adding the necessary changes for the sitemap. We only need to finish making sure that all of the cards match the current status of the website pages.

Blockers: We haven't been able to coordinate time to meet in the past couple of days

Availability: It looks like we'll be able to set up a time tomorrow to meet. I'll have time to take a look at separately as well

ETA: Should be completed in time for next week's team meeting

**Comment by ExperimentsInHonesty** [comment]
@Rosalyn-broddie @SaashaG a Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
@kristine-eudey will reach out to @daniellex0 about the changes we discussed during the last meeting. If she could put those here on the issue so that either the currently assigned people or new people can finish

**Comment by kristine-eudey** [comment]
@daniellex0 can you please share new sitemap image for development if it's ready?

**Comment by kristine-eudey** [comment]
Design looks great! Design portion is finished. Unassigning @SaashaG @Rosalyn-broddie

**Comment by kristine-eudey** [comment]
New sitemap image:
![Sitemap -07142021](https://user-images.githubusercontent.com/16949503/127555208-82fd28b0-59dd-47d1-87b8-7350b0c3d43a.jpeg)
