### ISSUE TITLE
Create a Donate page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1739]
### Overview
We need to create a dedicated Donate page so that users clearly know how to donate directly to Hack for LA before they visit the Code for America donate page.

### Action Items

Design
- [x] Review the donate gif and instructions in the bottom of the [Join Us page](https://www.hackforla.org/join)
- [x] Create a new page on Figma for the donate page
- [x] Design a donate page with the same gif and instructions as the About page (the design on the page can look similar to the layout in About Us)
   - [x] When users click the 'Donate' button in the header or footer of any page, they will be led to the donate page (currently they are led directly to Code for America, which means they miss the instructions about how to donate directly to HfLA)

Development
- [x] Develop the Donate page based on the design in [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11166%3A91022) in the pink rectangle
   - [x] Duplicate the body from the last card in the Join Us page
   - [x] Follow the lead of the header in the Join Us page too
- [x] Do not link the page to the website yet- this should remain an unlinked page for now, until the header copy is finished
- [x] Add header image to [Credits](https://www.hackforla.org/credits/) page

### Resources/Instructions
[Join Us page](https://www.hackforla.org/join) (donate instructions on bottom)
Donate page design in [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11166%3A91022) (in the pink rectangle)
[How to Create a new HfLA website page](https://github.com/hackforla/website/wiki/How-to-create-a-page-on-the-HfLA-website)
[HfLA Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)
[Credit.yml file template](https://github.com/hackforla/website/wiki/credit.yml-file-template)

<img width="350" alt="Screen Shot 2021-06-28 at 11 55 58 AM" src="https://user-images.githubusercontent.com/67400366/123689329-f7e0af00-d807-11eb-8d0e-25b22059af66.png">

**Comment by Sihemgourou** [comment]
@mgodoy2023 are you actively working on the issue ? If yes, 
Please add update
1. Progress
2. Blockers
3. Availability
4. ETA
Thanks :)

**Comment by mgodoy2023** [comment]
Hi @Sihemgourou. I am still working on this issue - haven't had a ton of time to work on it yet, but will tomorrow. I'll post an update on blockers and progress at the end of the day. Thanks.

**Comment by ExperimentsInHonesty** [comment]
@mgodoy2020 I am going to remove the "To update" label.  You can always remove that anytime its on your issue, and then you make an update.

**Comment by mgodoy2023** [comment]
1. Progress: 
- Created the donate.html _donate.scss and donate.yml files for the Donate page. 
- Created a donate folder in assets/images with the images used on the page. 
- Updated the main.scss file to include the _donate.scss file.

2. Blockers: 
- On the credits page the image isn't showing up
- The text "Donate to Hack for LA" is not appearing all on one line on the Donate page

3. Availability:
- Until 3:30pm today and after 10pm tonight.

4. ETA:
- Should be done by mid day tomorrow

Images of Blockers:
<img width="1440" alt="Screen Shot 2021-07-13 at 11 37 06 AM" src="https://user-images.githubusercontent.com/86011089/125507014-5efd04d1-ce33-4994-99f8-d3960cf2236e.png">

<img width="1440" alt="Screen Shot 2021-07-13 at 11 37 43 AM" src="https://user-images.githubusercontent.com/86011089/125507025-6eccb601-c688-454c-90a9-ae4a347269e0.png">

**Comment by Abel-Zambrano** [comment]
IMPORTANT!! 
This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
