### ISSUE TITLE
Implement Design system heading typography in the code base 

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#1743]
### Overview
We need to implement the headings part of the design system as classes in the code base so that our heading sizes are no longer attached to h1/h2/h3 tags etc and can no longer negatively affect the accessibility/hierarchy of the web pages for people using screen readers

### Action Items

- [x] Go to the [Figma Design System page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) Typography section on the top row
- [x] Read the Start Here if you do not know about design systems (_*Danielle note: sorry, the developer summary isn't there yet! But the designer one still explains the basics_)
- [x] Find the headings (from Title1 to Title6 ) in the figma link (See 1.Style & Rules => Typography)
- [x] Add new classes Title1 through Title6 with only the size properties (not the other properties like typeface, line height etc. at this time because that may be automatically applied to all typography on the site elsewhere) into the code base in the appropriate scss file (the classes will be implemented in headings throughout the site in a future issue in collaboration with design, after this step is finished)

<img width="507" alt="Screen Shot 2021-06-17 at 3 43 02 PM" src="https://user-images.githubusercontent.com/67400366/122481899-68740a00-cf84-11eb-8e7c-4e20fafd564b.png">

### Resources/Instructions
[Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)

**Comment by Sihemgourou** [comment]
@Zak234 Please add uptades on this issue before taking another one (I unassigned you from [this one](https://github.com/hackforla/website/issues/1825) but Please feel free to take it back once you finish working on this issue.

**Comment by edeneault** [comment]
Question/clarification: Are these new typography classes meant to only affect the sizes of the "toolkit" page?  or should they be set-up to be applied "site wide"?
