### ISSUE TITLE
Update Project Profile: Civic Tech Index

### ISSUE THREAD

**Issue by connie-yu-dotcom** [hackforla/website#1748]
Updated by @Aveline-art June 16, 2021

### Overview
As a product manager of Civic Tech Index, the project needs to be up to date on the HackforLA website

### Project card

https://www.hackforla.org/projects/civic-tech-index

### Action Items

- [x] Update current project team
- [x] Remove the 3 currently listed open roles on the project card
- [ ] Remove the Tuesday Developer meeting
- [x] For details and specifics [see this comment below](https://github.com/hackforla/website/issues/1748#issuecomment-861964152)

### Resources
[Template of a project.md file](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)
[Hack for LA's Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

**Comment by connie-yu-dotcom** [comment]
1. Please update the current project team to the following: 
<img width="785" alt="Screen Shot 2021-05-04 at 8 41 45 PM" src="https://user-images.githubusercontent.com/80801490/122146400-f933d400-ce24-11eb-944e-58e4e470e77f.png">


2. No open roles please remove the 3 currently listed on the project card
<img width="493" alt="Screen Shot 2021-06-15 at 9 58 55 PM" src="https://user-images.githubusercontent.com/80801490/122146363-e4efd700-ce24-11eb-97fb-934ddd463587.png">

3. Meetings: please remove the Tuesday Developer meeting 
<img width="225" alt="Screen Shot 2021-06-15 at 10 00 05 PM" src="https://user-images.githubusercontent.com/80801490/122146471-1b2d5680-ce25-11eb-845b-b1819b0d6e2a.png">

**Comment by ExperimentsInHonesty** [comment]
@connie-yu-dotcom the meeting times are controlled by the VRMS team.  The website just uses their API to display.  Please open an issue using this [template](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=) to update your meeting times
