### ISSUE TITLE
Provide feedback about the "Being a Part of the Hack For LA Team" wiki page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1749]
### Overview
We need to gather feedback/edits/suggestions from new volunteers on the team about the "Being a Part of the Hack For LA Team" wiki page to make sure that it is as effective and clear as possible.

### Action Items
- [ ] Read the [Being a Part of the Hack For LA Team wiki page
](https://github.com/hackforla/website/wiki/Being-a-Part-of-the-Hack-For-LA-Team#phase-2-how-to-train-yourself-to-become-a-leader)
- [ ] Write any feedback/comments/suggested edits in a comment in this issue below

### Resources/Instructions
[Being a Part of the Hack For LA Team wiki page
](https://github.com/hackforla/website/wiki/Being-a-Part-of-the-Hack-For-LA-Team#phase-2-how-to-train-yourself-to-become-a-leader)

**Comment by aliibsin** [comment]
@hackforla/website-write please leave your feedback

**Comment by KenMan79** [comment]
I'd like to say this is excellent, what do you think of this?
"The first step to becoming a leader is to: Share your intention of becoming a Leader within our Team!"

**Comment by margaretgeary** [comment]
Could I please be removed from the emailing list? My email is
***@***.***
Thank you!

**Comment by sena-ji** [comment]
I think we recorded some examples of reviewing PRs from the meetings. If we have a guide on how to do PRs, maybe we can link them within the first section just like how we linked "Helpful documents: How To Lead Team Meetings" in the third section. 

Maybe we can also expand on what "request for changes" are. Not sure if everyone will know exactly what that means.

**Comment by KenMan79** [comment]
@sena-ji this makes sinnce

**Comment by Zak234** [comment]
The wiki itself is quite good but it is a little bit buried especially because this seems like a very good document for new people to view to get an idea of what steps to get to be on-boarded.

**Comment by akibrhast** [comment]
Closed because we have gotten enough feedback
