### ISSUE TITLE
HfLA: ALL TEAM PRE Meeting Agenda 2021

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#1796]
### Overview
This issue tracks the **PRE meeting** agenda for the HFLA website team. Don't hesitate to write here your suggestions, questions or other things that you want to talk about during the meeting ! 

### Action Items
- [ ] Add next meetings items below in a comment

**Comment by Aveline-art** [comment]
@Sihemgourou I am unsure what you mean by "PRE meeting"? Does it mean PRE as in the prefix "pre-"? Or is it an acronym for something?
