### ISSUE TITLE
Add comments to _sass/variables/_layout.scss

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#1816]
### Overview
We need to add documentation to our layout variables so people understand what they are and how to use it

### Action Items
- [x] Add documentation that clarifies use cases of sass variables

### Resources/Instructions
[Variable to document](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_layout.scss
)
[	
8 Best Practices for Perfect CSS Documentation](https://webdesign.tutsplus.com/articles/css-documentation-best-practices--cms-30139)

**Comment by Abel-Zambrano** [comment]
IMPORTANT!! 
This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
