### ISSUE TITLE
Replicate mobile version of Wins page 

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1823]
### Overview
We need to adjust the mobile version of the [Wins page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0), because the current version on there is not the right standard mobile width for our Figma designs (should be 375px wide)

### Action Items
- [x] Update the mobile version of the [Wins page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) on Figma (in blue rectangle)
   - [x] Pull the top nav and bottom nav components from the [Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4532%3A164) or any other page in Figma
   - [x] Base the header measurements off of the standards in the [Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) (in section 3- Layouts & Grids - Anatomy of Page guidelines)
   - [x] Layout the rest of the page based on the current mobile version of the [Wins page](https://www.hackforla.org/wins/) on our website using Right click > "Inspect" in your browser to measure margins, font sizes, etc (ask @daniellex0 for guidance, and see more details in comment below- scroll down)
   - [x] Pull elements from the desktop version of the page on Figma

### Resources/Instructions
[Wins page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) on Figma (in blue rectangle)
[Wins page](https://www.hackforla.org/wins/)

**Comment by daniellex0** [comment]
How to check measurements in mobile with "inspect"-

Select both of these:
<img width="127" alt="Screen Shot 2021-05-19 at 11 28 33 PM" src="https://user-images.githubusercontent.com/67400366/118929973-08913180-b8fa-11eb-9a96-49aff5bcaff7.png">

And then you can measure specific elements of the page by hovering over them to replicate the designs of the Project page in mobile:

<img width="283" alt="Screen Shot 2021-05-20 at 3 18 38 PM" src="https://user-images.githubusercontent.com/67400366/119055931-b0504300-b97e-11eb-9c2a-9bed16485e88.png">

**Comment by kristine-eudey** [comment]
Hi @irisxie, thanks for taking on this issue! When you first assign yourself an issue please comment what your estimated availability and ETA is for completing it, and provide weekly status updates in the format below. And please always feel free to reach out by mentioning me (or anyone else relevant to the issue) in a comment. 
- Progress:
- Blockers:
- Availability:
- ETA:

**Comment by ahoang94** [comment]
This issue is about halfway done and will be complete within the week!

**Comment by ahoang94** [comment]
@kristine-eudey 

The design portion of this issue is complete and is situated in the orange rectangle to the right of the final designs (blue rectangle).

Please note that I've posed a question about cases of when a person has more badges than can be displayed in a row:

![Screen Shot 2021-08-06 at 12 55 26 PM](https://user-images.githubusercontent.com/85914721/128564727-d2f6addd-39ed-4246-b9a6-a2adbf17251d.png)

**Comment by kristine-eudey** [comment]
This design portion of this issue has been reviewed and is ready for development. To your question above, @ahoang94, based on the previous design, badges will be limited to 5 in the collapsed view.

**Comment by Sihemgourou** [comment]
For now, show all the badges (as for desktop view)

**Comment by ahoang94** [comment]
@kristine-eudey The Figma file has been updated include multiple rows for badges.

**Comment by kristine-eudey** [comment]
The design portion of this issue has been reviewed and approved. Thanks for updating this @ahoang94!
