### ISSUE TITLE
Create new donation gif

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1824]
### Overview
We need to update the donation gif on the bottom of both the Join and About pages because the current gif is outdated and no longer consistent with the Code for America donate box, so it may confuse users and discourage them from donating.

<details >
<summary>current gif appearance in Join page (blue)</summary>

<img width="500" alt="Screen Shot 2021-06-23 at 11 47 38 PM" src="https://user-images.githubusercontent.com/67400366/123215859-c9687a00-d47d-11eb-9320-a1c01537fa72.png">
</details>

<details>
<summary>How gif should look from Code for America site (purple)</summary>

<img width="250" alt="Screen Shot 2021-06-23 at 11 47 55 PM" src="https://user-images.githubusercontent.com/67400366/123215974-e7ce7580-d47d-11eb-807e-2b42a760eefa.png">

</details>

### Action Items
- [x] Create a new gif following the same exact actions/flow as the current gif on the bottom of the [Join page](https://www.hackforla.org/join)
- [x] Get approval from product/design for the new gif
- [x] Replace the old gif with the new one in bottom of [Join](https://www.hackforla.org/join) and [About](https://www.hackforla.org/about/) pages

### Resources/Instructions
[Join page](https://www.hackforla.org/join)
[About page](https://www.hackforla.org/about/)
[Code for America donate page](https://www.codeforamerica.org/donate/)

**Comment by Sihemgourou** [comment]
@daniellex0 could we more this to the prioritized backlog?

**Comment by daniellex0** [comment]
@Sihemgourou Sure, if it's approved? I can't remember if it was!

**Comment by Aveline-art** [comment]
Hello! It has taken me a while to learn the art of the gif, but I think I have outdone myself. Let me know if this suffices or if I should do anything else.

<img src="https://user-images.githubusercontent.com/62368440/125002019-d69e7080-e008-11eb-9ddb-eb432252bab9.gif" width="300" length="150" />

**Comment by daniellex0** [comment]
Looks awesome!! Thank you @Aveline-art !!

**Comment by Abel-Zambrano** [comment]
IMPORTANT!! 
This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
