### ISSUE TITLE
Mobile Responsiveness check on donate page

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#1841]
### Overview
We need to check the mobile version of the donate page on the website  so that we correct any bug that is appearing on mobile. 

### Action Items
Design: 
- [x] Check the mobile responsiveness of donate page (https://www.hackforla.org/donate/) (use your mobile to do it ;) ) 
- [x] If there is any bug/any inconsistency or problem, however small or large, edit this issue and list the bug with screenshots  _You have more than one bug? duplicate this issue and create one issue per bug._ 
- [x] List all the changes to implement to correct the bug (eg: resizing..) in the development action items below :arrow_down:. (don't hesitate to create 1 checkbox for each changes)
- [x] Provide links to the figma file (if there is one), and a URL link to the page where the bug is observed.
- [x] Put the issue(s) in the new issue review column to check the feasibility with the devs. 

Development: 

### Resources/Instructions
Infos for developers:  Ensure that the correction doesn't break any other pages that is connected to the one your changing. For that, check  [the sitemap](https://www.hackforla.org/sitemap.xml)

**Comment by Sihemgourou** [comment]
Donate page is still not live

**Comment by kristine-eudey** [comment]
@ashleylin1 can you please provide an update on this issue?

- Progress: 
- Blockers: 
- Availability: 
- ETA:

**Comment by ashleylin1** [comment]
Progress:

There is an accessibility issue in that the text inside the green circles is too small to read on mobile. 
<img src="https://user-images.githubusercontent.com/54569038/137396588-de79d880-1089-401e-959e-70fac73d5401.jpg" width=30% height=30%>

According to our Design System on typography, the smallest accessible text for mobile is 16px:
<img src="https://user-images.githubusercontent.com/54569038/137397085-c902dcb9-3fc1-42f8-865d-b7959287f553.png" width=50% height=50%>

The graphic either needs to be redesigned to format the text properly or the text can be simply increased in font to 16px.

Option 1: Increase font to 16px and resize the circles accordingly: 
<img src="https://user-images.githubusercontent.com/54569038/137400103-4bbbc4b5-ee68-4665-9246-30a64cf3278d.png" width=30% height=30%>

Option 2: If the percentages of spending is known, a pie chart could be used to show the actual percentage of spending that is used to increase transparency about donations:
<img src="https://user-images.githubusercontent.com/54569038/137400206-da3088cc-b458-4ef9-a3b6-5bfc569fb4c4.png" width=30% height=30%>

Option 3: Use a pyramid chart: 
<img src="https://user-images.githubusercontent.com/54569038/137400284-a6b6d7a4-4b58-4ae1-ab7f-c7fca804464b.png" width=30% height=30%>

All three options are found in the "Donate Page (WIP)" on the Figma in the purple border
Link: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11166%3A91022
<img src="https://user-images.githubusercontent.com/54569038/137400445-22e0b960-2384-4513-915f-82c4364a7c7b.png" width=20% height=20%>

All other aspects of the Donate Page seem to function as intended and are not in need of any other changes.

Blockers: I moved this to the New Issue Approval section of the Project Board. Is this the same as the new issue review column stated above?
Availability: weekends
ETA:

**Comment by kristine-eudey** [comment]
Thank you @ashleylin1! I moved this to questions/in review so we can flag it to share your findings with the larger team at today's meeting.

**Comment by kristine-eudey** [comment]
Final version for development is here: [Donate Page (Mobile) - Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17065%3A104582) Changes from current live version are annotated with notes.

**Comment by adam-abundis** [comment]
Created #2392 for dev implementation of the donate (mobile) design.
