### ISSUE TITLE
Mobile Responsiveness on getting-started 

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#1842]
### Dependency
~#1619~

### Overview
We need to check the mobile version of  the getting started page  so that we correct any bug that is appearing on mobile. 

### Action Items
Design: 
- [x] Check the mobile responsiveness of getting started page (use your mobile to do it ;) ) 
- [x] If there is any bug/any inconsistency or problem, however small or large, edit this issue and list the bug with screenshots  _You have more than one bug? duplicate this issue and create one issue per bug._ 
- [x] List all the changes to implement to correct the bug (eg: resizing..) in the development action items below :arrow_down:. (don't hesitate to create 1 checkbox for each changes)
- [x] Provide links to the figma file (if there is one), and a URL link to the page where the bug is observed.
- [x] Put the issue(s) in the review column to check the feasibility with the devs. 

Development: 
- [ ] Resize the text below the heading ("Follow the steps...") from 18px to 16px, per the [website design system](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=6207%3A40530).
- [ ] The icons besides each sub-step should be vertically aligned to the top of the text:
<img width="271" alt="Screen Shot 2021-09-25 at 5 27 12 PM" src="https://user-images.githubusercontent.com/85914721/134789212-e2e0fc0f-e110-4de0-b21b-da3c685f2d11.png">

### Resources/Instructions
Infos for developers:  Ensure that the correction doesn't break any other pages that is connected to the one your changing. For that, check  [the sitemap](https://www.hackforla.org/sitemap.xml)

**Comment by ExperimentsInHonesty** [comment]
~@abuna1985 @macho-catt Can you add a size to this issue and then add the "Ready for Prioritization" label~

**Comment by ExperimentsInHonesty** [comment]
@abuna1985 I changed my mind.  please make a new issue from this just for development, mention it in a comment on this issue.

**Comment by JessicaLucindaCheng** [comment]
These were the dev issues:
- https://github.com/hackforla/website/issues/2396
- https://github.com/hackforla/website/issues/2417
