### ISSUE TITLE
Mobile Responsiveness on wins page 

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#1845]
### Overview
We need to check the mobile version of every pages on the website  so that we correct any bug that is appearing on mobile. 

### Action Items
Design: 
- [x] Check the mobile responsiveness of wins page (use your mobile to do it ;) ) 
- [x] If there is any bug/any inconsistency or problem, however small or large, edit this issue and list the bug with screenshots  _You have more than one bug? duplicate this issue and create one issue per bug._ 
- [x] List all the changes to implement to correct the bug (eg: resizing..) in the development action items below :arrow_down:. (don't hesitate to create 1 checkbox for each changes)
- [x] Provide links to the figma file (if there is one), and a URL link to the page where the bug is observed.
- [x] Put the issue(s) in the review column to check the feasibility with the devs. 

Development: 
- [ ] Increase the padding below the "See More" link:
![Padding](https://user-images.githubusercontent.com/85914721/127588466-35cc5196-9aa4-4a4f-af9c-32657c37a503.jpg)
- [ ] Create "See Less" link to collapse/reverse content expansion.
- [ ] Alphabetize the options in the Role dropdown menu for ease of use.

### Resources/Instructions
Infos for developers:  Ensure that the correction doesn't break any other pages that is connected to the one you're changing. For that, check  [the sitemap](https://www.hackforla.org/sitemap.xml)

**Comment by ahoang94** [comment]
I should have this done by the end of this week!

**Comment by ExperimentsInHonesty** [comment]
@ahoang94 did we accidentally skip this issue during the meeting?  Meaning do you need feedback on this?

**Comment by Sihemgourou** [comment]
We need to review this issue with the devs

Téléchargez Outlook pour iOS<https://aka.ms/o0ukef>
________________________________
De : Bonnie Wolfe ***@***.***>
Envoyé : Monday, August 2, 2021 3:29:57 AM
À : hackforla/website ***@***.***>
Cc : Sihem GOUROU ***@***.***>; Author ***@***.***>
Objet : Re: [hackforla/website] Mobile Responsiveness on wins page (#1845)


@ahoang94<https://github.com/ahoang94> did we accidentally skip this issue during the meeting? Meaning do you need feedback on this?

**Comment by ahoang94** [comment]
@ExperimentsInHonesty This was my first time working on an issue, and I was under the assumption that I was suppose to move its status to "In Review" after I completed my part. Apologies if this was incorrect!
