### ISSUE TITLE
GitHub Actions: Switching update labels when update is added

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#1847]
### Overview
It is quite easy for our busy team to mislabel issues. For this action, we want the "To Update !" label to disappear when the assignee of an issue makes an update to their assigned issue, and add the "Status: Updated" label instead.

### Psudo-code
- [ ] Create a GitHub action that implements this behavior:
  - [ ] Triggers when a new comment is made to an issue with the label "To Update !"
  - [ ] Checks if the comment is made by the assignee.
  - [ ] If so, removes the "To Update !" label and adds the "Status: Updated" label.
  - [ ] Else, exit without problem.

### Checks
- [ ] Properly logs the code to aid in debugging for future programmers.
- [ ] Have comments explaining the reasoning behind opaque parts of your code
- [ ] Test what happens when:
  - [ ] A comment is made when there _is no_ "To Update !" label (should do nothing)
  - [ ] A comment is made by the assignee when there _is_ a "To Update !" label (should switch label)
  - [ ] A comment is made by someone _other than the assignee_ when there is a "To Update !" label (should do nothing)
  - [ ] A label is added (should do nothing)
  - [ ] A label is removed (should do nothing)

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)

Note that you might want to do something outside the scope of the above psudo-code. If so, be sure to leave comments in your PR or this issue that justifies your reasoning. If you feel you need guidance, be sure to reach out! We cannot foresee whether this issue is solvable, or what hard decisions have to be made, but we would love to hear and help you!

#### Additional resources:
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[GitHub GraphQL](https://docs.github.com/en/graphql)

**Comment by Aveline-art** [comment]
@akibrhast @Sihemgourou  Please edit this as it fits, and please give feedback on whether we would like this feature or not! I will keep this in the ice box for now.

**Comment by akibrhast** [comment]
Looks great! I recommend for moving it to Prioritized Back Log

**Comment by Aveline-art** [comment]
Scrapped because of this risks over-automation. It is better for developers to learn the small ways in which we work, and also allow the team to adjust if our workflow changes.
