### ISSUE TITLE
Mobile Responsiveness on [press] : [quick recap of the bug here]

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#1849]
### Overview
We need to check the mobile version of every pages on the website  so that we correct any bug that is appearing on mobile. 

REPLACE THIS TEXT - 
1. Explain the bug that you have observed 
2. Put a screenshot of the bug: you can use the following template to create a drop down image
<details>
<summary>TITLE IMAGE </summary>

PASTE_YOUR_IMAGE_HERE
</details>

### Action Items
Design: 
- [ ] Check the mobile responsiveness of [this page ](https://www.hackforla.org/#press)(use your mobile to do it ;) ) 
- [ ] If there is any bug/any inconsistency or problem, however small or large, edit this issue and list the bug with screenshots in the Overview section above :arrow_up:. _You have more than one bug? duplicate this issue and create one issue per bug. 
- [ ] List all the changes to implement to correct the bug (eg: resizing..) in the development action items below :arrow_down:. (don't hesitate to create 1 checkbox for each changes)
- [ ] Put the issue(s) in the review column to check the feasibility with the devs. 

Development 
- [ ] Implement the following changes : "_list your changes here_ "
- [ ] Ensure that the correction doesn't break any other pages that is connected to the one your changing. For that, check  [the sitemap](https://www.hackforla.org/sitemap.xml)

### Resources/Instructions
REPLACE THIS TEXT - Provide links to the figma file (if there is one), and to the page where the bug is observed.

**Comment by Sihemgourou** [comment]
Hey @daniellex0, I've just found this bug. Why do we also have it on the figma ? 
<details>
<summary>Bug</summary>
![image](https://user-images.githubusercontent.com/55627107/123718651-08347080-d880-11eb-9eea-d630cfa6dc4b.png)
</details>

**Comment by daniellex0** [comment]
Sorry @Sihemgourou the link doesn't work for me?

**Comment by Sihemgourou** [comment]
Sorry ! Now it works

**Comment by daniellex0** [comment]
@Sihemgourou Is it that the mayor's photo is a bit off-screen?

**Comment by Sihemgourou** [comment]
Yes
