### ISSUE TITLE
Update Project Profile: Open Community Survey

### ISSUE THREAD

**Issue by ebele-oputa** [hackforla/website#1851]
Action items reformatted by @Aveline-art 

### Overview

As a product manager of Open Community Survey, I want my project's details to be up to date on the HackforLA website

### Project card
_insert url of their card here before sending - their cards can be found in this folder: https://github.com/hackforla/website/blob/gh-pages/_projects/open-community-survey.md

### Action Items

- [x] Update the GitHub link to [this](https://github.com/hackforla/open-community-survey)
- [x] Remove all open roles
- [x] Under Tools include: Figma
- [x] Under Technologies include: Markdown
- [x] Under Partners include: LA Department of Neighborhood Empowerment (DONE), LA Neighborhood Councils (NCs), LA Department of Transportation (LADOT), LA City Planning Department (LACP)
- [x] Check [this comment ](https://github.com/hackforla/website/issues/1851#issuecomment-865452023)for reference for above items
- [x] Update current team; see [comment ](https://github.com/hackforla/website/issues/1851#issuecomment-865453782)below

### Resources/Instructions

[Open Community Survey project page](https://www.hackforla.org/projects/open-community-survey)
[Project Card page](https://www.hackforla.org/#projects)
[open-community-survey.md](https://github.com/hackforla/website/blob/gh-pages/_projects/open-community-survey.md)

**Comment by ebele-oputa** [comment]
@Aveline-art Hi! Are you the one working on this issue? Just to let you know there hasn't been any update to our project card on the website. Thanks!

**Comment by Aveline-art** [comment]
@ebele-oputa Hi! Currently, no one is assigned to this issue, but we will push to get it assigned. Thank you for your patience!

**Comment by bfirestone23** [comment]
Hi @ebele-oputa, working on wrapping this up for you ASAP - can you please confirm if the updated partner list should include those already on the site (EmpowerLA, various Neighborhood Councils (e.g., Westlake NC)), or if the updated partner list should replace all? Thank you!

**Comment by ebele-oputa** [comment]
@bfirestone23 The updated list should replace all. Thank you!
