### ISSUE TITLE
Title links are not specific on Credit page

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#1865]
### Overview
As a user I need to be able to find the specific title link to each image on the credits page

### Action Items

- [x] Check all the images and list the ones that do not have the right title link
- [x] Create an issue template with devs 
- [x] Create an issue for each images

### Resources/Instructions
https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits

**Comment by Sihemgourou** [comment]
List of all the images with no specific title link: 
- [act](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/act.yml)
- [agile](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/agile.yml)
- [book](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/agile.yml)
- [contact us](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/contact-us.yml)
- [delegate](https://github.com/hackforla/website/issues/1865)
- [diversity](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/diversity.yml)
- [employees](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/employees.yml)
- [give](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/employees.yml)
- [global](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/global.yml)
- [hands](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/hands.yml)
- [partnership](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/partnership.yml)

**Comment by Sihemgourou** [comment]
@akibrhast

**Comment by daniellex0** [comment]
@Sihemgourou These are the correct links for these:

Agile - https://thenounproject.com/search/?creator=4249001&q=agile&i=2525741
Contact Us - https://www.freepik.com/free-vector/contact-us-concept-landing-page_4661525.htm#page=1&query=contact%20us&position=13
Partnership - https://thenounproject.com/search/?creator=3694290&q=partnership&i=3193867
Action - https://thenounproject.com/search/?creator=638256&q=action&i=784248
Employees- https://thenounproject.com/search/?creator=1145943&q=employees&i=3201878

(I created issues for these)

Will get back to you as soon as I find the others

**Comment by Sihemgourou** [comment]
Hey @daniellex0 did you create all the corresponding issues or do you need some help with this matter?

**Comment by Sihemgourou** [comment]
1. Progress : It doesn't seems that @daniellex0 checked all the links 
2. Blockers : none
3. Availability : full 
4. ETA : August 15
Thanks :)

**Comment by daniellex0** [comment]
@Sihemgourou Sorry about this, I'm just finishing up some things I didn't get to wrap up before I left as it's been a crazy couple weeks- I will work with @kristine-eudey this week in making new issues for these remaining icon credits

**Comment by Sihemgourou** [comment]
Perfect thank you ! I will assign you and @kristine-eudey to this issue then :)

**Comment by kristine-eudey** [comment]
@Sihemgourou all of the issues for the missing credit links have now been created.

**Comment by Sihemgourou** [comment]
Perfect, thanks @kristine-eudey ! 

I'm closing this issue then :)
