### ISSUE TITLE
Create new folder with templates and graphic assets

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#187]
### Overview
Create new folder with templates and graphic assets

### Action Items
- [x] Create new folder with templates and graphic assets (i.e. social media icons, logos, etc.)
- [x] Transfer relevant templates and graphic assets to folder

### Resources/Instructions

**Comment by KianBadie** [comment]
Added to the folder the social media icon svgs I am currently using in my branch.

**Comment by KianBadie** [comment]
Am I allowed to close this issues since it is in the "Done" section, or is it important to keep it open? This goes for other "done" issues as well.
