### ISSUE TITLE
Update 'Agile' image credit link

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1872]
### Overview
We need to correct the [image credit Name link](https://www.hackforla.org/credits/) for the 'Agile' image to the specific link, because it currently leads to a generic Noun Project link.

### Action Items
- [ ] Replace the generic Noun Project link for the image titled "Agile" in the [credits page](https://www.hackforla.org/credits/) with [this specific link](https://thenounproject.com/search/?creator=4249001&q=agile&i=2525741) instead in the 'Name' category 

### Resources/Instructions
[Credit.yml template wiki](https://github.com/hackforla/website/wiki/credit.yml-file-template)
[Credits page](https://www.hackforla.org/credits/)
['Agile' correct Image link](https://thenounproject.com/search/?creator=4249001&q=agile&i=2525741)

**Comment by Abel-Zambrano** [comment]
IMPORTANT!! 
This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
