### ISSUE TITLE
Write copy for Donate page header

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1878]
### Overview
We need to write copy for the new Donate page header paragraph because it is currently a placeholder

### Action Items

UX Writing
- [ ] Draft a header paragraph for the donate page
- [ ] Get approval/edits from Product

Development
- [ ] Add new header text into Donate page

### Resources/Instructions
[Donate page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11166%3A91022)

<img width="300" alt="Screen Shot 2021-07-01 at 12 30 30 PM" src="https://user-images.githubusercontent.com/67400366/124179805-2bba0f80-da68-11eb-8a14-46c79b88be4c.png">

**Comment by ExperimentsInHonesty** [comment]
@sijiapitts I think you are working on redesigning the donate page and this old issue came up.  Let's reconcile where you are working on the new instructions for reformatting the page.

**Comment by sijiapitts** [comment]
@ExperimentsInHonesty The design has been [updated](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24579%3A285100) according to your feedback. Issue number is [#3661](https://github.com/hackforla/website/issues/3661)
