### ISSUE TITLE
Update the Program Areas > Citizen Engagement page design

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1879]
### Overview
We need to update the [Program Areas > Citizen Engagement (Figma)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3625%3A0) page design so that it is up to date with the latest developments, and is consistent with the design system.

### Action Items
- [x] Duplicate the version of the [Program Areas Citizen Engagement page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3625%3A0) in the pink rectangle (command+d) in Figma so that you can edit your own copy of it and save the original as-is 
- [x] Adjust header so it matches the standard header layout in the [design system](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) (pasted in the bottom of the Program Areas Citizen Engagement Figma file for easy reference)
- [x] Make sure the standard black text on the back is HEX# 333 ('Dark-I' text color in the Figma Styles column)
   - [x] The navy blue subheadings in the cards can stay as-is for now
- [x] Remove "User Centered Design Workshop' card and turn it into a regular card like the ones above it, for the Open Community Survey project (get logo from its project card in [homepage](https://www.hackforla.org/))
   - [x] The text can be lorem ipsum for now
   - [x] Keep SDG section generic for now
- [x] Make all of the page cards 1080px width (instead of 1098px) to match the design system XL page card. Adjust the card content accordingly
- [x] Adjust the margins in the body of the page between, above, and below the cards to match the design system layout (again reference the design system measurement template pasted below the mockup)
- [x] Feel free to try to play around with some different versions of the problem/solution/impact page cards on the side to see if you can think of some better layouts
- [x] Feel free to adjust the layout of the 'Organizations We Work With' page card to look better/more evenly aligned

### Resources/Instructions
[Program Areas > Citizen Engagement page in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15901%3A100458) (final version in pink rectangle)

**Comment by anonymousanemone** [comment]
1. Done
2. None
3. Open
4. Complete

**Comment by ExperimentsInHonesty** [comment]
@anonymousanemone Here are my changes for Lucky Parking

**Current text**

> For a car-centric city like Los Angeles, parking regulations are a major concern to those who have to use street parking during the course of business or because off-street parking is not provided at their residence. For these reasons, the effect of parking citations is unevenly felt across different socio-economic strata of the community. Ideally, the publically available Los Angeles parking citation dataset can be used as a basis for discussions about this disparity, but the unwieldy size and inconsistency of this data has been enough of a barrier to make it inaccessible to non-researchers.

**New Text**

``` 
Parking citations are distributed unevenly across different socio-economic strata of the cities residents as they use  public parking  during the course of business or because enough off-street parking is not provided at their residence. The current publicly available Los Angeles parking citation dataset can be used as a basis for discussions about this disparity, but the unwieldy size and inconsistency of this data has been enough of a barrier to make it inaccessible to non-researchers.
```

**Comment by ExperimentsInHonesty** [comment]
@anonymousanemone Here is my changes to the text at the top

**Current Text**

> We at Hack for LA are volunteers that believe in building technology and analyzing data to make it easier to participate effectively in your community. Here, you'll find a series of products that we have built or are building to make that happen.
> 
> Whether you have a new idea, want to submit feedback to participate in guiding the next iteration of an existing tool, or want to start programming with us, please contact us at citizenengagement@hackforla.org.



**New Text**
```
We at Hack for LA are volunteers that believe in building technology and analyzing data to make it easier to participate effectively in your community. Below are our products that are making that happen.

If you have a new idea, want to submit feedback that will guide the next iteration of an existing tool, or want to start working on a project team with us, please contact us at citizenengagement@hackforla.org.
```

**Comment by anonymousanemone** [comment]
Progress: Fully complete (to my knowledge)
Blockers: None
Availability: Unable to do any work this entire week
ETA: I thought this was complete

**Comment by ExperimentsInHonesty** [comment]
@Sihemgourou you and I need to make this into an issue for development and stick in the icebox with a dependency of another issue (which also needs to be made) which is making the mobile view of the same page.

**Comment by kevngaleu** [comment]
Everything has been properly updated on this issue. I will remove the "to update" label and move it to the "Done" column of the project board.

**Comment by ExperimentsInHonesty** [comment]
This issue has been completed, you can see the final designs here: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15901%3A100458
