### ISSUE TITLE
Create Kanban board how-to deck

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#188]
### Overview
Create Kanban board how-to deck that instructs new members on how to use GH project boards.

### Action Items
- [x] Create Kanban board how-to deck
- [x] Upload Kanban board how-to-deck to assets folder
- [x] Add to Appropriate location (Civic Tech Structure readme)

### Resources/Instructions
https://github.com/hackforla/civic-tech-structure/blob/main/README.md
[Github: Kanban board setup](https://docs.google.com/presentation/d/1LHtvnHb35Sw7cHzk8RYJG4a1U9RblZepsC3wL7ZEpV0/edit#slide=id.g5e46fb07f1_0_1)

**Comment by ExperimentsInHonesty** [comment]
Finished https://docs.google.com/presentation/d/1LHtvnHb35Sw7cHzk8RYJG4a1U9RblZepsC3wL7ZEpV0/edit#slide=id.g5e46fb07f1_0_1
