### ISSUE TITLE
Standardize code for large icon page cards

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1887]
### Overview
We need to standardize the scss code for the large icon page cards in the [Join Us](https://www.hackforla.org/join) and [Site Map](https://www.hackforla.org/sitemap/) pages, because they are different and we should make them the same so that there is one standard reusable code for the design system.

### Action Items
- [ ] Decide which large icon page card's code is better between the [Join Us](https://www.hackforla.org/join) and [Site Map ](https://www.hackforla.org/sitemap/) ones (Feel free to consult with the dev team for consensus)
- [ ] Implement the selected code format in the page that uses the other code version so that this is now the standard code for large icon page cards across all pages that use it. Make sure it still looks good after the update.

### Resources/Instructions
[Join Us page](https://www.hackforla.org/join)
[Site Map page](https://www.hackforla.org/sitemap/)

Join Us page's large icon page card code (padding all around):

<img width="450" alt="Screen Shot 2021-07-03 at 9 14 32 PM" src="https://user-images.githubusercontent.com/67400366/124373017-d0447900-dc43-11eb-8ca9-3845a9c2c667.png">

Sitemap page's large icon page card code (padding not on left side):

<img width="450" alt="Screen Shot 2021-07-03 at 9 14 46 PM" src="https://user-images.githubusercontent.com/67400366/124373027-de929500-dc43-11eb-86c2-ebac07472321.png">

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 @macho-catt @abuna1985 have decided to use flexbox but they need to know where in the css files it should go so that it can be a standard reusable class.  Josh is suggesting putting it in here: https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_cards.scss  Do you approve?  Have alternate suggestions, comments, questions, etc.?

**Comment by daniellex0** [comment]
@ExperimentsInHonesty @macho-catt @abuna1985 Sure, putting it in the _cards.scss file works- it can be in the bottom (right above 'small card'), and please also make sure to include it in the index on the top of the file.
