### ISSUE TITLE
GitHub Actions: Refactoring adding-labels-to-pull-request action 

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#1892]
### Overview
We need to make sure our GHAL adding-labels-to-pull-request is organized, and readable so that we can easily make changes in the future.

### Action Items
- [x] Separate the JS logic in the two yml files (see below) into a new directory in [this directory](https://github.com/hackforla/website/tree/gh-pages/github-actions)
  - [x] Make sure the GitHub action still maintains its key functions. See #1787 and #1707 for details

### Resources/Instructions

Don't know how to do GitHub actions? Start [here](https://docs.github.com/en/actions)!

#### A. Things to consider

The logic in the GitHub action this issue is about is quite heavy, since it runs in 3 parts.

1. Find the issue number.
2. Using the issue number, find the issue labels.
3. Add the labels from the issue onto the pull request.

Consider whether to have all this logic in one file, or split into two, or even three files, so that they may be reused in future GitHub actions. If a discussion must be had with the team, feel free to open it up.

#### B. yml files
- [add-issue-labels-to-pr.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-issue-labels-to-pr.yml)
- [wr-add-issues-labels-to-pr.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/wr-add-issues-labels-to-pr.yml)

#### C. Helpful links

- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)
- [GitHub RESTAPI](https://docs.github.com/en/rest)
- [GitHub GraphQL API](https://docs.github.com/en/graphql)
- [Keeping your GitHub Actions and workflows secure: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
- [octokit/rest.js](https://octokit.github.io/rest.js/v18)
- [Github Actions only triggers on default branch](https://github.com/actions/checkout/discussions/277)

**Comment by ExperimentsInHonesty** [comment]
@glenflorendo I moved this to in progress.  You need to do that when you self assign.  Also, you need to indicate what your availability is for the next week and when you think this issue will be completed.

**Comment by glenflorendo** [comment]
Progress: Going through some docs on GitHub Actions right now.

Blockers: N/A

Availability: I'm generally available during the evenings for this week and the weekend.

ETA: I expect to be done by the end of next week, hopefully.

**Comment by glenflorendo** [comment]
Progress: Working through it. I was delayed, since I didn't know how to test GH Actions locally. Though, I found a way to do that now, so development should speed up now.

Blockers: N/A

Availability: I'm generally available during the evenings for this week and the weekend.

ETA: I aiming to have a PR ready by end of this week.

**Comment by glenflorendo** [comment]
Progress: Almost done, but I'm trying to see if I can improve things any further.
Blockers: N/A
Availability: A few hours per night.
ETA: Hopefully, by Sunday 9/25.

**Comment by glenflorendo** [comment]
Progress: I'm just about done! However, I would like to go over a few clarifying questions, probably with @macho-catt and @abuna1985. I can bring it up on our Thursday night meeting unless y'all want to meet earlier!

Blockers: N/A

Availability: I am available almost every afternoon and evening this week (except Wednesdays).

ETA: Hopefully, by end of the week. I just need a few things clarified.

Pictures: N/A

**Comment by macho-catt** [comment]
@glenflorendo I can DM you on slack for my availability

**Comment by glenflorendo** [comment]
> @glenflorendo I can DM you on slack for my availability

@macho-catt Thanks for clarifying with me! I'll get this done soon. 😄 ✌🏽

**Comment by macho-catt** [comment]
Hi @glenflorendo, any updates on this? Thanks :)

**Comment by glenflorendo** [comment]
> Hi @glenflorendo, any updates on this? Thanks :)

Hey @macho-catt! Sorry for the delay. I had a busy week, but things have settled down. I'm just about done. I think it would be great if we could demo this a bit. I made some changes, so it would be great to make sure this behaves as expected. 😸

**Comment by macho-catt** [comment]
@glenflorendo reached out to you on slack, sorry I missed your message!

**Comment by glenflorendo** [comment]
Awaiting review on PR.
