### ISSUE TITLE
Standardize code for header layout 

### ISSUE THREAD

**Issue by arghmatey** [hackforla/website#1898]
### Overview
Create standardized header layout component html and css to ensure visual consistency, and to make creating new pages easier and more efficient.

### Action Items
- [x] Determine class names and properties necessary based on Figma file
- [x] Implement CSS and HTML changes to create standard header component to all pages that use this specific component layout 
- [x] Update [How to create a page on the HfLA website](https://github.com/hackforla/website/wiki/How-to-create-a-page-on-the-HfLA-website) wiki page
- [x] Release dependency on #19 

### Resources/Instructions
Issues with current header layout commented on #1791

**Comment by arghmatey** [comment]
HTML code and reusable class names are complete for the page header. 
- [x] Determine where the CSS should live for reusable classes in order to create PR
- [x] Discuss changing the template on the [How to create a page on the HfLA website](https://github.com/hackforla/website/wiki/How-to-create-a-page-on-the-HfLA-website) wiki page

**Comment by Sihemgourou** [comment]
Hi @arghmatey, please add a size to the issue :) thanks!

**Comment by arghmatey** [comment]
@Sihemgourou Done!

Meeting with Danielle tomorrow to discuss my previous comment. If all is good, PR to be submitted tomorrow afternoon.

**Comment by Sihemgourou** [comment]
perfect thanks ! don't hesitate to use this template for next time 

1. Progress
2. Blockers
3. Availability
4. ETA
Thanks :)

**Comment by adam-abundis** [comment]
The `dependency` tag has been removed from #19

**Comment by adam-abundis** [comment]
Updated [How to create a page on the HfLA website](https://github.com/hackforla/website/wiki/How-to-create-a-page-on-the-HfLA-website) wiki page.
