### ISSUE TITLE
Add your Duplicate Style Classes HERE!!!!

### ISSUE THREAD

**Issue by averdin2** [hackforla/website#1901]
### Overview
I am starting this issue off as more of a discussion place. 

Currently, there are many places within the codebase where the same style classes are copied and pasted in multiple different files. We want to keep the codebase clean by maintaining a single source for classes that are being used in multiple places. We need to prioritize communicating with the team that if they are finding themselves copying and pasting styles from another file into a new file, that they should consider placing those styles in a consolidated place to keep the code clean. We also need to give some guidance on where these good consolidated places are within the codebase. 

I think that there are too many instances for just one person to go through the code and fix everything, but if we can encourage the team to fix these issues as they are working on other issues, then we may be able to remedy this problem.

I am thinking we can use this issue as a discussion place for potential issues regarding fixing duplicate styles, and we can make more actionable issues based on those discussions if it is needed.

- One place I am already seeing potential issues with is with our refactoring of the home page. A lot of styles in the [_home.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_home.scss) file are being used in the home page, but may also be used elsewhere in the future (some styles are being used in the new projects page). There is a file called [_projects.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_projects.scss) which is a complete copy of some styles in the _home.scss file, but they are being duplicated into another styles file when making the new projects page. Where are we going to want the styles from the _home.scss file once the home page is refactored?

### Resources/Instructions
None as of this time, but if we want to make this issue a more actionable one, feel free to add action items.

**Comment by ExperimentsInHonesty** [comment]
Discuss issue where we have been fixing class issues in specific files, and we might need to be fixing them in a higher level so that all pages can use them.

Example
PR #2005 / Issue #1919
- https://github.com/hackforla/website/pull/2005/files
- https://github.com/hackforla/website/blob/gh-pages/_sass/components/_program-areas.scss

Issue #1908  - I don't know

**Comment by Abel-Zambrano** [comment]
@averdin2 Will change this issue into an actionable issue.

**Comment by SAUMILDHANKAR** [comment]
@averdin2 should this still be open?

**Comment by adam-abundis** [comment]
Closing this issue. If there is a need to document duplicate styles, please re-open this issue.
