### ISSUE TITLE
Two of the same badges appear together in the same card within the Wins Page

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#1911]
### Overview
We need to have unique icons for the three types of mentoring on the wins page to indicate the difference.

### Action items
Development
- [x] Replace old mentorship badge icons with new ones as shown in linked Figma file in the yellow box, see this comment below to know which ones you are looking for https://github.com/hackforla/website/issues/1911#issuecomment-903313669

### Extra details you probably don't need to read (from before the issue was assigned to dev)
When the following wins are chosen:
  - I mentored someone on my team
  - I mentored someone on another team
  - Found a Mentor

They show the same icon. We would like to find/create new icons for 2 of these so that each win has a unique icon. 

<details>
  <summary>Current card with <em>I mentored someone on my team</em> and <em>I mentored someone on another team</em></summary>
  <img src="https://user-images.githubusercontent.com/21162229/125144997-a3c1ae80-e0d4-11eb-9bb9-48648dfab6f0.png" />
</details>

### Action Items
Team discussion
- [x] Determine with the website dev team how feasible it is to come up with a new icon for <em>I mentored someone on another team</em>

Design
- [x] Find 2 new icons ([NounProject](https://thenounproject.com/) is a good resource) in a similar style to current icons.
- [x] Replace old icons with new ones in this [Figma frame](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=10117%3A10218)
- [x] Add credit information for new icons, following the way it's listed in the green rectangle on the same Figma file. 

### Resources/Instructions

- https://hackforla.org/wins/
- [Issue 1817 thread - background](https://github.com/hackforla/website/issues/1817#issuecomment-873642174)
- [Figma - Wins Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0) Yellow rectangle section shows updated design with unique icons. 
- [NounProject](https://thenounproject.com/)

**Comment by jbubar** [comment]
IMPORTANT!! 
This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)

**Comment by janieche** [comment]
Progress: Assigned, next steps are to look for new icons and replace in Figma
Blockers: n/a
Availability: 7/30 (evening), 7/31 (morning, early afternoon), Tuesday (evening)
ETA: Wed 8/4

**Comment by janieche** [comment]
Added two new mentor icons. The final version is in the yellow frame [here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=13423%3A90826).

**Comment by kristine-eudey** [comment]
Design work has been reviewed and is ready for development. Image credit links are in green frame.

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-design   I looked at the figma link provided above and check the blue section of the figma page and could not find the new icons.

**Comment by ExperimentsInHonesty** [comment]
![mentor1](https://user-images.githubusercontent.com/37763229/130366601-4abae723-5958-4772-ac09-b54f9e295920.png)
![mentor2](https://user-images.githubusercontent.com/37763229/130366603-85d25f20-2532-4bff-8432-87b6bbd7da0f.png)

**Comment by kristine-eudey** [comment]
@ExperimentsInHonesty the current design with the new icons are shown in the yellow rectangle [here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=13423%3A90826)
