### ISSUE TITLE
Fix Communities of Practice page mobile view

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1919]
### Overview
We need to fix the [Communities of Practice page](https://www.hackforla.org/communities-of-practice)'s mobile view because somehow it has changed and some sections no longer match the original Figma design

### Action Items
- [ ] Ensure that all of the page cards (in mobile) have a consistent image height- they should match the ones in the [Program Areas page](https://www.hackforla.org/program-areas).
   - [ ] The images for the Ops and UI/UX cards are currently too tall (see screenshot below) - they need to match the rest 
- [ ] The leader cards' text in mobile currently looks different from the [original Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3194%3A25627) (in pink rectangle)- the lines wrap to a second row even though they shouldn't (see screenshot below). Please fix them so that they match the original design

### Resources/Instructions
[Communities of Practice page](https://www.hackforla.org/communities-of-practice)
[Original Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3194%3A25627) (in pink rectangle)
[Program Areas page](https://www.hackforla.org/program-areas)

<details>
<summary>Page cards images in mobile that are too tall</summary>
<br>
<img width="200" alt="Screen Shot 2021-07-11 at 8 44 02 AM" src="https://user-images.githubusercontent.com/67400366/125201734-2d809180-e225-11eb-943a-3eaf213c0325.png">
</details>

<details>
<summary>Current leader cards that don't match the original design (incorrect)</summary>
<br>
<img width="150" alt="Screen Shot 2021-07-11 at 8 47 29 AM" src="https://user-images.githubusercontent.com/67400366/125201791-5c970300-e225-11eb-9797-af8bd7f833a4.png">
</details>

<details>
<summary>Original Figma design leader cards (correct):</summary>
<br>
<img width="150" alt="Screen Shot 2021-07-11 at 8 47 38 AM" src="https://user-images.githubusercontent.com/67400366/125201807-7a646800-e225-11eb-8ed6-0829306efd09.png">
</details>

**Comment by adam-abundis** [comment]
@daniellex0 I may have figured out the bug. So the `<svg>` is nested in an `<object>`. there is a class `header-img--communities` which has a `margin-left` of 80px. This extra 80px is being applied to the width of the `<svg>`. Please see the image below:

<details>
  <summary>Screenshot of header image with 80px of margin-left</summary>
  <img src="https://user-images.githubusercontent.com/21162229/125206348-af7bb500-e23b-11eb-93a1-395b9a0929b2.jpg" />
</details>

<details>
 <summary>Screenshot of header image with <strong>NO</strong> margin-left</summary>
 <img src="https://user-images.githubusercontent.com/21162229/125205439-18146300-e237-11eb-9198-6b50e32086d7.jpg" />
</details>

### Potential Solution

Wrap `<object>`, `<svg>` in a `<div>` and add the `margin-left` 80px to that `<div>`. Or you can set `display: flex` on the `<div>` and place it centered (`justify-content: center`)

**Comment by daniellex0** [comment]
@abuna1985  Ohhh yeah that sounds right, thank you for figuring it out!! 💯  Do you want to implement the fix, or should we make this a good section issue (or small issue) and someone can follow your instructions?
