### ISSUE TITLE
Write user stories for Hack for LA Leader persona

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#192]
### Overview
Write user stories for Hack for LA Leader persona

### Action Items
- [ ] Write some user stories that describe your needs and wants as a Hack for LA leader within the [Personas and User Stories](https://github.com/hackforla/website/projects/6) board

### Resources/Instructions

**Comment by ExperimentsInHonesty** [comment]
Leader is responsive to Donor/Advisor volunteer/Partners. so no leader persona needed
