### ISSUE TITLE
Standardize photo page cards in mobile Events page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1920]
### Overview
We need to try to standardize the image page cards' mobile view in the [Events page](https://www.hackforla.org/events/), because the images are too tall

### Action Items
- [x] Try to decrease the mobile view height of the images in the Events page's image cards, to match similar ones in other pages' mobile view (like [Program Areas](https://www.hackforla.org/program-areas)) - see screenshots below for reference
   - [x] Try to make sure the location text still appears- try to cut off the top of the image instead

### Resources/Instructions
[Events page](https://www.hackforla.org/events/)
[Program Areas](https://www.hackforla.org/program-areas) (reference for good page card mobile image height)

<details>
<summary>Current Events page mobile page card image height (too tall)</summary>
<br>
<img width="200" alt="Screen Shot 2021-07-11 at 8 58 16 AM" src="https://user-images.githubusercontent.com/67400366/125202141-1773d080-e227-11eb-87de-f22b5553bf8c.png">
</details>

<details>
<summary>What the height should look like:</summary>
<br>
<img width="200" alt="Screen Shot 2021-07-11 at 8 58 25 AM" src="https://user-images.githubusercontent.com/67400366/125202173-45591500-e227-11eb-9d7f-ea8b12c64caf.png">
</details>

**Comment by adam-abundis** [comment]
@MariannaAskova Are you still working on this issue? I do not see an update for 2 weeks now.

**Comment by macho-catt** [comment]
We're putting this back to the backlog for the time being since the issue has not been worked on for two weeks.

**Comment by blakes24** [comment]
### Update

1. Progress: Pull request made
2. Blockers: None
3. Availability: open
4. ETA: pending review
5. Pictures: 

<img width="387" alt="Screen Shot 2021-08-20 at 11 49 09 AM" src="https://user-images.githubusercontent.com/62186905/130304747-a5785c25-1090-4c0b-9770-ee3688396c45.png">
