### ISSUE TITLE
Audit all buttons on hackforla.org website

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#1921]
### Overview
We need to do an audit of the buttons on the website so that their coding can be consistent across the site.

### Action Items
- [x] Make a spreadsheet in the hackforla.org website shared drive with the following columns: 
   - [x] **Name** (Name of button, for example, "donate button", "join us button", etc)
   - [x] **Page** (What page button appears on, can be more than one page, for example "home", "wins", "projects/engage")
   - [x] **Action** (Desired Action of Button - probably what it already does now, for example, "links to [page]")
   - [x] **Code**
   - [x] **Recommendation** (what the new code should be -- see Ava's [recommendation/proposal](https://github.com/hackforla/website/issues/1352#issuecomment-877676139)
- [x] Find all the buttons and fill out the spreadsheet

### Resources/Instructions
[Audit of Buttons google sheet](https://docs.google.com/spreadsheets/d/1n3va-1kwGOCTP4JaXpL3TjgvS_2RWDkurb8PyCJSp-0/edit?usp=sharing)
#2104

**Comment by adam-abundis** [comment]
Created a spreadsheet within the HackForLA google drive. The audit should be complete by tomorrow afternoon.
[Spreadsheet can be found here](https://docs.google.com/spreadsheets/d/1n3va-1kwGOCTP4JaXpL3TjgvS_2RWDkurb8PyCJSp-0/edit?usp=sharing)

**Comment by adam-abundis** [comment]
@hackforla/website-write Completed audit of all buttons on the HfLA website:
- **27** buttons using the `btn` class
  - **19** buttons that need to be refactored
  - **8** buttons that do not need changes

**Next Steps:** I will create an issue to standardize the 20 buttons within the [Google Sheets Button Inventory](https://docs.google.com/spreadsheets/d/1n3va-1kwGOCTP4JaXpL3TjgvS_2RWDkurb8PyCJSp-0/edit?usp=sharing)

**Comment by adam-abundis** [comment]
Created #2104 to track changes to HTML buttons.

**Comment by adam-abundis** [comment]
All tasks are complete for this issue.
