### ISSUE TITLE
Update Project Profile: Engage

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#1923]
### Overview
We need to update the Engage project's hero so that it will render properly.

### file locations
location of their project card: /gh-pages/_projects/engage.md
location of their current hero: image-hero: /gh-pages/assets/images/projects/engage-hero-2.jpeg

### Action Items
- [ ] replace their hero image with the one provided by
   - [ ]  downloading it, renaming it engage-hero.png and putting in the /gh-pages/assets/images/projects/ folder
   - [ ] change the reference to it in the engage.md file to be /assets/images/projects/engage-hero.png
   - [ ] delete the file /gh-pages/assets/images/projects/engage-hero-2.jpeg

### Resources
Link to the new image [here](https://drive.google.com/file/d/1P0m4tOu40c3hUfH6rNzoUsM6ubddYKzu/view?usp=sharing).

**Comment by JasonUranta** [comment]
@rmayott Here is a screenshoot of what the new image looks like in the page on my local development branch, the image is still being cut off. Do you want to provide an image that is a bit lower.
![Screen Shot 2021-07-15 at 9 28 59 AM](https://user-images.githubusercontent.com/86503503/125823371-f58a69c9-f64d-413e-9467-5ecd1fe2a4b7.png)

**Comment by rmayott** [comment]
@JasonUranta Hmmm interesting. Here's an [image](https://drive.google.com/file/d/1nktZFztwR14d8NWMBZR0awkvIRMAJSii/view?usp=sharing) without the logo. That should fix the issue!
