### ISSUE TITLE
Add project-specific language metadata to Project Home Page

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#193]
### Overview
Collect project-specific language data

### Action Items
- [ ] Collect project-specific language data from project leads and enter into spreadsheet on Google Drive
- [ ] Slack Stephen Nelson link to spreadsheet so he can add to yml and update page

### Resources/Instructions
Where Jekyll stores it data [overview](https://jekyllrb.com/docs/datafiles/)

**Comment by ExperimentsInHonesty** [comment]
@StephenVNelson is working on this Jan 1-1 week.  demo on 6th

**Comment by StephenVNelson** [comment]
Update:
I now have a GitHub action that successfully 
1. Checks out gh-pages branch
2. Makes an API call
3. sends the data to the GitHub workflow
4. forwards that data to a GitHub action that saves it as a JSON file
5. activates a GitHub action that adds all new content to the repository and commits the file

What is left to do is:
- [ ] Clean up code and add comments
- [ ] Add logic that stops the Github action if there is an error or if the API data is empty
- [ ] Add logic that stops the GitHub action if there are no differences between the current JSON data and the data from the API call
- [ ] Add "languages" data to every project page

**Comment by ExperimentsInHonesty** [comment]
@StephenVNelson Please provide an update here so we can arrange for a handoff.
1. Progress
2. Blocks
3. Availability (if you can be available for a few handoff questions, etc).
4. ETA

**Comment by ExperimentsInHonesty** [comment]
hero image https://github.com/hackforla/website/issues/272

**Comment by cnk** [comment]
Data collection script has been merged. Once data is in the repo, we can add code to include languages data to project cards

**Comment by cnk** [comment]
@KianBadie has incorporated the languages data from GitHub API into the project cards so I am closing this issue.
