### ISSUE TITLE
Tablet design for the wins page

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1933]
### Overview
There is good progress on the wins feature right now in the wins-feature-1 branch, but we have run into a design problem

The desktop behaves as expected, mobile behaves as expected, but from about 767px - 960px the wins page behavior is not perfect. 

It would be great if the design team to make a decision on what to do for this tablet-ish view

<details>
    <summary>a gif of what it looks like now</summary>

![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/53061723/125367550-2f357c80-e32d-11eb-9ecb-a10235be0257.gif)

The gif above shows the desktop view 👍,.. mobile view👍... and then an in between view🚫..
This in between view behaves a bit like mobile with the accordion see more <-> see less, 
but:
- it has two columns
- the see less is in the wrong place... it sometimes covers up words.
- the icons do not show their text

</details>

### Action Items
- [ ] look at the gif
- [ ] make a decision on what to do
- [ ] tell some developers or make an issue

### Resources/Instructions
- Thought: we could expand mobile view a little larger, or expand the desktop modal view to fit smaller screens
- If you want to pull the changes.. try these commands
```bash
git stash #make sure that everything is cleared out..
git fetch upstream 
git checkout -b wins-feature-1 upstream/wins-feature-1
docker compose up #run the site
```
***adapted from [this wiki](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)

**Comment by daniellex0** [comment]
Please make tablet same as mobile- thank you!
