### ISSUE TITLE
Update lucky parking project profile card

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#1944]
### Overview

As a product manager I need to have my project profile card up to date.

### Action Items

- [x] Remove these people from the Lucky Parking project team:
  - [x] David Kim
  - [x] Abhinav Bommakanti
  - [x] Sam Guan

### Resources/Instructions

[Lucky Parking project page](https://www.hackforla.org/projects/lucky-parking)
[Lucky parking md file](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md)
[Check this template md for reference](https://github.com/hackforla/website/wiki/project.md-file-template)

**Comment by natenateo** [comment]
thank you

**Comment by Jain8888** [comment]
This is first issue. I am still setting up my dev-environment. I am working on reading the 'how to contribute' document and will try to resolve this issue by next Sunday

**Comment by Zhu-Joseph** [comment]
1. Progress: Started getting more familiar with code, structure, and website processes.
2. Blockers: None so far.
3. Availability: Normal working hours.
4. ETA: I think I should get it done by the end of Tuesday.
