### ISSUE TITLE
Adjust Homepage filter dropdown checkboxes and text

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1948]
### Overview
Per issue #1398 , we need to adjust the homepage filter dropdown checkboxes to have better functionality/accessibility, and to have better vertical alignment

### Action Items
- [x] In filter drop-downs, extend hover-over pointer from just the checkbox to include pointer over the text as well (sorry, screenshot won't capture this)
- [x] Improve alignment of checkboxes with their text (currently text is a little lower- should be evenly aligned) (see screenshot below)

### Resources/Instructions
[Homepage](https://www.hackforla.org/#)
Issue #1398

Text should be more center-aligned with the corresponding checkboxes:
<img width="200" alt="Screen Shot 2021-07-15 at 11 45 38 AM" src="https://user-images.githubusercontent.com/67400366/125840993-b32db656-e12a-42be-a0c2-d468026a901f.png">

**Comment by Sihemgourou** [comment]
removing @marcobarrera assignment because no update has been made since 24 days
