### ISSUE TITLE
Wins page - make the tablet like the mobile view

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#1950]
### Overview
@daniellex0 indicated in the issue below that we should have the wins page look like the mobile view in tablet (below 960px)
- #1933

### Action Items
- [x] discover where in the css and html the screen size is being used to determine the layout of the wins page
- [x] Make it so the current mobile view layout is expanded to include tablet view
- [x] Check to see that the see more see less functionality still works

### Resources/Instructions
IMPORTANT - This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)

**Comment by jbubar** [comment]
Thanks Erika!

**Comment by jbubar** [comment]
progress: Did this
blockers: Found a few more bugs that I want to fix with the same pr
ETA: Tomorrow
availability: Today after 5pm

**Comment by adam-abundis** [comment]
@jbubar Are you still working on this? I do not see an update for 2 weeks.

**Comment by macho-catt** [comment]
Will contact @jbubar about the issue. If there's no contact, we will recycle the issue.

**Comment by jbubar** [comment]
Pretty sure that this is done. Sorry for being mia

**Comment by ExperimentsInHonesty** [comment]
@abuna1985 please UAT this

**Comment by adam-abundis** [comment]
@ExperimentsInHonesty No other issues were found.
