### ISSUE TITLE
Navigation options  (like having all pages show up in footer) for many pages

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#1969]
### Overview
We need to add all of the HfLA website's page links to the footer to help improve user navigation.

### Action Items

Design
- [x] Compile links to all of the HfLA website pages
- [x] Research footer examples with links on other websites
- [x] Duplicate current footer design in Figma and ideate new version with page links, Test different alternatives (should we put all the live pages on the footer?)
- [x] Show a few new options for footer with links to design lead/PM and get approval

Development
- [ ] Update website footer with new design with page links

### Resources/Instructions

http://civictechindex.org/home

[HfLA Sitemap on Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1558%3A13110) (current in pink rectangle) - for links
[HfLA footer design in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3417%3A3) (current in pink rectangle)

Example of Shopify footer with links (image taken from Bonnie's comment [here](https://github.com/hackforla/website/issues/797#issuecomment-723500649)):

![Screen Shot 2020-11-07 at 2 01 38 PM](https://user-images.githubusercontent.com/37763229/98452180-c80e5b00-2101-11eb-8fed-81fff026a5f9.png)

**Comment by kristine-eudey** [comment]
@SaashaG Please provide an update on this issue:

- Progress
- Blockers
- Availability
- ETA

**Comment by SaashaG** [comment]
Progress: Starting the comp analysis
Blockers: n/a
Availability: varied
ETA:Update at next design meeting

**Comment by kristine-eudey** [comment]
Hi @SaashaG, thanks for working on this! Please comment on this issue to add these things as discussed in our last Thursday meeting:

- Any updates
- A link to your competitive analysis
- Your design work to the [Figma footer page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3417%3A3)

**Comment by SaashaG** [comment]
**Progress:** Competitive Analysis complete [here](https://docs.google.com/document/d/1FqiwafJQPfnat6HCF9zaqLczNXVOKh83OuzNL1lCINg/edit?usp=sharing), moving on to design ideation
**Blockers:** n/a
**Availability**: varied
**ETA**: 8/14/21

**Comment by Sihemgourou** [comment]
Hey @SaashaG just compiled a similar issue into this one, please feel free to ask me any question if needed :)

**Comment by SaashaG** [comment]
Progress: Design Ideation
Blockers: n/a
Availability: varied
ETA: TBD
See design option screenshots and linked [here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3417%3A3). Let me know your thoughts before I can move on. 
![image](https://user-images.githubusercontent.com/83323065/129089902-64b53c32-0a62-46e6-9c4d-5d604187295b.png)

**Comment by kristine-eudey** [comment]
[Footer design versions](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14021%3A92886) are ready for feedback by product & dev.

**Comment by ExperimentsInHonesty** [comment]
@SaashaG I left a note in the figma file about preferring a version without the part that looks like this
> words
> --------

Caps or no caps up to team and UX Research

How to order menu (either using top menu or making a new sort order) to be determined by user testing.

**Comment by kristine-eudey** [comment]
@SaashaG  Feedback from all-team meeting on 8/15/21:

- The preference is for either option 1 or 2, the simplest versions (those without the top horizontal nav.) No top nav, no divider line, keep it as simple as possible. 
- Add “About us” and “Press to main menu
- “Project team meetings” and “Our Locations” should be replaced with “Events” page
- Design two different versions and user test these to see which organizational structure is preferred by users: 
    - One with pages organized as they are on the Sitemap / Current top menu on site (Saasha’s version) 
    - Another that uses a different organizational structure that doesn’t follow sitemap but tries to group information based on prioritization of information and main themes. (Kristine's version on bottom of Figma)

**Comment by SaashaG** [comment]
Progress: Design options linked. let me know for the final ok then I can work on mobile versions
Blockers: n/a
Availability: Varied, on vacation until Sep 12
ETA: TBD
See design options here: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3417%3A3

**Comment by kristine-eudey** [comment]
The design portion of this issue is completed and can be found in the red box here: [Figma - Footer](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14814%3A95261). 

As per team discussion and vote, we're moving forward with the navigational structure highlighted in the red box and listed as "version 2". This design moves away from grouping pages based on the current menu options in the current top nav and groups content into sections based on what we believe will be more easily navigable to users. The goal was to create more natural groupings of information which can encompass all the site’s current content and can more easily accommodate the addition of new pages to the site. It will also pave the way for an update to the top nav #1256 

Moving to UAT. Dependency for development would be all pages listed in the footer going live (I believe, correct me if I'm wrong)

**Comment by ExperimentsInHonesty** [comment]
@abuna1985 have a true/false flag for displaying the new content, and the content is driven by a markdown file.

**Comment by adam-abundis** [comment]
Created #2393 for dev implementation of the footer
