### ISSUE TITLE
Github action: To update label not working 

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#1974]
### Overview
As a Product Manager, I need the [Update Comment GitHub action ](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/update-comment-on-update-label.yml)to @ message every person assigned to the issue when I put a 'To Update !' label.

#### Clarification

**How the GHA works currently:** 

<details>
<summary>Sasha and Ava are assigned to the same issue. The github action will notify only Sasha </summary>

![Screenshot 2021-07-19 at 22 49 28](https://user-images.githubusercontent.com/55627107/126225497-9f1c93a7-87bd-4703-a4e8-9e3d94c449aa.png)

</details>

**How the GHA should work ideally:**  

<details>
<summary>Sasha and Rosalyn are assigned to the same issue. The github action will notify Sasha and Rosalyn

</summary>

![Screenshot 2021-07-19 at 22 53 35](https://user-images.githubusercontent.com/55627107/126225986-4c196646-e095-4237-b18a-5be392ffba5a.png)

</details>

### Action Items

- [x] Edit the automation such that every assignee to an issue will be notified when an update label is added.

### Resources/Instructions
Don't know how to do GitHub actions? Start [here](https://docs.github.com/en/actions)!

Other considerations: The current GitHub action uses ```peter-evans/create-or-update-comment@v1``` as a third-party action, which may or may not prove ideal. If you would like to make further edits to the GHA to remove the third-party action, you are more than welcome to as long as its final functionality remains the same.

**Comment by Aveline-art** [comment]
#### Additional resources:
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)
[GitHub GraphQL](https://docs.github.com/en/graphql)
