### ISSUE TITLE
Change Submit your pitch button on homepage

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#1975]
### Overview
We need to have the submit your pitch button convey a subject line, so that when people click on it and send an email we can tie to the action of having clicked the button.

### Action Items
- [x] Add subject line to button action

Subject line should be:
Submitting my pitch to Hack for LA

### Resources/Instructions
Example: 
```
<a href="mailto:test@example.com?subject=Testing out mailto!">First Example</a>
```

**Comment by SAUMILDHANKAR** [comment]
Progress: I have created a new pull request for the issue. I have made the changes to the homepage and request a review. 
Blockers: new learnings 
Availability: 20 hrs
ETA: this week
Pictures: ![before](https://user-images.githubusercontent.com/843538/129469450-45063b72-3f90-4410-b2cb-44689049c3e2.PNG)
![after](https://user-images.githubusercontent.com/843538/129469449-1c4d9fa6-df6d-4fc9-b77d-28993a73cf49.PNG)
