### ISSUE TITLE
Add GitHub links to Community of Practice pages

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#1979]
### Overview
We need to add GitHub links to the Communities of Practice pages in order to make GitHub more easily accessible to volunteers.

### Action Items
Design
- [x] Ideate how best to incorporate GitHub repository links for each card on the Communities of Practice page. 
- [x] Duplicate the Figma frame
- [x] Come up with 2-3 versions and create desktop and mobile designs

### Resources/Instructions
[Figma: Communities of Practice page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=6888%3A501
)
[GitHub: HfLA Communities of Practice](https://github.com/hackforla/communities-of-practice)
[GitHub: UI-UX](https://github.com/hackforla/UI-UX)
[GitHub: Product Management](https://github.com/hackforla/product-management)
[GitHub: Ops](https://github.com/hackforla/ops)
[GitHub: Data Science](https://github.com/hackforla/data-science)
[GitHub: Engineering](https://github.com/hackforla/engineering)

**Comment by kristine-eudey** [comment]
@ktlevesque19 Please provide an update on this issue:

- Progress
- Blockers
- Availability
- ETA

**Comment by ktlevesque19** [comment]
Progress: Not started
Blockers: None at this time!
Availability: I'll be tackling this early this week in the evenings
ETA: I expect to be done by this Thursday 8/5

**Comment by ExperimentsInHonesty** [comment]
@ktlevesque19 Did you mean to say 6/6?

**Comment by ktlevesque19** [comment]
Good catch, I meant this week, just updated my comment with the accurate date. Thanks!

**Comment by ktlevesque19** [comment]
Progress: Completed 
Blockers: None at this time

@kristine-eudey Just completed this so it's ready for review, there are three options in a blue square [here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3194%3A25627) - there was already a link to the slack channel for each card, so I did options for how to incorporate the GitHub links assuming equal hierarchy of the two. If you need additional options where one of these is weighted more heavily let me know!

<img width="862" alt="Screen Shot 2021-08-05 at 6 20 09 PM" src="https://user-images.githubusercontent.com/84823624/128581164-c96879b9-1123-4bc1-8683-df26aebe7ac7.png">

**Comment by kristine-eudey** [comment]
Thanks @ktlevesque19, these look great! My vote is for Option 3 with the stacked icon buttons, though we can discuss at Sunday's meeting and move a design forward from there.

**Comment by Sihemgourou** [comment]
- maybe change the wording for the github page. it should say "next steps" or something equivalent. 

- please provide another option with icones and text

**Comment by ktlevesque19** [comment]
Just updated per the feedback from Sunday's meeting. Three button options, and three copy options are [here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3194%3A25627). Visually I think my preference is still Option 3, the icon buttons get a little long side by side in Option 2. Thanks!

<img width="742" alt="Screen Shot 2021-08-09 at 11 46 02 PM" src="https://user-images.githubusercontent.com/84823624/128820805-6e6cd570-519e-4346-bcf6-a6c1696c2f17.png">

**Comment by ExperimentsInHonesty** [comment]
@ktlevesque19 we have chosen Second button option and "next steps" as the text

**Comment by ktlevesque19** [comment]
Hello, just finished this out. New button text has been updated to "Next Steps", and applied to all cards. Pink box is around newest up to date layouts. Thank you!

<img width="733" alt="Screen Shot 2021-08-25 at 8 18 01 PM" src="https://user-images.githubusercontent.com/84823624/130894959-f6953f86-089b-4481-972c-aeac1919d5e5.png">

**Comment by kristine-eudey** [comment]
The design portion has been completed and meets the requirements of the issue.

**Comment by adam-abundis** [comment]
#2357 was created to complete the dev implementation of this design
