### ISSUE TITLE
Wins Page Modal CSS

### ISSUE THREAD

**Issue by Abel-Zambrano** [hackforla/website#1982]
### Overview
Wins page modal CSS icons are not aligned with text and columns are also unaligned.

<img width="1520" alt="Screen Shot 2021-07-15 at 5 29 11 PM" src="https://user-images.githubusercontent.com/67209686/126248831-e06172bc-5503-4d88-8380-9859605ed966.png">

### Action Items
- [x] Align CSS icon with text
- [x] Center columns evenly, and align with content

### Resources/Instructions

https://hackforla.org/wins/

**Comment by adam-abundis** [comment]
@HiThereImCam Are you still working on this issue? I do not see any updates.

**Comment by HiThereImCam** [comment]
@abuna1985 sorry I got really busy during my job search. I have time in the next 2 days to finish this. I can update then.

**Comment by adam-abundis** [comment]
@HiThereImCam No worries. I completely understand. I just wanted to check-in. Just remember to update the issue (even if there is nothing new to update).

**Comment by HiThereImCam** [comment]
@abuna1985 update- I was following the steps on how to work off a feature branch but ran into a git issue. I contacted @jbubar and we'll be working on the issue together tomorrow.

**Comment by HiThereImCam** [comment]
@abuna1985 Hi Adam, is the current image below what you're looking for? 
![current-wins-modal](https://user-images.githubusercontent.com/9407189/129952122-cd59192c-7e67-4df4-ae3b-625132927e2e.jpg)

The reason why I'm asking is because I took a look at the CSS and the icons/columns were already centered.

**Comment by adam-abundis** [comment]
@HiThereImCam I would refer to the [Figma Design for the wins page(the examples in the blue border)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0). The image above seems to match the design for the modal.

**Comment by HiThereImCam** [comment]
@abuna1985 I pulled from main and checked the styling against the figma desgin and it looks good. It looks like there is nothing to do and I recommend we close it. I am going to unassign myself. Thanks.

**Comment by adam-abundis** [comment]
@HiThereImCam did you pull from the `wins-feature-1` branch per the instructions above?

I can take a look at this later today.

**Comment by HiThereImCam** [comment]
@abuna1985 Correct. I was on a zoom call with @jbubar to ensure I was on the right branch.

**Comment by adam-abundis** [comment]
As I understand we are trying to adjust the icon/text in desktop view. When a user clicks on the `see more` link, it creates a modal version of that card (see below). @Abel-Zambrano or @jbubar I am going to fix the issue to address what needs to be done. It seems like there are edits to be made, but they are not mission-critical.

<details>
  <summary>Click to see current modal in desktop view</summary>
  <br >
  <img src="https://user-images.githubusercontent.com/21162229/130846849-de7cc8bd-3426-4ecb-b540-8096980b4b9b.jpg" />
</details>
<details>
  <summary>Click to see Figma modal in desktop view</summary>
  <br >
  <img src="https://user-images.githubusercontent.com/21162229/130848657-ed90f5f5-0060-4fc8-8980-6489a497149c.jpg" />
</details>

**Comment by Abel-Zambrano** [comment]
@abuna1985 I just took look at the wins-feature-1 wins page and it seems this issue was already resolved on another PR. Sorry for the confusion but we can close this issue if you agree with the current styling.
<img width="676" alt="Screen Shot 2021-08-29 at 9 33 47 AM" src="https://user-images.githubusercontent.com/67209686/131258124-20f42bf2-5081-47b3-951c-1e6f973b16ae.png">

**Comment by braguda** [comment]
Availability: 2 hours
ETA: 10/19/2022

**Comment by braguda** [comment]
Update-
Progress: Currently working on issue
Blocker: I am reading through the comments and am a little confused on whether this issue was already resolved on another pull request. 
Availability: 2 hours
ETA: 10/20/2022

**Comment by DmitriiTsy** [comment]
@braguda Hi Brian? Do you have any updates regarding this issue by any chance? 
If there is another PR with the solved issue I can put this task to "help wanted"

**Comment by DmitriiTsy** [comment]
<img width="466" alt="Screen Shot 2022-10-21 at 19 00 12" src="https://user-images.githubusercontent.com/101737790/197311827-92a382cd-ea99-4a10-a161-1eda2af4bd3a.png">

i. Availability: 2 hours
ii. ETA: 10/21/2022

@JessicaLucindaCheng Could you, please, close this issue?

**Comment by Abel-Zambrano** [comment]
Can I please be removed from these emails.

Thank you
Sent with Spark

**Comment by ExperimentsInHonesty** [comment]
@Abel-Zambrano Hope you are doing well.  Sadly, we cannot remove you from notifications.  Only you can do that.  Open this issue and click the button  `Notifications`

![image](https://user-images.githubusercontent.com/37763229/197404163-b7d0551d-4cfe-4419-aa91-a798530dee68.png)

**Comment by ExperimentsInHonesty** [comment]
I am closing this issue.  Not sure why it was still open  But will send to dev leads in case I am missing something.  Unassigning @DmitriiTsy

**Comment by blulady** [comment]
It looks like the wins-feature-1 branch has already been merged. The comment history  mentions that the issue was addressed by another PR, it would be nice if they had included the link to that PR. I also took a look at the wins page and it looks like the picture referenced by this [comment](https://github.com/hackforla/website/issues/1982#issuecomment-907823063). I think we are good.
