### ISSUE TITLE
Wins Page "see more" Toggle/Link - Mobile Screen

### ISSUE THREAD

**Issue by Abel-Zambrano** [hackforla/website#1984]
### Overview
“see more” toggle/link is not aligned with content - **Mobile Screen**

<img width="366" alt="Screen Shot 2021-07-19 at 6 44 47 PM" src="https://user-images.githubusercontent.com/67209686/126249694-80598c17-93a3-4cf5-8ade-c6c0e85e70af.png">

### Action Items
- [ ] Align "see more" with content.

### Resources/Instructions

IMPORTANT!!
This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)

Once you have pulled the feature branch to your environment, you can access the wins page to work on: [Wins Page](http://localhost:4000/wins/)

**Comment by lorenzejay** [comment]
I can't seem to replicate the view for this issue. This is how it looks on my end for the mobile view. @Abel-Zambrano 

![Uploading Screen Shot 2021-07-21 at 10.03.28 AM.png…]()

**Comment by Abel-Zambrano** [comment]
Hello @lorenzejay 

I updated the issue instructions. Sorry, it wasn't clear. You have to pull the feature branch to your environment and then go to the page link. Don't go to the page on the live site. I just checked and the bug is still there. Let me know if you continue to have problems.

Thank you,

**Comment by lorenzejay** [comment]
Gotcha, thank you for the clarification. @Abel-Zambrano

**Comment by lorenzejay** [comment]
@Abel-Zambrano and to be specific, the feature branch is the [wins-feature-1 branch](https://github.com/hackforla/website/tree/wins-feature-1) correct?

**Comment by Abel-Zambrano** [comment]
@lorenzejay correct

**Comment by lorenzejay** [comment]
I am on the specific branch with the link you provided and cannot replicate the issue. Can I get another dev to double check?

<img width="458" alt="Screen Shot 2021-07-27 at 6 05 58 AM" src="https://user-images.githubusercontent.com/63378463/127158697-f678bbdb-bfbe-45b4-889b-c4f4ced9b16c.png">
<img width="498" alt="Screen Shot 2021-07-27 at 6 06 06 AM" src="https://user-images.githubusercontent.com/63378463/127158702-5ebe55bc-cc94-4a8b-b4b5-95ce1337f6f5.png">
<img width="390" alt="Screen Shot 2021-07-27 at 6 06 36 AM" src="https://user-images.githubusercontent.com/63378463/127158711-01cdb809-65ce-435f-932b-eb00984d3e98.png">

**Comment by adam-abundis** [comment]
@lorenzejay Are you still working on this issue? I have not seen 3 updates for the last 3 weeks.

**Comment by macho-catt** [comment]
This may have been fixed already by @jbubar because I cannot see the issue on my environment as well. Josh, can you confirm? 
For now, we can un-assign @lorenzejay from this.

**Comment by jbubar** [comment]
Could not replicate either. I might have been fixed by accident w my last pr
