### ISSUE TITLE
Community of Practice Change: UI/UX

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#1987]
### Overview
As a product manager of UI/UX I want my CoP details to be up to date on the HackforLA website

### Action Items for requestor
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] Name of CoP 
      - [x] Description
      - [x] Meeting Times cannot be changed here.  Create an issue at VRMS for changing [meeting times](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=) if needed
      - [x] Leadership Type: 
      - [ ] leadership
         - [ ] name
         - [ ] GitHub Handle
         - [ ] Slack Member ID
      - [x] links
         - [ ] Slack

### Action items for Development
- [ ] Make changes to the [Community of Practice page](https://www.hackforla.org/communities-of-practice)

### Resources
[UI/UX CoP data - _data/internal/communities/ui-ux.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/communities/ui-ux.yml)

**Comment by ExperimentsInHonesty** [comment]
Add the following people to Leadership

Felicia Swafford 
slack id U0252LV021F
gihub feswafford

Kevin Wang 
Slack ID: U01GZHT5CM8
github: kvnw2020

**Comment by kristine-eudey** [comment]
Remove the following people from Leadership:

Danielle Nedivi
Tan Zhou
