### ISSUE TITLE
Github action : check issues that are not on the repo

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#1988]
### Overview
Problem: As of today,  HFLA contributors often forget to put their issue on the project board after creating them. The results is that some issues never get done because no one can find them. 

Solution: As a HFLA website contributor, I need to get notified if I forgot to put my issue on the project board so that my issue will be referenced on the project board.

### Action Items

- [ ] Create a github action that put a comment and @ message the creator of the issue with this template: " Hi @nameofthecreator, your issue is not on the project board, do you want to put it there ?"
- [ ] The action should be done every time a new issue is created without been put on the project board

### Resources/Instructions
Don't know how to do GitHub actions? Start [here](https://docs.github.com/en/actions)!

**Comment by Aveline-art** [comment]
Note: this issue can be reworded as an additional check for our [add-missing-labels GHA](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-missing-labels-to-issues.yml). Also, this and the missing labels action needs to consider issues that are opened elsewhere and transferred.

**Comment by Aveline-art** [comment]
Closed because #2127 already solves this issue
