### ISSUE TITLE
Create privacy policy

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#1989]
### Dependency 

https://github.com/hackforla/product-management/issues/26
#2105

### Instructions for HFLA team only.  Everyone else ignore
later we will need the following for the hfla site.  
   - [x] Move hackforla/website#797 from icebox to prioritized backlog
- [x] Design
   - [x] Create a design for a page that is just header/content/footer with content in one box
- [ ] Development 
   - [ ] Deploy page
Kian said : Link to the default layout we have: https://github.com/hackforla/website/blob/gh-pages/_layouts/default.html {{ content }} is where I believe the markdown file content would be inserted

@Rankazze Here is a empty doc for you to start your draft in: [Hackforla.org privacy policy draft doc](https://docs.google.com/document/d/19x1KsMTU-QBdopiV08HSBQ0i4g1ChrcPZ8ZXmUK50cY/edit#heading=h.wt4woon64tf1)
[template for privacy policy](https://docs.google.com/document/d/1PJtUTFR49n1nFjCYYVo9YdqJBKhdNrXP4wAyxxGz38c/edit#heading=h.1kvk4qkoxhzw) with city partner (made from TDM privacy policy)
Here is another [privacy policy template](https://docs.google.com/document/d/1SzbcR7Yb4VRzQABh8gMA4w-mdHNNRgQWOvcaaMlJbYg/edit) from Andan (a lawyer who works on EpungeAssist

[HackforLA privacy policy](https://docs.google.com/document/d/19x1KsMTU-QBdopiV08HSBQ0i4g1ChrcPZ8ZXmUK50cY/edit#heading=h.1psei6otfr6f) to publish on our website

**Comment by ExperimentsInHonesty** [comment]
closing this issue because there is another issue already on the product management board

**Comment by Aveline-art** [comment]
@ExperimentsInHonesty I noticed a P-feature label on this. Does this involve a new page for the website? The issue itself is very unclear.

**Comment by Rankazze** [comment]
@ExperimentsInHonesty   I have completed the Draft HackforLA Privacy Policy
https://docs.google.com/document/d/19x1KsMTU-QBdopiV08HSBQ0i4g1ChrcPZ8ZXmUK50cY/edit#heading=h.1kvk4qkoxhzw

**Comment by ExperimentsInHonesty** [comment]
I have edited and accepted the privacy policy.

**Comment by ExperimentsInHonesty** [comment]
@macho-catt to make a new issue for the privacy policy getting added as a page on the website
