### ISSUE TITLE
Add 'antonio-revilla' at Team Level to project GitHub

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#199]
### Overview
Add 'antonio-revilla' to project GitHub

### Action Items
- [ ] Add 'mailemalin' to project GitHub
- [ ] Update Team Roster to reflect

### Resources/Instructions

**Comment by ExperimentsInHonesty** [comment]
@harishlingam please close this issue and the issues related to it.  If it still needs to be done, please make into one issue

**Comment by ExperimentsInHonesty** [comment]
@harishlingam I believe this is the issue you created to replace this and the other issues: https://github.com/hackforla/website/issues/195

**Comment by ashlingam** [comment]
@ExperimentsInHonesty That's correct. The individual cards for each new member were redundant and consolidated into one card. All new members on the Team Roster have been added to GitHub now and I'm closing the redundant open issues.
