### ISSUE TITLE
HackForLA Wiki: Audit wiki articles to bring them up to date.

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#1992]
### Dependency
- [x] #3636
- [x] #1534 Bonnie will sort out which issues are still needed.
- [x] #4589

### Overview
As a member of the team, it is very discouraging when the wiki documentation turns out to be unhelpful. We need to have wiki articles that are up-to-date.

### Action Items
- [ ] Perform an audit of all wiki articles, and record results in a spreadsheet.
- [ ] For each wiki article, record the title, link, a brief note of its content (10 words or less), and one (and only one) of these labels
  - [ ] FINE AS IS: meaning, no change is needed
  - [ ] OUTDATED: meaning the information no longer applies to the project as it currently stands
  - [ ] FIX AS WE GO ALONG: meaning that information might be outdated but can be updated along with some issues
    - [ ] For example, if an issue involves changing or standardizing the headers, the [How to create a page wiki](https://github.com/hackforla/website/wiki/How-to-create-a-page-on-the-HfLA-website) needs to be updated along with the changes to the headers
  - [ ] NOT NEEDED: meaning this wiki is not useful to the dev team, the design team, or the PM team, and should be removed
  - [ ] CONFUSED AS TO PURPOSE: meaning you have no clue what this is about, and we should discuss this during a meeting
  - [ ] REQUIRES DISCUSSION: meaning that it might be useful to someone, or might not, but we need to ask to find out
- [ ] Create an issue for adding the articles labeled FIX AS WE GO ALONG to the How To Create an Issue wiki if it exists. Otherwise, add this step to [this issue](https://github.com/hackforla/website/issues/1941).

### Resources/Instructions
[Wiki](https://github.com/hackforla/website/wiki)

The purpose behind this audit is to make sure everything is up-to-date, and the labels will help us determine what steps to take with each article. We want to avoid a rewrite of the entire wiki. Instead, focus must be on the most useful articles. Therefore, when deciding which label is best, ask yourself:

1. Do the dev, design, and PM team use the information in this article?
2. Will the cost of updating this article ultimately speed up development time of the team?

Remember the goal of the wiki is to provide information in the hopes that it will A) bring people up to speed on our project and B) relay information that will increase our [velocity](https://en.wikipedia.org/wiki/Velocity_(software_development)) by guiding team members on all areas of the project (reviewing pull requests, creating issues, resolving projects/tickets, designing web pages, onboarding/training people to our project).

**Comment by Aveline-art** [comment]
@hackforla/website-admins @hackforla/website-design  I made this issue in a bit of a flurry, especially that last paragraph about the purpose of the wiki. It is only from my perspective as a developer, so that viewpoint might not match yours. I will mark this issue as Help Wanted because I have no idea how other teams uses our wiki and any feedback on such will help immensely when performing the audit.

**Comment by JessicaLucindaCheng** [comment]
This issue needs to be edited by a lead to reflect our migration to the [website-wiki repo](https://github.com/hackforla/website-wiki). For more info, read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki).

**Comment by ExperimentsInHonesty** [comment]
- This issue accidentally got remade, and the new one (#2676) has more content on it, so this issue is being closed.
