### ISSUE TITLE
Update main footer component in Figma design system using auto layout

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#1993]
### Overview
We need to update the main (master) footer component in the Figma design system - both mobile and desktop versions - because it has been updated on the website, and the Figma component needs to reflect the changes (every page using the component will automatically be updated as well). This needs to be changed using auto layout, because the original component is in auto layout.

### Action Items
- [x] Find the main footer component in the design system, all the way on the right of the file where the main/master components are (see screenshot below to know what to look for). There are new versions of the footer to the right of the current footer component for reference.
- [x] Make a duplicate of the main footer component(s) - mobile and desktop - and first practice editing them with auto layout to make them match the new footer layouts
- [x] Once you have figured out how to edit them, now edit the actual main/master footer components - desktop and mobile- using auto layout
- [x] Check any other page in the Figma file - Join Us, etc- the final designs in the pink rectangles should now have the new updated footer (desktop and mobile) if done correctly, since they all have that footer component

### Resources/Instructions
[Design System on Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3) (main footer components are all the way on the right of the file, in main/master component section)

Section to look for all the way on the right of design system:
<img width="400" alt="Screen Shot 2021-07-21 at 7 12 32 AM" src="https://user-images.githubusercontent.com/67400366/126508173-99e26366-0cb5-4104-a4ec-9888b5b180d8.png">

**Comment by ExperimentsInHonesty** [comment]
I have removed @anonymousanemone from this issue, since she is on vacation.  Sophia if you have done anything on this issue, please update it with your progress, so that the next person can pickup where you left off.

**Comment by kristine-eudey** [comment]
@anonymousanemone Please provide update:

- Progress
- Blockers
- Availability
- ETA

**Comment by anonymousanemone** [comment]
Progress: Playing with auto-layout
Blockers: None
Availability: Currently occupied with developer issue and school things
ETA: Tuesday

**Comment by anonymousanemone** [comment]
Issue completed! 
PS. Should I delete the footers on the side?

**Comment by kristine-eudey** [comment]
Design for this issue is approved.

**Comment by anonymousanemone** [comment]
Development said that this looks good, if there's any specific questions, please let us know on this issue and move this to developer meeting column.
PS. I think this component is already on the live web page. @Aveline-art

**Comment by ExperimentsInHonesty** [comment]
Make an issue for development

**Comment by anonymousanemone** [comment]
Footer has been updated to match with live version of website.
