### ISSUE TITLE
Update Community of Practice pages

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#1994]
### Dependency
- ~#1996~ 

### Overview
We need to update all the CoPs on the website https://www.hackforla.org/communities-of-practice with relevant lead info so that new members know who to reach out to

### Action Items
- [ ] Fill out template on behalf of the following CoPs
- [ ] send the issues to the CoP leads for them to edit/confirm

### Resources/Instructions
UI/UX 
Add 
- remove all

Product Management 
Add 
- Priyanka
- Bonnie

Marketing 
Add 
Bonnie
Mike Chiuasno
Sequoia 

Revenue
- Remove all

Engineering 
Remove: Greg Palwin
Add: Ava Li
End Result: Ava Li ([Aveline-art](https://github.com/Aveline-art))

**Comment by kristine-eudey** [comment]
Please see #1996 for template issue

**Comment by phuonguvan** [comment]
@ExperimentsInHonesty Hey! This is the design team lead and it's been two weeks since you worked on the project.  Please let me know if you are going to continue working!

**Comment by ExperimentsInHonesty** [comment]
This has been updated separately and the communities of practice that are dormant have been left off.
