### ISSUE TITLE
Communities of Practice information updates: UI/UX

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#1995]
### Overview
As a product manager of UI/UX I want my CoP details to be up to date on the HackforLA website

### Action Items for requestor
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] Name of CoP 
      - [x] Description
      - [x] Meeting Times cannot be changed here.  Create an issue at VRMS for changing [meeting times](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=) if needed
      - [x] Leadership Type: 
      - [ ] leadership
         - [ ] name
         - [ ] GitHub Handle
         - [ ] Slack Member ID
      - [x] links
         - [x] Slack

### Action items for Development
- [ ] Make changes to the [Community of Practice page](https://www.hackforla.org/communities-of-practice)

### Resources
To find your Slack Member ID
1. Go to your avatar in the top right corner
2. click "View Profile"
3. click "... More"
4. click "Copy member ID

**Comment by ExperimentsInHonesty** [comment]
Hi UI/UX community of practice leads, please add in your GitHub handle, Slack Member ID so we can update the community of practice page on the website:
Ryan Curtis
Felicia Swafford
Kevin Wang
Tan Zhou

**Comment by ExperimentsInHonesty** [comment]
Also, please remove Danielle so that new members don't reach out to her on slack.

**Comment by rcurtis2** [comment]
Github handle: rcurtis2
Slack Member ID: U01UPE4RNHZ

**Comment by daniellex0** [comment]
FYI @ExperimentsInHonesty you already added their information here : https://github.com/hackforla/website/issues/1987

(It's in the prioritized backlog for devs to take on)

**Comment by ExperimentsInHonesty** [comment]
Duplicate issue
