### ISSUE TITLE
TEMPLATE: Communities of Practice information updates

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#1996]
### Action Items
- [x] Draft a template in the comments below:
   - [x] name (the name you want to appear on this page: https://github.com/hackforla/civic-opportunity/issues/new/choose)
    - [x] about (the user story for when we use the template)
    - [x] title: name that matches the label [INSERT NAME OF X] (e.g., Initiative Review: [INSERT NAME OF INITATIVE])
   - [x] labels (what labels that an initiative should have when it is first opened.  This is not all the labels it will have over time, just the ones necessary for the starting of the issue - specifically the role of the first person who will work on it, and then the type of initiative or feature.)
   - [x] assignees (do not put anything here, we do not automatically assign anyone to new issues, rather we use the role labels to indicate what type of role should work on the item when its in the prioritized backlog) 
   - [x] regular format
```
### Overview
### Action Items
### Resources/Instructions
```
- [ ] Get signoff by dev/product team members that they understand how it works
   - [ ] Revise as needed
   - [ ] Repeat until done
- [ ] Make a Template out of it.  Requires Admin access to add it via the method described in the Resources below, anyone else can add using the PR method.
- [ ] UAT with product
- [x] Try it with one of the communities of practice (UI/UX) #1995 
- [ ] Release the dependency on #1994 

### Resources
**How to check if you have admin access so that you can use the administrative interface:**
<details>
<summary>you see the gear at the top of the repo</summary>

![settings](https://user-images.githubusercontent.com/37763229/126530971-3dcbcb7a-7e02-40a4-b163-a4d7519bc8f9.png)

</details>

<details>
<summary> and then the button marked "setup templates"</summary>

![templates button](https://user-images.githubusercontent.com/37763229/126531469-33516a97-5687-4c70-adef-706ff8bdf094.png)

</details>

<details>
<summary>Click on the down arrow to the right of the word select and choose Custom Template</summary>

![add template](https://user-images.githubusercontent.com/37763229/126573748-902d02c6-87a0-4e5b-829e-97bb89ac8953.PNG)

</details>

<details>
<summary>Click on the Preview and edit button</summary>

![add template 2](https://user-images.githubusercontent.com/37763229/126573940-8a8a7558-13e5-4854-8295-14c2d4a464d5.PNG)

</details>

<details>
<summary>Click on the pencil to edit</summary>

![add template 3](https://user-images.githubusercontent.com/37763229/126574086-b026f436-21de-446e-a9ff-0a7e5563ac97.PNG)

</details>

**If you don't have admin access, use the PR method to add the template**
<details>
<summary>Go to location of templates</summary>

go to [.github/ISSUE_TEMPLATE](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)

</details>

<details>
<summary>click on the Add file button > create new file in the drop down.</summary>

![add file](https://user-images.githubusercontent.com/37763229/126571271-88d990fd-f86b-486a-abd7-0e9c597981b2.PNG)

</details>

<details>
<summary>Type in the name (all lower case and with dashes where the spaces are)
Then paste in your content below</summary>

![add file-2](https://user-images.githubusercontent.com/37763229/126571274-ede72ec2-6dba-4ab9-92ab-25adf889e5e5.PNG)

</details>

<details>
<summary>Start a pull request</summary>

At the bottom of the page choose "Create a new branch for this commit and start a pull request"
Add a name for the branch
Click propose new file
![add file-3](https://user-images.githubusercontent.com/37763229/126571957-2b0098cb-3064-4b0c-a4e6-7295866f1bf9.PNG)

</details>

<details>
<summary>Submit the pull request</summary>

Add a label: role: product
Fill out the template
Submit the pull request
Contact the product team to ask for a review
![add file-4](https://user-images.githubusercontent.com/37763229/126572823-db8a428b-d062-43c3-9e72-8683d353709d.PNG)

</details>

**Comment by ExperimentsInHonesty** [comment]
### Template Draft

---
> name: Communities of Practice information updates
> about: Template for CoP leads to review and update the Name, Description. Leadership Type, Leadership members, Slack in order keep the community of practice page on the website up to date.
> title: Communities of Practice information updates: [INSERT NAME OF Community of Practice]
> labels: role: product management
> assignees: ''
---

### Overview
As a Community of Practice Co-Lead, I need my CoP's details to be up to date on the HackforLA website.

### Action Items for requestor
   - [ ] Please paste this checklist to a comment below and then check off everything that is **ok the way that it is**
```
- [ ] Name of CoP 
- [ ] Description
- [ ] Meeting Times cannot be changed here.  Create an issue at VRMS for changing [meeting times](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=) if needed
- [ ] Leadership Type: 
- [ ] Leadership
   - [ ] Name
   - [ ] GitHub Handle
   - [ ] Slack Member ID*
 - [ ] Links
    - [ ] Slack Channel
```
   - [ ] If you have someone to remove please write that below the checklist you paste in your comment
      - Example: 
```
Remove person and info from CoP card:
Name: Niven Prasad
```

   - [ ] If you have someone to add please write that below the checklist you paste in your comment
      - Example: 
```
Add person and info from CoP card:
 - Name: Ebele O.
 - Title: Co-lead
 - GitHub Handle: ebele-oputa
 - Slack Member ID: U01QJ2SB6A2
```

### Action items for Development
- [ ] Make changes to the [Community of Practice page](https://www.hackforla.org/communities-of-practice) as indicated by the comments. 

### Resources
#### Instructions for Cop lead to find the slack ID they need
To find your Slack Member ID
1. Go to your avatar in the top right corner
2. click "View Profile"
3. click "... More"
4. click "Copy member ID

#### Instructions for Developer
folder where files are in the repo: https://github.com/hackforla/website/tree/gh-pages/_data/internal/communities
where you can see the live page: https://www.hackforla.org/communities-of-practice

**Comment by ExperimentsInHonesty** [comment]
Make this into a template during pm meeting wednesday

**Comment by ExperimentsInHonesty** [comment]
We created a form under new issues for [updating communities of practice.](https://github.com/hackforla/website/issues/new?assignees=&labels=role%3A+product%2CP-Feature%3A+Communities+of+Practice&template=communities-of-practice-information-updates.yml&title=Communities+of+Practice+information+updates%3A+%5BINSERT+NAME+OF+Community+of+Practice%5D)
