### ISSUE TITLE
Add all website page links to footer

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#2000]
### Dependency
Issue #1969 

### Overview
We need to add all of the HfLA website's page links to the footer to help improve user navigation.

### Action Items

Design
- [ ] Compile links to all of the HfLA website pages
- [ ] Research footer examples with links on other websites
- [ ] Duplicate current footer design in Figma and ideate new version with page links 
- [ ] Show a few new options for footer with links to design lead/PM and get approval

Development
- [ ] Update website footer with new design with page links

### Resources/Instructions
[HfLA Sitemap on Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1558%3A13110) (current in pink rectangle) - for links
[HfLA footer design in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3417%3A3) (current in pink rectangle)

Example of Shopify footer with links (image taken from Bonnie's comment [here](https://github.com/hackforla/website/issues/797#issuecomment-723500649)):

![Screen Shot 2020-11-07 at 2 01 38 PM](https://user-images.githubusercontent.com/37763229/98452180-c80e5b00-2101-11eb-8fed-81fff026a5f9.png)

**Comment by Sihemgourou** [comment]
Closing this issue because of a duplicate issue currently in progress (#1969)
