### ISSUE TITLE
Update Project Profile: Access the Data 

### ISSUE THREAD

**Issue by abryant35** [hackforla/website#2007]
### Overview
As a product manager of Access the Data I want my project's details to be up to date on the HackforLA website

### Project card
_https://www.hackforla.org/projects/access-the-data 

### Action Items

- [x] Assess the Data Team Leadership
   - [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [x] leadership
      - [x] links
         - [x] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] looking- remove UX Lead to build surveys
      - [x] technologies
      - [x] location
      - [x] partner
      - [x] tools
      - [x] status
     
### Resources
[Markdown file where Access the Data is stored](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md)
File path: `_projects/access-the-data.md`

**Comment by ExperimentsInHonesty** [comment]
name: Lucy Chang
slack member ID: U025WJ8CHFC
Github handle: lrchang2
Title: product manager

Sarah Nabelsi
Slack ID: U01J9V1H63F
github: Sarah Nabelsi
Title: Project Manager

Alyssa Bryant
Slack ID :U026DETL43B
Github: abryant35
Title: Product manager

Jeremy DeCarvalho
Slack ID: UFDG06RJQ
GitHub: Jeremy-D
Title: Data Analyst

name: Assel Abilova
slack member ID: U026G6WV49K
Github handle: asselabilova
Title: UX/UI Designer

Name: Malak Hmimy
Slack ID: U01TL5WE7G8
GitHub: MalakH21
Title: Generalist

**Comment by abryant35** [comment]
Please update Malak Hmimy from Generalist to Data Analyst
