### ISSUE TITLE
Add Directions for a Shortcut to download Git to the CONTRIBUTING.md file

### ISSUE THREAD

**Issue by JasonUranta** [hackforla/website#2008]
### Overview
The current directions for downloading Git on the CONTRIBUTING.md file don't work for contributors with limited hard drive space (name any other issues that require this option).

### Action Items
- [x] Look into links in resources 
- [x] Decide which link is is easier to use for people new to Hack for LA.
- [x] Create step by step directions for using the chosen link or both if you decide both are equally beneficial.
- [x] Incorporate directions into CONTRIBUTING.md file.

### Resources/Instructions
The links that need to be incorporated into the CONTRIBUTING.md file are:
- [Here](https://www.ics.uci.edu/~pattis/common/handouts/macmingweclipse/allexperimental/macxcodecommandlinetools.html) (Provided by Cynthia)
- [Here](https://www.datacamp.com/community/tutorials/homebrew-install-use) (Provided by Bonnie and the link used by Jason Uranta)

**Comment by ExperimentsInHonesty** [comment]
@JasonUranta I reworded the above.  Please add any other reasons to the overview.

**Comment by JasonUranta** [comment]
@JasonUranta I went with the 2nd link (The link provided by Bonnie and the link used by me) because it explained how to download the Mac Xcode Command Line Tools and Homebrew while the first link only explained how to download the Mac Xcode Command Line Tools. The 2nd link is also more informative.

**Comment by ExperimentsInHonesty** [comment]
Next step for this is to identify size constraints of git installer and its dependents vs other methodology. and rewrite the contributing.md change to be about size.

**Comment by ExperimentsInHonesty** [comment]
@JasonUranta  Please provide any update you have related to this issue in this issue.

**Comment by ExperimentsInHonesty** [comment]
**Jason's notes** 
The download link for [Git](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git) in the current contributing.md (located under fork instructions) mentions several ways to install Git on a Mac (easy and more up-to-date version).  

Having two options can lead to confusion for new members: it is possible that some people will see the option to use the most up to date version and end up downloading the full Homebrew (8 gig package manager) before Git.

Current wording
Before cloning your forked repository to your local machine, you must have Git installed. You can find instructions for installing Git for your operating system [here](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git).

Suggested improvement is to add the add the following :
<details>
<summary>If you are installing Git on MacOS and decide to install the more up to date version of Git that the webpage mentioned.</summary>
   <br>
   You will be prompted to go to another page on the Git website and have the option to install a package manager called Homebrew as part of a way to download Git. The method given on that webpage would result in downloading a version of Homebrew that takes up a great amount of space on your Mac so I would suggest downloading Homebrew through the link <a href="https://www.datacamp.com/community/tutorials/homebrew-install-use">here</a>.
</details>

**Comment by ExperimentsInHonesty** [comment]
Current wording
Before cloning your forked repository to your local machine, you must have Git installed. You can find instructions for installing Git for your operating system [here](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git).

Suggested improvement is to rewrite:
Before cloning your forked repository to your local machine, you must have Git installed. You can find instructions for installing Git for your operating system [here](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git).  Please note that if you have a MAC the page offers several choices:
- easiest (this version is fine for use at hackforla)
- more up to date version (not required but optional if you want it): This option prompts you to go to install an 8Gig package manager called Homebrew.  If your computer is low on space, you can use this [tutorial](https://www.datacamp.com/community/tutorials/homebrew-install-use) to install XCode Command Tools and a lighter version of Homebrew and then install Git using this command: ```$ brew install git```  which in total only uses 300MB

**Comment by ExperimentsInHonesty** [comment]
Current wording
Before cloning your forked repository to your local machine, you must have Git installed. You can find instructions for installing Git for your operating system [here](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git).

Suggested improvement is to rewrite:
Before cloning your forked repository to your local machine, you must have Git installed. You can find instructions for installing Git for your operating system [here](https://git-scm.com/book/en/v2/Getting-Started-Installing-Git).  Please note that if you have a MAC the page offers several choices (see other option, if you need to conserve hard drive space):
- easiest (this version is fine for use at hackforla)
- more up to date version (not required but optional if you want it): This option prompts you to go to install an 8Gig package manager called Homebrew. 

Other option If your computer is low on space, you can use this [tutorial](https://www.datacamp.com/community/tutorials/homebrew-install-use) to install XCode Command Tools and a lighter version of Homebrew and then install Git using this command: ```$ brew install git```  which in total only uses 300MB
