### ISSUE TITLE
Audit Website for Javascript Code

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2009]
### Overview
As a website developer, the JS code is all over the place, so maintaining this will only grow into a bigger and bigger problem. We need a harder standard on how we house our JS code.

### Action Items

- [x] Find all instances of JS code.
- [x] Document it in a spreadsheet, with links, a few bits on how the code function, what pages the code is related to, and other findings.
- [x] Discuss with the team on how to handle this code on Thursday's backend meeting. Ideally, the discussion will end with issues that are made that involve our team on things that are more technical.
- [ ] For the VRMS API code, it might not be preferable to call the api multiple times. Is there a way to cache the data into a state variable that can be readily retrieved?

### Resources/Instructions
[Our codebase](https://github.com/hackforla/website)
[Link to audit spreadsheet](https://docs.google.com/spreadsheets/d/1jWVH-1QAgcaMd3BInWEW6Zaq-z9lN-C4qJ6I3mchfNs/edit?usp=sharing)

**Comment by Aveline-art** [comment]
* Progress: Started discussion with the team on some of the items. Will create issues on Sunday, then continue with discussion the remaining items.
* Blockers: None so far.
* Availability: Random time here and there.
* ETA: I am thinking approximately 2 weeks, if not earlier.

**Comment by Aveline-art** [comment]
* Progress: Continued the discuss on what to do with our JS code.
* Blockers: None so far.
* Availability: Will work on this only during meetings.
* ETA: In two weeks.

**Comment by Aveline-art** [comment]
* Progress: Have not made it far in discussion, but will close once all issues are made.
* Blockers: None so far
* Availability: 2 hours
* ETA: By the end of today.

**Comment by Aveline-art** [comment]
* Progress: Made more issues. Only a few remains.
* Blockers: Some issues requires more discussion than anticipated.
* Availability: 2 hours
* ETA: Unsure.

**Comment by Aveline-art** [comment]
Closed because completed!

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art Should this spreadsheet be linked in the WIKI?

**Comment by Aveline-art** [comment]
@ExperimentsInHonesty No, because the spreadsheet is an audit that is now outdated. Unless there is a further need for it, it should be deleted.
