### ISSUE TITLE
Add Slack channel field on each project.md card

### ISSUE THREAD

**Issue by sarL3y** [hackforla/website#201]
Add the project's slack channel link to a field on the project-specific page

**Comment by KianBadie** [comment]
@harishlingam @ExperimentsInHonesty is this field going to be a subfield of the existing "links" field? Or a new field of it's own? Some projects have a Slack link under the "links" field already. 

Also, for retrieving the slack links, would we just have to reach out to the project managers or do the digging on the github repo for the projects?

**Comment by ashlingam** [comment]
@KianBadie My thought would be to leave this as a subfield of the Links field for now until we have completed a rendition of the 'Get Started' drop down. It may make sense to relocate a Slack button into this drop down section. I'll think about this some more and wireframe out for us to discuss.

**Comment by ExperimentsInHonesty** [comment]
We added the slack field to the project card [template](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)

To item is to edit each project card, adding 
```yaml
  - name: Slack
    url: 'https://www.example.com'
```

**Comment by ExperimentsInHonesty** [comment]
This got handled by a few other issues where we put all the changes in.
