### ISSUE TITLE
Create mobile version of Program Areas / Citizen Engagement page

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2016]
### Overview
We need to add a mobile version of the **Program Areas > Citizen Engagement** page in Figma, because there is currently no mobile version (only desktop).

### Action Items
- [x] Create the mobile version of the Program Areas > Citizen Engagement page in Figma. 
    - [x] Use the standard mobile width for our Figma designs (375px wide), and ensure it fits the design system/uses design system components
    - [x] Duplicate all elements from the desktop version of the page on Figma
    - [x] Reference/copy elements from the mobile version of the **Program Areas Homepage** to ensure consistency.

### Resources/Instructions
[Figma File: Program Areas > Citizen Engagement Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=12056%3A95170)
[Figma File: Program Areas Homepage (Mobile)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=7410%3A0)

**Comment by janieche** [comment]
Progress: Not started yet
Blockers: None
Availability: Evenings and weekend
ETA: Next Thursday

**Comment by janieche** [comment]
Progress: Started replicating desktop elements into the mobile design
Blockers: Would be good to understand best practices in noting down the spacing and sizing from "Inspect" step. I'm finding it very tedious so far and wonder if there's a more efficient way
Availability: Evenings and weekend
ETA: Next Thursday (8/19)

**Comment by kristine-eudey** [comment]
@janieche action items for this issue have been updated to reflect answers to your above questions. Please let me know if you have any additional questions.

**Comment by janieche** [comment]
1. Progress: Completed. The mobile version is in the yellow box and I have 4 options for the Sustainability Development Goals cards to choose from.
2. Blockers: None
3. Availability: na
4. ETA: na
5. Pictures: 
<img width="140" alt="Screen Shot 2021-08-20 at 8 14 23 PM" src="https://user-images.githubusercontent.com/12770042/130307413-51430a73-6b7c-4695-af9f-c68afb04d6d5.png">

**Comment by kristine-eudey** [comment]
Hi @janieche, sharing some feedback from the team meeting:

- Please find a way to incorporate the link read more about SDG's that's currently at the top of the desktop version. The wording can change if needed, but mobile users also need to be able to access this information if they'd like to, as they can on desktop.
- Please make each project an accordion to reduce page length. For an example of how this works in other pages, take a look at the mobile version of the events page [here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=12942%3A95065) 
- Bring SDG descriptions back to the mobile versions
  - One suggestion brought up during the meeting is to try removing the gray background of the SDG boxes and try making entire box the SDG color (so it's not so box-on-box). This would definitely need to be tested with all SDG’s though to ensure contrast since some colors are light and would not work with white text atop them. Might also be a way to re-incorporate the SDG descriptions back into the boxes.

Please reach out to me to discuss more if needed, happy to meet up and talk more.

**Comment by janieche** [comment]
1. Progress: Updated [designs](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14612%3A94916) based on feedback in yellow box. 
2. Blockers: n/a
3. Availability: Evenings
4. ETA: 8/29
5. Pictures: 
<img width="195" alt="Screen Shot 2021-08-29 at 9 55 19 AM" src="https://user-images.githubusercontent.com/12770042/131256906-a3ad88e4-d20b-413d-9583-07876057730f.png">

**Comment by janieche** [comment]
1. Progress: Updated designs with [new variations](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15053%3A95269) based on feedback during team meeting in yellow box.
2. Blockers: Need a decision on which design to move forward with
3. Availability: Not available Thurs 9/2 - Tues 9/7
3. ETA: New designs are done, pending decision
4. Pictures:
<img width="229" alt="Screen Shot 2021-09-01 at 2 59 45 PM" src="https://user-images.githubusercontent.com/12770042/131744548-8502bb10-6b74-4e13-b401-4a66f4d1fda9.png">

**Comment by ExperimentsInHonesty** [comment]
@janieche I put a large purple line around the one I prefer.  Please integrate that into the designs so we can release it to development 🥳
![image](https://user-images.githubusercontent.com/37763229/132141235-5b270c89-81a3-46d9-ba16-35109979aa2c.png)

**Comment by janieche** [comment]
Updated mocks can be found in the [yellow rectangle.](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15307%3A98621) 

<img width="173" alt="Screen Shot 2021-09-07 at 5 27 35 PM" src="https://user-images.githubusercontent.com/12770042/132422811-556785ca-e8c5-48e8-a68c-ccf2c0ba218a.png">

**Comment by janieche** [comment]
Notes from 9/19 meeting:
* Format screens, bottom and left-to-right for most recent mocks
* Include desktop version too
* Use pink/red rectangle
* Comment that designs have been signed off by product and is ready for development when changes are made

**Comment by janieche** [comment]
[Designs in the red box](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15307%3A98621) have been signed off by product and is ready for development.

**Comment by adam-abundis** [comment]
#2180 was created for building a desktop/mobile view of the Citizen Engagement page.
