### ISSUE TITLE
Add correct text to Program Areas page

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2020]
### Overview
We need to replace the current text in the [Program Areas page](https://www.hackforla.org/program-areas) with the correct copy, in both Figma and the website version, so that this information can be accurate and consistent with other resources.
### Action Items
Design
- [x] View the accurate copy to add to the Program Areas page in the [What is Hack for LA?](https://docs.google.com/presentation/d/11tuskl2WL37Nz_xzFEa-5cHNFheAsSmm7XwTeC4BXzU/edit#slide=id.gc5eba6fabf_0_546) slide deck (can be accessed via Hackforla.org Website Google Drive > [UX/UI](https://drive.google.com/drive/folders/1Jq24FlOJTEmRD09M5xOgpWuHcKswH5Dk) )
   - [x] Each Program Area section - slide 22 (1. Citizen Engagement), slide 28 (2. Civic Structure), slide 35 (3. Diversity, Equity, and Inclusion), etc.
   - [x] The text from these^ Program Areas slides should replace the text currently in the [Program Areas](https://www.hackforla.org/program-areas) page cards
- [x] Make duplicates of the desktop and mobile versions of the Program Areas page designs in Figma (so that you can still reference the standard spacing in the original versions)
- [x] Edit the text in the duplicates- replace with the copy from the slide deck as mentioned above
   - [x] Replace the text in both desktop and mobile
   - [x] Make sure to adjust all spacing with the new text lengths so that it stays consistent with the standard spacing between everything (text, page cards, bottom of page card etc) as in the original design
   - [x] When finished, move pink rectangle around new desktop and mobile designs to indicate these are final

Product

- [ ] Product to sign off on updates.

Development
- [ ] Replace current text in [Program Areas page](https://www.hackforla.org/program-areas) with the new text in each page card in the [Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4452%3A21046) (in pink rectangle)
### Resources/Instructions
[Program Areas page](https://www.hackforla.org/program-areas)
[What is Hack for LA?](https://docs.google.com/presentation/d/11tuskl2WL37Nz_xzFEa-5cHNFheAsSmm7XwTeC4BXzU/edit#slide=id.gc5eba6fabf_0_546) slide deck
Program Areas page [Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4452%3A21046) (in pink rectangle)

**Comment by janieche** [comment]
1. Progress: Updated text copy. Need to adjust spacing to follow existing standards.
2. Blockers: None
3. Availability: 2 hours this Friday and 4 hours this Sunday
4. ETA: Next Thursday
5. Pictures: 
<img width="515" alt="Screen Shot 2021-08-06 at 10 27 27 AM" src="https://user-images.githubusercontent.com/12770042/128542317-59079cc0-c9bc-48c1-9687-cba958f1ad41.png">

**Comment by janieche** [comment]
Design tasks completed. Final designs are in the pink/red rectangle. The desktop frame is linked [here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=13574%3A95882) and the mobile frame linked [here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=13574%3A97901). 

<img width="264" alt="Screen Shot 2021-08-09 at 12 43 17 PM" src="https://user-images.githubusercontent.com/12770042/128757516-4be37905-7350-4d08-a219-d95d6fe17af5.png">

**Comment by kristine-eudey** [comment]
Thanks @janieche, looks great. The design portion of this issue has been reviewed and approved.

**Comment by ExperimentsInHonesty** [comment]
The items in this issue have already been completed.
