### ISSUE TITLE
Removing all the images that are no longer in the code.

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2023]
### Overview
Currently, we have some images in the assets folder that are not being used anywhere on the site.

### Action Items
- [x] Go through the assets/images folder and check if there are any files that are not findable through searching
- [x] Remove files

### Resources/Instructions
This is the image folder:
https://github.com/hackforla/website/tree/gh-pages/assets/images

**Comment by Abel-Zambrano** [comment]
Progress: Just getting started.
    Blockers: None
    Availability: weekdays after 5pm
    ETA: Monday 8/9 
    Pictures: n/a
