### ISSUE TITLE
Update comment on util.js file

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#2026]
### Overview
We need clear comments on code that is opaque. Update the comment on this util.js file so that it is clear what it does. https://github.com/hackforla/website/blob/89e49079d7ab06204affd21cc20bcea4ed03c516/assets/js/utils.js#L2

### Action Items
- [ ] change the words on line 2 of /assets/js/utils.js as shown below
```diff
- * Event Listener `locationchange` that gets triggered on
+ * Creates an event listener called 'locationchange' that gets triggered on
+ * see the following link for details: https://dirask.com/posts/JavaScript-on-location-changed-event-on-url-changed-event-DKeyZj 
```
- [ ] run the site locally to make sure nothing is broken
- [ ] push changes and make a pr
- [ ] post in the slack channel #hfla-site asking for someone to review it
- [ ] give someone a high five

### Resources/Instructions
- [our holy CONTRIBUTING.md doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)

**Comment by Sihemgourou** [comment]
Hello @Aveline-art, who is assigned to this issue ? should it belong in the prioritized backlog

**Comment by IpshitaSingh** [comment]
1. Progress: Changed the words in line 2 as mentioned in the issue. Not sure if there's anything more to be done.
2. Blockers: Faced (and resolved) some issues while setting up Docker 
3. Availability: 2 hours
4. ETA: I think its done
5. Pictures: N/A
