### ISSUE TITLE
disappear the annoying error message in wins-feature-1 docker

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#2029]
### Overview
This does not actually break anything.. it is just an annoying error. 

<details>
    <summary>See here</summary>

![Screen Shot 2021-08-01 at 11 28 54 AM](https://user-images.githubusercontent.com/53061723/127781545-6e03499d-3854-4fbd-a386-e794afeaf99d.png)

</details>

### Action Items
- [x] figure out how to make the error go away
- [x] remove the error

### Resources/Instructions
- the actual text of the error
    - `808857cc918e_hfla_site  | [2021-08-01 13:27:47] ERROR '/assets/js/inert.min.js.map' not found.`

Info:
- a `.map` file is just for viewing, not for functionality. 
- the inert.js file is helping with accessibility. It helps with making content focusable or not focusable when someone is using tab to navigate through the page

**Comment by jbubar** [comment]
IMPORTANT!!
This issue is working off of a feature branch!
Please follow this wiki before creating a new branch!
[how to work off a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)

**Comment by macho-catt** [comment]
The fix is to add the accompanying .map file that the polyfill is supposed to come with. :D

Source: https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/
