### ISSUE TITLE
Zoom links on wiki are out of date

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2034]
### Overview
We need the wiki to have up to date links so that people who are trying to join the meetings don't miss meeting

### Action Items
- [x] UI/UX 
  - [x] Provide information for your meeting times in a comment below
- [x] Front/Back
   - [x] check Tuesday time and link, adding details below about changes
   - [x] provide info for Thursday backend meeting (in comment below)
- [x] Product
  - [x] Update Time and link (in comments below)

### Resources/Instructions
https://github.com/hackforla/website/wiki/Joining-the-HackforLA.org-Website-Team

**Comment by ExperimentsInHonesty** [comment]
**UI UX meetings**
Thursday 5pm PST https://meet.google.com/bsf-njfy-dbb
UX/PM meeting Tuesdays at 12:15 PDT https://us02web.zoom.us/j/4451450308?pwd=U0JobzZqN0xGSXBUUkRsNlB5YzJiQT09
Research meetings happening as needed (invited via calendar invite)

**Comment by sobe-an** [comment]
**Frontend**
Tuesday - 7 pm PST https://us02web.zoom.us/j/85991861240?pwd=bjJPSVpsY21JY1VUbGx0UVZySGRtdz09

**Backend**
Thursday - 7:30 pm PST https://us02web.zoom.us/j/85991861240?pwd=bjJPSVpsY21JY1VUbGx0UVZySGRtdz09

**Comment by sobe-an** [comment]
**Product** 
Wednesday - 12 pm PST https://us02web.zoom.us/j/4451450308?pwd=U0JobzZqN0xGSXBUUkRsNlB5YzJiQT09

**Comment by sobe-an** [comment]
I've updated the meeting links and time.
