### ISSUE TITLE
Update ‘Trophy’ Icon and Credit info

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2043]
### Overview
We need to replace the Trophy icon in the Wins section of the [About page](https://www.hackforla.org/about/#accomplishments) (under Accomplishments) because the credit link for it isn’t a direct link, and the original icon link can’t be tracked down. 
### Action Items
- [x] Replace the Trophy icon in the Wins section of the [About page](https://www.hackforla.org/about/#accomplishments) (under Accomplishments) with the new one that has now replaced it in the [About page Figma file ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692)(in pink rectangle- scroll down to Wins section to locate and export new icon. Or just go to the bottom of the credit section in green rectangle, where the new icon and its info has replaced the old one)
- [x] Replace the old icon credit info in the [Credits page](https://www.hackforla.org/credits/) with the new icon’s credit info
  - [x] New icon credit link: https://thenounproject.com/term/trophy/3115497/ 
  - [x] New icon Artist: **iconpixel, ID** 
### Resources/Instructions
[About page](https://www.hackforla.org/about/#accomplishments) 
[About page Figma file ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692)
[Credits page](https://www.hackforla.org/credits/)
[Credit.yml file template](https://github.com/hackforla/website/wiki/credit.yml-file-template)
New Trophy icon:
<img width="611" alt="128059882-89b873a2-f2e6-45ae-abb4-f5c7018a2964" src="https://user-images.githubusercontent.com/16949503/128067493-36d41b7c-4a2c-41bc-bd4b-68a1e4d78075.png">
<img width="338" alt="128059899-ad7e4efb-98fd-40a8-be11-e3ea1a05c49c" src="https://user-images.githubusercontent.com/16949503/128067508-e92c8b25-363c-439d-8941-1fd5196d1b3c.png">

**Comment by Zhu-Joseph** [comment]
• Progress: Assigned to myself, but will look into the issue for further details soon.
• Blockers: None so far.
• Availability: Random time here and there.
• ETA: I am thinking approximately 1 week, if not earlier.
