### ISSUE TITLE
Update ‘Delegate’ image credit image name, link, and artist

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2045]
### Overview
We need to correct the [image credit Name, Name Link, and Artist](https://www.hackforla.org/credits/) for the ‘Delegate’ image to the accurate information and specific link (it currently leads to a generic Noun Project link).
### Action Items
- [x] Replace the generic Noun Project link for the image titled “Delegate” in the [credits page](https://www.hackforla.org/credits/) with [this specific link](https://thenounproject.com/search/?q=people+network&i=2228897) instead in the ‘Name’ category
- [x] In the ‘Name’ category, also change the name from Delegate to the correct one: “People Network”
- [x] In the ‘Artist’ category, change the artist to the correct one: “Sérgio Filipe Cardoso Pires, PT”
### Resources/Instructions
[Credit.yml template wiki](https://github.com/hackforla/website/wiki/credit.yml-file-template)
[Credits page](https://www.hackforla.org/credits/)
[‘Delegate (People Network)’ correct Image link](https://thenounproject.com/search/?q=people+network&i=2228897)

**Comment by IpshitaSingh** [comment]
Progress: Made all changes, have to take and attach 'before' and 'after' pictures
Blockers: Faced a little difficulty locating the file to be changed; Docker not correctly refreshing the page 
Availability: 2 hours
ETA: 1-2 days

**Comment by IpshitaSingh** [comment]
Progress: Done
Blockers: Faced a little difficulty locating the file to be changed; Docker not correctly refreshing the page
Availability: 2 hours
ETA: N/A
Pictures:
Before- 
<img src = "https://user-images.githubusercontent.com/60215488/132760480-17393c33-8b65-42b6-a677-6fb418273c10.jpg" width="650" height="300" > 
After-
<img src = "https://user-images.githubusercontent.com/60215488/132760336-fcfdacb9-b7bb-4ef8-8dd2-ab5062c72751.jpg" width="650" height="300">

**Comment by adam-abundis** [comment]
@IpshitaSingh This seems to be a weird caching bug within the Docker build. Basically, any .yml or .json file won't reflect the update in the Docker build. Our workaround is at the bottom of this section in the contributing guide https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#Prepare-your-changes-to-push-to-your-repository . I am going to edit to emphasize the steps needed to be completed.

### Steps to get updated data files to update within Docker

If you do not see the changes you applied when you run docker-compose up, do the following:
     1. Stop running your Docker application (if still running).
     2. Delete the `_site` directory in the root folder (`website`)
     3. Delete the `.jekyll-metadata` file in the root folder (`website`)
     4.  restart docker (run `docker-compose up` in the terminal)

This will force docker to rebuild the whole site and your updates will be reflected.

**Comment by ExperimentsInHonesty** [comment]
@IpshitaSingh we have not heard from you for two weeks.  It looks like you made the change from the screen shots and then had a little issue with your PR but you have not made a new PR since then.  Are you going to be able to make a new one?  Please let us know your availability and any challenges you are having.

**Comment by IpshitaSingh** [comment]
@ExperimentsInHonesty I'd like to apologise for the delay; there's an issue with my local repo and since I've been completely swamped with work, I haven't got around to fixing it and making another PR. 
I can make one by next week but if this needs to be urgently done, it'd be best if I could un-assign myself.

**Comment by ExperimentsInHonesty** [comment]
@IpshitaSingh we can wait.  Thank you for the update.  Please keep us updated weekly.

**Comment by IpshitaSingh** [comment]
@ExperimentsInHonesty Noted! Thanks for understanding

**Comment by IpshitaSingh** [comment]
Progress: Done
Blockers: Issue with local repo(now resolved)
Availability: 2 hours
ETA: N/A
