### ISSUE TITLE
Remove Hacker Fund logo (and text) from page bottom

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#205]
### Overview
Remove Hacker Fund logo from page bottom

### Action Items
Remove Hacker Fund logo from page bottom

### Resources/Instructions

**Comment by GeorgeSu** [comment]
@ExperimentsInHonesty Hey Bonnie, I noticed the website still says that Hack for LA is a project group of Hacker Fund. Does this need to be removed as well? If so, can you let me know what you want to replace the text with, thanks!

<img width="923" alt="Screen Shot 2019-12-03 at 8 06 20 PM" src="https://user-images.githubusercontent.com/7980047/70111886-8418f900-1608-11ea-862c-0935931503df.png">

**Comment by ExperimentsInHonesty** [comment]
@GeorgeSu Thank you for surfacing this.  Let's replace the text

Current text: Hack for LA is a project group of Hacker Fund and the official Los Angeles Chapter of Code for America.

Replacement text:  Hack for LA is a project and the official Los Angeles brigade of Code for America.

**Comment by ExperimentsInHonesty** [comment]
This issue is not completed yet.  The text is still there.
