### ISSUE TITLE
Move UX survey to hackforla.org/survey/[X]

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#206]
### Overview
Move UX survey to hackforla.org/survey/[X]

### Action Items
Move UX survey to hackforla.org/survey/[X]. 

The [X] will represent a unique identifier specific to the persona administered. This will allow us to collect persona specific data. 

We will use a separate spreadsheet to map identifiers to personas.

### Resources/Instructions

**Comment by StephenVNelson** [comment]
@harishlingam  Is this in progress? If so should we move it to "in progress"? If it's not in progress may I work on it?

**Comment by ashlingam** [comment]
@StephenVNelson I've moved to in progress. Happy to have your help, though waiting to hear back from @newdra24 to sort out access to the data, which he has. The idea is to have 4-5 domain subfolders, specific to each persona that completes the survey. This way the data is segregated, but the same form is used.

**Comment by ExperimentsInHonesty** [comment]
@harishlingam why is this in the review column?

**Comment by ashlingam** [comment]
@ExperimentsInHonesty Probably should have pinged you instead. Was intended as a reminder to review/approve the pull request so the new survey URLs will be operational on the live site.

**Comment by ExperimentsInHonesty** [comment]
duplicate to pr #339 and issue #316
