### ISSUE TITLE
Refactor Javascript: Delete unused code from survey guide page

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2063]
### Overview
As a member of the website development team, Javascript code is much more maintainable and reusable if they exist in a separate folder rather than embedded with html.

### Action Items

- [x] Delete the unused Javascript code from [this page](https://github.com/hackforla/website/blob/gh-pages/_guide-pages/survey-reporting-dashboard-guide.html).
- [x] Make sure the website still runs, and that the page looks the same as before the above change.

### Resources/Instructions
[survey-reporting-dashboard-guide.html](https://github.com/hackforla/website/blob/gh-pages/_guide-pages/survey-reporting-dashboard-guide.html)
[Building a Survey Reporting Dashboard](https://www.hackforla.org/guide-pages/survey-reporting-dashboard-guide)
#### Architecture Notes

The idea behind the refactor is to get all of our website's JS code into an organized, consolidated state. Currently, we want our JS files to exist in our [assets/js ](https://github.com/hackforla/website/tree/gh-pages/assets/js)directory with these specifications:

- In the main js directory, the js files should ideally have names corresponding to a related .html page (for example, updates.js should connect to updates.html).
- In the elements sub-directory, the js fjiles should correspond to code needed for our [design system elements ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)to function.
- In the utility sub-directory, the js files represent reusable code that can be used in multiple files. If any js code is reused, they belong in utility, and called in a separate file in the main directory.

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by Zhu-Joseph** [comment]
Progress: Started reading through code to identify unneeded JavaScript code.
Blockers: None so far.
Availability: Random time here and there.
ETA: By the end of the week.

**Comment by Sihemgourou** [comment]
hey @Zhu-Joseph, I see that you are assigned to 2 issues. The process is that you only take 1 issue, and make sure your PR to be merged before taking another issue.

**Comment by Zhu-Joseph** [comment]
Hi @Sihemgourou, ok sorry about that! I'll just hold off for now until this issue gets merged.

**Comment by sobe-an** [comment]
@Aveline-art Please could you let us know why this issue was closed.
