### ISSUE TITLE
Add GreenEarthOS project card

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2064]
### Overview
We need to add GreenEarthOS to the website, so that our list of projects is complete.

### Action Items
See this issue for details on project
https://github.com/hackforla/GreenEarthOS/issues/3#issuecomment-893120885

See this issue comment for logo and hero
https://github.com/hackforla/GreenEarthOS/issues/3#issuecomment-884618633
All image text for the logo : GreenEarthOS logo with text in green and a globe as a "O"

For UAT reach out to Puneet on slack in the #GreenEarthOS-climate channel

**Comment by PLoiya** [comment]
We have added the overview link. Here is the link for the same - https://github.com/hackforla/product-management/blob/master/project-one-sheets/GreenEarthOS%20one%20sheet.pdf

**Comment by PLoiya** [comment]
We have a new team member. here is the info - https://github.com/hackforla/GreenEarthOS/issues/3#issuecomment-897300443

**Comment by grhhhh** [comment]
Progress: Project completed and pending review
Blockers: NA
Availability: I will be available during the coming week should any corrections or review be necessary
ETA: Pending Review
Pictures: 
<img width="50%" alt="Screen Shot 2021-08-14 at 4 09 01 PM" src="https://user-images.githubusercontent.com/79604590/129463075-b06475d6-545e-47a3-b8fb-a682440fa0d9.png">
<img width="75%" alt="Screen Shot 2021-08-14 at 4 10 31 PM" src="https://user-images.githubusercontent.com/79604590/129463078-66f79166-dba5-4b1a-8f69-23f55a19edcb.png">

**Comment by ExperimentsInHonesty** [comment]
Hi @grhhhh Garret!  We are going to make a new issue for some post pr cleanup. And good for you to note for next time.  Items on the cleanup are
The overview link does not resolve and the username of one of the people (me) was not given to you properly, and since its not a real github username you can tell because it shows a specific icon.  See here for details: https://github.com/hackforla/GreenEarthOS/issues/3#issuecomment-903319935

**Comment by grhhhh** [comment]
@ExperimentsInHonesty Thanks for your feedback and for including me in the conversation. I'd be happy to take on making those changes if you like.

**Comment by macho-catt** [comment]
@ExperimentsInHonesty  So for the overview link, it's actually a problem with how the href tag was written and not necessarily the fact that there are spaces in the name of the file. Currently the href tag is written like this:
```
<a href=${ item.url }>
```
but it should be like this:
```
a href="${ item.url }"
```
Where enclosing the value of the href tag ensures that everything in the name is taken into account, including the spaces. Without it, the name cuts off when it sees the first space character.

Devs can make an issue that resolves this issue not just for this project card, but for future links in other project cards.
