### ISSUE TITLE
GitHub Actions: Create issue at a timed interval to check for updates to GHA version

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2065]
### Overview

As a developer who maintains the repository, we need to periodically update our dependencies so that our GitHub actions do not unexpectedly break.

### Psudo-code
- [x] Discuss with the team on how often the interval should be. (Until this discussion happens, you can use a workflow_dispatch trigger to test your code for now).
- [ ] Trigger: when the update interval arrives
  - [x] Post a new issue
    - [ ] The issue is a well formed issue containing:
      - [x] Overview
      - [x] Action items, perhaps something like "Check all GitHub action dependencies for updates" and "create further issues to update the GitHub action as needed"
      - [x] Resources/Instructions
      - [ ] Other notes as needed
    - [x] The issue needs to be well labeled.
    - [x] The issue needs to be moved to the correct column.
    - [x] The issue needs to exist on an external md file so that it can be easily edited by the team as needed.

### Checks

- [ ] None, but the GHA should be run once as a trial, to create an official issue. This issue can then be taken up by a member of the team, and this member can give feedback on the issue's content.

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)

Note that you might want to do something outside the scope of the above psudo-code. If so, be sure to leave comments in your PR or this issue that justifies your reasoning. If you feel you need guidance, be sure to reach out! We cannot foresee whether this issue is solvable, or what hard decisions have to be made, but we would love to hear and help you!

#### Additional resources:
[About actions](https://docs.github.com/en/actions/creating-actions/about-actions)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)
[GitHub GraphQL](https://docs.github.com/en/graphql)

**Comment by BeckettOBrien** [comment]
Availability: 9 AM to 5 PM PST weekdays
ETA: EOD 7/20/22

**Comment by BeckettOBrien** [comment]
I'm working on writing a section of the issue that shows how to check an action's dependencies for updates but I need to clarify what you mean by "dependency" for actions. Does it include npm dependencies for actions that run scripts or is it just for external actions like `actions/checkout`?

**Comment by t-will-gillis** [comment]
The PR [3414](https://github.com/hackforla/website/pull/3414) associated with this issue was closed 10/4/22 with a reference that the issue was no longer relevant as explained in issue [3598](https://github.com/hackforla/website/issues/3598). 

Since there is a linked PR this issue is not being updated with the `2 weeks inactive` label. Will create an ER...
