### ISSUE TITLE
Refactor Javascript: Move donut code to external folder

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2068]
### Overview
As a member of the website development team, Javascript code is much more maintainable and reusable if they exist in a separate folder rather than embedded with html.

### Action Items

- [x] Read the notes below to understand the architecture of our JS files.
- [x] Visit [this file](https://github.com/hackforla/website/blob/gh-pages/_guide-pages/2FA.html)
  - [x] Look for the code that is located on the "member analytics" section (it is currently set, with inline styling, as display: none).
  - [x] Move the code to an appropriate folder, with an appropriate name. 
  - [x] Remove the inline styling, and comment out the div instead.
  - [x] Add a brief comment that explains why the div is commented out. Include this issue number

### Resources/Instructions
[2FA.html](https://github.com/hackforla/website/blob/gh-pages/_guide-pages/2FA.html)
[2FA guide](https://www.hackforla.org/guide-pages/2FA)

#### Architecture Notes

The idea behind the refactor is to get all of our website's JS code into an organized, consolidated state. Currently, we want our JS files to exist in our [assets/js ](https://github.com/hackforla/website/tree/gh-pages/assets/js)directory with these specifications:

- In the main js directory, the js files should ideally have names corresponding to a related .html page (for example, updates.js should connect to updates.html).
- In the elements sub-directory, the js fjiles should correspond to code needed for our [design system elements ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)to function.
- In the utility sub-directory, the js files represent reusable code that can be used in multiple files. If any js code is reused, they belong in utility, and called in a separate file in the main directory.

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by anonymousanemone** [comment]
1. Found the code that needs to be moved (I think), currently researching exactly what to do with the code using previous issues.
2. Lack of technical knowledge
3. 5 hours
4. By next Sunday
5. N/A

**Comment by anonymousanemone** [comment]
1. Struggling to figure out what to do (what code to move, specifically. Is it the entire div, or is it just the script? And does the instruction mean to comment out the entire div?)
2. Issues
3. 5 hours
4. After resolving blocker
