### ISSUE TITLE
Google Drive Google Tables Discussion Initial

### ISSUE THREAD

**Issue by averdin2** [hackforla/website#2071]
### Overview
In order to automate Hack for LA’s volunteer onboarding processes, we are using Google Tables and Google App Scripts to automate various onboarding processes. We need to define constraints for each of Hack for LA’s platforms to better understand how we can implement our automation scripts.

### What HfLA Platform is this issue Discussing?
Google Drive
### Action items for Discussion
- [ ] What is Hack for LA currently doing with this platform? Is automation needed for this platform?
- [ ] What are automations supposed to do for this platform? What are the minimum functional requirements for this platform?
- [ ] What is the technical feasibility of implementing automations for this platform?
- [ ] Will any accounts be needed for automation? Bot accounts, email accounts, accounts for work or documents to be stored, etc?
  - [ ] Are there any accounts that exist for this platform that can be reused instead of creating new ones?
  - [ ] Who is going to need access to these accounts? What permissions do these accounts need to have?
  - [ ] Where are these accounts located (vaults, spreadsheets, etc)?
- [ ] What external APIs may be needed for implementation?
- [ ] How is information related to this platform going to be represented in Google Tables? (Do we need api keys as a column, do we need access tokens, do we need folder ids, etc?)

### Resources
REPLACE THIS TEXT - Put any resources that can help us understand how to implement automations with this platform here.

**Comment by averdin2** [comment]
### What is Hack for LA currently doing with this platform? Is automation needed for this platform?
- We use it for storing rosters, files, app scripts. 


### What are automations supposed to do for this platform? What are the minimum functional requirements for this platform?
- The automation that is needed is adding new members to shared drives.
- Automation to remove inactive users after a period of time.
- Updating rosters?

### How to have Google Tables update Google Sheets?
- We can use app scripts to communicate between roster sheets and Google Tables, and vice versa.

**Comment by adam-abundis** [comment]
@averdin2, @chelseybeck, @jpandh

@ExperimentsInHonesty needs an update on the progress for this issue. Please post progress here.

Thank you.

**Comment by averdin2** [comment]
We decided that the MVP for the project is only going to be focused on implementing automations for adding users to Google Drive Folders and GitHub teams. We no longer have a need for this separate discussion issue. All discussions will be in issue #1833
