### ISSUE TITLE
Put a program area filter on project page

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#2076]
### Overview
As a potential stakeholder, having a filter for program areas is useful to understanding the scope of a project.

### Action Items

- [x] Create a new filter called "program areas" for the new projects page
- [x] The filter must contain the items listed on our program areas page.
- [x] The filter must function as any other filter on the page.
- [x] It might be preferred that the filter comes from some shared data list between the program areas page and this filter, but consider whether this is possible and whether the solution follows best practices.
- [x] Be sure to follow our best practices when working with js code (outlined below).

### Resources/Instructions
[program-areas page](https://www.hackforla.org/program-areas.html)
[new projects page](https://www.hackforla.org/projects/)

#### Architecture Notes

The idea behind the refactor is to get all of our website's JS code into an organized, consolidated state. Currently, we want our JS files to exist in our [assets/js ](https://github.com/hackforla/website/tree/gh-pages/assets/js)directory with these specifications:

- In the main js directory, the js files should ideally have names corresponding to a related .html page (for example, updates.js should connect to updates.html).
- In the elements sub-directory, the js fjiles should correspond to code needed for our [design system elements ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)to function.
- In the utility sub-directory, the js files represent reusable code that can be used in multiple files. If any js code is reused, they belong in utility, and called in a separate file in the main directory.

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by Aveline-art** [comment]
@Abel-Zambrano Requirements for this has changed, as noted from this: https://github.com/hackforla/website/projects/7#card-66864847 (reproduced below)

> Development: Make sure there's an issue for removing location from project page and home page and adding program area
new order: program areas, technology, status

What is your progress so far on the issue? Can this be incorporated into your issue? If not, can you create a follow-up issue from this card? If you can, once you are done, can you delete the card?

**Comment by Abel-Zambrano** [comment]
@Aveline-art I added the "program areas" filter and am currently working on filter checkbox functionality. I can definitely add this to my issue and delete the card when done.

**Comment by Abel-Zambrano** [comment]
Progress: built the filter, just need to work on the data that's passed in.
Blockers: matching keys from 2 objects are mismatched.
Availability: 5hrs
ETA: Monday

**Comment by Abel-Zambrano** [comment]
Progress: Finished working on the displayed filter title. I discovered a new issue where there's something being populated in the filter list with zero value.
Blockers: n/a
Availability: 5hrs
ETA: 9/13

**Comment by Abel-Zambrano** [comment]
Progress: Need to separate JS code to assets/js
Blockers: Liquid syntax errors
Availability: 5hrs
ETA: 9/24

**Comment by Aveline-art** [comment]
@Abel-Zambrano *psst*

<details>
<summary>Hint</summary>
<br>
https://stackoverflow.com/questions/58517425/how-do-i-include-liquid-global-variables-defined-using-jekyll-in-a-javascript-fi
<br>
</details>

**Comment by Abel-Zambrano** [comment]
@Aveline-art Thank you!!
