### ISSUE TITLE
Mobile Responsiveness on About page: body cuts off below mobile view

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2077]
### Overview
This is a follow-up issue as mentioned in PR #1928.
Currently, below a certain breakpoint (below 375px) the sections in the body of the About page gets cut off instead of adjusting itself via a Media Query. It should not cut off and just adjust itself.

Steps to reproduce the issue - 
1. Go to the about page: https://www.hackforla.org/about
2. Open the dev tools and go to the Responsive Design Mode
3. Change the screen width to about 375px or below, and the body will start getting cut off

<details>
<summary>Sample 1</summary>

![cut off below a certain bp](https://user-images.githubusercontent.com/48004150/128810549-15a2f24d-d22a-4aa1-807c-fb6a3906902f.png)

</details>

<details>
<summary>Sample 2</summary>

![Screenshot from 2021-08-09 21-51-23](https://user-images.githubusercontent.com/48004150/128810600-a9f6e03c-af10-4956-82f0-1fc2f4762662.png)

</details>

<details>
<summary>Sample 3</summary>

![Screenshot from 2021-08-09 21-52-18](https://user-images.githubusercontent.com/48004150/128810618-adaebf69-1669-4beb-a5d3-5a8a8392cf6e.png)

</details>

<details>
<summary>Sample 4</summary>

![Screenshot from 2021-08-09 21-52-34](https://user-images.githubusercontent.com/48004150/128811914-c95fd5c7-19c6-4339-bc8c-1f3e6a3d4070.png)

</details>

### Action Items
Development: 
- [ ] Figure out why this is happening (most likely, media queries / flex is not set to the parent divs after a certain breakpoint)
- [ ] Identify which sections of the page are not reacting properly, and fix them
- [ ] Ensure that implementing the fix does not break anything in the page

### Resources/Instructions
Where the issue was initially found: #1928 
[CSS Tricks Flex Guide](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)
[Flexbox Guide by Interneting is hard](https://internetingishard.netlify.app/html-and-css/flexbox/index.html)
[Mobile Queries](https://css-tricks.com/snippets/css/media-queries-for-standard-devices/)
[Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

**Comment by JackRichman** [comment]
@ExperimentsInHonesty could not replicate

**Comment by macho-catt** [comment]
Looks like the issue has been resolved, we will close.
