### ISSUE TITLE
Add all Wins page badge icon credits to Credits page

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2078]
### Overview
We need to add all of the Wins page badge icons’ credit information to the [Credits page](https://www.hackforla.org/credits/) to follow image use compliance standards

### Action Items
- [x] Locate all icon credit information in [Wins page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=9246%3A80729) (in green rectangle on bottom right)
- [x] Add all of the icon credit information to the [Credits page](https://www.hackforla.org/credits/)
### Resources/Instructions
Icon credit information in [Wins page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=9246%3A80729) (in green rectangle on bottom right)
[Credit.yml template wiki](https://github.com/hackforla/website/wiki/credit.yml-file-template)
[Wins page](https://www.hackforla.org/wins/)

**Comment by aalieu** [comment]
1. Just starting
2. None yet
3. Flexible
4. By next Tuesday's meeting

**Comment by ExperimentsInHonesty** [comment]
@adam will make an issue to have all the svgs on the credits page for these badges appear larger.  Will coordinate with @kristine-eudey to determine if images on credits page are supposed to be similar in size to each other or related to the size they appear on the site.  My preference is that they would be mostly the same size as each other.

**Comment by adam-abundis** [comment]
#2263 was created and merged. No need to create a new issue.
