### ISSUE TITLE
Add new heading class to design system’s heading typography in the code base

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2080]
### Overview
We need to add a new heading class (“.title7”) and adjust a previous heading class (“title6") to the standardized design system headings in the code base, since an 18px heading has been added to the design system (18px heading is necessary and exists in several current pages, including the project cards).

Refer to this image from the [figma ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)for typography rules
<details>
<summary>Screenshot</summary>

![typo](https://user-images.githubusercontent.com/48004150/130729783-4449020e-37bd-4d4b-9738-18ca7f1e4ab9.PNG)

</details>

### Action Items
- [x] Refer to issue #1743 and PR #1814 to learn about the background of the standard heading classes and how to add a new one
- [x] Change the “.title6” class font size to 18px (in rem)
    - [x] Edit the "$font-size-title6" variable in this [file ](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_typography.scss) for desktop, tablet, and mobile so it conforms to the new typography rules
    - [x] Edit the “.title6” classes in this [file ](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_typography.scss)for desktop, tablet, and mobile so it conforms to the new typography rules
- [x] Add a “.title7" class that is font size 16px (1rem) to accommodate the change above
    - [x] Add a "$font-size-title7" variable in this [file ](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_typography.scss) for desktop, tablet, and mobile so it conforms to the new typography rules
    - [x] Add “.title7” classes in this [file ](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_typography.scss)for desktop, tablet, and mobile so it conforms to the new typography rules

### Resources/Instructions
issue #1743 
PR #1814 
[SCSS Variables Location for Typography](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_typography.scss)
[SCSS Classes Location for Typography](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_typography.scss)
[Figma for Typography Rules](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)

**Comment by sheltoG** [comment]
@hackforla/website-merge This issue needs more specificity for the medium level. Please edit to provide the names of the file the person would need to make changes to and any other edits that are necessary.

**Comment by macho-catt** [comment]
I edited this post to add the links to the files that need to be changed as well as the variables concerned in the topic. I also included the link to the figma, plus the screenshot of the typography rules.
Thanks.

**Comment by mehmehmehlol** [comment]
1. Progress: Just created a pull request for this issue.
