### ISSUE TITLE
Apply design system heading classes to Events page

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2081]
### Overview
We need to apply the new [standardized heading classes](https://github.com/hackforla/website/issues/1743) to the Events page headings (for accessibility/to remove the styling reliance on h tags), so that that the page can now follow the design system plan and be more accessible.
### Action Items
- [x] Apply the heading classes noted in the [Events page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8552%3A0) (in pink rectangle) to the [Events page](https://www.hackforla.org/events/)
- [x] Make sure the headings still look good and correct (same as the Figma) both in mobile and desktop, and that nothing gets messed up due to these changes
- [x] Make sure to adjust the heading h tags now so that they reflect the correct hierarchy of the page for screen readers (since the styling no longer relies on the h tags)
### Resources/Instructions
[Events page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8552%3A0) (in pink rectangle)
[Events page](https://www.hackforla.org/events/)
From Figma:
![Screen Shot 2021-08-08 at 1 03 15 AM](https://user-images.githubusercontent.com/67400366/128625425-166f5bd4-3722-406c-bc6f-f69ce663bdb5.png)

**Comment by lindseyindev** [comment]
Availability: 5 hours
ETA: midnight 12/29
