### ISSUE TITLE
Apply design system heading classes to Wins page 

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2082]
### Overview
We need to apply the new [standardized heading classes](https://github.com/hackforla/website/issues/1743) to the Wins page headings (for accessibility/to remove the styling reliance on h tags), so that that the page can now follow the design system plan and be more accessible.
### Action Items
- [x] Apply the heading class “.title1” to the [Wins page](https://www.hackforla.org/wins/) header’s heading text (“Let’s celebrate together!“)
- [x] Make sure the heading still looks the same as it did before in mobile and desktop, and that nothing gets messed up due to these changes
### Resources/Instructions
[Wins page](https://www.hackforla.org/wins/)
[Guide to working on a feature branch (wins-feature-1)](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
![Screen Shot 2021-08-08 at 1 11 22 AM](https://user-images.githubusercontent.com/67400366/128625605-0a1dac5c-cc61-4c03-ba60-13f8a679e600.png)

**Comment by adam-abundis** [comment]
@adrian-zaragoza please close #2150 and create a new branch that splits from `wins-feature-1` instead of `gh-pages`. I added [Guide to working on a feature branch (wins-feature-1)](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch) in the resources section of the issue. Then push changes to the newly made branch and create a new pull request.

**Comment by adrian-zaragoza** [comment]
Hi @abuna1985 , I created the new PR [2189](https://github.com/hackforla/website/pull/2189) to merge my changes with the wins-feature-1 branch. Let me know if I need to do anything else.

**Comment by adam-abundis** [comment]
Thank you @adrian-zaragoza. My apologies for not catching this earlier.

**Comment by Aveline-art** [comment]
@adrian-zaragoza please close this if this is done. I think this is happening because a linked PR was closed, rather than merged. When this happens, the linked issue does not close, but it does go into UAT. When closing (rather than merging) reviews, please remove the linked issue in the PR.

**Comment by adrian-zaragoza** [comment]
Closing this issue because its complete.
