### ISSUE TITLE
Apply design system heading classes to Getting Started page 

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2083]
### Overview
We need to apply the new [standardized heading classes](https://github.com/hackforla/website/issues/1743) to the Getting Started page headings (for accessibility/to remove the styling reliance on h tags), so that that the page can now follow the design system plan and be more accessible.
### Action Items
- [x] Apply the heading classes noted in the screenshots below to the [Getting Started page](https://www.hackforla.org/getting-started)
  - [x] “.Title1” class for the header’s heading text (“Getting Started”)
  - [x] “.Title4” class to the “Frequently Asked Questions” heading in the bottom of the page
- [x] Make sure the headings with the new classes look good both in mobile and desktop, and that nothing gets messed up due to these changes
- [x] If needed, adjust the heading h tags (h3 etc.) so that they reflect the correct hierarchy of the page for screen readers (since the styling no longer relies on the h tags)
### Resources/Instructions
[Getting Started page](https://www.hackforla.org/getting-started)
![Screen Shot 2021-08-07 at 3 14 18 PM](https://user-images.githubusercontent.com/67400366/128625738-19e44b8c-fb1a-4eb6-bbee-c67622fa425c.png)
![Screen Shot 2021-08-07 at 3 16 33 PM](https://user-images.githubusercontent.com/67400366/128625741-d4cab507-925e-47a2-af2e-c6a86a63bca5.png)

**Comment by 1anya1** [comment]
Availability for this week: Tue-Fri total 9 hrs.
My estimated ETA for completing this issue: 02/25/2022

**Comment by 1anya1** [comment]
@kristine-eudey Im a bit confused am I making the changes to Getting Started Page or Events page? It looks like the link is wrong.

**Comment by JessicaLucindaCheng** [comment]
@1anya1 Sorry for the confusion. It should be the Getting Started page. I have edited the issue to reflect that.

**Comment by 1anya1** [comment]
@JessicaLucindaCheng Thank you for clarifying!
