### ISSUE TITLE
Apply design system heading classes to Donate page 

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2084]
### Overview
We need to apply the new [standardized heading classes](https://github.com/hackforla/website/issues/1743) to the Donate page headings (for accessibility/to remove the styling reliance on h tags), so that that the page can now follow the design system plan and be more accessible.
### Action Items
- [x] Apply the heading classes noted in the [Donate page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11561%3A91657) (in pink rectangle) to the [Donate page](https://www.hackforla.org/donate)
- [x] Make sure the headings still look good and correct (same as the Figma) both in mobile and desktop, and that nothing gets messed up due to these changes
- [x] Make sure to adjust the heading h tags if needed so that they reflect the correct hierarchy of the page for screen readers (since the styling no longer relies on the h tags)
### Resources/Instructions
[Donate page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11561%3A91657) (in pink rectangle)
[Donate page](https://www.hackforla.org/donate)
From Figma:
![Screen Shot 2021-08-08 at 1 26 50 AM](https://user-images.githubusercontent.com/67400366/128626096-3db050b3-3884-4831-894c-cdbe5cc73a29.png)

**Comment by pattshreds** [comment]
**Availability:** 1.23.2022, I will be available for 2-4 hours. Will be busy from ~9:30am - ~5:00pm.
**ETA:** 1.23.2022 ~8pm latest.

**Comment by pattshreds** [comment]
**Progress:** Classes assigned, just need to define in SASS.
**Blockers:** Wasn't sure if I had to define the classes in the SASS file, talked to Saumil and learned I do so I'm doing that this morning.
Update: Having trouble repositioning the first h1 element to left align with the paragraph beneath it. Changing it to 
text-align: left; doesn't move it so I need to find why it won't move left.

**Availability:** 1.25.2022 2 hours in the evening.
**ETA:** 1.26.2022, ~8am. 

**Edit 1.24.2022 9:38pm:**
Changed ETA and added new blocker.

**Comment by pattshreds** [comment]
**Progress:** Moved the first h1 element with a negative margin.
**Blockers:** Moving the h1 element without using a negative margin. I couldn't get anything else to work, including flex properties.
**Availability:** Today through Friday 1.28.2022 I have a few hours each night.
**ETA:** I don't want to keep changing this everyday so I'll just say by Friday 1.28.2022 although it will likely be finished before then.

**Comment by pattshreds** [comment]
**Progress:** Title classes are assigned in HTML.
**Blockers:** The title 4 element and the first title7 element don't seem to be the correct sizes. Need to figure out where to define their sizes.
**Availability:** This week 6pm - 8pm
**ETA:** Thursday 3/24/22

**Comment by phuonguvan** [comment]
@JessicaLucindaCheng @pattshreds Hey! This is the design team lead and I was wondering if you are still working on this project. Bonnie told me to update you guys so let me know as soon as possible!

**Comment by JessicaLucindaCheng** [comment]
@phuonguvan Updates are in the pr associated with this issue https://github.com/hackforla/website/pull/2723. See the most recent comments by @pattshreds https://github.com/hackforla/website/pull/2723#issuecomment-1077115270 and by me (@JessicaLucindaCheng) https://github.com/hackforla/website/pull/2723#issuecomment-1077115270
