### ISSUE TITLE
Apply design system heading classes to Homepage 

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2085]
### Overview
We need to apply the new [standardized heading classes](https://github.com/hackforla/website/issues/1743) to the Home page headings (for accessibility/to remove the styling reliance on h tags), so that that the page can now follow the design system plan and be more accessible.
### Action Items
- [x] Apply the heading classes noted in the [Home page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=13607%3A93001) (on the left inside a pink rectangle) to the [Home page](https://www.hackforla.org)
- [x] Make sure the headings still look good and correct (same as the Figma) both in mobile and desktop (there is no reference for the mobile version on Figma yet, but make sure it looks fine), and that nothing gets messed up due to these changes
- [x] Make sure to adjust the heading h tags if needed so that they reflect the correct hierarchy of the page for screen readers (since the styling no longer relies on the h tags)
### Resources/Instructions
[Home page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=13607%3A93001) (on the left inside a pink rectangle)
[Home page](https://www.hackforla.org)
From Figma:
![Screen Shot 2021-08-08 at 1 41 32 AM](https://user-images.githubusercontent.com/67400366/128626367-9b045458-099d-469f-8002-db01cfc1f2f0.png)
![Screen Shot 2021-08-08 at 1 41 39 AM](https://user-images.githubusercontent.com/67400366/128626369-d53a2dab-c6aa-4246-bdc7-5d55e0cb2b69.png)

**Comment by Zhu-Joseph** [comment]
Progress - Began reading through code and standardized heading classes
Blockers - None so far
Availability - Random time here and there
ETA - End of next week if not earlier
