### ISSUE TITLE
Apply design system heading classes to Toolkit page 

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2086]
### Overview
We need to apply the new [standardized heading classes](https://github.com/hackforla/website/issues/1743) to the Toolkit page headings (for accessibility/to remove the styling reliance on h tags), so that that the page can now follow the design system plan and be more accessible.
### Action Items
- [x] Apply the heading classes noted in the [Toolkit page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=5892%3A0) (in pink rectangle) to the [Toolkit page](https://www.hackforla.org/toolkit/)
- [x] Make sure the headings still look good and correct (same as the Figma) both in mobile and desktop, and that nothing gets messed up due to these changes
- [x] Make sure to adjust the heading h tags if needed so that they reflect the correct hierarchy of the page for screen readers (since the styling no longer relies on the h tags)
### Resources/Instructions
[Toolkit page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=5892%3A0) (in pink rectangle)
[Toolkit page](https://www.hackforla.org/toolkit/)
From Figma:
![Screen Shot 2021-08-08 at 1 47 36 AM](https://user-images.githubusercontent.com/67400366/128626497-9bf30b16-449e-42ff-95ca-3865e6a931e5.png)

**Comment by Carlos-A-P** [comment]
Availability for this week: 6hrs
My estimated ETA for completing this issue: 1 week
