### ISSUE TITLE
Apply design system heading classes to Program Areas page 

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2088]
### Overview
We need to apply the new [standardized heading classes](https://github.com/hackforla/website/issues/1743) to the Program Areas page headings (for accessibility/to remove the styling reliance on h tags), so that that the page can now follow the design system plan and be more accessible.
### Action Items
- [x] Apply the heading class (“.Title4”) noted in the screenshot below to the [Program Areas page](https://www.hackforla.org/program-areas)
  - [x] “.Title4" class for the headings in the page cards (“Citizen Engagement,” “Civic Tech Infrastructure,” etc)
- [x] Make sure the headings with the new classes look good both in mobile and desktop, and that nothing gets messed up due to these changes
- [x] If needed, adjust the heading h tags (h3 etc.) so that they reflect the correct hierarchy of the page for screen readers (since the styling no longer relies on the h tags)
### Resources/Instructions
[Program Areas page](https://www.hackforla.org/program-areas)
![Screen Shot 2021-08-08 at 12 29 11 AM](https://user-images.githubusercontent.com/67400366/128626902-37573861-ab76-4815-a213-e9ac5d0ca7b9.png)

**Comment by Carlos-A-P** [comment]
Availability for this week: 4 hrs
My estimated ETA for completing this issue: 2/17/22 Thursday
