### ISSUE TITLE
Apply design system heading classes to Project Team Meetings page 

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2089]
### Overview
We need to apply the new [standardized heading classes](https://github.com/hackforla/website/issues/1743) to the Project Team Meetings page headings (for accessibility/to remove the styling reliance on h tags), so that that the page can now follow the design system plan and be more accessible.
### Action Items
- [x] Apply the heading class (“.Title3”) noted in the screenshot below to the [Project Team Meetings page](https://www.hackforla.org/project-meetings)
  - [x] “.Title3" class for the day-of-week subheadings in the meeting times page card (Monday, Tuesday, etc)
- [x] Make sure the headings with the new classes look good both in mobile and desktop, and that nothing gets messed up due to these changes
- [x] If needed, adjust the heading h tags (h3 etc.) so that they reflect the correct hierarchy of the page for screen readers (since the styling no longer relies on the h tags)
### Resources/Instructions
[Project Team Meetings page](https://www.hackforla.org/project-meetings)
![Screen Shot 2021-08-08 at 12 23 58 AM](https://user-images.githubusercontent.com/67400366/128627021-5fd4418c-f190-416d-8c9c-22e689a4b1e9.png)

**Comment by Aveline-art** [comment]
@kristine-eudey There seems to be overlap between this issue #2090 and #2091. It seems like one of them might be not needed?

**Comment by kristine-eudey** [comment]
@Aveline-art thanks for noticing that, I closed issue #2090 as it duplicates this issue.

**Comment by RyanCahela** [comment]
ETA: 3 Hours or less.
Availability: 12 (Noon) - 5PM 03/24/22
