### ISSUE TITLE
Create a Guide: Using Kanban Project Boards for Team Effectiveness

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#209]
### Dependency
- #918 

### Overview
We need a guide that exaplains how and why we use kanban for new members so that they will have an overview.

### Action Items
- [x] Create draft doc
- [ ] identify how doc is different from guide published on website
- [ ] send to UI for mockup

- [ ] This guide issue needs to be updated on our [Guide Tracking sheet](https://docs.google.com/spreadsheets/d/1omYkR_WeploNuOkF3Pqsg6DhIdej5SS2EBbG9FRefbA/edit?usp=sharing)

### Resources/Instructions
[draft guide](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit)

**Comment by alexandrastubbs** [comment]
Draft of the article: https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit

**Comment by alexandrastubbs** [comment]
Update: Most content is represented in the google doc. The next step is to start to format with powerpoint so all images are represented accurately and layout is clear for when this is passed off to design.

**Comment by alexandrastubbs** [comment]
Guide is complete [here](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit). 

@ExperimentsInHonesty please review once you have a chance.

**Comment by ahdithebomb** [comment]
Please review the article and add use the comment feature for any questions you may have before the next team meeting. 

https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit

**Comment by ltung05** [comment]
Review the article again and leave any comments for new product managers in the future.
@pawan92 @ahdithebomb @ltung05 @Munasmusthafa @IAgbaje

**Comment by ahdithebomb** [comment]
I've added some comments to the document.

**Comment by ExperimentsInHonesty** [comment]
we need to review this deck and figure out where in this guide it goes and it could also use an update: https://docs.google.com/presentation/d/1XUSHMjSEPwIHcLUK4aLrXFMSp6SmZpxFTCqLJtZU2g8/edit#slide=id.p

**Comment by tarang100** [comment]
@pawan92 will suggest some additional language for comment on page 3
@tarang100 will sign-up for Miro and make a flowchart (issue #890 )

**Comment by pawan92** [comment]
I have updated the document addressing my comment on page 3.

**Comment by ExperimentsInHonesty** [comment]
@pawan92 Add glossary items to the doc and a screen shot for the no:projects search on the issues tab

**Comment by pawan92** [comment]
Update:
Progress: Addressed all necessary comments and reached out via slack to commentors to take a look again. Added borders for images as well.
Blockers: N/A
Availability: Yes
ETA:

**Comment by pawan92** [comment]
Update:
Document is ready for another round of reviews. All the previous comments were addressed.

**Comment by pawan92** [comment]
Reached out to Alex lee from Home unite us and Jegede

**Comment by IAgbaje** [comment]
- [ ] This guide issue needs to be updated on our [Guide Tracking sheet](https://docs.google.com/spreadsheets/d/1omYkR_WeploNuOkF3Pqsg6DhIdej5SS2EBbG9FRefbA/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
added the draft doc to the civictechstructure.org page

**Comment by tarang100** [comment]
Need to discuss the draft 'How to Use Kanban' guide with Bonnie during the weekly PM Meeting and resolve all possible pending comments. [Link to draft guide](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit#heading=h.m5h97ersfmtg)

**Comment by tarang100** [comment]
Moving this to Icebox because of the dependency on #918

**Comment by ExperimentsInHonesty** [comment]
Guess what team.  Nowhere in this document does it mention that only one issue should be assigned to a person at a time.  Let's discuss.

**Comment by tarang100** [comment]
**Update**

_Progress_ - I have identified the ideal section in the draft guide for mentioning the practice of assigning only one issue to a person at a time. Sharing link to the exact location in the document [here](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit?disco=AAAAIK0F30Q), request @ExperimentsInHonesty feedback on this
_Blockers_ - None
_Availability_ - Flexible
_ETA_ - Completed

**Comment by tarang100** [comment]
- The responsibility for turning this into the guide format has been handed over to the PM Communities of Practice https://github.com/hackforla/knowledgebase-content/issues/16

**Comment by ExperimentsInHonesty** [comment]
- The issue https://github.com/hackforla/knowledgebase-content/issues/16 is where we will continue this work.  So we no longer need this issue.
