### ISSUE TITLE
Apply design system heading classes to Project Description page 

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2091]
### Overview
We need to apply the new [standardized heading classes](https://github.com/hackforla/website/issues/1743) to the Project Description page headings (for accessibility/to remove the styling reliance on h tags), so that that the page can now follow the design system plan and be more accessible.
### Action Items
- [x] Apply the heading classes noted in the [Project Description page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=5892%3A0) (in pink rectangle) to the [Project Description page](https://www.hackforla.org/toolkit/)
  - [x] “.Title1” class for the header’s heading text (“100 Automations”)
  - [x] “.Title6” class to the page card headings (“Project Overview,” “Resources,” etc)
- [x] Make sure the headings still look good and correct (same as the Figma) both in mobile and desktop, and that nothing gets messed up due to these changes
- [x] Make sure to adjust the heading h tags if needed so that they reflect the correct hierarchy of the page for screen readers (since the styling no longer relies on the h tags)
### Resources/Instructions
[Project Description page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=7891%3A0) (in pink rectangle)
[Project Description page](https://www.hackforla.org/projects/100-automations)
From Figma:
![Screen Shot 2021-08-08 at 2 19 20 AM](https://user-images.githubusercontent.com/67400366/128627234-a35eb4dc-5d63-44f4-b08e-6d505d05d717.png)

**Comment by edeneault** [comment]
Progress: In progress.
Blockers: No blockers.
Availability: Will have availability to complete this week.
ETA: "Monday Nov 1st is the target.
