### ISSUE TITLE
Update ‘Hands’ image credit link and information

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2092]
### Overview
We need to correct the [image credit Name link](https://www.hackforla.org/credits/) and credit information for the ‘Hands’ image to the specific link and accurate information, because it currently has incorrect information and leads to a generic Noun Project link.
### Action Items
- [ ] Replace the generic Noun Project link for the image titled “Hands” in the [credits page](https://www.hackforla.org/credits/) with [this specific link](https://thenounproject.com/search/?q=unity&i=2334876) instead in the ‘Name’ category 
- [ ] Change the credit Name of the icon from Hands to “Unity”
- [ ] Change the credit Artist of the icon from Lucky Day to “Kiran Shastry”
### Resources/Instructions
[Credit.yml template wiki](https://github.com/hackforla/website/wiki/credit.yml-file-template)
[Credits page](https://www.hackforla.org/credits/)
[‘Unity’ (Hands) correct Image link](https://thenounproject.com/search/?q=unity&i=2334876)

**Comment by SAUMILDHANKAR** [comment]
Update 

Progress: "Project is currently in the status of PR needs review. I have made the necessary changes."
Blockers: "None"
Availability: "20 hrs"
ETA: "Aug 23, 2021"
Pictures: "Attached below"

![before](https://user-images.githubusercontent.com/843538/130337078-100393a2-9443-4ef6-8a26-18426b5c8938.PNG)
![after](https://user-images.githubusercontent.com/843538/130337079-fa2a28e3-83f2-4d0f-84c1-aff7913fe9ea.PNG)
