### ISSUE TITLE
Update ‘Give’ image credit link and information

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2093]
### Overview
We need to correct the [image credit Name link](https://www.hackforla.org/credits/) and credit information for the ‘Give’ image to the specific link and accurate information, because it currently has incorrect information and leads to a generic Noun Project link.
### Action Items
- [x] Replace the generic Noun Project link for the image titled “Give” in the [credits page](https://www.hackforla.org/credits/) with [this specific link](https://thenounproject.com/search/?q=care&i=1499467) instead in the ‘Name’ category 
- [x] Change the credit Name of the icon from Give to “Care”
- [x] Change the credit Artist of the icon from Nawicon to “Bharat”
### Resources/Instructions
[Credit.yml template wiki](https://github.com/hackforla/website/wiki/credit.yml-file-template)
[Credits page](https://www.hackforla.org/credits/)
[‘Care’ (Give) correct Image link](https://thenounproject.com/search/?q=care&i=1499467)

**Comment by SAUMILDHANKAR** [comment]
@adrian-zaragoza Please move your issue to the in progress column by @Aveline-art
