### ISSUE TITLE
Update ‘Diversity’ image credit link

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2094]
### Overview
We need to correct the [image credit Name link](https://www.hackforla.org/credits/) for the ‘Diversity’ image to the specific link, because it currently leads to a generic Noun Project link.
### Action Items
- [ ] Replace the generic Noun Project link for the image titled “Diversity” in the [credits page](https://www.hackforla.org/credits/) with [this specific link](https://thenounproject.com/search/?q=diversity&i=1923175) instead in the ‘Name’ category
### Resources/Instructions
[Credit.yml template wiki](https://github.com/hackforla/website/wiki/credit.yml-file-template)
[Credits page](https://www.hackforla.org/credits/)
[‘Diversity’ correct Image link](https://thenounproject.com/search/?q=diversity&i=1923175)

**Comment by Johnnie007** [comment]
Availability for this week 12/5 -12/11:
Tuesday & Thursday Evenings/Night EST
My estimated ETA for completing this issue:
15 mins
