### ISSUE TITLE
Update ‘Global’ image credit link and information

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2095]
### Overview
We need to correct the [image credit Name link](https://www.hackforla.org/credits/) and credit information for the ‘Global’ image to the specific link and accurate information, because it currently has incorrect information and leads to a generic Noun Project link.
### Action Items
- [x] Replace the generic Noun Project link for the image titled “Global” in the [credits page](https://www.hackforla.org/credits/) with [this specific link](https://thenounproject.com/search/?q=impact&i=1710368) instead in the ‘Name’ category 
- [x] Change the credit Name of the icon from Global to “Environmental Impact”
- [x] Change the credit Artist of the icon from Flatart to “Made x Made”
### Resources/Instructions
[Credit.yml template wiki](https://github.com/hackforla/website/wiki/credit.yml-file-template)
[Credits page](https://www.hackforla.org/credits/)
[‘Environmental Impact’ (Global) correct Image link](https://thenounproject.com/search/?q=impact&i=1710368)

**Comment by Zhu-Joseph** [comment]
Progress: Started 
Blockers: None so far
Availability: Random hours here and there
ETA: Within a couple of days

**Comment by adam-abundis** [comment]
@Zhu-Joseph don't forget to move columns in the project board from the `Prioiritzed  Backlog` column to the `In progress (actively working)` column after you assign yourself the issue. This can be achieved in the Project section on the right-side menu under the Labels section.
