### ISSUE TITLE
Create @hackforla.org email address for contacting research participants

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2096]
### Overview
The UX Research team needs an email address to contact potential research participants. 

### Action Items

- [ ] Create Hack for LA email address. Possibilities (in order of preference) could include: 
   - [ ] research@hackforla.org
   - [ ] design@hackforla.org
   - [ ] ux@hackforla.org
   - [x] siteresearch@hackforla.org
- [ ] Share login instructions with UX Research team via 1password
   - [x] Make a list of all people to be added to one password and invite them
     - [x] Basu
     - [x] Pamela
     - [x] Simone
     - [x] Kristine
   - [ ] Accepted
     - [x] Basu
     - [ ] Pamela
     - [x] Simone
     - [x] Kristine
- [x] Add all the UX team members to the fowrarder for the  new email by inviting them 
     - [x] Basu
     - [x] Pamela
     - [x] Simone
     - [x] Kristine
- [x] Make filters for each after they accept 
     - [x] Basu
     - [ ] Pamela
     - [x] Simone
     - [x] Kristine

**Comment by ExperimentsInHonesty** [comment]
The email needs to be specific to this team
Brainstorm:
~hfla-site-research@hackforla.org~
~hflasiteresearch@hackforla.org~
siteresearch@hackforla.org

**Comment by ExperimentsInHonesty** [comment]
@kristine-eudey I setup the email and added it to 1 password.  During our next meeting we I can add all the other people who who need access to the folder, and we can setup forwarders in the email that will send any mail that comes in to each of the people on the team that need it. More details during meeting.

**Comment by Basu3040** [comment]
basudharas@gmail.com

**Comment by PamelaLi36** [comment]
pli36@jh.edu

**Comment by sacamp** [comment]
onesimcam@gmail.com

**Comment by kristine-eudey** [comment]
kristine.eudey@gmail.com

**Comment by ExperimentsInHonesty** [comment]
Next steps

- [x] For people invited to 1 password to accept
- [x] Bonnie to confirm them in 1 password and add to vault
- [x] for one person to log into the email address and add everyone as a forwarder.

**Comment by Basu3040** [comment]
Progress: All the emails of the research team were added.
Now, how can we access the email?

**Comment by kristine-eudey** [comment]
@Basu3040 answer to your question is [here](https://github.com/hackforla/website/issues/2096#issuecomment-900595702) in a previous comment. I gave more detailed info on Slack too for next steps on this.

**Comment by Basu3040** [comment]
@sacamp @PamelaLi36 Let us know if you can access the one password email.

**Comment by ExperimentsInHonesty** [comment]
@PamelaLi36 please accept the invite for 1password that I just sent.  Then we can get you added to the vault.

**Comment by Basu3040** [comment]
This has done!
