### ISSUE TITLE
Update styling for 404 page (Mobile View)

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2097]
### Overview
Making styling changes for the mobile view of the 404 page so it matches the Figma design.

<details>
<br>
  <summary>Click here to see <strong>figma design (iPhone X view)</strong> with visual lines - black lines for margin, red lines for spacing</summary

![Screenshot 2021-07-26 095953](https://user-images.githubusercontent.com/21162229/127033059-1ba1a9df-3bca-4624-95cb-e1bdba4af603.jpg)
<br>
</details>

<details>
<br>
  <summary>Click here to see <strong>your current 404 page (iPhone X view)</strong> with visual lines- black lines for margin, red lines for spacing</summary>
  
  ![Screenshot 2021-07-26 101301](https://user-images.githubusercontent.com/21162229/127032836-cd9721f5-7afd-4b61-9c03-ff2c3957579f.jpg)
<br>  
</details>

### Action Items
- [x] Add left/right margin for the 404 page so it matched the Figma design.
- [x] Adding top/bottom space between the 404 page title.
- [x] `Looks like something went wrong...` text needs to drop the font size for mobile view.

### Resources/Instructions
[404 Error page in Figma (final design in the pink rectangle)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=9616%3A0)
[PR 1972 - My original comment that notated the styling reccomendations](https://github.com/hackforla/website/pull/1972#pullrequestreview-715114095)

**Comment by scorbz9** [comment]
Availability for this week: 6h
My estimated ETA for completing this issue: 6h
