### ISSUE TITLE
Refactor Javascript: Move events page js code to js folder

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2100]
### Overview
As a member of the website development team, Javascript code is much more maintainable and reusable if they exist in a separate folder rather than embedded with html.

### Action Items

- [x] Review the notes below to understand recent changes to our architecture
- [x] Move the code from [events.html ](https://github.com/hackforla/website/blob/gh-pages/pages/events.html)into the main js directory under the name events.js
- [x] Delete the script from events.html
- [x] Call the events.js directory from events.html

### Resources/Instructions
[events.html](https://github.com/hackforla/website/blob/gh-pages/pages/events.html)
[assets/js](https://github.com/hackforla/website/tree/gh-pages/assets/js)

#### Architecture Notes

The idea behind the refactor is to get all of our website's JS code into an organized, consolidated state. Currently, we want our JS files to exist in our [assets/js ](https://github.com/hackforla/website/tree/gh-pages/assets/js)directory with these specifications:

- In the main js directory, the js files should ideally have names corresponding to a related .html page (for example, updates.js should connect to updates.html).
- In the elements sub-directory, the js fjiles should correspond to code needed for our [design system elements ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)to function.
- In the utility sub-directory, the js files represent reusable code that can be used in multiple files. If any js code is reused, they belong in utility, and called in a separate file in the main directory.

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by Aveline-art** [comment]
@abuna1985 I feel this issue can be turned into a standardization for dropdown issue. Any thoughts?

**Comment by Aveline-art** [comment]
This issue will be as is. Once it had been moved, it can then become a standardization issue.

**Comment by Sparky-code** [comment]
ETA: Wednesday 3/9/22 EOD
AVAIL: 3hrs during evenings through wednesday + On-call wednesday.
** Will be out of town 3/09-3/16 (Unavailable next wednesday)
