### ISSUE TITLE
Refactor Javascript: Move copy button js code to js elements folder

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2101]
### Overview
As a member of the website development team, Javascript code is much more maintainable and reusable if they exist in a separate folder rather than embedded with html.

### Action Items

- [x] Locate code for copy button [here](https://github.com/hackforla/website/blob/gh-pages/_guide-pages/github-issues.html)
- [x] Move the code to the elements directory in [assets/js](https://github.com/hackforla/website/tree/gh-pages/assets/js)
- [x] Call the file with the copy button with a script tag where the code was originally
- [x] Currently the copy button indicates it was clicked, but never reverts. Fix this behavior such that it returns to its default state. Also, after copying the code to clipboard, the highlighting should disappear.
- [x] Ensure the website appears the same after the changes (except for the copy button).
- [x] **Want to go above and beyond?** You may also try to do something fancy to show transition from default -> clicked state. For example, you might have the text change from "code" to "clicked" and revert back to "code" after a second or so. Feel free to be as creative as you want!

### Resources/Instructions
[assets/js](https://github.com/hackforla/website/tree/gh-pages/assets/js)
[github-issues.html](https://github.com/hackforla/website/blob/gh-pages/_guide-pages/github-issues.html) (contains copy button code)

#### Architecture Notes

The idea behind the refactor is to get all of our website's JS code into an organized, consolidated state. Currently, we want our JS files to exist in our [assets/js ](https://github.com/hackforla/website/tree/gh-pages/assets/js)directory with these specifications:

- In the main js directory, the js files should ideally have names corresponding to a related .html page (for example, updates.js should connect to updates.html).
- In the elements sub-directory, the js fjiles should correspond to code needed for our [design system elements ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)to function.
- In the utility sub-directory, the js files represent reusable code that can be used in multiple files. If any js code is reused, they belong in utility, and called in a separate file in the main directory.

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by Aveline-art** [comment]
@hackforla/website-design How do we want the copy button to behave on the bottom of [this page](https://www.hackforla.org/guide-pages/github-issues) when clicked? In [Carbon](https://www.carbondesignsystem.com/components/breadcrumb/code) and [Bootstrap](https://getbootstrap.com/docs/5.0/components/breadcrumb/) the standard appears to be with a tooltip popup. Any thoughts, or should development decide?

@hackforla/website-merge Any thoughts?

**Comment by Aveline-art** [comment]
Per Thursday meeting, this code will be a placeholder for the button until design gets around to completing an updated one.

**Comment by blakes24** [comment]
Progress: Pull request made
Blockers: none
Availability: 5 hours
ETA: pending approval 
Pictures: 
<details>
<summary>Copy button clicked</summary>
  
![after](https://user-images.githubusercontent.com/62186905/132076346-bd98cf1d-4139-4784-920b-233b229eb6fb.gif)

</details>

**Comment by Aveline-art** [comment]
Hi @blakes24 Just realized that my instructions were unclear after seeing the gif. For the highlighting, we would want it to not happen at all. I know that is the complete opposite of the action item, but it was a complete brain fart on my part.

**Comment by blakes24** [comment]
Okay. I updated it so that the text doesn't get highlighted.
<details>
<summary>Updated copy button</summary>
  
![copy-btn](https://user-images.githubusercontent.com/62186905/132108831-356df52c-9bb7-4bf6-9b77-85f4729a4b63.gif)

</details>
