### ISSUE TITLE
Complete refactor/standardization of all buttons within Home Page

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2104]
### Overview
We need to refactor for buttons within the Home page from the recommendations in the CSS standardization spreadsheet (resource below) so that we have a consistent button appearance through the HfLA site.

### Action Items
- [x]  Make the 8 recommended edits for the buttons from the spreadsheet below (4 files will be updated)
  

1.  - [x] Update **line 4** of `website/_includes/donate-button.html` with HTML from the `Reccomendation` column
2.  - [x] Update **line 5** of `website/_includes/footer.html` with HTML from the `Reccomendation` column
3.  - [x] Update **line 2** of `website/_includes/_includes/home-getting-started.html` with HTML from the `Reccomendation` column
4.  - [x] Update **line 10** of `website/_includes/forms/contact-us.html` with HTML from the `Reccomendation` column
5.  - [x] Update **line 14** of `website/_includes/forms/contact-us.html` with HTML from the `Reccomendation` column
6.  - [x] Update **line 25** of `website/_includes/forms/contact-us.html` with HTML from the `Reccomendation` column
7.  - [x] Update **line 30** of `website/_includes/forms/contact-us.html` with HTML from the `Reccomendation` column
8.  - [x] Update **line 35** of `website/_includes/forms/contact-us.html` with HTML from the `Reccomendation` column

- [x] Confirm after the recommended edits that the `Action` of each button works as intended within the Home page
- [x] Update CSS to ensure the buttons remain the same as before
- [x] Create a Pull Request with the proposed changes to the button

### Resources/Instructions
[Google Sheets - CSS Standardization Buttons](https://docs.google.com/spreadsheets/d/1n3va-1kwGOCTP4JaXpL3TjgvS_2RWDkurb8PyCJSp-0/edit?usp=sharing)
#1921

**Comment by sheltoG** [comment]
@abuna1985 please break this down into a separate issue for each page effected.

**Comment by adam-abundis** [comment]
@sheltoG This project has been broken down to #2104, #2158, #2159, #2165, #2187

**Comment by ExperimentsInHonesty** [comment]
@abuna1985 this issue is pinned to the [issues homepage](https://github.com/hackforla/website/issues)  Can  you explain why?

**Comment by adam-abundis** [comment]
@ExperimentsInHonesty My apologies. I thought pinning an issue was for individual views not for the entire team. The issue has been unpinned.

**Comment by Zak234** [comment]
ETA: 1 day
Availability: Anytime

**Comment by Zak234** [comment]
Update:
Made changes and tested code. Changes 1, 2 and 3 do not work as intended while the rest seem to be working fine. Will try and update changes 1, 2 and 3 to work properly.

ETA: 1 day

**Comment by Zak234** [comment]
My mistake. Change 3 works fine but changes 4 and 5 don't.
