### ISSUE TITLE
Button to allow win submitter to donate

### ISSUE THREAD

**Issue by sheltoG** [hackforla/website#2108]
### Dependency
- [x] ~thank you email process for wins to be set up.~ we decided this is not necessary at this point.
- [x] #1789 

### Overview
When someone receives an email thanking them for submitting their win, there should be a button in the email that opens up the donation page so that they can potentially make a donation to HfLA so we can keep the organization going

### Additional Detail
Primary goal: **Generate donations to Hfla**
As a submitter of a win, I want to open the donation page, so that I can make a donation to Hfla.

### Action Items

- [ ] Create a donation button in the body of the email notification that points to the donation page

### Resources/Instructions

[HfLA Wins Page](https://www.hackforla.org/wins/)

**Comment by ExperimentsInHonesty** [comment]
@sheltoG I think I prematurely moved this into prioritized backlog.  I don't think we have a mechanism to email or slack the people who donate yet.  So this probably needs a dependency and another issue created or (if one is already made) linked. 

@Aveline-art am I right about this, there is no email that goes out when someone submits a win?

**Comment by ExperimentsInHonesty** [comment]
Also, this issue has two role labels on it.  It only can have one (whoever needs to touch it next).

**Comment by Aveline-art** [comment]
@ExperimentsInHonesty We do not send out an email upon wins submission, as far as I can tell, except maybe beyond a default google email. I have tested it and did not receive an email.

**Comment by ExperimentsInHonesty** [comment]
it probably wont be a button, but rather a link

**Comment by ExperimentsInHonesty** [comment]
I think we can revise this issue to make sure the form that they fill out sends them a copy of the form, and the post message (that the form delivers) has the link to donate.

**Comment by ExperimentsInHonesty** [comment]
I have revised the form to now say

> Confirmation message
> Thank you for sharing your win with us! 
> 
> We need some time to review your win before it will be displayed on the site.
> 
> In the meantime, read some other's wins: https://www.hackforla.org/wins/
> 
> Hack for LA is a project of Civic Tech Structure, Inc. 501(c)(3) and we accept donations at https://hackforla.org/donate.

And I am closing this issue.
