### ISSUE TITLE
Design System Audit: Swap colors with color variables: Reds

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2112]
### Overview
As a developer, hard-coding colors only makes things difficult when colors change. For this only change the red colors so we can use the color variables.

### Action Items

- [x] Refer to [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss) for the current color variables (reds)
- [x] Identify an instance of the hard-coded color 
   - [x] Check to see what that code impacts on the site.
   - [x] Switch out the hard-coded color with the appropriate variable
   - [x] Check to see if it broke anything. Some changes might break the website
   - [x] If the color doesn't stay the same or you get any other kind of error, you can try using the classes from this file website/_sass/elements/_color-styles.scss
     - [x] Add a comment to this issue with any instances of needing to use the styles instead of colors.scss
- [x] If a color variable is unused, 
  - [x] Check if its corresponding color class is used. See a list of classes here: [/_sass/elements/_color-styles.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_color-styles.scss) 
- [x] If both the color variable itself and the color class are not used for a specific color,
  - [x] Delete the color variable from this file: `_sass/variables/_colors.scss`
  - [x] Delete its corresponding color class from this file: `/_sass/elements/_color-styles.scss`
- [ ] Release dependency on #2114, if conditions are met

### Resources/Instructions
- https://github.com/hackforla/website/blob/09d4b31f55f3ab8eea179e1805f1b1a292e56654/_sass/variables/_colors.scss#L5-L11

<details>
  <summary>Click here to see a visual example of search/replace for color variables within VS code</summary>
  <br>
  Search: hex color<br>
  Replace: color variable<br>
  files to include: ./<br>
  files to exclude: *.svg, _site, _colors.scss<br>
  Click on the `Replace All` button (shortcut: Ctrl+Alt+Enter)
  Click `Ok` to confirm replace
  <img src='https://user-images.githubusercontent.com/21162229/131246575-ce0b8a00-cf0b-4803-8fc1-8bcedd7f941e.gif' />
</details>

If the task seems tedious, this might smooth things along if your native IDE is VSCode. Other IDEs might also have similiar functionality.
[Advanced find and replace options for VSCode](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options)
- Information about color CSS property: https://developer.mozilla.org/en-US/docs/Web/CSS/color

**Comment by Aveline-art** [comment]
@hackforla/website-merge As seen in the above action items, there are two files that lists our website's colors. One for the sass color variables, and the other for classes. What is the ideal use case for variables and the ideal use case for classes?

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art This needs to be broken out into multiple issue
the issue should be to audit one specific color to see which pages it appears (annotating in issue) and then changing all of those pages - in one pr.

**Comment by Aveline-art** [comment]
@ExperimentsInHonesty We currently have [nearly 40 colors](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_color-styles.scss). I feel that that might be too many issues, especially for one person to create, even with a template. I had made this issue to complete the unfinished task from #1378 , and have made a follow up audit with #2114. I want to confirm that this absolutely must be broken separately by color before proceeding. If so, I would need to know what the priority of this task is so that I may properly block time to make all the issues, or if I could assign someone else to the task of issue creation.

**Comment by sheltoG** [comment]
Per @abuna1985 and @ExperimentsInHonesty conversation this issue will get rewritten.

**Comment by adam-abundis** [comment]
@sheltoG @ExperimentsInHonesty Issue has been updated.

**Comment by clayton1111** [comment]
ETA: End of the day
Availability: All day

**Comment by ExperimentsInHonesty** [comment]
This issue got reopened, because we did an manual check and found that on one color alone there were at least 5 changeable instances that did not get changed.

- $color-red: #fa114f;
  - _sass/components/_guides.scss
     - `text-decoration-color: #fa114f;`
     - `color: #fa114f;`
  - _layouts/guides.html
     - `ref="https://www.google.com/"style="color: #fa114f;" >`
  - _guide-pages/how-to-set-reminders-in-slack.md
     - `color: #FA114F;`
  -  pages/guides.html
     - `href="https://www.google.com/"style="color: #fa114f;" >`
     -  `color: #FA114F;`

**Comment by esantiano** [comment]
ETA: 11/18/22
Availability: 3 Hours

**Comment by ExperimentsInHonesty** [comment]
There is activity on the PR as of 6 days ago

**Comment by esantiano** [comment]
`Progress:` changed all changeable instances of #fa114f to "$color-red". Checking pages for instances of "$color-salmon: #ffadad" and "rgb(250, 17, 79)"
`Blockers:` Recently started a new job. 
`Availability:` 3 Hours 
`ETA:` 12/03/2022

**Comment by ExperimentsInHonesty** [comment]
This is only place a color remains.  I am reopening this issue.
https://github.com/hackforla/website/blob/a9b9119133c884c251a0f5fe21704d8bad876025/_layouts/project.html#L171
https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html#L171

@hackforla/website-merge please make a new issue to resolve.  Then this epic can close.
