### ISSUE TITLE
Design System Audit: Swap colors with color variables: black, grey, and white

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2113]
### Overview
As a developer, hard-coding colors only makes things difficult when colors change. For this only change the black, grey, and white colors so we can use the color variables.

### Action Items

- [x] Refer to [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss) for the current color variables (black, grey and white colors)
  - [x] Also, make sure to check the equivalent hex values
    - [x] For `$color-black`, `#333` is the same as `#333333`
    - [x] For `$color-mediumgrey`, `#ccc` is the same as `#cccccc`
    - [x] For `$color-white`, `#fff` is the same as `#ffffff`
- [x] Replace all instances of the hard-coded colors with the color variables
  - [x] Make sure to do this carefully, as some changes might break the website
  - [x] If it breaks, investigate why and make edits accordingly. Ask for help if needed.
- [x] If a color variable is unused, 
  - [x] Check if its corresponding color class is used. See a list of classes here: [/_sass/elements/_color-styles.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_color-styles.scss) 
- [x] If both the color variable itself and the color class are not used for a specific color,
  - [x] Delete the color variable from this file: `_sass/variables/_colors.scss`
  - [x] Delete its corresponding color class from this file: `/_sass/elements/_color-styles.scss`
- [x] Release dependency on #2114 , if conditions are met

### Resources/Instructions
https://github.com/hackforla/website/blob/09d4b31f55f3ab8eea179e1805f1b1a292e56654/_sass/variables/_colors.scss#L49-L58

If the task seems tedious, this might smooth things along if your native IDE is VSCode. Other IDEs might also have similar functionality.
[Advanced find and replace options for VSCode](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options)

You can do a search within VS Code with the **following values**:

 **Search**: hex color goes here
  **Replace**: color variable goes here
  **files to include**: ./
  **files to exclude**: *.svg, _site, _colors.scss
  
  Once the values are in the search form, do the **following actions**:
  1. Click on the `Replace All` button (shortcut: Ctrl+Alt+Enter)
  2. Click `Ok` to confirm replace
<details>
  <summary>Click here to see visual example of search/replace for color variables within VS code</summary>
  <br>
  <img src='https://user-images.githubusercontent.com/21162229/131246575-ce0b8a00-cf0b-4803-8fc1-8bcedd7f941e.gif' />
</details>

**Comment by sheltoG** [comment]
Per @abuna1985 and @ExperimentsInHonesty conversation this issue will get rewritten.

**Comment by adam-abundis** [comment]
@sheltoG @ExperimentsInHonesty This task has been updated.

**Comment by raswani2023** [comment]
ETA: Tomorrow
Availability: 2hrs

**Comment by 7kram** [comment]
This issue got reopened, because we did a manual check and found that on two of the colors, there were 3 changeable instances that did not get changed.

- $color-darkblue: #030d2d; 
   - _sass/components/_guides.scss
 ```
   .is-active a:focus {
--
163 | color: #030d2d;
```
- $color-white: #fff; 
   - _sass/components/_guides.scss
     - `color: #fff;`
     - `background-color: #fff;`

**Comment by ldaws003** [comment]
ETA: Tuesday by 3:00pm
Availability: Tuesday 2:00pm to 6:00pm, Wednesday 12:00pm-5:00pm

**Comment by JessicaLucindaCheng** [comment]
@ldaws003 Thanks for working on this issue! I just want to let you know I just updated the Action Items to make them clearer.

**Comment by ldaws003** [comment]
ok, thanks

**Comment by ldaws003** [comment]
> @ldaws003 Thanks for working on this issue! I just want to let you know I just updated the Action Items to make them clearer.

Hi Jessica, should I replace all hard coded colors that show in the  "Blacks, Greys, White" section, or only white, black and mediumgrey?

**Comment by JessicaLucindaCheng** [comment]
@ldaws003 Sorry, I didn't see your comment to me until now. In the future, please @ mention me so that I get notified. Thanks.
