### ISSUE TITLE
Design System Audit: Audit for hardcoded colors

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2114]
### Dependency
- [x] #4138 
- [x] #2112
- [x] #2113 
- [x] #2198
- [x] #2199
- [x] #2200
- [x] #2204
- [x] #2205

### Overview
We want to stop using hard-coded colors, and instead, use variables so future changes to colors in our color palette will be easier to implement on our website.

### Action Items
- [x] Check our entire code base for hard-coded colors (as opposed to a color variable).
  - [x] Check for all of the color types listed in the Resource section below.
  - [x] If a color is hard-coded*, and is not currently a variable (see files below), add a comment on this issue noting:
    - [x] its location, including
      - [x] file
      - [x] code snippets 
    - [x] the type of color (reds, oranges, blacks, etc)
    - [x] suggested color variable name
  - [x] Else:
    - [x] change the hard-coded color to a variable instead  

### Resources/Instructions
- HTML colors: https://htmlcolorcodes.com/
- Color variables and classes in our codebase
  - Color variables: https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss
  - Color classes: https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_color-styles.scss
- If the task seems tedious, this might smooth things along if your native IDE is VSCode. Other IDEs might also have similar functionality.
  - [Advanced find and replace options for VSCode](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options)
  
 #### *Hard-coded colors can be one of the following color types:
- HTML color codes
- Hex color codes
- RGB 
- HSL values
- HTML color names

**Comment by bishrfaisal** [comment]
We need clarification on what the action items in this section mean. 

> If a color is hard-coded

**Comment by ExperimentsInHonesty** [comment]
- $color-red: #fa114f;
  - _sass/components/_guides.scss
     - `text-decoration-color: #fa114f;`
     - `color: #fa114f;`
  - _layouts/guides.html
     - `ref="https://www.google.com/"style="color: #fa114f;" >`
  - _guide-pages/how-to-set-reminders-in-slack.md
     - `color: #FA114F;`
  -  pages/guides.html
     - `href="https://www.google.com/"style="color: #fa114f;" >`
     -  `color: #FA114F;`

**Comment by JessicaLucindaCheng** [comment]
- PMs will be re-auditing the following issues:
  - #2112
  - #2113 
  - #2198
  - #2199
  - #2200
  - #2204
  - #2205
- If a PM finds any hard-coded colors, the corresponding issue above will be re-opened by the PMs for a dev to redo the issue. 
- This issue will be placed back in the Ice Box until all issues in the Dependency are complete again.

**Comment by ExperimentsInHonesty** [comment]
Additionally, the issues will need to be fully audited once they are completed.

**Comment by JessicaLucindaCheng** [comment]
Here is a screenshot example of searching `color` hard-coded and not currently a variable:
<img width="960" alt="image" src="https://user-images.githubusercontent.com/31293603/200191768-6d68b5e4-6782-4c84-8e30-1b18bfe305ed.png">

**Comment by JessicaLucindaCheng** [comment]
I updated the Action Item

**Comment by JessicaLucindaCheng** [comment]
The following colors don't have variable names and should be included in this issue's audit. However, this list is not exhaustive and the person assigned to this issue will need to do a more thorough search/audit of our codebase.
- `#000000`
- `#efefef`

**Comment by AHP15** [comment]
i. Availability: 03/06/2023
ii. ETA: 05/06/2023

**Comment by AHP15** [comment]
- file : `_sass/_normalize.scss`
- line 89, code snippet:` a { background-color: transparent; }`
- color type: transparent
- suggested name: `color-transparent`

**Comment by AHP15** [comment]
- file: `_sass/_normalize.scss`
- line 146, code snippet: `mark {
  background: #ff0;
  color: #000;
}`
- color type: black and yellow
- suggested name: `color-dark-black` and `color-yellow`

**Comment by AHP15** [comment]
- file: `_sass/components/_404.scss` and `_sass/components/_getting-started-page.scss` and `_sass/components/_guides.scss`
- line 89 and 331 and 242 (respectively), code snippet:
 ```
.main-message-404 {
  font-weight: bold;
  font-size: 24px;
  color: #000000;
  opacity: 0.5;
  margin-bottom: 80px;

  @media #{$bp-below-desktop} {
    margin-bottom: 0px;
  }

  @media #{$bp-below-tablet} {
    margin-top: 10px;
    margin-bottom: 5px;
    margin-right: 5px;
    font-size: 16px;
  }
}
```

and 
```
.step-header {
  display: flex;
  justify-content: left;
  color: #000000;
  font-family: "Roboto"sans-serif;

  @media #{$bp-below-tablet} {
    justify-content: center;
  }
}
```

and
```
.fa {
	font-size: 30px;
	width: 50px;
	text-align: center;
	text-decoration: none;
	color: #000000;
}
```

- color type: black
- suggested name: `color-dark-black`

**Comment by AHP15** [comment]
- file: `_sass/components/_about.scss`
- line 467, code snippet:
```
.eliptical {
  color: #959393;
  text-align: right;
}
```
- color type: grey
- suggested name: `color-grey`

**Comment by AHP15** [comment]
- file: `_sass/components/_dashboard.scss`
- line 3, code snippet:
```
.dashboardEmbed{
    display: flex;
    background-color: #020d2d;
    margin: 0 auto 0 auto;

    @media #{$bp-tablet-up}{
        #mobileView{
            display: none;
        }
    }
    @media #{$bp-below-tablet}{
        #mobileView{
            display: block;
            margin: 22% auto 0 auto;
        }
        #webView{
            display: none;
        }
    }
}
```
- color type: blue
- suggested name: `color-darkblue`

**Comment by AHP15** [comment]
- file: `_sass/components/_donate-components.scss`
- line 25, code snippet:
```
.circle-with-text {
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: #cde4c5;
    border-radius: 50%;
}
```
- color type: white
- suggested name: `color-palemint`

**Comment by Abdessittir** [comment]
- file: `_sass/components/_donate-components.scss`
- line 58, code snippet:
```
.inside-circle-text {
    text-align: center;
    color: #030D2D;
    margin: 0;    
}
```
- color type: blue
- suggested name: `color-darkblue-2`

**Comment by Abdessittir** [comment]
- file: `_sass/components/_home.scss`
- line 324 and 328, code snippet:

```
.status-Active {
  background-color: rgb(187, 255, 187);
}

.status-Rebooting {
  background-color: rgb(164, 213, 255);
}
```
- color type: blue
- suggested name: `color-lightblue`

**Comment by Abdessittir** [comment]
- file: `_sass/components/_privacy-policy.scss`
- line 69, code snippet:
```
 p {
      font-size: $font-size-paragraph3;
      line-height: 1.375;
      font-family: "Roboto", sans-serif;
      font-weight: 400;
      color: #333;
    }
```
- color type: black
- suggested name: `color-lightblack`

**Comment by AHP15** [comment]
- file: `_sass/components/_wins-page.scss`
- line 379, code snippet:
```
.overlay {
        display: none;
        z-index: 1;
        position: fixed;
        left: 0px;
        top: 0px;
        width: calc(100vw + 17px);
        height: 100%;
        background-color: rgba(70, 70, 70, 0.5);
        padding: 10px;
        overflow-y: auto;
        overflow-x: hidden;
    }
```
- color type: black
- suggested name: `color-semitransparentblackgray`

**Comment by AHP15** [comment]
- file: `_sass/components/_credit-items.scss`
- line 3, code snippet:
```
.wide-div {
  margin-top: 29px;
  background: #030c2c;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  font-family: "Roboto" sans-serif;
  font-style: normal;
  font-weight: normal;
}
```
- color type: blue
- suggested name: `color-deepnavyblue`

**Comment by AHP15** [comment]
- file: `_sass/components/_guides-page.scss`
- line 41, code snippet:
```
      @media #{$bp-below-mobile} {
        background: linear-gradient(to bottom, rgba(3,13,45,0.3) 30%, $color-darkblue 100%);
      }
```
- color type: blue
- suggested name: `color-slightlytransparentdarkblue`

**Comment by AHP15** [comment]
- file: `_sass/components/_project-page.scss`
- line 242 , code snippet:
```
.sdg-description-card {
  padding-top: 30px;
  display: flex;
  flex-direction: column;
  flex-wrap: wrap;
  margin-right: auto;
  background: #02548B;
  text-align: center;
  border-radius: 10px 10px 11px 11px;
  height: fit-content;

```
- color type: blue
- suggested name: `color-mediumshadeblue`

**Comment by AHP15** [comment]
- file: `_saas/components/_guides.scss`
- line 52, 225, code snippet:
```
.guide-links ul {
	color: #000;
	list-style-type: disc;
}
```
and 
```
.author-img-placeholder {
	background-color: #efefef;
	width: 100px;
	height: 100px;
	border-radius: 50%;
}
```
- color type: black , white
- suggested names: color-black-2, color-lightgray
