### ISSUE TITLE
Refactor JS: Move script from wins page into js directory

### ISSUE THREAD

**Issue by Abel-Zambrano** [hackforla/website#2116]
### Overview
We need to separate `<script>` code from `wins.html` into a separate folder so we can better maintain and reuse our JavaScript code.

### Action Items

- [x] Review the notes below to understand recent changes to our architecture
- [x] Move line 25-280 from the `/pages/wins/wins.html` into a new js file in the assets/js main directory. it should be something like `/assets/js/wins.js`. Omit the opening and closing `<script>` tag.
- [x] once `/assets/js/wins.js` has the code from `<script>` tag in `wins.html`, delete line 24-281 (opening and closing `<script>`.
- [x] replace line 24 with a script element tied to the newly created file like `<script src="/assets/js/wins.js" type="module"></script>`
- [x] Ensure that the website still appears the same. No visual changes should be made as this is a refactor.

### Resources/Instructions

https://github.com/hackforla/website/blob/8a6df1dcd270c17403fa75c5842be9aa07ab3fa9/pages/wins/wins.html#L24-L481
[wins page](https://www.hackforla.org/wins/)

#### Architecture Notes

The idea behind the refactor is to get all of our website's JS code into an organized, consolidated state. Currently, we want our JS files to exist in our [assets/js ](https://github.com/hackforla/website/tree/gh-pages/assets/js)directory with these specifications:

- In the main js directory, the js files should ideally have names corresponding to a related .html page (for example, updates.js should connect to updates.html).
- In the elements sub-directory, the js fjiles should correspond to code needed for our [design system elements ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)to function.
- In the utility sub-directory, the js files represent reusable code that can be used in multiple files. If any js code is reused, they belong in utility, and called in a separate file in the main directory.

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by Aveline-art** [comment]
@Abel-Zambrano This is no longer an issue, as it has been fixed as part of a recent PR. I will recycle this issue into a different issue.

**Comment by linds-fonnes** [comment]
Progress: Moved the script from wins.html lines 24-480 to its own JS file. 
Blockers: Need to figure out how to reassign both the localData and gitHubData variables that were previously assigned in the HTML file using Liquid.
Availability: 5 hours
ETA: By Oct 1
Pictures: N/A

**Comment by linds-fonnes** [comment]
Progress: Need to make requested changes to add in the see more/less functionality to JS file from HTML file
Blockers: None
Availability: 5 hours
ETA: Sunday night
Pictures: No visual changes
