### ISSUE TITLE
Refactor JS: Move hamburger-nav html script to the js folder

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2117]
### Overview
As a member of the website development team, Javascript code is much more maintainable and reusable if they exist in a separate folder rather than embedded with html.

### Action Items

- [x] Review the notes below to understand recent changes to our architecture
- [x] Move the script code [here](https://github.com/hackforla/website/blob/gh-pages/_includes/hamburger-nav.html) to a JS file in the [main JS directory](https://github.com/hackforla/website/tree/gh-pages/assets/js) with an appropriate name.
- [x] Call the newly made JS file in the original html file in place of the moved script. 
- [x] Ensure that the website and the hambuger nav functions the same way. No functional or visual changes should happen.
  - [x] If this is not the case, then edit the code as appropriate to maintain functionality.
### Resources/Instructions
[How do I include liquid/global variables defined using Jekyll in a Javascript file?](https://stackoverflow.com/questions/58517425/how-do-i-include-liquid-global-variables-defined-using-jekyll-in-a-javascript-fi)

#### Architecture Notes

The idea behind the refactor is to get all of our website's JS code into an organized, consolidated state. Currently, we want our JS files to exist in our [assets/js ](https://github.com/hackforla/website/tree/gh-pages/assets/js)directory with these specifications:

- In the main js directory, the js files should ideally have names corresponding to a related .html page (for example, updates.js should connect to updates.html).
- In the elements sub-directory, the js fjiles should correspond to code needed for our [design system elements ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)to function.
- In the utility sub-directory, the js files represent reusable code that can be used in multiple files. If any js code is reused, they belong in utility, and called in a separate file in the main directory.

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by adam-abundis** [comment]
@Aveline-art closing this issue because #1970 was made to address the alt text within the credits page.

**Comment by Aveline-art** [comment]
@abuna1985 I never intended for this issue to be ready for review by an entity outside of me (hence the the back and forth removal of the 'ready for milestone' label). I had noticed the duplicate issue and was going to repackage this as a different issue. Is there a way for me to mark an issue as a draft so that it is safely ignored?

**Comment by adam-abundis** [comment]
My bad. We were reviewing #1970 and were requested to close this. I'll reopen it and you can make the changes you need. It should be fine in the New Issue Approval column. Once it's ready add the 'Ready for Milestone' tag so product can move it to the appropriate column.

**Comment by GLRJr** [comment]
just finished, it only needed the front matter for jekyll.

**Comment by GLRJr** [comment]
created new pull request with front matter changed
