### ISSUE TITLE
Adjust footer position

### ISSUE THREAD

**Issue by blakes24** [hackforla/website#2125]
### Overview
We need to move the footer to a fixed position at the bottom of all pages so we can have a consistent look for the page footer no matter the width of the page (all breakpoints).

- [x] **Redirect page**: issue is present for all screen sizes
<details>
<summary>Redirect Page screenshot </summary>
<img width="1436" alt="Screen Shot 2021-08-17 at 3 14 21 PM" src="https://user-images.githubusercontent.com/62186905/129812469-e7c5ad1a-25dd-4859-a891-9ec3c829e190.png">
</details>

- [x] **404 page**: observed for screen widths between 480px and 767px, above 1453px, and in ipad pro view from chrome dev tools (screen height also affects whether the footer is above the bottom of the page)

<details>
<summary>404 Page screenshot </summary>
<img width="505" alt="Screen Shot 2021-08-17 at 3 11 13 PM" src="https://user-images.githubusercontent.com/62186905/129812486-affe964f-dd5a-4ea1-b4c6-61b0fdb50369.png">
</details>

- [ ] **Project page**: screen widths above 768px it is possible to scroll past the footer when projects are filtered to a single row of results

<details>
<summary>Project Page screenshot (filtered to only show 2 projects) </summary>
<img width="506" alt="Screen Shot 2021-08-17 at 3 06 58 PM" src="https://user-images.githubusercontent.com/62186905/129812556-941fa9e1-8982-47df-bfc5-faf3a77e063d.png">
</details>

### Action Items
- [ ] Adjust footer position so that it is always at the bottom of the page (fixed position at the bottom of each page)
- [ ] Ensure that the correction doesn't break any other pages that are connected to your changes

### Resources/Instructions
[footer.html](https://github.com/hackforla/website/blob/gh-pages/_includes/footer.html)
[_layouts/default.html](https://github.com/hackforla/website/blob/gh-pages/_layouts/default.html)

**Comment by macho-catt** [comment]
@blakes24 Could you specify the screen sizes you found the issue on for the three pages? Thanks!

**Comment by blakes24** [comment]
@macho-catt The issue has been updated to include screen sizes and an additional page.

**Comment by Abel-Zambrano** [comment]
Progress: Fixed footer on 404 page.
    Blockers: Generating the "redirecting" page.
    Availability: 5hrs
    ETA: 9/13/21

**Comment by Abel-Zambrano** [comment]
@blakes24 Hello, do you have any steps or a specific link/url that I can use to generate the "redirect" page?

**Comment by macho-catt** [comment]
@Abel-Zambrano, you can manipulate the line in the code:
```
<meta http-equiv="refresh" content="0;url={{ page.redirect_to }}" />
```
Change content from 0 to 5 for example, for five seconds. Change the time to as long as you want so you can look at the page.
[Line in code](https://github.com/hackforla/website/blob/7750bd39e6546ef9ef0e82c4d04ffbea3c157329/_layouts/redirect.html#L7)

**Comment by Abel-Zambrano** [comment]
Progress: Fixed footer on 404 page.
Blockers: currently out of town
Availability: be back 10/16
ETA: 10/16

**Comment by Abel-Zambrano** [comment]
> @Abel-Zambrano, you can manipulate the line in the code:
> 
> ```
> <meta http-equiv="refresh" content="0;url={{ page.redirect_to }}" />
> ```
> 
> Change content from 0 to 5 for example, for five seconds. Change the time to as long as you want so you can look at the page. [Line in code](https://github.com/hackforla/website/blob/7750bd39e6546ef9ef0e82c4d04ffbea3c157329/_layouts/redirect.html#L7)

Hey @macho-catt . I tried doing this and nothing changes. Am I supposed to see a redirect page on every link that's clicked on the site or is there something else I need to do?

**Comment by adam-abundis** [comment]
@Abel-Zambrano use the `donation-form` link within https://www.hackforla.org/donate/

When you click on it, it will open a new tab with the redirect page followed by the Code For America Donation page.

**Comment by macho-catt** [comment]
@Abel-Zambrano  as @abuna1985 mentioned, the redirect link only works for redirections. For a list of possible redirections, you can refer to this directory in the code: https://github.com/hackforla/website/tree/gh-pages/redirections

Now every time you go to a permalink from that directory (like the donate permalink, which is pointing to /codeforamerica) it will first lead you to the redirect page, then the actual page of redirection. By increasing the seconds from 0 to 5, this redirect page will show for longer.

Thanks!

**Comment by adam-abundis** [comment]
@Abel-Zambrano I found the following issues with both the projects page & wins page

<details>
  <summary>Click here to see projects page gif</summary>
<p>Noitice when there is 1 card, the footer goes under the card and the height stays as long as the dropdown filter menu</p><strong>The footer is not at the bottom</strong>

![Projects - Hack for LA](https://user-images.githubusercontent.com/21162229/138542073-3cae4b72-300e-4e25-a8de-342230fd9de7.gif)

<p>screenshot of footer display error (wins page)</p>

![screencapture-hackforla-org-projects-2021-10-22-21_22_24](https://user-images.githubusercontent.com/21162229/138542142-ffaf7f45-c173-424d-966a-3c7e0bfc3070.png)
</details>

<details>
  <summary>Click here to see wins page gif</summary>
<p>Noitice when there is 0card, the footer goes under the blank space and the height stays as long as the dropdown filter menu</p><strong>The footer is not at the bottom</strong>

![Wins - Hack for LA](https://user-images.githubusercontent.com/21162229/138542178-ff07a2ae-9810-4ac0-93bf-cfbcf15728c6.gif)

<p>screenshot of footer display error (wins page)</p>

![screencapture-hackforla-org-wins-2021-10-22-21_21_36](https://user-images.githubusercontent.com/21162229/138542185-9fd6b402-ee3f-4d1a-81a6-35ab6e8c1fe2.png)
</details>

**Comment by Abel-Zambrano** [comment]
Progress: Complete
Blockers: Waiting for merge approval
Availability: n/a
ETA: n/a

**Comment by Abel-Zambrano** [comment]
Progress: Fixed footer on all pages except redirect page.
Blockers: n/a.
Availability: 2hrs
ETA: 11/19/2021

**Comment by Abel-Zambrano** [comment]
Progress: Complete
Blockers: Pending Review
Availability: n/a
ETA: n/a

**Comment by Abel-Zambrano** [comment]
Progress: Complete
Blockers: Pending Review
Availability: n/a
ETA: n/a
