### ISSUE TITLE
Gather .svg files for icons of technologies used at HfLA

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2130]
### Overview
We need .svg files of the icons for as many of the technologies used in HfLA projects, so that users exploring our projects by technology can get a quick sense of the technologies we use. This will support the homepage redesign. 

### Action Items

UI/UX:
- [ ] Refer to the list of technologies in the Projects Page dropdown
- [ ] Locate .svg files for the icons of each of the technologies listed. 
  - [ ] These can often be found by googling "logo [technology]", for example "logo jekyll" leads to [these results ](https://www.google.com/search?client=firefox-b-1-d&q=svg+of+logo+jekyll) which leads to [this page](https://github.com/jekyll/brand)
- [ ] Place all .svgs in the folder identified below in the Resources section of this issue
  - [ ] When choosing an .svg to place in the folder, choose the one that appears on the main page of its website.
- [ ] Make a spreadsheet in the same folder with each technology's name, a link to where the .svg was downloaded from, a link to the technology's homepage and a yes/no column.
  - [ ] In the yes/no column, a yes indicates that the .svg has been placed in the drive folder, and a no means that some Photoshop magic or whatnot would be required to retrieve the logo as an .svg.
  
Developer: 
- [ ] Have a copy of all the downloaded .svgs inside a new directory named "technologies-logos" within [this folder](https://github.com/hackforla/website/tree/gh-pages/assets/images)

### Resources/Instructions
[Hack for LA - Projects Page](https://www.hackforla.org/projects/)
[Google Drive folder - Technology icon .svg files](https://drive.google.com/drive/folders/1Vq4_CAM0vbJWQLsszne2PeQu5y3r3MeO?usp=sharing)
[assets/images](https://github.com/hackforla/website/tree/gh-pages/assets/images)

**Comment by ExperimentsInHonesty** [comment]
Hi @kristine-eudey I know Ava volunteered the dev team to work on this, but they have a big backlog of stuff that NEEDs to get done that only they can do, so this need to be the ui/ux team.  When you get to the point where you have some that its not clear what is the official logo or if there is not a easily findable logo, then product will look at those specifically and provide guidance.

**Comment by kristine-eudey** [comment]
@ExperimentsInHonesty no problem at all, design can source the files. Since only a selection of the icons are now going to be featured on the homepage, can you let me know the 10 most commonly used technologies (or whichever needs to be featured there?)

**Comment by Aveline-art** [comment]
@kristine-eudey Here's 12 in case some of them do not have logos. They are in no specific order, but candidates to remove might be Python and Javascript.

1. Docker
2. React
3. AWS
4. Django
5. Javascript
6. Python
7. Figma
8. Express
9. MongoDB
10. PostgreSQL
11. GitHub
12. NoSQL

**Comment by kristine-eudey** [comment]
@Aveline-art thanks for compiling this list! Based on what you shared, and by looking at the most frequently used technologies on the projects page dropdown I've incorporated the icons listed below on the homepage. I think the only one here that wasn't on your list which I've added is Node.js, which is shown to be used in 7 projects on the dropdown list. 

@Aveline-art and @abuna1985 please take a look and let me know if there are any important technologies you think are missing, or any here that shouldn't be featured. You can see them on the homepage [here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15145%3A98212).

1. React
2. Node.js
3. Docker
4. Django
5. MongoDB
6. PostgreSQL
7. AWS
8. GitHub
9. Express
9. NoSQL

**Comment by ExperimentsInHonesty** [comment]
@kristine-eudey we still need to review this list some more.  Items that came up after you left the meeting were: Figma, data science technologies (Jupyter notebook, Google Colab) and anything else people put in comments below

**Comment by adam-abundis** [comment]
@kristine-eudey I think we can remove `nosql` with `Figma`. We have 2 references to specific databases. This will allow us to feature design tools.

**Comment by kristine-eudey** [comment]
Edited to reflect above comments: nosql was replaced with Figma. See current list on [Figma - Homepage Redesign](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15505%3A99314)

**Comment by kristine-eudey** [comment]
Moving issue to ice box since we are no longer incorporating technologies icons on the homepage.

**Comment by ExperimentsInHonesty** [comment]
@kristine-eudey where did the logo images end up getting stored?  In figma someonewhere, google drive?  Can you add the links into this issue?

**Comment by kristine-eudey** [comment]
@ExperimentsInHonesty the logo icons are stored on our google drive. The link is in the resources section of the issue, and also here: [Google Drive - Technology icon .svg files](https://drive.google.com/drive/folders/1Vq4_CAM0vbJWQLsszne2PeQu5y3r3MeO?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
Bonnie to talk with Developers to see if we want to put these in the code folders or link to it from the online design system

**Comment by ExperimentsInHonesty** [comment]
@macho-catt create new issue for having the svgs uploaded to the assets folder
