### ISSUE TITLE
Wins page remaining issues

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#2135]
### Overview

We need to group action items for the `wins-feature-1` branch and Wins page. We will convert each action item into an issue and create a pull request to close the corresponding issue.

### Action Items
<i>The following actions are in order</i>
- [x] #2029 
- [x] #2138
- [x] #2176
- [ ] refactor code if so inclined
- [ ] do a page audit after it is live
- [x] #2021
- [x] #2246
- [ ] put wins data formatting in the google app script and take it out of the wins.html (To be accomplished by #2145)
- [x] #1980
- [x] #2267
- [x] #2207

### Resources/Instructions
https://www.hackforla.org/wins/

### Ideas for further features
- Limit the number of wins that can be viewed at one time
- have another filter-dropdown for peoples wins - i.e. "I got a new job", "I increased the number of commits on my github profile"
- create a way for us to add people add avatar photos individually just in case they want to give us a photo (just add it to our repo in assets or something)
- make the projects on each card a link to the project page

**Comment by adam-abundis** [comment]
from @jbubar on 8/19/2021

Will finish this issue after the next sun meeting, but before next Tuesday's meeting. Each of the actions will be their own issue

**Comment by jbubar** [comment]
Amendment. Will pick at this as I have time. Will prob take me another few weeks to find the time🤦‍♂️

**Comment by Abel-Zambrano** [comment]
@arghmatey Will create issues after merge of wins-feature-1.

**Comment by ExperimentsInHonesty** [comment]
Design will change it so that see more is on the bottom of the card and text will just have three dots if it does not fit.
and on mobile it will move too.  However right now the three dots and see more don't seem aligned on mobile  and since the three dots (not red) will stay, it will need to be aligned properly.
![image](https://user-images.githubusercontent.com/37763229/131261513-7d7f46b1-9f98-48fc-b966-b83531e19c59.png)

**Comment by macho-catt** [comment]
@arghmatey will work on creating issues for each action items

**Comment by arghmatey** [comment]
Progress: Researched action items. Created issues were needed, and attached issues that already existed.
Blockers: Time! 
Availability: 2 hours
ETA: Monday 9/13
Pictures: N/A

**Comment by arghmatey** [comment]
Remaining issues have been created or linked. Closing issue.
