### ISSUE TITLE
Assess safety of website from liquid injections

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2141]
### Overview
As a developer, we must investigate new potential sources of attack, so that we can defend against them.

### Action Items

- [x] Read up on [this article ](https://mrcoles.com/inlining-json-jekyll-liquid-template/)to understand liquid injections.
- [x] Investigate the sources of our various JSON data that will be displayed on our website.
- [x] Find out how easily it would be for an individual to inject html scripts into the JSON data either on purpose or by accident.
- [x] Conclude whether current measures are enough or if further action should be taken to escape data.
- [x] Look for other sources of external data besides JSON and investigate whether injections are possible.
- [x] Generate a report of your findings as a file in our drive (please put the link in this issue-comment).
  - [x] The report must specify the files, and a copy of the vulnerable lines, if any.
  - [x] It must also provide recommended changes to correct the vulnerability, if any.
- [x] If problems are found, write an issue for another developer to fix the code based on your recommendations.
  - [x] If the fix is too big/complex for one issue, the issue you write should be for another developer instructing them to write an epic and figure out how to break down your recommendations into manageable issues.

### Resources/Instructions
[Inlining JSON in a Jekyll Liquid Template](https://mrcoles.com/inlining-json-jekyll-liquid-template/)
[escape – Liquid template language](https://shopify.github.io/liquid/filters/escape/)
[data directory](https://github.com/hackforla/website/tree/gh-pages/_data)
#2139

**Comment by JessicaLucindaCheng** [comment]
@tamara-snyder 
At the time you self-assign an issue, make sure to write in a comment the following:
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"

**Comment by tamara-snyder** [comment]
@JessicaLucindaCheng Thanks for reminding me!

Availability this week: 4 hours
ETA: Three weeks from now (April 10, 2022)

**Comment by tamara-snyder** [comment]
Progress: I've read up on how Liquid injections can occur and located files where data is read from JSONs on the site and whether they use uri_escape. I still need to look through all the JSON data and gain a clearer understanding of how it is used on the site.
Blockers: None
Availability: 4 hours
ETA: April 10, 2022

**Comment by JessicaLucindaCheng** [comment]
@tamara-snyder 
Please give a progress report in a comment in this issue. See what you need to include in your progress report and more information in [section 2.5 Reporting progress on your issue in CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#25-reporting-progress-on-your-issue)

**Comment by tamara-snyder** [comment]
@JessicaLucindaCheng Oh my goodness, how time flies! So sorry about that. I will write an update now.

**Comment by tamara-snyder** [comment]
Progress: I've checked everywhere that JSON data is used on the site. Everything is covered by uri_escape except for a few spots, and it looks like those render data from an already escaped object (I plan on double-checking this because I'm a little confused right now). As far as I can tell from what I've been reading, since we're not dealing with any HTTP, there's not really any other way for an attack to get through. I'm definitely planning on doing more testing to be sure, though.
Blockers: Just a question: The only content in the external data folder appears to be JSON, which I've already checked. Is there anything else I should be looking for in regards to external data? Thank you!
Availability: 4 hours
ETA: Tuesday, April 12, 2022

**Comment by tamara-snyder** [comment]
Progress: Just need to finish my write-up. Had some interviews this week, so I didn't have as much time to work on this issue as originally anticipated.
Blockers: None
Availability: 3 hours
ETA: Tuesday, April 19, 2022

**Comment by tamara-snyder** [comment]
@hackforla/website-merge

Here it is! An assessment of [Liquid injection vulnerabilities on our site](https://docs.google.com/document/d/1aJxb7KPL4zQKL1XUR8mwzP4tY6c3m223OpDmhX9MmEg/edit#). I'm quite new to security-related things, so any and all feedback is welcome.

Thanks!

**Comment by JessicaLucindaCheng** [comment]
Availability: 3 hours
Review ETA: Sat, Apr 23, 2022

**Comment by JessicaLucindaCheng** [comment]
@tamara-snyder Good job on the write-up. It looks good. I just wrote a couple of comments in the Google Doc.

Also, I added an Action Item to the issue, which I think is needed for having another developer fix the code based on your recommendations. (Let me know if my Action Item is confusing or unclear because I wasn't sure how to word it.)

**Comment by Sparky-code** [comment]
Reviewing:
ETA 4/26-27 EOD
Avail: 2hrs

**Comment by Sparky-code** [comment]
Good Morning @tamara-snyder Write up looks good, I really don't know much about liquid so it was cool to learn some things. I added a couple comments that might be helpful for organization / clarification but over all, great job!

**Comment by tamara-snyder** [comment]
Progress: I need to make updates according to the feedback in the Google doc.
Blockers: None
Availability: Monday morning, 2 hours (traveling this weekend)
ETA: 05/03/2022

**Comment by tamara-snyder** [comment]
@Sparky-code @JessicaLucindaCheng Thank you both for your feedback on this doc! I've edited it based on your comments and left a clarification question for Devin. Would love to get a re-review when you get the chance.

**Comment by Sparky-code** [comment]
@tamara-snyder Sounds great, I'll take a look in the timeframe below
Avail: 1-2hrs
ETA: 5/18-19 EOD

**Comment by tamara-snyder** [comment]
@Sparky-code @JessicaLucindaCheng I believe I have resolved Devin's last comment. If you get a chance, a final review of the doc would be helpful. In the meantime, I can get to work writing the issues to make these fixes. Realistically, that will probably be done next week.

**Comment by Sparky-code** [comment]
@tamara-snyder looks great! Reads very clearly now. 👍

**Comment by JessicaLucindaCheng** [comment]
@tamara-snyder Sorry for the delay in reviewing your write up again. Everything looks good now. The write up is clear and concise. Good job.

**Comment by tamara-snyder** [comment]
Progress: Just need to write the issues. Haven't had time this week and I'm traveling the next couple days, so will work on this next week.
Blockers: None
Availability: 3 hours
ETA: Friday, June 10, 2022

**Comment by tamara-snyder** [comment]
- Progress: I've created https://github.com/hackforla/website/issues/3257 to resolve my findings.
Blockers: Now I just need someone to review it!
Availability: 1 hour
ETA: Thursday, June 23

**Comment by tamara-snyder** [comment]
My issue has been reviewed, edited, and approved by two people, so I am closing this issue.
