### ISSUE TITLE
Migrate Wins Data: Create both AF and KVF data structure

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2145]
### Overview
As a developer, to turn the wins card into a reusable component, we must first be able to generate a wins-data.json file of a more specific format than our current one. For this issue, we will create a new file with a more specific format for our repo in preparation for a data migration. This issue is part of a series that aims to migrate us to the more specific format.

### Action Items

- [x] Read the resources/instructions below to understand your task.
- [x] Ask the project director for permissions to view the apps script.
- [x] Learn how the apps script generate the AF file in our code base.
- [x] Have the code generate the KVF version _**in addition to**_ the AF version. (if possible!)
  - [x] To follow best data practices, in this KVF version, make sure that only data that is used is generated. If any data is not needed, do not include that data.
- [x] Write instructions in this issue on how to clean up the code to stop generating the AF version.
  - [x] Attach a link to these instructions on an action item on #2147  
- [x] As part of the PR for this issue, change the current KVF file to the newly generated KVF file.
- [x] Release dependency on #2146

### Resources/Instructions
Currently we have two json files for wins: [_wins-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/_wins-data.json) and [wins-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/wins-data.json). The former will henceforth be called KVF (for key-value file) and AF (for array file). AF is generated daily from a script on google while KVF appears to be an older, dysfunc version. The format in the KVF version, however, is much friendlier to formatting in liquid syntax. Therefore, we need to incrementally port our codebase to use the KVF version of the data and remove the AF version we currently use. This will be done in multiple steps:

1. Have the apps script generate both AF and KVF version.
2. Migrate all uses of AF to KVF.
3. Have the apps script stop generating the AF version.
4. Delete the AF version from our repo since it is now unused.

For this issue, we are doing step 1.

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art Is this required in order for the page to show up on the new homepage design. If it is the milestone will be higher.  please let me know and then re-add the ready for milestone label.

**Comment by Aveline-art** [comment]
@ExperimentsInHonesty This is not required for the homepage redesign (HPR), technically. For the HPRe, I had made a new static file (this file is not updated in real time) with the correctly formatted data, so as long as the HPRe wins card do not need the latest wins updates, then we are good.

**Comment by macho-catt** [comment]
Progress: Got access to google app script
Blockers: N/A
Availability: 5 hours
ETA: 2 weeks
Pictures: N/A

**Comment by macho-catt** [comment]
Progress: I have a working prototype of creating a KVF from google app script and updating a github repo. This can be implemented pretty easily.

Blockers: How to implement our API key in Google App Script #1980

**Comment by macho-catt** [comment]
Same as last week.

Progress: I have a working prototype of creating a KVF from google app script and updating a github repo. This can be implemented pretty easily.

Blockers: How to implement our API key in Google App Script #1980. I have a demo tonight to present during the backend meeting.

**Comment by macho-catt** [comment]
Progress: I have a working prototype of creating a KVF from google app script and updating a github repo. This can be implemented pretty easily.

Blockers: Need to write documentation for #1980 then implement the change for token

**Comment by macho-catt** [comment]
Blockers: Need to finish documentation for #1980, then transfer wins responses to admin drive

**Comment by macho-catt** [comment]
This is completed
