### ISSUE TITLE
Migrate Wins Data: Migrating from AF to KVF data structure

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2146]
~~### Dependency~~
~~#2145~~

### Overview
As a developer, to turn the wins card into a reusable component, we must first be able to generate a wins-data.json file of a more specific format. This issue is part of a series that aims to migrate us to the more specific format.

### Action Items

- [x] Read the resources/instructions below to understand your task.
- [x] Find areas in our codebase where we are using the AF version of the file (currently it is only the [wins-page](https://www.hackforla.org/wins/), but that might change by the time this issue is assigned).
- [x] Change all uses of the AF version to the KVF version.
- [x] Change code as needed to ensure the website still functions the same way. This means there are no visual changes to the website.
- [x] Release dependency on #2147

### Resources/Instructions
[wins-page](https://www.hackforla.org/wins/)

Currently we have two json files for wins: [_wins-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/_wins-data.json) and [wins-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/wins-data.json). The former will henceforth be called KVF (for key-value file) and AF (for array file). AF is generated daily from a script on google while KVF appears to be an older, dysfunc version. The format in the KVF version, however, is much friendlier to formatting in liquid syntax. Therefore, we need to incrementally port our codebase to use the KVF version of the data and remove the AF version we currently use. This will be done in multiple steps:

1. Have the apps script generate both AF and KVF version.
2. Migrate all uses of AF to KVF.
3. Have the apps script stop generating the AF version.
4. Delete the AF version from our repo since it is now unused.

For this issue, we are doing step 2.

**Comment by macho-catt** [comment]
Progress: I have an idea of what I need to remove so we can completely transfer to the new file
    Blockers: None
    Availability: 2 hrs
    ETA: Next week
    Pictures: n/a
