### ISSUE TITLE
Retrieve list of successful brigades with donor/sponsor pages

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#215]
### Overview
List of successful brigades with donor/sponsor pages

### Action Items
Retrieve list of successful brigades with donor/sponsor pages. This will serve as reference for the HFLA Website buildout of a donor/sponsor website section.

### Resources/Instructions
https://www.codeforamerica.org

**Comment by ExperimentsInHonesty** [comment]
Here is the [brigade budget spreadsheet](https://docs.google.com/spreadsheets/d/1DODGZyLItHJrvzJEmznHzYXh3pqHvPgTnNRnE1jokF4/edit?usp=sharing)
