### ISSUE TITLE
Update Contribution File to add PR to Project Board

### ISSUE THREAD

**Issue by adrian-zaragoza** [hackforla/website#2151]
### Overview
We need to add instructions  to add pull requests to the Project Board in order for PMs to be able to monitor pull requests.

### Action Items
- [ ] Add the sentence: "On the right sidebar, in Projects, click the gear and assign Project Board to the pull request."
at the end of this paragraph
![image](https://user-images.githubusercontent.com/77212035/130304822-a1777e28-e157-45b6-be6c-4b249195a8ff.png)

### Resources/Instructions
Update [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)

**Comment by Aveline-art** [comment]
@adrian-zaragoza Don't forget to also add your issue to the project board!

**Comment by adrian-zaragoza** [comment]
@Aveline-art Thanks for the tip! I added Project Board!
