### ISSUE TITLE
Refactor JS: Delete unused hotjar code

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2153]
### Overview
We need to remove the script tag containing Hotjar tracking details so that we remove code unnecessary code from the codebase.

### Action Items
- [x] Review the notes below to understand recent changes to our architecture
- [x] Locate the hotjar script in [head.html](https://github.com/hackforla/website/blob/gh-pages/_includes/head.html)
- [x] Delete the script
- [x] Ensures the website still runs as is
  - [x] Be sure to examine the console output before and after your changes **_in [localhost](http://localhost:4000/)_** to make sure something mysterious does not occur. 
  - [x] If any mysterious errors happen from the console output, attempt to fix it, or ask someone to help, if needed.

### Resources/Instructions
[head.html](https://github.com/hackforla/website/blob/gh-pages/_includes/head.html)
[localhost](http://localhost:4000/)

#### Architecture Notes

The idea behind the refactor is to get all of our website's JS code into an organized, consolidated state. Currently, we want our JS files to exist in our [assets/js ](https://github.com/hackforla/website/tree/gh-pages/assets/js)directory with these specifications:

- In the main js directory, the js files should ideally have names corresponding to a related .html page (for example, updates.js should connect to updates.html).
- In the elements sub-directory, the js fjiles should correspond to code needed for our [design system elements ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)to function.
- In the utility sub-directory, the js files represent reusable code that can be used in multiple files. If any js code is reused, they belong in utility, and called in a separate file in the main directory.

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by adam-abundis** [comment]
@ExperimentsInHonesty Are any teams using Hotjar (tracking users interactions) for the Hack for LA website?

**Comment by Aveline-art** [comment]
@abuna1985 hotjar is currently unused and some adblockers and browsers flags or disables it. I have spoken with @ExperimentsInHonesty and the best course of action is to remove it.

**Comment by adam-abundis** [comment]
@Aveline-art Thank you. I'm sure we have talked about this before. Just confirming.
