### ISSUE TITLE
Create a copy button element for our website

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2154]
### Overview
As a developer, we would like to have a design for copy buttons in our [design system ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3).

### Action Items

- [ ] Read below to get a sense of the dev's team preference for a copy button.
- [ ] Create a copy button for our design system.
- [ ] Go over designs with the dev team to edit as necessary.

### Resources/Instructions
[Current copy button](https://alyssabenipayo.github.io/website/guide-pages/github-issues)(please scroll to the bottom)
[Tooltip explainer from w3schools](https://www.w3schools.com/bootstrap/bootstrap_tooltip.asp)
[Figma - Design System / Buttons](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4752%3A13)

From discussion with the dev team, they would like copy buttons that mimic the ones in [Carbon](https://www.carbondesignsystem.com/components/breadcrumb/code) or [Bootstrap](https://getbootstrap.com/docs/5.0/components/breadcrumb/) (meaning that a [tooltip ](https://getbootstrap.com/docs/5.0/components/tooltips/)indicates that the button has been clicked). This would also add tooltips to our arsenal of design elements, which the design team can reuse when designing our webpages!

<details>
<summary>Bootstrap copy button
</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/130363064-b397c960-d31d-449f-bc97-32c4b1f75675.png" width="600" length="300" />
<br>
</details>

<details>
<summary>Carbon Copy Button</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/130363072-fd594d72-719b-47fe-8eab-9a10e3ef05f9.png" width="600" length="300" />
<br>
</details>

<details>
<summary>Our copy button</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/130363101-a353e77e-2b92-438a-9223-1de9095aea2f.png" width="600" length="300" />
<br>
</details>

**Comment by ahoang94** [comment]
@kristine-eudey Upon browsing the [Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17291%3A106505), I found that a Copy button had been designed at some point. 

- I have gone ahead and revised the button to adhere to the design system's colors and as well as the minimum text size for accessibility.
- I also created a tooltip to be displayed once the Copy button is selected.

**Comment by ExperimentsInHonesty** [comment]
@ahoang94 @kristine-eudey question for ya'll - seems like the button for copying should be red instead of black to match other buttons on our site.  No?  Also, do we have an amount of time that we want the copied tool tip to be there?  Or does it go away when you move away from it with your cursor.

![image](https://user-images.githubusercontent.com/37763229/139603358-ccc56549-55ed-47e5-8294-7ca57fcca78d.png)

**Comment by kristine-eudey** [comment]
Hi @ExperimentsInHonesty and @ahoang94  I took a look at the context of the Design System pages in which this copy button will live, and based on what I saw there, along with reviewing the design system guidance I think the above button styling (light with dark hover state) is the best option. Some of my thinking behind this:

- The pages these will be used on will provide guidance on buttons, amongst other things. It will show buttons as examples, as the subject of description and guidance in many cases. For this reason, I think styling the Copy buttons in a more subdued way will help keep the hierarchy of content within the page more clear. If we go with the red buttons, there will be a long line of red buttons trailing down the right side of the page which will draw a lot of visual attention, drawing it away from the important main content we want people to be focusing on. To me it makes more sense for these copy buttons to act more like a support infrastructure, than as strong CTAs (which is how we intend for all the red buttons on our site to act). Styling them light vs red let's them act as support without distracting from the main content of the page. 

   Here you can see how the red buttons would zig-zag across the page if the copy buttons were also red. I think this would cause unhelpful distraction and cognitive load for the user:
   - ![Screen Shot 2021-11-01 at 4 10 57 PM](https://user-images.githubusercontent.com/16949503/139736884-2f6ea386-0347-45df-9f5d-1aa1127282d8.png)


- The Design System has guidance for a light button option, which the current design Anh linked to is following. My suggestion would be to stick with this button styling. 

![Screen Shot 2021-11-01 at 4 07 46 PM](https://user-images.githubusercontent.com/16949503/139736627-75a4eb45-9631-4db1-a5f5-fee64d208fe4.png)

**Comment by ahoang94** [comment]
@kristine-eudey @ExperimentsInHonesty 

I have no prior insight as to why the initial 'copy' button was designed the way that it was, but I think that Kristine's provided logic as to making it 'light' is sound. After all, these buttons aren't true CTAs, but rather tools that developers may choose to use at their discretion.

As to the length of time that the tooltip is displayed, my thought is to defer to the developers as they will be the end users and the feature is for their benefit.

**Comment by ExperimentsInHonesty** [comment]
I agree.  We will keep it as is designed.  Thanks @kristine-eudey @ahoang94
