### ISSUE TITLE
Complete refactor/standardization of all buttons within Communities of Practice/Program Areas Page

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2158]
### Overview
We need to refactor for buttons within the Home page from the recommendations in the CSS standardization spreadsheet (resource below) so that we have a consistent button appearance through the HfLA site.

**Note:** The buttons should have the same length and width after the changes. if it is not, please add CSS styling to make sure they match.

### Action Items
- [x]  Make the 3 recommended edits for the buttons from the spreadsheet below (2 files will be updated)
  

1.  - [x] Update **line 68** of `website/pages/communities-of-practice.html` with HTML from the `Reccomendation` column
2. - [x] Update **line 70** of `website/pages/communities-of-practice.html` with HTML from the `Reccomendation` column
3. - [x] Update **line 87** of `website/pages/program-areas.html` with HTML from the `Reccomendation` column

- [x] Confirm after the recommended edits that the `Action` of each button works as intended within the Communities of Practice/Join Us/Program Areas page
- [x] Confirm the button length/width within the page are the same after changes. If not refactor CSS (this can be accomplished with custom padding for the specific button element or length/width CSS properties)
- [x] Create a Pull Request with the proposed changes to the button

### Resources/Instructions
[Google Sheets - CSS Standardization Buttons](https://docs.google.com/spreadsheets/d/1n3va-1kwGOCTP4JaXpL3TjgvS_2RWDkurb8PyCJSp-0/edit?usp=sharing)
#1921

**Comment by Zhu-Joseph** [comment]
Progress: Reviewing CSS sheet and code
Blockers: None
Availability: Random hours here and there
ETA: End of week

**Comment by adam-abundis** [comment]
@Zhu-Joseph I have added an action item. My apologies for not being clear with the issue. If you need assistance creating styling for the buttons, feel free to reach out to me.
