### ISSUE TITLE
Complete refactor/standardization of all buttons within Sitemap/Events Page

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2159]
## Overview
We need to refactor for buttons within the Home page from the recommendations in the CSS standardization spreadsheet (resource below) so that we have a consistent button appearance through the HfLA site.

### Action Items
- [x]  Make the 3 recommended edits for the buttons from the spreadsheet below (2 files will be updated)
  

1. - [x] Update **line 43** of `website/pages/sitemap.html` with HTML from the `Reccomendation` column
2. - [x] Update **line 65** of `website/pages/sitemap.html` with HTML from the `Reccomendation` column
3. - [x] Update **line 19** of `website/pages/events/left-col-content.html` with HTML from the `Reccomendation` column

- [x] Confirm after the recommended edits that the `Action` of each button works as intended within the Home page
- [x] Create a Pull Request with the proposed changes to the button

### Resources/Instructions
[Google Sheets - CSS Standardization Buttons](https://docs.google.com/spreadsheets/d/1n3va-1kwGOCTP4JaXpL3TjgvS_2RWDkurb8PyCJSp-0/edit?usp=sharing)
#1921

**Comment by tamara-snyder** [comment]
Progress: Requested access to the Google sheets document
Blockers: Awaiting access
Availability: Sunday evening and Tuesday, Thursday, and Friday mornings (EST)
ETA: Should have this done by the end of next week

Edit: I have access to the document now!

**Comment by tamara-snyder** [comment]
Progress: All tasks finished. I just need to create a pull request
Blockers: None
Availability: Thursday and Friday morning (EST)
ETA: Most likely by Thursday morning
