### ISSUE TITLE
Distill compliance requirements for corporate sponsorship

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#216]
### Overview
Distill rules/requirements for donor/sponsor solicitation

### Action Items
Distill rules/requirements for donor/sponsor solicitation, including legal, tax deduction, marketing/advertising, and donation match.

### Resources/Instructions

https://codeforsanfrancisco.org/sponsor/

https://www.councilofnonprofits.org/tools-resources/corporate-sponsorship

https://www.adlercolvin.com/revenue-generating-activities-of-charitable-organizations-legal-issues/

https://www.thebalancesmb.com/nonprofit-corporate-sponsors-2502063

https://www.classy.org/blog/corporate-sponsorships-for-nonprofits-the-basics/

**Comment by ExperimentsInHonesty** [comment]
Code for America is our fiscal sponsor.  This issue is closed
