### ISSUE TITLE
Fix new wins submission notification

### ISSUE THREAD

**Issue by sheltoG** [hackforla/website#2161]
### Overview
We need to receive one notification for every win submitted so that product knows what to review.

### Action Items
[ ] Confirm we are receiving two notifications for every win submission
[ ] If we are, identify why it is happening and fix the issue 

### Resources/Instructions
See the last two notifications we received #2142 & #2143

**Comment by macho-catt** [comment]
This is fixed since in the tests I've done we only get one issue creation per google form submission.

**Comment by macho-catt** [comment]
closing as my recent tests on the admin drive have generated one notifications each
