### ISSUE TITLE
Update project profile: GreenEarthOS update overview

### ISSUE THREAD

**Issue by sobe-an** [hackforla/website#2162]
### Overview
We need the update the greenearthos project file so that it shows the correct information for the project.
This is also a part of the effort to standardize pdf files as per #2211

### Action Items
- [x] Change the link to the project overview so the pdf opens as a new tab
    - [x] Download a copy of GreenEarthOS's overview [pdf ](https://github.com/hackforla/product-management/blob/master/project-one-sheets/GreenEarthOS-One-Sheet.pdf)and put it in [/assets/pdfs](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
    - [x] Change the 'Overview' link for the [markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/green-earth-os.md) to point to the pdf file living under /assets/pdfs
    - [x] Ensure that the links in both the [project page](https://www.hackforla.org/projects/) and the project's [dedicated page](https://www.hackforla.org/projects/green-earth-os) open the pdf file properly after the change
- [x] Update Bonnie's GitHub link URL so that it does not look like this ([see image](https://github.com/hackforla/GreenEarthOS/issues/3#issuecomment-903319935))
- from: https://avatars.githubusercontent.com/experiementsinhonesty
- to:  https://avatars.githubusercontent.com/experimentsinhonesty
- [x] confirm that link to pdf resolves, and add screen shots to this issue, then Post a message on GreenEarthOS's issue @ mentioning the assignee to let them know its ready to be looked at with a link to your comment with the screenshot.

### Resources/Instructions
https://github.com/hackforla/website/blob/4a5807c3faf252b4c271da880cbe62a83de5466b/_projects/green-earth-os.md#L1-L59
https://github.com/hackforla/GreenEarthOS/issues/3

**Comment by macho-catt** [comment]
@abuna1985 @ExperimentsInHonesty @sobe-an I was wondering if I can rewrite the action item for the pdfs part here to comply with the action item I am trying to accomplish for #2211
Basically standardizing how pdf files open in the website so that it just opens directly in the browser as a new tab, instead of opening it as part of a github page.

My other option would be to create an issue that is dependent on this, but I feel like it's too small and simple of an issue that just modifying the action items here would be the easiest option.

**Comment by adam-abundis** [comment]
@macho-catt I am good with rewriting the issue action item on this issue to reflect standardizing the pdf view.

**Comment by macho-catt** [comment]
Updated the post to be in line with #2211

**Comment by adrian-zaragoza** [comment]
Hi @sobe-an , the screenshots of the fixes are below. I will be creating a pull request for the changes.

<details>
<summary>Bonnie's GitHub Link Update</summary>

![image](https://user-images.githubusercontent.com/77212035/138023581-0856f46e-87a7-47e8-b10d-e668f7e70141.png)


</details>

<details>
<summary>Overview Link Update</summary>

![image](https://user-images.githubusercontent.com/77212035/138023648-0d4e2f2b-8c4a-49d9-8894-058b6620f005.png)


</details>
