### ISSUE TITLE
Remove "about" text from the credit page

### ISSUE THREAD

**Issue by sheltoG** [hackforla/website#2163]
### Overview
We need make sure the icons on the Credit page are correctly listing which images we are using on the site, where they are used and where they came from.
 
### Action Items
- [ ] remove the reference to the About page (the icon on the about page is a different icon), on the credits page, under care icon, after "used in:"

 ### Resources/Instructions
Credit page URL: https://www.hackforla.org/credits/
location of page in our code /pages/credits.html

#### you probably don't need these, but jus in case
Prior PR that added the content to the page #2093 
[Figma-credits page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1074%3

**Comment by ExperimentsInHonesty** [comment]
Hi @sheltoG 

Here is what you put for the issue

> ### Overview
> We need to remove the About from the `Used in` section under the care icon on the credits page since it is a different icon on the About page.
> 
> ### Action Items
> [ ] Design needs to find the proper image for the following page: [](https://www.hackforla.org/about/#platform)
> [ ] On the credits page, remove the word about from the care icon
> 
> ### Resources/Instructions
> #2093 

Here is what I changed it to 

> ### Overview
> We need make sure the icons on the Credit page are correctly listing which images we are using on the site, where they are used and where they came from.
>  
> ### Action Items
> [ ] remove the reference to the About page (the icon on the about page is a different icon), on the credits page, under care icon, after "used in:"
> 
>  ### Resources/Instructions
> Credit page URL: https://www.hackforla.org/credits/
> location of page in our code /pages/credits.html
> 
> #### you probably don't need these, but jus in case
> Prior PR that added the content to the page #2093 
> [Figma-credits page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1074%3A0)

I made another issue for the other item #2169 using the following labels:
role: design
p-feature: Credit
p-feature: About Us

> ### Overview
> We need make sure the icons on the Credit page are correctly listing which images we are using on the site, where they are used and where they came from.
>  
> ### Action Items
> - [ ] Please find the hand and heart image next to Giving on the [about page under platform](https://www.hackforla.org/about/#platform) and add the details to the Figma for the credit file and provide details for development:
>   - [ ] Name: 
>   - [ ] Used in: About
>   - [ ] Artist: 
>   - [ ] Provider
> 
>  ### Resources/Instructions
> In the past this image was improperly conflated with a similar hand image - see Prior PR #2093 
> [Figma-credits page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1074%3A0)
