### ISSUE TITLE
Complete refactor/standardization of all buttons within Join Us Page

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2165]
### Overview
We need to refactor for buttons within the Home page from the recommendations in the CSS standardization spreadsheet (resource below) so that we have a consistent button appearance through the HfLA site.

### Action Items
- [x]  Make the 4 recommended edits for the buttons from the spreadsheet below (1 files will be updated)
  

1.  - [x] Update **line 64** of `website/pages/join-us.html` with HTML from the `Reccomendation` column
2.  - [x] Update **line 78** of `website/pages/join-us.html` with HTML from the `Reccomendation` column
3.  - [x] Update **line 80** of `website/pages/join-us.html` with HTML from the `Reccomendation` column
4.  - [x] Update **line 82** of `website/pages/join-us.html` with HTML from the `Reccomendation` column

- [x] add the follow CSS code on line 39 of `website/_sass/elements/_buttons.scss`
  ```
   .btn--default {
     align-items: center;
    display: flex; 
    justify-content: center;
    margin: 5px 0;
  }
  ```
- [x] add `.btn--default` class to line 64, 78, 80, and 82 of `website/pages/join-us.html` (within the `<a>` tag
- [x] Confirm after the recommended edits that the `Action` of each button works as intended within the Communities of Practice/Join Us/Program Areas page
- [x] Create a Pull Request with the proposed changes to the button

### Resources/Instructions
[Google Sheets - CSS Standardization Buttons](https://docs.google.com/spreadsheets/d/1n3va-1kwGOCTP4JaXpL3TjgvS_2RWDkurb8PyCJSp-0/edit?usp=sharing)
Link to the entire audit: #1921

**Comment by mehmehmehlol** [comment]
1. Progress: I have finished all the requirements on the issue and have created a pull request. 
2. Blockers: The buttons did not look the same after refactoring. Details in the pull request.
