### ISSUE TITLE
Find icon author

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2169]
### Overview
We need make sure the icons on the Credit page are correctly listing which images we are using on the site, where they are used and where they came from.
 
### Action Items
- [x] Please find the hand and heart image next to Giving on the [about page under platform](https://www.hackforla.org/about/#platform) and add the details to the Figma for the credit file and provide details for development:
  - [x] Name: 
  - [x] Used in: About
  - [x] Artist: 
  - [x] Provider

 ### Resources/Instructions
In the past this image was improperly conflated with a similar hand image - see Prior PR #2093 
[Figma-credits page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1074%3A0)

**Comment by ahoang94** [comment]
@kristine-eudey The correct icon author has been sourced and the information has been added to the Figma file.

![Screen Shot 2021-08-24 at 9 46 43 PM](https://user-images.githubusercontent.com/85914721/130728186-ed14e012-2d8c-4de1-9fac-37964d893e93.png)

**Comment by kristine-eudey** [comment]
@ahoang94 thanks! The design portion of this issue has been completed.

**Comment by kristine-eudey** [comment]
@abuna1985 design portion of this issue is complete, please make development issue. Thank you!

**Comment by adam-abundis** [comment]
@kristine-eudey #2356 has been created to add an icon to the Credits page. Moving this issue to the `Done` column
