### ISSUE TITLE
Add font link to head.html file

### ISSUE THREAD

**Issue by adrian-zaragoza** [hackforla/website#2170]
### Overview
Even though the font is set as "Roboto" in the [typography scss file](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_typography.scss) the font is not Roboto on actual site.  The roboto font is listed in the figma file. This font issue is affecting all the text in the site.

### Action Items
- [x] Add the links below to the head.html [file](https://github.com/hackforla/website/blob/gh-pages/_includes/head.html) inside the head tags.

```
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
```

### Resources/Instructions
[head.html](https://github.com/hackforla/website/blob/gh-pages/_includes/head.html)

<details>
    <summary>Before - Screenshot of the Home page with sans-serif font</summary>
     <br>
     <img src="https://user-images.githubusercontent.com/21162229/130679114-e65ab13d-5119-44b9-b7fd-7907716a5330.jpg" 
 alt="Hack for Sans-Serif"/>
</details>

<details>
    <summary>Expected - Screenshot of the Home page with Roboto font</summary>
     <br>
     <img src="https://user-images.githubusercontent.com/21162229/130678712-d89d0f6f-fb6c-4f63-a262-41553df27d05.jpg" alt="Hack for LA Roboto" />
</details>

**Comment by adam-abundis** [comment]
@adrian-zaragoza Thank you for making this issue. I have some edits I would like you to make so I can present it to the product management team. Thank you.


1. Please **remove** the following labels  in the right-hand menu under `Labels` (the gear icon):  
- `Feature Missing`
- `role missing` 

2. Now **add** the following labels  in the right-hand menu under `Labels`  (the gear icon):  
- `role: front-end` 
- `Feature: Standard` 
- `bug`

3. Can you add `The Project Board` in the right-hand menu under `Projects` (the gear icon). Once the project board is connected confirm it is in the `New Issue Approval` column (it should be put in the column by default).

4. Turn your action items into a checkbox like so
```- [ ] Add the links below to the head.html file inside the head tags.```

5. not sure why the Figma resources are on here. The goal of resources is to provide some starting points. So let's remove the following resources
- [Figma Home](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=13607%3A93001)
- [Figma Projects](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=532%3A1455) 

6. We can add the following links to the `Resources` section
- [head.html](https://github.com/hackforla/website/blob/gh-pages/_includes/head.html) ` [head.html](https://github.com/hackforla/website/blob/gh-pages/_includes/head.html)`
- let's show a screenshot of the homepage with the default (sans-serif) - copy the code block below and add it to `Resources`
```
<details>
    <summary>Before - Screenshot of the Home page with sans-serif font</summary>
     <br>
     <img src="https://user-images.githubusercontent.com/21162229/130679114-e65ab13d-5119-44b9-b7fd-7907716a5330.jpg" 
 alt="Hack for Sans-Serif"/>
</details>
```
- let's show a screenshot of the homepage with the Roboto - copy the code block below and add it to `Resources`
```
<details>
    <summary>Expected - Screenshot of the Home page with Roboto font</summary>
     <br>
     <img src="https://user-images.githubusercontent.com/21162229/130678712-d89d0f6f-fb6c-4f63-a262-41553df27d05.jpg" alt="Hack for LA Roboto" />
</details>
```
It should look like this:

<details>
    <summary>Before - Screenshot of the Home page with sans-serif font</summary>
     <br>
     <img src="https://user-images.githubusercontent.com/21162229/130679114-e65ab13d-5119-44b9-b7fd-7907716a5330.jpg" 
 alt="Hack for Sans-Serif"/>
</details>

<details>
    <summary>Expected - Screenshot of the Home page with Roboto font</summary>
     <br>
     <img src="https://user-images.githubusercontent.com/21162229/130678712-d89d0f6f-fb6c-4f63-a262-41553df27d05.jpg" alt="Hack for LA Roboto" />
</details>

**Comment by adrian-zaragoza** [comment]
Hi @abuna1985 Thank you for the recommendations! I have updated this issue with the recommended action items. I've also verified that this issue is now in the `New Issue Approval` column in the project board.
