### ISSUE TITLE
Change mobile menus on Toolkit page

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2171]
### Overview
We need to adjust the mobile menus on the Toolkit page so that users are only able to select a single practice area at a time in order to simplify development. We also need to adjust styling so that the dropdown menus match those used elsewhere on the site in order to follow our design system and provide a consistent user experience. 

### Action Items

- [x] Duplicate current Toolkit mobile dropdown menu in Figma in order to work on a new copy.
- [x] Remove checkboxes so that user only has ability to sort by one practice area at a time. 
- [x] Remove red background from selected practice area so that menu matches other mobile dropdowns used across the site, for example those here on the [Projects](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=9335%3A80823) page
- [x] Create designs showing each: 
   - [x] The initial/empty state of the dropdown when a users first lands on the page
   - [x] The dropdown menu a user selects from
   - [x] The active state when a user selects a practice area to sort by
  
The current Figma design that requires the above listed changes:
<img width="516" alt="Screen Shot 2021-08-24 at 10 04 30 AM" src="https://user-images.githubusercontent.com/16949503/130631073-c7d63caa-c51b-4e1a-b75b-eab866a3b4be.png">

### Resources/Instructions
Figma: [Design System / Dropdown menus](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4752%3A13)
Figma: [Toolkit Page / Mobile](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8759%3A78628)

**Comment by ktlevesque19** [comment]
Progress: Just started
Blockers: None at this time
Availability: Will work on this today and evenings this week
ETA: Will be complete by Thursday 10/14

**Comment by ktlevesque19** [comment]
Just completed this. @kristine-eudey I did have a quick question on this! The reference style seemed to be drop down menus that had more of a tab header. I completed with the wider menu type, which was in the reference but also included a tab version on the side. It also felt like it might help to have a gray color bar when pressed before the menu changes over to the selection since we no longer have the checkbox to visually confirm a click? Feels like it may be nice to give some indication of a selection even if it's quick. Thank you!

<img width="468" alt="Screen Shot 2021-10-17 at 1 23 26 AM" src="https://user-images.githubusercontent.com/84823624/137618423-70f5d6b1-e744-4a13-aa7e-d49e872a3299.png">

**Comment by kristine-eudey** [comment]
Hi Kristin, sorry for the delay in following up on your question! I think the gray box for pressed state is great and let's go for the version circled below, rather than the one on the right which matches the reference style on the Projects page. In looking back at that menu, I think it was made larger to accommodate one menu item that was very long and necessitated the larger box. I think keeping it all the same width here will be cleaner. I'll denote this on the Figma for the developers and close the issue, thanks for your work on it! 

<img width="468" alt="kristin's issue" src="https://user-images.githubusercontent.com/16949503/138353016-1f39c103-869f-4be0-be88-11014c4c333a.png">

**Comment by kristine-eudey** [comment]
Design portion of this issue is completed and can be found here: [Figma - Toolkit Mobile](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17125%3A107543) This is now ready for a front-end issue to be created.

**Comment by adam-abundis** [comment]
Created #2391 for the dev implementation of the toolkit mobile menu design
