### ISSUE TITLE
Refactor JS: Clean toolkit page script

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2172]
### Overview
As a member of the website development team, Javascript code is much more maintainable and reusable if they exist in a separate folder rather than embedded with html. This issue is to clean up the script on the toolkit page.

### Action Items
- [x] Review the notes below to understand recent changes to our architecture
- [x] The [toolkit page ](https://www.hackforla.org/toolkit/)contains 2 scripts. The top one will be called ST (for script top) and the bottom SB (for script bottom).
- [x] ST is to be moved into the [assets/js](https://github.com/hackforla/website/tree/gh-pages/assets/js) directory, in a js file named toolkit.js.
  - [x] This script has a known bug in that if the nav bar links are entered through the url, the page does not show the associated filtered page. For example, [this link ](https://www.hackforla.org/toolkit/#Development)will not lead to showing development only results, but all results.
  - [x] Change the JS code to fix this bug. It should work similar to [this](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events).
- [x] SB is to be deleted, and its function refactored into css or scss code instead.

### Resources/Instructions
[assets/js](https://github.com/hackforla/website/tree/gh-pages/assets/js)
[toolkit page](https://www.hackforla.org/toolkit/)
[toolkit.html](https://github.com/hackforla/website/blob/gh-pages/pages/toolkit.html)
[toolkit/#Development page bug](https://www.hackforla.org/toolkit/#Development)
[Github docs sample link](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events).

#### Architecture Notes

The idea behind the refactor is to get all of our website's JS code into an organized, consolidated state. Currently, we want our JS files to exist in our [assets/js ](https://github.com/hackforla/website/tree/gh-pages/assets/js)directory with these specifications:

- In the main js directory, the js files should ideally have names corresponding to a related .html page (for example, updates.js should connect to updates.html).
- In the elements sub-directory, the js fjiles should correspond to code needed for our [design system elements ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)to function.
- In the utility sub-directory, the js files represent reusable code that can be used in multiple files. If any js code is reused, they belong in utility, and called in a separate file in the main directory.

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by juliansmith0** [comment]
Availability for this week: 5 hours
My estimated ETA for completing this issue: Sunday, June 5, 2022

**Comment by Sparky-code** [comment]
@juliansmith0 Checking in to see if you are still working on this issue or if your availability has changed. Please add your ETA and availability. Thanks!

**Comment by ExperimentsInHonesty** [comment]
@juliansmith0 I don't see any activity on this issue, so I am going to unassign and put back into the prioritized backlog.  If you are still working on it, please reassign, move to in progress  and update the issue

**Comment by ericvennemeyer** [comment]
i. `Availability`: Weds 8/17 - 2hrs, Thurs 8/18 - 3hrs
ii. `ETA`: EOD Thursday, 8/18

**Comment by ericvennemeyer** [comment]
Hey hey, I was unable to work on this as I'd hoped yesterday, so I'm running a little behind. I will also be offline from now until Monday morning. Please see below for update.

i. `Progress`: Fixed the bug in ST, page is now correctly filtered when navbar links are entered as hashes in the URL. However, with my current solution there is a visible flicker on the page when all cards are loaded before being filtered. Would ideally like to find a prettier way to do this.
ii. `Blockers`: For SB, the issue requests refactoring into SCSS/CSS. Unfortunately, the style applied in SB is based on the conditional presence of a child element. Have done some research but there doesn't seem to be an easy way to select only a parent element that contains a specific child element in SCSS/CSS. Will research further next week.
iii. `Availability`: Flexible; 2-3hrs in total.
iv. `ETA`: EOD Friday 8/26

**Comment by ericvennemeyer** [comment]
**Update:**

All points in this issue have been addressed:
1. URL filtering bug has been fixed and ST refactored into it's own file in assets/js
2. Styling in SB has been refactored into _toolkit.scss

I did notice that there's an additional bug not mentioned in the original issue: when filtering the page via URL hash, the associated navbar link is not highlighted. For example, if I enter the URL with `#Development` at the end, the navbar link for `All` remains highlighted. Should I address this bug in this issue, or open a new issue?

**Comment by ExperimentsInHonesty** [comment]
There is a [comment from Eric](https://github.com/hackforla/website/issues/2172#issuecomment-1224382184).  Then some additional commits.  Did Eric take care of it in the PR that closed this issue? If yes, please note that in a comment, and move this to the done column.  If not, please create a new issue

**Comment by arpitapandya** [comment]
- Yes, #3483 closes this issue and is taken care of by Eric. The additional commits are because of the stale branch and later resolving merge conflicts. There is also another issue #3489 created (came up and discussed), and PR #3581  merged for that separately for removing the duplicate CSS selectors.
