### ISSUE TITLE
Project links with spaces are not read properly

### ISSUE THREAD

**Issue by blakes24** [hackforla/website#2175]
### Overview
The project link href tags need to be enclosed in quotes to avoid issues with URLs that may contain spaces.

### Action Items
- [x] In [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js) replace 
```javascript
${project.links.map(item => `<a href=${ item.url } rel="noopener" target='_blank'> ${ item.name }</a>`).join(", ")}
```
 with 
```javascript
${project.links.map(item => `<a href="${ item.url }" rel="noopener" target='_blank'> ${ item.name }</a>`).join(", ")}
```
- [x] Ensure that the links still work correctly

### Resources/Instructions
https://github.com/hackforla/website/blob/823a06c316bb621c505f5a8d6b1774d1c42adb9c/assets/js/current-projects.js#L414

The links appear on these pages:
[https://www.hackforla.org](https://www.hackforla.org)
[https://www.hackforla.org/projects/](https://www.hackforla.org/projects/)

**Comment by ghost** [comment]
I think the file that needs to be changed is current-projects.js not current-projects.html. Can someone confirm this?

**Comment by macho-catt** [comment]
@amnak1284 it's current-projects.html, line 427. It's written in liquid and not js.

**Comment by ghost** [comment]
@macho-catt  My scripts section looks like this

<img width="404" alt="Screen Shot 2021-11-11 at 11 19 51 AM" src="https://user-images.githubusercontent.com/16737379/141356466-c543460c-141e-4ba5-9d33-b74b2488637d.png">

**Comment by macho-catt** [comment]
@amnak1284 the issue is asking to update line 427, not the scripts section.

In particular, this line:
https://github.com/hackforla/website/blob/8a6df1dcd270c17403fa75c5842be9aa07ab3fa9/_includes/current-projects.html#L427

**Comment by blakes24** [comment]
@amnak1284 you're right. The issue was created before the javascript got moved to a separate file so the link in the resources section is to an old version of the file.

This is the line that needs to be updated:

https://github.com/hackforla/website/blob/823a06c316bb621c505f5a8d6b1774d1c42adb9c/assets/js/current-projects.js#L414

**Comment by macho-catt** [comment]
whoops, my mistake. Yes, @blakes24 and @amnak1284 are correct.
