### ISSUE TITLE
fix the wins expanded icon styling in tablet view

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#2176]
### Overview
We need to refactor the expanded wins cards in tablet view so we can have a consistent view of the wins icons within the wins card. 

This is a CSS problem that is a little harder than the average medium issue.

<details>
    <summary>Click here to see the current wins page card </summary>

![Screen Shot 2021-08-19 at 10 25 40 PM](https://user-images.githubusercontent.com/53061723/130718321-de8b86ea-fb61-4abe-bb27-32137e4de4c9.png)

</details>

Here is the figma (for mobile. does not have tablet view)
<details>
    <summary>click for screenshot</summary>

![Screen Shot 2021-08-24 at 7 50 34 PM](https://user-images.githubusercontent.com/53061723/130718368-7db171ed-b951-4cf2-b3d5-8662cbc5fc36.png)

</details>

### Action Items
- [x] Figure how the icons are styled. 
    - which classes are associated with which styles and etc
- [x] rewrite a lot of the css for the icons so that it looks like the figma

### Resources
https://github.com/hackforla/website/blob/c6358c0698a5356b63a0d8e76f186f11e902f400/pages/wins/wins-card-template.html
https://github.com/hackforla/website/blob/c6358c0698a5356b63a0d8e76f186f11e902f400/_sass/components/_wins-page.scss
https://github.com/hackforla/website/blob/c6358c0698a5356b63a0d8e76f186f11e902f400/pages/wins/wins.html
- [Wins page Figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=9246%3A80729) 
- #2135

**Comment by adrian-zaragoza** [comment]
Progress: Researched the tablet classes, icons, and breakpoint variables. Reviewed figma file. 
Blockers: None.
Availability: I won't be available much this week to work on it. I will have more time on Monday.
ETA: Friday, Oct 8

**Comment by adrian-zaragoza** [comment]
Progress: Created a pull request with changes.
