### ISSUE TITLE
Create a wiki article to detail Github Actions

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2179]
### Overview
As a developer, it will be helpful to have a wiki article that details what the various github actions are that run for the website repository. This will also help when a developer needs to create a new action, or edit an existing action.

### Action Items
- [x] Learn the github actions that currently work on this repo
    - [x] The github actions live in this [directory ](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
    - [x]  Any accompanying javascript files for their corresponding github action live in this [directory](https://github.com/hackforla/website/tree/gh-pages/github-actions)
    - [x] Refer to the current running workflows [here](https://github.com/hackforla/website/actions)
- [x] Create a new wiki article that details the structure of the github actions [directory ](https://github.com/hackforla/website/tree/gh-pages/.github)and the accompanying js [directory](https://github.com/hackforla/website/tree/gh-pages/github-actions) based on the [new proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015) for restructuring github actions. Each action's purpose should be summarized and any important modules or info should be linked.
    - [x] Schedules (military time)
        - [x] Schedule Friday 0700
        - [x] Schedule Thursday 1100
        - [x] Schedule Daily 1100
    - [x] Linters
        - [x] Lint SCSS
    - [x] PR Trigger
        - [x] Add Linked Issue Labels to Pull Request
        - [x] Add Pull Request Instructions
    - [x] Issue Trigger
        - [x] Add Missing Labels To Issues
    - [x] WR - PR Trigger
        - [x] WR Add Linked Issue Labels to Pull Request
        - [x] WR Add Pull Request Instructions
    - [ ] WR - Issue Trigger
    - **Note: if there are additional github actions, please add them as well**
- [x] Properly style the article so the chronology and navigation links make sense
- [x] Add links to this newly created wiki from other wiki articles
    - [x] From the central wiki location ([here](https://github.com/hackforla/website/wiki))
    - [x] From the site architecture [wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)
    - [x] From the wiki sidebar

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[Creating a new wiki article](https://docs.github.com/en/communities/documenting-your-project-with-wikis/adding-or-editing-wiki-pages)
[Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)
[Other wikis for reference](https://github.com/hackforla/website/wiki)
[BETA GitHub Actions wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)

#### Additional resources:
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)
[GitHub GraphQL](https://docs.github.com/en/graphql)

**Comment by macho-catt** [comment]
As per @Aveline-art, the devs will have further discussion during our Thursday backend meeting (tomorrow) that may alter some details on github action conventions. Because of this, we want to hold off on adding the 'ready for milestone' label so we can further revise the Action Items after our meeting. Thanks.

**Comment by macho-catt** [comment]
We will have a proposal for how to refactor the current gh-action workflows to make them more manageable during the Thursday dev meeting. Afterwards, issues will be created to refactor the directory structure, and then this will be updated to reflect those changes.

**Comment by macho-catt** [comment]
Proposal can be found [here](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit?rtpof=true#gid=1231634015). Updating issue to reflect the new proposal.

**Comment by Aveline-art** [comment]
* Progress: Have not started.
* Availability: 5 hours
* ETA: By this weekend

**Comment by macho-catt** [comment]
Hi @Aveline-art, any updates on this? :) Thanks

**Comment by Aveline-art** [comment]
* Progress: Started the wiki page
* Blockers: Could not complete it due to a sudden personal problem. Cannot say when it will resolve.
* Availability: N/A
* ETA: N/A

**Comment by Aveline-art** [comment]
* Progress: Have not made progress being away for the week.
* Blockers: Nothing so far.
* Availability: 4 hours
* ETA: Probably next week

**Comment by Aveline-art** [comment]
The article first draft has been completed ([link](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)). Please give feedback here, so that further edits can be made! Please let me know if it is useful to everyone!

**Comment by macho-catt** [comment]
@Aveline-art I looked at the draft, and it looks good! Of course we're still in the process of moving stuff over, but the architecture is what we're aiming for. It is missing info on the scheduled triggers (in terms of how they will look under the .github directory and how they differ from normal triggers) and workflow run triggers (how it's different from normal triggers, why we do it and the security reasons behind it), but other than those it looks good to me.

**Comment by Aveline-art** [comment]
@macho-catt I wasn't too sure what to comment on for the scheduled triggers since the file does not exist in the architecture yet. Should it be added now, or later when the refactoring has reached that stage?

**Comment by macho-catt** [comment]
@Aveline-art  I believe in our discussion before we just decided to rename the current scheduled triggers to the times they trigger, then if we need to add new triggers on a specific time we either add them to existing triggers (if they make sense) or create a new workflow for the new scheduled time. Does that make sense? If so, we could add that info now.

**Comment by Aveline-art** [comment]
Alright, second draft is done! @macho-catt

**Comment by macho-catt** [comment]
@Aveline-art it looks good to me! Thank you for this :)
