### ISSUE TITLE
Create a Citizen engagement page layout

### ISSUE THREAD

**Issue by kevngaleu** [hackforla/website#2180]
### Overview
We need to create a template page for the program area Citizen engagement so that people can find the project related to this program area.

### Action Items
Development
- [x] Develop the Donate page based on the design in [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4947%3A26584) in the pink rectangle
- [x] Do not link the page to the website yet- this should remain an unlinked page for now, until the new home page is finished
- [x] Add header image to [Credits](https://www.hackforla.org/credits/) page

### Resources/Instructions
[How to Create a new HfLA website page](https://github.com/hackforla/website/wiki/How-to-create-a-page-on-the-HfLA-website)
[HfLA Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)
[Credit.yml file template](https://github.com/hackforla/website/wiki/credit.yml-file-template)

Design issue for the Citizen Engagement page https://github.com/hackforla/website/issues/1879

**Comment by Aveline-art** [comment]
@R-Tomas-Gonzalez Are you working on this issue? If so, please move it from the backlog to the in progress column. Thank you!

**Comment by R-Tomas-Gonzalez** [comment]
> @R-Tomas-Gonzalez Are you working on this issue? If so, please move it from the backlog to the in progress column. Thank you!

Moved! Thank you

**Comment by Aveline-art** [comment]
@abuna1985 Is this issue for a whole page? If so, it might prove easier to complete and review if the page is divided into multiple issues.

**Comment by R-Tomas-Gonzalez** [comment]
> @R-Tomas-Gonzalez
> 
> Please add update using the below template (even if you have a pull request). Afterwards, remove the 'To Update !' label and add the 'Status: Updated' label.
> 
> 1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
> 2. Blockers: "Difficulties or errors encountered."
> 3. Availability: "How much time will you have this week to work on this issue?"
> 4. ETA: "When do you expect this issue to be completed?"
> 5. Pictures: "Add any pictures of the visual changes made to the site so far."
> 
> If you need help, be sure to either: 1) place your issue in the developer meeting discussion column and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel.
> 
> You are receiving this comment because your last comment was before Tuesday, September 28, 2021 at 12:02 AM PST.

1. I have finished making this site today and have made a PR for it.
2. None. Needs review
3. Done with this issue. Sent in PR
4. Done.
5. None.

**Comment by ExperimentsInHonesty** [comment]
Hi!  @R-Tomas-Gonzalez  - I noticed that you did a pr which should have created the page on the site, can you tell me what the url of the page will be, so that I can see it (e.g., https://hackforla.org/citizen-engagement/)

**Comment by ExperimentsInHonesty** [comment]
@R-Tomas-Gonzalez I did not see a screenshot of the mobile view in this pr https://github.com/hackforla/website/pull/2324  did you do the break points for mobile too?

**Comment by R-Tomas-Gonzalez** [comment]
> Hi! @R-Tomas-Gonzalez - I noticed that you did a pr which should have created the page on the site, can you tell me what the url of the page will be, so that I can see it (e.g., https://hackforla.org/citizen-engagement/)

Hi Bonnie! Yes, https://hackforla.org/citizen-engagement is the endpoint to reach this page. However, the original merge in pull request #2324 was reverted due to issues mentioned by @macho-catt. The new pull request #2375 addresses the concerns linked in the former pr. I can add a mobile view preview to pull request #2324 if you'd like, or I can leave it be. I'll also message you on slack concerning this. Hope this is informative!
