### ISSUE TITLE
Refactor JS: Move script from projects.html to an external js file

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2182]
### Overview
As a member of the website development team, Javascript code is much more maintainable and reusable if they exist in a separate folder rather than embedded with html. For this issue, we are moving the script in [projects.html](https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html).

### Action Items
- [x] Review the notes below to understand recent changes to our architecture
- [x] Move the code to a new and appropriately named file in the appropriate directory.
- [x] Delete the script.
- [x] Call the newly made file in [projects.html](https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html).
- [x] Ensure that the site does not break.

### Resources/Instructions
[assets/js](https://github.com/hackforla/website/tree/gh-pages/assets/js)
[Projects page](https://www.hackforla.org/projects/)
[projects.html](https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html)
[How do I include liquid/global variables defined using Jekyll in a Javascript file?](https://stackoverflow.com/questions/58517425/how-do-i-include-liquid-global-variables-defined-using-jekyll-in-a-javascript-fi)

#### Architecture Notes

The idea behind the refactor is to get all of our website's JS code into an organized, consolidated state. Currently, we want our JS files to exist in our [assets/js ](https://github.com/hackforla/website/tree/gh-pages/assets/js)directory with these specifications:

- In the main js directory, the js files should ideally have names corresponding to a related .html page (for example, updates.js should connect to updates.html).
- In the elements sub-directory, the js fjiles should correspond to code needed for our [design system elements ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)to function.
- In the utility sub-directory, the js files represent reusable code that can be used in multiple files. If any js code is reused, they belong in utility, and called in a separate file in the main directory.

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by macho-catt** [comment]
Availability: 2 hours
ETA: by Sunday next week
