### ISSUE TITLE
Refactor JS: Delete unused code in project-filter.js

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2183]
### Overview
As a member of the website development team, Javascript code is much more maintainable and reusable if they exist in a separate folder rather than embedded with html. For this issue, the code in [project-filter.js ](https://github.com/hackforla/website/blob/gh-pages/assets/js/project-filter.js)will be removed, if verified to be unused.

### Action Items
- [x] Review the notes below to understand recent changes to our architecture
- [x] Verify that project-filter.js is not used at all
  - [x] One way to check might be to add console.log to its functions, and traverse the pages to see if the log is ever called.
  - [x] Your IDE might have a search function that can be used to quickly locate code (you are encourage to use online resources to find if said function exists)
  - [x] You can also remove the code and see if anything breaks.
  - [x] GitHub also tracks file history, which can help verify how the code was used and changed over time. You are also encouraged to use online resources to find the history tracker in GitHub's interface.
- [x] If not used: delete.
- [ ] If used: this issue can be closed.
- [x] Make sure that the website still runs and appears the same. No visual changes should be present.

### Resources/Instructions
[assets/js](https://github.com/hackforla/website/tree/gh-pages/assets/js)
[project-filter.js ](https://github.com/hackforla/website/blob/gh-pages/assets/js/project-filter.js)

#### Architecture Notes

The idea behind the refactor is to get all of our website's JS code into an organized, consolidated state. Currently, we want our JS files to exist in our [assets/js ](https://github.com/hackforla/website/tree/gh-pages/assets/js)directory with these specifications:

- In the main js directory, the js files should ideally have names corresponding to a related .html page (for example, updates.js should connect to updates.html).
- In the elements sub-directory, the js fjiles should correspond to code needed for our [design system elements ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)to function.
- In the utility sub-directory, the js files represent reusable code that can be used in multiple files. If any js code is reused, they belong in utility, and called in a separate file in the main directory.

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by JessicaLucindaCheng** [comment]
@Wny-Duong
At the time you self-assign an issue, make sure to write in a comment the following:
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"

**Comment by Wny-Duong** [comment]
Availability: 8 hours
ETA: Monday, 4/25.

Sorry about that! I thought the ETA was just for first issues and progress reports.
