### ISSUE TITLE
Complete refactor/standardization of all buttons within Wins Page

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2187]
## Overview
We need to refactor for buttons within the Home page from the recommendations in the CSS standardization spreadsheet (resource below) so that we have a consistent button appearance through the HfLA site.

**Note:** The buttons should have the same length and width after the changes. if it is not, please add CSS styling to make sure they match.

### Action Items
- [x]  Make the 1 recommended edits for the buttons from the spreadsheet below (1 files will be updated)
  
1. - [x] Update **line 5** of `website/pages/wins/wins-hero.html` with HTML from the `Reccomendation` column

- [x] Confirm after the recommended edits that the `Action` of each button works as intended within the Home page
- [x] Confirm the button length/width are the same after changes. If not add CSS (this can be accomplished with custom padding for the specific button element)
- [x] Create a Pull Request with the proposed changes to the button

### Resources/Instructions

https://hackforla.org/wins/
[Google Sheets - CSS Standardization Buttons](https://docs.google.com/spreadsheets/d/1n3va-1kwGOCTP4JaXpL3TjgvS_2RWDkurb8PyCJSp-0/edit?usp=sharing)
#1921

**Comment by adam-abundis** [comment]
@Zhu-Joseph I see you self-assigned this issue. It is still being reviewed and is in the `New Issue Approval` column. Feel free to check the [Prioritized Backlog Column](https://github.com/hackforla/website/projects/7#column-7198257) to see what issues are available.

**Comment by Zhu-Joseph** [comment]
> @Zhu-Joseph I see you self-assigned this issue. It is still being reviewed and is in the `New Issue Approval` column. Feel free to check the [Prioritized Backlog Column](https://github.com/hackforla/website/projects/7#column-7198257) to see what issues are available.

Hey Adam, got it! I will just check something else out!

**Comment by Sparky-code** [comment]
ETA: Wednesday 3/02/22 EOD
Avail: 1hr Tuesday 3/01, + Time needed on Wednesday while on call

**Comment by Sparky-code** [comment]
ETA: Friday 3/04/22 EOD
Blocker: Access to google sheets is restricted, waiting for access confirmation
Avail: Wednesday 7-9p PST, and same times through friday

**Comment by JessicaLucindaCheng** [comment]
@Sparky-code You should have access to the Google Sheet now, so I'm removing the "Status: Help Wanted" label. If you need help with something else, please let me know.
