### ISSUE TITLE
Adjust styling of Getting Started page

### ISSUE THREAD

**Issue by arghmatey** [hackforla/website#2193]
### Dependency

~#1619~

### Overview

We need to adjust the styling for the [Getting Started page](https://www.hackforla.org/getting-started) so that we can match the Figma Design for the Getting Started page.

### Action Items
- [x] Update width of **.info-icon** from `.75em` to `.875rem`
- [x] Update font-weight of **.getting-started-step-title-faq** from `500` to `700`
- [x] Update `height` of **.step-img-intro** to `max-height`

### Resources/Instructions
[New Getting Started page design in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=13%3A0)- on the right in purple rectangle)
[Link to PR this originated from.](https://github.com/hackforla/website/pull/2059) If interested, this includes more detailed notes.
[_getting-started-page.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_getting-started-page.scss)

**Comment by benrempel** [comment]
It seems the first 2 tasks have already been addressed and merged in an earlier PR.

For the 3rd task (.step-img-intro height), I'm running into a problem. I've set `height` to `max-height`. However, the "solidarity" image doesn't dynamically resize. See screenshots.

Any suggestions? I've tried setting `width` to `max-width` and then `100%` and neither worked. I noticed that the resolution for solidarity.png is much smaller than the other 4 images, could that matter?

<details>
<summary>Current website, narrow window</summary>

<img width="702" alt="Screen Shot 2021-09-07 at 3 00 25 PM" src="https://user-images.githubusercontent.com/5412677/132416802-0338c81a-147a-4dd2-b310-56c80bba1e51.png">
</details>

<details>
<summary>Current website, wide window</summary>

<img width="1276" alt="Screen Shot 2021-09-07 at 3 00 46 PM" src="https://user-images.githubusercontent.com/5412677/132416840-2851b181-036e-429b-8f6f-68f524318c26.png">
</details>

<details>
<summary>Local with change, narrow window</summary>

<img width="709" alt="Screen Shot 2021-09-07 at 3 00 33 PM" src="https://user-images.githubusercontent.com/5412677/132416821-5c7264d7-4e1b-4f50-95ad-2bdb5d09836d.png">
</details>

<details>
<summary>Local with change, wide window:</summary>

<img width="1280" alt="Screen Shot 2021-09-07 at 3 00 54 PM" src="https://user-images.githubusercontent.com/5412677/132416889-680e97e4-2ae7-4e76-b58d-1194ac3fee34.png">
</details>

**Comment by benrempel** [comment]
@arghmatey @macho-catt any suggestions? I'll try again myself, but you probably know CSS better than I do so I wanted to ask if anything looks obvious to you

**Comment by arghmatey** [comment]
@benrempel Sorry - I didn't see your first comment! I tried it out locally and it's working for me. Based on your last picture, it might not be applying correctly. Can you look at the style through Chrome Dev Tools and verify it's not returning an error?

**Comment by benrempel** [comment]
@arghmatey ah I misunderstood, I had set `height: max-height;` which is not valid. Now I see, I'm supposed to replace the property "height" with "max-height", so `max-height: 100px`

**Comment by arghmatey** [comment]
@benrempel I apologize - I should have written that action item much differently. Sorry to have held you up!
