### ISSUE TITLE
GitHub Actions: Delete Unused GHA

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2194]
### Overview
As a maintainer of the website, when assets are unused, they should be removed from the repo to keep things neat and tidy for the team. For this issue, we will be deleting the [update-comment-on-update-label.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/update-comment-on-update-label.yml) GHA, which is superseded by [add-update-label-weekly.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-update-label-weekly.yml)

### Action Items

- [x] Locate below file.
- [x] Delete it.

### Resources/Instructions
[update-comment-on-update-label.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/update-comment-on-update-label.yml)

**Comment by IpshitaSingh** [comment]
Progress: Done
Blockers: None
Availability: 2 hours
ETA: N/A

**Comment by lindseyindev** [comment]
Availability: evening 12/13 & 12/14
ETA: Will try by midnight 12/13, else by midnight 12/14
