### ISSUE TITLE
Design System Audit: Swap colors with color variables: Oranges

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2198]
### Overview
As a developer, hard-coding colors only makes things difficult when colors change. For this only change the orange colors so we can use the color variables.

### Action Items

- [x] Refer to [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss) for the current color variables (oranges)
- [x] Replace all instances of the hard-coded colors with the color variables
  - [x] Make sure to do this carefully, as some changes might break the website
  - [x] If it breaks, investigate why and make edits accordingly. Ask for help if needed.
- [x] If a color variable is unused, delete it from the files noted above.
- [ ] Release dependency on #2114 , if conditions are met

### Resources/Instructions
https://github.com/hackforla/website/blob/09d4b31f55f3ab8eea179e1805f1b1a292e56654/_sass/variables/_colors.scss#L13-L17

<details>
  <summary>Click here to see visual example of search/replace for color variables within VS code</summary>
  <br>
  Search: hex color<br>
  Replace: color variable<br>
  files to include: ./<br>
  files to exclude: *.svg, _site, _colors.scss<br>
  Click on the `Replace All` button (shortcut: Ctrl+Alt+Enter)
  Click `Ok` to confirm replace
  <img src='https://user-images.githubusercontent.com/21162229/131246575-ce0b8a00-cf0b-4803-8fc1-8bcedd7f941e.gif' />
</details>

If the task seems tedious, this might smooth things along if your native IDE is VSCode. Other IDEs might also have similiar functionality.
[Advanced find and replace options for VSCode](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options)

**Comment by d-perez-8** [comment]
Availability: Wednesday, Thursday 4:30-6 Pacific
ETA: 08/17/22 EOD

**Comment by ExperimentsInHonesty** [comment]
Re audited this issue, all necessary changes were made.
