### ISSUE TITLE
Design System Audit: Swap colors with color variables: Yellows

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2199]
### Overview
As a developer, hard-coding colors only makes things difficult when colors change. For this only change the yellow colors so we can use the color variables.

### Action Items

- [x] Refer to [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss) for the current color variables (yellow)
- [x] Replace all instances of the hard-coded colors with the color variables
  - [x] Make sure to do this carefully, as some changes might break the website
  - [x] If it breaks, investigate why and make edits accordingly. Ask for help if needed.
- [x] If a color variable is unused, 
  - [x] Check if its corresponding color class is used. See a list of classes here: [/_sass/elements/_color-styles.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_color-styles.scss) 
- [x] If both the color variable itself and the color class are not used for a specific color,
  - [ ] First, check for all of the color types listed in the Resource section below to make sure it isn't used in our codebase.
  - [ ] Then, if it isn't used,
    - [x] Delete the color variable from this file: `_sass/variables/_colors.scss`
    - [x] Delete its corresponding color class from this file: `/_sass/elements/_color-styles.scss`
- [ ] Release dependency on #2114 , if conditions are met
- [ ] See additional Action Items in this comment: https://github.com/hackforla/website/issues/2199#issuecomment-1334702332

### Resources/Instructions
https://github.com/hackforla/website/blob/09d4b31f55f3ab8eea179e1805f1b1a292e56654/_sass/variables/_colors.scss#L19-L22

If the task seems tedious, this might smooth things along if your native IDE is VSCode. Other IDEs might also have similar functionality.
[Advanced find and replace options for VSCode](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options)

You can do a search within VS Code with the **following values**:

 **Search**: hex color goes here
  **Replace**: color variable goes here
  **files to include**: ./
  **files to exclude**: *.svg, _site, _colors.scss
  
  Once the values are in the search form, do the **following actions**:
  1. Click on the `Replace All` button (shortcut: Ctrl+Alt+Enter)
  2. Click `Ok` to confirm replace
<details>
  <summary>Click here to see visual example of search/replace for color variables within VS code</summary>
  <br>
  <img src='https://user-images.githubusercontent.com/21162229/131246575-ce0b8a00-cf0b-4803-8fc1-8bcedd7f941e.gif' />
</details>

 #### Hard-coded colors can be one of the following color types:
- HTML color codes
- Hex color codes
- RGB 
- HSL values
- HTML color names

**Comment by d-perez-8** [comment]
Availability: 8/29/22
ETA: 1 hour

**Comment by JessicaLucindaCheng** [comment]
- This has been re-audited and the following color variables were not used anywhere in the code:
  - $color-lightyellow
  - $color-papayawhip
- Thus, these colors should be removed from
  - [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss)
  - [/_sass/elements/_color-styles.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_color-styles.scss)

**Comment by angelenelm** [comment]
**Availability:** 10AM - 3PM PST Nov 28, 30, Dec 1, 2, 2022
**ETA:** End of day Dec 2, 2022

**Comment by JessicaLucindaCheng** [comment]
@angelenelm Thanks for working on this issue! Can you please check if the color equivalents of the hex colors were used in the code before deleting the color variables and its associated class? (See the Action Item(s) I added and the list of "Hard-coded colors can be one of the following color types:" above in the issue.) Thanks.

**Comment by angelenelm** [comment]
@JessicaLucindaCheng Sorry I only just saw your comment after my PR was merged! I did see that the rgb equivalent of the ```lightyellow``` variable (```#ffff97```) was used in

- ```_sass/components/_home.scss```
- ```_sass/components/_projects-page.scss```
- ```_sass/components/_projects.scss```

for the project status indicator. the ```papayawhip``` color equivalents were not found anywhere in the code. How would you like for me to proceed?

**Comment by JessicaLucindaCheng** [comment]
@angelenelm 

> @JessicaLucindaCheng Sorry I only just saw your comment after my PR was merged! I did see that the rgb equivalent of the `lightyellow` variable (`#ffff97`) was used in
> 
> * `_sass/components/_home.scss`
> * `_sass/components/_projects-page.scss`
> * `_sass/components/_projects.scss`
> 
> for the project status indicator. the `papayawhip` color equivalents were not found anywhere in the code. How would you like for me to proceed?

Sorry for my delay in getting back to you. Please do the following:
- [x] Put the `lightyellow` variable back in `_sass/variables/_colors.scss`
- [x] Put the `lightyellow` class back in `/_sass/elements/_color-styles.scss`
- [x] Replace the RGB equivalents of `lightyellow` with the variable
- [x] Using Docker, check your changes don't break anything on the website.
- [x] Open a new pull request, with the changes you made.

Please let me know if you have questions.
