### ISSUE TITLE
Communities of Practice information updates: [Product]

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2202]
### Overview
As a Community of Practice Co-Lead, I need my CoP's details to be up to date on the HackforLA website.

### Action Items for requestor
   - [x] Please paste this checklist to a comment below and then check off everything that is **ok the way that it is**
```
- [ ] Name of CoP 
- [ ] Description
- [ ] Meeting Times cannot be changed here.  Create an issue at VRMS for changing [meeting times](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=) if needed
- [ ] Leadership Type: 
- [ ] Leadership
   - [ ] Name
   - [ ] GitHub Handle
   - [ ] Slack Member ID*
 - [ ] Links
    - [ ] Slack Channel
```
   - [x] If you have someone to remove please write that below the checklist you paste in your comment
      - Example: 
```
Remove person and info from CoP card:
Name: Niven Prasad
```

   - [x] If you have someone to add please write that below the checklist you paste in your comment
      - Example: 
```
Add person and info from CoP card:
   - Name: Ebele
   - GitHub Handle:
   - Slack Member ID: 
```

### Action items for Development
- [ ] Make changes to the [Community of Practice page](https://www.hackforla.org/communities-of-practice) as indicated by the comments. 

#### Instructions for Cop lead to find the slack ID they need
To find your Slack Member ID
1. Go to your avatar in the top right corner
2. click "View Profile"
3. click "... More"
4. click "Copy member ID

#### Instructions for Developer
folder where files are in the repo: https://github.com/hackforla/website/tree/gh-pages/_data/internal/communities
where you can see the live page: https://www.hackforla.org/communities-of-practice

**Comment by ExperimentsInHonesty** [comment]
- [ ] Name of CoP 
      - [ ] Description
      - [ ] Meeting Times cannot be changed here.  Create an issue at VRMS for changing [meeting times](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=) if needed
      - [ ] Leadership Type: 
      - [ ] Leadership
         - [ ] Name: Ebele
         - [ ] GitHub Handle: 
         - [ ] Slack Member ID*:
      - [ ] Links
         - [ ] Slack Channel

Remove

Name: Niven Prasad
Role: Co-lead

**Comment by ExperimentsInHonesty** [comment]
- [x] Name of CoP 
- [x] Description
- [x] Meeting Times cannot be changed here.  Create an issue at VRMS for changing [meeting times](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=) if needed
- [x] Leadership Type: 
- [ ] Leadership
   - [ ] Name Ebele
   - [ ] GitHub Handle
   - [ ] Slack Member ID*
 - [x] Links
    - [x] Slack Channel

Remove person and info from CoP card:
Name: Niven Prasad

Add person and info from CoP card:
   - Name: Ebele O.
   - Title: Co-lead
   - GitHub Handle: ebele-oputa
   - Slack Member ID:  U01QJ2SB6A2

**Comment by ExperimentsInHonesty** [comment]
### Overview
As a Community of Practice Co-Lead, I need my CoP's details to be up to date on the HackforLA website.

### Action Items
Change CoP name: NO

Change Description: NO

Change Leadership Type: NO

Change Slack Link: NO

Remove person(s) and info from CoP file: YES
Name: Niven Prasad

Add person(s) and info to CoP file: YES
Name: Ebele O.
Title: Co-lead
GitHub Handle: ebele-oputa
Slack Member ID: U01QJ2SB6A2

### Resources
folder where files are in the repo: https://github.com/hackforla/website/tree/gh-pages/_data/internal/communities
where you can see the live page: https://www.hackforla.org/communities-of-practice

**Comment by adrian-zaragoza** [comment]
Progress: The template is complete. Here is the [link](https://github.com/adrian-zaragoza/website/issues/new?assignees=&labels=role%3A+product&template=demo-communities-of-practice-information-updates.yml&title=Communities+of+Practice+information+updates%3A+%5BINSERT+NAME+OF+Community+of+Practice)
Blockers: None
Pictures: "Add any pictures of the visual changes made to the site so far."
<details>
<summary>Visuals before changes are applied</summary>

![image](https://user-images.githubusercontent.com/77212035/136711529-36631625-5db6-47c4-b04d-53841e3e0747.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![image](https://user-images.githubusercontent.com/77212035/136711546-b4692a91-50a2-453c-9dd0-791f7190a3e4.png)

</details>

**Comment by ExperimentsInHonesty** [comment]
@adrian-zaragoza 

Great work, just a few minor changes

1. sometimes the CoPs will not be changing either adding someone or removing someone.  So there needs to be an option to say NO changes to either of the fields.
2. The following text should be at the bottom of the issue and is not changeable (no need for a form field)
```
### Resources
folder where files are in the repo: https://github.com/hackforla/website/tree/gh-pages/_data/internal/communities
where you can see the live page: https://www.hackforla.org/communities-of-practice
```

When you are done with these changes, please put this in the review column.

**Comment by adrian-zaragoza** [comment]
@ExperimentsInHonesty I have made the changes. Please see the updated form [here](https://github.com/adrian-zaragoza/website/issues/new?assignees=&labels=role%3A+product&template=demo-communities-of-practice-information-updates.yml&title=Communities+of+Practice+information+updates%3A+%5BINSERT+NAME+OF+Community+of+Practice)

I had a question as I was creating the form. Why are "Change CoP name:", "Change Description" , "Change Leadership Type" and "Change Slack Link" always NO?  

<details>
<summary>Visuals before changes are applied</summary>

![image](https://user-images.githubusercontent.com/77212035/136844436-ec18c3e3-f375-4b32-8ddb-87f2ce461a68.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![image](https://user-images.githubusercontent.com/77212035/136844798-8466a4f1-0678-4c5b-a44d-ea4566dca8f5.png)

</details>

**Comment by adrian-zaragoza** [comment]
I added an update to this on a comment above, but here it is again.
 I have made the changes. Please see the updated form [here](https://github.com/adrian-zaragoza/website/issues/new?assignees=&labels=role%3A+product&template=demo-communities-of-practice-information-updates.yml&title=Communities+of+Practice+information+updates%3A+%5BINSERT+NAME+OF+Community+of+Practice)

I had a question as I was creating the form. Why are "Change CoP name:", "Change Description" , "Change Leadership Type" and "Change Slack Link" always NO?  

<details>
<summary>Visuals before changes are applied</summary>

![image](https://user-images.githubusercontent.com/77212035/136844436-ec18c3e3-f375-4b32-8ddb-87f2ce461a68.png)

</details>

<details>
<summary>Visuals after changes are applied</summary>

![image](https://user-images.githubusercontent.com/77212035/136844798-8466a4f1-0678-4c5b-a44d-ea4566dca8f5.png)

</details>

**Comment by macho-catt** [comment]
to bring up this Sunday with @ExperimentsInHonesty

**Comment by macho-catt** [comment]
I updated #2291 based on the discussion last Sunday and releasing the dependency on it.
