### ISSUE TITLE
Design System Audit: Swap colors with color variables: blues

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2204]
### Overview
As a developer, hard-coding colors only makes things difficult when colors change. For this only change the blue colors so we can use the color variables.

### Action Items

- [x] Refer to [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss) for the current color variables (blues)
- [x] Replace all instances of the hard-coded colors with the color variables
  - [x] Make sure to do this carefully, as some changes might break the website
  - [x] If it breaks, investigate why and make edits accordingly. Ask for help if needed.
- [x] If a color variable is unused, delete it from the files noted above.
- [x] Release dependency on #2114 , if conditions are met

### Resources/Instructions
https://github.com/hackforla/website/blob/09d4b31f55f3ab8eea179e1805f1b1a292e56654/_sass/variables/_colors.scss#L31-L40

If the task seems tedious, this might smooth things along if your native IDE is VSCode. Other IDEs might also have similar functionality.
[Advanced find and replace options for VSCode](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options)

You can do a search within VS Code with the **following values**:

 **Search**: hex color goes here
  **Replace**: color variable goes here
  **files to include**: ./
  **files to exclude**: *.svg, _site, _colors.scss
  
  Once the values are in the search form, do the **following actions**:
  1. Click on the `Replace All` button (shortcut: Ctrl+Alt+Enter)
  2. Click `Ok` to confirm replace
<details>
  <summary>Click here to see visual example of search/replace for color variables within VS code</summary>
  <br>
  <img src='https://user-images.githubusercontent.com/21162229/131246575-ce0b8a00-cf0b-4803-8fc1-8bcedd7f941e.gif' />
</details>

**Comment by lindseyindev** [comment]
Availability: 5 hours
ETA: By midnight  1/27

**Comment by lindseyindev** [comment]
Updating issue; not finished
Blockers: time
Availability: 1/29-1/30 - 4 hours
ETA: midnight 1/30 pending no technical blockers

**Comment by lindseyindev** [comment]
Realized an SVG was disappearing after I changed the fill color from a hardcoded hex value to a variable. After researching it seems it's a bit tricky to use a variable as a color for an SVG as an SVG is not part of the DOM.. I believe there's still a way to use a variable color by formatting the SVG in a different way but more time needed to research and test. 
This is the SVG for reference website/assets/images/about/platform-header-elements/workforce-development.svg

None of the other color replacements had breaking changes on the website, there was one element I could not find on the website to verify, it is a piechart from website/assets/js/2FA.js

Last note: color-royalblue and color-babyblue are not being used on the website so I will delete them from the variables. 

ETA: Midnight 2/2/22

**Comment by lindseyindev** [comment]
Couldn't get the SVG to accept a variable color tried multiple different syntaxes including fill="var(--dodgerblue)" and
<img width="592" alt="Screen Shot 2022-02-06 at 8 06 52 AM" src="https://user-images.githubusercontent.com/89806097/152689901-a905be27-64f3-481b-8881-b0701c30806e.png">

going to move forward and finish the issue as I looked through the other SVGs on Hack for LA and variable colors for fill do not exist all of the fill colors are hex codes. It appears to have variable colors the SVGs would need to change how they are written -- my research pointed to using other svg properties like <use> or background colors instead of a fill color -- which is out of the reach of this issue.

**Comment by lindseyindev** [comment]
ETA: midnight 2/11
Availability: 3 hours

**Comment by 7kram** [comment]
This has been re-audited and the following color variables have been removed:
$color-royalblue: #4169e1
$color-babyblue: #a4d5ff

**Comment by ExperimentsInHonesty** [comment]
This is the only place a blue color remains.  A new issue will need to be made.  the blue `#336699` is not in the scss files.
https://github.com/hackforla/website/blob/a9b9119133c884c251a0f5fe21704d8bad876025/_layouts/project.html#L171
https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html#L171

- @hackforla/website-merge please make a new issue to resolve and mention it here.  Then this issue can get moved to the QA column.  Update the epic issue #2114 dependency with the new issue number.

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - issue was made here
- https://github.com/hackforla/website/issues/4138
