### ISSUE TITLE
Design System Audit: Swap colors with color variables: purples,

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2205]
### Overview
As a developer, hard-coding colors only makes things difficult when colors change. For this only change the purple colors so we can use the color variables.

### Action Items

- [x] Refer to [/_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss) for the current color variables (purple colors)
- [x] Replace all instances of the hard-coded colors with the color variables
  - [x] Make sure to do this carefully, as some changes might break the website
  - [x] If it breaks, investigate why and make edits accordingly. Ask for help if needed.
- [x] If a color variable is unused, delete it from the files noted above.
- [x] Release dependency on #2114 , if conditions are met

### Resources/Instructions
https://github.com/hackforla/website/blob/09d4b31f55f3ab8eea179e1805f1b1a292e56654/_sass/variables/_colors.scss#L42-L45

If the task seems tedious, this might smooth things along if your native IDE is VSCode. Other IDEs might also have similar functionality.
[Advanced find and replace options for VSCode](https://code.visualstudio.com/docs/editor/codebasics#_advanced-find-and-replace-options)

You can do a search within VS Code with the **following values**:

 **Search**: hex color goes here
  **Replace**: color variable goes here
  **files to include**: ./
  **files to exclude**: *.svg, _site, _colors.scss
  
  Once the values are in the search form, do the **following actions**:
  1. Click on the `Replace All` button (shortcut: Ctrl+Alt+Enter)
  2. Click `Ok` to confirm replace
<details>
  <summary>Click here to see visual example of search/replace for color variables within VS code</summary>
  <br>
  <img src='https://user-images.githubusercontent.com/21162229/131246575-ce0b8a00-cf0b-4803-8fc1-8bcedd7f941e.gif' />
</details>

**Comment by neevliberman** [comment]
i. Availability: 2 hrs
ii. ETA: 30 minutes

**Comment by ExperimentsInHonesty** [comment]
This has been audited and every instance was caught appropriately.
