### ISSUE TITLE
GHA: Sort closed issues to correct column

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2206]
### Overview

As a developer, we have to ensure that our kanban board is organized for all teams so that productivity is high. For this issue, we are creating a sorter that will move closed issues and PRs to the correct column by their labels when they are closed.

### Psudo-code
- [x] When an issue/PR is closed:
  - [x] If the issue/PR contains a label from the hard label list:
    - [x] Place the issue/PR in the column marked 'Done'.
  - [x] Else if the issue/PR contains a label from the soft label list:
    - [x] If the issue also contains a label from the soft label counter list:
      - [x] Place the issue/PR in the column marked 'UAT'
    - [x] Else:
      - [x] Place the issue/PR in the column marked 'Done'.
  - [x] Else:
    - [x] Place the issue/PR in the column marked 'UAT'.
- [x] Hard label list: any labels involving refactoring
- [x] Soft label list: 'role: back end' label, 'Feature: Analytics'
- [x] Soft label counter-list: 'role: front end'

### Checks

- [x] An issue containing only 'role: back end' and 'role: front end' labels closes -> UAT.
- [x] An issue containing only 'role: front end' closes -> UAT.
- [x] An issue containing only 'Feature: Refactor CSS', 'Feature: Refactor JS / Liquid', and 'P-Feature: Home page' -> Done.
- [x] An issue containing no label -> UAT
- [x] Make sure the labels are placed in the code in such a way that we can easily add, edit, or delete labels
- [ ] ~~The columns id should ideally be a secret, so that they are not exposed. When the id is found, please consult an admin to add it to [our secrets](https://docs.github.com/en/actions/reference/encrypted-secrets).~~ Columns id can be retrieved as a link, from the columns settings menu, [for example ](https://github.com/hackforla/website/projects/7#column-7198257). Please retrieve the id from there.
- [x] In the PR, request the reviewer to, after merging, test that the board automation does not intercept or supercede this GHA. If so, the team leads will need to remove the default automation to allow this one to work.

Note: The purpose of this issue is to sort closed issues into 2 categories. The "there are visual changes to the website"(C) and "no change"(NC) categories. Anything that is C needs to be in UAT, whereas anything that is NC belongs in Done. If any labels fit the NC category, feel free to tack it onto this issue, but be sure to justify it in your PR.

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)

Note that you might want to do something outside the scope of the above psudo-code. If so, be sure to leave comments in your PR or this issue that justifies your reasoning. If you feel you need guidance, be sure to reach out! We cannot foresee whether this issue is solvable, or what hard decisions have to be made, but we would love to hear and help you!

#### Additional resources:
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)
[GitHub GraphQL](https://docs.github.com/en/graphql)
[Encrypted secrets](https://docs.github.com/en/actions/reference/encrypted-secrets)

**Comment by Aveline-art** [comment]
@ExperimentsInHonesty As per our discussion earlier today concerning automation on the UAT column, I want to make sure that we are creating automation that meets stakeholder demands, and would not conflict with the PM team's need. This current automation performs this task:


#### This automation
>```If a closed issue or pull request contains a label that indicates no changes to the website's appearance (for example, the "role:backend" or the "refactor:js" label), the issue goes straight to "Done" and "UAT" otherwise.```

However, today you asked for a new automation that performs this task:

#### New proposed automation
>```If a closed issue's linked pull request contains github image links, send the issue to "UAT" and add the "visual changes" label. Otherwise, send the issue to "UAT" and add the "no visual changes" label.```

These two automation when working together will create the following scenarios:
- an issue has no image links, and is not refactor: js -> go to UAT with "no visual changes" label
- an issue has image links and is not refactor: js-> go to UAT with "visual changes" label
- an issue has no image links, and is refactor: js-> go to Done with "no visual changes" label
- an issue has image links and is refactor: js-> go to ??? with "visual changes" label (realistically, would not happen)

Does this scenario follow what you have in mind? Please indicate which automation should proceed:

- [x] This automation
- [ ] New proposed automation
- [ ] Both
- [ ] Neither, please specify
- [ ] Other, please specify


Also, how should the GHA manage the possibility of human error, such as issues being mislabeled (a possibility, as labels are becoming increasingly complex), or images not being put in the PR when they should (developers usually do not insist on photos since pulling it locally is often easier)?

---

On an adjacent note: Between issue creation, to approval, to assignment, to review, it can take anywhere from 2 weeks to 2 month before a GHA is fully implemented, by which time it might become defunct. For example, with the wins-feature-1 branch merged, this [GHA involving feature branches ](https://github.com/hackforla/website/issues/1940)has become potentially irrelevant for the foreseeable future. With our plans for creating a Dev and UAT version of the website, will UAT automations become irrelevant as well? 

Also, will the GHA still be valuable after the backlog in the UAT column has been cleared?

I apologize if this is a lot to think over. I want to set expectations because it sounds like the UAT backlog might be a temporary problem, in which case a GHA might arrive too late to help.

**Comment by Aveline-art** [comment]
@blakes24 As per today's meeting, I have reworded the issue to better match PM intentions. Feel free to continue this issue and undraft your PR when it is ready for review. Thank you so much for working on this issue!

**Comment by blakes24** [comment]
Progress: I have made the requested changes and updated my PR
Blockers: none
Availability: 5 hours
ETA: pending review
Pictures: NA

**Comment by ExperimentsInHonesty** [comment]
@macho-catt when you review the code, if it seems like there are two many conditionals, ask @blakes24 to review this summary which Matthew, Adam and I came up with during our lead meeting today.

All issue/PR that contain the following go to UAT:
front end  that are not hard label 
back end issues that are soft label
