### ISSUE TITLE
Adjust "...See More" placement on Wins Cards

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2207]
### Overview
We need to move the "...see more" link on the Wins cards from the end of the text to the bottom right of the card in order to standardize card design, making the design and functionality the same regardless of whether the cards do or do not have expandable text. 

### Action Items
Design:
- [x] Duplicate current [Wins card](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=7991%3A41757) in Figma
- [x] Move "See more" to bottom right of card. Keep the "..." in its current position at the end of the text to indicate text continues. This expanded text will be viewable when user clicks the "See more" on bottom of card
- [x] Denote the new updated version in Figma

Development:

- [x] Implement above design change in Wins card. Moved to #2339 

### Resources/Instructions
[Wins Page](https://www.hackforla.org/wins/)
[Figma - Wins Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=7991%3A41757)
#2135 for further context on this issue

**Comment by ktlevesque19** [comment]
Progress: Just assigned, not started
Blockers: None at this time
Availability: I'll be tackling this early next week in the evenings
ETA: I expect to be done by this upcoming Thursday 9/16

**Comment by ktlevesque19** [comment]
Progress: Not started
Blockers: None at this time
Availability: This week got crazy at work, planning to tackle this early this week
ETA: Expect to be done by this upcoming Thursday 9/23

**Comment by ktlevesque19** [comment]
@kristine-eudey I've completed three options in the blue box to the right, ready for review!

This may be a separate issue for once this page goes to development, but I did want to note that the card rows probably won't line up perfectly as they do in the initial page design unless we decide to standardize the card size and leave room for 2 rows of icons always, or limit to one row before expanding. Unless we're okay with the rows not perfectly aligning (which shows in my adjusted version. I don't think it's bad, just definitely a different look than the initial page where two icon row cards never fall next to a single icon row card). 

<img width="561" alt="Screen Shot 2021-09-24 at 5 24 10 PM" src="https://user-images.githubusercontent.com/84823624/134751508-84540419-dde4-41ac-bf20-906c322f2174.png">

**Comment by kristine-eudey** [comment]
As decided at 9/26 team meeting, we'll move forward with **Option A for the desktop version** and **Option B for mobile version** and is ready for development. 

- Context on decision: We decided on this option, just the "See More" to bring up the modal since the behavior of this is different from behavior (accordion expansion) that the down arrow currently relates to on the site. The down arrow will be used for mobile since in mobile the card will expand downward as suggested by the arrow

**Comment by adam-abundis** [comment]
Created #2339 to complete dev portion of this issue.
