### ISSUE TITLE
Administer UX interview forms to internal stakeholders

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#221]
### Dependencies
~Issue #242~

### Overview
Administer UX survey forms to various stakeholders. Announce survey at hack night and email appropriate parties.

### Action Items
- [ ] Administer survey at DTLA Hacknight
- [ ] Administer survey at Westside Hacknight
- [ ] Administer survey at SOLA Hacknight
- [ ] Administer online survey via email blast and Meetup links
- [ ] Set up word cloud account and analyze questionnaire responses

### Resources/Instructions

https://www.wordclouds.com

**Comment by ExperimentsInHonesty** [comment]
This isssue has been replaced with a defined research plan conducted by UX lead and team #1289
