### ISSUE TITLE
Design mobile version of new homepage

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2213]
### Dependency
#2190 

### Overview
We need to design a mobile version of the redesigned homepage so that the page can be launched. 

### Action Items

- [ ] Refer to findings and assessments from #2190
- [ ] Design a mobile version of the redesigned homepage following the current mobile design standards in the design system and using design system components whenever possible. 
- [ ] Communicate with developers throughout the process to ensure design solutions are technically feasible.

### Resources/Instructions
[Figma - Homepage Redesign](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14637%3A94968)
[Figma - Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
[NN Group - Basic Patterns for Mobile Navigation - A Primer](https://www.nngroup.com/articles/mobile-navigation-patterns/)
[UX Booth - The Rules for Modern Navigation](https://www.uxbooth.com/articles/the-rules-for-modern-navigation/)

**Comment by abenipa3** [comment]
Progress: Created mobile mockups for the Technologies and CoP sections. [[Figma Link]](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15663%3A100278)
Blockers: N/A
Availability: 5
ETA: Completed - Looking forward to feedback.
Pictures: 

<details> <summary> Technologies Section  </summary>

![Mobile - Technology](https://user-images.githubusercontent.com/38295612/133573769-c2e09a07-95ed-4f6e-ae95-3d0c7c607709.png)


</details> 

<details> <summary> Communities of Practice Section  </summary>

![Mobile - CoP](https://user-images.githubusercontent.com/38295612/133573845-3d0015e8-2423-4024-be51-df33f77c83cd.png)



</details>

**Comment by janieche** [comment]
1. Progress: Created updated mobile mockups for the Join Us, Wins, and Get in Touch sections. [Figma Link](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15855%3A100459)
2. Blockers: N/A
3. Availability: 3
4. ETA: Updates from feedback completed - looking for
<img width="258" alt="Screen Shot 2021-09-18 at 1 21 59 PM" src="https://user-images.githubusercontent.com/12770042/133906303-10f96a10-1fec-480d-b680-cf8d9944e6a3.png">
 additional feedback.
5. Pictures:

**Comment by abenipa3** [comment]
Progress: 

- Applied feedback from our last meeting. 
- Updated mockups for Community of Practice and Technologies according to our latest Desktop Updates.
- [Figma Link](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16034%3A100670)

Blockers: Struggled with font sizes of the numbers under Technologies. 

<details> <summary> Technologies Preview </summary>

![image](https://user-images.githubusercontent.com/38295612/134443604-153251cc-60ca-4b8b-b45a-a032227f7b02.png)

</details>

Availability: 3

ETA: TBD - Definitely looking forward to more feedback!

**Comment by ahoang94** [comment]
1. Progress: Created updated mobile mockups for the hero banner & Program Areas sections, including several different carousel options. [(Figma Link)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15514%3A100330)
2. Blockers: N/A
3. Availability: 3
4. ETA: TBD; awaiting feedback come Thursday's meeting

**Comment by abenipa3** [comment]
Progress: Created new mockups for [technology](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16634%3A101973) and [CoP](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16634%3A101974) sections. 
Blockers: N/A
Availability: 2
ETA: TBD; awaiting feedback.

<details> <Summary> Technology </summary> 

![image](https://user-images.githubusercontent.com/38295612/135958464-19f266bd-de7f-4769-a7c4-ffd352756e16.png)

</details>

<details> <Summary> Communities of Practice </summary> 

![image](https://user-images.githubusercontent.com/38295612/135958529-23468a2c-8023-4b43-ab03-a00f2ca2ce70.png)


</details>

**Comment by abenipa3** [comment]
Progress: 

- Our team reviewed full mock-ups yesterday during Design Meeting.
- Action Items are as seen in https://github.com/hackforla/website/issues/2106#issuecomment-938078849

Blockers: N/A

Availability: 2 (Alyssa)

ETA: TBD

Notes: Downloaded free mobile app called Figma Mirror to test visuals of our full mock-up. (Can't create previews at the moment because the app keeps disconnecting on my phone. Recommending our team to try it in case it works.)

**Comment by kristine-eudey** [comment]
Version for team discussion [here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16852%3A102341)

**Comment by kristine-eudey** [comment]
Hi @alyssabenipayo @ahoang94 and @janieche! I made some tweaks to the mobile homepage as per the feedback from Sunday's meeting, along with incorporating changes based on feedback from a meeting I had today with Bonnie and the Product team. Please take a look at the updated version [here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16865%3A102493) and let's discuss at Thursday's meeting. I made notes on the Figma describing all the changes.

**Comment by abenipa3** [comment]
Hi @kristine-eudey! I saw the changes to the mobile homepage - the updates look great on the Technology and CoP sections! Thank you!

**Comment by kristine-eudey** [comment]
@arghmatey I have a question about the feasibility of using a different version of the CoP gradient box for the mobile version: 

- In effort to make the design of this section more cohesive and translate better to a side-scroll, I'm wondering if it would be possible (and if it would be a huge amount of additional work) to use this version for mobile? 
- CoP names inside the colored box, rather than outside the box as they are on the desktop version
![Screen Shot 2021-10-21 at 4 57 49 PM](https://user-images.githubusercontent.com/16949503/138355783-ef7851d1-3cd8-428c-9dde-9a83ba48ac74.png)

**Comment by arghmatey** [comment]
@kristine-eudey I should be able to implement that with little effort. I'll have some time to work on this on Sunday, and will keep you posted if I run into any problems. Thanks!

**Comment by kristine-eudey** [comment]
Great, thank you @arghmatey! Final design for development can be found here: [Homepage - Mobile Design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16905%3A102823). The design portion of this issue is done so I'll close this issue. @arghmatey or @abuna1985 , if you need to make a dev issue or anything for this, feel free to take it from here. Thanks!

**Comment by ExperimentsInHonesty** [comment]
The Development issue is https://github.com/hackforla/website/issues/2317
