### ISSUE TITLE
GitHub Actions: Update trigger on add missing labels GHA

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2215]
### Overview
As a developer, we need to cover edge cases on our code. For this issue, we will update the trigger for our Add missing labels to new issues job under the "[Issue Trigger](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml)" GHA.

### Action Items

- [x] Add "transferred" to the GHA trigger noted above (line 4).
```
  issues:
    types: [opened, transferred]
```
- [x] Update the if conditional for the job so it also triggers on issue transfer (line 10).
```
if: ${{ github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'transferred')}}
```
- [x] If possible, test in your local environment that the action works as intended.

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)

Note that you might want to do something outside the scope of the above psudo-code. If so, be sure to leave comments in your PR or this issue that justifies your reasoning. If you feel you need guidance, be sure to reach out! We cannot foresee whether this issue is solvable, or what hard decisions have to be made, but we would love to hear and help you!

#### Additional resources:
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[Issue Trigger](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml)

**Comment by gardenqu** [comment]
I have removed myself from this issue

**Comment by ExperimentsInHonesty** [comment]
@troywzhu removing you from this issue for lack of response.  If you still want to work on the team, please reach out to the tech leads in the hfla site channel for help.

**Comment by aricforrest** [comment]
Available: 3 hours
ETA: 9-23-22
