### ISSUE TITLE
GitHub Actions: Rename "Add Update Label to Issues Weekly" to "Schedule Friday 0700"

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2220]
### Overview
As a member of the backend team, github actions are much more maintainable and easier to understand if they are structured based on triggers and functionality. For this issue, we want to update [add-update-label-weekly.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-update-label-weekly.yml) and rename the action to 'Schedule Friday 0700' so all scheduled actions that occur on 7am every Friday can live in this file.

### Action Items
- [x] Review the notes below to understand recent changes to our architecture
- [x] Rename the file from 'add-update-label-weekly.yml' to 'schedule-fri-0700.yml'
- [x] Rename the name of the action from 'Add Update Label to Issues Weekly' to 'Schedule Friday 0700'
    - [x] The name of the job should still stay the same (line 8)
- [x] Update the location of the [accompanying files](https://github.com/hackforla/website/tree/gh-pages/github-actions/add-update-label-weekly)
    - [x] If not created yet, create a new directory under /[github-actions](https://github.com/hackforla/website/tree/gh-pages/github-actions)/ called trigger-schedule
    - [x] Move the [add-update-label-weekly directory](https://github.com/hackforla/website/tree/gh-pages/github-actions/add-update-label-weekly) under /github-actions/trigger-schedule
    - [x] Update the github action's js requirement to reflect the change in directory
- [x] If possible, do a test on your local environment and make sure it still works

### Resources/Instructions

- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [add-update-label-weekly.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-update-label-weekly.yml)
- [GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
- [Accompanying JS](https://github.com/hackforla/website/tree/gh-pages/github-actions)
- See previous work done on this issue: https://github.com/hackforla/website/pull/3426
- [How to test GitHub Actions](https://docs.google.com/document/d/1A2sj5KROv_AD3qTUrPO-YI730hKj2-o1FnE8GE1PUVY/edit#heading=h.t6xbafvaf6mp)

#### Architecture Notes

The idea behind the refactor is to organize our GitHub Actions so that developers can easily maintain and understand them. Currently, we want our GitHub Actions to be structured like so based on this [proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015):

- Schedules (military time)
        - Schedule Friday 0700
        - Schedule Thursday 1100
        - Schedule Daily 1100
- Linters
        - Lint SCSS
- PR Trigger
        - Add Linked Issue Labels to Pull Request
        - Add Pull Request Instructions
- Issue Trigger
        - Add Missing Labels To Issues
- WR - PR Trigger
        - WR Add Linked Issue Labels to Pull Request
        - WR Add Pull Request Instructions
- WR - Issue Trigger

Actions with the same triggers (excluding linters, which will be their own category) will live in the same github action file. Scheduled actions will live in the same file if they trigger on the same schedule (i.e. all files that trigger everyday at 11am will live in one file, while files that trigger on Friday at 7am will be on a separate file).

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

#### Additional resources:
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)
[GitHub GraphQL](https://docs.github.com/en/graphql)

**Comment by poorvi4** [comment]
ETA: 3-5 hours
Availability: Sunday-Tuesday 2 hours each day, 8-10 pm

**Comment by blulady** [comment]
- see issue #3426 for what prior work had been done and also checkout this [google doc](https://docs.google.com/document/d/1A2sj5KROv_AD3qTUrPO-YI730hKj2-o1FnE8GE1PUVY/edit#heading=h.t6xbafvaf6mp) to see how to use Nekros

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge This was discussed at the last DEV/PM meeting, and it was decided that dev leads would look at this issue to see what next steps are with this issue.

**Comment by ExperimentsInHonesty** [comment]
I dont see any movement on this.  Adding back to dev/pm agenda and moving to Question column

**Comment by jdingeman** [comment]
Adding a note in resources for the work that was done previously before it was abandoned. We are going to send this back to the prioritized backlog.

**Comment by jefflueck** [comment]
Availability: Wed, Thur, Fri, Sat 10 am - 5 pm CST / Week of 3/27/23
Week of 4/3/23 Mon,Wed,Fri, Sat 10 am - 5 pm CST
ETA: End of next week. 4/7/23

**Comment by jefflueck** [comment]
Test on fork: https://github.com/jefflueck/website-1/actions/runs/4584213135/jobs/8095565715
All workflows showed complete
