### ISSUE TITLE
GitHub Actions: Rename "Update Team Members" to "Schedule Thursday 1100"

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2221]
### Overview
As a member of the backend team, github actions are much more maintainable and easier to understand if they are structured based on triggers and functionality. For this issue, we want to update [update-team-members.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/update-team-members.yml) and rename the action to 'Schedule Thursday 1100' so all scheduled actions that occur on 11am every Thursday can live in this file.

### Action Items
- [x] Review the notes below to understand recent changes to our architecture
- [x] Rename the file from 'update-team-members.yml' to 'schedule-thu-1100.yml'
- [x] Rename the name of the action from 'Update Team Members' to 'Schedule Thursday 1100'
    - [x] The name of the job should still stay the same (line 11)
- [x] Update the location of the [accompanying js file](https://github.com/hackforla/website/blob/gh-pages/github-actions/github-data/contributors-data.js)
    - [x] If not created yet, create a new directory under /[github-actions](https://github.com/hackforla/website/tree/gh-pages/github-actions)/ called trigger-schedule
    - [x] Create a subdirectory under /github-actions/trigger-schedule called trim-contributors
    - [x] Move the js file [contributor-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/github-data/contributors-data.js) under /github-actions/trigger-schedule/trim-contributors
    - [x] Update the github action's js requirement to reflect the change in directory
- [ ] If possible, do a test on your local environment and make sure it still works

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[add-update-label-weekly.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-update-label-weekly.yml)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Accompanying JS](https://github.com/hackforla/website/tree/gh-pages/github-actions)

#### Architecture Notes

The idea behind the refactor is to organize our GitHub Actions so that developers can easily maintain and understand them. Currently, we want our GitHub Actions to be structured like so based on this [proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015):

- Schedules (military time)
        - Schedule Friday 0700
        - Schedule Thursday 1100
        - Schedule Daily 1100
- Linters
        - Lint SCSS
- PR Trigger
        - Add Linked Issue Labels to Pull Request
        - Add Pull Request Instructions
- Issue Trigger
        - Add Missing Labels To Issues
- WR - PR Trigger
        - WR Add Linked Issue Labels to Pull Request
        - WR Add Pull Request Instructions
- WR - Issue Trigger

Actions with the same triggers (excluding linters, which will be their own category) will live in the same github action file. Scheduled actions will live in the same file if they trigger on the same schedule (i.e. all files that trigger everyday at 11am will live in one file, while files that trigger on Friday at 7am will be on a separate file).

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

#### Additional resources:
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)
[GitHub GraphQL](https://docs.github.com/en/graphql)

**Comment by SAUMILDHANKAR** [comment]
@poorvi4 Requesting to unassign from this issue and move it back to new issue approval column so it can be re-prioritized. Please hold-off on picking-up a new issue until your previous issue has been merged. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@poorvi4 Unassigning you from this issue since you are on a break. Just to make sure this issue could be worked upon if someone is available in the meantime. Please feel free to pick it back up when you join back and if this issue is still available. Thank you.

**Comment by BeckettOBrien** [comment]
Availability: 3 Hours
ETA: EOD 7/11/22
