### ISSUE TITLE
Add XML tree to site

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#223]
### Overview
Add navigation site tree to Wiki. 

### Action Items
Add navigation site tree to Wiki. See if a plug-in is available that will provide breadcrumb navigation to each page of the Wiki.

### Resources/Instructions

**Comment by ExperimentsInHonesty** [comment]
Here is a where you might find resources for this: https://github.community/t5/forums/searchpage/tab/message?advanced=false&allow_punctuation=false&q=wiki

**Comment by ExperimentsInHonesty** [comment]
There is currently no tool for jekyll sites but there there is plenty of tools for creating xml site maps so it seems as if one is not needed.  Here is a good one https://www.xml-sitemaps.com/. We should clean up our site and then add an xml sitemap to google and then if we want to we can create a graphic representation of it using the XML file.

I am going to rename this issue so it more accurately reflects what we need done.  Previous name was Add navigation site tree to Wiki .  New name will be Add XML tree to site.

**Comment by akibrhast** [comment]
## Progress
Done. Awaiting PR review
## Blockers

## Availability

## ETA
