### ISSUE TITLE
Make engineering pre work issue template

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2232]
### Overview

Need a pre work template so new people can know how to make a new issue and know what to do when they first arrive

### Action Items

- [ ] Write a draft in comments of new template
- [ ] Ask team members for advice on what should go in template

### Resources/Instructions

[Contributing](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Site architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

**Comment by ExperimentsInHonesty** [comment]
# from the ui/ux prework template

### Overview
Fill in the following fields as you work on these items on the Hack for LA website project. Add the link of the items you worked on in the list as examples.

### Onboarding Action Items
- [ ] Join UX/UI Github and Google Drive
- [ ] Set up [2FA](https://www.hackforla.org/guide-pages/2FA.html) on Github and mark HfLA membership [public](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership#changing-the-visibility-of-your-organization-membership)
- [ ] Read the [guide for using our Github Kanban boards](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit#heading=h.nl3p4nf4eqb4) (working draft)
- [ ] All Hack for LA teams use Figma for our collaborative design. New to Figma? Learn more: [Figma for Beginners videos 1-4](https://www.youtube.com/watch?v=dXQ7IHkTiMM&ab_channel=Figma)  
- [ ] All Hack for LA teams generally work in an Agile framework. Read more about Agile and how it relates to Kanban [HERE](https://www.atlassian.com/agile).

**Comment by ExperimentsInHonesty** [comment]
Review with team what has been written so far and see if they recommend other items

**Comment by ExperimentsInHonesty** [comment]
[Link to see the board by Good First Issue and the Prioritized backlog column is highlighted](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22good+first+issue%22#column-7198257)
[Link to see the board by Good Second Issue and the Prioritized backlog column is highlighted](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22size%3A+good+second+issue%22#column-7198257)

**Comment by ExperimentsInHonesty** [comment]
# This came from the BOP project

### Reporting progress
- Be sure to check the box when you finish an action item.
- Report your progress weekly in a comment below using the following format:
     - Progress: 
     - Blockers: 
     - Availability :
     - Estimated date of completion:

### Stopping mid issue 
#### Reasons: 
- Got personally busy, can’t finish
-  Only want to do a specific type of task per interview
- There is a blocker in the way of finishing and I still have time to work on other issues 
#### What to do if you have to stop working mid issue:
- Note your progress in the checkboxes 
- Add a note in the comments with details
- Move the issue to the questions/review column 

### Unassigning yourself from this issue
If you are finished with one of the 4 Action Items and you are not going to do the next one
- [ ] Move this issue from the ‘In progress’ to the ‘Prioritized Backlog’(see animated GIF below) 
- [ ] Unassign yourself from this issue (see animated GIF below) 

### Resources/Instructions

#### Assign & Unassign yourself to this issue
![Assign & Unassign](http://g.recordit.co/MkwqNlnWWO.gif)

####  Move this issue from the ‘Prioritized Backlog’ to the ‘In progress’ & back
![Prioritized to In progress & back](http://g.recordit.co/wvXm85TR1Q.gif)

**Comment by ExperimentsInHonesty** [comment]
provide guidance that the only thing on the board new developers and designers need to pay attention to are

Developers & Designers
Prioritized Backlog
In Progress

Developers
Pull Requests

Once a developer has had their good first issue and good second issue PRs approved then they can look at the "PR Needs review (Automated Column, do not place items here manually)" column to find [good first issues](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22size%3A+good+first+issue%22#column-15520436)
 [good second issues](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22size%3A+good+second+issue%22#column-15520436)

**Comment by adam-abundis** [comment]
# Working Example

### Overview
This template will provide steps to set up your development environment and begin contributing to the Hack for LA Website team


### Action Items
- [ ] Go to the Contributing.md document - https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md
    - [ ] Complete [Step 2: Installing Git](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#Installing-Git)
    - [ ] Complete [Step 3: Fork the repository](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#Fork-the-repository)
    - [ ] Complete [Step 4: Clone the forked repository](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#Clone-the-forked-repository)
    - [ ] Complete [Step 5: Set up Docker](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#Set-up-Docker-%5B4%5D)
    - [ ] Complete [Step 6: Build and serve the website locally](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#Build-and-serve-the-website-locally)
- [ ]  Claim your first issue
    - [ ] Go to the [Project Board](https://github.com/hackforla/website/projects/7)
    - [ ] 

### Resources/Instructions

**Comment by adam-abundis** [comment]
## Update - 10/16/2021
1. Progress: I would like to pivot to updating the Contributing.md as a source of truth this is a more detailed and living document
2. Blockers: Unsure about adding another issue that needs to be monitored by the website-merge team. I would prefer to update the contributing.md and provide a clear path to setting up/work on issues.
3. Availability: now-Sunday evening
4. ETA: Pushing contributing.md updates, then after feedback, close this issue.
5. Pictures: N/A

**Comment by adam-abundis** [comment]
Closing this issue. Decided to add all of the information into our Contributing Document

https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md

**Comment by ExperimentsInHonesty** [comment]
UI/UX prework issue https://github.com/hackforla/website/issues/2360

**Comment by adam-abundis** [comment]
@ExperimentsInHonesty Engineering pre-work issue template has been created.

@macho-catt I would present the pre-work issue template to the team on Tuesday for feedback. I would also have someone present it to Bonnie on Sunday.

**Comment by ExperimentsInHonesty** [comment]
review this with the developers to see if they think anything is missing
[Issue: Pre-work Template - Developers](https://github.com/hackforla/website/issues/new?assignees=&labels=good+first+issue%2C+role%3A+front+end%2C+role%3A+back+end%2C+Feature%3A+Onboarding%2FContributing.md&template=pre-work-template--dev.md&title=Pre-work+Checklist%3A+Developer%3A+%5Breplace+brackets+with+your+name%5D)

### Notes for improvement

- [x] remove the role label being automatically added
- [x] add an action item to add the role label.

**Comment by macho-catt** [comment]
Template has been updated, should be ready to close unless there are additional points to add
