### ISSUE TITLE
Update how 'Overview' link opens for Access The Data

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2234]
### Overview
As a user, clicking on the 'Overview' link for the Access The Data project should open a new tab to the pdf file directly. This is made as an action item of #2211 

### Details
When clicking the 'Overview' link, each project page acts differently. Some open to a google docs page, others open to a github page that hosts the pdf file, and another downloads the pdf file locally to the machine. There needs to be a standard in how the pdf files open. Developers decided during the backend meeting that pdfs should be opened as a separate tab to the file directly, since modern browsers have the ability to view pdfs.

**Example:**
[How Access The Data's pdf file currently opens](https://docs.google.com/document/d/1bWWhI0Zuas22sdEEDC6sSuRYZ3gXiBZ8LuyNUmD_s7o/edit)
[How it should open](https://www.hackforla.org/test/Access-the-Data-One-Sheet.pdf)

### Action Items
- [x] Download a copy of Access The Data's overview pdf and put it in [/assets/pdfs](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
- [x] Change the 'Overview' link for the [markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md) to point to the pdf file living under /assets/pdfs
- [x] Ensure that the links in both the [project page](https://www.hackforla.org/projects/) and the project's [dedicated page](https://www.hackforla.org/projects/access-the-data) open the pdf file properly after the change

### Resources/Instructions
[Markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md)
[Project Page](https://www.hackforla.org/projects/access-the-data)
[Location for pdf files](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
[Jekyll Static Files](https://jekyllrb.com/docs/static-files/)

**Comment by anthonysim** [comment]
Availability for this week: 
Wed (12/8): 5 - 7 PM
Fri (12/10): 5 - 7 PM
Sat (12/11): 11 - 1 PM
My estimated ETA for completing this issue: 12/11/2021
