### ISSUE TITLE
Update how 'Overview' link opens for BallotNav

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2235]
### Overview
As a user, clicking on the 'Overview' link for the BallotNav project should open a new tab to the pdf file directly. This is made as an action item of #2211 

### Details
When clicking the 'Overview' link, each project page acts differently. Some open to a google docs page, others open to a github page that hosts the pdf file, and another downloads the pdf file locally to the machine. There needs to be a standard in how the pdf files open. Developers decided during the backend meeting that pdfs should be opened as a separate tab to the file directly, since modern browsers have the ability to view pdfs.

**Example:**
[How BallotNav's pdf file currently opens](https://github.com/hackforla/product-management/blob/master/project-one-sheets/BallotNav-Project-One-Sheet.pdf)
[How it should open](https://www.hackforla.org/test/Access-the-Data-One-Sheet.pdf)

### Action Items
- [x] Download a copy of BallotNav's overview pdf and put it in [/assets/pdfs](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
- [x] Change the 'Overview' link for the [markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/ballot-nav.md) to point to the pdf file living under /assets/pdfs
- [x] Ensure that the links in both the [project page](https://www.hackforla.org/projects/) and the project's [dedicated page](https://www.hackforla.org/projects/ballot-nav) open the pdf file properly after the change

### Resources/Instructions
[Markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/ballot-nav.md)
[Project Page](https://www.hackforla.org/projects/ballot-nav)
[Location for pdf files](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
[Jekyll Static Files](https://jekyllrb.com/docs/static-files/)

**Comment by lopezpedres** [comment]
Availability for this week: 
    -Thursday: 3 pm - 5:30 pm
    -Sunday: 9 am - 12 pm
My estimated ETA for completing this issue: 2021/12/05
