### ISSUE TITLE
Update how 'Overview' link opens for Civic Tech Structure

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2238]
### Overview
As a user, clicking on the 'Overview' link for the Civic Tech Structure project should open a new tab to the pdf file directly. This is made as an action item of #2211 

### Details
When clicking the 'Overview' link, each project page acts differently. Some open to a google docs page, others open to a github page that hosts the pdf file, and another downloads the pdf file locally to the machine. There needs to be a standard in how the pdf files open. Developers decided during the backend meeting that pdfs should be opened as a separate tab to the file directly, since modern browsers have the ability to view pdfs.

**Example:**
[How Civic Tech Structure's pdf file currently opens](https://github.com/hackforla/product-management/blob/master/project-one-sheets/Civic-Tech-Structure-Product-One-Sheet.pdf)
[How it should open](https://www.hackforla.org/test/Access-the-Data-One-Sheet.pdf)

### Action Items
- [x] Download a copy of Civic Tech Structure's overview pdf and put it in [/assets/pdfs](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
- [x] Change the 'Overview' link for the [markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-structure.md) to point to the pdf file living under /assets/pdfs
- [x] Ensure that the links in both the [project page](https://www.hackforla.org/projects/) and the project's [dedicated page](https://www.hackforla.org/projects/civic-tech-structure) open the pdf file properly after the change
- [x] Release dependency on #2211 

### Resources/Instructions
[Markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-structure.md)
[Project Page](https://www.hackforla.org/projects/civic-tech-structure)
[Location for pdf files](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
[Jekyll Static Files](https://jekyllrb.com/docs/static-files/)

**Comment by SAUMILDHANKAR** [comment]
@riddle015 Request to please add your availability and ETA for completing the issue once you pick up an issue. Thanks.

**Comment by JessicaLucindaCheng** [comment]
@riddle015 Also, please move this issue into the "In Progress" column since you are actively working on it.

**Comment by riddle015** [comment]
Progress: Just starting
Blockers: None
Availability: ~7 hours
ETA: 2/6

**Comment by SAUMILDHANKAR** [comment]
@riddle015 Just wanted to follow up regarding your progress on this issue. Please let us know if you have any questions or need help. Thanks.

**Comment by riddle015** [comment]
Progress: "None"
Blockers: "None"
Availability: "2 hours"
ETA: "2/20/2022"

**Comment by SAUMILDHANKAR** [comment]
@riddle015: Just wanted to follow up regarding your progress on this issue. Please let us know if you have any questions, need help or if there is any change in your availability. I will leave a slack message as well about the same. Thanks.

**Comment by riddle015** [comment]
@SAUMILDHANKAR I need help on this issue. I'm having trouble accessing the correct file structure.

Thanks

Hiram

**Comment by SAUMILDHANKAR** [comment]
> @SAUMILDHANKAR I need help on this issue. I'm having trouble accessing the correct file structure.
> 
> Thanks
> 
> Hiram

@riddle015 Thanks for getting back. Requesting @JessicaLucindaCheng to follow up on this. Thank you.

**Comment by JessicaLucindaCheng** [comment]
@riddle015  

> I'm having trouble accessing the correct file structure.

- I assume you already added the pdf to `/assets/pdfs`. If you mean you are having trouble figuring out how to format the link in markdown, here are a couples examples from the current codebase:
  - https://github.com/hackforla/website/blob/b883cd0cbef033de9ac0ef0abe1de8c7058996f9/_projects/100-automations.md?plain=1#L52-L53
  - https://github.com/hackforla/website/blob/b883cd0cbef033de9ac0ef0abe1de8c7058996f9/_projects/ballot-nav.md?plain=1#L67-L68

- If the link formatting looks right but you don't see the changes when you use Docker, try the instructions in [2.7.b.i. What if you cannot see your changes locally within Docker? in CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-what-if-you-cannot-see-your-changes-locally-within-docker).
- If it is something else, please specify.
