### ISSUE TITLE
Update how 'Overview' link opens for Engage

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2239]
### Overview
As a user, clicking on the 'Overview' link for the Engage project should open a new tab to the pdf file directly. This is made as an action item of #2211 

### Details
When clicking the 'Overview' link, each project page acts differently. Some open to a google docs page, others open to a github page that hosts the pdf file, and another downloads the pdf file locally to the machine. There needs to be a standard in how the pdf files open. Developers decided during the backend meeting that pdfs should be opened as a separate tab to the file directly, since modern browsers have the ability to view pdfs.

**Example:**
[How Engage's pdf file currently opens](https://github.com/hackforla/product-management/blob/master/project-one-sheets/Engage-Product-One-Sheet.pdf.pdf)
[How it should open](https://www.hackforla.org/test/Access-the-Data-One-Sheet.pdf)

### Action Items
- [x] Download a copy of Engage's overview pdf and put it in [/assets/pdfs](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
- [x] Change the 'Overview' link for the [markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/engage.md) to point to the pdf file living under /assets/pdfs
- [x] Ensure that the links in both the [project page](https://www.hackforla.org/projects/) and the project's [dedicated page](https://www.hackforla.org/projects/engage) open the pdf file properly after the change

### Resources/Instructions
[Markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/engage.md)
[Project Page](https://www.hackforla.org/projects/engage)
[Location for pdf files](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
[Jekyll Static Files](https://jekyllrb.com/docs/static-files/)

**Comment by BrianCodes33** [comment]
Is there a reason why there are two .pdf extensions at the end of the file name? Don't think I've ever seen that. I also changed the markdown fiile, and it's still linking to Github for some reason. 

here is the code i edited in md file: `url: '../assets/pdfs/Engage-Product-One-Sheet.pdf.pdf'`

**Comment by BrianCodes33** [comment]
Availability for this week: Evenings M-F
ETA: 2-3 Days

**Comment by JessicaLucindaCheng** [comment]
@BrianCodes33
> Is there a reason why there are two .pdf extensions at the end of the file name? Don't think I've ever seen that. I also changed the markdown fiile, and it's still linking to Github for some reason.
> 
> here is the code i edited in md file: `url: '../assets/pdfs/Engage-Product-One-Sheet.pdf.pdf'`

- Good catch! The name of the file should be `Engage-Product-One-Sheet.pdf`. Once you download the file, you can rename it so it only has one .pdf extension.
- If you make changes to code and don't see it when you use Docker to view the website locally on your computer, run `docker-compose down`, then clear your cache and delete the file `.jekyll-metadata` and the directory `_site`, and then run `docker-compose up`. You should see changes locally.
