### ISSUE TITLE
Update how 'Overview' link opens for LA TDM Calculator

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2242]
### Overview
As a user, clicking on the 'Overview' link for the LA TDM Calculator project should open a new tab to the pdf file directly. This is made as an action item of #2211 

### Details
When clicking the 'Overview' link, each project page acts differently. Some open to a google docs page, others open to a github page that hosts the pdf file, and another downloads the pdf file locally to the machine. There needs to be a standard in how the pdf files open. Developers decided during the backend meeting that pdfs should be opened as a separate tab to the file directly, since modern browsers have the ability to view pdfs.

**Example:**
[How LA TDM Calculator's pdf file currently opens](https://github.com/hackforla/product-management/blob/master/project-one-sheets/TDM-Calculator-Product-One-Sheet.pdf)
[How it should open](https://www.hackforla.org/test/Access-the-Data-One-Sheet.pdf)

### Action Items
- [ ] Download a copy of LA TDM Calculator's overview pdf and put it in [/assets/pdfs](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
- [ ] Change the 'Overview' link for the [markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md) to point to the pdf file living under /assets/pdfs
- [ ] Ensure that the links in both the [project page](https://www.hackforla.org/projects/) and the project's [dedicated page](https://www.hackforla.org/projects/tdm-calculator) open the pdf file properly after the change

### Resources/Instructions
[Markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md)
[Project Page](https://www.hackforla.org/projects/tdm-calculator)
[Location for pdf files](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
[Jekyll Static Files](https://jekyllrb.com/docs/static-files/)

**Comment by SAUMILDHANKAR** [comment]
Reopening this as the PR #2772 which is supposed to fix this issue isn't merged yet.

**Comment by JessicaLucindaCheng** [comment]
@blulady In response to https://github.com/hackforla/website/issues/2683#issuecomment-1059504566,
> Progress: I need to be able to push the correct code up to github Blockers: struggling with pushing a specific branch Availability: I have 8 hours to work on this ETA: as soon as I hear back Pictures: I haven't been able to make any changes

Are you trying to push changes for the branch `update-how-overview-link-opens-for-LA-TDM-Calculator_2242`? I'm asking because I'm trying to better understand the problem/blocker you are encountering.

**Comment by blulady** [comment]
Progress: I need to be able to push the correct code up to github
Blockers: struggling with pushing a specific branch
Availability: I have 8 hours to work on this
ETA: as soon as I hear back
Pictures: I haven't been able to make any changes

**Comment by blulady** [comment]
1. from github repository website branch gh-pages click fetch upstream
2. on local repository website branch gh-pages cli git fetch upstream
3. on local repository git checkout update-how-overview-link-opens-for-LA-TDM-Calculator_2242 branch
4. fetch from origin (for some reason the tdm pdf was in my github repo but not the local one)
	still not on the local in pycharm but can see it in cli
5.because I can see it in cli, I attempt to push it
	git push --set-upstream origin update-how-overview-link-opens-for-LA-TDM-Calculator_2242
	git says "Everything up-to-date"
	'update-how-overview-link-opens-for-LA-TDM-Calculator_2242' set up to track remote branch 'update-how-overview-link-opens-for-LA-TDM-Calculator_2242' from 'origin'.

6. then i attempt to update the local clone/fork
	git checkout upstream-gh-pages
	git pull  
	git checkout gh-pages 
	git merge upstream-gh-pages 
7. git push *here is where I get an error.

C:\Users\ssang\Documents\hackforla\website\assets\pdfs>git push
fatal: The current branch gh-pages has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin gh-pages

**Comment by JessicaLucindaCheng** [comment]
@blulady When you run the command `git remote -v`, do you get the following on your terminal?
```
origin  https://github.com/blulady/website.git (fetch)
origin  https://github.com/blulady/website.git (push)
upstream        https://github.com/hackforla/website.git (fetch)
upstream        https://github.com/hackforla/website.git (push)
```

**Comment by blulady** [comment]
origin  https://github.com/blulady/website.git (fetch)
origin  https://github.com/blulady/website.git (push)
upstream        https://github.com/hackforla/website.git (fetch)
upstream        https://github.com/hackforla/website.git (push)

**Comment by JessicaLucindaCheng** [comment]
@blulady
> C:\Users\ssang\Documents\hackforla\website\assets\pdfs>git push
> fatal: The current branch gh-pages has no upstream branch.
> To push the current branch and set the remote as upstream, use
> 
>     git push --set-upstream origin gh-pages

It looks like you are in "C:\Users\ssang\Documents\hackforla\website\assets\pdfs". Does changing to  "C:\Users\ssang\Documents\hackforla\website\" make a difference when you try to push?

**Comment by blulady** [comment]
![Screenshot (59)](https://user-images.githubusercontent.com/67162265/157137036-7fdb90da-b88a-4da7-ada7-dd5e389e954a.png)

**Comment by SAUMILDHANKAR** [comment]
@blulady Just wanted to check if you still have the error log that we received after `git push --set-upstream origin gh-pages` during our last meeting. Please let me know. Thanks.
