### ISSUE TITLE
Change Wins form to our internal "Share Your Wins" form

### ISSUE THREAD

**Issue by arghmatey** [hackforla/website#2246]
### Dependency
- #2021

### Overview
We need to update the "Share your wins" link on the wins page to redirect to our internal ["Share your wins"](https://www.hackforla.org/share-your-wins/) form. The link is currently directing to a google form. 

### Action Items
- [ ] Verify "Share your wins" form is functioning correctly, and pushes user submitted data to Wins Responses Google Sheet
- [ ] Change "Share your wins" anchor href attribute to `"share-your-wins/"`

### Resources/Instructions
#1060 - wins form creation
[Wins page](https://www.hackforla.org/wins)
[Share your wins page](https://www.hackforla.org/share-your-wins/)

**Comment by arghmatey** [comment]
Closing issue temporarily while security issues with API keys and google scripts are worked out. Issue can be reopened once we are confident and ready to implement.

**Comment by roslynwythe** [comment]
- As a result of #4588 it was determined that the Custom WINS form is not secure and so related issues including this one will be closed as not planned.

**Comment by ExperimentsInHonesty** [comment]
This has been added as a decision record to the backlog of items that will be added to the wiki once its moved.
