### ISSUE TITLE
Add new project to website: Design Systems

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2255]
### Overview

We need to add a new project to the hack for la website so that our project list can be current

### Project Details
- Name: Design-Systems
- Name of future project.md file: design-systems.md
- Files you will need to upload to the website repository: design-systems.jpg and design-system-hero.jpg
- Where you will store the files:
   - images go in this folder: /assets/images/projects
   - project.md file goes in this folder: _projects

### Action Items
- [x] Take the content listed here and create a new project.md card (skip anything that has strikethrough)
- [x] Download the images
- [x] Add both project card and images to appropriate folders
- [x] Once you have it working on your local environment
  - [x] Take screen shots of the project card on the homepage and the projects project page adding them to issue
   - [ ] Reach out to the product manager to ask if they are satisfied by adding a comment to [this issue](https://github.com/hackforla/product-management/issues/297) with a link to the screenshots on your issue
- [ ] Submit pull request
- [ ] Let Product Manager know when its live

### Resources
[Template for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

#### Content of the project.md card
- [x] A link to the [600 x 400 image](https://drive.google.com/file/d/1X5FLl9PdU-lI-bWWY9H2Hpa5AAPZ_5Kz/view?usp=sharing)
- [x]  Alt image text - 'Hack for LA logo and the title of the project, Design Systems'
- [x]  A link to the [1500 x 700 hero image](https://drive.google.com/file/d/1MiwRrs3idDNf86CKoF7zILmWDD0vqm6y/view?usp=sharing) 
- [x]  Name of project: Design Systems
- [x]  A blurb about your project:
```
The Design System initiative seeks  to empower volunteers with the tools, documentation and templates for creating and maintaining a design system for their HfLA projects.  As Hack for LA continues to scale it has become more essential to create consistent documentation and standards for design deliverables. 

A Design System is a single source of truth for a website’s designers and developers– a collection of reusable components, styles, and code guided by clear standards and documentation. Design systems are now an industry standard used by the website teams of most major companies.
```
- [x]  Links:
- GitHub: https://github.com/hackforla/design-systems/projects/1
- Slack: Design-System](https://hackforla.slack.com/archives/CH2U1CB9Q
- [x]  Any resources for a Getting Started link (a link to a wiki, readme(s) or both):
   - Wiki: https://github.com/hackforla/design-systems/wiki
   - Overview: https://github.com/hackforla/product-management/blob/master/project-one-sheets/Design-Systems-One-Sheet.pdf
- [x]  ~What you are looking for skills wise: N/A~
- [x]  ~Partner(s): N/A~
- [x]  Location: Remote
- [x]  Status: Active
- [x] Program Area: Civic Tech Infrastructure

**Comment by adam-abundis** [comment]
Screenshots of the proposed changes

<details>
  <summary>Click here to screenshots of the proposed Design Systems project card</summary>
  <h3>Project card (desktop)</h3>
  <img src="https://user-images.githubusercontent.com/21162229/134635555-cad32989-cf87-4bac-bba3-6c3d0b8cdf3e.jpg" />
  <h3>Project card (mobile)</h3>
  <img src="https://user-images.githubusercontent.com/21162229/134635379-c61c51cd-4d1f-4c28-b904-fd3f53781c75.jpg" />
</details>

<details>
  <summary>Click here to screenshots of the proposed Design Systems project profile</summary>
  <h3>Design Systems project profile (desktop)</h3>
  <img src="https://user-images.githubusercontent.com/21162229/134635871-f6708a4c-926f-4abd-9883-5dcd6433503b.png" />
  <h3>Design Systems project profile (mobile)</h3>
  <img src="https://user-images.githubusercontent.com/21162229/134635804-83cc8f84-6fea-4a2f-867b-659567392378.png" />
</details>

**Comment by adam-abundis** [comment]
Update
1. Completed changes. Awaiting approval from @hannahlivnat to complete PR
2. Just awaiting PM approval
3. Will be available Sunday/Monday to complete this
4. By the end of next week.

**Comment by Hanastevenson** [comment]
Hi @abuna1985 

Thanks for the update. The project card works. The Project profile needs some adjustment. In the current screen shot provide by you there seems to be little padding from the top of the artwork to the navigation.

Please see below the preferred layout. I've left in the bounding box to illustrate. The artwork size needs to be reduced to align with the sides of the 'project overview' white boxes underneath.
<img width="882" alt="Screenshot 2021-09-24 at 14 41 59" src="https://user-images.githubusercontent.com/6236085/134742999-3651533a-a173-4110-9626-3cea8cbcca5f.png">

**Comment by Hanastevenson** [comment]
@ExperimentsInHonesty Do we need to review the copy? Highlighting the fact this initiative goes across 20+ product teams?

**Comment by abuna1985** [comment]
@Hanastevenson The profile page styling is prebuilt for all projects. If we change the styling for the specific project page, it would affect all project pages.

**Comment by ExperimentsInHonesty** [comment]
@Hanastevenson i think we took this text from the one sheet. Maybe we should revisit both.

**Comment by adam-abundis** [comment]
@Hanastevenson For the background picture, we may need to have the picture shrunk down and transparent space around it to align the photo and the content box below. The current styling is that the photo stretches the full width of the page for all project info pages.

**Comment by Hanastevenson** [comment]
@abuna1985 are you able to provide the dimensions so @ahoang94 can re-format the project header?
We have an Issue for reformatting. https://github.com/hackforla/design-systems/issues/123

**Comment by adam-abundis** [comment]
@Hanastevenson My apologies for the delay. The dimensions for the hero will stay the same as the current image @ahoang94 (1500x700). We just need to add space between the image and border to match the text alignment.

**Comment by adam-abundis** [comment]
Update
1. Waiting for an updated hero image with extra space between the content and border. Will implement and provide updated screenshots when available.
2. Just need an updated image from @ahoang94 (My apologies for the delay in this update)
3. Will be available Tuesday and Thursday Afternoon
4. ETA 7-10 days.

**Comment by ahoang94** [comment]
@abuna1985 New image files in PNG and SVG format have been saved to the "Branding and Assets" folder. I have resized the header artwork so that the primary image matches the width of the white content boxes that are to show below, but please advise if the Developer team has determined a suggested measurement for the top & bottom margins.

**Comment by adam-abundis** [comment]
@ahoang94 Where is the path to the 'Branding and Assets' folder? Could you provide a direct link to the image?

**Comment by ahoang94** [comment]
@abuna1985 Apologies, I thought you had access to the folder. 

SVG: https://drive.google.com/file/d/1C5SWxzXOOYAD72XSMcDCBCc27Z0VbVSG/view?usp=sharing
PNG: https://drive.google.com/file/d/1aoukvj0QbBcBs8nlzgJuzcNYwDu4uYFC/view?usp=sharing

**Comment by ExperimentsInHonesty** [comment]
@abuna1985 Can we get a PR in for adding the design systems team to the website today?

**Comment by adam-abundis** [comment]
@ExperimentsInHonesty @Hanastevenson Thank you so much for your patience. My apologies for the delay. I have submitted pull request #2365. I will also attach screenshots below for you to see the final changes made.

<details>
 <summary>Project Card/Page final version (<strong>desktop</strong>)</summary>
  <h3>Hack for L.A. projects design systems page - desktop version</h3>
  <img alt="Hack for L.A. projects design systems page - desktop version" src="https://user-images.githubusercontent.com/21162229/136894703-5e9c71d7-09e4-4fae-b12b-017e29726ffc.png" />
  <h3>Hack for L.A. projects design systems card - desktop version</h3>
  <img alt="Hack for L.A. projects design systems card - desktop version" src="https://user-images.githubusercontent.com/21162229/136894662-927a96f3-d549-4639-a423-45e9aa3332cc.jpg" />
</details>

<details>
  <summary>Project Card/Page final version (<strong>mobile</strong>)</summary>
  <h3>Hack for L.A. projects design systems page - mobile version</h3>
  <img alt="Hack for L.A. projects design systems page - mobile version" src="https://user-images.githubusercontent.com/21162229/136895239-841c8251-a635-463d-a5a0-05c5ce23204d.png" />
  <h3>Hack for L.A. projects design systems card - mobile version</h3>
  <img alt="Hack for L.A. projects design systems card - mobile version" src="https://user-images.githubusercontent.com/21162229/136895204-3fe78d2c-aeaa-4908-a443-074a39e82a4a.jpg" />
</details>

Let me know if you have any questions. 👋 👋 👋

**Comment by Hanastevenson** [comment]
@abuna1985 @ExperimentsInHonesty  
Hi Adam, 
Thank you for the update. One small query, on the mobile design are you able to shift the H1 down so there is less padding between the H1 and the card? I understand this may be an extra ticket as it could affect all other project cards, please proceed.

**Comment by ExperimentsInHonesty** [comment]
@abuna1985 does not seem connected to the repo because its not showing "All Time Contributors" section
see https://www.hackforla.org/projects/design-systems

![image](https://user-images.githubusercontent.com/37763229/137647187-5f24dcea-1928-41ba-a7e4-2548807b396b.png)

**Comment by adam-abundis** [comment]
@hackforla/website-merge reopening this issue to make edits and get all-time contributors added

**Comment by adam-abundis** [comment]
Reopening for 1 more round of edits

**Comment by adam-abundis** [comment]
@Hanastevenson Can you please add the following topic to the Design Systems repository (https://github.com/hackforla/design-systems):

* `hack-for-la`

**Note:** I have included [a link for an article from GitHub on how to add topics](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics)

This will help when we are collecting the data from your repo for the project details page.

Thank you! 👋 👋 👋
