### ISSUE TITLE
Create a project card for Undebate

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#226]
### Overview
The Undebate project needs to be added to the website

### Action Items
Add new undebate.md file to hackforla.org website, populated with the info for the project
Make sure you use the last image posted, not the prior image.

### Resources/Instructions
[Collateral](https://github.com/EnCiv/undebate/issues/23)

**Comment by ExperimentsInHonesty** [comment]
@KianBadie please post a screen shot of what the card looks like on your computer into this issue.

**Comment by KianBadie** [comment]
@ExperimentsInHonesty oh yeah I can do that, sorry about that. I'll try to do that along with my post next time before I make a pull request.

**Comment by KianBadie** [comment]
![Screenshot from 2020-01-02 20-51-00](https://user-images.githubusercontent.com/18221058/71707837-b5205100-2da1-11ea-8851-e8f5c3e8cfc3.png)
