### ISSUE TITLE
Change description text for CoP URL on Getting Started PAge

### ISSUE THREAD

**Issue by sheltoG** [hackforla/website#2268]
### Overview
We need to change the description text for a URL on the Getting Started Page. 

Currently the text on the page is as follows:
[Join your Community of Practice's Slack channel](https://www.hackforla.org/communities-of-practice) for access to announcements, meeting zoom links, and helpful resources.

We need to update it to:
[Join your Community of Practice ](https://www.hackforla.org/communities-of-practice) for access to announcements, meeting zoom links, and helpful resources.

### Action Items

- [ ] Replace text for the URL
- [ ] Test and verify the Getting Started page shows the updated link text

### Resources/Instructions
https://www.hackforla.org/getting-started
https://github.com/hackforla/website/blob/a159ab43e798007daa61f334d2c4a810560e8c26/pages/getting-started.html#L103-L104

**Comment by Aveline-art** [comment]
@robertestrada If you are actively working on this, please move it to the in progress column after assignment. Thank you!

**Comment by robertestrada** [comment]
Understood, thank you for the direction!
