### ISSUE TITLE
Fix header bug

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2269]
### Overview
We need to fix a bug that has crept into the site on some of the headers so that they go back to being consistent with the design systems for the website.

### Details of where to find the bug 
https://www.hackforla.org/communities-of-practice
https://www.hackforla.org/about/
https://www.hackforla.org/join
https://www.hackforla.org/project-meetings

### Resources/Instructions
<details>
<summary>Image of what it looks like currently</summary>

![image](https://user-images.githubusercontent.com/37763229/133512589-f99778b4-610e-442f-9d09-f655df3a2f48.png)

</details>

<details>
<summary>Image of what it should look like</summary>
  
![image](https://user-images.githubusercontent.com/37763229/133512730-eebc109c-693a-4903-95e9-2b71e1411e9e.png)

</details>

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge On some recent merge, a few pages headers got broken. Please add a size to this issue and assign it immediately.

**Comment by Aveline-art** [comment]
@glenflorendo Are you still working on #1892? If not, it needs to go back into the backlog before you can take a second issue, unless it involves collaborative work.
