### ISSUE TITLE
Reconcile issues not showing up on any project board

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#227]
### Overview
There are open issues that are not on the project boards.

### Action Items

- [ ] review the missing issues
- [ ] assign them to the appropriate boards, or close them.

### Resources/Instructions
Go to this [url](https://github.com/hackforla/website/issues?utf8=%E2%9C%93&q=no%3Aproject+type%3Aissue+is%3Aopen) to see all issues that are not on any project board.

**Comment by ashlingam** [comment]
Not sure why I overlooked this. I've reviewed the open issues from the list you linked and closed or assigned them to project boards as appropriate. Thank you @ExperimentsInHonesty
