### ISSUE TITLE
Add Program Area: Green Earth OS

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2271]
### Overview
We need to add program area information to the Green Earth OS project so that it will show up when we add the program areas filter.

### Action Items
- [ ] Review the project.md file model in the Resources section
- [ ] Add the following text to the file indicated in the Resources section
- [ ] See visual changes on the [Projects page's](https://www.hackforla.org/projects/) Green Earth OS card.
  <details>
    <summary>Here is where you will see changes:</summary>
    <img width="253" alt="Green-Earth-OS" src="https://user-images.githubusercontent.com/31293603/150218485-8281ef0a-d79c-4664-a7ee-c9e2d0e6d9d0.png">
  </details>
```
program-area:  
    - Environment
```

### Resources/Instructions
- File location to make the change: _projects/green-earth-os.md

- URL for UAT to check the page has been changed: https://github.com/hackforla/website/blob/gh-pages/_projects/green-earth-os.md

- [Model for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

- Link to [Projects page](https://www.hackforla.org/projects/)

**Comment by macho-catt** [comment]
@abuna1985 and I discussed that we'll modify the "program area" text to "programs" as a result of "program areas" not being valid html attribute name due to spacing. This is in regards to fixing #2076 and addressed in PR #2259.
Modifying the action item of this issue as a result.

**Comment by scarter31191** [comment]
Availability for this week: 3/14, 3/15, 3/16
My estimated ETA for completing this issue: 3/14

**Comment by scarter31191** [comment]
for this issue am I just adding `program-area:  - Environment` to the `green-earth-os.md` file? or am I making it visible on the card?

**Comment by JessicaLucindaCheng** [comment]
@scarter31191 To the green-earth-os.md, you are just adding 
```
program-area:  
    - Environment
```
After adding that, you should see the changes on the card because the code for making it visible already exists. If you don't see it, try the instructions in [2.7.b.i. What if you cannot see your changes locally within Docker? in CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-what-if-you-cannot-see-your-changes-locally-within-docker).
