### ISSUE TITLE
Add Program Area: Jobs for Hope

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2272]
### Overview
We need to add program area information to the Jobs for Hope project so that it will show up when we add the program areas filter.

### Action Items
- [ ] Review the project.md file model in the Resources section
- [ ] Add the following text to the file indicated in the Resources section
```
program-area:  
    - Social Safety Net
```

### Resources/Instructions
File location to make the change: _projects/jobs-for-hope.md

URL for UAT to check the page has been changed: https://github.com/hackforla/website/blob/gh-pages/_projects/jobs-for-hope.md

[Model for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

**Comment by macho-catt** [comment]
@abuna1985 and I discussed that we'll modify the "program area" text to "programs" as a result of "program areas" not being valid html attribute name due to spacing. This is in regards to fixing #2076 and addressed in PR #2259.
Modifying the action item of this issue as a result.

**Comment by ExperimentsInHonesty** [comment]
This seems like a duplicate issue for https://github.com/hackforla/website/issues/2384
