### ISSUE TITLE
Add Program Area: New Schools Today

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2273]
### Overview
We need to add program area information to the New Schools Today project so that it will show up when we add the program areas filter.

### Action Items
- [x] Review the project.md file model in the Resources section
- [x] Add the following text to the file indicated in the Resources section
```
program-area:  
    - Diversity, Equity & Inclusion
```

### Resources/Instructions
File location to make the change: _projects/new-schools-today.md

URL for UAT to check the page has been changed: https://github.com/hackforla/website/blob/gh-pages/_projects/new-schools-today.md

[Model for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

**Comment by macho-catt** [comment]
@abuna1985 and I discussed that we'll modify the "program area" text to "programs" as a result of "program areas" not being valid html attribute name due to spacing. This is in regards to fixing #2076 and addressed in PR #2259.
Modifying the action item of this issue as a result.

**Comment by BrianCodes33** [comment]
Looks like this has already been worked on? 
<img width="403" alt="Screen Shot 2022-01-19 at 9 52 11 AM" src="https://user-images.githubusercontent.com/13526442/150187621-ec3b924a-4f9c-440c-86f8-04e26864de87.png">

**Comment by Sparky-code** [comment]
ETA: EOD Thursday, 2/24/22
Availability: 4-6hrs across weekday evenings

**Comment by Sparky-code** [comment]
Progress: Completed pending a re-review. cleared and updated docker/browser to reflect visual changes in screenshots
Blockers: An error with the docker cache led me to believe this issue didn't have visual changes.
Availability: ~3hrs avail this weekend, monitoring this issue for review
ETA: Friday EOD, pending review
