### ISSUE TITLE
Add Program Area: Adopt Civic Art

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2275]
### Overview
We need to add program area information to the Adopt Civic Art project so that it will show up when we add the program areas filter.

### Action Items
- [x] Review the project.md file model in the Resources section
- [x] Add the following text to the file indicated in the Resources section
```
program-area:  
    - Citizen Engagement
```

### Resources/Instructions
File location to make the change: _projects/adopt-civic-art.md

URL for UAT to check the page has been changed: https://github.com/hackforla/website/blob/gh-pages/_projects/adopt-civic-art.md

[Model for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

**Comment by Zhu-Joseph** [comment]
Progress: Started updating info
Blockers: None so far
Availability: Random hours here and there
ETA: By next week

**Comment by macho-catt** [comment]
@abuna1985 and I discussed that we'll modify the "program area" text to "programs" as a result of "program areas" not being valid html attribute name due to spacing. This is in regards to fixing #2076 and addressed in PR #2259.
Modifying the action item of this issue as a result.

**Comment by macho-catt** [comment]
@Zhu-Joseph please note the above change for your PR. Thanks!
