### ISSUE TITLE
Add Program Area: Curbmap

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2277]
### Overview
We need to add program area information to the Curbmap project so that it will show up when we add the program areas filter.

### Action Items
- [x] Review the project.md file model in the Resources section
- [x] Add the following text to the file indicated in the Resources section
```
program-area:  
    - Citizen Engagement
```

### Resources/Instructions
File location to make the change: _projects/curbmap.md

URL for UAT to check the page has been changed: https://github.com/hackforla/website/blob/gh-pages/_projects/curbmap.md

[Model for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

**Comment by macho-catt** [comment]
@abuna1985 and I discussed that we'll modify the "program area" text to "programs" as a result of "program areas" not being valid html attribute name due to spacing. This is in regards to fixing #2076 and addressed in PR #2259.
Modifying the action item of this issue as a result.

**Comment by answebdev** [comment]
ETA: End of day 2/20/2022
Availability: Saturday (2/19/2022) (3 hours) Sunday (2/20/2022)
