### ISSUE TITLE
Add new project to website: Civic Tech Jobs

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2287]
### Dependency
~Waiting on Civic Tech Jobs team to complete gathering of assets https://github.com/hackforla/CivicTechJobs/issues/36~

### Overview

We need to add a new project to the hack for la website so that our project list can be current

### Project Details
- Name: Civic Tech Jobs
- Name of future project.md file: civic-tech-jobs.md
- Files you will need to upload to the website repository: civic-tech-jobs.jpg and civic-tech-jobs-hero.jpg
- Where you will store the files:
   - images go in this folder: /assets/images/projects
   - project.md file goes in this folder: _projects

### Action Items
- [x] Take the content listed here and create a new project.md card (skip anything that has strikethrough)
- [x] Download the images
- [x] Add both project card and images to appropriate folders
- [x] Once you have it working on your local environment
  - [x] Take screen shots of the project card on the homepage and the projects project page adding them to issue
   - [x] Reach out to the product manager to ask if they are satisfied by adding a comment to [this issue](https://github.com/hackforla/CivicTechJobs/issues/36) with a link to the screenshots on your issue
- [x] Submit pull request
- [ ] Let Product Manager know when its live

### Resources
[Template for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

#### Content of the project.md card
- [x] A link to the [600 x 400 image](https://user-images.githubusercontent.com/37763229/149637447-2d336d29-e615-44df-82e4-b92a8ade7455.png)
- [x]  Alt image text - 'Hack for LA logo and the title of the project, Civic Tech Jobs'
- [x]  A link to the [1500 x 700 hero image](https://drive.google.com/file/d/1fCbocnGqLuw2fkKeAi3Ke0UVFo3qXaqE/view?usp=sharing) 
- [x]  Name of project: Civic Tech Jobs
- [x]  A blurb about your project:

> The CivicTechJobs.org MVP website will be a platform to help prospective volunteers find inter disciplinary projects that will be useful for their career development while contributing to positive civic impact and a CMS for Hack for LA projects to be able to list their open roles.
> 
> The tool will match volunteers by availability, role, and program area. Future iterations of the platform will focus helping volunteers find volunteer opportunities that match paid job postings, so that a volunteer can better prepare themselves for the marketplace.
- [x] Team members: (see comment below): https://github.com/hackforla/website/issues/2287#issuecomment-1019559014
- [x]  Links:
- GitHub: https://github.com/hackforla/civictechjobs
- Slack: [CivicTechJobs](https://hackforla.slack.com/messages/C02509WHFQQ)
- [x]  Any resources for a Getting Started link (a link to a wiki, readme(s) or both):
   - Wiki: 
   - Overview: [PDF](https://github.com/hackforla/product-management/blob/master/project-one-sheets/Civic-Tech-Jobs-One-Sheet.pdf)
- [x]  ~What you are looking for skills wise: N/A~
- [x]  ~Partner(s): N/A~
- [x]  Location: Remote
- [x]  Status: Active
- [x] Program Area: Civic Tech Infrastructure

**Comment by ExperimentsInHonesty** [comment]
Team members

Name: Syed Danish Imran
Role: Product Manager
Slack ID:U020Z27JB1S
GitHub handle: sdimran

Name: Sharad Gaurav
Role: Product Manager
Slack ID: U01RETBMLKS
GitHub handle:SharadGaurav7 

Name: Ava Li
Role: Full Stack Developer
Slack ID:U01B73XGCKV
GitHub handle: Aveline-art

Name: Sarah Williams
Role: Software Developer
Slack ID:U01S1S75NLW
GitHub handle: arghmatey

Name: Jen Chung
Role: UX/UI Designer
Slack ID:U02A6H5PVAA
GitHub handle: jenchuu

Name: Grace Lin
Role: UX/UI Designer
Slack ID:U02AE5H5BJ9
GitHub handle: graceerya

Name: Patty Costello
Role: UX Researcher
Slack ID:U01UTFC17L4
GitHub handle: patula006

Name: Stephanie G. Stahlberg
Role: UX Researcher
Slack ID:U02H06YBR7F
GitHub handle: stephaniestahlberg

Name: Helene Dendor
Role: UX Researcher
Slack ID:U02C41H7919
GitHub handle: dendorable

**Comment by Aveline-art** [comment]
Screenshots
---

[Project card desktop](https://user-images.githubusercontent.com/62368440/151217250-282ad5f8-74cc-4e8f-b491-efa1ae7477d5.png)
[Project card mobile](https://user-images.githubusercontent.com/62368440/151217487-b4900281-a0ef-412c-99d8-77784262ee76.png)


[Project page desktop](https://user-images.githubusercontent.com/62368440/151217676-b27355cc-e624-4f72-a287-90e2d53277cd.png)
[Project page mobile](https://user-images.githubusercontent.com/62368440/151217725-28a81979-4155-4507-92c9-4de59b30bf67.png)
