### ISSUE TITLE
Add new project to website: Tech Work Experience

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2288]
### Dependency
- https://github.com/hackforla/internship/issues/248

### Overview

We need to add a new project to the hack for la website so that our project list can be current

### Project Details
- Name: Tech Work Experience
- Name of future project.md file: tech-work-experience.md
- Files you will need to upload to the website repository: 
   - tech-work-experience.png
   - tech-work-experience-hero.png
- Where you will store the files:
   - images go in this folder: /assets/images/projects
   - project.md file goes in this folder: _projects

### Action Items
- [x] Take the content listed here and create a new project.md card (skip anything that has strike-through)
- [x] Download the images
- [x] Add both project card and images to appropriate folders
- [x] Once you have it working on your local environment
  - [x] Take screen shots of the project card on the homepage and the projects project page adding them to issue
   - [x] Reach out to the product manager to ask if they are satisfied by adding a comment to [this issue](https://github.com/hackforla/internship/issues/57) with a link to the screenshots on your issue
- [x] Submit pull request
- [ ] Let Product Manager know when its live (by @ messaging them in this issue)
```
@priyatalwar
```

### Resources
[Template for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

#### Content of the project.md card
- [x] A link to the [600 x 400 image]
- [x]  Alt image text - 'Tech Work Experience'
- [x]  A link to the [1500 x 700 hero image] 
- [x]  Name of project: Tech Work Experience
- [x]  A blurb about your project:
```
The Tech Work Experience project is a structured summer internship program for college and high school students to work on open source projects in the fields of software, product development, project management, and UI/UX design at LA’s fastest growing Civic Tech non-profit organization in order to gain confidence, competence and deliverables to support their future career and personal journeys.

```
- [x]  Links:
- GitHub: https://github.com/hackforla/intership
- Slack: [Internship](https://hackforla.slack.com/messages/C01VAUPU788)
- [x] Any resources for a Getting Started link (a link to a wiki, readme(s) or both):
   - Wiki: https://github.com/hackforla/internship/wiki
   - Overview: 
      - future location will be: assets/pdfs/Tech-Work-Experience-One-Sheet.pdf
      - currently location (to copy from): https://github.com/hackforla/product-management/blob/master/project-one-sheets/Tech-Work-Experience-One-Sheet.pdf
- [x] leadership: this should be updated right before this issue gets worked on.  The project team keeps this up to date: https://github.com/hackforla/internship/wiki/The-Team#current-team
- [x] Partners (don't list any)
- [x] Location: Remote
- [x] Status: Active
- [x] Program Area: Workforce Development
- [x] Tools: Figma, Miro, Otter.ai, Zoom, Calendly, LinkedIn, 1password, GitHub Wiki, Google Workspace (Sheets, Docs, Forms, Mail Merge, Calendar) Google Data Studio

#### Related issue
- https://github.com/hackforla/internship/issues/57

**Comment by epierotti3** [comment]
![Hero Sample 12](https://user-images.githubusercontent.com/44823677/175969451-fb04aca8-87d7-4236-9d65-04c96484d8c6.png)

**Comment by ExperimentsInHonesty** [comment]
![Project Card](https://user-images.githubusercontent.com/44823677/176914496-545eb0fb-d84d-411e-9710-308b3e7ca6ff.png)

**Comment by ExperimentsInHonesty** [comment]
URL for one where to find the one sheet https://github.com/hackforla/product-management/blob/master/project-one-sheets/Tech-Work-Experience-One-Sheet.pdf

**Comment by RyanGehris** [comment]
ETA: EOD 03/24/2023
Availability: 6pm-10pm PST M-F

**Comment by RyanGehris** [comment]
ETA: EOD 03/28/2023
Availability: 6pm-10pm PST M-Th

**Comment by roslynwythe** [comment]
Hi @ftblmagician thank you for taking up this issue.  When you assign an issue, please move it to the In Progress Column.

**Comment by ftblmagician** [comment]
i. Availability: 8:30 - 9:30 4/9
ii. ETA: 4/19

**Comment by ftblmagician** [comment]
Fixes #2288

### What changes did you make and why did you make them ?
A new Tech Work Experience project.md card was added in the _projects folder The image and hero image files were also added to the /assets/images/projects folder. The new project makes the hack for la website project list current.

### Screenshots of Proposed Changes Of The Website  (if any, please do not screen shot code changes)

[Tech-Work-Experience.pdf](https://github.com/hackforla/website/files/11201835/Tech-Work-Experience.pdf)

**Comment by ftblmagician** [comment]
Hello @cbutcher318 @priyatalwar

Do the screenshots satisfy the project requirements?

Thank you

**Comment by ExperimentsInHonesty** [comment]
@ftblmagician Sorry for the delay.  The internship team didn't see you message.

I am moving this to the questions and review column so that it does not get lost again.

If you are still interested in working on this, @robinelayn will be providing a new image for the hero by the end of the week

<details>
<summary>project card</summary>

![image](https://github.com/hackforla/website/assets/37763229/d7dbaef8-d4a6-44fc-9d0c-8261e2f570d5)
</details>

<details>
<summary>hero we are replacing</summary>

![image](https://github.com/hackforla/website/assets/37763229/8fb8f17a-c28e-4d7a-8359-0485b5646e87)
</details>

**Comment by RobinElayn** [comment]
[TWE Hero for HfLA TWE Website ](https://www.figma.com/file/TTRS2FWXsrymHYpPJL1IdH/Internship-Team-Main-file?type=design&node-id=2859-40269&t=1rNwG7wyzLDYTsf8-4)

![HfLA_TWEProject_Hero ](https://github.com/hackforla/website/assets/124115511/717d9cd7-d83a-4fcc-9158-4e12666c0093)

**Comment by ExperimentsInHonesty** [comment]
@ftblmagician are you going to be able to finish this issue?

**Comment by ExperimentsInHonesty** [comment]
@ftblmagician please make the changes asked for in the pr.  You don't need to address anything else, except the changes asked for there.

As soon as your pr is accepted, we will make a new issue for the changes the team has requested here in the issue.

**Comment by adrianang** [comment]
- Availability: MTThFSS, 6 PM - 10 PM (PST) (Weeks of 6/26, 7/3)
- ETA: I plan on finishing this issue by Tuesday, 7/4 at 10 PM.

**Comment by adrianang** [comment]
**Update - July 2, 2023**
1. Progress
   - I was able to get the associated files (images and overview PDF) for Tech Work Experience, place them in their proper locations, and create a new markdown file for the project.
   - Currently running into a few blockers preventing me from moving forward with the action items (see below)...
2. Blockers
   1. **I can't see the project card for TWE on the homepage in my Docker** -- is there something that I should be doing to get it to show? The project page itself (/projects/tech-work-experience) is showing and can be accessed when I type its path, but the card is not showing up on the homepage (screenshots below, in _5. Photos_). For some reason, my Docker view is also missing all the filters to the side of the Current Projects on the homepage.
      - I've tried deleting `_site` and `.jekyll-metadata`, restarting with `docker-compose down` and `docker-compose up`, restarting my computer, editing/modifying other projects locally to test and see if those change on the homepage (they didn't...), and trying it on a different browser. 
   2. **Should the Current Team be in a specific order?** I noticed the Current Team linked in the TWE wiki is in (mostly) alphabetical order by first-name, but most of the other HfLA projects have it sorted in some hierarchy with role.
      - For my progress so far, I generally sorted it by role, then once roles seemed even, keeping the same order as the table in the TWE wiki, but was unsure exactly how project leads would like to proceed.
   3. **I'm missing a Slack ID for Bryan Dick** -- there were a few Bryans in the HfLA Slack channel, and I couldn't tell which one belonged to them.
3. Availability
   - Week of 7/2:
     - Sunday (7/2); Tuesday (7/4); Saturday(7/8): 10 AM - 10 PM PST
     - Monday (7/3); Thursday (7/6); Friday (7/7): 6 PM - 10 PM PST
6. ETA
   - I'd still like to get my PR in by Tuesday, 7/4 at 10 PM if my blockers can be resolved before then! But if not, I may have to adjust this ETA later.

**Photos for Progress/Blockers**
<details>
<summary>Tech Work Experience Project Page (/projects/tech-work-experience)</summary>

![localhost_4000_projects_tech-work-experience](https://github.com/hackforla/website/assets/24426473/dd67f478-d706-4615-922d-2be2c2114eca)

</details>

<details>
<summary>Main Page (Tech Work Experience Project Card not showing up)</summary>
  
![localhost_4000_-web](https://github.com/hackforla/website/assets/24426473/44cd832e-b64c-4f67-8b21-6eb63b446b6d)

</details>

**Comment by ExperimentsInHonesty** [comment]
@adrianang 

The order of the people is perfect.

Please take me off the team list.

Not sure why the card is not showing up,  I will add a ready for dev lead label, and you should come to the team meeting happening in 16 min to troubleshoot live.

**Comment by priyatalwar** [comment]
@adrianang In response to your slack message, the tag has been added. Please let me know if you have any questions. Thanks!

**Comment by chrismenke45** [comment]
@priyatalwar PR #4911 4911 has been merged
