### ISSUE TITLE
Add new project to website: Guides Team

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2289]
### Dependency
<del>https://github.com/hackforla/guides/issues/38</del>

### Overview

We need to add a new project to the hack for la website so that our project list can be current

### Project Details
- Name:  Guides Team
- Name of future project.md file: guides-team.md
- Files you will need to upload to the website repository: guides-team.jpg and guides-team-hero.jpg
- Where you will store the files:
   - images go in this folder: /assets/images/projects
   - project.md file goes in this folder: _projects

### Action Items
- [x] Take the content listed here and create a new project.md card (skip anything that has strikethrough)
- [x] Download the images
- [x] Add both project card and images to appropriate folders
- [x] Submit pull request
- [x] Let Product Manager know when its live (by posting in their issue)

### Resources
[Template for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

#### Content of the project.md card
- [x] A link to the 600 x 400 image: https://user-images.githubusercontent.com/37763229/134694971-836863d6-f445-4b8f-9d28-6974867f86e2.jpg
- [x] Alt image text - 'Globe Map made of dots and hackforla logo and text reading Guides Team'
- [x] A link to the 1500 x 700 hero image: https://user-images.githubusercontent.com/37763229/134694967-fb336994-8eea-46f8-8136-7dd8e6109cb5.jpg
- [x] Name of project: Civic Tech Guides
- [x] A blurb about your project:
```
The Hack for LA Guides Team project is creating guides and templates from the effective practices that HfLA has developed and iterated from our projects. HfLA Guides aim to share replicable processes and practices from Engineering, UI/UX, Product Management, Data Science, Marketing Fundraising, DevOps, Admin, and Professional Development. The project seeks to further grow HfLA’s peer learning and iterative culture, and ultimately improve outcomes for the entire civic tech ecosystem.

```
- [x]  Links:
- GitHub: https://github.com/hackforla/guides
- Slack: [Guides](https://hackforla.slack.com/archives/C028T9XU9S5)
- [x] Any resources for a Getting Started link (a link to a wiki, readme(s) or both):
   - Overview: https://github.com/hackforla/product-management/blob/master/project-one-sheets/Guides-Team-One-Sheet.pdf
- [x] ~What you are looking for skills wise: N/A~
- [x] Partners: N/A
- [x] Location: Remote
- [x] Status: Active
- [x] Program Area: Civic Tech Infrastructure

**Comment by adam-abundis** [comment]
@ExperimentsInHonesty Made comment of an updated project page in https://github.com/hackforla/guides/issues/38

Issue tasks have now been completed.

**Comment by ExperimentsInHonesty** [comment]
@abuna1985 Please remove the N/A from partners
