### ISSUE TITLE
Convert Project Profile Card review and update Template to Github Form Issue

### ISSUE THREAD

**Issue by adrian-zaragoza** [hackforla/website#2292]
### Overview
As an issue creator, we want to implement issue templates for issue creation to streamline and simplify the process. The current issue forms require the person to replace the text, and is less user-friendly compared to GitHub Form issues.

### Action Items
- [x] Define the form elements and their behavior
  - [x] Review with product and Front End Lead
- [x] Create a project-profile-card-review-and-update.yml file in your own fork in: ```gh-pages/.github/ISSUE_TEMPLATE```
- [x] Follow github form syntax readings below to code a similar form to the [current issue template](https://github.com/hackforla/website/issues/new?assignees=&labels=&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D).
- [x] Get Signoff by Product on the proposed template before making a PR
- [x] Delete project-profile-card-review-and-update.md file in [this folder](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)

### Resources/Instructions
[Current Issue Template Code File](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.md)
[Github Forms Issue Reading](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
[Github Forms Issue Reading Pt 2](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)
#2128 

To get signoff from product: put your issue in the Review column on the project board.

**Comment by MattPereira** [comment]
Availability: 10 AM - 2 PM
ETA: 10/23/22

**Comment by MattPereira** [comment]
## **Form Elements & Behavior**
### **Overview** 
- `type: markdown` | Description of issue that will be created using this GitHub form
### Project Name
- A `type: dropdown`  list of all HFLA project names
### Project Card URL
- A `type: dropdown`  list of all the file names in the https://github.com/hackforla/website/tree/gh-pages/_projects/ folder 
### Title, Image, Links, and Meeting Times
- Start with a _yes or no_ `type:dropdown` followed by a `type:input` to be used only if the answer to the matching dropdown was _yes_

### Description, Technologies, Partners, Tools, and Leadership
- Start with a _yes or no_ `type:dropdown` followed by a `type:textarea` to allow for extra input space. Also only to be used if the answer to the matching dropdown was _yes_


### Status
- `type: dropdown` | `required: true` Status can be either Active, Completed, or On Hold

[Proposed GitHub Form Link](https://github.com/MattPereira/website/blob/convert-project-profile-card-2292/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml)

**Comment by 7kram** [comment]
Our product team needs updates to the project card. Once you're ready for us to user test the feature, here are the changes that we will be making:

### People to Remove
Phuong Van
Sakari Salminiitty

### People to Add
Name: Sijia Pitts
* GitHub handle: sijiapitts
* Role: Senior Designer
* SLACK ID: U03CBK89KUY

**Comment by MattPereira** [comment]
Thanks for the update @7kram ! :+1: 

Here is a link to the current state of the new form: [Proposed GitHub Form](https://github.com/MattPereira/website/blob/convert-project-profile-card-2292/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml)

Are you able to handle approval of this template so that I can complete the following action item on this issue?

>  Get Signoff by Product on the proposed template before making a PR

**Comment by MattPereira** [comment]
Ready for research to test with project managers : [Link to Project Profile Card Review & Update](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D)

**Comment by ExperimentsInHonesty** [comment]
- have added an item to the next pm agenda to address https://github.com/hackforla/website/issues/2212#issuecomment-1464052635
- made an ER https://github.com/hackforla/website/issues/4246
