### ISSUE TITLE
Ensure that all project links are included in the project page

### ISSUE THREAD

**Issue by sheltoG** [hackforla/website#2296]
### Overview
We need to make sure the same links are available on both the project card and project page to 

<details>
  <summary>Current project card (100 automation) - 4 links</summary>
  <h3>An example that highlighs links within project card</h3>
  <img alt="project card example" src="https://user-images.githubusercontent.com/36433204/134233503-65ff9bdd-cff7-4b10-b647-03b8315dd192.png" />
</details>

<details>
  <summary>Current project page (100 Automation) - 1 link</summary>
  <h3>Notice one link is available in the page instead of 4</h3>
  <img alt="project page example" src="https://user-images.githubusercontent.com/36433204/134233538-7a3217ee-e64b-4090-8532-277fb5fe72bd.png" />
</details>

### Action Items

- [x] Review [line 32-55 of _layouts/project.html](https://github.com/hackforla/website/blob/6b3d76fffa1476f2d17a39440da3ada82d4a4c21/_layouts/project.html#L32-L55)
- [x] Refactor the code so that a list of links similar to the project card (comma separated) show up on the project page
- [x] Verify the project card and project page provide a similar list of links (comma separated)
- [x] Create a pull request for final review

### Resources/Instructions
- Projects Page: https://www.hackforla.org/projects/
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/6b3d76fffa1476f2d17a39440da3ada82d4a4c21/_layouts/project.html#L32-L55

#### Backround information about the Jekyll framework (optional reading)
[Liquid docs - iteration (for loops)](https://shopify.github.io/liquid/tags/iteration/)
[Liquid docs - control flow (if/elseif/else)](https://shopify.github.io/liquid/tags/control-flow/)

**Comment by adam-abundis** [comment]
@sheltoG This is a super vague issue. How would one know to find the appropriate link if one is not given?

Maybe it would be better to have a checklist from each given project to ensure the person taking this issue is clear about what needs to be done.

**Comment by ExperimentsInHonesty** [comment]
100 Automations
Change Readme link
From: https://github.com/OpenSourceAutomations/OSA-Website/blob/master/README.md
To: https://github.com/100Automations/Website/blob/gh-pages/README.md

**Comment by lopezpedres** [comment]
Availability for this week:
Wed (12/8/2021): 10 AM - 3 PM
Sat (12/11/2021): 1 PM - 5 PM
Sun (12/12/2021): 10-2 PM

My estimated ETA for completing this issue:
Sunday (12/12/2021)
