### ISSUE TITLE
Create a new issue form for feasibility

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2298]
### Overview
As a developer, we want to standardize issue templates that are repeatedly used. For this issue, we will create an issue form template for feasibility related issues.

### Action Items

- [x] Create a feasibility-issue-template.yml file in [this folder](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)
- [x] This template needs the following fields:
  - [x] Title
  - [x] Dependency (a check box to indicate yes/no dependency, then an input for what it is if yes)
  - [x] Overview
  - [x] Action Items
  - [x] Feasibility Checklist
  - [x] Resources/Instructions
- [ ] The resulting issue should look like this [issue](https://github.com/hackforla/website/issues/2128#issue-973987353)

### Resources/Instructions
[Github Forms Issue Reading](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
[Github Forms Issue Reading Pt 2](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)

**Comment by jdingeman** [comment]
Availability: 4 hrs
ETA: EOD 7/27

**Comment by ExperimentsInHonesty** [comment]
Here is a link to open a new feasibility issue using the template created https://github.com/hackforla/website/issues/new?assignees=&labels=&template=feasibility-issue-template.yml&title=Standard+Feasibility+Issue+Template+
