### ISSUE TITLE
Create a new issue form for GitHub Actions

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2299]
### Overview
As a developer, we want to standardize issue templates that are repeatedly used. For this issue, we will create an issue form template for GHA-related issues.

### Action Items

- [x] Create a gha-issue-template.yml file in [this folder](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)
- [x] This template needs the following fields:
  - [x] Title
  - [x] Dependency (a check box to indicate yes/no dependency, then an input for what it is if yes)
  - [x] Overview
  - [x] Action Items/Psudo-code (optional)
  - [x] Checks (optional)
  - [x] Resources/Instructions
     - [x] a link to https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions
  - [x] Check box to indicate that this is to create a new GHA
    - [x] This checkbox, when checked, will add the staple instruction text (see below)
- [x] The resulting issue should look like this [issue](https://github.com/hackforla/website/issues/2206#issue-982258182)
  - [x] Be sure to pre-add the resources into this template

### Resources/Instructions
[Github Forms Issue Reading](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms)
[Github Forms Issue Reading Pt 2](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema)

<details>
<summary>staple instruction text</summary>
<br>
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)

Note that you might want to do something outside the scope of the above psudo-code. If so, be sure to leave comments in your PR or this issue that justifies your reasoning. If you feel you need guidance, be sure to reach out! We cannot foresee whether this issue is solvable, or what hard decisions have to be made, but we would love to hear and help you!
<br>
</details>

**Comment by arpitapandya** [comment]
Availability for this week: 6hrs
My estimated ETA for completing this issue: 5hrs

**Comment by arpitapandya** [comment]
Time spent: 1hr to complete
Availability: 6hrs for next week
Blockers: None, but I was confused whether the checkbox information I have used is correct? or I misunderstood

**Comment by arpitapandya** [comment]
Availability for this week: 6hrs
My estimated ETA for completing this issue: 5hrs

**Comment by ExperimentsInHonesty** [comment]
Sample new issue from the form https://github.com/hackforla/website/issues/new?assignees=&labels=&template=gha-issue-template.yml&title=Sample+form+for+GitHub+actions+
