### ISSUE TITLE
Return good first issue label to its original title

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2301]
### Overview
We need to rename the label "size: good first issue" back to the original wording back to "good first issue" so that we are using the standard Github tag

#### Details
GitHub promotes this label and other entities use like [Hacktoberfest](https://hacktoberfest.digitalocean.com/) use it when encouraging people to find open source projects to work on.

### Action Items
- [x] Identify what GHAs are relying on the changed version of the label "size: Good first issue"
- [x] change the label and update the GHA's via a PR.

### Resources/Instructions
[See text of conversation in slack](https://github.com/hackforla/website/issues/2301#issuecomment-925201665)
[Potentially related GHA](https://github.com/hackforla/website/issues/2301#issuecomment-925201665)

**Comment by ExperimentsInHonesty** [comment]
@macho-catt @Aveline-art I am moving this from a conversation in slack to this issue because this is now urgent.  Octoberfest planning kickoff meeting has just happened and none of our issues are going to qualify.  Please move any Slack DMed conversations you had to this issue and let's get this fixed asap.

Slack conversation from 2021-09-04

```
Bonnie  9:32 AM
@Ava Li (she/her/hers) someone has changed the good first issue label to "size: good first issue".  Before I change it back, can you let me know if it was done to make some automation work?  Reason  I will need to change it back, is that its a standard Github tag, that they promote and that other entities use like Hacktoberfest, when encouraging people to find open source projects to work on.

HacktoberfestHacktoberfest
Hacktoberfest presented by DigitalOcean
Open source is changing the world – one pull request at a time. (478 kB)
https://hacktoberfest.digitalocean.com/


Ava Li (she/her/hers)  9:55 AM
I am not sure if anyone had changed it. @Matthew Cacho, looking at the code, I think this might break this GHA. Any thoughts on how to fix this? I am thinking of replacing the regex searcher with a list of allowable labels.

check-labels.js
// Constant variables
const REQUIRED_LABELS = ['Size', 'role', 'Feature']
const LABEL_MISSING = ['size: missing', 'role missing', 'Feature Missing']

// Global variables
Show more
<https://github.com/hackforla/website|hackforla/website>hackforla/website | Added by GitHub

Matthew Cacho  9:59 AM
I'll check the code, I need some time to wake my brain up lol
:slightly_smiling_face:
1


Slackbot  10:00 AM
Reminder: Join the team meeting https://zoom.us/j/4451450308?pwd=U0JobzZqN0xGSXBUUkRsNlB5YzJiQT09

1 reply
17 days agoView thread

Matthew Cacho  12:21 PM
nvm, I talked to @Ava Li (she/her/hers) about this. I have a solution in mind that I will DM in private
:raised_hands:
1
```

**Comment by macho-catt** [comment]
I can fix this right now and open a PR.

**Comment by macho-catt** [comment]
@ExperimentsInHonesty the label can now be returned to "good first issue." Thanks

**Comment by Aveline-art** [comment]
Closed because the task is finished.
