### ISSUE TITLE
Wins Randomizer for homepage

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2304]
### Overview
We need a randomizer for the new homepage so that we can give visibility to different volunteer types.

### Action Items
- [ ] Provide which wins go in the wins randomizer (add names and screenshot to resources section)
  - [x] Front End
  - [x] Backend/Devops
  - [ ] PM
  - [x] Design
  - [x] Research
  - [ ] Business Analyst
  - [ ] Data Science
  - [ ] Content
  - [ ] Marketing
  - [ ] Operations
  - [ ] Q/A
  - [ ] Accessibility 
- [ ] Add a link to homepage issue #2317
- [ ] We need to reach out to people in the org who represent the practice areas missing.  See [sheet](https://docs.google.com/spreadsheets/d/1fXmYrmNtrgdzkM_odGIRbSwdaea3yS0cTLCJUzZ6Sc0/edit#gid=1301054877&fvid=2044070941) for details
  - [ ] PMs have submitted, I just have not chosen yet.
- [x] Make a new issue for Adding automation to Homepage Summary page of [Wins-form (responses)](https://docs.google.com/spreadsheets/d/1fXmYrmNtrgdzkM_odGIRbSwdaea3yS0cTLCJUzZ6Sc0/edit#gid=1301054877) so that we can stay on top of the outreach.

### Resources/Instructions
<details>
<summary>Developers Top 3 Wins (please pick 2/3)</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/134718529-c0a4dece-d633-4e91-8259-1142bb089251.png" width="900" length="450" />
<br>
</details>

**Comment by Aveline-art** [comment]
This is placed in questions and review to bring awareness to this, and to make sure that the last action item (linking this to the HPRe issue, will not be forgotten) should the HPRe issue be made.

**Comment by Basu3040** [comment]
Progress:  Callout of wins has been posted on the ui-ux slack channel!

**Comment by kristine-eudey** [comment]
Callout for UI-UX wins has been posted to the ui-ux slack channel in [this post](https://hackforla.slack.com/archives/C017ESHSMNG/p1633279435126900) and I will be contacting the CoP leads to ask them to call this out in the meetings and ask people to submit their wins.

**Comment by Basu3040** [comment]
Progress:  Call-out has been posted on ui-ux channel
Blockers: Waiting for people to respond

**Comment by kristine-eudey** [comment]
**UI-UX Progress:** Posted this call-out on the ui-ux channel:

> Hi ui-ux community! Are you a Hack for LA alum, or current member? Has Hack for LA had a positive impact on your career/community/life? If so, we would LOVE to know about it! We are currently working on a big redesign of the hackforla.org homepage and will be featuring our volunteers' wins. We want to feature more ui-ux wins specifically to speak more directly to the ui-ux community and get more folks from our discipline involved with the organization. Please help us, and help the ui-ux community more broadly, by Sharing your Wins! 
Thank you so much! :two_hearts:

I have also reached out directly to former members of our team to ask if they would be willing to submit a win. Will re-post on the ui-ux channel again today to try to drum up more submissions. 

**Blockers** People from ui-ux don't seem to be submitting many Wins so we only have the 4 currently on the site to choose from, 1 of which doesn't seem to actually be from a UX person, and the other 2 are pretty so-so. 

**ETA** I will make another Slack push / reach out to people directly / reach out to ui-ux CoP leads to plug this and have 2-3 chosen within 1 week (Oct. 21)

**Comment by Basu3040** [comment]
I have reached out to ui-ux alums of hfla via LinkedIn. Will keep you updated.

**Comment by Basu3040** [comment]
Progress: We have reached out to HfLA alumni.
Blockers: A few of the projects are missing and Kristine has created an issue for the developers.
Availability: We are dependent on the submission
ETA: TBD

**Comment by kristine-eudey** [comment]
I have reached out personally to 2 recent website team UX alums, Basu and Janie, who have both agreed to contribute their wins. They should be coming in shortly. Currently, there is 1 UI-UX win currently on the site that would be good on the homepage randomizer. Of the other 3, 1 is talking about the wins of the project rather than of the volunteer, 1 appears to be from someone who wasn't in UI-UX specifically, and the 3rd could work in a pinch but is a little vague. 

![Screen Shot 2021-11-01 at 4 45 29 PM](https://user-images.githubusercontent.com/16949503/139926971-fd14885d-45ce-4350-9a2f-7234cdb47898.png)
:

**Comment by kristine-eudey** [comment]
I've heard back from 2 UX team members that have recently submitted wins, but they are not yet live on the site. @ExperimentsInHonesty, once these are approved and go live to the site they can be added to the homepage randomizer.

**Comment by arghmatey** [comment]
I have added a column to the Wins-form (Responses) Google sheet. If wins are chosen to be on the homepage, the value of this column should be changed to "TRUE". I have already changed current wins to reflect the appropriate value. On approval of an incoming win, if it will not be featured on the homepage the value should be set to "FALSE" and visa versa.

**Comment by kristine-eudey** [comment]
I don't have access to the Wins-form (Responses) Google sheet, but the 2 UX wins we'd like to feature in the randomizer are by Thomas Philip Franklin II (shown above) and Basudhara Sen. Basudhara's was just submitted and approved on the sheet by Bonnie, though not yet on the live site so I can't screenshot it to add here.

**Comment by macho-catt** [comment]
There is a monthly trigger to update the wins, but I can manually trigger it.

**Comment by kristine-eudey** [comment]
Please include Janie Chen's win as a "Yes" on the randomizer, that will put us to 2 designers and 1 researcher being featured.

**Comment by ExperimentsInHonesty** [comment]
The randomizer got built during this pr https://github.com/hackforla/website/pull/2373/files

**Comment by ExperimentsInHonesty** [comment]
We need to open another issue to add it to the about page after the homepage launch.  issue will go into the icebox with the dependency of homepage launch

The issue should have a check box to reopen or re-evaluate this issue once its working, to see if we have even distribution of roles in the randomizer

**Comment by jdingeman** [comment]
Hey @ExperimentsInHonesty - issue made here
- https://github.com/hackforla/website/issues/4190

**Comment by ExperimentsInHonesty** [comment]
- Added ER https://github.com/hackforla/website/issues/4282
