### ISSUE TITLE
Create new gradient overlay for Projects pages

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2312]
### Overview
We need to create a new gradient for the hero-image overlay on Project pages so that it looks smooth and visually pleasing, and is applied consistently to Project page hero images. 

### Action Items

- Determine best format for this gradient (.svg, .png, etc) Consult with dev team if necessary to determine this. 
- Create new gradient in Figma, using standard desktop screen size and hero section dimensions as currently shown in the Figma design.
- Assess how this gradient will look on each of the Project page hero sections to make sure there won't be any issues. 

### Resources/Instructions
- [Project Page Example: 100 Automations](https://www.hackforla.org/projects/100-automations)
- [Figma - Project Description Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11346%3A42)

**- Current gradient, note the transition of tones/color is not smooth with visible breaks:**

![Screen Shot 2021-09-28 at 11 29 07 AM](https://user-images.githubusercontent.com/16949503/135118379-479334c2-e2c8-4a5c-8831-9eb787ec67ec.png)

**Comment by jenjen26** [comment]
**Progress:** Working on making gradient smoother in FIGMA
**Blockers**: Discussing format of final asset with Matt from dev team.
**Availability:** 5 hours
**ETA**: 12/4

**Comment by jenjen26** [comment]
Progress: Completed - ready to review with design team 12/2 meeting.
Blockers: Where best in design system documentation to place asset?
Availability: 
ETA: 12/2

Before:

![135118379-479334c2-e2c8-4a5c-8831-9eb787ec67ec](https://user-images.githubusercontent.com/64928677/144510404-0954cba7-7cf0-4df6-bc41-52db16999e3f.png)


After:
![Screenshot 2021-12-02 160536](https://user-images.githubusercontent.com/64928677/144510994-10c67174-b3ad-410c-9ad4-b06d217d6fe6.png)

**Comment by IsaacDesigns** [comment]
@jenjen26 there seems to have been a misunderstanding with this issue. The gradient looks great but we all we need is the gradient, not the background image. Please update and add in comment. Thank you!

**Comment by jenjen26** [comment]
@IsaacDesigns I am currently discussing with Matt from the dev team where best to place the final gradient overlay in the Figma files. Once we figure that out, I will update with the final gradient and location in the Figma file.

**Comment by jenjen26** [comment]
@IsaacDesigns 

Here is the asset: [Final Gradient](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18173%3A122891)

I placed the gradient in the [Project Description Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/?node-id=7891%3A0) in a box underneath the 'final version' outlined in pink.

**Comment by IsaacDesigns** [comment]
Looks good! Thanks!

**Comment by ExperimentsInHonesty** [comment]
Development will make a new issue for replacing the css with this
