### ISSUE TITLE
Develop Homepage Redesign

### ISSUE THREAD

**Issue by arghmatey** [hackforla/website#2317]
### Overview
We need to develop the new Homepage Redesign based on Figma file provided by design.

### Action Items

- [x] Develop the redesigned Home page
     - [x] Ensure applicable design system classes are applied throughout
     - [x] Add new icons on [credits page](https://www.hackforla.org/credits/)
     - [x] Move or create 'includes' files into home-page folder nested in the _includes folder
     - [x] Update program areas images
- [x] Develop mobile version of Home page

### Resources/Instructions
[Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15570%3A99833) (in pink rectangle)
[index.html](https://github.com/hackforla/website/blob/gh-pages/pages/index.html) - for home page architecture
[Credit folder](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits) & [credit.yml template](https://github.com/hackforla/website/wiki/Credits-yml-file-template)
Homepage Redesign - #2057
Design mobile version of new homepage - #2213

**Comment by arghmatey** [comment]
Progress: Almost all sections of homepage are developed and styled to be mobile responsive.
Blockers: Dependency on issue. Styling of communities of practice gradient may not be possible as is (researching and testing currently). Mobile version not completed yet, but [issue](https://github.com/hackforla/website/issues/2213) is created and being worked on.
Availability: 1 hour tomorrow morning (Saturday AM)
ETA: Based on blockers.

**Comment by arghmatey** [comment]
Progress: Updated technology section's mobile responsiveness. Created gradient for communities of practice section.
Blockers: Dependency on issue.
Availability: 2 hours on Monday 10/18.
ETA: Based on blockers.

**Next steps**: Create draft pull request. Create javascript logic for random win to be displayed on home page load and set up with the wins that have been chosen.

**Comment by arghmatey** [comment]
Connected with design regarding Program Areas images. The images I exported out of Figma are too small and appear grainy. Older versions of images were 360px, though show pixelated on the Program Areas page. I suggest they be imported at 900px width to insure they appear clear throughout the site.

**Comment by arghmatey** [comment]
Mobile design has been completed via #2213. New action item added to implement mobile designs.

**Comment by arghmatey** [comment]
Progress: Getting through mobile design. 
Blockers: Week became busy with interviews. Not all wins are chosen, but im going to move forward with the ones we have. Figured launch can happen with those chosen or fillers can be picked then replaced. 
Availability: A few hours on Sunday, then a large chunk of time on Monday. 
ETA: Wednesday 10/3

**Comment by arghmatey** [comment]
Creating homepage-launch-feature branch to use for pull request instead.

**Comment by arghmatey** [comment]
Development is complete. 

I need the homepage-launch-feature branch created as I wasn't able to create a parallel branch myself. The wins response edits also need to be pushed in order to display the chosen homepage wins.

**Comment by ExperimentsInHonesty** [comment]
@arghmatey We are still in the process of adding wins to the random list, but there are enough now to prove if it's working properly.  See this [sheet](https://docs.google.com/spreadsheets/d/1fXmYrmNtrgdzkM_odGIRbSwdaea3yS0cTLCJUzZ6Sc0/edit#gid=1301054877&fvid=2044070941) to know what should be appearing

**Comment by phuonguvan** [comment]
@JessicaLucindaCheng Hey! This is the design team lead and I was wondering if you are still working on this project. Bonnie told me to update you guys so let me know as soon as possible!

**Comment by JessicaLucindaCheng** [comment]
I'm reopening this issue because I still need to check if this issue has been completed or there are items that still need to be done

**Comment by JessicaLucindaCheng** [comment]
- Issue and pr review ETA to see where this issue is at: Wed, Mar 30

**Comment by JessicaLucindaCheng** [comment]
The homepage has been implemented completely but @JessicaLucindaCheng will make new issues to address the following:
- [x] Program Area images should be `alt=""` and is related to issue #2354. The alt text also impacts the images on the Program Areas page.
- [x] Infinity symbol should have a descriptive alt text.
- [x] Communities of Practice section images should have `alt=""` and remove `/` from the end of the img tag.
- [x] Delete line 13 and uncomment line 14 when about page is done. Need to add a dependency label and figure out what the issue before this one will be. Edit: This is the issue for it: #7689 https://github.com/hackforla/website/blob/467a797f7c9518fcb466b6bdd034de27050b838e/_includes/home-page/hero.html#L12-L13

**Comment by JessicaLucindaCheng** [comment]
@phuonguvan The Homepage has been implemented completely except for some alt text related changes that need to be made and can be addressed in separate issues. Thus, I'm closing this issue.
