### ISSUE TITLE
Gathering images to represent Civic Tech Infrastructure program area on homepage

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2328]
### Overview
We need to find an image which best represents the Civic Tech Infrastructure program area for the [new homepage design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16301%3A101535). 

### Action Items

- Do you have an idea for an open-source image which best represents Civic Tech Infrastructure?
- If so we'd love to see it! 
- Please post the image, along with a link in the comments below.

### Resources/Instructions
See all Civic Tech Infrastructure projects here: [Hack for LA  - Civic Tech Infrastructure ](https://www.hackforla.org/projects/?programs=Civic+Tech+Infrastructure)

**Comment by kristine-eudey** [comment]
**Progress:** Posted this call-out in Slack channels but didn't get any engagement with it/image submissions. I will search for images and come up with 3-5 alternate images for the team to consider. 

**Slack call-out:** 
Hi website team! The UX team is currently searching for a photo which best represents the Civic Tech Infrastructure program area for the new homepage and we would love your input! :camera_with_flash:
Can you think of an image, or type of image, which represents Civic Tech Infrastructure to you? If so we'd love your input in order to best represent this on the new homepage!
Please post the image (and link) to the comments in this issue.
Ideally the photo would be open source and available for our use on the site, but if not that's okay too in that it can help us generate ideas for the type of images which best represent this. All input helps! 

**Blockers**: No engagement in response to request for submissions, but in lieu of that I can do the image search and present the team with options. 
**Availability:** 1 hr this week, should not take longer than that. 
**ETA:** Thursday 10/14

**Comment by kristine-eudey** [comment]
### Civic Tech Infrastructure - New image options:
<details>
  <summary> Option 1</summary>
  
  ## Option 1
![jacek-dylag-nhCPOp4A2Xo-unsplash](https://user-images.githubusercontent.com/16949503/137634902-1f2f8082-ca7a-4093-8427-81b5fa3e3932.jpeg)
  
</details>
<details>
  <summary> Option 2</summary>
  
  ## Option 2
![abraham-barrera-8Nn49K7Snow-unsplash](https://user-images.githubusercontent.com/16949503/137635091-ccabf642-4528-4723-a4a7-41e5e5100b47.jpeg)
  
</details>
<details>
<summary> Option 3</summary>
  
  ## Option 3
![erik-van-dijk-uAWRPtZ6n0s-unsplash](https://user-images.githubusercontent.com/16949503/137635172-fa7bdf6e-e842-423a-8d8d-11c70a841019.jpeg)
  
</details>

**Comment by rpbracker** [comment]
### Civic Tech Infrastructure -- more image ideas: 

<details>
  <summary>DTLA PM Time Lapse Option 1</summary>
![A long exposure photo of Downtown Los Angeles at night, showing part of a freeway and skyscrapers](https://user-images.githubusercontent.com/14296840/138025011-611cd8dd-cd50-4527-8514-c83a64610a18.jpg)

[Pexels](https://www.pexels.com/photo/city-road-traffic-street-6136571/)
</details>

<details>
  <summary>DTLA Time Lapse Option 2</summary>
![A long exposure photo of Downtown Los Angeles at night, showing part of a freeway and skyscrapers](https://user-images.githubusercontent.com/14296840/138024655-56de5cab-d40c-4ae7-9b8d-679fa42285e9.jpg)

[Unsplash](https://unsplash.com/photos/GqGgPA2swJA)
</details>

<details>
  <summary>Metro bus depot</summary>

![An aerial photo of Los Angeles Metro buses at a bus depot lot](https://user-images.githubusercontent.com/14296840/138024773-ae65d54b-1815-44e3-91ea-4f4dfee0e1a6.jpg)

[Pexels](https://www.pexels.com/photo/cars-on-road-8783151/)
</details>

<details>
  <summary>Power lines</summary>

![A photo of power lines at sunset](https://user-images.githubusercontent.com/14296840/138024822-8ece535d-2473-4554-a587-35e7aaacacc9.jpg)
![pexels-kehn-hermano-6136571 (1)](https://user-images.githubusercontent.com/14296840/138025089-5198ada3-16b0-4ee4-b6bb-b74999adb2e0.jpg)

[Unsplash](https://unsplash.com/photos/16RZ-Q3brGw)
</details>

<details>
  <summary>Bus in front of Pershing Square</summary>

![A photo facing upward that shows the 90 Metro bus in front of Pershing Square, with a view of skyscrapers and palm trees behind the bus](https://user-images.githubusercontent.com/14296840/138024874-67f504cd-2c8b-4eae-8a7b-f244a846a4df.jpg)

[Unsplash](https://unsplash.com/photos/9TUkYXQKXec)
</details>

**Comment by jenjen26** [comment]
### Civic Tech Infrastructure Image Ideas
[Port of LA](https://unsplash.com/photos/5WQJ_ejZ7y8) 
[Judge Harry Pregerson interchange](https://unsplash.com/photos/k5w21D7PgMk) - there are lots of different images of this 
[View of city ](https://unsplash.com/photos/0YWaDPylkYA)

**Comment by kellychoe** [comment]
> ### Overview
> We need to find an image which best represents the Civic Tech Infrastructure program area for the [new homepage design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16301%3A101535).
> 
> ### Action Items
> * Do you have an idea for an open-source image which best represents Civic Tech Infrastructure?
> * If so we'd love to see it!
> * Please post the image, along with a link in the comments below.
> 
> ### Resources/Instructions
> See all Civic Tech Infrastructure projects here: [Hack for LA - Civic Tech Infrastructure ](https://www.hackforla.org/projects/?programs=Civic+Tech+Infrastructure)

Hi-Pulled bunch so that you can edit to what you're looking for.  hope this helps.https://www.figma.com/file/wj6W2Hc0su6EOUxzMTmWpr/Civic-Tech-Infrastructure-Imags?node-id=0%3A1

**Comment by kristine-eudey** [comment]
Progress: Submissions have been gathered. 
Blockers: None
Availability: 1.5 hours this week to compile all the images, and make a selection to share with the team. I will also create a composited image showing some icons from current Civic Tech projects on the screen of the iPad shown in the [current image](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16091%3A101199). 
ETA: Sunday 10/31

**Comment by kristine-eudey** [comment]
Progress: None since last update
Blockers: None, have just been busy with other work on the project
Availability: 2 hours this coming week
ETA: Sunday 11/21

**Comment by kristine-eudey** [comment]
@ExperimentsInHonesty I've created a new version which uses the current image but replaces the graphics shown on the iPad with icons showing things we discussed as representing our Civic Tech projects (magnifying glass, data, teamwork, guide). Please let me know your thoughts. 

![Screen Shot 2021-11-18 at 7 25 21 PM](https://user-images.githubusercontent.com/16949503/142518362-de9b53b5-99d6-4716-a125-a7389d6b92a8.png)

**Comment by ExperimentsInHonesty** [comment]
@kristine-eudey yes, I think this is perfect.  The only improvement I can think of is it not being male just because the constituency of non profit leads is mostly female. In the meantime I will make this issue as closed given you are done with your tenure.  And ill hand this off to @arghmatey  

Hi Sarah, do you have time to change out the Civic Tech Structure image on the homepage redesign?  If yes, please use the image above as the new Civic tech structure image.  Leave a comment and mark the issue closed when you have seen this message if you are going to make the change.  Otherwise leave a note saying no, and I'll make a new issue for someone else to change it.

**Comment by arghmatey** [comment]
Civic Tech Infrastructure image has been updated, and new commit has been pushed to #2373. Closing issue.

**Comment by kristine-eudey** [comment]
@arghmatey I'm not sure if you had access to a large enough file for the updated image, since the one I pasted in the issue was just a screenshot. I just uploaded the square cropped images in both 900px and 1200px size to the [Drive folder](https://drive.google.com/drive/folders/1pDthtEiPKgn998deuPAlCiqvcd4mlmvr?usp=sharing).

**Comment by ExperimentsInHonesty** [comment]
@arghmatey did you see Kristine's last comment

**Comment by arghmatey** [comment]
@kristine-eudey @ExperimentsInHonesty Great! I believe the image was a little smaller than the others, so I'll replace it now. Thank you!
