### ISSUE TITLE
Create demographic survey for donors

### ISSUE THREAD

**Issue by Basu3040** [hackforla/website#2334]
### Overview
We need to create a survey in the google form for the website redesign project. This survey will help collate the demographic data of both individual and corporate donors.

### Action Items
1. Create a survey in the google form 

### Resources/Instructions
https://docs.google.com/document/d/1ELtk7H_uubatggRcTO9imHzdheeiPWkDLs3KZepMwh0/edit
#2015

**Comment by sacamp** [comment]
created the survey, ready for use. 
Located in the UX research drive [https://docs.google.com/forms/d/1O8I7EM1b8dP9DPCMWtsekCLVzyyn-TI77U3hYNrOHzs/edit]

**Comment by sacamp** [comment]
Progress: done. Found at the following: https://docs.google.com/forms/d/1O8I7EM1b8dP9DPCMWtsekCLVzyyn-TI77U3hYNrOHzs/edit?usp=sharing
