### ISSUE TITLE
Update the card format for the Wins page for Desktop/Mobile

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2339]
### Overview
We need to update the Sass(CSS) for the win page cards in order to match the [Figma file (design with dark blue border)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16207%3A101187) provided by the design team

### Action Items
- [x] Ensure the cards within **desktop view** of the Wins page match `Option B`  within the [The Wins Page Figma design (within the dark blue border)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16207%3A101187)
    - [ ] Change the see more link at the bottom of the card to the carrot, as shown in screenshots below. 

- [x] Ensure the cards within **mobile view** of the Wins page match `Option B`  within the [The Wins Page Figma design (within the dark blue border)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16207%3A101187)
    - [x] Create an arrow that indicates whether the card is expanded or not (it will be similar to our accordion element)
        - [x] Arrow pointing up means not expanded (default)
        - [x] Arrow pointing down is expanded (functionality works, you just need to switch out `see more` with arrow) 
- [x] Add styling to ensure all items of the card are evenly spaced vertically (this can be accomplished with flexbox/CSS grid)

  <summary><strong>Click here to see before/after for Wins Page (desktop view)</strong></summary>
  <h3>Current look of Wins Page card - desktop view </h3>
  <img src="https://user-images.githubusercontent.com/81049661/182913501-09684f74-2fef-4348-a511-56e6248a256f.png" 
 alt="Figma Design for Hack for LA Wins Card - mobile view"/>
</details>

<br>
  <h3>Desired look of Wins Page card - desktop view (Figma design)</h3>
  <img src="https://user-images.githubusercontent.com/21162229/136122187-3191ee15-2509-4e7f-9d3b-cf39b3018ca7.jpg" 
 alt="Figma Design for Hack for LA Wins Card - mobile view"/>
</details>

### Resources/Instructions
[The completed Figma design for the Wins Page card (within the dark blue border)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16207%3A101187)
https://www.hackforla.org/wins/
Design Issue for reference #2207
https://github.com/hackforla/website/issues/2207#issuecomment-929324091
Reach out to the @hackforla/website-merge if you have any questions or need clarifications.

**Comment by JessicaLucindaCheng** [comment]
@tamara-snyder Please work on and complete a small issue before working on a medium-size issue. Please un-assign yourself from this issue and place it back in the prioritized backlog. Then pick a small issue to work on.

**Comment by tamara-snyder** [comment]
@JessicaLucindaCheng Oh whoops, sorry! Will do.

**Comment by Carlos-A-P** [comment]
Availability: 5 hrs
ETA: Monday 2/28/2022

**Comment by Carlos-A-P** [comment]
1. Progress - I have been busy this week as I just started my internship. It's taking me a bit to catch up to speed but I should have better time management this upcoming week. 
2. Blockers - I started to make some changes on wins.js and started off by removing the function that adds the relative class to the '.wins-see-more-div' class. However, the changes in the .js file aren't visible when I run docker only when I made a change to the .html file. 
3. Availability - 1 week
4. ETA - Sunday, 3/6/2022

**Comment by JessicaLucindaCheng** [comment]
@Carlos-A-P If you don't see changes to code when you use Docker to view the website locally on your computer, run `docker-compose down`, then clear your cache and delete the file `.jekyll-metadata` and the directory `_site`, and then run `docker-compose up`. See if that helps with you seeing changes locally.

**Comment by Carlos-A-P** [comment]
1. Progress - I have changed the card layout within the mobile view but I ran into a blocker in the desktop view
2. Blockers - In order to cut the text and add the three dots after overflowing text I added the following code to the `.wins-card-text p`
```
.wins-card-text p {
  text-overflow:ellipsis;
  overflow:hidden;
  display: -webkit-box !important;
  -webkit-line-clamp: 4;
  -webkit-box-orient: vertical;
  white-space: normal;
}
```
Unfortunately, the `display: -webkit-box !important;` property seems to affect the see more button and I'm trying to find a way around it. 
3. Availability - 2 weeks
4. ETA -  3/12/2022

**Comment by JessicaLucindaCheng** [comment]
@Carlos-A-P If you still need help with your blocker, could you push your code for this issue into a topic branch on your forked repo? I think it will help me see your code in context with other code so I can try to help you with your blocker.

**Comment by Carlos-A-P** [comment]
1. Progress - Still working on the blocker, submitted a PR to show where I'm currently at https://github.com/hackforla/website/pull/2977
2. Blockers - same blocker where `display: -webkit-box` is affecting the see more button by hiding it 
3. Availability - 3 hrs this week
4. ETA - 03/20/2022

**Comment by JessicaLucindaCheng** [comment]
@Carlos-A-P 

When I compared your changes with the current live website using developer tools,
- your code has hidden set to true: `<div class="wins-see-more-div" hidden="true">`
- while the current live website doesn't have a hidden attribute: `<div class="wins-see-more-div">`.

I think the changes you made may have impacted the logic in the addSeeMore() function in wins.js, which deals with whether the "See more" is hidden or not. I'm not sure if it has to do with webkit because I am not familiar with it.

**Current Live Website**
<img width="960" alt="wins-no-hidden" src="https://user-images.githubusercontent.com/31293603/158717971-7712cdae-8251-4533-8975-02844ba5596e.png">

**Your Changes Seen Using Docker**  
<img width="960" alt="wins-hidden-true" src="https://user-images.githubusercontent.com/31293603/158718000-10705138-818d-4443-ba06-7a1238a5ecd5.png">

**Comment by Carlos-A-P** [comment]
@JessicaLucindaCheng thank you, I was able to resolve the blocker by removing the code that was unnecessary within the addSeeMore() function

**Comment by JessicaLucindaCheng** [comment]
- Need to write issue for this: https://github.com/hackforla/website/pull/2977#issuecomment-1094341044

**Comment by kathrynsilvaconway** [comment]
@ExperimentsInHonesty I'm a little confused about the third checkbox on this issue. It says we need to change it to look the the mobile design on Figma, but the the Figma link is to a desktop version.

**Comment by ExperimentsInHonesty** [comment]
- I created the new issue #3539 Now we can close this
