### ISSUE TITLE
Fix spelling typo in yml file name from envirnoment to environment

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2341]
### Prerequisite
Please make sure you have read the **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue

### Overview
As a developer, we need to keep code quality standards high on this project so that we can model best practices for new developers and team pride.  

### Action Items
- [x] Correct a spelling mistake by renaming [this ](https://github.com/hackforla/website/blob/gh-pages/_data/internal/program-areas/envirnoment-card.yml) file from `envirnoment-card.yml` to `environment-card.yml`
- [x] Ensure that the [corresponding webpage](https://www.hackforla.org/program-areas) stays the same after the change

#### File and Code links you will need to review this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/program-areas/envirnoment-card.yml`

- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/7750bd39e6546ef9ef0e82c4d04ffbea3c157329/_data/internal/program-areas/envirnoment-card.yml#L1-L39

#### Backround information about the Jekyll framework (optional reading)
[Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
[Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

**Comment by ExperimentsInHonesty** [comment]
@macho-catt I updated the overview and the action items to conform to our standard issue format.
