### ISSUE TITLE
Change alt text for Citizen Engagement program area

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2342]
### Prerequisite
Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to provide clear and descriptive alt text on the Citizen Engagement Program Area page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity.

### Action Items
- [x] Change the image_alt property value to 'A group discussion behind a laptop' within `_data/internal/program-areas/citizen-engagement-card.yml`

**From**
`image_alt: Two guys holding hands`

**To:**
`image_alt: A group discussion behind a laptop`

- [ ] Ensure that the corresponding [Program Areas page](https://www.hackforla.org/program-areas) stays the same after the change
- [ ] Ensure that the new alt text gets incorporated after the change

#### File and Code links you will need to review this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/program-areas/citizen-engagement-card.yml`

- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/f015a891265d56372f87e1adb1e1b6088dcfac06/_data/internal/program-areas/citizen-engagement-card.yml#L10

#### Backround information about the Jekyll framework (optional reading)
[Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
[Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

**Comment by ExperimentsInHonesty** [comment]
@macho-catt  I removed the original text you had on the overview and integrated the information into the Resources section and the new Overview.

> As a developer, it is good practice to adhere to Web Content Accessibility Guidelines (WCAG). For this issue, update the alt text for the Citizen Engagement program area [yml file](https://github.com/hackforla/website/blob/gh-pages/_data/internal/program-areas/citizen-engagement-card.yml) because it is currently inaccurate if you refer to the image on the corresponding [webpage](https://www.hackforla.org/program-areas).

**Comment by adam-abundis** [comment]
claiming this issue because @rashmeesinha has a pull request (#2379 ). But they must reformat the initial comment in the PR. Will check on Wednesday (10/27) to see if any information is updated.

**Comment by adam-abundis** [comment]
This issue is now available again. If @rashmeesinha wants to submit another pull request for this issue, they will need to leave a comment here letting us know they are still working on it.
