### ISSUE TITLE
Fix typo for Food Oasis under Accomplishments: from lising to listing

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2345]
### Prerequisite
Please make sure you have read the **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue

### Overview
We need to keep code quality standards high on this project so that we can model best practices for new developers and team pride.  

### Action Items
- [ ] Correct the spelling mistake in the Accomplishments section of the About page by changing "lising" to "listing" in line 11:
From
```
Launched 8/2020 the most comprehensive lising of Food Pantries and Meals to address food insecurity in Los Angeles (listed as a resource on LA County Public Health website).
```
To
```
Launched 8/2020 the most comprehensive listing of Food Pantries and Meals to address food insecurity in Los Angeles (listed as a resource on LA County Public Health website).
```
- [ ] Ensure that the [corresponding webpage](https://www.hackforla.org/about/#accomplishments) reflects the spelling fix

#### File and Code links you will need to review this issue
- Directory to find the page in once you have it in your IDE: ```gh-pages/_data/internal/accomplishments.yml```

- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/f015a891265d56372f87e1adb1e1b6088dcfac06/_data/internal/accomplishments.yml#L11

#### Backround information about the Jekyll framework (optional reading)
[Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
[Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

**Comment by Chetana16032002** [comment]
I have corrected the issue can you please assign this to me and add a hacktoberfest-accepted label😅

**Comment by macho-catt** [comment]
@Chetana16032002 Thank you for showing interest in this issue. We don't actually "assign" issues. In order to claim issues, you can join a volunteer onboarding meeting and can be added to the Hack for LA organization/website repo. Feel free to check out our Getting Started page (https://www.hackforla.org/getting-started) and our guide to contributing (https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) to see how our team works. Let me know if you have any other questions.
