### ISSUE TITLE
Fix typo for 311 Data under Accomplishments: from comprensive to comprehensive

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2346]
### Prerequisite
Please make sure you have read the **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue

### Overview
We need to keep code quality standards high on this project so that we can model best practices for new developers and team pride.  

### Action Items
- [x] Correct the spelling mistake in the Accomplishments section of the About page by changing "comprensive" to "comprehensive" in line 22:
From
```
    Launched 8/2020 a comprensive 311 service report Neighborhood Council (NC) and City Council district 
```
To
```
    Launched 8/2020 a comprehensive 311 service report Neighborhood Council (NC) and City Council district 
```
- [x] Ensure that the [corresponding webpage](https://www.hackforla.org/about/#accomplishments) reflects the spelling fix

#### File and Code links you will need to review this issue
- Directory to find the page in once you have it in your IDE: ```gh-pages/_data/internal/accomplishments.yml```

- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/f015a891265d56372f87e1adb1e1b6088dcfac06/_data/internal/accomplishments.yml#L22

#### Backround information about the Jekyll framework (optional reading)
[Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
[Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

**Comment by adam-abundis** [comment]
@hackforla/website-merge I have accepted @SumayyaZiyad pull request and have merged the changes. Closing this issue.

Thank you again @SumayyaZiyad  for your contribution! ⭐ ⭐ ⭐
