### ISSUE TITLE
Update LA TDM Calculator Highlight under Accomplishments

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2349]
### Prerequisite
Please make sure you have read the **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue

### Overview
We need to fix inaccurate information on the website. Currently, the highlight for LA TDM Calculator is a copy of Food Oasis' highlight.

### Action Items
- [x] Update the information on lines 16 and 17 from:
```
    Launched 8/2020 the most comprehensive lising of Food Pantries and Meals to address food 
    insecurity in Los Angeles (listed as a resource on LA County Public Health website).
```
to:
```
    Hack for LA’s first software application in CI/CD on LA City Department of Transportation’s 
    Azure servers - launching publicly in Q4 2020
```
- [x] Ensure that the [corresponding webpage](https://www.hackforla.org/about/#accomplishments) reflects the changes

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: ```gh-pages/_data/internal/accomplishments.yml```
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/756215895f60bd92636d6e06ebc2475ee6f93c43/_data/internal/accomplishments.yml#L16-L17
- [Figma displaying the right information](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=2705%3A20747)
- [About page](https://www.hackforla.org/about/#accomplishments)

#### Backround information about the Jekyll framework (optional reading)
[Jekyll Data Files](https://jekyllrb.com/docs/datafiles/)
[Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)

**Comment by Aryannath** [comment]
Hi i have a PR for this at #2358

**Comment by adam-abundis** [comment]
@hackforla/website-merge I have accepted @Aryannath pull request and have merged the changes. Closing this issue.

Thank you again @Aryannath for your contribution! ⭐ ⭐ ⭐
