### ISSUE TITLE
Identify URL of general HFLA Meetup page vs. Westside-specific Meetup page

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#235]
### Overview
Identify URL difference between general HFLA Meetup page and Westside-specific page

### Action Items
- [ ] Identify URL difference between general HFLA Meetup page and Westside-specific page
- [ ] Check-in with Kian to update "Join our Meetup" call to action button

### Resources/Instructions
https://www.meetup.com/hackforla/

**Comment by ExperimentsInHonesty** [comment]
This does not seem to be possible.  Alternative would be setting up different meetup accounts.  Which has the downside of bifurcating our membership and hurting the new hacknight SOLA
