### ISSUE TITLE
Add GitHub link to Community of Practice Card

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2357]
### Overview
We need to add the Community of Practice GitHub link to the Community of Practice card so we can provide the end-user with more information about our communities.

#### Current CoP Card

<details>
  <summary>Current site Community of Practice card (PM) - desktop view</summary>
  <h3>Current site Community of Practice card (PM) - desktop view</h3>
  <img src="https://user-images.githubusercontent.com/21162229/136688645-0e34b6a0-3c6d-4e2e-b1a0-7cbc44cc51a5.jpg" />
</details>

<details>
 <summary>Current site Community of Practice card (Dev) - mobile view</summary>
  <h3>Current site Community of Practice card (Dev) - mobile view</h3>
  <img src="https://user-images.githubusercontent.com/21162229/136688739-bbfc01ca-7112-4ef2-8a8b-f0e7e5115173.jpg" />
</details>

#### After Proposed Changes

<details>
  <summary>Proposed Community of Practice card (PM) - desktop view</summary>
  <h3>Proposed  Community of Practice card (PM) - desktop view</h3>
  <img src="https://user-images.githubusercontent.com/21162229/136688805-31f2529f-5846-49ad-93ca-e0719240890c.jpg" />
</details>

<details>
 <summary>Proposed Community of Practice card (Dev) - mobile view</summary>
  <h3>Proposed Community of Practice card (Dev) - mobile view</h3>
  <img src="https://user-images.githubusercontent.com/21162229/136688845-331a5250-ad3d-403d-90a2-ddc253d80349.jpg" />
</details>

### Action Items
- [x] Update HTML for Community of Practice Card (add a button & icons)
- [x] Update CSS for Community of Practice Card (if needed)
- [x] Once it matches the [Figma design - blue border (option 2)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3194%3A25627), complete a pull request for a final review

### Resources/Instructions
[Figma design - blue border (option 2)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3194%3A25627)
https://github.com/hackforla/website/blob/49f572428fce86fc30256393dee2a123304f38e2/pages/communities-of-practice.html#L1-L80
https://github.com/hackforla/website/blob/49f572428fce86fc30256393dee2a123304f38e2/_sass/components/_communities-of-practice.scss#L1-L128

**Comment by adrian-zaragoza** [comment]
Status: PR for this issue has been created. PR #2412

**Comment by ExperimentsInHonesty** [comment]
@macho-catt to make an issue for adding the github links to the communities of practice that are missing them.  See this repos readme for the links to repos 
https://github.com/hackforla/communities-of-practice/blob/main/README.md

**Comment by macho-catt** [comment]
@macho-catt created the issue for Ops, @adrian-zaragoza will create the issue for PM and UI/UX sections
