### ISSUE TITLE
Retrieve JSON file for website repo

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#236]
### Overview
Retrieve JSON file for website repo to review available actionable data fields

### Action Items
Retrieve JSON file for website repo
Attach JSON file to this issue

### Resources/Instructions

**Comment by StephenVNelson** [comment]
@KianBadie @ExperimentsInHonesty @harishlingam 
# Example Of GitHub API Call
Here is some data I pulled with postman using the API call that Kegan put together. It has detailed results form everything that is under the _hack-for-la_ topic, which is ostensibly all the data from [this GitHub search](https://github.com/search?q=topic%3Ahack-for-la). _notice both the API return and this seach have 21 items_

So any data listed in the json file _(linked below)_ is something that may be able to automate the site. 

All somebody has to do to add their project to the list is add the _hack-for-la_ topic to their repository. 

Also, I know I said I would just include some of the data but I went ahead and included all of the data. ¯\\_(ツ)_/¯

[exampleOfAPICall.json.zip](https://github.com/hackforla/website/files/4013609/exampleOfAPICall.json.zip)
