### ISSUE TITLE
Add text to readme to encourage stars.

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2362]
### Overview
We should update the README so that we can encourage more people to star our repo so that we can get noticed.

### Action Items
- [ ] Add the following text to the bottom of the website's readme file

```
## We love our Stars ⭐⭐⭐
Thanks to the following people who have given us a star on our repo: 
[![Stargazers repo roster for @hackforla/website](https://reporoster.com/stars/hackforla/website)](https://github.com/hackforla/website/stargazers)
```

### Resources/Instructions
This code comes from this: https://github.com/nastyox/Repo-Roster
location of file to edit in your IDE: **gh-pages/README.md**

**Comment by ExperimentsInHonesty** [comment]
@abuna1985 I wrote this issue, so it would be good if someone else reviewed it to see if anything else needs to be added.

**Comment by macho-catt** [comment]
@chrisfoose can you put this to "in progress" under the project board please? Thanks

**Comment by chrisfoose** [comment]
Is this done?

**Comment by SAUMILDHANKAR** [comment]
@chrisfoose: Yes, it is done. Please feel free to pick up any small, medium or large issue. Also, wanted to share a point from our Sunday team meeting. We are now requesting all developers to add eta and availability at the time of picking up an issue or when you are assigned to an issue. Just wanted to let you know. Thank you.
