### ISSUE TITLE
Audit all Project Card/Page links to verify up to date information

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2363]
### Overview
We need to go through all of our project card/page links so that we ensure end-users are provided their expected result

<details>
  <summary>Click to see example of links within project card</summary>
  <h3>An example that highlighs links within project card</h3>
  <img alt="project card example" src="https://user-images.githubusercontent.com/36433204/134233503-65ff9bdd-cff7-4b10-b647-03b8315dd192.png" />
</details>

<details>
  <summary>Click to see example of links within project page</summary>
  <h3>An example that highlighs links within project page</h3>
  <img alt="project page example" src="https://user-images.githubusercontent.com/36433204/134233538-7a3217ee-e64b-4090-8532-277fb5fe72bd.png" />
</details>

### Action Items
- [x] Review each project card and page to verify the links are working as expected.
   - [x] If links are not working, please leave a [comment in this issue like this](https://github.com/hackforla/website/issues/2363#issuecomment-940369337)
   - [x] If all links are working correctly, please leave a [comment in this issue like this](https://github.com/hackforla/website/issues/2363#issuecomment-940370994)
- [x] Once all project cards/pages are audited, we will convert non-working links into issues to be resolved (`good first issue`)

### Resources/Instructions
Projects Page: https://www.hackforla.org/projects/

**Comment by adam-abundis** [comment]
Update project links: 100 Automations
Overview: We need the 100 Automation links on the hackforla.org website to be up to date

Reason for change: The current link resolves/redirects but it has the old GitHub org name.

**Action Items**
Change Readme link
From: https://github.com/OpenSourceAutomations/OSA-Website/blob/master/README.md
To: https://github.com/100Automations/Website/blob/gh-pages/README.md

Created issue #2433

**Comment by adam-abundis** [comment]
Update project links: 311-data

**Action Items**
No changes needed

**Comment by macho-catt** [comment]
**Access the Data**

Action Items
No changes needed

**BallotNav**

Action Items
No changes needed

**Update project links:  Brigade Organizer's Playbook**

Reason for change: The current link for slack resolves but leads to an archived channel

Action Items
Review the slack link and ensure that it points to the right one 


**Update project links:  Civic Opportunity Project**

Reason for change: The current link for github resolves to their project board. Is this intended?

Action Items
Review the link and ensure it is intended

**Civic Tech Index**

Action Items
No changes needed

**Civic Tech Structure**

Action Items
No changes needed

**Engage**

Action Items
No changes needed

**Comment by adrian-zaragoza** [comment]
Update project links: Open Community Survey

Action Items
No changes needed

**Comment by adrian-zaragoza** [comment]
Update project links: VRMS

Action Items
No changes needed

**Comment by adrian-zaragoza** [comment]
Update project links: Write for All

Action Items
Demo Link goes to http://writeforall.org/ but end up with the error below.

<details>
  <summary>Click to see error</summary>
<img src="https://user-images.githubusercontent.com/77212035/137056105-fcbdb024-07d9-4bdf-9d4f-cc8d9f30a678.png" />
</details>

**Comment by SAUMILDHANKAR** [comment]
Update project links: Expunge Assist
Overview: We need the Expunge Assist links on the hackforla.org website to be up to date

Reason for change: The current link resolves/redirects but it has a different channel link.

Action Items
Change slack link
From: https://app.slack.com/client/T04502KQX/CDWKEBYBB
To: https://app.slack.com/client/T04502KQX/CN8NXTPK5

There's an issue about updating the expunge assist project details, but no indication of anything about slack. We can either create a new issue or tag on this as an action item: #2122

**Comment by adrian-zaragoza** [comment]
Update project links: Youth Justice Nav

Action Items
No changes needed

**Comment by adrian-zaragoza** [comment]
Update project links: Heart

Action Items
No changes needed

**Comment by adrian-zaragoza** [comment]
Update project links: HelloGOV

Action Items
Github link points to its own hellogov github account
Slack link points to the fola slack channel

**Comment by SAUMILDHANKAR** [comment]
Update project links: Food Oasis
Overview: We need the Food Oasis links on the hackforla.org website to be up to date

Reason for change: The current link resolves/redirects but it has a different channel link.

Action Items
Change slack link
From: https://hackforla.slack.com/archives/C6JBH478W
To: Unknown

**Comment by adrian-zaragoza** [comment]
Update project links: Public Tree Map

Action Items
Github link points to its own Hello Tree Map github account

**Comment by mdhailwood1** [comment]
Update project links: Spare
Action Items
Change Site Link
From: http://whatcanyouspare.org/
To: Unknown

Update project links: Not Today
Action Items
No changes needed

Update project links: New Schools Today
Action Items
No changes needed

Update project links: Jobs for Hope
Action Items
No changes needed


Update project links: Work for la
Potential Action Items
Github-Linked to hunterowens repo and may need to change

Update project links: Undebate
Potential action item
Github - part of Enciv repo and may need to change


Update project links: Railstats LA
Action Items
No changes needed

**Comment by SAUMILDHANKAR** [comment]
Update project links: GreenEarthOS
Overview: We need the GreenEarthOS links on the hackforla.org website to be up to date

Reason for change: The current overview link redirects to page not found.

Action Items                          
From: https://github.com/hackforla/product-management/blob/master/project-one-sheets/GreenEarthOS
To: Unknown

There is already an issue created for this: #2162

**Comment by SAUMILDHANKAR** [comment]
Update project links: Home Unite Us
Overview: We need the Home Unite Us links on the hackforla.org website to be up to date

Links for Demo, test site and site are not working.

**Comment by SAUMILDHANKAR** [comment]
Update project links: LA TDM Calculator
Action Items
No changes needed

**Comment by SAUMILDHANKAR** [comment]
Update project links: Lucky Parking
Action Items
No changes needed

**Comment by adam-abundis** [comment]
All immediate issues have been resolved via other PRs. Closing this issue.

**Comment by adam-abundis** [comment]
Reopening so @macho-catt can make remaining issues for all remaining links that need o be updated

**Comment by macho-catt** [comment]
All issues have been created. Closing
