### ISSUE TITLE
Make prework issue template: UX Researcher

### ISSUE THREAD

**Issue by Basu3040** [hackforla/website#2389]
### Overview

Need a pre work template so new people can know how to make a new issue and know what to do when they first arrive

### Action Items

- [x] Write a draft in comments of new template
- [ ] Ask team members for advice on what should go in template

### Resources
The same issue but for Designers https://github.com/hackforla/website/issues/2360

**Comment by ExperimentsInHonesty** [comment]
---
name: 'Pre-work Checklist'
about: 'All new Research team members should start by making this issue '
title: 'Pre-work Checklist: Researcher: [replace brackets with your name]'
labels: 'role: ux researcher', 'good first issue'
assignees: ''

---

### Overview
As a new researcher on the HfLA website UX team, fill in the following fields as you complete each onboarding item.

### Action Items
- [ ] Add yourself to the #hfla-site-ux and #hfla-site Slack channels
- [ ] Share your Gmail address with the research team lead
- [ ]  (once added to the drive) Add yourself to the team roster.
- [ ]  Confirm with the research team lead that they have added you to the meeting invites and Github repo
- [ ]  Confirm that the research team lead has given you login credentials for the team Miro and Figma accounts
- [ ] Attend weekly team meetings:
   - UX weekly team meeting, Thursdays 5 pm PST
   - All team meetings (UX, Development, Product), Sunday 10 am PST
   - Research team meetings, Mondays, 11:30 am PST
- [ ] Review the  [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) to see what Research Issues are available (this will not be the complete list, but will give you some talking points for your conversation with your lead).
- [ ] Meet with team lead to receive first assignment
- [ ] Once you accept an assignment (issue), please add the following in a comment
```
Availability for this week:
My estimated ETA for completing this issue:
```
- [ ] Weekly, please also provide an update on the issue
```
provide update
1. Progress
2. Blockers
3. Availability
4. ETA
```

### Resources/Instructions
[Project Board filtered to show role: user research](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22)
[Miro](https://miro.com/app/board/o9J_l6zD0JA=/)
[Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=2009%3A26149)
[Googledrive-UI/UX](https://drive.google.com/drive/folders/1Jq24FlOJTEmRD09M5xOgpWuHcKswH5Dk)
[Googledrive-HackforLA website](https://drive.google.com/drive/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT)
[UX Research Presentations](https://drive.google.com/drive/folders/1yV9YRrjVKmVLU_xSM_BjtdIaNITRhP5j)
[Weekly Meeting Agendas](https://github.com/hackforla/website/issues/2106)
