### ISSUE TITLE
Create background color mockup variations for project's section of HFLA Home Page

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#239]
### Overview
Create background color mockup variations for Projects section

### Action Items
- [ ] Create 3 mockup variations of background color for Projects section using the the following three background colors: (1) light grey (2) taupe (3) white with drop shadow for project cards (4) gradient continuation from page top to page bottom (no break).
- [ ] Verify against compliance with ADA color and contrast standards.

### Resources/Instructions

Existing background color:

<img width="1280" alt="Screen Shot 2019-12-31 at 10 13 32 AM" src="https://user-images.githubusercontent.com/21990572/71630152-62367600-2bb6-11ea-8115-f61bb6b22a98.png">

Consider neutral colors of beige, gray, and white found in home page banner photo:

<img width="1280" alt="Screen Shot 2019-12-31 at 10 15 17 AM" src="https://user-images.githubusercontent.com/21990572/71630203-a6297b00-2bb6-11ea-9b9f-82b66ed38f4d.png">

**Comment by cnk** [comment]
Light backgrounds are tough if you are going to have the correct contrast ratio with the default header color (#fa114f) But if you leave the current heading color (#333) "Current Projects" doesn't really 'pop'

Here is what the page looks like if you just continue the previous background:
<img width="861" alt="HackForLA-continue-gradient" src="https://user-images.githubusercontent.com/5952/72774043-1592f900-3bbe-11ea-9806-f6b0416c82ac.png">

Or here is a light gray (#d3d3d3):
<img width="861" alt="HackForLA-d3d3d3" src="https://user-images.githubusercontent.com/5952/72774101-41ae7a00-3bbe-11ea-9d13-47e6e7004767.png">

**Comment by ExperimentsInHonesty** [comment]
@leonelRos please shrink your screen size when you do the screen shots, so we can see more of the page for context

**Comment by leonelRos** [comment]
Will do! Thanks again.

**Comment by leonelRos** [comment]
1) Hey, guys,

 I have been playing around with these colors. Feel free to let me know how it looks or any feedbacks. I use gradient colors mixing the one requested above

<img width="1225" alt="Screen Shot 2020-01-26 at 6 22 33 PM" src="https://user-images.githubusercontent.com/50648001/73146788-1669d600-4069-11ea-8aed-da709acec871.png">

It starts with a gray color and drops down to a very light gray (#b3b1af, #ebedee)

<img width="1217" alt="Screen Shot 2020-01-26 at 6 22 51 PM" src="https://user-images.githubusercontent.com/50648001/73146791-1d90e400-4069-11ea-95ff-5abfb64996f4.png">

<img width="1217" alt="Screen Shot 2020-01-26 at 6 23 06 PM" src="https://user-images.githubusercontent.com/50648001/73146799-22ee2e80-4069-11ea-9f48-59051884d047.png">

<img width="1204" alt="Screen Shot 2020-01-26 at 6 23 23 PM" src="https://user-images.githubusercontent.com/50648001/73146803-25508880-4069-11ea-808d-20ac9b936bfb.png">

Also, I change the font color of "current projects" to the same color of Hack for LA logo (pink...ish)
More mockups coming!!!

**Comment by leonelRos** [comment]
2) This one here starts with Taupe and drops down to a very light beige(maybe misspelled) color. 
<img width="1217" alt="Screen Shot 2020-01-26 at 6 44 54 PM" src="https://user-images.githubusercontent.com/50648001/73147453-57171e80-406c-11ea-951f-332e1177420b.png">

<img width="1218" alt="Screen Shot 2020-01-26 at 6 45 11 PM" src="https://user-images.githubusercontent.com/50648001/73147456-5c746900-406c-11ea-8485-181d6a87565c.png">

<img width="1221" alt="Screen Shot 2020-01-26 at 6 45 26 PM" src="https://user-images.githubusercontent.com/50648001/73147461-61391d00-406c-11ea-83bd-ecbc0d8c0255.png">

<img width="1217" alt="Screen Shot 2020-01-26 at 6 45 38 PM" src="https://user-images.githubusercontent.com/50648001/73147468-69915800-406c-11ea-8cf6-1733dbcfdbed.png">

**Comment by ExperimentsInHonesty** [comment]
@leonelRos Not sure why the garcetti quote is not staying white.  It should remain separate.  Hard to get the feel without that.

**Comment by ExperimentsInHonesty** [comment]
TOP
![Screen Shot 2020-01-28 at 1 50 47 AM](https://user-images.githubusercontent.com/37763229/73253054-a21a5a00-4170-11ea-8d18-b1de80ced8d9.png)


BOTTOM
![Screen Shot 2020-01-28 at 1 40 32 AM](https://user-images.githubusercontent.com/37763229/73252203-397ead80-416f-11ea-9d63-5cf0a4777e15.png)
#f5f7f5

**Comment by ExperimentsInHonesty** [comment]
TOP
![Screen Shot 2020-01-28 at 1 49 07 AM](https://user-images.githubusercontent.com/37763229/73252950-726b5200-4170-11ea-8240-238bb76c5c96.png)



BOTTOM 
![Screen Shot 2020-01-28 at 1 42 03 AM](https://user-images.githubusercontent.com/37763229/73252324-6af77900-416f-11ea-9f47-c133b81e5644.png)

#f7f5f5

**Comment by ExperimentsInHonesty** [comment]
TOP
![Screen Shot 2020-01-28 at 1 47 51 AM](https://user-images.githubusercontent.com/37763229/73252833-4223b380-4170-11ea-8191-ddc72eb8e938.png)


BOTTOM
![Screen Shot 2020-01-28 at 1 43 51 AM](https://user-images.githubusercontent.com/37763229/73252485-aa25ca00-416f-11ea-9abd-a2df6ca0fdbf.png)

#f5f6f7

**Comment by ExperimentsInHonesty** [comment]
TOP
![Screen Shot 2020-01-28 at 1 46 21 AM](https://user-images.githubusercontent.com/37763229/73252730-0c7eca80-4170-11ea-8d53-1ef472d5b951.png)

BOTTOM
![Screen Shot 2020-01-28 at 1 44 56 AM](https://user-images.githubusercontent.com/37763229/73252587-d2adc400-416f-11ea-83c0-2af31f8e1ce8.png)

#f7f7f5

**Comment by leonelRos** [comment]
@ExperimentsInHonesty  that is because I also change the background color of the Garcetti quote. I might have misunderstood the directions above.  Anyways, I am working on the cards project now.  I will update soon!!

**Comment by ExperimentsInHonesty** [comment]
Mockups complete.  Decision made on issue #240
