### ISSUE TITLE
Implement the new design for the footer: desktop

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2393]
### Dependency
- [x] #2958 
- [x] https://github.com/hackforla/website/issues/3023
- [x] https://github.com/hackforla/website/issues/3026
- [x] https://github.com/hackforla/website/issues/2802

### Overview
We need to create a dynamic footer based on the [Figma Design of our Footer](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14814%3A95261) so that we have a more user-friendly footer.

<details>
  <summary>Click here to see current HfLA footer</summary>

![Screenshot 2021-10-22 224110](https://user-images.githubusercontent.com/21162229/138544168-3c872509-214a-45f5-8862-6b76d5b89ffc.jpg)
 

</details>

<details>
  <summary>Click here to see the proposed footer (Figma design)</summary>

![image](https://user-images.githubusercontent.com/37763229/191559894-7dc75d3a-3e59-4ab1-909c-edc894440e7f.png)

</details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch` and the pull request created from this issue should be pushed into that feature branch. Please read and follow the steps in the [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch) wiki article.
- [x] Create data files (if they don't exist yet) with the column title (Our Work, join Us, Get in Touch, etc) and the list of links that go in each column
    - [x] The data can be stored under `_data/navigation`
    - [x] The footer should dynamically get the data using liquid instead of being statically rendered
- [x] Modify the existing footer section based on the Figma design
- [x] Check all the links in the footer work and go to the correct webpage or section on a webpage
- [x] Make sure that the order of the items appearing in the footer sections can be changed easily (e.g., we might later want to change the order of the items that appear under Join us).
- [x] Create a PR that is pushing to the `feature-homepage-launch` branch
~- [ ] Once PR is approved and merged, release dependency on #2554~

### Resources/Instructions

- [Feature branch wiki article](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Figma - Footer (final design)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14814%3A95261)
- https://github.com/hackforla/website/issues/1969#issuecomment-921299370 (for design historical reference only)
- Click below to see page footer

https://github.com/hackforla/website/blob/66f89317e84517f4bbbd29911bb21aeddb8bb2d3/_includes/footer.html#L1-L24

**Comment by kristine-eudey** [comment]
@macho-catt I just updated the order of menu items in the "Join Us" section of the footer to match the order they appear on the Join Us page.

**Comment by Providence-o** [comment]
This is a screenshot of the footer that Kristine updated 
![image](https://user-images.githubusercontent.com/97491889/158035990-afc1a412-4eb9-4bf4-a2f0-55faf8fc64c0.png)

**Comment by ExperimentsInHonesty** [comment]
Once this issue is done, please send back to product with a note for them to ask design and research to confirm the order they want the Join Us footer items in.

**Comment by jyaymie** [comment]
Availability: 11/29/22 - 12/2/22
ETA: 12/2/22

**Comment by jyaymie** [comment]
@ExperimentsInHonesty

The current Contact Us link - `/#contact-us` - takes me to the top of the home page where I can't find any info for contacting HfLA. I wanted to know if I have the correct link. Thanks!

<details>
<summary>Where the Contact Us link takes me:</summary>

![Screen Shot 2022-11-29 at 7 46 35 PM](https://user-images.githubusercontent.com/104411072/204705638-628e4113-bdaf-4625-962d-6a26f7a343a3.png)

</details>

**Comment by JessicaLucindaCheng** [comment]
@jyaymie 
> The current Contact Us link - `/#contact-us` - takes me to the top of the home page where I can't find any info for contacting HfLA. I wanted to know if I have the correct link. Thanks!
> 
> Where the Contact Us link takes me:

Contact Us should go to www.hackforla.org/#get-in-touch, so the Docker equivalent is localhost:4000/#get-in-touch
It should redirect to the Get in Touch section at the bottom of the redesigned homepage.

**Comment by jyaymie** [comment]
Thanks for the correction, @JessicaLucindaCheng! This will mean that the user will have two links directing them to www.hackforla.org/#get-in-touch, specifically, "Get in Touch" (in bold) and "Contact Us" in the third column of the footer. Will both links be needed?

**Comment by JessicaLucindaCheng** [comment]
@jyaymie 
> This will mean that the user will have two links directing them to [www.hackforla.org/#get-in-touch](http://www.hackforla.org/#get-in-touch), specifically, "Get in Touch" (in bold) and "Contact Us" in the third column of the footer. Will both links be needed?

That is a good point. I assumed the bold text was just supposed to act like a header for each column and was not supposed to be linked but I could be wrong about this. 

Please reach out to Bonnie (GitHub handle: ExperimentsInHonesty) and ask her your question. She may know the answer.

**Comment by jyaymie** [comment]
@ExperimentsInHonesty - There are two links directing the user to the same section of the home page. I wanted to know how I should proceed, as this feels redundant to the user.

> This will mean that the user will have two links directing them to [www.hackforla.org/#get-in-touch](http://www.hackforla.org/#get-in-touch), specifically, "Get in Touch" (in bold) and "Contact Us" in the third column of the footer. Will both links be needed?

**Comment by Rabia2219** [comment]
> @ExperimentsInHonesty @hackforla/product-managment
> 
> The current Contact Us link - `/#contact-us` - takes me to the top of the home page where I can't find any info for contacting HfLA. I wanted to know if I have the correct link. Thanks!
> 
> Where the Contact Us link takes me:

@jyaymie Hi there! Tagging '@hackforla/product-managment' sends this message to all the PMs across HackforLA. You only need to tag the PM for you project or add the 'ready for milestone' label to get feedback :)

**Comment by jyaymie** [comment]
> @jyaymie Hi there! Tagging '@hackforla/product-managment' sends this message to all the PMs across HackforLA. You only need to tag the PM for you project or add the 'ready for milestone' label to get feedback :)

@Rabia2219 Sorry about that! The comment has been edited accordingly 🙂

**Comment by jyaymie** [comment]
1. Progress: I have confirmed that the footer is dynamically getting data using liquid and that the data can be easily modified to implement future changes to the order of the footer items. I have also modified the CSS to match the Figma design.
2. Blockers: Currently, there are two links - "Get in Touch" (in bold) and "Contact Us" in the third column of the footer - that direct the user to the same section of the home page, [www.hackforla.org/#get-in-touch](http://www.hackforla.org/#get-in-touch). This might be redundant to the user. I am waiting for instruction on how I should proceed.
3. Availability: Flexible
4. ETA: Jan 2023
5. Pictures (optional): The footer with its CSS modifications:
<img width="1200" alt="Screen Shot 2022-12-16 at 8 10 03 AM" src="https://user-images.githubusercontent.com/104411072/208141646-60a863e8-48af-4653-afda-17e2fd4f3ad7.png">

**Comment by roslynwythe** [comment]
@jyaymie I just wanted to mention that there is a PR #3754 that is also modifying the footer CSS on feature-homepage-launch

**Comment by jyaymie** [comment]
> @jyaymie I just wanted to mention that there is a PR #3754 that is also modifying the footer CSS on feature-homepage-launch

@roslynwythe Great eye! Thanks for bringing this to my attention. I'll watch out for further development on that issue and modify my code accordingly.

**Comment by jyaymie** [comment]
1. Progress: There is no progress to report since my last update. However, a discussion with the dev team at today's meeting shed light on other potential blockers.
2. Blockers: 
- As previously mentioned, the two links, "Get in Touch" and "Contact Us" are directing users to the same section of the home page, [www.hackforla.org/#get-in-touch](http://www.hackforla.org/#get-in-touch). 
- I wonder if users will instinctively know that the bolded headers of each column are also links.
- Even at a max font weight of 900, these bolded headers don't look that different from other non-bolded links. See [screenshot](https://github.com/hackforla/website/issues/2393#issuecomment-1355165417).

3. Availability: Flexible
4. ETA: Jan 2023

**Comment by jyaymie** [comment]
In today's All Team meeting, it was confirmed that the URL of some links are placeholders to be updated as the website develops, so I will move forward with the links as they currently are.

Blockers related to the column headers will be considered following user testing.
