### ISSUE TITLE
Update Getting Started Page: icon alignment in page step cards

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2396]
### Overview
We need to update the step cards icon alignment so that the Getting Started page matches the Figma design. 

<details>
  <summary><strong>Click here</strong> to see the current step card icon alignment (<strong>before changes</strong>)</summary>

![getting-started-before-changes-desktop](https://user-images.githubusercontent.com/21162229/138683533-11a5cc83-a4fd-430c-8f98-eee0ae53ebd3.png)
</details>
<details>
  <summary><strong>Click here</strong> to see the proposed step card icon alignment (<strong>after changes</strong>)</summary>

![getting-started-after-changes-desktop](https://user-images.githubusercontent.com/21162229/138683714-cf937562-0caf-49a1-b846-ffb3bb5a8c1d.png)
</details>

### Action Items

- [x] Change the styling alignment on classes for the icons so it is aligned to the top ( something like `align-self: flex-start;`)

### Resources/Instructions
Design issue #1842 
https://www.hackforla.org/getting-started

https://github.com/hackforla/website/blob/055674d5ccb25b7acc2e8d33a9b7f29b929b0fe2/_sass/components/_getting-started-page.scss#L201-L306

**Comment by ExperimentsInHonesty** [comment]
@abuna1985 reminder to divide this into two issues

**Comment by sydneywalcoff** [comment]
Availability for this week: Friday, Sat, Mon, Tue, Wed
My estimated ETA for completing this issue: Fri Dec 10, 2021
