### ISSUE TITLE
Split test Projects section color variations at hacknight

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#240]
### Overview
Split test Projects section color variations at hack night

### Action Items
Split test Projects section background color mockup variations at next Westside Hacknight.

### Resources/Instructions
color variations are in #239

**Comment by melodylaishram** [comment]
Split Test Projects Section Color Variation Results:

Green: 6
Pink: 14
Blue: 5
Grey (last color variation): 7 votes

Pink being the overall winner with 37.5% of votes captured.
