### ISSUE TITLE
GitHub Actions: Implement CodeQL

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2400]
### Overview
As a developer, we need to ensure that we write secure code and defend against vulnerabilities. To do so, we need to configure code scanning using [CodeQL](https://codeql.github.com/docs/codeql-overview/about-codeql/#:~:text=CodeQL%20is%20the%20analysis%20engine,against%20databases%20extracted%20from%20code.).

### Action Items
- [x] Research and investigate how we can use CodeQL
    - [x] Any notes should be documented in this ticket or should be stored on the website team's Google Drive
- [x] We want CodeQL to scan the vulnerabilities for the following:
    - [x] JS code
    - [x] GitHub Actions
    - [x] Liquid
- [x] Create a prototype on your own fork of the repository
- [x] Schedule a time with the dev team and the lead to demo your findings and implementation
- [x] Once approved, write a pull request to implement CodeQL

### Resources/Instructions
[Code Scanning in GitHub](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning)
[About CodeQL](https://codeql.github.com/docs/codeql-overview/about-codeql/#:~:text=CodeQL%20is%20the%20analysis%20engine,against%20databases%20extracted%20from%20code.)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)

**Comment by SAUMILDHANKAR** [comment]
ETA: 5/25/22
Availability: 2 hrs per week

**Comment by SAUMILDHANKAR** [comment]
Progress: Did preliminary research on CodeQL. Planning to start configuring in my own repo next week.
Blockers: No blockers
Availability: 1 hr
ETA: 5/30/22

**Comment by SAUMILDHANKAR** [comment]
Progress: Not much progress since last week but will have more time next week.
Blockers: No blockers
Availability: 1 hr
ETA: 6/20/22

**Comment by SAUMILDHANKAR** [comment]
Progress: Did some more reading, should have more updates on this, next week
Blockers: No blockers
Availability: 2 hrs
ETA: 7/5/22

**Comment by SAUMILDHANKAR** [comment]
Progress: I setup a default version of CodeQL with GitHub actions workflow in one of the branches in my repo. Would be editing the workflow and testing out the functionality next.
Blockers: No blockers
Availability: 2 hrs
ETA: 7/12/22

**Comment by SAUMILDHANKAR** [comment]
Progress: Not much progress, still need to make changes to the workflow.
Blockers: No blockers
Availability: 2 hrs
ETA: 7/29/22

**Comment by SAUMILDHANKAR** [comment]
Progress: Would be working on the workflow changes this week.
Blockers: No blockers
Availability: 2 hrs
ETA: 8/10/22

**Comment by SAUMILDHANKAR** [comment]
Progress: I was able to run a few tests using the CodeQL workflow which is now setup in my repo and below are the main observations:

1. Currently, CodeQL only scans vulnerabilities for some of the programming languages including JavaScript. This should be useful for our project since we have a lot of JavaScript code.
2. CodeQL workflow can be setup for a repo and can be customized similar to how GitHub action workflows are setup. The workflow can be triggered on push, pull requests or on a specific schedule. It can also be customized to work with different branches (Would need a discussion on which approach is the best. My recommendation is to trigger once a month on gh-pages).
3. While scanning the codebase in my repo, CodeQL reported 3 different types of warnings:
    - [Potentially unsafe external link](https://github.com/SAUMILDHANKAR/website/security/code-scanning/1)
    - [Inclusion of functionality from an untrusted source](https://github.com/SAUMILDHANKAR/website/security/code-scanning/18)
    - [DOM text reinterpreted as HTML](https://github.com/SAUMILDHANKAR/website/security/code-scanning/17)
4. There is also an option to run custom queries but that would need more analysis. 

Will be reaching out to the leads to schedule a demo next.
Blockers: No blockers
Availability: 2 hrs
ETA: 8/28/22

**Comment by blulady** [comment]
@SAUMILDHANKAR hasn't responded since August, sending this back to New Issue Approval to see if anything needs to happen with it before we return it to Prioritized Backlog.

**Comment by bishrfaisal** [comment]
@blulady Have we tried to reach Saumil by Slack or email?

**Comment by JessicaLucindaCheng** [comment]
@bishrfaisal I sent Saumil an email today using the websitedevs@hackforla.org account and also private messaged him in Slack.

**Comment by JessicaLucindaCheng** [comment]
@SAUMILDHANKAR responded with the following Slack message:
> I would like to finish the issue. Would work on the demo and post the update in a few days. Will reach out to Kathryn to schedule a demo. Sorry for the delay and thank you for following up.

Thus, I will be moving this issue back to the In Progress column.

Please remember to post progress updates (Progress, Blockers, Availability, ETA) in this issue. Thanks.

**Comment by SAUMILDHANKAR** [comment]
Progress: I have set-up the CodeQL workflow in a branch in my repo and ready for demo. @kathrynsilvaconway  @blulady, @bishrfaisal @JessicaLucindaCheng Please advise on an appropriate time for the demo. My availability is flexible and I have added preferred time below as well.
Blockers: No blockers
Availability: Thursday 11/10 6-9 PM Pacific Time, Sunday 11/13 10AM - 1 PM Pacific Time, Tuesday 11/15 6-9 PM Pacific Time
ETA: 11/18/22

**Comment by blulady** [comment]
@SAUMILDHANKAR So sorry I missed this!! Could you make any of the Website Meetings this week? We'll make room for you whenever you are ready.

**Comment by SAUMILDHANKAR** [comment]
> @SAUMILDHANKAR So sorry I missed this!! Could you make any of the Website Meetings this week? We'll make room for you whenever you are ready.

@blulady Thank you for getting back. Sure, planning to attend the Tuesday dev meeting.

**Comment by SAUMILDHANKAR** [comment]
Progress: Did the demo for this issue on 11/15. Below are the notes from the team discussion:
- The preferred frequency for running this workflow should be once a week.
- Need more research on if and when this workflow might exceed the billing quota.
- Should include screenshots of how to add code scanning for languages other than JavaScript to the workflow
- Seek more info on how to add custom queries for code involving liquid/GitHub actions (but we can skip it if too complicated)
- Check if the errors go away once the suggested changes have been made especially for noopener noreferrer error.

Would be working on the above items next and would reach out to leads once done with the analysis.
Blockers: No blockers
Availability: 5 hours 
ETA: 12/2/22

**Comment by SAUMILDHANKAR** [comment]
Progress

**Comment by SAUMILDHANKAR** [comment]
Progress

**Comment by SAUMILDHANKAR** [comment]
Progress: 
  - In regard to testing if the errors go away once the suggested changes have been made:
    - I changed line 10, ````<a href="{{sponsor.link}}" target="_blank" alt="{{sponsor.name}}">```` in ````[_includes/about-page/about-card-sponsors.html]```` to ````<a href="{{sponsor.link}}" target="_blank" rel="noopener noreferrer" alt="{{sponsor.name}}">````, in my own repo, as per the recommended solution and the error indeed went away.
    - Since, our code uses liquid to pull up the links, we might look into if the current architecture is the best way to add ````rel="noopener noreferrer"```` to the links, since CodeQL's recommendation would be based on plain JavaScript.
    - I tested the webpage after making the changes and it looked the same.
  - CodeQL automatically detects, and attempts to analyze, any supported languages in the repository. See the image below for how the workflow would look with automatic detection of languages. 
    <details>
    <summary>Image of default workflow</summary>
    <img src="https://user-images.githubusercontent.com/843538/208839541-4248d99d-c730-4edf-bb04-b84626b98336.PNG" width="600" length="2000" />
    </details>

    - We can also manually add a language to the workflow from a list of [supported languages](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#changing-the-languages-that-are-analyzed) as per image below.
      <details>
      <summary>Image of how to add a language manually</summary>
      <img src="https://user-images.githubusercontent.com/843538/208840614-774b7e28-f2a1-4b51-8eb0-24c70f1a1c4e.PNG" width="2200" length="600" />
      </details>

  - Also, since there is no limit on [GitHub actions on public repositories](https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#about-billing-for-github-actions), we don't have to worry about billing.
  - Would be working on how to add custom queries for code involving liquid/GitHub actions next.

Blockers: No blockers
Availability: 5 hours
ETA: 12/22/22

**Comment by SAUMILDHANKAR** [comment]
Progress: During the last week, I have been exploring how to add custom queries for scanning our codebase:
- CodeQL provides an [out of the box custom query](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#example-configuration-files), I added [queries: security-and-quality](https://github.com/SAUMILDHANKAR/website/blob/4ae237a550fc6cfb24901cf0d1c82fdb7988f6c1/.github/workflows/codeql.yml#L55) in the CodeQL workflow in my own repo and this increased the number of alerts from 26 to 52. My recommendation is to add this query as it will help in reducing vulnerabilities.
- With regards to writing custom queries for our website repo, I was able to run a sample QL query locally as follows:
  - I created a database of my own website repo using the QL extension available in VS code marketplace.
  - Ran a sample JS query on this database to produce alerts.
  - Will try to reciprocate these alerts as part of the CodeQL workflow in my own website repo next.
- Also, will work on creating a demo query for identifying vulnerabilities with GitHub actions since I haven't come across any query pack available to do this within CodeQL codebase. 


Blockers: No blockers
Availability: 5 hours 
ETA: 1/10/23

**Comment by SAUMILDHANKAR** [comment]
Progress: Made progress on adding custom codeql query for scanning our codebase:

- I added a custom codeql javascript query as per the following steps:
  - Created a [codeql config yaml file](https://github.com/SAUMILDHANKAR/website/blob/forcodeqlv4/.github/workflows/codeql-config.yml) in my own repo with the [path](https://github.com/SAUMILDHANKAR/website/blob/0756b66e6979daa309f15995664664646e4bce70/.github/workflows/codeql-config.yml#L7) to JS query. Also, added a condition ``disable-default-queries: true`` which makes sure that no other query except the custom query is run.
  - This path points to the [.ql file](https://github.com/SAUMILDHANKAR/codeql/blob/main/javascript/ql/src/Security/CWE-830/FunctionalityFromUntrustedSource.ql) in my cloned repo of github/codeql repo. Using github/codeql repo directly works as well but it isn't advised.
  - Added a reference of [codeql config yaml file](https://github.com/SAUMILDHANKAR/website/blob/forcodeqlv4/.github/workflows/codeql-config.yml) to the main [codeql.yml](https://github.com/SAUMILDHANKAR/website/blob/forcodeqlv4/.github/workflows/codeql.yml) workflow file.
  - On running the [codeql.yml](https://github.com/SAUMILDHANKAR/website/blob/forcodeqlv4/.github/workflows/codeql.yml) workflow file now, we can see the [security alerts](https://github.com/SAUMILDHANKAR/website/security/code-scanning/29) being generated as per the single custom query. Older alerts are also updated accordingly.
- Next, will work on creating a custom query for identifying vulnerabilities in the yml files used for GitHub actions' workflows. 

Blockers: No blockers
Availability: 5 hours 
ETA: 1/26/23

**Comment by SAUMILDHANKAR** [comment]
Progress: Didn't work much on this issue since I had a take home assessment for a job opportunity last week, but I should have an update on this soon.
Blockers: No blockers
Availability: 5 hours
ETA: 2/12/23

**Comment by jdingeman** [comment]
Hey @SAUMILDHANKAR. hope you are well. Just wanted to check in with you on this. Looks like you had planned an update on February 12, but looks like no movement since February 3.

**Comment by SAUMILDHANKAR** [comment]
Progress: @jdingeman sorry for the delay in update, below is my progress so far:

- Things that I have tried so far for setting up custom queries:
  - I ran a java query on a sample repo but it is failing at the autobuild step. This step might need customization for some specific languages.
  - I created a javascript custom query to identify vulnerability in a test js file as part of GitHub actions workflow which was unsuccessful. CodeQL has [documentation](https://docs.github.com/en/code-security/codeql-cli/using-the-codeql-cli/testing-custom-queries#prepare-a-query-and-test-files) on testing custom queries for CLI but I need more research to use this as part of our workflow.
- Things that I am planning to try next: 
  - Planning to dig deeper on custom queries as per this [documentation](https://codeql.github.com/docs/writing-codeql-queries/codeql-queries/#codeql-queries).
  - Study [CodeQL library guide for JavaScript](https://codeql.github.com/docs/codeql-language-guides/codeql-library-for-javascript/) and explore if this information can be used in developing custom queries for GitHub actions/Liquid.
  - I expect these steps might take couple of weeks for completion
- General observation: It would be really helpful to have few working examples of sample custom queries within CodeQL documentation but I haven't come across any such yet.

Blockers: No blockers, however huge learning curve to develop custom queries from scratch though it should be worth it for our repo in the long run.
Availability: 5 hours per week.
ETA: 3/6/23

**Comment by SAUMILDHANKAR** [comment]
Progress: Quick update 
  - While reading up on JavaScript language guide, I came across ```semmle.javascript.yaml``` [YAML library](https://codeql.github.com/docs/codeql-language-guides/codeql-library-for-javascript/#yaml). This could be helpful for writing queries for the yml files in GitHub actions. I couldn't test this out yet since Actions is experiencing an incident outage but will try again over the weekend. 
  - Also searched ruby language guide for any support library on liquid code but didn't find any. Creating one just like it exists for yaml might be helpful for creating custom queries for liquid. Will explore this more.

Blockers: No blockers.
Availability: 5 hours per week.
ETA: 3/10/23

**Comment by SAUMILDHANKAR** [comment]
Progress: Update on creating a custom query: 
  - As part of creating a custom query, I created a [test js](https://github.com/SAUMILDHANKAR/website/blob/forcodeqlv5/assets/js/commentedcode.js) file in my hfla website repo with errors related to commented out code and then ran the [commented out code ql query](https://github.com/SAUMILDHANKAR/codeql/blob/testingquery/javascript/ql/src/Comments/CommentedOutCode.ql). This was successful and I was able to capture the errors in [code scanning alerts](https://github.com/SAUMILDHANKAR/website/security/code-scanning) under the security tab.    
    - Next step as part of this would be to edit the default commented out code ql query to include an extra scenario and then try capturing it again in code scanning alert. Subsequently, we can have an entirely new custom query as per the project requirements. 
  - Also, created a yaml file with syntax error related to on push/pull_request and ran the standard javascript security and quality ql query. However, was not able to catch the error. This will need more work.
  - Finally, we would also need to define an actual error in yml files or liquid code which our custom query is supposed to capture. I will do more research on this and will also check with the team for more ideas.

Blockers: No blockers.
Availability: 5 hours per week.
ETA: 4/1/23

**Comment by SAUMILDHANKAR** [comment]
Progress update: 
  - Instead of using [commented out code ql query](https://github.com/SAUMILDHANKAR/codeql/blob/testingquery/javascript/ql/src/Comments/CommentedOutCode.ql) (as shared in my last progress update) provided by CodeQL, I created a new [QL file](https://github.com/SAUMILDHANKAR/codeql/blob/testingquery/javascript/ql/src/Comments/FUTUREBUG.ql) to generate scanning alerts based on error introduced in my [test js](https://github.com/SAUMILDHANKAR/website/blob/forcodeqlv5/assets/js/commentedcode.js) file. I was able to successfully generate the [scanning alert](https://github.com/SAUMILDHANKAR/website/security/code-scanning/82) for the bug introduced. The new QL query uses regexpmatch function to identify certain keywords in comments as per the requirements.
    - Key takeaways: I created two new files [.ql](https://github.com/SAUMILDHANKAR/codeql/blob/testingquery/javascript/ql/src/Comments/FUTUREBUG.ql) and [.qhelp](https://github.com/SAUMILDHANKAR/codeql/blob/testingquery/javascript/ql/src/Comments/FUTUREBUG.qhelp). In the .ql file, imported just the javascript library, added metadata and included from, where and select clauses (used to display results). 
    - [This query](https://github.com/SAUMILDHANKAR/website/blob/5a2e4183b614649512cdae122ce29a227d052c34/.github/workflows/codeql.yml#L76) in the yaml file generates the alert
    - Similarly, we can create other Javascript custom queries based on specific requirements.
  - Next step: In the next custom query, I am planning to import ```semmle.javascript.YAML``` library to scan errors related to yaml files.

Blockers: No blockers but still learning from CodeQL documentation.
Availability: 5 hours per week.
ETA: 4/20/23

**Comment by SAUMILDHANKAR** [comment]
Progress update: 
  - To identify errors, in yaml files (used to write GitHub actions) using custom CodeQL queries, I created two new QL files. [QL file for parse error](https://github.com/SAUMILDHANKAR/codeql/blob/testingquery/javascript/ql/test/library-tests/YAML/tests.ql) and [QL file for YAML anchor node](https://github.com/SAUMILDHANKAR/codeql/blob/testingquery/javascript/ql/test/library-tests/YAML/ForYAMLNodeAnchor.ql) to generate scanning alerts, based on errors introduced in my [yaml1](https://github.com/SAUMILDHANKAR/website/blob/forcodeqlv5/.github/workflows/testyamlnode.yml) and [yaml2](https://github.com/SAUMILDHANKAR/website/blob/forcodeqlv5/.github/workflows/merge1.yaml) files. I was able to successfully generate the [scanning alert1](https://github.com/SAUMILDHANKAR/website/security/code-scanning/5434) and [scanning alert2](https://github.com/SAUMILDHANKAR/website/security/code-scanning/5433) respectively for the bugs introduced, using the classes defined in ```semmle.javascript.YAML``` library.
    - Key takeaways: Process to write a custom query for yaml files(GitHub actions) is similar to what I shared earlier for custom query for js files. I created two new files [.ql](https://github.com/SAUMILDHANKAR/codeql/blob/testingquery/javascript/ql/test/library-tests/YAML/tests.ql) and [.qhelp](https://github.com/SAUMILDHANKAR/codeql/blob/testingquery/javascript/ql/test/library-tests/YAML/tests.qhelp). In the .ql file, imported the ```javascript``` and ```semmle.javascript.YAML``` libraries, added metadata and included from, where (if required) and select clauses (used to display results). 
    - Specifically, I used [YamlParseError](https://codeql.github.com/codeql-standard-libraries/javascript/semmle/javascript/YAML.qll/type.YAML$YamlParseError.html) and [YamlNode](https://codeql.github.com/codeql-standard-libraries/javascript/semmle/javascript/YAML.qll/type.YAML$YamlNode.html) classes to generate code scanning alerts related to generating an error message while parsing yaml file and returning a node referring to anchor string respectively. Scanning alerts for [parsing error](https://github.com/SAUMILDHANKAR/website/security/code-scanning/5434) and [yaml node anchor](https://github.com/SAUMILDHANKAR/website/security/code-scanning/5433).
	- For YAML anchor node, [this query](https://github.com/SAUMILDHANKAR/website/blob/331b835764d18e90e0d4a1298cb58e9a17b727fe/.github/workflows/codeql.yml#L83) in the yaml file generates the alert and for parse error, [this query](https://github.com/SAUMILDHANKAR/website/blob/331b835764d18e90e0d4a1298cb58e9a17b727fe/.github/workflows/codeql.yml#L81) generates the alert.
	- I would update the qhelp and meta data specifically for these queries in my final demo.
	- Similarly, we can define other custom queries based on requirements to identify specific vulnerabilities in GitHub actions.
  - Next step: Will be working on the final action item for this issue, that is to generate scanning alerts for liquid syntax. Planning to either use Regex module or create a new library within Ruby to accomplish that.

Blockers: No blockers, would be reading up on regex and new library creation from CodeQL documentation.
Availability: 5 hours per week.
ETA: 4/30/23

**Comment by SAUMILDHANKAR** [comment]
Progress update: 
  - For working with liquid code, I created a [custom script](https://github.com/SAUMILDHANKAR/codeql/blob/testingquery/javascript/ql/src/Comments/ForLiquidComment.ql) for if there is liquid code with syntax, ```{{ xxx }}```, in the comments of an html file, there should be a code scanning alert. I was able to generate the [code scanning alert](https://github.com/SAUMILDHANKAR/website/security/code-scanning/5432) for an instance created in a [test html file](https://github.com/SAUMILDHANKAR/website/blob/forcodeqlv5/pages/newComment.html).
  - I am using [this query](https://github.com/SAUMILDHANKAR/website/blob/b1306379ac4ba05cd03dcc7456d12bd945bfd33b/.github/workflows/codeql.yml#L78) in a yaml file to generate the code scanning alerts for this case. 
  - Next, I will clean up my code so it is ready for demo before reaching out to leads for feedback. Planning to reach out by coming Sunday.
  - We can also discuss if other custom queries should be explored.

Blockers: No blockers.
Availability: 5 hours per week.
ETA: 5/10/23

**Comment by SAUMILDHANKAR** [comment]
Progress update: 
  - I have cleaned up my documentation and am ready for demo to the leads. 

Blockers: No blockers.
Availability: 5 hours per week.
ETA: 5/25/23

@jdingeman Hi Justin, I would like to demo my research on this issue before making a pull request. Please recommend a suitable time to connect. My schedule is flexible, and I can make it around team meeting slots or any other time as well. Will leave a note on slack as well. Thank you.

**Comment by SAUMILDHANKAR** [comment]
Progress update: 
  - Following up with dev team if demo might be preferred before making the pull request. 

Blockers: No blockers.
Availability: 5 hours per week.
ETA: 6/20/23

**Comment by t-will-gillis** [comment]
Hi @SAUMILDHANKAR  thanks so much for your extensive work on this issue. There is a lot of info here to digest and I apologize if I am asking questions that you have already answered, but just to confirm- the current implementation will scan all of the js files in the website repo and generate in this case the 57 notifications that we could address one by one. Then it is also scanning future PRs, correct? You indicate that it will block merging for critical or high security issues- for the others I assume it would flag the issues so they could be addressed before merging? 

Side discussion: As a group, do we need to decide which “Protection rules” to use, i.e. what “Security” level and “Errors, Warnings, or Any”- or for now do we go with the defaults?

Lastly, the 3 linked comments I believe refer to custom queries you wrote for scanning yaml and liquid code. Would these scans run at the same time as scans for the js files?

Thank you again- this is going to be very useful when it is up and running
