### ISSUE TITLE
Experiment with embedding an iframe of the project into 

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2407]
### Overview
We want to be able to test displaying the projects on the project pages on the hfla site using iframe and see how this works for us.

### Action Items
- [x] Decide where and how we would store the iframe info for project cards
- [x] create a flag or other method for the pages to know when to display the extra card and iframe per page
- [x] embed the iframe into a new extra card on the bottom of the food oasis page.  

### Resources/Instructions
- [Food Oasis's Instructions for embedding the food oasis tool into our site](https://github.com/hackforla/food-oasis/wiki/Embedding-Food-Oasis-in-Your-Web-Site)
- Food Oasis page on hackforla.org website: https://www.hackforla.org/projects/food-oasis

**Comment by macho-catt** [comment]
Progress: Can show iframe on specific pages, but height is static
Blockers: Other projects / life
Availability: 2 hours
ETA: next week
Pictures: N/A

**Comment by ExperimentsInHonesty** [comment]
@macho-catt Weirdly on one of my screens it looks fine, and another one is does not.  Both on the same computer.  two different chrome windows

![image](https://user-images.githubusercontent.com/37763229/141925222-53f9b9f0-8a11-48eb-adda-50060a883cf1.png)

![image](https://user-images.githubusercontent.com/37763229/141925351-bde14d83-6c6d-4981-977b-09c3f0770b50.png)

**Comment by macho-catt** [comment]
@ExperimentsInHonesty you may have to clear your cache and exit all browsers, then reopen. Another clean way of testing this is opening the webpage in incognito mode.

**Comment by SAUMILDHANKAR** [comment]
@macho-catt will add the relevant code to project.md file in the wiki.

**Comment by macho-catt** [comment]
Added new lines at the end for iframes:
https://github.com/hackforla/website/wiki/project.md-file-template
