### ISSUE TITLE
GitHub Actions: Modify: Add Update Label to Issues Weekly

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2409]
~### Dependency~
~#1977~

### Overview
We need to ONLY notify developers that we need an update if necessary to move things forward, so that the requests for updates don't start getting ignored and the issue become hard to read.

### Details
Currently, the GitHub action will ask a developer for an update on an issue even if they have an open PR. Modify the JS of [this](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-update-label-weekly.yml) GitHub action so that if an issue has a linked PR, the bot won't ask the user for an update on the issue.

The JS already looks if their is a linked PR to the issue, and the bot does not comment on the first week that the PR was linked, but then the bot will continue to ask for updates the weeks afterwards. This should not be the case.

### Pseudo
- [ ] Triggers at the same time as [this](https://github.com/hackforla/website/blob/gh-pages/github-actions/add-update-label-weekly/add-label.js) gh-action
    - [ ] If the issue has a linked PR by the same assignee of the issue
        - [ ] Then the bot should not ask for an update

### Actions
- [ ] Implement the above pseudo-code
- [ ] Test the action on your own fork first and ensure that it works
- [ ] When you open your PR, link your fork and add screenshots of the action working
    - [ ] Alternatively, you can demo the GitHub Action to the current backend lead

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[Add Update Label to Issues Weekly](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-update-label-weekly.yml)
[Related JS](https://github.com/hackforla/website/blob/gh-pages/github-actions/add-update-label-weekly/add-label.js)

Note that you might want to do something outside the scope of the above psudo-code. If so, be sure to leave comments in your PR or this issue that justifies your reasoning. If you feel you need guidance, be sure to reach out! We cannot foresee whether this issue is solvable, or what hard decisions have to be made, but we would love to hear and help you!

#### Additional resources:
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[GitHub GraphQL](https://docs.github.com/en/graphql)

**Comment by SAUMILDHANKAR** [comment]
This has already been implemented in #1977 so closing this issue.

**Comment by SAUMILDHANKAR** [comment]
I closed this issue since this was accomplished in #1977, however, now we need to create a new issue which posts comments every week so the review is timely and efficient. My question is should we edit this issue or create a new issue?

**Comment by SAUMILDHANKAR** [comment]
> I closed this issue since this was accomplished in #1977, however, now we need to create a new issue which posts comments every week so the review is timely and efficient. My question is should we edit this issue or create a new issue?

During the team meeting, we decided to move this to Done as this issue is not related to the above comment.
