### ISSUE TITLE
 Update Getting Started Page: header text

### ISSUE THREAD

**Issue by adam-abundis** [hackforla/website#2417]
### Overview
We need to update the styling for our header text so that it makes the page more readable. 
<details>
  <summary><strong>Click here</strong> to see the current header text (<strong>before changes</strong>)</summary>

  ![getting-started-header-text-before-desktop](https://user-images.githubusercontent.com/21162229/138681123-acafc401-e88f-476a-937d-5f6428ae6111.jpg)
</details>
<details>
  <summary><strong>Click here</strong> to see the proposed header text (<strong>after changes</strong>)</summary>

  ![getting-started-header-text-after-desktop](https://user-images.githubusercontent.com/21162229/138681659-eedaf386-9a23-4672-be49-b73992f5506d.jpg)
</details>

### Action Items

- [x] Change the **font-size** property to `font-size: 16px;` for the following classes: 
  - [x] `.header-bold-p`
  - [x] `.header-p`

### Resources/Instructions
Design issue #1842 
https://www.hackforla.org/getting-started
https://github.com/hackforla/website/blob/055674d5ccb25b7acc2e8d33a9b7f29b929b0fe2/_sass/components/_getting-started-page.scss#L5-L32

**Comment by JessicaLucindaCheng** [comment]
Availability: 7am - 5pm Thu, Dec 9 - Sat, Dec 11
ETA: Sun, Dec 12, 2021

**Comment by JessicaLucindaCheng** [comment]
- Progress: Done and PR made
- Blockers: None
- Availability: 7am-9am PST Mon-Thu, Dec 13-16, 2021
- ETA: Already completed

**Comment by ExperimentsInHonesty** [comment]
This issue was followed completely and the developer did a good job.  I am keeping it open because while QAing it, I compared it against another page and found out that they were not consistently styled.  I am adding a note here about it, to investigate the problem.  The original assignee does not need to do anything.

This is a new PR(#2417), but when I look at the headers for these two pages they are different
      [getting started](https://www.hackforla.org/getting-started) page  ```<p class="header-p">```
      vs the [communities of practice ](https://www.hackforla.org/communities-of-practice)  ```<p>```
