### ISSUE TITLE
Update Project Profile: Design Systems

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2419]
### Overview
As a product manager of Design Systems I want my project's details to be up to date on the HackforLA website

### Project card
URL where existing file can be found
https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md

### Action Items
- [x] Add the following team members to the Leadership section of the project card
Name: Hana Stevenson
Role: Product Manager
Slack ID: UJ32EQ9LG
GitHub Handle: hanastevenson

Name: Nasim Biglari
Role: Research Lead 
Slack ID: U01N30TK76W
GitHub Handle: nasimbiglari

Name: Ryan Curtis
Role: UX/UI Lead 
Slack ID: U01UPE4RNHZ
GitHub Handle: rcurtis2

Name: Anh Hoang
Role: UX/UI Designer
Slack ID: U025DUAKAPK
GitHub Handle:ahoang94

Name: Jeanette Renema
Role: UX Researcher
Slack ID: U02HE00UDQS
GitHub Handle: JeannyRen

Name: Anthony Navarro-Liu
Role: UX Researcher 
Slack ID: U02H764K6D8
GitHub Handle: navarroliuanthony

Name: Anna Knutson
Role: UX Researcher
Slack ID: U02HDMN9JD9
GitHub Handle: avknutson

Name: Bernard Adesina
Role: UX/UI Designer
Slack ID: U01FAP6GL23
GitHub Handle: AdesinaBernard

Name: Anastasia Nekrasova
Role: UX/UI Designer
Slack ID: U028E4B7JSC
GitHub Handle: anekkk

**Comment by JessicaLucindaCheng** [comment]
Availability: 7am - 5pm Thu, Dec 9 - Sat, Dec 11
ETA: Sun, Dec 12, 2021

**Comment by JessicaLucindaCheng** [comment]
Hana Stevenson's Slack id is UJ32EQ9LG.

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng fyi, for the future, please use the [full page screen shot chrome extension](https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en
) to make the screen.  So in the case of this issue it would look like this:
![screencapture-hackforla-org-projects-design-systems-2021-12-12-15_14_42](https://user-images.githubusercontent.com/37763229/145733553-c5e86314-4200-49c6-9628-97635a2640b1.png)

**Comment by ExperimentsInHonesty** [comment]
sent design team a message to have them signoff on issue

**Comment by JessicaLucindaCheng** [comment]
> @JessicaLucindaCheng fyi, for the future, please use the [full page screen shot chrome extension](https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en
> ) to make the screen.  So in the case of this issue it would look like this:
> ![screencapture-hackforla-org-projects-design-systems-2021-12-12-15_14_42](https://user-images.githubusercontent.com/37763229/145733553-c5e86314-4200-49c6-9628-97635a2640b1.png)
> 
> 
@ExperimentsInHonesty I'll be sure to do that in the future. Thanks.

**Comment by ExperimentsInHonesty** [comment]
Didn't hear back from them. Went ahead an closed this issue
