### ISSUE TITLE
Revise UX survey forms and link to website

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#242]
### Overview
Revise UX survey forms for distribution to organization.

### Action Items
- [x] Revise Google UX survey forms to split questions by Yes/No and free-form response types. 
- [x] Revise Excel dashboard to reflect changes to survey.
- [x] Collect royalty-free images for use in survey banner
- [x] Update project lists across all surveys
- [x] Post project leader survey in Project Lead Slack channel

### Resources/Instructions
https://docs.google.com/forms/d/1hE2H-r5SIT4Ewzu2Vz5vSGqMYVZqQL94g4jpaLYXpGM/edit

"Why are you here?" spreadsheet: https://docs.google.com/spreadsheets/d/1FcgoJJVy1ZxqDnONDUaL7XUk2vj3kUPbY6zZC2Neh7k/edit#gid=0

Reference survey by Nathan Danielson for SoCal tech community mapping project: https://docs.google.com/forms/d/e/1FAIpQLSf-ARwLJofwDe6iGQeMKCYEznrrJ3NnSwURaUxmooSHIX0_Mw/viewform

Shared drive: https://drive.google.com/drive/u/0/folders/1p76K0FgfiAWeIIEyoyJ_Iik8FVj8cBjT

Survey tracker: https://docs.google.com/spreadsheets/d/1zo4I6NiGPgkweC1OIrcLaGDrK-FTGke6PfJREla-VdQ/edit#gid=1260346201

**Comment by ashlingam** [comment]
1. Progress - All Google Survey forms have been revised to incorporate questions specific to stakeholder. Excel workbook has been updated and no longer includes a composite spreadsheet, since survey forms are not homogenous. Ready to post to website and share URL links.
2. Blocks - None
3. Availability - Mon, Thurs, Fri, Sun
4. ETA - 2/16

**Comment by ashlingam** [comment]
@ExperimentsInHonesty I believe the user surveys are now ready to be deployed. I brought over a few relevant questions from the Project Leader survey to the New Member survey that concern skills (https://docs.google.com/forms/d/1UB28awbncRSbsk-YjtAt-AYQdYootj_K2bFhaahtTPI/edit?usp=drive_web).

I think the next step is to host the surveys on the website and associate each Google Form with a corresponding unique URL. These URLs can then be shared with our target survey recipients.

I believe aggregate analytics are best visualized within each Google Form itself. Data for those survey questions found across all our forms may be aggregated into a composite Excel spreadsheet, if necessary, at any point in time.

**Comment by ExperimentsInHonesty** [comment]
@harishlingam create an issue that has all the routes
eg   
hackforla.org/survey1
https://docs.google.com/forms/d/1UB28awbncRSbsk-YjtAt-AYQdYootj_K2bFhaahtTPI/edit?usp=drive_web

drop in website folder.

**Comment by ashlingam** [comment]
1. Progress - Onboarding survey has been updated to incorporate question concerning COVID-19 response: https://docs.google.com/forms/d/1hE2H-r5SIT4Ewzu2Vz5vSGqMYVZqQL94g4jpaLYXpGM/edit. Other surveys are being updated to reflect current projects list: https://docs.google.com/forms/d/1_nar2H41_Ac-4MC2Eyx8vZGDzvflqnNgxu9irfAJWVE/edit?usp=sharing
2. Blocks - None
3. Availability - Sunday, Monday, Saturday
4. ETA - 04/06/20
