### ISSUE TITLE
Accessibility: Change bold to strong in 2FA.html

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2423]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
To be WCAG compliant and ensure the same experience to all users, we want to change b tags to strong tags.

### Action Items
- [x] Change all the b tags to strong tags within `_guide-pages/2FA.html`
- [x] **Line 24**

From:
```
<h3 class="title-left"><b>To Enable 2FA:</b></h3>
```
To:
```
<h3 class="title-left"><strong>To Enable 2FA:</strong></h3>
```
- [x] **Line 25**

From:
```
<h5 class="title-left"><b>Visit and follow </b><b><a href="https://docs.github.com/en/github/authenticating-to-github/configuring-two-factor-authentication" target="blank">Github's Guide to Setting Up 2FA</a></b></h5>
```
To:
```
<h5 class="title-left"><strong>Visit and follow <a href="https://docs.github.com/en/github/authenticating-to-github/configuring-two-factor-authentication" target="blank">Github's Guide to Setting Up 2FA</a></strong></h5>
```

### Resources/Instructions
- [Article on why we should use semantic tags like strong and em](https://help.siteimprove.com/support/solutions/articles/80000448460-accessibility-bold-vs-strong-and-italic-vs-emphasis)
- [Affected webpage](https://www.hackforla.org/guide-pages/2FA)
- Directory to find the page in once you have it in your IDE: `_guide-pages/2FA.html`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/e29b4b2d474c012dfba681f1342d8cfcaa67039f/_guide-pages/2FA.html#L24-L25

**Comment by JessicaLucindaCheng** [comment]
@greylaw89 At the time you self-assign an issue, make sure to write in a comment your availability (how many hours you have to work on the issue this week) and ETA (when you think you will finish the issue).

**Comment by JessicaLucindaCheng** [comment]
@greylaw89 Also, when you self-assign an issue, you need to move the issue from the Prioritized Backlog into the In Progress column. So, please move this issue into the In Progress column.

**Comment by JessicaLucindaCheng** [comment]
@Sparky-code I saw you moved this issue into the Questions/In Review column. Did you have a question about this issue that Kristoffer is assigned to?

**Comment by greylaw89** [comment]
Thank you Jessica - I'll make the revisions and changes this weekend.

Kristoffer Law

**Comment by Sparky-code** [comment]
@JessicaLucindaCheng No, I'm sorry that must have been by mistake.

**Comment by JessicaLucindaCheng** [comment]
@greylaw89 I went ahead and moved the issue into the In Progress column this time.

> @greylaw89 Also, when you self-assign an issue, you need to move the issue from the Prioritized Backlog into the In Progress column. So, please move this issue into the In Progress column.

**Comment by SAUMILDHANKAR** [comment]
@greylaw89 I am planning to unassign you from this issue due to inactivity. Feel free to work on this or any other issue when your availability changes. Thank you.

**Comment by juliansmith0** [comment]
Availability for this week: 5 hours
My estimated ETA for completing this issue: Friday, May 20, 2022
