### ISSUE TITLE
Accessibility: Change bold to strong in about-card-donations.html

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2424]
### Prerequisite
Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
To be WCAG compliant and ensure the same experience to all users, we want to change b tags to strong tags.

### Action Items
- [ ] Change all the b tags to strong tags within `_includes/about-page/about-card-donations.html`
- [ ] **Line 10**

From:
```
<li class="donation-spacing"><p>To make a donation please select <b>Hack for LA</b> under the brigades listed.</p>
```
To:
```
<li class="donation-spacing"><p>To make a donation please select <strong>Hack for LA</strong> under the brigades listed.</p>
```

### Resources/Instructions
- [Article on why we should use semantic tags like strong and em](https://help.siteimprove.com/support/solutions/articles/80000448460-accessibility-bold-vs-strong-and-italic-vs-emphasis)
- [Affected Webpage](https://www.hackforla.org/about/#donations)
- Directory to find the page in once you have it in your IDE: `_includes/about-page/about-card-donations.html`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/e29b4b2d474c012dfba681f1342d8cfcaa67039f/_includes/about-page/about-card-donations.html#L10

**Comment by oneamanish** [comment]
Hello,
can you assign me?

**Comment by oneamanish** [comment]
Hello,
can you assign me?

**Comment by macho-catt** [comment]
Hi @oneamanish, to contribute to our repo, you do need to join the HackForLA organization first. Please check this [website ](https://www.hackforla.org/join)to learn more on how to join our team.
