### ISSUE TITLE
Accessibility: Change bold to strong in donate.html

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2425]
### Prerequisite
Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
To be WCAG compliant and ensure the same experience to all users, we want to change b tags to strong tags.

### Action Items
- [x] Change all the b tags to strong tags within `pages/donate.html`
- [x] **Line 54**

From:
```
To make a donation please select <b>Hack for LA</b> under the brigades
```
To:
```
To make a donation please select <strong>Hack for LA</strong> under the brigades
```

### Resources/Instructions
- [Article on why we should use semantic tags like strong and em](https://help.siteimprove.com/support/solutions/articles/80000448460-accessibility-bold-vs-strong-and-italic-vs-emphasis)
- [Affected webpage](https://www.hackforla.org/donate/)
- Directory to find the page in once you have it in your IDE: `pages/donate.html`
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/e29b4b2d474c012dfba681f1342d8cfcaa67039f/pages/donate.html#L54

**Comment by oneamanish** [comment]
see my pull req.

**Comment by macho-catt** [comment]
Hi @oneamanish, to contribute to our repo, you do need to join the HackForLA organization first. I will close your pull request. Please check this [website ](https://www.hackforla.org/join)to learn more on how to join our team.
