### ISSUE TITLE
Update Civic Opportunity Project GitHub link

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2434]
### Prerequisite
Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We need to ensure that links on the website resolve properly and are up to date.

### Action Items
- [x] Change the GitHub link for Civic Opportunity Project so it resolves to the correct url
    - **Line 24** under `_projects/civic-opportunity-project.md`

From:
```
url: 'https://github.com/hackforla/civic-opportunity/projects/1'
```
To:
```
url: 'https://github.com/hackforla/civic-opportunity'
```
- [x] Ensure that clicking the Readme link from the [projects page](https://www.hackforla.org/projects/) and [Civic Opportunity Project page](https://www.hackforla.org/projects/civic-opportunity-project) both resolve to the new address

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/civic-opportunity-project.md`
- [Projects page](https://www.hackforla.org/projects/)
- [Civic Opportunity Project page](https://www.hackforla.org/projects/civic-opportunity-project)
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/883a983b8f987ad3c0167781de7512c8c06b0d60/_projects/civic-opportunity-project.md#L24

**Comment by anthonysim** [comment]
Availability for this week: 
- Fri (12/3/21): 5:00 - 7:00 PM
- Sat (12/4/21): 12:00 - 1:30 PM
My estimated ETA for completing this issue: 12/4/2021
