### ISSUE TITLE
Update outdated Demo link for Write for All

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2435]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We need to ensure that links on the website resolve properly so that we can maintain a professional website. If they are outdated or no longer work, they should be removed or updated.  

### Action Items
- [x] In `_projects/writeforall.md`, update the Demo link for Write for All since it is outdated
  From:
  ```
  - name: Demo link
    url: 'http://writeforall.org/'
  ```
  To:
  ```
  - name: Demo link
    url: 'https://hackforla.github.io/writeforall/'
  ```
- [x] Ensure that the demo link works properly on the [projects page](https://www.hackforla.org/projects/) and [Write for All page](https://www.hackforla.org/projects/writeforall)

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/writeforall.md`
- [Projects page](https://www.hackforla.org/projects/)
- [Write for All page](https://www.hackforla.org/projects/writeforall)
- Click on the link to see the source file code: https://github.com/hackforla/website/blob/gh-pages/_projects/writeforall.md?plain=1

**Comment by ExperimentsInHonesty** [comment]
Bonnie will write to Joel and find out what happened to the domain name.

**Comment by ExperimentsInHonesty** [comment]
I have written to Joel. Check back for a response at next meeting
https://mail.google.com/mail/u/0/#search/joel%40joelparkerhenderson.com

**Comment by ExperimentsInHonesty** [comment]
Hi Dev leads, there is several things that need to be done here.  we have added it to todays dev/pm meetings for clarification.

I met with Joel.  We need to mark this project as on hold and replace the demo link with this url https://hackforla.github.io/writeforall/

**Comment by ExperimentsInHonesty** [comment]
@blulady I updated the instructions to make this issue easier to process

**Comment by 7kram** [comment]
We can remove the product label and add front/back end so that devs can work on it

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 
> Hi Dev leads, there is several things that need to be done here. we have added it to todays dev/pm meetings for clarification.
> 
> I met with Joel. We need to mark this project as on hold and replace the demo link with this url https://hackforla.github.io/writeforall/

- This issue has been updated with the new demo link: https://hackforla.github.io/writeforall/
- Issue #3837 addresses marking this project as on hold.

**Comment by christinaor** [comment]
Availability for this week: Monday - Friday EST
My estimated ETA for completing this issue: Sunday, 1/29

**Comment by christinaor** [comment]
How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?
About 2 weeks due to personal events blocking me.
