### ISSUE TITLE
Remove outdated Site link for Spare

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2437]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We need to ensure that links on the website resolve properly. If they are outdated or no longer work, they should be removed.

### Action Items
- [ ] Remove the Site link for Spare since it is outdated
    - **Lines 12 - 13** under `_projects/spare.md`

Delete:
```
 - name: Site
   url: 'http://whatcanyouspare.org'
```

- [x] Ensure that the site link is removed from the [projects page](https://www.hackforla.org/projects/) and [Spare page](https://www.hackforla.org/projects/spare)

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/spare.md`
- [Projects page](https://www.hackforla.org/projects/)
- [Spare page](https://www.hackforla.org/projects/spare)
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/883a983b8f987ad3c0167781de7512c8c06b0d60/_projects/spare.md#L12-L13

**Comment by SAUMILDHANKAR** [comment]
@KazushiR Please add your issue to the In progress column and share your ETA and availability for working on this issue. Thank you.

**Comment by KazushiR** [comment]
@SAUMILDHANKAR I have updated the progress of this issue and I will see if I can get this done sometime next week.

**Comment by SAUMILDHANKAR** [comment]
@KazushiR Thank you for moving the issue to the In progress column. Just wanted to share the format to be used while picking up an issue:

Availability for this week:
My estimated ETA for completing this issue:
