### ISSUE TITLE
GitHub Actions: Improvements to error logs in add-label.js

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2438]
### Overview
As a developer, we need to ensure that the GHA to add labels produces a more descriptive error log when failing because currently it produces a generic error statement which might not be too helpful while debugging.

### Action Items
- [x] Become familiar with how the [GitHub action](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-update-label-weekly.yml) "Add Update Label to Issues Weekly" works
- [x] [JS Edits](https://github.com/hackforla/website/blob/gh-pages/github-actions/add-update-label-weekly/add-label.js)
    - [x] Under the function removeLabels (line 141), update the catch so it logs the exact error when it fails
    - [x] Under the function addLabels (line 163), update the catch so it takes in err as a parameter, and log the exact error if it fails
    - [x] Under the function postComment (line 190), update the catch so it logs the exact error when it fails
    - [x] Under the function getAssignees (line 227), update the catch so it logs the exact error when it fails

### Details
It is always better to have more info on what the specific error is, rather than outputting a generic statement that a developer won't be able to debug. At the least, the error code should be added. At most, just include the body of the error statement so a developer can have an idea of why something failed.
<details>
<summary>Click for an example for a good error logging</summary>

```
console.err(`Function failed to <insert specific action here>. Please refer to the error below: \n ${err}`)
```

</details>

### Resources/Instructions
[add-update-label-weekly](https://github.com/hackforla/website/tree/gh-pages/github-actions/add-update-label-weekly)

**Comment by AsherEngelberg** [comment]
Availability: The Rest of the Day

ETA: 6:00 PM

**Comment by Suman2795** [comment]
Availability: Weekend,3-4 hours
ETA:Sunday,23/10/22
