### ISSUE TITLE
Create a project card for HackforLA.org Website 

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#244]
### Overview
Provide collateral for the HackforLA website

### Action Items
- [x]   Gather items
  - [x]  600 x 400 image (for hackforla homepage project card)
  - [x] 1500 x 700 Hero image (similar to hackforla homepage)
  - [x]  Alt image text
  - [x]  Name of project
  - [x]  A blurb about your project
  - [x]  Links (website, github, etc.)
  - [x]  What you are looking for skills wise
  - [x]  Tools your team uses (e.g. Balsamic, Figma, Photoshop, LucidChart, etc.)
  - [x]  Partner(s)
  - [x]  Location

- [ ]   Add project Card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples

**Comment by ashlingam** [comment]
@KianBadie @ExperimentsInHonesty HackforLA.org Website should have a card added to the website.

**Comment by KianBadie** [comment]
@harishlingam Sounds good! Is there currently information for what values will go in the fields for description, looking for, links, etc.?

**Comment by ExperimentsInHonesty** [comment]
![Screen Shot 2020-01-19 at 11 12 47 AM](https://user-images.githubusercontent.com/37763229/72699233-63472d00-3afc-11ea-9ecb-38dba8059d6b.png)


 Alt image text for project card image:, wireframe sample from new website
 Name of project: hackforla.org website
 Links (website, github, etc.): Site=hackforla.org
 What you are looking for skills wise: UI (wireframes), Photoshop
 Tools your team uses (e.g. Balsamic, Figma, Photoshop, LucidChart, etc.): LucidChart
 Partner(s): N/A
 Location: Santa Monica, Downtown and Remote

@harishlingam - the only thing left to do is write the blurb and find the image for the hero section on the project homepage.  Can you take a stab at writing the blurb?

**Comment by ExperimentsInHonesty** [comment]
See issue #272

**Comment by ExperimentsInHonesty** [comment]
@harishlingam please update with:
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
@ExperimentsInHonesty will write the blub after the 27th.

**Comment by ExperimentsInHonesty** [comment]
hero image https://github.com/hackforla/website/issues/272

**Comment by ExperimentsInHonesty** [comment]
1. Progress - none
2. Blocks - too many open issues and meetings
3. Availability - limited for this project
4. ETA 2/9

**Comment by ExperimentsInHonesty** [comment]
The hackforla.org website is our organization's way of communicating with new volunteers, stakeholders, and donors.  This project is a good place to start for new volunteers looking to polish their git protocol skills (branches, separation of concerns, etc.).  We are currently in a redesign phase, using CI/CD in the run up to demoing the new version at Code for America's Summit 2020 in Washington, D.C.

**Comment by leonelRos** [comment]
@ExperimentsInHonesty @harishlingam  I can't find the blurb for the HACKFORLA project card. I checked both issues #244 and #272 and can't find them. Please let me know.
