### ISSUE TITLE
Remove outdated links for Home Unite Us

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2441]
### Prerequisite
Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We need to ensure that links on the website resolve properly. If they are outdated or no longer work, they should be removed.

### Action Items
- [x] Remove the Demo link for Home Unite Us since it is outdated
    - **Lines 29 - 30** under `_projects/home-unite-us.md`

Delete:
```
  - name: Demo
    url: 'https://lacommunity.site/hosthome'
```
- [x] Remove the Test Site and Site links since they're also outdated
    - **Lines 37 - 40** under `_projects/home-unite-us.md`

Delete:
```
  - name: Test site
    url: "https://test.homeunite.us/"
  - name: Site
    url: 'https://homeunite.us/'
```

- [x] Ensure that the links are removed from the [projects page](https://www.hackforla.org/projects/) and [Home Unite Us page](https://www.hackforla.org/projects/home-unite-us)

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/home-unite-us.md`
- [Projects page](https://www.hackforla.org/projects/)
- [Home Unite Us page](https://www.hackforla.org/projects/home-unite-us)
- Click on the filename below to see the source file code:

https://github.com/hackforla/website/blob/883a983b8f987ad3c0167781de7512c8c06b0d60/_projects/home-unite-us.md#L29-L30

https://github.com/hackforla/website/blob/883a983b8f987ad3c0167781de7512c8c06b0d60/_projects/home-unite-us.md#L37-L40

**Comment by jqg123** [comment]
Availability for this week: 10hr
My estimated ETA for completing this issue: 12/2/21
