### ISSUE TITLE
Delete outdated page: getting-started-with-video.html

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2442]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We need to ensure that outdated and unused pages on the website are removed.

### Action Items
- [x] Delete the html file `/pages/getting-started-with-video.html`
- [x] Ensure that after deletion, visiting the link for the [webpage](https://www.hackforla.org/getting-started-with-video) in your environment results in a 404 error page.

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `pages/getting-started-with-video.html`
- [Source file code](https://github.com/hackforla/website/blob/8b2585f5cd0ac7c5ff568b7d790832f9935a5a01/pages/getting-started-with-video.html)

**Comment by Garcia1416** [comment]
Availability for this week: 6 hours
My estimated ETA for completing this issue: 1 week
