### ISSUE TITLE
Update Expunge Assist Slack link

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2443]
### Prerequisite
Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We need to ensure that links on the website resolve properly and are up to date.

### Action Items
- [x] Change the GitHub link for Expunge Assist so it resolves to the correct url
    - **Line 35** under `_projects/expunge-assist.md`

From:
```
url: 'https://hackforla.slack.com/messages/CDWKEBYBB'
```
To:
```
url: 'https://hackforla.slack.com/messages/CN8NXTPK5'
```
- [x] Ensure that clicking the Slack link from the [projects page](https://www.hackforla.org/projects/) and [Expunge Assist page](https://www.hackforla.org/projects/expunge-assist) both resolve to the new address

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/expunge-assist.md`
- [Projects page](https://www.hackforla.org/projects/)
- [Expunge Assist page](https://www.hackforla.org/projects/expunge-assist)
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/8b2585f5cd0ac7c5ff568b7d790832f9935a5a01/_projects/expunge-assist.md#L35

**Comment by sydneywalcoff** [comment]
Availability for this week: available all today (wed)
My estimated ETA for completing this issue: done by today
