### ISSUE TITLE
Update "Current Pages" in Figma (Credits, Sitemap, Program Areas, and Program Areas: Citizen Engagement)

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2446]
### Overview
We need to update the "Current Pages" file in Figma so that it accurately reflects both the current live versions of the **Credits, Sitemap, Program Areas, and Program Areas: Citizen Engagement** pages on the site, as well as the most updated Figma designs (which may or may not currently be live, but are approved for development).

### Action Items

- [x] Go to the "Current Pages" section in Figma
- [x] Locate the section in the gray box which provides guidance on how to structure the work you'll be doing on the page
- [x] Start a new section below what's currently on the page (following our Figma page layout guidance).
- [x] Find the Figma pages for each: **Credits, Sitemap, Program Areas,** and **Program Areas: Citizen Engagement**
- [x] For each one, navigate to that particular page on the current live website (if there is a live version, use sitemap page to check page status) 
- [x] Going back to the Figma page for the page you're working on, find the design that is currently live on the site. Copy and paste that design (both desktop and mobile) into the Current Pages file, following the structure shown in the example section of gray boxes. 
- [x] Go back to the Figma page for the page you're working on and find the design located in the red box, which represents the most up-to-date design for the page that has been approved for development. Copy and paste this version to the Current Pages file below the "Current live version" you just added. 
- [x] Do this for all 4 pages listed in this issue. 

### Resources/Instructions
[Figma - Current Pages](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A0)
[HfLA - Credits](https://www.hackforla.org/credits/)
[HfLA - Sitemap](https://www.hackforla.org/sitemap/)
[HfLA - Program Areas](https://www.hackforla.org/program-areas)
[HfLA - Program Areas - Citizen Engagement](https://www.hackforla.org/citizen-engagement)

**Comment by jenjen26** [comment]
**Progress:** Completed and moved to In Review 11/22
**Blockers:** 


**Availability:**
**ETA:**

**Comment by IsaacDesigns** [comment]
All pages look good except for Program Areas. Please organize it the same as the other pages.

Also, add the status of pages within the live sitemap similar to how I did in my issue similar to yours.

**Comment by ExperimentsInHonesty** [comment]
@jenjen26 The [HfLA - Program Areas - Citizen Engagement](https://www.hackforla.org/citizen-engagement) is live on the site, its just not linked to a menu at this point.  You can still check it.

**Comment by IsaacDesigns** [comment]
@jenjen26 No need to finish this issue. It will be resolved when I finish issue https://github.com/hackforla/website/issues/2512.
