### ISSUE TITLE
Update "Current Pages" in Figma (Projects Page, Individual Project Page, Join Us)

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2447]
### Overview
We need to update the "Current Pages" file in Figma so that it accurately reflects both the current live versions of the **Projects Homepage, Individual Projects Page, and Donate** pages on the site, as well as the most updated Figma designs (which may or may not currently be live, but are approved for development).

### Action Items

- [x] Go to the "Current Pages" section in Figma
- [x] Locate the section in the gray box which provides guidance on how to structure the work you'll be doing on the page
- [x] Start a new section below what's currently on the page (following our Figma page layout guidance).
- [x] Find the Figma pages for each: **Projects Page, Individual Project Page, Join Us**
- [x] For each one, navigate to that particular page on the current live website (if there is a live version, use sitemap page to check page status) 
- [x] Going back to the Figma page for the page you're working on, find the design that is currently live on the site. Copy and paste that design (both desktop and mobile) into the Current Pages file, following the structure shown in the example section of gray boxes. 
- [x] Go back to the Figma page for the page you're working on and find the design located in the red box, which represents the most up-to-date design for the page that has been approved for development. Copy and paste this version to the Current Pages file below the "Current live version" you just added. 
- [x] Do this for all 4 pages listed in this issue. 

### Resources/Instructions
[Figma - Current Pages](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A0)
[HfLA - Projects Page](https://www.hackforla.org/projects/)
[HfLA - 100 Automations (Individual Project)](https://www.hackforla.org/projects/100-automations)
[HfLA - Join Us](https://www.hackforla.org/join)

**Comment by iilashi** [comment]
Progress: Self-Assigned
Blockers: None at the moment!
Availability: Will be working on it in the coming days.
ETA: Ideally by this week's Thursday meeting.

**Comment by ExperimentsInHonesty** [comment]
@ilashi I see that you moved this issue into the questions column.  Please leave a comment indicating what the question is.

**Comment by iilashi** [comment]
I completed the issue and want it to be reviewed by the team to make sure everything is correct!

**Comment by IsaacDesigns** [comment]
No need to finish this issue. It will be resolved when I finish issue https://github.com/hackforla/website/issues/2512.
