### ISSUE TITLE
Update "Current Pages" in Figma (Nav Components, Toolkit, Guide Page, Donate)

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2448]
### Overview
We need to update the "Current Pages" file in Figma so that it accurately reflects both the current live versions of the **Nav Components (Top Nav & Footer), Toolkit, Guides, Donate** pages on the site, as well as the most updated Figma designs (which may or may not currently be live, but are approved for development).

### Action Items

- [x] Go to the "Current Pages" section in Figma
- [x] Locate the section in the gray box which provides guidance on how to structure the work you'll be doing on the page
- [x] Start a new section below what's currently on the page (following our Figma page layout guidance).
- [x] Find the Figma pages for each: **Nav Components (Top Nav & Footer), Toolkit, Guides, Donate**
- [x] For each one, navigate to that particular page on the current live website (if there is a live version, use sitemap page to check page status) 
- [x] Going back to the Figma page for the page you're working on, find the design that is currently live on the site. Copy and paste that design (both desktop and mobile) into the Current Pages file, following the structure shown in the example section of gray boxes. 
- [x] Go back to the Figma page for the page you're working on and find the design located in the red box, which represents the most up-to-date design for the page that has been approved for development. Copy and paste this version to the Current Pages file below the "Current live version" you just added. 
- [x] Do this for all 4 pages listed in this issue. 

### Resources/Instructions
[Figma - Current Pages](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A0)
[HfLA - Toolkit](https://www.hackforla.org/toolkit/)
[HfLA - Guide Page](https://www.hackforla.org/toolkit/)
[HfLA - Donate](https://www.hackforla.org/donate/)

**Comment by AnyaStewart** [comment]
Hi! 

I have put my work in a blue box and some comments there as well. 
Notes: 
1. TOP NAV: Current live version of the top nav has a dropdown, but I couldn't find the design of that dropdown.
2. FOOTER: I couldn't find the designs for the new footer for mobile. 
3. TOOLKIT: The designs match? 
4. DONATE: The designs match? 
5. GUIDES: I couldn't compare pages for the same guides, but from I can tell the Hero banner has changed. 

Let me know what you think and if I looked in right places!
Thx, 
Anya

**Comment by AnyaStewart** [comment]
All done. See my previous comment.

**Comment by ExperimentsInHonesty** [comment]
@kristine-eudey There seems to be confusion on how to know if this issue is done, meaning did we as a team do all that was required?  If you could provide what the criteria @IsaacDesigns can use to make that decision, it would be greatly appreciated.

**Comment by IsaacDesigns** [comment]
@AnyaStewart No need to finish this issue. It will be resolved when I finish issue https://github.com/hackforla/website/issues/2512.

**Comment by IsaacDesigns** [comment]
@kristine-eudey I'm looking for the Guides live site page. The linked Guides pages in this issue goes to Toolkit. Please update the Guides page link when you get the chance.
