### ISSUE TITLE
Update "Current Pages" in Figma (Homepage, About Us, Wins, Organizational Dashboard)

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2449]
### Overview
We need to update the "Current Pages" file in Figma so that it accurately reflects both the current live versions of the **Homepage, About Us, Wins, and Organizational Dashboard** pages on the site, as well as the most updated Figma designs (which may or may not currently be live, but are approved for development).

### Action Items

- [x] Go to the "Current Pages" section in Figma
- [x] Locate the section in the gray box which provides guidance on how to structure the work you'll be doing on the page
- [x] Start a new section below what's currently on the page (following our Figma page layout guidance).
- [x] Find the Figma pages for each: **Homepage, About Us, Wins, and Organizational Dashboard**
- [x] For each one, navigate to that particular page on the current live website (if there is a live version, use sitemap page to check page status) 
- [x] Going back to the Figma page for the page you're working on, find the design that is currently live on the site. Copy and paste that design (both desktop and mobile) into the Current Pages file, following the structure shown in the example section of gray boxes. 
- [x] Go back to the Figma page for the page you're working on and find the design located in the red box, which represents the most up-to-date design for the page that has been approved for development. Copy and paste this version to the Current Pages file below the "Current live version" you just added. 
- [x] Do this for all 4 pages listed in this issue. 
- [x] Reach out the the design lead if you have any questions!

### Resources/Instructions
[Figma - Current Pages](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A0)
[HfLA - Homepage](https://www.hackforla.org/#)
[HfLA - About Us](https://www.hackforla.org/about/)
[HfLA - Wins](https://www.hackforla.org/wins/)
[HfLA - Organizational Dashboard](https://www.hackforla.org/dashboard/)

**Comment by IsaacDesigns** [comment]
- Progress:
(Just self-assigned)

- Blockers: 

- Availability:

- ETA:

**Comment by kristine-eudey** [comment]
Hi @IsaacDesigns - can you give an update on this issue to let the team know your progress/blockers/eta on this? And also 
please add a label to your section (your name / issue # / status / date). Thank you!

**Comment by IsaacDesigns** [comment]
Progress: 80% done

Blockers: Need to find Figma files. Had trouble understanding the instructions.

Availability: I have 4 hours to work on this issue

ETA: By Wednesday 24th

**Comment by IsaacDesigns** [comment]
Added the Figma sitemap and status of each page within the sitemap.
