### ISSUE TITLE
Hackforla-site Project card issue

### ISSUE THREAD

**Issue by Sihemgourou** [hackforla/website#2450]
### **Overview**

We need to update the information about the project [INSERT PROJECT NAME] so that it is up-to-date on the Hack for LA website

### **Action Items**

Please check the standardized format for each element on the template 

**PMs**

Please put in a comment the element that needs changes + changes to implement 

- [ ]  title [of project]
- [ ]  description [of project]
- [ ]  image
<NOBR> <details><summary>Template image </summary> 
<NOBR> image: /assets/images/projects/[project repo name + .jpg or .png]
alt: 'description of the card image'
_Card image should be 600px wide x 400px high_
</NOBR> </details>  </NOBR>

- [ ]  Current Project Team - leadership on top
<NOBR><details><summary>Template Current Project Team</summary>
name: First Last
role: Product Manager
links:
slack: 'https://hackforla.slack.com/team/xxxxxx'
github: 'https://github.com/githubusername'</details>   
</NOBR><NOBR><details> <summary>Infos**</summary>
<NOBR>- Any project member who has been actively contributing on your team for at least 1 month, and who is not already listed under "Current Project Team". 
<NOBR>- Slack:*To create a Slack link for each person, search for their slack profile, click on their name; this should give you a popup window with the user's picture, name, and a link to "View full profile". Click on "View full profile". That pane gives you the options message, call, and more. Click on "more" and you should be shown "Copy member ID" followed by the actual id. This is the id you need to use in the slack url, e.g. [https://app.slack.com/team/](https://app.slack.com/team/)<member_id_here_
</details>
</details>

- [ ]  links
    - [ ]  Github
    - [ ]  Slack
    - [ ]  Test Site
    - [ ]  Demo Site
    - [ ]  Site
    - [ ]  Overview [find your project's one-sheet [here](https://github.com/hackforla/product-management/tree/master/project-one-sheets) ]
    - [ ]  Wiki
    - [ ]  Readme
<NOBR><details><summary>Template links </summary>
<NOBR>- name: Github
<NOBR>- url: 'https://www.example.com'
    </details>   

    </details>   
- [ ]  technologies: These are not the languages that show up on your repo homepage, rather things that don't such as React, Node.js 
- [ ] tools: Things like google docs, zoom, figma, usability hub, etc.
- [ ]  partner
- [ ]  status
<details><summary>info-status</summary>If the card should not be included on the site, change visible to "false"</details>

**Comment by ExperimentsInHonesty** [comment]
I am closing this issue.  The details have been recorded in the wiki https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Not-Implemented
