### ISSUE TITLE
Update donate section on multiple pages to be the same component

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2451]
### Overview
We need to componentize the donate section on multiple pages to ensure consistent changes and formatting.

### Action Items
- [x] Notice the donate section on the following two links: [HfLA - Donate](https://www.hackforla.org/donate/) and [HfLA - Join](https://www.hackforla.org/join)
- [x] Extract the html file from the donation part of the [HfLA - Join page](https://www.hackforla.org/join) and store the new html file in the [_includes directory](https://github.com/hackforla/website/tree/gh-pages/_includes)
- [x] This html file should be used for both pages using the keyword {% include %} in liquid
- [x] Ensure that both pages look and function the same after the change in desktop, tablet, and mobile views

### Resources/Instructions
[HfLA - Donate](https://www.hackforla.org/donate/)
[HfLA - Join](https://www.hackforla.org/join)
[Join Us html file](https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html)
[Donate html file](https://github.com/hackforla/website/blob/gh-pages/pages/donate.html)
[_includes directory](https://github.com/hackforla/website/tree/gh-pages/_includes)
[Jekyll - using "includes"](https://jekyllrb.com/docs/includes/)
[Intro to Liquid](https://shopify.github.io/liquid/basics/introduction/)

**Comment by Mattre7** [comment]
i. Availability: All day Monday (8/1), Tuesday evening, all day Wednesday and Thursday  

ii. ETA: I believe I finished the issue earlier today, just finished opening a pull request detailing my experience with the issue, now waiting to be reviewed
