### ISSUE TITLE
Update the image location for partners

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2457]
### Overview
We need to refactor the location for the partners images so they become reusable for other components.

### Action Items
- [x] Move the file directory `assets/images/about/partners` one level up so it becomes `assets/images/partners`
- [x] As a result of the above change, change the paths of the partner images in the following file:
    - [x] [partners.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/partners.yml)
- [x] Ensure that the [partners section](https://www.hackforla.org/about/#partners) of the about page looks the same after the changes

### Resources/Instructions
[partners.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/partners.yml)
[Partners section of the About Page](https://www.hackforla.org/about/#partners)
[Partner images directory](https://github.com/hackforla/website/tree/gh-pages/assets/images/about/partners)

**Comment by JessicaLucindaCheng** [comment]
Availability: Th, Dec 16 and Tu, Dec 21 7am-10am
ETA: Tu, Dec 21

**Comment by JessicaLucindaCheng** [comment]
- Progress: Completed
- Blockers: Waiting for review approval and merging
- Availability: Not applicable because completed issue and waiting for feedback. Will update availability if changes need to be made once I receive feedback.
- ETA: Completed already
