### ISSUE TITLE
Update the image location for sponsors

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2458]
### Overview
We need to refactor the location for the sponsors images so they become reusable for other components.

### Action Items
- [x] Delete the existing `assets/images/sponsors` directory along with its contents
- [x] Move the file directory `assets/images/about/sponsors` one level up so it becomes `assets/images/sponsors`
- [x] As a result of the above change, change the paths of the sponsor images in the following file:
    - [x] [sponsors.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/sponsors.yml)
    - [x] [about-card-sponsors.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-sponsors.html)
- [x] Ensure that the [sponsors section](https://www.hackforla.org/about/#sponsors) of the about page looks the same after the changes
- [x] Ensure that the images for the sponsors at the bottom of the [citizen engagement page](https://www.hackforla.org/citizen-engagement) look the same after the changes
- [x] Ensure that the sponsors (bottom of the page) in the [current homepage](https://www.hackforla.org/#) look the same after the changes

### Resources/Instructions
[sponsors.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/sponsors.yml)
[Sponsors section of the About Page](https://www.hackforla.org/about/#sponsors)
[Citizen engagement page](https://www.hackforla.org/citizen-engagement)
[Sponsors images directory](https://github.com/hackforla/website/tree/gh-pages/assets/images/about/sponsors)
[Current homepage](https://www.hackforla.org/#)

**Comment by JasonY188** [comment]
Availability: 4hrs
ETA: 03-05

**Comment by SAUMILDHANKAR** [comment]
@JasonY188 Please share your weekly progress update on this issue. You can use the template provided in the pre work checklist. You can remove the To Update label on this issue after that. Thank you.

**Comment by JasonY188** [comment]
1. Progress - finished 7 of 8 tasks
2. Blockers - still looking at code for one image in sponsors section of About page
3. Availability - 3 hrs
4. ETA - 03-15

**Comment by SAUMILDHANKAR** [comment]
@JasonY188 Thank for sharing your weekly progress report. Feel free to check off the action item in #2750 and close that issue if rest of the items are done. Thanks.
