### ISSUE TITLE
Update Project Profile: Public Tree Map

### ISSUE THREAD

**Issue by KianBadie** [hackforla/website#246]
### Overview
Update the following fields for your project. These updated fields will then be updated to be shown on the website.

### Action Items
Provide in the comments below:
- [x] updated wording if necessary on the project card (see [hackforla.org](https://www.hackforla.org/))
- [x] information on which Tools your team is using for the project (Ex: figma, Balsamiq, photoshop, etc.) . This is different than programming languages
- [x] updates for "Looking For" Section
- [x] any updated links that are not currently displayed on the site (do you have a demo site?)
- [x] Hero image to be displayed on Project Home Page at 1500 x 700 px
- [x] any resources for a Getting Started link (either a link to a wiki or readme)

### Resources/Instructions
See the hero image on the [hackforla.org](https://www.hackforla.org/) homepage

**Comment by KianBadie** [comment]
As I was typing this, I realized something. While we have an example of a good project banner, should all the project banners across the site be the same size? That way, if a user clicks from project to project there will be consistency. If so, what should the size of the project banner be? A quick and shallow google search threw up some numbers like 16:9 for ratios for banner images.

**Comment by ExperimentsInHonesty** [comment]
Hi @emillipede we have updated this issue's specifications, it's now ready for your team.

**Comment by emillipede** [comment]
hi @ExperimentsInHonesty, a couple of weeks ago I provided what we had in #253

**Comment by ExperimentsInHonesty** [comment]
https://github.com/hackforla/website/issues/253#issuecomment-573986790
Public Tree Map documents all 35,000 public trees (and vacant tree sites) in Santa Monica's urban forest. The map includes contextual information compiled from open datasets, digitized city records, and federal ecosystem services values. To reflect tree plantings and removals, the map updates every day.

Links: Github, Test Site, Slack
Partner: City of Santa Monica Public Landscape
Tools: JS, leaflet, python
Looking for: Front-end web development, data processing, project management, appreciation for trees.
Location: Santa Monica

**Comment by ExperimentsInHonesty** [comment]
![Screen Shot 2020-02-16 at 11 54 26 AM](https://user-images.githubusercontent.com/37763229/74611709-28142b80-50b3-11ea-8271-6746679100e1.png)

**Comment by ashlingam** [comment]
@emillipede Could you please provide a list of software tools used (e.g. Photoshop, Figma, pen & paper, etc.)? What non-programming languages do you use on your project? Thanks!

**Comment by emillipede** [comment]
@harishlingam Thank you for following up, I'm sorry I didn't address that question. In addition to github and slack, we currently just use zeplin. We're not using google docs or sheets right now. 

What do you mean by non-programming languages? The repositories include css, json, and html files. 

Please do not use the screenshot above. I'll work on providing an updated project image. Since that screenshot isn't useful, I prefer to stick with the image currently visible on the site. If you need to change the image right away, please let me know.

Can you share an example of a project banner? We don't have one.

Thanks again!

**Comment by ExperimentsInHonesty** [comment]
@emillipede we are not changing the image on the hackforla homepage for the public tree map project.  What we are asking for is a hero image similar to the women on the top of the hack-for-la website.  A wordless image that conveys the your project's theme or at least doesn't conflict with your website's visuals.  This image will be used for a project home page for your specific project. We are creating one for each project.

**Comment by ExperimentsInHonesty** [comment]
I am closing this issue.  The temporary hero is good enough for now, and the public-tree map team can provide a new one later at their discretion.

**Comment by ExperimentsInHonesty** [comment]
opps.  I spoke too soon.  Here are Emily's changes
https://github.com/hackforla/website/issues/351https://github.com/hackforla/website/issues/351#issuecomment-596872438

Please update the project description: "Public Tree Map helps connect people to Santa Monica's urban forest. The map includes information about each of the 35,000 trees (and vacant tree sites) in Santa Monica's publicly-owned urban forest (compiled from open datasets, digitized city records, and federal ecosystem services values), as well as tools for users to share favorite trees. To reflect tree plantings and removals, the map updates every day."

Please update looking for: Front-end web development (JavaScript, Leaflet), data processing (geopandas, python), QA and UX testing, appreciation for trees (anyone interested is welcome!)

**Comment by emillipede** [comment]
image credit: Dave Baiocchi, www.studiobaiocchi.com
![Yate 6 - Dave Baiocchi](https://user-images.githubusercontent.com/22624609/76593907-d0e85780-64b4-11ea-91cf-35ec844478d8.jpg)

**Comment by ExperimentsInHonesty** [comment]
@emillipede the image needs to be 1500 x 700.  Please crop the image and repost

**Comment by emillipede** [comment]
@ExperimentsInHonesty thank you for the clarification about dimensions. please see below for an appropriate image at that size. the image credit is the same: Dave Baiocchi, www.studiobaiocchi.com. thanks again.

![Coral tree - Dave Baiocchi resized](https://user-images.githubusercontent.com/22624609/76781451-f8b51500-676b-11ea-9f93-40a6d5b3d614.jpeg)

**Comment by emillipede** [comment]
@harishlingam following up - on our project page, Mark asked to be listed as a backend dev. can you please make that update? thank you.

**Comment by ashlingam** [comment]
@emillipede I believe the change is now reflected on the current project card

**Comment by emillipede** [comment]
Hi @harishlingam I don't see a change, he's still listed as lead

**Comment by emillipede** [comment]
summary for @yulia-kh. thank you for making these updates!

- Please remove the current screenshot image. Please use the below image (also uploaded in a comment above). If for any reason you can't use the image, please let me know and for now just remove the screenshot (our team didn't supply it, I asked that it not appear on the website). The image credit for the photograph is: "Dave Baiocchi, www.studiobaiocchi.com" : 
![coral tree](https://user-images.githubusercontent.com/22624609/78579010-2c241600-77e5-11ea-8e2e-96519279bf4f.jpeg)
- Please update the project description: "Public Tree Map helps connect people to Santa Monica's urban forest. The map includes information about each of the 35,000 trees (and vacant tree sites) in Santa Monica's publicly-owned urban forest (compiled from open datasets, digitized city records, and federal ecosystem services values), as well as tools for users to share favorite trees. To reflect tree plantings and removals, the map updates every day."
- Please update looking for: Front-end web development (JavaScript, Leaflet), data processing (geopandas, python), QA and UX testing, appreciation for trees (anyone interested is welcome!)
- Please change Mark Jackson's role to backend dev (from the start, he asked to be classified as a dev)
