### ISSUE TITLE
Update project card: Guides Team

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2462]
### Overview
We need the current team of volunteers to show up on the Guides team project card on the website so that new volunteers will know who to reach out to.

### Action Items
Add the following 
- name: Bonnie Wolfe
   role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/UE1UG1YFP'
      github: 'https://github.com/experimentsinhonesty'
- name: Carol Zhu
   role: Product Manager
    links:
     slack: 'https://hackforla.slack.com/team/UVA3VD727'
     github: 'https://github.com/carolzjy'
- name: Bukola Ogunleye
   role: Product Manager
    links:
     slack: 'https://hackforla.slack.com/team/U02617GM7QX'
    github: 'https://github.com/SheIsBukki'
- name: Thuy Le
   role: Product Manager
    links:
     slack: 'https://hackforla.slack.com/team/U02GGGF26D9'
     github:https://github.com/thuyhle193

### Resources/Instructions
https://www.hackforla.org/projects/guides-team
https://github.com/hackforla/website/blob/gh-pages/_projects/guides-team.md
Where in your IDE you will find the file: /_projects/guides-team.md
Use this as an example of how to format the information: https://github.com/hackforla/website/wiki/project.md-file-template

**Comment by macho-catt** [comment]
@Emmettlsc since this has been inactive for a while, I will unassign you. Please feel free to pick up this issue again when you have the time. Thanks
