### ISSUE TITLE
Update Citizen Engagement page's h4 titles to match Figma design 

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2464]
### Overview
We need to adjust ~the SDG card padding and~ the font color of the H4 titles so that they match the Figma design and the design system color usage guidelines. 

Jessica removed the action item of updating the SDG card padding from this issue. (See https://github.com/hackforla/website/issues/2464#issuecomment-1014110882 for more information.)

### Action Items
- [x] **Adjust color of H4 titles so that they match the Figma design and the design system. They are currently #464646, rather than #333333 as the design system stipulates for our dark font.** 
   <img width="1036" alt="Screen Shot 2021-11-08 at 5 45 21 PM" src="https://user-images.githubusercontent.com/16949503/140831683-eb6e9bf5-6594-4719-a5cd-4f8593b0e98f.png">

<details>
  <summary>No longer adjusting bottom padding of SDG card</summary>
  - [ ] **Adjust bottom padding of SDG card so that it matches the Figma design.**
  - Current version on site to be changed:
    <img width="479" alt="Screen Shot 2021-11-08 at 5 51 46 PM" src="https://user-images.githubusercontent.com/16949503/140831026-ba89dc66-7b50-40f9-9f21-38d0b658e783.png">
  - Figma design:
    <img width="539" alt="Screen Shot 2021-11-08 at 5 51 55 PM" src="https://user-images.githubusercontent.com/16949503/140831098-dc314b3c-a7e0-4469-b559-edffb4c89d68.png">
</details>

### Resources/Instructions
[HfLA - Citizen Engagement Page](https://www.hackforla.org/citizen-engagement)
[Figma - Citizen Engagement](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15901%3A100458)
[Citizen Engagement SCSS](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_citizen_engagement.scss)
[citizen-engagement.html](https://github.com/hackforla/website/blob/gh-pages/pages/citizen-engagement.html)

**Comment by lindseyindev** [comment]
ETA: by midnight 1/4/2022
Availability: 5 hrs [between 1/2-1/4]

**Comment by lindseyindev** [comment]
Progress: Have researched sizing and compared to figma, multiple containers are not sized matching figma specs, need to discuss with tech leads as only adjusting bottom padding does not make the container match the figma design.
Blockers: Sizing of containers
Availability: 3 hours
ETA: Will attend office hours on Thursday, should have next steps or resolution by EoD 1/6
Pictures (optional):
<details> Zero bottom padding and smaller left and right padding 
<img src="https://gyazo.com/5b0fd4cfd6529c59cd4435767569947b.png" />
</details>

<details>Versus figma design which show bottom padding/margin of 20px
<img src="https://gyazo.com/767f0c223e1d24a29c8d0946d03eed39.png" />
</details>

**Comment by lindseyindev** [comment]
@IsaacDesigns 

Hi Isaac! Question for design on this: I figured out with my team that to make the website container match the figma design the image size and the font size also need to be updated to match (right now they're all different dimensions)

There was some concern on my team that the minimum font size must be 16px across the website (possibly for accessibility reasons?), can you confirm if that's accurate or if I can proceed with changing the font size to 14px to match?

<details><summary>Figma design I'm referencing </summary>
<img src="https://gyazo.com/767f0c223e1d24a29c8d0946d03eed39.png" alt="figma design" />
</details>

**Comment by lindseyindev** [comment]
@IsaacDesigns Hi Isaac! I am not able to move forward on this issue as it needs to be rewritten 

The figma design has font-size 14px for the text in part 1 when the minimum allowed font size is 16px so adjusting the padding will not make the website match the figma

If you agree that this needs to go back to design please let me know so I can move this to new issue approval for re-work

**Comment by lindseyindev** [comment]
Talked to Isaac, text color still needs to be changed and design is now aware of the difference between figma and allowed font, Isaac confirmed design will work to update the figma soon and we'll bring up the issue in the Sunday meeting. 
Will have a better ETA and next steps after 1/16

**Comment by JessicaLucindaCheng** [comment]
> Talked to Isaac, text color still needs to be changed and design is now aware of the difference between figma and allowed font, Isaac confirmed design will work to update the figma soon and we'll bring up the issue in the Sunday meeting. Will have a better ETA and next steps after 1/16

@lindseyindev I updated the issue above and removed the action item to adjust the SDG padding. Once the Design Team has updated the Figma for Citizen Engagement, they can let us know if they still want us to change the padding for it.

**Comment by JessicaLucindaCheng** [comment]
@IsaacDesigns After discussing with you during [today's meeting](https://github.com/hackforla/website/issues/1734#issuecomment-1013922203), I removed the action item to "Adjust bottom padding of SDG card so that it matches the Figma design." for this issue. After the Design Team updates the Figma design for the Citizen Engagement page to match what is currently on the website, we can write a new issue for developers to adjust the padding if you determine it is still needed.

**Comment by ExperimentsInHonesty** [comment]
@phuonguvan lets discuss this with @JessicaLucindaCheng to get us up to speed on this issue and determine if there are next steps for design.

**Comment by ExperimentsInHonesty** [comment]
@phuonguvan please make a new issue to determine what to do on this:

Website has 
the box at 280 width
And the SDG image at 120x120

Figma 
the box at 318 width  
And the SDG image at 88x88

Design to decide which of those is preferred.  If website is fine, then we leave as is, if website needs to change, then a new issue will be created.  Its quite possible that the text on the SDG icon is too small to be accessible when its 88.  Try finding an all cap matching font to see if you can identify when the SDG icon size matches 16

### Figma
![image](https://user-images.githubusercontent.com/37763229/167311049-17695958-fcdb-47f8-9ace-18911838579e.png)



### Website
![image](https://user-images.githubusercontent.com/37763229/167311105-a5f94cd7-bf8a-48e4-b51e-d0de5e6451c3.png)

**Comment by ExperimentsInHonesty** [comment]
@kathrynsilvaconway I show this issue as having been moved by you from New Issue Approval to Icebox on August 1st.  Can you explain why it should be there or what you intended.

**Comment by ExperimentsInHonesty** [comment]
Not having heard from Kathryn I am moving this back to the new issue approval column

**Comment by plang-psm** [comment]
> @phuonguvan please make a new issue to determine what to do on this:
> 
> Website has the box at 280 width And the SDG image at 120x120
> 
> Figma the box at 318 width And the SDG image at 88x88
> 
> Design to decide which of those is preferred. If website is fine, then we leave as is, if website needs to change, then a new issue will be created. Its quite possible that the text on the SDG icon is too small to be accessible when its 88. Try finding an all cap matching font to see if you can identify when the SDG icon size matches 16
> 
> ### Figma
> ![image](https://user-images.githubusercontent.com/37763229/167311049-17695958-fcdb-47f8-9ace-18911838579e.png)
> 
> ### Website
> ![image](https://user-images.githubusercontent.com/37763229/167311105-a5f94cd7-bf8a-48e4-b51e-d0de5e6451c3.png)

Hello, checking in to see if the @hackforla/website-design has decided to keep the site as is or if we are implementing the Figma changes. Please confirm the changes needed to generate an accurate new issue. Thank you!

**Comment by JessicaLucindaCheng** [comment]
- Design issue #3117 addresses this:

> > @phuonguvan please make a new issue to determine what to do on this:
> > Website has the box at 280 width And the SDG image at 120x120
> > Figma the box at 318 width And the SDG image at 88x88
> > Design to decide which of those is preferred. If website is fine, then we leave as is, if website needs to change, then a new issue will be created. Its quite possible that the text on the SDG icon is too small to be accessible when its 88. Try finding an all cap matching font to see if you can identify when the SDG icon size matches 16
> > ### Figma
> > ![image](https://user-images.githubusercontent.com/37763229/167311049-17695958-fcdb-47f8-9ace-18911838579e.png)
> > ### Website
> > ![image](https://user-images.githubusercontent.com/37763229/167311105-a5f94cd7-bf8a-48e4-b51e-d0de5e6451c3.png)
> 
> Hello, checking in to see if the @hackforla/website-design has decided to keep the site as is or if we are implementing the Figma changes. Please confirm the changes needed to generate an accurate new issue. Thank you!
