### ISSUE TITLE
Ensure consistent spelling of "Site Map" across the site

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2465]
### Overview
We need to ensure "Site Map" is written consistently across the site as two words, vs one word so that we optimize our site for SEO and maintain professionalism across the site by sticking to consistent wording/spelling of terms.

### Action Items

- [x] Change spelling in footer to "Site Map". 
   - [x] Note: new footer design has correct spelling, but if it will be some time until that is developed and goes live, then the current footer should be updated to reflect the correct spelling. 
- [x] Change spelling of subheading on Site Map page so that both instances of this written on the page are consistent (as 2 words vs. 1)
  
<img width="949" alt="Screen Shot 2021-11-08 at 6 28 35 PM" src="https://user-images.githubusercontent.com/16949503/140834871-d2363d85-73b9-45fe-9afd-a0716794581f.png">

  

### Resources/Instructions
[Figma - Footer](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=14814%3A95261)
[HfLA - Site Map page](https://www.hackforla.org/sitemap/)
[sitemap.html](https://github.com/hackforla/website/blob/gh-pages/pages/sitemap.html)
[footer.html](https://github.com/hackforla/website/blob/gh-pages/_includes/footer.html)

**Comment by lindseyindev** [comment]
Availability: 3 hours
ETA: by midnight 12/18
