### ISSUE TITLE
Update Project Profile: Lucky Parking

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#247]
### Overview
Update the following fields for your project. These updated fields will then be updated to be shown on the website.

### Action Items
Provide in the comments below:
- [ ] updated wording if necessary on the project card (see [hackforla.org](https://www.hackforla.org/))
- [ ] information on which Tools your team is using for the project (Ex: figma, Balsamiq, photoshop, etc.) . This is different than programming languages
- [ ] updates for "Looking For" Section
- [ ] any updated links that are not currently displayed on the site (do you have a demo site?)
- [ ] Hero image to be displayed on Project Home Page at 1500 x 700 px
- [ ] any resources for a Getting Started link (either a link to a wiki or readme)

### Resources/Instructions
See the hero image on the [hackforla.org](https://www.hackforla.org/) homepage

**Comment by breeze-094** [comment]
- Description: A platform looking for nearby street parking with least possibility of getting citation 
- Tools: Google Colab and its dependency 
- Looking for:  Python, Machine Learning, Deep learning, Data Science.
- Link is update to date
- Banner to be updated later
- readme: https://drive.google.com/open?id=1gnEUpcPIu8AX5bw1kPIZdubwcDDtsI-y; https://drive.google.com/open?id=1-7G2inkbz4o14AHIX1VQjmz-QUESYlhg

**Comment by ExperimentsInHonesty** [comment]
This issue has been replaced with https://github.com/hackforla/lucky-parking/issues/40 since they had no card to update.

**Comment by ashlingam** [comment]
Rong provided a revised list of open roles. Please update Looking For: Frontend Software Engineer, Backend Software Engineer, Advanced Data Scientist, Python Enthusiast

References hackforla/lucky-parking#40
