### ISSUE TITLE
Update the Citizen Engagement page so the project data is dynamic

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2474]
### Overview
We need to update the Citizen Engagement Page so that the data is dynamically rendered using liquid.

### Action Items
- [x] For each of the projects that are currently in the [Citizen Engagement page](https://www.hackforla.org/citizen-engagement), edit the corresponding md file under the [_projects collection directory](https://github.com/hackforla/website/tree/gh-pages/_projects) so that the data lives there
    - [x] Add a new property "problem" and copy the Problem description from the specific project in the Citizen Engagement page to the markdown file
    - [x] Add a new property "solution" and copy the Solution description from the specific project in the Citizen Engagement page to the markdown file
    - [x] Add a new property "Impact" and copy the Impact description from the specific project in the Citizen Engagement page to the markdown file
    - [x] Add a new property "sdg" and copy the Sustainable Development Goal description from the specific project in the Citizen Engagement page to the markdown file
    - [x] Add a new property "sdg-image" and copy the destination of the asset used to the markdown file
- [x] Update the [citizen-engagement.html](https://github.com/hackforla/website/blob/gh-pages/pages/citizen-engagement.html) file so that instead of statically rendering the data, it uses liquid to loop through the [_projects collections](https://github.com/hackforla/website/tree/gh-pages/_projects). If the project has the value "Citizen Engagement" for the program-area property, it should render it
    - [x] Use the new properties declared above to render the data for each project
- [x] Ensure that the page still looks and functions the same after the change

### Resources/Instructions
[Citizen Engagement Page](https://www.hackforla.org/citizen-engagement)
[_projects collection directory](https://github.com/hackforla/website/tree/gh-pages/_projects)
[citizen-engagement.html](https://github.com/hackforla/website/blob/gh-pages/pages/citizen-engagement.html)
[Using liquid with jekyll](https://jekyllrb.com/docs/liquid/)

**Comment by anthonysim** [comment]
Availability for this week:
Wed - 12/15/21: 5 to 7 PM
Thurs - 12/16/21: 5 to 7 PM
Sat - 12/18/21: 12 to 2 PM

My estimated ETA for completing this issue:
Sat - 12/18/21

Edit: Currently updating the citizen-engagement.html page to make it more "DRY." New estimate for completing this issue:
Sun - 12/26/21

**Comment by anthonysim** [comment]
@ExperimentsInHonesty @R-Tomas-Gonzalez, so created a card in `_includes` that iterates through the md files in `_projects` and generates a card for each item that has a program-area of Citizen Engagement and visible of true. 

My question is this, the src links and alt links need to be dynamic as well for the img tags. Should these be added as properties in the md files that has to do with Citizen Engagement? Please see the img tags below, there are 2 where I placed the notes .

```
{% assign visible_projects = site.projects | where: "program-area", "Citizen Engagement" | where: "visible", "true" %}
             {% for item in visible_projects %}
                   <div class="page-card card-primary page-card-lg card-body card-width program-area" data-dropdown>

                            <!-- QUESTIONS HOW TO MAKE THIS REUSEABLE -->
                            <!-- src, alt -->
                        <img class="card-image" src="/assets/images/projects/311.jpg" alt="311 project card"/>
                           <div class="mobile-card-info-container">
                               <div class="mobile-card-nav">
                                   <h3>{{ item.title }}</h3>
                                   <input class="dropdown-arrow" data-dropdown-arrow type="image" src="/assets/images/citizen-engagement/arrow-button-icon.svg" alt="dropdown-arrow">
                               </div>
                               <div class="project-dropdown">
                                           <div class="problem-info">
                                               <h4>Problem</h4>
                                               <p>{{ item.problem }}</p>
                                           </div>
                                           <div class="solution-info">
                                               <h4>Solution</h4>
                                               <p>{{ item.solution }}</p>
                                           </div>
                                           <div class="impact-info">
                                               <h4>Impact</h4>
                                               <p>{{ item.impact }}</p>
                                           </div>
                               </div>
                           </div>
                       <div class="sustainable-dev-goal">
                           <h4>Sustainable Development Goal</h4>
                           <div class="card-bottom-info">
                            <!-- QUESTIONS HOW TO MAKE THIS REUSEABLE-->
                            <!-- src, alt -->
                               <img class="card-bottom-icon" src="/assets/images/about/sdg-elements/peace-justice.svg" alt="peace justice bottom sustainable dev goal"/>
                                       <p>{{ item.sdg }}</p>
                           </div>
                       </div>
                   </div>
            {% endfor %}
```
