### ISSUE TITLE
GitHub Actions: Change Linter version to @v4 when source code bug is fixed

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2479]
### Dependency
~Source code fix on https://github.com/github/super-linter/issues/2128~

### Overview
We have to update the version for our linter when the source code bug is fixed to ensure that everything is up to date.

### Details
There is a bug with super linter v4.8.3 (the latest version) where the image for the release is missing. Because of this, all GitHub actions related to linting will fail. There is an open issue in the repository of the source code:
https://github.com/github/super-linter/issues/2128

I temporarily updated the version number to v4.8.1 where everything is still working

### Action Items
- [x] Once the bug is fixed in the linked issue above, revert the version number back in line 22 to:
```
        uses: github/super-linter@v4
```
- [x] Confirm the linter works after the change

### Resources/Instructions
Issue opened on the source code of the repo: https://github.com/github/super-linter/issues/2128
[lint-scss.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/lint-scss.yml)

**Comment by neevliberman** [comment]
i. Availability: 3 hours
ii. ETA: 7-30-2022

**Comment by neevliberman** [comment]
Question: It looks like the linked issue is closed, so I'm attempting to see if reverting the version number will break anything, but I'm unsure how to test a linter. Any insight?

**Comment by esantiano** [comment]
Availability for this week: 2 PM- 4PM
My estimated ETA for completing this issue: 10/25/22
