### ISSUE TITLE
Refactor JavaScript: Move script from citizen-engagement.html to external file

### ISSUE THREAD

**Issue by R-Tomas-Gonzalez** [hackforla/website#2480]
### Overview
JavaScript is much more maintainable and reusable if it exists in an external folder, rather than including it into the html doc. Please make a new file and place all required JS there. 

### Action Items

- [x] Create a new file [here](https://github.com/hackforla/website/tree/gh-pages/assets/js) and name it citizen-engagement.js

- [x] Remove the JavaScript from this [page](https://github.com/hackforla/website/blob/gh-pages/pages/citizen-engagement.html) and replace it in the citizen-engagement.js file

- [x] Add the JS file to the html page in a script tag

- [x] Adjust changes between the files mentioned in this issue such that the website appears the same visually

- [ ] Release dependency on https://github.com/hackforla/website/issues/2887

### Resources/Instructions
[Here](https://github.com/hackforla/website/issues/2058) is the issue that helped me make this issue. The reference files for that issue is [here(html doc)](https://github.com/hackforla/website/blob/gh-pages/pages/project-meetings.html) and [here(js file)](https://github.com/hackforla/website/blob/gh-pages/assets/js/project-meetings.js).

[How do I include liquid/global variables defined using Jekyll in a Javascript file?](https://stackoverflow.com/questions/58517425/how-do-i-include-liquid-global-variables-defined-using-jekyll-in-a-javascript-fi)

The html doc for this issue is [here](https://github.com/hackforla/website/blob/gh-pages/pages/citizen-engagement.html).

If you have any questions, feel free to ping me on the HackforLA slack - Tomas Gonzalez. 

**Architecture Notes**
The idea behind the refactor is to get all of our website's JS code into an organized, consolidated state. Currently, we want our JS files to exist in our assets/js directory with these specifications:

In the main js directory, the js files should ideally have names corresponding to a related .html page (for example, updates.js should connect to updates.html).
In the elements sub-directory, the js fjiles should correspond to code needed for our design system elements to function.
In the utility sub-directory, the js files represent reusable code that can be used in multiple files. If any js code is reused, they belong in utility, and called in a separate file in the main directory.
That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by JasonY188** [comment]
Availability 3hrs
ETA 02-22-22

**Comment by tamara-snyder** [comment]
I added a task to release the dependency on issue https://github.com/hackforla/website/issues/2887 once this issue is closed.
