### ISSUE TITLE
Upload .svg files for various HfLA technologies into the assets/images directory

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2483]
### Overview
We need to upload the .svg files for various HfLA technologies used in different projects so we can use them in the future.

### Action Items
- [x] Download the .svg files from the [Google Drive](https://drive.google.com/drive/u/1/folders/1Vq4_CAM0vbJWQLsszne2PeQu5y3r3MeO)
- [x] Create a new directory under [assets/images](https://github.com/hackforla/website/tree/gh-pages/assets/images) called technologies-icons
- [x] Upload the .svg files into the newly created directory

### Resources/Instructions
- Source for this issue: #2130
- [assets/images directory](https://github.com/hackforla/website/tree/gh-pages/assets/images)
- Files location in the [Google Drive](https://drive.google.com/drive/u/1/folders/1Vq4_CAM0vbJWQLsszne2PeQu5y3r3MeO)

**Comment by lindseyindev** [comment]
Availability: 3 hours
ETA: midnight 12/23

**Comment by SAUMILDHANKAR** [comment]
@lindseyindev: Thanks for adding your availability and eta. Just wanted to share a point from our Sunday team meeting. We are now requesting all developers to add eta and availability at the time of picking up an issue or when you are assigned to an issue. You are already doing this, so nothing needs to be done at your end. Just wanted to let you know. Thanks for your awesome work.
