### ISSUE TITLE
Add GitHub link to community of practice: Ops

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2484]
### Prerequisite
Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We need to update the community of practice GitHub links so we can provide the end-user with more information about our communities.

### Action Items
- [x] Update line 27 of the file `_data/internal/communities/ops.yml`
from:
```
    url: 
```
to:
```
    url: https://github.com/hackforla/ops
```
- [x] Ensure that the Communities of Practice page on your local environment reflects your changes
    - [x] The local environment url will be localhost:4000/communities-of-practice
    - [x] A "View GitHub" button should appear on the Ops page card after the change
    - [x] Clicking the button should resolve to the Ops GitHub repository

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_data/internal/communities/ops.yml`
- [Communities of Practice page](https://www.hackforla.org/communities-of-practice)
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/33919f82796dd815087b7826e95dcfff1fda0952/_data/internal/communities/ops.yml#L26-L27

**Comment by JessicaLucindaCheng** [comment]
Availability for this week: Any time, except Sunday 10am-12pm
My estimated ETA for completing this issue: Sunday, December 5, 2021
