### ISSUE TITLE
Update the Program Areas page so the projects are dynamically rendered

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2485]
### Overview
The Program Areas page mini cards need to be rendered dynamically so they match the results from the project filters.

### Details
Currently, the [program-areas.html](program-areas.html) file use liquid to loop through each program area yml file under [_data/internal/program-areas/](https://github.com/hackforla/website/tree/gh-pages/_data/internal/program-areas). Projects for each program area are declared in the yml file. However, if we add a new project under the [_projects collection](https://github.com/hackforla/website/tree/gh-pages/_projects) and declare their program area, we also need to update the proper program area yml file. Additionally, if we ever need to change a project's program area, we need to ensure that the program area yml files are updated as well.

Since this becomes unmaintainable in the long run, it would be smarter if the program-areas.html file renders the mini page cards for each project by referencing the _projects collection instead of the program area yml files.

### Action Items
- [x] Notice how the [program-areas.html](program-areas.html) file currently loop through the yml files to render the mini page cards for each project
- [x] Change the for loop under line 42 so that the liquid references the _projects collection instead of the program area yml files
    - [x] If the current program-area property is equal to the program-area property of the project, render it
- [x] Ensure that after the changes, the webpage still looks and functions the same

### Resources/Instructions
[program-areas.html](program-areas.html)
[_data/internal/program-areas/](https://github.com/hackforla/website/tree/gh-pages/_data/internal/program-areas)
[_projects collection](https://github.com/hackforla/website/tree/gh-pages/_projects)
[Liquid in Jekyll](https://jekyllrb.com/docs/liquid/)
[Iteration in Liquid](https://shopify.github.io/liquid/tags/iteration/)

**Comment by ghost** [comment]
Progress: Currently I have created a branch and am now going to look into how to solve the issue
Blockers: currently there are no blockers 
Availability:  This week I have 4 hours to work on this issue
ETA: either tomorrow or next Tuesday
Pictures:  No visuals so far

**Comment by macho-catt** [comment]
Hi @amnak1284, just wanted to see what your progress on this issue is?

**Comment by macho-catt** [comment]
@amnak1284 since this has been inactive for a while, I will unassign you. Please feel free to pick up this issue again when you have the time. Thanks

**Comment by jdingeman** [comment]
ETA: Friday EOD
Availability: After 3pm each day

**Comment by jdingeman** [comment]
Blocker: It does not look like the files in the [_projects collection](https://github.com/hackforla/website/tree/gh-pages/_projects) have links to their respective hackforla.org/ pages like the currently used .yml files. To properly link the projects the same way they are currently, I think would need to add a link to each .md file to include their hackforla page link.

e.g.
**Currently Used:**
The link for the 311 Data card will redirect to https://www.hackforla.org/projects/311-data

**The Problem:**
The 311-data.md file in [_projects](https://github.com/hackforla/website/tree/gh-pages/_projects) does not currently contain a link to https://www.hackforla.org/projects/311-data

Also, I am having trouble getting the conditional correct to compare the program-area in the .md file to that of the program areas .yml file.

**Comment by jdingeman** [comment]
Blocker: I am unsure how to access the [_projects collection](https://github.com/hackforla/website/tree/gh-pages/_projects) using Liquid. It does not seem to react the same way as the [/data/internal/program-areas](https://github.com/hackforla/website/tree/gh-pages/_data/internal/program-areas) collection. 

When I tried to debug, I found that the page will display all of the data in the program-areas collection (.yml files) when using:
`{{ site.data.internal.program-areas }}`
and even will display all data in the external folders (.json files) using:
`{{ site.data.external }}`
but it will not do the same for the _projects collection (.md files) using:
`{{ site.projects }}`. 
So I'm not sure if it is unable to render .md files the same way as .yml or .json files.

**Comment by jdingeman** [comment]
I tried to experiment with changing the file paths around and here's what I've found:

- Referencing `site` will only work if followed by any path in /_data, it does not work with any other path at the same level as _data
- I tried copying all of the .md files from the _projects collection into their own folder _within_ the /_data folder as its own subfolder (/_data/internal/project-test), and in trying to call `{{ sites.data.internal.project-test}}`, the site will not render any content in the .md file
  - As a reaction, I tried simply changing one of the .md files to a .yml file and the site was able to render the data from that file after it was switched. 

I suspect there may be something with the Jekyll configuration that we would need to change to:
1.  Access dependencies _outside_ of /_data
2.  Read and render content from the .md files

**Comment by jdingeman** [comment]
Blocker: While my previous blocker proved to not really be much of an issue, I have discovered that the statement (assuming we use `{% for project in site.projects %}`)
`{% if program_areas[1].program-area == project.program-area %}` does not not seem to yield expected results.
While we can display each of the `program-area` of each file independent of each other, but despite being the exact same string, the if statement doesn't seem to show any of the mini cards, and when we use !=, it will show _all_ of the mini cards in each large card.

**Comment by aricforrest** [comment]
@jdingeman the jekyll _projects files are including program-areas as a list/array. You'll need to loop through each of these before the comparison. Take a look at the snippet below.

```
            <ul class="project-card-mini-list-alignment">
                {% for project in site.projects %}
                  {% for program-area in project.program-area %}
                    {% if program_areas[1].program-area == program-area %}
                      <li class="project-card-mini inline-list" id="{{project.identification}}">
                        <h6>{{project.title}}</h6>
                          <img class="project-card-mini-image" src="{{project.image}}" alt="{{project.image_alt}}" />
                          <a class="project-card-mini-title" href="{{project.links[0].url}}">{{project.title}}</a>
                      </li>
                    {% endif %}
                  {% endfor %}
                {% endfor %}
                
                <!--Spacer li are used to center the project card mini on mobile-->
                <li class="project-card-mini-spacer"></li> 
                <li class="project-card-mini-spacer"></li>
                <li class="project-card-mini-spacer"></li>
            </ul>
```

**Comment by jdingeman** [comment]
> 

This worked! I am curious as to why it hadn't worked when we changed the program-area in 311-data.md from
```
program-area:
- Citizen Engagement
```
to
```
program-area: Citizen Engagement
```

Nonetheless, thank you so much!!

**Comment by aricforrest** [comment]
As I said on the call, the changes in `311-data.md` didn't work because jekyll was not rebuilding the files so it still treated the `project.program-area` as the original array. I discovered if you run `jekyll clean` it will delete the full `_site` directory and jekyl metadata. The jekyll serve command (docker-compose.yml runs this) will then rebuild all files ensuring you have the latest version. 

I created issue https://github.com/hackforla/website/issues/3587 to have docker-compose updated to do this on it's own before building and serving. Until this is merged you can simply run `jekyll clean` before `docker-compose up`.

**Comment by jdingeman** [comment]
> 

Awesome, thanks so much for the explanation and insight!

**Comment by jdingeman** [comment]
@kathrynsilvaconway @blulady @arpitapandya I am almost ready to open a pull request, however I wanted to propose a possible list of "good second issues". 
The current page has hyperlinks for each project leading to their hackforla.org/projects/[project name] page, but the md files do not have those links. I am fine with going through and adding them to the files, but I wanted to run this by you all to see what you think. For example, citizen-engagement-card.yml shows
```
projects:
  - id: 190321758
    name: 311 Data
    image: /assets/images/projects/311_data.png
    image_alt: 311 data logo.
    link: https://www.hackforla.org/projects/311-data
```
whereas 311-data.md shows
```
links:
  - name: GitHub
    url: 'https://github.com/hackforla/311-data'
  - name: Slack
    url: 'https://hackforla.slack.com/archives/CJY4R382X'
  - name: Wiki
    url: 'https://github.com/hackforla/311-data/wiki'
  - name: Join Us
    url: 'https://github.com/hackforla/311-data/wiki/Joining-the-311-Team'
  - name: Site
    url: 'https://www.311-data.org/'
```

**Comment by blulady** [comment]
> @kathrynsilvaconway @blulady @arpitapandya I am almost ready to open a pull request, however I wanted to propose a possible list of "good second issues". The current page has hyperlinks for each project leading to their hackforla.org/projects/[project name] page, but the md files do not have those links. I am fine with going through and adding them to the files, but I wanted to run this by you all to see what you think. For example, citizen-engagement-card.yml shows
> 
> ```
> projects:
>   - id: 190321758
>     name: 311 Data
>     image: /assets/images/projects/311_data.png
>     image_alt: 311 data logo.
>     link: https://www.hackforla.org/projects/311-data
> ```
> 
> whereas 311-data.md shows
> 
> ```
> links:
>   - name: GitHub
>     url: 'https://github.com/hackforla/311-data'
>   - name: Slack
>     url: 'https://hackforla.slack.com/archives/CJY4R382X'
>   - name: Wiki
>     url: 'https://github.com/hackforla/311-data/wiki'
>   - name: Join Us
>     url: 'https://github.com/hackforla/311-data/wiki/Joining-the-311-Team'
>   - name: Site
>     url: 'https://www.311-data.org/'
> ```

This is a great idea, let's chat about it tonight and see what Kathryn thinks.

**Comment by ExperimentsInHonesty** [comment]
Hi Devs, and specifically @jdingeman After we had a conversation at one of our meeting about how to do it, a different approach was taken than is mentioned above.  I want to make sure that an explanation of that method is documented in the wiki.  If it is not, please make an issue for that to be done.

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - this method written has now been written into the wiki. See page [here](https://github.com/hackforla/website/wiki/DR:-Updated-Program-Areas-so-Projects-are-Linked-to-Project-Pages)

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge I think the wiki page that @jdingeman made is perfect. We need to make sure a link to it is added to the future content that will be here https://github.com/hackforla/website/wiki/Pages-on-Hack-for-LA-website, or temporarily add it to https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture#pages

https://github.com/hackforla/website/wiki/DR:-Updated-Program-Areas-so-Projects-are-Linked-to-Project-Pages

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - link has been added under "Program Areas" https://github.com/hackforla/website/wiki/Pages-on-Hack-for-LA-website
