### ISSUE TITLE
Create a new Privacy Policy page for the website

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2486]
### Overview
We need to add a Privacy Policy to our website to detail our views and procedures on the information collected from visitors.

### Action Items
Design
- [x] Refer to the approved privacy policy draft in the [drive](https://docs.google.com/document/d/19x1KsMTU-QBdopiV08HSBQ0i4g1ChrcPZ8ZXmUK50cY/edit#heading=h.1kvk4qkoxhzw)
- [x] Create a new Figma page titled "Privacy Policy"
- [x] Create a design for a new page for the privacy policy
- [x] Create a mobile version of the new Privacy Policy page once the desktop version is confirmed

### Resources/Instructions
- Source issue: #1989
- [Document](https://docs.google.com/document/d/19x1KsMTU-QBdopiV08HSBQ0i4g1ChrcPZ8ZXmUK50cY/edit#heading=h.1kvk4qkoxhzw) in the Google Drive
- [HfLA Figma - Policy Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17845%3A137765)

**Comment by ahoang94** [comment]
A desktop version of the [Privacy Policy page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17845%3A139750) has been created in Figma. 

I am awaiting feedback before I create a mobile version of the page.

**Comment by ExperimentsInHonesty** [comment]
@ahoang94 The page looks good.  Do you want a new issue made for the mobile or will you continue on this issue?  If you will continue on this issue, please move this back to in progress.

**Comment by ahoang94** [comment]
@ExperimentsInHonesty I will revise this issue and add a mobile component to the checklist.

**Comment by ahoang94** [comment]
The mobile version of the Policy Page has been laid out: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17947%3A123030
