### ISSUE TITLE
Remove languages from the technologies field for each project

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2487]
### Overview
We need to remove the languages from the technologies field for each project so we can properly implement languages as its own filter field.

### Action Items
- [x] Go through each .md file under the [_projects collection](https://github.com/hackforla/website/tree/gh-pages/_projects) directory and remove any instances of a language under the 'technologies' property
    - [x] Click [this](https://www.hackforla.org/projects/?technologies=Python,SASS,SCSS,TypeScript) link for all the projects that currently have a language under the 'technologies' property
    - [x] Remove TypeScript, Python, SCSS, and SASS wherever possible
- [x] Ensure that both the [projects page](https://www.hackforla.org/projects/) and each individual project's landing page no longer has any of the mentioned languages under 'Technologies'
- [x] Ensure that the filter under the [projects page](https://www.hackforla.org/projects/) no longer lists any of the mentioned languages as a possible filter option
- [x] Once approved and merged, release dependency on #2488

### Resources/Instructions
[projects page](https://www.hackforla.org/projects/)
[_projects collection](https://github.com/hackforla/website/tree/gh-pages/_projects)
[Projects with languages](https://www.hackforla.org/projects/?technologies=Python,SASS,SCSS,TypeScript)

**Comment by anthonysim** [comment]
Availability for this week:
Thurs (12/9/2021): 5-7 PM 
Sat (12/11/2021): 12-2 PM
Sun (12/12/2021): 12-2 PM

My estimated ETA for completing this issue:
Sunday (12/12/2021)

**Comment by anthonysim** [comment]
Progress: Plan to finish this weekend.
Blockers: None
Availability: 

Availability for this week:
Thurs (12/9/2021): 5-7 PM
Sat (12/11/2021): 12-2 PM
Sun (12/12/2021): 12-2 PM

My estimated ETA for completing this issue:
Sunday (12/12/2021)
ETA: "When do you expect this issue to be completed?"

Pictures: N/A

**Comment by anthonysim** [comment]
Hi @macho-catt, did you want me to remove (delete all the technologies listed) or comment them out? I'm just wondering in case that information might come in handy later down the line.

**Comment by ExperimentsInHonesty** [comment]
@anthonysim fyi, don't move your issue into QA on the board.  The system will do that manually when the pr is merged.  Thanks!
