### ISSUE TITLE
Add languages to the technologies project filter

### ISSUE THREAD

**Issue by macho-catt** [hackforla/website#2488]
### Dependency
#2487

### Overview
The languages for each project under the projects page should be included as a filter with the Technologies

### Action Items
- [x] Become familiar with the JS in the [project.html](https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html) and how it obtains the languages used for a project from [_data/external/github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/github-data.json)
- [x] In the [projects page](https://www.hackforla.org/projects/), update each project page card so the languages are listed
    - [x] You should be able to utilize the same JS as above to get the languages for a project
    - [x] Each project card and the contents inside are generated in the [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js) file
    - [x] You can put the 'Languages' field in between 'Partner' and 'Technologies'
    - [x] Refer to the screenshots below
- [x] In the [projects page](https://www.hackforla.org/projects/), update the filter so projects can be filtered by Technologies and Languages
    - [x] Under the existing 'Technologies' filter, add the languages from the projects
    - [x] Change the name of the filter to 'Languages / Technologies'
    - [x] The filter should be able to filter by languages and/or technologies
    - [x] Refer to the [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js) file
- [x] Make sure the page looks fine for smaller viewport screens as well, such as tablet, mobile (responsiveness)
- [x] Once the PR is completed and merged, release dependency on #2502

**Screenshots**
<details>
<summary>Languages from here</summary>

![c1](https://user-images.githubusercontent.com/48004150/141726777-97c3de43-7d36-4099-accc-82f115c573a2.png)

</details>

<details>
<summary>Should appear here</summary>

![c2](https://user-images.githubusercontent.com/48004150/141726817-5fe5786a-66a2-4f4e-b171-9488df7d74ca.png)

</details>

### Resources/Instructions
[projects page](https://www.hackforla.org/projects/)
[current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)

**Comment by sydneywalcoff** [comment]
Availability: Full :)
ETA : Tuesday Dec 21, 2021

**Comment by sydneywalcoff** [comment]
Tuesday was ambitious with the holiday
Updated ETA: Sunday Dec 26, 2021

**Comment by ExperimentsInHonesty** [comment]
Looks good.  Only items remaining (to be handled on another issue) are to 
1. make it so that if its a lanugage when you select it, it show up with the chip saying language: javascript vs what it says now technologies: javascript.
2. go through all project.md files that have the language also under technology, to remove anything that is showing up as a language (e.g., docker is actually dockerfile)
