### ISSUE TITLE
Remove Projects from "Our Locations" section of Events page

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2497]
### Overview
We need to remove the Projects from the "Our Locations" section of [Events](https://www.hackforla.org/events/) page in order to more accurately reflect the now fully-remote nature of the organization. We need to keep the 3 photo tiles for Westside, Downtown, and South LA in order to show HfLA's base and connection to the Los Angeles area. 

### Action Items

- [x] Duplicate the Events Page in Figma (both desktop and mobile) 
- [x] Remove the right hand section of the 3 location cards (The section that shows day of week and Projects)
![Screen Shot 2021-11-17 at 12 28 18 PM](https://user-images.githubusercontent.com/16949503/142251633-0c621b85-5408-4baa-8e75-29ff864e3f78.png)

- [x] Redesign this section of the page to just feature the 3 images (Westside, Downtown, and South LA) and put them all the on the same row.
  - Refer to the [design system](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3), and other designs on the site utilizing photo grids, like the [homepage](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=16301%3A101535) for example. 

 

### Resources/Instructions
[HfLA - Events](https://www.hackforla.org/events/)
[Figma - Events ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8552%3A0)
[HfLA Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)

**Comment by jenjen26** [comment]
**Progress**: Assigned to self 11/30
**Blockers:** none currently
**Availability:** ~10hrs this week
**ETA:** 12/10

**Comment by jenjen26** [comment]
Redesigned to show 3 location image cards and removed all day of the week and project information. Ready for review.

[Redesign of events page for desktop and mobile](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18112%3A126109)
![Screenshot 2021-12-10 144729](https://user-images.githubusercontent.com/64928677/145639447-9a8b662b-0c72-4966-a63e-a76a6f66d18d.png)

**Comment by IsaacDesigns** [comment]
@jenjen26 This looks good to me!

**Comment by ExperimentsInHonesty** [comment]
@jenjen26 Please make the desktop version the same square as the mobile.

**Comment by jenjen26** [comment]
@ExperimentsInHonesty @IsaacDesigns Changing the desktop version to square appears to go against the design system currently. I am more than willing to make the change - just wanted to confirm prior to completing.

**Comment by IsaacDesigns** [comment]
@jenjen26 Thanks for addressing this and going off of the design system. We can review this in Thursday's meeting.

**Comment by IsaacDesigns** [comment]
@jen please add in a comment where in the design system it says to make the Desktop cards rectangle rather than square.

**Comment by jenjen26** [comment]
@IsaacDesigns 
The new locations page follows the '[large card' format](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=6195%3A42255) in the design system for the image, which was what the [old locations page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8552%3A0) was using.

Since we've removed the text section to the right of the image on the card, we may want to add a square image design to the design system if that is the preference.

**Comment by IsaacDesigns** [comment]
@jenjen26 yes we have agreed that we will go with your square image design and we will have to add this new square image to the design system.

**Comment by jenjen26** [comment]
Progress: I added this to the [Large Cards](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=6195%3A42255) in the design system.
Blockers: how to complete CSS and naming convention portion in design system
ETA 01/31

**Comment by ExperimentsInHonesty** [comment]
@jenjen26 
FYI: When you put things in the review column, please be as specific as possible about who needs to review and why.  This will ensure that you get the fastest response possible   E.g. on this issue you could have written:

Next Steps: 
- [ ] For Design Team or Design Lead to review and sign off or provide comments
- [ ] When design team or lead is done, Product team needs to review and provide sign off or comments.

**Comment by ExperimentsInHonesty** [comment]
@jenjen26 Thanks for the new work.  Looks perfect, we will turn it over to Development now to make a new issue where they define the classes that are currently in use by adding them to the design system (because it seems like they are missing now).

**Comment by JessicaLucindaCheng** [comment]
Dev follow up issue for this is #3027
