### ISSUE TITLE
HfLA: UXR Meeting Agendas

### ISSUE THREAD

**Issue by sacamp** [hackforla/website#2498]
### Dependecy
When we get a new research lead

### Overview
This issue tracks the agenda for the UXR team's weekly Wednesday meetings.

### Agenda Template:
Meeting: (DATE)

Participants:

**Things to discuss:**

**Things discussed:**

**Actions to take:**

**Comment by sacamp** [comment]
### Meeting: 11/17/21

### Participants: Simone, Summer, Jackie, Anya

### Things to discuss:

- Team member intros
    -    name, background, what you want to learn
    
- Team structure and workflows (brainstorming)
    -    defining team values and priorities: 
   
 -Github tour/overview 
- New researchers complete the prework issue 
- Current donor/partner/advisor research project
- No meeting next week due to Thanksgiving holiday

### Things discussed:

- Team member intros
    -    name, background, what you want to learn

    
- Team structure and workflows (brainstorming)
    -    defining team values and priorities 
    
- New researchers complete the prework issue on GitHub

- Current donor/partner/advisor research project

- No meeting next week due to Thanksgiving holiday

### Actions to take:
- Jackie will create an issue on compiling volunteer research for persona creation
- Summer and Jackie will complete prework checklist
- Simone will provide Summer and Jackie with github instructions and access to accounts
- The team will create a research roadmap  and updated research plan for persona creation of different user groups

**Comment by sacamp** [comment]
### Meeting: 12/8/21

### Participants: Simone, 

### Things to discuss:

- [x] making sure researchers have submitted their individual pre-work issue and are able to check off all boxes
- [x] progress update: working on/progress or blockers
- [x] walkthrough issues on the github board (each team member will self assign onto an issue or continue working on their current issue)
   - [x] #2561 
   - [x]  #1730 
   - [x] #2537



### Actions to take:

**Comment by sacamp** [comment]
### Meeting: 12/15/21

### Participants: Simone, 

### Things to discuss:

- [ ] No meeting next week (12/22), are team members available to meet on 12/29?
- [ ] Github issue and  pre-work issue reminders
- [ ] Progress update: working on, progress, blockers
- [ ] Review issues on the [prioritized backlog](https://github.com/hackforla/website/projects/7#column-7198257) (each team member will self assign onto an issue and/or continue working on their current issue)
   - [ ] #2589 
 

### Meeting notes:
 - no meeting on 12/22, we will meet to touch base on 12/29 to keep momentum
 - github issue reminders: hitting "close issue" will close an issue and mark it as complete. to simply close out of an issue, click on the 'X' on the top right-hand corner
 - importance of Sunday meetings: chance to interact with Bonnie, pitch ideas to her, discuss ideas with Bonnie and the broader team (developers, etc.) etc. 
 - new feature: when you open a pre-work issue it'll automatically add the labels
 -
 - **Shruti** is using the template Simone shared, has been creating a google doc reviewing all our previous research. it will take her some time to do all this, since she's reviewing all our research extremely thoroughly and organizing it
 -      Shruti wondered if everything is in the google drive, or if there is anything else she needs to look at? Simone said that the google drive has all the information she needs. 
 -      Simone encouraged Shruti to check off boxes on the issue as she's working, and asked Shruti to share her link to the google doc she's making once she's done with the doc 
 -      Shruti has a good handle on it, has a sense of what she's looking for, and thinks she can handle it 
 -      Shruti will provide an update on 12/22 before she goes on her break (since she can't attend the 12/29 meeting)
 - 
 -  **Summer** whole homepage or just the single picture for preference testing? whole page could give context, answer their questions, represent a match between system and the real world in terms of how future users would actually see the site; just image lets users focus on just the issue we're testing 
 -       might be helpful to users to explicitly state/make it clear "it's just this top section that's different, only the header image is image"
 -      we could ask users to do an abbreviated version of our desired action, then ask why they were more likely to pursue a certain image
 -      could describe HfLA, then ask which image aligns better with our mission statement 
 -      in addition to the questions, ask them their natural reaction for how they'd move forward, pretending they're a volunteer and/or donor
 -      if we give users the whole page, they'd likely be able to infer the types of activities that volunteers/donors do
 -      i could give a little context for the volunteer/donor roles by saying 'volunteers contribute to HfLA by doing X, donors provide financial support by doing X'
 -
 - **Jackie** picked up an issue related to google analytics and has uploaded a doc into the analytics folder
 -       has some questions, including: how can we identify, track and follow up on potential leads? we could potentially discuss this with developers and designers, but maybe: an interest form, a follow up email, etc.
 -      she found donors are going to the donate page, but not to the Code for America: maybe they're skeptical of going to an external site, maybe they didn't mean to go to the donate page. Questions: why are people going to the donate page, why are people going to the donate page but not donating?
 -      Jackie suggests a 'true intent' pop-up survey, to gain insight RE who is accessing the website and who isn't, which could help us in our donor study 
 -      she suggests UX to identify pain points in donating, interviews to determine why folks are donating, conduct content testing so we're also highlighting volunteer wins, project wins, so people feel more compelled to donate
 -      opportunities to embed donation in the other content, potentially? so users are funneled back to learn more about donations. potentially consider ordering of menu items, such as sorting by frequency of selection
 -     we can go to other chapters' 'donate' site to see if/how they're doing it differently, essentially a competitive analysis (our donate page appears to already be better than other sites :) )
 -      a natural next step for Jackie could be an issue RE solicitation strategy, for which she'd need to pick Bonnie's brain to learn more about the donors
 - 
 - we're all busy with our current issues, so we won't look at the prioritized backlog for now
 - remember to update your issues every week (should get an automatic reminder about that) 
 - when we meet with Bonnie on Sundays, we don't have an agenda for that meeting: Bonnie meets specifically with the UXers in the first 30 mins of that meeting, which is when we get good face-to-face time with her, then the whole team gets together and it's an exchange, like if UX has questions for development, and vice versa
 - eventually it's important for us to be able to present what we do to Bonnie
 - Jackie is wondering if we could set up a dedicated time and ask her more in-depth questions RE who our users are, what the strategy is
 - Simone wrote up a new issue RE conducting an internal interview w/ Bonnie to find out more about volunteers, which we don't have to address immediately but can in upcoming weeks. once we add the info about volunteers to the google doc Shruti and Summer made, we can run that document past Bonnie and ask, is this what you mean, is this right, do you have anything to add to this - to progress the conversations w/ Bonnie RE user groups, so we can round out this document as a whole
 - maybe at the next meeting we can chat about starting this issue

**Comment by sacamp** [comment]
### Meeting: 1/5/22

### Participants: Simone, Shruti, Jackie, Summer
### Things to discuss:

- [x] Migrating to a new Google Drive [folder](https://drive.google.com/drive/folders/1we_k_Hd0vwBmCxcDaX_C6L9JUMX7xO63)
   - [x] Please copy any documents that you have created on the old drive to the new Drive
   - [x] all new documents from this point forward need to be added to the new Drive
- [x] Progress update: working on, progress, blockers
   - [x] when updating your issue, be sure to change the labels to reflect the current status of the issue

### Meeting notes:

**Comment by sacamp** [comment]
### Meeting: 1/12/22

### Participants: Simone, Summer, Jackie, Tammy, Anya and Shruti 
### Things to discuss:

- [ ] Designate a note taker for today's meeting
- [ ] Research request from Anya
- [ ] Progress update: working on, progress, blockers
- [ ] [Drive file access issues](https://drive.google.com/drive/folders/1we_k_Hd0vwBmCxcDaX_C6L9JUMX7xO63)

  

### Meeting notes: 
-	Introductions. 
-	Progress updates below. 
-	Summer: Working on a new home page. Conducting preference test using usability hub website. Hoping for 115 responses. At 102 responses. It is neck to neck. There is text entry from participants for responses explaining why they chose the specific image. Got responses by posting through different slack channels. Should I plan to share the compiled qual data (open text responses as to “why” folks picked 1 image over the other) and themes I’ve identified next week, and we’ll have hit our goal of 115 participants by then? 
-	Anya: designing the mobile. Top navigation bar design. Bonnie suggested we do some research to inform the decisions. Will get more information on which pages which pages will be launching, and which ones won’t be launching. Research request on gauging what users expect by clicking on certain parts of the navigation. Bonnie said links function differently on the navigation page. Anya is going to write an issue template, the necessary tags on it, and actionable items.  
-	Anya will work in collaboration with Summer and Shruti to conduct the necessary research on the navigation related issue.   
-	Jackie: working on impact page. Who are the local and general financial partners? Start with interviews if possible so that we know who they are and what their motivations are. Jackie shared a document which was a planning guide to conduct the impact page research and the Needed UX research methods to get inputs from Simone. 
-	Simone: is working on wiki pages for projects on github. 
-	Shruti: working on the excel sheet on auditing existing UX research repository. Going to link the google pages with each research folder. Summer and Shruti will collaborate with Anya on the research issue once Anya has the issue fleshed out. 
-	Tammy: attended her first research meeting. Had questions about how the research team works.

**Comment by sacamp** [comment]
### Meeting: 1/19/22

### Participants: 
### Things to discuss:

- [x] Designate a note taker for today's meeting
- [x] Progress update: working on, progress, blockers
- [x] Work on top nav issue #2686 

### Meeting notes:

**Comment by summerharveyux** [comment]
Progress update: Summer
 - shared preference test findings and recommendations
 - to do: 1) put your Miro board on the team Miro board and 2) give notes for the main points for each slide, for Simone to share with Bonnie 

Progress update: Shruti
 - working on auditing existing UX research
 - has linked all the issues from Github
 - wanted to ask Simone: Bonnie mentioned creating user personas for volunteers; Shruti can start working on that using existing data from usability tests and interviews. Shruti is open to working on the issue: internal stakeholder interview w/ Bonnie, an issue Simone wrote last month. Simone says that Shruti has fulfilled her task on the audit issue, so the next task is getting the stakeholder interview underway. Once that is completed, can potentially work on persona creation. Shruti will assign herself to stakeholder task. Shruti will read that issue and ask Simone if she has questions. 
 
Progress update: Jackie 
 - met w/ Simone and Bonnie RE Impact Page Planning Guide
 - would like a clear answer on which user groups to prioritize/who the impact page is intended for. Update from Bonnie: pages in construction will be done soon and she'll give Jackie an update then. Once the website is in draft stage is when we can consider our usability tests and getting input RE impact page
 - Jackie's next step: competitive analysis she can work on in the down time, and can move forward on the true purpose/true intent survey (needs to follow-up with Thomas on that) 
 - Bonnie's response to the issue Jackie wrote: it should only have the user research role; it shouldn't have developer issue checkboxes - rather, communicate with the developers to create their own issue RE adding the survey to the website 
 - but, since the survey questions have been created, it's probably more of a developer issue, so Simone suggests removing the UX role, and messaging Thomas 

Anya, Shruti, Summer, Simone: new issue RE app navigation UX research
 - plan: look at the issue and agree on it, before submitting it to Bonnie
 - we'll brainstorm, Simone will write down what we brainstorm, then we'll polish up the issue
 - we need a formal, written UX research plan (would be similar to previous examples of research plans we have, that Simone will slack to Anya and we'll work in in the slack thread)
 - Shruti knows we already have some interview template scripts, she can look into finding one for us from her audit
 - we won't assign anyone to the issue until it's approved and gets a milestone
 - Simone/Shruti will add some links to the current research we can use as templates, some of the aspects of the issue (like research questions, goals, methods) will go into the research plan
 - Simone will tighten up the issue structure and mark that it's ready for a milestone, so we can all get assigned
 - Shruti will make a google folder for the issue so we can keep everything in one place

**Comment by sacamp** [comment]
### Meeting: 1/26/22

### Participants: 
### Things to discuss:

- [ ] Designate note taker for today's meeting
- [ ] Progress update: working on, progress, blockers
- [ ] view [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) if you are in need of a new issue to work on

### Meeting notes: 

- Simone is working on the research wiki so that everything is in one place
- Priyanka is working on user interview guide and will follow up with Bonnie on leads for recruits
- Summer has reviewed Bonnie's comments on her presentation and will revise her presentation to include pertinent details
-  Summer will also follow up with Anya and Shruti about the mobile top nav issue now that it has been approved

**Comment by sacamp** [comment]
### Meeting: 2/16/22

### Participants: Simone, Shruti, Jackie, Tammy, Dionne
### Things to discuss:
- [ ] Designate note taker for today's meeting
- [ ] Progress updates: working on, progress, blockers
- [ ] view [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) if you are in need of a new issue to work on

### Meeting notes: 
-Simone will coordinate with Bonnie times that Shruti will be able to interview her. In the meantime, Shruti will review previous volunteer research in preparation
-Jackie made some adjustments to the true intent survey questions. We decided to keep the race/ethnicity question broad rather than specific, since the main goal is to get a general overview of who donors are.
-Tammy updated the email messaging to corporate donors to reflect flexibility in scheduling. She will edit the donor demographic portion of the questions so that it is aimed more at a corporate audience.
-Simone is working with the product team to develop a research roadmap to help prioritize UX research projects moving forward.

**Comment by sacamp** [comment]
### Meeting: 3/09/22

### Participants: 

### Things to discuss:
- [ ] Starting this meeting, we will use the project board as a guide for  [progress updates](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22#column-7198228): working on, progress, blockers
- [ ] view [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) if you are in need of a new issue to work on

### Meeting notes: 

 - going through Github project board 'in progress' column for organized work updates
 - Simone: creating a UX research roadmap for the HfLA site. progress: created a rough outline, starting w/ determining stakeholder needs (e.g., understanding who uses the website and why). website goals: communicate as much info about HfLA as possible, and reduce repetitive internal one-off conversations. 
 - Tammy: issue: Script and messaging to recruit donors in the interview process. Extracting info from main Homepage Redesign Research Plan document. Unsure of difference between partners and donors, and 'partners' keeps creeping into the donor script. Bonnie wants to ensure research questions align with research objectives. Will utilize the document Jackie made. 
- Anya's issue: both Summer and Shruti have provided comments on google doc and/or Maze site, and are available and responsive, but Anya seems to be launched and doing fine independently 
- Shruti: is scheduling stakeholder interviews. Has read all the conducted research on the volunteer group to create personas, in preparation for Sunday's interview.  Then, will be transcribing and coding interview to get a sense of what else we need. 
 - Jackie: true intent survey. no updates. survey is pretty much ready to go, just needs some communication from developers to determine if they need any more info, to explore options for incorporating on the website. Sunday meetings are hard to attend, but would probably be ideal for Jackie to attend to move the issue forward. Alternatively, Jackie can give notes for Simone to share with developers and provide feedback for Jackie.  Jackie has added comments in blue on the original document, which Simone can share at the Sunday meeting. Thomas originally said he would help, but has since left HfLA and Jackie hasn't heard from anyone else in the meantime. Simone will look into this. 
 -        Bonnie wants Jacke to review her pre-work checklist, it seems incomplete.
 - Summer: just waiting to hear back from Bonnie on the 3 questions I've commented on my issue (1) which of the 2 in-person selfies should I use; 2) is she taking the Zoom screenshots; 3) is she stitching them together?). Can run and analyze the preference test as soon as I obtain the 2 images.

**Comment by summerharveyux** [comment]
- going through Github project board 'in progress' column for organized work updates
 - Simone: creating a UX research roadmap for the HfLA site. progress: created a rough outline, starting w/ determining stakeholder needs (e.g., understanding who uses the website and why). website goals: communicate as much info about HfLA as possible, and reduce repetitive internal one-off conversations. 
 - Tammy: issue: Script and messaging to recruit donors in the interview process. Extracting info from main Homepage Redesign Research Plan document. Unsure of difference between partners and donors, and 'partners' keeps creeping into the donor script. Bonnie wants to ensure research questions align with research objectives. Will utilize the document Jackie made. 
- Anya's issue: both Summer and Shruti have provided comments on google doc and/or Maze site, and are available and responsive, but Anya seems to be launched and doing fine independently 
- Shruti: is scheduling stakeholder interviews. Has read all the conducted research on the volunteer group to create personas, in preparation for Sunday's interview.  Then, will be transcribing and coding interview to get a sense of what else we need. 
 - Jackie: true intent survey. no updates. survey is pretty much ready to go, just needs some communication from developers to determine if they need any more info, to explore options for incorporating on the website. Sunday meetings are hard to attend, but would probably be ideal for Jackie to attend to move the issue forward. Alternatively, Jackie can give notes for Simone to share with developers and provide feedback for Jackie.  Jackie has added comments in blue on the original document, which Simone can share at the Sunday meeting. Thomas originally said he would help, but has since left HfLA and Jackie hasn't heard from anyone else in the meantime. Simone will look into this. 
 -        Bonnie wants Jacke to review her pre-work checklist, it seems incomplete.
 - Summer: just waiting to hear back from Bonnie on the 3 questions I've commented on my issue (1) which of the 2 in-person selfies should I use; 2) is she taking the Zoom screenshots; 3) is she stitching them together?). Can run and analyze the preference test as soon as I obtain the 2 images.

**Comment by sacamp** [comment]
### Meeting: 3/09/22

### Things to discuss:

- [ ] Welcome new members!
- [ ] Review the project board as a guide for  [progress updates](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22#column-7198228): working on, progress, blockers
- [ ] view [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) if you are in need of a new issue to work on

Meeting notes
Progress Updates
-(Simone) Create UXR Roadmap, align business goals with future research endeavors 
-(Jacqueline) Define requirements for surveys, developers to test surveys, need a parental consent form for minors to complete surveys to capture demographic of volunteers <18 years old, Satisfaction question too personal may raise trust issues
-(Summer) Hero page, edit form to New Hero Page to distribute to different groups, which image do users prefer, performed preference test to yield quantitative and qualitative data, provided recommendation based on findings to stakeholders.

**Comment by sacamp** [comment]
### Meeting: 3/16/22

### Things to discuss:

- [ ] New member intro!
- [ ] Review the project board as a guide for  [progress updates](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22#column-7198228): working on, progress, blockers
- [ ] view [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) if you are in need of a new issue to work on

###Meeting notes

Progress Update Vivian 
-Access for Google Analytics, Revising Scripts
-Wins submission process- usability testing. User questions for wins page social media sharing. How comfortable are users willing to share on social media 
-Recruiting users who want to submit wins but have not
-What are other ways to share website without using social media

Progress Update Shruti
-Interviewed Bonnie on Sunday, in process of transcribing the interview. 
-Concerns: volunteers do not know what they need
-Read through previous volunteer interviews next steps are to code and transcribe interviews
-Will create a spreadsheet of recommendations
-Will create user personas for volunteers

Progress Update Jackie
-Career satisfaction question
-illegal to survey minors
-Looked for pricing plans to use for surveys (Survey Monkey and Qualtrics). Survey Monkey more viable option. 
-What is our budget?

Progress Update Summer
-Created flyer revised based upon suggestions
-Bonnie made a list of projects to see images 
-Will discuss the images after meetings to make a preference test

Progress Update Dionne
-Revising Research Plan to target corporate donors
-TO DO: Write questions about corporate donors to present at the Sunday meeting
-Get resources for corporate donors in User groups in Google Drive
-When organizations change donors left (why?)
-Individual vs corporate donors
-Get the link from Simone about corporate donor interviews

Progress Update Sherri
-New Member
- Assign an issue

**Comment by sacamp** [comment]
### Meeting: 3/23/22

### Things to discuss:

- [ ] Team photo for Summer's research!
- [ ] Review the project board as a guide for  [progress updates](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22#column-7198228): working on, progress, blockers
- [ ] view [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) if you are in need of a new issue to work on

###Meeting notes

**Comment by sacamp** [comment]
### Meeting: 3/30/22

### Things to discuss:

- [ ] Team photo for Summer's research!
- [ ] Review the project board as a guide for [progress updates](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22#column-7198228): working on, progress, blockers
- [ ] view [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) if you are in need of a new issue to work on
- [ ] Reminder: no team meetings next week since it is the first week of the month

###Meeting notes

1. Summer took a team photo for her issue. 

2. Shruti: Updated on her issue that she is working on transcribing Bonnie’s interviews. The MIRO board has reached its maximum limit. Cannot edit any frames to add insights. Simone will follow up with Bonnie about  Miro’s subscription. Going to make a User profile for volunteers and keep changing it as things evolve. Check out otter.ai free software for transcription. 

3. Jackie: shared her ongoing work on the True Intent Survey and how she is incorporating Bonnie's feedback on occupation data. Challenges with long surveys and what insights we could get from the backgrounds. Shared insights from google analytics of the donation page. Very few potential donors were visiting the website. Clarification is needed from Bonnie about this issue. What survey platform to use to conduct the survey? Will reach out to websites to learn what their capabilities are.  

4. Summer: Bonnie has not shared flyers with all teams. Only 4 teams have images. Maybe it is enough to run a preference test. Simone is going to remind Bonnie about sharing the flyer. Can stitch together existing images using more stock images from Google. 

5. Dionne: corporate donor research plans. Revising the plan to target a specific user - corporate donors. How we can optimize the HLA website to better assist the community. Clarified some KPIs with Simone. Kept research questions about the corporate donors. Thematic analysis with the individual donors. 

6. Vivian: Started recruiting a few days ago in Slack. It was difficult to get recruits. Did not want to make the pool narrow by just having Wins. Simone shared some more ideas about how to find people on LinkedIn. 

7. Sherri: working on creating issues. Simone will message about what Bonnie and she discussed. 

8. No team meeting next week. Feel free to continue to work on your issues.

**Comment by sacamp** [comment]
### Meeting: 4/13/22

### Things to discuss:

- [ ] Miro update
- [ ] Review the project board for [progress updates](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22#column-7198228): working on, progress, blockers
- [ ] view [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) if you are in need of a new issue to work on

### Meeting Notes:

**Comment by SAUMILDHANKAR** [comment]
After website homepage launch, research will look into a global change for all the menu items and their corresponding page/section titles. [Related comment](https://github.com/hackforla/website/issues/2481#issuecomment-1100764836)
> As per [all team meeting](https://github.com/hackforla/website/issues/2027#issuecomment-1098698081) discussion on Apr 17, 22.

**Comment by sacamp** [comment]
### Meeting: 4/20/22

### Things to discuss:

- [ ] Research updates
   - [ ] Review the project board for [progress updates](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22#column-7198228): working on, progress, blockers
- [ ] view [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) if you are in need of a new issue to work on

### Meeting Notes:
Simone: Wiki Issues
Vivian: Research Presentation on Wins Page. 
Shruti: Transcribed interview. Pulled insights from previous volunteer interviews and Bonnie's interview. 
Jackie: Simone will send a link to get access to the survey
Summer: Preference test suggested by Bonnie. need 115 responses, then will launch a second preference test. 
Dionne: Will work on wiki issues. Will meet with bonnie to discuss the research plan.
Sherri: Onboarding issues. Make a quiz to determine users' skill levels to direct to different teams. 
Claudia: In the process of selecting an issue to work on

**Comment by sacamp** [comment]
### Meeting: 4/27/22

### Things to discuss:

- [ ] Research updates
   - [ ] Review the project board for [progress updates](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22#column-7198228): working on, progress, blockers
- [ ] view [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) if you are in need of a new issue to work on

### Meeting Notes:

**Comment by sacamp** [comment]
### Meeting: 5/18/22

### Things to discuss:

- [ ] Research updates
   - [ ] Review the project board for [progress updates](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22#column-7198228): working on, progress, blockers
- [ ] view [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) if you are in need of a new issue to work on

### Meeting Notes:

Information from Summer, requesting that if folks are in other UX-relevant slack groups that they please share the blurb advertising the preference tests: 

slacks I've posted in: Hack for LA, UX Rescue, UXPA Boston, UX Research & Strategy, People Nerds, Hexagon UX, Ideate Labs, Delta CX, ResearchOps, Research by Leaners

blurb I posted:
Happy Monday, y'all!
If you have a spare 1ish minute to help a non-profit organization (Hack for LA, a Code for America chapter) select their website homepage image, I'd really appreciate it! [Please use this link](https://app.usabilityhub.com/do/f317c83b986/654d) to take a wicked brief online survey which asks which of 2 images you prefer and why.
Thanks so much for your time!!:star2: :hugging_face::sunny:

link: https://app.usabilityhub.com/do/f317c83b986/654d

**Comment by sacamp** [comment]
### Things to discuss:

- [ ] Team updates
- [ ] Research updates
   - [ ] Review the project board for [progress updates](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22#column-7198228): working on, progress, blockers
- [ ] view [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) if you are in need of a new issue to work on

**Comment by vaisali89** [comment]
### Meeting: 7/20/22

### Participants:
 - Vaisali Krishna Kumar
 - Sandarsh Pandey
 - Neha Syed
 - Emily Tat
 - Alice MillerMacPhee
 - Anna 
 - Vanessa Murray
 - Shima Houshyar
 - Karen Munnelly 

### Things to discuss:
- [x] Introductions
- [x] Onboard new members
- [x] Research updates
- [x] Review the project board for [progress updates](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22#column-7198228): working on, progress, blockers
 view [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) if you are in need of a new issue to work on.

### Meeting Notes:
- Alice, Anna, and Sandarsh wanted to discuss on persona creation process and recruit participants for interviews.

**Comment by vaisali89** [comment]
### Meeting: 9/11/22

### Participants:

- [ ] Neha Syed
- [x] Karen Munnelly
- [x] Vanessa Murray

 

### Things to discuss:
- [ ] Discuss research updates
- [ ] Review the project board for [progress updates](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22#column-7198228): working on, progress, blockers
 view [prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+user+research%22) if you are in need of a new issue to work on.

### Meeting Notes:
-

**Comment by ExperimentsInHonesty** [comment]
Currently, not having meetings
