### ISSUE TITLE
Update Site map

### ISSUE THREAD

**Issue by IsaacDesigns** [hackforla/website#2501]
### Overview
We need to update the Figma site map page so that it accurately represents the current state of the Hack for LA site.

### Action Items
- [x] Duplicate the most recent version of the sitemap page in Figma and add to Draft Pages section.
- [x] Rename copy to be  
```
Site Map - [add date draft last updated] (WIP)
```
- [x] Review the live site, checking for any inconsistencies between the status of pages on the live site and what is shown on the site map. 
- [x] Update the site map in Figma, making any necessary changes to ensure it accurately represents the current status of all pages on the site. 
- [x] Add the following pages to the sitemap as if they were live (in preparation for the new homepage launch). Any pages that are not listed in the sitemap add them to the Future Pages section within the sitemap.
  - [x] About
  - [x] Program Areas
     - [x] Citizen Engagement
     - [x] Civic Tech Infrastructure
     - [x] Diversity / Equity and Inclusion
     - [x] Environment
     - [x] Justice
     - [x] Social Safety Net
     - [x] Vote / Representation
     - [x] Workforce Development
- [ ] Once accepted and closed, let development know to make an issue for updating the sitemap, and that they need to put it in the homepage feature branch until homepage launches.

### Resources/Instructions
Figma-[Current Pages](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A0)
Issue [2512](https://github.com/hackforla/website/issues/2512) lists all pages and their status within the Resources/Instructions section
[Figma site map file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=12457%3A96372)
[Live site map page](https://www.hackforla.org/sitemap/)
[Figma of the new homepage](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=9477%3A88938)

**Comment by iilashi** [comment]
Progress: Issue is on hold until further notice.
Blockers: No known status of pages Civic Tech thru Workforce Development
Availability: A few hours a day
ETA: N/A

**Comment by IsaacDesigns** [comment]
This issue is on hold until @ExperimentsInHonesty and I can update the development status of the Current Pages page in Figma.

**Comment by IsaacDesigns** [comment]
@ilashi I have updated the status of each page in Figma's "Current Pages" page to reflect the current status and near future status for when the site launches this month.

**Comment by iilashi** [comment]
Progress: WIP
Blockers: None at the moment
Availability: A few hours a day
ETA: In the next few days

**Comment by iilashi** [comment]
Progress: Ongoing
Blockers: None 
Availability: A few hours a day
ETA: n/a

**Comment by iilashi** [comment]
@ExperimentsInHonesty Is this the finalized version of the navigation bar that I should follow? Or are updates/changes still being made? Because the navigation shown on the completed current pages doesn't match the one shown below.

![image](https://user-images.githubusercontent.com/92768477/151522575-d6654ccd-0551-4460-8855-7d339698d445.png)

**Comment by iilashi** [comment]
Progress: Ongoing
Blockers: Some pages are still WIP, cannot update until status is provided
Availability: A few hours a day
ETA: N/A

**Comment by iilashi** [comment]
Progress: Ongoing
Blockers: None
Availability: A few hours a day
ETA: N/A

**Comment by iilashi** [comment]
Progress: Ongoing
Blockers: None
Availability: Few hours daily
ETA: N/A

**Comment by ExperimentsInHonesty** [comment]
@ilashi Can you provide an update that includes when you think you will have this completed?

**Comment by iilashi** [comment]
Progress: WIP
Blockers: None
Availability: 
ETA: TBD

**Notes:** 

![image](https://user-images.githubusercontent.com/92768477/161874777-61086965-9ca7-4260-bf28-1bea2156a03d.png)
![image](https://user-images.githubusercontent.com/92768477/161874905-2998402b-c5e5-4b21-b990-2eb4b40eea32.png)

A *red star has been added next to any page titles that don't have existing pages to match them. Meaning there's no current status or design available for them. This is subject to change as more pages are added and updated! Every page that is listed on the sitemap is based off the current navigation/footer available on the figma file.

![image](https://user-images.githubusercontent.com/92768477/161875042-0036bd07-caf3-4d5c-92ba-30a305cbbe16.png)

These pages are complete and live but aren't listed on the current navigation or footer. So the current placement of them is unknown.

**Comment by nathan944** [comment]
Availability for this week:

1. Progress: I've completed 'program areas', with 2 more tasks to be completed.
2. Blockers: N/A
3. Availability: A few hours
4. ETA: By Sunday (4/24/22) this week, for the review
Images:
![image 2](https://user-images.githubusercontent.com/76053494/164793693-8368f4b4-c6f5-4964-a8d1-4b3f27a27834.png)

**Comment by phuonguvan** [comment]
There are external links on the website that lead to Google forms to links that would make the users leave the website (ex. transportation's survey in hackforla.org) 
![image](https://user-images.githubusercontent.com/100561599/172989331-1a4ed09c-378d-4c84-8504-dd72a6cf1c6b.png)
There is a suggestion to use Iframes which creates a mini-frame where the user is able to access the Google form in the same website. This will allow them to not leave the website while filling out these google forms. In the site map, these Google forms are labeled as  as external links, If we decide to create the issue to add the Iframes, then someone has change them to internal links.
