### ISSUE TITLE
Test for updated api token

### ISSUE THREAD

**Issue by elizabethhonest** [hackforla/website#2503]
A new wins form submission has just been created. Please navigate to the link below to review it.<br><br>- [Wins Submission Google Sheet](https://docs.google.com/spreadsheets/d/1fXmYrmNtrgdzkM_odGIRbSwdaea3yS0cTLCJUzZ6Sc0/edit#gid=1706218917)

**Comment by macho-catt** [comment]
I updated the token since it recently expired. This is just a test to ensure that api works with the new token
