### ISSUE TITLE
Create mobile version of new footer 

### ISSUE THREAD

**Issue by IsaacDesigns** [hackforla/website#2511]
### Overview
We need to create a mobile version of the new footer so that it can be implemented and launched alongside the desktop version. 

### Action Items

- [x] Familiarize yourself with the desktop version of the site’s new footer in Figma
- [x] Create a section to the right of the desktop version for the mobile design
- [x] Review the Mobile Navigation Audit in Figma to familiarize yourself with the way mobile nav is designed across the rest of the site
- [x] Create a design that translates the desktop version of this new footer design for mobile.
- [x] Ensure your design is usable and intuitive for mobile, keeps consistent with Design System guidance and other usage across the site, and provides a good experience for users.
- [ ]  Once accepted and closed, let development know to make an issue for updating the sitemap, and that they need to put it in the homepage feature branch until homepage launches.

### Resources/Instructions
Figma - [New Footer](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3417%3A3)
Figma - [Mobile Navigation Audit](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=15122%3A95165)

**Comment by Stephen-Parent** [comment]
Progress: New design is complete and ready for review
Blockers: NA
Availability: 3+ hours
ETA:
Pictures: (left is new, right is current)
![image](https://user-images.githubusercontent.com/94029486/144727908-85f09b3a-250c-4819-9670-3f0b2cdc14f0.png)
