### ISSUE TITLE
Update Project Profile: helloGOV

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#252]
### Overview
Update the following fields for your project. These updated fields will then be updated to be shown on the website.

### Action Items
Provide in the comments below:
- [x] updated wording if necessary on the project card (see [hackforla.org](https://www.hackforla.org/))
- [x] information on which Tools your team is using for the project (Ex: figma, Balsamiq, photoshop, etc.) . This is different than programming languages
- [x] updates for "Looking For" Section
- [x] any updated links that are not currently displayed on the site (do you have a demo site?)
- [x] Hero image to be displayed on Project Home Page at 1500 x 700 px
- [x] any resources for a Getting Started link (either a link to a wiki or readme)

### Resources/Instructions
See the hero image on the [hackforla.org](https://www.hackforla.org/) homepage

**Comment by kate-rose** [comment]
Update wording of anything currently on the project card (see hackforla.org)

HelloGOV is helping grassroots organizations connect supporters to their state assembly and state senate representatives for call campaigns to advocate on the legislation that matters most to their work. The HelloGOV webapp generates a campaign shortlink that can be used in texts, social posts, and more.

 Update "Tools" Section to display the tools being used for the project (Ex: figma, Balsamiq, photoshop, etc.)

Mongo, Angular, Node, JS

Update "Looking For" Section

Looking for folks to help with implementing end to end testing, user testing and outreach, and a UI redesign. All skill levels, all kinds of contribution welcome.

 Update any links that are not currently displayed on the site (do you have a demo site?) - none
 Banner Image to be displayed on project specific page 16:9 ratio (min width 1200px) - none

 Any resources for a Getting Started link (either a link to a wiki or readme) - https://github.com/helloGov/webapp

**Comment by ExperimentsInHonesty** [comment]
@kate-rose We have to have a banner image, for the project homepages, it's not optional.  Let me know if you need the loan of a UI person to make one, if you don't have someone on your team with that skill set.

Note to website team, here is the url direct to the readme: https://github.com/helloGov/webapp/blob/master/README.md

**Comment by ashlingam** [comment]
@kate-rose  Posted to HelloGOV Slack channel to request update: https://hackforla.slack.com/archives/CDA23KHKP/p1582484825000900

**Comment by ExperimentsInHonesty** [comment]
Use this
![hellogov-hero](https://user-images.githubusercontent.com/37763229/75644569-96023c00-5bf7-11ea-8257-abd2cd20eced.jpg)

**Comment by ExperimentsInHonesty** [comment]
@kate-rose I was unable to find a graphic designer to make a hero for you.  So we going with a solid teal block for the hero.  This will make sense when the page is live. Talk to you then.

**Comment by ExperimentsInHonesty** [comment]
Message from kate
Leadership is me (username kate-rose) 
Sarah (seport)
Brett (beekley) as leadership too. Thank you!

**Comment by ExperimentsInHonesty** [comment]
@zempo zempo added 
```yaml
leadership:
  - name: Kate
    slack: 'https://app.slack.com/team/UA02Y8W2Z'
  - name: Sarah 
    slack: 'https://app.slack.com/team/U686ZV93P'
  - name: Brett 
    slack: 'https://app.slack.com/team/USRRN73NE'
```
and this under links
```yaml
  - name: Testing site
    url: 'http://food-oasis.herokuapp.com/' 
```
but the pull request had merge conflicts, so was not accepted.   Waiting for resubmit.

**Comment by ExperimentsInHonesty** [comment]
Leadership and Tools have been defined.  Add those to the project card.  Issue ready to work.  Team has not provided hero image.  We will revisit later.

**Comment by parkderick** [comment]
Pull Request submitted

**Comment by cnk** [comment]
We are still missing a last name for Kate Rose and roles for the 3 people on the leadership listing
