### ISSUE TITLE
Create a reference document containing summaries/definitions of target user groups

### ISSUE THREAD

**Issue by sacamp** [hackforla/website#2527]
### Overview
We need to create a reference document containing summaries/definitions of different target user groups so that researchers have a common understanding of the types of user groups we aim to research in #2015 .
### Action Items

- [x] watch UX team's interview with Bonnie about different stakeholders
- [x] create a document containing definitions of the following groups:
   - [x] volunteers
   - [x] individual donors
   - [x] institutional donors
   - [x] advisors
   - [x] financial partners
   - [x] local government partners

### Resources/Instructions
[Interview with Bonnie](https://drive.google.com/drive/folders/1tQbN7EtJBmFuiASY4-9gw4pVVtoVw80R)
[Slide deck with preliminary notes](https://docs.google.com/presentation/d/1YYgEuKMGV_gmmxTLQF1gOvVd_wDJDN5E2f7mHwDorKg/edit#slide=id.ge6342aa826_0_93)

**Comment by summerharveyux** [comment]
Progress: I finished watching Bonnie's interview, typed up all my notes from it on the 3 groups of advisors, financial partners, and local government partners, and added my notes to the Google doc that @ShrutiMukherjee started and shared with me, so I believe my assignment on this is complete
Blockers: None.
Availability: Task completed from my side.
ETA: Task completed from my side.

**Comment by sacamp** [comment]
[Reference document containing summaries/definitions of target user groups](https://docs.google.com/document/d/18FnLUCApXPzMB_hdtMmNrLwPcC0dsStwT___IsHWgcU/edit)

**Comment by ghost** [comment]
Progress: Finished watching Bonnie's interview and typed up the definitions of volunteers, individual donors, and institutional donors on the google sheet. There is not much about "volunteers" in this interview. 
Blockers: None
Availability: Task completed from my side. 
ETA: Task completed from my side.
