### ISSUE TITLE
Add credits for photos and icons for redesigned homepage

### ISSUE THREAD

**Issue by kristine-eudey** [hackforla/website#2528]
### Overview
We need to add credits for all new icons and photographs used in the redesigned version of the homepage so that the Credits page is up to date. 

### Note: Feature Branch
The pull request created from this issue should be pushed into a feature branch called "feature-homepage-launch." Please note this [wiki article](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch) on how to work off of a feature branch.

### Action Items

- [ ] Add credits to the Credits Page for all the icons and photographs used on the redesigned homepage. All the credit information can be found [here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724).

### Resources/Instructions
[HfLA - Credits Page](https://www.hackforla.org/credits/)
[Figma - Homepage Redesign: Credits](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)

**Comment by jqg123** [comment]
Availability for this week: 20h
My estimated ETA for completing this issue: 12/14/21

**Comment by jqg123** [comment]
I have a blocker. I do not know where to source the new icons from. The previous icons have photos in the assets folder. I have added a discussion teamwork link. I have attempted to download the svg from the link and add it to the images. The result was a blank pictures. Possibly the picture is scaled too large or I do not know the format of the svg file. I am working on the add-credit-icon-redesign-2528 branch of my forked repo. Any assistance is appreciated.

**Comment by macho-catt** [comment]
@jqg123 you can export the image from the figma design. I can show you in tonight's meeting.

**Comment by SAUMILDHANKAR** [comment]
@jqg123: Thanks for adding your availability and eta. Just wanted to share a point from our Sunday team meeting. We are now requesting all developers to add eta and availability at the time of picking up an issue or when you are assigned to an issue. You are already doing this, so nothing needs to be done at your end. Just wanted to let you know. Thanks for your awesome work.

**Comment by jqg123** [comment]
I have no idea how to resolve the conflicts. Perhaps there were update while I was away? I have tried to update the website from upstream first before I submitted.

**Comment by SAUMILDHANKAR** [comment]
I changed the size label to medium since scope of work involved now is greater than a small issue.

**Comment by SAUMILDHANKAR** [comment]
Received an update from John: "not able to continue on this due to an upcoming job".
Unassigning and moving this issue back to new issue approval column as the issue needs a rewrite as well.
Including Jessica for reference (@JessicaLucindaCheng)

**Comment by JessicaLucindaCheng** [comment]
I want to make this into an epic. I will be breaking down each credit into its own small complexity issue.

**Comment by JessicaLucindaCheng** [comment]
This issue will be broken down and implemented in this epic #3130 because
- Some of the credits exist on the feature branch but need some of the information changed because it has outdated/inaccurate info.
- Some credits need to be created from scratch but the image exists on the feature branch already.
- One credit needs to be created and needs an image added.
- It will make it easier to review each credit.

Thus, I will be closing this issue.
