### ISSUE TITLE
Create interview guides for each type of user interview

### ISSUE THREAD

**Issue by sacamp** [hackforla/website#2529]
### Overview
We need to create interview guides that can be used during user interviews with our different user groups.

### Action Items

- [ ] Read the individual donor research plan as an example
- [ ] Define overarching research question for each user group
- [ ] Write interview questions which address overarching research questions

### Resources/Instructions
[Donor research plan](https://docs.google.com/document/d/1ELtk7H_uubatggRcTO9imHzdheeiPWkDLs3KZepMwh0/edit)

**Comment by ExperimentsInHonesty** [comment]
No longer deemed necessary
