### ISSUE TITLE
Update Project Profile: Public Tree Map

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#253]
### Overview
Update the following fields for your project. These updated fields will then be updated to be shown on the website.

### Action Items
- [ ] Update wording of anything currently on the project card (see [hackforla.org](https://www.hackforla.org/))
- [x] Update "Tools" Section to display the tools being used for the project (Ex: figma, Balsamiq, photoshop, etc.)
- [x] Update "Looking For" Section
- [x] Update any links that are not currently displayed on the site (do you have a demo site?)
- [ ] Banner Image to be displayed on project specific page 16:9 ratio (min width 1200px)
- [ ] Any resources for a Getting Started link (either a link to a wiki or readme)

### Resources/Instructions
Rough example of a good banner image from the helloGOV project:
![](https://user-images.githubusercontent.com/37763229/71553521-b75f6580-29c5-11ea-892e-0f0391069dc7.png)

**Comment by emillipede** [comment]
Public Tree Map documents all 35,000 public trees (and vacant tree sites) in Santa Monica's urban forest. The map includes contextual information compiled from open datasets, digitized city records, and federal ecosystem services values. To reflect tree plantings and removals, the map updates every day.

Links: [Github](https://github.com/orgs/Public-Tree-Map/projects/1), [Test Site](https://public-tree-map.surge.sh/), [Slack](https://hackforla.slack.com/messages/C9UU5KKAA/)
Partner: City of Santa Monica Public Landscape
Tools: JS, leaflet, python
Looking for: Front-end web development, data processing, project management, appreciation for trees.
Location: Santa Monica

**Comment by emillipede** [comment]
> ### Action Items
> * [ ]  Update wording of anything currently on the project card (see [hackforla.org](https://www.hackforla.org/))

nb - I did make a small change to the wording
