### ISSUE TITLE
Donor Focused UX Research Plan

### ISSUE THREAD

**Issue by JackieRiley1** [hackforla/website#2536]
### Overview
The purpose is to create a UX research plan focused on increasing donations. We currently have a research plan focused on multiple user groups, but would like to extract the donor related information to make the plan more focused.

### Action Items
Review existing UX studies focus on how non-profits increased donations.
Revise existing research plan

### Resources/Instructions
Existing Research Plan: https://docs.google.com/document/d/1ELtk7H_uubatggRcTO9imHzdheeiPWkDLs3KZepMwh0/edit 

Donor Focused Research Plan: https://docs.google.com/document/d/1jxm8UTujCm1y9ww5CySvuxoDEx1EDHZq/edit?rtpof=true 

Resources for Donor focused UX Research: 
https://www.nngroup.com/articles/donation-usability/
https://uxdesign.cc/charity-website-a-ux-case-study-209071f1622b
https://www.givergy.com/us/blog/improve-your-user-experience-to-increase-charity-donations/
https://www.reasononeinc.com/blog/task-oriented-design-for-nonprofit-donations-cri

**Comment by JackieRiley1** [comment]
Research plan draft has been created. It will undergo revisions as more information is learned and data is collected.

**Comment by sacamp** [comment]
- This is being worked on in issue #2309
