### ISSUE TITLE
Update Project Profile: VRMS

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2552]
### Overview
As a product manager of VRMS I want my project's details to be up to date on the HackforLA website

### Project card
https://github.com/hackforla/website/blob/gh-pages/_projects/vrms.md

### Action Items

- [x] VRMS Team Leadership
   - [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [x] leadership
         - [x] Name
         - [x] GitHub hand
         - [x] Role
         - [x] SLACK ID
      - [x] links
         - [x] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] looking
      - [x] technologies
      - [x] location
      - [x] partner
      - [x] tools
      - [x] status

**Comment by ExperimentsInHonesty** [comment]
Description: VRMS is a browser-based software tool created by Hack for LA (HfLA) for volunteer organizations to curate participant journeys and further organizational goals of workforce development and project impact. By collecting and using relevant data, VRMS is able to automate repetitive tasks; match volunteers with projects, relevant training and job opportunities; measure engagement with projects and activities; and surface insights to improve organizational effectiveness and the volunteer experience over time. 

Remove the following people
Khushboo Shah
Olga Bilogurova

Add the following people
Name: Katiuska Alicea de Leon
Github handle: chukalicious
Role: Full Stack Web Developer
Slack ID: U0100R46ESC

Name: Glen Paul Florendo
Github: glenflorendo
Role: Full Stack Developer
Slack: DFPQ91VHN

Name: Walter (JunJie) Tang
GitHub handle: WalterT-MK
Role: Full Stack Developer
Slack ID: U02KAPGUZ0T

Name: Josh Bubar
Github handle: jpbubar
Role: Shows up to meetings
Slack ID: UMNNMHXV2

Name:  David Rubinstein
GitHub: drubgrubby 
Role: Engineer for the People 
Slack ID:  U015FP47R5G

Add the following link (by downloading the pdf and adding it to where we store pdfs on this project (https://github.com/hackforla/website/tree/gh-pages/assets/pdfs)
https://github.com/hackforla/product-management/blob/master/project-one-sheets/VRMS-One-Sheet.pdf

Add the following Tools
MongoDB Atlas
Insomnia
Postman

**Comment by sydneywalcoff** [comment]
Availability this week: Wed-Fri
My estimated ETA for completing this issue: Wed Dec 15, 2021

**Comment by sydneywalcoff** [comment]
Updated ETA: Today Thursday, Dec 16 21

**Comment by ExperimentsInHonesty** [comment]
![vrms](https://user-images.githubusercontent.com/37763229/151480681-f5c6fc60-fc9b-4ce0-9dc2-93286a819ae4.png)
