### ISSUE TITLE
TYPO - change GitHub hand to GitHub handle

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#2553]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We need to keep code quality standards high on this project so that we can model best practices for new developers and team pride.

### Action Items
- [x] Correct the spelling mistake in the Issue Template "[Project Profile Card review and update](https://github.com/hackforla/website/blob/ced4d6e9a900c02f55f3fc0449057b830783d4bb/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.md?plain=1#L26)" markdown file by changing "GitHub hand" to "GitHub handle" in line 26:

From
```
         - [ ] GitHub hand
```
To
```
         - [ ] GitHub handle
```
- [x] Ensure that creating a new issue using [this](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D) form reflects the spelling fix.

#### File and Code links you will need to review this issue
- Directory to find the page in once you have it in your IDE: ```gh-pages/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.md```

- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/ced4d6e9a900c02f55f3fc0449057b830783d4bb/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.md#L26

**Comment by mrgeraffe-kun** [comment]
Hello, can I get assigned with this issue?

**Comment by macho-catt** [comment]
hi @Yogeshp0012 . Thank you for your interest in contributing to our organization. If you would like to contribute to our repository, you need to join our organization first. To join, please check this [website](https://www.hackforla.org/getting-started).

Joining involves being onboarded to our team, and following the contributing document. We only allow volunteers to work and fix one issue at a time to give other volunteers the opportunity for good first issues. After you've been onboarded, you can claim a single issue and open a PR to have it reviewed and merge.

After you've joined the team, I will be happy to assign you an issue and review your PRs. Thanks!

**Comment by JessicaLucindaCheng** [comment]
@blulady You don't need to do two first good issues. I think you already are doing this one https://github.com/hackforla/website/issues/2431. Also, we ask that you please only work on one issue at a time and wait for your pull request to be merged before working on another issue. Thank you.

**Comment by blulady** [comment]
Hey, 
Sorry!! What is my next action with regards to this issue?
All Apologies,
Sarah

**Comment by JessicaLucindaCheng** [comment]
@blulady I will unassign you and put the issue back in the Prioritized Backlog.

**Comment by blulady** [comment]
I appreciate your patience. Thank You!!

**Comment by Pauljsyi** [comment]
Availability for this week: Friday 1pm - 5pm
My estimated ETA for completing this issue: 2 hours
