### ISSUE TITLE
Create project card for new-schools-today

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#257]
### Overview
Provide collateral for the HackforLA website

### Action Items
- [x]   Gather items
  - [x]  600 x 400 image
  - [x]  Alt image text
  - [x]  Name of project
  - [x]  A blurb about your project
  - [x]  Links (website, github, etc.)
  - [x]  What you are looking for skills wise
  - [x]  Partner(s)
  - [x]  Location
- [x]   Add project Card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples
[Project Card](https://docs.google.com/document/d/1AOiuwxfXEkg_SlIVzzIzen5XEUAZ1IIs0PhNT2k7Sz0/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
when you do the pull request ask cnk to review.
use fixes # and issue number on pull request

**Comment by ExperimentsInHonesty** [comment]
@sugarsyntax please update with:
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by leonelRos** [comment]
fix #257. Also, I don't see the status of this project so I will leave it like that as of now. @ExperimentsInHonesty

**Comment by ExperimentsInHonesty** [comment]
@leonelRos can you do another pull request to use the picture I got approval on?  Sorry it was not clear from my comment.  Here is the picture I have approval on: https://github.com/hackforla/website/issues/257#issuecomment-572666670

Also, when you do that pull request, in the pull request notes itself, you need to write 
```yaml
Fixes #257
```
otherwise this issue won't close automatically.

**Comment by JacobZwang** [comment]
![Group Photo Full](https://user-images.githubusercontent.com/59858341/74611228-b9cd6a00-50ae-11ea-94fc-edfd820e9d60.jpg)
![Group Photo Raw](https://user-images.githubusercontent.com/59858341/74611231-bfc34b00-50ae-11ea-9886-886a4327baf3.jpg)
![Group Photo 7x15](https://user-images.githubusercontent.com/59858341/74611234-c6ea5900-50ae-11ea-9b7c-5f86b934adf5.jpg)
