### ISSUE TITLE
Update Project Profile: LA TDM Calculator

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2576]
### Dependency
- Waiting for TDM team to provide the link and the leadership info https://github.com/hackforla/tdm-calculator/issues/1028

### Overview
As a product manager of TDM, I want my project's details to be up to date on the HackforLA website

### Project card
- their cards can be found in this folder: https://github.com/hackforla/website/tree/gh-pages/_projects_
- file you will be updating: https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md

### Action Items
- [ ] TDM Team Leadership
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [ ] leadership
         - [ ] Name
         - [ ] GitHub hand
         - [ ] Role
         - [ ] SLACK ID
      - [ ] links
         - [x] Github
         - [x] Slack
         - [ ] Test Site :  tdmdev.azurewebsites.net
         - [x] Demo Site 
         - [ ] Site: tdm.azurewebsites.net
      - [x] looking
      - [ ] technologies - Add Cypress
      - [x] location
      - [x] partner
      - [x] tools
      - [x] status

**Comment by ExperimentsInHonesty** [comment]
The TDM team will be updating the leadership portion of the team list and providing a public link to the site

**Comment by ExperimentsInHonesty** [comment]
Development Site: [tdmdev.azurewebsites.net](https://tdmdev.azurewebsites.net) 
Live Site:  [tdm.azurewebsites.net](https://tdm.azurewebsites.net)

**Comment by KPHowley** [comment]
TDM Members to add to Website: 

Name: Seena Iype
GitHub handle: seenaiype
Role: Product Manager
SLACK ID: Seena Iype / U024C8A6H29

Name: Jane He
GitHub handle: Jane4925
Role: UX Research Lead
SLACK ID: Jane He / U01RDSRT46R

Name: Cathy Duong
GitHub handle: cduong5
Role: UI/UX Designer
SLACK ID: Cathy Duong / U028TU0981M

Name: Fang Liu
GitHub handle: fyliu
Role: Fullstack Developer
SLACK ID: @ Fang / UCE01B4AX

Name: James Higgs
GitHub handle: jahpe777
Role: Frontend Developer
SLACK ID: James Higgs / U015ZGMK171

Name: Jill Armitage
GitHub handle: jarmitageux
Role: UX Researcher
SLACK ID: Jill Armitage / U02HPUSATL2

Name: Shaeeka Salauddin
GitHub handle: Shaeeka
Role: UI Design Lead
SLACK ID: @Shaeeka Salauddin | U028C3EGDDE

Name: Pranav Meda
GitHub handle: pmeda12
Role: UX Researcher
SLACK ID: Pranav Meda / U02KCGML5JB

**Comment by JessicaLucindaCheng** [comment]
Moving this back into Ice Box because it looks like this issue may have been moved into New Issue Approval by accident.

**Comment by bishrfaisal** [comment]
Bonnie needs to get their current information. The issue that was a dependency was out of date.

**Comment by ExperimentsInHonesty** [comment]
Am closing issue.  New issue will get made
