### ISSUE TITLE
Update Accomplishments

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2585]
### Overview
We need to update the accomplishments part of the About page on the website.

### Action Items
- [x] Review with Bonnie the projects that she knows have accomplishments
- [x] Reach out to all the project to find out if they have any
- [x] Provide guidance to the teams about what you are looking for

### Resources
https://www.hackforla.org/about/#accomplishments
Projects on the website: https://www.hackforla.org/projects/

### Recording
[Accomplishments folder on google drive](https://drive.google.com/drive/folders/1_yMq7uLH5eO5Nu6vK3Ii6NHWO3P12nR9?usp=sharing)
[Spreadsheet for tracking accomplishments](https://docs.google.com/spreadsheets/d/1pL63C8ENyeReeLRCXyzYIX1PiONCPKaLXh8u2e0oS9k/edit?usp=sharing)
[Google Doc with Final Drafts of Accomplishments](https://docs.google.com/document/d/1bZ6BUtiq-eArLMExOtYYE_NJdjY-Vqt7nhdtEU8k-cA/edit)

**Comment by zzhoje** [comment]
Availability for this week: 10 hrs

**Comment by ExperimentsInHonesty** [comment]
Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by zzhoje** [comment]
1. Progress: completed spreadsheet; contacting managers to confirm accomplishments and ask for more details
2. Blockers: none
3. Availability: for now 6 hours this week due to holidays and 10 hours next week
4. ETA: draft by Jan 3rd

**Comment by zzhoje** [comment]
1. Progress: contacted all managers; started writing drafts
2. Blockers: none
3. Availability: 10 hours
4. ETA:  drafts for Jan 3rd meeting

**Comment by zzhoje** [comment]
Progress: most drafts written
Blockers: more info needed from BallotNav, TDM Calculator, and Youth Justice Nav (sending messages to their slack channels right now)
Availability: 8-10 hours
ETA: after we review these drafts, I can get the final versions to you by the next meeting (Jan 10th)

**Comment by zzhoje** [comment]
Progress: more concise versions written
Blockers: just need info from BallotNav (have followed up again)
Availability: 6 hours (traveling to see relatives, so I can't make the Jan 17th meeting, but I will continue to work on edits if needed and update this issue throughout next week)
ETA: soon; hopefully we can publish these accomplishments after a few more tweaks :)

**Comment by zzhoje** [comment]
Progress: all updates made 
Blockers: no blockers ( I see the doc from BallotNav)
Availability: 8-10 hours this week
ETA: 3rd versions ready to be checked for meeting tomorrow

**Comment by ExperimentsInHonesty** [comment]
This has been approved and is ready to be added. [Google Doc with Final Drafts of Accomplishments](https://docs.google.com/document/d/1bZ6BUtiq-eArLMExOtYYE_NJdjY-Vqt7nhdtEU8k-cA/edit)

**Comment by ExperimentsInHonesty** [comment]
- This has been followed up with this new issue https://github.com/hackforla/website/issues/3035
