### ISSUE TITLE
Conduct an internal stakeholder interview with Bonnie re volunteers

### ISSUE THREAD

**Issue by sacamp** [hackforla/website#2589]
### Overview
We need to setup a stakeholder interview with Bonnie to obtain insight on HfLA volunteers to complete this reference [document](https://docs.google.com/document/d/18FnLUCApXPzMB_hdtMmNrLwPcC0dsStwT___IsHWgcU/edit?usp=drive_web&ouid=110157642717183613031)
### Action Items

- [x] Read this [article](https://www.userinterviews.com/ux-research-field-guide-chapter/internal-stakeholder-interviews) on the importance/process of conducting internal stakeholder interviews
- [x] Brainstorm interview goals/ interview questions and share them with the research team
- [x] Schedule interview with Bonnie (TBD)
- [x] Synthesize notes from the interview 
- [x] Add a summary of the volunteer user group to the reference document 

### Resources/Instructions
 [Article on stakeholder interviews](https://www.userinterviews.com/ux-research-field-guide-chapter/internal-stakeholder-interviews)
[User groups document](https://docs.google.com/document/d/18FnLUCApXPzMB_hdtMmNrLwPcC0dsStwT___IsHWgcU/edit?usp=drive_web&ouid=110157642717183613031)
Issue about user groups reference document #2527

**Comment by ghost** [comment]
Progress: Going to read the articles and work on the interview guide using archival material from the UX research folder. 
Blockers: None
Availability: 6-7 hours
ETA: Interview questions should be ready by Jan 26

**Comment by ghost** [comment]
Progress: Going to read the articles and work on the interview guide using archival material from the UX research folder.
Blockers: None
Availability: 6-7 hours
ETA: Interview questions should be ready by Feb 2

**Comment by ghost** [comment]
Progress: Working on the interview guide using archival material from the UX research folder.
Blockers: None
Availability: 6-7 hours
ETA: The interview guide should be ready before Wed UX meeting on google drive.

**Comment by ghost** [comment]
Progress: Working on the interview guide using archival material from the UX research folder.
Blockers: None
Availability: 6-7 hours
ETA: Going to brainstorm interview questions in today's UX research meeting and discuss the next steps. 

Resource: https://docs.google.com/document/d/1Cy5VtGukJDCi0UMSjgIC5EFH54U3ssIeq_elayOhChc/edit

**Comment by ghost** [comment]
Progress: Finalized interview guide using archival material from the UX research folder.
Blockers: None
Availability: 6-7 hours
ETA: Working with Simone to figure out an appointment with Bonnie for the stakeholder interview. 

Resource: https://docs.google.com/document/d/1Cy5VtGukJDCi0UMSjgIC5EFH54U3ssIeq_elayOhChc/edit

**Comment by ghost** [comment]
Progress: Finalized interview guide using archival material from the UX research folder.
Blockers: None
Availability: 6-7 hours
ETA: Working with Simone to figure out an appointment with Bonnie for the stakeholder interview.

Resource: https://docs.google.com/document/d/1Cy5VtGukJDCi0UMSjgIC5EFH54U3ssIeq_elayOhChc/edit

**Comment by ExperimentsInHonesty** [comment]
@ShrutiMukherjee I can do 11am or 1pm next Sunday

**Comment by ghost** [comment]
@ExperimentsInHonesty Thanks Bonnie. 1 pm EST or PST? I Will set up a zoom meeting link accordingly.

**Comment by ExperimentsInHonesty** [comment]
@ShrutiMukherjee I am available today at 11am PST or next week at this time.  Please just show up to the all team meeting and we will drop into a breakout room.

**Comment by ghost** [comment]
@ExperimentsInHonesty Will attend the all team meeting next Sunday and meet with you in a breakout room. See you soon.

**Comment by ghost** [comment]
Hi @ExperimentsInHonesty Confirming our meeting this Sunday. I will join the all teams meeting at 10 am PST/ 1 pm EST. 
Below is the document for your reference which has all the questions I am going to ask you. 

Resources: 
https://docs.google.com/document/d/1Cy5VtGukJDCi0UMSjgIC5EFH54U3ssIeq_elayOhChc/edit

**Comment by ghost** [comment]
@ExperimentsInHonesty Is there an all team meeting today, since it is the first week of the month?

**Comment by ghost** [comment]
@ExperimentsInHonesty I just read the slack update that today's all teams meeting has been cancelled. Should we plan to meet in the next team meeting on March 13th?

**Comment by ghost** [comment]
Hi @ExperimentsInHonesty Checking in about the Sunday meeting on March 13. I am planning to attend it and interview you in the breakout session. Does that still work for you? Let me know and I will plan my weekend accordingly. Thank you.

**Comment by ghost** [comment]
Progress: Conducted internal stakeholder interview with Bonnie on user group - volunteers.  
Blockers: None
Availability: 6-7 hours
ETA: Going to transcribe the interview and thematically code it on Miro in the coming week

Resources:
https://drive.google.com/drive/folders/13pkSi9Irsklume_osxpiYvAtwZqhxh6K
https://github.com/hackforla/website/wiki/Volunteer-Research-Org#current-status
https://docs.google.com/presentation/d/1bueC40PkklLSJVPttiFeYJvcB69PgJx8pxZK5G7gzzo/edit#slide=id.g10c55e2c17c_0_30
https://github.com/hackforla/internship/wiki/Meetings-Summer-2022-for-Software-Engineers
https://docs.google.com/document/d/1Cy5VtGukJDCi0UMSjgIC5EFH54U3ssIeq_elayOhChc/edit

**Comment by ghost** [comment]
Progress: Transcribing Bonnie's interview this week. 
Blockers: None
Availability: 6-7 hours
ETA: This will be completed before next week. 

Resources:
https://docs.google.com/document/d/1kj8wWrykXJiE5RJk4S-iJNgJXrXm9kocV84QJ0ZcdlI/edit

**Comment by ghost** [comment]
Progress: Transcribing Bonnie's interview this week.
Blockers: Health issue last week derailed of meeting this deadline. 
Availability: 6-7 hours
ETA: This will be completed before next week.

Resources:
https://docs.google.com/document/d/1kj8wWrykXJiE5RJk4S-iJNgJXrXm9kocV84QJ0ZcdlI/edit

**Comment by ExperimentsInHonesty** [comment]
@ShrutiMukherjee I recommend Otter.ai.  We have used it with Research teams on several projects with great success.  If the recording with me is too long to use the free version, let Simone know, so that we can use one of Hack for LA's paid otter accounts to do the transcription.

**Comment by ghost** [comment]
@ExperimentsInHonesty I have the transcript but need access to the Miro board to code and analyze the qualitative data from your interview and previous interviews of volunteers. The free Miro board has reached its plan limit and I am not able to edit any frame to add my data there.

**Comment by ghost** [comment]
Progress: Coding and Analyzing user needs from interviews of volunteers and internal stakeholder interview
Blockers: Need access to Miro to code and analyze data. Current Miro has reached the plan limit and not letting me edit the frames to add all the data there. 
Availability: 6-7 hours
ETA: Will finish depending on when I get access to Miro.

**Comment by sacamp** [comment]
@ShrutiMukherjee we are working on a solution to get you edit access to Miro, this should be resolved by Wednesday

**Comment by ghost** [comment]
@sacamp I have some hours on Friday to work on this issue. Will pick it up then. Thanks.

**Comment by ghost** [comment]
Progress: Coding and Analyzing user needs from interviews of volunteers and internal stakeholder interview
Blockers: Need access to Otter.ai from Hack for L.A. The free version let me transcribe for only 29 mins. The interview is about 60 mins. 
Availability: 6-7 hours
ETA: Will finish this week depending on when I get access.

**Comment by ghost** [comment]
Progress: Working on synthesizing data for user needs from previous volunteer interviews and internal stakeholder interview
Blockers: Can I get access to the User Persona issue because I am working on that simultaneously as well. Will be easier to keep the stuff for that issue separate. 
Availability: 6-7 hours
ETA: Data synthesis on Miro should be available before the end of this week. Linked to new issue now https://github.com/hackforla/website/issues/2662 

Resources:
https://github.com/hackforla/website/wiki/Volunteer-Research-Org
https://drive.google.com/drive/u/0/folders/13pkSi9Irsklume_osxpiYvAtwZqhxh6K 
https://miro.com/app/board/uXjVO8mpdzI=/
https://docs.google.com/document/d/1JhmssH6ecN4Nu8ImyRywJL4AYH-qDgfW9rt1cl-hypU/edit
https://docs.google.com/document/d/11MhdWy-Mco-a7txy9x4cY5O_LRoSdp1AuWdRqaLhReQ/edit
https://docs.google.com/document/d/1fYS8QiFQKLK3wux32N_KmJS1kghS4zAb0_i9a_f2R5A/edit
