### ISSUE TITLE
Broken link in CONTRIBUTING.md

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2591]
### Overview
As a developer, we need to make sure our guide for how to contribute is accurate. For this issue, we will fix a broken link.

### Action Items
- [ ] On line 615 in ```CONTRIBUTING.md``` change 
```
[instructions below](#incorporating-changes-from-upstream)
```
to
```
[instructions below](#27e-working-on-an-issue-5-incorporating-changes-from-upstream)
```

- [ ] Commit and push changes to your branch on your forked repository
- [ ] In CONTRIBUTING.md on your remote branch, check that the link redirects to section [2.7.e Working on an issue (5): Incorporating changes from upstream](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream)

### Resources/Instructions

- Line 615 in CONTRIBUTING.md:
https://github.com/hackforla/website/blob/1b023400064eb805668b3fa5f19ed94b071a486e/CONTRIBUTING.md?plain=1#L615
- Where link should redirect to: [2.7.e Working on an issue (5): Incorporating changes from upstream](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream)

**Comment by frankstepanski** [comment]
Availability for this week:
My estimated ETA for completing this issue: Today

UPDATE
Progress: Have submitted a pull request. Awaiting approval
Blockers: None
Availability: Weeknights (EST) and Sunday
ETA: Completed
Pictures: https://github.com/hackforla/website/pull/2742

**Comment by SAUMILDHANKAR** [comment]
@frankstepanski: Please note the following items:
  - I have mentioned this in your good first issue as well, the issue should remain open until the PR is merged.
  - Request you to pick up only one issue at a time. Please do not pick up your next issue until your previous issue has been merged. This is really important and helps in managing our project board, keeping track of things and so on..
