### ISSUE TITLE
Correct Misspelled Words in Figma

### ISSUE THREAD

**Issue by IsaacDesigns** [hackforla/website#2597]
### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained. In this issue you will audit Figma screens for any misspellings and report them to development to correct them in the Hack for LA site.

### Action Items
   - [x] Identify which Figma plugin for catching spelling errors that you think the team should use and document (in the comments of this issue) why you think this is the best plugin.
   - [x] Use the Current Pages page in Figma and audit the latest designs (in red container)to identify any misspellings. Do this for both desktop and mobile screens.
   - [x] Compare findings to the live Hack for LA site for any misspellings you may have come across in Figma.
   - [x] Correct any misspellings you may come across on the Current Pages page and each individual page within Figma. Record the results in a H4LA Google spreadsheet that development can use to correct them on the website.
   - [x] Add link to Spreadsheet in the resources section below. 
   
Developers
- [ ] Reference this [issue](https://github.com/hackforla/website/issues/2401#issue-1036767586) to create your issue

### Resources/Instructions
[Figma spell check plug in SPELL](https://www.figma.com/community/plugin/754026612866636376/SPELLL---Spell-Checking-for-Figma-%26-FigJam)
[Figma spell check plug in Spellchecker](https://www.figma.com/community/plugin/738839069237725273/Spellchecker)
[Hack for LA site](https://www.hackforla.org)
[Spreadsheet
](https://docs.google.com/spreadsheets/d/1qDD7n9XbogIJgDh6mcgdEJAH1x3FMoPnGYNt3pKhhUk/edit?usp=sharing)

**Comment by tamalatrinh** [comment]
My estimated ETA for completing this issue: 3-6 hrs

**Comment by tamalatrinh** [comment]
Progress: 1/4 of the way through
Blockers: NA
Availability: WED + THU 2 hrs per day
ETA: 3 more hours to completion

**Comment by ExperimentsInHonesty** [comment]
@tamalatrinh please provide a link to the spreadsheet.

**Comment by IsaacDesigns** [comment]
@tamalatrinh this [issue](https://github.com/hackforla/website/issues/2512) will have pages in the Resources/Instructions section that you can't find on the live H4LA site

**Comment by tamalatrinh** [comment]
Update: I tried SPELL, Spellchecker, and CopyDoc test kit. I decided to go with CopyDoc because it was the easiest to use. Corrected the misspellings in Figma. Linked the spreadsheet as well.

**Comment by ExperimentsInHonesty** [comment]
@tamalatrinh Excellent work!! Thank you so much, this is going to be really helpful for the devs 💃
