### ISSUE TITLE
Contact Us form submission not routing to /thank-you page

### ISSUE THREAD

**Issue by saintach** [hackforla/website#26]
I was trying to contact HackforLA via the contact form on the website for the potential volunteering opportunity. Interestingly, my email address was sent to `api.actionnetwork.org`. 

[https://github.com/hackforla/website/blob/master/pages/index.vue#L201](url)

I guess I will just reach out to someone here via opening issue 😃 

Ref for debugging: 
![screen shot 2018-12-20 at 4 13 18 am](https://user-images.githubusercontent.com/553898/50284691-b0932f80-040e-11e9-9adc-bdcbab70d921.png)

**Comment by thekaveman** [comment]
Thanks for this report @saintach. We're moving away from this web infrastructure, to one where ActionNetwork is the main email capture mechanism. So this shouldn't be an issue going forward!
