### ISSUE TITLE
Apply new gradient overlay for Projects pages

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2600]
### Overview
We need to use a new gradient for the hero-image overlay on Project pages so that it looks smooth, visually pleasing and is applied consistently to Project page hero images.

### Action Items
- [x] Identify where the [gradient image file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18173%3A122891) must be placed in the code repository. 
- [x] Make the code changes so that the gradient is applied on all the Project pages.
- [x] Check if the gradient looks good on each of the Project page and provide screenshots of all of them. 
  - [x] If it does not look good on all of them, identify the ones it does not look good on, and bring them to the team meeting to discuss, or address it directly with design.

### Resources/Instructions
- [Project Page Example: 100 Automations](https://www.hackforla.org/projects/100-automations)
- [HfLA figma, design system page, gradient](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24996%3A285234&t=VH2yEoPVb8SMTAOs-0)
- Related issue #2312
- How to export the image from figma
  - Click on Export on the right side and download from there. 
![image](https://user-images.githubusercontent.com/88953806/196586336-fbf11dc3-3d23-4669-a353-55773739285e.png)

<details>
<summary>Depreciated links - please ingore</summary>

- [Figma - Project Description Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11346%3A42)
- Here is the gradient image file: [Final Gradient](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18173%3A122891)
- Location of the gradient in the [Project Description Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/?node-id=7891%3A0) in a box underneath the 'final version' outlined in pink.

</details>

**Comment by blulady** [comment]
Good Morning Hiram, 
We have a volunteer who is interested in working on this issue and it looks like you haven't done any progress reports or updates. I would hate to take this away from you if you've done the work but if you haven't started, we'd like to re-assign this issue. If I don't hear back from you by next week, we'll assume you aren't interested.

**Comment by carolemlago** [comment]
i. Availability: 1-4PM Tue and Wed
ii. ETA: 1PM Thu

**Comment by carolemlago** [comment]
Progress: I haven't been able to progress as much with this issue since due to doubts that haven't been answered
Blockers: I'm not sure if there's a gradient file to use or if I should apply a gradient overlay using CSS. All resources links send me to the same Figma project board.
Availability: Wed 10am-3pm, Thu 5pm-7pm
ETA: Fri 1pm

**Comment by jdingeman** [comment]
@carolemlago from what I understand from the issue, it seems you will need to place the image somewhere in the [assets folder](https://github.com/hackforla/website/tree/gh-pages/assets) and then apply the image to the to the Project page as an overlay. 
The issue doesn't specify what format, so I recommend experimenting with the different image formats.

**Comment by carolemlago** [comment]
@jdingeman Great! One quick question: is there a specific file I need to save and apply? All the resources links redirect me to the figma board so I'm not sure. Thx

**Comment by jdingeman** [comment]
> @jdingeman Great! One quick question: is there a specific file I need to save and apply? All the resources links redirect me to the figma board so I'm not sure. Thx

Click on Export on the right side and download from there. 
![image](https://user-images.githubusercontent.com/88953806/196586336-fbf11dc3-3d23-4669-a353-55773739285e.png)

**Comment by carolemlago** [comment]
> * Project Description Page

@jdingeman Thank you

**Comment by jyaymie** [comment]
Availability: 4 hours each day
ETA: EOD 10/26

**Comment by jyaymie** [comment]
I exported what I think is the gradient image file (Screen Shot 2020-08-23 at 9.13 1.png) on Figma, but the image contains devices:

![Screen Shot 2020-08-23 at 9 13 1](https://user-images.githubusercontent.com/104411072/197456739-7ae56b7d-d80f-4753-94e1-2ac8486b847a.png)

I also noticed that the gradient appears to be going in a diagonal direction as the top right corner is brighter than the top left corner. Based on the last screenshot in the comments section of related issue [#2312](https://github.com/hackforla/website/issues/2312#issuecomment-985045742), it seems the gradient should be going vertically.

I'd like to know if there is a clean version of the gradient image without any devices and with the gradient going in the appropriate direction.

I am working in the `apply-gradient-on-projects-pages-2600` branch on my forked repo.

Any assistance is appreciated. Thank you!

**Comment by jdingeman** [comment]
Hi @jyaymie. I think I see what's going on now. It doesn't look like the gradient file exists on its own fro you to use. I cannot find it on Figma or in the repo. I will talk to Design to see if they have any insight. 

I would say for the time being and you are willing to try it out, try editing the CSS in _project-page.scss to expand the linear gradient to more closely match the Figma prototype. I don't think the step that says to add the image file to the repository makes sense since the image they are referring to doesn't exist.

**Comment by jyaymie** [comment]
> Hi @jyaymie. I think I see what's going on now. It doesn't look like the gradient file exists on its own fro you to use. I cannot find it on Figma or in the repo. I will talk to Design to see if they have any insight.
> 
> I would say for the time being and you are willing to try it out, try editing the CSS in _project-page.scss to expand the linear gradient to more closely match the Figma prototype. I don't think the step that says to add the image file to the repository makes sense since the image they are referring to doesn't exist.

Thanks so much for looking into this, @jdingeman! I'll go the CSS route in the meantime.

**Comment by jyaymie** [comment]
During the dev meeting today (10/25/22), I learned that the gradient image file could not be found. I will go forward with implementing the gradient change via CSS and apply it to both desktop and mobile screens.

**Comment by ExperimentsInHonesty** [comment]
Hi All,

It took me about 5 min to find the gradient image in our Figma.  So it occurs to me that the dev team might need a refresher and possibly some documentation about how to find things if they get moved.

In the meantime, here is the file's new location https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24996%3A285234&t=VH2yEoPVb8SMTAOs-0

Should we make a new issue for this, or reopen this one and clean it up?

**Comment by ExperimentsInHonesty** [comment]
We agreed to reopen the issue.  The dev leads will need to 
1. remove old references to the figma file 
2. add the the new link in the [hfla figma, design system page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24996%3A285234&t=VH2yEoPVb8SMTAOs-0) to resources
3. keep Justin's comment about how to export
4. hide all the other irrelevant comments

**Comment by str-xjua24** [comment]
Availability: Whole week
ETA: End of the week

**Comment by ExperimentsInHonesty** [comment]
@str-xjua24 Checking in on you now that we are back from break, to see if you are still working on this issue.

**Comment by str-xjua24** [comment]
Availability: All afternoons after 5pm except for Tues
ETA: End of the week

**Comment by ExperimentsInHonesty** [comment]
@str-xjua24 Please provide update on this issue or let us know that you want to return it.  Expected amount of time for this issue is 6 hours or less.  We are short of medium size issues right now, so please respond asap so we know if we can give it to someone else.

**Comment by KazushiR** [comment]
Availability: Weekdays
ETA: Flexible

**Comment by KazushiR** [comment]
Progress: had to locate where to place the gradient file. Know how to tackle the issue.
Blockers: no blockers since the developer meeting cleared most of it up.
Availability: weekdays Monday-Friday
ETA: sometime this week.
Pictures (optional): N/A

**Comment by KazushiR** [comment]
Completed the assigned tasks. Need to confirm with Dev leads if the final product looks good as I did need to make changes to the code base.

**Comment by KazushiR** [comment]
Had issues with the scalling of the image. Got the issue resolved. Will make a commit once I go through each of devices to see if it renders perfectly fine.
