### ISSUE TITLE
Need to change "Current Project Team" with "Project Team"

### ISSUE THREAD

**Issue by R-Tomas-Gonzalez** [hackforla/website#2604]
### Overview
When projects are completed, there is no longer a "current project team". Therefore, we need to change the words from "Current Project Team" to "Project Team" on completed projects.

### Action Items
<details>
<summary>Picture Summary of Changes needed</summary>
If the status is completed, the h1 tag should say "Project Team" instead of "Current Project Team"
<img width="917" alt="Screen Shot 2022-01-07 at 1 12 44 PM" src="https://user-images.githubusercontent.com/63771558/148595014-454e55cc-9165-4ba7-b776-bf27d63cd409.png">
</details>

- [x] Find the h1 tag that is attributed to the "Current Project Team" header in the [project template](https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html)
     - [x] Use liquid if statement to check if the status of the project is completed
     - [x] Make sure you're using this methodology: if project status is completed, h1 tag should say "Project Team", else h1 tag should say "Current Project Team"

### Resources/Instructions
*Note: Best way to see all of the completed projects is to search through the completed filtered projects on the project page of HFLA. 

[Completed Projects Page](https://www.hackforla.org/projects/?status=Completed)

Issue Creator - [Tomas Gonzalez - Slack DM](https://hackforla.slack.com/app_redirect?channel=U02DF1PPQUA)

**Comment by ExperimentsInHonesty** [comment]
@R-Tomas-Gonzalez I read the instructions above.  The pages are dynamic.  One should never edit the _sites folder, that is built when the static site generator builds the site and will be overwitten the next time the site is built.

There needs to be an if statement that checks to see what the status is of the project is and if the project is completed, it displays the wording Project Team, else it displays Current Project Team.  That code would be placed in this page in the section where it calls the Project Team:
https://github.com/hackforla/website/blob/701ed9d32a3eadb2c4ff0708a06f01056a3b0f79/_layouts/project.html#L106

Please rewrite this issue

**Comment by SAUMILDHANKAR** [comment]
@Georgema20: This issue needs a rewrite, so I will unassign you and move this issue to new approval column. Please take up another issue from the Prioritized column. Thank you.

**Comment by JessicaLucindaCheng** [comment]
Removed `Ready for Milestone` label as the issue was already in the Prioritized Backlog (before it was moved to the In Progress column) and had a milestone already.
