### ISSUE TITLE
Hide all time contributors - dependent on current project team number

### ISSUE THREAD

**Issue by R-Tomas-Gonzalez** [hackforla/website#2605]
### Overview
If there are less all time contributors than the current project team, hide the div that contains the all time contributors. 

### Action Items
An example of this issue can be found in the [EMS Triage Tracker](https://www.hackforla.org/projects/ems-triage-tracker) page. There are less all time contributors than on the current project team.

- [x] Locate the projects where this issue occurs and their html docs. 
- [x] Locate the JS file `assets/project.js` and the corresponding JavaScript that creates the html elements on line 58.
- [x] Implement an algorithm that counts all of the Current Project Team members and if its less than the All Time Contributors than hide the All Time Contributors and the title

### Resources/Instructions
- https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js - The file where the All Time Contributors gets generated

<details>
<summary>Current H2 Tag for Completed Projects</summary>
<img src="https://user-images.githubusercontent.com/63771558/148591114-fdcd0905-ece2-4ca1-84a0-13bfe2351574.png"/>
</details>

Issue Creator - [Tomas Gonzalez - Slack DM](https://hackforla.slack.com/app_redirect?channel=U02DF1PPQUA)

**Comment by ExperimentsInHonesty** [comment]
@R-Tomas-Gonzalez This page is not a good example of this.  Triage tracker is a good example.  The BOP project has another issue, which is: our page is not connected to the repo properly.  It has the same use case as Work For LA.  We will discuss at next meeting.

**Comment by ExperimentsInHonesty** [comment]
The file website/_data/external/github-data.json is being built by something, and the BOP project is not showing up in it, which is why the BOP project page does not show all time contributors https://www.hackforla.org/projects/brigade-organizers-playbook

**Comment by tamara-snyder** [comment]
Availability: Tuesday and Thursday evening, Friday morning (EST)
Issue completion ETA: Friday, March 4, 2022

**Comment by tamara-snyder** [comment]
Progress: Located the projects where the issue occurs.
Blockers: Not really a blocker, but I need to take some more time to understand how the files work together before changing anything. I'll probably end up with some questions.
Availability: Thursday evening, Tuesday and Friday morning (EST)
ETA: I didn't have as much time as anticipated to work on this this week, so my new ETA will be Friday, March 11.
