### ISSUE TITLE
Wrap resource titles on project page 

### ISSUE THREAD

**Issue by R-Tomas-Gonzalez** [hackforla/website#2606]
### Dependency
 - [ ] ACTIONS ITEMS IN THIS ISSUE WILL BE COMPLETED IN ISSUE #3449. When that issue is approved and moved to the prioritzied backlog, this issue is complete. Remove ready for dev leads label .
### Overview
Currently, the resource cards on the individual projects pages do not follow design patterns, and do not look great when there is more than one row of text. Redesign these cards to fix this problem making sure to follow design standards and the Hack for LA brand style.

### Action Items
- [x] Review "Current styling" and "Option 1" below
- [x] Review design system to see if there are any components, related or not, that might inform next steps
- [x] Define new card options
- [x] Mock up new options and add them as screenshot in the comments.
- [x] Walk through with design team explaining your reasoning and rational behind new designs
- [x] Walk through with product team as well
- [ ] Once new designs are approved add it as a component to the design system or update the current version

<details>
<summary>Developer notes when ready for devs</summary>

- [ ] Locate the html tag that impacts `resource-card` list item in each project page
   - [ ] Find the scss file and add the inline-size and overflow wrap to implement the wanted effect
      - [ ] Note: implement `inline-size: min-content;` and not a particular pixel size
</details>

### Resources/Instructions
<details>
<summary>Current styling</summary>
<img width="897" alt="Screen Shot 2021-12-18 at 9 49 12 PM" src="https://user-images.githubusercontent.com/63771558/146663230-532beb3a-bb6d-409f-b91b-918dcd59a2c8.png">
</details>
<details>

<summary>Option 3</summary>
<img width="897" alt="Screen Shot 2021-12-18 at 9 49 45 PM" src="https://user-images.githubusercontent.com/81049661/182509088-aef2b1b6-c112-4051-8a25-55444295ea91.png">
</details>

- [Mozilla CSS Resource](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text/Wrapping_Text)
- [Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
- [Material Design-cards](https://material.io/components/cards#behavior)

**Comment by ExperimentsInHonesty** [comment]
Having seen the proposed solution, I am going to add this to the design team agenda, because it doesn't look that great now that I see it. I hate my own suggestion

**Comment by R-Tomas-Gonzalez** [comment]
> Having seen the proposed solution, I am going to add this to the design team agenda, because it doesn't look that great now that I see it. I hate my own suggestion

Sounds good. Thank you. Do I need to do anything with this issue?

**Comment by ExperimentsInHonesty** [comment]
@IsaacDesigns Please rewrite issue, keeping Tomas's mockups

**Comment by IsaacDesigns** [comment]
@ExperimentsInHonesty I've rewritten the issue and it looks good to go.

**Comment by jenjen26** [comment]
Progress: initiated issue and reading resources
Blockers: none
ETA: 01/12

**Comment by jenjen26** [comment]
@IsaacDesigns I created three different designs that we can review/critique at our design meeting tomorrow.

![Screenshot 2022-01-12 160002](https://user-images.githubusercontent.com/64928677/149229897-d9a2556c-3ec0-4f2e-aea8-3c7471763259.png)

**Comment by jenjen26** [comment]
@IsaacDesigns I've updated the issue with the changes we discussed: annotations of each option to show the differences and logos/imgs reflective of the current project pages including 2 rows. I scanned through all the project pages and they currently range from 2-7 cards - not sure if this will impact decision making.

[Three small card designs for feedback at Sunday meeting](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18798%3A126490)

Let me know if you need anything clarified - thanks!

**Comment by ExperimentsInHonesty** [comment]
@jenjen26 Use design #3

**Comment by jenjen26** [comment]
Progress: updated design guide with style 3 including measurements, updated content example on style guide
Blockers: how to update CSS on style guide
ETA: 01/31

**Comment by ExperimentsInHonesty** [comment]
@jenjen26 Thank you for this work.  We will make a new issue for development to update the classes to reflect the new design and implement the change

**Comment by IsaacDesigns** [comment]
Thank you @ExperimentsInHonesty I have added an extra step to this issue action items for you to update the design system. Once updated make sure to remove the [3 small card designs](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18798%3A126490) from the design system and put them in their appropriate place.

**Comment by JessicaLucindaCheng** [comment]
@IsaacDesigns
- It looks like this issue isn't quite ready for development. Let Saumil or me know when it is ready. Thanks.
- Also, should this issue be reopened since you moved it to the In progress column?

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty @IsaacDesigns @jenjen26 I know it was decided to go with design 3 at a Sunday meeting but I just checked the font size for the design 3 resource cards and it is 14px, which is too small according to the [note in the Typography section of the Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3689%3A21144) and minimum legible font size is 16px. I think we may need to decide between the other two options, which have 16px font size.

**Comment by jenjen26** [comment]
@ExperimentsInHonesty @JessicaLucindaCheng I was able to bump up the text size to 16 for the [small cards](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4548%3A222) in the design system with no alternate changes to the card. I'll move this to be reviewed.

**Comment by ExperimentsInHonesty** [comment]
@jenjen26 great work. Sorry for the delay in reviewing this.  I am moving it to the dev's attention so that they can make an issue for it.

**Comment by ExperimentsInHonesty** [comment]
We are using option 3 on this figma page [3 small card designs](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18798%3A126490)

Note there is an example of what it is supposed to look like when there are longer and shorter lines and there are details for dev  off to the left side 
![image](https://user-images.githubusercontent.com/37763229/174497230-bca7e219-23f7-4c6e-8270-8c10fe94b740.png)

**Comment by ExperimentsInHonesty** [comment]
- This issues that Kathryn made is the handoff issue completed.  https://github.com/hackforla/website/issues/3449
