### ISSUE TITLE
Edit the link to deleted resource on Wiki

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2619]
### Overview
As a member of the team, we need to ensure the Wiki is an up to date and accurate resource. For this issue, we will remove a link to a deleted resource on our Wiki page. 

### Action Items

- [x] Strikethrough the link for "Developers' Guide to Using Figma" on the Home page of the Wiki by placing the link within ~ and add "File seems to be deleted" after that as shown below:
`- ~[Developers' Guide to Using Figma](https://docs.google.com/document/d/1Is5Ah0tUH07kWYG_J6HTo0RF8Z9Foi2l)~ File seems to be deleted`
- [x] In the "Edit message" text box, write what changes you made
- [x] Click the Save Page button
- [x] Ask a technical lead on the team to approve the changes you made by @mentioning them in a comment below
    - [x] Include a summary of what you did
    - [x] Include a link to the Wiki page you made changes to 

### Resources/Instructions
- [Hack for LA's Website's Wiki](https://github.com/hackforla/website/wiki)

**Comment by SAUMILDHANKAR** [comment]
@JessicaLucindaCheng Let's bring this up in the Sunday meeting just to make sure the file hasn't been moved to some other location. If so we can update the link.

**Comment by ExperimentsInHonesty** [comment]
This link has not been moved to another location, someone has accidentally deleted it and we can't get it back.

**Comment by pattshreds** [comment]
@SAUMILDHANKAR  @JessicaLucindaCheng Finished this issue. Added strikethrough to "Developers' Guide to Using Figma", and added "File seems to be deleted" after the link.

[Link to the Wiki Homepage](https://github.com/hackforla/website/wiki)

**Comment by JessicaLucindaCheng** [comment]
- Availability: 6 hours
- Review ETA: Monday, January 24, 2022

**Comment by JessicaLucindaCheng** [comment]
@pattshreds Looks good to me. Thanks for working on this issue! Feel free to start working on another issue.
