### ISSUE TITLE
GitHub Actions: Add a comment to be posted with 2 weeks inactive label

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2625]
### Overview
As a developer, we have to ensure that our kanban board is organized for all teams so that productivity is high. For this issue, we want a comment to be posted whenever 2 weeks inactive label is added to an issue.

### Details
Currently, we are posting the same comment with both the `To update !` label and `2 weeks inactive` label even though there should be separate comments for each. For this issue, we want a separate comment to be posted whenever a `2 weeks inactive` label is added to an issue. You can use the format similar to this [comment](https://github.com/hackforla/website/issues/2625#issuecomment-1092536660):
<details>
  <summary>Click here to see the screenshot of the comment</summary>
  <img width="674" alt="Screenshot 2023-02-06 173227" src="https://user-images.githubusercontent.com/31293603/217125632-b81ff00f-0948-401c-b911-39e58e360c21.png">
</details>

  However, it should be customized for the `2 weeks inactive` label, such as changing where it says `To Update !` to `2 weeks inactive` in the line: "Afterwards, remove the 'To Update !' label and add the 'Status: Updated' label."

### Action Items
- [x] Review add-label.js file as well as update-instructions-template.md file located at (https://github.com/hackforla/website/tree/gh-pages/github-actions/add-update-label-weekly)
- [x]  Add a condition which checks for the type of label being added (to update or 2 weeks inactive) and post the comment accordingly.

### Pseudo-code
- When a 2 weeks inactive label is added to an issue
    - [x] A comment should be posted similar to the one for to update label, except it should mention 2 weeks inactive label.

### Checks
- [x] Test in your local environment that it works
- [x] If a to update label is added to an issue, it should be accompanied with a comment for `to update label!`
- [x] If a 2 weeks inactive label is added to an issue, it should be accompanied with a comment for `2 weeks inactive label!`

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)

**Comment by ExperimentsInHonesty** [comment]
I have moved this to the top of the Prioritized backlog because of the time savings and volunteer management value

**Comment by scarter31191** [comment]
Availability:  4/1 - 4/4 
ETA:  4/4

**Comment by scarter31191** [comment]
Progress: Haven't Started The issue yet due to interviews, but now my time is cleared.
Blockers: None
Availability:  3hrs per day
ETA:  4/11
Pictures: No visual changes

**Comment by scarter31191** [comment]
@JessicaLucindaCheng For this issue do we want the same comment to be used like 'Status: Updated'. But instead replace 'Status: Updated' with 2 weeks inactive?

**Comment by SAUMILDHANKAR** [comment]
@scarter31191 For this issue we want a comment to be posted whenever a 2 weeks inactive label is added to an issue. You can use the format similar to this [comment](https://github.com/hackforla/website/issues/2625#issuecomment-1092536660) but it should be customized for the 2 weeks inactive label. Currently, we are posting same comment with both "To update" label and "2 weeks inactive" label even though there should be separate comments for each. Hope my explanation helps and sorry should have made the issue more descriptive. Please let me know if you have more questions. Thank you.

**Comment by JessicaLucindaCheng** [comment]
@scarter31191 I see there is still a "Status: Help Wanted" label. Did you still need help or have other questions?

Edit: Also, I sent a Slack message about it on May 4, 2022.

**Comment by Sparky-code** [comment]
Good Morning @scarter31191 Checking in on the status of this issue and if the "Status: Help Wanted" label was still relevant. Please include a comment with your availability and ETA in your reply, Thanks!

**Comment by Sparky-code** [comment]
@scarter31191 Checking in to see how your availability is and if you are still working on this issue or if I should unassign you. If you can please add an update to your availability and ETA if you are still working on this issue. Thanks!

**Comment by scarter31191** [comment]
@Sparky-code 

Availability: 1hrs per day
ETA: 6/27
Blockers: The issue seems a bit complex for my understanding, some files seem like they need to be changed or added, I would like to go over my thought process with someone more senior.

**Comment by Sparky-code** [comment]
Hey @scarter31191 Thanks for getting back to me! 
That's understandable, I don't have experience with GitHub actions but I want to say @usaboo does? 
I would say that posting to the #general or #hfla-site channel in slack would be a good way to shout out to those who may have more experience. If nothing else, we can talk it out at Thursday office hours or Sundays all hands.

**Comment by usaboo** [comment]
Hi @scarter31191 , sorry for the late response. I am pretty experienced with Github actions at this point. Would you want to set up a meeting with me at some point this week so that we could go over your issue? 
You could also DM me on Slack!

**Comment by jdingeman** [comment]
Moving this issue back into prioritized backlog. Issue has not been worked on since June 2022.

**Comment by maryjng** [comment]
Availability: Weekdays 10 PM - 11 PM EST
ETA: 2/3

**Comment by maryjng** [comment]
Progress: Unfortunately, not much. Tried working with cloned repositories and nektos/act to figure out testing and how GHA works.
Blockers: First time working with GHA, nektos/act, and the HFLA GHA codebase. Need to figure out how to test GHA.
Availability: Probably 30 mins to an hour a day.
ETA: I hope to get testing working by this coming week.

**Comment by chrismenke45** [comment]
Availability: 2/14 1-5pm, 2/15 10-1pm, 2/16 1-5pm, 2/17 10-1pm
ETA: Aiming for 2/17 at 12pm.

**Comment by chrismenke45** [comment]
Update: 
-Completed on my branch "2weeks-inactive-comment-2625" (in my forked repo). 
-Tested by breaking up code into smaller bits on my local machine
-Need to check with leadership if this testing is acceptable before creating PR
