### ISSUE TITLE
Project hero image missing alt attribute

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2627]
### Prerequisite
Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, we need to make sure the site follows Web Content Accessibility Guidelines (WCAG). For this issue, we will add `alt=""` attribute to the hero image on the Projects page. Without an alt attribute, some screen readers will read the name of the file instead according to [W3C](https://www.w3.org/WAI/tutorials/images/decorative/).

### Action Items
- [x] On [line 20 of pages/projects-page.html](https://github.com/hackforla/website/blob/d3b10fadfefa646ade8bdd5e3de6b89fa1ad466b/pages/projects-page.html#L20), add `alt=""` to 
```
<img src="/assets/images/projects-page/projects-hero.svg">
```
so the result is
```
<img src="/assets/images/projects-page/projects-hero.svg" alt="">
```

### Resources/Instructions
- [Projects page](https://www.hackforla.org/projects/)
- [Line 20 of pages/projects-page.html](https://github.com/hackforla/website/blob/d3b10fadfefa646ade8bdd5e3de6b89fa1ad466b/pages/projects-page.html#L20)
- [Information about alt text for decorative images](https://www.w3.org/WAI/tutorials/images/decorative/)

**Comment by Architsharma7** [comment]
Hey , if no one is working on this, can i do?

**Comment by pattshreds** [comment]
**Availability for this week:** 1.17.2022 all day.
**My estimated ETA for completing this issue:** Within the next hour.
