### ISSUE TITLE
DRAFT: Identify and fix inconsistent code indentation in a SCSS file

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2628]
### Overview
As a developer, we need to make sure the code is easy to read. In this issue, we will identify and fix inconsistent indentation in [_getting-started-page.scss](https://github.com/hackforla/website/blob/d3b10fadfefa646ade8bdd5e3de6b89fa1ad466b/_sass/components/_getting-started-page.scss) using [Lint SCSS](https://github.com/hackforla/website/blob/78ddb139237e60fe91582c8bca706455dcf45be7/.github/workflows/lint-scss.yml)

### Action Items
- [ ] Review [Lint SCSS](https://github.com/hackforla/website/blob/78ddb139237e60fe91582c8bca706455dcf45be7/.github/workflows/lint-scss.yml) and [Stylelint json file](https://github.com/hackforla/website/blob/gh-pages/.stylelintrc.json)
- [ ] Make the necessary code changes and run the GitHub action to identify indentation errors in your own repo
- [ ] Create a pull request with the right indentations in [_getting-started-page.scss](https://github.com/hackforla/website/blob/d3b10fadfefa646ade8bdd5e3de6b89fa1ad466b/_sass/components/_getting-started-page.scss) as well as the code changes to identify inconsistent indentation
- [ ] Make sure the changes don't break the existing flow for other issues, such as submitting PR, merging a PR etc.

### Checks
- [ ] Make sure lines with inconsistent indentation are identified while working in your own repo:
- Lines [172](https://github.com/hackforla/website/blob/d3b10fadfefa646ade8bdd5e3de6b89fa1ad466b/_sass/components/_getting-started-page.scss#L172) to 199
- Lines [285](https://github.com/hackforla/website/blob/d3b10fadfefa646ade8bdd5e3de6b89fa1ad466b/_sass/components/_getting-started-page.scss#L285) to 297

### Resources/Instructions
- [_getting-started-page.scss](https://github.com/hackforla/website/blob/d3b10fadfefa646ade8bdd5e3de6b89fa1ad466b/_sass/components/_getting-started-page.scss)
- [.github/workflows/lint-scss.yml](https://github.com/hackforla/website/blob/78ddb139237e60fe91582c8bca706455dcf45be7/.github/workflows/lint-scss.yml)
- [github/super-linter README](https://github.com/github/super-linter)
- Related PR: #1957
- A list of the stylelint rules can be found [here](https://stylelint.io/user-guide/rules/list/).

**Comment by JessicaLucindaCheng** [comment]
Going to discuss this issue write up with @SAUMILDHANKAR during meeting time.

**Comment by SAUMILDHANKAR** [comment]
@JessicaLucindaCheng Added an action item to ensure the changes don't break the existing flow.

**Comment by JessicaLucindaCheng** [comment]
@SAUMILDHANKAR Should this be labeled with "Dependency"? I think this issue https://github.com/hackforla/website/issues/2651 you are drafting needs to be done first, which is installing linters locally. Then, running all the code through it locally to fix all the issues including this one. Then we could configure the linters for the repo and test out how it behaves on the repo. What do you think?

**Comment by SAUMILDHANKAR** [comment]
> @SAUMILDHANKAR Should this be labeled with "Dependency"? I think this issue #2651 you are drafting needs to be done first, which is installing linters locally. Then, running all the code through it locally to fix all the issues including this one. Then we could configure the linters for the repo and test out how it behaves on the repo. What do you think?

This could be done independently of #2651, so wanted to keep it separate. 

Also, closing this issue as #2695 will be used to fix this (so that anyone can reach out to the author in case there are more questions)

**Comment by ExperimentsInHonesty** [comment]
test

**Comment by ExperimentsInHonesty** [comment]
@SAUMILDHANKAR
