### ISSUE TITLE
jQuery needs to be placed alphabetically in the Technologies filter on the Projects page

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2629]
### Overview
As a developer, we should make sure the website is intuitive to use. In this issue, we will fix jQuery being placed last on the Technologies filter on the Projects page.

<details>

<summary>Current Technologies filter</summary>

![technologies-filter-jQuery](https://user-images.githubusercontent.com/31293603/147403546-a771536b-a0cf-4472-8ce9-7b1755a97a54.jpg)

</details>

### Action Items
- [ ] Fix the Technologies filter to display jQuery and the rest of the technologies in alphabetical order

### Resources/Instructions
- [Projects page](https://www.hackforla.org/projects/)
- [pages/projects-page.html](https://github.com/hackforla/website/blob/d3b10fadfefa646ade8bdd5e3de6b89fa1ad466b/pages/projects-page.html) 
- [assets/js/current-projects.js](https://github.com/hackforla/website/blob/d3b10fadfefa646ade8bdd5e3de6b89fa1ad466b/assets/js/current-projects.js)

**Comment by SAUMILDHANKAR** [comment]
@ExperimentsInHonesty I see the milestone has already been added, but was not sure if the issue should just be added to the prioritized backlog or sorted as well. So, I am leaving the ready for milestone label on and will bring it up in future discussion. This applies to #2627 as well.
