### ISSUE TITLE
Revise Program Area on Open Community Survey Project Details

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2631]
### Overview
We need to revise the program area information to the Open Community Survey project so that it will show up correctly in the program area filter and the citizen engagement page

### Action Items
- [x] Review the project.md file model in the Resources section
- [x] Revise the following text on `_projects/open-community-survey.md` 

from
```
program-area:  
 - Vote / Representation
```
to
```
program-area:  
- Citizen Engagement

```

### Resources/Instructions
File location to make the change: _projects/open-community-survey.md

URL for UAT to check the page has been changed: https://github.com/hackforla/website/blob/gh-pages/_projects/open-community-survey.md

[Model for project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)

- Link to [Projects page](https://www.hackforla.org/projects/). See "Open Community Survey" card, look under the field "Program Areas" to see changes.

**Comment by tamara-snyder** [comment]
Availability for this week: Weekday evenings except Wednesday (EST)
My estimated ETA for completing this issue: By Sunday, but probably earlier

**Comment by tamara-snyder** [comment]
**UPDATE**
Progress: Have submitted a pull request. Awaiting approval
Blockers: None
Availability: Weeknights (EST) and Sunday
ETA: Upon PR approval
Pictures: https://github.com/hackforla/website/pull/2700
