### ISSUE TITLE
Bug on code of conduct

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2632]
### Overview
This is a bug that I have found.

When I was searching through Google for our code of conduct, it gave me a link to an incomplete page. Please look at the resources for more information.

Note: Might overlap with #110. I'm not sure 😔 

### Action Items
- [ ] Explore ways to keep [Broken code of conduct page](https://www.hackforla.org/CODEOFCONDUCT.html) from displaying when the site is googled.
    - [x] Try the following possible approach: Jekyll's [configuration ](http://jekyllrb.com/docs/configuration/options/)accepts file exclusions, which prevents the file from being considered when site is built.
- [ ] Make sure the fix/changes do not affect other parts of the website.

### Resources/Instructions
<details>
<summary>Google search</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/147436136-19d1d77c-70f8-45bf-8f0c-35e1c4d65acc.png" width="600" length="300" />
<br>
</details>

[Broken code of conduct page](https://www.hackforla.org/CODEOFCONDUCT.html)
- Please read through the commens for additional information and links

**Comment by ExperimentsInHonesty** [comment]
I realized why this page is in our main dir: https://github.com/hackforla/website/blob/gh-pages/CODEOFCONDUCT.md  Its part of GitHub's health files https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

So the question is how do we keep it from displaying when the site is googled.

**Comment by Aveline-art** [comment]
@ExperimentsInHonesty Jekyll's [configuration ](http://jekyllrb.com/docs/configuration/options/)accepts file exclusions, which prevents the file from being considered when site is built. Not sure if this works, but worth a shot?

**Comment by michaelmagen** [comment]
Availability: 4 hours
ETA: 10/16/22

**Comment by blulady** [comment]
Hi @michaelmagen,
So we went ahead last night and made the edit you suggested. 
Unfortunately now google search links directly to the CODEOFCONDUCT.md instead of the html.
We're going to role it back but  @jdingeman recommended looking at 
https://github.com/jbranchaud/til/blob/master/html/prevent-search-engines-from-indexing-a-page.md

**Comment by michaelmagen** [comment]
Progress: Need to check with others about testing of new approach
Blockers: Initial approach did not work, attempting new approach to solve problem 
Availability: 4 hours
ETA: 10/25/22

**Comment by blulady** [comment]
> Progress: Need to check with others about testing of new approach Blockers: Initial approach did not work, attempting new approach to solve problem Availability: 4 hours ETA: 10/25/22

Thanks for updating. I'll remove the two-weeks inactive label but feel free to do it yourself.
