### ISSUE TITLE
Update link to the communities of practice yml file template in our Wiki's Sidebar

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2639]
### Overview
As a developer on the team, we need to ensure the Wiki is an up to date and accurate resource. For this issue, we will update the link [Communities of practice yml file template](https://github.com/hackforla/website/wiki/Communities-of-practice-yml-file-template) in our Wiki's Sidebar. 

### Action Items
- [x] Change the link in our Wiki's Sidebar from
```
+ **[Communities.md file template](communities.md-file-template)**
```
to
```
+ **[Communities of practice yml file template](Communities-of-practice-yml-file-template)**
```
  - [x] In the "Edit message" text box, write what changes you made
  - [x] Click the Save Page button
- [x] Ask one of the technical leads on the team to approve the changes you made by @mentioning them in a comment below
    - [x] Include a summary of what you did
    - [x] Include a link to the Wiki page you made changes to  

### Resources/Instructions
- [Wiki for Hack for LA's website](https://github.com/hackforla/website/wiki)
- [Communities of practice yml file template](https://github.com/hackforla/website/wiki/Communities-of-practice-yml-file-template)

**Comment by 1anya1** [comment]
Availability for this week: 10 hours (Tues-Fri)
My estimated ETA for completing this issue: February 24, 2022

**Comment by 1anya1** [comment]
@JessicaLucindaCheng I updated the link to the communities in the Wiki Sidebar here is the link https://github.com/hackforla/website/wiki . The change can be found under "File Template Link".
<img width="392" alt="Screen Shot 2022-02-24 at 3 37 17 PM" src="https://user-images.githubusercontent.com/52765927/155625482-a9b371ab-30d1-404e-b331-ff5c603b4ef6.png">

Please let me know if there is someone else I should reach out to.

**Comment by JessicaLucindaCheng** [comment]
@1anya1 Thanks for working on this issue! I see the changes you made for the Communities of practice yml file template link. However, I compared the changes to the previous version and the link for the `Credit.yml file template` is missing now. See the comparison here: 
https://github.com/hackforla/website/wiki/_Sidebar/_compare/b28cb07156f354b464abcaad37babc45db887404...0ade5b5ba306b31da12410296594c73ef51579ab

- [x] Please fix this and add the `Credit.yml file template` link back.
- [x] When you are ready, please @ mention me again to review the changes.

**Comment by 1anya1** [comment]
@JessicaLucindaCheng Sorry about that. I have added Credit.yml link back to wiki. Here is the link https://github.com/hackforla/website/wiki/_Sidebar/_compare/b75c2a8efb31ea7c0c9aae22121e1005fe27c904

**Comment by JessicaLucindaCheng** [comment]
@1anya1 Thanks for making the changes. I see all the links now. Feel free to pick up a small issue to work on now.
