### ISSUE TITLE
GitHub Actions: Bot adding and removing the same label

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2650]
### Overview
As a developer, we have to ensure that our kanban board is organized for all teams so that productivity is high. For this issue, we want to know why the GitHub action bot is adding and removing the same label and change the code logic so it doesn't do that.

### Action Items
- [x] Please go through the wiki article on [Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
- [x] Review the [set-pr-label.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-pr/set-pr-labels.js) file, to understand how labels are applied on the PR
- [x] Understand why the comment adds and removes the same label. Helpful links from PR #2621: [Link1](https://github.com/hackforla/website/runs/4611929579?check_suite_focus=true), [Link2](https://github.com/hackforla/website/runs/4611935048?check_suite_focus=true)
- [x] Change the code logic to fix this error
- [x] Make sure all labels still get added correctly

### Checks

- [x] Test in your local environment that it works
- [x] Only correct labels should be mentioned in the GitHub bot comment

### Resources/Instructions
<details>
  <summary>Screenshot of pr #2621 showing github-actions adding and removing labels "role: back end/devOps" and "Size: Large"</summary>
  <img width="475" alt="pr-2621-GHA-adding-removing-backend-large-labels" src="https://user-images.githubusercontent.com/31293603/149262548-5670f408-19a9-4440-ba65-2b608e7f2805.png">
</details>

Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)

#### Architecture Notes

The idea behind the refactor is to organize our GitHub Actions so that developers can easily maintain and understand them. Currently, we want our GitHub Actions to be structured like so based on this [proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015):

- Schedules (military time)
        - Schedule Friday 0700
        - Schedule Thursday 1100
        - Schedule Daily 1100
- Linters
        - Lint SCSS
- PR Trigger
        - Add Linked Issue Labels to Pull Request
        - Add Pull Request Instructions
- Issue Trigger
        - Add Missing Labels To Issues
- WR - PR Trigger
        - WR Add Linked Issue Labels to Pull Request
        - WR Add Pull Request Instructions
- WR - Issue Trigger

Actions with the same triggers (excluding linters, which will be their own category) will live in the same github action file. Scheduled actions will live in the same file if they trigger on the same schedule (i.e. all files that trigger everyday at 11am will live in one file, while files that trigger on Friday at 7am will be on a separate file).

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by Zak234** [comment]
I checked the pull request and I don't think this is a code issue. The person accidentally wrote the wrong issue number whose labels were pulled for the pull request and then changed it to the correct one which led to the GitHub action removing some of the previous labels while keeping the others as the two issues shared some labels in common.

**Comment by SAUMILDHANKAR** [comment]
@Zak234 Thanks for adding your analysis for this issue. Looks like your observation is correct for the case mentioned in the issue description above however, there are a few more cases where the labels are getting added unexpectedly and sorry, I did not add them to the issue earlier.  Please notice that the GitHub action bot adds and removes the same label in:

- #2462 on Dec 9
- #2497 on Dec 2 
- #2561 on Jan 20 
- #2397 on Dec 23
- #2317 on Dec 9 

It would be really helpful if these can be analyzed as part of this issue as well by reopening this issue, but if you think a separate issue would be better to resolve it, let me know.

Additionally, GitHub actions bot sometimes removes a label unexpectedly. See the cases below:

- #2676 on Jan 8
- #2397 on Oct 25 

These might not be related but just wanted to add it here in case it is useful. I will reach out to you on slack as well for better reach. Thanks.

**Comment by Zak234** [comment]
I took a look at them and it looks like the first five have an issue
with add-update-label-weekly.yml
while the last two have an issue with issue-trigger.yml. I'll take a closer
look at the files but I also wanted to ask if you had any more recent
examples of the GitHub bot adding and removing update labels as the five
are all from last year and there may have been updates to the action in the
meantime that solved the issue.

**Comment by SAUMILDHANKAR** [comment]
@Zak234 Thanks for getting back. There have been a few updates to the actions that you mentioned above but none of them seems to be directly about fixing this issue. It is possible that any other code change might have fixed this issue, but it would need more analysis. I will check my notes for a more recent example where this has occurred and let you know. Thank you.

**Comment by Zak234** [comment]
Let me know if you can find any more recent examples. I also wanted to make
sure that for the issue where its removing the milestone label that both
you and Adam are part of merge team, right? I'm going to be gone for the
next five days but I'll get back to this when available again.

**Comment by SAUMILDHANKAR** [comment]
@Zak234 I was definitely part of the merge team when the label was removed and as far as I can remember Adam was part of the merge team as well though not 100% sure.

**Comment by Zak234** [comment]
I took a closer look at the issue where it removed the "Ready for
Milestone" label and it looks like the issue is that when the issue trigger
runs that the check-labels.js file doesn't check if the issue creator is
part of the merge team and instead just considers the "Ready for Milestone"
label as an unwanted label all the time and removes it. I can write an
issue for it if you want.

**Comment by Zak234** [comment]
I talked with Bonnie in standup and she told me to go ahead and create the
issue, if thats okay with you?

**Comment by SAUMILDHANKAR** [comment]
@Zak234 Thanks for looking into it. I will let you and the current leads decide on if a new issue should be written for it or if it should be fixed as part of this issue. 

Also, were you able to look into the other issues as well where the GitHub actions bot was adding and removing the status updated label? If these are 2 separate problems, then making a new issue would definitely be a good idea.

**Comment by Zak234** [comment]
I believe that they are 2 separate separate issues. I'll take a closer look
at the status updated issue.

**Comment by Zak234** [comment]
I found some more recent issues with the status updated issue, so it looks
like it was never fixed. I can create a new issue for it but I was also
wondering if the To Update! label is still in use as it was also being
added and removed but I can find only one current issue with the label and
its 2 months old.

**Comment by SAUMILDHANKAR** [comment]
@Zak234 Thanks for looking into this. Sure, feel free to create an issue for that. Unless something came up regarding the To update! label recently, my understanding is that it is still being used. The reason there aren't too many of those labels currently might be because of a bug which would be addressed in the issue: #2634

**Comment by Zak234** [comment]
Okay, thank you!

**Comment by ExperimentsInHonesty** [comment]
The following issues got made
- https://github.com/hackforla/website/issues/3334
- https://github.com/hackforla/website/issues/3341
