### ISSUE TITLE
DRAFT: Pre work checklist bot comments are currently addressed to author, should be addressed to the name in title

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2653]
### Overview
REPLACE THIS TEXT - Clearly state the purpose of this issue in 2 sentences or less

### Action Items
REPLACE THIS TEXT - List the research to be done, or the steps to be completed.
Note: If the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

### Resources/Instructions
REPLACE THIS TEXT - Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc.

**Comment by JessicaLucindaCheng** [comment]
It was decided in [Dev/PM meeting on Jan 15, 2022](https://github.com/hackforla/website/issues/2607#issuecomment-1013550364) that we will not implement this. For pre-work checklists, the author and the assignee should be the same person, which means the assignee should be creating the pre-work issue themselves. Thus I will be closing this draft issue.
