### ISSUE TITLE
Changing text size for Getting Started page

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2656]
### Dependency
- [x] ~https://github.com/hackforla/website/issues/2690~

### Overview
We need to make sure the text sizes for the header section on the Getting Started page is consistent with the rest of the site.

### Action Items
- [x] Review the text sizes of all the project pages.
- [x] Change the text size of Getting Started page by using the SCSS class `paragraph2` for the paragraphs in the header section so it is consistent with other project pages. (See the Paragraphs section under Typography in the [Design System in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3689%3A21144) for how paragraph classes are defined.)
- [x] This issue should also address cleaning up the code in the .header-p class (where it would overlap with the properties in the paragraph2 class). Here is a link to the .header-p class: https://github.com/hackforla/website/blob/8b0d5bffa7c6757340f673e1dad6d10ecd6bc5ec/_sass/components/_getting-started-page.scss#L16-L32
- [x] Make sure the page looks fine for smaller viewport screens as well, such as tablet, mobile (responsiveness)

### Resources/Instructions
- See the Paragraphs section under Typography in the [Design System in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3689%3A21144) for how paragraph classes are defined
- See the [Getting Started page design in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11987%3A91947) in the red box
- Link to [Getting Started page](https://www.hackforla.org/getting-started)
- Link to [Getting Started page SCSS code](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_getting-started-page.scss)
- Link to [Getting Started page HTML code](https://github.com/hackforla/website/blob/8b0d5bffa7c6757340f673e1dad6d10ecd6bc5ec/pages/getting-started.html)

#### Screenshot of the paragraph text size to be changed as per Figma
![Getting started page paragraph font size](https://user-images.githubusercontent.com/843538/148481628-9c894043-cc82-4e5a-bc98-5af1dad7e252.PNG)

**Comment by ExperimentsInHonesty** [comment]
Please change this issue to call the proper class.  @JessicaLucindaCheng  is going to make an issue so this gets put into the icebox until that is complete

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty @SAUMILDHANKAR I added the dependency on https://github.com/hackforla/website/issues/2690 to the issue above.

**Comment by A-BMT02** [comment]
Availability: 1 hour
ETA: in 24 hours

**Comment by A-BMT02** [comment]
I have a blocker

**Comment by A-BMT02** [comment]
I have a blocker 
How do i import the "paragraph2" class to the "getting-started" html page

**Comment by A-BMT02** [comment]
I have a blocker
How do i import the "paragraph2" class to the "getting-started" html page

Do i just give the paragragh to be changed a classname of "paragraph2" or i have to import it from the "_typography.scss"?

**Comment by JessicaLucindaCheng** [comment]
@A-BMT02 You don't need to import the classes because 

> All sass (.scss) files are imported to the main.scss file, which Jekyll processes into a single stylesheet, main.css, which defines all the styles used on the site.

For more info, see [Hack for LA's Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture).

So, you can add paragraph2 as a class to the starting HTML tag. For example, if I wanted to use paragraph2 class for a paragraph, I would do something like the following in the starting tag, `<p class="paragraph2">`.

**Comment by A-BMT02** [comment]
Noted
Thank You!

**Comment by A-BMT02** [comment]
Progress: Done with the checklist and awaiting final review
Blockers: No difficulties
Availability: Whole weekend
ETA: Done and awaiting review
