### ISSUE TITLE
Fixing comment on 2FA Guide Page

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2657]
### Overview
As developers, we need to make sure any comments we make in the code do not show up on the live website and that code comments are easy to understand. For this issue, we will add the end tag `-->` on a comment so it does not show on the bottom of the [2FA Guide page](https://www.hackforla.org/guide-pages/2FA) and we will indent the comment start tag to make it easier to understand the code. 

<details>
  <summary>Screenshot of problem: Comment seen on bottom of 2FA Guide page</summary>
  <img width="960" alt="bottom-of-2fa-page" src="https://user-images.githubusercontent.com/31293603/148589281-c5779fb2-e5b5-4629-8eb7-8421b9c8d6da.png">
</details>

### Action Items
In [_guide-pages/2FA.html](https://github.com/hackforla/website/blob/89661863dcbd5f0b5ebb17792182ac82d382229b/_guide-pages/2FA.html),
- [x] [Line 85-86](https://github.com/hackforla/website/blob/89661863dcbd5f0b5ebb17792182ac82d382229b/_guide-pages/2FA.html#L85-L86) currently looks like this:
  ```
  <!-- Refactor Javascript, moved script to 2FA.js, issue #2068   
      <div class='section-container' style="display: none;">
  ``` 
  Indent the start of the comment on line 85 so that the result is:
    ```
        <!-- Refactor Javascript, moved script to 2FA.js, issue #2068   
        <div class='section-container' style="display: none;">
    ``` 
- [x] [Line 103-104](https://github.com/hackforla/website/blob/89661863dcbd5f0b5ebb17792182ac82d382229b/_guide-pages/2FA.html#L103-L104) currently looks like this:
  ```
      </div>
  </div>
  ```
  Add an indented comment end tag `-->` after line 103 so that the result is:
    ```
        </div>
        -->
    </div>
    ```
- [x] Check that all features on the page still work

### Resources/Instructions
- [2FA Guide page](https://www.hackforla.org/guide-pages/2FA)
- [_guide-pages/2FA.html](https://github.com/hackforla/website/blob/89661863dcbd5f0b5ebb17792182ac82d382229b/_guide-pages/2FA.html)
- https://github.com/hackforla/website/blob/89661863dcbd5f0b5ebb17792182ac82d382229b/_guide-pages/2FA.html#L85-L86
- https://github.com/hackforla/website/blob/89661863dcbd5f0b5ebb17792182ac82d382229b/_guide-pages/2FA.html#L103-L104

**Comment by pattshreds** [comment]
**Availability:** All day today 1.22.2022
**ETA:** Within the next hour

**Comment by JessicaLucindaCheng** [comment]
@pattshreds This isn't ready to be worked on. Please pick an issue from the Prioritized Backlog column. I will be moving this back to the New Issue Approval column and un-assigning you.
