### ISSUE TITLE
Make a sentence easier to understand in CONTRIBUTING.md

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2659]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
As developers, we want to make sure the content in [CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md) makes sense. For this issue, we will be fixing the sentence "What if you don't see any bugs/errors that is not connected to an issue?" to "What if you see bugs/errors that are not connected to an issue?" in two lines of the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md) file.

### Action Items
- [x] On [line 40 in CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md?plain=1#L40), we will change the sentence and its associated link from
```
      - [**2.3.e What if you don't see any bugs/errors that is not connected to an issue?**](#23e-what-if-you-dont-see-any-bugserrors-that-is-not-connected-to-an-issue)
```
to
```
      - [**2.3.e What if you see bugs/errors that are not connected to an issue?**](#23e-what-if-you-see-bugserrors-that-are-not-connected-to-an-issue)
```

- [x] On [line 390 in CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md?plain=1#L390), we will change
```
#### **2.3.e What if you don't see any bugs/errors that is not connected to an issue?**
```
to
```
#### **2.3.e What if you see bugs/errors that are not connected to an issue?**
```

### Resources/Instructions
- [CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md)
- [line 40 in CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md?plain=1#L40)
- [line 390 in CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md?plain=1#L390)

**Comment by Garcia1416** [comment]
Availability for this week: 4 hours
My estimated ETA for completing this issue: 1.5 weeks

**Comment by JessicaLucindaCheng** [comment]
@Gorck1416 It looks like you already are doing issue https://github.com/hackforla/website/issues/2442 and have an open pull request for it. You only need to do one good first issue. I will be unassigning you from this issue.

**Comment by usaboo** [comment]
Availability for this week: Monday, Wednesday --> 7PM EST - 9PM EST
My estimated ETA for completing this issue: --> Thursday(24th February, 22)

**Comment by usaboo** [comment]
Issue PR submitted! Waiting for review!
