### ISSUE TITLE
Update Project Profile: Metro OnTime

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#266]
### Overview
Update the following fields for your project. These updated fields will then be updated to be shown on the website.

### Action Items
Provide in the comments below:
- [x] updated wording if necessary on the project card (see [hackforla.org](https://www.hackforla.org/))
- [x] information on which Tools your team is using for the project (Ex: figma, Balsamiq, photoshop, etc.) . This is different than programming languages
- [x] updates for "Looking For" Section
- [x] any updated links that are not currently displayed on the site (do you have a demo site?)
- [x] Hero image to be displayed on Project Home Page at 1500 x 700 px
- [x] any resources for a Getting Started link (either a link to a wiki or readme)

### Resources/Instructions
See the hero image on the [hackforla.org](https://www.hackforla.org/) homepage

**Comment by ExperimentsInHonesty** [comment]
@sent to Cam via team slack channel on Sunday 1/26/20 11:38am

**Comment by ctsexton** [comment]
@harishlingam @ExperimentsInHonesty 

## Project card image
I don't have a "hero" style image unfortunately, but we are using this as our logo currently. It would be good to update that on the project card on hackforla.org.
![logo_network](https://user-images.githubusercontent.com/32211826/73143320-8a968080-404d-11ea-8267-43989c78471e.png)

## Project card wording
### Railstats LA
Railstats LA tracks LA Metro trains and generates punctuality reports. Our website enables both Metro officials and the public to easily review up-to-date statistics for LA's 6 train lines.

**Links:** [Railstats LA](https://la.railstats.org/), [GitHub](https://github.com/metro-ontime)
**Partner:** [LA Metro](https://metro.net)
**Looking For:** Application Developers (Javascript, Node, React, D3) & Data Engineers (Python, Pandas, GIS)
**Tools:** Docker, AWS, [Observable](https://observablehq.com/@ctsexton/railstats-marey-diagram)
**Location:** Downtown LA

## Getting started
https://github.com/metro-ontime/performance_tracker

**Comment by ExperimentsInHonesty** [comment]
@ctsexton Do you need a ui person to help with a hero image?

**Comment by ctsexton** [comment]
@ExperimentsInHonesty sure, if someone wants to create one we can discuss it on Tuesday

**Comment by ExperimentsInHonesty** [comment]
@ctsexton we have a couple of projects that need help with hero images.  I am still looking for someone to help with that.  In the meantime, which of these do you like better.  I will use one as a placeholder until we get something better.

![Screen Shot 2020-02-16 at 1 18 23 PM](https://user-images.githubusercontent.com/37763229/74612929-d6719e00-50be-11ea-9758-90cd3ad61c55.png)

![metro_rail_line_1500x700](https://user-images.githubusercontent.com/37763229/74613196-294c5500-50c1-11ea-805e-7dd8ea433bc9.png)

**Comment by ashlingam** [comment]
@ctsexton Sent message in Slack

**Comment by ctsexton** [comment]
Let's go with the first one!
