### ISSUE TITLE
Delete the about-us.html file

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2661]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
As developers, we want to keep our codebase up to date. For this issue, we will be removing the [about-us.html](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/_includes/about-us.html) file because it has no lines of code and is not used anywhere on the website.

### Action Items
- [x] In your IDE, locate [about-us.html file](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/_includes/about-us.html) in the `_includes` directory
- [x] Delete the [about-us.html file](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/_includes/about-us.html)

### Resources/Instructions
- [_includes/about-us.html](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/_includes/about-us.html) file

**Comment by Carlos-A-P** [comment]
Availability for this week: 4 hours
My estimated ETA for completing this issue: .5 weeks
