### ISSUE TITLE
GitHub Actions: Review ETA and availability

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2668]
### Overview
Team members reviewing a PR should add their review ETA and availability (in a comment) at the time of assignment so the team is aware of the timeline and the review process becomes more efficient.

### Action Items
- [x] Review the notes below to understand the GitHub actions architecture we are currently moving towards
- [x] Please go through the wiki article on [Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
- [x] Analyze and implement if this should be a new job under any of the GitHub action files mentioned in the Architecture notes below or should be in a separate file based on the following:
    - [ ] This job triggers when any reviewer is added to the PR
    - [ ] The comment should address the reviewers as @reviewerusername 
    - [ ] The comment should request reviewers to add their review ETA and availability
- [ ] Make sure other jobs are not affected by this

### Checks

- [ ] Test in your local environment that it works
- [ ] If a reviewer is added, the comment should be posted in the PR

### Resources/Instructions
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)

#### Architecture Notes

The idea behind the refactor is to organize our GitHub Actions so that developers can easily maintain and understand them. Currently, we want our GitHub Actions to be structured like so based on this [proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015):

- Schedules (military time)
        - Schedule Friday 0700
        - Schedule Thursday 1100
        - Schedule Daily 1100
- Linters
        - Lint SCSS
- PR Trigger
        - Add Linked Issue Labels to Pull Request
        - Add Pull Request Instructions
- Issue Trigger
        - Add Missing Labels To Issues
- WR - PR Trigger
        - WR Add Linked Issue Labels to Pull Request
        - WR Add Pull Request Instructions
- WR - Issue Trigger

Actions with the same triggers (excluding linters, which will be their own category) will live in the same github action file. Scheduled actions will live in the same file if they trigger on the same schedule (i.e. all files that trigger everyday at 11am will live in one file, while files that trigger on Friday at 7am will be on a separate file).

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by lilyarj** [comment]
Availability: 3 hrs
ETA: 7/27?

**Comment by lilyarj** [comment]
ETA: 8/20
Availability: 3hrs

**Comment by arpitapandya** [comment]
ETA: EOD 2022-09-30
Availability: 6hrs

**Comment by arpitapandya** [comment]
Progress: I have added job and `.md files for the message`. I am working on the script.
Blockers: I do not have blockers.
Availability: 10 hrs
ETA: 2022-10-15

**Comment by arpitapandya** [comment]
Progress: Not much progress.
Blockers: I do not have blockers.
Availability: 10 hrs
ETA: 2022-10-25

**Comment by ExperimentsInHonesty** [comment]
@arpitapandya please either provide an update or return this issue to the prioritized backlog

**Comment by arpitapandya** [comment]
> @arpitapandya please either provide an update or return this issue to the prioritized backlog

- Hey @ExperimentsInHonesty sorry, for not leaving feedback. 
- Progress: I have already worked on this issue, I am testing it.
- Once it's tested locally I will submit PR.
- No blockers

**Comment by arpitapandya** [comment]
Un-assigning myself as I am unable to focus until the end of December.
