### ISSUE TITLE
Add svg icon for NoSQL to the website repo and delete non svg icons from Google Drive folder

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2669]
### Overview
We need .svg file of the icon for NoSQL, so that users exploring our projects by technology can get a quick sense of the technologies we use.

### Action Items
- [x] Locate .svg file for the icon of NoSQL. 
  - [x] This can often be found by googling "logo [technology]", for example "logo NoSQL"
- [x] Have a copy of the downloaded .svg inside the directory named "technologies-icons" within [this folder](https://github.com/hackforla/website/tree/gh-pages/assets/images)
  - [x] When choosing an .svg to place in the folder, choose the one that appears on the main page of its website.
- [x] Delete all non svg icons from this [Google Drive folder](https://drive.google.com/drive/folders/1Vq4_CAM0vbJWQLsszne2PeQu5y3r3MeO?usp=sharing)

### Resources/Instructions
[Hack for LA - Projects Page](https://www.hackforla.org/projects/)
[Google Drive folder - Technology icon .svg files](https://drive.google.com/drive/folders/1Vq4_CAM0vbJWQLsszne2PeQu5y3r3MeO?usp=sharing)
[assets/images](https://github.com/hackforla/website/tree/gh-pages/assets/images)
[Related issue](https://github.com/hackforla/website/issues/2130)

**Comment by Pauljsyi** [comment]
ETA: 2 hours
Availability: Friday 5pm

**Comment by SAUMILDHANKAR** [comment]
Unassigning @Pauljsyi due to inactivity. Moving the issue back to Prioritized Backlog column.

**Comment by frankstepanski** [comment]
Availability for this week: Saturday and Sunday afternoon
My estimated ETA for completing this issue: By or before Sunday 1pm EST

**Comment by frankstepanski** [comment]
There already is a nosql.svg in the google drive, can I just use that one? 

Progress: Asked @SAUMILDHANKAR a question on the existing NoSQL.svg file in google drive.
Blockers: Waiting for clarification and then will complete.
ETA: Today

**Comment by JessicaLucindaCheng** [comment]
@frankstepanski Since you are working on this issue, please move it to the In Progress column. Thanks.

**Comment by SAUMILDHANKAR** [comment]
> There already is a nosql.svg in the google drive, can I just use that one?
> 
> Progress: Asked @SAUMILDHANKAR a question on the existing NoSQL.svg file in google drive. Blockers: Waiting for clarification and then will complete. ETA: Today

@frankstepanski Hi Frank, sure, you can use the file that is already in the google drive. Thanks for checking.

**Comment by frankstepanski** [comment]
UPDATE
Progress: Have submitted a pull request. Awaiting approval
Blockers: None
Availability: Monday and Tuesday
ETA: Upon PR approval
Pictures: https://github.com/hackforla/website/pull/3030
