### ISSUE TITLE
Update the section on how to add a pull request to the project board in CONTRIBUTING.md

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2670]
### Dependencies
- [x] https://github.com/hackforla/website/issues/2641
- [x] https://github.com/hackforla/website/issues/2395 

### Overview
As developers, we need to make sure our guide on how to contribute is up to date. In this issue, we will update the section on how to add a new pull request to the Project Board.

### Action Items
- [x] In the section on "How to add your pull request to the project board" in CONTRIBUTING.md, please update the following sentence in the instructions:
```
We are in the process of automating newly created pull requests being added to the Project Board.
```
to 
```
There is an automation for adding newly created pull requests to the Project Board.
```

- [x] Commit and push changes to your branch on your forked repository
- [x] In CONTRIBUTING.md on your remote branch, check that your changes have been made

### Resources/Instructions
- [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [How to add a pull request to the project board](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#v-complete-pull-request-5-how-to-add-a-pull-request-to-the-project-board)

**Comment by JessicaLucindaCheng** [comment]
Once this issue is in the New Issue Approval column, a dev lead needs to review the issue and determine if it is ready for a PM to prioritize it. If it isn't ready, a dev lead will need to edit this issue so that it is ready for a PM to add a milestone and prioritize it.

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng I removed this text, because there does not seem to be a requirement to update the wiki in this issue

> - [ ] NOTE: As of 3/26/23, we are in the process of moving the old wiki to the [website-wiki repo](https://github.com/hackforla/website-wiki). Please see this link for current instructions for adding/updating content in the website-wiki repo.

**Comment by thedvo** [comment]
i. Availability: Tues-Friday after 2pm
ii. ETA: 4/4 or 4/5

**Comment by thedvo** [comment]
@JessicaLucindaCheng Apologies, I wasn't sure from the instructions when checking my changes were made on my remote branch and I thought I needed to merge it onto my own forked repo to see the changes to the markdown file. Should I have just pushed the changes and stopped there?

**Comment by JessicaLucindaCheng** [comment]
@thedvo No, the instructions was just for checking the changes you made to the CONTRIBUTING.md visually. Sorry, the instructions weren't clear. Also, you don't make a pr in your own repo; instead, you should follow the instructions in here: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-3-pull-requests

**Comment by thedvo** [comment]
@JessicaLucindaCheng Okay thank you for the confirmation. I will keep note of that for next time and follow the instructions noted for making a pr. Also to fix my issue, should I revert my merge on my forked repo?

**Comment by JessicaLucindaCheng** [comment]
@thedvo Currently, your fork of gh-pages is ahead, which you don't want because it will mess up future branching. The easiest way to fix this is to re-fork the website repo.
