### ISSUE TITLE
Fix Trophy's link on Credits page leading to a "Page Not Found" on external site

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2674]
### Dependency
- [x] ~#2960~ 

### Overview
As developers, we should make sure links to external web pages exist. For this issue, we will fix where the Trophy link should redirect to.

<details>
  <summary>Screenshot of problem: Trophy link on Credits page</summary>
  <img width="212" alt="credits-trophy-link" src="https://user-images.githubusercontent.com/31293603/150619089-7b84154d-6c73-4ed8-977f-8d1059fbee98.png">
</details>

### Action Items
- [ ] On [line 3 in _data/internal/credits/trophy.yml](https://github.com/hackforla/website/blob/8b0d5bffa7c6757340f673e1dad6d10ecd6bc5ec/_data/internal/credits/trophy.yml#L3), update `title-link` with the correct link: [INSERT LINK HERE]
- [ ] Using Docker locally on your computer, check the Trophy link on the [Credits page](https://www.hackforla.org/credits/) goes to the correct external webpage

### Resources/Instructions
- Where to place the correct link: https://github.com/hackforla/website/blob/8b0d5bffa7c6757340f673e1dad6d10ecd6bc5ec/_data/internal/credits/trophy.yml#L3
- [Credits page](https://www.hackforla.org/credits/)

**Comment by JessicaLucindaCheng** [comment]
I did an initial search for the correct link but could not find the trophy icon nor the artist on [The Noun Project website](https://thenounproject.com/).

**Comment by JessicaLucindaCheng** [comment]
@JessicaLucindaCheng This needs to bring up during Sunday meeting with Design.

**Comment by JessicaLucindaCheng** [comment]
Note to technical lead reviewing this issue for Ready for Milestone:
- This issue still needs a complexity label - either a good second issue or small. This is dependent on if it is just a change to the link or a whole new image is used.
- The content of this issue will need to be updated dependent on the results of issue #2960.
- If it is a whole new image, in addition to updating the credit on the Credits page, the image will need to be updated where ever the trophy image is used on the website, which could be in a separate issue.

**Comment by ExperimentsInHonesty** [comment]
See note [on the https://github.com/hackforla/website/issues/2960](https://github.com/hackforla/website/issues/2960#issuecomment-1086732073)
