### ISSUE TITLE
Draft: Adding scroll bar to the technologies dropdown in mobile version of projects page

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2677]
### Overview
As a developer,
REPLACE THIS TEXT - Clearly state the purpose of this issue in 2 sentences or less

### Action Items
REPLACE THIS TEXT - List the research to be done, or the steps to be completed.
Note: If the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

### Resources/Instructions
* [Related issue](https://github.com/hackforla/website/issues/2069)

**Comment by JessicaLucindaCheng** [comment]
Closing this draft issue because it will be addressed in this issue #2397
