### ISSUE TITLE
Add relevant information to UX research wiki page

### ISSUE THREAD

**Issue by sacamp** [hackforla/website#2680]
### Overview
We need to flesh out the UX research portion of the wiki so that all resources and work are centrally located and easily accessed.

### Action Items

- [x] review the current UXR page on the wiki
- [x] add pages/ links to relevant information to the wiki
- [x] Organize links onto separate pages
- [x] Add summaries and descriptions of completed works

### Resources/Instructions
HfLA website [UX Research wiki page](https://github.com/hackforla/website/wiki/UI-UX-Researcher)

#### Examples:
[TDM calculator wiki example](https://github.com/hackforla/tdm-calculator/wiki/Usability-Testing-Overview)

**Comment by sacamp** [comment]
Added link to relevant documents to the [UI UX Researcher wiki page](https://github.com/hackforla/website/wiki/UI-UX-Researcher)

**Comment by ExperimentsInHonesty** [comment]
Please make seperate pages for each type of research, and add information such as Dates & summary of each link

**Comment by ExperimentsInHonesty** [comment]
Research plan #1
Title: Volunteers
Links: 
- Research Plan
- Scripts
- Interviews
- Analysis/Synthesis
- Presentation of Findings

**Comment by sacamp** [comment]
Progress: I have made separate pages for each type of research. I still need to add descriptions for each project and organize within each subpage.
Blockers: Need to speak with previous UX lead (Danielle) for context on some previous work
Availability: 1-2 hours
Links: https://github.com/hackforla/website/wiki/UI-UX-Researcher

**Comment by sacamp** [comment]
Progress: I am organizing the links according to Bonnie's last comment. While doing this, I am compiling a list of missing documents or information that needs to be added. 
Availability: 1-2 hours

Current notes:
- onboarding research: full body of research, including analysis and presentations, but no research plan
- open roles page: research questions but no research plan

**Comment by sacamp** [comment]
Progress: Pages have been organized. While doing this, I compiled some notes on incomplete projects

Notes:
Research projects initiated, but no data collected:
- member feature page

Research projects with some data collected, but incomplete (no formal research plan)
- HfLA google analytics

Ongoing research projects
- persona research:
   -  corporate donors
   - volunteers
   - advisors

[UX Research Wiki Page](https://github.com/hackforla/website/wiki/UI-UX-Researcher)

**Comment by vaisali89** [comment]
Updated the information with new template
