### ISSUE TITLE
DRAFT: Issues to create by developers

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2681]
Thank you for wanting to help us write an issue! Before writing an issue, please read [How to create issues](https://github.com/hackforla/website/wiki/How-to-create-issues). 

### Instructions
1. Look through the issues that need to be written up below and pick one to create/write up.  If you have questions, please contact the person who wrote it through Slack.
2. In the Issue creator/writer field under the Issue Creation section, put @ and your Github Handle and click the "Update comment" button. For example,
`Issue creator: @JessicaLucindaCheng`
3. Add your Availability and ETA for writing this issue. 
4. Follow the instructions for [How to create issues](https://github.com/hackforla/website/wiki/How-to-create-issues)
  4.a. Add a points label to the issue you created. A point is a time estimation for how long you think it will take to complete an issue. 1 point is equal to 6 hours of work.
5. When you are done writing the issue, fill in the Issue # with the number on the issue you created. For example, 
`Issue #2676`

### Resources
- [How to create issues](https://github.com/hackforla/website/wiki/How-to-create-issues)
- [How to read and interpret labels](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels)
- [How to add a label](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#applying-a-label)

**Comment by JessicaLucindaCheng** [comment]
To Dos for Jessica:
- Add instructions for someone using a template
  - Should add instructions to pre-check if an issue exists before adding it to this list of issues to create.
- Try to make it similar to the one for pms/devs meeting template
- Add instructions for how to add Slack id/link: Example: https://hackforla.slack.com/team/U02NWK24H3N
  -  Should I do it with name? Example: [Jessica Cheng](https://hackforla.slack.com/team/U02NWK24H3N)
- Should I include a field with ETA and Availability for the Issue creator/writer?

TEMPLATE FOR A PROBLEM
```
If you have questions about this problem, contact (Your Slack Name)[https://hackforla.slack.com/team/put-your-member-id-here] through Slack.

### What is the problem? (In one or two sentences.)

### Link(s) to the problem (if any): Link to website pages. For GitHub Action problems, a link to the pull request or issue where the problem was seen. 

### Screenshots of problem
### Slack for person adding issue to be created: https://hackforla.slack.com/team/put-member-id-here
<details>
  <summary>Screenshot(s) of the problem</summary>
  Drag and drop image(s) here
</details>


### Issue Creation (below is for the person creating and writing up the issue formally to fill out)
- Issue creator: @ issue writer's GitHub handle
- Issue #write issue number here
- Availability:
- ETA for writing this issue:
```


______________________________________________________________________________________________________________
TEMPLATE FOR OTHER ISSUES TO BE CREATED
```
If you have questions about this problem, contact (Your Slack Name)[https://hackforla.slack.com/team/put-your-member-id-here] through Slack

### What issue needs to be created? (In one or two sentences.)

### Link(s) (if any):

### Screenshots (if any)
<details>
  <summary>Screenshot(s)</summary>
  Drag and drop image(s) here

</details>


### Issue Creation (below is for the person creating and writing up the issue formally to fill out)
- Issue creator: @ issue writer's GitHub handle
- Issue #write issue number here
- Availability:
- ETA for writing this issue:
```

**Comment by JessicaLucindaCheng** [comment]
If you have questions about this problem, contact [Jessica Cheng](https://hackforla.slack.com/team/U02NWK24H3N) through Slack.

### What is the problem?
In issue #2676 and #2397, GitHub Actions is removing the Ready for Milestone label after a Technical Lead places it on the issue.

### Link(s) (if any): https://github.com/hackforla/website/issues/2676, https://github.com/hackforla/website/issues/2397

### Screenshots of problem:
<details>
  <summary> Screenshot of problem in issue #2676</summary>
    <img width="675" alt="GHA-removing-Ready-for-Milestone-right-after-Tech-Lead-puts-it-on" src="https://user-images.githubusercontent.com/31293603/148704020-df956c90-eab8-4ef4-9de9-af989a897abd.png">
</details>

<details>  
  <summary> Screenshot of problem in issue #2397</summary>
    <img width="452" alt="2397-remove-milestone-label" src="https://user-images.githubusercontent.com/31293603/148878773-a0148ed6-19d2-4fa2-86f1-a558be7c865d.png">
</details>


### Issue Creation (below is for the person creating and writing up the issue formally to fill out)
- Issue creator: @ issue writer's GitHub handle
- Issue #write issue number here
- Availability:
- ETA for writing this issue:

**Comment by JessicaLucindaCheng** [comment]
If you have questions about this problem, contact [Jessica Cheng](https://hackforla.slack.com/team/U02NWK24H3N) through Slack.

### What is the problem?
github-actions adds and removes the "Status: Updated" label in issue #2397 at the same time. Also, github-actions adds and removes the "To Update!" label at the same time in issue #2317. 

### Link(s) to the problem (if any): issue #2397, #2317

### Screenshots of problem
<details>
  <summary>Screenshot(s) of the problem in issue #2397</summary>
  <img width="500" alt="2397-GHA-adding-removing-status-updated-label" src="https://user-images.githubusercontent.com/31293603/149263754-5ecd19d3-b48f-4fad-b65f-2884d2c988e7.png">
</details>

<details>
  <summary>Screenshot(s) of the problem in issue #2317</summary>
  <img width="539" alt="image" src="https://user-images.githubusercontent.com/31293603/149632797-3f015b49-2272-4f5c-bb9d-493e61f68c67.png">
</details>


### Issue Creation (below is for the person creating and writing up the issue to fill out)
- Issue creator: @ issue writer's GitHub handle
- Issue #write issue number here
- Availability:
- ETA for writing this issue:

**Comment by JessicaLucindaCheng** [comment]
If you have questions about this problem, contact [Saumil](https://hackforla.slack.com/team/U02AG2K2BB3) through Slack.

### What issue needs to be created?
Explore linters available for local installation

### Issue Creation (below is for the person creating and writing up the issue to fill out)
- Issue creator/writer: @SAUMILDHANKAR 
- Issue #2651
- Availability:
- ETA for writing this issue:

**Comment by JessicaLucindaCheng** [comment]
Closing this issue because we aren't going to implement this.

**Comment by ExperimentsInHonesty** [comment]
@SAUMILDHANKAR

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng

**Comment by ExperimentsInHonesty** [comment]
test
