### ISSUE TITLE
Move template to correct folder

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#269]
### Overview 
Move template file from website to .github repository

### Action item
Move the template update-project-profile---name-of-project-.md in this folder
https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE
to this folder
https://github.com/hackforla/.github/tree/master/.github/ISSUE_TEMPLATE

**Comment by cnk** [comment]
This can be closed once https://github.com/hackforla/.github/pull/1 is closed. 

I have already closed https://github.com/hackforla/website/pull/279 and verified new issues are now able to see the issue templates from hackforla/.github
