### ISSUE TITLE
DRAFT: Move the "...see more" to the bottom right of the card for each card on the Wins page

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2707]
Bottom right of every card put red “...see more” instead of in the paragraph
- for both mobile and desktop it should be in the same place on every card
- also, make sure paragraph ends at the end of line (currently see more cuts it off)

### Overview
As members of the Hack for LA website team, we want each page to have the best user experience possible. For this issue, we will edit the format of the Wins card on the [Wins page](https://www.hackforla.org/wins/). 

### Action Items
- [ ] 

### Resources/Instructions
- [Wins page](https://www.hackforla.org/wins/).

**Comment by tamara-snyder** [comment]
If I'm not mistaken, I just assigned myself to an existing issue that will accomplish this: [Update the card format for the Wins page for Desktop/Mobile #2339](https://github.com/hackforla/website/issues/2339)

**Comment by JessicaLucindaCheng** [comment]
@tamara-snyder Good catch! Thanks for letting me know!

**Comment by JessicaLucindaCheng** [comment]
Closing this issue because it is already addressed in issue #2339

**Comment by ExperimentsInHonesty** [comment]
test

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng
