### ISSUE TITLE
Update Project Profile: Open Community Survey

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2711]
### Overview
As a product manager of Open Community Survey I want my project's details to be up to date on the HackforLA website

### Project card
Their card URL: https://github.com/hackforla/website/tree/gh-pages/_projects/open-community-survey.md

### Action Items

- [x] Open Community Survey Team Leadership
   - [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [x] leadership
         - [x] Name
         - [x] GitHub hand
         - [x] Role
         - [x] SLACK ID
      - [x] links
         - [x] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
         - [ ] Overview
      - [x] technologies
      - [x] partner
      - [x] tools
      - [x] status

**Comment by ExperimentsInHonesty** [comment]
### Add link
- Overview: https://github.com/hackforla/product-management/blob/master/project-one-sheets/Open-Community-Survey-NC-Websites-One-Sheet.pdf

### Remove the following people
JoAnne Narcisse
Ebele O.
Sonu
Amy Wilkins
Jasmine Kim
Shika Zhou

 
### Add the following people
 Name
 GitHub hand
 Role
 SLACK ID

**Comment by ExperimentsInHonesty** [comment]
one sheet https://github.com/hackforla/product-management/blob/master/project-one-sheets/Open-Community-Survey-One-Sheet.pdf

**Comment by kalyaniraman** [comment]
### Remove the following people
JoAnne Narcisse
Ebele O.
Sonu
Amy Wilkins
Jasmine Kim
Shika Zhou
Kevin 
Bernard

### Add the following people

Name:  Kalyani Raman
GitHub handle: kalyaniraman
Role: PM
SLACK ID: U02QW65RU1M

Name: Mary Kate Leibman
GitHub handle: mkleibman
Role: Researcher
SLACK ID: U031V93CYB0

**Comment by kalyaniraman** [comment]
@ExperimentsInHonesty I have updated the latest list of which team members to remove and who needs to be added to the team overview page.

**Comment by JessicaLucindaCheng** [comment]
@kathrynsilvaconway At the time you self-assign an issue, make sure to write in a comment the following:
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"

Also, please move the issue to the In Progress column.

Also, you only need to do one small issue, which you have already done. If you need to do more than one small issue, such as needing to learn something new before moving on to a related medium issue, please let us know and discuss it with the team leads. In addition, we want to make sure we have enough small issues so that all new developers can work on at least one. For your next issue, please pick up a medium issue. Let me know if you have questions. Thanks.

**Comment by JessicaLucindaCheng** [comment]
@kathrynsilvaconway Not sure if you saw my comment above: https://github.com/hackforla/website/issues/2711#issuecomment-1092355398

**Comment by kathrynsilvaconway** [comment]
@JessicaLucindaCheng Sorry, I actually submitted a PR on this issue last night. There was a typo in my PR, it was linked it to the wrong issue. I just fixed that. I also completely forgot to move the issue to 'in progress.' Dumb little mistakes. I will be more careful going forward.

**Comment by ExperimentsInHonesty** [comment]
@kathrynsilvaconway Sorry for this last min ask... but can you add one more person to the project 

Name: Tugba Metinyurt
GitHub handle: Tugba
Role: Researcher
SLACK ID: U02NF293BRQ
@ExperimentsInHonesty Yes, I will add it tonight and push the changes.

**Comment by SAUMILDHANKAR** [comment]
@ExperimentsInHonesty Just want to confirm if the role of Kalyani Raman is Product Manager or Project Manager. Currently, it is listed as PM above and I understand we generally have Product Managers in various projects but just wanted to make sure. Please let me know.
Also, I noticed while checking the GitHub links, for Tugba, GitHub profile mentions developer whereas above it is listed as researcher, so just want to make sure we have the correct GitHub handle. Thanks.

**Comment by SAUMILDHANKAR** [comment]
@kalyaniraman Hello Kalyani, I need your help on the following points:
- I see your role is listed as PM above but we are not sure if we should go with Product Manager or Project Manager. 
- On the Open community survey project page, under All-time contributors, I see Tugba's GitHub handle as TugbaMet, whereas in a comment above it is just Tugba, So just wanted to confirm that.

I will leave a slack message for you as well so we can get this merged sooner. Thanks.

**Comment by kalyaniraman** [comment]
@SAUMILDHANKAR Hello Saumil, 
- My role is Product Manager
- My apologies, the GitHub Handle is TugbaMet. When i copied over and pasted i must have missed it. Thankyou for checking.

**Comment by SAUMILDHANKAR** [comment]
@kalyaniraman Thanks for letting me know. Will request changes accordingly.

**Comment by kalyaniraman** [comment]
We verified the website and all looks good.
