### ISSUE TITLE
Emails about failed workflow run happening daily

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2712]
### Overview
I am getting emails daily about a failed run (see details below). Please fix this!

### Action Items

- [x] Find out what is happening
- [x] Fix it

### Resources/Instructions
<details>
<summary>Email in question</summary>
<br>
<img src="https://user-images.githubusercontent.com/62368440/150692183-34160fcb-f467-484d-93d2-17adf7ffec50.png" width="600" length="300" />
<br>
</details>

[Link to failed run details for Jan 23, 2022](https://github.com/hackforla/website/actions/runs/1735712547)

Some thoughts as to what might be happening:

- expired token
- bug in code
- GitHub changed their API
- Recent code change disrupted workflows

**Comment by JessicaLucindaCheng** [comment]
@Aveline-art
Thanks for the tips on letting us know what might be happening! I updated the expired token used in the workflow that was failing. Are you still getting emails about the Update GitHub Data workflow failing?

**Comment by Aveline-art** [comment]
I have not been receiving emails for the last couple of days. I am not sure when the token was updated, but I'm happy that it is no longer bothering my inbox! Thank you @JessicaLucindaCheng

**Comment by JessicaLucindaCheng** [comment]
Closed issue because Update GitHub Data workflow no longer failing after updating an expired token.
