### ISSUE TITLE
Update Project Profile: Home Unite Us

### ISSUE THREAD

**Issue by JRHutson** [hackforla/website#2715]
### Overview
As a product manager of Home Unite Us I want my project's details to be up to date on the HackforLA website

### Project card
https://www.hackforla.org/projects/home-unite-us

### Action Items

- [ ] Home Unite Us Team Leadership
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [ ] title
      - [x] description
      - [ ] image
      - [ ] leadership
         - [ ] Name
         - [ ] GitHub hand
         - [ ] Role
         - [ ] SLACK ID
      - [ ] links
         - [ ] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [ ] Site
      - [ ] technologies
      - [x] partner
      - [ ] tools
      - [x] status

**Comment by JRHutson** [comment]
Leadership:
Add the following people

Name: Regan Hutson
Role: Product Management
Slack ID: U0602E4LA
GithHub Handle: JRHutson

Name: Kristy Points
Role: Product Management
Slack ID: U02FMMKPG7M
GitHub Handle: kpoints

Name: Abiha Ali
Role: Product Management
Slack ID: U02RW9T17PY
GitHub Handle: abiha1234

Name: Erik Guntner
Role: Front End Developer
Slack ID: U0103MJB0AZ
GithHub Handle: erikguntner

Name: Rachel Bracker
Role: Design Lead
Slack ID: U02JQLQ6YGY
GithHub Handle: rpbracker

Remove the following person

Name: Abby Hipp

**Comment by JRHutson** [comment]
Modify Description

The Home Unite Us project is developing a workflow management tool for community non-profits to automate and scale their existing Host Home initiatives, prioritizing streamlining of caseworkers' repetitive workloads, reducing institutional bias, and effectively capturing crucial data.

Host Home programs are centered around housing young people, 18 - 25 years old. Their approach focuses on low-cost, community-driven intervention by matching a willing host with a guest or group of guests, providing a stable housing environment for youths who are experiencing homelessness and seeking stable housing.

**Comment by JRHutson** [comment]
Overview link

https://github.com/hackforla/product-management/blob/master/project-one-sheets/Home-Unite-Us-One-Sheet.pdf

**Comment by JRHutson** [comment]
Tool Updates:
Remove: Miro, Teraform, Dynamo DB,

**Comment by JRHutson** [comment]
Meeting Schedule Update:
Move Design Meeting to Tues 7:00-8:00PM every other Tuesday
Update Product Team Meeting to Tues 6:00-7:00 PM every week
Remove Weds Product Meeting

**Comment by ExperimentsInHonesty** [comment]
site: https://homeunite.us/

**Comment by jnmrles** [comment]
Review ETA: 02/24 EOD
Availability: Wed-Sat 12pm-10pm cst

**Comment by JessicaLucindaCheng** [comment]
@jnmrles Please wait until your good second issue is approved and merged before working on this issue. I will be unassigning you from this issue for now. Once your good second issue is approved and merged, you can assign yourself to this issue again if it is still available.

While you are waiting for your pull request to be merged, please review some pull requests. Here is a guide for [How to Review Pull Requests](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests).

**Comment by SAUMILDHANKAR** [comment]
@jnmrles Hope you are doing well. Just wanted to share one of the decisions made during our team meeting. We are now requesting all website team members to attend at least one meeting in a week (Tuesday, Thursday or Sunday) as we strive to replicate a professional working environment within our team amongst other things. Therefore, request you to let us know which of the weekly meetings would be suitable for you based on availability. We have decided to make an exception for this requirement only on a case-by-case basis. I will leave a message for you on slack as well. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@jnmrles Just wanted to follow up regarding your progress on this issue. Please let us know if you have any questions, need help or your availability has changed. I will leave a slack message as well about the same. Thanks.

**Comment by ExperimentsInHonesty** [comment]
@JRHutson please let us know if the changes we made match what you asked for by adding a comment to this issue.
