### ISSUE TITLE
Remove non-existent classes from citizen-engagement-cards.html

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2720]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
As developers, we should make sure our code does not use SCSS classes that do not exist. For this issue, we will remove the non-existent classes `card-body` and `card-width` from a line of code.

### Action Items
- [x] On [line 3 in _includes/citizen-engagement-cards.html](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/_includes/citizen-engagement-cards.html#L3), remove the classes `card-body` and `card-width` from
```
                   <div class="page-card card-primary page-card-lg card-body card-width program-area" data-dropdown>
```
so the result is
```
                   <div class="page-card card-primary page-card-lg program-area" data-dropdown>
```
- [ ] Using Docker locally on your computer, check [Citizen Engagement page](https://www.hackforla.org/citizen-engagement) looks the same as the page on the current site in various desktop, tablet, and mobile views using developer tools

### Resources/Instructions
- [line 3 in _includes/citizen-engagement-cards.html](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/_includes/citizen-engagement-cards.html#L3)
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)

**Comment by ExperimentsInHonesty** [comment]
@A-BMT02 I assume  you didn't mean to assign yourself this good first issue, since you already did one.  [Please look at the prioritized backlog for good second issue](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22+label%3A%22size%3A+good+second+issue%22#column-7198257) 

I am unassigning you from this issue.

**Comment by A-BMT02** [comment]
Sorry for that

**Comment by scarter31191** [comment]
Availability for this week: Friday 3/11, Saturday 3/12, Sunday 3/13
My estimated ETA for completing this issue: Friday 3/11
