### ISSUE TITLE
Remove non-existent classes from citizen-engagement.html

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2721]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
As developers, we should make sure our code does not use SCSS classes that do not exist. For this issue, we will remove the non-existent classes `card-body` and `card-width` from a line of code.

### Action Items
- [x] On [line 41 in pages/citizen-engagement.html](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/pages/citizen-engagement.html#L41), remove the classes `card-body` and `card-width` from
```
            <div class="page-card card-primary page-card-lg card-body card-width organizations">
```
so the result is
```
            <div class="page-card card-primary page-card-lg organizations">
```
- [x] Using Docker locally on your computer, check [Citizen Engagement page](https://www.hackforla.org/citizen-engagement) looks the same as the page on the current site in various desktop, tablet, and mobile views using developer tools

### Resources/Instructions
- [line 41 in pages/citizen-engagement.html](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/pages/citizen-engagement.html#L41)
- [Citizen Engagement page](https://www.hackforla.org/citizen-engagement)

**Comment by mayanknoldus** [comment]
I would like to work on this issue. Could you please assign me this.

**Comment by JessicaLucindaCheng** [comment]
@mayanknoldus Thanks for your interest in working on this issue. However, this issue is not ready to be worked on. Also, to work on any of our issues, you need to join Hack for LA. (There are no fees for joining.) If you are interested in joining, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).

**Comment by JessicaLucindaCheng** [comment]
@A-BMT02 
At the time you self-assign an issue, make sure to write in a comment the following:
- Availability: (how many hours you have to work on the issue this week)
- ETA: (when you think you will finish the issue)

**Comment by A-BMT02** [comment]
Noted , i will next time
