### ISSUE TITLE
Clarify steps in README.md for Code Contributors

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2726]
### Overview
As developers, we want the README.md to have clear steps for people looking to contribute to our codebase. In this issue, we will update the "Contributing" section in the README.md to have clearer steps for code contributors.

### Action Items
- [x] Currently, the [Contributing section in the README.md starting on line 16](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/README.md?plain=1#L16-L19) is
```
## Contributing


Once you have gone through onboarding, go to the [WIKI](https://github.com/hackforla/website/wiki). For developers looking for the standard README, see the [CONTRIBUTING](./CONTRIBUTING.md) document for more details on how to get started. Also see our [Code of Conduct](./CODEOFCONDUCT.md) and [License](./LICENSE.txt) documents.
```
We will change it to
```
## Contributing

We require all Code Contributors to
1. Join our organization by going through [Hack for LA onboarding](https://www.hackforla.org/getting-started).  It's free to join!
2. Read the [onboarding section of our WIKI](https://github.com/hackforla/website/wiki/Joining-the-HackforLA.org-Website-Team).
3. Read our [CONTRIBUTING](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md) document and follow the steps.
```
- [x] Commit and push changes to your branch on your forked repository
- [ ] In README.md on your remote branch, see the changes you made look good

### Resources/Instructions
- [Contributing section in the README.md starting on line 16](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/README.md?plain=1#L16-L19)

**Comment by jnmrles** [comment]
Availability for this week: Wed-Sat 12pm-11pm CST
My estimated ETA for completing this issue: EOD 09/24
