### ISSUE TITLE
Update Project Profile: Civic Tech Index

### ISSUE THREAD

**Issue by kevindphan** [hackforla/website#2728]
### Dependency
[Issue tracking this on Civic Tech Index project board](https://github.com/civictechindex/CTI-website-frontend/issues/1062)

### Overview
As a product manager of Civic Tech Index I want my project's details to be up to date on the HackforLA website

### Project card
[Civic Tech Index Card Link](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-index.md)

### Action Items

- [ ] Civic Tech Index Team Leadership
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [ ] leadership
         - [ ] Name
         - [ ] GitHub hand
         - [ ] Role
         - [ ] SLACK ID
      - [ ] links
         - [ ] Github
         - [ ] Wiki
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [ ] technologies
      - [x] partner
      - [ ] tools
      - [x] status

### Resources/Instructions
- File where changes need to be made [Civic Tech Index Card Link](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-index.md)
- Related issue link to be followed: [CTI project issue](https://github.com/civictechindex/CTI-website-frontend/issues/1062) 
- Link to the CTI project page on our website: [CTI project](https://www.hackforla.org/projects/civic-tech-index)

**Comment by kevindphan** [comment]
**Remove the following people:**

Levi Adissi
Iffath Sultana
Maria Studnicka
Shipra Prakash
Emily Marinaro

**Comment by kevindphan** [comment]
**Add the following people:**

 - name: Sean Sada
    role: Product Manager
    links:
      slack: https://hackforla.slack.com/team/U016XE06ZS5
      github: https://github.com/smsada
    picture: https://avatars.githubusercontent.com/smsada

 - name: Dennis Chatkhan
    role: Frontend Developer
    links:
      slack: https://hackforla.slack.com/team/U01B4S459CZ
      github: https://github.com/mealthebear
    picture: https://avatars.githubusercontent.com/mealthebear

 - name: Nandana Rao
    role: Fullstack Developer
    links:
      slack: https://hackforla.slack.com/team/U013JA9H62E
      github: https://github.com/nrrao
    picture: https://avatars.githubusercontent.com/nrrao

  - name: Briana Bennett
    role: Product Manager
    links:
      slack: 'https://hackforla.slack.com/team/U031BRKV59C'
      github: 'https://github.com/bribenn'
    picture: https://avatars.githubusercontent.com/bribenn
    
  - name: Joyce Kim
    role: UI/UX Designer
    links:
      slack: 'https://hackforla.slack.com/team/U022B355CF2'
      github: 'https://github.com/joycekimdesigns'
    picture: https://avatars.githubusercontent.com/joycekimdesigns
    
  - name: Adaeze Nwaezeigwe
    role: UI/UX Designer
    links:
      slack: 'https://hackforla.slack.com/team/U0336CC3T9B'
      github: 'https://github.com/AdaezeMN'
    picture: https://avatars.githubusercontent.com/AdaezeMN
    
  - name: Ron Fu
    role: Full Stack Developer
    links:
      slack: 'https://hackforla.slack.com/team/UGWDHDF46'
      github: 'https://github.com/rfvisuals'
    picture: https://avatars.githubusercontent.com/rfvisuals
    
  - name: Vance Dubberly
    role: Full Stack Developer
    links:
      slack: 'https://hackforla.slack.com/team/U0336CC3T9B'
      github: 'https://github.com/deserat'
    picture: https://avatars.githubusercontent.com/deserat
    
  - name: Isaiah Ozadhe
    role: Full Stack Developer
    links:
      slack: 'https://hackforla.slack.com/team/U034X04V2H5'
      github: 'https://github.com/Tekkieware'
    picture: https://avatars.githubusercontent.com/Tekkieware

**Comment by kevindphan** [comment]
**Edit Meeting Times:** 

Please remove Wed 12:30-1:00PM Product Manager's meeting

Other meeting times are correct.

**Comment by SAUMILDHANKAR** [comment]
@kevindphan Just wanted to confirm if there are any changes to links, partner, tools and status before adding a milestone on this issue. Please let us know. Thank you.

**Comment by SAUMILDHANKAR** [comment]
~~Add technology as per: https://github.com/civictechindex/CTI-website-frontend/issues/1062#issuecomment-1029588418
Also, left a slack message on Civic Tech Index slack channel requesting updates for this issue.~~
For technology, see the [comment](https://github.com/hackforla/website/issues/2728#issuecomment-1086737209) below.

**Comment by SAUMILDHANKAR** [comment]
@kevindphan Just wanted to follow up regarding any update on this issue. I will leave a slack message as well. Thanks.

**Comment by JessicaLucindaCheng** [comment]
@kevindphan VRMS handles meeting times. You need to submit an issue in the VRMS repo to change meeting times.

> **Edit Meeting Times:**
> 
> Please remove Wed 12:30-1:00PM Product Manager's meeting
> 
> Other meeting times are correct.

**Comment by SAUMILDHANKAR** [comment]
Update: New person would be taking over this issue and get back with updates or changes if required, as suggested by Kevin.

**Comment by ExperimentsInHonesty** [comment]
Technologies: Add AWS

change github to https://github.com/civictechindex/CTI-website-frontend
change wiki to https://github.com/civictechindex/CTI-website-frontend/wiki

add tools: Google docs, Figma, Usability Hub

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng @SAUMILDHANKAR @tamara-snyder It turns out that the team has two repos and unless we scrape both for the languages, the language display will not be accurate.

Here is the one we are scrapping https://github.com/civictechindex/CTI-website-frontend
Here is the one we also need to scrape https://github.com/civictechindex/CTI-website-backend. 

I realize this might require a change to how we get the data.  Let's move the languages part to another ticket.

**Comment by ExperimentsInHonesty** [comment]
See this issue comment for latest team member updates
https://github.com/civictechindex/CTI-website-frontend/issues/1062#issuecomment-1086903518

Updated the above comments with the latest team members as well.

**Comment by RyanCahela** [comment]
Availability: Weekdays, 3-5PM.
ETA: Friday 4/22/22.

**Comment by JessicaLucindaCheng** [comment]
@RyanCahela Since you have already completed a Small issue, please work on a Medium size issue for your next issue.

**Comment by RyanCahela** [comment]
@JessicaLucindaCheng OK, should I unassign myself from this issue?

**Comment by Wny-Duong** [comment]
Availability: 5/7 - 5/8 (6 hours), 5/11 (2 hours)
ETA: Wednesday, 5/11

**Comment by Sparky-code** [comment]
avail: 5/10 - 1hr
ETA: EOD Tuesday 5/10

**Comment by JessicaLucindaCheng** [comment]
- An issue needs to be made for scraping languages for any projects with multiple repos. See this comment for more info: https://github.com/hackforla/website/issues/2728#issuecomment-1086902818

**Comment by ExperimentsInHonesty** [comment]
I don't know if an issue got made for scraping the multiple repos, but it has not yet been mentioned here.  After it's found or remade it should be mentioned here and then this issue moved to QA

**Comment by MattPereira** [comment]
- #3805
