### ISSUE TITLE
Create Support Us page

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#273]
### Overview
Create content for Support Us page that will appeal to large and small donors alike.

#219 contains data showing impact of project teams that can shed meaningful light to financial stakeholders on the importance of giving to HFLA. 

### Dependency
#191 

### Action Items
- [ ] Project Management & HfLA Leadership
   - [ ] Review [Donor-Sponsor solicitation strategy](https://github.com/hackforla/website/projects/3#card-29730182)
   - [ ] Review Donor-Sponsor [user stories](https://github.com/hackforla/website/projects/6#column-7010925)
   - [ ] Write requirements and acceptance criteria for page
      - [ ] A donate link
      - [ ] A Partnership/Sponsors section
- [ ] UI
   - [ ] Create wireframe in Figma
   - [ ] Create prototype in Figma
   - [ ] Get signoff and add Front End dev label
- [ ] Development
   - [ ] Creating page, new menu item (desktop and mobile) and any logic around display.

### Resources/Instructions
https://github.com/hackforla/website/projects/6#column-7010925

**Comment by ExperimentsInHonesty** [comment]
see issue #219 for content

**Comment by alexandrastubbs** [comment]
We have decided not to do this in favor of adding this as a section on the Join Us page about ways to contribute.
