### ISSUE TITLE
Create a Survey: True Intent

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#2733]
### Overview
We  need to create a true intent survey so that we can determine who our users are, what their goals are for accessing the website and if they are able to achieve their goals.

### Action Items
- [X] Create survey questions
- [x]  Review with Product 

### Resources/Instructions
[True Intent Instructions and Survey Questions](https://docs.google.com/document/d/16b-gVZCT9aI9rdkmEz1GT1Kaj8P5sYtGaT5LKZVtglM/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
@JackieRiley1 

I saw this referred to two different ways by members of the Research team
From this survey: What is your ethnicity? (Optional)
Another survey (I don't remember which ) it was racial identity. 

Please find out what best practices are currently and report back, and talk with team lead about how we will capture the best practices in the wiki for future survey reference

We should use a stand federal list as well.  Please site source.

**Comment by ExperimentsInHonesty** [comment]
@JackieRiley1 please indicate size of issue using the points system

**Comment by ExperimentsInHonesty** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by ExperimentsInHonesty** [comment]
@JackieRiley1 Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by JackieRiley1** [comment]
The survey has been updated. Notes addressing comments from the Google Doc have been added at the bottom of the document.

**Comment by ExperimentsInHonesty** [comment]
@JackieRiley1 thank you for the details about consent for under 18.  ~Please add a question to the top of the survey asking yes or no, 18 or over.  If they say no, then the survey is ended.~

I found this, and it might be more applicable.  Please review
https://calschls.org/survey-administration/parental-consent/

**Comment by ExperimentsInHonesty** [comment]
See Code for America's question about gender on their [brigade census survey](http://c4a.me/census)
![image](https://user-images.githubusercontent.com/37763229/156443456-893d0419-3ac5-4304-b116-c4845d767ca0.png)

**Comment by ExperimentsInHonesty** [comment]
@JackieRiley1 Please put your research plan into the format developed on this issue 
https://github.com/hackforla/knowledgebase-content/issues/138

If you have sections that are not in the current template. Please create them in your document and then note it in the guide to making a research plan issue, so that the next person who works on the guide can integrate these additional sections.

**Comment by JackieRiley1** [comment]
I've added some additional comments in response to the [True Intent Survey](https://docs.google.com/document/d/16b-gVZCT9aI9rdkmEz1GT1Kaj8P5sYtGaT5LKZVtglM/edit?usp=sharing)

**Comment by ExperimentsInHonesty** [comment]
@JackieRiley1 I have responded to your comments/questions with same.  Looking forward to next version

**Comment by sacamp** [comment]
Questions have been revised and survey implementation options are being explored in issue #2663
