### ISSUE TITLE
Communities of Practice information updates: Engineering

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#2744]
### Overview
We need to add information on the COP page so it is up to date.

### Action Items
- [x] Please make the following changes (Note: Find and add the complete links for GitHub handle and Slack IDs in the Engineering.yml file):
```
Remove person(s) and info from CoP file?

YES

If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:

Name: [Greg Pawin](https://hackforla.slack.com/team/UUEQF3AJG)

Add person(s) and info to CoP file?

YES

If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Ava Li
Title: Lead
GitHub Handle: Aveline-art
Slack Member ID: https://hackforla.slack.com/team/U01B73XGCKV
```
- [x] Make sure the changes are reflected in your repo

### Resources/Instructions
- Webpage where changes should be reflected: [Hackforla COP page](https://www.hackforla.org/communities-of-practice)
- File where changes need to be made: [Engineering yml file](https://github.com/hackforla/website/blob/b602137a825371cb5ff28917f892f43b030d7c44/_data/internal/communities/engineering.yml)

**Comment by JessicaLucindaCheng** [comment]
@luke-karis At the time you self-assign an issue, please add your initial issue availability (how many hours you have to work on this issue this week) and the ETA (when you expect to complete the issue).

**Comment by luke-karis** [comment]
Belated Availability and ETA:
Sun: 1-2 hours, Monday: 1 hour, Tuesday 30min-1 hour
ETA: Sunday/Monday (Feb 27/28)

**Comment by SAUMILDHANKAR** [comment]
@luke-karis Hope you are doing well. Just wanted to share one of the decisions made during our team meeting. We are now requesting all website team members to attend at least one meeting in a week (Tuesday, Thursday or Sunday) as we strive to replicate a professional working environment within our team amongst other things. Therefore, request you to let us know which of the weekly meetings would be suitable for you based on availability. We have decided to make an exception for this requirement only on a case-by-case basis. I will leave a message for you on slack as well. Thank you.
