### ISSUE TITLE
Update Project Profile: Design systems 

### ISSUE THREAD

**Issue by nasimbiglari** [hackforla/website#2745]
### Overview
As a product manager of Design systems I want my project's details to be up to date on the HackforLA website

### Project card
_insert url of their card here before sending - their cards can be found in this folder: https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md

### Action Items

- [ ] Design systems team Leadership
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [ ] leadership
         - [ ] Name
         - [ ] GitHub handle
         - [ ] Role
         - [ ] SLACK ID
      - [x] links
         - [x] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] technologies
      - [x] partner
      - [ ] tools
      - [x] status
 - [x] Open an issue on VRMS to update the meeting times and provide the link to the new issue in the comment below

### Resources
- https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md

**Comment by nasimbiglari** [comment]
### Tools:
 Figma, Google docs, Zoom, Otter.ai

**Comment by nasimbiglari** [comment]
Meeting times are all correct.

**Comment by allthatyazz** [comment]
### Add  Team members:
Name: Yasaman Roostaeian
Role: Product Manager
Slack ID: U033GFQ1UQM
GitHub Handle: allthatyazz


Name: Wataru Inoue
Role: Lead UX/UI Designer
Slack ID: U02SMT4H4LR
GitHub Handle: winoue90

Name: Tammy Trinh
Role: UX/UI Designer
Slack ID: U02RZRF34DA
GitHub Handle: tamalatrinh

Name: Kelene Lee
Role: Researcher
Slack ID: U02U49VDV2L
GitHub Handle: kelenelee

Name: Dongchen Hou
Role: Researcher
Slack ID: U02QPKCB7UN
GitHub Handle: hdchangie

Name: Eric J Cunningham
Role: Researcher
Slack ID: U02V6PA5NJY
GitHub Handle: cunninghamej


Name: Sandra Berjan
Role: UX Writer
Slack ID: U03753VQBSR
GitHub Handle: sandraberjan

Name: Joyce Chang
Role: Researcher
Slack ID: U02U727NYM9
GitHub Handle: tfeng95725



### People to remove:
Nasim Biglari
Jeanette Renema
Hana Stevenson
Bernard Adesina
Ryan Curtis
Anna Knutson
Anastasia Nekrasova
Anh Hoang

**Comment by allthatyazz** [comment]
@JessicaLucindaCheng Please refer to the most recent comment for the latest members list.

**Comment by JessicaLucindaCheng** [comment]
Note: I'm self-assigning and working on this issue because it has been over a month and still hasn't been completed even though it is time sensitive.

- Availability: 1 hour
- ETA: Today, March 25, 2022

**Comment by JessicaLucindaCheng** [comment]
@allthatyazz Updates have been made to https://www.hackforla.org/projects/design-systems. Leave a comment below to let me know if updates look good to you or if you need additional changes. Thanks.

![updated-design-systems-page](https://user-images.githubusercontent.com/31293603/160218744-35eb4d4c-96f7-481c-b617-802e8d1b40ff.png)

**Comment by JessicaLucindaCheng** [comment]
@allthatyazz Updates have been made to https://www.hackforla.org/projects/design-systems. Leave a comment below to let me know if updates look good to you or if you need additional changes. Thanks.

![updated-design-systems-page](https://user-images.githubusercontent.com/31293603/160218744-35eb4d4c-96f7-481c-b617-802e8d1b40ff.png)
