### ISSUE TITLE
Review status of In-Progress "Update Project Profile cards"

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#275]
### Overview
Review status of In-Progress "Update Project Profile cards"

### Action Items
Review status of In-Progress "Update Project Profile cards". Identify which projects have submitted their information and which have not. Follow up with project leads of those projects with outstanding information and identify/resolve any roadblocks they may have.

### Resources/Instructions
https://github.com/hackforla/website/projects/7#column-7198228

**Comment by ExperimentsInHonesty** [comment]
Transferred Not-Today [issue](https://github.com/hackforla/not-today/issues/23) and added note

**Comment by ExperimentsInHonesty** [comment]
Transferred food-oasis [issue](https://github.com/hackforla/food-oasis/issues/238)

**Comment by ExperimentsInHonesty** [comment]
Transferred 311 data [issue](https://github.com/hackforla/311-data/issues/207)

**Comment by ExperimentsInHonesty** [comment]
Left David a note on undebate [issue](https://github.com/hackforla/website/issues/255) asking for hero image

**Comment by ExperimentsInHonesty** [comment]
Transfered lucky parking [issue](https://github.com/hackforla/lucky-parking/issues/40).  It's a new project with no card on the home page yet.  We still need some images from them.

**Comment by ExperimentsInHonesty** [comment]
Sent Metro Ontime a message in slack asking for an update.
Bonnie  11:39 AM
@Cam we need an update to this issue: https://github.com/hackforla/website/issues/266

**Comment by ExperimentsInHonesty** [comment]
Posted a message for Undebate on Issue #255 and on Slack asking David for the hero image.

Bonnie  1:27 PM
Hi @david looks like the only thing missing is the hero image - https://github.com/hackforla/website/issues/255

**Comment by ExperimentsInHonesty** [comment]
Posted a message for Engage on Issue #251 and on slack.

**Comment by ExperimentsInHonesty** [comment]
Assigned Kate to the Hello Gov issue #252 and sent her a message on slack

**Comment by ExperimentsInHonesty** [comment]
Updated and slacked Emily on the Public Tree map issue #246  and sent her a message on slack.

**Comment by ExperimentsInHonesty** [comment]
Updated and slack Matt on the VRMS [issue](https://github.com/hackforla/VRMS/issues/19).

**Comment by ExperimentsInHonesty** [comment]
@harishlingam on Monday please review if there has been any action taken by the teams mentioned here, since my last post:

**Santa Monica teams that we need updates or cards from:**
Not Today (readme, hero image)
Undebate (hero image)
HelloGov (everything)
Lucky Parking (hero image, 600 x 400 image)
Public Tree Map (everything)
VRMS - (card created)

**Santa Monica teams that have completed updates:**
Engage (awaiting revised hero image)

**Santa Monica Teams that we owe updates to:**
New Schools Today - they have submitted their project card info and are waiting for us to add it to the website.
Record Clearance - they have submitted their project card info and are waiting for us to add it to the website.

**DTLA teams that we need updates from:**
Food Oasis (everything)
311 Data (everything)
Metro OnTime (hero image)
TDM (readme)

**Teams I need to work with on creating cards**
Slack Redactor
Host Home
Jobs for Hope?

**Comment by ExperimentsInHonesty** [comment]
Received an update from Kate on the HelloGov issue #252 , still need hero image, asked if she needed support in producing that.

**Comment by ExperimentsInHonesty** [comment]
Wrote to Not Today: https://github.com/hackforla/not-today/issues/23#issuecomment-586744680

**Comment by ExperimentsInHonesty** [comment]
Posted request for update on Lucky Parking https://github.com/hackforla/lucky-parking/issues/40#issuecomment-586745188

**Comment by ExperimentsInHonesty** [comment]
public tree map is done.

**Comment by ExperimentsInHonesty** [comment]
vrms is done.

**Comment by ExperimentsInHonesty** [comment]
food oasis is done.

**Comment by ExperimentsInHonesty** [comment]
moved 311 data issue to in progress and assigned John to it.

**Comment by ExperimentsInHonesty** [comment]
moved issue tdm to their board, assigned kevin.

**Comment by ExperimentsInHonesty** [comment]
Slack redactor
https://github.com/hackforla/website/issues/312

**Comment by ExperimentsInHonesty** [comment]
I made two temp heroes for metro-ontime #266 and asked for Cam's input.

**Comment by ashlingam** [comment]
Awaiting input/information from project leads of these projects:
Engage #251 
Undebate #255

**Comment by ExperimentsInHonesty** [comment]
Undebate update: Bonnie Sent this request to kian for additional image tests https://github.com/hackforla/website/issues/255#issuecomment-605720161

**Comment by ExperimentsInHonesty** [comment]
Engage update: Ready to work. https://github.com/hackforla/website/issues/251#issuecomment-605720708

**Comment by ExperimentsInHonesty** [comment]
Hello Gov update: Ready to work https://github.com/hackforla/website/issues/252#issuecomment-605721300

**Comment by ExperimentsInHonesty** [comment]
Equity Language update: Waiting for project lead feedback https://github.com/hackforla/website/issues/301#issuecomment-605721997

**Comment by ExperimentsInHonesty** [comment]
TDM update: ready to work https://github.com/hackforla/website/issues/327#issuecomment-605722441

**Comment by ashlingam** [comment]
**Undebate**
Internal: Test hero images/page for proper display on mobile
Issue: https://github.com/hackforla/website/issues/255#issuecomment-605720161

**Engage**
Internal: add tools to project card
Issue: https://github.com/hackforla/website/issues/251#issuecomment-605720708

**HelloGOV**
Internal: Add leadership and tools to project card
Issue: https://github.com/hackforla/website/issues/252#issuecomment-605721300

**Equity Language**
External: Missing list of tools and need confirmation if we can project link
Issue: https://github.com/hackforla/website/issues/301#issuecomment-605721997

**TDM Calculator**
Internal: replace hero image on project homepage
Issue: https://github.com/hackforla/website/issues/327#issuecomment-605722441

**Comment by ExperimentsInHonesty** [comment]
host home update: still waiting for project lead info https://github.com/hackforla/host-home/issues/90

sent the following slack message: https://hackforla.slack.com/archives/CRWUG7X0C/p1585541914008700

**Comment by ExperimentsInHonesty** [comment]
Wrote to @equity-language about this on their slack today - again.

**Comment by ExperimentsInHonesty** [comment]
Sent Yuila a message on issue about reformatting text: https://github.com/hackforla/website/issues/408#issuecomment-609464428

**Comment by ExperimentsInHonesty** [comment]
@harishlingam has opened opened a issue #414 for changing the status of Shared housing to on hold

**Comment by ExperimentsInHonesty** [comment]
Engage
Internal: add tools to project card
Issue: #251 (comment)

HelloGOV
Internal: Add leadership and tools to project card
Issue: #252 (comment)

TDM Calculator
Internal: replace hero image on project homepage
Issue: #327 (comment)

Host Home
Internal: Asked Julia to reformat description
Issue #408 

Shared Housing
Internal: change status to onhold
Issue #404

---
Equity Language
External: Missing list of tools and need confirmation if we can project link
Issue: #301 (comment)

Undebate
External:  - Discuss with David (Test hero images/page for proper display on mobile)
Issue: #255 (comment)

**Comment by ExperimentsInHonesty** [comment]
Host Home
External: Need links and to discuss with carolanne/tyler the names change issue
Issue comment: https://hackforla.slack.com/archives/DPS0US63H/p1586658260000100

**Comment by ExperimentsInHonesty** [comment]
Engage
External: Need tools if they have them
Issue Comment: https://github.com/hackforla/website/issues/251#issuecomment-612722781

**Comment by ExperimentsInHonesty** [comment]
Civic Tech Index
Internal: Change Bonnie's name
Issue Comment: https://github.com/hackforla/website/issues/351#issuecomment-612677326

**Comment by ExperimentsInHonesty** [comment]
The project called Host Home has been changed to Home Unite Us

**Comment by ExperimentsInHonesty** [comment]
Engage
Internal: Add tools: hotjar and google analytics to their project card.
Issue Comment https://github.com/hackforla/website/issues/251#issuecomment-616177640

**Comment by ExperimentsInHonesty** [comment]
Home Unite Us
Internal:
Issue Comment https://github.com/hackforla/website/issues/351#issuecomment-610721690

**Comment by ExperimentsInHonesty** [comment]
Meeting links page: https://www.hackforla.org/project-meetings
Internal: 
Please link 
- [ ] civic tech index (thurs and sunday) to their project page: https://www.hackforla.org/projects/civic-tech-index
- [ ] host homes (saturday) to their project page: https://www.hackforla.org/projects/host-home

**Comment by ExperimentsInHonesty** [comment]
Lucky parking
Internal
see issue #444

**Comment by ExperimentsInHonesty** [comment]
Team meeting page
Internal
see issue #445

Engage 
Internal: Tools update
Issue #251

**Comment by ExperimentsInHonesty** [comment]
Home Unite Us changes needed.  
reaname repo
change all the links on the card as indicated in the above comment
See https://github.com/hackforla/host-home/issues/133

**Comment by ExperimentsInHonesty** [comment]
@switchzer0 Going though each of these updates together will help with requirements building for VRMS.  Warning this will be tedious.

**Comment by ahdithebomb** [comment]
We are closing this issue and starting a new one for the current quarter.
