### ISSUE TITLE
Add condition to event sorting to group by project.

### ISSUE THREAD

**Issue by JRHutson** [hackforla/website#2751]
### Overview
Would like to update display of events so that team meetings from the same team appear together if they are at the same time.

### Details
Currently Home Unite Us has two meetings at the same time that alternate from week to week. The display order is separating them, so someone might not think to look for the second meeting. After sorting events by time, we need to add a sort by team to make sure that the two meetings are together so someone is more likely to see both.

### Action Items
- [x] Review [Right column content](https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/right-col-content.html) file
- [x] Analyze how the events are currently being sorted using [Right-col-content.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/right-col-content.js) and [API-events.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/utility/api-events.js) files
- [x] Make changes to [Right-col-content.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/right-col-content.js) or/and [API-events.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/utility/api-events.js) files to ensure meetings from same team appear together or any other way we can achieve the same
- [x] Please ensure the look and functionality of the events page is still the same.

### Resources/Instructions
<details>
<summary>Screenshot from the events page</summary>

![image](https://user-images.githubusercontent.com/10876900/153060673-5c203ee1-6121-468d-94f6-8fd86ce14333.png)

</details>

- [Events page](https://www.hackforla.org/events/)
- [Right column content html](https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/right-col-content.html) 
- [Right-col-content.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/right-col-content.js)  
- [API-events.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/utility/api-events.js)

**Comment by JRHutson** [comment]
I do not have permission to edit issue labels in this repo.

**Comment by Providence-o** [comment]
@JessicaLucindaCheng @SAUMILDHANKAR this issue was opened by Reagan from the Home Unite Us team. Bonnie and I discussed this and it's definitely an important feature to add to the site. This will have the milestone: onboarding.

**Comment by luke-karis** [comment]
Availability and ETA:
Wednesday, Thursday from 4-5, Saturday and Sunday from 10-12
I hope to finish this ticket by Monday March 14
