### ISSUE TITLE
CONTRIBUTING.md: how to progress through issues according to complexity

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2760]
### Overview
As a developer on the team, I want to know how to progress through issues according to its complexity so I know what issue I am eligible to work on next. For this issue, we will update the CONTRIBUTING.md file with information about issue progression based on complexity.

### Action Items
- [x] Figure out where in [CONTRIBUTING.md section 2.1 Hack for LA Contributor expectations](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#21-hack-for-la-contributor-expectations) the following information should be added and add the information:
```
- Progress through issues with increasing complexity in the following order:
  - Good first issue
  - Good second issue
  - Small 
  - Medium 
  - Large
    - The reasons for this progression are:
      - The issues start out as being prescriptive and become less so as you gain more experience by working through increasingly complex issues.
      - We are trying to teach you the team methodology through the issues themselves.
      - It ensures you understand what we expect and the quality of contributions.
```
- [x] To see the visual changes for the CONTRIBUTING.md and make sure the changes look good:
  - [x] Push the changes to your remote forked repo's topic branch
  - [x] Go to your remote forked repo on GitHub
  - [x] Switch to your topic branch
  - [x] Click on the CONTRIBUTING.md file
  - [x] On the upper right, click on "Display the rendered blob" to see what your changes look like. Here is an image of what the "Display the rendered blob" button looks like:   
    <img width="332" alt="image" src="https://user-images.githubusercontent.com/31293603/155828894-d1c3e207-ff57-4ed6-8f67-0c69c2926d78.png">

### Resources/Instructions
- [CONTRIBUTING.md section 2.1 Hack for LA Contributor expectations](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#21-hack-for-la-contributor-expectations)

**Comment by JessicaLucindaCheng** [comment]
@Jaretzbalba 
Since you have already worked on a small issue, we request that you please pick up a medium issue as your next issue as that is the recommended order of progression for members of the Website Team, and it provides you with the opportunity to learn how to work on more complex issues that are less prescriptive. Also, since we have a limited number of Small issues and each one takes a while to write, we want to make sure there are Small issues available to newer developers that have not worked on one yet. Please let us know if you have any questions or challenges while picking up a medium complexity issue.

**Comment by Jaretzbalba** [comment]
@JessicaLucindaCheng Sorry for the confusion! Still learning a lot right now so was just trying to help out where I could. I'll definitely pick up a medium issue for my next one, thanks!
