### ISSUE TITLE
Contributing.md:  stopping mid issue text update 

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2768]
### Overview
As a developer, I want the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) to have accurate instructions. In this issue, we will update a line in section [2.6.b What to do if you have to stop working mid issue](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#26b-what-to-do-if-you-have-to-stop-working-mid-issue).

### Action Items
- [x] Change [line 457 in the CONTRIBUTING.md](https://github.com/hackforla/website/blob/ca3b53c3d4a5bdd0a4e0e413fe839e7862aef530/CONTRIBUTING.md?plain=1#L457)
  ```
  - Remove the progress in the checkboxes (all checkboxes should be empty)
  ```
  to 
  ```
  - For your issue, uncheck the checkboxes for any action items that have to be redone by the next developer picking up the issue.
  ```
- [x] To see the visual changes for the CONTRIBUTING.md
  - [x] Push the changes to your remote forked repo's topic branch
  - [x] Go to your remote forked repo on GitHub
  - [x] Switch to your topic branch
  - [x] Click on CONTRIBUTING.md file
  - [x] On the upper right, click on "Display the rendered blob" to see what your changes look like. Here is an image of what the "Display the rendered blob" button looks like:   
    <img width="332" alt="image" src="https://user-images.githubusercontent.com/31293603/155828894-d1c3e207-ff57-4ed6-8f67-0c69c2926d78.png">
  
### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `CONTRIBUTING.md`
- Click on the links below to see the source file code:
https://github.com/hackforla/website/blob/ca3b53c3d4a5bdd0a4e0e413fe839e7862aef530/CONTRIBUTING.md?plain=1#L457

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty @Providence-o In terms of wording, is this what we want to change [line 457 in the How to Contribute to Hack for LA document](https://github.com/hackforla/website/blob/ca3b53c3d4a5bdd0a4e0e413fe839e7862aef530/CONTRIBUTING.md?plain=1#L457) from
  ```
  - Remove the progress in the checkboxes (all checkboxes should be empty)
  ```
  to 
  ```
  - If you do not have an open pull request associated with the issue you are working on, remove the progress in the checkboxes (all checkboxes should be empty) for your issue.
  ```
  ?

**Comment by JessicaLucindaCheng** [comment]
@Gorck1416 At the time you self-assign an issue, make sure to write in a comment the following:
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"

**Comment by Garcia1416** [comment]
Availability: I will have 3 hours to work on this issue
    ETA: I expect to finish this issue next week

**Comment by JessicaLucindaCheng** [comment]
@Gorck1416 Please give a progress report in a comment in this issue. See what you need to include in your progress report and more information in [section 2.5 Reporting progress on your issue in CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#25-reporting-progress-on-your-issue)

**Comment by Garcia1416** [comment]
Progress: I still need to change the lines. I have created a branch but have not changed anything in the files
    Blockers: None
    Availability: 5 hours
    ETA: Monday March 21
    Pictures (optional): n/a
