### ISSUE TITLE
DRAFT: Edit content field and remove type field from [INSERT FILE NAME HERE].yml file

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2771]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We want to edit the content and remove type texts from the [INSERT FILE NAME HERE].yml file so they can be better utilized in the [credits.html](https://github.com/hackforla/website/blob/gh-pages/pages/credits.html) file. This issue is tracked in the epic #2775.

### Action Items
For the file `_data/internal/credits/[INSERT FILE NAME HERE].yml`, do the following:
- [ ] Change line [ADD LINE NUMBER WHICH HAS CONTENT] for the content field from
  ```
  content: [INSERT THE CURRENT TEXT ON THE FILE HERE]
  ```
  to
  ```
  content-type: image
  ```

- [ ] Remove line [ADD LINE NUMBER WHICH HAS TYPE] for the type field
  ```
  type: [INSERT THE CURRENT TEXT ON THE FILE HERE]
  ```

#### File and Code links you will need to work on this issue
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/[INSERT FILE NAME HERE].yml`

- Click on the links below to see the source file code:
[INSERT PERMALINK FOR THE LINE NUMBER WHICH HAS CONTENT] 
[INSERT PERMALINK FOR THE LINE NUMBER WHICH HAS TYPE]

**Comment by JessicaLucindaCheng** [comment]
This was created to draft a template before actually creating it in the issues templates. Since the template has been created, this issue can be closed.
