### ISSUE TITLE
Google Data Studio related error on Dashboard page 

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2776]
### Overview
As a developer, I want to make sure that up-to-date data is reflected on the [Dashboard page](https://www.hackforla.org/dashboard/). For this issue, we will fix the error where data related to remote onboarding is not visible on the dashboard page.

### Action Items
- [x] Request [Google data studio](https://datastudio.google.com/reporting/16J9XI19pQejSDNFvjl_V3ZezJ502rM_a/page/qx6RB) access from tech leads/merge team 
- [x] Review how the data set is configured ([Remote Onboarding data tab](https://docs.google.com/spreadsheets/d/1sIhdPzSpMNn7ZwGftiCbgMRtF-84ziJgmr8EjsC_yK8/edit#gid=340717816))
- [x] Identify the reasons for the error and explore ways to fix it
- [x] If required, make a copy of the [Survey Data Workbook](https://docs.google.com/spreadsheets/d/1sIhdPzSpMNn7ZwGftiCbgMRtF-84ziJgmr8EjsC_yK8/edit?usp=sharing) in your drive to test the changes in your own repo
- [x] Please upload the screenshots from your repo once the error is fixed
- [x] Discuss your solution with the tech leads or in a team meeting (before making final configuration changes)
- [x] Make sure no other functionality is impacted, once the error is fixed

### Resources/Instructions
<details><summary>Screenshot of the error page</summary>

![Dashboard page error](https://user-images.githubusercontent.com/843538/153749463-5f9064f8-4dcc-4cdf-8809-948bb3349692.PNG)

</details>

<details><summary>Data set configuration error log</summary>

![Data set configuration error log](https://user-images.githubusercontent.com/843538/161853010-0b724ca6-eb30-406c-a5d5-02c9511e486e.PNG)

</details>

[Google data studio error page](https://datastudio.google.com/reporting/16J9XI19pQejSDNFvjl_V3ZezJ502rM_a/page/qx6RB)
[Dashboard page](https://www.hackforla.org/dashboard/)
[Survey Data Workbook](https://docs.google.com/spreadsheets/d/1sIhdPzSpMNn7ZwGftiCbgMRtF-84ziJgmr8EjsC_yK8/edit?usp=sharing)
[Remote Onboarding data tab](https://docs.google.com/spreadsheets/d/1sIhdPzSpMNn7ZwGftiCbgMRtF-84ziJgmr8EjsC_yK8/edit#gid=340717816)

**Comment by ExperimentsInHonesty** [comment]
We need to talk about google data studio.  This issue really has nothing to do with the iframe, but rather GDS.  Its been added to our next dev meeting

**Comment by jdingeman** [comment]
Availability: Every day after 3pm
ETA: Sunday, August 28 EOD

**Comment by jdingeman** [comment]
Will begin issue after my [medium issue pull request](https://github.com/hackforla/website/pull/3436) is merged.

**Comment by jdingeman** [comment]
When prompted to create a copy of the Google Data Studio environment, I am presented with this issue 
![image](https://user-images.githubusercontent.com/88953806/185820524-52ea80b6-b311-438a-8c5e-ed7f3536d7a4.png)

I am not sure why the data sources are "unknown" but perhaps we can try to fix that. I don't want to try and rename the whole thing and affecting the data that is already transferred into the studio. 

But more on the issue, I am not sure what the layout of the Suggestions for Improvement by Respondent should be. After reconnecting that module to a new data source using the [Survey Data Workbook | Remote Onboarding](https://docs.google.com/spreadsheets/d/1sIhdPzSpMNn7ZwGftiCbgMRtF-84ziJgmr8EjsC_yK8/edit#gid=340717816), this is how it immediately appeared:
![image](https://user-images.githubusercontent.com/88953806/185820926-d5a8e8c8-1e90-4dc0-b55e-7ee0b46696e1.png)

I think the only issue with this is that the module needed to be reconnected to the workbook.

**Comment by jdingeman** [comment]
UPDATE:
Progress: Unchanged. Need administrative approval for updating data studio.
Blockers: Mentioned in progress.
Availability: Every day after 3pm
ETA: Hopefully by next Monday, 9/12

**Comment by jdingeman** [comment]
Added data source into main data studio. 
![image](https://user-images.githubusercontent.com/88953806/189266386-69f842e1-a672-44a5-96bd-12790207510e.png)

Ready for issue close unless formatting is needed. @kathrynsilvaconway @ExperimentsInHonesty

**Comment by arpitapandya** [comment]
I had a meeting with @jdingeman on 2022-09-15. We reviewed all the relevant changes and it's correct and working. Also, meets all the issue requirements and a working copy. Great job @jdingeman

**Comment by ExperimentsInHonesty** [comment]
product needs to review

**Comment by ExperimentsInHonesty** [comment]
Ready for product - we need to review the comments and see what action items are necessary and which suggestions are resolved.

**Comment by ExperimentsInHonesty** [comment]
- Made an ER #4276
