### ISSUE TITLE
Get contributor information for display on Project Home Pages

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#282]
### Overview
We need to display the contributors to a project on the Project Homepages.  We are going to pull that information from the teams.

### Action Items

- [x] Review Github json file to determine location of information. 
- [x] Run test to identify what information comes back when you query that endpoint
- [x] Experiment with parsing the data into a useable format for the project

### Resources/Instructions
https://github.com/hackforla/website/files/4013609/exampleOfAPICall.json.zip

**Comment by ExperimentsInHonesty** [comment]
This is an excerpt from the above json file

{
    "total_count": 21,
    "incomplete_results": false,
    "items": [
        {
            "id": 197452459,
            "node_id": "MDEwOlJlcG9zaXRvcnkxOTc0NTI0NTk=",
            "name": "tdm-calculator",
            "full_name": "hackforla/tdm-calculator",
            "private": false,
            "owner": {
                "login": "hackforla",
                  ...
            },
            "html_url": "https://github.com/hackforla/tdm-calculator",
            "description": "DTLA Hack for LA is partnering with Los Angeles Department of Transportation (LADOT) to develop a Traffic Demand Management (TDM) calculator tool.  This tool will help planners at LADOT and real estate developers to meet the Los Angeles’s Mobility Plan goals by 2035. ",
            "fork": false,
            "url": "https://api.github.com/repos/hackforla/tdm-calculator",
            "forks_url": "https://api.github.com/repos/hackforla/tdm-calculator/forks",
            "keys_url": "https://api.github.com/repos/hackforla/tdm-calculator/keys{/key_id}",
            "collaborators_url": "https://api.github.com/repos/hackforla/tdm-calculator/collaborators{/collaborator}",
            "teams_url": "https://api.github.com/repos/hackforla/tdm-calculator/teams",



See the teams_url at the bottom of above.

**Comment by cnk** [comment]
### First iteration TO DO: 

- [ ] 1. Merge github actions code from @StephenVNelson - https://github.com/hackforla/website/issues/193
- [ ] 2. Make credential information variable
- [ ] 3. Create an API user for the production commits (insert info into variables from step 2)
- [ ] 4. Figure out how to run checks on daily schedule on hackforla/website repo but not everyone's forks.
- [ ] 5. Make version live (can use the primary language in the project card using current data)

### Second iteration:

- [ ] Change the structure of the db.json we store so it is {"id": "nnn", "languages": {dict of langs from lang endpoint}, "contributors": {dict of contributors info}}
- [ ] Make this file dynamic by populating from github actions (Promises.all())
- [ ] Change project pages to use this data
- [ ] Push project pages live without linking to them from project cards

**Comment by cnk** [comment]
1. Progress
   * Hand off from Stephen Nelson
   * Worked with Stephen Ettinger on building a version using Promise
   * Built a playground to test actions outside of website repository
2. Blocks
   * Promises not working
3. Availability
   * Good. This is my current project
4. ETA
   * Full version: unsure
   * Build a static db.json we can use for placing languages and contributors on current projects

**Comment by ExperimentsInHonesty** [comment]
ask thekaveman to review.

**Comment by cnk** [comment]
@thekaveman My proposed data structure for each project is as follows. If we start grabbing more data for each project we could add a key + data. Is this OK by you?

    {"id": <project.id>,
     "name": <project.name>,
     "languages": {"url": <project.languages_url>,
                   "data": ["Ruby", "HTML", "Dockerfile"]
                   },
     "contributors": {"url": <project.contributors_url>,
                      "data": {"id": <user.id>,
                               "github_url": <user.html_url>,
                               "avatar_url": <user.avatar_url>,
                               "gravatar_id": <user.gravatar_id>
                              }
                     }
     }

**Comment by cnk** [comment]
Contributor info url: https://api.github.com/repos/hackforla/VRMS/contributors

**Comment by cnk** [comment]
@thekaveman @KianBadie @ExperimentsInHonesty My experiments with the GitHub API have hit a wall. The code I developed with promises / await runs when run from the command line but when executed from a GitHub action all happens AFTER the action has moved on. So I get no data.

Will need to regroup with someone with JavaScript expertise. In the mean time, I committed the data structure and sample data in pull request #320 so this doesn't remain a blocker for Kian's development of project pages.

**Comment by ashlingam** [comment]
@wesrowe @ExperimentsInHonesty @cnk Following up on Sunday's standup -- the team needs to recruit someone who has experience with Promises and JavaScript.

**Comment by wesrowe** [comment]
We can recruit one tonight

**Comment by ExperimentsInHonesty** [comment]
@KianBadie Did this get resolved?

**Comment by cnk** [comment]
@KianBadie  got this working.
