### ISSUE TITLE
Update Project Profile: 311 Data

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#285]
### Overview
Provide collateral for the HackforLA website

### Action Items
- [ ]   Gather items
  - [ ]  600 x 400 image
  - [x]  Alt image text
  - [ ]  Name of project
  - [ ]  A blurb about your project
  - [ ]  Links (website, github, etc.)
  - [ ]  What you are looking for skills wise
  - [ ]  Partner(s)
  - [ ]  Location
- [ ]   Add project Card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples
[Project Card](https://docs.google.com/document/d/1AOiuwxfXEkg_SlIVzzIzen5XEUAZ1IIs0PhNT2k7Sz0/edit?usp=sharing)

**Comment by johnr54321** [comment]
@harishlingam   Please see the comment here on what to update.  Thanks!  https://github.com/hackforla/311-data/issues/207#issuecomment-594295120

**Comment by johnr54321** [comment]
FYI.  Comment has been updated.

**Comment by ExperimentsInHonesty** [comment]
duplicate of https://github.com/hackforla/311-data/issues/207
