### ISSUE TITLE
Create project card for VRMS Project

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#288]
### Overview
Provide collateral for the HackforLA website

### Action Items
- [x]   Gather items
  - [x]  600 x 400 image (for hackforla homepage project card)
  - [x] 1500 x 700 Hero image (similar to hackforla homepage)
  - [x]  Alt image text
  - [x]  Name of project
  - [x]  A blurb about your project
  - [x]  Links (website, github, etc.)
  - [x]  What you are looking for skills wise
  - [x]  Tools your team uses (e.g. Balsamic, Figma, Photoshop, LucidChart, etc.)
  - [x]  Partner(s)
  - [x]  Location

- [x]   Add project Card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples

**Comment by ExperimentsInHonesty** [comment]
@sarL3y - can you update this issue with the new hero image and when you create the card, it will have this

```yaml
title: VRMS
description: VRMS is a tool used for the engagement, support, and retention of a network of volunteers.
image: vrms.jpg
alt: "VRMS homepage showing the check-in buttons"
image-hero: vrms-hero.jpg
alt: "city of LA skyline"
links: 
  - name: Github
    url: 'https://github.com/hackforla/VRMS'
  - name: Site
    url: 'vrms.io'

looking: Currently seeking front end and back end developers at any level (from Junior to Lead)
location: Santa Monica, Downtown LA
partner: TBD
status: Active
---

**Comment by sarL3y** [comment]
Here is the background image (1500x700):

![vrms-bg-1500x700](https://user-images.githubusercontent.com/39248174/75727878-fac2a280-5c9a-11ea-98b5-134d70bd44d6.png)

**Comment by cnk** [comment]
Card will be added when we merge the leadership updates
