### ISSUE TITLE
Update Donate page images' alt text to adhere to WCAG

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2886]
### Overview
As a developer, we need to provide clear and descriptive alt text on the Donate web page so that we adhere to the Web Content Accessibility Guidelines (WCAG) and we can achieve our mission of inclusivity. For this issue, we will change the alt texts on the Donate web page to adhere to WCAG.

### Action Items
The following alt text changes are for the [Donate web page](https://www.hackforla.org/donate/)
- [x] Change the image's alt property value within [donate.html](https://github.com/hackforla/website/blob/557ff50b2f426a7c481a22ac5ce5dd72020f6c10/pages/donate.html) for the following lines of code only:
  - [x] The following alt text is on the `Header-container Header-container--donate` area on the web page
    - [x] On line 18, change the `alt="donate banner icon"` text  to `alt=""`
  - [x] The following alt text is on the `Content-section Donate-card-container` area on the web page
    - [x] On line 24, change the `alt="donate card image"` text  to `alt=""`
    - [x] On line 34, change the `alt="donation chart"` text  to `alt="Hosting, mailing list services, Zoom accounts, domain names, stickers, t-shirts"`
    - [x] On line 45, change the `alt="donation form image"` text  to `alt="Gif showing how to select Hack for LA from donation list"`
    - [ ] Review with product referencing the parent issue https://github.com/hackforla/website/issues/2568 

- [x] Check that the Donate web page looks the same
- [x] Check that the new alt texts got incorporated after the change by inspecting the web page using developer tools

#### File and Code links you will need to review this issue
- Link to web page: https://www.hackforla.org/donate/

- Directory to find the source file code once you have it in your IDE: `pages/donate.html`

- Click on this link to see the source file code: https://github.com/hackforla/website/blob/557ff50b2f426a7c481a22ac5ce5dd72020f6c10/pages/donate.html

- Related design issue: https://github.com/hackforla/website/issues/2568

- Link to the tab on Google Sheets: https://docs.google.com/spreadsheets/d/1abMlPOX88zHTV29E4BFxAYwahCxgJN28Mn95cXr8jak/edit#gid=14599403

**Comment by 7kram** [comment]
- https://github.com/hackforla/website/pull/2982/files
This merge shows that the updates were made, however, the updates don't show on the live site
- https://www.hackforla.org/donate/
- https://github.com/hackforla/website/blob/gh-pages/_includes/donate-card.html

**Comment by blulady** [comment]
We are replacing this issue with this issue #3630
