### ISSUE TITLE
Update Project Profile: Guides Website

### ISSUE THREAD

**Issue by SheIsBukki** [hackforla/website#2888]
### Overview
As a product manager of the Guides Team, I want my project's details to be up to date on the HackforLA website

### Project card
- [guides-team.md](https://github.com/hackforla/website/blob/427c0c8ae104955f91a41e9af0fc4594cce08c22/_projects/guides-team.md?plain=1)
- [Guides Team on Hack For LA Website](https://www.hackforla.org/projects/guides-team)

### Action Items

- We need to update the Current Project Team to remove former team members who are:
      - Thuy Le
      - Carol Zhu

### Resources
- https://github.com/hackforla/website/blob/427c0c8ae104955f91a41e9af0fc4594cce08c22/_projects/guides-team.md?plain=1
- https://www.hackforla.org/projects/guides-team

**Comment by JessicaLucindaCheng** [comment]
@SheIsBukki I need some clarification. Do you want to keep Bonnie's and Bukola's information as is on the [Guides Team page](https://www.hackforla.org/projects/guides-team) under the Current Project Team section?

**Comment by SheIsBukki** [comment]
Hi @JessicaLucindaCheng yes, I want to. Thanks

**Comment by blulady** [comment]
ETA: Monday 3.21.22
Availability: Tuesday 3.22.22 1-6pm
