### ISSUE TITLE
Add weekly meeting requirements to CONTRIBUTING.md

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2896]
### Overview
As developers, we want to make sure the contributor expectations in [CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md) are clear. For this issue, we will be adding weekly meeting requirements to [CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md) file.

### Action Items
- [ ] Review the Table of Contents in [CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md) file.
- [ ] Analyze which section would be the best to add the following weekly meeting requirements: 
```
All website team members are required to attend at least 1 team meeting in a week (held on Tuesdays, Thursdays and Sundays). In case, you are unable in any given week, you should reach out to the tech leadership team. Exceptions to this requirement may be provided on a case-by-case basis.
```
```
Also, please let the tech leadership team know (through a slack message in the hfla-site channel as well as an @ mention in a comment of the issue that you would be working on) if you are planning to take a week off or a longer vacation.
```
- [ ] Consider adding the above requirement to [Section 2.1](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md#21-hack-for-la-contributor-expectations) vs making a new section 
- [ ] Add the weekly meeting requirements mentioned above to the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md) file
- [ ] Make sure you can see the changes in your own repo.

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md): file where changes need to be made

**Comment by JessicaLucindaCheng** [comment]
@harshitasao At the time you self-assign any issue, please
- [x] Move the issue to the "In progress" column
- [x] Add your initial availability and ETA:
```
Availability for this week:
My estimated ETA for completing this issue:
```

**Comment by harshitasao** [comment]
Availability for this week: Flexible
My estimated ETA for completing this issue: 12/03/2022
