### ISSUE TITLE
Remove no-labels-template.md file

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2898]
### Overview
We need to remove [no-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/no-labels-template.md) file so that the total number of bot comments are reduced, and developers would have less notifications

### Action Items
- [x] Remove  [no-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/no-labels-template.md) file
- [x] Edit the following lines in [post-labels-comment.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/post-labels-comment.js) file such that if no label i.e., (role, size and feature) is missing, no bot comment should be posted: https://github.com/hackforla/website/blob/dc04be749651270020eb965c428c2a36431d9c5e/github-actions/trigger-issue/add-missing-labels-to-issues/post-labels-comment.js#L47-L55

### Checks
- [x] For testing in your own repo (after making the necessary code changes)
    - [x] Create a project board in your own repo
    - [x] Create a new issue with all the required labels, i.e., (role, size and feature) and submit the issue
    - [x] Confirm that no comment is posted by the bot

### Resources/Instructions
Directory where files are located `website/github-actions/trigger-issue/add-missing-labels-to-issues/`
File that needs to be removed [no-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/no-labels-template.md)
File where changes need to be made: [post-labels-comment.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/post-labels-comment.js)
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)

**Comment by raswani2023** [comment]
ETA: Just submitted a PR for the issue after being able to test it in my local repository to make sure the changes worked.
Availability: Monday, Tuesday, Wednesday

**Comment by ExperimentsInHonesty** [comment]
Which GHA are you working on.  See this directory: https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions

**Comment by ExperimentsInHonesty** [comment]
~I just looked at the PR and it looks like one file was deleted and another had all the logic removed from a function.  Is there a reason why we didn't delete the function?  Not advocating that, just asking for a second look to make sure we cleaned up what we were intending to, and that~ This change  needs to be properly documented in the wiki and in this issue.  See my question from the 12th.

**Comment by ExperimentsInHonesty** [comment]
Please make a new issue to document this change appropriately in the [wiki, GHAs](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions), which should include marking a GHA as depreciated with details why.

**Comment by jdingeman** [comment]
> Please make a new issue to document this change appropriately in the [wiki, GHAs](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions), which should include marking a GHA as depreciated with details why.

- New issue has been made. See #3849
