### ISSUE TITLE
Add weekly time commitment requirements to CONTRIBUTING.md

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2902]
### Overview
As developers, we want to make sure the contributor expectations in [CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md) are clear. For this issue, we will be adding minimum weekly time commitment requirements to [CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md) file.

### Action Items
- [x] Review the Table of Contents in [CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md) file.
- [x] Analyze which section would be the best to add the following weekly meeting requirements: 
```
All website team members are expected to devote a minimum of 6 hours per week while working on various assignments during their entire tenure at the website team (excluding week offs and vacations).
```
- [x] Consider adding the above requirement to [Section 2.1](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md#21-hack-for-la-contributor-expectations) vs making a new section 
- [x] Add the weekly time commitment requirements mentioned above to the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md) file
- [ ] Make sure you can see the changes in your own repo.

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/f42f4920dc9766f1669661228eb8c32b4462b932/CONTRIBUTING.md): file where changes need to be made

**Comment by scarter31191** [comment]
Availability for this week: 3/26, 3/27
My estimated ETA for completing this issue: 3/27
