### ISSUE TITLE
Fix misspelled word on donate.html file

### ISSUE THREAD

**Issue by answebdev** [hackforla/website#2907]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items
- [x] For the file `pages/donate.html`,  on line 32, change the spelling from "commmunity" to "community", so
  ```
  products to the commmunity.
  ```
  becomes
  ```
  products to the community.
  ```
- [x] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website page with issue: https://www.hackforla.org/donate
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/pages/donate.html
Line of code: https://github.com/hackforla/website/blob/c7d279e09a30099593e5ffdf1d24dfb4e98c90a7/pages/donate.html#L32

**Comment by JessicaLucindaCheng** [comment]
@answebdev Good job writing this issue! I just wanted to provide some feedback:
- [x] In the Resources/Instructions section, please add a link to the file on GitHub. So, for this issue, it would be: https://github.com/hackforla/website/blob/gh-pages/pages/donate.html
- [x] For any good first issue you write, before the Overview section, please add the following:
```
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
``` 
- [x] Also, I know our documentation doesn't include the points yet but please add a points label. Just search "pt" when looking for the label and you will see all the points labels. 1 point is equivalent to 6 hours of work. (The labels have a more detailed definition of the hours.)

**Comment by answebdev** [comment]
@JessicaLucindaCheng Thank you for the feedback. I went ahead and addressed what you mentioned. Let me know if there is anything else.

**Comment by Jaretzbalba** [comment]
Progress: Found the misspelled word
Blockers: Forgot to create a new branch to work on this issue and did a commit to my main. How can I undo this?
Availability: Mon/Wed/Friday during the day
ETA: Need help with my blocker but after that it's an easy task. 
Pictures (optional): "Add any pictures of the visual changes made to the site so far."

**Comment by SAUMILDHANKAR** [comment]
@Jaretzbalba Regarding your blocker, looks like your remote gh-pages does not have the commit that you mentioned in your comment. So, I am assuming it is only in your local gh-pages. You can use [git revert](https://git-scm.com/docs/git-revert) to record some new commits to reverse the effect of some earlier commits.
