### ISSUE TITLE
Fix misspelled words on citizen-engagement-card.yml file from "policymaking" to "policy making"

### ISSUE THREAD

**Issue by answebdev** [hackforla/website#2909]
### Dependency
- [x] https://github.com/hackforla/website/issues/3546

### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items

- [ ] For the file `_data/internal/program-areas/citizen-engagement-card.yml`, on line 6, change the spelling from "policymaking" to "policy making", so

  ```
  these projects empower local residents to impact policymaking in their communities.
  ```
  becomes
  ```
  these projects empower local residents to impact policy making in their communities.
  ```
- [ ] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website page with issue: https://www.hackforla.org/program-areas
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/_data/internal/program-areas/citizen-engagement-card.yml
Line of code:
https://github.com/hackforla/website/blob/08b2f7096e54feb7b88466b92d90bbb19357ef01/_data/internal/program-areas/citizen-engagement-card.yml#L6

**Comment by PMKnight** [comment]
Availability for this week: 8 hours
My estimated ETA for completing this issue: 2 hours

**Comment by JessicaLucindaCheng** [comment]
@PMKnight 
Please give a progress report in a comment in this issue that includes Progress, Blockers, Availability, and ETA. See what you need to include in your progress report and more information in [section 2.5 Reporting progress on your issue in CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#25-reporting-progress-on-your-issue)

**Comment by JessicaLucindaCheng** [comment]
@PMKnight Please give a progress report in a comment in this issue that includes Progress, Blockers, Availability, and ETA. See more detailed information in [section 2.5 Reporting progress on your issue in CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#25-reporting-progress-on-your-issue). If you are taking a leave of absence or a vacation, please also let us know in your progress report. 

Also, let us know if you have questions or need clarification by reaching out to us on the #hfla-site Slack channel.

If we don't hear back from you by Thu, May 12, 2022, we will close your pre-work, un-assign you from this issue, close your pr, and mark you as inactive in our roster.

Edit: Sent an email and Slack message about providing a Progress Update on Thu, May 5, 2022.

**Comment by JessicaLucindaCheng** [comment]
Pulling this issue from the Prioritized Backlog until I can speak with the PM about it.

Edit: Spoke to PM about it and added a dependency.

**Comment by angieintech** [comment]
Availability: Thursday evening
ETA: A week or two from now.

**Comment by CalvinTan607** [comment]
i. Availability: 7/31 
ii. ETA: About 10 minutes

**Comment by JessicaLucindaCheng** [comment]
@CalvinTan607 This issue isn't ready to be worked on yet because it was still in the Ice Box column when you picked it. I am unassigning you from this issue and moving this back to the Ice Box.

For how to find issues to work on, please read [Part 2: How the Website team works with GitHub issues](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues), especially section 2.3 Where can I find GitHub issues to work on?

**Comment by CalvinTan607** [comment]
Oh sorry I misunderstood, I will go look for another issue on the Prioritized Backlog.

**Comment by blulady** [comment]
We looked it up [policymaking](https://www.collinsdictionary.com/dictionary/english/policymaking) can be one word. We are going to close this issue.
