### ISSUE TITLE
Proposal to change project.md file format to update "Looking For"

### ISSUE THREAD

**Issue by KianBadie** [hackforla/website#291]
### Overview
We want to accommodate the use of commas in "Looking For" descriptions. 

### Action Items
- [ ] Edit a sample project md file in the following way 
Current State:

```yaml
looking: One skill, another skill, a compound skill (part 1, part1)
```

Future State:

```yaml
looking:
  - One skill
  - another skill
  - a compound skill (part 1, part 2)
```
- [x] write logic for project hompage include to display
- [x] add screenshot to issue
   - [ ] Get sign off by Bonnie 
- [ ] Edit all project files

### Resources/Instructions
[Additional dialogue on another issue regarding this topic](https://github.com/hackforla/website/issues/157#issuecomment-582031428)

**Comment by KianBadie** [comment]
@ExperimentsInHonesty 
For my example I used the LA Metro Health Monitor project
**Project card on homepage**
![Screenshot from 2020-02-08 17-33-33](https://user-images.githubusercontent.com/18221058/74094626-2934cf80-4a99-11ea-991e-22c8ba18d53f.png)

**metro-ontime.md code snippit**:
```yaml
looking: 
  - Frontend Developers (React, D3) 
  - Backend Developers (Python, Pandas)
```

**current-projects.html logic code snippit**:
```
                  {%- if item.looking -%}
                    <div class="project-needs">
                      <strong>Looking for: </strong>
                        {% for role in item.looking %}
                          {% if forloop.last == false %}
                            <p style='display:inline;'>{{ role }}, </p>
                          {% else %}
                            <p style='display:inline;'>{{ role }}</p>
                          {% endif %}
                        {% endfor %}
                    </div>
                  {%- endif -%}
```
I avoided putting the styling rule in a class because I wanted to avoid making a class for just one rule.

**Comment by ExperimentsInHonesty** [comment]
This is the code for displaying links
```yaml
{%- if item.links -%}
                    <div class="project-links">
                      <strong>Links: </strong> 
                        {%- for item in item.links -%} 
                          <a href={{ item.url }} rel="noopener" target='_blank'> {{ item.name }}</a>{%- if forloop.last == false -%},
                          {%- endif -%}
                        {%- endfor -%}
```

**Comment by ExperimentsInHonesty** [comment]
progress report is 

1. Progress - mostly done, will update based on comments (making it similar to existing links section)
2. Blocks - none
3. Availability - sunday/monday no problem.
4. ETA 2/10

**Comment by KianBadie** [comment]
Update with revisions in code @ExperimentsInHonesty. The code is written to be identical to the way it is implemented in the links section. 

**Screenshot**:
![Screenshot from 2020-02-10 12-33-06](https://user-images.githubusercontent.com/18221058/74187486-83e93b00-4c01-11ea-9e87-af68dca625c3.png)

**Revision in code**:
```
                  {%- if item.looking -%}
                    <div class="project-needs">
                      <strong>Looking for: </strong>
                        {% for role in item.looking %}
                          <p style='display:inline;'> {{ role }}</p>{% if forloop.last == false %},
                          {% endif %}
                        {% endfor %}
                    </div>
                  {%- endif -%}
```

**Comment by KianBadie** [comment]
@ExperimentsInHonesty I totally forgot if we talked about this/made a decision last night, but is my example/code clear to go? Should I add it to the rest of the project cards?

**Comment by cnk** [comment]
@KianBadie I am not Bonnie but I think your code looks good.
