### ISSUE TITLE
Fix misspelled word on environment-card.yml file

### ISSUE THREAD

**Issue by answebdev** [hackforla/website#2910]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items

- [x] For the file `_data/internal/program-areas/environment-card.yml`, on line 6, change the spelling from "susainability" to "sustainability", so

  ```
  these projects support Hack for LA’s advocacy of environmentalism and susainability.
  ```
  becomes
  ```
  these projects support Hack for LA’s advocacy of environmentalism and sustainability.
  ```
- [x] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website page with issue: https://www.hackforla.org/program-areas
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/_data/internal/program-areas/environment-card.yml
Line of code:
https://github.com/hackforla/website/blob/08b2f7096e54feb7b88466b92d90bbb19357ef01/_data/internal/program-areas/environment-card.yml#L6

**Comment by eodero** [comment]
- [x] Availability for this week: 2hrs
- [x] My estimated ETA for completing this issue: 4/22/2022
