### ISSUE TITLE
Fix misspelled word on about-card-platform.html file

### ISSUE THREAD

**Issue by answebdev** [hackforla/website#2911]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items

- [x] For the file `_includes/about-page/about-card-platform.html`,  on line 76, change the spelling from "definitley" to "definitely", so

  ```
  And last but definitley not least, a true open door policy....
  ```
  becomes
  ```
  And last but definitely not least, a true open door policy....
  ```
- [x] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website page with issue: https://www.hackforla.org/about
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-platform.html
Line of code:
https://github.com/hackforla/website/blob/08b2f7096e54feb7b88466b92d90bbb19357ef01/_includes/about-page/about-card-platform.html#L76

**Comment by RyanCahela** [comment]
Availability: 03/23/22 2PM - 5PM (PST)
ETA: 1hr or less
