### ISSUE TITLE
Fix misspelled word on join-us.html file from "commmunity" to "community"

### ISSUE THREAD

**Issue by answebdev** [hackforla/website#2913]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items

- [x] For the file `pages/join-us.html`,  on line 93, change the spelling from "commmunity" to "community", so

  ```
  products to the commmunity.
  ```
  becomes
  ```
  products to the community.
  ```
- [x] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website page with issue: https://www.hackforla.org/join
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html
Line of code:
https://github.com/hackforla/website/blob/08b2f7096e54feb7b88466b92d90bbb19357ef01/pages/join-us.html#L93

**Comment by trishajjohnson** [comment]
Availability for this week: 6 hours
My estimated ETA for completing this issue: 2 hours

**Comment by trishajjohnson** [comment]
How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?

Approximately 3-4 hours
