### ISSUE TITLE
Fix misspelled word on join-us.html file from "non-profit" to "nonprofit"

### ISSUE THREAD

**Issue by answebdev** [hackforla/website#2914]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items

- [x] For the file `pages/join-us.html`,  on line 77, change the spelling from "non-profit" to "nonprofit", so

  ```
  <a href="./survey3" target="_blank" class="btn btn-primary btn-md btn-partner-with-us btn--default" title="Non-profit 
  Contact Form">Non-Profit</a>
  ```
  becomes
  ```
  <a href="./survey3" target="_blank" class="btn btn-primary btn-md btn-partner-with-us btn--default" title="Nonprofit 
  Contact Form">Nonprofit</a>
  ```
- [x] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website page with issue: https://www.hackforla.org/join
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html
Line of code:
https://github.com/hackforla/website/blob/08b2f7096e54feb7b88466b92d90bbb19357ef01/pages/join-us.html#L77

**Comment by JessicaLucindaCheng** [comment]
@JayBarbanel 
At the time you self-assign an issue, make sure to write in a comment the following:
- Availability: "How much time will you have this week to work on this issue?"
- ETA: "When do you expect this issue to be completed?"
