### ISSUE TITLE
Fix misspelled words on lucky-parking.md file

### ISSUE THREAD

**Issue by answebdev** [hackforla/website#2916]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items

- [x] For the file `_projects/lucky-parking.md`,  on line 56, change the spelling from "webapp" to "web app", so

  ```
  solution: Hack for LA’s Lucky Parking project seeks to map the 12.5 million parking citations on a webapp
  ```
  becomes
  ```
  solution: Hack for LA’s Lucky Parking project seeks to map the 12.5 million parking citations on a web app
  ```
- [x] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website page with issue: https://www.hackforla.org/citizen-engagement
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md
Line of code:
https://github.com/hackforla/website/blob/08b2f7096e54feb7b88466b92d90bbb19357ef01/_projects/lucky-parking.md?plain=1#L56

**Comment by JessicaLucindaCheng** [comment]
@eodero
- When you self-assign an issue, please move the issue to the In Progress column. See instructions for how to do this in [2.4.b Move this issue from the ‘Prioritized Backlog’ to the ‘In progress’ & back](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#24b-move-this-issue-from-the-prioritized-backlog-to-the-in-progress--back).
- At the time you self-assign an issue, make sure to write in a comment the following:
    - Availability: "How much time will you have this week to work on this issue?"
    - ETA: "When do you expect this issue to be completed?"

**Comment by Sparky-code** [comment]
Hey @eodero, Some things with this issue got caught after I'd merged it so I'm reopening the issue for you to address them. Sorry for any confusion over the back and forth. 

_NOTE: You should be able to work on the same branch you created for this issue but you will probably need to open a new PR._  

- [ ] Make sure to check off the action items at the top of this issue as you complete them.
- [ ] Please move your pre-work issue into 'actively working' on the project board. You should also be actively checking off items in your pre-work issue as you complete them.
- [ ] Double check that the spelling of 'web app' is still correct.
- [ ] Please change the double quotes around the links in the file you edited back to single quotes, this is the standard for H4LA. 

_NOTE: If this change was a result of 'linting' in your IDE and not something you did intentionally. Make sure that the links don't revert back to double quotes when you save the file, you may have to disable your linter. Feel free to reach out if you run in to trouble with that._

**Comment by eodero** [comment]
@Sparky-code Hello, thanks for the comments. For the double quotes, I did not intentionally edit or change from single quotes. I use VS Code, I have checked and didn't see any linter extension installed and I don't know how to disable the feature it has been enabled by default. Can you advise. Thanks

**Comment by answebdev** [comment]
@eodero This might be something to do with the auto-formatting when you save on VS Code. I had the same issue when I started, where it was automatically changing to double-quotes, for example. If you are on Windows, do Control - Shift - P in VS Code. Then up top, search for and select **File: Save without Formatting**. This should save your file without automatically formatting and changing the quotes to double-quotes. This worked for me.

![vsc](https://user-images.githubusercontent.com/36783010/165677160-755d7832-ebdf-416e-9f21-b53ecac8f9ec.jpg)
