### ISSUE TITLE
Create icon sourcing page in resources section of wiki

### ISSUE THREAD

**Issue by KianBadie** [hackforla/website#292]
### Overview
Create page in the resources section of the wiki that helps visitors see sourcing, modifications, and licenses of icons we are using

### Dependencies
- Finish icon choices for site

### Action Items
- [ ] Determine format/method of displaying resource licenses and descriptions.

### Goals
- [ ] Display license file link
- [ ] Source of icon
- [ ] What modifications were made

### Resources/Instructions
[Creating a table in markdown](https://help.github.com/en/github/writing-on-github/organizing-information-with-tables)
[Wiki/Resources](https://github.com/hackforla/website/wiki/resources)

Place the links to the files for license files here:

**Comment by ExperimentsInHonesty** [comment]
See https://github.com/hackforla/website/issues/296 - for icon update details.

**Comment by ExperimentsInHonesty** [comment]
After research it was determined that we needed to place the credits on the site, so we are building that page.  See issue #571
