### ISSUE TITLE
Remove unused alt-text field in toolkit guides html files: github-issues, use-of-images, 1password (file names abbreviated)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2930]
### Overview
As a developer, I want to make sure unused code is removed from the codebase in the guide pages' HTML files, so that 
- time to load the website is as low as possible, 
- it's easier to understand the code, and 
- time to review the code is reduced. 

For this issue, we will remove the unused alt-text fields from the guide pages' HTML files.

### Details
At the top of each guide pages' HTML file, there is a section containing YAML front matter, which contains variables that can be accessed using Liquid tags. (See the links in the Resources/Instructions section for more information about front matter and Liquid tags.) 

In the front matter of each guide pages' HTML file, there are the variables: `svg` and `alt-text`. `svg` field contains the location of a decorative image and `alt-text` is the alt text associated with the `svg` image.  Currently, `alt-text` is not used anywhere in our codebase since the images are not used within an `img` HTML tag and the images are displayed through svg HTML tags. 

Moreover, the alt text for all the images should be `alt=""` and will be programmatically set for all the alt properties associated with each image in issue #2929. 

### Action Items
- [x] Remove the line of code with the `alt-text` field in the following files only:
  - [x] github-issues.html
    https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/github-issues.html#L19
  - [x] responsible-use-of-images-on-opensource-projects.html
    https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/responsible-use-of-images-on-opensource-projects.html#L10
  - [x] setting-up-1password-on-opensource-project.html
    https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/setting-up-1password-on-opensource-project.html#L10
- [x] The guide pages' HTML files are used on the website in the Toolkit page and the guides linking from the Toolkit page.
  - [x] Check the Toolkit page and make sure it looks the same as the current [Toolkit page](https://www.hackforla.org/toolkit/)
  - [x] Check each guide page by clicking on its link in the Toolkit and making sure it looks the same as guides on the current website

### Resources/Instructions
- [Information about Front Matter as used by Jekyll](https://jekyllrb.com/docs/front-matter/) 
- [Introduction to Liquid, including information on tags](https://shopify.github.io/liquid/basics/introduction/)
- [Toolkit page](https://www.hackforla.org/toolkit/)
- Directory to find the files once you have it in your IDE: _guide-pages
- Click on the links below to see the code for each file:
  - https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/github-issues.html#L19
  -  https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/responsible-use-of-images-on-opensource-projects.html#L10
  - https://github.com/hackforla/website/blob/da9579386570cb1e1ba6b72d20e76df9ae04d1e9/_guide-pages/setting-up-1password-on-opensource-project.html#L10

**Comment by juliansmith0** [comment]
Availability for this week: 4.5 hours
My estimated ETA for completing this issue: Sunday, May 29, 2022
