### ISSUE TITLE
BOP project page not connected to its GitHub repo properly

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2934]
### Overview
As a developer, I want the data on all our project pages to be up to date. For this issue, we will fix an error on the [BOP project page](https://www.hackforla.org/projects/brigade-organizers-playbook) where all-time contributors are not getting displayed.

### Action Items
- [x] Review the [project.md file template](https://github.com/hackforla/website/wiki/project.md-file-template) for tips on how data for the 'contributors' section is pulled from the project's GitHub main repository using the GitHub API
- [ ] Review [brigade-organizers-playbook.md](https://github.com/hackforla/website/blob/gh-pages/_projects/brigade-organizers-playbook.md?plain=1) file and [project.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js) file
- [ ] Fix the error and ensure that the data is getting pulled on the BOP project page in your own repo
- [ ] Make sure existing functionalities are not impacted by the change

### Resources/Instructions

<details>
<summary>Screenshot of error</summary>

![BOP project page error](https://user-images.githubusercontent.com/843538/162287381-63958c26-e5b8-43cd-a3e2-0bafcffb865a.PNG)

</details>

- [BOP project page](https://www.hackforla.org/projects/brigade-organizers-playbook)
- [project.md file template](https://github.com/hackforla/website/wiki/project.md-file-template)
- [brigade-organizers-playbook.md](https://github.com/hackforla/website/blob/gh-pages/_projects/brigade-organizers-playbook.md?plain=1) file
- [project.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js) file
- Related comments: https://github.com/hackforla/website/issues/2605#issuecomment-1013941235 and https://github.com/hackforla/website/issues/2605#issuecomment-997477244

**Comment by kathrynsilvaconway** [comment]
Availability: 5-6 hours
ETA: End of the day on 4/10

**Comment by JessicaLucindaCheng** [comment]
@kathrynsilvaconway This issue is not ready to be worked on. I will be unassigning you from this issue. Please work on an issue from the Prioritized Backlog. (Below are detailed instructions for how to do that.)

**How to find issues to work on:**
1) In the "Onboarding info/links" column on the far left of the Project Board, scroll down the column until you see the cards that say "Sort by Front-end Issues" and "Sort by Back-end Issues".
<img width="973" alt="Filter-cards" src="https://user-images.githubusercontent.com/31293603/159599628-3961821f-50ad-4f82-9f81-de924ff083e7.png">

2) Then, you can filter by role and complexity by clicking on the links in those cards. Since you were looking for a front-end small issue, click on the "Small" link for the "Sort by Front-end Issues" card.

3) After applying the filters, pick the top issue from the "Prioritized Backlog" column to work on because that issue has been prioritized with the highest priority compared to the other small, front-end issues.

**Comment by RyanCahela** [comment]
Availability: Weekdays, 3-5PM.
ETA: Friday 4/22/22.

**Comment by RyanCahela** [comment]
@SAUMILDHANKAR @JessicaLucindaCheng

I've been trying to run get-project-data.js in a sandbox on my machine but I get stopped by the rate limit for unauthenticated requests. I know there is a reference to a process.env.token on line 17.

I'm wondering if there is an official auth token I can use locally to find out when and where the script is failing?

The more I look at the script the more I think those error messages we saw in github actions are related to this bug. It throws an error right as it is supposed to output the contributors for the BOP handbook.


ETA update: maybe Tuesday 4/26/22

**Comment by SAUMILDHANKAR** [comment]
@RyanCahela Hi Ryan, thanks for bringing this up. Looks like a good approach to me but, unfortunately, I am not aware if there is an official auth token that can be used. I will keep an eye out for it and will check with PM as well but that would be towards the end of the week. Sorry for the delay.

**Comment by RyanCahela** [comment]
@SAUMILDHANKAR @JessicaLucindaCheng @tamara-snyder

I think I've found a solution for this bug, it's in get-project-data.js on line 166 "cfa" should be changed to "codeforamerica". 

I'm trying to test the solution by manually running the "update github data" action in my forked repo. I'm getting a 'Input required and not supplied: token" error. 

There is a reference to  ```token: ${{ secrets.HACKFORLA_BOT_PA_TOKEN }}``` in github-data.yml are there any environment variables you guys have access to that I could use to run this action in my repo to test this solution?

Let me know if there is a better way of testing this.

**Comment by SAUMILDHANKAR** [comment]
@RyanCahela Great job in figuring out the changes required. Yes, I do have access to the repo token that you mentioned and we can use it for testing. Just want to make sure that we change it once the test is complete. So, please let me know how and when you would like the token to be shared. We can also setup some time around Tuesday meeting time or some other time if you would prefer to do it in a team setting. Thank you.

**Comment by RyanCahela** [comment]
Hey @SAUMILDHANKAR sorry for the delayed reply, I'm going out of town today and I'll be back Wednesday. If you want to slack me the token I can work on the testing next Wednesday and if I run into any problems I'll join the Thursday office hours. Let me know if that would be the best way to send the token or if there is a better way you had in mind. Thanks!

**Comment by SAUMILDHANKAR** [comment]
@RyanCahela Sounds good to me. Will share the token on slack, however, just wanted to check if we change the repo in [line 11](https://github.com/hackforla/website/blob/857d3161b00c01b73fe35318dcb248248d2093da/.github/workflows/github-data.yml#L11) to your personal repo and also create a test bot account with similar privileges as hackforlabot account, we can avoid sharing the token. Please let me know your thoughts. Thank you.

**Comment by SAUMILDHANKAR** [comment]
@RyanCahela Hi Ryan, another approach that came up during our tech lead meeting discussion was to create a PR without testing in your repo. Since, the change is minor (changing 'cfa' to 'codeforamerica') the risk is low, we can try it for a day and revert if required. Look forward to hearing from you.

**Comment by SAUMILDHANKAR** [comment]
Reopening this issue and moving it back to In-progress column as we are still testing if the code changes will work correctly and as expected in our main hackforla/gh-pages branch. Will revisit this issue in 2-3 days and close it if workflow run goes well or will revert the above PR as soon as an error is detected.

**Comment by answebdev** [comment]
@SAUMILDHANKAR and I had a discussion and we went over the code, and we couldn't find anything that would be an issue because of the code changes. Since everything looks fine, we are closing this issue.
