### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#2935]
### Overview

As a dev

### Action Items

- [ ] This is an action item
- [ ] Action item

### Resources/Instructions

- links

### Is there a dependency?

Yes

### If Yes, please explain

Need dependency

**Comment by JessicaLucindaCheng** [comment]
Reopening to test how issues work with beta project board

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng This is not on the board, please decide what to do with it

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty I'm going to go ahead and close it.
