### ISSUE TITLE
Edit contents of add-labels-template.md file

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2939]
### Overview
As a developer, I need to edit contents of [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md) file so that the members who are not part of the website repo would get notified about their inability to add labels

### Action Items
- [x] Review [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md) and [issue-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml) files
- [x] Add a note for the team members (who do not have write access for the website repo) to ignore the comment about adding labels to the [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md) file
- [ ] Test if the updated comment gets posted on an issue in your own repo

### Checks
- [ ] For testing in your own repo (after making the necessary code changes)
    - [ ] Create a project board in your own repo
    - [ ] Create a new issue and add it to one of the newly created columns (do not add labels to your issue so that [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md) file gets triggered)
    - [ ] Make sure the post with updated comment gets posted on your issue
- [ ] Make sure all the functionalities in [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md) file still work fine

### Resources/Instructions
- File where changes need to be made [add-labels-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/add-labels-template.md)
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)

**Comment by poorvi4** [comment]
Availability: Monday, Wednesday, Thursday 9-11 pm
Estimated time to complete: 5 hours (not familiar with github automations)

**Comment by JessicaLucindaCheng** [comment]
@poorvi4 
Please give a progress report in a comment in this issue. See what you need to include in your progress report and more information in [section 2.5 Reporting progress on your issue in CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#25-reporting-progress-on-your-issue)

**Comment by JessicaLucindaCheng** [comment]
@poorvi4 Your comment https://github.com/hackforla/website/issues/2964#issuecomment-1091133534 in the pre-work should be a comment in this issue. Once you have added the progress report to this issue, you can check off the "Progress Reports" check box in your pre-work checklist.

Also, please move this issue to the In Progress column.

@SAUMILDHANKAR Can you help Poorvi with their blocker?
