### ISSUE TITLE
Fix typo on citizen-engagement-card.html file from "throughout out" to "throughout"

### ISSUE THREAD

**Issue by answebdev** [hackforla/website#2942]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.

### Action Items

- [ ] For the file `pages/citizen-engagement-card.html`, on line 45, change the typo from "throughout out" to "throughout", so

  ```
  throughout out our communities.
  ```
  becomes
  ```
  throughout our communities.
  ```
- [ ] Make sure the changes look fine in your local environment. (For both desktop and mobile views)

### Resources
Website page with issue: https://www.hackforla.org/citizen-engagement
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/pages/citizen-engagement.html
Line of code:
https://github.com/hackforla/website/blob/6c99fa3042ac616ae9e7ab456c157b842be441fb/pages/citizen-engagement.html#L45

**Comment by scarter31191** [comment]
Availability for this week: 3/25
My estimated ETA for completing this issue: 3/25
