### ISSUE TITLE
Move old, closed issues off the Project Board

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#2955]
### Overview
As a developer, I want to move old, closed issues (that are in the Done column) from the "Project Board" to the "Issues Closed 13 months or more" project so that the Project Board becomes easier to manage and faster to respond.

### Action Items
- [ ] Please go through the wiki article on [Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
- [ ] Review the files in the following directories: `website/.github` and `website/github-actions`
- [ ] **Note: Issues that are closed and have been in the done column for more than 30 days should be moved from the ["Project Board"](https://github.com/hackforla/website/projects/7) to the ["Issues Closed 13 months or more"](https://github.com/hackforla/website/projects/14) project**
- [ ] This automation should run weekly.
- [ ] Analyze if a new GitHub action should be created or any of the existing actions can be modified.
- [ ] Add the code logic to implement this functionality in your own repo first.
- [ ] Make sure existing functionalities are not impacted and finally create a pull request.

### Checks

- [ ] Test in your local environment that it works
- [ ] Issues that are closed and have been in the done column for 30 days should automatically be moved to a new project board
- [ ] Issues that are open and in the done column shouldn't be moved to the new project board.

### Resources/Instructions
[Project Board](https://github.com/hackforla/website/projects/7)
[Issues Closed 13 months or more project](https://github.com/hackforla/website/projects/14)
Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)

#### Architecture Notes

The idea behind the refactor is to organize our GitHub Actions so that developers can easily maintain and understand them. Currently, we want our GitHub Actions to be structured like so based on this [proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015):

- Schedules (military time)
        - Schedule Friday 0700
        - Schedule Thursday 1100
        - Schedule Daily 1100
- Linters
        - Lint SCSS
- PR Trigger
        - Add Linked Issue Labels to Pull Request
        - Add Pull Request Instructions
- Issue Trigger
        - Add Missing Labels To Issues
- WR - PR Trigger
        - WR Add Linked Issue Labels to Pull Request
        - WR Add Pull Request Instructions
- WR - Issue Trigger

Actions with the same triggers (excluding linters, which will be their own category) will live in the same github action file. Scheduled actions will live in the same file if they trigger on the same schedule (i.e. all files that trigger everyday at 11am will live in one file, while files that trigger on Friday at 7am will be on a separate file).

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by Carlos-A-P** [comment]
Availability: 2 week
ETA: 6/01/2022

**Comment by kathrynsilvaconway** [comment]
Hi Carlos, I am moving this over to the 'in progress' column for you.

**Comment by Carlos-A-P** [comment]
1. Progress - Currently still learning how to approach this issue while I'm learning more about GitHub actions
2. Blockers - no blockers at the moment
3. Availability - 1 week
4. ETA - 6/8/2022

**Comment by ExperimentsInHonesty** [comment]
We will not be doing this automation.  We have decided instead to use the archive feature.

**Comment by ExperimentsInHonesty** [comment]
I don't think there is a decision record for this. I am adding a ready for product label on it and sticking it in the new issue approval column so that we can write something up about the process.

**Comment by ExperimentsInHonesty** [comment]
We have resolved this by archiving the done column periodically.
