### ISSUE TITLE
[Draft] Revise order on footer to match the join page

### ISSUE THREAD

**Issue by Providence-o** [hackforla/website#2958]
### Overview
We want to revise the order on the footer to match the join page on the HFLA website
### Action Items
- [ ] Visit the Join us page 
- [ ] Make a list of all of the section in the order that they appear on the page 
- [ ] Edit figma to match the order 

### Resources/Instructions
[Current footer design](https://github.com/hackforla/website/issues/2393)
[Join us page](https://www.hackforla.org/join)

**Comment by ExperimentsInHonesty** [comment]
- we are still working on this issue.  It stems from #2481

**Comment by ExperimentsInHonesty** [comment]
This issue can be closed.  The current footer in [figma, footer page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3417%3A3) says 
#### Join Us
- Donate
- Advise Us
- Volunteer with Us
- Partner with Us
- Submit your Pitch

**Comment by ExperimentsInHonesty** [comment]
I want to make sure before I archive this that the requirements have been translated to a development issue on the feature branch

**Comment by ExperimentsInHonesty** [comment]
- It got implemented on https://github.com/hackforla/website/issues/2393
