### ISSUE TITLE
Fix Trophy link on the Credits page on the HFLA website

### ISSUE THREAD

**Issue by Providence-o** [hackforla/website#2960]
### Overview
We need the external link for each image on the credit page to go to it's source. 

#### Details
The Trophy link on the [Credits page](https://www.hackforla.org/credits/) goes to "Page Not Found" on the external website [The Noun Project website](https://thenounproject.com/). We need to figure out the correct image and let the dev team know the link. 

### Action Items
- [ ] Browse [the nouns project](https://thenounproject.com/browse/icons/term/trophy/?iconspage=1) website for the correct icon that exists on the [credits page](https://www.hackforla.org/credits/)
- [ ] copy the link to the correct icon and let the development team know so that it can be fixed. 
  - [ ] If the correct icon cannot be found, select a new image (it has to fit with the icons on [this page](https://www.hackforla.org/about/#accomplishments)) and provide the corresponding link to the development team, then update the [figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692)
- [ ] Release dependency on issue #2674 

### Resources/Instructions
  <details>
      <summary>Screenshot of problem: Trophy link on Credits page</summary>
      <img width="212" alt="credits-trophy-link" src="https://user-images.githubusercontent.com/31293603/150619089-7b84154d-6c73-4ed8-977f-8d1059fbee98.png">
    </details>

**Comment by ExperimentsInHonesty** [comment]
The rep from the Noun project said we don't need to make a change when their icon disappears from their collection.

![image](https://user-images.githubusercontent.com/37763229/161402843-d47e6b55-52df-48d1-88ba-705980ceefda.png)
