### ISSUE TITLE
Partners: Change the image for Los Angeles County Homeless Initiative

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3016]
### Overview
As a developer, I want the logos for our partners to be up to date so that 
- we maintain professionalism on our website and 
- are consistent with the current logos the partners use for themselves. 

For this issue, we will replace an old partner logo image with a new one.
 
### Action Items
- [x] Remove `real-help-lasting-change.svg` from `assets/images/partners` directory
- [x] For the new image:
  - [x] Download the new image from https://homeless.lacounty.gov/wp-content/uploads/2018/09/HI_Logo_lasting-change-v3.png
  - [x] Rename the new image to `la-county-homeless-initiative.png`
  - [x] Add the new image to `assets/images/partners` directory
- [x] For `The Los Angeles County Homeless Initiative` in [_data/internal/partners.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/partners.yml), update the link for the image field so it points to the new image you added to `assets/images/partners` directory
- [x] In the [Partners section on the About Us page](https://www.hackforla.org/about/#partners), check the image looks good on mobile, tablet, and desktop views using developer tools

### Resources/Instructions
- Image to remove: [real-help-lasting-change.svg](https://github.com/hackforla/website/blob/gh-pages/assets/images/partners/real-help-lasting-change.svg)
- Link to new image: https://homeless.lacounty.gov/wp-content/uploads/2018/09/HI_Logo_lasting-change-v3.png
- [_data/internal/partners.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/partners.yml)
- [Partners section on the About Us page](https://www.hackforla.org/about/#partners)

**Comment by poorvi4** [comment]
Availability: March 27th, 10:00-11:00 pm
Estimated time needed: 3 hours

**Comment by JessicaLucindaCheng** [comment]
@poorvi This issue is not ready to be worked on. I will be un-assigning you from this issue. Please pick and work on a Small issue from the Prioritized Backlog column. Here is more information on where to find issues to work on: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#23-where-can-i-find-github-issues-to-work-on

**Comment by poorvi4** [comment]
Ah ok that makes sense and thank you!

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng is this ready for me to put a milestone on it?  Not sure why its still in draft

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 
> @JessicaLucindaCheng is this ready for me to put a milestone on it? Not sure why its still in draft

It's ready for you to put a milestone on now.

**Comment by RyanCahela** [comment]
Availability: 4/12/22 2PM - 5PM
ETA: 3 Hours
