### ISSUE TITLE
CONTRIBUTING.md: Additional Column Filtering Description in Section 2.2

### ISSUE THREAD

**Issue by Sparky-code** [hackforla/website#3018]
### Overview

As a developer, I would like to clarify the process for choosing new issues to work on, so that higher priority issues can be worked upon first. 

### Details

Feedback from new members found that practice for choosing most time sensitive issues wasn't entirely clear. This issue aims to reiterate the best practice.

### Action Items

- [x] Add the text specified below to the bottom of section 2.2, but **before** the current note.

Text:
```Note: The Prioritized Backlog column is filtered so the first (top) issue has the highest priority and should be worked on next.```

- [x] Add a line break between the notes. 
- [x]  To see the visual changes for the CONTRIBUTING.md and make sure the changes look good:
  - [x] Push the changes to your remote forked repo's topic branch
  - [x] Go to your remote forked repo on GitHub
  - [x] Switch to your topic branch
  - [x] Click on the CONTRIBUTING.md file
  - [x] On the upper right, click on "Display the rendered blob" to see what your changes look like. Here is an image of what 
  the "Display the rendered blob" button looks like:
  
<details><summary>Image of "Display the rendered blob" button</summary>

<img width="320" alt="" src="https://user-images.githubusercontent.com/31293603/161406861-26ace7b4-26b6-4981-9514-be8f651f5d6e.png">

</details>

### Resources/Instructions

[Link to CONTRIBUTING.md section 2.2 - How hack for la organizes issues](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#22-how-hack-for-la-organizes-issues) 

### Is there a dependency?

No

### If Yes, please explain

N/A

**Comment by SAUMILDHANKAR** [comment]
@Sparky-code Just wanted to share with you some of the formatting edits I made to the issue:
- Enclosed your note in triple backticks, to create a fenced code block which is easier to copy
- Added your image to a collapsible dropdown

Thanks again for writing the issue.

**Comment by Olanrewaju-Ak** [comment]
ETA: End of the day on 6/10
Availability: 1 hour
