### ISSUE TITLE
Partners: Change the image for Golden Gate University School of Law

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3025]
### Overview
As a developer, I want the logos for our partners to be up to date so that 
- we maintain professionalism on our website and 
- are consistent with the current logos the partners use for themselves. 

For this issue, we will replace an old partner logo image with a new one.
 
### Action Items
- [x] Remove `ggu-school-of-law.png` from `assets/images/partners` directory
- [x] For the new image:
  - [x] Download the new image from https://law.ggu.edu/media/shared/images/logos/2021/law-stack.png
  - [x] Rename the new image to `ggu-school-of-law`
  - [x] Add the new image to `assets/images/partners` directory
- [x] For `Golden Gate University School of Law` in [_data/internal/partners.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/partners.yml), make sure the link for the image field points to the new image you added to `assets/images/partners` directory
- [x] In the [Partners section on the About Us page](https://www.hackforla.org/about/#partners), check the image looks good on mobile, tablet, and desktop views using developer tools

### Resources/Instructions
- Image to remove: [ggu-school-of-law.png](https://github.com/hackforla/website/blob/gh-pages/assets/images/partners/ggu-school-of-law.png)
- Link to new image: https://law.ggu.edu/media/shared/images/logos/2021/law-stack.png
- [_data/internal/partners.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/partners.yml)
- [Partners section on the About Us page](https://www.hackforla.org/about/#partners)

**Comment by KazushiR** [comment]
I will go ahead and start working on this issue.

**Comment by JessicaLucindaCheng** [comment]
@KazushiR 
- At the time you self-assign an issue, please move this issue to the In Progress column.
- At the time you self-assign an issue, make sure to write in a comment the following:
  - Availability: "How much time will you have this week to work on this issue?"
  - ETA: "When do you expect this issue to be completed?"

**Comment by ExperimentsInHonesty** [comment]
@KazushiR

Please respond to Jessica's message above https://github.com/hackforla/website/issues/3025#issuecomment-1089629351

**Comment by KazushiR** [comment]
```````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````````

> @KazushiR
> 
> * At the time you self-assign an issue, please move this issue to the In Progress column.
> * At the time you self-assign an issue, make sure to write in a comment the following:
>   
>   * Availability: "How much time will you have this week to work on this issue?"
>   * ETA: "When do you expect this issue to be completed?"
Hello Jessica,
Please see below for response.

Availability: 2-3 hours this week.
ETA: I expect the issue to be completed in the week or two.
