### ISSUE TITLE
Events page: Remove projects from Our Locations section

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3027]
### Overview
As a developer, I want to update the Our Locations section on the [Events page](https://www.hackforla.org/events/) so that it reflects Hack for LA going fully remote and no longer doing in-person meetings. For this issue, we will remove projects from the Our Locations section on the [Events page](https://www.hackforla.org/events/) following the new Figma design for it.

#### Screenshots of the New Our Locations Section on Events Page
Below are screenshots of the updates but please reference the [Events page Figma design in the red box](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18738%3A126404) when working on this issue to see more of the design and details more clearly.

<details>
  <summary>New Desktop Our Locations section on Events page</summary>
  <img width="874" alt="new-events-our-location-desktop" src="https://user-images.githubusercontent.com/31293603/161418445-cd6cf6b1-bf09-4e7d-90dd-e798e74bc82d.png">

</details>

<details>
  <summary>New Mobile Our Locations section on Events page</summary>
  <img width="99" alt="new-events-our-location-mobile" src="https://user-images.githubusercontent.com/31293603/161418465-f78ae4cc-b562-4e81-b940-654d09b52e48.png">

</details>

### Action Items
- [x] Please reference the [Events page Figma design in the red box](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18738%3A126404) when working on this issue to see details of the design
- [x] Implement the desktop version of the new Our Locations section on the Events page
- [x] Implement the mobile version of the new Our Locations section on the Events page
- [x] Check the page looks good in mobile, tablet, and desktop views using developer tools
- [x] Give your email address associated with your Figma account to a merge team member or technical lead and request access so you can make edits in Figma
  - [x] In Figma, under the Large Cards section in the Design System, add the information for the Class, CSS, Uses, and Context Example columns for the [Events Card](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=6195%3A42255)

### Resources/Instructions
- [Events page](https://www.hackforla.org/events/)
- [Events page Figma design for the square version in the red box](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18738%3A126404)
- Code files to get you started. (Note: You may need other files.):
  - https://github.com/hackforla/website/blob/gh-pages/pages/events.html
  - https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/our-locations-content.html
  - https://github.com/hackforla/website/blob/gh-pages/_sass/components/_events.scss
- [Events Card in Design System in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=6195%3A42255)
- Related design issue: https://github.com/hackforla/website/issues/2497
- Tracked in https://github.com/hackforla/website/issues/2481#issuecomment-968349924

**Comment by kathrynsilvaconway** [comment]
ETA: 5/17/22 End of day.
Availability: 12 hours

**Comment by A-BMT02** [comment]
Availability: 2 hours
ETA: in 24 hours

**Comment by A-BMT02** [comment]
Blocker : What should be the breakpoint  from the mobile to desktop

**Comment by geedtd** [comment]
Availability this week Friday-Sunday before 2PM
Estimated Completion Sunday around Noon, unless I run into unforeseen bugs

**Comment by kathrynsilvaconway** [comment]
@geedtd 
Hi, this issue has not been updated in over 2 weeks. If you are still interested in working with HfLA, please let us know by updating your ETA and Availability. If we don't hear back within 7 days, we will unassign you from this issue and put it back in the queue. Thanks!

**Comment by JessicaLucindaCheng** [comment]
@geedtd Since we haven't heard back from you, I'm unassigning you from this issue.

**Comment by roslynwythe** [comment]
Availability: 10 am - 7 pm 11/9, 10 am - 6 pm 11/10, 10 - 2 11/11, 10 -2 11/13, 10-noon 10/14
ETA: 11/15

**Comment by roslynwythe** [comment]
@JessicaLucindaCheng please advise - From Figma I see that in desktop view, the three location images are displayed in a single row, and in the mobile version, they appear in a single column.  However Figma contains no tablet design, so I'm wondering, in tablet view would it be ok if one of the images wraps down to the next row?  Please see the Toolkit page http://localhost:4000/toolkit/, in the External Resources section, which has a similar design and is implemented using flexbox.  Note that at tablet size there are two rows of images and the bottom row is left justified.  I would like to use a similar css approach but just want to check that the tablet view is acceptable.

**Comment by roslynwythe** [comment]
Progress: large screen looks good, mobile version almost ready, need a bit of work on tablet version.  The location images are not scaling properly moving between mobile and tablet views.  

Blockers: This isn't blocking yet but I will need access to Figma to update styles for event-card, also I'm unclear on the process for updating Figma (version control?).  Request made to @kathrynsilvaconway 

Availability: I can work 3 hrs 11/13, 3 hrs 11/14, no time 11/15, 4 hrs 11/16

ETA: EOD 11/16

I have to admit, I don't know how to take a picture of the entire page.  I have a small device at max res so I'm show screen shots of just the events location portion of the page, and it appears cut off but that is just because the screen is too small.  


![image](https://user-images.githubusercontent.com/5314153/201516971-2ce035c2-6652-44d2-97e3-bad122ebb65a.png)

![image](https://user-images.githubusercontent.com/5314153/201518333-a68073ca-4956-45b6-9412-70ae035c5a57.png)

![image](https://user-images.githubusercontent.com/5314153/201518594-213e5528-c1cf-4d34-8db7-f3371c6f7040.png)
