### ISSUE TITLE
Project Description Page: Add Problem, Solution, and Impact Section

### ISSUE THREAD

**Issue by phuonguvan** [hackforla/website#3034]
### Overview
We need to design an additional section on each individual project page that displays the Problem, Solution, and Impact & SDG info so that development can build the content into the site.

### Details
The content design has already been created (sort of), on the Citizen Engagement page.  But it may or may not fit onto the current width of the project page

### Action Items
- [x] Review the Citizen Engagement project card display layout (Figma and online)
- [x] Review the Project Pages layout (Figma and online)
- [x] See if you can fit the card in between two of the existing cards.  If it doesn't fit (the content is too wide, etc.), brainstorm ideas about how you might reformat the content on that card to work with the layout of the project page. 
- [x] Review ideas with the design lead
- [x] Design low-fi prototypes of the section in mobile and desktop views 
- [x] Decide if it goes before or after the resources section in the project description
- [x] Review low-fi designs with the design and product lead 
- [x] Design hi-fi prototypes of the section
- [x] Review hi-fi designs with the design lead 

#### Current page layouts
- [Example of a Current Project Page](https://www.hackforla.org/projects/311-data)
- [Example of the Problem, Solution, Impact  & SDG info layout on Citizen Engagement page](https://www.hackforla.org/citizen-engagement)

#### Where to find words to use in your mockup
- [Program Areas Audit](https://docs.google.com/spreadsheets/d/1wkzmWck-aGTzGxiryYEUhGbKRJX8rDDT3RLsAn-E-9o/edit#gid=0) - This spreadsheet will tell you which SDG to use in your mockup for a specific project
- [Writing Draft for Problem, Solution, Impact](https://docs.google.com/document/d/16BZINmiMZLBDrRwuFlRqY63wtf_7fFV67ZhaLCstuUE/edit) - This document has the current wording for what to use in your mockup for the Problem, Solution & Impact

#### Figma files
- [Design Systems](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node)
- [Figma - Citizen Engagement page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3625%3A0)
- [Figma - Individual Project Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=7891%3A0)

**Comment by gold-o** [comment]
Availability for this week:

1. Progress: I have brainstormed ideas for the issue and need to review them with the design lead
2. Blockers: N/A
3. Availability: 5 hours
4. ETA: Second week of May

Images:

![image](https://user-images.githubusercontent.com/38343775/165625445-fa01ac02-e218-4b00-8ad2-f1530f46966e.png)

**Comment by ExperimentsInHonesty** [comment]
@gold-o Phu and I reviewed your questions, and you can remove all of the items you suggested
✔️can remove picture
✔️make all text 16 pt
✔️don’t have to have the 311 title
✔️can lengthen card

**Comment by gold-o** [comment]
**Progress:** I have completed the low-fi prototypes and the design lead and I had a voting session with the team to decide which prototype to develop into a hi-fi prototype. I am currently in the progess of developing the hi-fi prototype.
**Blockers:** I have to brainstorm ways to enlarge the SDG icon and fit it into the prototype in progress
**Availability:** 4-6 hours
**ETA:** By the 5th of June
**Pictures:**

![Screen Shot 2022-05-29 at 11 44 25 AM](https://user-images.githubusercontent.com/38343775/170886741-4e47b128-3bfc-4eeb-b294-e098afc0af22.png)

**Comment by gold-o** [comment]
Progress: I have completed the hi-fi prototypes.
Blockers: N/A
Availability: N/A
ETA: This issue is completed (06/19)
Pictures: 

![Screen Shot 2022-06-20 at 12 37 28 AM](https://user-images.githubusercontent.com/38343775/174549562-aabe4ce2-a9dd-451b-9749-ac948b96ff6c.png)

**This is ready for development**

**Comment by kathrynsilvaconway** [comment]
@ExperimentsInHonesty Am I writing an issue to update the project page to the most recent Figma design? Just checking because this one is ready for dev, but it doesn't have any explicit action for me to take.

**Comment by ExperimentsInHonesty** [comment]
@kathrynsilvaconway Please make an issue for development to take the change to the project pages layout and make it into new code for the project pages.  Do this in a new feature branch.  Here is the page that they will edit https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html

**Comment by blulady** [comment]
- Not sure why this showed up in New Issue Approval today, but it is closed by issue #3547. If there is anything else we need to do with this, please make a comment, otherwise I think it can go into the done column.

**Comment by ExperimentsInHonesty** [comment]
Moving back to done and archiving.  It was in the new issue approval column because an issue had not been made, you just didn't see it until the day you mentioned it.
