### ISSUE TITLE
About Page: Allowing users to see highlights from each year in the Accomplishments Section

### ISSUE THREAD

**Issue by phuonguvan** [hackforla/website#3035]
### Overview
We need to have visitors who see the accomplishments in the about page, be able to understand the full breadth of what we have accomplished over the last two years, while not making the section so huge that no one looks at it.

### Details
- It should be broken up by year
- There should also be a way for product to be able to add the orgs achievements without having to send it back to design for reformatting each year

### Action Items
- [x] Interview Product to understand why we think we need all the previous accomplishments
- [x] Brainstorm ideas for designs 
- [x] Review ideas with the design lead 
- [x] Design low-fi prototypes of the section in mobile and desktop views 
- [x] Review low-fi designs with the design and product lead
- [x] Design hi-fi prototypes of the section
- [x] Review hi-fi designs with the design lead
- [x] Review the final designs with the design lead 

#### Current page layouts
[Accomplishments Section](https://www.hackforla.org/about/#accomplishments)

#### Figma files
- [Figma, About Page Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692)
- [Figma, Design Systems](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
- [Figma, Current pages](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A0)

- [Figma, Designer work file](https://www.figma.com/file/MVRUNtLFjuamihX8PQg2Ic/Hack-for-LA-about%2Faccomplishment?node-id=0%3A1)

- [2021 Q4 Accomplishments](https://docs.google.com/document/d/1bZ6BUtiq-eArLMExOtYYE_NJdjY-Vqt7nhdtEU8k-cA/edit)

**Comment by sijiapitts** [comment]
1. Progress: Shared my design ideas with Phu and received feedback. The next step is to create low-fi prototypes (web version) using the actual content. 
2. Blockers: No blockers on my end. Phu might need to check with the developers to see if we can use pictures in the accomplishment section. 
3. Availability: 6+ hours 
4. ETA: The low-fi prototypes will be completed by the next team meeting on 5/4

**Comment by sijiapitts** [comment]
1. Progress: Completed the web version Hi-fi design, waiting for review. For the mobile version, I created 2 solutions for the problem "users should be able to view 2020 and 2019 achievements easily after they finish broswing the 2021 achievements", waiting for review. 
2. Blockers: No blockers  
3. Availability: 6 hours

**Comment by sijiapitts** [comment]
1. Progress: Confirmed the final design for web and mobile. What's left: Check the margins. Design screens for 2019 and 2020 accomplishment
2. Blockers: No blockers
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: By the next meeting

**Comment by sijiapitts** [comment]
1. Progress: Completed the final design for web and mobile except for a few blockers. 
2. Blockers: - Missing 2019 accomplishments. - Missing program area for two projects (indicated on the figma file). - Heading is inconsistent (H4 on web, but H5 on mobile)

Solved Blockers: Font size on the dropdown menu is 14.4px. I have confirmed with Phu and changed them to 16px.

**Comment by sijiapitts** [comment]
1. Progress: Reviewed and confirmed the final design for web. Next step: Will do an audit on all the drop down menus (mobile view), then create an consistent drop down menu design. 
2. Blockers: Waiting for copies for: 2019 accomplishment National Day of Civic Hacking (NdoCH)
3. Availability: 5 hours 
4. ETA: By the next meeting

**Comment by sijiapitts** [comment]
- Working on ticket [#3277](https://github.com/hackforla/website/issues/3277)

**Comment by sijiapitts** [comment]
- Still working on Issue #3277  which is required for this issue

**Comment by ExperimentsInHonesty** [comment]
@sijiapitts 

Is this what you are waiting for on this issue?
National Day of Civic Hacking (NdoCH) program area: Justice
Climate Collabathon: Environment

**Comment by ExperimentsInHonesty** [comment]
@sijiapitts Hope you had a great break.  I want to get this issue closed out.  Can you review it and let me know what remains other than the 2019 text 


National Day of Civic Hacking (NdoCH) program area = Justice
Climate Collabathon program area = environment

**Comment by sijiapitts** [comment]
@ExperimentsInHonesty Hope you had a great holiday break too Bonnie. 

I reviewed everything and have updated the program areas. 

But we are still missing one thing: I noticed we don't have the copies for 2019 National Day of Civic Hacking (NdoCH). All the copies [on this file](https://docs.google.com/document/d/1bZ6BUtiq-eArLMExOtYYE_NJdjY-Vqt7nhdtEU8k-cA/edit) are for 2021 and 2020 projects. In 2019, we have two projects: National Day of Civic Hacking (NdoCH) and Slack Redactor. I found the copies for the Slack Redactor project on[ this design file ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=2390%3A0&t=VKKuoio3RmDyGHWy-4), but it seems like copies for the 2019 NdoCH is missing.

**Comment by sijiapitts** [comment]
1. Progress: Design completed. Waiting for the missing content. 
2. Blockers: No blockers. Justing waiting for the content. 
3. ETA: After the missing content is provided, the project can be completed within 1 day.

**Comment by ExperimentsInHonesty** [comment]
National Day of Civic Hacking (NdoCH)
In 9/2019 Hack for LA joined Code for America brigades to work on Justice issues.  During this day long event, we developed a Journey map of the record clearance process which led to the launch of the Hack for LA Record Clearance project, now called Expunge Assist.

**Comment by sijiapitts** [comment]
Completed. Ready for development. The final design can be found [here ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=22519%3A129240&t=T4fUryG82CYBwkH5-4)

**Comment by ExperimentsInHonesty** [comment]
@sijiapitts It looks amazing! Thanks.

We will make a dev issue to build it.

**Comment by jdingeman** [comment]
I think it would look best to keep highlights grouped by program area rather than having each project listed with it's program area subheader. I think it'll give a cleaner look and naturally more categorical. I think this would also emphasize that there are multiple highlights per program area, rather than 1 highlight per project.

**Comment by blulady** [comment]
Just wondering how the yearly wins will be selected for display...

**Comment by ExperimentsInHonesty** [comment]
We will be sorting by program area for display

**Comment by ExperimentsInHonesty** [comment]
- The new issue for development is in draft here https://github.com/hackforla/website/issues/4188
