### ISSUE TITLE
Update Project Profile: Lucky Parking

### ISSUE THREAD

**Issue by gregpawin** [hackforla/website#3056]
### Overview
As a product manager of Lucky Parking I want my project's details to be up to date on the HackforLA website

### Project card
https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md

### Action Items
- [ ] In [_projects/lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md), update the [Lucky Parking](https://www.hackforla.org/projects/lucky-parking) Team Leadership as follows. If an item is already checked off, double check the information matches the info in [_projects/lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md).  
  - [x] name: Greg Pawin
    - [ ] role: Data Scientist Lead
    - [X] slack: 'https://hackforla.slack.com/team/UUEQF3AJG'
    - [X] github: 'https://github.com/gregpawin'
    - [X] picture: https://avatars.githubusercontent.com/gregpawin
  - [ ] name: Yuting Chu
    - [ ] role: Product Manager Lead
    - [ ] slack: 'https://hackforla.slack.com/team/U03J4E55KCH'
    - [ ] github: 'https://github.com/ychu196'
    - [ ] picture: https://avatars.githubusercontent.com/ychu196
  - [ ] name: Glen Florendo
    - [ ] role: Full-Stack Developer Lead
    - [ ] slack: https://hackforla.slack.com/team/UFQGH8JH0
    - [ ] github: https://github.com/glenflorendo
    - [ ] picture: https://avatars.githubusercontent.com/u/9373317
    - [ ] name: Michael Morgan
    - [ ] role: UX/UI Design Lead
    - [ ] slack: 'https://hackforla.slack.com/team/U01SPJCC26A'
    - [ ] github: 'https://github.com/mklmrgn'
    - [ ] picture: https://avatars.githubusercontent.com/mklmrgn
  - [ ] name: Yen Phan
    - [ ] role: User Research
    - [ ] slack: 'https://hackforla.slack.com/team/U025M9VRDJR'
    - [ ] github: 'https://github.com/ymphan'
    - [ ] picture: https://avatars.githubusercontent.com/ymphan
  - [ ] name: Yujin Chang
    - [ ] role: UI Designer
    - [ ] slack: 'https://hackforla.slack.com/team/U0270QURQCD'
    - [ ] github: 'https://github.com/eugenecha'
    - [ ] picture: https://avatars.githubusercontent.com/eugenecha
  - [ ] name: Jodie Chen
    - [ ] role: UI/UX Designer
    - [ ] slack: 'https://hackforla.slack.com/team/U03RFGLLAQG'
    - [ ] github: 'https://github.com/jojochen25'
    - [ ] picture: https://avatars.githubusercontent.com/u/103106753
  - [ ] name: Sijia Pitts
    - [ ] role: UI/UX Designer
    - [ ] slack: 'https://hackforla.slack.com/team/U03CBK89KUY'
    - [ ] github: 'https://github.com/sijiapitts'
    - [ ] picture: https://avatars.githubusercontent.com/u/103976231
  - [ ] name: Pratibha Shivanand
    - [ ] role: Data Scientist
    - [ ] slack: 'https://hackforla.slack.com/team/U03SM1LF9HD'
    - [ ] github: https://github.com/pratibhanagesh
    - [ ] picture: https://avatars.githubusercontent.com/u/8139348
  - [ ] name: Aletia Trepte
    - [ ] role: Data Scientist/Engineer
    - [ ] slack: 'https://hackforla.slack.com/team/U03KAPRML9Y'
    - [ ] github: https://github.com/parcheesime
    - [ ] picture: https://avatars.githubusercontent.com/u/38143160
  - [ ] name: Yao Guan
    - [ ] role: Quant UXR
    - [ ] slack: 'https://hackforla.slack.com/team/U03F35T4PND'
    - [ ] github: https://github.com/yaoguan
    - [ ] picture: https://avatars.githubusercontent.com/u/41702875
   - [ ] name: Diedrich Chavarria
     - [ ] role: Full Stack Developer
     - [ ] slack: 'https://hackforla.slack.com/team/U031VEUS0CW'
     - [ ] github: 'https://github.com/DCH-CH'
     - [ ] picture: https://avatars.githubusercontent.com/DCH-CH
   - [ ] name: Seymour Liao
     - [ ] role: Data Scientist
     - [ ] slack: 'https://hackforla.slack.com/team/U018XPTSTC6'
     - [ ] github: 'https://github.com/Seymour100'
     - [ ] picture: https://avatars.githubusercontent.com/Seymour100
   - [ ] name: David Lam
     - [ ] role: Data Scientist
     - [ ] slack: 'https://hackforla.slack.com/team/U02D8CDURF0'
     - [ ] github: 'https://github.com/davidlamcanada'
     - [ ] picture: https://avatars.githubusercontent.com/davidlamcanada
- [x] Also, add the Overview PDF by
  - [x] Downloading the PDF from https://github.com/hackforla/product-management/blob/master/project-one-sheets/Lucky-Parking-One-Sheet.pdf
  - [x] Adding the PDF to the `assets/pdfs` directory
  - [x] In the `links` section [_projects/lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md), add an `Overview` with a url that points to the PDF you added to `assets/pdfs` directory. (For an example of an Overview link in code, see [food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md?plain=1).)

### Resources
- File to make edits: https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md
- [Lucky Parking page](https://www.hackforla.org/projects/lucky-parking)
- https://github.com/hackforla/product-management/blob/master/project-one-sheets/Lucky-Parking-One-Sheet.pdf
- For an example of an Overview link in code, see [food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md?plain=1).

<details>
  <summary>Click here to see the original request for reference</summary>

  - [ ] Lucky Parking Team Leadership
     - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
        - [X] title
        - [X] description
        - [X] image
        - [ ] leadership
        - [x] name: Greg Pawin
           - [ ] role: Product Owner
           - [X] slack: 'https://hackforla.slack.com/team/UUEQF3AJG'
           - [X] github: 'https://github.com/gregpawin'
           - [X] picture: https://avatars.githubusercontent.com/gregpawin
        - [ ] name: Gordon Ruby
           - [ ] role: Product Manager Lead
           - [ ] slack: 'https://hackforla.slack.com/team/U02AJ61CSQP'
           - [ ] github: 'https://github.com/gordonruby'
           - [ ] picture: https://avatars.githubusercontent.com/gordonruby
        - [X] name: Matthew Cacho
           - [X] role: Full-Stack Developer Lead
           - [X] slack: 'https://hackforla.slack.com/team/U0262GA4DD2'
           - [X] github: 'https://github.com/macho-catt'
           - [X] picture: https://avatars.githubusercontent.com/macho-catt
        - [ ] name: Yen Phan
           - [ ] role: Lead User Research
           - [ ] slack: 'https://hackforla.slack.com/team/U025M9VRDJR'
           - [ ] github: 'https://github.com/ymphan'
           - [ ] picture: https://avatars.githubusercontent.com/ymphan
        - [ ] name: Yujin Chang
           - [ ] role: UX/UI Lead
           - [ ] slack: 'https://hackforla.slack.com/team/U0270QURQCD'
           - [ ] github: 'https://github.com/eugenecha'
           - [ ] picture: https://avatars.githubusercontent.com/eugenecha
        - [ ] name: Marie Li
           - [ ] role: Data Science Lead
           - [ ] slack: 'https://hackforla.slack.com/team/U01S72NLGAC'
           - [ ] github: 'https://github.com/zhao-li-github'
           - [ ] picture: https://avatars.githubusercontent.com/zhao-li-github
        - [ ] name: Michael Morgan
           - [ ] role: UX/UI Design
           - [ ] slack: 'https://hackforla.slack.com/team/U01SPJCC26A'
           - [ ] github: 'https://github.com/mklmrgn'
           - [ ] picture: https://avatars.githubusercontent.com/mklmrgn
        - [ ] name: Glen Florendo
           - [ ] role: Full Stack Developer
           - [ ] slack: 'https://hackforla.slack.com/team/UFQGH8JH0'
           - [ ] github: 'https://github.com/glenflorendo'
           - [ ] picture: https://avatars.githubusercontent.com/glenflorendo
        - [ ] name: Diedrich Chavarria
           - [ ] role: Full Stack Developer
           - [ ] slack: 'https://hackforla.slack.com/team/U031VEUS0CW'
           - [ ] github: 'https://github.com/DCH-CH'
           - [ ] picture: https://avatars.githubusercontent.com/DCH-CH
        - [ ] name: Seymour Liao
           - [ ] role: Data Scientist
           - [ ] slack: 'https://hackforla.slack.com/team/U018XPTSTC6'
           - [ ] github: 'https://github.com/Seymour100'
           - [ ] picture: https://avatars.githubusercontent.com/Seymour100
        - [ ] name: David Lam
           - [ ] role: Data Scientist
           - [ ] slack: 'https://hackforla.slack.com/team/U02D8CDURF0'
           - [ ] github: 'https://github.com/davidlamcanada'
           - [ ] picture: https://avatars.githubusercontent.com/davidlamcanada
        - [X] links
           - [X] Github
           - [X] Slack
           - [X] Test Site
           - [X] Demo Site
           - [X] Site
        - [X] technologies
        - [X] partner
        - [X] tools
        - [X] status
   - [x] Open an issue on VRMS to update the meeting times and provide the link to the new issue in the comment below
   
  ### Resources
  [VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

</details>

**Comment by JessicaLucindaCheng** [comment]
@riddle015 This issue is not ready to be worked on, so I will be unassigning you. Please pick an issue from the Prioritized Backlog column. (Below are detailed instructions for how to do so if you need it.)

**How to find issues to work on:**
1) In the "Onboarding info/links" column on the far left of the Project Board, scroll down the column until you see the cards that say "Sort by Front-end Issues" and "Sort by Back-end Issues".
<img width="202" alt="front-end-back-end-filters" src="https://user-images.githubusercontent.com/31293603/163284446-66cc2ad6-fd4a-427a-835d-afabcc640957.png">

2) Then, you can filter by role and complexity by clicking on the links in those cards. For example, if I was looking for a front-end medium issue, click on the "Medium" link for the "Sort by Front-end Issues" card.

3) After applying the filters, pick the top issue from the "Prioritized Backlog" column to work on because that issue has been prioritized with the highest priority compared to the other filtered issues.

**Comment by JessicaLucindaCheng** [comment]
@gregpawin There is an unchecked Action Item that says, "Open an issue on VRMS to update the meeting times and provide the link to the new issue in the comment below". Did you need your meeting times updated too? If yes, you will need to fill out [VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

**Comment by gregpawin** [comment]
Sorry, I didn't know what that meant. No, we don't need them updated. I went ahead and checked it.

**Comment by JessicaLucindaCheng** [comment]
@gregpawin 
> Sorry, I didn't know what that meant. No, we don't need them updated. I went ahead and checked it.

Thanks for letting me know. Sorry for the confusion. I agree that Action Item is confusing and will update the template so it is clearer

**Comment by ExperimentsInHonesty** [comment]
Also add the Overview doc.  Here is the PDF https://github.com/hackforla/product-management/blob/master/project-one-sheets/Lucky-Parking-One-Sheet.pdf

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty
> Also add the Overview doc. Here is the PDF https://github.com/hackforla/product-management/blob/master/project-one-sheets/Lucky-Parking-One-Sheet.pdf

I added Action Items for adding the Overview and its PDF in the issue above in order to make it clear for the developer that implements this issue.

**Comment by macho-catt** [comment]
ETA: By next Monday
Availability: 3 hours
Progress: Just started
Blockers: None

**Comment by macho-catt** [comment]
Status: Done and opened PR #3146 
ETA: N/A
Availability: 3 hours
Progress: Done and opened PR #3146 
Blockers: None

**Comment by macho-catt** [comment]
Status: Will do the changes requested in pr
ETA: by next Sun
Availability: 2 hours
Progress: need to update PR
Blockers: None

**Comment by gregpawin** [comment]
Updated Marie's title--no longer interested in being lead.

**Comment by macho-catt** [comment]
Status: Updated PR
ETA: n/a
Availability: 2 hours
Progress: updated PR
Blockers: None

**Comment by gregpawin** [comment]
Updated Product manager to current product manager

**Comment by ExperimentsInHonesty** [comment]
@gregpawin @macho-catt can you tell me what is going on with this issue?  I thought Matt was taking care of it, but I don't see the changes on the website.  If Matt is not going to do them, then @gregpawin if you could give this a final update, I will push this to the prioritized backlog so that a developer on our team can do it.

**Comment by gregpawin** [comment]
Last I spoke to Matt he said the issue required someone to review and we
were waiting for a review from the dev team. Unfortunately, the issue has
been open so long, I'd have to redo the team roster at this point. I'll
write another note on the issue tonight.

**Comment by blulady** [comment]
@gregpawin @ychu196
Can you guys give us an update on changes you want to the Hack For LA Page Lucky Parking

**Comment by ychu196** [comment]
@blulady Greg and I are looking into this right now.

**Comment by ExperimentsInHonesty** [comment]
@ychu196 we are going to close this issue if we don't get an instructions from you by Sunday 2022-11-5.  We keep having to revisit it, unnecessarily

**Comment by gregpawin** [comment]
Apologies! We'll get back to you before Sunday.

**Comment by ExperimentsInHonesty** [comment]
@greg, I am closing this issue.  Should you want some changes to the hackforla website, please have @ychu196 open a [new project profile update issue](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D)
