### ISSUE TITLE
Demo Issue

### ISSUE THREAD

**Issue by Sparky-code** [hackforla/website#3060]
### Overview
What the title mean and **why**

### Action Items
what we are doing to accomplisth that

- [ ] dafa
- [ ] asdf
- [ ] asdf

### Resources/Instructions
Links

**Comment by JessicaLucindaCheng** [comment]
@Sparky-code When you close an issue you were using for demos, please add the `Ignore: Demo` label, so that QA knows they don't need to look at this issue. Thanks.
