### ISSUE TITLE
Update Project Profile: FOLA

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#308]
### Overview
Update the following fields for your project. These updated fields will then be updated to be shown on the website.

### Action Items
Provide in the comments below:
- [x] updated wording if necessary on the project card (see [hackforla.org](https://www.hackforla.org/))
- [x] information on which Tools your team is using for the project (Ex: figma, Balsamiq, photoshop, etc.) . This is different than programming languages
- [x] updates for "Looking For" Section
- [x] any updated links that are not currently displayed on the site (do you have a demo site?)
- [x] Hero image to be displayed on Project Home Page at 1500 x 700 px
- [x] any resources for a Getting Started link (either a link to a wiki or readme)

### Resources/Instructions
See the hero image on the [hackforla.org](https://www.hackforla.org/) homepage

**Comment by ExperimentsInHonesty** [comment]
Description: The website is focused on individuals seeking food in Los Angeles who need an up-to-date resource about food pantries and meals. Our mission is to update the existing website, foodoasis.la with a simplified UI and verified data. Future development goals include creating functionality for referral services that will allow the end user to annotate and update listings through a peer verification system.

Looking for: Project Management, Junior Python developers (2) , documentarian (UX) - specifically someone to help with the wiki for onboarding and communicating to stake holders what the project is about.

Hero image: https://github.com/hackforla/website/issues/308#issuecomment-584804725

Tools we use: figma, photoshop, sketch, pencil and paper, phone calls.
Testing site: http://food-oasis.herokuapp.com/ live site: foodoasis.la
readme: https://github.com/hackforla/food-oasis/blob/master/README.md

**Comment by ExperimentsInHonesty** [comment]
Needs the hero image to be applied.  Hero image in comment above https://github.com/hackforla/website/issues/308#issuecomment-584804725

**Comment by leonelRos** [comment]
Hero Image has been updated.
