### ISSUE TITLE
Update Project Profile: Home Unite Us

### ISSUE THREAD

**Issue by JRHutson** [hackforla/website#3084]
### Overview
As a product manager of Home Unite Us I want my project's details to be up to date on the HackforLA website

### Project card
https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md

### Action Items

- [x] Developer: Update the [Home Unite Us project info page](https://www.hackforla.org/projects/home-unite-us) Team Leadership as requested by the PM:
   - [x] PM: Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [x] leadership
         - [x] Remove Abiha Ali
         - [x] Add Ben Ross
              - [x] GitHub handle: @rossbb
              - [x] Role: Product Manager
              - [x] Slack ID: U03BZ5WL8GY
         - [x] Name
         - [x] GitHub handle
         - [x] Role
         - [x] SLACK ID
      - [x] links
         - [x] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] technologies
      - [x] partner
      - [x] tools
      - [x] status
 - [x] If you need updates to your meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue in the comment below: https://github.com/hackforla/VRMS/issues/1126

### Resources
- [VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)
- https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md
- [Home Unite Us project info page](https://www.hackforla.org/projects/home-unite-us)

**Comment by trishajjohnson** [comment]
Availability: 6hrs
ETA: EOD Thurs 5/19/22

**Comment by trishajjohnson** [comment]
Progress: Just need to review and submit for pull request.
Blockers: None
Availability: 1hr
ETA: EOD 5/20/22
Pictures: None
