### ISSUE TITLE
Order contributors by most recent commit 

### ISSUE THREAD

**Issue by cnk** [hackforla/website#311]
To encourage people to get involved, we want to order contributors by most recent commit rather than the total commits provided in the GitHub contributors API. This will require some manipulation of the contributors data.

Related to:  #282

**Comment by joelparkerhenderson** [comment]
Good idea! Here's how GitHub enables creating a commit with multiple authors: https://help.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors

**Comment by ExperimentsInHonesty** [comment]
@cnk Closing this issue.  Ultimately we decided that rewarding the most contributions over time so people could see themselves rising in the rankings was more valuable than initial encouragement to the final outome.
