### ISSUE TITLE
Edit label info for the HFLA wiki and contributing.md file

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#3110]
### Dependency
- [x] #3109  

### Overview
We are in the process of renaming the "Size" labels to "Complexity" to better clarify the purpose of the label. For this issue, we will edit the [contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) file and the [How to read and interpret labels](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels) wiki so that it has up-to-date information on our label names.

### Details
We are changing the following "Size" labels to instead be named "Complexity":
- ```Size: Good second issue``` to ```Complexity: Good second issue```
- ```Size: Small``` to ```Complexity: Small```
- ```Size: Medium``` to ```Complexity: Medium```
- ```Size: Large``` to ```Complexity: Large```

### Action Items
- [x] Review  [section 2.1](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#21-hack-for-la-contributor-expectations) , [section 2.2](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#22-how-hack-for-la-organizes-issues) and [section 2.3](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#23-where-can-i-find-github-issues-to-work-on) in the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) file
- [x] Appropriately update all references to the "size" label to instead be "complexity" for sections 2.1 through 2.3 of the  [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) by matching the casing as you swap the words
- [x] Appropriately update the [How to read and interpret labels wiki](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels) now that we are using "complexity" instead of "size" by matching the casing as you swap the words
- [x] Create a pull request for these changes to be merged
#### For Merge Team Only
- [ ] Once the pull request associated with this issue is merged, go to https://github.com/hackforla/website/labels and  update the following labels:
  - [ ] from `Size: Good second issue` to `Complexity: Good second issue`
  - [ ] from `Size: Small` to `Complexity: Small`
  - [ ] from `Size: Medium` to `Complexity: Medium`
  - [ ] from `Size: Large` to `Complexity: Large`
- [ ] Verify that all the project board and wiki links work properly after the changes have been merged. If they do not, create a `time-sensitive` issue to fix the links

### Resources/Instructions
- [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) file
    - [section 2.1](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#21-hack-for-la-contributor-expectations)
    - [section 2.2](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#22-how-hack-for-la-organizes-issues) 
    - [section 2.3](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#23-where-can-i-find-github-issues-to-work-on)

- [How to read and interpret labels](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels) wiki
    - [Size Series](https://github.com/hackforla/website/wiki/How-to-read-and-interpret-labels#the-size-series)

**Comment by JessicaLucindaCheng** [comment]
@MattPereira [Answering your question from Slack](https://hackforla.slack.com/archives/C0271FFEV0E/p1675289866209869). Here is an example of what you could put as an Action Item. 
#### Merge Team
- [ ] Once the pull request associated with this issue is merged, go to https://github.com/hackforla/website/labels and  update the following labels:
  - [ ] from `Size: Good second issue` to `Complexity: Good second issue`
  - [ ] from `Size: Small` to `Complexity: Small`
  - [ ] from `Size: Medium` to `Complexity: Medium`
  - [ ] from `Size: Large` to `Complexity: Large`

**Comment by vmaineng** [comment]
Availability for this week: Tuesday 10 - 12PM PST
My estimated ETA for completing this issue: I anticipate 2 hours.

**Comment by vmaineng** [comment]
This issue is still being worked on, but I have a question. I reached out to Matt Pereira if the 'size' in the hyperlinks in section 2.3b should be changed to 'complexity'. I'll start working on this after my question has been addressed.

**Comment by vmaineng** [comment]
I noticed some of the hyperlinks in section 2.3b in CONTRIBUTING.md file contains the word 'size' in it. I updated the 'size' in the hyperlinks to be changed to 'complexity'.
