### ISSUE TITLE
Fix alignment and scaling of resource links

### ISSUE THREAD

**Issue by Sparky-code** [hackforla/website#3118]
### Overview

As developers, we want to ensure that the behavior of the page is consistent between content types and across all platforms. For this issue, we will fix the mobile alignment of the Resources cards on the  project details pages.

### Action Items
- [x] Explore an individual project page in mobile view to see the alignment issues.
- [x] Edit the [_project-page.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-page.scss) file to center the Resources cards for mobile view 

### Instructions
-  On mobile, view the "Resources" section of the [100 Automations Project Page](https://www.hackforla.org/projects/100-automations). (Since all individual project pages draw from the same styling, you may choose any individual project page to use as a template for addressing this issue.) <details><summary>See Screenshot of Resources section on mobile</summary>![Screenshot from 2022-11-30 13-38-15](https://user-images.githubusercontent.com/73561520/204913743-c1c07271-17f9-47e9-b787-3c0487e2d814.png)</details>

### Resources
- [_project-page.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-page.scss) 
- [Media Query Variables File](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_layout.scss)

**Comment by JessicaLucindaCheng** [comment]
I think this issue is related to issue #2061

**Comment by kathrynsilvaconway** [comment]
@ExperimentsInHonesty 
How are the resource links meant to be displayed at these dimensions? Should they be left justified and three across like this? Should it be four across for the first row and two underneath? This issue addresses the fact that the links are left justified in the mobile view when they should be centered. Do we want them centered here too?
![image](https://user-images.githubusercontent.com/81049661/191876886-bd41415c-fda5-4a94-890c-5c8d275b7c00.png)

**Comment by ExperimentsInHonesty** [comment]
moved this from the icebox to new issue approval because the dependency is satisfied.

**Comment by MattPereira** [comment]
I am unable to locate the recommendations from the dependency that need to be transferred. See dependency:
- #3449

**Comment by jdingeman** [comment]
Hey @MattPereira, I think based on the result of the desktop version of the change, perhaps we want the mobile view to center the cards. I believe the box around the text of the titles stays the same as it does for the desktop view. 

When the cards wrap on desktop version, the last card gets pushed to the left. I don't think there is a figma mockup for the mobile design, so maybe we should discuss the look of when the cards wrap?

**Comment by MattPereira** [comment]
Hey @jdingeman I agree with centering the cards for mobile view. 

And I think pushing the last card to the left works fine for mobile view when the cards wrap and there is an odd number of resources.

But I have no idea what the original issue creator meant when they wrote 

> Edit the appropriate SCSS files ensure consistent scaling in mobile view" for the last action item. 

Also, are we concerned about the space between the cards being eliminated for screen widths between `490px` and `800px` ?

<details><summary> See space between screenshots</summary>
<img src="https://user-images.githubusercontent.com/73561520/211920516-2f862e1a-ff69-4704-9e7a-570570a40a52.png"/>

<img src="https://user-images.githubusercontent.com/73561520/211920737-88267409-77c6-4e85-8c74-1b81228454f8.png"/>

</details>

**Comment by jdingeman** [comment]
@MattPereira, for that last point, I think OIC is referring to any classes that are used in the mobile view that don't already exist in _project-page.scss.

As for the spacing - yes, the spacing should be configured so that the cards become centered in responsive views. As for how many cards exist on one line will depend on the card's retaining their size and how many can fit onto one line without squeezing too much of the space between.

**Comment by jdingeman** [comment]
Hi @MattPereira, I recommend centering the cards and keeping the space as it is for mobile view.

**Comment by Adaakal** [comment]
i. **Availability**: Sunday 2/12 & Monday 2/13 at 6-7p
ii. **ETA**: Wednesday 2/14

**Comment by Adaakal** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?" I just have to edit the [_project-page.scss] file to center the Resources cards for mobile view
Blockers: "Difficulties or errors encountered." 
I'm attending office hours to make sure I'm editing the right part of that .scss file. I think I am, but just want to confirm.
Availability: "How much time will you have this week to work on this issue?" 
I will work on it for about an hour or less.
ETA: "When do you expect this issue to be completed?"
By Sunday's All Hands.
Pictures (optional): "Add any pictures of the visual changes made to the site so far." N/A
