### ISSUE TITLE
Mobile Responsiveness Rejoice

### ISSUE THREAD

**Issue by Richey24** [hackforla/website#3119]
### Overview

<details>
<summary>TITLE IMAGE </summary>
![image](https://user-images.githubusercontent.com/77212035/134111368-bc5dfa08-0dd3-47be-a0e2-a60c6a362bf7.png)
</details>

### Design:

- [X] Check the mobile responsiveness of this page (use your mobile to do it ;) )
- [X] If there is any bug/any inconsistency or problem, however small or large, edit this issue and list the bug with screenshots in the Overview section above. _You have more than one bug? duplicate this issue and create one issue per bug. 
- [X] List all the changes to implement to correct the bug (eg: resizing..) in the development action items below. (don't hesitate to create 1 checkbox for each changes)
- [X] Put the issue(s) in the review column to check the feasibility with the devs. 

### Development

- [ ] Implement the following changes : '_list your changes here_ '
- [ ] Ensure that the correction doesn't break any other pages that is connected to the one your changing. For that, check  [the sitemap](https://www.hackforla.org/sitemap.xml)

### Resources/Instructions

Bootstrap

**Comment by SAUMILDHANKAR** [comment]
Closing this. Created by error.
