### ISSUE TITLE
Footer menu: Add link to the Privacy Policy page

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3129]
### Overview
As a stakeholder, I want a link to the [Privacy Policy page](https://www.hackforla.org/privacy-policy) in the footer menu so that visitors to the website can navigate to our Privacy Policy. 

### Action Items
- [ ] Add the link to the Privacy Policy page to the footer at the bottom of the website.
  - [ ] Currently, the footer shows:
      ```
      Credits | Site Map | Join Us
      ```
    Please add the privacy policy link in the following display order
      ```
      Credits | Site Map | Privacy Policy | Join Us
      ```
  - [ ] For "Privacy Policy" that you just added to the footer, it should link to `/privacy-policy`
- [ ] Check the change in the footer is seen throughout the website

### Resources/Instructions
- Related issue (comment): https://github.com/hackforla/website/issues/2555#issuecomment-1120350513
- Page you are changing is located here: _includes/footer.html

**Comment by Unity7** [comment]
ETA: 9/23/22
Availability: 2 Hours

**Comment by Unity7** [comment]
Having issues with Windows Docker.

Issue is ready to merge but I cannot get windows docker to load to make the screen shot to finish the PR.

**Comment by kimberlyvaldez07** [comment]
This is an image of the before:
<img src="https://user-images.githubusercontent.com/40401149/144154195-867292e4-e034-4631-8d3f-f1bfb05dae14.png">

This is the current footer 

<img width="1217" height="270" alt="Image" src="https://github.com/user-attachments/assets/b59b5638-77c2-4bb9-a006-82d983acc4de" />
