### ISSUE TITLE
Update Project Profile: EXPUNGE ASSIST

### ISSUE THREAD

**Issue by thomasdemoner** [hackforla/website#3135]
### Overview
As a product manager of EXPUNGE ASSIST I want my project's details to be up to date on the HackforLA website

### Project card
Insert url of your project card here before sending: https://github.com/hackforla/website/blob/gh-pages/_projects/expunge-assist.md

### Action Items

- [ ] EXPUNGE ASSIST Team Leadership
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in a new comment below:
      - [x] title
      - [x] description
      - [x] image
      - [ ] leadership
         - [ ] Name
         - [ ] GitHub handle
         - [ ] Role
         - [ ] SLACK ID
      - [ ] links
         - [x] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [ ] Site
      - [x] technologies
      - [x] partner
      - [x] tools
      - [x] status
 - [x] If you need updates to your meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue in a new comment below

### Resources
[VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

**Comment by thomasdemoner** [comment]
### Team leadership: REMOVE ALL CURRENT and ADD:

- Name: Thomas Demoner
   - Github handle: @thomasdemoner 
   - Role: Product Manager, Development
   - Slack ID: U02DFJ72V8Q

- Name: Valeriya Metla
   - Github handle: @ValeriyaMetla
   - Role: Product Manager, Research
   - Slack ID: U02NWJ2H8M6

- Name: Jamie Siu
   - Github handle: @jamiesiu
   - Role: Product Manager, Design
   - Slack ID: U036RQHGRRR

### Links: KEEP CURRENT and ADD:
- Product Website: https://expungeassist.org/

## Thank you!

**Comment by SAUMILDHANKAR** [comment]
@thomasdemoner I have checked off GitHub, Slack links as well as technologies since they don't need an update. Hope that is fine. Thank you.

**Comment by tunglinn** [comment]
Availability: Tuesday-Thursday 4 hours
ETA: 6/28/22
