### ISSUE TITLE
Write a short copy describing Wins

### ISSUE THREAD

**Issue by cwvivianlin** [hackforla/website#3139]
### Overview 
Based on the Wins submission research findings, users are confused about what a Win is. Write a short copy of what a Win is for (a)[ the Wins page](https://www.hackforla.org/wins/) and (b) the first page of the[ Wins submission form](https://docs.google.com/forms/d/e/1FAIpQLSeTiFjtxKbYgrJHAdFUovXlE55BdwwUQ9NePOXRY2q-h-w1tg/viewform), to give users context.

User quote:
“It would be helpful, …put a description about what does win means, will do, or what the purpose of this page is?….. Unless it's got a purpose. I think people will be more hesitant to submit their stories.”

### Details 

- [x] Review research presentation: https://docs.google.com/presentation/d/1RU80s0ep8azGb7V3IUQ3N-8dDmzQH7oV1nn8q_peTUY/edit#slide=id.p
- [x] Review analysis board: https://drive.google.com/drive/u/0/folders/1DQMLMmorazeKM3b1W-eZQZAV0GcIbRF2
<img width="387" alt="image" src="https://user-images.githubusercontent.com/98001447/168483318-c0bd36d4-5c23-4214-83e9-5d1a6bf106b0.png">

- [x] Write the copy for the Wins Page

- [x] Write the copy for the first page of the Wins submission form

### Resources  
Wins submission research Wiki: https://github.com/hackforla/website/wiki/Wins-submission-process-research

**Comment by cwvivianlin** [comment]
@ExperimentsInHonesty @sacamp

Would love to get our writer on board for this! Who is our writer? Is the person active? Should be quick ticket to implement. 

Thanks!

Vivian

**Comment by njackman-2344** [comment]
Availability: Monday night PST, Tuesday night PST, Friday night PST, 

ETA: Sunday 9/2 EOD PST

**Comment by njackman-2344** [comment]
I have read through the provided research and have written some copy. I would absolutely love feedback if it represents the wins page and first page submission well. I will put this in questions in review as well tag previous contributors. @cwvivianlin @bonniewolfe 
-----
Wins Page:

 This wins section is here to showcase what volunteering for HackforLA has led to. Our past and present members’ wins show to prospective volunteers that HackforLA allows one to learn career skills through contributing to something greater.

 Hopeful beginners to advanced professionals from all around the world we see you and we hope to see your win on this page soon.

Wins Submission Form:

A win is whatever growth you have earned in your tech career journey. Some examples are a large number of Pull Requests, comfortability with a desired tech stack or making a difference for the people of Los Angeles. Whatever your reason for joining, as long as it’s positive and inspiring, it is welcome. A win doesn’t have to be a job but a concrete result is very valuable feedback to our curious visitors.

A good win is growth oriented results usually after getting comfortable with the codebase  and tackling a couple big pull requests to communicating/collaborating with others as well as mentoring ( could be 6 months or more of time). 

A bad win is a false story of growth or false results. If you do the work, there are no bad wins.

**Comment by ExperimentsInHonesty** [comment]
Wins Page:

The wins below showcase the value volunteering for HackforLA has delivered to our members and the community.

Hopeful beginners to advanced professionals from all around the world we see you and hope to see your win on this page soon.

**Comment by ExperimentsInHonesty** [comment]
Wins Submission Form:

A win is whatever growth you have earned in your tech career journey. Some examples are a large number of Pull Requests, comfortability with a desired tech stack or making a difference for the people of Los Angeles. Whatever your reason for joining, it is welcome. Concrete results are valuable feedback to our curious visitors.

**Comment by njackman-2344** [comment]
Received notes in Meeting, looking for UI UX/PM ideas on desired results/soft skills/funny benefits (ex:zoom expert) and will update for Monday 5pm meeting.

Availability: Sun 3pm - 10pm PST, Mon 6am-8am PST

ETA: Mon 8am PST

**Comment by njackman-2344** [comment]
Wins Submission Form:

A win is whatever growth you have earned in your tech career journey. Some examples of a win include becoming a collaboration ninja, zoom expert, a wondrous prototype expert, project manager whiz or a git guru. Whatever your reason for joining, it is welcome. Concrete results are valuable feedback to our curious visitors.

-Rewrote and added in soft skills/funny benefits across the positions. @ExperimentsInHonesty

**Comment by ExperimentsInHonesty** [comment]
This text is perfect!

> A win is whatever growth you have earned in your tech career journey. Some examples of a win include becoming a collaboration ninja, zoom expert, a wondrous prototype expert, project manager whiz or a git guru. Whatever your reason for joining, it is welcome. Concrete results are valuable feedback to our curious visitors.

**Comment by ExperimentsInHonesty** [comment]
This text has been added to the form.  this now need to be made into a development issue.
