### ISSUE TITLE
Create website routes to survey forms

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#316]
### Overview
Create routes to survey forms on website

### Action Items
- [x] Identify the appropriate website file to be edited to route to individual Google Survey forms.
- [x] Insert routes to each form using the URL data provided in the Survey Tracker spreadsheet.

### Resources/Instructions
Survey Tracker: https://docs.google.com/spreadsheets/d/1kteHB0OlAssR5m5sVYopfO0aazCBGOYClYttaGHfR1s/edit#gid=0

This issue resolves #242.

**Comment by ashlingam** [comment]
From @KianBadie: "the files we touch are survey1, survey2, survey3, survey4, and survey5. When you type in the url "hackforla.org/survey[survey#]", the website will redirect you to wherever it is defined in the respective survey file. The redirect links are defined under a field called "redirect_to"

Example of survey1.md:

layout: redirect
permalink: /survey1
redirect_to: https://docs.google.com/forms/d/e/1FAIpQLSefNtY8hw6zoXVBQ6MHYzdDc3o4V1Q4ZX3PUhUHT8T9DraIng/viewform?usp=sf_link

**Comment by ExperimentsInHonesty** [comment]
ETA today

**Comment by ashlingam** [comment]
@leonelRos Do you have a progress update for this issue?

**Comment by leonelRos** [comment]
Yeah I should be making a pull request in the next 10 min
