### ISSUE TITLE
GHA: Update 'getCommentContributors' Function

### ISSUE THREAD

**Issue by answebdev** [hackforla/website#3165]
### Overview
As a developer, I want to update the array comment for the `getCommentContributors` Function to make it more descriptive so that it is clearer and easier to understand. 

### Details
Currently, the comment written is the same as the comment in the previous function, although the functions do not return the same thing.

### Action Items
- [x] Read and understand the code in the file [get-project-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/github-data/get-project-data.js), particularly the `getCommentContributors` function (lines 145-157).
- [x] For line 143, rewrite the following comment inside the square brackets so that it is more descriptive and easier to understand:
```
* @return {Array}     [An array of contributors based on how many commits they have made]
```

#### File and Code link you will need to work on this issue
- Location of the code in your IDE: `github-actions/trigger-schedule/github-data/get-project-data.js`

- Click on the link below to see the file on the repo:
https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/github-data/get-project-data.js

**Comment by ExperimentsInHonesty** [comment]
This issue bounced around.  Dev leads need to check that the issue makes sense before putting ready for milestone label back on.

**Comment by blulady** [comment]
The file had been reformatted to another location. Location has been updated and the comment hasn't changed.

**Comment by MatthewBozin** [comment]
Availability: 11/05/2022 morning, 11/07/2022 evening, 11/08/2022 morning.
ETA: By 11/08/2022.
