### ISSUE TITLE
Update Array Comment for the 'constructContributorParams' Function

### ISSUE THREAD

**Issue by answebdev** [hackforla/website#3166]
### Overview
As a developer, I want to update the comment for the function and make it more descriptive so that it is clearer and easier to understand.

### Details
The function `constructContributorParams` that the comment is written for is actually just for the parameters and it does not fetch comment contributors for a given repo.

### Action Items
- [x] Read and understand the code in the file [get-project-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/github-data/get-project-data.js), particularly the `constructContributorParams` function (lines 164-174). 
- [x] For line 160, rewrite the following comment so that it is more descriptive and easier to understand:
```
* Fetches comment contributors for a given repo
```

### Resources/Instructions
- [get-project-data.js file ](https://github.com/hackforla/website/blob/gh-pages/github-actions/github-data/get-project-data.js)

#### File and Code link you will need to work on this issue
- Directory to the code in your IDE: `github-actions/github-data/get-project-data.js`

- Click on the link below to see the source file code:
https://github.com/hackforla/website/blob/3aa4f322572988cd6c998e71742721cb365a881b/github-actions/github-data/get-project-data.js#L160

**Comment by angietechcafe** [comment]
i. Availability: Thursdays
ii. ETA: Next Thursday or the Thursday after.

**Comment by angietechcafe** [comment]
My update: 
1. Progress - Working on creating a JavaScript comment for this issue.
2. Blockers - Sun-Wed, Fri, and Sat
3. Availability - Th evenings
4. ETA - Th evening

**Comment by angietechcafe** [comment]
Update: I had to delete my git branch and will try to fix the pull request issue no later than this weekend.

**Comment by angietechcafe** [comment]
Update: 
Progress: I will attempt to fix a merge conflict issue I discovered from the pull request. 
Blockers - Sun-Wed, Fri, and Sat
Availability - Th evenings
ETA - Th evening

**Comment by angietechcafe** [comment]
Update: I fixed the merge issue from tonight's meeting. I moved the edited .js file to a different folder, and it's now ready for review.

**Comment by ExperimentsInHonesty** [comment]
Changed the wording to 

> Requests owner login for a given repo.
