### ISSUE TITLE
Update Current Project Team section for the Website Team

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#3177]
### Overview
As a member of the Hack for LA Website team, I want the information on the [Hackforla.org Website project information page](https://www.hackforla.org/projects/website) to be up to date. For this issue, we will be updating the Current Project Team section of the [Hackforla.org Website project information page](https://www.hackforla.org/projects/website).

### Action Items
 In the leadership section in [_projects/website.md](https://github.com/hackforla/website/blob/a476f37103da3087d5ea229d2f3634997319558e/_projects/website.md?plain=1):
- [x] Add Phu
   - [x] Name: Phuong Van
   - [x] Title: Design Lead
   - [x] GitHub: phuonguvan
   - [x] Slack: https://hackforla.slack.com/team/U031MRNSLNS

- [x] Add Tamara Snyder
   - [x] Name: Tamara Snyder
   - [x] Title: Technical lead
   - [x] GitHub: tamara-snyder
   - [x] Slack: https://hackforla.slack.com/team/U02SQV06ARZ
       
- [x] Remove Jessica Cheng
- [x] Remove Saumil Dhankar

### Resources/Instructions
- [Hackforla.org Website project information page](https://www.hackforla.org/projects/website)
- [_projects/website.md](https://github.com/hackforla/website/blob/a476f37103da3087d5ea229d2f3634997319558e/_projects/website.md?plain=1)

**Comment by ExperimentsInHonesty** [comment]
Hi @phuonguvan Please add your name and title as you want it to appear on the https://www.hackforla.org/projects/website page

**Comment by JessicaLucindaCheng** [comment]
@tamara-snyder Please add your information to this issue to update the leadership information for the Website Team on the website. Also, please remove @SAUMILDHANKAR and me.

**Comment by tamara-snyder** [comment]
Hi @phuonguvan, I've made some updates to this issue draft. When you get a chance, could you please check that your information is correct? Feel free to edit as needed. Thanks!

**Comment by BeckettOBrien** [comment]
Availability for this week: 6+ Hours
My estimated ETA for completing this issue: Less than 1 Hour
