### ISSUE TITLE
Create and Add survey for transportation and parking to website

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#323]
### Overview
The DLTA Hack Night must relocate to a new meetup space by June. Create a survey to understand the needs and priorities of DLTA, SOLA, and Westside attendees with respect to transportation and parking.

### Action Items

- [x] Brainstorm relevant survey questions
Parking is free-of-cost? 
Parking spaces are readily available
Location is accessible by rail
Want their email address as well
- [x] Draft survey questions in Google Form
- [x] Review and edit survey draft with Bonnie
- [x] Design Update Get In Touch home page section to add survey link button (under Volunteers section)
- [ ] Add to website

### Resources/Instructions
Survey View Form: https://docs.google.com/forms/d/e/1FAIpQLSeb5zITlv_OewbT_k0UMNw6kail8-Survey Edit 

Form: vKIyjM3E9qPMLYR6qiYw/viewform
https://docs.google.com/forms/d/1bRza8mipTH4p4j5MkFVLcOmadWlSUdS2Uv7KqJrnERs/edit

**Comment by ashlingam** [comment]
Draft survey: https://docs.google.com/document/u/1/d/12A1jWH0VI9X99mr00i1SxSJ7_QmQfrOvIAZzp_inSMU/edit?usp=drive_web&ouid=100731780837940898870

**Comment by ashlingam** [comment]
Draft Google Form: https://docs.google.com/forms/d/1bRza8mipTH4p4j5MkFVLcOmadWlSUdS2Uv7KqJrnERs/edit

**Comment by ashlingam** [comment]
1. Progress - Draft survey created. Awaiting feedback and review.
2. Blocks - N/a
3. Availability - Sunday, Monday
4. ETA - 3/16

**Comment by ashlingam** [comment]
Revised Figma: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205

**Comment by ashlingam** [comment]
@ExperimentsInHonesty @yuikomajima @leestella748 I have added a button to our transportation survey within our Get in Touch / Volunteer with us container. Please let me know if you have any suggested changes to this layout: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205

**Comment by ExperimentsInHonesty** [comment]
@harishlingam design looks good to me, let's add to the website.

**Comment by ashlingam** [comment]
@ye-susan Here is the Survey View Form link: https://docs.google.com/forms/d/e/1FAIpQLSeb5zITlv_OewbT_k0UMNw6kail8-Survey Edit

**Comment by ye-susan** [comment]
Thanks Harish,
@ExperimentsInHonesty  @harishlingam  Please see the screenshot of the mobile version, as we didn't have a Figma design for mobile - I'll submit the PR with your approval.
![image](https://user-images.githubusercontent.com/49918375/83560755-94346700-a4cb-11ea-9ce3-2d56de93ea9a.png)

**Comment by ashlingam** [comment]
@ye-susan Could you please increase the spacing between the bottom of the Getting Started button and the text above the Transportation button? Thanks!

**Comment by ye-susan** [comment]
Will do, I'll be pushing a PR for this issue. The mobile should look like this: 
![image](https://user-images.githubusercontent.com/49918375/83692814-8e14b800-a5a9-11ea-8705-c3dbe34e25de.png)
