### ISSUE TITLE
Update Project Profile: Food Oasis

### ISSUE THREAD

**Issue by sei1122** [hackforla/website#3232]
### Overview
We'd like to update our current team members on this page: https://www.hackforla.org/projects/food-oasis

### Action Items
- [x] Please remove the people currently listed under Current Project Team on https://www.hackforla.org/projects/food-oasis
- [x] In [_projects/food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md?plain=1), please update the leadership with the following people:  

Name: John
GitHub handle: @entrotech
Role: Architect and Technology Lead
Slack ID: UFLDX9V19

Name: Bryan Wu
GitHub handle: @fancyham
Role: Design Lead
Slack ID: U01PG6RD0T1

Name: Jieun Ryu
GitHub handle: @ryu-jieun
Role: UX Researcher 
Slack ID: U02LL2DF4HL

Name: Gigi Patel
GitHub handle: @LIlinit
Role: UX Researcher
Slack ID: U02KZ8WSHHV

Name: Virginia Wu
GitHub handle: VirginiaWu11
Role: Full Stack Engineer
Slack ID: U02G7SBKSV7

Name: Seiko Igi
GitHub handle: @sei1122
Role: Product Designer
Slack ID: U02U55MQEQ7

Name: Hannah Zulueta
GitHub handle: hanapotski
Role: Full Stack Engineer
Slack ID: U9SCMTNK0

### Resources/Instructions
- [Food Oasis webpage](https://www.hackforla.org/projects/food-oasis)
- [_projects/food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md?plain=1)

**Comment by lilyarj** [comment]
Availability: 3 hrs
ETA: 6/28

**Comment by lilyarj** [comment]
When putting in Hannah Zulueta's slack id, it reads an error when you click on the link in my local website. So I went to slack and searched up Hannah Zulueta and found her slack id. That slack id when it is put in does not read an error when it is clicked, and it links to her account I believe.
