### ISSUE TITLE
Update Project Profile: Civic Tech Index

### ISSUE THREAD

**Issue by smsada** [hackforla/website#3236]
### Overview

As a product manager of Civic Tech Index I want my project's details to be up to date on the HackforLA website

### Action Items

- [ ] Civic Tech Index Team Leadership
    - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
        - [x] title
        - [x] description
        - [x] image
        - [ ] leadership
            - [ ] Name
            - [ ] GitHub hand
            - [ ] Role
            - [ ] SLACK ID
        - [x] links
            - [x] Github
            - [x] Wiki
            - [x] Slack
            - [x] Test Site
            - [x] Demo Site
            - [x] Site
        - [x] technologies
        - [x] partner
        - [x] tools
        - [x] status
 
[Comment with the necessary changes](https://github.com/civictechindex/CTI-website-frontend/issues/1062#issuecomment-1151508065)

### Resources/Instructions
- File where changes need to be made [_projects/civic-tech-index.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-index.md)
- Link to the CTI project page on our website: [CTI project](https://www.hackforla.org/projects/civic-tech-index)
- Related issue link to be followed: https://github.com/civictechindex/CTI-website-frontend/issues/1062

**Comment by smsada** [comment]
**Remove the following people:**
Joyce Kim
Vance Dubberly
Adaeze Nwaezeigwe


**Add the following people:**
- name: Iffath Sultana
    role: Product Manager
    links:
    slack: https://hackforla.slack.com/team/U01JQ2V3NRZ
    github: https://github.com/DrIffathsultana
    picture: https://avatars.githubusercontent.com/driffathsultana

**Update the following people:**
 - name: Bhaggyalakshmi
    role: Full Stack Developer and Tech Lead
    links:
      slack: https://hackforla.slack.com/team/U01R30YR26L
      github: https://github.com/bhaggya
    picture: https://avatars.githubusercontent.com/bhaggya
 - name: Maxwell Countryman Skewes
    role: Front End Developer and Tech Lead
    links:
      slack: https://hackforla.slack.com/team/U01R6RWQR3L
      github: https://github.com/maxskewes
    picture: https://avatars.githubusercontent.com/maxskewes

**Comment by alan-zambrano** [comment]
Availability: 3hrs
ETA: 6/30
