### ISSUE TITLE
Donate webpage: Update image alt text for animated gif to adhere to WCAG

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3238]
### Overview
As a developer, we need to provide alt text that adheres to the Web Content Accessibility Guidelines (WCAG) so that we can achieve our mission of inclusivity. For this issue, we will change the alt text for the animated gif image of someone making a donation on the Donate webpage to adhere to WCAG.

### Action Items
The following alt text change is for the [Donate webpage](https://www.hackforla.org/donate/)
- [x] Change the image's alt property value within [pages/donate.html](https://github.com/hackforla/website/blob/gh-pages/pages/donate.html) for the following line of code only:
  - [x] The following alt text is on the `Content-section Donate-card-container` area on the webpage
    - [x] On line 45, change `alt="Gif showing how to select Hack for LA from donation list"` to `alt=""`
- [x] Check that the Donate web page looks the same
- [x] Check that the new alt text got incorporated after the change by inspecting the web page using developer tools
- [ ] Review with product referencing the parent issue https://github.com/hackforla/website/issues/2568 

### Resources/Instructions
- Link to webpage: https://www.hackforla.org/donate/
- Directory to find the source file code once you have it in your IDE: `pages/donate.html`
- Click on this link to see the source file code: https://github.com/hackforla/website/blob/gh-pages/pages/donate.html
- Related design issue: https://github.com/hackforla/website/issues/2568
- Link to the tab on Google Sheets: https://docs.google.com/spreadsheets/d/1abMlPOX88zHTV29E4BFxAYwahCxgJN28Mn95cXr8jak/edit#gid=14599403

**Comment by arpitapandya** [comment]
Availability for this week: 6hrs
My estimated ETA for completing this issue: 1.5hr

**Comment by JessicaLucindaCheng** [comment]
@arpitapandya This issue isn't ready to be worked on yet because it was still in the New Issue Approval column when you picked it. I am unassigning you from this issue and moving this back to New Issue Approval.

For how to find issues to work on, please read [Part 2: How the Website team works with GitHub issues](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#part-2-how-the-website-team-works-with-github-issues), especially section 2.3 Where can I find GitHub issues to work on?

**Comment by braguda** [comment]
Availability: 2 hours
ETA: 10/10/2022

**Comment by braguda** [comment]
Update:
Progress: I've found the page where the source code is supposed to be.
Blocker: I can't find the img tag where the alt needs to be changed. I tried to look into donate-card.html to see if I could find the code that needed changed but I came up empty. The directions say to look on line 45 however there is no line 45 on pages/donate.html nor donate-card.html. 
Availability: 2 hours
ETA: 10/13/2021

**Comment by arpitapandya** [comment]
As discussed I am unassigning @braguda and closing this issue.

The changes have been already made by the linked [issue](https://github.com/hackforla/website/issues/2886) found under resources of the current issue and [PR](https://github.com/hackforla/website/pull/2982/files) has been merged and all the changes have been addressed.

**Comment by arpitapandya** [comment]
https://github.com/hackforla/website/pull/2982/files

**Comment by 7kram** [comment]
@arpitapandya the instructions in the issue you referenced are incorrect (sometimes we make mistakes and future issues are meant to correct them). The gif image that shows how to donate is strictly decorative. The intent behind WCAG guidelines is that if you need the text in the image in order to navigate then it must be included in the alt text, otherwise it's omitted. The image just demonstrates what the text already tells people to do.

> Please follow this link to the Code for America [donation form](https://www.codeforamerica.org/donate)
> To make a donation please select Hack for LA under the brigades listed.

See Jessica's note here
- https://github.com/hackforla/website/issues/2568#issuecomment-1153230064

**Comment by ExperimentsInHonesty** [comment]
- We are going to replace this issue with https://github.com/hackforla/website/issues/3630
