### ISSUE TITLE
Update Project Profile: Food Oasis

### ISSUE THREAD

**Issue by sei1122** [hackforla/website#3240]
### Overview
Please add Hannah to the Current project team
https://www.hackforla.org/projects/food-oasis

Name: Hannah Zulueta
GitHub handle: hanapotski
Role: Full Stack Engineer
Slack ID *: U9SCMTNK0

**Comment by JessicaLucindaCheng** [comment]
@sei1122 
- I had the info for Hannah to be added as part of issue https://github.com/hackforla/website/issues/3232.

Thus, I am closing this issue.
