### ISSUE TITLE
Update new developer checklist 

### ISSUE THREAD

**Issue by angietechcafe** [hackforla/website#3254]
### Overview

As a new developer, I would like instructions to be more clear. For this issue, we will update the Developer Prework Checklist.

### Action Items
- [ ] Add a line there that says these steps can be completed in any order

### Resources/Instructions
- Prework issue template for new developers (https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/pre-work-template--dev.md)
- place to edit it the file gh-pages/.github/ISSUE_TEMPLATE

**Comment by ExperimentsInHonesty** [comment]
@angieintech Where in the [dev prework template file](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/pre-work-template--dev.md) do you think the text about the steps could be completed in any order should go.

After you have answered, please add the ready for dev lead label to this issue and remove the draft label

**Comment by kathrynsilvaconway** [comment]
@ExperimentsInHonesty @JessicaLucindaCheng @blulady @arpitapandya @SAUMILDHANKAR 
Can we take a quick vote on whether or not this addition to the prework remplate is necessary? Currently, under the special notes section, point 3 says:

"The action items listed below should mostly be worked on in a sequential order. However, you don't have to wait on one if you can proceed with the others, For instance, you don't have to wait for attending a weekly meeting before setting up your dev environment."

Does that seem clear enough?

**Comment by arpitapandya** [comment]
If I focus what's under Action Items? Yes, sequential order matters. Whereas, the second line depends on what the new dev thinks what's important in it to follow in sequence, as I am aware that there're few list of actions that they complete while Onboarding meeting and thenafter they checkmark whether they already completed(for eg. slack, GitHub handle, figma). The third line example(meeting) seems relevant. 

Or If we wanna separate the above checklist from Action Items. That may help to let the dev finish all the 32 tasks to close their Pre-work checklist and not re-opening for them of missing something.

It's just my thought. 

### Also, attaching this as this is a separate topic
(Is this new template? The first 3 lines are mandatory (*) and no checkbox and indented though it's a start of action items.)
![whyisthisdifferent](https://user-images.githubusercontent.com/66761308/189919780-8b74e174-e24a-459c-86c8-8183e8bcdca2.PNG)

I am seeing different pre-work checklist open with 32, 33 and 34 tasks in total.

**Comment by JessicaLucindaCheng** [comment]
> @ExperimentsInHonesty @JessicaLucindaCheng @blulady @arpitapandya @SAUMILDHANKAR 
> Can we take a quick vote on whether or not this addition to the prework remplate is necessary? Currently, under the special notes section, point 3 says:
> 
> "The action items listed below should mostly be worked on in a sequential order. However, you don't have to wait on one if you can proceed with the others, For instance, you don't have to wait for attending a weekly meeting before setting up your dev environment."
> 
> Does that seem clear enough?

@kathrynsilvaconway I think that's clear. However, I'm not a new developer and it might be confusing or unclear for new developers. I suggest asking the junior developers on the team about it during a meeting.

**Comment by JessicaLucindaCheng** [comment]
Next steps on this issue is to bring this up at the next meeting with the dev team and take a quick vote on whether or not the suggested change in [this issue](https://github.com/hackforla/website/issues/3254#issue-1272946053) is needed in the prework template? 

> Currently, under the special notes section, point 3 says:
> 
> "The action items listed below should mostly be worked on in a sequential order. However, you don't have to wait on one if you can proceed with the others, For instance, you don't have to wait for attending a weekly meeting before setting up your dev environment."
> 
> Does that seem clear enough?

**Comment by JessicaLucindaCheng** [comment]
@jdingeman I saw you brought this up in the meeting yesterday. Did you all vote on whether the suggested change in https://github.com/hackforla/website/issues/3254#issue-1272946053 is needed in the prework template? Or is it already clear enough with:

> ...under the special notes section, point 3 says:
> 
> "The action items listed below should mostly be worked on in a sequential order. However, you don't have to wait on one if you can proceed with the others, For instance, you don't have to wait for attending a weekly meeting before setting up your dev environment."

**Comment by jdingeman** [comment]
@JessicaLucindaCheng we hadn't taken a vote but we asked the devs to look over the issue and let us know since not everyone was at the meeting. Personally, I think it is already clear enough with the way that statement is written. We have had new devs ask us before if they need to complete one step before the other, and with this, I don't imagine they would question it and they can move on with their tasks.

**Comment by JessicaLucindaCheng** [comment]
@jdingeman If you think we don't need to implement this issue because the info in the developer checklist is clear enough, then please
- [x] Close this issue with a comment on why we are not implementing this issue
- [x] Also, add an appropriate `Ignore` label

Edit: I added a `ready for dev lead` label since this issue requires a dev lead to decide if this is needed.

**Comment by plang-psm** [comment]
Closing out as the dev team plans to keep the checklist as is.
