### ISSUE TITLE
Create filter_dropdown.scss File in Elements Folder

### ISSUE THREAD

**Issue by kathrynsilvaconway** [hackforla/website#3256]
### Overview

Currently, the dropdown filters menus on the projects page and the toolkit page use different SCSS classes, which creates visual inconsistency for the user and also makes it hard for future developers to apply changes correctly. We need to create an SCSS file the will contain all the classes necessary to build our filter menus and store it in the [elements folder](https://github.com/hackforla/website/tree/gh-pages/_sass/elements) for future use.

### Action Items

- [x] create a new SCSS file in the [elements folder](https://github.com/hackforla/website/tree/gh-pages/_sass/elements) called _dropdown_filters.SCSS.
- [x] Copy the entire contents of the  [_project-filter.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-filter.scss) file into the new _dropdown_filters.scss file.
- [x] Import the new scss file you created into main.scss and delete the import for the original [_project-filter.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-filter.scss) 
- [x] After you verify that the contents has been copied correctly, delete the original [_project-filter.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-filter.scss) file in your local repo and test the site to make sure nothing is broken.
- [x] Push your code to your feature branch.
- [ ] Demo your code with the merge team/tech leads. Which has not been made at this time.  Check the bottom of this issue to see if an issue has been made yet.  if not, leave a comment with this issue being done https://github.com/hackforla/website/issues/3277, if yes, then release dependency on the new issue that related this one.

### Note to Merge Team/Tech Leads:
- [ ] If moving this file does not break any code on the site, have the assignee open a pull request and the changes can be merged. If something does break, create an issue to investigate why and correct it.

### Resources/Instructions

Here is the _project-filter.scss file:
https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-filter.scss

**Comment by ExperimentsInHonesty** [comment]
@kathrynsilvaconway you mention that they should 

> After you verify that the contents has been copied correctly, you can delete the original [_project-filter.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-filter.scss) file.

But there is no mention that they should check to see if the pages that use it still work.... and I am left wondering if there are other steps they have to do to make sure the files that use the code know where to find it.

--

Also, when you use the issue making template, please delete the no dependency part or anything else that is unnecessary to the issue.  We do this to reduce cognitive load.

![image](https://user-images.githubusercontent.com/37763229/191558004-a1fa832a-a565-4bb3-94f4-7656dc333a01.png)

**Comment by ExperimentsInHonesty** [comment]
@kathrynsilvaconway left you a note above, and it looks like you did not address what I mentioned, but changed the labels back to ready for milestone.  Please address https://github.com/hackforla/website/issues/3256#issuecomment-1253935127

**Comment by blulady** [comment]
Changes requested have been made.

**Comment by DmitriiTsy** [comment]
Hi guys, hi world! 

Availability: 2 hours 
ETA: 2 hours

**Comment by jdingeman** [comment]
Hello Team,

Added a couple of items to clarify the issue:

- Changed name from `dropdown_filters.scss` to `_dropdown_filters.scss` to match naming convention
- Added item to import new file into `main.scss` and delete the import statement, otherwise this will break the page

**Comment by DmitriiTsy** [comment]
Availability: 6 hours
ETA: 2 hours

**Comment by ExperimentsInHonesty** [comment]
@DmitriiTsy Turns out we are trying to make sure that the filters are navigable by keyboard, not sure if the work you are doing on this issue needs to take that into account, but I thought I would drop you the resources Z has gathered

### Resources
- [Keyboard Accessible - sufficient techniques](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=211#principle2)
- [Using CSS when component receives focus](https://www.w3.org/WAI/WCAG21/Techniques/css/C15.html) - [Focus visible](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible)
- [Navigable Guideline 2.4](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/)
- [Focus Not Obscured](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/#2412-focus-not-obscured-minimum-aa)
- [Draft - Understanding Focus Not Obscured](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum)

**Comment by DmitriiTsy** [comment]
Thank you for these resources. It's amazing

 P.S. I'm on vacation till 11/28/2022

**Comment by arpitapandya** [comment]
As per the discussion - Dmitrii found a job, and doesn't wish to contribute for now. So, I am un-assigning and moving this issue back to `prioritized backlog` so that other dev can work on it.

**Comment by wendybarrios** [comment]
i. Availability: Monday, Tuesday, Thursday : 8:00am - 12:30pm and 6:00 pm - 7:30pm
ii. ETA: Tuesday, 1/17

**Comment by wendybarrios** [comment]
Blockers: School/Work
Availability: Evenings after 6:00pm
ETA: 1/27
