### ISSUE TITLE
Update Project Profile: TDM Calculator

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#327]
### Overview
Update the following fields for your project. These updated fields will then be updated to be shown on the website.

### Action Items
Provide in the comments below:
- [x] Obtain project card info
    - [x] updated wording if necessary on the project card (see [hackforla.org](https://www.hackforla.org/))
    - [x] information on which Tools your team is using for the project (Ex: figma, Balsamiq, photoshop, etc.) . This is different than programming languages
    - [x] updates for "Looking For" Section
    - [x] any updated links that are not currently displayed on the site (do you have a demo site?)
    - [x] Hero image to be displayed on Project Home Page at 1500 x 700 px
    - [x] any resources for a Getting Started link (either a link to a wiki or readme)
- [ ] add project card to website

### Resources/Instructions
See the hero image on the [hackforla.org](https://www.hackforla.org/) homepage

**Comment by ExperimentsInHonesty** [comment]
@KPHowley We are going need a new image without the words.  See what it looks like on the phone
![Screen Shot 2020-03-15 at 11 16 40 AM](https://user-images.githubusercontent.com/37763229/76707686-8df1d400-66ae-11ea-990e-db7c7aa49b4e.png)

**Comment by KPHowley** [comment]
@ExperimentsInHonesty @harishlingam  - Here's an image without the words, and the words separately in case you want to do any responsive resizing or centering
![LATDM Hero Image](https://user-images.githubusercontent.com/49739276/76798566-0f1f9880-678d-11ea-80cb-9a00b95b3b52.png)

![Better for LA](https://user-images.githubusercontent.com/49739276/76798199-5e18fe00-678c-11ea-839a-a7a3d5455b76.png)
![Better for your proj](https://user-images.githubusercontent.com/49739276/76798200-5eb19480-678c-11ea-9282-b820ec390136.png)

**Comment by ExperimentsInHonesty** [comment]
replace the hero with hero with no writing

**Comment by parkderick** [comment]
Submitted request issue #327.
