### ISSUE TITLE
Review and update wiki page: GHA: add update label weekly

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#3274]
### Overview
As a developer, I would like up to date information about our GitHub Actions in a wiki page. For this issue, we will review and update the wiki page for [GHA: add update label weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly).

### Action Items
- [x] Read the information about the add-update-label-weekly GHA [here](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions#add-update-label-weekly)
- [x] Understand how the workflow works. Related files: [move-closed-issues.yaml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/move-closed-issues.yaml) and [sort-closed-issues.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/move-closed-issues/sort-closed-issues.js)
- [x] Review the information on the [GHA: add update label weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly) wiki page
- [x] Add or edit the following information for the [GHA: add update label weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly) wiki page for each of the following sections:
    - [x] Summary (update overview, links, definitions for the GHA if possible). [Note: update the info [here](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions#add-update-label-weekly) as well, if required]
    - [x] Schedule (When does it trigger).
    - [x] Workflow (Include the link to the workflow file as well as the process steps for a complete workflow cycle)
    - [x] Supporting Files/Folder (Include links to the files or folders that are referenced in the workflow files as well as briefly describe the functionality of each file involved)
- [x] Reach out to the leads during the team meeting or on slack for a review since no PR would be required for this issue.
- [x] For reviewers: Once this issue has been reviewed and approved, please update and edit epic https://github.com/hackforla/website/issues/3229 by
    - [x] Checking off the dependency for this issue
    - [x] If all dependencies are checked off, please move issue https://github.com/hackforla/website/issues/3229 to the New Issue Approval column and remove the Dependency label

### Resources/Instructions
- [GHA list](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions#hack-for-las-ghas)
- [Move-closed-issues.yaml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/move-closed-issues.yaml) 
- [Sort-closed-issues.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/move-closed-issues/sort-closed-issues.js)
- [Move closed issues GitHub action folder](https://github.com/hackforla/website/tree/gh-pages/github-actions/move-closed-issues).

**Comment by bishrfaisal** [comment]
@ExperimentsInHonesty This issue is ready for milestone. After that we can attend to issue #3229 and remove its dependency label.

**Comment by 7kram** [comment]
@ExperimentsInHonesty 

* Maybe change title to "Review and update wiki page: GHA: add update label weekly" 
* 1st and 3rd Action Items are the same thing (remove the 3rd one)

Agree with @bishrfaisal Issue is completed and is ready for milestone. We should now make the necessary updates in issue #3229 (updating google spreadsheet tab and removing dependency label)

**Comment by ExperimentsInHonesty** [comment]
@SAUMILDHANKAR Step 1 and 3 in the action items are very similar (they both go to the same link).  And we assume there was a reason for providing it twice.  Can you update the issue to make it clearer what you want them to do in step 1 and 3 that is different?

Step 1: Read the information about the add-update-label-weekly GHA [here](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly)
Step 3: Review the information on the [GHA: add update label weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly) wiki page

Also, I have added the Milestone to this issue, so after you fix the above go ahead and put it in the prioritized backlog.

**Comment by SAUMILDHANKAR** [comment]
> @SAUMILDHANKAR Step 1 and 3 in the action items are very similar (they both go to the same link). And we assume there was a reason for providing it twice. Can you update the issue to make it clearer what you want them to do in step 1 and 3 that is different?
> 
> Step 1: Read the information about the add-update-label-weekly GHA [here](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly) Step 3: Review the information on the [GHA: add update label weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly) wiki page
> 
> Also, I have added the Milestone to this issue, so after you fix the above go ahead and put it in the prioritized backlog.

@ExperimentsInHonesty: Sorry, missed the notification and didn't fix this earlier. I have updated the link in step 1 to [this](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions#add-update-label-weekly). So, if the person working on this issue decides to make changes to the summary, they would need to check both the links i.e. in Step 1 and Step 3 as per your comment.

**Comment by Adaakal** [comment]
Availability: Tuesday 2/7 & Wednesday 2/8 - 12:30-1:30
ETA: Friday 2/11

**Comment by Adaakal** [comment]
Just got my laptop back. 
ETA: Monday 2/13

**Comment by Adaakal** [comment]
**Progress: What is the current status of your project?** 
I just started going through the Project Board.
**What have you completed and what is left to do?**
So far I've marked two as 'To Update'. There are still 61 issues 'In progress'
**Blockers: "Difficulties or errors encountered."**
My laptop suddenly stopped charging and had to be taken in. I just got it back yesterday. I'm also not sure if I'm doing this correctly. I will clarify on Sunday.
**Availability: "How much time will you have this week to work on this issue?"**
As I'm behind on other responsibilities, I won't have any more time today. I'll have some time on Sunday.
**ETA: "When do you expect this issue to be completed?"**
By at least Wednesday 2/15

**Comment by maryjng** [comment]
Availability: 7 PM - 10 PM EST most days
ETA: 2/27

**Comment by plang-psm** [comment]
The requested changes were addressed in the updated Wiki. Good work @maryjng !
