### ISSUE TITLE
Design a fix the dropdown menu design for projects page

### ISSUE THREAD

**Issue by sijiapitts** [hackforla/website#3277]
### Overview
During a site audit on Figma design file and on the website, we noticed that the drop-down menu design is not consistent. Each page has its own font size, margin, padding, etc. 

We decided that the first step is to fix the dropdown menu on the toolkit page. Afterwards, we will move on to the projects page and wins page.

- Toolkit page issue #3626
- Wins page issue #3627

**Update** 

The toolkit page met a blocker, so the team decided to finish the project page first 

### Action Items
- [x] Fix the inconsistency of padding
- [x] Fix the inconsistency of font sizes 
- [x] Determine the layout
- [x] Determine design details of the dropdown
- [x] Implement the new design
- [x] Review with design lead

### Resources/Instructions

[Design Systems](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
[Figma workfile](https://www.figma.com/file/MVRUNtLFjuamihX8PQg2Ic/Hack-for-LA-about%2Faccomplishment?node-id=179%3A55960)
[Final design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24096%3A281035)

**Comment by phuonguvan** [comment]
@sijiapitts Please give me updates on what you will be working on. Please also give me the Figma file so I can clean up the details on the issue.

**Comment by sijiapitts** [comment]
@phuonguvan I have included the Figma link to the descriptions. 

I will still be working on fixing the dropdown menu. But because we may add more toolkit categories in the future, we will need to change the web menu design to dropdown menus as well (like the project page and wins page). When working on this issue, I will use the project page as a reference.

**Comment by sijiapitts** [comment]
Blocker: Do we need a multi select dropdown (dropdown with check box) for the toolkit page? 

Because the nature of the toolkit page, I think users rarely will need to select multiple categories at the same time. In this case, a single select dropdown may be more intuitive and easier to use.

**Comment by sijiapitts** [comment]
1. Progress: Clarified the design direction for toolkit filters during the meeting on 7/10. We are trying to make the toolkit page filter work the same way as the landing page. Will create multiple filters(practice area, tools, and status) and checkboxs inside of dropdown (so people can select multiple items).
2. Blockers: No blockers
3. Availability: 5 hours
4. ETA: by the next meeting on 7/13

**Comment by ExperimentsInHonesty** [comment]
### Filters Needed

- ~Program~ Practice Areas (Product Management, Design, Research, etc.)
- Tool (Figma, GitHub, Miro, etc.)
- Type (article, plugin, video, guide, etc.)
- Status (Completed, Work In Progress, Depreciated)
- Contributors (for internal guides all contributors will be listed)
- Source (Hack for LA, Code for America, Other)

### Example of left filter from another project
http://civictechindex.org/search-projects (search for food to see filter)

**Comment by ExperimentsInHonesty** [comment]
@sijiapitts fyi, I opened this issue to have the development team add the other filter content to the code so that when the design is done, they can make the new filters right away
- https://github.com/hackforla/website/issues/3357

**Comment by 7kram** [comment]
@ExperimentsInHonesty Lets add a **Homepage launch** milestone to the issue

**Comment by sijiapitts** [comment]
We did usability testing with the entire team on 9/11 to check what works best for Hack for LA website regarding filter items. We showed the team members two options, as seen [here](https://www.figma.com/file/MVRUNtLFjuamihX8PQg2Ic/Hack-for-LA-about%2Faccomplishment-and-Toolkit-page?node-id=459%3A391177). 

The team decided that the best option for our website would be:

- Filter items should stay on the side bar
- Dropdown menu stays open by default 
- Add show all when the list gets too long
- The list items with the most results should be on the top. When users click show all, then the results will be displayed in an alphabetical order.

Please refer to the link above as an example.

**Comment by ExperimentsInHonesty** [comment]
- [ ] Create new issues:
   - [x] Adapt new Projects page Filters and Search design to Toolkit page
   - [x] Adapt new Projects page Filters and Search design to Wins page
- [ ] Put a screen shot of the New designs in this issue and a link to the Figma file
- [x] Close issue (which will send it to Q&A
- [ ] Q&A/Product will review and send to dev leads for new development issue creation.

**Comment by sijiapitts** [comment]
The design has been completed and approved. The final design (ready for developers) can be found [here ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24096%3A281035) or under the project description. 

In Figma, I have added some notes to the side and added additional comments on the design to better help the developers understand the design and interaction.

**Comment by 7kram** [comment]
See the previous comment from Sijia. 

Additional Note for Dev Lead Writing This Issue:
This is a new visual version of how the filters will appear. When refactoring it, the goal is to make it a component that can be re-used on multiple pages with different filters specified

**Comment by ExperimentsInHonesty** [comment]
once you make the issue stick it in the icebox with the following

```
### Dependency 
- #3256 
```

**Comment by blulady** [comment]
Reached out to Sijia with questions.

**Comment by blulady** [comment]
- Should we do some research about accessibility like we were going to with issue #2286 (Do we still need to do this audit if the drop down menu is changing?) or Azania's issue #2173

**Comment by ExperimentsInHonesty** [comment]
- I don't think issue has anything to do with the sticky nav #2173.  If you think it does, please be specific in your note.

**Comment by ExperimentsInHonesty** [comment]
@blulady I am unclear what you are asking in your comment above

> Should we do some research about accessibility like we were going to with issue https://github.com/hackforla/website/issues/2286 (Do we still need to do this audit if the drop down menu is changing?) 

I tried to look at the issue you reference, but it's too big for that.  It has so much info in the comments and there is no summary at the top.  In fact, I have no idea what work is left to be done on that issue, because all the checkboxes are checked.  If the comments require new work, they should be summarized into action items in the top of the issue.

If you want me to do something on this issue, please summarize your ask and the information I would need to make the decision into one comment.

**Comment by blulady** [comment]
@ExperimentsInHonesty All apologies for being unclear. What I was trying to suggest was that we should do research on how to make the drop down menu accessible like Azania did [here](https://github.com/hackforla/website/issues/2173#issuecomment-1279768721)? Or should I just move forward in creating an issue to create the drop down menu for the projects page?

**Comment by ExperimentsInHonesty** [comment]
@blulady I think we can make an issue for dev to build this function and while they are building it, take into account accessibility of navigating the filters with keyboard.  See these [Resources come from this comment from Z on another issue](https://github.com/hackforla/website/issues/2173#issuecomment-1279768721)

### Resources
- [Keyboard Accessible - sufficient techniques](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=211#principle2)
- [Using CSS when component receives focus](https://www.w3.org/WAI/WCAG21/Techniques/css/C15.html) - [Focus visible](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible)
- [Navigable Guideline 2.4](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/)
- [Focus Not Obscured](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/#2412-focus-not-obscured-minimum-aa)
- [Draft - Understanding Focus Not Obscured](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum)

### Dependency
once you make the issue stick it in the icebox with the following

```
### Dependency 
- #3256 
```

**Comment by blulady** [comment]
> See the previous comment from Sijia.
> 
> Additional Note for Dev Lead Writing This Issue: This is a new visual version of how the filters will appear. When refactoring it, the goal is to make it a component that can be re-used on multiple pages with different filters specified

Drafting up this issue, saw that issue #3626 is also `ready for dev lead` per the comment quoated above do we want to make this issue a dependency for #3626?
- #3626

**Comment by blulady** [comment]
> * [Keyboard Accessible - sufficient techniques](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=211#principle2)
> 
> * [Using CSS when component receives focus](https://www.w3.org/WAI/WCAG21/Techniques/css/C15.html) - [Focus visible](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible)
> 
> * [Navigable Guideline 2.4](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/)
> 
> * [Focus Not Obscured](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/#2412-focus-not-obscured-minimum-aa)
> 
> * [Draft - Understanding Focus Not Obscured](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum)

So I went to make the new issue and went ahead and looked at issue
- #3256 
And realized that the issue was no longer in the icebox and is currently being worked on. I went to take a look at that issue and that issue has the Developer creating a file called _dropdown_filters.scss in the elements folder. It looks like this is where I should have the developer working on this issue put the css they will be working on. Just wanted to explain my thought process on how to structure the issue 
- #3744

**Comment by blulady** [comment]
> @blulady I think we can make an issue for dev to build this function and while they are building it, take into account accessibility of navigating the filters with keyboard. See these [Resources come from this comment from Z on another issue](https://github.com/hackforla/website/issues/2173#issuecomment-1279768721)
> ### Resources
> 
>     * [Keyboard Accessible - sufficient techniques](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=211#principle2)
> 
>     * [Using CSS when component receives focus](https://www.w3.org/WAI/WCAG21/Techniques/css/C15.html) - [Focus visible](https://www.w3.org/WAI/WCAG21/Understanding/focus-visible)
> 
>     * [Navigable Guideline 2.4](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/)
> 
>     * [Focus Not Obscured](https://www.w3.org/WAI/standards-guidelines/wcag/new-in-22/#2412-focus-not-obscured-minimum-aa)
> 
>     * [Draft - Understanding Focus Not Obscured](https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum)
> 
> 
> ### Dependency
> 
> once you make the issue stick it in the icebox with the following
> 
> ```
> ### Dependency 
> - #3256 
> ```


So I went to make the new issue and went ahead and looked at issue
- #3256 
And realized that the issue was no longer in the icebox and is currently being worked on. I went to take a look at that issue and that issue has the Developer creating a file called _dropdown_filters.scss in the elements folder. It looks like this is where I should have the developer working on this issue put the css they will be working on. Just wanted to explain my thought process on how to structure the issue 
- #3744

**Comment by ExperimentsInHonesty** [comment]
- @blulady thanks for the info
-  I added a dependency label to #3744 and put it in the icebox
