### ISSUE TITLE
GitHub Actions: Bot removing labels added immediately after issue creation

### ISSUE THREAD

**Issue by Zak234** [hackforla/website#3334]
### Dependency
-  The Github Actions bot does not appear to be removing the `ready for milestone` label when an issue is created with the label attached anymore

 
### Overview
As a developer, we have to ensure that our kanban board is organized for all teams so that productivity is high. For this issue, we want to know why the GitHub action bot is removing the "Ready for Milestone" label when applied during issue creation and change the code logic so it doesn't.

### Action Items
- [ ] Please go through the wiki article on [Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
- [ ] Review the [check-labels.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/check-labels.js) file, to understand how the issue trigger bot checks and removes labels from the issue.
- [ ] Understand why the github action bot removes the "Ready for Milestone" label if applied during issue creation. See resources for links to two helpful issues that discuss this.
- [ ] Change the code logic to fix this error

### Checks

- [ ] Test in your local environment that it works
- [ ] Make sure that comments are still applied correctly and other labels are still added and removed correctly.

### Resources/Instructions
- Issue #2676 
- Issue #2397 
- Relevant files:
   - https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/check-labels.js
   - https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/post-labels-comment.js
   - https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-preliminary-comment/check-label-preliminary-update.js
   - https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml

Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
[GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
[GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[actions/github-script](https://github.com/actions/github-script)
[GitHub RESTAPI](https://docs.github.com/en/rest)

#### Architecture Notes

The idea behind the refactor is to organize our GitHub Actions so that developers can easily maintain and understand them. Currently, we want our GitHub Actions to be structured like so based on this [proposal](https://docs.google.com/spreadsheets/d/12NcZQoyGYlHlMQtJE2IM8xLYpHN75agb/edit#gid=1231634015):

- Schedules (military time)
        - Schedule Friday 0700
        - Schedule Thursday 1100
        - Schedule Daily 1100
- Linters
        - Lint SCSS
- PR Trigger
        - Add Linked Issue Labels to Pull Request
        - Add Pull Request Instructions
- Issue Trigger
        - Add Missing Labels To Issues
- WR - PR Trigger
        - WR Add Linked Issue Labels to Pull Request
        - WR Add Pull Request Instructions
- WR - Issue Trigger

Actions with the same triggers (excluding linters, which will be their own category) will live in the same github action file. Scheduled actions will live in the same file if they trigger on the same schedule (i.e. all files that trigger everyday at 11am will live in one file, while files that trigger on Friday at 7am will be on a separate file).

That said, this structure is not set in stone. If any part of it feels strange, or you have questions, feel free to bring it up with the team so we can evolve this format!

**Comment by MattPereira** [comment]
Availability: 8 - 10 PM
ETA: 11/20/22

**Comment by MattPereira** [comment]
#### Progress :
- Finished the first two action items
- Tested if the `Ready for Milestone` label is removed by GH bot if added during issue creation #3742 
- Tested if the `Ready for Milestone` label is removed by GH bot if added after issue creation #3747
#### Blockers :
- I do not understand why the github action bot removes the `Ready for Milestone` label if applied during issue creation. I suspect the bug may be triggered by adding the particular label after issue creation? 
- I'm having difficulty figuring out how to test the github action that triggers on issue creation using my fork
#### Availability :
- 10 hours

#### ETA : 
- To be determined

#### Pictures :
- None

**Comment by ExperimentsInHonesty** [comment]
@MattPereira Please put notes from the conversation we had with Ava at the Engineering Community of Practice on 2022-11-30 about race condition.

**Comment by MattPereira** [comment]
### Notes From Engineering CoP Meeting on 2022-11-30
- Ava successfully recreated the bug on #3759
    - link to the issue's github actions logs https://github.com/hackforla/website/actions/runs/3588856523/jobs/6040684324
- She deduced that the github-actions bot is removing the `Ready for Milestone` label because of a [race condition](https://en.wikipedia.org/wiki/Race_condition)
- Her recommendations:
    - Research github actions API to see if it is possible to prevent the label from being removed
    - Try altering the logic to wait X number of seconds before running the github action to prevent the race condition
    - Consider using a webhook to prevent the bug (very difficult)

**Comment by MattPereira** [comment]
1. Progress: Returning from December month off
2. Blockers: TBD
3. Availability: 20 hours / week
4. ETA: Will have a better handle on ETA by 1/8/23

**Comment by MattPereira** [comment]
1. Progress: Created another issue with the `Ready For Milestone` label attached during issue creation, but the github actions bot did not remove the label this time
    - #3803 
    - [GitHub Actions log](https://github.com/hackforla/website/actions/runs/3880646041/jobs/6618880931)
3. Blockers: Snowboarding this weekend
4. Availability: 15 hours
5. ETA: TBD

**Comment by MattPereira** [comment]
1. Progress: I have been creating issues with the `Ready For Milestone` label attached during issue creation, but the github actions bot is not removing the label
    - #3869
    - #3870
    - #3872
3. Blockers: I do not understand why it only removes the `Ready For Milestone` label sometimes
4. Availability: 15 hours
5. ETA: TBD

**Comment by MattPereira** [comment]
I am moving this issue back to icebox because the github actions bot has not removed a `ready for milestone` label from any of the many issues I have created with it.

**Comment by ExperimentsInHonesty** [comment]
This issue is resolved by us changing all the issue templates to have the missing labels by default #4307
