### ISSUE TITLE
Update Project Profile: [Civic Tech Jobs]

### ISSUE THREAD

**Issue by sdimran** [hackforla/website#3339]
### Overview
As a product manager of Civic Tech Jobs I want my project's details to be up to date on the HackforLA website

### Project card
Insert url of your project card here before sending; your card(s) can be found in this folder: https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md

### Action Items

- [ ] Civic Tech Jobs Team Leadership
   - [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in a new comment below:
      - [x] title
      - [x] description
      - [x] image
      - [ ] leadership
         - [ ] Name
         - [ ] GitHub handle
         - [ ] Role
         - [ ] SLACK ID
      - [x] links
         - [x] GitHub
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] technologies
      - [x] partner
      - [x] tools
      - [x] status
 - [ ] If you need updates to your meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue in a new comment below

### Resources
[VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

**Comment by sdimran** [comment]
We would like like to update our contributors for our active team: 

**Remove:** 

Sharad Gaurav (Product Manager)
Patty Costello (UX Researcher)
Sarah Williams (Software Developer)

**Add:**

Name - Salima Yacoubi Soussane
GitHub handle - Salimays
Role - Product Manager
SLACK ID - U03HUJM7YCX

Name - Kevin Park
GitHub handle - Enzyme3
Role - Backend Developer
SLACK ID - U02B1MG90PK

Name - Maria Elizabeth Rodriguez Beltran
GitHub handle - mariaelizabeth04
Role - UX Researcher
SLACK ID - U035B853S4W

Name - Summer Kim
GitHub handle - hkimsummer
Role - UX Researcher
SLACK ID - U0374ALAX2Q

**Comment by d-perez-8** [comment]
Availability: All day Monday, Tuesdays & Thursdays 5-6
ETA: End of day
