### ISSUE TITLE
Fix Punctuation and Capitalization in Access the Data  & food Oasis

### ISSUE THREAD

**Issue by Zak234** [hackforla/website#3354]
### Overview
We need to fix the capitalization and punctuation in food-oasis.md and access-the-data.md so we can keep everything understandable and up to standard on the website.

### Details
Below are screenshots of the tools currently on the Food Oasis and Access the Data webpages from the Hack for LA website as of 2022-09-04 (these tools are subject to change via another issue, so don't worry if they are different):
<details>
  <summary>Click here to see a screenshot of the Tools on the Food Oasis webpage</summary>
  <img width="226" alt="" src="https://user-images.githubusercontent.com/31293603/182266339-d064d686-434d-4fd1-9c1f-c4f4d502bc55.png">
</details>

<details>
  <summary>Click here to see a screenshot of the Tools on the Access the Data webpage</summary>
  <img width="218" alt="" src="https://user-images.githubusercontent.com/31293603/182266353-b02fb5fe-5822-4699-926a-601451c26abb.png">
</details>

### Action Items
- [x] Open _projects/food-oasis.md in VS Code or your IDE, then capitalize each tool in food-oasis.md and remove the period at the end (don't capitalize: pen, paper, phone calls)
- [x]  Open _projects/access-the-data.md in VS Code or your IDE, then capitalize each tool in access-the-data.md and remove the period at the end (don't capitalize: pen, paper, phone calls)

### Resources/Instructions
access-the-data.md
https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md
food-oasis.md
https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md

Website:
access-the-data page
https://www.hackforla.org/projects/access-the-data
food-oasis page
https://www.hackforla.org/projects/food-oasis

**Comment by bishrfaisal** [comment]
@ExperimentsInHonesty Issue looks good and ready for milestone.

**Comment by 7kram** [comment]
@ExperimentsInHonesty I agree with @bishrfaisal 

Maybe add a "good first issue" label since it's a quick edit to the two markdown files.

**Comment by michaelmagen** [comment]
Availability: 3 hours
ETA: 10/4/22
