### ISSUE TITLE
Replace 3 digit abbreviated hex color codes in _colors.scss

### ISSUE THREAD

**Issue by Zak234** [hackforla/website#3355]
### Overview
We need to replace the 3 digit abbreviated hex color codes in _colors.scss with its equivalent 6 digit hex color codes so that it fits in with the rest of the values on the page which are all 6 digit, which will promote readability.

### Action Items
Open _sass/variables/_colors.scss in VS Code or your IDE, then
- [x]  Change the line `$color-black: #333;` to `$color-black: #333333;`
- [x]  Change the line `$color-mediumgrey: #ccc;` to `$color-mediumgrey: #cccccc;`
- [x]  Change the line `$color-white: #fff;` to `$color-white: #ffffff`

### Resources/Instructions
[_sass/variables/_colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors.scss)

**Comment by JohnJBarrett22** [comment]
i. Availability: Open availability.
ii. ETA: Behind on answering this, just completed this task.

**Comment by 7kram** [comment]
@ExperimentsInHonesty **Technical debt** for milestone
