### ISSUE TITLE
Guide Pages: improve WCAG for Building a Reporting Dashboard and 2FA

### ISSUE THREAD

**Issue by Zak234** [hackforla/website#3360]
### Overview
We need to add alt text to the hero image of some guide pages so that they are Web Content Accessibility Guidelines (WCAG) compliant.

### Details
Alt text helps people using text to speech browsers understand the content in images if the image communicates something not written on the page (e.g., a navigation button with a picture of a map on it, to indicate you can see a map by clicking the button would require an alt tag, a button with the word map created by text appearing over a button image would not).

### Action Items
- [x] Open _layouts/guide-pages.html in VS Code or your IDE, then add `alt=""` to the line 
  ```
  <img class='page-hero' src="../assets/images/guides/guide-page-hero.png">
  ```
  so it looks like this
  ```
  <img class='page-hero' src="../assets/images/guides/guide-page-hero.png" alt="">
  ```

### Resources/Instructions
- [_layouts/guide-pages.html](https://github.com/hackforla/website/blob/gh-pages/_layouts/guide-pages.html)

### Acceptance Criteria
- Go to 
   - [Building a Reporting Dashboard ](https://www.hackforla.org/guide-pages/survey-reporting-dashboard-guide)
   - [2FA](https://www.hackforla.org/guide-pages/2FA)
- Inspect code and you will see `alt` without anything else
e.g., ![image](https://user-images.githubusercontent.com/37763229/188040754-7ef52bad-10fc-49ac-b221-dcd131de9e8b.png)

**Comment by JessicaLucindaCheng** [comment]
@Zak234 Thanks for writing this issue! I have added this issue to the Project Board. Please remember to add any issues you write to the Project Board in the future. Thanks. 😄

**Comment by christinaor** [comment]
Availability: 10am-5pm, M-F
ETA: Friday 2/3

**Comment by christinaor** [comment]
Progress: Checked the change with docker on the Building a Reporting Dashboard and 2FA pages. Completed action item and created a PR for this issue. Currently waiting for the PR to be reviewed.
Blockers: N/A
Availability: Fri 10a-5p EST if any issues arise
ETA: Thurs 10p EST
Pictures (optional): Change is visible in source code. No visual changes on the website are available.
