### ISSUE TITLE
Create SDG page

### ISSUE THREAD

**Issue by nathan944** [hackforla/website#3370]
### Overview
Create SDG page to be added to Hack for La website

### Action Items
- [ ] Product
   - [ ] ideate
   - [ ] define feature requirements
   - [ ]  make issues for UI/Development
      - [ ] UI
         - design the mockup
         - get feedback from product
     - [ ] Development
        - develope according to figma

### Resources
[figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)

**Comment by ExperimentsInHonesty** [comment]
- This is the actual issue https://github.com/hackforla/website/issues/3302
