### ISSUE TITLE
Google Apps Script: Fix extra empty JSON field problem 

### ISSUE THREAD

**Issue by luke-karis** [hackforla/website#3417]
### Overview
In the _wins-data.json and wins-data.json at the end of each Wins entry, there is "":"", which wasn't there in the current _wins-data.json and current wins-data.json in gh-pages. The objective of this ticket is to figure out why this is happening and implement a fix.

### Action Items
- [x] Obtain access to the Google Apps Script in the admin drive from the technical lead
- [x] Become familiar with the workflow process of writing to the _wins-data.json and wins-data.json files
- [ ] Determine the cause of the bug detailed in this ticket
- [ ] Fix the bug so that  there is no longer "":"" added to the end of each entry in the _wins-data.json and wins-data.json files

### Resources/Instructions
The PR where the updated wins data goes to is here https://github.com/hackforla/website/pull/3024. You can see the issue described by this ticket by going to the files changed tab in this PR and scrolling through one of the wins-data files until you reach the end of an entry.

**Comment by aricforrest** [comment]
Availability: Monday-Wednesday 5 PM - 7 PM PST
ETA: 10/19/2022

**Comment by aricforrest** [comment]
Blocker - Unable to replicate the bug of empty key value pairs in JSON in my own Google Apps Scripts instance using a copy of `Wins-form (Responses)` sheet.

@luke-karis created this issue on July 21, 2022 and completed updating another Wins process issue #2901 on September 17, 2022 so I'm wondering if this bug has already been resolved. Data in any columns after O in the spreadsheet would cause similar behavior as described by this bug. However, the bot's most recent PR (#3024) to update the Wins JSON files still show the empty key-value pairs. 

Google Apps Scripts aren't being stored in GitHub to check to see what changes were made for issue #2901 so I've created issue #3641 to begin storing/tracking Google Apps Scripts also in GitHub.

Should I copy the current `Wins-form (Responses)` Google Sheet into a new file in the same `HfLA website Admin/Wins to review` folder and attempt debugging/testing the main function there? 

- The main function calls the ghrequests library to update the Wins files in the bot's `update-wins-data` branch and initiates a PR against the project's primary gh-pages branch.

**Comment by aricforrest** [comment]
Google's Advanced Protection enabled on an account prevents running Apps Scripts from unverified/unapproved apps. A work around is to add the following block at the top of the script, but due to the `Wins-form (Responses)` using the `ghrequests` library from another Google Doc, this is not an option. 
```
/**
 * @OnlyCurrentDoc
 */
```
I am creating a new Google account without Advanced Protection enabled and sharing the Google Share with it to continue working on this issue.

**Comment by aricforrest** [comment]
The API token for the `elizabethhonest` GitHub account is not valid. The admin guide states this needs to be updated every month and it looks like it was last updated 1/30/2022.

**Comment by aricforrest** [comment]
- `elizabethhonest` bot GitHub API token updated and set to expire in 30 days.
- Manually called `Wins-form (Responses)/Code.gs` `main()` function to perform push of updated `_wins-data.json` and `wins-data.json` files without changes to JSON file building logic. 
- Commit [6bd12b3](https://github.com/elizabethhonest/website/commit/6bd12b33e57d430246a4cec2f49a29c620a27a8b) and [d464f52](https://github.com/elizabethhonest/website/commit/d464f52ea76a2ae654fcc1b29832db23d7125761) to `elizabethhonest`'s `update-wins-data` branch demonstrate the JSON structure issue is no longer present and likely was resolved during #2901 
- `elizabethhonest` pull request #3024 is now valid

**Comment by aricforrest** [comment]
Issue is ready for review @hackforla/website-merge

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge I am not sure if this is fixed or it was determined that its not a problem or it couldn't be determined that its not a problem because of the token issue https://github.com/hackforla/website/issues/3748

**Comment by jdingeman** [comment]
Closing issue since issue seems to have been fixed.
