### ISSUE TITLE
Investigate Herokuapp Ownership and Setup

### ISSUE THREAD

**Issue by Zak234** [hackforla/website#3433]
### Overview
We need slack invites to come from a role account instead of an individual HFLA member. We also need to create documentation of this setup and maintenance requirements so that our organization can be more sustainable.

### Details
- We use the SlackIn Extended to invite people to our Slack workspace
- SlackIn Extended is hosted on Herroku ([Slack Invite](https://hackforla-slack.herokuapp.com/))
- The invites come from slack user Nina Kin (former HFLA brigade captain) who is also an owner of the Slack workspace.
- When we tried to cleanup the Slack workspace's ownership by changing Nina's user profile from owner to member, it broke the automation. The issues were only fixed once Nina was returned as owner.
- Herroku app might need to be updated if the SlackIn extended code has been updated.

### Action Items
- [x] Setup a Slack account for slack@hackforla.org
- [x] Have leadership make the Slack user an owner
- [x] Contact Nina and ask her about the setup and ownership of the Herroku app
- [ ] Switch ownership of the Herroku account (if possible) from Nina to the newly created Slack role account
  - [ ] if not possible, explore solutions (including hosting SlackIn Extended on our AWS account)
- [ ] Inside SlackIn Extended, change the Slack user that sends the Slack invitation from Nina's to the new Slack role account
- [ ] Confirm everything is still working as intended
- [ ] Check if we can update the Herroku app due to updates from the developer of SlackIn Extended.

### Resources/Instructions
[Slack Invitation Screen](https://hackforla-slack.herokuapp.com/)
Nina's Email: nina@ninakin.com
[Slackin Extended (Used by Herokuapp)](https://github.com/emedvedev/slackin-extended)
[Herokuapp Documentation](https://devcenter.heroku.com/start)

**Comment by Zak234** [comment]
I have been unable to contact Nina but I did some more investigating by myself and I believe we may be able to just rehost the invite with role account.

**Comment by Zak234** [comment]
I did some more digging and I don't think we can actually remove Nina. This is because the slack API token that slackin extended uses is a legacy token type that has since been deprecated and can no longer be created. The reason slackin extended still works for us is due to slack not removing legacy tokens that are still in use as ours is. However, this also means we can't change that token out and it is tied to Nina's account and permissions. I also tried looking at other solutions for inviting members but all of the ones I could find relied on legacy tokens. It seems like the best idea for now is to just leave slackin extended be. If it ever goes down we could always just use an invite URL that expires in one month and just make it so the tech lead refreshes it once it expires which could be done at the same time as refreshing the repo secrets.

**Comment by ExperimentsInHonesty** [comment]
@Zak234 What is the token tied to exactly?  Is it her email address, it is the slack username or is it the slack ID?

**Comment by Zak234** [comment]
@ExperimentsInHonesty It should be tied to her slack ID.

**Comment by ExperimentsInHonesty** [comment]
https://hackforla.slack.com/join/shared_invite/zt-1ebi41ov6-wBbFoW3bbpd1~EQEAX5kdA#/shared-invite/email/expanded-email-form

**Comment by ExperimentsInHonesty** [comment]
https://join.slack.com/t/hackforla/shared_invite/zt-1ebi41ov6-wBbFoW3bbpd1~EQEAX5kdA

**Comment by Zak234** [comment]
I was able to contact Nina and am trying to set up a meeting time.

**Comment by ExperimentsInHonesty** [comment]
@Zak234 Hi Sakari.  It seems like the invite is broken now.  Can you connect with me, and let me know what exactly has changed.  Its been broken for a few weeks.

**Comment by ExperimentsInHonesty** [comment]
It turns out that the whole Heroku app is now not available.  The ownership of the invite has been changed.  This issue is now closed.

**Comment by ExperimentsInHonesty** [comment]
This will be replaced by an issue to see if there are other ways to send slack invites.

**Comment by ExperimentsInHonesty** [comment]
- A new ER #4277 was created
