### ISSUE TITLE
Refactor CSS for Home Page Footer on Smaller Screens for Redesigned Homepage

### ISSUE THREAD

**Issue by Zak234** [hackforla/website#3437]
### Overview
Currently, when you compress the HfLA home page on a computer screen, the CSS for mobile doesn't activate. We need to update the CSS so that the mobile CSS is activated for the compressed Home Page to ensure the intended formatting.

### Action Items
- [x] Feature Branch: You will be working off a feature branch called feature-homepage-launch. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] Review [_footer.scss](https://github.com/hackforla/website/blob/feature-homepage-launch/_sass/components/_footer.scss) and [_footer.html](https://github.com/hackforla/website/blob/feature-homepage-launch/_includes/footer.html) to understand how CSS is applied to the footer
- [x] Change the CSS so that the footer displays like the mobile version on compressed screens
- [x] Confirm everything is working as intended
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into feature-homepage-launch. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article

### Resources/Instructions
- Current redesigned Home page
  <details>
    <summary>Click here to see the current redesigned Home page as it is being compressed from 1024 to smaller sizes in developer tools:</summary>

    ![redesigned-homepage-footer-compression problem](https://user-images.githubusercontent.com/31293603/197980712-acf224a4-dae1-4764-8fad-ed84c77ce8ed.gif)

  </details>

- Desired Home page for smaller screens:
<img width="188" alt="intended home page" src="https://user-images.githubusercontent.com/67162265/197667595-e35a1ca1-0c72-400a-8559-f8d354fd4112.png">

Files:
- [_footer.scss](https://github.com/hackforla/website/blob/feature-homepage-launch/_sass/components/_footer.scss) 
- [_footer.html](https://github.com/hackforla/website/blob/feature-homepage-launch/_includes/footer.html) 
- [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- [Homepage Redesign in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)

**Comment by JessicaLucindaCheng** [comment]
@Zak234 Thanks for writing this issue! There were a couple things I noticed:

1) The footer on the feature-homepage-launch branch looks like this
    <details>
      <summary>Click here to see what the footer looks like on the redesigned homepage</summary>
      <img width="188" alt="Footer-redesigned-homepage-mobile" src="https://user-images.githubusercontent.com/31293603/183502629-ff9eae47-122f-4253-99a7-b723c870ef85.png">
    </details>
    This is from changes implemented from part of this pull request #3183. **Note:** Some of the links do not work because the anchors have not been implemented yet for some of the menu items.

2) I noticed your links to the _footer.scss and _footer.html are for the code in the gh-pages branch. If the developer is going to be working off the feature-homepage-launch branch for this issue, I recommend you link to the code in the feature-homepage-launch because the code for these files in feature-homepage-launch branch are different from the files in gh-pages.

**Comment by ExperimentsInHonesty** [comment]
@Zak234 Jessica sent you a message about this issue, bumping this back into your inbox

**Comment by kathrynsilvaconway** [comment]
@Zak234 
Hi, Sakari. Is this issue ready to be approved, or are you still working on it? Please let me know if you need any help this so I can get it approved and in the queue.

**Comment by ExperimentsInHonesty** [comment]
Sakari seems to have left the project.  Please review his issue and Jessica's comments and prepare the issue for milestone

**Comment by blulady** [comment]
Great eye as always @JessicaLucindaCheng!! I believe I have made the corrections she recommended. Linking to the eature-homepage-launch _footer.scss and _footer.html as well as replacing the image. Did I replace it with the right image from figma? This was the image under option 2 in the red square? I didn't see anything labeled feature-homepage-launch....

**Comment by JessicaLucindaCheng** [comment]
@blulady Thanks for making the changes! Remember to remove the `Draft` label off of an issue when you add a `Ready for Milestone` label on it. I went ahead and did it this time.

I replaced the image of the current redesigned homepage footer with a gif to illustrate the problem better and because the original image was out of date.

**Comment by blulady** [comment]
@JessicaLucindaCheng Thank you!! We need all the help we can get.

**Comment by PeterSYoo** [comment]
i. Availability: 4pm-5pm PST 11/01/22
ii. ETA: 11/03/22

**Comment by bishrfaisal** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

P.S. Please remember to always move your issue to the "In Progress" column when you self-assign. We have moved this issue for you.

**Comment by PeterSYoo** [comment]
Blockers: I'll be joining a hackathon from Nov 16 - Nov 21, but I'll be available again from Nov 21st!

**Comment by h3nry-m** [comment]
Hi all!
i. Availability: During the work week evenings
ii. ETA: Just sent a pull request. Please review and let me know if I understood the objective correctly.

**Comment by Jaretzbalba** [comment]
Review availability: Weekdays 10-12pm
ETA: 12/26 5pm

**Comment by JessicaLucindaCheng** [comment]
- Merged pull request #3774 fixes this issue
