### ISSUE TITLE
Add 100 automations website to HackForLA.org

### ISSUE THREAD

**Issue by Aveline-art** [hackforla/website#3440]
### Overview
As a user, I want to be able to find links to our web applications on the Hack for LA website so that I can easily access them. For this issue, let's add 100automations.org to the project card for 100 Automations.

### Action Items

- [x] Open _projects/100-automations.md in VS Code or your IDE, then under `links` add the following:
  ```
    - name: Site
      url: 'https://100automations.org/'
  ```
- [x] Using Docker to view the website locally, check the Site link you just added shows up under both the Links field and the Resources section on the [100 Automations webpage on the Hack for LA website](https://www.hackforla.org/projects/100-automations)

### Resources/Instructions
- [100 Automations webpage on the Hack for LA website](https://www.hackforla.org/projects/100-automations)
- [_projects/100-automations.md](https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md?plain=1)
- https://100automations.org/

**Comment by arpitapandya** [comment]
Availability for this week: 6hrs
My estimated ETA for completing this issue: 2hrs

**Comment by arpitapandya** [comment]
Time spent: 1hr to complete
Availability: 6hrs for next week
Blockers: None

**Comment by 7kram** [comment]
@ExperimentsInHonesty Issue has been closed but we can add an **Onboarding Flow** milestone
