### ISSUE TITLE
Update Resource Cards On Projects Pages

### ISSUE THREAD

**Issue by kathrynsilvaconway** [hackforla/website#3449]
### Overview
As a developer, I need our site to align with our current design standards to give our users a more consistent experience. For this issue, we will update the resource cards on the individual projects pages to accommodate multiple lines of text.

### Action Items

 - [x] Implement OPTION 3 in this [updated Figma design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=18798%3A126490) to create the new resource cards
     - [x] Note there is an example of what it is supposed to look like when there are longer and shorter lines and there are details for dev off to the left side of the Figma design.
     - [x] Locate the html tag that impacts `resource-card` list item in each project page
     - [x] Find the scss file and add the inline-size and overflow wrap to implement the wanted effect
     - [x] Note: implement `inline-size: min-content;` and not a particular pixel size
- [ ] When this issue is closed, release the dependency on #3118 and transfer the recommendations for mobile view

### Resources/Instructions
<details>
<summary>Current styling</summary>
<img width="897" alt="Screen Shot 2021-12-18 at 9 49 12 PM" src="https://user-images.githubusercontent.com/63771558/146663230-532beb3a-bb6d-409f-b91b-918dcd59a2c8.png">
</details>
<details>

<summary>Option 3</summary>
<img width="897" alt="Screen Shot 2021-12-18 at 9 49 45 PM" src="https://user-images.githubusercontent.com/81049661/182509743-5accb302-c6ab-4698-b12a-26e5f547566b.png">
</details>

- [Mozilla CSS Resource](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Text/Wrapping_Text)
- [Design System](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
- [Material Design-cards](https://material.io/components/cards#behavior)
- This issue solves issue #2606

**Comment by ExperimentsInHonesty** [comment]
@JohnJBarrett22 Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by ExperimentsInHonesty** [comment]
BTW.  After this issue is done, please choose issues that match your criteria (size, and role) from the prioritized backlog, instead of the new issue approval column.  I noticed that this issue and #3355 both came from new issue approval.

**Comment by kathrynsilvaconway** [comment]
@JohnJBarrett22  Hi, this issue has not been updated in over 2 weeks. If you are still interested in working with HfLA, please let us know by updating your ETA and Availability. If we don't hear back within 7 days, we will unassign you from this issue and put it back in the queue. Thanks!

**Comment by jdingeman** [comment]
ETA: Wednesday 10/5/22 EOD
Availability: after 3pm each day

**Comment by jdingeman** [comment]
Blocker: Branch does not pass linter for some reason. Unsure of best solution to this. I think it may have to do with updating stylelint as some rules were deprecated in [new version](https://stylelint.io/migration-guide/to-14/).
