### ISSUE TITLE
Tech issue: Unable to change Toolkit page

### ISSUE THREAD

**Issue by ethanstrominger** [hackforla/website#3453]
### Overview

The first item on the toolkit page says "HackforLa requires 2FA...".  I changed every occurrence of the phrase and the change does not show up.

### Action Items

TBD

### Resources/Instructions

- Deploy HfLA to Docker following instructions in Contributing.md.
- Change everywhere in source code it says "HfLA requires 2FA" to "Elephant"
- The change does not show up on the Toolkit page on localhost:4000

Similar issue when I add or delete an HTML directory into _guide_pages directory 
  - I don't see the added page 
  - The description for the deleted page shows up on the toolkit page.  When you click on it, you get an error message because the file does not exist.

### Is there a dependency?

No

**Comment by abenipa3** [comment]
@ethanstrominger I investigated this issue. If deleting the _site folder doesn't work, then it seems we need to hit the refresh button after every change made to the code files. Here are the steps I took to test this:

- I ran docker per our `Contributing.md`
- Tested by changing "HfLA requires 2FA" to "Elephant" as well as "Our toolkit" to "Our Elephant" using code files `pages\toolkit.html` and `_guide-pages\2FA.html`.
- Hit the refresh button and the changes will appear as seen below.

Please feel free to reach out if have any further questions. 👍 

![image](https://user-images.githubusercontent.com/38295612/183559137-ff3037a2-2c08-4a71-abff-ada8d337f7c8.png)

![image](https://user-images.githubusercontent.com/38295612/183559111-167930e0-1155-441f-bb63-c76b920f3d4d.png)

**Comment by ethanstrominger** [comment]
@alyssabenipayo Clearing the cache did not work for me but deleting _site did, followed by docker-compose-down and docker-compose up.  I will experiment later and once I get something that works, I will update the guide.

**Comment by abenipa3** [comment]
@ethanstrominger Hello, checking in - Have you informed dev leads regarding this issue? Was it viewed by dev leads as well? It seems like this issue was used as a Q&A which I'm not sure it's meant to be used this way.

**Comment by JessicaLucindaCheng** [comment]
@ethanstrominger This issue with not being able to see changes made on the website is already addressed in our [CONTRIBUTING.md section 2.7.b.i. What if you cannot see your changes locally within Docker?](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-what-if-you-cannot-see-your-changes-locally-within-docker).

In the future, if you have questions, please reach out to us on Slack in the #hfla-site channel. Thanks.

**Comment by JessicaLucindaCheng** [comment]
Closing this issue because  [CONTRIBUTING.md section 2.7.b.i. What if you cannot see your changes locally within Docker?](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-what-if-you-cannot-see-your-changes-locally-within-docker) already exists on how to address this problem
