### ISSUE TITLE
Update Project Profile: Hack for LA Website

### ISSUE THREAD

**Issue by vaisali89** [hackforla/website#3473]
### Overview
As a product manager of Hack for LA Website, I want my project's details to be up to date on the HackforLA website

### Project card
Insert url of your project card here before sending; your card(s) can be found in this folder: https://github.com/hackforla/website/tree/gh-pages/_projects

### Action Items

- [x] [Hack for LA Website Team Leadership
   - [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in a new comment below:
      - [x] title
      - [x] description
      - [x] image
      - [ ] leadership
         - [ ] Name
         - [ ] GitHub handle
         - [ ] Role
         - [ ] SLACK ID
      - [x] links
         - [x] GitHub
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] technologies
      - [x] partner
      - [x] tools
      - [x] status
 - [ ] If you need updates to your meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue in a new comment below

### Resources
[VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

**Comment by vaisali89** [comment]
Add
Vaisali Krishna Kumar
@vaisali89 
UX Research Lead
U028RCG9Z44

**Comment by ExperimentsInHonesty** [comment]
Looks like these changes have already been made.  Closing this issue
[screencapture-hackforla-org-projects-website-2022-09-12-14_16_02.pdf](https://github.com/hackforla/website/files/9551879/screencapture-hackforla-org-projects-website-2022-09-12-14_16_02.pdf) - clicking link will download the pdf

![screencapture-hackforla-org-projects-website-2022-09-12-14_16_02](https://user-images.githubusercontent.com/37763229/189760422-af9ba9a4-5fc0-404c-b2af-98ed98c1fa46.png)
