### ISSUE TITLE
Update Project Profile: BallotNav

### ISSUE THREAD

**Issue by kcoronel** [hackforla/website#3481]
### Overview
As a product manager of BallotNav want my project's details to be up to date on the HackforLA website

### Project card
Insert url of your project card here before sending; your card(s) can be found in this folder: https://github.com/hackforla/website/tree/gh-pages/_projects

https://github.com/hackforla/website/commit/f262cf7b87be1b558b534cb739ba11de2f423ee4 

#### BallotNav Team Leadership
- [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in a new comment below:
   - [x] title
   - [x] BallotNav is a tool that aims to help prevent disenfranchisement by providing reliable and up-to-date information on ballot drop off locations across the US. While some states have detailed information about ballot drop off locations, others leave it up to the local jurisdiction to publish that information. In some states, Counties, Towns, Parishes, etc., do not have websites, so there is no reliable online source for ballot drop off information. _BallotNav was created to provide a reliable online resource about where to drop your ballot, hours, accessibility, etc. We do this by calling each Jurisdictional office provided by the secretaries of state and confirming locations details._
    - [x] image
    - [x] leadership
       - [x] Please remove Alina, Randall, Jake, Seymour, Irina, and Federica
       - [x] Please add
          - [x] Stacey Rebekah Scott 
             - [x] staceyrebekahscott
             - [x] Product Manager 
             - [x] U02U9Q5DUF6
          - [x]  Layne Mostyn
             - [x] layneam
             - [x] Product Manager 
             - [x] U032H8FJX6U
          - [x]  Zuri Smith
             - [x] zuriisawesome
             - [x] UX Researcher 
             - [x] U035UP9N5PG
          - [x]  Jon Lam 
             - [x] jonlam27
             - [x] UX Researcher 
             - [x] U01N6C5GDA8
      - [ ] links
         - [x] GitHub
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
         - [ ] Please delete read me link, it is not necessary when we have the GitHub link on the project card 
      - [x] technologies
      - [x] partner
      - [x] tools
      - [x] status
 - [ ] If you need updates to your meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue in a new comment below

#### Hack for LA Developer Action Items
- [ ] Make the changes specified above
- [ ] after the merge, reach out to the issue author and get her to add a comment to the issue if she accepts the changes (UAT).

### Resources
[VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

**Comment by aricforrest** [comment]
Availability: Friday - Monday 9am - 12pm
ETA: 10/3/2022
