### ISSUE TITLE
Clean up selectors in _toolkit.scss

### ISSUE THREAD

**Issue by ericvennemeyer** [hackforla/website#3489]
### Overview
As a developer on the website team, SCSS code is easier to understand and maintain when it does not contain duplicate selectors. This issue is to consolidate duplicate selectors within `_toolkit.scss`.

### Action Items

- [x] Duplicate selectors are present in three places within [_toolkit.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_toolkit.scss). For each instance, remove overwritten properties and combine the remaining active properties under one selector:
  - [x] `.resource-svg-icons` appears on line 120, and again on line 225. 
  - [x] `.toolkit-info-container` appears on line 126, and again on line 230.
  - [x] `.toolkit-info-container h3` appears on line 130, and again on line 231. 
- [x] Note that properties in the second selector that match properties in the first will take precedence and overwrite the previous properties. See [CSS specificity rules](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) for reference.

### Acceptance Criteria
- [x] Compare the toolkit page at [localhost:4000](http://localhost:4000/) with the [toolkit page on the Hack for LA website](https://www.hackforla.org/toolkit/) to ensure your code modifications don't result in any visible change.

### Resources/Instructions
The duplicate selectors were highlighted when they failed to pass a `Lint SCSS` test for PR #3483. 
[_toolkit.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_toolkit.scss)
[toolkit page](https://www.hackforla.org/toolkit/)
[CSS Specificity Rules](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity) --> "When two selectors in the same cascade layer and origin have the same specificity, proximity is important; the last selector wins."

**Comment by kathrynsilvaconway** [comment]
@ericvennemeyer Nice work writing this up, Eric. I am removing the draft label,  it is ready for approval.

**Comment by bishrfaisal** [comment]
@ExperimentsInHonesty Issue is well written and specific. Ready for milestone.

**Comment by 7kram** [comment]
@ExperimentsInHonesty very clear and straight-forward! We can add a "good second issue" label for new members.

Maybe move the last action item: "comparing toolkit page" to an **Acceptance Criteria** section at the end

**Comment by ExperimentsInHonesty** [comment]
[7kram](https://github.com/7kram) said 

> @ExperimentsInHonesty very clear and straight-forward! We can add a "good second issue" label for new members.
> Maybe move the last action item: "comparing toolkit page" to an Acceptance Criteria section at the end

@7kram 
- I agree with moving the comparing toolkit page to acceptance criteria section.  I did that.
- Good second issues are more prescriptive than this, because the purpose of a good second issue is to test your development environment.  Good Small issues are actually issues which require you to make some decisions or otherwise be an independent engineer.

**Comment by Mattre7** [comment]
i. Availability: Sundays and Mondays. Rest of the days I work, but can still do a little bit, especially after 9 PST.
ii. Likely Tuesday 9/20 (tomorrow), at the latest, Sunday 9/25.
