### ISSUE TITLE
Update Contributing.md With Improved Git Hygeniene Practices

### ISSUE THREAD

**Issue by kathrynsilvaconway** [hackforla/website#3493]
### Overview
We need our documentation for working on issues to be as up-to-date as possible and to reflect best practices for Git Hygiene, so all developers can create the same quality of code.

### Action Items
- [x] In our Contribiuting.md, at the end of section 2.7.a, 
  - [x] add the following:
IMPORTANT: Before you push your local commits to your repository, sync your fork to the main Hack For LA website repository. `git pull upstream` will ensure that your local repository is up-to-date with the main site:

```bash
git pull upstream
```
You can also sync your fork directly on GitHub by clicking "Sync Fork" at the right of the screen and then clicking "Update Branch"
   - [x] Add a brief screen capture to demonstrate syncing the fork on GitHub.
- [x] Make the Following changes to section 2.7.d:
    - [x] Change section title to read "Working on an issue (4): Pulling from upstream before you push"
    - [x] Change everything above subsection "i" to the following:

````
IMPORTANT: Before you push your local commits to your repository, sync your fork to the main Hack For LA website repository. `git pull upstream` will ensure that your local repository is up-to-date with the main site:

```bash
git pull upstream
```
You can also sync your fork directly on GitHub by clicking "Sync Fork" at the right of the screen and then clicking "Update Branch"
````
- [x] Add a brief screen capture to demonstrate syncing the fork on GitHub.

### Resources/Instructions
[Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)

**Comment by ExperimentsInHonesty** [comment]
@kathrynsilvaconway I updated the overview to reflect the format required `We need to do X for Y reason`

> As a developer, I need our documentation for working on issues to be as up-to-date as possible. For this issue, we will update the [Contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) file to reflect best practices for Git Hygiene.

**Comment by ExperimentsInHonesty** [comment]
**@kathrynsilvaconway @7kram  figured out that if you use four backticks to surround the three backticks, you can get a code block within a code block.  Copying the code block above gives us:**

IMPORTANT: Before you push your local commits to your repository, sync your fork to the main Hack For LA website repository. `git pull upstream` will ensure that your local repository is up-to-date with the main site:

```bash
git pull upstream
```
You can also sync your fork directly on GitHub by clicking "Sync Fork" at the right of the screen and then clicking "Update Branch"


**Now that we have made this change and others, please re-review the issue**

**Comment by MattPereira** [comment]
Availability: 1 PM - 3 PM
ETA: End of Day 10/17/22
