### ISSUE TITLE
Place your request for changes to your project homepage here

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#351]
### Overview
You are here because you were sent a link to your temp page on the hack for LA website (hackforla.org) and we want to hear about the information you want added or changed on your project homepage.

### Action Items

- [ ] Identify which team you are writing from (engage, tdm-calculator, etc.)
- [ ] Tell us what information needs to be changed, or what new information or resource you want us to link to.

### Resources/Instructions
Here is a list of all the active projects with project pages:
https://www.hackforla.org/projects/311-data.html
https://www.hackforla.org/projects/engage.html
https://www.hackforla.org/projects/equity-language.html
https://www.hackforla.org/projects/food-oasis.html
https://www.hackforla.org/projects/hellogov.html
https://www.hackforla.org/projects/lucky-parking.html
https://www.hackforla.org/projects/metro-ontime.html
https://www.hackforla.org/projects/new-schools-today.html
https://www.hackforla.org/projects/public-tree-map.html
https://www.hackforla.org/projects/record-clearance-project.html
https://www.hackforla.org/projects/tdm-calculator.html
https://www.hackforla.org/projects/undebate.html
https://www.hackforla.org/projects/vrms.html
https://www.hackforla.org/projects/website.html

**Comment by joelparkerhenderson** [comment]
Thanks! Please make mobile friendly a.k.a. responsive a.k.a. when the browser window is narrower, then the page item layout changes such that the various items, icons, etc. all show up on the browser screen. 

You can see an example in the Equity Language page: when the browser screen gets narrow, the project text does not reflow correctly to keep all the text on screen; the same kind of visual interference seems to happen with all the pages, and also with all the sections for "Contributors" and "Project Resources".

**Comment by emillipede** [comment]
Thanks @ExperimentsInHonesty, for public tree map:

- Please remove the current screenshot. If you need a banner image right now, please use https://www.smgov.net/uploadedImages/Portals/UrbanForest/Yate%206%20%20Dave%20Baiocchi.jpg?n=9712. I have permission to use it. The image credit is Dave Baiocchi, www.studiobaiocchi.com
- Please update the project description: "Public Tree Map helps connect people to Santa Monica's urban forest. The map includes information about each of the 35,000 trees (and vacant tree sites) in Santa Monica's publicly-owned urban forest (compiled from open datasets, digitized city records, and federal ecosystem services values), as well as tools for users to share favorite trees. To reflect tree plantings and removals, the map updates every day."
- Please update looking for: Front-end web development (JavaScript, Leaflet), data processing (geopandas, python), QA and UX testing, appreciation for trees (anyone interested is welcome!)

Would you prefer I make the requests in a PR?

**Comment by ExperimentsInHonesty** [comment]
@emillipede I'll queue your changes up for a member of the website team.  But thanks for offering to do the PR!   -  The image doesn't resolve for me though.  I get this:
![Screen Shot 2020-03-12 at 12 42 41 PM](https://user-images.githubusercontent.com/37763229/76561036-ba63e100-645f-11ea-9d5f-a0d48aeb3602.png)

**Comment by emillipede** [comment]
@ExperimentsInHonesty I just shared the image in #246

**Comment by ashlingam** [comment]
For Lucky Parking, @breeze provided a revised list of open roles: Frontend Software Engineer, Backend Software Engineer, Advanced Data Scientist, Python Enthusiast

**Comment by ashlingam** [comment]
@leonelRos @yulia-kh For Hack for LA Website project card, please revise title to "Hackforla.org Website"

**Comment by yulia-kh** [comment]
@ExperimentsInHonesty Both files (Website and Lucky parking) have been updated. Pull request has been created.

**Comment by ExperimentsInHonesty** [comment]
**Note for hackforla.org website development team**
If there are changes below this comment, please move this issue to the **in progress** column and self assign.  Then comment when you are done, and move it to the **questions** column.   Also when you do a pull request, mention this issue number but don't write Fixes pound sign issue number.   

If there are no comments below this one, just move on to next issue in prioritized backlog.

**Comment by c-fuchs** [comment]
For Host Home/HomeUnite.Us, please: 
1) Add another meeting to the weekly schedule for 7-8 PM Tuesday nights
2) Change the name to HomeUnite.Us 
3) On the project page, add the demo, wiki, and slack links to the Links section at the top:
demo link (Different from the others, don't judge): https://lacommunity.site/hosthome 
wiki link: https://github.com/hackforla/HomeUniteUs/wiki
slack link: https://hackforla.slack.com/archives/CRWUG7X0C

**Comment by ExperimentsInHonesty** [comment]
please change my name from Wolf to Wolfe on civic-tech-index project homepage card.

**Comment by ExperimentsInHonesty** [comment]
on this page: https://www.hackforla.org/project-meetings please link 

civic tech index (thurs and sunday) to their project page: https://www.hackforla.org/projects/civic-tech-index
host homes change to Home Unite Us (saturday) to their project page: https://www.hackforla.org/projects/host-home

**Comment by breeze-094** [comment]
@harishlingam 
for lucky parking web page, update below items(keep the items that are not covered below):

Partner: Seeking
Tools: Google Colab, AWS, React-JS
Languages: Python, JavaScript, PL/pgSQL
Front End Lead: David Kim
Back End Lead: Elly Kyles

**Comment by ExperimentsInHonesty** [comment]
@breeze-094 we will be making these changes today with some slight revisions.  See below:

Lucky Parking:
Partner: Seeking
Tools: Google Colab, AWS, (this is a framework and should show up under languages automatically, if it doesn't we will re address: React-JS )
Languages: Python, JavaScript, PL/pgSQL (this should be showing up automatically - it pulls from  if its not, let's talk about why it's not).
Front End Lead: David Kim (david kim's slack member ID: UV407QSBE)
Back End Lead: Elly Kyles (Elly Kyles slack member ID: UPPLBKK71)

**Comment by breeze-094** [comment]
@ExperimentsInHonesty 
Yay , that great!
You can adjust but  just want these words showing up somewhere. 

Thank you so much!

**Comment by ddfridley** [comment]
To #undebate please change Looking for:  to "Node, React, UI/UX, Marketing/Branding/Social Media" thanks.

**Comment by cnk** [comment]
@breeze-094 @ExperimentsInHonesty Lucky Parking is not showing Python and React because the repository we use for getting language data shows the project as 99.9% Jupyter Notebook.

**Comment by ExperimentsInHonesty** [comment]
@breeze-094 - we are going to add a separate "framework" section to each project card on the website and the project homepage.    Please you post your frameworks in this issue: https://github.com/hackforla/website/issues/459

Sent her a message on slack about the above ^

**Comment by ExperimentsInHonesty** [comment]
Created issue #466 for undebate update.

**Comment by ExperimentsInHonesty** [comment]
@cnk Let's have a talk about how we can deal with project's that use Jupyter Notebook's which is obscuring their use of python.  Example: Lucky Parking.   I think its worth having @joelparkerhenderson  talk with their tech lead to see if they actually need Jupyter Notebook.  Their tech lead has reached out before, so I think this is worth exploring before we put in a lot of logic to accommodate getting languages from other places than github.

**Comment by ExperimentsInHonesty** [comment]
after talking with Sophia, it seems like project will move off of Jupyter Notebook and into exposed python files.  So no need to add those manually or change code to allow for manual entry.  This also follows good practice, so that they can get remote contributors by people finding them using the github api.

--- no new open issues at this time

**Comment by ggrrettcchhenn** [comment]
record-clearance-project

1. Please remove all current open roles, and replace with Marketing/Communications.
2. Please add Andan Eddy as our third Product Manager – Slack @Andan Eddy, GitHub Andan-Eddy
