### ISSUE TITLE
Update Project Profile: HackforLA website team

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#3520]
### Overview
As a product manager of the hackforla.org website team I want my project's details to be up to date on the HackforLA website

### Project card
URL of my project card: https://github.com/hackforla/website/blob/gh-pages/_projects/website.md

### Action Items

- [X] hackforla.org website Team Leadership
   - [X] Please check off everything that is ok the way that it is, and if not, please provide the updated information in a new comment below:
      - [x] title
      - [x] description
      - [x] image
      - [X] leadership
         - [X] Name
         - [X] GitHub handle
         - [X] Role
         - [X] SLACK ID
      - [x] links
         - [x] GitHub
         - [x] Slack
         - [x] WIKI
         - [x] Site
      - [x] technologies
      - [x] partner
      - [X] tools
      - [x] status
 - [x] If you need updates to your meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue in a new comment below

### Resources
[VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

**Comment by ExperimentsInHonesty** [comment]
### Check the times on these and open a ticket with VRMS for changes
PM Meeting, Wed 12:00 pm - 1:00 pm
UI-UX Meeting, Thu 5:00 pm - 6:00 pm
UX Research, Wed 2:00 pm - 3:00 pm
UX Design, Wed 2:30 pm - 3:30 pm

**Comment by ExperimentsInHonesty** [comment]
### People to add
- Name: Akram Nour
  - GitHub handle: 7kram
  - Role: PM
  - SLACK ID: U03UW53122J
- Name: Bishr Aboobaker
  - GitHub handle: bishrfaisal
  - Role: PM
  - SLACK ID: U03VDRGD34P
- Name: Vaisali Krishna Kumar
  - GitHub handle: vaisali89
  - Role: Researcher
  - SLACK ID: U028RCG9Z44
- Name:
  - GitHub handle:
  - Role:
  - SLACK ID:

### People to remove
- Simone Campbell
- Providence Onyenekwe

### Tools to add
1Password

**Comment by plang-psm** [comment]
i. Availability: 10hrs
ii. ETA: end of 9/9/22

**Comment by 7kram** [comment]
### People to add
- Name: Simone Samuels
  - GitHub handle: Steph112792
  - Role: PM
  - SLACK ID: U03SJS7LYCC
