### ISSUE TITLE
Create SDG page to be added to Hack for La website

### ISSUE THREAD

**Issue by nathan944** [hackforla/website#3532]
### Overview
Create SDG page to be added to Hack for La website

### Action Items
- [ ] Product
   - [ ] ideate
   - [ ] define feature requirements
   - [ ]  make issues for UI/Development
      - [ ] Design
        - [ ] design the mockup
        - [ ] get feedback from Product
     - [ ] Front-end
         - [ ] develop according to Figma

### Resources
[Figma File](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website)

**Comment by 7kram** [comment]
This is a duplicate of - #3370
