### ISSUE TITLE
Calendar: Removing inactive members

### ISSUE THREAD

**Issue by 7kram** [hackforla/website#3540]
### Overview
We need to remove every member with an "x" by their name for the HfLA Website Team meeting to make room for new members. 

### Prerequisite
- [x] Need to have access to the HfLA website 1Password vault

### Action Items
- [x] Look for the weekly Sunday "HfLA Website Team Meeting" on Google calendar. 
- [x] Find the owner of the team meeting 
   - [x] Log into the associated Gmail account for the owner through 1password
- [x] Once signed in, find the same "HfLA Website Team Meeting" listed above and edit the event: 
   - [x] Remove every person on the invite list with a (x) near their name/profile. 
   - [x] Once you click save, it will ask you whether to apply changes to only this meeting or all subsequent meetings. Choose "This and following events"
   - [x] When prompted with an option to send a message to all impacted guests, write "
 
#### If they have an X  
```
We saw that you had an X next to your name in the invite.  So we have removed you to make space for new team members. If you believe this is a mistake, please message us on #hfla-site Slack, and we will add you right back!
```
#### If they have never accepted the invite (no icon next to their name)
```
We saw that you had never accepted the Google Calendar invite for this meeting. So we have removed you to make space for new team members. If you believe this is a mistake, please message us on #hfla-site Slack, and we will add you right back!
```
### Resources/Instructions
- https://1password.com

**Comment by 7kram** [comment]
Hey @ExperimentsInHonesty Are there any resources I should add to the issue? Please review the issue and see if I should make any changes. Thanks

**Comment by Adaakal** [comment]
Availability: Wednesday 1/17/22 3-4 pm
ETA: 4-5 hours

**Comment by Adaakal** [comment]
Availability: 1/19 7-8pm-Going to office hours today.

**Comment by vanessavun** [comment]
Availability: Thursday-Friday 02/09-02/10 evenings
ETA: Monday, 02/13

**Comment by vanessavun** [comment]
I finished removing members with an "x" next to their name for the Sunday "HFLA Website Team Meeting". I am not attaching a before and after since they would show people's email addresses.

@ExperimentsInHonesty Task complete! Please review/close. Thank you.

**Comment by jdingeman** [comment]
Hi @vanessavun, thank you! We'll review with Bonnie and you can go ahead and move on to your next issue.

**Comment by jdingeman** [comment]
Hi @vanessavun, we've slightly expanded the scope of this issue in include removing anyone who never responded to the calendar invite. Please see below: 

#### If they have never accepted the invite (no icon next to their name)
```
We saw that you had never accepted the Google Calendar invite for this meeting. So we have removed you to make space for new team members. If you believe this is a mistake, please message us on #hfla-site Slack, and we will add you right back!
```

**Comment by vanessavun** [comment]
@jdingeman @ExperimentsInHonesty I removed all emails that never responded (no icon next to their name). We now have a total of 63 guests for the next Sunday meeting.

**Comment by jdingeman** [comment]
@vanessavun, thank you! We can close this issue and move on. Any devs that were removed from the calendar can reach back out to leads on Slack.
