### ISSUE TITLE
Agenda does not show up as a template

### ISSUE THREAD

**Issue by ethanstrominger** [hackforla/website#3549]
### Overview

Create Agenda is missing from New Issue templates

### Action Items

- Read https://github.com/hackforla/product-management/wiki/Agenda-Format
- Tried creating a new issue - no template.
- Template showed for open-source-community when creating a new issue
https://github.com/hackforla/open-community-survey/issues/new/choose
<img width="600" alt="image" src="https://user-images.githubusercontent.com/32078396/190012563-88e4e6f2-0781-42c5-9537-65f33d7544b8.png">
- It does not show for this repository https://github.com/hackforla/website/issues/new/choose
<img width="720" alt="image" src="https://user-images.githubusercontent.com/32078396/190013375-3f58ec22-e496-4072-98bc-d3d20f1b599e.png">

### Resources/Instructions

- Click on Issues, then new Issue.  You should see a Create Agenda option.

### Is there a dependency?

No

**Comment by ExperimentsInHonesty** [comment]
@ethanstrominger please dont remove the missing labels. Until the labels that are supposed to be there are added.

**Comment by ExperimentsInHonesty** [comment]
@ethanstrominger We don't make one time agendas.  We just add the agenda items to existing team agendas.  For instance, on this team you can find all our currently open agendas here: https://github.com/hackforla/website/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+agenda%22

**Comment by ExperimentsInHonesty** [comment]
I removed agenda template from here https://github.com/hackforla/open-community-survey/issues/new/choose.  

I updated this page, so that it has the correct links: https://github.com/hackforla/product-management/wiki/Agenda-Format
