### ISSUE TITLE
Guides Team card: Make Program Area show

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3562]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As a developer, I want the Program Area for the Guides Team to show up on the Guides Team card on the [Projects page](https://www.hackforla.org/projects/), so that I can see what Program Area the Guides Team project falls under. For this issue, we will fix the code in [guides-team.md in the _projects directory](https://github.com/hackforla/website/blob/gh-pages/_projects/guides-team.md?plain=1).

### Action Items
- [x] In your IDE on your computer, navigate to `guides-team.md` in the `_projects` directory
- [x] In your IDE, edit `guides-team.md` by adding a dash in `program area:` so that
  ```
  program area:
  ```  
  becomes
  ```
  program-area:
  ``` 
- [x] Using Docker, check that the Program Area field shows up on the Guides Team card on the Projects page by going to http://localhost:4000/projects/

### Resources/Instructions
- Directory to find the file in your IDE: `_projects/guides-team.md`
- Click on the link to see the source file code: https://github.com/hackforla/website/blob/gh-pages/_projects/guides-team.md?plain=1
- [Projects page on the live website](https://www.hackforla.org/projects/)

**Comment by rolzar** [comment]
Availability for this week: 10hrs
My estimated ETA for completing this issue: 10/1

**Comment by rolzar** [comment]
Blocker: Did the change mentioned above but nothing changed in the card.
<img width="973" alt="image" src="https://user-images.githubusercontent.com/44422381/193201325-d9bba8e0-d101-4ecb-a4be-655214ff8d2c.png">
<img width="925" alt="image" src="https://user-images.githubusercontent.com/44422381/193201452-54fa17c5-b065-4a65-a99e-6463063a2df0.png">
