### ISSUE TITLE
Research Plan: Toolkit Page Filter

### ISSUE THREAD

**Issue by alice-milmac** [hackforla/website#3563]
### Overview
We need to create a research plan so that we can uncover the value of including a new filter within the website. More specifically, we would like to understand if including a "Recommended by" filter will add value for users.

### Action Items

- [x] Create new "RP" label (i.e. RP014) 
- [x] Include "RP014" label within Issue 
- [x] Create "R014: Research Plan: Toolkit Page Filter" folder within shared Google Drive
- [x] Complete Issue and replace "Draft" label with "Ready for Milestone" for Bonnie's review
- [x] Copy the template of the Research Plan
- [x] Create a new document for Research Plan
- [x] Add new document to "R014: Research Plan: Toolkit Page Filter" folder within shared Google Drive
- [x] Submit completed Research Plan document to UX Lead (Sijia) for review

### Resources/Instructions

- [HfLA Guide to Research Plan](https://docs.google.com/document/d/1ovSBNVkuizZD2EMOE2w522_x-sOAzQBEheMqfPWmQKk/edit#heading=h.c8tc614ce3iu)

#### Types of Users
- Contributors 
- Hack for LA website users 
- Donors and 
- Organizations.

#### Resources

- [Research Plan](https://drive.google.com/drive/u/0/folders/1_BAEyxgGtjHzw7PwmBozjf0QnUJ6sVfG)

**Comment by ExperimentsInHonesty** [comment]
@vaisali89 please see the example of the TWE research plan template and guide to filling out the template https://github.com/hackforla/internship/wiki/UX-Research-Guides-Templates
