### ISSUE TITLE
Update Project Profile: Food Oasis 

### ISSUE THREAD

**Issue by yiminng** [hackforla/website#3572]
### Overview
As a product manager of Food Oasis I want my project's details to be up to date on the HackforLA website. As developers, we need to update the Food Oasis project's description, leadership, partner, and tools.

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the [food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md) file and find the `leadership`, `description`, `partner`, and `tools` variables.
- [x] Replace the existing `description` variable with the following: 
```
Food Oasis is focused on supporting individuals seeking food in Los Angeles. We aim to provide an up-to date resource on food pantries and meal services. The team is currently working on updating listings on our website [foodoasis.net](http://foodoasis.net/), improving UI, and establishing new partnerships.
```
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
    - [x] Name: Stacey Rebekah Scott
         Github Handle: staceyrebekahscott 
         Role: Senior Project Manager
         Slack ID: U02U9Q5DUF6
    - [x] Name: Erin Dean
         Github Handle: itserindean
         Role: Senior Product Manager
         Slack ID: U03JSNJ3UKE
- [x] Update the value of the following team member's `role`s
    - [x] Name: Gigi Patel
          Role: Lead UX Researcher 
    - [x] Name: Seiko Igi
           Role: Senior Product Designer
    - [x] Name: John Darragh 
          Role: Lead Developer 
    - [x] Name: Bryan Wu
          Role: UX/UR Lead
    - [x] Name: Hannah Zulueta
           Role: Lead Developer 
 - [x] partner (remove seeking)
 - [x] Add the following `tools`
     - [x] paper prototyping
     - [x] Google forms
     - [x] Google Sheets
     - [x] Google Analytics
     - [x] FigJam
     - [x] SPSS
     - [x] Mplus
     - [x] AtlasTI
     - [x] Usabilityhub.com surveys
 - [x] Update the following `tools`
     - [x] change `pencil and paper` to `whiteboard / paper & pencil`

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- Food Oasis markdown file: https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### Related Issues
- Meeting time update submitted by the Food Oasis team to VRMS: https://github.com/hackforla/VRMS/issues/1216

**Comment by fancyham** [comment]
Hi, Yiming, I’m a UX/UR Lead aka design/research lead

**Comment by sei1122** [comment]
Can you change my role to Senior Product Designer?

**Comment by yiminng** [comment]
https://github.com/hackforla/VRMS/issues/1216

**Comment by yiminng** [comment]
Made an update to team roster - Removed Rylan, and changed meeting times

**Comment by ExperimentsInHonesty** [comment]
@yiminng 
- Under Tools
  - You added excel but all spreadsheets should be Google sheets, so I changed it
  - You added R.  If you are using R to do data analysis then it should be added to the repo, and then it will automatically show up under languages, which is pulled directly from GitHub's API

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge I am reformatted the issue to make it clearer what are changes and what are additions.  This is ready for the dev leads/merge team to do whatever you think necessary so that we can release to the developers.

**Comment by christinaor** [comment]
Availability: 10am-5pm EST, M-F
ETA: Mon 10pm EST

**Comment by MattPereira** [comment]
Removing action item that instructed adding **Yi Min Ng** to leadership because **Erin Dean**, Senior Product manager of Food Oasis, posted [this comment](https://github.com/hackforla/VRMS/issues/1216#issuecomment-1397859086) in the related VRMS meeting time change issue indicating that Yi has been offboarded as of 2 weeks ago.

**Comment by roslynwythe** [comment]
Hi @itserindean @MattPereira I noticed I that in the new description, the project site URL is listed as http://foodoasis.net, but in the "Links" and "Resources" sections, the site links point to https://foodoasis.la".  Would it be better if the links were all consistent?

**Comment by itserindean** [comment]
I confirmed with @staceyrebekahscott and we agree we'd like it to be http://foodoasis.net everywhere for consistency

**Comment by roslynwythe** [comment]
- New Issue Update Food Oasis Project URL in Profile Links and Resources #3955 addresses the site URL in the Links section.

**Comment by ExperimentsInHonesty** [comment]
@staceyrebekahscott @itserindean 
- Please confirm that we made all the changes you asked for except changing the URL, which has been moved to another issue https://github.com/hackforla/website/issues/3955

**Comment by staceyrebekahscott** [comment]
Remove Jieun Ryu (no longer part of the team). 

Meeting times should be updated as follows: 

- Mon 6:30-7PM Development Team Meeting
- Every Other Tues 6:30-7:30PM UX Research Team Meeting
- Wed 5-6PM Product/ Project Team Meeting
- Thurs 10-11AM Content Team Meeting
- Thurs 6-7PM Leads/ PM Team Meeting
- Thurs 7-8PM Design Team Meeting
- 1st Thurs of Each Month All Hands Team Meeting

**Comment by ExperimentsInHonesty** [comment]
@staceyrebekahscott 

Please see my message in the product management community of practice channel for how to self-service updating meeting times in VRMS!!

I will pass on the request to remove  Jieun Ryu to the development team

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge please make a new issue to remove Jieun

**Comment by roslynwythe** [comment]
- New Issue for removing Jieun Ryu:  #4238
