### ISSUE TITLE
Link projects in program areas page to project page

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#3592]
### Overview
We need to ensure that the Hack for LA project page links are attached to their respective project cards on [program areas page](https://hackforla.org/program-areas.html).

### Details
Developers have noted that the files in [/_projects](https://github.com/hackforla/website/tree/gh-pages/_projects) do not have the links for their respective project pages. Previously, when a user clicked on the title of a program card, they would be led to the Hack for LA project specific webpage, but currently they lead to the GitHub project webpage. We need make it so when a user clicks on the link in the mini-cards, they are redirected to the project page. 

### Action Items / Pseudo Code
- [x] Research Liquid if it is possible to reference the project filename
- [x] Go to [pages/program-areas.html](https://github.com/hackforla/website/blob/gh-pages/pages/program-areas.html) and navigate to the  `<ul class="project-card-mini-list-alignment">` element
- [x] Within the for loop, assign the filename to a variable as a string 
  - [x] Manipulate the string in the variable to exlcude the .md portion of the filename
  - [x] Append this to [projects page](https://www.hackforla.org/projects/) link so that it will lead directly to whichever project page it is referencing 
- [x]  Change the href in `<a class="project-card-mini-title" href="{{project.links[0].url}}">{{project.title}}</a>` so that it links the title of the project card to the project page
  - [x]  For example, clicking on this will lead to [311 Data](https://hackforla.org/projects/311-data) instead of its [GitHub page](https://github.com/hackforla/311-data) 
![image](https://user-images.githubusercontent.com/88953806/197653795-57c980dc-cb95-49ae-a570-feec3c06d52a.png)

### Resources
- [Liquid documentation](https://shopify.github.io/liquid/)
- [Liquid in Jekyll](https://jekyllrb.com/docs/liquid/)
- [Program Areas](https://github.com/hackforla/website/blob/gh-pages/pages/program-areas.html) source code
- https://www.hackforla.org/program-areas

**Comment by luiderek** [comment]
Availability: 10am-10pm PDT
ETA: < 4 hours

**Comment by ExperimentsInHonesty** [comment]
While reviewing this page, I see that the project mini card doesn't work for long titles
https://www.hackforla.org/program-areas.html
![image](https://user-images.githubusercontent.com/37763229/204127212-63daac38-ad5d-4bb8-8415-81c57357f35d.png)

**Comment by ExperimentsInHonesty** [comment]
Product to make a new issue to deal with the long titles.  
We have to look at why the titles are long, can they be shortended and is there a limit

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge 

I have looked at the project names and only two are a problem. 
![image](https://user-images.githubusercontent.com/37763229/221388961-e7a84e22-07c2-496b-a5ef-1d1fa9e41f3a.png)
![image](https://user-images.githubusercontent.com/37763229/221388965-cc8d88cf-d88c-4cd3-8ccf-821d76148740.png)
 
I suggest the following name changes
change 
```
Los Angeles Criminal Sentencing Project
```
to 
```
LA Criminal Sentencing
```

Change
```
Not Today - Self-Defense Against Suicidal Thoughts
```
to
```
Not Today
```
and change the description for the project from

```
Not Today is an app intended to help people wait out periods of suicidal thinking without acting on their thoughts.
```
to
```
Not Today - the self-defense against suicidal thoughts app is intended to help people wait out periods of suicidal thinking without acting on their thoughts.
```

Please make an issue

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - issues to the above have been made here:
- https://github.com/hackforla/website/issues/4081
- https://github.com/hackforla/website/issues/4082
