### ISSUE TITLE
Update Project Profile: HackforLA website team 

### ISSUE THREAD

**Issue by 7kram** [hackforla/website#3596]
### Overview
As a product manager of HackForLA website team I want my project's details to be up to date on the HackforLA website

### Project card
URL of my project card: https://github.com/hackforla/website/blob/gh-pages/_projects/website.md

### Action Items

- [x] HackForLA Website team Team Leadership
   - [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in a new comment below:
      - [x] title
      - [x] description
      - [x] image
      - [x] leadership
         - [ ] Name
         - [ ] GitHub handle
         - [ ] Role
         - [ ] SLACK ID
      - [x] links
         - [x] GitHub
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] technologies
      - [x] partner
      - [x] tools
      - [x] status
 - [x] If you need updates to your meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue in a new comment below

### Resources
[VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

**Comment by 7kram** [comment]
### People to add
- Name: Stephanie Samuels
  - GitHub handle: Steph112792
  - Role: PM
  - SLACK ID: U03SJS7LYCC

**Comment by jyaymie** [comment]
Availability: 5 hours
ETA: 10/18/22 EOD

**Comment by 7kram** [comment]
Just checked the project page and updates were made.
