### ISSUE TITLE
Add Merge Team to Current Project Team

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#3619]
### Overview
As a member of the Hack for LA Website team, I want the information on the [Hackforla.org Website project information page](https://www.hackforla.org/projects/website) to be up to date. For this issue, we will be updating the Current Project Team section of the [Hackforla.org Website project information page](https://www.hackforla.org/projects/website).

### Action Items
 - [x] Remove Sakari Salminiitty
 - [x] Remove Phuong Van
 - [x] Add Justin Dingeman under merge team 
      - [x] Slack ID: U03P33YE2PQ
      - [x] title: Merge Team
      - [x] GitHub handle jdingeman

### Resources
[Website project information page](https://www.hackforla.org/projects/website).
location of markdown file: _projects/website.md

**Comment by PeterSYoo** [comment]
Availability for this week: 5pm-6pm PST Sun-Sat
My estimated ETA for completing this issue: 11/01
