### ISSUE TITLE
Design a fix for the dropdown menu design for toolkit page

### ISSUE THREAD

**Issue by sijiapitts** [hackforla/website#3626]
### Overview
During a site audit on Figma design file and on the website, we noticed that the drop-down menu design is not consistent. Each page has its own font size, margin, padding, etc.

We decide the first step is to fix the dropdown menu on the toolkit page. Afterwards, we will move on to the projects page and wins page.

- Project page issue #3277
- Wins page issue #3627

### Update
The UI is completed, tested with the users, and approved as of 9/18/2022. The users believe [this Toolkit page design](https://www.figma.com/file/MVRUNtLFjuamihX8PQg2Ic/Hack-for-LA-Filters-Redesign?node-id=417%3A391336) is the most clear and easy to use. This design version has a dark background and a 3 columns layout on the toolkit guides section. The filters are on the sidebar. The filters section has the same background color as the page, and the text color is white. 

10/30/2022
The design is [completed](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24519%3A284897), and ready for development. 

### Action Items

- [x] Design for web version 
- [x] Design for mobile version 
- [x] Review with the design lead 

### Resources/Instructions
[Hack for LA Team project design file ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A0)
[Figma work file ](https://www.figma.com/file/MVRUNtLFjuamihX8PQg2Ic/Hack-for-LA-Filters-Redesign?node-id=203%3A55960)
[Toolkit page content](https://docs.google.com/spreadsheets/d/1WbACQLJO4WnA7qlc74xuPrsol9-Y1YcJ8y30hu3Ty9c/edit#gid=0)

### Final Design
https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1548%3A1967

**Comment by ExperimentsInHonesty** [comment]
Hi  @sijiapitts  We revised the fields we need on the toolkit page to include Technologies.  Can you add that?

**Comment by sijiapitts** [comment]
@ExperimentsInHonesty Done.  Here is [the updated design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24499%3A284862)

**Comment by ExperimentsInHonesty** [comment]
Here is the order for design

1. Status: Active, Draft, Depreciated
1. Practice Area
1. Tools
1. Resource Type
1. Technologies
1. Source
1. Contributors

**Comment by sijiapitts** [comment]
The design is [completed](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24519%3A284897), and ready for development.

![image](https://user-images.githubusercontent.com/37763229/200191859-d6354884-0461-4f38-9175-adb840da437c.png)

**Comment by ExperimentsInHonesty** [comment]
The design is [completed](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24519%3A284897), and ready for development.

This is probably a medium size issue for front end

**Comment by blulady** [comment]
- So if I am reading this correctly, you want this issue completed before issue #3744, so the instructions to create the CSS for the drop-down menu belongs in the issue that will correspond to this issue and not in #3744

**Comment by ExperimentsInHonesty** [comment]
- Both #3744 and the new issue you will create from here will have the dependency #3256 

- Next step, create the issue and add the dependency

```
#### Dependency
- #3256
```

**Comment by ExperimentsInHonesty** [comment]
@blulady 

- Both #3744 and the new issue you will create from here will have the dependency #3256 

- Next step, create the issue and add the dependency

```
#### Dependency
- #3256
```

**Comment by blulady** [comment]
- see #3985
