### ISSUE TITLE
Update Donate page image's alt text to adhere to WCAG (again)

### ISSUE THREAD

**Issue by blulady** [hackforla/website#3630]
### Overview
We need to update the donate page image's alt text to provide alt text that adheres to the Web Content Accessibility Guidelines (WCAG).

### Action Items
- [x] make the correction to the file
    - [x] from `alt="join us card image"` to `alt=""`
    - [x] from  `alt="donation chart"` to ` alt="Hosting, mailing list services, Zoom accounts, domain names, stickers, t-shirts"`
    - [x] line 28 from `alt="donation form image"` to `alt=""`
- [x] check that the donate page looks the same
- [x] check that the new alt texts got incorporated after the change by inspecting the web page using developer tools
- [x] Review with product referencing the parent issue https://github.com/hackforla/website/issues/2568 

### Resources/Instructions
- link to the tab on google sheets: [Alt Attribute Review, Donate Page ](https://docs.google.com/spreadsheets/d/1abMlPOX88zHTV29E4BFxAYwahCxgJN28Mn95cXr8jak/edit#gid=14599403)
- To correct this mistake we must make the change in the [_includes/donate-card.html](https://github.com/hackforla/website/blob/gh-pages/_includes/donate-card.html)

#### Historical Notes (you do not need to read)
- The development team made a mistake in addressing this [issue](https://github.com/hackforla/website/issues/2886).
- The changes recommended are slightly different than this issue #2886
- This issue also replaces #3238.

**Comment by ExperimentsInHonesty** [comment]
- Update this issue to include fixing the animated gif to be empty alt as well https://github.com/hackforla/website/issues/3238. 
- Then close 3238

**Comment by braguda** [comment]
Availability: 2 hours
ETA: 10/20/2022
