### ISSUE TITLE
Updating Wiki: Creating a Repo

### ISSUE THREAD

**Issue by blulady** [hackforla/website#3634]
### Overview
We need to create a new repository to put the Website Wiki for increased security and navigability. After the new repository is created, we will be installing MkDocs and uploading the Website Wiki into the new repository.

### Action Items
- [x] decide on a name for the new repository
- [x] create a new repository for the wiki within the specs of the MkDoc documentation
- once the repository has been created:
   - [x]  release the dependency on issue #3635 to install MkDocs
   - [x] post the link to the new repository under Resources/Instructions in issue #3635

### Resources/Instructions
https://www.mkdocs.org/

**Comment by roslynwythe** [comment]
Availability: 3:30 - 11:30 11/8, 10 am - 8 pm 11/9, 10 am - 7 pm 11/10
ETA: 11/11

**Comment by ExperimentsInHonesty** [comment]
I cant remember what I was supposed to call the wiki.

**Comment by ExperimentsInHonesty** [comment]
call the repository website-wiki

**Comment by ExperimentsInHonesty** [comment]
repo created https://github.com/hackforla/website-wiki
Added the repo to each of the teams for the website
