### ISSUE TITLE
Updating Wiki: Install MkDocs

### ISSUE THREAD

**Issue by blulady** [hackforla/website#3635]
Dependency
- #3634

### Overview
We need to install MkDocs into the new repository so that we can start to move the content from old wiki to new wiki

### Action Items
- [x] research MkDoc requirements
- [x] make a record of the research/requirements and choose a place in the wiki to keep the research 
 - [x] read the documentation on MkDocs for any additional info you might need to install (and update our documentation with the steps/choices)
 - [x] install MkDocs in the repository listed under Resources/Instructions
 - once MkDocs have been installed in the repository 
    - [x] Move issue #3636 to New Issue Approval column and remove the Dependency label
    - [x] post the link to the research/requirements under Resources/Instructions in issue #3636

### Resources/Instructions
- new repo: https://github.com/hackforla/website-wiki
- https://www.mkdocs.org/ 

#### Themes for mkdocs
- [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/getting-started/) is a theme for MkDocs, a static site generator geared towards (technical) project documentation.
- [Jekyll Doc](https://idratherbewriting.com/documentation-theme-jekyll/index.html) is a documentation theme for [Jekyll](https://jekyllrb.com/). 

#### Article comparing MK Docks vs Jekyll for WIKI
* [MkDocs or Jekyll for Technical Documentation](https://blogs.sap.com/2020/07/24/mkdocs-or-jekyll-for-technical-documentation/) - we decided to go with mkdocks

#### Examples
The Youth Justice Nav Project's documentation currently uses Material for MkDocs.
* [Youth Justice Nav repo](https://github.com/hackforla/youthjusticenav-info/tree/main/docs)
* [Youth Justice Nav documentation static site](https://hackforla.github.io/youthjusticenav-info/Juvenile%20Hall/)

GreenearthOS uses Mkdocks without material
- https://www.greenearthos.org/

#### other stuff

- [notes](https://docs.google.com/document/d/1Se4HW4Ab_UR7tgy9Ul8M0Rxev_wrL36rvPPGqYB93uU/edit)
- [audit spreadsheet](https://docs.google.com/spreadsheets/d/1QzfMX3URWfpfeoun34jRm8oDOxXMAMMRvUDS05WLpNY/edit#gid=0)
- Example of another mkdocks install https://brigade.cloud/projects/

**Comment by t-will-gillis** [comment]
Availability: 10-12 daily most days
ETA: tbd

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis Please move this issue into the in progress column

**Comment by ExperimentsInHonesty** [comment]
I installed the following files into [website-wiki](https://github.com/hackforla/website-wiki/tree/main)
/mkdocks.yml
/workflow/ci.yml
/docs/index.md (just a place holder to open the directory)

And I changed the following items in Settings
![screencapture-github-hackforla-website-wiki-settings-pages-2023-03-06-19_14_20](https://user-images.githubusercontent.com/37763229/223311251-7410f17f-60fc-4117-9374-55e7dd3cd1cc.png)

**Comment by ExperimentsInHonesty** [comment]
This is what it looks like now https://hackforla.github.io/website-wiki/

**Comment by JessicaLucindaCheng** [comment]
@t-will-gillis Bonnie installed MkDocs last night to the website-wiki repo but she said it still needs to be configured. See Bonnie's comments:
- https://github.com/hackforla/website/issues/3635#issuecomment-1457447102
- https://github.com/hackforla/website/issues/3635#issuecomment-1457447525

**Comment by t-will-gillis** [comment]
1. Progress: Researching MkDocs, which Bonnie has already installed.
2. Not blockers, but for clarification: 
- Documentation: is this meant to be a description of what has been done already- how to install MkDocs or something more along lines of  https://github.com/codeforamerica/brigade-project-index/blob/master/docs/docs.md 
- Additional info needed- is this referring to formatting options via the `mkdocs.yml` file, such as navbars, tocs, extensions, features, etc.?  Is there a direction we want to head, for example https://github.com/codeforamerica/brigade-project-index/blob/master/mkdocs.yml 
3. Availability: most days 11-3
4. ETA: targeting by Friday 17 March

**Comment by JessicaLucindaCheng** [comment]
@t-will-gillis I found some problems with the Readme.md, so I am reopening this issue.
See my review here: https://github.com/hackforla/website-wiki/pull/2#pullrequestreview-1347583951

**Comment by t-will-gillis** [comment]
@JessicaLucindaCheng Got it- will take care of these comments a little later today, eta 6 pm
