### ISSUE TITLE
Add a visual demo of Reviewing a Pull Request

### ISSUE THREAD

**Issue by blulady** [hackforla/website#3651]
### Overview
One of our devs created an outstanding visual guide to reviewing a pull request. It would be helpful to link the demo to the Contributing Wiki. Find a good place to add a link and store the files so this can be added to the wiki.

### Action Items
- [ ] Research where to store the file
- [ ] Read the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) to figure out a good word or phrase to attach the hyperlink to.
 

### Resources/Instructions
https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md
[How to Review a PR 2.pdf](https://github.com/hackforla/website/files/9847698/How.to.Review.a.PR.2.pdf)

**Comment by patrickohh** [comment]
Availability: 11/3 - 11/6
ETA: By 11/4

**Comment by ExperimentsInHonesty** [comment]
@patrickohh Why did this get moved to the done column.  If it was a mistake, no problem, what status does it have.  If its been agreed that this issue will not be worked on, then please explain.

**Comment by patrickohh** [comment]
@ExperimentsInHonesty It might have been my mistake. I assumed since the pull request was committed and merged that it was done. Sorry for the confusion and if it was the wrong tag to move this issue to!

**Comment by ExperimentsInHonesty** [comment]
Hi @patrickohh according to your PR #3696 , in the contributing file you made the following changes

### Before: 
For new volunteers, check this [wiki on completing pull request reviews](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests) and our [wiki on creating issues](https://github.com/hackforla/website/wiki/How-to-create-issues) for more ways to contribute to the project.

### After
For new volunteers, check this [wiki on completing pull request reviews](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests), [visual demo on pull request reviews](https://drive.google.com/file/d/1b6uW_Od8ftACsEr5u-nxe8qNb8UjkISN), and our [wiki on creating issues](https://github.com/hackforla/website/wiki/How-to-create-issues) for more ways to contribute to the project.

I was looking for the visual guide referenced in this issue's scope.  I am assuming that is this file
[visual demo on pull request reviews](https://drive.google.com/file/d/1b6uW_Od8ftACsEr5u-nxe8qNb8UjkISN)

Is that correct?

**Comment by patrickohh** [comment]
Yes that is correct! @ExperimentsInHonesty

**Comment by ExperimentsInHonesty** [comment]
I will create an ER for this to either remove or remake the slide deck.  We will need to talk to @AzaniaBG about the original deck.
