### ISSUE TITLE
Redesign  Donate page (mobile view) 

### ISSUE THREAD

**Issue by sijiapitts** [hackforla/website#3661]
### Overview
When developers were working on implementing the Donate page (mobile view) design, they noticed some unclear instructions. Text alignments, box shadows... have different styles than the ones on the current website. But it wasn't clear to them if they should implement the Figma style. More details can be found in [Issue #2392 ](https://github.com/hackforla/website/issues/2392)

As the team examing the design on Sunday all teams meeting on 10/23, we noticed the page lacks visual hierarchy as well. 

So, the page needs to be redesigned. The new page should clearly define the two sections: Donate money and donate services. The team decided to remove the current content and image on the hero section because it adds very little value and creates confusion. 
 

### Action Items

- [x] Fix the styles of typography, image etc. 
- [x] Redesign the donate page (mobile view)
- [ ] Review the completed design with the team lead

### Resources/Instructions
[Figma - Donate Page mobile design (final)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=11166%3A91022)

**Comment by sijiapitts** [comment]
I created [two solutions ](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24457%3A284739). Waiting for review in the next team meeting.

**Comment by sijiapitts** [comment]
Design has been [updated](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24579%3A285100) according to feedback.

**Comment by ExperimentsInHonesty** [comment]
Design approved.

**Comment by ExperimentsInHonesty** [comment]
This is ready to be made into a development issue to change the current donate Mobile and desktop layout.  Dev can extrapolate from the mobile version what the changes the desktop should be.

**Comment by roslynwythe** [comment]
- created issue https://github.com/hackforla/website/issues/3983 for implementation.
