### ISSUE TITLE
Improve homepage styling on home page

### ISSUE THREAD

**Issue by cnk** [hackforla/website#367]
I found a few more things to tweak but I think we should merge this as a good start.

<img width="352" alt="Text-hidden-under-logo-iphone5" src="https://user-images.githubusercontent.com/5952/76694532-2cd7eb00-6631-11ea-8fd3-9e398faf1180.png">
<img width="734" alt="Text-hidden-under-logo-iphone6" src="https://user-images.githubusercontent.com/5952/76694529-28133700-6631-11ea-8f1d-c1d15a4c22fc.png">
<img width="379" alt="GitHub-icon-missing-iphone5" src="https://user-images.githubusercontent.com/5952/76694530-2ba6be00-6631-11ea-89fc-9eb02e1859c2.png">
<img width="379" alt="Twitter-icon-missing-on-iphone5" src="https://user-images.githubusercontent.com/5952/76694531-2c3f5480-6631-11ea-9e2d-43ae254d8154.png">

_Originally posted by @cnk in https://github.com/hackforla/website/pull/363#issuecomment-599162510_

**Comment by leonelRos** [comment]
Hey, @cnk @ExperimentsInHonesty  I apologize for the delay on this issue. I modified the few overlapping issues we had with the mobile view.  let me know if this is correct. I can work on it again. One thing I noticed is that by removing "sign up for updates and the email field". It kind of made everything easier. we might need to check back again if we were to put that back again.

<img width="306" alt="Screen Shot 2020-03-20 at 10 26 31 PM" src="https://user-images.githubusercontent.com/50648001/77220096-f5b67d80-6af9-11ea-90bf-9afbbda17cc0.png">
<img width="454" alt="Screen Shot 2020-03-20 at 10 26 56 PM" src="https://user-images.githubusercontent.com/50648001/77220098-f818d780-6af9-11ea-846c-342f5b1ad5a0.png">
<img width="674" alt="Screen Shot 2020-03-20 at 10 27 56 PM" src="https://user-images.githubusercontent.com/50648001/77220104-11218880-6afa-11ea-87ce-f208b328e84f.png">
