### ISSUE TITLE
Toolkit page: Hide suggest buttons

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3678]
### Overview
On the Toolkit page, we want to temporarily hide the currently non-functional `Suggest a guide` and `Suggest a resource` buttons so that visitors cannot select or click buttons on our website that do not function yet.

### Details
We are hiding the buttons until we figure out how the buttons will function when they are clicked, such as where the buttons lead to.
<details>
  <summary>Click here to see screenshots of the Suggest a resource and Suggest a guide buttons on the Toolkit page</summary>
  <img width="947" alt="" src="https://user-images.githubusercontent.com/31293603/200724753-c5d6fae6-997e-4911-a22a-d376716b4e50.png">
  <img width="947" alt="" src="https://user-images.githubusercontent.com/31293603/200724756-52a5f20e-ee24-4236-9497-f74dd7c936ba.png">

</details>

### Action Items
In `pages/toolkit.html`, using the `hidden` attribute
- [x] Hide the `Suggest a guide` button and add a comment about it by changing
  ```
          <button class="btn btn-primary btn-md-narrow">Suggest a guide</button>
  ```
  to
  ```
          <!-- The Suggest a guide button has been temporarily hidden until we figure out how this button will function after it's clicked. See issue #3678 for more details. -->
          <button hidden class="btn btn-primary btn-md-narrow">Suggest a guide</button>
  ```
- [x] Hide the `Suggest a resource` button and add a comment about it by changing
  ```
                  <button class="btn btn-primary btn-md-narrow">Suggest a resource</button>
  ```
  to
  ```
                  <!-- The Suggest a resource button has been temporarily hidden until we figure out how this button will function after it's clicked. See issue #3678 for more details. -->
                  <button hidden class="btn btn-primary btn-md-narrow">Suggest a resource</button>
  ```
- [x] Using developer tools, make sure both the buttons are not visible when you visit the Toolkit page in mobile, tablet, and desktop views
- [x] Using a screen reader, such as the Screen Reader Chrome Extension, make sure both the buttons are not read by the screen reader either

### Resources/Instructions
- Toolkit page: https://www.hackforla.org/toolkit/
- Source code on GitHub: https://github.com/hackforla/website/blob/gh-pages/pages/toolkit.html
- Screen Reader Chrome Extension: https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn?hl=en-US
- HTML hidden Attribute Info: https://www.w3schools.com/tags/att_hidden.asp
- The problem with the buttons being non-functional was brought up in this comment: https://github.com/hackforla/website/issues/2802#issuecomment-1110506971
- Related issue: #3115

**Comment by JessicaLucindaCheng** [comment]
For finishing writing this issue:
- Blocker: Internet problem with my computer.
- Availability: Not sure; dependent on resolving my Internet problem
- ETA: November 7, 2022 (dependent on resolving my Internet problem)

**Comment by JessicaLucindaCheng** [comment]
For finishing writing this issue:
Blocker: None. I fixed my Internet.
Availability: 6 hours
ETA: November 13, 2022

Edit: Finished drafting issue

**Comment by Skydodle** [comment]
Availability: Wednesday, Saturday, Sunday

ETA : Sunday 11/20 by the end of day

**Comment by ExperimentsInHonesty** [comment]
Is this documented in the wiki?

**Comment by ExperimentsInHonesty** [comment]
Document what happened in our wiki page for the Toolkit and then when the design gets relaunched we can decide how and where we are brining the buttons back.

**Comment by JessicaLucindaCheng** [comment]
> Document what happened in our wiki page for the Toolkit and then when the design gets relaunched we can decide how and where we are brining the buttons back.

- Issue #3848 will address documenting the Toolkit page's hidden buttons.
