### ISSUE TITLE
Create "Getting Started" page for remote projects

### ISSUE THREAD

**Issue by cnk** [hackforla/website#368]
### Overview
Create a Getting Started page. References #404.

### Action Items
- [ ] Review final wireframe for Getting Started page refresh
- [ ] Update Getting Started page based on finalized wireframe

### Resources/Instructions
Draft for v2.0: https://docs.google.com/document/d/14ACgDU4CgYhsJXI5H49CdbLzItV8IinbzDCayCgPKjY/edit
References #404

**Comment by cnk** [comment]
- [x] Getting started video - introduction to Hack for LA
- [x] How to choose a project
- [x] Link to [Getting Started wiki ](https://github.com/hackforla/getting-started) ??
- [x] Link to [Code of Conduct](https://github.com/hackforla/codeofconduct) ??

**Comment by ashlingam** [comment]
Draft of page content: https://docs.google.com/document/d/1_cTOgTghyPa4JA0Azz573JLE7nA6_g3jCYTbkVoZfms/edit

**Comment by ashlingam** [comment]
@KianBadie @ExperimentsInHonesty The screenshots for the Online Onboarding section are overstretched vertically and need to be scaled down.

**Comment by KianBadie** [comment]
@harishlingam is this something that is currently reflected on the page? If so can you please provide screenshots? And is this happening on mobile or desktop view?

**Comment by ExperimentsInHonesty** [comment]
All issues addressed.

**Comment by ashlingam** [comment]
@harishlingam Revise content of page to reflect edits discussed during team meeting

**Comment by ashlingam** [comment]
Updated draft: https://docs.google.com/document/d/1_cTOgTghyPa4JA0Azz573JLE7nA6_g3jCYTbkVoZfms/edit

**Comment by ashlingam** [comment]
1. Progress - A refresh of the current Getting Started page is underway. @yuikomajima has created a wireframe that will make the page more graphical and easier to read: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=13%3A3. We are editing the wireframe and a final version will be shared with the group.
2. Blocks - None
3. Availability - Sunday, Saturday, Monday
4. ETA - 04-08-20

References #404

**Comment by ExperimentsInHonesty** [comment]
This is what the page used to look like.
![Screen Shot 2020-04-12 at 12 24 00 PM](https://user-images.githubusercontent.com/37763229/79077796-c5a56900-7cb8-11ea-9867-f5c82902e17c.png)
