### ISSUE TITLE
Communities of Practice information updates: Data Science

### ISSUE THREAD

**Issue by KarinaLopez19** [hackforla/website#3693]
### Overview
We want to update the information in the Data Science CoP card so that the information is accurate.

### Action Item
- [x] In _data/internal/communities/data-science.yml, update the file to reflect the information written below:
  - [x] **Remove person(s)**
    - [x] Ryan Swan
  - [x] **Add person(s)**
    - [x] Name: Karina López
      Title: Co-lead
      GitHub Handle: KarinaLopez19
      Slack Member ID: Karina Lopez
- [x] Once the pull request associated with this issue has been merged, please send this back to the Product Managers by
  - [x] Adding a `ready for product` label and placing this issue in the New Issue Approval column
  - [ ] The bio information below is for Bonnie and Product Manager(s). The bio information below is not part of this issue, so the developer does not need to implement it as part of this issue.
    
      I would also like to add my bio to the website per Bonnie's request. I'm not sure which page exactly but I provided the blurb below. Thanks!
      > Karina (she/they) combines her passions in activism, research, and art into her data pursuits.
      > 
      > She holds a BA from Dartmouth College in neuroscience with a focus on computational social behaviors. In other words, she loves understanding how and why people behave the way they do translated from patterns in data.
      > 
      > Keeping inclusivity and activism at the forefront, she enjoys supporting folks navigating their entry into a data science profession as well as building spaces for WOC in tech. When she's not on her laptop, you can find her adopting new creative hobbies or rollerskating on smooth pavement.

### Resources/Instructions
- Communities of Practice webpage: https://www.hackforla.org/communities-of-practice
- Link to Data Science card source code: https://github.com/hackforla/website/blob/gh-pages/_data/internal/communities/data-science.yml
- If needed for future reference, here is the content of the original request submitted by KarinaLopez19: https://github.com/hackforla/website/issues/3693#issuecomment-1314405145

**Comment by ExperimentsInHonesty** [comment]
I approve these changes.  I will add the bio on a different page.  Just send this back to product when finished.

**Comment by jdingeman** [comment]
Hey PMs, I edited the issue and linked the resources for the dev. Is there a page that the bio will show up in as per Bonnie's comment?

**Comment by JessicaLucindaCheng** [comment]
If needed for future reference, here is the content of the original request submitted by KarinaLopez19:

### Remove person(s) and info from CoP file?

YES

### If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:

Ryan Swan

### Add person(s) and info to CoP file?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Karina López
Title: Co-lead
GitHub Handle: KarinaLopez19
Slack Member ID: Karina Lopez

I would also like to add my bio to the website per Bonnie's request. I'm not sure which page exactly but I provided the blurb below. Thanks!

> Karina (she/they) combines her passions in activism, research, and art into her data pursuits.
> 
> She holds a BA from Dartmouth College in neuroscience with a focus on computational social behaviors. In other words, she loves understanding how and why people behave the way they do translated from patterns in data.
> 
> Keeping inclusivity and activism at the forefront, she enjoys supporting folks navigating their entry into a data science profession as well as building spaces for WOC in tech. When she's not on her laptop, you can find her adopting new creative hobbies or rollerskating on smooth pavement.

**Comment by JessicaLucindaCheng** [comment]
@jdingeman I went ahead and edited this issue more because PMs wanted it to be more clear. See this issue as an example: 
- #3691

Also, I think Bonnie wanted this passed back to PMs after it was implemented, so I went ahead and added the `ready for milestone` label and removed `ready for product` label for now. Sorry for my confusion.

**Comment by Satenik-Ba** [comment]
Availability: 11/28/2022
ETA: 1hr

**Comment by jdingeman** [comment]
@hackforla/product-managment, per item in issue, I am tagging this as ready for product and returning to new issue approval.

**Comment by Rabia2219** [comment]
> @hackforla/product-managment, per item in issue, I am tagging this as ready for product and returning to new issue approval.

@jdingeman Hi there! Tagging 'hackforla/product-managment' sends this message to all the PMs across HackforLA. You need to tag the PM for your project only :)

**Comment by ExperimentsInHonesty** [comment]
Product on the website team will need to draft an issue on this

**Comment by ExperimentsInHonesty** [comment]
- The bio has been added to https://github.com/hackforla/website/issues/4104
