### ISSUE TITLE
Update Project Profile: VRMS

### ISSUE THREAD

**Issue by juliagab56** [hackforla/website#3694]
### Overview
As a developer, we need to ensure our project's details are up to date on the HackforLA website. We need to update the VRMS project's leadership to include the current team members and remove some of the old team members.

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the [vrms.md](https://github.com/hackforla/website/blob/gh-pages/_projects/vrms.md) file and find the `leadership` variable.
- [x] Remove the following people from the `leadership` variable
    - [x] Alex Anakin
    - [x] Adam Spar
    - [x] Katiuska Alicea de Leon
    - [x] Glen Paul Florendo
    - [x] David Rubinstein
    - [x] Walter Tang
- [x] Add the following people to the `leadership` variable
    - [x] Name: Julia Gab
Github: juliagab56
Role: Lead UX Designer
Slack ID: U03AS9FBAAU
    - [x] Name: Judy Lee
Github: JudyLee533
Role: UX Designer
Slack ID: U03K7Q1FV3P
    - [x] Name: Alex Lee
Github: heyitsalexander
Role: Product Manager
Slack ID: U03PC4KKGAG
    - [x] Name: Amanda Glover
Github: AmandaGlover-PM
Role: Product Manager
Slack ID: U042G8B7RB3
    - [x] Name: Trillium Smith
Github: Spiteless
Role: Developer
Slack ID: U010G9864Q1

- [x] Update the value of Josh Bubar's `role` variable from "Shows up to meetings" to "Developer"
- [x] Check the [VRMS project page](https://www.hackforla.org/projects/vrms) on your local development environment to ensure the "Current Project Team" section is properly displaying the changes you made

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [The VRMS markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/vrms.md)
- [HFLA wiki on project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [How to find a Slack ID](https://github.com/hackforla/admin/wiki/Slack:-Find-a-Slack-ID)

**Comment by juliagab56** [comment]
I'd like to update the "current project team" section of VRMS to reflect current team members. 

1. Name: Julia Gab
   Github: juliagab56
   Role: Lead UX Designer
   Slack ID: U03AS9FBAAU

2. Judy Lee
JudyLee533
UX Designer
Slack ID: U03K7Q1FV3P
  
3. Alex Lee
heyitsalexander
Product Manager
Slack ID: U03PC4KKGAG

4. Amanda Glover
AmandaGlover-PM
Product Manager
Slack ID: U042G8B7RB3

5. Josh Bubar
jbubar
Developer
Slack ID: UMNNMHXV2

6. Trillium Smith
Spiteless
Developer
Slack ID: U010G9864Q1

**Comment by ExperimentsInHonesty** [comment]
I approve the proposed changes, but the issue needs to be formatted for the developers

**Comment by MattPereira** [comment]
It is unclear if Julia's [comment](https://github.com/hackforla/website/issues/3694#issuecomment-1302545397) suggests only adding additional team members or if all previously existing team members that are not mentioned should be removed

**Comment by juliagab56** [comment]
Hi! @MattPereira Apologies for the confusion. I didn't know how to format this issue properly. Bonnie pointed it out to me a few days ago but I've been busy with work and didn't get around to it yet. This issue might change because we may add more people to our team next year so it's not high priority I guess. 
But basically, the volunteers I mentioned in the comments are meant to substitute the ones currently on the site. And Josh would be updated in this case since he's still on the team. I will love to confirm with them next time we're able to get all together. It's just been busy for everyone.

**Comment by MattPereira** [comment]
Hey @juliagab56, no worries and thanks for the speedy clarification! :+1:

**Comment by ExperimentsInHonesty** [comment]
Remove the following people
Alex Anakin
Adam
Katiuska
Glen
David
Walter

Add the people she specified in the comment https://github.com/hackforla/website/issues/3694#issuecomment-1302545397

**Comment by ExperimentsInHonesty** [comment]
@juliagab56 The website team will make these changes, but they still need some information from you.

### Next steps to make your request actionable:
1. Have members without the Slack ID to add themselves to your roster, including finding their slack ID.  
- Alex Lee
- Amanda Glover
- Josh Bubar

If they don't have access to the roster, then that means they were never added to the drive.  Please add them to the drive.
[VRMS Roster](https://docs.google.com/spreadsheets/d/1sMIPMDy7j6zDQ2-jF0xX2x-W-tEY8IcUiikmii7tVa0/edit#gid=0)

Here is our [Slack: Find a Slack ID helpfile](https://github.com/hackforla/admin/wiki/Slack:-Find-a-Slack-ID) for how to find your (or someone else's slack ID)

2. Update the comment above with their slack IDs: https://github.com/hackforla/website/issues/3694#issuecomment-1302545397

3. Add the `ready for milestone` label so I can re-review

**Comment by ExperimentsInHonesty** [comment]
I gave them a nudge, by adding it to their meeting agenda for their monday meeting

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge I hid all the comments where we were trying to figure out what specifically they were asking for.  Now all the visible comments are relevant, this issue can be reformatted for the devs.

**Comment by RyanGehris** [comment]
Availability: Tues-Thurs 1pm-5pm
ETA: 02/14/2023 by 9pm

**Comment by RyanGehris** [comment]
I accidentally removed my assignment. There are no updates to my Availability or ETA

Availability: Tues-Thurs 1pm-5pm
ETA: 02/14/2023 by 9pm

**Comment by RyanGehris** [comment]
@juliagab56 I have made all of the requested changes for the leadership variable, but the Slack link for several members is not working correctly. I want to confirm that the SlackID's are correct before making a pull request.

Could you confirm the SlackID for Judy Lee, Alex Lee, Amanda Glover, and Josh Bubar please. After appending their SlackID to "https://hackforla.slack.com/team/", the link brings the user to a slack profile with no information. I have attached a photo of the result when clicking on your link, vs Judy Lee's link.

<details>
<summary>Working Link: Julia Gab</summary>

<img width="553" alt="Screenshot 2023-02-13 at 9 42 56 PM" src="https://user-images.githubusercontent.com/105510284/218650290-603f692c-3e17-4375-b23f-bbc6c0a02055.png">

</details> 

<details>
<summary>Broken Link: Judy Lee</summary>

<img width="556" alt="Screenshot 2023-02-13 at 9 42 39 PM" src="https://user-images.githubusercontent.com/105510284/218650329-2ae50531-56de-4033-ad26-3403d8ab8788.png">

</details>

**Comment by RyanGehris** [comment]
@juliagab56 Please dismiss my above comments. Today I confirmed that the SlackIDs were correct and the reason why some profiles weren't populating was because those users weren't in the specific slack channel that I had selected at  the time. Thank you for providing all of the Leadership information. 

I will submit a pull request now!

**Comment by ExperimentsInHonesty** [comment]
@juliagab56 Please confirm that the changes you requested got made.  If we didn't make the changes, indicate what is not what you expected.  If there are new information changes (not previously requested) you can open a [new project update issue](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D).

**Comment by ExperimentsInHonesty** [comment]
I am moving this to done because VRMS has not responded.  No further action is required.
