### ISSUE TITLE
Update Project Profile: Lucky Parking

### ISSUE THREAD

**Issue by ychu196** [hackforla/website#3697]
### Overview
As a product manager of Lucky Parking I want my project's details to be up to date on the HackforLA website

### Action Items
 In the [_projects/lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md) file, update the `leadership` variable as follows (the order is important):
 - [ ] name: Yuting Chu
    - [ ] role: Product Manager Lead
    - [ ] slack: ‘https://hackforla.slack.com/team/U03J4E55KCH’
    - [ ] github: ‘https://github.com/ychu196’
    - [ ] picture: https://avatars.githubusercontent.com/ychu196
- [x] name: Greg Pawin
    - [ ] role: Data Scientist Lead (currently it says Product Owner / Data Science, and he is dropping the Product Owner)
    - [X] slack: ‘https://hackforla.slack.com/team/UUEQF3AJG’
    - [X] github: ‘https://github.com/gregpawin’
    - [X] picture: https://avatars.githubusercontent.com/gregpawin
 - [ ] name: Glen Paul Florendo
    - [ ] role: Full-Stack Developer Lead
    - [ ] slack: https://hackforla.slack.com/team/UFQGH8JH0
    - [ ] github: https://github.com/glenflorendo
    - [ ] picture: https://avatars.githubusercontent.com/u/9373317
  - [ ] name: Michael Morgan
    - [ ] role: UX/UI Design Lead
    - [ ] slack: ‘https://hackforla.slack.com/team/U01SPJCC26A’
    - [ ] github: ‘https://github.com/mklmrgn’
    - [ ] picture: https://avatars.githubusercontent.com/mklmrgn
  - [ ] name: Yen Phan
    - [ ] role: User Research
    - [ ] slack: ‘https://hackforla.slack.com/team/U025M9VRDJR’
    - [ ] github: ‘https://github.com/ymphan’
    - [ ] picture: https://avatars.githubusercontent.com/ymphan
  - [ ] name: Yujin Chang
    - [ ] role: UI Designer
    - [ ] slack: ‘https://hackforla.slack.com/team/U0270QURQCD’
    - [ ] github: ‘https://github.com/eugenecha’
    - [ ] picture: https://avatars.githubusercontent.com/eugenecha
- [ ] name: Jodie Chen
    - [ ] role: UI/UX Designer
    - [ ] slack: ‘https://hackforla.slack.com/team/U03RFGLLAQG’
    - [ ] github: ‘https://github.com/jojochen25’
    - [ ] picture: https://avatars.githubusercontent.com/u/103106753
- [ ] name: Sijia Pitts
    - [ ] role: UI/UX Designer
    - [ ] slack: ‘https://hackforla.slack.com/team/U03CBK89KUY’
    - [ ] github: ‘https://github.com/sijiapitts’
    - [ ] picture: https://avatars.githubusercontent.com/u/103976231
- [ ] name: Pratibha Shivanand
    - [ ] role: Data Scientist
    - [ ] slack: ‘https://hackforla.slack.com/team/U03SM1LF9HD’
    - [ ] github: https://github.com/pratibhanagesh
    - [ ] picture: https://avatars.githubusercontent.com/u/8139348
- [ ] name: Aletia Trepte
    - [ ] role: Data Scientist/Engineer
    - [ ] slack: ‘https://hackforla.slack.com/team/U03KAPRML9Y’
    - [ ] github: https://github.com/parcheesime
    - [ ] picture: https://avatars.githubusercontent.com/u/38143160
- [ ] name: Yao Guan
    - [ ] role: Quant UXR
    - [ ] slack: ‘https://hackforla.slack.com/team/U03F35T4PND’
    - [ ] github: https://github.com/yaoguan
    - [ ] picture: https://avatars.githubusercontent.com/u/41702875
- [ ] name: Diedrich Chavarria
    - [ ] role: Full Stack Developer
    - [ ] slack: ‘https://hackforla.slack.com/team/U031VEUS0CW’
    - [ ] github: ‘https://github.com/DCH-CH’
    - [ ] picture: https://avatars.githubusercontent.com/DCH-CH
 - [ ] name: Arpita Pandya
    - [ ] role: Full Stack Developer
    - [ ] slack: ‘https://hackforla.slack.com/team/U02LQ20MEDU'
    - [ ] github: ‘https://github.com/arpitapandya’
    - [ ] picture: https://avatars.githubusercontent.com/arpitapandya
- [ ] name: Seymour Liao
    - [ ] role: Data Scientist
    - [ ] slack: ‘https://hackforla.slack.com/team/U018XPTSTC6’
    - [ ] github: ‘https://github.com/Seymour100’
    - [ ] picture: https://avatars.githubusercontent.com/Seymour100
- [ ] name: David Lam
    - [ ] role: Data Scientist
    - [ ] slack: ‘https://hackforla.slack.com/team/U02D8CDURF0’
    - [ ] github: ‘https://github.com/davidlamcanada’
    - [ ] picture: https://avatars.githubusercontent.com/davidlamcanada
- [ ] name: Carlos Olivas
    - [ ] role: Data Scientist
    - [ ] slack:
    - [ ] github: 
    - [ ] picture: https://avatars.githubusercontent.com/u/41702877
 - [ ] name: Sam Sengupta
    - [ ] role: UX/UI
    - [ ] slack:
    - [ ] github: 
    - [ ] picture: https://avatars.githubusercontent.com/u/41702879

### Instructions
- If an item is already checked off, double check the information matches the info in [_projects/lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md)
- Unchecked items are new info which needs to be updated or added.
- Make sure to use valid YAML syntax. You must match the existing structure of [_projects/lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md)
- Verify the changes by checking the "Current Project Team" section of the [Lucky Parking project page](https://www.hackforla.org/projects/vrms) on your local development environment

### Resources
- [Lucky Parking markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [Slack: Find a slack ID](https://github.com/hackforla/admin/wiki/Slack:-Find-a-Slack-ID)

**Comment by ExperimentsInHonesty** [comment]
@ychu196 Please finish filling out the checklist below


   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in a new 
      - [ ] links
         - [ ] GitHub
         - [ ] Slack
         - [ ] Test Site
         - [ ] Demo Site
         - [ ] Site
      - [ ] technologies
      - [ ] partner
      - [ ] tools
      - [ ] status
 - [ ] If you need updates to your meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue in a new comment below

### Resources
[VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

**Comment by ychu196** [comment]
@ExperimentsInHonesty Done as per your request
- [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in a new
  - [x] links
    - [x] GitHub
    - [x] Slack
    - [x] Test Site
    - [x] Demo Site
    - [x] Site
  - [x] technologies
  - [x] partner
  - [x] tools
  - [x] status

**Comment by Jaretzbalba** [comment]
Review availability: Weekdays 10-12pm
ETA: 12/13 5pm

**Comment by arpitapandya** [comment]
This issue doesn't seem to be ready, It has missing information. @ExperimentsInHonesty Can we move this back and add a draft label? else @ychu196 can you provide links for Carlos and Sam?

**Comment by ychu196** [comment]
@arpitapandya Carlos and Sam have no links. Leave it as blank. Thanks!

**Comment by arpitapandya** [comment]
@Jaretzbalba Please, move the issue to the `In progress` column, when you start working on the issue from `prioritized backlog`. I am moving it now.

**Comment by arpitapandya** [comment]
> @arpitapandya Carlos and Sam have no links. Leave it as blank. Thanks!

Updated my information

**Comment by arpitapandya** [comment]
I reviewed PR worked by @Jaretzbalba, so my thoughts since we don't have other links for 2 members(picture). Either we can make it even by adding if one person is missing or we can request the 2 members for links to be added. I am not sure if Bonnie is on this team. I am sorry @ychu196 do you have any thoughts?
![ofcourseadded](https://user-images.githubusercontent.com/66761308/207451772-071aa040-f1f2-4be4-8b4d-e9a4c83d3a9c.PNG)

![tomakeitevenifnopicture](https://user-images.githubusercontent.com/66761308/207450103-ad4e109f-5933-4daa-b657-fc6ff6f1b671.PNG)

**Comment by ychu196** [comment]
@arpitapandya 
1) No apologies necessary - your questions are valid and spot on :)

2) Use a placeholder image

3) No Bonnie is not part of this team, she's the Exec Director of Hack for LA.

**Comment by arpitapandya** [comment]
@Jaretzbalba In case you need help, I have updated the issue with the placeholder links for both missing. I will merge it tomorrow.
