### ISSUE TITLE
Fix Events page bug with VRMS data not displaying

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#3701]
### Overview
We need to get the VRMS team meeting data back onto our Events page so that people can see when we have meetings.

### Details
I made an update with the VRMS team in their database for the DevOps community of practice team and its meeting schedule, and now the events page on the hackforla.org website is not loading the data.  We need to figure out why and then work with them on a fix (either something I put in the data needs to be removed), or we need to change something in the processing of the data.

- I made the change on 2022-11-08 and 1 min later the data stopped showing on the events page.
- I immediately checked a project page, and the event times are still showing there.

I have checked, and meeting data is still showing up on individual event pages.  See 311 data's project page (link in the resources)

I cannot remember exactly what I changed but we should be able to look at an older copy of the data and compare

### Action Items
- [ ] Investigate [_includes/events-page](https://github.com/hackforla/website/tree/gh-pages/_includes/events-page) and [pages/events.html](https://github.com/hackforla/website/blob/gh-pages/pages/events.html) to find where the data might be disconnected
  - [ ] Going to the events page on the published site and checking the console in developer tools may aid in locating the issue
- [ ] Test in your local repo to find a fix that will display the meeting times
- [ ] Ensure that this does not break any other pages that use data from VRMS files, such as the project pages

#### Pages where VRMS data should be displaying and are not
- Events page: https://www.hackforla.org/events/ 
- Projects meetings page: https://www.hackforla.org/project-meetings page 

#### Pages that are displaying VRMS data
- project page sample: https://www.hackforla.org/projects/311-data (meeting time times)

#### Other
- VRMS application: https://vrms.io/
- Slack Channel for VRMS team [#vrms](https://hackforla.slack.com/archives/CRGH5HM0Q)

### Where we store our event data from VRMS
https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json

Data as of 2022-11-07 (before the change): https://github.com/hackforla/website/blob/0379993a76c776561de8c18554465d0d4becdace/_data/external/vrms_data.json

Data as of 2022-11-09 (after the change): 
https://github.com/hackforla/website/blob/0798902d1bc2b22a51ddd588eb60383e5058fb09/_data/external/vrms_data.json

**Comment by jyaymie** [comment]
Availability: After 5pm throughout the week of 1/16/22
ETA: 1/23/22
