### ISSUE TITLE
CLASP for Google Apps Scripts development evaluation / decision 

### ISSUE THREAD

**Issue by aricforrest** [hackforla/website#3722]
### Overview
Evaluate if Google's CLASP (Command Line Apps Script Projects) should be utilized for Google Apps Script development. 

### Action Items
**Understand what Google Apps Scripts and Google CLASP is:**
- [x] [Google Apps Scripts](https://www.google.com/script/start/) are serverless JavaScript runtime for G Suite.
- [x] [Google CLASP](https://github.com/google/clasp) is a command-line tool that allows you to locally create, pull, edit, and deploy Apps Scripts.

**Review benefits to using CLASP:**
- [x] Allows for collaboration of Apps Scripts using version control (e.g. GitHub)
- [x] Allows creating Apps Scripts locally in preferred IDE
-- Nicer user interface
-- auto completion of Google Apps Script classes and methods
-- syntax highlighting
-- keyboard shortcuts
-- additional plugins such as linters
- [x] TypeScript support in Apps Scripts via [ts2gas](https://www.npmjs.com/package/ts2gas)
- [x] NPM/ES6 module support in Apps Scripts via [Webpack](https://webpack.js.org/)

**Review required changes:**
- [x] Existing Apps Scripts will need to be cloned via CLASP and pushed to GitHub
- [x] Documentation will need to be created introducing the Google Apps Scripts development process using CLASP
- [x] Node.js and NPM required on (Google Apps Scripts) developer workstation
- [x] Google Apps Script API needs to be enabled on the users' Google account

**Review potential downsides:**
- [x] Larger learning curve for Apps Script development

**Review and Document**
- [x] Write up Decision Record
- [x] Review with Team
- [x] Let product know what you are recommending
- [x] Get sign off
- [x] Create issues

### Resources/Instructions
- Google Apps Script - https://www.google.com/script/start/
- Google clasp - https://github.com/google/clasp
- clasp codelab - http://g.co/codelabs/clasp

**Comment by roslynwythe** [comment]
Availability: 2/6 3-5 pm, 2/7 4-11 pm, 2/8 5-11 pm, 2/9 9-noon
ETA: 2/20

**Comment by roslynwythe** [comment]
Progress
- Installed Node.js, npm, clasp, test google account, cloned wins-form-responses, made changes locally and did push/pull.
- About to explore versioning and deployment

**Comment by roslynwythe** [comment]
Progress:

- installed node.js, clasp node module, @types/google-apps-script
- used clasp to clone winsResponseForm from my Google Drive code.gs to my workstation, then edited in VS Code. 
- created .claspignore, then used clasp push to copy updated code to my personal Google Drive.

**Comment by roslynwythe** [comment]
My conclusion is that use of clasp is feasible and does offer benefits, enabling local editing and committing of code.  Code testing still must be done in the Google Apps Script IDE.  

I would like to add a few additional benefits, changes and downsides to those already listed in the Action Items:

### (Additional) benefits of using CLASP:
 
- It would be possible for the dev team to create an npm package to implement a custom “build/deploy” process that integrates clasp along with other tools such as prettifier, transpiler and ESLint.  

### (Additional) Required Changes:
- npm packages: clasp, @types/google-apps-script, clasp-env (optional).  
- if dev chooses to develop in ES6 or TypeScript, additional npm packages such as Babel and ts2gas are required to transpile the code and the dev would have to run the transpiler before every push (or create an npm script to do same).  
.gitignore and .claspignore will require update. 
### (Additional) potential downsides:
- Larger learning curve for Apps Script development
- It is not possible to run/debug code locally, so if code is edited locally, it must be pushed the Google Drive to run/debug.

**Comment by roslynwythe** [comment]
Decision Record: https://github.com/hackforla/website/wiki/DR:-Use-of-CLASP-in-Google-Apps-Script-Development

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I see the DR document you made, but what happened?  Did we decide to implement or not?
It needs to be listed on one the appropriate pages:
https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted
https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Not-Implemented

It looks like this is not the only DR not placed on one of the above pages. There are a total of 4 missing.

**Comment by ExperimentsInHonesty** [comment]
Moved the issue to the adopted.  Resolved all the other DRs missing classifications
