### ISSUE TITLE
Project information updates: Website

### ISSUE THREAD

**Issue by blulady** [hackforla/website#3724]
### Add person(s) and info to CoP file?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Philip Sanchez
Title: Merge Team
GitHub Handle: plang-psm
Slack Member ID: U03UG3VCRK6

Name: Matt Pereira
Title: Merge Team
GitHub Handle: MattPereira
Slack Member ID: U045XKKB5DH

#### Resources:
folder where files are in the repo: https://github.com/hackforla/website/blob/gh-pages/_projects/website.md
where you can see the live page: https://www.hackforla.org/projects/website

**Comment by 7kram** [comment]
Is this for product? Also, I believe there is a [template](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D) for updating project cards.

**Comment by jdingeman** [comment]
This issue was superceded by another that was already closed.
