### ISSUE TITLE
Update Project Profile: Design Systems

### ISSUE THREAD

**Issue by allthatyazz** [hackforla/website#3731]
### Overview
As a developer, we must ensure our project's details are up to date on the HackforLA website. We need to update the [Design Systems](https://www.hackforla.org/projects/design-systems) "Project Overview" links and "Current Project Team".

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of [_projects/design-systems.md](https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md) to find the `links` and `leadership` variables. 
- [x] Add a new link to the project's `links` variable. (The one with no indentation)
    - [x] Name: Releases
URL: https://github.com/hackforla/design-systems/releases
- [x] Remove the following persons from the `leadership` variable
    - [x] Eric J Cunningham
    - [x]  Anthony Navarro-Liu
    - [x] Dongchen Hou
    - [x] Joyce Chang
    - [x] Tammy Trinh
    - [x] Kelene Lee
    - [x] Sandra Berjan (The role has changed see the section below)
    - [x] Wataru Inoue (The role has changed see the section below)
- [x] Add the following persons `name`, `role`, `links`, and `picture` to the `leadership` variable (make sure you put the product manager first, then any leads, and then the non lead roles)
   - [x] Name: Yasaman Roostaeian
GitHub Handle: allthatyazz
Role: Product Manager
Slack Member ID: U033GFQ1UQM
    - [x] Name: Rachel Newcomb
GitHub Handle: rachelita2
Role: Lead UX Researcher
Slack Member ID: U03Q5J8SVM3
  - [x] Name: Sandra Berjan
GitHub Handle: sandraberjan
Role: Lead Content Designer
Slack Member ID: U03753VQBSR
  - [x] Name:  Khanh Cao
GitHub Handle: khanhcao17
Role: Co-Lead UX/UI Designer
Slack Member ID: U04A19TDBED
  - [x] Name: Debbie Nyasetia
GitHub Handle: kangina-tech
Role: Co-Lead UX/UI Designer
Slack Member ID: U03FJ3V58FN
  - [x] Name: Wataru Inoue
GitHub Handle: winoue90
Role:  UX Consultant
Slack Member ID: U02SMT4H4LR 
  - [x] Name: Faezeh Faezipour
GitHub Handle: fuzjan81 
Role: UX Researcher
Slack Member ID: U04AT8KU5CY
  - [x] Name: Eva Kwock
GitHub Handle: EvaKw 
Role: UX Researcher
Slack Member ID: U049PSE3ZMZ
  - [x] Name: Zeynep Aslan
GitHub Handle: zeaslan 
Role: UX Researcher
Slack Member ID: U04HDCMD90A
   - [x] Name: Gala Stojnic 
GitHub Handle: GalaStojnic 
Role: UX Researcher
Slack Member ID: U03307LRD2A
  - [x] Name: Eli Marietta 
GitHub Handle: elimarietta 
Role: UX Researcher
Slack Member ID: U03P6Q87BEZ   
  - [x] Name: Asad Haider
GitHub Handle: TobyShanti
Role: UX/UI Designer
Slack Member ID: U04H6Q4K5AS
   - [x] Name: Liz Zheng
GitHub Handle: liz-zheng 
Role: UX/UI Designer
Slack Member ID: U04GYRW4DAT
   - [x] Name: Michael Morgan
GitHub Handle: mklmrgn 
Role: UX/UI Designer
Slack Member ID: U01SPJCC26A
  - [x] Name: Robert Schacht
GitHub Handle: rsschacht
Role: Content Designer
Slack Member ID: U02R5GG3T09

- [x] Test the [Design Systems project page](https://www.hackforla.org/projects/design-systems) on your local development environment to ensure the changes are being displayed properly

### Instructions
- Be sure to use valid YAML syntax and match the existing structure of [_projects/design-systems.md](https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md)
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/
- For the github link, append the team member's github handle to https://github.com/
- For the picture URL, append the team member's github handle to https://avatars.githubusercontent.com/

### Resources
- [Design Systems project page](https://www.hackforla.org/projects/design-systems)
- [_projects/design-systems.md](https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### Update your meeting times?
Yes

### If YES on update meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue
- https://github.com/hackforla/VRMS/issues/1248

**Comment by ExperimentsInHonesty** [comment]
I have added the ready for dev lead label.  This is our first test of the new form.  It looks like they are making very limited changes.  How do we proceed?

**Comment by MattPereira** [comment]
From the perspective of the developer reformatting the issue, it was mildly cumbersome having to scroll so much and delete all of the items not being updated. However, I also recognize that the repetitive yes/no confirmation helps to reinforce accuracy.

Additionally, I noticed the link to the new VRMS issue was not included by the Product Manager who appears to have just listed the new meeting times instead. Is the implication that I should handle opening the issue on the VRMS repository?

**Comment by allthatyazz** [comment]
Regarding the missing link to the VRMS issue, our team has never used VRMS for meetings. What's the purpose of submitting an issue to VRMS then? Is it now a requirement for all HfLA teams to use VRMS? If the answer to the latter question is No, there is no further action needed there.

**Comment by MattPereira** [comment]
Hi @allthatyazz , I think the VRMS API controls the list of meeting times that are displayed on [your project page](https://www.hackforla.org/projects/design-systems)

**Comment by ExperimentsInHonesty** [comment]
@allthatyazz I know you don't have an experience with VRMS, but VRMS is what controls which meeting times show up on the website.  These were entered into vrms before you came on the project.

So when you go to https://www.hackforla.org/projects/design-systems and you see the meeting times, you are seeing the data that VRMS has

![image](https://user-images.githubusercontent.com/37763229/205744837-46e75215-0a7d-4739-aad2-20715c43d349.png)

So given that the times that are on the website are not correct, please open a ticket at VRMS to update them.  Here is the link for that https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D

**Comment by allthatyazz** [comment]
Thank you @ExperimentsInHonesty for clarifications. It makes a lot of sense. Please [see the link to the VRMS issue](https://github.com/hackforla/VRMS/issues/1248) I just submitted. I also edited the first comment to reflect the link.

**Comment by steven-positive-tran** [comment]
i. Availability: (When are you available to work on the issue/answer questions other programmers might have about your issue?)

Anyday past 6pm contact me at slack or schedule with me if needed earlier.

ii. ETA: (When do you expect this issue to be completed?)

Sunday at the most I'll try to get this done at Friday.

**Comment by ExperimentsInHonesty** [comment]
@allthatyazz Please review to see if we made all the changes you asked for (except for meeting times)

**Comment by allthatyazz** [comment]
@ExperimentsInHonesty Thank you! The page looks great! Just two more action items that I am not sure we can include in the current issue or if we need to submit a new issue?!
- [ ] Add more people to the leadership (Is it too late if we wanna add Joshua and another person who joined in the past week?)
- [ ] Update the project One- Sheet (I have updated our One Sheet as documented in https://github.com/hackforla/design-systems/issues/486 Can we update that as well if you approve the update? )

**Comment by ExperimentsInHonesty** [comment]
@allthatyazz Please open a new issue for the leadership changes.  Also, I can help you get your one sheet into the right location, so it's ready for adding to the website.
