### ISSUE TITLE
GitHub Actions: Automatically Move Issues with Completed Dependencies from Ice Box

### ISSUE THREAD

**Issue by bishrfaisal** [hackforla/website#3732]
### Overview

As a product manager, I want to ensure that our kanban board is organized for all teams to increase productivity. In order to achieve that, we need to create a GitHub action automation that automatically moves issues with completed dependencies from the Ice Box to the New Issue Approval column.

### Action Items
- [ ] Refer to the Resources section to understand the GitHub actions architecture we follow
- [ ] Review the checks section below
- [ ] Create a GHA that does the following and will pass the checks
   - [ ] Finds issues in the "Ice Box" column
   - [ ] For each issue in the "Ice Box" column, determine if the issue has dependencies that are fully enumerated with checkboxes and attached issue numbers.  See Example 1 under "Resources".  Note that Examples 2 and 3 under "Resources" depict issues that would not be addressed in this issue.   For issues with dependencies that are fully enumerated with issues:
     - [ ] Determine if the issue has all its enumerated dependency issues closed.  If so:
     - [ ] Move issue to the New Issue Approval Column 
     - [ ] Add a `ready for dev lead` label
- [ ] Demo the GitHub action with merge team/tech leads

### Checks
- [ ] Create a copy of HackforLA's project board into your own repo - see [tip](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-6-creating-your-own-project-board)
- [ ] Test in your local environment to make sure it works
- [ ] Ensure that the action moves issues only from the "Ice Box" column, and only those issues whose dependencies are all enumerated, and only if all enumerated issues are closed - see example 1 below under "Resources"
- [ ] Ensure that the action does **not** affect issues whose dependencies are:
  - [ ] Not enumerated/text only - see example 2 below under "Resources"
  - [ ] Mix of enumerated and text - see example 3 below under "Resources"
- [ ]  When relevant issues that are dependencies are closed, the GitHub action should automatically move the issue with those dependencies to the New Issue Approval column.

### Resources
<details><summary>Example 1: an issue in which dependencies are all enumerated with issues</summary>

- Example from issue # 3881

![image](https://github.com/hackforla/website/assets/5314153/46531938-a3da-4c91-b4de-f65b6006f3b0)

</details> 
<details><summary>Example 2: an issue in which dependencies are not enumerated or are enumerated with text </summary>

- Example from issue # 609

    <img src="https://user-images.githubusercontent.com/37763229/219986541-c50a9a8e-a568-4a37-ae91-58ecb891e090.png" width=200px>

</details> 
<details><summary>Example: Mix of enumerated and text </summary>

- Example from issue #2108

    <img src="https://user-images.githubusercontent.com/37763229/219986471-9048fa34-e4d5-4754-804e-104ddf3cc54e.png" width=200px>

</details> 

- This is to create a new GHA [Start here!](https://docs.github.com/en/actions)
- [HackforLA's Github Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
- [GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
- [GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)
- [GitHub RESTAPI](https://docs.github.com/en/rest)

**Comment by jdingeman** [comment]
Updated this draft as I am not sure if Bishr is still with the org.

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge There are several different types of issues with dependencies.  This issue should only address Type 1, the others we can do manually.

### Type 1: Issues have dependencies with issues enumerated
- Example from issue #1742 

    <img src="https://user-images.githubusercontent.com/37763229/219986341-1ed24070-2e88-4391-b919-5040ba987ab2.png" width=200px>

### Type 2:  Issues have text that explains what the dependency is 
- Example from issue #609

    <img src="https://user-images.githubusercontent.com/37763229/219986541-c50a9a8e-a568-4a37-ae91-58ecb891e090.png" width=200px>

### Type 3:  Issues have both text and issues enumerated
- Example from issue #2108

    <img src="https://user-images.githubusercontent.com/37763229/219986471-9048fa34-e4d5-4754-804e-104ddf3cc54e.png" width=200px>

**Comment by jdingeman** [comment]
Adding this as ready for prioritization

**Comment by RyanGehris** [comment]
Availability: Mon-Thurs 6-10pm PST
ETA: 04/11/2023 11:59pm

**Comment by RyanGehris** [comment]
I was not able to complete the large issue within a two week time frame. I needed to complete a take home assignment, and now have to prepare for an interview and will be out of town immediately following that. I unassigned myself and moved the issue back to New Issue Approval column where it can be reprioritized. I also notified a Justin of my coming absence.

**Comment by Jaretzbalba** [comment]
Availability: Tues-Fri 10-12pm
ETA: EOD 04/25/23

**Comment by Jaretzbalba** [comment]
This issue seemed to be out of my current scope of knowledge and I wasn't able to dedicate enough time to learn about working with GH actions due to some personal reasons and interview preparations. I'll look for a smaller issue to help ease myself into working on these types of issues. I've unassigned myself and moved the issue back to the New Issue Approval column.

**Comment by JpadillaCoding** [comment]
i. Availability: Saturday and Sunday: 8 AM - 4 PM, Tuesday-Thursday: 5 PM - 5 AM
ii. ETA: Hopefully by Thursday since I have no experience with Github actions

**Comment by JpadillaCoding** [comment]
Provide Update
1. Progress: 
Action checks for action list under the dependency section. It verifies if all items are checked off. If an item dos not have a issue linked to it, it'll eject the job. 
Action adds the "ready for dev lead label"
3. Blockers: Difficult to test moving the issue from the icebox column to the new issue approval column, since github tokens are involved and a local repo does not have the same environment as the website repo
4. Availability: 
thurs: 5pm- 5am
friday-sat: 8pm-9pm
6. ETA: Friday by 9pm

**Comment by JpadillaCoding** [comment]
I have a blocker that I do not think I can overcome since it is not possible to recreate in my local environment. 
Github projects have migrated and we are currently using projects (classic). The automation package used for moving issues based on actions (github-project-automation-plus) is not supported on the new Github Projects. The Issue is I cannot recreate a projects (classic) since it is no longer an option, but Github has allowed existing projects (classic) to remain. 
I can confirm that my workflow does in fact target enumerated issues under the Dependency section and will not proceed if there are any non-enumerate tasks.
I would like for a tech lead or merge team member to see my demonstration and give me guidance on testing the workflow considering the above.

**Comment by LRenDO** [comment]
Hi @JpadillaCoding! Adding this slack message here for easy reference for other folks as well. I had to navigate the same classic projects issue for my last issue. If you take a look at the pull request #4908 under the “Testing Resources” section, you’ll find some info that will help you copy classics project into your test repo.

**Comment by JpadillaCoding** [comment]
@LRenDO Thanks to your help, I was able to test using the classic project! Much appreciated for sharing your testing steps.

**Comment by roslynwythe** [comment]
- The merged changes were reverted in #5053 due to a bug which caused issues in columns other than the Ice Box to be moved.

**Comment by roslynwythe** [comment]
@Jaretzbalba I am editing the issue in preparation for reopening it.   I'm not making any real changes to the issue, just clarifying the description of the dependency section, since it was a bit unclear.  Are you interested in continuing work on the issue?  Please let me know.
