### ISSUE TITLE
Issue Demo 

### ISSUE THREAD

**Issue by blulady** [hackforla/website#3734]
### Dependency
- #2027 

### Overview
We are fixing a thing because it being broken interferes with these other things.

### Action Items
- [ ] thing 1
- [ ] thing 2
- [ ] thing 3

### Resources/Instructions
REPLACE THIS TEXT - Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc.

**Comment by ExperimentsInHonesty** [comment]
@blulady I noticed you closed this.  Can we put an ignore label on this? I remember creating this in a meeting, but am not sure why.

**Comment by ExperimentsInHonesty** [comment]
We used this when I was demoing how to write an issue and can be ignored
