### ISSUE TITLE
Improve Documentation for wins form in wiki

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#3735]
### Overview
We need to document how we do the wins page `on form submit`  trigger so that we can do the same on other forms

### Details
I was looking for how we did formatting of the spreadsheet from a normal form response to a review layout for the wins page spreadsheet in the wiki, but it only references it as "on form submit" trigger 

### Action Items
- [ ] Identify how this is done
- [ ] Document for wiki
- [ ] let Bonnie know

### Resources/Instructions
https://github.com/hackforla/website/wiki/Wins-page 

![image](https://user-images.githubusercontent.com/37763229/203094377-1d4e5561-169d-45c9-8fed-95615050e87a.png)

![image](https://user-images.githubusercontent.com/37763229/203094541-1b99a377-ddd6-48c2-8e14-a5ba7c7fd3c8.png)

**Comment by blulady** [comment]
Hey if I am understanding the issue correctly, the [google apps script](https://script.google.com/home/projects/18uQ6VT7PGZ5skTLD-KDACf3DpMCMPi0WCcl2hBKhTFhi8F0tJKuq0Z9A/edit) attached to the [Wins-form(Responces)](https://docs.google.com/spreadsheets/d/1fXmYrmNtrgdzkM_odGIRbSwdaea3yS0cTLCJUzZ6Sc0/edit#gid=1706218917) is in charge of updating the Wins-form(Resoponces) with the human readable format. JS is not my jam but it looks like it starts on line 126 in the google apps script. Before moving further, I want to make sure that I understand the issue correctly.

### Resources
[Wins Form Admin Guide](https://docs.google.com/document/d/1j1JTX5XzotgVCVZ91ImvenedPN5-IVjdSKDukq1B9iE/edit#)
[Google Apps Script attached to Wins-Form(Responses)](https://script.google.com/home/projects/18uQ6VT7PGZ5skTLD-KDACf3DpMCMPi0WCcl2hBKhTFhi8F0tJKuq0Z9A/edit)
[Wins Form Responses](https://docs.google.com/spreadsheets/d/1fXmYrmNtrgdzkM_odGIRbSwdaea3yS0cTLCJUzZ6Sc0/edit#gid=1706218917)

**Comment by blulady** [comment]
@ExperimentsInHonesty This is a really great idea, I would suggest that we make an issue template for issues that change the function of the website by adding a section called `###Update The Wiki `where we ask developers who have made changes to the way the website functions to update the changes in the wiki (and if that functionality doesn't have a wiki to create one).

**Comment by blulady** [comment]
Hey the `ready for dev lead` was left on this issue but I haven't received confirmation that I am on the right track for this issue.
I am putting `ready for product`/`milestone` on this to get a response.

**Comment by ExperimentsInHonesty** [comment]
@blulady you are on the right track.  If we could document this more fully in the wiki that would be good. And the idea of adding update the wiki to all relevant issues is great.

**Comment by blulady** [comment]
I think we can close this issue with #4033
