### ISSUE TITLE
ER: Wins token needs monthly update

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#3748]
### Emergent Requirement - Problem
On The API token for the elizabethhonest needs to be updated every month and it doesn't look like it's happening automatically or being managed manually all that well.  At the time of discovery it had not been updated for 4 months

### Issue you discovered this emergent requirement in
- #3417

### Date discovered 
2022-10-21

### Did you have to do something temporarily
- [x] YES
  - 2022-10-285 elizabethhonest bot GitHub API token updated and set to expire in 30 days.
- [ ] NO

### Who was involved
@aricforrest 

### What happens if this is not addressed
I think the new wins stop posting, but I am not sure

### Resources
https://github.com/hackforla/website/wiki/Wins-page

### Recommended Action Items
- [x] Make a new issue
- [x] Discuss with team
- [x] Let a Team Lead know

### Potential solutions [draft]
- Slack reminder in channel
- Automated creation of new issue on X day of month
- Add to agendas
- Reopen an issue each month

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge please update this issue or close it if you already made another.  It needs to to reflect the decision made during last mondays dev/pm meeting 2023-01-09 where we decided we would change the token to never expires, and then just refresh it every time someone finishes work on the api.

**Comment by jdingeman** [comment]
- Issue has been made here: https://github.com/hackforla/website/issues/3957
Closing this issue now that new issue exists.

**Comment by JessicaLucindaCheng** [comment]
Today, I 
- Updated the hackforla bot token and the elizabethhonest bot token to never expire.
- Updated the documentation for each token: [How to update Hackforlabot token](https://docs.google.com/document/d/1ZKmzwSgDFRAFthTFFPIw5NohCn7nPEXJXTHoL8R2uhw/edit?usp=sharing) and [Wins Form Admin Guide](https://docs.google.com/document/d/1j1JTX5XzotgVCVZ91ImvenedPN5-IVjdSKDukq1B9iE/edit?usp=sharing). I have added links to these documents in the [Admin section of the Resources wiki page](https://github.com/hackforla/website/wiki/Resources#admin).
- To the How to create issues wiki page, I added [Step 4-1: Additional action items for issues involving HfLA Website Admin Drive](https://github.com/hackforla/website/wiki/How-to-create-issues#step-4-1-additional-action-items-for-issues-involving-hfla-website-admin-drive)
