### ISSUE TITLE
Manage website info for all team meetings

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#375]
### Overview
This issue is to document the current meeting time/method of all teams, and to have it auto notify the website team so that they can add that info to the website when there are changes. 

### Action Items

- [ ] Add or or post a comment revising your meeting time
- [ ] Add details about the method if you want it to appear on your project page (you could also only share it via slack, your choice).

**Comment by ExperimentsInHonesty** [comment]
**Monday**

- 5:30-10:30 pm lucky parking
- 6:30-8:30 pm HelloGov
- 6:30-8:45pm Record Clearance
- 6:30-6:40 Not Today (updates)
- 6:30-8:30 pm New Schools Today
- 6:30-TBD pm Public Tree map
- 7:00-9:00 pm VRMS

**Tuesday**

- 6:30-7:30 pm Food Oasis
- 7:00-9:00 pm 311 data team meeting

**Wednesday**

- 6:30-9:00 pm Undebate
- 6-6:45pm IT + hosting + operations working group
- 6:00-7:00 pm engage
- 7:00-9:00 pm  equity language
- 7:00-8:30 pm TDM Calculator

**Thursday**
- 7:00-8:00 pm 311-data management meeting
- 8:00-10:00 pm CivicTechIndex
- 8:00-9:00 pm Food Oasis


**Friday**


**Saturday**

- 10:00-12:00 am TDM-Calculators
- 12:00-2:00 pm Host Homes
- 2:00-4:00 pm New Schools Today

**Sunday**

- 10:00-12:00 am Hack for LA website
- 12:00-2:00 pm  Hack for LA marketing team.  **NEW**
- 2:00-4:00 pm CivicTechIndex


**The teams I have not heard what their meeting time is going to be is:**
record-clearance 
hellogov

**Comment by emillipede** [comment]
public tree map: 
- Mondays at 6:30 pm (duration tbd)
- I'll plan to share links to the meetings in slack

**Comment by ExperimentsInHonesty** [comment]
VRMS
- Wednesdays at 7:00-9:00
- we will publish the link on our project homepage (when that becomes possible, in the meantime details in slack).

**Comment by poornaraob** [comment]
Undebate: 
-  We planned to meet on Wednesday between 6.30p.m to 9.00p.m 
-  Meeting will be hosted on the link: meet.google.com/hpe-jxin-kww
-  We have posted the link on Slack. We can also publish the link on our project homepage too.

**Comment by breeze-094** [comment]
Lucky Parking:
- Mondays at 5:30 pm-10:30 pm
- Share the meeting info through Slack pinned items and also through the home page.

**Comment by KPHowley** [comment]
This week The TDM Calculator team will also be meeting Wednesday from 7:00PM - 8:30PM

**Comment by Cstoyanoff** [comment]
Civic Tech Index:

- Sundays at 2 p.m. - 4 p.m.
- Thursdays at 8 p.m. - 10 p.m.
- Join us at #civic-tech-index on Slack

**Comment by joelparkerhenderson** [comment]
Equity Language:

  * Wednesday 7pm-9pm

For March 18 the contact info is:

  * https://zoom.us/j/415-317-2700

After March 18 the contact info is:

  * https://zoom.us/j/525121156?pwd=UUlKNTlRRkdnK2x1Y1JvMHRrMEpNQT09
  * Zoom Meeting ID: 525 121 156
  * Zoom Password: 099998

**Comment by joelparkerhenderson** [comment]
IT + hosting + operations working group:

  *  Wednesday 6pm-6:45pm

For March 18 the contact info is:

  * https://zoom.us/j/415-317-2700

After March 18 the contact info is:

  * https://zoom.us/j/410239238?pwd=WXFZbXBNUFVyUkZ1NkRJcEZxMVJOUT09
  * Meeting ID: 410 239 238
  * Password: 068399

**Comment by KPHowley** [comment]
The TDM Calculator project is having a meeting tonight at 7:00pm

-  The zoom link for tonight is: https://us04web.zoom.us/j/437018661

**Comment by ExperimentsInHonesty** [comment]
BTW.  I add a 👍 when I add or update a teams schedule above: https://github.com/hackforla/website/issues/375#issuecomment-599829924

**Comment by lucas-homer** [comment]
The FOLA team is moving their Sunday at 4pm meeting to Thursdays at 8pm (starting tonight!)

Tuesdays at 6:30pm -- [https://us04web.zoom.us/j/254220274](https://us04web.zoom.us/j/254220274)
Thursdays at 8pm -- [https://us04web.zoom.us/j/658859348](https://us04web.zoom.us/j/658859348)

**Comment by jpmikesell** [comment]
The FOLA team is moving their Sunday at 4pm meeting to Thursdays at 8pm.

Tuesdays at 6:30-7:30pm -- https://us04web.zoom.us/j/254220274
Thursdays at 8-9pm -- https://us04web.zoom.us/j/658859348

**Comment by kate-rose** [comment]
HelloGOV

Mondays at 6:30-8:30p 
Zoom link to be sent to the #hellogov Slack channel.

**Comment by ExperimentsInHonesty** [comment]
host home project is now called HomeUniteUs or Home Unite Us

**Comment by alexandrastubbs** [comment]
New issue will be created for another round of updates.
