### ISSUE TITLE
Consolidate Reusable Functions in github-actions

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#3750]
### Overview
Developers have noted that certain javascript functions in [github-actions](https://github.com/hackforla/website/tree/gh-pages/github-actions) are being declared and defined across multiple files. We want to make these functions reusable within the codebase so they are not being defined multiple times for the same function across different files.

### Action Items
- [x] Look through the [github-actions](https://github.com/hackforla/website/tree/gh-pages/github-actions) folder and find all instances of a function that is defined more than once
  - [x] e.g. getTimeline(issueNum) is defined in add-label.js _and_ preliminary-update-comment.js
  - [x] Take note of any functions that have the same name, but different sets of parameters
- [x] Define all reusable functions within the github-actions/utils folder so they can be called in other files without redefining them
- [x] Test in your local repo that this does not break any existing GHAs 

### Resources/Instructions
- [Github Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)

**Comment by wendybarrios** [comment]
i. Availability: [Mondays, Wednesday, Thursdays]: 8:00 am - 10 am / 5:00pm - 8:00 pm
ii. ETA: 3/20

**Comment by ExperimentsInHonesty** [comment]
It looks like you assigned yourself to this issue but didn't move it into the in progress.  I'll do that now.

**Comment by wendybarrios** [comment]
1. Progress: Read GHA Resources
2. Blockers: Work
3. Availability: 5 hours
4. ETA: 4/2

**Comment by wendybarrios** [comment]
I have a blocker. I am getting this error message when I run the Add-Update-Label-to-Issues-Weekly workflow on act.js.  I created a file called get-timeline.js to hold the getTimeline function to use in these files: add-label.js and preliminary-update-comment.js. I'm not sure if I am calling the function correctly in add-label.js. The message says "issueNum is not defined" but I'm not sure if I'm importing/exporting the getTimeline function correctly.


 
Error Message: 
<img width="1193" alt="Screen Shot 2023-04-12 at 4 28 14 PM" src="https://user-images.githubusercontent.com/102558203/231607654-1453d101-2842-4fa2-8020-303ce7b6b57a.png">
Get-timeline file I created to export the getTimeline function:
<img width="1149" alt="Screen Shot 2023-04-12 at 4 31 50 PM" src="https://user-images.githubusercontent.com/102558203/231608049-6083aa9f-dfc8-4828-98c9-216ef40e714a.png">
Used Require to import the function to add-label.js:
<img width="937" alt="Screen Shot 2023-04-12 at 4 38 52 PM" src="https://user-images.githubusercontent.com/102558203/231608948-dc12abbd-ed1d-42d4-a9e7-08f0e217e4e0.png">
Called the function in add-label.js:
<img width="1235" alt="Screen Shot 2023-04-12 at 4 35 31 PM" src="https://user-images.githubusercontent.com/102558203/231608510-6ab5b1ea-4b57-48eb-a314-938d247fdc67.png">

I'm working in the "consolidate-reusable-functions-in-github-actions-3750" branch on my forked repo.
Any help is appreciated!

**Comment by jdingeman** [comment]
@wendybarrios have you tried doing something like this

get-Timeline.js
```
/*
code body
*/

export { getTimeline };
```

and importing it into add-label.js like this
```
import { getTimeline } from './utils/get-timeline.js'
/* 
code body
*/
````

**Comment by wendybarrios** [comment]
@jdingeman Yes! But when I ran the workflow, this is the message I got. For this message, I tried adding: `"type": "module"` to the package.json file but the file was locked.

<img width="1158" alt="Screen Shot 2023-04-13 at 6 39 48 PM" src="https://user-images.githubusercontent.com/102558203/231919433-659d9742-ee2f-4e0c-b863-bdf01db505e3.png">

**Comment by wendybarrios** [comment]
Progress: Testing GHAs
Blockers: Work
Availability: 5 hours
ETA: 5/7

**Comment by roslynwythe** [comment]
Hi @wendybarrios please leave us an update using the format outlined in the comments above, or let us know if you are not able to continue working on this issue.  Thank you

**Comment by wendybarrios** [comment]
Sorry, I'll provide an update by tomorrow!

**Comment by wendybarrios** [comment]
Progress: Tested getTimeline(issueNum) in add-label.js and need to test getTimeline(issueNum) in preliminary-update-comment.js
Blockers: GHA Testing
Availability: 5 hours
ETA: 6/18

**Comment by roslynwythe** [comment]
Hi @wendybarrios thank you for briefing us on this issue at the Sunday meeting.  Please provide an update to let us know if you will be continuing with work on this issue.

**Comment by wendybarrios** [comment]
Update: I unassigned myself from this issue. For the future assignee, I gathered the reusable functions I could find and their locations. I stored them in this Replit link: https://replit.com/@wendybarrios/Consolidate-Reusable-Functions-in-github-actions-3750#index.js. Feel free to edit the replit! : )

**Comment by one2code** [comment]
**ETA**:  09/13/23

**Comment by one2code** [comment]
**Progress:** My computer was down for repairs, I just got it back from the shop tonight, so I haven't been able to work on the issue much since I pulled the issue.
**Availability:** I should have 2-3 hours Sunday, and then some more time on the following Wednesday & Thursday
**ETA:** Probably going to need another two weeks, so I expect end of month.

**Comment by LRenDO** [comment]
Hi @one2code! Hope you're doing well and the laptop has been working for you. Are you still working on this issue? If so, please add an update. If not, please let us know you're unable to complete the issue. If we don't hear from you soon, we will remove you from the issue. Thanks!

**Comment by LRenDO** [comment]
Taking @one2code off of this issue since we haven't received an update. Moving back to new issue approval for re-prioritization.

**Comment by aadilahmed** [comment]
Availability: 9am- 5pm Monday-Friday
ETA: 11/28 EOD
