### ISSUE TITLE
Update Project Profile: [TDM Calculator]

### ISSUE THREAD

**Issue by Biuwa** [hackforla/website#3755]
### Overview
As a developer, we must ensure our project's details are up to date on the HackforLA website. We need to update the [TDM Calculator](https://www.hackforla.org/projects/design-systems) page's links and leadership.

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of [_projects/tdm-calculator.md](https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md) to find the `links` and `leadership` variables. 
- [x] Add two new links to the project's `links` variable. (The one with no indentation)
    - [x] Name: Test Site
URL: https://tdmdev.azurewebsites.net/calculation/4
    - [x] Name: Site
URL: https://tdm.ladot.lacity.org/
- [x] Remove the following persons from the `leadership` variable
    - [x] Kevin Howley
    - [x] Claire Nguyen
    - [x] Kevin Shih
    - [x] Vivek Jha
- [x] Add the following persons `name`, `role`, `links`, and `picture` to the `leadership` variable
    - [x] Name: Ebi Imafidon
GitHub Handle: Biuwa
Role: Product Manager
Slack Member ID: U031EU2E6LB
    - [x] Name: Renee Moore-Adams
GitHub handle: Reneedesigns
Role: Lead, UX Design
Slack ID: U032LNZNRJ5
    - [x] Name: Jane He
GitHub handle: Jane4925
Role: Lead, UX Research
SLACK ID: U01RDSRT46R
    - [x] Name: James Higgs
GitHub handle: jahpe777
Role: Frontend Developer
SLACK ID: U015ZGMK171
- [x] Test the [TDM Calculator project page](https://www.hackforla.org/projects/tdm-calculator) on your local development environment to ensure the changes are being properly displayed
### Instructions
- Be sure to use valid YAML syntax and match the existing structure of [_projects/tdm-calculator.md](https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md)
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/
- For the github link, append the team member's github handle to https://github.com/
- For the picture URL, append the team member's github handle to https://avatars.githubusercontent.com/

### Resources
- [TDM Calculator project page](https://www.hackforla.org/projects/tdm-calculator)
- [_projects/tdm-calculator.md](https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by Jaretzbalba** [comment]
Review availability: Weekdays 10-12pm
ETA: 12/16 5pm

**Comment by arpitapandya** [comment]
@Jaretzbalba I have to un-assign you. Please work on only one small issue, Since you already completed your small issue, look for a medium issue. You may find the instructions on your pre-work checklist.

**Comment by bzzz-coding** [comment]
Availability for this week: 3 hours
My estimated ETA for completing this issue: the end of the day Friday, Jan 12, 2023
