### ISSUE TITLE
ER: github-actions bot removing Draft label

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3758]
### Emergent Requirement - Problem
The github-actions bot is removing the `Draft` label. This happens when the `Draft` label is added after clicking the "Submit new issue" button.

### Issue you discovered this emergent requirement in
- #3738
- #3757
- #3756 

### Date discovered 
November 21, 2022

### Did you have to do something temporarily?
- [x] YES
- [ ] NO

I had to reapply the "Draft" label.

### Who was involved?
@JessicaLucindaCheng 

### What happens if this is not addressed
If the "Draft" label is removed by the bot and not reapplied by the issue writer, then it will require someone to take the time to read the issue to see the status of the issue and then reapply the "Draft" label.

### Recommended Action Items
- [ ] See if it Is possibly related to issue #3334, #3341 
- [ ] Make a new issue
- [ ] Discuss with the team

### Potential solutions [draft]
- After discussion at the PM/Dev Lead meeting on March 27, 2023, it was determined that we will make new issues to add the labels that are part of the Missing series onto the templates so that the label exists on the issue already before the dev submits the new issue. 
  - This won't solve the issue directly, but the idea is that we avoid the GitHub bot's intervention if the template already has the labels
  - Need to make a template for the issue
  - Make a bunch of good first/second issues to fix the issue templates

**Comment by JessicaLucindaCheng** [comment]
Finishing this ER:
- Progress: Almost done but I need to step away before I can complete filling out the ER
- Availability: 6 hours
- ETA: Thu, Dec 1, 2022

Update: Finished writing ER

**Comment by jdingeman** [comment]
It was discussed during the Tuesday planning meeting that this may not be fixable as it is a matter of us putting the labels against GitHub's API -- specifically when the issue creator puts a new label immediately after submitting the issue.

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge So what are the next steps for this issue, should move it into prioritized backlog?

**Comment by jdingeman** [comment]
@hackforla/website-merge - we need to discuss the possibility of having the templates already include the "Missing: " series to avoid situations of issue writers adding labels to an issue immediately after issue submission. That way since the template will come prefilled with the labels, the automation (ideally) won't try to take off the label upon submission.

**Comment by MattPereira** [comment]
@hackforla/website-merge 

I thought we discussed this issue of bot ripping off any label you add right after creation of an issue.

The github API is kinda slow and will just reject any labels if you add them too quickly after issue creation.

Its nothing we can fix with the code in our repository. My first `large` issue was this same problem but with the `Ready for Milestone` label and I spent months disappointed in myself that I couldn't solve it

I would hate for another dev to be given a mission impossible issue. It feels real bad.

**Comment by MattPereira** [comment]
> having the templates already include the "Missing: " series to avoid situations of issue writers adding labels to an issue immediately after issue submission

This could potentially address the required `size`, `complexity`, and `role` labels but this ER is about the optional `draft` label

> the automation (ideally) won't try to take off the label upon submission

I don't think the automation ever takes off labels that are already attatched prior to issue creation

**Comment by jdingeman** [comment]
Started a new epic with issue template based off of our conversation about adding the Missing series labels to our issue templates:
- https://github.com/hackforla/website/issues/4307
If template and plan is acceptable, can we close this ER?

**Comment by ExperimentsInHonesty** [comment]
I have added the draft label to the ER that Justin opened above.
