### ISSUE TITLE
Getting Started webpage: Fix Steps 3 and 4 to be consistent

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3761]
### Overview
On the Getting Started webpage, we want Step 3 to be Adopt Our Standards and Step 4 to be Choose a Role in the header section of the page so that 
- the order of the steps is consistent with the detailed instruction cards in the body of the page and
- we maintain a professional-looking website.

### Details
<details>
  <summary>current state of Getting Started webpage image of the steps in the header section</summary>
  <img width="836" alt="" src="https://user-images.githubusercontent.com/31293603/211765412-65277217-8468-4748-875b-2900a01d3468.png">
</details>

<details>
  <summary>future state of Getting Started webpage image of the steps in the header section</summary>
  <img width="836" alt="" src="https://user-images.githubusercontent.com/37763229/212552620-c4c47d0d-c284-4ff1-ac6a-f4c2efd8db51.png">
</details>

### Action Items
**Developer**
- [x] In the `pages/getting-started.html`, switch Step 3 and Step 4 in the header section so that Step 3 is Adopt Our Standards and Step 4 is Choose a Role
- [x] Using developer tools, make sure your changes look good when you view the page in mobile, tablet, and desktop views

**Product Manager**
- [ ] After the pull request to fix this issue has been merged and passed Quality Assurance, pass this to the Design Lead to write an issue for a designer to update the Getting Started section in the [Current Pages in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A0&t=vN6N6qjUVS9lbn3j-0) so that
  - the desktop design for the webpage has the steps in the header be Step 3 is Adopt Our Standards and Step 4 is Choose a Role
  -  the desktop design for the webpage has the detailed, instruction cards on the lower part of the page be Step 3 is Adopt Our Standards and Step 4 is Choose a Role
  - update the site screenshot with the current Getting Started page for desktop view

### Resources/Instructions
- [Getting Started webpage](https://www.hackforla.org/getting-started)
- [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)

**Comment by JessicaLucindaCheng** [comment]
### Issue writing
- Progress: Still need to add images but awaiting an answer to my blocker before proceeding further with writing the issue
- Blocker: See https://github.com/hackforla/website/issues/3761#issuecomment-1336128568
- Availability: 6 hours
- ETA: Dependent on when my blocker is addressed

### Notes
On https://www.hackforla.org/getting-started page, change the detailed cards on the bottom half of the page to match the steps at the top of the page so that Step 3 is Choose a Role and Step 4 is Adopt Our Standards.
- See how it is in Figma: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A0
- Currently: On the top, Step 3 is Choose a Role and Step 4 is Adopt Our Standards, which is correct. However, on the detailed cards on the bottom half of the webpage, Step 3 is Adopt Our Standards and Step 4 is Choose a Role, which is incorrect.
- I noticed a discrepancy in the order between the Figma desktop and mobile designs for the Getting Started detailed page cards

### To Dos
- [x] Add images to Details section of issue

**Comment by JessicaLucindaCheng** [comment]
On the [Current Pages in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A0&t=vN6N6qjUVS9lbn3j-0), I noticed a discrepancy in the order between the desktop and mobile designs for the Getting Started detailed page cards. Is it supposed to be:
  1. Step 3 is Choose a Role and Step 4 is Adopt Our Standards

<details>
  <summary>Expand here to see Getting Started page in desktop view</summary>
  ![4 edited desktop MVP](https://user-images.githubusercontent.com/31293603/205435327-c99ffef5-bca0-4c4f-b3e9-aa8f067ab894.png)

</details>

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 
For the Getting Started designs on the [Current Pages in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A0&t=vN6N6qjUVS9lbn3j-0), I noticed a discrepancy in steps 3 and 4 between the desktop and mobile designs' detailed page cards. 

Which one is it supposed to be?
a. Step 3 is Choose a Role and Step 4 is Adopt Our Standards
b. Step 3 is Adopt Our Standards and Step 4 is Choose a Role

Answer: b

<details>
  <summary>Expand here to see Getting Started page Figma design for desktop</summary>
  <img src="https://user-images.githubusercontent.com/31293603/205435327-c99ffef5-bca0-4c4f-b3e9-aa8f067ab894.png" alt="">
</details>

<details>
  <summary>Expand here to see Getting Started page Figma design for mobile</summary>
  <img src="https://user-images.githubusercontent.com/31293603/205435712-2a7b16fa-0e11-426e-92f2-672fb09c71a1.png" alt="">

</details>

**Comment by d-perez-8** [comment]
Availability: Weekdays 4pm-5:30pm
ETA: EOD 1/19/2022
