### ISSUE TITLE
Update Project Profile: Home Unite Us

### ISSUE THREAD

**Issue by randelbrot** [hackforla/website#3773]
### Overview
As a developer, we must ensure our project's details are up to date on the HackforLA website. We need to update the [Home Unite Us](https://www.hackforla.org/projects/home-unite-us) page's leadership.

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of [_projects/home-unite-us.md](https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md) and find the `leadership` variable. 
- [x] Remove the following persons from the `leadership` variable
    - [x] Tracy Michelle
    - [x] Regan Hutson
    - [x] Kristy Points
    - [x] Ben Ross
- [x] Add the following persons `name`, `role`, `links`, and `picture` to the `leadership` variable
    - [x] Name: Jed Stewart
GitHub Handle: jed-stewart
Role: Developer
Slack Member ID: U04A3J6V0HY
    - [x] Name: Mira Kinebuchi
GitHub Handle: mira-kine
Role: Developer
Slack Member ID: U0411CAL13N
    - [x] Name: Stephen Barkley-Yeung
GitHub Handle: stevbark
Role: Developer
Slack Member ID: U041403GHEC
    - [x] Name: Kristelle Gumaru
GitHub Handle: K-Gumarama
Role: Product Manager
Slack Member ID: U031VJ99ATU
    - [x] Name: Sanya Nijhawan
GitHub Handle: sanya301
Role: Product Manager
Slack Member ID: U031FLYS561
    - [x] Name: Raji Pradheap
GitHub Handle: rpradheap
Role: Product Manager
Slack Member ID: U02R9MKA6KH
    - [x] Name: Bryce Lednar
GitHub Handle: brycelednar
Role: Product Manager
Slack Member ID: U049TSDG2SX
    - [x] Name: Farah Khan
GitHub Handle: fourmatte
Role: UX/UI Designer
Slack Member ID: U01JC8VEKMH
    - [x] Name: Eduardo De La Rosa
GitHub Handle: edela0015
Role: UX/UI Designer
Slack Member ID: U0430G2T4AC
    - [x] Name: Flora Osmond
GitHub Handle: itzflowa
Role: UX/UI Designer
Slack Member ID: U047ZT4GP5E

- [x] Test the Home Unite Us Project Page at [http://localhost:4000/projects/home-unite-us](http://localhost:4000/projects/home-unite-us) on your local development environment to ensure the changes are being properly displayed

### Instructions
- Be sure to use valid YAML syntax and match the existing structure of [_projects/home-unite-us.md](https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md)
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/
- For the github link, append the team member's github handle to https://github.com/
- For the picture URL, append the team member's github handle to https://avatars.githubusercontent.com/

### Resources
- [Home Unite Us project page](https://www.hackforla.org/projects/home-unite-us)
- [_projects/home-unite-us.md](https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by Satenik-Ba** [comment]
Availability : 1/12/2023
ETA: 1hr

**Comment by ExperimentsInHonesty** [comment]
@brycelednar Can you confirm that we made all the changes you expected.

**Comment by randelbrot** [comment]
Hi @Satenik-Ba, 

I have one edit after reviewing the changes:

- In the Current Project Team section, please update the role for any team members currently listed as "Project Manager" to "Product Manager"

Thank you!

**Comment by Satenik-Ba** [comment]
Hi @brycelednar, 
Done. Thank you!
