### ISSUE TITLE
Credits page: Add "Altered by" field

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3775]
### Overview
We need an "Altered by" field to show up for some credits used in the redesigned version of the homepage so that the Credits webpage gives credit to Hack for LA designers that have edited images we use on the website. 

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] If a credit's yml information file has an `altered-by` entry, make the `Altered by:` field (along with the name of the person who altered it) show up after the `Provider` field for that credit on the Credits page.
  <details>
    <summary>Click here to see an example of where the Altered by field should show up</summary>
    <img width="419" alt="" src="https://user-images.githubusercontent.com/31293603/211209240-c4350a1e-5653-4ed5-8c3c-b6a1e6b413d9.png">
  </details>
- [x] The `Altered by` field should show up for the following existing credits:
  - [x] Diversity, Equity, Inclusion
  - [x] Social Safety Net 
  - [x] If the pull request to fix issue #3352 has been merged, then Civic Tech Infrastructure should have the field show up as well.
- [x] The "Altered by" field should also show up for any credits added in the future with that field
- [x] The "Altered by" field should **not** show up for any credit's yml files that either
  - [x] has an `altered-by` field that doesn't contain any information (e.g. `altered-by:              `)
  - [x] or doesn't have an `altered-by` field
- [x] Take screenshots of the credits with the `Altered by` field and place them in a new comment below.
- [x] Show the screenshots/visual changes to the Credits page to our Stakeholder Rep and get the Stakeholder Rep's approval of the changes you made. (You can find who the Stakeholder Rep is on the Hackforla.org Website project's detailed information webpage.)
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into `feature-homepage-launch`. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article

**Tech Lead or Merge Team**
- [x] After the pull request associated with this issue is approved and merged, please make sure this issue is closed. If it is not closed by the automation, leave a new comment stating what pr number fixes this issue and then close this issue as completed.

### Resources/Instructions
- [Credits page](https://www.hackforla.org/credits/)
- [How to work off of a feature branch wiki page](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
- Directory of all the yml credit information files on the feature-homepage-launch branch: [`_data/internal/credits`](https://github.com/hackforla/website/tree/feature-homepage-launch/_data/internal/credits)
  - [diversity-equity-inclusion.yml](https://github.com/hackforla/website/blob/feature-homepage-launch/_data/internal/credits/diversity-equity-inclusion.yml)
  - [social-safety-net.yml](https://github.com/hackforla/website/blob/feature-homepage-launch/_data/internal/credits/social-safety-net.yml)
- You can find who the Stakeholder Rep is on the [Hackforla.org Website project's detailed information webpage](https://www.hackforla.org/projects/website) 
- This issue is tracked in epic #3130.

**Comment by JessicaLucindaCheng** [comment]
Issue Writing
- Availability: 6 hours
- ETA: Sun, January 8, 2023

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty Since we don't have a design of how the "Altered by" field looks and this will be on the feature-homepage-launch, is QA after this issue's pr is merged sufficient? Or do you want me to add the following Action Item so that you approve of changes before it is merged? Ans: Add Action Item to get PM approval
- [ ] Take screenshots of the credits with the `Altered by` field and show them to the PM(s) to approve of the changes.

**Comment by Satenik-Ba** [comment]
Availability: 1/21/23
ETA: 1 week

**Comment by ExperimentsInHonesty** [comment]
@Satenik-Ba I have moved this issue to in the progress column.  Please do that in future when you self assign

**Comment by Satenik-Ba** [comment]
screenshots of the credits with the Altered by field 
<img width="387" alt="Screen Shot 2023-01-23 at 12 22 53 PM" src="https://user-images.githubusercontent.com/79809138/214151202-4a35fed4-be0b-43c5-8893-48fba797ae70.png">

<img width="363" alt="Screen Shot 2023-01-23 at 1 06 25 PM" src="https://user-images.githubusercontent.com/79809138/214151245-fb02dd13-38d2-415d-8718-dfa3d1162380.png">

**Comment by Satenik-Ba** [comment]
Hi @ExperimentsInHonesty! Above comment has the screenshot of the visual changes to the credits page with Altered by fields. Would you please review the changes made? Thank  you!

**Comment by Satenik-Ba** [comment]
Update
Awaiting @ExperimentsInHonesty to approve the changes to the credits page with Altered by fields before pull request.

**Comment by Satenik-Ba** [comment]
Update
Awaiting @ExperimentsInHonesty to approve the changes to the credits page with Altered by fields before pull request.

**Comment by ExperimentsInHonesty** [comment]
@Satenik-Ba The new layout works for me.  I do want to add something else, though.  Let's link the Altered by name to their LinkedIn.  Kristine's LinkedIn is https://www.linkedin.com/in/kristine-eudey/

Sorry for the delay.  If you need me to review in the future, please put this issue in the questions and review column with a `ready for product` label on it.  Usually these questions get resolved at the Sunday meeting. If you can't make that meeting, adding it to the questions and review column will get someone's attention.  You can also reach out to the leads if you are blocked.

**Comment by Satenik-Ba** [comment]
Sounds good, will make the updates. 
Availability: 2/27
ETA: 1day

**Comment by JessicaLucindaCheng** [comment]
- PR #4053 fixed this issue.
