### ISSUE TITLE
Allow for project "languages" to be pulled from multiple repositories

### ISSUE THREAD

**Issue by MattPereira** [hackforla/website#3805]
### Overview
As developers, we need to ensure all of the languages are displaying on the [Civic Tech Index Project Page](https://www.hackforla.org/projects/civic-tech-index). Since Civic Tech Index has two separate repositories for their front and back end, we need to figure out a way to display the languages data from both repos.

### Action Items
- [x] Understand how the website is currently grabbing the `languages` data for projects
- [x] Understand how the languages data makes it onto each project page (not coming from the [civic-tech-index.md](https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-index.md))
- [x] Figure out which file controls the languages that are displayed for each project. Alter the logic of this file so that the Civic Tech Index pages shows the languages from both of their github repositories.

### Resources/Instructions
- [See Comment that created this issue](https://github.com/hackforla/website/issues/2728#issuecomment-1086902818)
- [Wiki: How languages are added to the `project` variable](https://github.com/hackforla/website/wiki/Guide-to-the-Project-Layout-File#adding-languages)
- [CTI Front End Repo](https://github.com/civictechindex/CTI-website-frontend)
- [CTI Back End Repo](https://github.com/civictechindex/CTI-website-backend)

**Comment by jch1013** [comment]
Availability - Weeknights after 5pm
ETA: 2 weeks from today, but subject to change

**Comment by jdingeman** [comment]
Hey @jch1013, just wanted to check in to see if you could provide an updated ETA. I see you said your ETA two weeks ago and I'd just like to confirm if you've been able to work on this/plan to work on this.

**Comment by jch1013** [comment]
Sorry for the lack of update, life has been crazy this last week. I am working on it but am having some difficulty understanding how the language data is pulled. Hoping to get some help on Thursday, I can provide an updated ETA then!

**Comment by jch1013** [comment]
I'm not going to be able to figure this one out, still don't have a full understanding of why the program isn't working as it should. For anyone working on this in the future, a good starting point might be determining why line 107 on get-project-data.js isn't including the missing repository even though it has the hack-for-la tag. I think the large categorization might be more appropriate for this issue.

**Comment by d-perez-8** [comment]
Availability: Weekdays 3pm -5pm
ETA: 3/15/2023

**Comment by jdingeman** [comment]
Hey @d-perez-8 - I know this one has been a doozy. I wanted to see if you had any updates? Please comment a progress report and any blockers you are facing. Thanks! 😄

**Comment by d-perez-8** [comment]
@jdingeman Hey Justin. I have been slowly working on the FigJam diagram and I will be looking forward to some help at Tuesday's meeting. No blockers so far, just need a second opinion to make sure the diagram makes sense. Thanks for checking in!

**Comment by d-perez-8** [comment]
Blocker: My solution to combine the languages section also affects the contributors' list. We may need to write another issue to resolve this problem. I am unsure whether to submit a pull request or try to fix the contributors' list, although it is outside the scope of this issue.

**Comment by d-perez-8** [comment]
Update: After fixing the language issue, the contributor section would not populate the contributors. I will look further into the issue and fix the contributor section. 
ETA: 04/04/2023
Availability: 2-5 weekdays

**Comment by d-perez-8** [comment]
Another issue: The current-project.js now has an error because it only takes one identification number from the md page. This error causes the project cards not to be populated onto the projects page.

**Comment by jdingeman** [comment]
Hey @d-perez-8 - I know you've been toiling over this one. Have you made any progress?

**Comment by d-perez-8** [comment]
@jdingeman Hey, Justin. I'm sorry for not getting back to you sooner, but I am taking a break from HackForLA. I'll be available to help whoever will take this issue via Slack.

**Comment by jdingeman** [comment]
> @jdingeman Hey, Justin. I'm sorry for not getting back to you sooner, but I am taking a break from HackForLA. I'll be available to help whoever will take this issue via Slack.

Hey @d-perez-8 - no worries, totally understandable! If possible, could you do a small write up here about steps you've tried and what has and hasn't worked? That way the developer won't redo all of your steps. Also if you can keep your branch published on the remote so they can reference if there were any changes you made. Thanks!!

After that, we'll go ahead and unassign you and reprioritize it.

**Comment by StephenTheDev1001** [comment]
i. Availability: M - F 10am - 12pm
ii. ETA: May 18th

**Comment by roslynwythe** [comment]
Hi @StephenTheDev1001 please leave us an update.  Thanks.

**Comment by StephenTheDev1001** [comment]
1. Progress: Figuring out how to grab data from multiple repositories.
2. Blockers: 
3. Availability: 15 hrs for the following 7 days
4. ETA: Jun 20

**Comment by StephenTheDev1001** [comment]
The data for both CTI Front End and CTI Back End show up on [github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/github-data.json). If [github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/github-data.json)  is populated by [get-project-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/github-data/get-project-data.js), how would changes to [get-project-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/github-data/get-project-data.js) solve the problem? I'm thinking the code that pulls from [github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/external/github-data.json) would need changes. I'm looking for the code that pulls from github-data.json. Would this approach be appropriate?

or making changes to [get-project-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/github-data/get-project-data.js) and make CTI Front End and CTI Back End into one object would be better?

**Comment by MattPereira** [comment]
@StephenTheDev1001 you are absolutely correct the data is already in the `github-data.json` file. Apologies for the misdirection caused by [the comment](https://github.com/hackforla/website/issues/2728#issuecomment-1086902818) that prompted creation of this issue.

I agree with your assessment that the code that pulls from `github-data.json` is what needs to be altered

**Comment by StephenTheDev1001** [comment]
1. Progress: Looking for the code that pulls from github-data.json
2. Blockers:
3. Availability: 10am - 12pm M - F
4. ETA: July 5th

**Comment by StephenTheDev1001** [comment]
I think I found the old file that pulled code from `github-data.json` [github/workflows/main.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/main.yml). It's a broken link that I found here [Wiki: Fetching Correct Project](https://github.com/hackforla/website/wiki/Guide-to-the-Project-Layout-File#fetching-correct-project).

Would the broken link need a new issue to fix it?
I'm new, can someone lead me to some docs for creating new issues?

**Comment by StephenTheDev1001** [comment]
From my understanding so far, [project.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js) takes a single github repo ID#. 

Then outputs the languages using this script [Wiki: How languages are added to the `project` variable](https://github.com/hackforla/website/wiki/Guide-to-the-Project-Layout-File#adding-languages)

My suggestion is to modify [project.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js) to enable it to accept multiple ids per project.

On line 15 -16 of [project.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js)
`const scriptTag = document.getElementById("projectScript");`
`const projectId = scriptTag.getAttribute("projectId");`

I'm trying to figure out which file `"projectScript"` is coming from. Any suggestions would be appreciated.

**Comment by StephenTheDev1001** [comment]
Progress: One file found that needs to be altered. [gh-pages/assets/js/project.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js)
Blockers: Finding out how to add a project to the website would be helpful. The file that `project.js` gets the github repo id from needs to be found.
Availability: M-F 10am - 12pm
ETA: July 18th
