### ISSUE TITLE
Update Project Profile: TDM Calculator

### ISSUE THREAD

**Issue by Biuwa** [hackforla/website#3818]
### Overview
As a developer, we need to ensure our project's details are up to date on the HackforLA website. We need to update the "Current Project Team" for the [TDM Calculator Project Page](https://www.hackforla.org/projects/tdm-calculator).

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the [tdm-calculator.md](https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md) file and find the `leadership` variable.
- [x] Remove Renee Moore-Adams from the `leadership` variable
- [x] Add the new team members names, roles, slack links, github links, and picture to the end of the `leadership` variable
    - [x] Name: Anousha Shadrach
GitHub Handle: Noushie
Role: UX Designer
Slack Member ID: U045EHW8NDA
    - [x] Name: Moji Momoh
GitHub Handle: mojimoh
Role: Product Manager
Slack Member ID: D04HDM7DM18

- [x] Check the [TDM Calculator Project Page](http://localhost:4000/projects/tdm-calculator) on your local development environment to ensure the "Current Project Team" section is properly displaying the changes you made

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [tdm-calculator.md](https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md)
- [HFLA wiki on project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [How to find Slack IDs](https://github.com/hackforla/admin/wiki/Slack:-Find-a-Slack-ID)

**Comment by kotynskm** [comment]
Available: 1/31/23 ETA: expected completion today

**Comment by ExperimentsInHonesty** [comment]
@Biuwa Please confirm that we made all the changes you asked for.  If not, we will reopen this issue.  If you need changes not specified in this issue, feel free to open a new issue.

**Comment by Biuwa** [comment]
- @ExperimentsInHonesty yes all changes were implemented, but i misspelt Moji's last name and i opened a new issue #3963 to correct this and also make Anousha the lead UX designer
