### ISSUE TITLE
Wiki page: How to resolve merge conflicts

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3821]
### Pre-requisite
- You have resolved a merge conflict before.

### Overview
We need to write a wiki page for how to resolve merge conflicts so that developers have guidance on how to resolve merge conflicts when they encounter it.

### Action Items
- [x] Create a wiki page named `How to resolve merge conflicts` and add a link in the Resources/Instructions section [1]
- [x] In the wiki page, give instructions for developers on how to resolve merge conflicts
  - [x] You can provide links to other resources in the wiki page if you think they will be helpful to other developers
- [x] Have Website Team Technical Lead(s) and/or Merge Team member(s) review your wiki page 

### Resources/Instructions
- [1] Add a link to the wiki page you created here: https://github.com/hackforla/website/wiki/How-to-Resolve-Merge-Conflicts

**Comment by Skydodle** [comment]
Availability: Monday 03/13/23, Wed 03/15/23, Friday 03/17/23, 7 to 9pm
ETA: EOD Friday 03/17/23

**Comment by Skydodle** [comment]
Provide Update
1. Progress: Sorry something came up last week. I would like to have more time to work on this issue.
2. Blockers: No blockers.
3. Availability: Wed 3/22 to Fri 3/24
4. ETA: Friday 3/23 EOD

**Comment by Skydodle** [comment]
Provide Update

Progress: I'm at 80% completion, added page link to issue above, will continue to work on it tomorrow 3/25 and hope to wrap it up.
Blockers: No blockers. The content of this issue just takes more time than I expeceted.
Availability: Sat 3/25
ETA: Sat 3/25 EOD

**Comment by Skydodle** [comment]
Hello, 

I have completed the wiki page. I'm not sure if I put too much or too little content as it is a complex topic with numerous possible factors. Please kindly review and let me know know what changes need to be done.

Thank you so much!

**Comment by jdingeman** [comment]
@Skydodle - this is excellent! You made a very thorough and informative Wiki page and I believe we cnan sign you off for this issue. Thank you so much!

**Comment by Skydodle** [comment]
@jdingeman Thank you. I am thankful to have had this opportunity to practice writing documentations. I am curious to learn what happens with this wiki page next in QA?  What's the process and who would be incoporating this page into the Wiki category?

Also now that I have completed a large issue, what should I do next? Am I free to pick up medium and large issues? I accidentally closed my pre-work checklist (didnt realize it has do be after large issue sorry 😅 I closed it after completing a second issue) back in Nov before I took a 3 months break from HFLA for a job. Do I need to do something about this?

Thank you so much Justin!

**Comment by jdingeman** [comment]
Hey @Skydodle - when an issue goes to QA, it will go to Bonnie to review to make sure nothing else is needed or any other emergent requests come out of it. She will comment on this issue if something needs to be done, otherwise she will put it into the Done column. 
You are free to pick up another large issue! We try to save the medium issues for those that need to complete that complexity. Let's talk some time this week via Slack about some next steps for you.
