### ISSUE TITLE
CONTRIBUTING.md: Fix Windows docker-users... broken link

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3822]
### Overview
As a developer, I want to fix the `Windows docker-users group error guide` broken link in the CONTRIBUTING.md so that it links to the correct wiki page and is a useful resource for developers.

### Action Items
- [x] In VS Code or your IDE on your computer, go to section `1.5.a Docker installation troubleshooting` in the` CONTRIBUTING.md` file and fix the `Windows docker-users group error guide` broken link so that it links to https://github.com/hackforla/website/wiki/Add-local-user-accounts-to-the-docker-users-group-on-Windows-10. To do this, change this line of code
  ```
  - [Windows docker-users group error guide](https://github.com/hackforla/website/wiki/Adding-local-user-accounts-to-the-docker-users-group-on-Windows-10)
  ```
  to
  ```
  - [Windows docker-users group error guide](https://github.com/hackforla/website/wiki/Add-local-user-accounts-to-the-docker-users-group-on-Windows-10)
  ```
- [x] To see the visual changes
  - [x] Push the changes to your remote forked repo's topic branch
  - [x] Go to your remote forked repo on GitHub
  - [x] Switch to your topic branch
  - [x] Navigate to the file
  - [x] On the upper right, click on "Display the rendered blob" to see what your changes look like. Here is an image of what the "Display the rendered blob" button looks like:   
    <img width="320" alt="Display-rendered-blob" src="https://user-images.githubusercontent.com/31293603/161406861-26ace7b4-26b6-4981-9514-be8f651f5d6e.png">

### Resources/Instructions
- File to navigate to in your IDE: `CONTRIBUTING.md`
- [1.5.a Docker installation troubleshooting section in CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#15a-docker-installation-troubleshooting)
- [Add local user accounts to the docker users group on Windows 10](https://github.com/hackforla/website/wiki/Add-local-user-accounts-to-the-docker-users-group-on-Windows-10) wiki page

**Comment by vanessavun** [comment]
Availability: evenings, Thu 2/16 - Mon 2/19
ETA: by tomorrow 9PM, Fri 2/17
