### ISSUE TITLE
`Error` Credit: Fix name link

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3823]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We want to update an incorrect link on our Credits webpage so that proper credit is given for each image we use on the website.

### Action Items
- [x] In `_data/internal/credits/404.yml`, change the title-link from 
```
title-link: https://www.freepik.com/
```
to
```
title-link: https://www.freepik.com/free-vector/no-data-concept-illustration_5928292.htm#query=error&position=6&from_view=author
```
- [x] For the Error credit on the Credits webpage, ensure that when you click on **Error** it goes to https://www.freepik.com/free-vector/no-data-concept-illustration_5928292.htm#query=error&position=6&from_view=author.

### Resources/Instructions
- Credits webpage: https://www.hackforla.org/credits/
- Directory to find the page in once you have it in your IDE: `_data/internal/credits/404.yml`
- Click on the link to see the source file code: https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/404.yml

**Comment by steven-positive-tran** [comment]
i. Availability: (When are you available to work on the issue/answer questions other programmers might have about your issue?)

Any day after 6pm 

ii. ETA: (When do you expect this issue to be completed?)
Tuesday.
