### ISSUE TITLE
Mark Write for All project as On Hold

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3837]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We want to mark the Write for All project as `On Hold` so that 
- our website accurately reflects the status (Active, Complete, or On Hold) of our projects, 
- and visitors to our website can know the status of our projects.

### Action Items
- [x] In `_projects/writeforall.md`, change the status for Write for All from
  ```
  status: Active
  ```
  to
  ```
  status: On Hold
  ```
- [x] Ensure that the `On Hold` status is displayed properly on the [projects page](https://www.hackforla.org/projects/) and [Write for All page](https://www.hackforla.org/projects/writeforall)

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/writeforall.md`
- [Projects page](https://www.hackforla.org/projects/)
- [Write for All page](https://www.hackforla.org/projects/writeforall)
- Click on the link to see the source file code: https://github.com/hackforla/website/blob/gh-pages/_projects/writeforall.md?plain=1
- This issue is a result of this comment: https://github.com/hackforla/website/issues/2435#issuecomment-1314129039

**Comment by Sheikh-JamirAlam** [comment]
@JessicaLucindaCheng Can you assign this issue to me? Also can you move the issue from "prioritized backlog" to "in progress" under the Projects section?
@maryjng requested these [changes](https://github.com/hackforla/website/pull/3886#pullrequestreview-1274351225).

**Comment by JessicaLucindaCheng** [comment]
@Sheikh-JamirAlam 
- In order for you to assign yourself an issue and move the issue to the Prioritized Backlog, you need to join Hack for LA as a member. (There are no fees to join.) To become a member of Hack for LA, you will need to attend an online onboarding session, which you can sign up for here: https://www.meetup.com/hackforla/events
- For now, I will be closing your pr #3886. Once you join Hack for LA and if this issue is still available, you can self-assign this issue to work on it.

**Comment by vanessavun** [comment]
Availability for this week: Friday
My estimated ETA for completing this issue: Friday, 02/03/2023

**Comment by vanessavun** [comment]
I have a blocker. I'm not able to see the status change for Write For All under the projects page (/projects). The status did change to "On Hold" under "/projects/writeforall".

I followed the instructions under /writeforall to change the status:
```
status: Active
```
to
```
status: On Hold
```
![Screenshot 2023-02-03 122628](https://user-images.githubusercontent.com/94583613/216704160-b25ef85a-4375-4d12-9143-2085b1570651.png)
![Screenshot 2023-02-03 122810](https://user-images.githubusercontent.com/94583613/216704218-e18713eb-3c72-4644-9242-96ee7fa66ba9.png)

I inspected the projects page to find a hint on where else I'd need to change, but perhaps someone would already know why it is not changing.

I am working in the "update-writeforall-3837" branch in my forked repo.

**Comment by MattPereira** [comment]
Hi @vanessavun ,

So I don't fully understand why this is necessary, but if you shut down your docker container with `ctrl-c` or `docker compose down` and then start docker back up again with `docker compose up`, it will update and show the project status as `On Hold` for the "Write for All" project card on the http://localhost:4000/projects/ page. 

For working on this website, thats usually my go to move if a change isn't showing up as expected

**Comment by ftblmagician** [comment]
Availability for this week: Friday
My estimated ETA for completing this issue: 3/3/2023

**Comment by vanessavun** [comment]
> Availability for this week: Friday
> My estimated ETA for completing this issue: 3/3/2023

@ftblmagician this issue is done.  Please look for issues under Prioritized backlog. (This issue was under the Done status.)
