### ISSUE TITLE
Update Project Profile: Hackforla.org Website

### ISSUE THREAD

**Issue by blulady** [hackforla/website#3840]
### Overview
As a developer, we need to ensure our project's details are up to date on the HackforLA website. We need to update the "Current Project Team" for the [Hackforla.org Website Project Page](https://www.hackforla.org/projects/website).

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md) file and find the `leadership` variable.
- [x] Add the new team members names, roles, slack links, github links, and picture to the end of the `leadership` variable (just after Justin Dingeman). Order matters here. Note how Bonnie is listed first in markdown and thus appears at the top of the "Current Project Team" section.
    - [x] Name: Matt Pereira
Role: Merge Team
GitHub Handle: MattPereira
Slack Member ID: U045XKKB5DH
    - [x] Name: Phillip Sanchez
Role: Merge Team
GitHub Handle: plang-psm
Slack Member ID: U03UG3VCRK6
- [x] Remove 
   - [x] Name: Stephanie Samuels
   - [x] Name: Vaisali Krishna Kumar
- [x] Check the [Hackforla.org Website Project Page](http://localhost:4000/projects/website) on your local development environment to ensure the "Current Project Team" section is properly displaying the changes you made

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [Hackforla.org Website markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [HFLA wiki on project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [How to find Slack IDs](https://github.com/hackforla/admin/wiki/Slack:-Find-a-Slack-ID)

**Comment by perlaroyerc** [comment]
Availability: 11am-6pm ET, M-F
ETA: Monday Feb 6
