### ISSUE TITLE
Create dependabot.yml file for dependabot to create pull requests

### ISSUE THREAD

**Issue by Suman2795** [hackforla/website#3843]
### Overview

GH Dependabot has been enabled to issue alerts for vulnerabilities and security. Therefore we need a configuration file, dependabot.yml, to create pull requests so that we maintain up to date security in our repo.

### Action Items

- [x] Read [configure dependabot.yml](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates)
- [x] Read #3598 to understand HfLA's decision for implementing dependabot
  - [x] See associated [Decision Record for Dependabot](https://github.com/hackforla/website/wiki/DR:Using-Dependabot-to-update-GHA)
- [x] Create a dependabot.yml file in the [.github](https://github.com/hackforla/website/tree/gh-pages/.github) and configure the file as per the instructions given in 1st link

### Resources/Instructions

- [Enabling Dependabot Version Updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates)
- [Configuration Options for Dependabot.yml file](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file)
- ER for Decision Record: https://github.com/hackforla/website/issues/3598
- [Decision Record for Dependabot](https://github.com/hackforla/website/wiki/DR:Using-Dependabot-to-update-GHA)
- See previous work done here: #4102

**Comment by blulady** [comment]
Hey @Suman2795,
You did an outstanding job on this issue!! It just needed the dev leads label to get a lead to approve it (which I am going to but just for the sake of demoing I put the label on it so you can see it) and to be put onto the Project Board (which I also did but reach out if you want me to show you, it's not hard). But I think I failed to put a link about [issue creation](https://github.com/hackforla/website/wiki/How-to-create-issues) so it's kind of my fault.
But this is great, it will be very easy for a dev to follow this issue.

**Comment by Suman2795** [comment]
Thanks Sarah for reviewing this. I might have missed the dev leads label and yes please tell me how to put the issue on project board.

**Comment by ExperimentsInHonesty** [comment]
@kurikurichan please ignore the message asking you for an update only 1 day after you took on the issue.  But do this part

Do let fellow developers know about your:-
i. Availability: (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. ETA: (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks

**Comment by kurikurichan** [comment]
@ExperimentsInHonesty I'm available to work on this issue tomorrow afternoon, Tuesday afternoon, Weds night, and Thurs night. I would like to have this issue completed by Thurs (honestly, I would LOVE to have it done even sooner, this is just in case I have issues by then, and that way someone at the office hours can help me)

**Comment by blulady** [comment]
Moving this back into backlog. See Closed PR https://github.com/hackforla/website/pull/4102 for work that's already been done.

**Comment by ExperimentsInHonesty** [comment]
See the note Sarah left above, determine if this is ready for prioritization or something else needs to happen (such as removing completed items from the Action Items list.

**Comment by jdingeman** [comment]
Cleaned up issue. Issue is straightforward and is ready to priroritize.

**Comment by one2code** [comment]
Availability: 11 AM - 5PM EST on 4/20/23,  1-4 PM EST on 4/21/23, and available to answer questions at various times between 8 PM -4 AM between 4/21/23 - 4/23/23
 ETA: 4/26/23

**Comment by one2code** [comment]
Progress: Reviewed relevant documentation and began creating the config file on a new branch
Blockers: Understanding how to create the dependabot.yml, without having admin access in settings to automatically configure the dependabot as show in fig.1 . I reviewed relevant .yml files in the workflows directory to develop a deeper understanding of how to configure the dependabot.
Availability: 4/29/23-4/30/23 afternoon.
ETA: 4/30/23

**Comment by one2code** [comment]
Progress: Created the Dependabot.yml file based on the package managers listed in the package.json/lock file, and enabled version and security updates on my fork
Blockers: Having trouble testing it to verify that it works correctly. Need some guidance.
Availability: 5/5/23 Available 5-10pm EST. Then available to answer private messages on Slack (Travis) at various times throughout the weekend. Will be able to implement recommendations for testing during the evenings on the weekend, and will have all day available on 5/9/23 if need be.
ETA: 5/9/23

**Comment by one2code** [comment]
**Progress:** The Dependabot configuration file is now being read, as determined in insights>dependency graph>dependabot

**Blockers:** Difficulty in testing Github Actions without merging (create-dependabot.yml#3843 not found). Trying to find a way to test on a different branch. Tried changing the target-branch to "/", same issue persists. The npm package manifest is also not located in root, which will have to be resolved later.

**Availability:** Afternoon 5/10/23, evening 5/12/23, and afternoon 5/13 + 5/14 EST

**ETA:** 5/14/23

**Comment by blulady** [comment]
@one2code So it looks like we did do it correctly. It looks like Github no longer creates a public PR but sends an email instead. So check your emails...

**Comment by blulady** [comment]
> @one2code So it looks like we did do it correctly. It looks like Github no longer creates a public PR but sends an email instead. So check your emails...

Actually it did create pr's in my repo...

**Comment by t-will-gillis** [comment]
PR 4733 associated with this issue has been merged.
