### ISSUE TITLE
Create a Decision Record for the Toolkit's page hidden button

### ISSUE THREAD

**Issue by plang-psm** [hackforla/website#3848]
### Overview

We temporarily hide a non-functional button in the Toolkit's Page in issue #3678 and need to document the change in the Wiki. You will be creating a decision record documenting the changes made.

### Action Items

Before beginning, read through issue #3678. Once you have a good understanding of what the issue is about, continue to the below action items:

- [x] Go to the Decision Records in the Wiki or search the resources section for the link.
- [x] Determine if issue #3678 was adopted or implemented.
- [x] Create a new page (found on the top right) and fill out the template below.
``` 
This is a record in the [Decision Records on Solutions Not Implemented](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Not-Implemented).

#### Issue 
#### Problem Statement
#### Potential Solution
#### Feasibility Determination
```

- [x] After you save the page, copy and paste the link of your record in the records section of the adopted or implemented home page.
- [x] Once you check off all the items above, leave a comment mentioning the the Merge Team to review your work.

**Merge Team**

- [x] Review the Decision Record.
- [x] If the decision record passes all checks, leave a comment and link the record in issue #3678 noting that the document was recorded in the wiki.

### Resources/Instructions

Link to related issue: https://github.com/hackforla/website/issues/3678
Link to Decision Records: https://github.com/hackforla/website/wiki/Decision-Records
Example of Decision Record Structure: https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Not-Implemented
Example of a Decision Record: https://github.com/hackforla/website/wiki/DR:-Use-an-existing-add-on-converter-called-Docs-to-Markdown

**Comment by KazushiR** [comment]
i. Availability: Flexible
ii. ETA: 02/14/2023 6pm ET

**Comment by KazushiR** [comment]
@plang-psm Please see wiki per below. Please let me know if there are any errors that needs to be corrected by the merge team.
https://github.com/hackforla/website/wiki/DR:Create-a-Decision-Record-for-the-Toolkit's-page-hidden-button

**Comment by MattPereira** [comment]
@hackforla/website-merge hey Phillip wanna review the work for this issue?

**Comment by KazushiR** [comment]
Provide Update
1. Progress-Have completed the wiki
2. Blockers-Awaiting word from merge team
3. Availability-Flexible
4. ETA-02/14/2023

**Comment by plang-psm** [comment]
Thanks for taking up this issue @KazushiR . There are some changes that need to be made:
1. Please make sure you're taking issues off the '**Prioritized backlog**' and not the '**New issue approval**' column. This issue was still in the new issue approval but has since been approved for the backlog.

2. Make sure to leave the template headings in the record. Follow the example below with the headings in bold and information without any styling. [Example](https://github.com/hackforla/website/wiki/DR:-Use-an-existing-add-on-converter-called-Docs-to-Markdown)

3. Add a space in between DR: and the title

4. Make sure to add the record to the main page. [Link](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted)
      - Click edit
      - Add the link below the last DR.

Sorry for the hold up! Was not getting notified for the mention. I went ahead and unchecked what needs to be fixed. Go ahead and check them off when finished with the above and I'll close up the issue! Let me know if you have any questions.

**Comment by KazushiR** [comment]
@hackforla/website-merge @plang-psm Hello, I believe I have updated the changes. Please let me know if there are any more issues with my documentation.

**Comment by plang-psm** [comment]
Great work @KazushiR ! The DR looks great and I will be closing this issue as a result.
