### ISSUE TITLE
Figure out how include master calendar on hackforla.org + meeting times on project pages

### ISSUE THREAD

**Issue by cnk** [hackforla/website#385]
Now that we are not meeting in 3 on site hack nights, we need to let everyone know when the teams are meeting to coordinate work.  Wish list: 

- [ ] Master calendar showing all meetings of Hack for LA teams
- [ ] Times for team meetings on individual project pages
- [ ] "Add to my calendar" link for each meeting

**Comment by cnk** [comment]
Create ical files for each meeting time for a team. Info we need for each ical file:

- Project name
- optional subproject name (some teams may have different meetings for front end, back end, etc)
- date/time/repeat
- zoom or other link

**Comment by KianBadie** [comment]
Mock up:
![Screenshot from 2020-03-22 10-54-06](https://user-images.githubusercontent.com/18221058/77256444-88a30500-6c2b-11ea-887b-bf467b8717c7.png)

Right now, the online meetings list uses the same id/styling rules as the "#open-roles" section. The changes we made to make it look different from the Open Roles section is to make the column-count: 1. In addition, there is a css class/id that adds the styling to the bullet-ed list labeled "#open-roles li:before {}". A quick fix was to remove the "content" property of that class. However, I am guessing a better option would be to either create a new css class for the meetings lists that creates a new styled list of it's own. Or to continue having the meetings list inherit the #open-roles class, and add another class that removes/changes the desired styling. 

My vote goes for creating a new css class that creates a new styled list of it's own.

**Comment by yulia-kh** [comment]
@ExperimentsInHonesty What do you think about this as a first step for the master calendar? The owner of the calendar can subscribe for other calendars and include them in the iframe that google provides for us. Here is my calendar embeded in hfla website. Also, do you want to open it in a new page?
<img width="1217" alt="Screen Shot 2020-03-24 at 9 54 06 AM" src="https://user-images.githubusercontent.com/13112628/77457879-8c18c680-6dba-11ea-9d01-b3e713fb5244.png">

**Comment by ExperimentsInHonesty** [comment]
@yulia-kh we are going to hold on the each team producing their own calendar for now, but holding this in reserve, if other automated solutions don't turn out to be feasible.

**Comment by ExperimentsInHonesty** [comment]
working with VRMS team on calendar.  Waiting for data model from @sarL3y 
template so far
Identification: (this is a number of the project)
Start Time: YYYY-MM-DDTHH:mm:ss.sssZ
End Time: YYYY-MM-DDTHH:mm:ss.sssZ
Meeting Name: 
Meeting Description: 
Meeting Type:
Meeting Location: (online, DTLA, SM, soLA)
Zoom Link:

**Comment by ExperimentsInHonesty** [comment]
@yulia-kh @cnk will go to the Monday night VRMS meeting to talk calendar

**Comment by ExperimentsInHonesty** [comment]
Matt was out last week for a family emergency.  He is back.  Can team members @yulia-kh @cnk will go to the Monday night VRMS meeting to talk calendar?

**Comment by ashlingam** [comment]
1. Progress - Yulia/Cynthia participated in VRMS meeting. Still need further clarity on data model (as of now, appears focused on volunteers). CMS may be a secure way to enable dynamic update of Project Team Meetings page by project leads.
2. Blocks - Data model questions
3. Availability - Saturday anytime
4. ETA - ~2 weeks

**Comment by ExperimentsInHonesty** [comment]
Rachel W @sarL3y are working on a data model.  I have added the model above as a comment on the following doc: https://docs.google.com/drawings/d/1-y4xhfKoM0Ic5v7YhdPMAknxkq_VONIq7uBnTF6nwYM/edit

**Comment by ExperimentsInHonesty** [comment]
Asked Matt and Rachel to join us.  If not, we are moving ahead with a model to implement redesign of team meeting display.

**Comment by ExperimentsInHonesty** [comment]
@sarL3y posted in slack

Hey Website team! I've got an endpoint for you: https://vrms.io/api/recurringevents
I'll check in with you all at the meeting tomorrow morning, but if there's anything you need in the meantime, hit me up here.

<img width="558" alt="VRMS API - Recurring Events" src="https://user-images.githubusercontent.com/37763229/81506134-181e7900-92a9-11ea-8394-cba5ab32eb54.png">

**Comment by sarL3y** [comment]
### Next Steps
- [ ] @sarL3y will add a sorting function to send requested data in order by date
- [ ] Website team will begin consuming endpoint to see if all requirements are met

**Comment by ruben1s** [comment]
Here is the code I am trying @sarL3y 
![Screenshot from 2020-05-12 13-40-47](https://user-images.githubusercontent.com/33906590/81743287-48574a80-9456-11ea-98b1-abfad1ab8d22.png)
![Screenshot from 2020-05-12 13-40-55](https://user-images.githubusercontent.com/33906590/81743293-49887780-9456-11ea-9b15-911560715d40.png)

I think we need you guys to add CORS headers that allows all because we cant consume data with no-cors set up.

**Comment by cnk** [comment]
@ruben1s commit https://github.com/hackforla/website/commit/a4b5ca5f57a5cda9bb464d1f8d8bd9a4e8b9b198 got this data feed filling in the project meetings summary page. Now we need to figure out how to do the same / similar thing and just display the meetings for the specific project.

**Comment by ExperimentsInHonesty** [comment]
@cnk and @ruben will look at making github action for setting nighty pull of calendar data to use as the placeholder for team meeting page, that then gets replaced by live data that is good.  Educate @ExperimentsInHonesty @ye-susan  on what kind of data validation we are doing on the vrms data when it comes in.

**Comment by cnk** [comment]
Next step: @ruben1s to create a GitHub Action for saving https://www.vrms.io/api/recurringevents as _data/project-meetings-from-vrms.json

After that, we will move on to using that data to add next meetings to individual project pages.

**Comment by ExperimentsInHonesty** [comment]
@ruben1s 
1. Progress none yet
2. Blocks: @cnk can help with github actions, @ye-susan should be on that discussion.
3. Availability: M-F 8-1pm
4. ETA: early this week.

**Comment by ExperimentsInHonesty** [comment]
@ruben1s to make a pull request to display 
project.name + description. and make sure link is only on the project.name.

example see above https://github.com/hackforla/website/issues/385#issuecomment-626361698
