### ISSUE TITLE
Migration to Google Analytics 4

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#3863]
### Overview
Since Google's Universal Analytics (UA) will stop processing hits on July 1, 2023, we need to migrate from UA to Google Analytics 4 (GA4) so that our website will continue to gather site usage data.

### Important 
**We need to export our Universal Analytics (UA) data by December 31, 2023 in order to have that record for the future.**
From [Universal Analytics is going away](https://support.google.com/analytics/answer/11583528?hl=en)
- > After July 1, 2023, you'll be able to access your previously processed data in your Universal Analytics property for at least six months. We know your data is important to you, and we strongly encourage you to [export](https://support.google.com/analytics/answer/11583528#export) your historical reports during this time. 

### Details
- From [[UA→GA4] Automatically created Google Analytics 4 properties](https://support.google.com/analytics/answer/12938611#zippy=%2Cin-this-article),
 > We strongly recommend you [manually migrate your Universal Analytics settings to GA4](https://support.google.com/analytics/answer/10759417). If you do nothing, a new GA4 property will automatically be created for you, and your Universal Analytics configurations will be copied to the new GA4 property. Not all UA configurations have an obvious GA4 counterpart, and the automated process might not make the same choices as you would.

### Action Items
- [x] You must be a Technical Lead or Merge Team member to self-assign this issue
- [x] You will need access to 
    - [x] 1) Hack for LA's 1Password and
    - [x] 2) the `webadmin@hackforla.org` account sign-in information within Hack for LA's 1Password.
    - [x] 3) [HfLA Website Admin Google Drive](https://drive.google.com/drive/folders/0APij3x0zmh7aUk9PVA)
  - [x] If you do not have access to any of the above, you will need to ask a Product Manager on the Website Team for access.
- [x] Depending on when you work on this issue, Google may have already automatically migrated us to GA4. Check if the migration has happened and do the appropriate set of Action Items below.

#### If migration from UA to GA4 has **not** happened yet
- [x] Research what needs to be done to migrate to GA4, including (but not limited to):
  - [x] What changes may happen with the migration?
  - [x] With the migration from UA to GA4, are any features deprecated?
- [x] In a new comment below, write up your research findings
- [ ] Discuss your findings with other dev leads (Merge Team members and Technical Leads) and the Product Managers at a meeting
- [ ] Get approval from a Product Manager to proceed with the migration
- [ ] After receiving approval from a Product Manager, migrate from UA to GA4
- [x] Make sure the website's analytics work properly after the migration. According to [Google's documentation](https://support.google.com/analytics/answer/9744165#zippy=%2Cin-this-article), 
  > It can take up to 30 minutes for data to begin appearing in your new GA4 property.
  > 
  > To verify that data is being collected, browse your website, then select Realtime from the report navigation. You should see activity in the [Realtime report](https://support.google.com/analytics/answer/9271392)
- [ ] After GA4 has been set up properly, export all UA analytics data in every format described in [Ways to export Google Analytics data](https://support.google.com/analytics/answer/11583528#export&zippy=%2Chow-can-i-export-data-from-my-universal-analytics-property) and place it in the [Google Universal Analytics Data folder](https://drive.google.com/drive/folders/0APij3x0zmh7aUk9PVA) in the HfLA Website Admin Google Drive.

#### If the migration from UA to GA4 **already** happened
- [ ] You'll need to see what configurations and properties we had before in UA and make sure the GA4 is set up to function the same way the UA did in terms of the analytics we gather.
- [ ] Research:
  - [ ] What changes happened with the automatic migration?
  - [ ] With the migration from UA to GA4, were any features deprecated?
  - [ ] What changes (if any) to the configurations and properties need to happen to the GA4 so it functions the same way the UA did in terms of the analytics we gather?
- [ ] In a new comment below, write up your research.
- [ ] Discuss your findings with other dev leads (Merge Team members and Technical Leads) and the Product Managers at a meeting
- [ ] Get approval from a Product Manager to proceed with changing configuration and properties for the GA4 (if changes are needed)
- [ ] After receiving approval from a Product Manager, proceed with changing the configuration and properties for the GA4 (if changes are needed)
- [ ] Make sure the website's analytics work properly after making changes to GA4. According to [Google's documentation](https://support.google.com/analytics/answer/9744165#zippy=%2Cin-this-article), 
  > It can take up to 30 minutes for data to begin appearing in your new GA4 property described in [Ways to export Google Analytics data](https://support.google.com/analytics/answer/11583528#export&zippy=%2Chow-can-i-export-data-from-my-universal-analytics-property)
  > 
  > To verify that data is being collected, browse your website, then select Realtime from the report navigation. You should see activity in the [Realtime report](https://support.google.com/analytics/answer/9271392)
- [ ] After GA4 has been set up properly, export all UA analytics data in every format and place it in the [Google Universal Analytics Data folder](https://drive.google.com/drive/folders/0APij3x0zmh7aUk9PVA) in the HfLA Website Admin Google Drive.

### Resources/Instructions
- Here is a starting point for your research: [[GA4] Make the switch to Google Analytics 4](https://support.google.com/analytics/answer/10759417?ref_topic=10737980?utm_campaign%3D2022-q1-gbl-all-gafree&utm_source=google-growth&utm_medium=email&utm_content=ga-deprecation-comm-ua-only)
- [Google Universal Analytics Data folder](https://drive.google.com/drive/folders/0APij3x0zmh7aUk9PVA) in HfLA Website Admin Google Drive
- This is where our current GA code lives https://github.com/hackforla/website/blob/gh-pages/_includes/head.html
- https://github.com/hackforla/website/blob/gh-pages/_layouts/redirect.html
- search for googletagmanager https://github.com/search?q=repo%3Ahackforla%2Fwebsite+googletagmanager&type=code

**Comment by JessicaLucindaCheng** [comment]
- [x] Ask how Bonnie wants historical data to be saved and used
- [x] Add Action Item to export data from Google Analytics
- [x] Add info about this email: [Hack for LA Mail - We’ll soon configure Google Analytics 4 for you.pdf](https://github.com/hackforla/website/files/10670957/Hack.for.LA.Mail.-.We.ll.soon.configure.Google.Analytics.4.for.you.pdf)

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty I know you want data to be preserved when we migrate from Universal Analytics to Google Analytics 4. 
1. How do you want this data to be preserved? Ans: Export all the data in every method after Google automatically migrates us over
    - Notes:
      - > After July 1, 2023, you'll be able to access your previously processed data in your Universal Analytics property for at least six months. We know your data is important to you, and we strongly encourage you to [export](https://support.google.com/analytics/answer/11583528#export) your historical reports during this time. 
      - [Ways to export Google Analytics data](https://support.google.com/analytics/answer/11583528#export&zippy=%2Chow-can-i-export-data-from-my-universal-analytics-property)
2. How is this data going to be used? Ans: To be able to do a comparison with the new homepage when launched and the previous one.

**Comment by JessicaLucindaCheng** [comment]
Blocker:
I wasn't sure where the exported data should go. So, I created a folder [Google Universal Analytics Data folder](https://drive.google.com/drive/folders/0APij3x0zmh7aUk9PVA) in HfLA Website Admin Google Drive and said to put the data there because I have concerns about data privacy if we put it in the regular drive. I'm wondering if it should go somewhere else, such as the personal Google Drive of the webadmin@hackforla.org account.

edit: In Admin drive because nothing should ever be in a personal drive of one of the HfLA Google Accounts - just in case the accounts change or are deleted.

**Comment by JessicaLucindaCheng** [comment]
@jdingeman @ExperimentsInHonesty I know we had discussed waiting for Google to migrate us over automatically to Google Analytics 4 but I don't know how long we have to wait until the migration; Google said they would start in March 2023 but didn't give us a date when they expect to complete automatically migrating all accounts. Thus, I decided to make this issue so it would work for both if the automatic migration already happened and if it didn't happen yet because even with the automatic migration, we still might need to do some manual changes to configurations and properties according to Google:

- From [[UA→GA4] Automatically created Google Analytics 4 properties](https://support.google.com/analytics/answer/12938611#zippy=%2Cin-this-article),
 > We strongly recommend you [manually migrate your Universal Analytics settings to GA4](https://support.google.com/analytics/answer/10759417). If you do nothing, a new GA4 property will automatically be created for you, and your Universal Analytics configurations will be copied to the new GA4 property. Not all UA configurations have an obvious GA4 counterpart, and the automated process might not make the same choices as you would.

**Comment by t-will-gillis** [comment]
Availability: 5/19-5/25 daily
ETA: tbd

**Comment by t-will-gillis** [comment]
Update: I have a blocker 

While I now have access to the password for the `webadmin@hackforla.org` account, the sign in for the 'Admin' link to Google Analytics also requires a Secret Key. Unless I am missing something, I believe that I need the key to continue on to Google Analytics.

**Comment by JessicaLucindaCheng** [comment]
@t-will-gillis 
1) Please move this issue to the In Progress column
2) Did you get an answer to your blocker?

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis I found a spreadsheet that had some other codes in it.  I assumed they were old passwords, but I think one of them might be the key.  Can you review them in the Google Analytics 1 password record and see if any of those work for you?

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis Before you do any conversions, can you download the stats by year.  See this for an example, but obviously it would be better as a csv.

[PDF of stats per page for 2021](https://drive.google.com/file/d/1aIF3v2gYyTgiZIhCm8SGAwRhoHSLyIRp/view) (printout from Google Analytics)

**Comment by ExperimentsInHonesty** [comment]
Got this email in webadmin@hackforla.org

Your Google Analytics account needs immediate attention. Our next-generation measurement solution, Google Analytics 4, is replacing Universal Analytics. Starting July 1, 2023, standard Universal Analytics properties will stop processing new data. If you use Google Ads, this means that any Universal Analytics data that you're using for ad campaigns will start to degrade and your ad performance may be impacted. We strongly recommend that you follow our [step-by-step guide to make the switch to Google Analytics 4](https://support.google.com/analytics/answer/10759417?utm_campaign=2023-q2-gbl-all-gafree&utm_source=google-growth&utm_medium=email&utm_content=Wave4_Email8_SL2) as soon as possible

[SET UP GOOGLE ANALYTICS 4](https://notifications.google.com/g/p/ACUgQrFiapu7DiFWu7Aqm6rv9GVjeMUyxXaMX5tX-IhKBt-Aoav_VOaQEBNIbi2bikjnuh6JItJL8n7IIlkBTRyFZiMFvrR28hQYDCWkmWdQh6AIM-W17eq4VzL6GtOyCCkp36uoc8_PD3Ds7YzFa9esFOSbQH1gez9uy6UpBD1BO4fMv2Af7D9PiqDW0_MvdRv1K179TZwgImXVxy5lVrM8IkZKfZ_O3rMY90pvP7ekdxeuiF8ALOHDEPqtGRul27ASOB7jmlWXkXojqqGIUqoSvWQDMk4Tk1KFO-Bx75CyyyXSnoOmr1tQIMW5IMpaWZYVdxVLiQcqKlREHy9ISCHhWMpak6gTTmC00sACphDNlbSCGqtHa5KhAbOPZJxfIs8NPpkreygOpHSWCUqh0lOWIkK3SgyfbhTiJdoogxYg9lfI2zyggOYZ7zt60mvxBHM)
 

To build data and continuity in Google Analytics 4, it is essential that you start your setup now. This will allow you to start collecting the right data in Google Analytics 4 for your unique needs, and help avoid disruption to any Google Ads campaigns still relying on Universal Analytics conversions and audiences.
 
Unless you've opted out, we've already configured or soon will configure a Google Analytics 4 property for you with some basic features, including certain goals and Google Ads links moved over from your Universal Analytics configuration. But parts of your existing Universal Analytics setup, including custom dimensions and metrics, cannot be moved. Customizing your Google Analytics 4 setup now will ensure you collect the right data for the specific conversions, audiences, and other Analytics data that you care most about, so you can continue to measure your most valuable actions and run more efficient ad campaigns.
 
[For what to expect for Universal Analytics next month, visit the Help Center](https://notifications.google.com/g/p/ACUgQrEhzEKz7Gnu_yMI5B3W9vWfDsQNcnDMprUvzikiqGDXM6BdtIYbis05RQjuqSs3ylElhhynu88k4Y41R_k2bP6UoJJa1YDTVJAkafO5BJuzOB-2EIq8VhwBns9iygzJ-pDAoFSCJcNSGTcMEg25awwj-dMp41N-ZNakhpYsSoNjY2dl6Rvid3hFaVfKYMp7dbGHTN9HKga8lIJy3rlTLyTMpDDnZP-J1j5PrceWcyYmHHn-MUHwRTB-KagxkxSRZ-wZD8FpWjQbgb8ub5dJhpLshhGIEh3TVmLx48s9VpCk9m9nrxZ3S7Qi0bfomfa3ymqLf3KSzpBDRfPMtMzrCz3fxg1FR0JDHzxlCP8DDWWI3njItIcMym-X9Y8uTnix0R_g). - you have to be logged into webadmin@hackforla.org to see this
 
See you online,
The Google Analytics Team

**Comment by t-will-gillis** [comment]
> @t-will-gillis Before you do any conversions, can you download the stats by year. See this for an example, but obviously it would be better as a csv.
> 
> [PDF of stats per page for 2021](https://drive.google.com/file/d/1aIF3v2gYyTgiZIhCm8SGAwRhoHSLyIRp/view) (printout from Google Analytics)

@ExperimentsInHonesty which Google Drive folder is this linking to? It says I don't have access through '339.colorado.dev@gmail.com'- I'll send a request for access

**Comment by t-will-gillis** [comment]
- I have begun downloading numerous reports from Universal Analytics, 2020, 2021, and 2022 in both PDF and csv formats. 
- On the day of migration, I plan to download the remaining report for 2023 and for all time up till that date.
- I looked at whether the UA data can simply migrate to GA4- short answer is no:

> Can You Migrate Your Data To GA4?
> The primary concern is whether GA users can transfer or migrate Universal Analytics data into their Google Analytics 4 property. Unfortunately, you cannot migrate your data to GA4, and it’s not likely to be a feature we’ll see added in the coming months. Migrating your data to GA4 is not likely to be a feature because the two versions use completely different data models.
> I spoke with [Charles Farina](https://twitter.com/CharlesFarina), Head of Innovation at Adswerve, and he explained that: “It is the difference in schema and dimension definitions/calculations that make merging the data not possible.” Schema refers to how the data is organized and the language used to ensure compatibility. Essentially it is the blueprint. He explains you can see the differences in schema well when comparing the BigQuery integrations for UA and GA4.
>  “The [UA export](https://support.google.com/analytics/answer/3437719?hl=en) is sessionized, meaning each row in the export is a session, and every interaction is nested in that row. The [GA4 export] (https://support.google.com/analytics/answer/7029846?hl=en) is very different, where each row is the event (interaction) itself,” shared Farina.
> Another key reason is how dimensions and metrics are defined and calculated in GA4 compared to UA. 
> Google has a great [support page](https://support.google.com/analytics/answer/9964640?hl=en#zippy=%2Cin-this-article) that goes over many of these. For example, let’s look at one of the most common KPIs, “Users.” Universal Analytics reports on Total Users or all users, while GA4 focuses on Active Users or users that have visited the website at least once in the past 28 days. Even if we could migrate UA data to GA4, it would be like comparing apples to oranges. If you’re wondering why this change is happening, you’ll find the answer in our article, [Google Analytics 4 FAQs: Stay Calm & Keep Tracking]
https://www.searchenginejournal.com/google-analytics-4-faqs/446167/  


> What’s the difference between UA and GA4?
Google Analytics 4 doesn’t just offer more of what Universal Analytics offers. It’s built differently to align with current and future needs for reporting and privacy. Here are some of the differences and benefits.
•	Event-based: Universal Analytics is session-based, while GA4 is event–based. In other words, the ability to track events like button clicks, video plays, and more is built in with GA4, while this requires advanced setups in UA. This comes from the premise that page views aren’t the sole important metric.
•	Cross-device tracking: UA was built around desktop web traffic, while GA4 gives businesses visibility into the customer journeys across all of their website and apps.
•	Machine learning: GA4 uses machine learning technology to share insights and make predictions.
•	Privacy-friendly: UA data relies heavily on cookies, GA 4 does not.
 > [Click to enlarge](https://www.wordstream.com/wp-content/uploads/2022/03/UA-vs-GA4.png)
> You can also read [Google’s explanation of UA vs GA4 here](https://support.google.com/analytics/answer/9964640?hl=en#zippy=%2Cin-this-article).

**Comment by t-will-gillis** [comment]
> Note: As of 6/30/23 at 9 pm, it appears that since we made the changes and linked the new GA4 property to the UA property, we are already collecting data _**and we might not need to make any additional changes to the website.**_  

### Goal conversions
The previous goals (i.e. Donate button, Government Survey button, etc.) have been converted to GA4 format. Post migration will confirm these are functioning.

###  Google Site Tag 
These are all files that are using the **Global Site Tag | gtag.js | `UA-167506267-1`** with 'googletagmanager'. 

- [‎_includes/head.html](https://github.com/hackforla/website/blob/gh-pages/_includes/head.html)
- [ _layouts/redirect.html](https://github.com/hackforla/website/blob/gh-pages/_layouts/redirect.html)

Per Google, it appears that we can continue using the existing `gtag` :

> [GA4] About connected site tags
> This article is for website owners who are setting up a Google Analytics 4 property and who are given the option (by the GA4 setup wizard) to reuse their existing Universal Analytics tagging.
> If your Universal Analytics property uses [gtag.js](https://support.google.com/analytics/analytics/answer/10220869) or [analytics.js](https://support.google.com/analytics/analytics/answer/10268458) (including if analytics.js was deployed through a tag management system like Google Tag Manager), the GA4 Setup Assistant wizard can reuse your existing tagging (i.e., the tag being used by your Universal Analytics property). This tag reuse saves you from having to add the tag manually to your web pages and is made possible via a feature called connected site tags.

The Google docs give many options for . need to replace:
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-167506267-1"></script>
<script>  
  window.dataLayer = window.dataLayer || [];   
  function gtag(){dataLayer.push(arguments);}  
  gtag('js', new Date());  
  gtag('config', 'UA-167506267-1'); 
</script>
 <! -- End Google tag -->
```
by adding new GA4 tag config after the UA tag config:
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-167506267-1"></script>
<script>  
  window.dataLayer = window.dataLayer || [];   
  function gtag(){dataLayer.push(arguments);}  
  gtag('js', new Date());  
  gtag('config', 'UA-167506267-1'); 
  gtag('config', 'G-QNFX2EYZC8');
</script>
<! -- End Google tag --> 
```
This is the **_failsafe_** if the above addition of the new gtag does not function as intended for whatever reason, there is the option to replace the gtag completely with GA4 tags:
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-QNFX2EYZC8"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-QNFX2EYZC8');
</script>
```

### Google Tag Manager

We have four additional files referencing **Google Tag Manager | gtm.js | `GTM-PMQK7VL`:** 
- [pages/credits.html](https://github.com/hackforla/website/blob/gh-pages/pages/credits.html)  
- [pages/events.html](https://github.com/hackforla/website/blob/gh-pages/pages/events.html)
- [pages/projects-page.html](https://github.com/hackforla/website/blob/gh-pages/pages/projects-page.html)
- [pages/projects-check/html](https://github.com/hackforla/website/blob/gh-pages/pages/projects-check.html)

Note: Per [analyticsmania](https://www.analyticsmania.com/post/how-to-install-google-analytics-4-with-google-tag-manager/), it appears that Google Tag Manager does not need to be updated when switching from UA to GA4. _**Will need to verify after migrating to GA4.**_ Therefore, the embedded code will not change:
```
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PMQK7VL" height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->
```
Finally, the Google tag and Google Tag Manager should be reversed so that Google tag is first.

**Comment by t-will-gillis** [comment]
@ExperimentsInHonesty @JessicaLucindaCheng 

Please see the above explanation of the changes that may need to be made. The GA4 property is created and the goals are converted already. The GA4 property is connected to the existing UA property. The Google Tag Manager does not need to be updated.

> Note: As of 6/30/23 at 9 pm, it appears that with the changes and linking the new GA4 property to the UA property, we are already collecting data _**without making changes to the website.**_  

<br>
![Migration_015](https://github.com/hackforla/website/assets/40799239/2864aeae-1857-4ccc-9fc7-71298f3e7252)
<br>
From my research, I believe these are the important things to note:

1. UA collects data per session, GA4 data is per event. The UA data is incompatible/ not transferable to GA4 for this reason. 
I have been saving PDFs and csvs of all data that seems relevant to me, but I don't think I am saving every possible query of the data. **Therefore if there is any data that is very important, please let me know so that I can be sure that I am saving it.** FYI- from what I am reading I believe UA data will be available for a few months still but I will finish saving file before migrating.<br>
![UA-vs-GA4](https://github.com/hackforla/website/assets/40799239/b4200251-9db2-4647-a4cc-d931cd681a43)<br>
2. From what I have researched, we should be able to migrate most if not all of our current settings because we don't have that many. Using the GA4 Setup Assistant, we are able to monitor that new properties are created in GA4 based on existing properties that we currently have with Universal Analytics.
  a. This includes the Google Site Tag referenced above `UA-167506267-1`  
     i. I have screen shots of all settings to verify that the migration tool is creating a similar setting.
     ii. It appears that GA4 will migrate most if not all of our current settings. In HfLA it appears the most developed analytic settings are for Goals. GA4 has a Goals Migration Tool to try to emulate the same kinds of data collection.  
     iii. Again, there will be differences in future data collection because GA4 is measuring per event while UA is measuring per session.  
b. The Google Tag Manager referenced above `GTM-PMQK7VL` will also migrate with GA4.

**Comment by t-will-gillis** [comment]
-	GA4 appears to be functioning as we intended based on previous settings in UA- after doing the setup steps in GA4 it appears we are up and running without the need to change any code
-	More details:
  o	We have existing Google tracking as ‘Google Site Tag’ in `_include/head.html` and `_layouts/redirect.html`. Although there is a new GA4 code available, the previous UA code is tied to GA4 without us needing to make any changes.
  o	The existing tracking from ‘Google Tag Manager’ (present in 5 files) is reusable by GA4, thus no changes here either. 
  o	The previous UA ‘Goal’ settings have been converted to a GA4 format/ event and appear to be functioning.
  o	There is an associated PR #4904 that:  
    a.) adds html comments,  
    b.) reformats the Google tags for readability only, and  
    c.) switches the order of the ‘Google Site Tag’ and ‘Google Tag Manager’ per the recommendation of Google. 

HOWEVER: since everything appears to be working, we might not want or need to make these changes.
