### ISSUE TITLE
Update Project Profile: 311-Data (Change Getting Started link)

### ISSUE THREAD

**Issue by johnr54321** [hackforla/website#387]
### Overview

Dependency: [Issue 18 on PM Board](https://github.com/hackforla/product-managment/issues/18)

### Overview
Update the following fields for your project. These updated fields will then be updated to be shown on the website.

### Action Items
- [ ] Update Getting started link to go here: https://github.com/hackforla/311-data/wiki/Joining-the-311-Team

**Comment by ExperimentsInHonesty** [comment]
@johnr54321 please go to the getting started here: https://www.hackforla.org/projects/civic-opportunity-project
we can take the one sheet that you make into a pdf and put it here on the page under overview.  Please attach pdf in a comment.

**Comment by alexandrastubbs** [comment]
@johnr54321 any updates on this? Haven't seen any progress come through yet.

**Comment by johnr54321** [comment]
I had put it on the ticket you have for the one sheets for all projects.  Will provide a link when I get to a desktop.

**Comment by johnr54321** [comment]
@ExperimentsInHonesty I'm hearing a few different things.  Do you need my 1 sheet?  It's on the ticket with all the 1 sheets.  If you want to use the hackforLA sign up link and use our readme for the link on our site, then that is ok now that we have instructions to tell people to contact me, I'll use that link.  We should have a link saying who the leads are and how to contact them.  Anyways, I'm a little confused on the ask here.  Originally, I had made this ticket in March because our website didn't have any of this. I do think it's a little confusing as is, because we should make the links to the leads, rosters, etc. available so they can click directly and do as much of the sign up process themselves as possible.  Feel free to close this if no action is needed now.

**Comment by ExperimentsInHonesty** [comment]
@johnr54321 This doc that you listed on the one sheet, is the doc we made for the city: https://docs.google.com/document/d/1vC9TH4VAX20IKFghlUkZfsurbA4QOHyRHBYp5uRzJKA/edit?pli=1

It’s not the 1 sheet that I need.  The one sheet I need is the one where it says what the 6 months deliverables are, history, accomplishments, etc.    If you look at the ones for the other teams you will see what I mean: https://github.com/hackforla/product-managment/issues/3 (edited)

**Comment by alexandrastubbs** [comment]
@johnr54321 any progress on this?

**Comment by ExperimentsInHonesty** [comment]
I have been unable to get John's attention on this.  Going to bring it up at the next product-management meeting

**Comment by alexandrastubbs** [comment]
Per dependency at the top, currently waiting for Bonnie to update [one-sheeter](https://docs.google.com/document/d/1WgTN4kTT2LNoNxq7AHp5tOl9RhMIBTjqYonPzEXPmkE/edit) before we can move forward with this issue.

**Comment by nielseny** [comment]
Bonnie will assign to new 311 PM after project interviews/updates.
