### ISSUE TITLE
Develop new Google Apps Script function to create GitHub issues for reporting problems

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#3881]
### Dependency
- [x] #3641 
- [x] #4134
- [x] #5746

### Overview

We need to develop a function to be used to create GitHub issues alerting developers of problems in the execution of Wins Apps Script

### Action Items
- [ ] Request VIEW access from the dev lead/merge team member, to the `Wins Form Admin Guide`, the `Wins-form (Response)` Sheet, and the `gh-requests` Doc.   
- [ ] Read the Wins Apps Script Development Guide[^1] including the section "Testing Wins in a test repository" describing the process for testing in a test repository.  Using those instructions, create a test environment and update your copy of gh-requests to work with your test repository.  
- [ ] In the code behind your copy of gh-requests, add a new function to create a GitHub issue representing a bug report and to add the new issue to the Project Board.  The function should accept as parameters:  repository, issue name, issue body, and project board column. 
- [ ] For testing, invoke the new function from with main()
- [ ] Demo the code to the technical lead and team

### Resources/Instructions

Resources/Instructions
[Google Apps Script](https://developers.google.com/apps-script/overview)
[_wins-data file](https://github.com/hackforla/website/blob/gh-pages/_data/external/_wins-data.json)
[wins page JS](https://github.com/hackforla/website/blob/gh-pages/assets/js/wins.js)
[Response sheet](https://docs.google.com/spreadsheets/d/1fXmYrmNtrgdzkM_odGIRbSwdaea3yS0cTLCJUzZ6Sc0/edit#gid=1301054877)
https://github.com/hackforla/website/issues/2901#issue-1153764909
[^1]:[Wins Apps Script Development Guide](https://github.com/hackforla/website/issues/4134#issuecomment-1741851926)

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe please add this project to the project board

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe this was in the icebox, but there is no dependency.

**Comment by roslynwythe** [comment]
> @roslynwythe this was in the icebox, but there is no dependency.

- @ExperimentsInHonesty I added a dependency on #3641,  however I am having second thoughts about this retaining this issue, because we have seen no evidence that the "out of sync" problem still exists; it seems likely that it was fixed already by luke-karis in #2901.  Unfortunately we could find no documentation of his work and the code is not in source control so we cannot be certain.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe dependencies are cleared.  Please review the issue and determine if it's ready for prioritization.

**Comment by ExperimentsInHonesty** [comment]
RW said

> I am having second thoughts about this retaining this issue, because we have seen no evidence that the "out of sync" problem still exists; it seems likely that it was fixed already by luke-karis in https://github.com/hackforla/website/issues/2901. Unfortunately we could find no documentation of his work and the code is not in source control so we cannot be certain.

@roslynwythe If your last comment still stands, please close this issue as unplanned.
