### ISSUE TITLE
Mark 100 Automations project as On Hold

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#3892]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We want to mark the 100 Automations project as `On Hold` so that 
- our website accurately reflects the status (Active, Complete, or On Hold) of our projects, 
- and visitors to our website can know the status of our projects.

### Action Items
- [x] In `_projects/100-automations.md`, change the status for 100 Automations from
  ```
  status: Active
  ```
  to
  ```
  status: On Hold
  ```
- [x] Ensure that the `On Hold` status is displayed properly on the [projects page](https://www.hackforla.org/projects/) and [100 Automations page](https://www.hackforla.org/projects/100-automations)

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/100-automations.md`
- [hackforla.org, Projects page](https://www.hackforla.org/projects/)
- [hackforla.org, 100 Automations project page](https://www.hackforla.org/projects/100-automations)
- Click on the link to see the source file code: https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md?plain=1
- This issue is part of an epic: #3891

**Comment by KazushiR** [comment]
Availability for this week: Flexible
My estimated ETA for completing this issue: 4 hours
