### ISSUE TITLE
Mark Civic Opportunity Project as On Hold

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#3893]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We want to mark the Civic Opportunity project as `On Hold` so that 
- our website accurately reflects the status (Active, Complete, or On Hold) of our projects, 
- and visitors to our website can know the status of our projects.

### Action Items
- [x] In `_projects/civic-opportunity-project.md`, change the status for Civic Opportunity Project from
  ```
  status: Active
  ```
  to
  ```
  status: On Hold
  ```
- [x] Ensure that the `On Hold` status is displayed properly on the [projects page](https://www.hackforla.org/projects/) and [Civic Opportunity Project page](https://www.hackforla.org/projects/civic-opportunity-project)

### Resources/Instructions
- Directory to find the page in once you have it in your IDE: `_projects/civic-opportunity-project.md`
- [hackforla.org, Projects page](https://www.hackforla.org/projects/)
- [hackforla.org, Civic Opportunity project page](https://www.hackforla.org/projects/civic-opportunity-project)
- Click on the link to see the source file code: https://github.com/hackforla/website/blob/gh-pages/_projects/civic-opportunity-project.md?plain=1
- This issue is part of an epic: https://github.com/hackforla/website/issues/3891

**Comment by mjh-projects** [comment]
i. Availability:  - Evenings after 6PM and on weekend. 
ii. ETA: (When do you expect this issue to be completed?) Thursday 2/2/2023
