### ISSUE TITLE
Update Project Profile: 311

### ISSUE THREAD

**Issue by EchoProject** [hackforla/website#3900]
### Overview
As a product manager of 311 Data I want my project's details to be up to date on the HackforLA website. As developers, we need to update the 311 Data project's leadership information.

### Action items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the [311-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/311-data.md) file and find the `leadership`variable.
- [x] Add the new team member's `name`, `role`, `slack` link, `github` link, and `picture` to the `leadership` variable
    - [x] Name: Michael Criste
GitHub Handle: mc759
Role: Product Manager
Slack Member ID: U048U430FQV
- [x] Verify the changes by viewing the [311 Data project page](https://www.hackforla.org/projects/311-data) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- 311 Data markdown file: https://github.com/hackforla/website/blob/gh-pages/_projects/311-data.md
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### Related Issues
- Meeting time update submitted by the 311 Data team to VRMS: https://github.com/hackforla/VRMS/issues/1279

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge this is ready for cleanup and priortization

**Comment by MarkWiltberger** [comment]
**Availability:** Daily 10am-6pm ET (7am - 3pm PT)
**ETA:** 02/15/2023 Wed 6pm ET (3pm PT)
