### ISSUE TITLE
ER: Getting Started Page png name inconsistency

### ISSUE THREAD

**Issue by d-perez-8** [hackforla/website#3903]
### Emergent Requirement - Problem
The PNG file names no longer match the numerical steps in the `pages/getting-started.html` page. Steps 2-5 images on the header do not match the png file names. 

### Issue you discovered this emergent requirement in
- #3845

### Date discovered 
2023-01-25

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@Adastros
@MattPereira 

### What happens if this is not addressed
The inconstant file names can lead to confusion when working on them. 

### Resources
- See #3845 after merge on lines 21, 26, 31, 36.
- Step 2 [image](https://github.com/hackforla/website/blob/gh-pages/assets/images/getting-started/step2.png)
- Step 3 [image](https://github.com/hackforla/website/blob/gh-pages/assets/images/getting-started/step3.png)
- Step 4 [image](https://github.com/hackforla/website/blob/gh-pages/assets/images/getting-started/step4.png)

### Recommended Action Items
- [x] Make a new issue
- [x] Discuss with team
- [x] Let a Team Lead know

### Potential solutions [draft]
`./assets/images/getting-started/solidarity.png` to `./assets/images/getting-started/step2.png`
`./assets/images/getting-started/step4.png` to `./assets/images/getting-started/step3.png`
`./assets/images/getting-started/step2.png` to `./assets/images/getting-started/step4.png`
`./assets/images/getting-started/step3.png` to `./assets/images/getting-started/step5.png`

**Comment by MattPereira** [comment]
@d-perez-8 excellent job creating this emergent request issue!

**Comment by MattPereira** [comment]
- Addressing this ER with #3936
