### ISSUE TITLE
Create a Github Action to verify Pull Requests are created by website team members

### ISSUE THREAD

**Issue by MattPereira** [hackforla/website#3906]
### Overview
As developers, we need to ensure that only members of our organization create pull requests to the hackforla / website repository. For this issue, we will add a github action that checks if the pull request creator is a member of the website team.

### Action Items
- [x] Learn how github actions work
- [x] Add a github action that checks if the creator of a pull request is a member of the `website-write` team
    - [x] If the author is not a member of the `website-write` team, close the pull request with this comment:
```
You must be a member of the HFLA  website team in order to create pull requests. Please see our page on how to join us as a member at HFLA: https://www.hackforla.org/getting-started.  If you have been though onboarding, and feel this message in error, please message us in the #hfla-site team slack channel with the link to this PR.
```
 
### Resources/Instructions
- Wiki for writing new GHAs at HFLA: https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions
- Wiki for explaining HFLA GHA architecture: https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions

**Comment by KazushiR** [comment]
i. Availability: Weekdays
ii. ETA: N/A. I am trying to figure out how Github Actions work. Will give weekly updates on my progress.

**Comment by KazushiR** [comment]
Didn't realize this was in a draft file. Will be unassigning myself and moving this back new issue-approval

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty If the GHA finds that a non-member has created a PR, perhaps the GHA should close the PR.  Should I add that action to this issue?

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe how often does it happen?  If its only occasionally, then we should double check them.

**Comment by roslynwythe** [comment]
> @roslynwythe how often does it happen? If its only occasionally, then we should double check them.

You mean double-check in case the GHA action was incorrect and the contributor is in fact a member of Hack for LA?   My main concern is that a bot comment in a PR is not all that visible and it may not come to the attention of the contributor or the merge team, unless we can do something to increase visibility, like make it appear in red or somehow give it an appearance similar to a failed GitHub check or a request for change.

**Comment by ExperimentsInHonesty** [comment]
Agreed.  Let's have it auto close the prs.  Also lets add the same text in the close message on the pr template itself.

https://github.com/hackforla/website/blob/gh-pages/.github/pull_request_template.md

**Comment by roslynwythe** [comment]
> Agreed. Let's have it auto close the prs. Also lets add the same text in the close message on the pr template itself.
> 
> https://github.com/hackforla/website/blob/gh-pages/.github/pull_request_template.md

@ExperimentsInHonesty I updated the issue so that if a pull request is created by a non-member, the PR is closed with a comment.  I'm not sure I understand "Also lets add the same text in the close message on the pr template itself"

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I have created an ER to address the remaining items on this issue (adding it to the pr template)

**Comment by roychan1** [comment]
i. Availability: 8am-5pm
ii. ETA: I am hoping to complete the ticket or at least make significant progress by 1/17 Wednesday.

**Comment by roychan1** [comment]
1. Progress: performing research on GitHub Actions
2. Blockers: I have been preoccupied with other responsibilities
3. Availability: this week
4. ETA: 2 weeks

**Comment by ExperimentsInHonesty** [comment]
@roychan1 You need to give updates every week, or we unassign you from the issue.

**Comment by roychan1** [comment]
> @roychan1 You need to give updates every week, or we unassign you from the issue.

I had been occupied and forgotten to provide updates or reassign the ticket, I apologize about that! I will be resuming my work on this issue and provide updates from now!

**Comment by roychan1** [comment]
1. Progress: continue performing research on GitHub Actions and begin implementing
2. Blockers: I have been occupied with personal matters
3. Availability: 9am-5pm
4. ETA: 1 week

**Comment by roychan1** [comment]
1. Progress: continue performing research on GitHub Actions and begin implementing
2. Blockers: busy schedule
3. Availability: 8am-5pm
4. ETA: 1 week

**Comment by roychan1** [comment]
1. Progress: continue performing research on GitHub Actions and begin implementing
2. Blockers: I have been occupied with work
3. Availability: 9am-5pm
4. ETA: 1 week

**Comment by LRenDO** [comment]
Hi @roychan1! It seems like you've got a lot going on right now which is totally okay. I am going to remove you from this issue for now. If you feel you can complete in the next two weeks feel free to add yourself back. Otherwise, feel free to take on another issue when your availability opens up. Thanks!

**Comment by ajb176** [comment]
ETA: 3 weeks
Availability: Evenings

**Comment by ajb176** [comment]
1. Have a rough idea of what the implementation needs to look like, still need to set up the testing environment and take a few hours to go through the Github API docs.
2. Nothing yet, will update this if necessary over the next two days
3. Will have a lot of time this weekend
4. Hope to finish by the end of this weekend if there are no blockers, latest by next weekend.

**Comment by ajb176** [comment]
Progress: The control flow for verifying team membership seems like it's working properly, still need to test the API call that closes the PR. 
Blockers: None, but testing is time consuming 
Availability: Tuesday evening
ETA: Sunday, if not done by Wednesday

**Comment by ajb176** [comment]
Code is done but due to a personal emergency I most likely won't be able to draft a PR for a few days
