### ISSUE TITLE
Add `image-hero-credit` to public-tree-map.md and create a new credit

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#3922]
### Overview
The `public-tree-map.md` file needs a new `image-credit` field and a new credit in [`data/internal/credits`](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits) since it is a credit to the photographer. 

### Action Items
- [x] Add a new field to [public-tree-map.md](https://raw.githubusercontent.com/hackforla/website/gh-pages/_projects/public-tree-map.md) under `image-hero` called `image-hero-credit` 
```
image-hero-credit: 'Coral tree from City of Santa Monica. Photo by Dave Baiocchi www.studiobaiocchi.net'
```
- [x] Create a new credit yaml file in [`data/internal/credits`](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits)
  - [x] Use this [template](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)

### Resources/Instructions
- [public-tree-map.md](https://raw.githubusercontent.com/hackforla/website/gh-pages/_projects/public-tree-map.md)
- Public Tree Map [project page](https://www.hackforla.org/projects/public-tree-map)
- Coral tree [image hero](https://github.com/hackforla/website/blob/c8a48d402a6472538dba4c279c88a3e947e05fd1/assets/images/projects/public-tree-map-hero.jpeg)
- Coral tree [source](https://www.davebaiocchi.net/santa-monica-urban-forest/r5drejeht8obbydv2c14krzuglraql)

**Comment by jdingeman** [comment]
@ExperimentsInHonesty  Photographer's website does not connect -- not sure what the `title-link` field should be since we can't navigate the website for the source. Should it just be left blank?

**Comment by jdingeman** [comment]
Jessica found the credit: https://www.davebaiocchi.net/santa-monica-urban-forest/r5drejeht8obbydv2c14krzuglraql
But we want to be sure that we actually requested the use for this image so that we don't run into licensing problems. See related issue
- #246

**Comment by ExperimentsInHonesty** [comment]
I am confused about the instructions in this issue.  Please re-review.

**Comment by jdingeman** [comment]
> I am confused about the instructions in this issue. Please re-review.

Corrected the issue to make it clearer. Decided that the credit should be `image-hero-credit` because there is already an `image` attribute that is for a _different_ image.

**Comment by vmaineng** [comment]
Availability: weekday evenings
ETA: 10PM 2/23

**Comment by jdingeman** [comment]
Hello @ftblmagician - please ignore the 2 week inactive message, but please provide us with your ETA and availability for this issue. Thanks! 😄

**Comment by ftblmagician** [comment]
i. Availability: 8AM 3/25
ii. ETA: 3/26

**Comment by ExperimentsInHonesty** [comment]
@ftblmagician I noticed that you skipped good first issue and second and went right to small.  I am unassigning you from this issue. Please pick from this category when your development environment has been fully setup, and you are ready to pick up an issue [Good First Issue](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22good+first+issue%22+label%3A%22role%3A+front+end%22+label%3A%22role%3A+back+end%2Fdevops%22#column-7198257)
