### ISSUE TITLE
Update Project Profile: Guides Team

### ISSUE THREAD

**Issue by edwardsarah** [hackforla/website#3925]
### Overview
As a product manager of the Guides Team I want my project's details to be up to date on the HackforLA website. As developers, we need to update the Guides Team project's leadership information.

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/guides-team.md` file and find the `leadership` variable.
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
    - [x] Name: Sarah Edwards
GitHub Handle: edwardsarah
Role: Product Manager
Slack Member ID: U03KBU16APN
    - [x] Name: Shawn Wong
GitHub Handle: seannwvong
Role: Product Manager
Slack Member ID: U04MXRWPQ64
    - [x] Name: Prakhar Singh
GitHub Handle: designer2209
Role: UI/UX Designer
Slack Member ID: U038R24FU3S
- [x] Verify the changes by viewing the [Guides Team project page](https://www.hackforla.org/projects/guides-team) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [guides-team.md](https://github.com/hackforla/website/blob/gh-pages/_projects/guides-team.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge this is ready for formatting and prioritizing

**Comment by MattPereira** [comment]
@ExperimentsInHonesty when you say "ready for prioritizing" are you instructing merge team to move it into the "prioritized backlog" skipping past the normal `Ready for Milestone` procedure ?

**Comment by jlu9d2** [comment]
Availability: March 3rd through March 5th

ETA: Today, March 3rd
