### ISSUE TITLE
Update Project Profile: Home Unite Us

### ISSUE THREAD

**Issue by randelbrot** [hackforla/website#3929]
### Overview
As developers, we need to ensure all project details are up to date on the HackforLA website. For this issue, we will update the project information for Home Unite Us.

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) in the `_projects/home-unite-us.md` file.
- [x] Update the `techonologies` variable 
    - [x] Remove: auth0
    - [x] Add: Amazon Cognito
- [x] Remove the following person(s) from the `leadership` variable
    - [x] Kristelle Gumaru
- [x] Add the following persons to the `leadership` variable
    - [x] Name: Samuel Kowitch
GitHub Handle: KowDesign
Role: UX/UI Designer
Slack Member ID: U04GYSFB98X
    - [x] Name: Muyin Zheng
GitHub Handle: IndigoYinZ
Role: UX/UI Designer
Slack Member ID: U04HAEEKT29
    - [x] Name: Emily Eldar
GitHub Handle: emeldar
Role: Developer
Slack Member ID: U04BEDM1B2L
- [x] Check the Home Unite Us details page on your local development environment to verify the changes 
- [x] Include a screenshot of your successful changes with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- The Project Markdown File: https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md
- [HFLA Wiki on Project Markdown Files](https://github.com/hackforla/website/wiki/project.md-file-template)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge This is ready for dev.

**Comment by roslynwythe** [comment]
Sorry, I assigned myself and then realized the issue was still in new issue approval board, so I removed my assignment

**Comment by perlaroyerc** [comment]
Availability: M-F 11 to 6 pm ET
ETA: Friday 17

**Comment by ExperimentsInHonesty** [comment]
@brycelednar there were a couple of tickets for homeuniteus open at the same time.  Can you double check the page now, to make sure it has the most recent updates it needs?  https://www.hackforla.org/projects/home-unite-us.  If it's not correct, I think its best to open a [new project update ticket](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D) at this point.

**Comment by randelbrot** [comment]
@ExperimentsInHonesty the page has the updates that it needs - thank you! If any additional updates are needed, I'll create a new project update ticket.
