### ISSUE TITLE
Create project card for Civic Tech Index

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#393]
### Overview
Get the project **Civic Tech Index** added to the website

### Action Items
- [ ] Use the content from this issue: https://github.com/civictechindex/website/issues/7 to create a new project card.  Call the card civic-tech-index.md (no dashes).
- [ ] Insert the screen shots requested in the Notes into this issue
- [ ] Get signoff of on which hero to use, by slacking the hfla-site channel and at mentioning Bonnie

### Notes
There are two hero images in the issue.  One with lots of space around the image of the map and one where it rolls off.  Please try it with each on the project homepage and take screen shots, for us to see.

The content in the last post on the issue, is the most current.

### Resources
local URL to CivicTechIndex project homepage http://localhost:4000/projects/civic-tech-index once you have created a project.md card

**Comment by parkderick** [comment]
Pull request has been created.
