### ISSUE TITLE
Update Project Profile: Expunge Assist

### ISSUE THREAD

**Issue by kelseylondon** [hackforla/website#3931]
### Overview
As a developer, we need to ensure the Expunge Assist project's details are up to date on the HackforLA website. For this issue, we will update the Expunge Assist project's partners, links, and leadership.

### Action items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the [expunge-assist.md](https://github.com/hackforla/website/blob/gh-pages/_projects/vrms.md) file and find the `partners`, `links`, and `leadership` variable.
- [x] Remove the `partner` variable since there are no current partners for this project
- [x] Remove the "Overview" link by deleting the following lines from the project's `links` variable
```
    - name: Overview
      url: '../assets/pdfs/Expunge-Assist-Project-One-Sheet.pdf'
```
- [x] Remove Valeriya Metla from the `leadership` variable
- [x] Add the following persons to the `leadership` variable
    - [x] Name: Sheron Virani
GitHub Handle: sheronvirani21
Role: Product Manager, Research
Slack Member ID: U041X0628B0
    - [x] Name: James Shin
GitHub Handle: jamesshin27
Role: Product Manager, Design
Slack Member ID: U04BS46F67L
- [x] Check the [Expunge Assist project page](https://www.hackforla.org/projects/expunge-assist) on your local development environment to verify the changes and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [The Expunge Assist markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/expunge-assist.md)
- [HFLA wiki on project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [How to find a Slack ID](https://github.com/hackforla/admin/wiki/Slack:-Find-a-Slack-ID)

**Comment by kelseylondon** [comment]
@jamesshin27 - could you add the label "ready for org rep" to this issue, and then move it to the Project Board [(directions can be found at the bottom of the issue form)](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D) - I don't have the permissions to do so.

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge This is ready for dev lead reformatting.

**Comment by MarkWiltberger** [comment]
i. **Availability**: 10am - 6pm ET Mon - Fri
ii. **ETA**: 02/07/2023 6pm ET

**Comment by MarkWiltberger** [comment]
i. Availability: 10am - 6pm ET Mon - Fri
ii. ETA: 02/08/2023 Wed 6pm ET

**Comment by jdingeman** [comment]
Hi @MarkWiltberger, thank you for taking up this issue, however, it was in the New Issue Approval column meaning it is waiting for final approval from product. Please only take issues from the Prioritized Backlog and be sure that the issue does not have the "Ready for Milestone" label

**Comment by MarkWiltberger** [comment]
Thank you, sounds good, will do.

**Comment by ExperimentsInHonesty** [comment]
@kelseylondon I am approving these changes, but you will have to get the teams's one sheet updated and back on the website asap.  All projects must have them.

**Comment by kelseylondon** [comment]
@ExperimentsInHonesty - thank you! I'm not actually a PM, so tagging @jamiesiu and @jamesshin27 re: updating the team's one sheet.

**Comment by d-perez-8** [comment]
Availability: 2pm-4:30pm Weekdays
ETA: 02/21/2023

**Comment by ExperimentsInHonesty** [comment]
This issue will get accepted as done when expunge assist team creates a new issue on our repo to re-add the overview (one sheet) - they are currently working on a draft https://github.com/hackforla/expunge-assist/issues/868#issuecomment-1475046611
