### ISSUE TITLE
Correct erroneous file names for the step images on the Getting Started Page

### ISSUE THREAD

**Issue by MattPereira** [hackforla/website#3936]
### Overview
As developers, we need to ensure our image files are named properly so that we do not get confused in the future. For this issue, we will change several image file names in the `/assets/images/getting-started/` folder so that they describe the content of the image instead of the step number.

### Action Items
- [x] Rename `assets/images/getting-started/step1.png` to `./assets/images/getting-started/business.png`
    - [x] Update the `_data/internal/credits/business.yml` file to use the new png file name for the `image-url` variable
- [x] Rename `assets/images/getting-started/step4.png` to `./assets/images/getting-started/technology.png`
    - [x] Update the `_data/internal/credits/technology.yml` file to use the new png file name for the `image-url` variable
- [x] Rename `assets/images/getting-started/step2.png` to `./assets/images/getting-started/button.png`
    - [x] Update the `_data/internal/credits/button.yml` file to use the new png file name for the `image-url` variable
- [x] Rename `assets/images/getting-started/step3.png` to `./assets/images/getting-started/people.png`
    - [x] Update the `_data/internal/credits/people.yml` file to use the new png file name for the `image-url` variable
- [x] Update all of the file names appropriately for the `<img>` `src` attributes in the `pages/getting-started.html` file so that everything stays the same visually
- [x] Check the [Getting Started Page](https://www.hackforla.org/getting-started) to ensure the page remains unchanged
- [x] Check the [Credits Page](https://www.hackforla.org/credits/) to ensure the page remains unchanged

### Resources/Instructions
- https://www.hackforla.org/getting-started
- https://www.hackforla.org/credits/
- https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits
- https://github.com/hackforla/website/tree/gh-pages/assets/images/getting-started
- https://github.com/hackforla/website/issues/3903

**Comment by JessicaLucindaCheng** [comment]
@MattPereira Developer will also need to find and update the `image-url` for the credit files in [_data/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits) that use those images you are renaming. These credits show up on the [Credits page](https://www.hackforla.org/credits/).

**Comment by MattPereira** [comment]
@JessicaLucindaCheng 

Do you think we should consider naming the png image files to match the credit name instead of the step number?

So for instance `step4.png` would change to `technology.png`

I kinda think that would be less confusing

**Comment by JessicaLucindaCheng** [comment]
@MattPereira 
> Do you think we should consider naming the png image files to match the credit name instead of the step number?
> 
> So for instance `step4.png` would change to `technology.png`
> 
> I kinda think that would be less confusing

I think that's a good idea! Also, thanks for writing the issue!

**Comment by kotynskm** [comment]
i. Availability: 2/17/23 all day
ii. ETA: 2/17/23 - 2/20/23
