### ISSUE TITLE
Slack workspace bot is not working in heroku

### ISSUE THREAD

**Issue by debasistripathy01** [hackforla/website#3937]
### Overview

slack workspace link expired  as heroku limited it's hosting and requestings

### Action Items

- [ ] For new devs, it would be great if the slack workspace would work
- [ ] Render.com would work for the bot

### Resources/Instructions

- [ ] Render.com / Railway / Cyclic.app

**Comment by jdingeman** [comment]
Closing this issue as we will not be updating the website with an open invite for Slack at this time.
