### ISSUE TITLE
Update Project Profile: Youth Justice Nav

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/website#3949]
### Project Name

Youth Justice Nav

### Project Card URL

youthjusticenav.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Nielsen
Name: Daniel Lee

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Rabia Shaikh
GitHub Handle: Rabia2219
Role: Project Manager
Slack Member ID: U01QSJ10XRA

Name: Hyun Joo Sandy Oh
GitHub Handle: doctorsandy
Role: UX Researcher
Slack Member ID: U03RZE7TTKP

### Project Status

Active

### Update your meeting times?

NO

**Comment by jdingeman** [comment]
Issue has been created here: 
- https://github.com/hackforla/website/issues/3958
