### ISSUE TITLE
Perform website audit

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#395]
### Overview
Perform website audit to identify areas of improvement. 

### Action Items
- [ ] Perform initial review of website
- [ ] Identify potential tweaks to web page UI, including buttons

### Resources/Instructions
http://www.hackforla.org

**Comment by ashlingam** [comment]
Suggested edits based on initial audit: [https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=0%3A1](url)

**Comment by ExperimentsInHonesty** [comment]
This phase complete
