### ISSUE TITLE
Update Food Oasis Project URL in Profile Links and Resources 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#3955]
### Overview

As developers we would like to use a consistent URL in the various hyperlinks representing the Food Oasis project site.  In this issue, the URL displayed in the Links and Resources sections will be updated.

### Action Items

- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the [food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md) file and find the 'links' list.
- [x] In the 'links' list, for the member 'Site', replace the existing value of 'url' with "https://foodoasis.net".  This single change will update the hyperlink URLs displayed on the website under the headings "Links" and "Resources".  

### Resources
Food Oasis markdown file: https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md
[Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

### Related Issues
Update Project Profile: Food Oasis #3572

**Comment by mademarc** [comment]
i. Availability: (02/09/2023)
ii. ETA: (by 9pm)

**Comment by roslynwythe** [comment]
@mademarc  @jdingeman Hi Marco, this issue is in the "New Issue Approval" column of the Project Board (on the right sidebar of the page), and it has the "Ready for Milestone" label.  Both of those indicate that the issue is not ready for assignment yet.  I really appreciate your enthusiasm and interest in getting started on this issue, but it simply isn't ready yet; project management could still make changes to the scope, size and description of the issue, and we wouldn't want any of your effort to be wasted.  Therefore I have to un-assign you from the issue.

**Comment by mademarc** [comment]
Hello @roslynwythe thanks for the heads up and no worries as well

**Comment by brianf4** [comment]
i. Availability: Monday/Wednesday
ii. ETA: Today (2/14/23) or by Friday (2/17/23)
