### ISSUE TITLE
Monthly Reminders to Update Wins Page Token

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#3957]
### Dependency/ER
- [x] #3748 

### Overview
We need to research and find a way to make sure dev leads know when the GitHub API token is expiring and needs to be updated. This affects how certain GHAs and the Wins Page Google Apps Script behave.

### Action Items
- [ ] Research possible GHAs or Slackbot reminders that remind dev leads to refresh the token to avoid expiration
  - [ ] For example: an automatic issue/pull request that serves as a big reminder that the token is about to expire or a Slackbot Reminder
- [ ] Discuss with the dev leads/merge team and product to determine the most feasible solution

### Resources/Instructions
- Issue discovered in: https://github.com/hackforla/website/issues/3417
- Wins Page [Google Apps Script](https://script.google.com/home/projects/18uQ6VT7PGZ5skTLD-KDACf3DpMCMPi0WCcl2hBKhTFhi8F0tJKuq0Z9A/edit)
- Wins Page [wiki](https://github.com/hackforla/website/wiki/Wins-page)

**Comment by ExperimentsInHonesty** [comment]
@jdingeman 
- I just reviewed this issue and there is a comment on it that is not reflected in this issue https://github.com/hackforla/website/issues/3748#issuecomment-1383221254 .  So I am putting this back into the new issue approval column.

**Comment by JessicaLucindaCheng** [comment]
Today, I updated the hackforla bot token and the elizabethhonest bot token to never expire.

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - Jessica did a thorough job at updating the admin guide and the wiki to reflect the process of updating the token and granting/revoking permissions for devs using it.
