### ISSUE TITLE
Update Project Profile: Youth Justice Nav

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#3958]
### Overview
The Youth Justice Nav page needs to be updated to reflect accurate team information. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/youthjusticenav.md` file and find the `leadership` variable.
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
  - [x] Name: Rabia Shaikh
GitHub Handle: Rabia2219
Role: Project Manager
Slack Member ID: U01QSJ10XRA
  - [x] Name: Hyun Joo Sandy Oh
GitHub Handle: doctorsandy
Role: UX Researcher
Slack Member ID: U03RZE7TTKP
- [x] Remove the following members and their information from the file:
  - [x] Nielsen (Product Manager)
  - [x] Daniel Lee (Product Designer)
- [x] Verify the changes by viewing the [Youth Justice Nav project page](https://www.hackforla.org/projects/youthjusticenav) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [youthjusticenav.md](https://github.com/hackforla/website/blob/gh-pages/_projects/youthjusticenav.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by ExperimentsInHonesty** [comment]
- @Rabia2219 we have moved the changes you requested to this issue https://github.com/hackforla/website/issues/3958

**Comment by bootcamp-brian** [comment]
ETA: End of day Thurs
Availability: Tonight & Thurs before 6pm

**Comment by bootcamp-brian** [comment]
Completed issue and submitted pull request.
