### ISSUE TITLE
Update Project Profile: TDM Calculator

### ISSUE THREAD

**Issue by Biuwa** [hackforla/website#3963]
### Overview
The TDM Calculator page needs to be updated to reflect accurate team information. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/youthjusticenav.md` file and find the `leadership` variable.
- [x] Update the following team members' `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
  - [x] Name: Moji Jimoh
GitHub Handle: mojimoh
Role: Product Manager
Slack Member ID: D04HDM7DM18
  - [x] Name: Anousha Shadrach
GitHub Handle: Noushie
Role: Lead, UX Design
Slack Member ID: U045EHW8NDA
- [x] Verify the changes by viewing the [Youth Justice Nav project page](https://www.hackforla.org/projects/youthjusticenav) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [tdm-calculator.md](https://github.com/hackforla/website/blob/gh-pages/_projects/tdm-calculator.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by jdingeman** [comment]
Hi @Biuwa,

Could you please clarify if these members' info just need to be updated or completely removed? Their info already exists in the file. 
![image](https://user-images.githubusercontent.com/88953806/218608440-15f7771f-9c59-456c-9ba3-c358818a567e.png)

**Comment by jdingeman** [comment]
### Project Name

LA TDM Calculator

### Project Card URL

tdm-calculator.md

### Update the Title?

NO

### Title

_No response_

### Update the Description?

NO

### Description

_No response_

### Update the Image?

NO

### Image

_No response_

### Update the Technologies?

NO

### Technologies

_No response_

### Update the Partner(s)?

NO

### Partners

_No response_

### Update the Tools?

NO

### Tools

_No response_

### Update GitHub Link?

NO

### GitHub Link

_No response_

### Update Slack Link?

NO

### Slack Link

_No response_

### Update Test Site Link?

NO

### Test Site Link

_No response_

### Update Demo Site Link?

NO

### Demo Site Link

_No response_

### Update Site Link?

NO

### Site link

_No response_

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Moji Momoh
Name: Anousha Shadrach

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Moji Jimoh
GitHub Handle: mojimoh
Role: Product Manager
Slack Member ID: D04HDM7DM18

 Name: Anousha Shadrach
GitHub Handle: Noushie
Role: Lead, UX Design
Slack Member ID: U045EHW8NDA



### Project Status

Active

### Update your meeting times?

NO

### If YES on update meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue

_No response_

**Comment by Biuwa** [comment]
@jdingeman Info updated. There was a misspelling of Moji's last name; the correct spelling is JIMOH, but it currently shows MOMOH also correct Anousha's role to Lead, UX Design.

**Comment by jdingeman** [comment]
> @jdingeman Info updated. There was a misspelling of Moji's last name; the correct spelling is JIMOH, but it currently shows MOMOH also correct Anousha's role to Lead, UX Design.

Got it, thank you!

**Comment by perlaroyerc** [comment]
Availability: M-F 11:00 to 06:00 ET
ETA: March 2
