### ISSUE TITLE
Fix Position of First Paragraph on Getting Started Page when the Viewport Width is Below 768px

### ISSUE THREAD

**Issue by Adastros** [hackforla/website#3973]
### Overview

As developers, we want to ensure that there are no visual inconsistencies with the text on the website. We need to reposition the first paragraph on the Getting Started page so that it is visually consistent with the other paragraph on the page.

### Details
<details>
<summary>Current State of the Paragraphs When the Viewport Width is below 768px</summary>

![image](https://user-images.githubusercontent.com/48114590/218962725-c0522465-9a89-4710-a75f-7471394428d0.png)

</details>

<details>
<summary>Future State of the Paragraphs When the Viewport Width is below 768px</summary>

![image](https://user-images.githubusercontent.com/48114590/218962656-d6f1a079-7c00-4fbe-8b67-c4a76ccd4aec.png)

</details>

### Action Items

- [x] Update class `.header-bold-p` in the scss file so that the opening paragraph is positioned similarly to the paragraph below it.
- [x] Test your update by setting the viewport width below 768px and verifying that the two paragraphs under the Getting Started header are positioned uniformly with each other. 
- [x] Test your update at other viewport widths and verify that there are no unintended side effects at those viewport widths

### Resources/Instructions

- [Getting Started Page](https://www.hackforla.org/getting-started)
- [Hack for LA Figma Link](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8561%3A72465)
- [_getting-started-page.scss file](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_getting-started-page.scss)

**Comment by upendrasahni** [comment]
Hey @Adastros i would love to work in this issue so can you please assign it to me?

**Comment by upendrasahni** [comment]
Hey @Adastros i would love to work on this issue so can you please assign it to me?

**Comment by Adastros** [comment]
Hi @upendrasahni, thanks for offering to work on this issue! Unfortunately, this issue is currently in the draft phase. Once I finish the draft, the dev. leads will need to review and approve it before it can be worked on. Once it's approved, this issue will be moved to the "Prioritized backlog" column of the project board. If you see this issue there, you can assign yourself to this issue to work on it. 

In the meantime, you can try picking up another issue in the "Prioritized backlog" while this issue goes through the approval process.

**Comment by ronaldpaek** [comment]
i. Availability: 03/03~03/07
ii. ETA: 03/03

**Comment by ronaldpaek** [comment]
Am I suppose to put a label of status updated to let people know to look at this issue/task?

**Comment by Adastros** [comment]
Hi @ronaldpaek, no need to put the `Status: Updated` label. Pull requests are typically self assigned so everyone gets a chance to practice reviewing code. That being said, we do review open pull requests and ask for volunteers to review them at every developer meeting on Tuesday (no meeting this Tuesday, 07MAR23). We try to have at least 2 reviewers per pull request before merging. Hope this helps!

**Comment by Adastros** [comment]
Forgot to mention, adding reviewers via the gear icon on the reviewer section of the page is sufficient to notify someone specifically to review a pull request. Do take care to make sure whoever you add is active and on the website team. If you need the merge/ dev lead team to review something, feel free to @ someone on the team or notify the entire team with `@hackforla/website-merge` in a comment. Slack works too if needed
