### ISSUE TITLE
Fix Hack for LA Website Header and Nav Menu at Fractional Viewport Widths

### ISSUE THREAD

**Issue by Adastros** [hackforla/website#3975]
### Overview

As developers, we want to ensure that the website UI functions as intended at various viewport widths. We will need to fix the UI so that the header and the navigation menu are not displaced from the top of the page.

#### Size details
This issue could turn into a Medium size issue if making the changes ends up having unintended side effects.  Do not self assign this issue if you are needing a slower on ramp to coding.

#### Details
This bug can be seen from any page on the Hack for LA website and may affect the layout of other elements on certain pages. 

This bug occurs if the browser displays the viewport with fractional widths (e.g. 767.33px) on certain high-dpi devices. 

This bug is due to how the breakpoints are set in the `_layout.scss` file. The breakpoints currently only account for integer viewport widths. Any fractional viewport widths that fall in-between the breakpoints are not accounted for causing the browser to not apply the intended styling for the elements. 

For example, the breakpoints for `$bp-tablet-up` and `$bp-below-tablet` are set to `min-width: 768px` and `max-width: 767px`, respectively. We can interpret them as 

```
$bp-tablet-up: Style for viewports >= 768px
$bp-below-table: Style for viewports <= 767px
```

or 

`767px <= x <= 768px`

x can be thought of as 767px plus some fractional number (e.g. 767.33px). Any viewport width that falls in between 767 and 768 can cause the browser to not style the page like we want it to. 

<details>
<summary>Home Page with the Header and Nav Menu Bug</summary>

![Home Page GIF](https://user-images.githubusercontent.com/48114590/231071162-6f9af96c-57f8-413b-9dd3-f1cfe0f11f6e.gif)

</details>

<details>
<summary>Getting Started page with the Header and Nav Menu Bug</summary>

![Getting Started Page GIF](https://user-images.githubusercontent.com/48114590/231071642-af8e694d-3fa1-48ac-a643-4c7f62914e27.gif)

</details>

### Action Items

- [x] Update the SASS variables containing “$bp-below-” in their name in the `_layout.scss` file to subtract .02 instead of 1. 
- [x] Test and verify that the header and navigation menu on all Hack for LA website pages do not exhibit the bug.
- [ ] Test and verify that updates to the device width breakpoints do not have any unintended side effects on any elements on all of the pages on the website.

### Resources/Instructions

- [Hack for LA Homepage](https://www.hackforla.org/#)
- [Reference this solution from Bootstrap](https://getbootstrap.com/docs/5.2/layout/breakpoints/#max-width)
- [_layout.scss file](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_layout.scss)
- [Range Context - W3C Media Queries Level 4 Specification](https://www.w3.org/TR/mediaqueries-4/#range-context)
  - Additional reading for a future solution we will implement. Also helpful to learn more on why the website is experiencing the issue. 
- One way to replicate/test on Windows 10
  - select a display for testing
  
    <details>
  
    ![image](https://github.com/hackforla/website/assets/48114590/4a336664-45a0-4718-adf1-d8eed88086b4)

    </details>

  - set scaling for a monitor/ screen to 125% (or any other scaling % if 125% doesn't work for your setup)
  
    <details>
    
    ![image](https://github.com/hackforla/website/assets/48114590/f7775c03-0dcb-4088-b851-4d1d67da2d5d)

    </details>

  - display the browser on that monitor with the 125% scaling
  - test to see if your browser width is displayed in fractions by changing the width between 767px and 768 px with the developer tools to see if the hamburger icon has a red box around it.
    - Note 1: Chromium browsers display the fractions of the viewport width when you change it in the non-mobile testing view. In the mobile testing view, the width will be displayed as an integer but you can enter in a fractional number (e.g. 767.67) and it will change the viewport width to that number. Do note that it won't show the fraction component when you do this.
    - Note 2: Firefox doesn't seem to display the fractional part of the width for both mobile and non-mobile testing views. The mobile testing view does not allow you to enter fractions. You will need to manually change the viewport width to see if the bug is present.
    <br>
    <details> 
    <summary>Chrome fractional width example - non-mobile testing view</summary>
    
    ![image](https://github.com/hackforla/website/assets/48114590/320a44f3-7518-485a-9f2a-ead8fe924dc8)

    </details>

    <details> 
    <summary>Chrome fractional width example - mobile testing view</summary>
    
    ![image](https://github.com/hackforla/website/assets/48114590/d7fa601a-2bd4-45cc-bc91-f70fd3aa152f)

    </details>

**Comment by Adastros** [comment]
Since this bug can seen on all Hack for LA pages, I wasn't sure which P-Feature label to add. I added the `P-Feature: Home Page` label for now

**Comment by ExperimentsInHonesty** [comment]
Please make a [decision record](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted) first, then this issue can get prioritized.

it should contain
- info about the overall problem
- what Bootstrap has done to solve
- What is currently happening at W3C
- What we are going to do
- What we will need to keep an eye on at WC3, so that we know when to undo the changes and use the new standard.

**Comment by Adastros** [comment]
`Progress:` Drafted the issue but will need to update it to implement a solution similar to Bootstrap's solution. A decision record will need to be drafted as well.
`Blockers:` I will be out from 10MAR23 - 02APR23. I will finish this issue and the decision record when I am back. 
`Availability:` TBD when I am back on 03APR23.
`ETA:` TBD when I am back on 03APR23.

**Comment by Adastros** [comment]
Availability (PST): 10 - 11:30 PM Monday - Tuesday; Flexible 08APR23 - 09APR23
ETA: 11:30 PM 10APR23

**Comment by Adastros** [comment]
Below is a draft of a decision record to be added to the new website-wiki repo which is not released at this time. 

### DR: Updating Hack for LA Website’s Device Width Breakpoints to Account for Fractional Widths

This is a record in the [Decision Records on Solutions Adopted](DEV LEAD: Add a link to it in the website-wiki repo if we are still linking back to that page. Otherwise, this line might need to be edited. Confer with the technical writer.).

#### Issue

[Issue #3975 - Fix Hack for LA Website Header and Nav Menu at Fractional Viewport Widths](https://github.com/hackforla/website/issues/3975)

#### Problem Statement

Hack for LA Website’s Device Width Breakpoints do not currently account for fractional viewport widths (e.g. 767.33px). If a user’s browser is displaying the Hack for LA website at a fractional width, HTML and CSS elements on the website may not behave as intended. 

#### Potential Solution

* Immediate Solution
  * The immediate solution involves implementing fractional device width breakpoints similar to [how Bootstrap has theirs](https://getbootstrap.com/docs/5.0/layout/breakpoints/#max-width). Doing so would require updating the subtraction value from an integer to a decimal number (e.g. “-1” to “-.02”) for all SASS variables containing “$bp-below-” in their name in [_layout.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_layout.scss). This would provide a temporary work around for the issue until we can use [range context queries](https://www.w3.org/TR/mediaqueries-4/#mq-range-context) when the [Media Queries Level 4 specification](https://www.w3.org/TR/mediaqueries-4/) is standardized by W3C **OR** when there is sufficient adoption of the range context query specification prior to W3C standardization by most/all major browser vendors, users, and relevant dependencies (e.g. SASS) used on the website. 

* Future Solution
  * The future solution involves replacing the device width media features in _layout.scss with range context queries as described in the Media Queries Level 4 specification. Instead of using the “min-/max- width” media features to determine device width breakpoints, mathematical comparison operators (e.g. “<” or “>=”) will be used instead to indicate device width breakpoint ranges. 

#### Feasibility Determination

* Immediate Solution
  * The immediate solution is feasible and currently implemented by Bootstrap. Implementing the solution for the website only requires changing the subtraction value from an integer to a decimal number (e.g. “-1” to “-.02”). The challenging part is verifying and testing all pages on the website to ensure the potential solution does not cause any unintended side effects.
* Future Solution
  * The future solution is feasible and requires the same effort as the immediate solution.
  * Implementation will only occur if one of the two conditions is met: 
    * the Media Queries Level 4 specification is standardized by W3C
      * Note: At the time of writing this decision record, it is currently being worked on. It is unknown when the specification will be standardized. Routine monitoring is required to ensure we switch over to using range context queries as soon as the specification is released
    * there is sufficient adoption of the range context query specification prior to W3C standardization by most/all browsers, relevant dependencies used on the website, and browser versions that support the specification by users (i.e. are most users using the latest version(s) of a browser that implements the specification?). Routine monitoring is required to determine when to implement the solution.
      * Note 1: [Most browsers](https://caniuse.com/?search=media-queries) at the time of writing this decision record have implemented the range context queries with Safari being the last major browser to implement it in version 16.4 on 27MAR2023. That being said, adoption of the latest version of the Safari browser is not there yet when compared to previous versions of Safari. Implementing it now may cause issues for users who visit the website using Safari.
      * Note 2: SASS has added [support ](https://sass-lang.com/documentation/breaking-changes/media-logic ) for the Media Queries Level 4 specification. There shouldn’t be any conflicts with SASS if we decide to implement it ahead of time.

**Comment by kurikurichan** [comment]
Hello all,
i. Availability: I am available to work on this issue tonight and weekday evenings this week (except Tuesday and Friday)
ii. ETA: I should have it done by next Thursday. Will update if it will be longer

**Comment by kurikurichan** [comment]
Hi all, I am unassigning myself from this issue for the following reasons:
1.) I do not have a high-DPI device so I can't confirm if the desired fix works or not (all of my browsers automatically round to integer numbers and cannot break up individual pixels, none of my monitors can do 4k)
2.) According to the [link provided to the Bootstrap docs](https://getbootstrap.com/docs/5.2/layout/breakpoints/#max-width), it appears that max-width below already works under the hood by subtracting .02 px from the max-width value. I could be wrong about this but if that's the case, wouldn't manually subtracting .02 px just basically tell the browser to check for a value that is minus .04 px? @Adastros

**Comment by Adastros** [comment]
Hi @kurikurichan, no problem! 

A 4K resolution monitor isn't needed to test for the bug. I was able to replicate this on a 1920 x 1200 and 1920 x 1080 display, each a different size. I've updated the testing instructions for Windows 10 to hopefully clarify how the bug can be replicated. 

Per the [site architecture wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture), the website doesn't use Bootstrap. The Bootstrap link is for reference on where the solution came from. Subtracting 0.02 from the breakpoints will not lower the value by 0.04.

**Comment by one2code** [comment]
**Availability:** 5/29/23, 5/31/23-06/02/23
**ETA:**06/02/23

@Adastros since SASS has added support for the Media Queries Level 4 specification, and Safari has supported the change for a couple of months now, is it ok if I go ahead and resolve the issue with range context queries?

**Comment by Adastros** [comment]
Hi @one2code, it's difficult to say but I think it would be best to implement the immediate solution. Looking at the [caniuse website](https://caniuse.com/?search=media-queries) most Safari users haven't transitioned over to the latest Safari versions yet. It might be a while before we see significant adoption of a compatible Safari versions.

**Comment by one2code** [comment]
@Adastros OK, I will begin implementing the immediate solution. 
**Update:** The fractional viewport implementation on the nav and header is working without any unintended side effects. Will test further on the rest of the website today or tomorrow if I have time, to see if there are any unintended side effects.
**ETA:** 6/9/23
