### ISSUE TITLE
Getting Started Page: Fix Text Positioning for Step 5 in the Header Container

### ISSUE THREAD

**Issue by Adastros** [hackforla/website#3976]
### Overview

As developers, we want to ensure that there are no visual inconsistencies with the text on the website. We need to ensure that the text "Step 5" on the getting started page is visually consistent with the other "step" texts on the page.

### Details
<details>
<summary>Current State of Step 5 When the Viewport Width is Between Approximately 768 to 795px</summary>

![image](https://user-images.githubusercontent.com/48114590/218966005-a8db4868-3a37-4798-bd86-e32770dfdd0e.png)

</details>

<details>
<summary>Future State of Step 5  When the Viewport Width is Between Approximately 768 to 795px</summary>

![image](https://user-images.githubusercontent.com/48114590/219570317-a191eec7-f66b-4712-8787-cb687013a862.png)

</details>

### Action Items

- [x] Update the code in the `_getting-started-page.scss` file so that the text "Step 5" is visually consistent with the other "step" texts. 
- [x] Test your updates by changing the viewport between 768 to 795px and verify that the text "Step 5" is visually consistent with the other "step" texts. 
- [x] Test your updates at various viewport widths and verify that your updates have no unintended side effects at those viewport widths. 

### Resources/Instructions

- [Getting Started Page](https://www.hackforla.org/getting-started)
- [Hack for LA Figma Link](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=8561%3A72465)
- [_getting-started-page.scss file](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_getting-started-page.scss)

**Comment by christinaor** [comment]
Availability: Tues 2/21, 8-10pm
ETA: Wed 2/21, 10pm

**Comment by ExperimentsInHonesty** [comment]
I have no complaints with the execution of this issue.  I think we need to review the way its working and make a new issue to change the way the steps in the header are responsive.  See this image and lets discuss at next dev lead meeting
![image](https://user-images.githubusercontent.com/37763229/221401190-fd7bee90-c9a9-4082-93fe-e181f30e1fe2.png)

**Comment by jdingeman** [comment]
> I have no complaints with the execution of this issue. I think we need to review the way its working and make a new issue to change the way the steps in the header are responsive. See this image and lets discuss at next dev lead meeting ![image](https://user-images.githubusercontent.com/37763229/221401190-fd7bee90-c9a9-4082-93fe-e181f30e1fe2.png)

- Issue has been made here: https://github.com/hackforla/website/issues/4084
