### ISSUE TITLE
Implement Redesigned Donate Page (mobile and desktop)

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#3983]
### Overview

As developers, we need to implement the new Figma design for the Donate Page, in both mobile and desktop views. 

<details>
<summary>Existing Design</summary>

![Donate page current mobile](https://user-images.githubusercontent.com/5314153/218994919-17bad791-a5a6-4c23-b494-d5e2ff68cc5c.png)

![Screenshot_20230215_015012](https://user-images.githubusercontent.com/5314153/218994231-fd5722ab-97dc-4f3c-a43f-d4207bb3a07a.png)

</details>

<details>
<summary>New Design (with update: see first Action Item)</summary>

![donate develop this version red star](https://user-images.githubusercontent.com/5314153/219311444-ea60fa93-63b6-4896-ae57-0e5d440a1762.png)

</details>

### Action Items

- [x] Implement Figma design for mobile view, with the following update: The blue color in the donate form should instead match the dark blue color in https://www.hackforla.org/assets/images/about/hfla-donate.gif
- [x] Consider the existing mobile and desktop pages, and from the new mobile design, extrapolate a corresponding desktop design and implementation.  
- [x] This issue will require changes to `_includes/donate-card.html`,  which is included in both `pages/donate.html` and `pages/join-us.html`.  To prevent changes to the Join Us page, make a copy of the unmodified `_includes/donate-card.html`, rename it `_includes/join-donate-card.html,` and update `pages/join-us.html` to include `_includes/join-donate-card.html`
- [x] Check to ensure that the appearance of the Join Us page is unchanged, except for  the updated donation circle graphic.  
- [x] Submit a pull request with the proposed changes

### Resources/Instructions
[Donate page](https://hackforla.org/donate)
[pages/donate.html](https://github.com/hackforla/website/blob/9a7168d42d43d5de8cc6e3995402bd8746e6b17a/pages/donate.html)
[_includes/donate-card.html](https://github.com/hackforla/website/blob/gh-pages/_includes/donate-card.html)
[Join Us page](https://hackforla.org/join)
[pages/join-us.html](https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html)
[Figma design - marked with red star](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24579%3A285100&t=C14tX0fL6J4V5RWB-4)
[_sass/components/_donate.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_donate.scss)

**Comment by roslynwythe** [comment]
Hi @sijiapitts @ExperimentsInHonesty - This issue was created in connection with the design from https://github.com/hackforla/website/issues/3661. 
 There are several designs outlined in Figma; for the screenshot in Overview, I selected the one with the label "Final version for development" for the screenshot in that issue.   Please confirm I provided the correct design.

**Comment by sijiapitts** [comment]
Hi @roslynwythe sorry for the confusion, but the frame marked as "final version for development" is not the correct one. It used to be the final design until we noticed some issues and did a redesign. 

The correct mobile version is [this one](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24579%3A285100&t=C14tX0fL6J4V5RWB-4). This link should direct you directly to the frame.  I also added a star and an arrow next to the design in case it's not clear. Please let me know if you have any other questions!

**Comment by ExperimentsInHonesty** [comment]
I think the new design is actually the old design.  See https://codeforamerica.org/donate/ for the new color. I have added this to this weeks dev/pm agenda.

**Comment by ExperimentsInHonesty** [comment]
@sijiapitts I think we changed to the dark blue gif that you currently see here https://www.hackforla.org/assets/images/about/hfla-donate.gif
when Code for America updated their site, but it never made its way to the design.  Which is where the confusion is coming in.  \

- [x] @roslynwythe is going to update this issue to communicate to the developers to make all the changes specified in your design except for changing it back to the light blue version.

- [x] @chriskong217 please make a design issue to update the [figma donate (wip) page]( https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24579%3A285100&t=mm8VLUVgXHzrUo9z-0) with the new dark blue image https://www.hackforla.org/assets/images/about/hfla-donate.gif 
- [ ] @bonniewolfe Design issue: https://github.com/hackforla/website/issues/4051

**Comment by Thinking-Panda** [comment]
Availability: 10AM- 3 PM
ETA: 3/13/23

**Comment by Thinking-Panda** [comment]
I needed more clarification and I am in contact with merge team. My updated ETA will be 3/20/23

**Comment by ExperimentsInHonesty** [comment]
@Thinking-Panda Please add notes about your question here since you have put this in the Questions column.  If you think it needs to be asked in person, please summarize.

**Comment by Thinking-Panda** [comment]
While working on this issue, I made changes in 4 files pages/donate.html, _includes/donate-card.html, _sass/components/_donate.scss and assets/images/join-us/donation-graphic.svg

based on Figma design, the image was placed in donate.html (to be on the page header with a full width white background). Doing that also affected the join-us page (the donation-graphic.svg is not displayed). Bringing the image back to donate-card.html will still affect the join-us page (with a full width white background rather than in a page-card with rounded edges). Hope I explained it clear.

Please let me know how to proceed.

**Comment by Thinking-Panda** [comment]
@ExperimentsInHonesty , While working on this issue, I made changes in 4 files pages/donate.html, _includes/donate-card.html, _sass/components/_donate.scss and assets/images/join-us/donation-graphic.svg

Based on Figma design, the image was placed in donate.html (to be on the page header with a full width white background). Doing that also affected the join-us page (the donation-graphic.svg is not displayed). Bringing the image back to donate-card.html will still affect the join-us page (with a full width white background rather than in a page-card with rounded edges). Hope I explained it clear.

Please let me know how to proceed.

**Comment by roslynwythe** [comment]
@Thinking-Panda @ExperimentsInHonesty @hackforla/website-merge   I agree that since the Donate page design has diverged from the Join Us page design, both because there are fewer common elements and the card styles differ, it might not be feasible to use donate-card.html to share all the common elements,  and modification will have to be made to Join Us, which is out of the scope of this issue.

**Comment by ExperimentsInHonesty** [comment]
- @Thinking-Panda thanks for enumerating
- @roslynwythe thanks for looking more closely at this issue #3983 and #4263 
I think we need to review this at a meeting.  Because there are definitely some conflicts in the instructions.

The main change this issue was supposed to accomplish was to just change the paragraph and image at the top from

<img src="https://user-images.githubusercontent.com/37763229/227699628-6789f4ba-b253-48d2-92ce-5b9f539c406b.png" width=330px>


to 

<img src="https://user-images.githubusercontent.com/37763229/227699634-49c4c1a5-c658-48c2-bb61-1f6e6967f7b8.png" width=330px>

and move the content

> How to help us continue to do impactful work
> Provide [In-Kind services](mailto:%20donations@hackforla.org)
> Make a donation through Code for America (see below)

to a separate card

**Comment by ExperimentsInHonesty** [comment]
Hi @roslynwythe @Thinking-Panda

I looked at the PR on the formatting changes.  Here are the revisions that I think would close out this PR

# In Kind section

Please change this
![image](https://user-images.githubusercontent.com/37763229/227760182-a5b42ac3-58dd-49c3-9d74-7d4bd6c7d960.png)

to this
![image](https://user-images.githubusercontent.com/37763229/227761129-11da29d4-f020-4a56-a8de-de6b6c863c1d.png)


```
Provide In-Kind Software & Services

Your donation of software or services help Hack for LA continue to use cutting edge technology in support of our nonprofit mission.

Putting your tools in the hands of Hack for LA volunteers creates a new generation of tech workers who bring experience with your product to their companies.

We provide visible credit on the credits page and can collaborate on joint press releases or social media posts if desired.

Reach out to us if you would like to offer [in-kind software or services](mailto:donations@hackforla.org).
```

# Make a Donation section
 I have made a deck up to use in our discussion tomorrow, which I hope explains the big picture about the donation card part of the page [Hack for LA donation include files and implementation
](https://docs.google.com/presentation/d/1sD5TAtCe7lQkxFMMbNAHU99Z9DZMhwR_vGV5xFC5-q4/)

**Comment by ExperimentsInHonesty** [comment]
@Thinking-Panda, @roslynwythe also noticed a problem with the Join Us page created by the PR.  She is going to add screenshots to this issue, so I can review.  In the meantime, please check in with the Engineering Community of Practice to pick up a guide issue 
- [Templates and Guide project board](https://github.com/hackforla/engineering/projects/4)
- [Resources](https://github.com/hackforla/guides/wiki/Guide-Resources)

**Comment by roslynwythe** [comment]
Here is a screenshot of the Join Us page from the PR branch:
![image](https://user-images.githubusercontent.com/5314153/227861791-1f88f44f-9443-4723-8270-d860397dbd22.png)

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe That is helpful.  Here is what I think @Thinking-Panda could do in order not to break the Join us page that was using the same include to deliver the content to the join us page, as was being delivered to the donate page.  
![image](https://user-images.githubusercontent.com/37763229/227862980-1f63ab57-fcf2-41b0-ba90-1765fc4bb42f.png)

 She could make a copy of the original include and name it something related to the join us page, and then edit the join us page to use it.  We can then later make an issue to fix the join us page.  
 
 Roslyn does that make sense to you, or do you think we should do something else?

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty yes I agree, but I think she may also need to make some modifications to _sass/components/donate.scss to maintain the appearance of the Join Us page.   The Donate and Join Us pages were both referencing the same donation circle graphic so please advise, are we ok with using the new donation circle graphic on the Join Us page, or do we need to make a copy of that as well?

![image](https://user-images.githubusercontent.com/5314153/227883733-c5582dc7-f7e0-4d1f-b751-1b073a18e18a.png)

Also should I add an Action Item with the changes that you describe in your comment https://github.com/hackforla/website/issues/3983#issuecomment-1484016722  ?

**Comment by Thinking-Panda** [comment]
Hi @roslynwythe , I wanted to check with you as I am waiting for the issue action item to be updated after all the discussions. Should I work on the join-us page as well ?

**Comment by roslynwythe** [comment]
Hi @Thinking-Panda The dev lead team discussed this with Bonnie and we have several requests.  

- Bonnie noticed that on the donation form, the text is now placed on the right.  It should be placed to the left of the form, as it is in the current design.  
- In order to avoid making layout changes to the Join Us page, please make a copy of the original _includes/donate-card.html and rename it _includes/join-donate.html, then update pages/join-us.html to include the newly created include file

We apologize for the extra effort and time involved in this issue.  None of us understood the impact that would be caused by the issue as originally written.  Thank you for your patience and persistence on this issue.

**Comment by Thinking-Panda** [comment]
Thank you @roslynwythe for the updates. I am glad working with Hack for LA and this issue as it has given me a lot of learning opportunities. I will reach out in case I need help.

**Comment by Thinking-Panda** [comment]
Availability- 10 AM - 3PM M-F
ETA- 4/17/23

**Comment by ExperimentsInHonesty** [comment]
@Thinking-Panda, @roslynwythe and I are working on making some new issues to try to clear everything up.  I put everything I am thinking into this ER:  #4407, aut I want the merge team to take a look at it to see if there is anything we left off.  @roslynwythe has an eagle eye for that kind of thing.  And I want to make sure that we dont set you off with increasing the scope of your issue, and then create more problems.  Feel free to follow along on the ER for now.  If you want to return your issue with a note on it, I could add it to icebox with a dependency of getting this ER sorted out and you could move on to something else.  Then we could come back to you when we have clarification.  OR you could just wait a day or two ish for us to sort it out.

**Comment by Thinking-Panda** [comment]
@roslynwythe and @ExperimentsInHonesty I would like to wait a couple of days and try to complete working on this issue. Until then, working on guides.

**Comment by roslynwythe** [comment]
Hi @Thinking-Panda I made an update to the Action Items to clarify the requirements.  Please contact me on Slack if I can assist with the completion of this PR.

**Comment by roslynwythe** [comment]
Hi @Thinking-Panda I just learned from Bonnie that this issue has become time-sensitive because there are a number of other issues that are dependent on its completion, and those issues must be completed to reflect organizational changes affecting donations that will take place later this month.  If you would rather work on a different issue, please let Justin or I know and we will find you something that suits your needs.
