### ISSUE TITLE
Fix the dropdown menu for toolkit page

### ISSUE THREAD

**Issue by blulady** [hackforla/website#3985]
### Dependency
-  #3744 (its the issue that makes the component)
- #3256 

### Overview

During recent audits, the team realized that the drop-down menu design is not uniform. In an attempt to unify all drop-down menus the design team has redesigned the drop-down menu. This issue is to implement the new uniform design specifically on the toolkit page using the component designed for the project page.

### Action Items

- [x] Update the drop-down menu on the toolkit page to reflect the design in Figma using the component designed for the project page.
  - [x] You do not need to develop the search bar function.  The goal is to make this component reusable on multiple pages with different filters specified
- [x] Make the appropriate changes to the CSS, HTML, and JS as you need to
- [x] Ensure that changes to the component on the Toolkit page do not break pages in other pages (i.e. Projects Page, Wins, etc.)

### Resources/Instructions
- [final design](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=24519%3A284897) 
- for a reference a link to related design issue: #3626 
- in the elements folder https://github.com/hackforla/website/tree/gh-pages/_sass/elements you should find _dropdown_filters.SCSS that have been modified and should be ready to use
- in the [pages](https://github.com/hackforla/website/tree/gh-pages/pages) you should find the toolkit page https://github.com/hackforla/website/blob/gh-pages/pages/toolkit.html
- in the [assets/js](https://github.com/hackforla/website/tree/gh-pages/assets/js) you should find toolkit
- how to code for re-useability [Standardized Component](https://github.com/hackforla/website/blob/gh-pages/assets/js/toolkit.js) 
- write  up on [accessibility ](https://github.com/hackforla/website/issues/2173#issuecomment-1279768721)  (not specifically for drop down menus)

**Comment by ExperimentsInHonesty** [comment]
- @bonniewolfe I made a new issue #1156 
- @bonniewolfe I made a new issue F[ix typo on contributing readme #1156 ](https://github.com/hackforla/website/issues/1156)

**Comment by chrismenke45** [comment]
ETA: Monday 2/27 3pm
Availability: 2/22 & 2/23 10am-2pm, 2/24 12pm-2pm, 2/27 8am-12pm

**Comment by chrismenke45** [comment]
Updated ETA: 3/6
Availability: mon-fri 8am-12pm
Blockers:Figuring out how all the files work together with Jekyll, but it should just take some time.

**Comment by chrismenke45** [comment]
Update as of 2/28 meeting: Prepare drop down menu for mobile, review this issue with Bonnie to ensure that is what is required/expected.
ETA: 3/12 (Next possible meeting with Bonnie attending)

**Comment by chrismenke45** [comment]
Update 3/10:
ETA: 3/12 (Next possible meeting with Bonnie attending)

**Comment by ExperimentsInHonesty** [comment]
Dependency issues have been closed.  Please review this issue and the closed issues to see if its ready for prioritization

**Comment by kwangric** [comment]
i. Availability: Weekdays after 1pm PDT
ii. ETA: May 12th

**Comment by kwangric** [comment]
Progress: Haven't had as much time as I would have liked this past week, but I've removed the original dropdown menu and started reviewing the code for the new dropdown menu already implemented on the projects page.
Blockers: Having a little difficulty understanding the workflow of the code mentioned above. I'm slowly piecing it together and will try to contact Chris if I get completely stuck.
Availability: Most days I'm free after 3pm PDT
ETA: Still hoping to be completed by May 12th, will update if anything changes.

**Comment by kwangric** [comment]
Progress: Been working through the issue this week, made progress populating the filters based on the guide-pages. Gonna be working on the filter functionality next.
Blockers: Having a little difficulty understanding the workflow of the code mentioned above. I'm slowly piecing it together and will try to contact Chris if I get completely stuck.
Availability: Most days I'm free after 5pm PDT
ETA: Gonna work on it through next week and hoping to get it done by Friday.
Pictures: 
![fil](https://github.com/hackforla/website/assets/43795498/566a51c6-12ce-47bc-a31b-4cf9164fb57d)

**Comment by kwangric** [comment]
**Progress:** Implemented the filter functionality. Just need to add additional features to make it uniform with the filters on the projects page. This includes:

1. Adding a number in parenthesis indicating how many guides are in each filter.
2. Adding buttons that show all applied filters, with the ability to clear the individual filters or all of them.
3. Add 'view all' button in each category with more than 8 filters.
4. Allow user to collapse each category.

**Blockers:** See comments below.

**Availability:** Most days I'm free after 3pm PDT

**ETA:** Within the next two weeks.

---

### Details on blocker

As per the design on Figma, I've added all the filter categories for the guide pages except for "Technologies". Looking through the data for the guide-pages, there doesn't seem to be any information on technologies used. See pictures for details.

---

<details>
<summary>Design on Figma showing Technology section</summary>

- Filters on the mockup on Figma show a Technology category with different technologies used.

![Figma](https://github.com/hackforla/website/assets/43795498/e7c233dc-5db9-4030-bb35-4c14c991d7ac)

</details>

<details>
<summary>Guide-Page in the repository without any technology information</summary>

- The html file for the guide pages that I'm pulling the information to create the filters do not include technology.

![Guide Page](https://github.com/hackforla/website/assets/43795498/57ffe156-d47e-4415-9342-b0e7638b9418)

</details>

---

Is there another location where the technology used can be found? If not, should I just exclude it? Thanks.

**Comment by ExperimentsInHonesty** [comment]
Hi @kwangric.  I think that the guides that are there now, are not great examples... However, you can add the following to the one you are using an an example.

Create a Kanban Project Board from Our Template
The Technology for it should be GitHub
the Tool name Kanban

[Building a Survey Reporting Dashboard](https://www.hackforla.org/guide-pages/survey-reporting-dashboard-guide)
Technology: Looker Studio
Tool: Dashboard

**Comment by kwangric** [comment]
Progress: Finished most of the requirements of the issue. Last main issue is making it mobile friendly as well as some minor style details.
Blockers: N/A
Availability: Most days I'm free after 3pm PDT
ETA: On course to finish it this week

![image](https://github.com/hackforla/website/assets/43795498/f600a6b3-6a72-4bd9-a57e-2281765e94a5)
