### ISSUE TITLE
Create a DR for `_project-page.scss`

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#3990]
### Overview
- We need to create a Decision Record for the implementation of the `_project-page.scss` used in 
#3767 
so that we can document that solution adopted was to create a style in the `_project-page.scss` file instead of in a parent class.

### Action Items
- [x] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)
- [x] Create a new Decision Record in the [Wiki](https://github.com/hackforla/website/wiki) for the solution adopted in the pull request.
  - [x] The reason this should be documented is since the Project, Solution, and Impact card could potentially be a reusable component in the future, we would want to have its style be a part of a parent class (i.e. a new `.scss` file specific to the card) to access later
  - [x] This would potentially involve creating a new `.html` component that holds the layout of the card, which would then be used in a Liquid `include` statement in the layout of the [project.html](https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html)
- [x] Document the changes made in the `_project-page.scss` file specific to the Problem, Solution, and Impact card
- [x] Add a link to the DR in the [Decision Records on Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted)
- [x] When finished with the Decision Record:
  - [x] Place this issue into the [Questions / In Review](https://github.com/hackforla/website/projects/7#column-8178690) column
  - [x] Add a "ready for dev lead" label
  - [x] Notify merge team/tech leads to review

### Resources/Instructions
- [Solution adopted](https://github.com/hackforla/website/pull/3767/files)
- [Example](https://github.com/hackforla/website/blob/d503baa697a01ce7d56a043924afb4d160c1ae56/_layouts/project.html#L120) of a Liquid `include` statement
- [Liquid in Jekyll](https://jekyllrb.com/)

**Comment by jdingeman** [comment]
Will complete this issue when I have clarification of this [comment].(https://github.com/hackforla/website/issues/3547#issuecomment-1428973185)

**Comment by kurikurichan** [comment]
Provide Update
1. Progress - Starting on it- going to look at other DR's for proper formatting
2. Blockers - Mainly just working up the mental energy to look at the other DR's and really analyze them
3. Availability - Weekdays this week (so just not Sunday really) 
4. ETA - I think I can have it done by Tuesday at the latest, I don't think it will actually take long once I focus on it

**Comment by kurikurichan** [comment]
Comment draft:

This is a record in the [Decision Records on Solutions Adopted](Decision-Records-on-Solutions-Adopted).

#### Issue 
* #3990
#### Problem Statement
* We want a resuable component that displays on specific project pages that have problem, solution, and impact fields.
#### Potential Solution
* A style was implemented in the ```_project-page.scss``` file.
#### Feasibility Determination
* To use the new styles, developers can use the recently added classes such as: `.project-page-value-description`, `.sdg-card--title`, `.sdg-grid-item`, `.sdg-description-wrapper`, and `.sdg-description-card`.
#### Summary
* We needed an additional section on the project pages that displayed the Problem, Solution, Impact section, as originally requested in issue #3547. After a solution was implemented, it was decided in issue #3990 to make that styled component resuable.
* We could have created a parent class (i.e. a new .scss file specific to the card) for the style, to access later. However, it was decided to instead create a style in the ```_project-page.scss``` file.
* If using the parent class method instead, we would potentially have had to create a new `.html` component that held the layout of the card, which would then have been used in a Liquid `include` statement in the layout of the project.html.

**Comment by kurikurichan** [comment]
I followed the instructions for the new website-wiki repo and put my draft in the comment above. @jdingeman @roslynwythe , please let me know if there's anyone else I should ping/notify

**Comment by jdingeman** [comment]
Hi @kurikurichan, thank you! Closing this so you can move on to a new issue.
