### ISSUE TITLE
After you have finished adding yourself to the roster, let a merge team member or a technical lead know you have added yourself to the roster and would like to be added to the `website-write` and `website` teams on GitHub

### ISSUE THREAD

**Issue by angieyan** [hackforla/website#4001]

**Comment by plang-psm** [comment]
Hi @angieyan , there is no action item to create an issue for the pre work checklist therefore I will be closing this issue. You are already included on both the website and website-write.

**Comment by angieyan** [comment]
Thank you Philip.
