### ISSUE TITLE
Create a new data field in the project card markdown file for no project homepage

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#402]
### Overview
Some projects should not have a project homepage for any given reason, make it possible.

### Action Items

- [ ] Add logic for a project-homepage: false in _includes/project-card.html to do the following
   - [ ] change the title to Black text, so that it does not look like a link
- [ ] Add corresponding logic item in the sample project.md card
   - project-homepage: false

### Instructions
Use work-for-la as the sample because we don't want it to have a project homepage anyway (it has no content like leadership, etc).

**Comment by cnk** [comment]
Yulia, When I was checking things after merging I noticed that there is also a link around the image  on the card. Could you also remove that link when project-homepage is false? Thanks.

Also, the CSS to color the title black doesn't seem to be working. I am not sure why not.

**Comment by yulia-kh** [comment]
@cnk Thanks, Cynthia. I removed the link around the image too. I don't know why CSS doesn't work. I can see the black title for Work for LA locally and on the deployed website. I've checked in Chrome and Firefox.
![Screen Shot 2020-04-11 at 10 03 18 PM](https://user-images.githubusercontent.com/13112628/79061007-69066780-7c40-11ea-8778-797745a7eecb.png)
