### ISSUE TITLE
Communities of Practice information updates: Engineering

### ISSUE THREAD

**Issue by MicahBear** [hackforla/website#4025]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Communities of Practice - Engineering project card needs to be updated to reflect accurate team information. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `internal/communities/engineering.yml` file and find the `leadership` variable.
- [x] Remove the following member's info
  - [x] Ava Li
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
  - [x] Name: Micah Elm
Role: Co -Lead
GitHub Handle: MicahBear
Slack Member ID: U04N8H0V72R
  - [x] Name: AJ Price
Role: Co-Lead
GitHub Handle: mxajprice
Slack Member ID: U02UZ5BK8UB
  - [x] Name: Fang Yi Liu
Role: Co-Lead
GitHub Handle: fyliu
Slack Member ID: UCE01B4AX
  - [x] Name: Alejandro Gomez
Role: Co-Lead
Github: agosmou
Slack Member ID: U04HFRQ5Y12
  - [x] Name: Harrison Katz
Role: Co-Lead
GitHub Handle: hkatzdev
Slack Member ID: U04PFCPK6EP
- [x] Verify the changes by viewing the [Communities of Practice page](https://www.hackforla.org/communities-of-practice) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [engineering.yml](https://github.com/hackforla/website/blame/gh-pages/_data/internal/communities/engineering.yml)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by jdingeman** [comment]
### Remove person(s) and info from CoP file?

YES

### If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:

Name: Ava

### Add person(s) and info to CoP file?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Micah Elm
Title: Co -Lead
GitHub Handle: MicahBear
Slack Member ID: U04N8H0V72R

Name: aj price
Title: Co-Lead
GitHub Handle: mxajprice
Slack Member ID: U02UZ5BK8UB

Name: Fang Yi Liu
Title: Co-Lead
GitHub Handle: fyliu
Slack Member ID: UCE01B4AX

Name: Alejandro Gomez
Title: Co-Lead
Github: agosmou
Slack Member ID: U04HFRQ5Y12

Name: Harrison Katz
Title: Co-Lead
GitHub Handle: hkatzdev
Slack Member ID: U04PFCPK6EP

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge we need a new issue to change the engineering from mentor led to peer led

**Comment by roslynwythe** [comment]
- New issue (but needs to be finalized with final text) #4239 
- @MicahBear please provide updated text to describe the change from mentor led to peer led.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe what updated text are you looking for.  That was my change, not @MicahBear 

I just wanted to change it from 
Leadership Type: Mentor Led
to 
Leadership Type: Peer Led

similar to how UI/UX is
![image](https://user-images.githubusercontent.com/37763229/226976219-6f686390-c4d6-458b-9049-4061909064a7.png)

**Comment by roslynwythe** [comment]
- @ExperimentsInHonesty I'm sorry, I wasn't sure what precise changes were required in #4239.  Thank you @MicahBear for updating the issue appropriately.
