### ISSUE TITLE
Bug: Create a Function To Sort Project Meeting Times

### ISSUE THREAD

**Issue by plang-psm** [hackforla/website#4028]
### Overview

The Projects page is currently displaying the meeting times out of order due to the way it was entered into VRMS. We need to implement a sorting function to prevent times from being displayed out of order.

### Begin by reading through the issue and pull request listed below to better understand where and what files need to be changed:

- [x] #3890 
- [x] [Merged Pull Request for 3890](https://github.com/hackforla/website/pull/3939)
<details>
<summary>Image of Issue via Food Oasis Project Page</summary>
<img width="368" alt="image" src="https://user-images.githubusercontent.com/101952500/220834900-9729bd08-3959-422c-b5f6-ecb53209203b.png">

</details>

### Once you have a good understanding, begin the action items below:
- [x] Navigate to the `assets/js/project.js` file
- [x] Locate the `function appendMeetingTimes(scheduleData)` on line 127
- [x] Create a function to sort the meeting times rendered in the function
   - Make changes to the `function appendMeetingTimes()` if needed
- [x] Document the code with a comment above your function indicating its purpose.

### Resources/Instructions

- [assets/js/project.js file](https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js)
- [VRMS Data](https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json)
   - Holds the data. Use command(ctrl) + F to search for startTime, endTime, description, etc. 
- #3890 
- [Merged Pull Request for 3890](https://github.com/hackforla/website/pull/3939)

**Comment by bootcamp-brian** [comment]
Availability: Sun 2/26
ETA: End of day Sun 2/26

**Comment by ExperimentsInHonesty** [comment]
@bootcamp-brian please move this to the inprogress column

**Comment by bootcamp-brian** [comment]
@ExperimentsInHonesty Thanks for the reminder.

**Comment by bootcamp-brian** [comment]
Provide Update
1. Progress: Committed my updates and submitted pull request for review.
