### ISSUE TITLE
Wiki: Document Wins Page `on form submit` :  Wins Page

### ISSUE THREAD

**Issue by blulady** [hackforla/website#4033]
### Overview
We need to document how the Wins Page's `on form submit` trigger works and add it to the Wiki 

### Action Items
- [x] Identify how the wins page `on form submit` trigger works
  - [x] Note that `on form submit` runs two different functions in the script
- [x] Add a subpoint to the [wiki](https://github.com/hackforla/website/wiki/Automations-for-Wins-page-using-Google-Apps-Script) where the `on form submit` is mentioned
- [x] Review the [wiki](https://github.com/hackforla/website/wiki/Automations-for-Wins-page-using-Google-Apps-Script) to make sure it has good formatting, grammar, spelling
- [x] Check to see if there are more resources  for the Wins Page but not included here and add them to the Wiki if applicable
- [x] When you have finished the wiki, place this issue into the "Questions/In Review" column of the project board and put a `ready for dev leads` label
- [x] Let Bonnie know/show it to Tech Leads so they can bring it to Bonnie

### Resources/Instructions
- [Automations for Wins page using Google Apps Script Wiki](https://github.com/hackforla/website/wiki/Automations-for-Wins-page-using-Google-Apps-Script)
- [Wins Page Wiki](https://github.com/hackforla/website/wiki/Wins-page)
- [Wins Form Admin Guide](https://docs.google.com/document/d/1j1JTX5XzotgVCVZ91ImvenedPN5-IVjdSKDukq1B9iE/edit#)
- [Google Apps Script attached to Wins-Form(Responses)](https://script.google.com/home/projects/18uQ6VT7PGZ5skTLD-KDACf3DpMCMPi0WCcl2hBKhTFhi8F0tJKuq0Z9A/edit)
- [Wins Form Responses](https://docs.google.com/spreadsheets/d/1fXmYrmNtrgdzkM_odGIRbSwdaea3yS0cTLCJUzZ6Sc0/edit#gid=1706218917)
- #3735

**Comment by richardmundyiii** [comment]
Availability: M-F 6am - 8am, 8pm-10pm
ETA: EOD 3/20/2023

**Comment by richardmundyiii** [comment]
Updated Wiki document for Wins Page's 'on form submit'. Added subpoints and sub-subpoints to demonstrate what the functions are doing and in what order.

**Comment by richardmundyiii** [comment]
As approved by Bonnie on 3/19/2023
