### ISSUE TITLE
Update wins Google Apps Script to format wins json feed

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4035]
### Dependency

- [x] #3641 
- [x] #4134
- [x] #5746

### Overview

Currently the wins JSON feed contains no line breaks or spaces separating elements and so it is difficult to review Pull Requests for wins data updates.  By formatting the JSON with each submission on a separate line and with use of spaces to indent, readability  will be improved and JSON feeds could be compared more efficiently.  

### Action Items

- [x] Request VIEW access to the Wins Form Admin Guide Doc, the Wins-form (Response) Sheet, and gh-requests Doc from the dev lead
- [x] Read the Wins Form Admin Guide to understand the flow of wins data.  
- [x] This issue will require modification of the code within the `Wins-form (responses)` sheet, but you will require a test environment that includes copies of `Wins-form (Responses)` and `gh-requests`.  It will also be necessary to setup a test environment in your GitHub repository.  Follow instructions in the comment in the Hfla Google Apps Script Development Guide[^1] and Testing WINS in a test repository[^2]  
- [x] Once you have made copies of the required documents, let the dev lead know that access can be ended.
- [x] In the Google Apps Script module Code.gs in the project WinsFormResponse, which is bound to `Wins-form (Responses)` Sheet, update main() to format the _wins-data.json feed, either using options built into the JSON.stringify method, or a different method.  Required features are: 
  - [x]  Line Breaks separating array items (where each array item represents the data for a contributor)
  - [x]  Line Break with spaces indenting properties within each array item
- [x] Test the code by running main() in debug mode.  A new pull request "Update wins-data.json via Google Apps Script" should be appear in your test repository.  Examine the json data and if it looks good, merge into your repository test branch and examine the resulting Wins page. 
- [x] Add/commit `Code.js` and create a pull request as usual 
- [x] In the pull request, provide links to the "Update wins-data.json via Google Apps Script" Pull Request and also the Wins page (both in your repository), for the convenience of reviewers. 
- [x] Contact a dev lead to discuss review/demonstration 

### Dev Lead
- [ ] Remove VIEW access to all protected documents

### Resources/Instructions

-  sample PR for  updating wins data #4029
- (https://github.com/hackforla/website/issues/4134#issuecomment-1741851926)
-  [Wins data (json)](https://github.com/hackforla/website/blob/gh-pages/_data/external/_wins-data.json)
-  [Wins webpage](https://www.hackforla.org/wins)
-  [wins.html](/hackforla/website/blob/gh-pages/pages/wins/wins.html)
-  [Wins js](/hackforla/website/blob/gh-pages/assets/js/wins.js)
[^1]:[Hfla Google Apps Script Development Guide - draft](https://github.com/hackforla/website/issues/4134#issuecomment-1741851926)
[^2]:[Testing WINS in a test repository](https://github.com/hackforla/website/issues/5746#issuecomment-1846549069)

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe This was in the icebox with dependencies, which have now been cleared.  It is still missing a size and probably could use a once over by you to make sure that it's still good to go and does not need any other updating.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty I added a new dependency, moved issue back into Ice Box

**Comment by roslynwythe** [comment]
- This is ready to go when the last dependency is closed.  The only change at that time will be to link to the specific relevant comments in #4134 and #5746

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty For security reasons, I did not provide links to the Google Apps Scripts.  The dev lead will know where they are.  

- I applied the `Time Sensitive` label because an issue has come up with merge conflicts in recent the Wins https://github.com/hackforla/website/pull/5767  and it is difficult to solve without being able to do a line by line comparison.

**Comment by Jung-GunSong** [comment]
i. From today, 1/24/24 to next week, 1/31/24.

ii. Likely by next week (unsure because some guidance might be needed to set up the test environment).

As always, let me know if there's anything else I can help with!

**Comment by roslynwythe** [comment]
Issue noticed on #4706
The drop downs on the wins page sometimes are very small, and it forces the content in them to wrap, but there is plenty of room on the page at the time.
<details><summary>screenshot</summary>
<p>
![image](https://github.com/hackforla/website/assets/37763229/cfd12419-9cde-493e-9dda-3890527650b7)

</details>
