### ISSUE TITLE
Fix the meeting names for project details page

### ISSUE THREAD

**Issue by MattPereira** [hackforla/website#4054]
### Overview
On the events and project details pages, we are currently showing the meetings `details` as the name of the meetings. For this issue, we will change it to show the meeting `name` instead.

### Action Items
- [x] Change the `project.js` file to show meeting names instead of meeting descriptions on the individual project details pages ( i.e. https://www.hackforla.org/projects/vrms )
- [x] Change the `api-events.js` file to show the meeting `name` instead of `description` on the [events](https://www.hackforla.org/events/) page
- [x] Check that the VRMS meeting on "Sun 7:00 pm - 8:00 pm" displays the name `VRMS All Team` and NOT `Only this part will show website` on both the [VRMS details page](https://www.hackforla.org/projects/vrms) and the [Events Page](https://www.hackforla.org/events/)

### Instructions
- Do not merge the PR associated with this issue until VRMS and Bonnie are ready sometime on Sunday March 5th

### Resources

<details><summary>The Event Object coming from VRMS API for the VRMS Sun 7 - 8PM meeting </summary>

![image](https://user-images.githubusercontent.com/73561520/221921509-44cfaf1f-0b26-4c4f-8f97-ad0aac581887.png)

</details>

<details><summary>Events Page</summary>

![image](https://user-images.githubusercontent.com/73561520/221915523-381f168e-d062-437e-bb96-bbf11fedd530.png)

</details>

<details><summary>VMRS details page</summary>

![image](https://user-images.githubusercontent.com/73561520/222872483-08c00774-d0fb-43b9-97d4-2a7e16f54444.png)

</details>

**Comment by ExperimentsInHonesty** [comment]
@MattPereira I'll be at the VRMS meeting on Monday so that we can talk about what happened when I tried to get product managers to change the times.  Has the product team discussed new tickets based on the feedback the PMs gave in this issue? https://github.com/hackforla/VRMS/issues/1178?
