### ISSUE TITLE
Change title in criminal-sentencing.md

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4081]
### Overview
We need to shorten the `title` for the LA Criminal Sentencing Project so that its name fits the mini-card on the [program areas page](https://www.hackforla.org/program-areas).

### Action Items
- [x] Change the title to 
```
LA Criminal Sentencing
```
- [x] Check in your local environment that the title does not run off the mini-card like it does below:

![image](https://user-images.githubusercontent.com/88953806/222292910-14e71527-c2af-4232-9942-aee2f5dcab57.png)

### Resources/Instructions
- [criminal-sentencing.md](https://raw.githubusercontent.com/hackforla/website/gh-pages/_projects/criminal-sentencing.md)

**Comment by nicolettedmabeza** [comment]
i. Availability: 3-5pm PST
ii. ETA: 3/5

**Comment by ExperimentsInHonesty** [comment]
@nicolettedmabeza Congrats on making your first PR.  From now on, please only assign yourself issues that are in the prioritized backlog.  The new issue approval column is designated for issues that are not yet ready to work on.  For instance, this one was missing a milestone.  So there might have been another good first issue that was a higher priority.
