### ISSUE TITLE
Change title and description in not-today.md

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4082]
### Overview
We need to shorten the `title` for the Not Today Project so that its name fits the mini-card on the [program areas page](https://www.hackforla.org/program-areas), and we need to change its `description` so it is more inviting. 

### Action Items
- [x] Change the title to 
```
Not Today
```
- [x] Change the description to
```
Not Today - the self-defense against suicidal thoughts app is intended to help people wait out periods of suicidal thinking without acting on their thoughts.
```
- [x] Check in your local environment that the title does not run off the mini-card like it does below:

![image](https://user-images.githubusercontent.com/88953806/222293813-55081402-3a43-4bb4-9eb1-9611fbc21d22.png)

### Resources/Instructions
- [not-today.md](https://raw.githubusercontent.com/hackforla/website/gh-pages/_projects/not-today.md)

**Comment by mattmalane** [comment]
**Availability for this week:** Mon, Tue, Wed 3PM - 5PM PST
**My estimated ETA for completing this issue:** Mon, March 6 5PM PST
