### ISSUE TITLE
Edit the Getting Started Page to Correct Steps in Onboarding Card

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4083]
### Overview
The herokuapp used to link the public Slack invite onto the [Getting Started](https://www.hackforla.org/getting-started) is no longer functioning, so we need to remove this step from the Onboarding Card. 

### Action Items
Currently, the Onboarding card looks like this
<details>
<summary>Onboarding card</summary>

![image](https://user-images.githubusercontent.com/88953806/222296878-f7cc8ac9-4fe5-42d5-ac27-ffc58a11ef38.png)
</details>

![image](https://user-images.githubusercontent.com/88953806/222298155-b2dc2e7b-0ee2-447a-b52e-9f359e41ed8b.png)
but if a user were to click the Slack invite, they are redirected to this 

<details>
<summary>Deadlinked page</summary>

![image](https://user-images.githubusercontent.com/88953806/222296941-61bcc834-5cfa-444c-bbf2-769defb794fc.png)

</details>

- [x] Remove the current Step 1
- [x] Make "Read the [Hack for LA Code of Conduct](https://github.com/hackforla/codeofconduct)." Step 1 under "Before the Meeting:"
- [x] Make "Complete our [Onboarding Survey](https://docs.google.com/forms/d/e/1FAIpQLScXnJSyCXgO_RCAuCyOkG4sqGILpAepTlJ0HOaK4H_ccEVmNw/viewform)." Step 2 under "After the Meeting:"

### Resources/Instructions
- [Getting Started page](https://www.hackforla.org/getting-started)

**Comment by mattmalane** [comment]
**Availability:** Tue 5PM-7PM PST, Wed 5PM-7PM PST
**ETA:** Wed 5PM
