### ISSUE TITLE
Adjust Alignment on Getting Started in Mobile View

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4084]
### Overview
The Getting Started Page shows a step-by-step graphic that changes alignment when a user views it in a responsive viewport, so we need to adjust the alignment so that it looks clean and professional.

<details>
<summary>Getting Started page in desktop view</summary>

![image](https://user-images.githubusercontent.com/88953806/222298870-cf335c84-855e-4f79-8e6f-ee9a420eeb9d.png)

 </details>

<details>
<summary>Getting Started page in mobile view (1027px x 842px)</summary>

![image](https://user-images.githubusercontent.com/88953806/222299355-6567fada-351a-486d-8baf-53875e39870a.png)

</details>

<details>
<summary>Getting Started page in mobile view (1010px x 842px)</summary>

![image](https://user-images.githubusercontent.com/88953806/222299612-87811b50-b04b-42bb-a0b6-83704fa5c81c.png)

</details>

### Action Items
- [x] View the [Getting Started](https://www.hackforla.org/getting-started) page in various viewport sizes to see how the text and graphics respond
- [x] Adjust the spacing between the text and the graphics in mobile view so the graphics remain in line with each other
  - [x] Consider bottom aligning the graphics so they do not move independently

OR
  - [ ] Find alternative ways to display the text and graphics in mobile views without changing the general look of it

### Resources/Instructions
- [_getting-started.scss](https://github.com/hackforla/website/blob/a8d86b813c914f75fffd0f649907c01fe57e5f4b/_sass/components/_getting-started-page.scss)
- [Working with Flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/)

**Comment by jch1013** [comment]
Availability: after 3PM T,Th,F
ETA: March 11

**Comment by Jaretzbalba** [comment]
@jch1013 I'm moving this issue over to the `in progress` column so that no one accidentally works on this issue as well!
