### ISSUE TITLE
Communities of Practice information updates: Ops

### ISSUE THREAD

**Issue by JasonEb** [hackforla/website#4085]
### Overview
As a co-lead of the Ops Community of Practice, I want my project's details to be up to date on the HackforLA website. As developers, we need to update the Ops' CoP leadership information.

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_data/internal/communities/ops.yml` file and find the `leadership` variable.
- [x] Remove Nicole Dubin from the leadership section
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
  - [x] Name: Dean Church
Title: Co-Lead
GitHub Handle: Rankazze
Slack Member ID: UJR0UKBN1
- [x] Verify the changes by viewing the Ops section on the [Communities of Practice page](https://www.hackforla.org/communities-of-practice) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [ops.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/communities/ops.yml)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by jdingeman** [comment]
Remove person(s) and info from CoP file?
YES

If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:
Name: Nicole Dublin

Add person(s) and info to CoP file?
YES

If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:
Name: Dean Church
Title: Co-Lead
GitHub Handle: n/a
Slack Member ID: UJR0UKBN1

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - if Dean does not have a github, then do you want some other link to be used for the `github` and `picture` field?

**Comment by ExperimentsInHonesty** [comment]
@jdingeman he has one.  I added it.

**Comment by Sebster3** [comment]
ETA: 5PM 3/17/23
Availability: 3-5PM M/Th/F
