### ISSUE TITLE
Communities of Practice information updates: UI/UX

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/website#4087]
### Overview
As a co-lead of the UI/UX Community of Practice, I want my project's details to be up to date on the HackforLA website. As developers, we need to update the UI/UX's CoP leadership information.

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_data/internal/communities/ui-ux.yml` file and find the `leadership` variable.
- [x] Add the new team members `name`s, `role`s, `slack` links, `github` links, and `picture` to the `leadership` variable
  - [x] Name: Jennifer Nguyen
Title: Co-Lead
GitHub Handle: nguyen-jenn
Slack Member ID: U04K89GRNDS
- [x] Verify the changes by viewing the UI/UX section on the [Communities of Practice page](https://www.hackforla.org/communities-of-practice) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [ui-ux.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/communities/ui-ux.yml)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by ExperimentsInHonesty** [comment]
I approve the change.   Please reformat for devs

**Comment by jdingeman** [comment]
Remove person(s) and info from CoP file?
NO

If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:
No response

Add person(s) and info to CoP file?
YES

If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:
Name: Jennifer Nguyen
Title: Co-Lead
GitHub Handle: nguyen-jenn
Slack Member ID: U04K89GRNDS

**Comment by arcan9** [comment]
Availability for this week: 

- 03/15 after 5PM PST
- 03/16  - 03/18 | 2PM to 8PM PST

My estimated ETA for completing this issue: 03/13 by 5PM PST.
