### ISSUE TITLE
Hero Photo for 311 Website Page

### ISSUE THREAD

**Issue by Ambmoney** [hackforla/website#409]
#Description
Photo needed for the 311 website page. This should be size 1500x 700

## Action Items

- [ ] Decide with team on best photo.

- [ ] Schedule Photo Shoot

- [ ] Send photo to John

**Comment by ExperimentsInHonesty** [comment]
Issue is ready to be worked.  Simply replace current hero image with provided image.

**Comment by parkderick** [comment]
Submitted pull request issue #409
