### ISSUE TITLE
Fix artist's name for Coding credit for redesigned homepage

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4111]
**Note:** Numbers in brackets (example: [1]) refers to the numbered item in the Resources/Instructions section.

### Overview
We need to fix a misspelled name on a credit for an image used in the redesigned version of the homepage so that the Credits page [1] is accurate.

### Details
From the Homepage Redesign Credits in Figma [2], here is a screenshot of the credit's information for reference and how the artist's name should be spelled:
  <details>
    <summary>Click here to see the screenshot of the Coding credit in Figma</summary>
    <img height="200" src="https://user-images.githubusercontent.com/31293603/175393444-ef5d9cdc-ca7d-4ee7-8779-eebcbc459c99.png" alt="">
  </details>

Here is a screenshot of the current credit on the Credits page on the feature-homepage-launch branch:
  <details>
    <summary>Click here to see the screenshot of the Coding credit on the feature-homepage-launch branch</summary>
    <img height="200" alt="" src="https://user-images.githubusercontent.com/31293603/222934910-d2840c06-266a-49a5-9348-e10abd87cb9b.png">

  </details>

### Action Items
- [x] **Feature Branch:** You will be working off a feature branch called `feature-homepage-launch`. Please follow ["Step 1: Create your branch" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-1-create-your-branch) wiki article.
- [x] For `_data/internal/credits/coding.yml`, switch the `t` and `z` in the last name so that
  ```
  artist: Ralf Schmizter
  ```
  becomes
  ```
  artist: Ralf Schmitzer
  ```
- [x] To update your topic branch, please follow ["Step 2: Update your branch with upstream changes" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-2-update-your-branch-with-upstream-changes) wiki article.
- [x] The pull request created from this issue should be merged into `feature-homepage-launch`. Please follow ["Step 3: Create a pull request" in How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch#step-3-create-a-pull-request) wiki article
  
### Resources/Instructions
1. [Credits page](https://www.hackforla.org/credits/)
2. [Homepage Redesign Credits in Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17951%3A122724)
3. [How to work off of a feature branch](https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch)
4. [_data/internal/credits/coding.yml on feature-homepage-launch branch](https://github.com/hackforla/website/blob/feature-homepage-launch/_data/internal/credits/coding.yml)
5. [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)
6. This is a follow-up issue to #3130

**Comment by jefflueck** [comment]
Availability: Tuesday, Thursday, and Saturday 10 am - 6 pm CST
ETA: 3/22/23

**Comment by jdingeman** [comment]
Closing this issue as the change has been merged. Not sure why the automation did not kick in.
