### ISSUE TITLE
Remove Slack self-invite link from CoP page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4132]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview

The Slack self-invite link previously hosted by Heroku is no longer active.  Instead we need to direct potential members to the Getting Started page. 

### Action Items

- [x] On the [Communities of Practice page](https://github.com/hackforla/website/blob/gh-pages/pages/communities-of-practice.html), replace the html
```
<p class="alert--communities">To join the Slack channels below, you first need to be a member of our Hack for LA Slack Community – you can self-invite <a href="https://hackforla-slack.herokuapp.com" target="_blank">here</a>.
</p>
```
with
```
<p class="alert--communities">To join the Slack channels below, you first need to be a member of our Hack for LA Slack Community. If you have not joined yet, please follow the steps in <a href="/getting-started" target="_blank">Getting Started</a>.
</p>
```

 

  

### Resources/Instructions

- [Communities of Practice webpage](https://www.hackforla.org/communities-of-practice)
- [Getting Started webpage](https://www.hackforla.org/getting-started)

**Comment by jdingeman** [comment]
Hi @ExperimentsInHonesty - I think this looks good. Let us know if you'd like it worded differently. Added this to Onboarding Flow but wasn't sure if it should be Technical Debt instead.

**Comment by kimberlytanyh** [comment]
Availability: Friday (3-10PM), Saturday (10AM-5PM)
ETA: 2 hours, EOD (3/10/2023)
