### ISSUE TITLE
Update Self-Invite Link for the Slack Icon in the Footer of the Website

### ISSUE THREAD

**Issue by Adastros** [hackforla/website#4141]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Slack self-invite link previously hosted by Heroku is no longer active. Instead, we need to direct potential members to the Hack for LA Slack channel.

### Action Items
- [x] Change the link value of the icon in the `social.yml` file:

**From:**
```
https://hackforla-slack.herokuapp.com/
```

**To:**
```
https://hackforla.slack.com
```

### Resources/Instructions
- [Hack for LA Website](https://www.hackforla.org/#)
- [social.yml file](https://github.com/hackforla/website/blob/gh-pages/_data/navigation/social.yml)

**Comment by ftblmagician** [comment]
i. Availability: 7-9am 
ii. ETA: 3/11/23

**Comment by ftblmagician** [comment]
We changed the self-invite link previously hosted by Heroku to the Hack for LA Slack channel. We made the change because the Heroku link is no longer active.
