### ISSUE TITLE
Update Slack Link on Program Areas Page

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4142]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
At the bottom of the Program Areas page, there is section called 'Join a Project' that refers new volunteers to `join our slack` via an embedded link. We want this to change so that new volunteers are referred to our onboarding process in 'Getting Started'. 

### Action Items
On the [Program Areas](https://github.com/hackforla/website/blob/gh-pages/pages/program-areas.html) page:

- [x] Change the text in the join-us-footer first paragraph from:
```
To join any of the projects click through their project pages for details on getting started.
```
to
```
We are looking for volunteers of all different skill types, levels, and civic interests. If you have not joined yet, please see the <a href="/join" target="_blank">Join Us</a> page. 
```
- [x] Delete the entirety of the join-us-footer second paragraph as shown here:
```
<p class="second-paragraph">
          The projects that are in formation are not yet on our website. To 
          connect with the current project team <a href="https://hackforla-slack.herokuapp.com/"> join our slack</a> and 
          browse for their channel name.
</p>
```

### Resources/Instructions
[Program Areas webpage](https://www.hackforla.org/program-areas)
[program-areas.html](https://github.com/hackforla/website/blob/gh-pages/pages/program-areas.html)

**Comment by ExperimentsInHonesty** [comment]
Hi @t-will-gillis I am not sure I understand the need for this part of the change, please provide reasoning

- [ ]  Change the button from:
```
<a href="/join" class="btn btn-primary btn-md btn--default">Join Us</a>
```
to
```
<a href="/getting-started" class="btn btn-primary btn-md btn--default">Getting Started</a>
```

**Comment by t-will-gillis** [comment]
Hi @ExperimentsInHonesty - Edited to keep the 'Join Us' button as is, with the addition of an embedded link to the 'Getting Started' page within the text instead.

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis I think there is a misunderstanding of what product wants.  When can we discuss in person?

**Comment by t-will-gillis** [comment]
Hi @ExperimentsInHonesty I can anytime today, 3/16- I am available right now if you want.

**Comment by Sebster3** [comment]
ETA: EOD 3/20
Availability: 7PM-9PM 3/20
