### ISSUE TITLE
Update Slack Link on Join Us Page

### ISSUE THREAD

**Issue by MattPereira** [hackforla/website#4145]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview

The Slack self-invite link on the Join Us page's Advise Us card is broken. Instead, we need to direct potential members to the Getting Started page. 

### Action Items

- [ ] On the [Join Us page](https://www.hackforla.org/join), change the "Advise Us" card's first `<li>` element 

from 
````
<li>Join our <a href="https://hackforla-slack.herokuapp.com/" target="_blank">Slack</a></li>
````
to 
````
<li>Follow the steps on our <a href="/getting-started" target="_blank">Getting Started</a> page</li>
````

### Resources/Instructions

- [Join Us Page](https://www.hackforla.org/join)
- [Getting Started webpage](https://www.hackforla.org/getting-started)

**Comment by kwangric** [comment]
i. Availability: 3/17 after 1pm PDT
ii. ETA: 3/17 3pm PDT

**Comment by ExperimentsInHonesty** [comment]
I am moving this issue to the in progress column.  Please do that yourself next time you self assign.
