### ISSUE TITLE
Add id value to yml collection

### ISSUE THREAD

**Issue by steven-positive-tran** [hackforla/website#4146]
### Dependency

- [x] #2216
- [x] #4188 

### Prerequisite

1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).

2.  Please make sure you have read our [Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview

As a developer, we want to add an id key pair value to each component so that when we program in the backend we can refer to each component using the id or create components of certain elements using an id.

From jyaymine #2216 

> 
> 
> Okay, so here is the gist. In HTML the id attribute is used to identify an HTML object. For example:
> 
> ```
> <div id="div-1" />
> ```
> 
> Now imagine that you have a function that programmatically inserts these ids, say for instance:
> 
> ```
> function add_ids_to_divs(id):
>   div.add(id)
> ```
> 
> This function will work in code, but when the resulting <div> is rendered through the brower's engine the HTML will crash if we insert [any values that does not follow the HTML5 standard](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute). In order to work around this then, we need checks to:
> 
>     1. make sure all ids are unique
> 
>     2. make sure that there are no spaces
> 
>     3. make sure that there is at least 1 character
> 
> 
> But imagine if we need to reuse this id, for some other function, which has other criteria such as:
> 
>     1. it cannot have symbols
> 
>     2. it cannot container upper cases
> 
> 
> You can see how this will increasingly constrain the id and make it near impossible to account for. Since we are using some visible field to construct the ID, such as the project's name, we need to apply escaping, since we cannot simply change the name directly to use it as an id field (we do not want to end up displaying "HackforLA Website" as "HackForLAWebsite").
> 
> Therefore, we need some other value that can act as a value for the id attribute in html tags. This value should not be displayed, so we do not have to worry about how it'll appear to visitors, should not change, and also be unique (that way, we can use the id as exceptions, such as in `if id is "12345" then do this`).

### Action Items
- [ ]  For each yml file add an id key value for each component.
    - [ ] For community, press, credits, and program-area each component are in a seperate yml file
    For example using communities/data-science
```
    name: Data Science
    description: This group is a space where data science professionals from different projects can come together to share effective 
    ...


    id: communities_id
```

- [ ] The rest all the components are in the same file so you have to add the id key pair value to each.
For example in internal/accomplishments.yml
```
- title: National Day of Civic Hacking (NdoCH)
  ...
  id: accomplishment_id
- title: Food Oasis
  ...
  id: accomplishment_id

  etc
```
    

### Resources
- https://docs.google.com/spreadsheets/d/1km7lvlJfkbzjvL4ZNSL2SVaxj8q29C-ObTW_mdkymHE/edit#gid=886605444
- #2216

**Comment by ExperimentsInHonesty** [comment]
@steven-positive-tran FYI
- I moved this issue to the `new issue approval column` the only issues that go in the icebox are ones with unresolved dependencies, and I see that you are actually trying to close the other issue.  See my notes on #2216 about how to close.
- I reformatted the issue to conform to our standard issue template.  I don't know if we use prerequisites on issues other than good first issue, but it's causing no harm, so I left it.  

Here is the standard formatting.

```
### Dependencies
ANY ISSUE NUMBERS THAT ARE BLOCKERS OR OTHER REASONS WHY THIS WOULD LIVE IN THE ICEBOX

### Overview
WE NEED TO DO X FOR Y REASON

### Action Items
A STEP BY STEP LIST OF ALL THE TASK ITEMS THAT YOU CAN THINK OF NOW EXAMPLES INCLUDE: Research, reporting, etc.

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.
```

**Comment by ExperimentsInHonesty** [comment]
@steven-positive-tran generally small issues aren't 2pts.  I am not saying it could not be, but just want you to double check that.  This seems more like a medium or large size issue.

**Comment by jdingeman** [comment]
Message from @ExperimentsInHonesty: I don't doubt this issue needs to be done, but I would like to know more about it, we need a wiki page that explains the usage https://github.com/hackforla/website/issues/4146 Also, I need to know more about it so I can add the milestone properly. For now I am going to assume its related to making the accomplishments on the about page work, so i'll put it in Know HfLA. 

From merge team: When will you be able to come to a meeting so we can discuss this?

**Comment by ExperimentsInHonesty** [comment]
- @steven-positive-tran While going through your other issues I found this issue https://github.com/hackforla/website/issues/2216 which explains more the reasoning behind the the ids.  Please add more of the info from the previous issue to this issue in the top portion, so that it's clearer here.

**Comment by jdingeman** [comment]
@ExperimentsInHonesty, I think this could either be 1 issue working across all the files, or turn into an epic with a bunch of smaller issues since it is multiple files.

@steven-positive-tran, for those that say `id: accomplishment_id` are you saying they should _just_ be `id: accomplishment_id` or would the id be something like 

````
- title: National Day of Civic Hacking (NdoCH)
  ...
  id: accomplishment_nationaldayofcivichacking
- title: Food Oasis
  ...
  id: accomplishment_foodoasis

 etc
````

**Comment by steven-positive-tran** [comment]
I was thinking ```id: accomplishment_id``` because in my eye we are just listing and not doing anything unique with each and every individual accomplisments.
![image](https://user-images.githubusercontent.com/56055132/230554371-e020c8f9-508b-4ee7-9296-3e914f13efc0.png)

**Comment by ExperimentsInHonesty** [comment]
@steven-positive-tran @jdingeman We are in the process of re-architecting the accomplishments section on this issue https://github.com/hackforla/website/issues/4188 (see also notes).  So I want to put reviewing this issue on hold until that issue is addressed, unless you have a different use case where adding IDs is needed now.

- If there is no other use case, please put a dependency label on this issue, add #4188 under dependency and stick this in the icebox.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I moved this into the new issue review column because the dependency is resolved. Please add a ready for prioritization label if its ready.

**Comment by roslynwythe** [comment]
@steven-positive-tran @ExperimentsInHonesty  I am not entirely convinced of the need for this issue but if we do puruse it, I advise that each item in each yml file (for example, each accomplishment) should be assigned a unique id.  Regarding the composition of the ids, I like Justin's suggestion above:
```
- title: National Day of Civic Hacking (NdoCH)
  ...
  id: accomplishment_nationaldayofcivichacking
- title: Food Oasis
  ...
  id: accomplishment_foodoasis

 etc
```

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty I am not convinced of the need for this issue.  The audit was not clear on this point but I am not aware of any webpages in which it has been necessary to include an `id` attribute.  If the need arises to include an `id` attribute when generating HTML elements from YML data, it would seem that there are programmatic means of composing unique ids, that would be more reliable than manually maintaining ids.

**Comment by ExperimentsInHonesty** [comment]
We have not found a compelling reason for this doing this, at this time, or in the near future.
