### ISSUE TITLE
GHA to list inactive members

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4158]
### Overview
As a technical lead, I want to ensure that we are staying up to date with our active roster. We need to create a GitHub Action that will automatically create an issue listing users who are tagged as inactive based on specific criteria so that we can review and keep our roster and calendar events up to date.

### Pseudocode
- [x] Become familiar with [HfLA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
  - [x] If you have not already done so, create a copy of the Project Board into your own repo ([Tip 6: Creating your own Project Board](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-6-creating-your-own-project-board))
  - [x] Be sure to read up on using Personal Access Tokens to test the project board in your own repo ([Tip 7: Using Personal Access Tokens to test in your own Project Board](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-7-using-personal-access-tokens-to-test-in-your-own-project-board))
- [x] Use GitHub API to get a list of all members of the [website-write](https://github.com/orgs/hackforla/teams/website-write) team
- [x] Set up the action to run on the **last day of the month at 11:45pm**
- [x] Loop through each member
  - [x] If a member has no open issues
    - [x] Add member's GitHub handle to a list (do not include the @ symbol)
    - [x] After the GitHub handle, there should be a newline so there is one handle per line (think of a shopping list)
- [x] Open a new GitHub issue
  - [x] Title == "Review Inactive Members"
  - [x] Add list to issue text body
  - [x] Add labels:
    - [x] `Ready for dev lead`
    - [x] `Ready for product`
    - [x] `Complexity: Small`
    - [x] `Size: 0.5pt`
- [x] Place new issue onto Project Board
  - [x] Note that new issues submitted into the project board are already automatically moved to the New Issue Approval column with an existing Built in GitHub Action for Project Board Automation Classic. When testing in your local repo, ensure that the new issues are following this GHA.   Use the instructions in this [GitHub help file for automating a new issue into the ToDo column when added to the board](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/configuring-automation-for-project-boards) - p.s. we call our column `New Issue Approval` but it uses the todo automation.
- [x] When the issue is created, have the GHA write a comment on https://github.com/hackforla/website/issues/2607 so Dev Leads and PMs can review during the planning weeks
  
### Resources/Instructions

- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
- [GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)
- [GitHub RESTAPI](https://docs.github.com/en/rest)
- HfLA [GitHub Action](https://github.com/hackforla/website/tree/gh-pages/.github/workflows) workflows
- HfLA [GitHub Action](https://github.com/hackforla/website/tree/gh-pages/github-actions) JavaScript files

**Comment by ExperimentsInHonesty** [comment]
@jdingeman Great job on this issue.  I am concerned that the list will end up like this
experiementsinhonesty jdingeman roslynwythe and be kind of unreadable.  Can we specify comma delimited or one on each line?

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - excellent catch.

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - was about to prioritize but then I realized I never put a frequency of the GHA run. How often should we have the GHA run?

**Comment by ExperimentsInHonesty** [comment]
@jdingeman 

I think after this happens 

> Place issue onto Project Board

This happens automatically because of the GitHub automation we are already using

>  Move issue to New Issue Approval Column

So it might just be a matter of confirm its moving it to the New Issue Approval Column

**Comment by ExperimentsInHonesty** [comment]
@jdingeman you asked how often
> @ExperimentsInHonesty - was about to prioritize but then I realized I never put a frequency of the GHA run. How often should we have the GHA run?

I think monthly should do it.  Maybe have it be the last day of the month at 11:42 or something.  That way we can address it during planning week.

Also, possibly it could leave a comment on the agenda issue with a link to the issue.  Do you think that's a good addition?

**Comment by jdingeman** [comment]
@ExperimentsInHonesty, I do think that's a good idea. Added that in and noted the GitHub automation of the New Issue Approval column.

**Comment by ExperimentsInHonesty** [comment]
We need steps for
### becoming a temporary admin

### Copying the project board https://github.com/hackforla/website/projects/7
#### Click the hamburger menu ![image](https://user-images.githubusercontent.com/37763229/226754801-9564660a-38d6-41a8-b440-78c85347498a.png)
<details>
<summary>See it on bottom right side of this image:</summary>

<img src="https://user-images.githubusercontent.com/37763229/226754659-22e845dc-979d-4f1e-b696-7e1f7ad2c32a.png" width=300px>
</details>

#### Click the three dots ![image](https://user-images.githubusercontent.com/37763229/226755142-25dbc8b6-f79e-4465-9db2-5f5987337247.png)

<details>
<summary>See it on bottom right side of this image:</summary>

![image](https://user-images.githubusercontent.com/37763229/226755052-1dce05b9-317d-4cdb-9139-8a1b624f6a1d.png)
</details>

#### Choose copy

#### In the modal make the following changes
- Owner: choose the repo you want to copy it to
- Project Board Name: remove the `[Copy] ` from the name
- Automation settings: leave it checked
- Visibility: change to Public

<details>
<summary>See the modal </summary>

![image](https://user-images.githubusercontent.com/37763229/226755311-fbd8fa93-7eac-49ae-b291-2cf30806e34a.png)
</details>

#### Choose `Copy Project` button

### removing admin permission
Reach out to the person who gave you the admin permission and let them know you are done, so that they can remove you from the [website admin team page](https://github.com/orgs/hackforla/teams/website-admins/members)

### changing the access tokens
[INSERT INSTRUCTIONS HERE OR A LINK TO THE FILE IF WE ARE KEEPING IT PRIVATE]

**Comment by ExperimentsInHonesty** [comment]
@jdingeman I want to move this issue along, so I wrote out all the steps I know how to do.  The only thing left is the instructions for changing the access tokens

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - per our discussion, devs won't need admin access to make a copy of the project board, and they should automatically have admin access to their own copies of the project board. Wrote up the section for using personal access tokens in the Wiki and added it at the beginning of the issue.

**Comment by ExperimentsInHonesty** [comment]
@jdingeman It does not tell them how to copy the board locally though in the top part of the issue.  Are you going to move that instruction to the wiki and link to it in this issue?

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - added to the Wiki on how to create a project board and linked to this issue.

**Comment by ExperimentsInHonesty** [comment]
@jdingeman where in the above does it have link to creating your own board in the wiki? I must be missing seeing the link

**Comment by jdingeman** [comment]
@ExperimentsInHonesty, it's Tip 6

**Comment by ExperimentsInHonesty** [comment]
When you do the PR, once it's merged and accepted, a dev lead should change it temporarily to run that day on the repo.  So we have the results to start working with.  Then we can go back to running once a month.

**Comment by bzzz-coding** [comment]
Availability: Tuesday and Thursday evenings, some Monday evenings and some weekends.
ETA: 4/20/23

Update: Unassigned myself so I can focus on other merge team responsibilities.

**Comment by bzzz-coding** [comment]
I see that this issue has a "time sensitive" label. Please let me know if this issue needs to be fixed before my ETA. In that case, I'll unassign myself. Thanks!

**Comment by mattmalane** [comment]
**Availability:** Mar 31 - April 7 3PM - 6PM Pacific
**ETA:** Friday April 7 6PM Pacific

**Comment by mattmalane** [comment]
@jdingeman Hi Justin, I have most of this issue finished and working on my local machine and cloned project board. I'm looking to get some input/help on two tasks:

1. Set up the action to run on the last day of the month at 11:45pm

Months have various last days. For example, April has 30 days in the month, May has 31 days in the month, February has 28 day in the month (29 on leap year). Multiple cron schedules can be specified for a job to cover all possible last days of each month, but will need additional logic to determine if the scheduled action is actually on the last day of the current month.

Would it be possible to schedule this job on the 28th of every month, or the 1st? I believe this would make the cron schedule less complex to implement.

2. Place new issue onto Project Board

When interacting with github's user interface, Github allows you to manually place issues into the project board without needing to place the issue in a particular column. This works well with the automation set up that places the new issues into the "New Issue Approval" column.

I've searched through the Github API and haven't seen an endpoint that allows me to create a project card/place an issue into the project board without **specifying a specific column**.

I have a working solution that places the issue into "New Issue Approval" column using the Github API, but it doesn't follow the action item's task of placing the issue into the project board without a specific column and having the automation handle placing it into the "New Issue Approval".

**Comment by mattmalane** [comment]
**Update**

**Availability:** April 10 - April 14 3PM - 6PM Pacific
**ETA:** Friday April 14 6PM Pacific

**Comment by mattmalane** [comment]
This weeks updated Availability and ETA

**Availability:** April 10 - April 14 3PM - 6PM Pacific
**ETA:** Friday April 21 6PM Pacific
