### ISSUE TITLE
Finalize UX surveys for administration

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#416]
### Overview
Review UX surveys for completion

### Action Items
- [x] Review all UX surveys for content and completion.
- [x] Identify categories of desired information and tag all questions by categories.
- [x] Produced finalized version of New Member and Remote Onboarding surveys.
- [x] Provide Wes with New Member survey update. New Member to be sent 2-4 weeks from date of remote onboarding.

### Resources/Instructions
**UX Survey Tracker** 
https://docs.google.com/spreadsheets/d/1kteHB0OlAssR5m5sVYopfO0aazCBGOYClYttaGHfR1s/edit#gid=0

**UX Survey Workbook**
https://docs.google.com/spreadsheets/d/1hvf8By61_7-DWViYFvKKuey1tdYLR-9nc7WCWjyu1dY/edit#gid=1802395225

**Comment by ashlingam** [comment]
1. Progress - Received feedback from @wesrowe concerning the Remote Onboarding survey. To discuss with him desired changes and review final version with @ExperimentsInHonesty. 
2. Blocks - None
3. Availability - Saturday, Sunday, Monday
4. ETA - 04-13-20

**Comment by ashlingam** [comment]
<img width="33" alt="Screen Shot 2020-04-12 at 3 09 41 PM" src="https://user-images.githubusercontent.com/21990572/79078701-bb429980-7ccf-11ea-898c-fc4655c05ab3.png"> @harishlingam  starting this chat to kick around thoughts on the onboarding survey we’re discussing how to evolve remote onboarding, that’s why i took a closer look today

i’ll thread a couple reactions to the qeustions as-is, the more interesting discussion to have is what questions help guide decisions

<img width="31" alt="Screen Shot 2020-04-12 at 3 09 30 PM" src="https://user-images.githubusercontent.com/21990572/79078710-ca294c00-7ccf-11ea-8fbb-1b2ea2413c92.png"> Hi @wesrowe - I think there is a tension here between keeping the survey economical and getting the information we want. To be clear, there is the Remote Onboarding survey, and the New Member survey to dispatch ~2 weeks after new member enrollment

<img width="33" alt="Screen Shot 2020-04-12 at 3 09 41 PM" src="https://user-images.githubusercontent.com/21990572/79078701-bb429980-7ccf-11ea-898c-fc4655c05ab3.png"> @harishlingam i agree with your “tension” observation. actually i think there are other questions about the remote experience that we aren’t asking yet but might want to. so that’s where i was coming from on reducing cognitive load.

but to your observation that so far people have filled out the whole thing — maybe hfla types can take the load and are less likely to drop off mid-way than average, just because they are awesome, engaged people!

<img width="33" alt="Screen Shot 2020-04-12 at 3 09 41 PM" src="https://user-images.githubusercontent.com/21990572/79078701-bb429980-7ccf-11ea-898c-fc4655c05ab3.png"> @harishlingam i’ll thread a couple reactions to the qeustions as-is, the more interesting discussion to have is what questions help guide decisions:

the “how is hfla handling comms during covid” question felt out of place to me. the target audience is noobs, they probably wouldn’t feel like they know enough to answer. and it has nothing to do with onboarding really (edited) 

the availability question — seems like it’s not about the onboarding, it’s… what, to help us place them on a team later? it’s not to schedule the onboarding… the argument for cutting is: since it’s relatively personal and hard to answer, there’s a cost to keeping it in here. it could drive frustration/dropoff

the questions tend to be “heavy” with choices, which translates to mental effort. if we have any evidence of dropoff (do we have analytics?), a place to look is reducing choices where possible. one place to look is skills, where each one is so nuanced. could get by with one dev, one design, etc

<img width="31" alt="Screen Shot 2020-04-12 at 3 09 30 PM" src="https://user-images.githubusercontent.com/21990572/79078763-14123200-7cd0-11ea-8a34-5d087be3aa74.png"> @wesrowe My thoughts to each of the reactions you've posted, in order:

This could potentially be reworded to focus on remote onboarding, although participants do have the option to select "Neither agree nor disagree."  The question on communication/outreach could be moved to the New Member survey.

I think a reason for this question to exist is to inform project leads of a new volunteers' availability (i.e. Many project leads or project members may seek regular or semi-regular meetings outside a team's scheduled weekly meetings). However, we have yet to establish a process for how availability information is consolidated or shared.

As far as survey analytics go, we can see responses for all completed forms. Of the 9 or so forms completed, all or nearly all have answered every question, but this is a small sample size. Drop-offs could become apparent down the road, but the current data don't show this. That being said, I don't have a problem with consolidating "Front/Back-End/Full Stack" into one "Development" choice for Q3.

**Comment by ashlingam** [comment]
<img width="33" alt="Screen Shot 2020-04-12 at 3 09 41 PM" src="https://user-images.githubusercontent.com/21990572/79078772-2be9b600-7cd0-11ea-8985-b7c68b26c094.png"> @harishlingam  I just looked at a couple google sheets that have been collecting data for a long time now and you might find interesting. the original onboarding survey, have you seen the results? it’s more about engagement — did you find a team, are you using slack, KPIs like that. the other is the slack new joiners — it captures name, email, stuff like that, but also what day and time people join. there might be some patterns in there if you want to explore
both are in the same Surveys folder as the new onboarding survey

**Comment by wesrowe** [comment]
To clarify, the above note to Harish was from me :)
My overall feeling about KPIs for onboarding -- I think we want to be studying whether new joiners successfully engage and feel productive. That's the outcome we want to measure. The older survey tried to get at that question, although VRMS is probably a much better tool than a survey for measuring engagement because it captures non-engagement too.

**Comment by ExperimentsInHonesty** [comment]
@wesrowe 100% to what you said above.  I think that the google form surveys are a good place for us to work out what we want to ask and how to ask it.  Then when we get our process tight, then we can migrate it to VRMS when they are ready.

**Comment by ashlingam** [comment]
@wesrowe Could you please share a link to the original onboarding survey you referred to? I didn't see it in the surveys folder on the shared drive.

**Comment by wesrowe** [comment]
@harishlingam Can you see this: https://docs.google.com/forms/d/e/1FAIpQLSd3ayiHXV3IZMxu-cqTVvwnozwnwfdbwZjpbqCjom1QbgIImQ/viewform?usp=sf_link

**Comment by ashlingam** [comment]
Hi @wesrowe, I am sharing with you a survey comparison board that @ExperimentsInHonesty  and I created: https://github.com/hackforla/website/projects/2. We've used this board to collate questions across the current Onboarding Survey (OS), New Member Survey (NMS), and Old Onboarding Experience Survey (OES), the survey you shared. The New Members survey is intended to dispatch ~2 weeks after a volunteer completes the Onboarding Survey. Your version of survey contains questions relevant to each of the other two surveys. 

If there are questions from the OES that you think belong in either one of the other two surveys, please let me know, either here in the issue, or by simply dragging them to the appropriate column so that I can review. Some questions are clearly redundant.

Thanks!

**Comment by ashlingam** [comment]
1. Progress - Engaged @wesrowe in discussion about remote and new member onboarding surveys, including strategic design, distribution, and relationship to larger project objectives. Reviewed PRD and introduced the user stories and personas board. Harish to establish finalized content of both surveys. Wes/Harish to configure dispatch of New Member Survey 1 mo. after onboarding. To be accomplished through either Greetbot or email platform.
2. Blocks - None
3. Availability - Saturday, Sunday, Monday
4. ETA - Monday
