### ISSUE TITLE
ER from TLDL: Feasibility of validating fields on Wins Form

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4185]
TLDL stands for Task List Dev Leads.

### Emergent Requirement - Problem
**Issue Description**
(Write a large issue to explore the feasibility) In the wins form, should we add validation to some fields, especially optional fields, for links such as for the Linkedin field?
  - Use built in validation vs adding special scripts by developers to validate?
  - Syntactic validation

This came up because this was submitted `https://linkedin/in/BonnieAWolfe` and the form allowed it. I know our Wins Google Forms has validating URL turned on for URLs but it allowed that and we were trying to see if there was a way to add more validation.

### Who was involved
GitHub Handle(s): JessicaLucindaCheng, SAUMILDHANKAR

### What happens if this is not addressed
The form stays the same and validation doesn't happen for optional fields.

### Action Items
- [x] Discuss with PMs/Bonnie and the team on how big a problem this is and if it is worth finding a fix
- [x] Search and check 
  - [x] If an open issue exists that addresses this ER
  - [x] If a closed issue exists that has already addressed this ER
- [x] If an open issue doesn't exist and this ER wasn't already fixed by a closed issue, make a new issue

**Comment by jdingeman** [comment]
@JessicaLucindaCheng - basic validation on the form already exists for optional fields that require a URL to be entered. Are you wanting to make it so that the actual URL is validated for what it should be? 

For example, someone submits a win and puts "https://www.facebook.com/blahblah" into the LinkedIn section. That's technically a valid URL in the eyes of the form, but of course it is not a LinkedIn URL.

**Comment by JessicaLucindaCheng** [comment]
This came up because this was submitted `https://linkedin/in/BonnieAWolfe` and the form allowed it. I know our Wins Google Forms has validating URL turned on for URLs but it allowed that and we were trying to see if there was a way to add more validation.

I just submitted a submission on the Wins form to test its URL validation (which I checked is on) and this is what was submitted for the LinkedIn and GitHub urls:
```
LinkedIn : https://linkedin/in/test 
GitHub : https://github/com/hackforla  
```
You can see the LinkedIn and GitHub aren't actually URLs.

Also, I don't know how big of a problem this is and whether a fix is worth it. So, I think it would be a good idea to discuss it with Bonnie.

**Comment by JessicaLucindaCheng** [comment]
@jdingeman 
This came up because this was submitted `https://linkedin/in/BonnieAWolfe` and the form allowed it. I know our Wins Google Forms has validating URL turned on for URLs but it allowed that and we were trying to see if there was a way to add more validation.

I just submitted a submission on the Wins form to test its URL validation (which I checked is on) and this is what was submitted for the LinkedIn and GitHub urls:
```
LinkedIn : https://linkedin/in/test 
GitHub : https://github/com/hackforla  
```
You can see the LinkedIn and GitHub aren't actually URLs.

Also, I don't know how big of a problem this is and whether a fix is worth it. So, I think it would be a good idea to discuss it with Bonnie.

**Comment by jdingeman** [comment]
@JessicaLucindaCheng  I see now. That's really weird that the form validates that with just the https. We'll make a new issue for it. Thanks!

**Comment by roslynwythe** [comment]
- @JessicaLucindaCheng @jdingeman  I noticed that there was an effort to develop a new, internal wins form.  The [new form](https://github.com/hackforla/website/blob/gh-pages/pages/wins/wins-share-form.html) was created in PR #1132, but apparently it needs some work described in issue #2021.  If we are still planning to move to a different form, that changes our options regarding URL input validation.   For the purposes of this ER, would you prefer that we just consider solutions to the validation problem in the context of current setup, or that we also consider using an internal form?

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe 
- > For the purposes of this ER, would you prefer that we just consider solutions to the validation problem in the context of current setup, or that we also consider using an internal form?

  - Answer: For this ER, the current Google Form we use for wins



- The question about the custom, coded form is related to #4387 and #4390. I have added to it to Dev/PM agenda for discussion.

**Comment by roslynwythe** [comment]
- Created issue #4405

**Comment by roslynwythe** [comment]
- Created issue https://github.com/hackforla/website/issues/4405

**Comment by roslynwythe** [comment]
- Created issue #4595
