### ISSUE TITLE
Fix SDG background color on project pages so that it matches the SDG icons

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4187]
### Dependency
- [x] #4344
- [x] #4225
- [x] #4253
- [x] #4233

### Overview
On detailed project pages, make the Sustainable Development Goal (SDG) background color match the color of the SDG mini-card so that the mini-card and the background blend in together.

### Details
- A couple examples of the problem
  <details>
    <summary>Click here to see a screenshot of the blue background not matching the SDG image color on the Lucky Parking page</summary>
    <img width="187" alt="" src="https://user-images.githubusercontent.com/31293603/225180655-0d2c7d35-60c3-4775-bd37-89241d148920.png">
  </details>

  <details>
    <summary>Click here to see a screenshot of the blue background not matching the SDG image color on the 311 Data page</summary>
    <img width="187" alt="" src="https://github.com/hackforla/website/assets/31293603/49405988-83ea-4769-8b48-a7d18e6df66e">
  </details>

### Action Items
- [x] In `_projects/lucky-parking.md`, after `sdg-image-alt: '11: sustainable cities and communities'`, add this new field:
  ```
  sdg-color-variable: $color-sdg11
  ```
- [x] In the following project's Markdown file, after the line `sdg-image-alt: '16: peace, justice and strong institutions'`, add this new field: 
  ```
  sdg-color-variable: $color-sdg16
  ```
  - [x] _projects/311-data.md
  - [x] _projects/access-the-data.md
  - [x] _projects/engage.md
  - [x] _projects/open-community-survey.md
- [x] In `_layouts/project.html`, change 
  ```
  <div class='sdg-description-card'>
  ```
  to
  ```
  {%- assign background_color = page.sdg-color-variable |  replace_first: "$", "background-" -%}
  <div class='sdg-description-card {{ background_color }}'>
  ```
- [x] In `_sass/components/_project-page.scss`, in the `.sdg-description-card` class, remove
  ```
  background: #02548B;
  ```
- [x] On the Lucky Parking page (https://www.hackforla.org/projects/lucky-parking), check that the SDG background color matches the orange color of the `11 Sustainable Cities and Communities` icon so that the icon and the background blend in together in desktop and tablet views and that it looks good.
- [x] Check that the Lucky Parking page in mobile view looks the same as the one on the live website.
- [x] Using Docker, check that the following pages look good in desktop, tablet, and mobile views:
  - [x] 311 Data: https://www.hackforla.org/projects/311-data
  - [x] Access the Data: https://www.hackforla.org/projects/access-the-data
  - [x] Engage: https://www.hackforla.org/projects/engage
  - [x] Open Community Survey: https://www.hackforla.org/projects/open-community-survey

### Resources/Instructions
- [Jekyll's use of Liquid template language](https://jekyllrb.com/docs/liquid/)
  - [Liquid template language](https://shopify.github.io/liquid/) 
- [Hack for LA's Site Architecture wiki page](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture) 

#### Files/Directories in the repo
- [_layouts/project.html](https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html)
- [_sass/components/_project-page.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-page.scss)
- [_sass/variables/_colors-sdg.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_colors-sdg.scss)
- [_sass/elements/_background-sdg-colors.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_background-sdg-colors.scss)
- [_projects/311-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/311-data.md?plain=1)
- [_projects/access-the-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md?plain=1)
- [_projects/engage.md](https://github.com/hackforla/website/blob/gh-pages/_projects/engage.md?plain=1)
- [_projects/lucky-parking.md](https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md?plain=1)
- [_projects/open-community-survey.md](https://github.com/hackforla/website/blob/gh-pages/_projects/open-community-survey.md?plain=1)
#### Webpages to check
- Lucky Parking page: https://www.hackforla.org/projects/lucky-parking
- 311 Data: https://www.hackforla.org/projects/311-data
- Access the Data: https://www.hackforla.org/projects/access-the-data
- Engage: https://www.hackforla.org/projects/engage
- Open Community Survey: https://www.hackforla.org/projects/open-community-survey
- This issue is tracked in #4153

**Comment by ExperimentsInHonesty** [comment]
My guess is that this blue is hard coded into the page layout instead of using a file to match color to the SDG to that project.  Here is the spreadsheet where we have a list of [SDG Hex Colors](https://docs.google.com/spreadsheets/d/1lV8d8AMSJ5HOiTWlFE7lzbqiKxqMmh8pHADcJMdp7JE/edit#gid=741671421)

**Comment by JessicaLucindaCheng** [comment]
- [x] Break this down into smaller issues and it's okay if it becomes 
  - [x] Remove the hard coded color
  - [x] Add color variables and color background color
  - [x] Remove and replace SDG images because colors are messed up
  - [x] Fix the Lucky Parking page
  - [ ] Etc

**Comment by JessicaLucindaCheng** [comment]
- Blocker related to this comment: https://github.com/hackforla/website/issues/4233#issuecomment-1483959603

**Comment by jch1013** [comment]
Availability: Weeknights
ETA: October 17
