### ISSUE TITLE
Edit Accomplishments in About Page to show different years 

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4188]
### Overview
We want to highlight the accomplishments across HackforLA for the projects across multiple years. Currently, the [About page](https://www.hackforla.org/about/#accomplishments) only shows accomplishments for the year 2022. We need to implement a new format so that a user can see highlights from previous years. 

### Action Items
- [x] We need to add three fields to [_data/internal/accomplishments.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/accomplishments.yml)
  - [x] `year`
  - [x] `project-file` (example: `project-file: food-oasis.md`)
  - [x] `program-area` (example: `program-area: Social Safety Net`)
- [x] If a project file exists, the program area should be retrieved from the project file, by using Liquid to run through the [_projects](https://github.com/hackforla/website/tree/gh-pages/_projects_) collection and find the program area that matches with the name of the project.  Therefore,  `program-area` should be specified only if no project file exists.  
- [x] See most recent Figma design (in resources below) and zoom into the Accomplishments section
- [x] Navigate to [_includes/about-page/about-card-accomplishments.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-accomplishments.html)
- [x] Implement the design so that when a user clicks on any of the years, the section shows accomplishments from that year
- [x] Note: The final layout for the Accomplishments section will slightly differ from the Figma design
   - [x] Rather than list accomplishments by project with the program area above as seen in current design (see below), 
 we want to list the accomplishments by program area. So the program area (e.g. Citizen Engagement) would be like the black header, and the accomplishments for each project in that program area will be listed. This is so the program areas do not get repeated for each project in that program area. 

### Resources/Instructions
- [about.html](https://github.com/hackforla/website/blob/gh-pages/pages/about.html)
- [about.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/about.js)

#### Current design
- About page, accomplishment section: https://www.hackforla.org/about/#accomplishments
- 
  <details>
  <summary>image from current state of website figma</summary>

  ![image](https://user-images.githubusercontent.com/88953806/225187991-6c285cb3-cae5-429d-abf1-6954b742092f.png)
  </details>

#### Future State of website after this issue is completed
- [Figma, accomplishment section](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=22519-129240&t=uYA0fTohWkL30foQ-0)
<details><summary>image from future state of website figma</summary>

**Web View**
<img src="https://github.com/hackforla/website/assets/86667836/f77760f5-4a32-4e06-9f78-03d0a125ea53" width= 400px>

**Mobile View**
<img src="https://github.com/hackforla/website/assets/86667836/8036dd64-c9ad-455d-b39d-0c4fe9dfc95d" width= 200px>

</details>

**Comment by jdingeman** [comment]
@ExperimentsInHonesty, see draft note 

> DRAFT NOTE: If this is the approach we want to go, how should the dev approach listing the accomplishments that don't have a program area?

**Comment by ExperimentsInHonesty** [comment]
@jdingeman I see a couple of issue.
1. Accomplishments that don't have a program area (which you pointed out) but also see the next item
    - I can give you the program areas they fall in
       - title: National Day of Civic Hacking (NdoCH) is Justice in 2020
       - title: Climate Collabathon is Environment
1. How will the code know the program area at all?
    - The titles don't currently match the file names
    - we should have project.md files for all the accomplishments (this has to be an issue for each accomplishment that does not yet have a project.md file.  And the template we used to use is out of date, so we have to make a new one.  So this is a level 2 issue making)
    - we should have a place in the _data/internal/accomplishments.yml file that has the project.md file name, so it can know its URL is hackforla.org/projects/...
1. How will the code know what year the item is?
   - After looking at this file [_data/internal/accomplishments.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/accomplishments.yml) I realize we don't have a method for storing or indicating years.  So we are going to have to figure out how we want that architected. We cannot leave it up to the person working on this issue because they don't yet know enough about the architecture to make good decisions (that's what all the rework we have been doing on the donate page and other pages has led me to realize).  Or this has to be made into an extra large issue and make it clear that they have to recommend an architecture and get it approved.  I am leaning towards we just decide
      - Could have a separate yml file per year
      - Could add a year field
      - Could also move the accomplishments to the project files and have it by year there. 
         - pros: we could also display the information easily on their project page if we decide to do that in future (likely)
         - cons: 
            - the code has to iterate through the entire set of project files to get the accomplishments, which slows the build, but not the user experience since it's a static site.
            - harder to see where we are missing accomplishments for, but could be mitigated by making an accomplishments-check page to see what projects we are missing accomplishments for what years.  Which would be pretty cool and useful.  p.s. if we decide to do that, we should add a start date to project.md files, so that we don't show on the accomplishments-check page that they are missing an accomplishment for a year that they didn't exist.

**Comment by ExperimentsInHonesty** [comment]
- @jdingeman how does https://github.com/hackforla/website/issues/4146 relate to this issue?

**Comment by roslynwythe** [comment]
Hi @ExperimentsInHonesty it looks like first we need to decide on the data structure for accomplishments.yml and then start populating accomplishments.yml so we know which projects.md files will have to be created.  I would probably suggest adding a date field and a project field to accomplishments.yml but the approach of listing accomplishments in the project file would also work.   But is it possible that in the future we might want to specify multiple dates and/or multiple projects for an accomplishment?

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe For expediency I propose that we add year and project.md name fields to the accomplishment.yml file.  And then later we can rearchitect it if we want to do more.

Also if there is no project.md file, such as in the case of NDOCH event then no link would appear, just the name.
And for that record, there would be a program area listed.

For the files with project.md files the program area will come from those files.


Examples
```
- title: National Day of Civic Hacking (NdoCH)
  link: 
  program area: Social Safety Net
  description: >
    In 9/2020 Hack for LA joined over 40 Code for America brigades in bringing together civic leaders, 
    public servants, designers, coders, and engaged citizens to partner with local government and community groups to help those most 
    in need of a social safety net services during COVID-19.

- title: Food Oasis
  link: https://www.hackforla.org/projects/food-oasis
  project-file: food-oasis.md
  description: >
    Launched 8/2020 the most comprehensive listing of Food Pantries and Meals to address food insecurity in Los Angeles (listed as a resource on LA County Public Health website).
```

**Comment by Josiah-O** [comment]
- We added the future state images of the accomplishments section. https://github.com/hackforla/website/issues/4188#issue-1624606656

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty I edited the Action Items to reflect your above suggestions

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe This issue has too many notes in it for it to be clear enough for someone to work on it.  We need to summarize anything from the comments into the top and hide all the comments.

**Comment by Thinking-Panda** [comment]
Availability: Weekdays
ETA: 10/31/23

**Comment by Thinking-Panda** [comment]
Questions 

1. The issue says the current highlights are for year 2022. The published website says the highlights are for the yea 2020. And, the Figma design shows 2019 as the earliest year. Please let me know how far back in years should I include ?
2. The current code is designed to have 4 accomplishments in each column. Should I continue with that layout or plan for situations when there could be more than 8 accomplishments per year. For example, when there are 9 accomplishments, should the left column have 5 or 4 accomplishments?

Thank you !

**Comment by Thinking-Panda** [comment]
1. Progress: Added more years to display accomplishments, added code to display the program areas as mentioned for all accomplishments. Working on filtering accomplishments by year and displaying the program area accordingly without repeating code.
2. Blockers: none at the moment
3. Availability: Weekdays
4. ETA:11/10

**Comment by ExperimentsInHonesty** [comment]
@Thinking-Panda I removed the `To Update !` and `ready for product` labels, now that you have done your update.  Thanks for working on this.  I am looking forward to seeing it when its done.

**Comment by Thinking-Panda** [comment]
1. The Figma design has "All" included in the dropdown in mobile viewport. But the desktop viewport does not include it. Should I add "All" to show all accomplishments?
2. The list of years to be displayed is added dynamically. But I notice that it is displayed twice and I'm unable to fix the problem. I am also attaching the console message I get when I tried to track it.
![AccYearConsoleMsg](https://github.com/hackforla/website/assets/122488603/3f17033b-2c89-42e5-a33a-603febbc08ee)

**Comment by LRenDO** [comment]
Hi @Thinking-Panda! 

Great observation on the difference between the desktop and mobile options. I would think that question would be good for the design team, but it looks like there is no one on the website design team currently from what I can see on GitHub. I would lean towards sticking with the Figma design since we can always create a new issue to add an "All" section, but tagging in @roslynwythe for guidance on whether or not to go ahead and add it now.

I am happy to take a look at what you have for the second issue that you are running into and/or get on Slack to work it out with you.  If you push your feature to your forked repo, sometime early next week I can take a look at what you've got.

**Comment by LRenDO** [comment]
Hi @Thinking-Panda! I was able to take a look at your branch and overall it's looking good so far! 

As far as the blocker, It looks like `about.js` is included in both `\pages\about.html` and `\_includes\about-page\about-card-accomplishments.html`. This is likely why there is duplication in the accomplishments section. Only including the script once should resolve the issue. If not,  [this SO article](https://stackoverflow.com/questions/22403261/chrome-vm-files-duplicate-javascript) might be helpful and includes a couple other potential causes/solutions. 

Aside from the blocker, I thought I would also mention that the for loops in `loadAccomplishmentYears()` are missing `let` in front of `i=year`. 

Again, looks like you're off to a solid start here! Please feel free to ping me here or on Slack if you need any additional help resolving the issue!
