### ISSUE TITLE
Fix the Add-Missing-Labels-to-Issues job error

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4189]
### Overview
Dev leads have noticed that the Add-Missing-Labels-to-Issues job is failing whenever we submit a new issue onto the project board. We need to correct the job so that it works correctly and adds missing labels to issues that are submitted for approval. 

### Action Items
- [ ] See associated issue https://github.com/hackforla/website/issues/4129 for more information
- [ ] Familiarize yourself with [GitHub Actions](https://docs.github.com/en/actions)
- [ ] Understand the HfLA GitHub Actions by reviewing the [wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions) and the different [GHAs](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions) we use
   - [ ] If you have not already done so, create a copy of the Project Board into your own repo ([Tip 6: Creating your own Project Board](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-6-creating-your-own-project-board))
  - [ ] Be sure to read up on using Personal Access Tokens to test the project board in your own repo ([Tip 7: Using Personal Access Tokens to test in your own Project Board](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-7-using-personal-access-tokens-to-test-in-your-own-project-board))
- [ ] See [issue-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml) and investigate what the issue may be
  - [ ] Determine if there are any deprecated functions that may be causing the issue
  - [ ] For testing purposes, create and edit [tokens](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-6-using-personal-access-tokens-to-test-in-your-own-project-board) as necessary for your repo
- [ ] Make corrections to workflow and test in your local repo to ensure that it works
- [ ] Provide a demo to the merge team for review

### Resources/Instructions
- Example of [failed job](https://github.com/hackforla/website/actions/runs/4422133435/jobs/7753636773)
- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
- [GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)
- [GitHub RESTAPI](https://docs.github.com/en/rest)
- [HfLA GitHub Actions Guide and Tips](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)

**Comment by JessicaLucindaCheng** [comment]
@jdingeman Thanks for writing the issue!
- For the action item "Create a copy of the Project Board into your own repo," I'm not sure if newer developers are able to create a project board using Projects (classic), which is the type we are currently using. Maybe you can check with newer developers during a meeting to see if they are able to create a project board using Projects (classic).

**Comment by jdingeman** [comment]
Sent a message to the Slack channel asking devs to follow the steps of copying the project board. Hopefully I get a few answers to check if they are able to without needing special permissions.

**Comment by jdingeman** [comment]
@JessicaLucindaCheng - confirmed that devs do not need admin access to make copies of the HfLA project board.

**Comment by ExperimentsInHonesty** [comment]
@jdingeman This should have a link to the instructions you are going to add to the wiki about them copying the project board from our repo.

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - added wiki links

**Comment by ExperimentsInHonesty** [comment]
@jdingeman where in the above does it have link to creating your own board in the wiki?

**Comment by jdingeman** [comment]
@ExperimentsInHonesty 
![image](https://user-images.githubusercontent.com/88953806/227393979-bcf7b8bc-cc9a-441d-9763-07da844b6ad7.png)

**Comment by richardmundyiii** [comment]
Availability: M-Sa 6am - 9am
ETA: EOD 4/1/2023

**Comment by jdingeman** [comment]
Hey @richardmundyiii, wanted to check in on this issue. Have you made any progress?

**Comment by richardmundyiii** [comment]
Availability: Sat & Sun 3pm -6pm
ETA: EOD 3/10/23

**Comment by richardmundyiii** [comment]
@jdingeman Sorry got caught up with my final BootCamp project then got super sick. But will complete this issue by the end of the weekend.

**Comment by richardmundyiii** [comment]
Availability: Wed-Sat 10am - 3pm but can meet with a lead at a more convenient time if needed.
ETA: 4/16/23

Update: There doesn't seem to be any deprecated functions that may be causing the issue. 

I will need to reach out to dev lead for more assistance. @jdingeman

**Comment by jdingeman** [comment]
Have you been able to traceback the first error to anything specific to the add-missing-labels-to-issues workflow?
![image](https://user-images.githubusercontent.com/88953806/231637934-60a2d368-b078-44f6-8a9c-a755f58b392d.png)

**Comment by roslynwythe** [comment]
Hi @richardmundyiii please provide an update including your progress, availability, ETA and blockers, and then remove the "2 weeks inactive" label.  If you are no longer able to continue work on this issue, please let us know.  If we have not heard from you by 8/14/23 we will unassign you from this issue.

**Comment by ExperimentsInHonesty** [comment]
@richardmundyiii I am removing you from the issue because you have not provided an update for over a month.

**Comment by EdASalazar** [comment]
Thur 3-7
Fri 6-9
Sun 10 - 6

ETA Wed.  6/14/23 - I can ask for help on the Dev call Tuesday night if I need it.

**Comment by t-will-gillis** [comment]
Hello @EdASalazar 
In case you did not see this, we implemented a new dependabot a couple of weeks ago that searches through our codebase looking for action modules that have older version numbers. The bot is recommending that we update various versions listed in the `issue-trigger.yml` file:
- #4734: four locations `actions/github-script@v4` --> `actions/github-script@v6`
- #4735: two locations `actions/checkout@v2` --> `actions/checkout@v3`
- #4737: one location `tspascoal/get-user-teams-membership@v1` --> `tspascoal/get-user-teams-membership@v2`

It will be a good idea to make these version changes to your test files right away, since a. we will need to update these versions very soon and b. the new versions (esp get-user-teams-membership) might eliminate some of the errors that are occurring. 

Let us know if you would like to talk about this more and/or have blockers. Thanks!

**Comment by EdASalazar** [comment]
I'll have the evening to continue to work on this. 
M 7-10
T 7-10

ETA Thurs or Office hours for help

**Comment by t-will-gillis** [comment]
> It will be a good idea to make these version changes to your test files right away, since a. we will need to update these versions very soon and b. the new versions (esp get-user-teams-membership) might eliminate some of the errors that are occurring.

As I am testing other GHAs for the dependabot-suggested version update changes: I believe that the updates suggested in issue 4734 might/will break this GHA and **should not** be done.

**Comment by EdASalazar** [comment]
Still trying to figure this out. I created a copy of the Hack for LA Project Board but my branch of the Website repo doesn't seem to allow me to create issues. So I'm not sure how I'm supposed to test anything.  I'll go to office hours on 6/22 to see if I can get any help then.

**Comment by t-will-gillis** [comment]
Hi @EdASalazar - you might check the Settings General in your repo and scroll down to Features and check if the Issues box is checked:  

![Screenshot 2023-06-20 081046](https://github.com/hackforla/website/assets/40799239/6aae02a6-73fe-4003-ac25-ad3afbbe03b8)

**Comment by EdASalazar** [comment]
> Hi @EdASalazar - you might check the Settings General in your repo and scroll down to Features and check if the Issues box is checked:
> 
That was it. Thank you so much! I was losing my mind.

**Comment by t-will-gillis** [comment]
Hello @EdASalazar -are you still working on this issue?

**Comment by t-will-gillis** [comment]
It appears that this issue has been resolved by regenerating the `secrets.TEAMS` tokens. Issue #4822 will check the next steps needed for reviewing the "Add-Missing-Labels-to-Issues" job.
