### ISSUE TITLE
Update Project Information: Access the Data

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4211]
### Overview
The Access the Data page needs to be updated to reflect accurate team information. 

### Action Items
- [x] Download a copy of the Access the Data [One Sheet](https://github.com/hackforla/product-management/blob/master/project-one-sheets/AtD-one-sheet.pdf) from the product management repo
  - [x] Replace the current Access the Data One Sheet in [/assets/pdfs](https://github.com/hackforla/website/tree/gh-pages/assets/pdfs) 
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/access-the-data.md` file and find the `leadership` variable.
- [x] Remove Mariana Melo-Vega and their information
- [x] Verify the changes by viewing the [Access the Data project page](https://www.hackforla.org/projects/access-the-data) on your local environment and include a screenshot with your pull request
  - [x] Ensure that the "Overview" hyperlink links to the new One Sheet
- [x] Remove the following variables (and their text content) from the access-the-data.md file
  - [x]  `problem` 
  - [x] `solution`
  - [x]  `impact`

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [access-the-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by oliviazhai** [comment]
Availability: Mar 21st
ETA: Mar 22nd

**Comment by ExperimentsInHonesty** [comment]
Hi @oliviazhai Please remember to move issues to the in progress column after you self assign.  I will do it now.

**Comment by oliviazhai** [comment]
I cant\'t find the Access the data one sheet from this repo: https://github.com/hackforla/product-management
How can I get the correct access data one sheet?

**Comment by jdingeman** [comment]
HI @oliviazhai - I am not sure what happened to the link, as it seems to have become dead since the time of issue creation. I will try to find it.

**Comment by jdingeman** [comment]
@oliviazhai - I updated the link. You'll find the one sheet here: 
- https://github.com/hackforla/product-management/blob/master/project-one-sheets/AtD-one-sheet.pdf

**Comment by karengcecena** [comment]
Availability: Mar 29 - 31
ETA: Mar 31

**Comment by mjh-projects** [comment]
Availability for this week: After 6:00 PM except Wednesday. 
My estimated ETA for completing this issue: 4/3/2023
