### ISSUE TITLE
Update Project Profile: Hackforla.org Website

### ISSUE THREAD

**Issue by MattPereira** [hackforla/website#4219]
### Overview
For this issue, please update the [Hackforla.org Website Project's](https://www.hackforla.org/projects/website) leadership information so that it is up to date.

### Action Items
- [x] Locate the `website.md` file inside of the `_projects/` collection folder
- [x] Find the `leadership` variable and look for `- name: Matt Pereira`
- [x] Change the `role` variable for Matt Pereira from `Technical Lead` to `Merge Team`

### Resources/Instructions
- https://www.hackforla.org/projects/website
- https://github.com/hackforla/website/blob/gh-pages/_projects/website.md
- https://jekyllrb.com/docs/front-matter/

**Comment by mjshelton12** [comment]
Availability: Wednesday sporadically, Thursday all day
ETA: Thursday by end of day

**Comment by mjshelton12** [comment]
Update: Ended up having enough time to complete it tonight. Pull request is up.
