### ISSUE TITLE
Hide projects that should not be visible in Program Areas page

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4220]
### Overview
We need the [Program Areas](https://www.hackforla.org/program-areas) page to only show projects whose visibility is set to `true` in the projects' markdown files. For this issue, you will hide projects whose visibility is set to `false` so that the page shows the most up to date information for each program area.

### Action Items
- [x] Navigate to [/pages/program-areas.hml](https://github.com/hackforla/website/blob/gh-pages/pages/program-areas.html)
- [x] Verify which projects should be rendered by looking through [/_projects](https://github.com/hackforla/website/tree/gh-pages/_projects)
- [x] Use Liquid to render _only_ the projects that have `visible: true`
  - [x] If the project has `visible: false` the mini card should not render
  - [x] If the project does not have a `visible:` attribute, the mini card should not render
- [x] Check in your local repo that this does not break the site and that all of the projects that should be visible are rendered

### Resources/Instructions
- [Liquid in Jekyll](https://jekyllrb.com/docs/liquid/)

**Comment by kwangric** [comment]
Availability: Tuesday/Wednesday after 1pm PDT
ETA: Wednesday afternoon
