### ISSUE TITLE
ER from TLDL: GHA message when a team member is assigned to multiple issues at the same time

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4230]
TLDL stands for Task List Dev Leads.

### Emergent Requirement - Problem
**Issue Description**
Write an issue to create a GHA script that posts a message to the team member that is assigned to multiple, open issues at the same time. The message will let the team member know they should only be assigned to one open issue at a time and to wait until their pr is merged or their issue has been closed through approval by PMs/design lead/research lead/other lead to assign themselves to another issue

### Who was involved
**GitHub Handle(s):**
- JessicaLucindaCheng
- SAUMILDHANKAR   

### What happens if this is not addressed
- A team member may not know or remember they need to wait until their pr is merged or their issue has been approved by PMs/stakeholder rep to assign themselves to another issue.

### Recommended Action Items
- [x] Search and check 
  - [ ] If an open issue exists that addresses this ER
  - [ ] If a closed issue exists that has already addressed this ER
- [x] If an open issue doesn't exist and this ER wasn't already fixed by a closed issue, make a new issue 
- [ ] Discuss with team

**Comment by jdingeman** [comment]
Same thing with this one as the multiple complexity issues ER here
- https://github.com/hackforla/website/issues/4193

Best way to get notification for this? New issue that GHA comments on each time it runs and adds to NIA column with appropriate labels?

Also noting that this will need to take into account that the prework issue should be excluded from the check

**Comment by JessicaLucindaCheng** [comment]
@jdingeman I think that's a good idea. However, I think the idea was to have the bot comment on the issue (that was self-assigned) telling the team member they can only be assigned to one issue at a time and to wait until their other issue has been closed in order to pick up another issue (unless approval was received from a lead to work on another issue).

You can bring it up with the Merge Team and PMs to get their input and ideas too.

**Comment by jdingeman** [comment]
@hackforla/website-merge - another one to discuss potential solutions for

**Comment by jdingeman** [comment]
New issue here:
- https://github.com/hackforla/website/issues/4505
