### ISSUE TITLE
ER from TLDL: Add a link to VS Code's documentation on Merge Conflicts to CONTRIBUTING.md

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4231]
TLDL stands for Task List Dev Leads.

### Emergent Requirement - Problem
**Issue Description**
Write an issue to add a link to [VS Code's documentation on Merge Conflicts](https://code.visualstudio.com/docs/editor/versioncontrol#_merge-conflicts) with a small description in our [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) document

### Who was involved
**GitHub Handle(s):**
- JessicaLucindaCheng
- SAUMILDHANKAR   

### What happens if this is not addressed
A developer may not know how VS Code deals with merge conflicts or how to find merge conflicts using VS Code.

### Resources
- [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [VS Code's documentation on Merge Conflicts](https://code.visualstudio.com/docs/editor/versioncontrol#_merge-conflicts) 

### Action Items
- [ ] Search and check 
  - [ ] If an open issue exists that addresses this ER
  - [ ] If a closed issue exists that has already addressed this ER
- [ ] If an open issue doesn't exist and this ER wasn't already fixed by a closed issue, make a new issue 

### Potential solutions [draft]

**Comment by jdingeman** [comment]
New issue made here: 
- https://github.com/hackforla/website/issues/4352
