### ISSUE TITLE
ER from TLDL: GHA to remove unmerged, closed PRs off the project board

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4232]
TLDL stands for Task List Dev Leads.

### Emergent Requirement - Problem
**Issue Description**
Write an issue to create a GHA automation to remove unmerged, closed PRs automatically off the project board. 

### Who was involved
**GitHub Handle(s):**
- JessicaLucindaCheng
- SAUMILDHANKAR   

### What happens if this is not addressed
The unmerged, closed prs will stay on the project board until someone manually removes them. This can be time-consuming.

### Action Items
- [ ] Search and check 
  - [ ] If an open issue exists that addresses this ER
  - [ ] If a closed issue exists that has already addressed this ER
- [ ] If an open issue doesn't exist and this ER wasn't already fixed by a closed issue, make a new issue 

### Potential solutions [draft]

**Comment by jdingeman** [comment]
Issue made here: 
- https://github.com/hackforla/website/issues/4357
