### ISSUE TITLE
Remove team member from the Food Oasis project.md file

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4238]
### Overview

As a product manager of Food Oasis I want my project's details to be up to date on the HackforLA website. As developers, we need to update the Food Oasis project's team

### Action Items

- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the [food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md) file and find the `leadership` variable.
- [x] Remove all of the items related to Jieun Ryu: name, role, links and picture.  

### Resources/Instructions

- Food Oasis markdown file: https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by mjshelton12** [comment]
Availability: 3/23 5:30-10pm
ETA: 3/23 by end of day
