### ISSUE TITLE
Update Engineering Community of Practice information to peer led

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4239]
### Overview

The Communities of Practice - Engineering project card needs to be updated to reflect accurate team information.

### Action Items

- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `internal/communities/engineering.yml` file and find the `leadership-type` variable.
- [x] Update the description 
     - ***From***
     ```leadership-type: Mentor Led```
     - ***To***
     ```leadership-type: Peer Led```

### Resources/Instructions

- [engineering.yml](https://github.com/hackforla/website/blame/gh-pages/_data/internal/communities/engineering.yml)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by Adaakal** [comment]
i. Availability: Sunday 3/26 3p-4p
ii. ETA: Tuesday: 3/28

**Comment by ExperimentsInHonesty** [comment]
I am unassigning you from this issue because you have already done a small issue.  Please only do issues of the size you have not done yet.  Exception: you can do multiple large issues, but I hope that you will join the merge team instead (after you finish your large issue).

**Comment by jeristella** [comment]
i. Availability: Tuesday - Thursday 11am to 4pm
ii. ETA: Saturday 10pm

**Comment by adevlinb** [comment]
@ExperimentsInHonesty I see @jeristella has assigned themselves to this issue. I just want to confirm, once someone has been assigned, the issue is considered taken? As in.. more than one person should not take on the assignment, unlike reviewing a PR.. where multiple people can review the work. So I will await looking for the next available issue to take on.

**Comment by jdingeman** [comment]
@adevlinb - yes, once someone has been assigned, the issue is considered taken.

@jeristella - please remember to move your issue from the Prioritized Backlog to the In Progress column when you assign yourself
