### ISSUE TITLE
ER: Create a new credit file

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4240]
### Emergent Requirement - Problem
We removed the author's name from the alt text of the image for the Not Today project.  That credit does not appear anywhere else.

### Issue you discovered this emergent requirement in
- #4047

### Date discovered 
2023-03-19

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
We are not in legal compliance with our agreement to use his image

### Resources
https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits
https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
Create a new yml file to display on the credits page
file name: cwmoss.yml
contents: 

```
---
# The title from the source provider
title: unknown
# The url where you can get direct access to the image on the provider site
title-link: 
# The type of content - image, audio, or video 
content-type: image 
# The page it's used on
used-in: Not Today Project Logo
# Name of the artist
artist: C.W. Moss
# Name of the image database you found it on
provider: The Grey Rainbow
# Please give the general site URL, not the link to the image
provider-link: http://greyrainbow.com/
# Location in our GitHub repo
image-url:
---
```
### Note
Figure out what the logic should be if there is no link for the provider

**Comment by jdingeman** [comment]
New issue here:
- https://github.com/hackforla/website/issues/4269

**Comment by ExperimentsInHonesty** [comment]
@jdingeman It's going to work ok without a provider link?

**Comment by jdingeman** [comment]
@ExperimentsInHonesty I'm not sure I understand because I checked the link you put in for `provider-link` and it led me to the artist's page.

**Comment by jdingeman** [comment]
@ExperimentsInHonesty Oh I see what you mean. I will need to test it again and I will report back.

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - when I tested in my local, if the title doesn't have an `href` it just reloads the localhost:4000, and here is what I've found, see `href=""` for the case of the empty link

![image](https://user-images.githubusercontent.com/88953806/227425654-2821700c-937e-4d2a-bb12-38f6eae715ab.png)

The credit will still render. Also, did you want to keep the title as "unknown"?

**Comment by ExperimentsInHonesty** [comment]
@jdingeman I am going to reach out to Mya tomorrow (the old Not Today PM, whose is friends with the artist) and see if I cant get a name for the piece. But he only has the one website, and its not licensed images like our other providers.  Could we update the code anyway, to have it not add an href, if there is no link?  That would be the most future proof.

P.s. I am moving this back to ER column.

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - sure, it would require refactoring the Liquid in the credits.html to only add an href if `title-link` exists. We can make an issue and make it a dependency for this credit issue? I think it would happen relatively quickly.

**Comment by ExperimentsInHonesty** [comment]
@jdingeman I think we should make that code change, I am moving this back to ER.  It will make two issues then: 
- [ ] https://github.com/hackforla/website/issues/4269
- [ ] Refactor credits.html Liquid code to only add a href if title-link exists
   - no need to create a dependency on 4269, I think it's minor enough problem that it would be useful to have that issue done, so it could be checked when the new issue is made.
   - Made this new issue a medium front & back end issue

**Comment by ExperimentsInHonesty** [comment]
I reached out to Mya on slack.  ill check my slack tomorrow to see if she responded.

**Comment by jdingeman** [comment]
New issue made here:
- https://github.com/hackforla/website/issues/4351
