### ISSUE TITLE
ER: Change the circles image on the donation page to CSS

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4241]
### Emergent Requirement - Problem
We have to update the image to have more items in it. Since we don't have a designer right now, what do you think about making the circles with css instead of using images? The text for each would be the following

Monthly: Hosting, Mailing List services, Zoom, Meetup
Annual: Domain Names, Insurance
Occasional: Stickers, T-shirts

### Issue you discovered this emergent requirement in
- #3856 

### Date discovered 
2023-03-21

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
We keep updating the alt, and it's not conforming to the recommended length for alt text

### Resources
The include file that has the image in it: https://github.com/hackforla/website/blob/gh-pages/_includes/donate-card.html
Places that the include shows up:
https://www.hackforla.org/donate/
https://www.hackforla.org/join

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

**Comment by roslynwythe** [comment]
- new issue #4263
