### ISSUE TITLE
ER: Use the SVGs in the src attribute in img tags, and write up details for wiki

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4242]
### Emergent Requirement - Problem
We need a new issue for making each of the SVGs on the  individual project pages have alt="" Which will require wrapping them in an <img src="...

  - update: The issue written to provide accessible text for the svgs #4291 did accomplish that goal but caused an unintended side effect and so another issue will be required to resolve that - see https://github.com/hackforla/website/issues/4242#issuecomment-1759091791
  
### Issue you discovered this emergent requirement in
- #2626 

### Date discovered 
2023-03-21

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty @JessicaLucindaCheng 

### What happens if this is not addressed
We don't have alt text for the SVGs which is not WCAG compliant.

### Resources
![image](https://user-images.githubusercontent.com/37763229/226971875-38c6a776-601f-4476-bd55-96e090ff6f2e.png)

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

**Comment by JessicaLucindaCheng** [comment]
Here is a wiki page for how to make a SVG WCAG compliant: https://github.com/hackforla/website/wiki/How-to-make-SVGs-and-other-images-WCAG-compliant

**Comment by roslynwythe** [comment]
- New issue #4291

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng The wiki page doesn't mention which method we prefer.  Or when to use either method. Is that something we want to do and does it belong in a decision record referenced by that page?

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 
> @JessicaLucindaCheng The wiki page doesn't mention which method we prefer. Or when to use either method. Is that something we want to do and does it belong in a decision record referenced by that page?

I think the preferred method and when to use it can just be in the wiki itself. I added the "When to use it" for each method. While I prefer putting images and SVGs in an img tag method, I want to get feedback from the team on their thoughts before picking one.

Edit: We decided in putting SVG as a src in an img tag as the preferred method.

**Comment by jdingeman** [comment]
@roslynwythe - was this ER resolved with that issue you had written? Looks like that issue has been merged and closed.

**Comment by roslynwythe** [comment]
@jdingeman - due to an error I made in writing the above issue, another issue will be required to resolve this ER, so I re-assigned myself.

**Comment by roslynwythe** [comment]
- @JessicaLucindaCheng @jdingeman I made an error in writing #4291 and as a result the screen reader is reading the name for some of the resource icons twice (for example, "GitHub GitHub".  There are two possible solutions to the problem.  

1. move (or copy) the resource svgs from the `_includes/svg` folder to the `assets/images` folder, and then reference the svgs in an img element with an empty alt attribute.  
2. Leave the svgs in `_includes` but add an `aria-labelledby` attribute to the svg element, that references the ID of a h4 that names the resource.  

I was hoping to do a site search to find all the places where these svg icons are referenced, so I don't break anything, but that is not straightforward.  Do you know if these resource svgs appear anywhere other than the project pages?  And do you have an opinion which of the above solutions are better?

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe 

> * @JessicaLucindaCheng @jdingeman I made an error in writing [Replace inline SVGs with IMG elements in Projects' Resources section #4291](https://github.com/hackforla/website/issues/4291) and as a result the screen reader is reading the name for some of the resource icons twice (for example, "GitHub GitHub".  There are two possible solutions to the problem.
> 
> 1. move (or copy) the resource svgs from the `_includes/svg` folder to the `assets/images` folder, and then reference the svgs in an img element with an empty alt attribute.
> 2. Leave the svgs in `_includes` but add an `aria-labelledby` attribute to the svg element, that references the ID of a h4 that names the resource.
> 
> I was hoping to do a site search to find all the places where these svg icons are referenced, so I don't break anything, but that is not straightforward. 

>Do you know if these resource svgs appear anywhere other than the project pages? 

Ans: I don't know. However, the spreadsheet created as part of this issue might be helpful: https://github.com/hackforla/website/issues/1900#issuecomment-1535012539

> And do you have an opinion which of the above solutions are better?

Ans: I don't have an opinion on which is better.

**Comment by roslynwythe** [comment]
- update:  #4291 did provide a descriptive name for the svgs in the Resource section of the project page, however there was an undesirable side-effect; that is, the `<a>` elements that wrap the svgs took on an additional name, and as a result, when the screen reader is focused on the link element, it reads a duplicate name, for example: "GitHub GitHub".  This is due to the fact that link elements are assigned "accessible names" based on concatenation of the accessible names of their child elements.  A child element (`<h4>GitHub</h4>`) alread exists and so adding the aria-label to the div adds another name.  
 
The two best solution I've found so far is:

- do not wrap the svg in a div with 'aria-label' and role="img"
- wrap the svg in another svg element.  The outer svg element should have:
   - attribute role="img"
   - attribute aria-labelledby="titleID"
   - the first child element:  <title id="titleID">ANAME</title> 
      -  where ANAME is the accessible name (ie the "alternative text")

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe will confirm that using the second option lets you change the color via scss.

**Comment by roslynwythe** [comment]
- Issue #6655 will implement the solution presented in https://github.com/hackforla/website/issues/4242#issuecomment-1759091791 
- Issue #6653 will create a wiki page to document the technique.

**Comment by roslynwythe** [comment]
Closing
