### ISSUE TITLE
ER: New code of conduct page 

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4243]
### Emergent Requirement - Problem
We need to add the code of conduct to our website, and we need several issues to do it

### Issue you discovered this emergent requirement in
- #110

### Date discovered 
2023-03-16

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
Our Code of Conduct is a mess.  It's hard for the people onboarding.  It also references CfA which will no longer be necessary

### Resources
https://github.com/hackforla/codeofconduct

### Recommended Action Items
- [x] Make new issues
1. Cleanup Code of Conduct
   - [x] #4244
     - role: product
2. New CoC page on hfla website
   - [x] #4249 
   - [x] Create a code of conduct page 
      - role: front end
3. Create a DR that records why our CoC branch is behind master
   - [x] #4250 
   - [x] DR: Code of Conduct differences between parent fork and HfLA
4. Make it go live on Transfer date
   - [x] #4251 
   - [x] Make the new code of conduct page live
      - role: front end
- [ ] Discuss with team
- [ ] Let a Team Lead know

#### Issue 2
The New Code of Conduct page should have a top nav and footer, but should get all its content from a markdown.  See 
- https://www.hackforla.org/about/
https://github.com/hackforla/website/blob/8cfa868c4065d753e0919305748e4d53d918977c/_includes/about-page/about-card-executive-letter.html#L6
- https://github.com/hackforla/website/blob/gh-pages/_data/internal/executive_letter.yml
- the page will be called code-of-conduct.html and live in the pages directory
- page will be visible by going to https://www.hackforla.org/code-of-conduct

#### Issue 3
- the details are in the comments on #4244

#### Issue 4
- Dependency: 2023-06-01
- Change the current redirect https://github.com/hackforla/website/blob/gh-pages/redirections/conduct.md to redirect to the new page https://www.hackforla.org/code-of-conduct

**Comment by jdingeman** [comment]
Drafted issue for Creating a new Code of Conduct page is here:
- https://github.com/hackforla/website/issues/4249

**Comment by jdingeman** [comment]
Issue for DR on HfLA Code of Conduct:
- https://github.com/hackforla/website/issues/4250

**Comment by jdingeman** [comment]
Issue for launch of Code of Conduct here:
- https://github.com/hackforla/website/issues/4251

**Comment by jdingeman** [comment]
Issues all created. Closing this ER.
