### ISSUE TITLE
ER: update the Project Profile Card Review & Update issue template

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4246]
### Emergent Requirement - Problem
VRMS has changed the way that PMs can update meeting times, so we need to update the [Project Profile Card Review & Update](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D) issue template to change our instructions to their new process

In our Project Profile Card Review & Update issue template, it has
If YES on update meeting times, open an issue on VRMS to update the meeting times and provide the link to the new issue
[text box]
### Resources
- [VRMS Add/edit team meeting time template issue](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D)

The VRMS team has now made it possible for PMs to edit their meeting times directly in VRMS. 
I have made all the current PMs on projects editors on their projects in VRMS 
So if a PM is putting in a change with us and they see that their meeting times are not displaying correctly.  They should see the [VRMS User guide](https://github.com/hackforla/VRMS/wiki/User-Guide)

### Issue you discovered this emergent requirement in
- #2292

### Date discovered 
2023-03-22

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
People will keep opening tickets at VRMS that they are ignoring, and meeting time updates won't happen.

### Resources
 - [Open a new Project Profile Card Review & Update Issue](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D)
- template file: https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
update the template to replace all the VRMS related stuff with the text
```
If you need to update your meeting times, names, dates, or frequency, please see the [VRMS User Guide](https://github.com/hackforla/VRMS/wiki/User-Guide).  We get the meeting times from the updates the Project PM makes to the projet's meeting data in vrms.io
```

**Comment by jdingeman** [comment]
New issue made here:
- https://github.com/hackforla/website/issues/4268
