### ISSUE TITLE
ER: Increase width of event cards on Events page

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4247]
### Emergent Requirement - Problem
The events page two columns are unnecessarily narrow, leading to wrapping in the meeting titles

### Issue you discovered this emergent requirement in
- #950

### Date discovered 
2023-03-22

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
the meeting time names are wrapped which makes the page hard ro read

### Resources
https://www.hackforla.org/events/
<details>
<summary>full page screenshot of hackforla.org/events page</summary>

![screencapture-hackforla-org-events-2023-03-22-13_46_55](https://user-images.githubusercontent.com/37763229/227034282-8a9dce8c-1378-464a-be38-ee6bb99fbdd9.png)
</details>

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
Make it as wide as the locations images below

**Comment by jdingeman** [comment]
New issue here:
- https://github.com/hackforla/website/issues/4271
