### ISSUE TITLE
Update Project Profile: Food Oasis

### ISSUE THREAD

**Issue by itserindean** [hackforla/website#4248]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Food Oasis project page needs to be updated to reflect accurate partner information. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/food-oasis.md` file and find the `partner` variable.
- [x] Add the following partner
  - [x] UCLA (CESC 50XP)
- [x] Verify the changes by viewing the [Food Oasis project page](https://www.hackforla.org/projects/food-oasis) and the Food Oasis card on the [projects page](https://www.hackforla.org/projects/) on your local environment and include a screenshot with your pull request

### Resources
- [food-oasis.md](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by jdingeman** [comment]
### Project Name

Food Oasis

### Project Card URL

food-oasis.md


### Update the Partner(s)?

YES

### Partners

UCLA (CESC 50XP)

**Comment by ExperimentsInHonesty** [comment]
@thedvo This issue has not been completed.  I am reopening it and moving it back to the prioritized backlog.  To remove yourself from notifications for this issue, you have to open it and click the unsubscribe button.  But do not close it again.

**Comment by agutiernc** [comment]
i. Availability: Today.
ii. ETA: End of Day.
