### ISSUE TITLE
Launch HfLA Code of Conduct

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4251]
### Dependency
- [x] https://github.com/hackforla/website/issues/4249
- [x] Launch Date: June 1st, 2023

### Overview
We currently have a redirect in place for the HfLA Code of Conduct that leads to this [page](https://github.com/hackforla/codeofconduct). Since we have a new Code of Conduct page, we need to "launch" the page so that the public can view the Code of Conduct on the website. 

### Action Items
- [x] Change the [/redirections/conduct.md](https://github.com/hackforla/website/blob/gh-pages/redirections/conduct.md) from 
```
https://github.com/hackforla/codeofconduct
```
to
```
https://www.hackforla.org/code-of-conduct
```
- [x] Add a new link to the Code of Conduct in [/_includes/footer.html](https://github.com/hackforla/website/blob/gh-pages/_includes/footer.html) so it shows up here between `Privacy Policy` and `Join Us` (so that Join Us is the last item): 
 
![image](https://user-images.githubusercontent.com/37763229/227071617-db4f2099-049a-4499-bffc-bfc2807be7db.png)

### Resources/Instructions
- ER associated with this issue: https://github.com/hackforla/website/issues/4243

**Comment by mademarc** [comment]
Availability:4/4/2023 
ii. ETA: 4/10/2023

**Comment by jdingeman** [comment]
@mademarc - this issue is not ready for devs to pick up. Please only pick up issues out of the Prioritized Backlog.

**Comment by Jung-GunSong** [comment]
i. I am available to fix this issue from now until Tuesday of next week. 

ii. The issue will prob not take more than 1-2 hours of work.

As always let me know if there's anything else!

**Comment by mademarc** [comment]
Review ETA: 01/12/2024
Availability: 1:30PM
