### ISSUE TITLE
ER: Meetings that are on the events page but their project does not exist on the website

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4252]
### Emergent Requirement - Problem
Projects like Tech Work Experience, which is not yet on the website, is showing up on the events page but can't link to their project page because there isn't one yet.

### Issue you discovered this emergent requirement in
- #950

### Date discovered 
2023-03-22

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
Some of the project links on the page go to 404

### Resources
https://www.hackforla.org/events/

### Recommended Action Items
- [x] Make a new issue
- [x] Discuss with team
- [x] Let a Team Lead know

### Potential solutions [draft]
We could only show projects for which there is a active project page or Community of Practice or its an onboarding.  
Or we could create some kind of default page that we send the links to if the project page does not exist.

### Note:
- This issue is a dependency for another issue https://github.com/hackforla/website/issues/950.  Please add the issue that you create from this, into the the 950 issue.

**Comment by blulady** [comment]
@ExperimentsInHonesty should merge team make this an issue?

**Comment by jdingeman** [comment]
I like the idea of having a default page that says something like "We are still drafting this page" or something fun like "This project page is under construction. Check back soon!"

**Comment by jdingeman** [comment]
It is possible that the URLs are getting defined by VRMS.

**Comment by t-will-gillis** [comment]
The broken links have been fixed; all links confirmed working as of 8/25/23. Re: #4906
