### ISSUE TITLE
ER: Technologies and Tools confusion

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4261]
### Emergent Requirement - Problem
Project Managers are adding items to technologies instead of tools.  If a team adds something to tools, it's not showing up in technologies

### Issue you discovered this emergent requirement in
- #3487

### Date discovered 
2023-03-23

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
Using the filters on the projects page is less effective

### Resources
https://www.hackforla.org/projects-check/

### Recommended Action Items
- [x] Make new issues
   - [x] Add a Tools drop down to the projects-check page #4427
   - [ ] Revise the Project page Languages / Technology filter to include tools
      - Update the #3487 dependency with a link to `Revise the Project page Languages / Technology filter to include tools` issue
      - Last action item should be `- [ ] Release dependency on #3487`
   - [x] #4262
- [ ] Discuss with team
- [ ] Let a Team Lead know

**Comment by jdingeman** [comment]
Issue made here:
- https://github.com/hackforla/website/issues/4427

**Comment by ExperimentsInHonesty** [comment]
I am reopening this ER because there is still an issue missing 
Revise the Project page Languages / Technology filter to include tools

**Comment by ExperimentsInHonesty** [comment]
- epic https://github.com/hackforla/website/issues/4434
