### ISSUE TITLE
Update Project Profile Card Review & Update template

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4268]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
PMs are now able to directly change the meeting times for their teams in VRMS. We need to change the [Project Profile Card review and update](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml) template so that PMs are redirected to the [VRMS User Guide](https://docs.google.com/presentation/d/1bv9QH-d5qKtFCaecgCvsv608IoeLIpHfW7cEEqijHyE/preview?slide=id.g20628192ba7_0_93) if they need to change certain things about their meetings. 

### Action Items
- [x] In  [ISSUE_TEMPLATE/project-profile-card-review-and-update.yml](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml), replace the content in the `value` field on line 332 with
```
If you need to update your meeting times, names, dates, or frequency, please see the [VRMS User Guide](https://github.com/hackforla/VRMS/wiki/User-Guide).  The HackforLA.org website gets the meeting times from the updates the Project PM makes to the projet's meeting data in vrms.io
```
- [x] Remove lines 311 - 324

### Resources/Instructions
- Emergent Request Associated with this issue: https://github.com/hackforla/website/issues/4246
- [Deprecated method](https://github.com/hackforla/VRMS/issues/new?assignees=&labels=1+week+change+request&template=add-edit-team-meeting-time.md&title=Meeting+time+change+request+for+%5BProject+Name%5D) of requesting updated meeting times in VRMS
- [Template](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D) for opening a new issue to update Project Profile Card

**Comment by drakenguyen4000** [comment]
i. Availability: 3/25/23 
ii. ETA: 3/25/23
