### ISSUE TITLE
Create a new credit file for use of artist's image

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4269]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Currently, the alt text for the [Not Today logo](https://github.com/hackforla/website/blob/gh-pages/assets/images/projects/not-today.png) does not contain the credit to the artist. We need to create a new credit file for the artist so that we are in legal compliance for use of his image.

### Action Items
- [x] Create a new credit in [/internal/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits) called "cwmoss.yml"
- [x] Paste the content below into the file

```
---
# The title from the source provider
title: unknown
# The url where you can get direct access to the image on the provider site
title-link: 
# The type of content - image, audio, or video 
content-type: image 
# The page it's used on
used-in: Not Today Project Logo
# Name of the artist
artist: C.W. Moss
# Name of the image database you found it on
provider: The Grey Rainbow
# Please give the general site URL, not the link to the image
provider-link: http://greyrainbow.com/
# Location in our GitHub repo
image-url: assets/images/projects/not-today.png
---
```

- [x] For consistency across credit files, remove the comments in the new file you created

### Resources/Instructions
- Emergent Request associated with this issue: https://github.com/hackforla/website/issues/4240
- [Credits yml file template for Iconography and Imagery](https://github.com/hackforla/website/wiki/Credits-yml-file-template-for-Iconography-and-Imagery)

**Comment by ExperimentsInHonesty** [comment]
- Added a question to the ER #4240

**Comment by ExperimentsInHonesty** [comment]
We may or may not get additional information for this before your PR happens.  If we do, we will reach out. If we get it after, we will create a new issue.

**Comment by janice87** [comment]
i. Availability: 3/28 - 3/29 5-9PM EST 
ii. ETA: 3/29 9PM EST
