### ISSUE TITLE
Increase width of event columns on Events page

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4271]
### Overview
The white columns on the [Events](https://www.hackforla.org/events/) page are very narrow, which causes the events and meeting title text to wrap. We want to make the columns on the Events page wider so that the content is easier to read.

### Action Items
- [x] Edit the code in [/sass/components/_events.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_events.scss) to make the columns wider
- [x] First try matching the width of the columns to meet the edge of the "Our Locations" images below it

<details>
<summary>Referenced edges</summary>

![image](https://user-images.githubusercontent.com/88953806/227401762-6c2e1e2e-cefb-4ac6-b3b6-6b82b6dee716.png)

</details>

- [x] Try out other widths and placements that may look good instead of the current layout
- [x] Add images of different potential solutions to this issue
- [x] Consult with Product/Bonnie on the best layout from your proposals
- [x] Create a pull request with the changes of the final decision

### Resources/Instructions
- Guide to [Sass Basics](https://sass-lang.com/guide)
- Emergent Request associated with this issue: https://github.com/hackforla/website/issues/4247
<details>
<summary>Full page screenshot of Events page</summary>

![image](https://user-images.githubusercontent.com/88953806/227402255-63213067-30e1-434d-907b-a022a349bf2d.png)

</details>

**Comment by kwangric** [comment]
i. Availability: Weekdays after 1pm PDT
ii. ETA: 3/28 afternoon

**Comment by kwangric** [comment]
Below are two potential solutions.

<details>
<summary>Solution A</summary>

- Increased overall width of the event columns to match the width of the "Our Locations" images below. Also centered time zone text.
- Increased margins between the event columns to 32px to match the margins between the location images.

![Solution A](https://user-images.githubusercontent.com/43795498/228092269-72fddad8-ff51-4204-8c49-ed67adc8cad8.png)

</details>

<details>
<summary>Solution B</summary>

- Same changes as Solution A but kept the margins between the event columns the same as before (16 px).

![Solution B](https://user-images.githubusercontent.com/43795498/228092290-0e62f767-e57a-4685-a113-f1f90ad0251e.png)

</details>

<details>
<summary>Current Layout</summary>

![Current](https://user-images.githubusercontent.com/43795498/228092244-84008936-029e-4bbe-8d80-d9b0b97c377f.png)

</details>

**Comment by jdingeman** [comment]
@kwangric - nice job! I think both layouts look really good, but let's hear from @ExperimentsInHonesty for which solution may be the best to go with. I am going to put this into Questions/In Review and add the label so she has visibility of your potential solutions.

**Comment by ExperimentsInHonesty** [comment]
@kwangric I literally can't tell the difference between A and B

Perhaps screenshots of the parts that are different side by side or put stars next to the difference.

lol, this is like one of those can you spot the differences games!

**Comment by kwangric** [comment]
@ExperimentsInHonesty Below are the differences between A and B circled in green. The only difference is the width between the columns. Solution B has the original width, while in Solution A I increased the width to match the location pictures at the bottom of the page. Let me know if that makes it any more clear!

![Changes](https://user-images.githubusercontent.com/43795498/229433294-ea0888d6-138c-4824-beb9-2195cfc343e5.png)

**Comment by ExperimentsInHonesty** [comment]
@kwangric Thank you!!! that was really helpful.  Solution A please.
