### ISSUE TITLE
ER: Get Google Data Studio up to date so that we can use it for insights and its ready for launch

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4276]
### Emergent Requirement
GDS is not being actively used, we need to fix that.

### Issue you discovered this emergent requirement in
- #2776

### Date discovered 
2023-01-15

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
- This page will be public facing (when the about page is launched), and we need it to be relevant to people who view it
- We also need a way to use the data to improve onboarding and other things, it's highlighting
- There are projects on the form that are no longer live.  The form that drives it should allow people to check those as ones they are interested in from a list of specific projects

### Resources
- [Google Data Studio/Looker HfLA Dashboard](https://lookerstudio.google.com/reporting/16J9XI19pQejSDNFvjl_V3ZezJ502rM_a/page/e1JSB)
- [Form from onboarding that is supposed to feed the dashboard](https://docs.google.com/forms/d/e/1FAIpQLSdTM20e-XBD3_fmTPlYfkBKT7cv7aKdO1b2yx_OCrbHLCvLog/viewform)
- [Survey Data Workbook](https://docs.google.com/spreadsheets/d/1sIhdPzSpMNn7ZwGftiCbgMRtF-84ziJgmr8EjsC_yK8/edit?usp=sharing)
- [Remote Onboarding data tab](https://docs.google.com/spreadsheets/d/1sIhdPzSpMNn7ZwGftiCbgMRtF-84ziJgmr8EjsC_yK8/edit#gid=340717816)
- [Onboarding Slides](https://docs.google.com/presentation/d/1bueC40PkklLSJVPttiFeYJvcB69PgJx8pxZK5G7gzzo/)

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team (added to [PM agenda](https://github.com/hackforla/website/issues/2212)
- [ ] Let a Team Lead know

**Comment by ExperimentsInHonesty** [comment]
This issue has been resolved.  Whatever was breaking the links has been fixed

**Comment by Samhitha444** [comment]
- [ ] All the links in this issue will need to be checked to see if we have access
- https://github.com/hackforla/website/issues/2776
  - [ ] Have access, its located in ____
  - [ ] public
- [Live Project Board Issues Dashboard (Current)](https://lookerstudio.google.com/u/0/reporting/6410c484-f38f-44ba-b4ed-c29a6b2a081b/page/e1JSB](https://lookerstudio.google.com/reporting/16J9XI19pQejSDNFvjl_V3ZezJ502rM_a/page/e1JSB))
  - [ ] Have access, its located in ____
  - [ ] public
- https://github.com/hackforla/live-dashboard-automation/blob/444e9f010fe11e015acac6e9d2b14707398be049/.github/workflows/schedule_run_to_update_data.yaml#L56-L58
  - [ ] Have access, its located in ____
  - [ ] public
- https://github.com/hackforla/live-dashboard-automation/actions
  - [ ] Have access, its located in ____
  - [ ] public
- https://lookerstudio.google.com/u/0/reporting/6410c484-f38f-44ba-b4ed-c29a6b2a081b/page/e1JSB
  - [ ] Have access, its located in ____
  - [ ] public

**Comment by Samhitha444** [comment]
- [ ] All the links in this issue will need to be checked to see if we have access
- https://github.com/hackforla/website/issues/2776
  - [ ] Have access, its located in ____
  - [x] public
- [Live Project Board Issues Dashboard (Current)](https://lookerstudio.google.com/u/0/reporting/6410c484-f38f-44ba-b4ed-c29a6b2a081b/page/e1JSB)
  - [ ] Have access, its located in ____
  - [x] public
- [Hack for LA new volunteer survey](https://docs.google.com/forms/d/e/1FAIpQLSdTM20e-XBD3_fmTPlYfkBKT7cv7aKdO1b2yx_OCrbHLCvLog/viewform) - Form
  - [ ] Have access, its located in ____
  - [x] public
- https://docs.google.com/spreadsheets/d/1sIhdPzSpMNn7ZwGftiCbgMRtF-84ziJgmr8EjsC_yK8/edit?usp=sharing
  - [x] Need access, its located in ____
  - [ ] public
- https://docs.google.com/spreadsheets/d/1sIhdPzSpMNn7ZwGftiCbgMRtF-84ziJgmr8EjsC_yK8/edit#gid=340717816
  - [x] Need access, its located in ____
  - [ ] public
- [B: Hack for LA Self Onboarding](https://docs.google.com/presentation/d/1bueC40PkklLSJVPttiFeYJvcB69PgJx8pxZK5G7gzzo/)
  - [ ] Have access, its located in ____
  - [x] public
- https://github.com/hackforla/website/issues/2212
  - [ ] Have access, its located in ____
  - [x] public
