### ISSUE TITLE
ER: Make Program Area Consistent `Diversity, Equity & Inclusion`

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4281]
### Emergent Requirement - Problem
We have inconsistent references to the 'Diversity, Equity & Inclusion' program area across the website. Excluding where we need to continue using the 'Diversity / Equity / Inclusion' (refer to #4120), we want the name of this program area to be consistent.

### Issue you discovered this emergent requirement in
- #4120 

### Date discovered 
2023-3-23

### Did you have to do something temporarily
- [ ] YES
- [X] NO

### Who was involved
@t-will-gillis @ExperimentsInHonesty 

### What happens if this is not addressed
We will not be presenting a professional image on our website.

### Resources
- [Join Us page](https://www.hackforla.org/join)
- [About page](https://www.hackforla.org/about/#platform)
- [Program Areas page](https://www.hackforla.org/program-areas)
- [/pages/join-us.html](https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html)
- [/_includes/about-page/about-card-platform.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-platform.html)
- [/_data/internal/program-areas/diversity-equity-inclusion-card.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/program-areas/diversity-equity-inclusion-card.yml)

### Recommended Action Items
- [X] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
- Make changes to the files noted in 'Resources' above to refer consistently to the program area `Diversity, Equity & Inclusion`
- Do NOT make changes to the name of the program area if this will cause a feature to break- that is: continue using `Diversity / Equity / Inclusion` as shown in #4120 
- NOTE: Could be split into three X  `good first issue` , maybe three X `Complexity: Good second issue` ?

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis I agree, splitting into 3 good second issues would solve our shortage there.  Let us know if you are going to do that, or if you want someone else to do it.

**Comment by t-will-gillis** [comment]
@ExperimentsInHonesty Thank you- I will split into 3 good second issues, later today.

**Comment by t-will-gillis** [comment]
Issues created:
- #4284 
- #4286 
- #4287
