### ISSUE TITLE
Make Program Area Consistent on Program Areas Page

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4284]
### Overview
We want our website to use terms consistently when referring to program areas. On the [Program Areas](https://www.hackforla.org/program-areas) page, we need to change the title of the `Diversity, Equity, and Inclusion` card to `Diversity, Equity & Inclusion`.

### Action Items
- [x] Change the 'name' field of the[ diversity-equity-inclusion-card.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/program-areas/diversity-equity-inclusion-card.yml) file to: `Diversity, Equity & Inclusion`.
- [x] Important note: do **not** change the 'program-area' field on the same card. It needs to remain as shown.

### Resources/Instructions
- [Program Areas page](https://www.hackforla.org/program-areas)
- [/pages/program-areas.html](https://github.com/hackforla/website/blob/gh-pages/pages/program-areas.html)
- [/_data/internal/program-areas/diversity-equity-inclusion-card.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/program-areas/diversity-equity-inclusion-card.yml)

**Comment by LOSjr4** [comment]
Availability: Mon, Tues, Thursday 9AM - 1PM
ETA: 3/28/2023 1PM

**Comment by jch1013** [comment]
Availability: Thursday any time
ETA: 3/28 EOD
