### ISSUE TITLE
ER: Reorder the website team members

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4285]
### Emergent Requirement - Problem
The order of the team members on the website project card could be improved to have the leaders at the top.  Bonnie followed by Justin instead of Bonnie, Sarah, Arpita, Justin.

### Issue you discovered this emergent requirement in
- #4219

### Date discovered 
2023-03-24

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
Nothing much, it just doesn't make as much sense as reordering it.

### Resources
<details>
<summary>Current Project Team screenshot</summary>

![image](https://user-images.githubusercontent.com/37763229/227677976-bb71a7d0-5b6b-475c-9a48-d820724a419e.png)
</details>

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [x] Let a Team Lead know

**Comment by jdingeman** [comment]
New issue made here:
- https://github.com/hackforla/website/issues/4358
