### ISSUE TITLE
Make Program Area Consistent on About Us Page

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4286]
### Overview
We want our website to use terms consistently when referring to program areas. On the [About Us](https://www.hackforla.org/about/) page, in the 'Hack for LA Platform' section, we need to change the title of the `Diversity, Equity, and Inclusion` subsection to `Diversity, Equity & Inclusion`.

### Action Items
- [x] Change the corresponding `<span>` element on the [about-card-platform.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-platform.html) file so that `Diversity, Equity & Inclusion` is displayed.

### Resources/Instructions
- [About Us page](https://www.hackforla.org/about/)
- [/_includes/about.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about.html)
- [/_includes/about-page/about-card-platform.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-platform.html)

**Comment by aaronweixiangli** [comment]
i. Availability: 3/26/23 2-3pm
ii. ETA: 3/26/23
