### ISSUE TITLE
Make Program Area Consistent on Join Us Page

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4287]
### Overview
We want our website to be use terms consistently when referring to program areas. On the [Join Us](https://www.hackforla.org/join) page, in the 'Advise Us' section, we need to change the text `Diversity Equity and Inclusion` to `Diversity, Equity & Inclusion`.

### Action Items
- [x] Change the text in the 'Advise Us' section of the [join-us.html](https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html) file from `Diversity Equity and Inclusion` to `Diversity, Equity & Inclusion`.

### Resources/Instructions
- [Join Us page ](https://www.hackforla.org/join)
- [/pages/join-us.html](https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html)

**Comment by janice87** [comment]
i. Availability: 3/26 5-9PM EST
ii. ETA: 3/26 9PM EST
