### ISSUE TITLE
Update template of project.md file

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#429]
### Overview
Update template of project.md file

### Action Items
- [ ] Incorporate all possible links into project.md file

### Resources/Instructions
[project.md template](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)

**Comment by cnk** [comment]
The way the project cards are coded, there isn't an "all possible links". We have some links that show up special sections but then any other link added to the 'links' section is displayed at the bottom of the card.

If you want examples of all possible links, I would need a list of allowed link types and then we would have to change the way the project homepage is coded to display only links that match those types.

**Comment by ExperimentsInHonesty** [comment]
@cnk can you give us a break down of what links will appear where?

**Comment by cnk** [comment]
@ExperimentsInHonesty 

On the project homepage
  - links with the names "GitHub", "Site", and "Test Site" displayed in the "Links" section in the left half of the Project Overview. (I also suggested to Kian that he add "Demo Site" links to display on this section)
  - Links named Wiki and Readme are displayed under the "Getting Started" dropdown
  - All links are also displayed in the "Resources" section at the bottom of the project homepage

On the project card on HfLA homepage:
  - all links are displayed

**Comment by cnk** [comment]
Blockers: unsure of what action is needed

**Comment by ExperimentsInHonesty** [comment]
@cnk will move this info to the [template](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file) and close this issue.  All new updates to template will be described on the template wiki page.

**Comment by cnk** [comment]
Updated the [wiki](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file) with how links are displayed on the site.
