### ISSUE TITLE
Replace inline SVGs with IMG elements in footer

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4299]
### Overview

SVG files instantiated using an inline `<svg>` element do not contain alt text and so they are not WCAG compliant, and screen readers attempt to vocalize the links associated with the social media icons using their svg filenames which are not user-friendly.  In this issue we will provide an aria-label attribute to the <a href> element which wraps each social media icon, so that the screen reader will vocalize the descriptive name of the icon.  

### Action Items

- [x] HTML used for rendering the footer can be found in `_includes/footer.html`
- [x] replace 
```
              <a href="{{ item.link }}" rel="noopener" target="_blank" class="js-inline-link js-inline-link-{{ item.name | downcase }}">
```
with
```
              <a href="{{ item.link }}" rel="noopener" target="_blank" class="js-inline-link js-inline-link-{{ item.name | downcase }}" aria-label="{{ item.name }}" >
```
- [x] Browse to a HfLA web page (for instance the [Donate Page](https://hackforla.org/donate)) then enable the Google Chrome Screen Reader Extension.  Press the Tab key to navigate through the interactive elements on the page, and listen to the screen reader vocalize the accessible name of each interactive element.  Confirm that the name of each social media icon/link is correct. 

### Resources/Instructions

- [Footer HTML](https://github.com/hackforla/website/blob/gh-pages/_includes/footer.html)
- [Wiki "How to make SVGs and other images WCAG compliant"](https://github.com/hackforla/website/wiki/How-to-make-SVGs-and-other-images-WCAG-compliant) - see the section [Use an ARIA label in the div tag wrapping the svg ](https://github.com/hackforla/website/wiki/How-to-make-SVGs-and-other-images-WCAG-compliant#use-an-aria-label-in-the-div-html-tag-wrapping-the-svg) for a description of this technique
- [Chrome Screen Reader Extension](https://chrome.google.com/webstore/detail/screen-reader/kgejglhpjiefppelpmljglcjbhoiplfn)

**Comment by wongstephen** [comment]
i. Availability: AUG 2 10AM - 5PM PST
ii. ETA: EOD AUG 2
