### ISSUE TITLE
Change logic for project card and project homepage

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#430]
### Overview
We need to edit what is seen for projects that are completed.  Currently it does not display a project homepage, but we are going to re-enable that, and just edit what does appear.

### Action Items
For projects with a status of completed
- [x] hide getting started link (on project homepage)
- [x] write logic around not displaying getting started on projects with a completed status.
- [x] All project lead links will need to go to their github or linked instead of slack.
- [x] Add the a new field to the project.md file template called "completed-contact"
- [x] Add a project contact email link where open roles used to be. 
   - [x] PM to work with Designers about adding "If you would like to talk to us about this completed project, please reach out to team@hackforla.org"
- [x] Add logic that automatically uses team@hackforla.org as the email if there is not completed-contact email listed.

### Resources/Instructions
[example project with completed status](https://www.hackforla.org/projects/work-for-la)

**Comment by ExperimentsInHonesty** [comment]
@yulia-kh please update
1. progress
2. blocks
3. availability
4. ETA

**Comment by yulia-kh** [comment]
I'm still working on the issue. I have a question about project-homepage field. Do we need it after I finish working on this issue?

**Comment by ExperimentsInHonesty** [comment]
work for la contact is : WorkForLA@googlegroups.com.

**Comment by yulia-kh** [comment]
@KianBadie  Can you please review changes?

Getting started button for completed projects is hidden.
If we have a contact for a project we can see the provided email: 

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/13112628/82156239-e0767a80-982e-11ea-8d96-ee2be047c2d2.png">

If we don't have a contact then we see hack for la email:

<img width="1049" alt="image" src="https://user-images.githubusercontent.com/13112628/82156310-4d8a1000-982f-11ea-9ec7-b868e9f3b0e2.png">

Also all slack links for leadership team replaced with linkedin links (if provided) or github links

**Comment by ExperimentsInHonesty** [comment]
@yulia-kh is the email a link?  It’s showing as black on screen shot

**Comment by yulia-kh** [comment]
@ExperimentsInHonesty It's just a string now. I was thinking that we can put any wording in the contact-completed like name and email that will display "If you would like to talk to us about this completed project, please reach out to Joe Doe example@somemail.org". If we 100% sure that it's always an email address I can make it a mailto link

**Comment by ExperimentsInHonesty** [comment]
@yulia-kh for now just make it an email.
