### ISSUE TITLE
Cleanup Heart's project.md file

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#431]
### Overview
This project is about to become a showcase, we need to clean up the online presentation

### Action Items
- [x] Get a Hero image - Already added to the folder. See Charlotte's PR below.
- [x] Identify who the leaders of the project and their titles are
- [x] Update file with the above information
- [x] Add Wiki to the links
- [x] Remove Looking For details

### Resources/Instructions
[Heart project wiki](https://github.com/hackforla/heart/wiki)

**Comment by ExperimentsInHonesty** [comment]
@charlottesauce Can you make a hero image for this project?

**Comment by charlottesauce** [comment]
Sure. I think I'm just going to put our mocks up in an aesthetically
pleasing way for the hero.

**Comment by ExperimentsInHonesty** [comment]
@charlottesauce can I get hero from you on this, so the team can make the change today?

**Comment by writeforeveryone** [comment]
@ExperimentsInHonesty 

Below is the shutterstock img we talked about. It's a bit more blurry than we could tell. 

image-hero: /assets/images/projects/heart-hero.jpg
alt-hero: "a line of tents under a freeway overpass"

![heart-hero](https://user-images.githubusercontent.com/63891329/79699552-11ba5580-8245-11ea-848d-ed50117d3e85.png)

**Comment by charlottesauce** [comment]
@ExperimentsInHonesty

made a pull request with the changes.

**Comment by ExperimentsInHonesty** [comment]
Here is the leadership of this team:

For those that we don't have github handles for, I provided a picture that you can link to for the page.  Where it usually says slack under the person, put a new link that says linkedin.  I will have to work with the dev team to change the logic so if the status is completed it uses the linked in

Marie-Aimee Brajeux
Product Manager
https://linkedin.com/in/marie-aim%C3%A9e-brajeux-88b40978/
link to this picture:
![marie](https://user-images.githubusercontent.com/37763229/79702509-34a33480-825a-11ea-94e8-ff952f42863d.jpg)

Adrian Inchauste
Design Sprint Facilitator
https://linkedin.com/in/adrianinchauste
link to this picture: 
![Adrian](https://user-images.githubusercontent.com/37763229/79702530-63210f80-825a-11ea-8314-93950014939d.jpg)

Jason LaManque
Design Sprint Facilitator
https://www.linkedin.com/in/jasonlamanque/
Link to this picture: 
![Jason](https://user-images.githubusercontent.com/37763229/79702551-9a8fbc00-825a-11ea-819f-dde8cad5d058.jpg)

Lex Roman
UX Advisor (1st stage)
https://linkedin.com/in/lexroman/
https://github.com/calexity

Gian Reyes Dionisio
UX Design Lead
https://linkedin.com/in/gianreyesdionisio/
https://github.com/gianbun

Charlotte Soestini
UX Design and Documentarian (post project)
https://linkedin.com/in/charlotte-soestini
https://github.com/charlottesauce

Bonnie Wolfe
Documentarian (post project)
https://linkedin.com/in/bonnieawolfe
https://github.com/experimentsinhonesty

Roland Abregorivas
Tech Lead
https://linkedin.com/in/rolandabregorivas
https://github.com/abregorivas

Tien Yuan
Tech Lead
https://linkedin.com/in/tienyuan/
https://github.com/tienyuan

**Comment by ye-susan** [comment]
PR was created - updated leadership information, wiki link, and removed 'looking for' details.

**Comment by cnk** [comment]
Looks good - except for the links that lead nowhere. @ye-susan Do you want to take a stab at the link logic (linking to linked in rather than Slack)? Let me know if you need help finding the template that builds the links.

**Comment by ExperimentsInHonesty** [comment]
- [x] change status to Completed

**Comment by ye-susan** [comment]
I've changed the status and have created a pull request
