### ISSUE TITLE
ER: sdg-img-item class seems to not be used anywhere in our codebase

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4343]
### Emergent Requirement - Problem
In `_sass/components/_project-page.scss`, it doesn't seem `.sdg-img-item` class is used anywhere in our codebase.

### Issue you discovered this emergent requirement in
N/A

### Date discovered 
2023-03-29

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
GitHub handle: JessicaLucindaCheng 

### What happens if this is not addressed
We have an extraneous SCSS class in our codebase that isn't used to style any HTML.

### Resources
- [_sass/components/_project-page.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-page.scss)

### Recommended Action Items
- [ ] Search and check 
  - [ ] If an open issue exists that addresses this ER
  - [ ] If a closed issue exists that has already addressed this ER
- [ ] If an open issue doesn't exist and this ER wasn't already fixed by a closed issue, make a new issue 

### Potential solutions [draft]
- Figure out if the class is used anywhere in our codebase
- If it is not used, remove the class.

**Comment by jdingeman** [comment]
New issue made here:
- https://github.com/hackforla/website/issues/4422

Verified that class is not used anywhere in the code base.
