### ISSUE TITLE
Update Contributing.md to add information about Setting up SSH keys

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4350]
### Overview
Sometimes new developers run into authorization issues when they attempt to push code to their remote repository. We need to update the [contributing.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) to include documentation about setting up SSH keys so new developers know how to work past these potential issues.

### Action Items
- [x] Review research in https://github.com/hackforla/website/issues/947
- [x] In the contributing.md, add a new section 2.7.f named "Working on an issue (6): Handling SSH authorization errors"
- [x] Write instructions for setting up SSH kes for both Windows users and Mac users
- [x] View the changes made in your remote repository to ensure the style of the new section is in line with the rest of the contributing.md
- [x] Create a pull request with your changes

### Resources/Instructions
- [Generating a new SSH key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent)
- [Comment](https://github.com/hackforla/website/issues/947#issuecomment-806257539) with developer research

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - wasn't sure if this would be under Onboarding flow or Team workflow

**Comment by ExperimentsInHonesty** [comment]
@jdingeman I answered your question in the new ER I just created #4369.  Its Team workflow.

**Comment by Jaretzbalba** [comment]
Availability: 2 hours
ETA: 4/7/2023
