### ISSUE TITLE
Edit credits.html to only include href if credit has a title-link

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4351]
### Overview
Some of the credits in [/credits](https://github.com/hackforla/website/tree/gh-pages/_data/internal/credits) don't have a direct link to their photos. We need to update [credits.html](https://github.com/hackforla/website/blob/gh-pages/pages/credits.html) so that it only renders a link to the credit's photo if it has a direct link. 

### Action Items
- [x] See line 39 in credits.html:
https://github.com/hackforla/website/blob/a3c702fc14be53f17f16cf906b54eb6e63d19fd9/pages/credits.html#L39
- [x] Using Liquid, edit the html so that the title only links to photo if the credit has a valid `title-link`
- [x] All credits that do have a valid `title-link` must still have a direct link to their photos
- [x] Ensure this does not break any other page that uses the credits

### Resources/Instructions
- Example of a credit without a valid `title-link`: [cwmoss.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/cwmoss.yml)
- [Liquid](https://jekyllrb.com/docs/liquid/) in Jekyll

**Comment by drakenguyen4000** [comment]
ETA: 4/7/23
Availability: M-F 4pm-8pm

**Comment by Jaretzbalba** [comment]
@drakenguyen4000 I moved this issue over to the `in progress` column to make sure no one else works on this!

**Comment by drakenguyen4000** [comment]
I'll need one more day for this issue.  Reviewing Liquid before writing the code.  
ETA: 4/8/23
Availability: Sat-Sun 12pm-8pm
