### ISSUE TITLE
Add link to CONTRIBUTING.md for VS Code's documentation on Merge Conflicts

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4352]
### Overview
Merge conflicts are an issue that many developers will face for various reasons. We want to update the [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) with a link to VS Code's [documentation on Merge Conflicts](https://code.visualstudio.com/docs/sourcecontrol/overview#_merge-conflicts) so that developers are prepared to deal with merge conflicts.

### Action Items
- [x] Navigate to CONTRIBUTING.md
- [x] Add a new section under 3.1.c
  - [x] Name it "3.1.d Dealing with merge conflicts"
  - [x] Add a link to VS Code's [documentation on Merge Conflicts](https://code.visualstudio.com/docs/sourcecontrol/overview#_merge-conflicts) with a small description
  - [x] Add the link to the section in the [table of contents](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#table-of-contents)
- [x] Check your changes in your remote repository to ensure the style is in line with the rest of the CONTRIBUTING.md

### Resources/Instructions
- Associated ER for this issue: https://github.com/hackforla/website/issues/4231
- [3.1.c Editing a submitted pull request](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31c-editing-a-submitted-pull-request)

**Comment by se7en-illa** [comment]
Availability for this week: Monday-Friday 12:00pm to 8:00pm EST
My estimated ETA for completing this issue: EOD 4/10/23

**Comment by jdingeman** [comment]
@se7en-illa - please remember to place your issue into the In Progress column when you self assign

**Comment by se7en-illa** [comment]
Pull request created 4/17/23
