### ISSUE TITLE
Change website project description to enable proper screen reader pronunciation of "Hack for LA"

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4354]
### Overview
As developers, we must ensure that the Hack for LA website is accessible to users of screen readers in order to achieve our goal of inclusivity.  In the project description of the website project, we will replace the text "hackforla.org" with "Hack for LA Site (hackforla.org)".  

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the website project markdown file `_projects/website.md`, then find the `description` variable.  
- [x] In the starting text of the `description` variable, replace the string
`The hackforla.org website` 
with
`The Hack for LA Site (hackforla.org)`
- [x] Do not modify any other instances of `hackforla.org`
- [x] Confirm the change in the browser on the [Hack for LA Current Projects Page](https://www.hackforla.org/projects) and on the [Website Project Page](https://www.hackforla.org/projects/website).  The location of the modified text is shown the screenshots in the Resources section below. 

### Resources/Instructions
 
<details><summary>Display of the Project Description on the Hack for LA Current Projects page (circled)</summary>

![image](https://github.com/hackforla/website/assets/5314153/b4523b2d-80b5-4f35-bbb7-c07599239cd4)

</details> 

<details><summary>Display of the Project Description on the Hack for LA Website Project page (circled)</summary>

![image](https://github.com/hackforla/website/assets/5314153/205fac2e-ee30-4722-9d74-c78a5a636ae6)

</details> 

- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [Hack for LA Website Project Markdown File](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe did you already test this with a screen reader and making that change fixes it, or it will have to be retested again after the change is made?

Also, it seems to be in two places.  See this image
![image](https://user-images.githubusercontent.com/37763229/229367228-ee594a16-0e12-4c9e-b2a9-ebe982184763.png)

A: Yes its been tested, and the description change will be on another issue.

**Comment by roslynwythe** [comment]
Tested this solution further and found it does not solve the problem. Needs further research.

**Comment by ldietz08** [comment]
Availability: W-F 4pm-8pm PST
ETA: Before Friday
