### ISSUE TITLE
GitHub Actions: Remove unmerged, closed PRs off the project board

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4357]
### Overview
Our Project Board has too many cards on it, causing it to slow down, and we want to optimize it. For this issue, you will need to create a GitHub Action that removes PRs that are unmerged AND closed from the project board.

### Action Items
- [x] Familiarize yourself with HackforLA's GitHub Actions [guide](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
  - [x] If you have not done so already, create a copy of your own project board to test on GitHub (See [Tip 6](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-6-creating-your-own-project-board))
  - [x] Create a [personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token) for the GitHub Action (See [Tip 7](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-7-using-personal-access-tokens-to-test-in-your-own-project-board))
- [x] This should be a new job under the ["PR Trigger" workflow](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/pull-request-trigger.yml)
  - [x] This job should trigger when a Pull Request is closed **without merge**
  - [x] Be careful not to remove Pull Requests that are still [open](https://github.com/hackforla/website/pulls) (neither merged nor closed)

### Checks
- [x] Test in your local environment that it works
- [x] If a pull request is on the project board in any column, and it gets closed without merging, remove it from the project board

### Resources/Instructions
- See associated ER for this issue: https://github.com/hackforla/website/issues/4232
- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
- [GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)
- [GitHub RESTAPI](https://docs.github.com/en/rest)
- Using [nektos/act](https://github.com/nektos/act) to test GitHub Actions locally
  - Plus a dev-written [guide](https://docs.google.com/document/d/1A2sj5KROv_AD3qTUrPO-YI730hKj2-o1FnE8GE1PUVY/edit)
- Additional dev-written [guide for testing with a Project Board](https://docs.google.com/document/d/1frtvr5twBa_3yRGCG0divhlOMW8dPJxT/edit)

**Comment by christinaor** [comment]
Availability: 8-10pm weekdays
ETA: 4/12-4/13

**Comment by ExperimentsInHonesty** [comment]
@christinaor I have moved this into the In progress column.  Please don't forget to do that when you self assign.  Have fun on this issue! [christinaor](https://github.com/christinaor)

**Comment by christinaor** [comment]
Progress: I wrote the job for deleting closed and unmerged PRs and created a personal token to temporarily replace the HFLA token. A feature branch was created to test whether the GitHub Action would fire off. I've also temporarily set the branch in the file to this feature branch.

Blockers: Currently having trouble with the branch getting rejected when pushing it to its branch in origin. I am getting the following error message: 
```
(refusing to allow a Personal Access Token to create or update workflow `.github/workflows/pull-request-trigger.yml` without `workflow` scope)
```
I double checked that the workflow scope was checked off when creating the token and can confirm it is. I'll try recreating the token, but will reach out in the Slack channel for help if that doesn't work.

Availability: 8-10pm weekdays
ETA: 4/12-4/13
