### ISSUE TITLE
img Tag Refactor: Toolkit page

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4366]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/toolkit.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="header-hero-image" src="/assets/images/toolkit/toolkit-hero.svg" alt="" />
```
to
```
<img class="header-hero-image" src="/assets/images/toolkit/toolkit-hero.svg" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/toolkit.html](https://github.com/hackforla/website/blob/gh-pages/pages/toolkit.html)
2. Toolkit page: https://www.hackforla.org/toolkit
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty I'm going to be writing multiple issues to refactor the `img` tags and will be using the format of this issue as a template to write the other issues. I would like to get your approval on this issue before I start writing some of the other ones or have the other dev leads help write the other ones.

**Comment by cng008** [comment]
Availability for this week: after 2pm PT
My estimated ETA for completing this issue: 4/3
