### ISSUE TITLE
ER: why the executive letter is different than all other card types

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4367]
### Emergent Requirement - Problem
We need a decision record and a note to that decision record in the design system

### Issue you discovered this emergent requirement in
- #4249

### Date discovered 
2023-04-02

### Did you have to do something temporarily
- [x] YES - answer the question in #4249   
> DRAFT NOTE: If you want this option, should it be squared off like the Letter from the Executive, or rounded like the Platform or Sustainability cards?  ROUND
- [ ] NO

### Who was involved
- @ExperimentsInHonesty, because I realized we didnt have the reason documented anywhere
- @jdingeman, because he wrote the issue with the question
- `@drubgrubby`  because he did the original development of the page, and the decision is either in an issue he worked on, or in a conversation we had but didn't document (it might have been before DRs)

### What happens if this is not addressed
I have to keep answering this question and possibly someone in the future won’t know why and will change it to a round edge card to be consistent with the rest.

### Resources
https://www.hackforla.org/about/#letter

### Recommended Action Items
- [ ] Make a new DR
- [ ] Review it with Bonnie

### Potential solutions [draft] 
Title: card with the Letter on about page has square edges
- The reason that the card has square edges is that we want it to look like a letter.  It's going to be formatted like a letter and include a signature
- For now, it's the only letter on the site.  However, in the future it's possible that there might be another card on the site that is a letter, but it's unlikely.

**Comment by jdingeman** [comment]
New issue here:
- https://github.com/hackforla/website/issues/4426
