### ISSUE TITLE
ER: various issues with issue templates

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4385]
### Emergent Requirement - Problem
There are several random changes we need to specific issue templates

### Issue you discovered this emergent requirement in
- #4307

### Date discovered 
2023-04-02

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

#### various issues

- minor rework on each issue that the template is used on
- waste of time when looking for the template you want

#### Remove two templates
- https://raw.githubusercontent.com/hackforla/website/gh-pages/.github/ISSUE_TEMPLATE/project-md-file--removing-unused--alt-hero--field.md
  - can we delete this?  I think this was a one time template.  If all the issues are closed, and it won't be used again, let's remove it.  Find the original issue and see next action, and make issue to remove if appropriate
    - Ans: It can be deleted. 
- https://raw.githubusercontent.com/hackforla/website/gh-pages/.github/ISSUE_TEMPLATE/alt-text-audit---design.md
  - This issue template can be removed, it's no longer in use
- https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/credits-file-template--edit-content-field-and-remove-type-field.md
  - This template can be removed too. It was a template for an epic and all the issues have been written already. 
- When these templates are removed, please update #4307 to not have these in its list so that they don't make the issues

#### Other
- https://raw.githubusercontent.com/hackforla/website/gh-pages/.github/ISSUE_TEMPLATE/suggest-an-external-resource.md
  - this issue has weird codes in it.  Am only I seeing this?  If you can replicate, please make an issue to clean this up  
     ![image](https://user-images.githubusercontent.com/37763229/229416678-8b2091f4-eb12-4084-bdbd-f9e2d1bd4a62.png)

**Comment by jdingeman** [comment]
@ExperimentsInHonesty created the following pull requests as last chance before deletion and for traceability:
- #4462 
- #4463 
- #4464

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - old templates have been deleted and I corrected the issue with Suggest an External Resource template. I think there must have been some weird encoding issue when the dev made the template years ago and put it into github.
