### ISSUE TITLE
ER from TLDL: Think about converting Wins Google Form to a custom form

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4387]
TLDL stands for Task List Dev Leads.

### Dependency
- [ ] Issues written as a result of ER #4390 will help PM(s) determine whether we convert Wins Google Form to a custom form

### Emergent Requirement - Problem
**Issue Description**
Think about converting the Google form to a custom form on the site that we code, but then we would need a backend or way to send data to the Apps Script without revealing secrets. Also, is this already implemented? See: 
- https://www.hackforla.org/share-your-wins/ 
- #2246
- #2021

Note: This was partially from the Wins form research conducted by UX Researcher Vivian

### Who was involved
- @JessicaLucindaCheng
- `@SAUMILDHANKAR`
- @ExperimentsInHonesty 

### What happens if this is not addressed
We use the existing Google Form for submitting wins.

### Resources
- https://www.hackforla.org/share-your-wins/
- #2246
- #2021 

### Recommended Action Items
- [ ] Discuss with Website Team devs and PMs
- [ ] Make a decision on whether we want to convert the Google Form to a custom form on the site that we code
- [ ] Search and check 
  - [ ] If an open issue exists that addresses this ER
  - [ ] If a closed issue exists that has already addressed this ER
- [ ] If an open issue doesn't exist and this ER wasn't already fixed by a closed issue, make a new issue 

### Potential solutions [draft]

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng See what my thoughts are re the various ways this issue could go.

1. embedding the Google form, so it appears on the page (sure we could do that).  I think we already have tried the code, there may have been a reason why we stopped. 

2. Making it an actual form on Jekyll. This will be a feature of the VRMS site in the future (when people become inactive it will ask them if they got jobs, etc.) and the current form works fine.  

3. If there was a way to populate a form with the projects automatically, from our repo, so we didn't have to keep updating it, that would be worth looking into.

**Comment by JessicaLucindaCheng** [comment]
Passing this to dev leads because Issues written as a result of ER https://github.com/hackforla/website/issues/4390 will help PM(s) determine whether we convert Wins Google Form to a custom form

**Comment by roslynwythe** [comment]
@JessicaLucindaCheng I added this issue as a dependency on #4405

**Comment by roslynwythe** [comment]
- As a result of #4588 it was determined that the WINS custom form is not secure and so related issues including this one will be closed as not planned
