### ISSUE TITLE
ER: some projects are not filtered correctly by Languages/Technologies

### ISSUE THREAD

**Issue by nnr-nnr** [hackforla/website#4389]
### Emergent Requirement - Problem
Some projects are not displayed when the Languages/Technologies filter is used on the [Projects](https://www.hackforla.org/projects) page (and potentially other pages where this projects filtering feature is used).

### Issue you discovered this emergent requirement in
- #4120 

### Date discovered 
3/26/23

### Did you have to do something temporarily
- [ ] NO - does not affect the issue

### Who was involved
@t-will-gillis , @nnr-nnr 

### What happens if this is not addressed
Some projects will not show up when they should when the Languages/Technologies filter is used. For example, if someone is searching for projects in the Program Area "Diversity / Equity / Inclusion" and that use CSS, the [Write for All](https://www.hackforla.org/projects/writeforall) project will not be displayed even though it meets these two criteria.

### Resources
N/A

### Recommended Action Items
- [ ] Make a new issue
- [ ] Figure out which projects this  bug affects (so far, it appears to affect at least the [Write for All](https://www.hackforla.org/projects/writeforall) and [Heart](https://www.hackforla.org/projects/heart) projects)
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
Some possible places where this bug may be occuring:
- The collection of projects: see .md files in the  [_projects](https://github.com/hackforla/website/tree/gh-pages/_projects) folder without the `technologies` attribute do not allow filtering by Languages/Technology.
- From Will: 
> In the [/current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js) file line 27 the filter code is else if (filterName == 'technologies' ) use the filterTitle = 'languages / technologies' so if the card doesn't have the technologies  attribute it is ignored. This might be an easy fix but it could also turn out to be a lot of refactoring.

**Comment by t-will-gillis** [comment]
- Link to the new issue: #4587
