### ISSUE TITLE
Add manual trigger to the "Update VRMS data" workflow

### ISSUE THREAD

**Issue by MattPereira** [hackforla/website#4392]
### Overview
The `Update VRMS data` workflow is currently being triggered by a cron job that runs each day at 10:00AM UTC. For this issue, we will add an additional trigger so that we can update the meeting data for the hfla website on demand. 

### Action Items
- [x] Add the `workflow_dispatch` trigger to the `Update VRMS data` workflow

### Resources/Instructions
- [vrms-data.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/vrms-data.yml)
- [HFLA GHA Wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
- [GHA Docs on workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch)
- [GHA Docs on using multiple triggers](https://docs.github.com/en/github-ae@latest/actions/using-workflows/triggering-a-workflow#using-multiple-events)

**Comment by ExperimentsInHonesty** [comment]
@MattPereira Can't we have both?  A workflow that does it every day and one that runs on demand should we need it.  Cause changing it to only run on demand means someone would have to know to push the button each time a project lead makes an update to their meeting at vrms.

**Comment by MattPereira** [comment]
> Can't we have both? A workflow that does it every day and one that runs on demand should we need it.

Apologies for the misunderstanding. I do believe we can have multiple triggers for a single workflow. I will amend the issue to reflect this request

**Comment by LOSjr4** [comment]
Availability: M,T,Th 9AM-1PM
ETA: Tomorrow, 4/12, 2PM

**Comment by LOSjr4** [comment]
I believe I did the task, but I'm uncertain how to test it out. @MattPereira, do you have time today after 3:40PM to share a screen and walk me through testing? Otherwise I'll ask for help testing at tomorrows office hour.

**Comment by MattPereira** [comment]
Hey @LOSjr4 

Sorry no time for screen share today but here's a quick guide

1. Push your branch from local up to the fork
1. Go to settings on your fork of hfla/website and change your default branch to the newly pushed up branch

<details><summary>See screenshot</summary>

![image](https://user-images.githubusercontent.com/73561520/231593505-0d0dc6de-dd2b-4b1d-a6c2-4d7674aa2b9c.png)

</details>


3. Then go to Actions tab of your fork and find the `Update VRMS data` workflow from the list on the left

<details><summary>See screenshot</summary>

![image](https://user-images.githubusercontent.com/73561520/231593597-6c610cf0-4d5c-4216-aebe-560f9634ea09.png)

</details>

The action is going to fail on your fork because one of the steps uses a token, but I'm reasonably confident that it will work once PR is merged to main branch

Someone else on the team might know how to bypass the token for testing

**Comment by MattPereira** [comment]
Hey @LOSjr4 

Sorry no time for screen share today but here's a quick guide

1. Push your branch from local up to the fork
1. Go to settings on your fork of hfla/website and change your default branch to the newly pushed up branch

<details><summary>See screenshot</summary>

![image](https://user-images.githubusercontent.com/73561520/231593505-0d0dc6de-dd2b-4b1d-a6c2-4d7674aa2b9c.png)

</details>


3. Then go to Actions tab of your fork and find the `Update VRMS data` workflow

<details><summary>See screenshot</summary>

![image](https://user-images.githubusercontent.com/73561520/231593597-6c610cf0-4d5c-4216-aebe-560f9634ea09.png)

</details>

The action is going to fail on your fork because one of the steps uses a token, but I'm reasonably confident that it will work once PR is merged to main branch

Someone else on the team might know how to bypass the token for testing
