### ISSUE TITLE
img Tag Refactor: Getting Started page - `step-img-icon-git join-2.png`

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4394]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon-git" src="assets/images/getting-started/join-2.png" alt="" />
```
to
```
<img class="step-img-icon-git" src="assets/images/getting-started/join-2.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

**Comment by garrettallen0** [comment]
Availability: Saturday 4/15, Sunday 4/16
ETA: Thursday 4/20

**Comment by roslynwythe** [comment]
Hi @garrettallen0 I've moved this issue to the "In Progress" column since it looks like you will be working on it shortly.  In the future, try to remember to do move the issue to "In Progress" as soon as you self-assign it, just to keep our Project Board organized.  Thanks!!

**Comment by garrettallen0** [comment]
Hi @roslynwythe thank you! I took the issue during the meeting Sunday and I thought Justin said he was changing it to "In Progress" but I must have misunderstood him. Thank you, and will do myself in the future!
