### ISSUE TITLE
img Tag Refactor: Getting Started page - `step-img-icon shield.png`

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4399]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon" src="assets/images/getting-started/shield.png" alt="" />
```
to
```
<img class="step-img-icon" src="assets/images/getting-started/shield.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

**Comment by nung22** [comment]
Availability for this week: Weekdays 5:30 - 8:30 PM PST
My estimated ETA for completing this issue: Thursday by 9:00 PM PST.

**Comment by roslynwythe** [comment]
Hi @nung22, please leave a comment outlining your progress and including your availability and ETA.  If you no longer plan to work on this issue, please let us know.  Thank you.

**Comment by ExperimentsInHonesty** [comment]
@nung22 I am removing you from this issue since we have not heard from you.

**Comment by nung22** [comment]
Thank you for the update @ExperimentsInHonesty. My apologies @roslynwythe, I missed your comment last week. I  have not been free enough to work on the issue recently. Will make sure I have enough time to allocate to an issue before picking one up next time.

**Comment by Dprosser4** [comment]
Availability for this week: Weekdays 9:00am - 8:30 PM PST
My estimated ETA for completing this issue: Today
