### ISSUE TITLE
Enhance Google Apps Script to validate URLs and report failures in GitHub review issue

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4405]
### Dependency

- [x] #4134
- [x] #4387

### Overview

URL validation in the wins Google form is inadequate, so in the Google Apps Script behind the wins-form (response) Sheet, we will test URLs for valid format.  If a URL is found to be invalid, a message will be displayed within the GItHub review issue, and the URL will not be included in the _wins-data.json feed.   

#### Setup

- [ ] Obtain access to the wins form, the wins-form (response) Sheet, the Secret files and the Wins Admin Guide.  Make a copy of the wins form, wins-form (response) Sheet, and Secret files, placing the copies on your local Google Drive.  All subsequent modifications should be made on your local Google Drive copies.  
- [ ] Read the Wins Admin Guide to understand the flow of data between the wins form, the wins-form (response) Sheet, the GitHub review issue and the wins data feed.  
- [ ] read the wiki "Hfla Google Apps Script Development/Review Process" and follow instructions to setup your local environment.  Follow instructions for connecting your wins-form with the wins-form (response) Sheet, and configuring triggers in the wins-form (response) Sheet.  

#### Code Changes

- [ ] In Code.gs behind gh-requests, modify the function `createIssue()` so that it accepts a string input parameter `message` that will be displayed in the body of the new GitHub review issue.  
- [ ] In Code.gs behind wins-form (response) Sheet, prior to `invoking ghrequests.createIssue()`, test the GitHub and LinkedIn URLs for valid format.  If the test fails, generate a descriptive message and supply the message as an input parameter to `ghrequests.createIssue()`. 

### Resources/Instructions
- This issue was created as a result of ER #4185
- [Wins Admin Guide](https://docs.google.com/document/d/1j1JTX5XzotgVCVZ91ImvenedPN5-IVjdSKDukq1B9iE/edit?usp=share_link)
- Hfla Google Apps Script Development/Review Process

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe Friendly reminder to add a size label to this issue

**Comment by roslynwythe** [comment]
- We are taking a different approach - see #4671
