### ISSUE TITLE
img Tag Refactor: Getting Started page - `step-img-icon schedule.png`

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4415]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/getting-started.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-icon" src="assets/images/getting-started/schedule.png" alt="" />
```
to
```
<img class="step-img-icon" src="assets/images/getting-started/schedule.png" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. [pages/getting-started.html](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
2. Getting Started page: https://www.hackforla.org/getting-started
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

**Comment by oliviazhai** [comment]
ETA:  June 11th end of the day
Availability: June 9th 1:00 pm - 5: 00pm, June 10th 1:00 pm - 5:00pm

**Comment by SeyiAkinwale** [comment]
Availability: Weekday mornings, 2 hours per day
estimated ETA: June 30th

**Comment by SeyiAkinwale** [comment]
1) Progress: Issue resolved -- Removed closing "/" for consistency. Verified page looks the same across devices using dev tools.
2) Blocker of general understanding of tools resolved
3) Availability: weekdays: 1 hour around 8a, 1 hour around 6p
4) ETA - Done

**Comment by ExperimentsInHonesty** [comment]
@SeyiAkinwale Your last update says you are done.  Where is the PR?

**Comment by oliviazhai** [comment]
Hi, Sorry for the delay! I just opened the pull request for this issue

**Comment by roslynwythe** [comment]
Hi @oliviazhai this issue was assigned to @SeyiAkinwale so I'm unclear about why you opened the PR.  Should the be assigned to you?

**Comment by oliviazhai** [comment]
> Hi @oliviazhai this issue was assigned to @SeyiAkinwale so I'm unclear about why you opened the PR. Should the be assigned to you?

Hi @roslynwythe, this issue i was initially assigned to myself. and Seyi said he is done with this issue but didn't submit the PR, so I just finished and submitted the PR, please let me know what should I do at this point

**Comment by t-will-gillis** [comment]
@SeyiAkinwale this is `2 weeks inactive` from several weeks ago. https://github.com/hackforla/website/issues/4415#issuecomment-1608587496 
Unassigning and placing back in 'Prioritized Backlog'

**Comment by yujioshiro** [comment]
Availability for this week: 7/22 6pm-7pm PDT, 7/23 12pm-3pm PDT
My estimated ETA for completing this issue: 7/21 EOD
