### ISSUE TITLE
hack for la_lucky parking webpage team leader updates

### ISSUE THREAD

**Issue by breeze-094** [hackforla/website#442]
### Overview
hack for la_lucky parking webpage team leader updates

### Action Items
for [lucky parking web page](https://www.hackforla.org/projects/lucky-parking.html), update below items:
- Partner: Seeking
- Tools: Google Colab, AWS, React-JS
- Languages: Python, JavaScript, PL/pgSQL
- Front End Lead: David Kim
- Back End Lead: Elly Kyles

**Comment by breeze-094** [comment]
@harishlingam  Could you help update the website please since I cannot assign anybody here

**Comment by ruben1s** [comment]
Are the front end and back end leads replacing the old ones or are they being added on? Also, do you have the web addresses to their respective githubs and slack accts?

**Comment by alexandrastubbs** [comment]
This issue ended up getting lost and we'd like to give your page an update. Can you provide updated leadership information and identify any other information on the page that you need to be updated?

https://www.hackforla.org/projects/lucky-parking

**Comment by gregpawin** [comment]
Partner: Department of Neighborhood Empowerment / Department of Transportation
Tools: Jupyter Notebooks, Google Colab, AWS, React-JS
Languages: Python, JavaScript, SQL

This includes all of the current team so previous info can be discarded:
 
Product Owner / Data Science Lead: Greg Pawin
https://app.slack.com/team/UUEQF3AJG
gregpawin
Frontend Lead: Matthew Ginther
https://app.slack.com/team/U013GNM93U1
mg78856
Frontend: David Kim
https://app.slack.com/team/U3MNUEQJ3
hyomiTheTech
Frontend: Harris Nguyen
https://app.slack.com/team/U014UMW7E4U
harris-nguyen
Frontend: Sam Guan
https://app.slack.com/team/U0173AHJ004
samreality4
Backend Lead: Sophia Alice
https://app.slack.com/team/UN7V7L934
salice
Data Scientist / Backend: Andy Vu Hoang
https://app.slack.com/team/U013BF8HTNF
andy-vh
Data Scientist: Kazuki Takehashi
https://app.slack.com/team/U016E2G0C3H
Kazuki0131

**Comment by alexandrastubbs** [comment]
@gregpawin can you edit the above comment and add in the GitHub IDs for each individual?

**Comment by gregpawin** [comment]
Added github IDs
