### ISSUE TITLE
Remove .sdg-img-item class from _project-page.scss

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4422]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The `.sdg-img-item` class in `_sass/components/_project-page.scss` is not used anywhere in the codebase. We need to remove this so that we don't have extraneous SCSS class that aren't being used to style any HTML.

### Action Items
- [x] Navigate to [ _sass/components/_project-page.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-page.scss)
- [x] Delete the lines 290 - 296

```
.sdg-img-item {
  text-align: center;
  padding: 30px 60px 10px;
  border-radius: 10px 10px 0px 0px;
  background: #02548B;
}
```

### Resources/Instructions
- ER associated with this issue: https://github.com/hackforla/website/issues/4343
- [ _sass/components/_project-page.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-page.scss)
- [How to search across files in VS Code](https://code.visualstudio.com/docs/editor/codebasics#:~:text=VS%20Code%20allows%20you%20to%20quickly%20search%20over%20all%20files,each%20file%20and%20its%20location.)

**Comment by pranit-yawalkar** [comment]
Hey, I would like to take this.

**Comment by ExperimentsInHonesty** [comment]
@pranit-yawalkar I don't see you in our team roster.  You are welcome to take on any of the [good first issues that are on our project board in the prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22good+first+issue%22#column-7198257) as long as you have met the prerequisites.  If you do not meet the perequisites and you do a PR against an issue, it will not be accepted.  Thanks for your understanding. 

1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our [Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

**Comment by kurikurichan** [comment]
Availability for this week: A bit of time today (Friday), tomorrow morning (Saturday), a bit Sunday afternoon, also Monday/Tues next week
My estimated ETA for completing this issue: If I actually focus on reading the instructions, the actual issue itself is very simple so I could probably finish it today

**Comment by kurikurichan** [comment]
Provide Update
1. Progress
  - Working on it now
2. Blockers
  - My blocker was honestly just reading through all the instructions lol. I think I was reading a lot of the contributing.md guide and then kind of moved on to an issue based on that, instead of going back to the pre-work checklist. I get it now, though
3. Availability - A bit of time today (Friday), tomorrow morning (Saturday), a bit Sunday afternoon, also Monday/Tues next week
4. ETA - Today or at latest by the end of this weekend
