### ISSUE TITLE
Find all the places that the  "good second issue" labels is used

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4423]
### Overview
Find all the places that the "good second issue" labels appears so that we can change all references to point to "good first issue" labels in a future issue and when we do make the change, it changes in all our documentation and code as well.

### Details
We are going to stop using good second issues and just have everyone do two good first issues

### Action Items
- [x] Search the repository for any reference to "good second issue"
  - [x] This includes
    - [x] [wikis](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+%22good+second%22&type=wikis)
    - [x] [code](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+%22Good+second%22&type=code) via the web | Also search via VS code (see resources for details)
    - [x] [PRs](https://github.com/hackforla/website/pulls?q=is%3Apr+label%3A%22Complexity%3A+Good+second+issue%22+)
    - [x] [Project Board, `Onboarding infos/links` column](https://github.com/hackforla/website/projects/7#column-11381714)
- [x] Make a list of all references to "good second issue" or "2nd" and their locations in this [spreadsheet](https://docs.google.com/spreadsheets/d/1xoCOAxoUXo2kVNeaQAwUgfqlNU0RiLGcHrY6sAGqhfc/edit#gid=0)
- [x] When you have finished, place this issue into the Questions / In Review column with the "ready for dev lead" and "Status: Help Wanted" label
- [ ] When this issue is complete, release the dependency on 
   - [x] #4431 
   - [ ] #4432 

#### For Merge Team/Tech Lead
- [ ] See #4432 and review the drafts for all the implementation issues to confirm that they cover everything identified in this issue

### Resources/Instructions
- [How to Search in VS Code](https://code.visualstudio.com/docs/editor/codebasics#:~:text=VS%20Code%20allows%20you%20to%20quickly%20search%20over%20all%20files,each%20file%20and%20its%20location.)
- Hint: You can find exact phrasing in the GitHub repository search by wrapping the search term in quotation marks (")

#### Related issues
- ER associated with this issue: https://github.com/hackforla/website/issues/4371
- This issue is part of an epic https://github.com/hackforla/website/issues/4432

**Comment by jdingeman** [comment]
@ExperimentsInHonesty - my thought is that the dev can make a small list since we are not editing the wiki, and when the wiki is up and running on MkDocs then we can make actual issues to change the references to good second issues in the wiki via PRs. Thoughts?

**Comment by ExperimentsInHonesty** [comment]
@jdingeman 
- See this issue comment for context https://github.com/hackforla/website/issues/4432#issuecomment-1499448531

You said

> @ExperimentsInHonesty - my thought is that the dev can make a small list since we are not editing the wiki, and when the wiki is up and running on MkDocs then we can make actual issues to change the references to good second issues in the wiki via PRs. Thoughts?

- I think that is something you can address in the Update wiki issue that you will make as part of #4432

**Comment by vincentdang** [comment]
i. Availability: This upcoming week M-F weeknights.
ii. ETA: perhaps by the end of the week or the next week

**Comment by vincentdang** [comment]
@jdingeman 
Okay so my strategy to searching on GitHub is to type in org:hackforla "good second issue" 
or org:hackforla "good 2nd issue" in the search bar.  

https://github.com/search?q=org%3Ahackforla+%22good+second+issue%22&type=Issues

The "good 2nd issue" appears manageable with 7 links.
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/1876652/234173494-3cecc9b5-d514-4ec2-98cf-8430f16feb53.png">

The "good second issue" is bit much.

I'm able to enter in the wiki and code links but this yields 300+ issue links.  I would rather avoid
rote labor if there is an easier way.  


![image](https://user-images.githubusercontent.com/1876652/234173208-3700b2b1-47ff-4690-b402-8b5b897561bf.png)

**Comment by vincentdang** [comment]
Update: I have more or less finished searching for "good second/2nd issue" on GitHub, on the web, and on VS code so far it seems.

**Comment by vincentdang** [comment]
Update: I believe I found them all or mostly all of them.  I just need to relabel this and place it into the Question/In Review column.

**Comment by ExperimentsInHonesty** [comment]
@vincentdang In the location column, the links for the items designated as Web need cleaning up or explanation.

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge Please review this spreadsheet and identify if there are items that are not relevant that we could hide.

**Comment by vincentdang** [comment]
> @vincentdang In the location column, the links for the items designated as Web need cleaning up or explanation.

Hi I have provided explanations in the Relevant column next to the "web" items in the spreadsheet.
As they evaluate, they could delete the explanations as they see fit.

**Comment by ExperimentsInHonesty** [comment]
@vincentdang please update the sheet to make the following change

### Chang the links to code, to go to the main, instead of the commit in rows 56-66
Example:
Row 56 currently says 
> https://github.com/hackforla/website-wiki/blob/main/docs/About-the-Website-Development-Team.md

But it used to say 
>https://github.com/hackforla/website-wiki/blob/24d6cd766ef1ca57c66cf458913e49796a5f8293/docs/About-the-Website-Development-Team.md

I was able to change the link by going to the url you provide and clicking on main, and then copying the url. 


### Add the name of the issue on rows that just have url
You added the names of the issues other places, just not on these rows.

Example:
Row 52 shows
> https://github.com/hackforla/internship/issues/238

and it should say

> IS22 Intern Standup

with a note in the notes column saying its from the hackforla/internship repo

After you have made these changes, please reach out to the @hackforla/website-merge  team to see if they have any other feedback for you.

**Comment by vincentdang** [comment]
hey i will update this tomorrow

**Comment by vincentdang** [comment]
@ExperimentsInHonesty rows 61-66 do not have a main branch so I'm not sure how to deal with them. 56-60 I was able to change.  for adding the name of the issues that have just the url, I'm currently trying to figure out how to get the hyperlink version of it and have not been able to figure it out just yet.

**Comment by vincentdang** [comment]
Progress: rows 61-66 updated.  
Blockers: 56-60 do not have a main branch. not sure what to do.  not sure how to convert a url to a hyperlink for certain rows.
Availability: Weekend during the day or night.
ETA: possibly < a week.

**Comment by vincentdang** [comment]
> @vincentdang please update the sheet to make the following change
> 
> ### Chang the links to code, to go to the main, instead of the commit in rows 56-66
> Example: Row 56 currently says
> 
> > https://github.com/hackforla/website-wiki/blob/main/docs/About-the-Website-Development-Team.md
> 
> But it used to say
> 
> > https://github.com/hackforla/website-wiki/blob/24d6cd766ef1ca57c66cf458913e49796a5f8293/docs/About-the-Website-Development-Team.md
> 
> I was able to change the link by going to the url you provide and clicking on main, and then copying the url.
> 
> ### Add the name of the issue on rows that just have url
> You added the names of the issues other places, just not on these rows.
> 
> Example: Row 52 shows
> 
> > [hackforla/internship#238](https://github.com/hackforla/internship/issues/238)
> 
> and it should say
> 
> > IS22 Intern Standup
> 
> with a note in the notes column saying its from the hackforla/internship repo
> 
> After you have made these changes, please reach out to the @hackforla/website-merge team to see if they have any other feedback for you.


************************************************
************************************************
Update: I have finished the edits on the spreadsheet that Bonnie has requested that I do.
I am now reaching out to the merge team for feedback.
@hackforla/website-merge
@ExperimentsInHonesty 
@jdingeman

**Comment by roslynwythe** [comment]
Hi @vincentdang it looks like Bonnie was asking for URLs such as found in row 52 column A, to contain link text with the name of the issue.  Is that a correct interpretation?  If so, would that be possible?

**Comment by vincentdang** [comment]
> Hi @vincentdang it looks like Bonnie was asking for URLs such as found in row 52 column A, to contain link text with the name of the issue. Is that a correct interpretation? If so, would that be possible?

hi I think get what you mean.  it's been a while for this issue but let me see if i can get it to look that way.

**Comment by ExperimentsInHonesty** [comment]
I am marking this spreadsheet and issue as complete.  Thank you @vincentdang
