### ISSUE TITLE
DR: Write a Decision Record for the styling of the executive letter

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4426]
### Overview
The [Letter from the Executive](https://www.hackforla.org/about/#letter) currently exists on a page card that has squared corners. Most of the other cards across the website have rounded corners. We need a Decision Record to document this choice in design.

<details>
<summary>Corners of the Letter from the Executive</summary>

![image](https://user-images.githubusercontent.com/88953806/230251795-2976303d-ce22-4d0e-85a5-85ddb9e75bf9.png)

</details>

<details>
<summary>Corners of other cards</summary>

![image](https://user-images.githubusercontent.com/88953806/230251906-3e98e9b8-9be1-4dae-ac47-61b67486c465.png)

</details>

### Action Items
- [x] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)

### Action Items to be completed when new wiki is ready
- [x] Create a new [Decision Record for Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted) named "DR: Card with the Letter on About page has square edges"
- [x] Document the reasoning behind making it so the Letter has squared edges instead of rounded edges
  - [x] The reasoning is that we want the Letter to look like a real letter - this includes its formatting and that it will have a signature at the bottom. 
  - [x] It's the only card on the site with square edges, but there is a possibility that the card style may be used again.
- [x] Go back to the [Decision Records for Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted) page and add a link to this new article
- [x] Go back to the [Decision Records](https://github.com/hackforla/website/wiki/Decision-Records) homepage and add a link to the article preceded by a ✅
- [ ] When you have completed this, review your work with Bonnie

### Resources/Instructions
- ER associated with this issue: https://github.com/hackforla/website/issues/4367

##### Decision Records Template
````
This is a record in the [Decision Records on Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted).

#### Issue 
#### Problem Statement
#### Potential Solution
#### Feasibility Determination
`````

**Comment by jdingeman** [comment]
Just remembered that this may need to wait until the website-wiki is up and running for devs to contribute to.

**Comment by ExperimentsInHonesty** [comment]
@jdingeman, @JessicaLucindaCheng  has some text to be added to any issue that has a wiki component.  Can you get her to add it to a place we can all copy it from (perhaps we put it on a card in the new ER column for easy copying).

**Comment by JessicaLucindaCheng** [comment]
@jdingeman I added info about the wiki as the first Action Item.

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 

> @jdingeman, @JessicaLucindaCheng has some text to be added to any issue that has a wiki component. Can you get her to add it to a place we can all copy it from (perhaps we put it on a card in the new ER column for easy copying).

In the ER column, I added a card with an Action Item that can be copied into issues requiring editing or adding content to the wiki: https://github.com/hackforla/website/projects/7#card-88800266

**Comment by ldietz08** [comment]
Availability: 6/2-6/4 11am-3pm 
ETA: 6/3

**Comment by ldietz08** [comment]
This is a record in the [Decision Records on Solutions Adopted](Decision-Records-on-Solutions-Adopted).

#### Issue 
* #4426
#### Problem Statement

Ensure that the corners of the [Letter from the Executive](https://www.hackforla.org/about/#letter) page remain square to retain the visual characteristics of a traditional letter.

<details>
<summary>Corners of the Letter from the Executive</summary>

![image](https://user-images.githubusercontent.com/88953806/230251795-2976303d-ce22-4d0e-85a5-85ddb9e75bf9.png)

</details>

<details>
<summary>Corners of other cards</summary>

![image](https://user-images.githubusercontent.com/88953806/230251906-3e98e9b8-9be1-4dae-ac47-61b67486c465.png)

</details>

#### Potential Solution

We want to maintain the square corners on the [Letter from the Executive](https://www.hackforla.org/about/#letter) page so it resembles a letter with proper formatting and a signature. The square corners aligns with the formal and structured design of a traditional letter. 
 
ER associated with this issue: https://github.com/hackforla/website/issues/4367

**Comment by ExperimentsInHonesty** [comment]
@ldietz08 Good work on the Decision Record.  Its ready to add to our store of changes we will be making to the wiki.  Please see the action item that is unchecked above

> - [x] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)

And do the instructions in that wiki page it references to add this DR to the list of items we will add to the wiki once the new wiki is totally live.

**Comment by ldietz08** [comment]
I added a link to my comment under the `Content to be Added/Edited in the New website-wiki Repo` section.

**Comment by roslynwythe** [comment]
Thank you @ldietz08 for adding that link to your comment, so that it will be incorporated into the wiki once it is ready.
