### ISSUE TITLE
Replace all "good second issue" labels with "good first issue" label on open PRs and Issues

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4431]
### Dependency
- [x] #4423
- [ ] #4432 is ready for implementation

### Overview
Dev leads determined that having to separate "good first issues" and "good second issues" does not make much sense since the corresponding issues are essentially the same complexity. We need to replace all the "good second issue" labels with "good first issue" labels so that dev leads do not need to juggle making enough of each issue. 

### Details
All the Closed PRs and Issues have already been changed

### Action Items
- [ ] Go to the issues with the [good second issue label](https://github.com/hackforla/website/issues?q=is%3Aopen+is%3Aissue+label%3A%22Complexity%3A+Good+second+issue%22)
- [ ] If an issue has an assignee, post the following message on their issue
   ```
   Hi, we are about to change the label on your issue `Complexity: Good second issue` to `good first issue` to relect the update to our issue ladder of all members will work on two good first issues instead of the dev team making seperate issues for first and second (even though they were essentially the same).  
   
   You might be asking youself, why do you need to do two good first issues, instead of just one?!.  The first two issues is where we catch if anyone has problems with branching appropriately on our project.  So we intentionly make them very very small and perscriptive so that we can focus on making sure you have the branching down before we move you on to the bigger issues that get less and less perscriptive as you go up the ladder.
   
   When you sucessfully finish with this issue, you can go on to a Small issue just as you would have before.
   ```
- [ ] Go back to the issue tab and your search, 
   - [ ] Check the box at the top of the list to select the entire list
      - [ ] Click on "Label" 
         - [ ] Deselect "good second issue"
         - [ ] Select "good first issue"
         - [ ] Click off the drop down, to make it take effect.

### Resources/Instructions
- This issue is part of an epic https://github.com/hackforla/website/issues/4432

**Comment by ExperimentsInHonesty** [comment]
@jdingeman

- See this issue comment for context https://github.com/hackforla/website/issues/4432#issuecomment-1499448531

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty I searched and could not find any open Issues or PRs with the label "good second issue", so closing this issue as not planned.
