### ISSUE TITLE
Create Donation gif Component and Integrate into Donate Page Include

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4439]
### Dependency
- [x] #3983 

### Overview
As developers, we need to componentize the animated Donate gif and associated text, so that there is a consistent appearance across the site and to promote code reuse.  

### Details

- Currently the donation animated gif is part of larger Donate include file `_includes/donate-card.html` 
- We need to create a smaller reusable component ("include file") containing the Donation graphic and text, with page-independent styles in a separate SCSS file,  and then incorporate the new component into the Donate page include file so that the current appearance of the Donate page is maintained in mobile and desktop views.  

### Action Items
- [x] Create the new component file `_includes/donation/donate-gif-text.html` and open the Donate include file `_includes/donate-card.html`.  In this issue, elements will be moved from `_includes/donate-card.html`  to `_includes/donation/donate-gif-text.html`.  Those elements are depicted in the "Component elements" screenshots below, but before editing, note the following items.  
- [x] The elements depicted do not include the rounded edge "card" which is rendered from
 ` <div class="page-card card-primary page-card-lg page-card--join page-card--large-icon-container donation-grid">`
  Because it contains "card" styles, the above div is page-specific and so it must be retained in its current file.  It is necessary to refactor the html. One approach might be to remove the `donation-grid` class from this div, then create a new `<div class="donation-grid">` in the new component file, to wrap the container elements. 
- [x] The `<h3>` heading with text "Make a Donation to Hack for LA" is not depicted in the screenshot, because the styling of the header is page-specific, and so it will be retained in its current file.  Refactoring will be necessary.  One approach might be to move the `<h3>` so that it becomes the immediate first child of the card div.   
- [x] Move the remaining depicted elements from `_includes/donate-card.html` to `_includes/donation/donate-gif-text.html`, then in `_includes/donate-card.html`, in place of the moved elements, reference the new component file using the liquid `{% include <filename> %}` tag.  Note that `<filename>` is relative to the `_includes` folder. 
- [x] The existing SCSS file for the Donate page is `_sass/components/_donate.scss`.  Styles may have to be added to this file to style the `<h3>` since its location has changed.  The SCSS for styling the new component will be `_sass/components/_donate-components.scss`.   If this file does not exist, create it and add an import statement in `_sass/main.scss`.   Move classes specific to the component from the existing SCSS file  to the new SCSS file.   Styles in the new SCSS file should be page-independent and unique to the component, so that the component can be included in other pages.  Update SCSS classes and HTML as needed so that appearance of the modified Donate page matches the appearance shown in the "Final Appearance" screenshots.  Note that the position of the sentence "100% of donated proceeds..." moves below the animated gif in mobile view.  

#### For Merge Team 
- [ ] Check this issue off as merged in epic #4492.  If the merged PR closes the last of the issues under "Create New Components", then release dependencies on all the issues listed under "Clean Up". 

### Screenshots
  <details>
        <summary>component elements (desktop)</summary>

![image](https://user-images.githubusercontent.com/5314153/230876468-c12a99fa-6de3-418a-ba62-8fe3afa0a5f1.png)
</details>
  <details>
        <summary>component elements (mobile)</summary>

 ![image](https://user-images.githubusercontent.com/5314153/230875239-96eeb48c-7699-4e79-bc03-b20f153b4824.png)
  </details>
  <details>
        <summary>Final appearance, heading outside the component, together with the component (desktop)</summary>
  
![image](https://user-images.githubusercontent.com/5314153/230872506-92f04970-eebb-493a-99ea-17fa4c2ea752.png)   
 
</details>
<details>
        <summary>Final appearance, heading outside the component, together with the component (mobile)</summary>
  
![image](https://user-images.githubusercontent.com/5314153/230862773-087dc2cd-4bb9-4e8d-a3b9-b8669886ad8d.png)

</details>

### Resources/Instructions
- [Donate Card Include (html)](https://github.com/hackforla/website/blob/gh-pages/_includes/donate-card.html)
- This issue was created as a part of the Epic #4492

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe Thanks for writing this issue. I like that you put suggestions for how to approach implementing the issue for the developer, such in the second action item. Please make the following changes:
- [x] Rewrite the Overview to be in a modified user format of `We need to do X for Y reason` and you can move what you currently have into a Details section.
- [x] In the second action item, where it says, `<div class="donation grid">`, is it supposed to be 2 classes  (`donation` and `grid`) or did you mean `donation-grid` so that the existing `donation-grid` class would be used?

**Comment by roslynwythe** [comment]
Thank you @JessicaLucindaCheng you have an excellent eye and issues are clearly improved as a result of your review.  Regarding your second point, that was a typo.  Indeed I am suggesting that the existing `donation-grid` class can be used and I fixed that in the Action Item.  Please advise, is the issue "Ready for Prioritization"?

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe LGTM! Thanks for making the changes. I made a slight wording change to the Overview but otherwise good job. I think it's "Ready for Prioritization", so go ahead and:
- [x] Unassign yourself from this issue
- [x] Hide any comments the developer working on this issue doesn't need to see
- [x] Add a `Ready for Prioritization` label

**Comment by bphan002** [comment]
i. Availability: May 7th
II. ETA: May 9th

**Comment by Thinking-Panda** [comment]
Hi @roslynwythe and @bphan002  , I need a clarification. Does the text inside the red circle have to be included for the new version?
![issue4439](https://github.com/hackforla/website/assets/122488603/3c4cb2ba-1a8b-4fa6-b003-b421acdfb16b)
