### ISSUE TITLE
img Tag Refactor: Events page(s)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4445]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/events.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="vector-img" src="../assets/images/hack-nights/locations.svg" alt="" />
```
to
```
<img class="vector-img" src="../assets/images/hack-nights/locations.svg" alt="">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/pages/events.html
2. Webpage(s): https://www.hackforla.org/events/
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

**Comment by JessicaLucindaCheng** [comment]
Since I'm using this as an example issue, don't add a "Ready for Prioritization" label nor remove the "ready for dev lead" label until all the issues have been written in the [`img with Ending Slash` tab in the `HfLA-Website: img Tag Audit (Epic #4362)` Google Sheet](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0)

**Comment by wKategianes** [comment]
Availability: 12pm-5pm PST
ETA: 4/14/23

**Comment by roslynwythe** [comment]
Hi @wKategianes thank you for taking on this issue.  I'm moving the issue to the "In Progress" column.
