### ISSUE TITLE
Refactor/Remove donate-card component

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4454]
### Dependency

- [x] #4263 
- [x] #4439

### Overview

The large component `_includes/donate-card.html` has been replaced by smaller components so its elements will be moved into `pages/donate.html`, and the component ("include") file will be deleted. 

### Action Items

- [x] Open `_includes/donate-card.html` and `pages/donate.html`
- [x] In `pages/donate.html`, replace the line
```
{% include donate-card.html %}
```
with the contents of `pages/donate.html`
- [x] Delete the file `_includes/donate-card.html`
- [x] Use git to add and commit the change (deletion)
- [x] Using docker, confirm that the following website pages match the live web pages: 
   - [x] Donate Page: [docker](http://localhost:4000/donate) matches [live web page](https://hackforla.org/donate)
   - [x] Join Us Page: [docker](http://localhost:4000/join) matches [live web page](https://hackforla.org/join)
   - [x] About Us Page: (click to open the "Make a Donation" card) [docker](http://localhost:4000/about) matches [live web page](https://hackforla.org/about)

#### Merge Team
- [x] In Epic #4492, check off the dependency under "Clean up Issues".

### Resources/Instructions
<details><summary>Donate</summary>
<p>
https://www.hackforla.org/donate/

https://github.com/hackforla/website/blob/gh-pages/pages/donate.html

![screencapture-hackforla-org-donate-2024-01-22-18_09_16](https://github.com/hackforla/website/assets/37763229/8c8937b8-55cd-4801-be5c-9e2e7b772202)
</p>
</details> 

<details><summary>Join</summary>
<p>
https://hackforla.org/join

![image](https://github.com/hackforla/website/assets/37763229/af4120ff-675c-48ed-9aff-0eb5d6bd9d3c)

</p>
</details> 

<details><summary>About</summary>
<p>
https://hackforla.org/about

![image](https://github.com/hackforla/website/assets/37763229/337c4129-4b7c-42d9-8719-378e42c90c7f)

</p>
</details> 

- This issue is part of Epic #4492

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe LGTM! I think you can move this into the Ice Box and unassign yourself.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I will need screenshots of the way it is now or the way it will look, so that I can proof the work when it gets to QA

**Comment by heejung-hong** [comment]
1. **Availability:** Mon-Fri 5pm-9pm
2. **ETA:** 02/08
