### ISSUE TITLE
Refactor/Remove join-donate-card component

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4455]
### Dependency

- [x] #4565

### Overview

The large component `_includes/join-donate-card.html` has been replaced by smaller components, so its elements will be moved into `pages/join-us.html`, and the include file will be deleted. 

### Action Items

- [x] Open `_includes/join-donate-card.html` and `pages/join-us.html`
- [x] In `pages/join-us.html`, replace the line
```
{% include join-donate-card.html %}
```
with the contents of `_includes/join-donate-card.html`
- [x] Remove the file `_includes/join-donate-card.html`
- [x] Use git to add and commit the change (including the deletion)
- [x] Using docker, confirm that the local Join Us page matches the [Join Us webpage](https://hackforla.org/join)

#### Merge Team
- [x] In Epic #4492, check off the dependency under "Clean up Issues".

### Resources/Instructions
- Join Us [webpage](https://hackforla.org/join)
- This issue is part of Epic #4492

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe Good job! I see it still has a `Draft` label so if you want me review it again after you are doing drafting it let me know.
- [x] Please add a `Size` label.

Then, if you are done writing this issue, I think you can remove the `Draft` label, unassign yourself, and move it to the Ice Box column.

**Comment by k-rewd** [comment]
i. Availability: 11AM - 4PM PST M-F
ii. ETA: EOD 11/24/2023
