### ISSUE TITLE
Remove unused donation circle graphic file from donate images folder

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4456]
### Dependency

- [x] #4263 
- [x] #4439

### Overview
We want to delete the unused `donation-chart.svg` so that we keep the file system clean and avoid confusion.

### Details
The donation circle graphic previously used on the Donate page has been replaced with HTML/CSS for improved readability and accessibility.

### Action Items
- [x] Delete the file `assets/images/donate/donation-chart.svg`
- [x] Use git to add and commit the change (deletion)
- [x] Using docker, confirm that the Donate [local page](http://localhost:4000/donate) matches the [live webpage](https://hackforla.org/donate) 

#### Merge Team
- [ ] In Epic #4492, check off the dependency under "Clean up Issues".

### Resources/Instructions
- [unused donation graphic](https://github.com/hackforla/website/blob/gh-pages/assets/images/donate/donation-chart.svg)
- This issue was created as a result of #4407 and is a part of epic #4492

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe LGTM! I rewrote the Overview and moved a part of what you wrote in the Overview to a Details section. You can unassign yourself and move this to the Ice Box column.

**Comment by klei0229** [comment]
i. Availability: 6PM-10PM PST Weekdays
ii. ETA: (When do you expect this issue to be completed?) 9/1//2023 EOD
