### ISSUE TITLE
Create Component and Refactor HTML for "In-Kind" text on Donate page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4457]
### Dependency

- [x] #3983

### Overview

As developers we need to componentize donation elements which appear on multiple pages in the site, in order to present a consistent appearance and efficiently reuse code.  In this issue, the text on the Donate page below "Provide In-Kind Software & Services" will be componentized.  

### Details

- Please refer to the screenshot under Resources.  The paragraphs depicted in the screenshot appear beneath the header "Provide In-Kind Software & Services" on the Donate page, and the HTML is contained in `_includes/donate-card.html`.   
- To create a reusable component, the paragraphs below the heading (but not the heading) will be moved to a new component 

### Action Items

- [x] Open the current file `_includes/donate-card.html`.  Create a new component file `_includes/donation/in-kind.html` then remove the appropriate `<p>` elements from the current file and add them to the new file.  Note that the heading "Provide In-Kind Software & Services" will not be moved into the new component; instead it should be retained in the existing files.  
- [x] Update `_includes/donate-card.html` to reference the new component file using the liquid `{% include <filename> %}` syntax.  Note that 'filename' is relative to the `_includes` folder.  

#### Merge Team
- [x] In Epic #4492, check off the dependency under "Creating/Integrating New Issues".  If all of the dependencies under that heading have been merged, then release dependencies on all the issues listed under "Clean Up".

### Resources/Instructions

<details>
 <summary>Screenshot of the new component elements</summary>

![image](https://user-images.githubusercontent.com/5314153/234200133-e9b96721-5100-400d-9891-62decbcf87cb.png)

</details>

- HfLA Donate Page: [webpage](https://hackforla.org/donate) and [html](https://github.com/hackforla/website/blob/gh-pages/pages/donate.html)
- [Donate Card - Donate Page version](https://github.com/hackforla/website/blob/gh-pages/_includes/donate-card.html)

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty please see my question about this issue here https://github.com/hackforla/website/issues/4407#issuecomment-1513897404

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe did we answer the question in our meeting on Monday for the above comment? https://github.com/hackforla/website/issues/4457#issuecomment-1513904471

And is this ready to prioritize?

If we did, and it is, please unassign and add the ready for prioritization label.  If we did not, or it is not, please indicate remaining decisions.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty I do have a remaining question.  It appears that for the "In-Kind" component, it would make sense to include the heading 
`<h3>Provide In-Kind Software & Services</h3>`
in the component, because there is a consistent styling of the heading for both the Donate and Join Us page on which the component will be placed.   Is that acceptable to you?

**Comment by roslynwythe** [comment]
> @roslynwythe did we answer the question in our meeting on Monday for the above comment? [#4457 (comment)](https://github.com/hackforla/website/issues/4457#issuecomment-1513904471)
> 
> And is this ready to prioritize?
> 
> If we did, and it is, please unassign and add the ready for prioritization label. If we did not, or it is not, please indicate remaining decisions.

Yes @ExperimentsInHonesty it is ready for prioritization, but the issue is really quite simple and so I changed the Complexity tag to Small.

**Comment by pdimaano** [comment]
Availability: Weekday evenings
ETA: 5/12/23
