### ISSUE TITLE
Delete unused donation circle graphic from join-us image folder

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4466]
### Dependency

- [x] #4263 
- [x] #4439
- [x] #4544

### Overview
We want to delete the unused `donation-graphic.svg` so that we keep the file system clean and avoid confusion.

### Details
The donation circle graphic previously used on the Join Us page has been replaced with HTML/CSS for improved readability and accessibility.

### Action Items
- [x] Delete the file `assets/images/join-us/donation-graphic.svg`
- [x] Use git to add and commit the change (deletion)
- [x] Use docker to confirm that the Join Us [local page](http://localhost:4000/join) matches the [live webpage](https://hackforla.org)

#### Merge Team
- [ ] In Epic #4492, check off the dependency under "Clean up Issues".

### Resources/Instructions
- [unused donation graphic](https://github.com/hackforla/website/blob/gh-pages/assets/images/join-us/donation-graphic.svg)
- This issue is part of Epic #4492

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe LGTM! I rewrote the Overview and moved a part of what you wrote in the Overview to a Details section. You can unassign yourself and move this to the Ice Box column.

**Comment by ndmoc** [comment]
Hey Roslyn, can i take this issue as a good first issue?

**Comment by ndmoc** [comment]
i. Availability: (When are you available to work on the issue/answer questions other programmers might have about your issue?) From today to next Tuesday(8/29)
ii. ETA: (When do you expect this issue to be completed?)
Latest completion date 8/29
