### ISSUE TITLE
VS Code Spell Checker Extension: Meeting Messaging

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4470]
### Dependencies
- [x] #4101 
- [x] #5652

### Overview
As dev leads, we need to notify developers that we are adding the VS Code Spell Checker Extension across local environments so that everyone gets a chance to install the extension.

### Action Items
- [ ] Review the slides or instructions used during meetings, if any, and create additions or new materials to share the messaging that will support the rollout plan
- [ ] Notify developers during the following meetings:
  - [ ] Sun. Oct 8, 2023
  - [ ] Tues. Oct 10, 2023
  - [ ] Thurs. Oct 12, 2023
  - [ ] Sun. Oct 15, 2023
  - [ ] Tues Oct 17, 2023
  - [ ] Thurs Oct 19, 2023
  - [ ] Sun. Oct 22, 2023
  - [ ] Tues Oct 24, 2023
  - [ ] Thurs Oct 26, 2023
- [ ] When all meetings have been addressed, release dependency on https://github.com/hackforla/website/issues/4349. If all dependencies have been satisfied, move that issue into the New Issue Approval column with the ready for dev lead or ready for product label for review and a note about where to find the finished plan.

### Resources
- [HfLA website onboarding slide](https://docs.google.com/presentation/d/1aaAS4azzP84T_C8LK9Rp4juDn6T1SifspVBmpupYnZA/)
- [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) as a local linter

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge sorry I missed this.  can we revise the dates and then get this issue out.

**Comment by roslynwythe** [comment]
- @ExperimentsInHonesty I need help understanding why you had applied 'ready for dev lead' to this issue.   Don't we want instructions to be published before we make meeting annoucements?  I believe that would include, but not be limited to #4101.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I moved this into the new issue review column because the dependency is resolved. Please add a ready for prioritization label if its ready.

**Comment by ExperimentsInHonesty** [comment]
Or we can close this if everyone already knows.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty I believe most everyone knows because the instructions have been in CONTRIBUTING.md for awhile, but if there is still a desire to do messaging in meetings, I suggest that we rewrite this issue to add an item to the Tuesday or Sunday meeting agendas.  But in that case we should add dependencies on #6446 and/or on a proposed wiki page "How to manage spell check warnings"
