### ISSUE TITLE
Decision Record: VS Code Spell Checker Extension

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4471]
### Overview
We need to create a Decision Record so that we have the history of why & how we are using this spelling linter so that people in the future can understand it.

### Action Items
- [x] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)

### Action Items to be completed when new wiki is ready
- [x] Create a new Decision Record in [Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted)
- [x] Follow the template to document this choice
- [x] Be sure to include the following in your decision record:
  - [x] Why we are using the linter
  - [x] Why specifically this linter and what the requirements were
    - See comments in https://github.com/hackforla/website/issues/3546
  - [x] Link to the extension for developers to install
  - [x] Link to issue #4349 
  - [x] Steps being taken to implement the linter across the team
  - [x] Guidance on what has worked and what hasn't
    - This guidance should consider plans for implementing other local linters at a later time
- [x] Add a link to the DR in [Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted) 
- [x] Update the main [Decision Records](https://github.com/hackforla/website/wiki/Decision-Records) page with a link to the new DR preceded by a ✅
- [x] Present your record to Product and Dev Leads Team for approval

#### For Merge Team/Dev Leads/PM
- [ ] When the DR has been accepted, release dependency on https://github.com/hackforla/website/issues/4349. If all dependencies have been satisfied, move that issue into the New Issue Approval column with the ready for dev lead or ready for product label for review and a note about where to find the finished plan.

### Resources
- [Decision Records on Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted)
- [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) as a local linter

#### Decision Record Template
````
This is a record in the [Decision Records on Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted).

#### Issue 
#### Problem Statement
#### Potential Solution
#### Feasibility Determination
````

**Comment by amath95** [comment]
Availability: 05/07
ETA: 05/12

**Comment by LRenDO** [comment]
Availability: 6/9/23 11:30-3pm
ETA: 3pm

**Comment by LRenDO** [comment]
# DR: VS Code Spell Checker Extension
This is a record in the [Decision Records on Solutions Adopted](https://github.com/hackforla/website/wiki/Decision-Records-on-Solutions-Adopted).

#### Issue
#4471
 
#### Problem Statement
Preventing misspellings on our website.

#### Potential Solution
Using a spell check plugin and linter to ensure correct spelling.


#### Feasibility Determination
It was decided that we would use a linter to ensure correct spelling. The linter chosen was [Code Spell Checker](https://github.com/hackforla/website/issues/3546). More details for reasoning can be found in #3546.

Summary of reasoning for choosing Code Spell Checker:
- Can be used by developers that do not use VS Code
- Most other linters note their dictionaries might not be accurate and Code Spell Checker is the most current
- Can be used with GHA and locally with either VS Code plugin or npm package

##### Installation Resources
Resources from #3546:
- [Installation instructions for the Code Spell Checker VS Code extension](https://dev.to/codingwithadam/how-to-use-vs-code-spell-checker-detailed-walkthrough-to-setup-and-use-multiple-languages-5c6e)
- [FAQ on using Code Spell Checker as a linter or part of the build process](https://github.com/streetsidesoftware/vscode-spell-checker/blob/main/FAQ.md#can-i-use-the-spell-checker-as-a-linter-or-part-of-the-build-process)
- [Instructions for npm package installation for cspell](https://www.npmjs.com/package/cspell)

##### Roll Out Plan
The roll out plan including the steps being taken to roll out across the team can be found in #4349. 

Plan Summary:
- Update CONTRIBUTING.md wiki
- Add decision record
- Add GitHub Actions messages to pull requests and prework issues
- Create slides for developer and onboarding meeting messaging
- Messaging to developer team on slack


##### Future Plans
Guidance advised for future plans:
- Creating a new issue for a linter to address grammar issues, as Code Spell Checker only checks spelling
- Finding a solution that checks words of 3 letters or less in the future, as Code Spell Checker only checks words that are at least 4 characters

**Comment by LRenDO** [comment]
Hi @jdingeman, @roslynwythe, @t-will-gillis, and @blulady! 

I completed the [Decision Record](https://github.com/hackforla/website/issues/4471#issuecomment-1585074737) in the comment above. Please let me know if there are any changes you'd like or if I should loop someone else in as well. Thanks!

**Comment by LRenDO** [comment]
Hi @jdingeman, @roslynwythe, @t-will-gillis, and @blulady!

Pinging folks again since I haven't heard anything yet. The [Decision Record](https://github.com/hackforla/website/issues/4471#issuecomment-1585074737) above is ready for review. Please let me know if there are any changes you'd like. Thanks!

**Comment by LRenDO** [comment]
Progress Update
Work complete. Awaiting review.

**Comment by roslynwythe** [comment]
Hi @LRenDO This looks good to me, although I think under "Issue", you should list "#4471" since that is the issue for which you wrote the DR.  There is no team meeting on Sunday 7/2 so I will put it on the agenda for the PM/Dev Lead meeting on Monday 7/3, but Bonnie may want to discuss it with you at the 7/9 all-team meeting.

**Comment by LRenDO** [comment]
> Hi @LRenDO This looks good to me, although I think under "Issue", you should list "#4471" since that is the issue for which you wrote the DR.  There is no team meeting on Sunday 7/2 so I will put it on the agenda for the PM/Dev Lead meeting on Monday 7/3, but Bonnie may want to discuss it with you at the 7/9 all-team meeting.  

Thanks for the update, @roslynwythe and good catch on the issue number! I've updated it in the comment with the DR.

**Comment by LRenDO** [comment]
At the July 9th meeting, PM @wanyuguan approved closing this issue. @roslynwythe / @hackforla/website-merge will close the issue.
