### ISSUE TITLE
Update Project Profile: HackforLA.org Website

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4473]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Hackforla.org Website project page needs to be updated to reflect accurate team information. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/website.md` file and find the `leadership` variable.
  - [x] Remove Bitian Zhang
  - [x] Remove Arpita Pandya
- [x] Verify the changes by viewing the [Hackforla.org Website project page](https://www.hackforla.org/projects/website) on your local environment and include a screenshot with your pull request

### Instructions
- For the github link, append the team member's github handle to https://github.com/
- For the picture link, append the team member's github handle to https://avatars.githubusercontent.com/
- For the slack link, append the team member's slack ID to https://hackforla.slack.com/team/

### Resources
- [website.md](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by 93Belen** [comment]
Availability for this week: All day Tuesday, Friday and Sunday
My estimated ETA for completing this issue: 10 minutes

**Comment by roslynwythe** [comment]
Hi @93Belen when you self-assign an issue, please move it to the "In Progress" column of the Project Board.  You can do that by clicking on the arrow that is circled

![image](https://github.com/hackforla/website/assets/5314153/3fea2c06-fdfd-429a-94d0-d7ddb6eb9031)

**Comment by 93Belen** [comment]
Sorry about that! I'll do it next time :)
