### ISSUE TITLE
Integrate Donation gif component into About Us donate include

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4504]
### Dependency

- [x] #4439

### Overview

We need to integrate the new donation gif component into the About Us donate include, so that there is a consistent appearance for the animated donation gif and associated text throughout the site.  

### Action Items

- [x] Open the donation gif component file `_includes/donation/donate-gif-text.html` and the About Us Donation include file at `_includes/about-page/about-card-donations.html`.  Note that the visual elements represented in the donation gif component are also represented in the About Us Donation file, however, they are implemented using different html/css methods.  
- [x] In `_includes/about-page/about-card-donations.html`, remove all of the HTML elements which are represented in the donation gif component, replacing them with the liquid tag `{% include <filename> %}`, where `<filename>` references the donation gif component.  Note that `<filename>` is relative to the `_includes` folder. 
- [ ] The SCSS for styling the new component is located at `_sass/components/_donate-components.scss`.  Update SCSS classes as well as HTML (in the About Us Donation include file) as needed so that the component styles are independent of the About Us page styles and that the appearance of the page in desktop view matches the current appearance.  In mobile view, the appearance will differ from the current page because the animated gif is now centered, and the sentence "100% of donated proceeds..." is positioned beneath the animated gif.  

#### Merge Team
- [ ] In Epic #4492, check off the dependency under "Creating/Integrating New Issues".  If all of the dependencies under that heading have been merged, then release dependencies on all the issues listed under "Clean Up". 

### Resources/Instructions
- [About Us - Donation Include HTML](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-donations.html)
- [About Us page](https://www.hackforla.org/about/)
- This issue is part of Epic #4492

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe LGTM! I slightly changed the wording of the Overview and then made the items in the Resources/Instructions into bullet points so that the title for the epic would show.

**Comment by bphan002** [comment]
Availability Thursday
ETA Saturday
