### ISSUE TITLE
GitHub Actions: Notify developers if they are working on multiple issues at once

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4505]
### Overview
We need a GitHub Action that notifies a developer when they have assigned themselves to multiple open issues, so that they don't "camp on issues".  

### Details
Camp on issues = when a person assigns themselves to multiple issues, planning on working on them in the future.  You cannot work on two things simultaneously, so you are basically keeping other people who are looking for an issue from being able to start on them.

As a developer on the website team, you are expected to follow the chain of complexity when you assign yourself an issue; that is, two good first issues, one small issue, one medium issue, and at least one large issue while only working on one issue at a time. 

Currently, when a developer assigns themselves an issue, a GitHub Action runs that posts this comment on the issue:  
<details><summary>Message</summary>
 
  ```
  Hi @developer, thank you for taking up this issue! Hfla appreciates you :)
  
  Do let fellow developers know about your:-
  i. Availability: (When are you available to work on the issue/answer questions other programmers might have about your issue?)
  ii. ETA: (When do you expect this issue to be completed?)
   
  You're awesome!
  
  P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)  
  ```
</p>
</details>  

When a developer assigns themselves to more than one issue, we want to post an alternate message instead. 

### Action Items
- [x] Become familiar with [HfLA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
  - [x] If you have not already done so, create a copy of the Project Board into your own repo ([Tip 6: Creating your own Project Board](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-6-creating-your-own-project-board))
  - [x] Be sure to read up on using Personal Access Tokens to test the project board in your own repo ([Tip 7: Using Personal Access Tokens to test in your own Project Board](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-7-using-personal-access-tokens-to-test-in-your-own-project-board))  
- [x] Review the [.github/workflows/issue-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml) workflow and note the job "Ask-For-Preliminary-update", which is triggered when an issue is assigned (`event_name` and `event.action`). The workflow first checks labels, and then runs `preliminary-update-comment.js` to post a comment on the issue.
- [x] In [preliminary-update-comment.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-preliminary-comment/preliminary-update-comment.js), add to the existing script with code that checks whether the developer is assigned to multiple issues and if so posts the alternate message.
- [x] Your script should check the following:
   - [x] Whether the dev is assigned to multiple open issues at once
   - [x] Since closed issues stay assigned to the dev that completed them, it should not look at any of the dev's closed issues
      - [x] This should exclude any issues with label `Complexity: Prework`
      - [x] This should exclude any devs who are members of either the ['website-merge'](https://github.com/orgs/hackforla/teams/website-merge) or ['website-admins'](https://github.com/orgs/hackforla/teams/website-admins) teams
     - [x] This should exclude any Agenda issues (2010, 2027, 2212, 2607) 
     - [x] This should exclude any issues in the following columns:
        - [x] "Emergent Requests"
        - [x] "New Issue Approval"
- [x] Navigate to the [add-preliminary-comment](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-issue/add-preliminary-comment) collection
   - [x] Add a new .md file named `multiple-issue-reminder.md`
   - [x] Copy the following text into the .md file
      ```
      <!-- Template for a notification to the assignee that they're already assigned to an open issue and that they will be unassigned -->
      Hello @${issueAssignee}, we appreciate you taking on this issue, however it looks like you're already working on another issue at this time. Please wait until your current issue is merged before taking on another issue. :)

      We are going to unassign you from this issue so you can focus on your current issue.

      Hfla appreciates you! :)
      ```
  - [x] If the dev already has an open issue, the new comment `multiple-issue-reminder.md` should post **_instead_** of the comment that asks the dev for their availability
- [x] The script should also perform the following:
   - [x] Unassign the dev from the issue
   - [x] Add a `ready for dev lead` label
   - [x] Move the issue to the "New Issue Approval" column for dev leads to reprioritize 
- [x] Demonstrate your new GHA to the merge team

### Resources/Instructions
- ER associated with this issue: https://github.com/hackforla/website/issues/4230
- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
- [GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
- [actions/github-script](https://github.com/actions/github-script)
- [GitHub RESTAPI](https://docs.github.com/en/rest)
- HfLA [GitHub Action](https://github.com/hackforla/website/tree/gh-pages/.github/workflows) workflows
- HfLA [GitHub Action](https://github.com/hackforla/website/tree/gh-pages/github-actions) JavaScript files
- HfLA's [GitHub Actions](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions)

**Comment by ExperimentsInHonesty** [comment]
should also exclude issues that are agendas, in the ER column,  new issue approval column

**Comment by t-will-gillis** [comment]
> should also exclude issues that are agendas, in the ER column, new issue approval column

@ExperimentsInHonesty I believe the GHA could be set up to exclude members that have a role of maintainer on the "website-write" team, which should exclude the agendas and also as is current where yourself and Roslyn, etc. are assigned to multiple issues.


UPDATE: 3/24/24: Instead of 'Maintainer', note added to exclude team members from 'website-merge' and 'website-admins'

**Comment by davidwiese** [comment]
Availability: Weekdays 1pm-4pm PST
ETA: 10/13/23

**Comment by davidwiese** [comment]
Need to unassign, will not have time to complete this issue

**Comment by erinzz** [comment]
Availability: weekdays 1 - 6 PM
ETA: 10/13

**Comment by erinzz** [comment]
Have not had time to work on this as well, will unassign

**Comment by meru-a** [comment]
Availability: Evenings 6-10 pm & weekends
ETA: 10/29 EOD

**Comment by meru-a** [comment]
1. Progress: Familiarized myself with GHAs, completed 6/23 tasks, in the process of script development and testing. I might need more time to finish the task, so will be extending the ETA for another 2 weeks for now.
2. Blockers: None so far
3. Availability: Evenings & weekends
4. ETA: 11/12 EOD

**Comment by meru-a** [comment]
Sorry, didn't have time to work on this as well, I'll unassign

**Comment by one2code** [comment]
**Availability**: 02/08-02/09/24 12-6PM EST, 02/13/24,02/17-02/18/24 12-6PM EST
**ETA**: By 02/18/24

**Comment by one2code** [comment]
Current update: I have implemented logic that will pull all of the open issues and filter out issues with the label `Complexity: Prework or prework`. After testing that this is working correctly, I will begin to further implement logic to exclude the maintainer role, and and the `New Issues Approval and Emergent Requests`. It looks like the Projects API will need to be hit to perform that step.

This issue may take longer than expected, due to the different API's that need to be hit to successfully implement the requested features, and the challenges of managing this without exceeding Github's rate limiting.

**Comment by LRenDO** [comment]
Hi @one2code! Thanks for working on this issue. If you're still working on it, please add an update. If you're not able to continue to working on it, leave us a comment to let us know.  If we don't hear from you soon, we will remove you from the issue. Thanks!

**Comment by LRenDO** [comment]
Hi @one2code! Since we haven't received an update from you, I'm taking you off the issue and moving it for re-prioritization. Feel free to take on another issue, if you become available.

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis please check these off when the changes have been made.
- [x] It looks like there are comments that you and I have left on this issue, that possibly need to be integrated into the top portion so that we can hide them.  
- [x] One of the people who assigned and then was unassigned from the issue references that multiple APIs need to be used, and they were concerned about rate limiting.  Are there resources we have about those things that are not linked to this issue?  Or if they are linked, do we need to call them out more clearly?

WG: I revised / reordered the description in a way. About the rate limiting: although I have run into rate limiting once or twice in on past issues, this usually resets after an hour. IMO I don't believe there is anything unusual about this issue that would make the rate limiting a particular concern.

**Comment by Ayrh1** [comment]
Availability: Monday - Sunday: 6pm - 7:30pm 

ETA: Mon: 5/11/24

**Comment by ExperimentsInHonesty** [comment]
@Ayrh1 I have moved this issue into the in progress column.  Please remember to do that when assigning yourself to an issue in the future.

**Comment by Ayrh1** [comment]
Progress: "What is the current status of your project? What have you completed and what is left to do?"

-Ive gone through all the documentation on GitHub actions, a lot!
Blockers: "Difficulties or errors encountered."
-None Yet,

Availability: "How much time will you have this week to work on this issue?"
-6hrs per week 

ETA: "When do you expect this issue to be completed?"
-I and dedicating 6hrs per week, but the documentation alone was a bit long, but necessary. Might change my completion date depending of how much i advance this week.
  
Pictures (optional): "Add any pictures of the visual changes made to the site so far."
If you need help, be sure to either: 1) place your issue in the Questions/In Review column of the Project Board and ask for help at your next meeting, 2) put a "Status: Help Wanted" label on your issue and pull request, or 3) put up a request for assistance on the #hfla-site channel. Please note that including your questions in the issue comments- along with screenshots, if applicable- will help us to help you. https://github.com/hackforla/website/issues/1619#issuecomment-897315561 and https://github.com/hackforla/website/issues/1908#issuecomment-877908152 are examples of well-formed questions.

**Comment by Ayrh1** [comment]
1.Progress: "What is the current status of your project? What have you completed and what is left to do?"
I FINISHED REVIEWING THE RESOURCES PROVIDED, NOW IM WORKING ON THE CODE 
2.Blockers: "Difficulties or errors encountered."
I DID NOT KNOW MUCH OF GITHUB-ACTION BUT WITHT HE MATERIAL PROVIDED I FEEL I GOT A BETTER UNDERSTANDING 
3.Availability: "How much time will you have this week to work on this issue?"
ABOUT 6 HOURS 
4.ETA: "When do you expect this issue to be completed?" 
I EXPECT MAY 25
5.Pictures (optional): "Add any pictures of the visual changes made to the site so far."

**Comment by moazDev1** [comment]
Availability: Fri - Sun 5PM - 10PM
ETA: 6/23

**Comment by moazDev1** [comment]
Hi @${issueAssignee}, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
ii. **ETA:** (When do you expect this issue to be completed?)

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)
