### ISSUE TITLE
Integrate Donation gif component into Join Us donate include

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4507]
### Dependency

- [x] #4439

### Overview

We need to integrate the new donation gif component into the Join Us donate include, so that there is a consistent appearance for the animated donation gif and associated text throughout the site.

### Action Items
- [x] Open the Join Us donate include file at  `_includes/join-donate-card.html`.  This will be the only HTML file modified in this issue.  View the new Donation gif include at `_includes/donation/donate-gif-text.html`.    
- [x] The `<h3>` heading with text "Make a Donation to Hack for LA" is not part of the component and so it will be retained in the Join Us donate include file, however it must be moved from its current location.  One approach would be to move the `<h3>` into a new div that also contains `<div class="join-us-donation">`
- [x]  In `pages/join-donate-card.html` remove all elements contained in the new component, replacing them with the liquid tag `{% include <filename> %}`, where `<filename>` references the new component and is relative to the `_includes` folder. 
- [x] The SCSS for styling the new component is located at `_sass/components/_donate-components.scss`.  Update scss classes as needed so that the component styles are unique and independent of the target pages, and the appearance of the Join Us page is unchanged from the current page for both mobile and desktop screen sizes. Note that in mobile view, the sentence "100% of donation proceeds.." is positioned differently, beneath the animated gif. 
- [x] In `_sass/components/_join-us.scss` delete any styles that are no longer used.  

#### Merge Team
- [ ] In Epic #4492, check off the dependency under "Creating/Integrating New Issues".  If all of the dependencies under that heading have been merged, then release dependencies on all the issues listed under "Clean Up". 

### Resources/Instructions
- [Join Us Donate Card Include](https://github.com/hackforla/website/blob/gh-pages/_includes/join-donate-card.html) 
- [Donation Gif Include](https://github.com/hackforla/website/blob/gh-pages/_includes/donation/donate-gif-text.html)
- [Join Us SCSS](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_join-us.scss)
- This issue was created as a part of the Epic #4492

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe LGTM! I made a minor few edits:
- slightly edited the wording in the Overview,
- made the links in the Resources/Instructions section into bullet points so that the title of the epic would display, and
- I fixed the links, including Donation Gif Include link from https://github.com/hackforla/website/blob/gh-pages/_includes/donate-gif-text.html 
to 
https://github.com/hackforla/website/blob/gh-pages/_includes/donation/donate-gif-text.html

If you are done with writing this issue, I think you can unassign yourself from this issue. :smiley:

**Comment by adrianang** [comment]
- Availability: MTThFSS, 6 PM - 10 PM (PST) (Weeks of 7/3, 7/10)
- ETA: I plan on finishing this issue by Tuesday, 7/11 at 10 PM.
