### ISSUE TITLE
Remove references to "good second issue" labels in the Onboarding infos/links column

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4509]
### Dependency
- [x] #4423
- [x] #4432 is ready for implementation

### Overview
We need to remove the card so that developers do not use the hyperlink to filter the Project Board for issues that don't exist.

### Action Items
- [ ] Delete the card: [Card Backend 2nd issue](https://github.com/hackforla/website/projects/7#card-72853600)
- [ ] Move this issue to the Questions/In Review column and set the label `ready for dev lead`

#### For Merge Team/Tech Lead/PM
- [ ] When this issue is closed, release the dependency for this issue on #4432

### Resources/Instructions
- This is part of epic #4432 
- HfLA site [Project Board](https://github.com/hackforla/website/projects/7)

**Comment by roslynwythe** [comment]
The card "Backend 2nd Issue" card no longer exists and all other references to "good second issue" have been removed from cards in the Onboarding info/links column, so this issue is not necessary.
