### ISSUE TITLE
Change "HackforLA.org" project title to enable proper screen reader pronunciation

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4514]
### Overview
As developers, we must ensure that the Hack for LA website is accessible to users of screen readers in order to achieve our goal of inclusivity.  Screen readers do not prounounce "Hackforla" properly, therefore in this issue we will rename the project "Hack for LA website"

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the website project markdown file `_projects/website.md`, then find the `title` variable. 
- [x] Change the value of the `title` variable from 
`hackforla.org` 
to 
`Hack for LA Site`
- [x] Do not change any other instances of `hackforla.org`.  
- [x] Confirm the change in the browser on the [Hack for LA Current Projects Page](https://www.hackforla.org/projects) and on the [Website Project Page](https://www.hackforla.org/projects/website).  The location of the modified text is shown the screenshots in the Resources section below.  

### Resources/Instructions
<details><summary>Display of the project title on the Current Projects page (circled)</summary>

![image](https://github.com/hackforla/website/assets/5314153/ba99fa0e-ca8c-4b50-a8ce-fd9742dac4fb)

</details> 
<details><summary>Display of the project title on the Website Project page (circled)</summary>

![image](https://github.com/hackforla/website/assets/5314153/f9d8ec82-7b63-400b-92ed-9aa9f52268da)

</details> 

- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [Hack for LA Website Project Markdown File](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [Website Project Page](https://www.hackforla.org/projects/website)
- [Hack for LA Current Projects Page](https://www.hackforla.org/projects)

**Comment by roslynwythe** [comment]
Tested this solution further and found it does not solve the problem.  Needs further research.

**Comment by 1bhavyasingh1** [comment]
May I try this??

**Comment by roslynwythe** [comment]
@1bhavyasingh1 Our issues are available only members of the "Hack for LA" organization.  Perhaps you would like to join us?  You don't have to live in L.A.  Please see https://www.hackforla.org/join.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty - the only way to ensure correct screen reader pronunciation of the project title is to change the title from "HackforLA.org Website" to "Hack for LA Website".  Unfortunately that does not communicate the address of the site.  Please advise, should we proceed with this issue or should it be closed as Not Planned?

A similar situation exists (in a separate issue) regarding the text "hackforla.org website" in the project description.

**Comment by ExperimentsInHonesty** [comment]
Hack for LA Site
The Hack for LA Site (hackforla.org) is…

**Comment by Abrosss** [comment]
Availability: Monday-Friday
ETA: today
