### ISSUE TITLE
ER: Tools Data format is inconsistent with current data format

### ISSUE THREAD

**Issue by Sebster3** [hackforla/website#4523]
### Emergent Requirement - Problem
In the project files at `/_projects`, we are currently storing tools data for projects in a csv

> Tools: figma, photoshop, google drive

Technologies is being stored in yml array

> Technologies
>   - Node.js
>   - React

### Issue you discovered this emergent requirement in
- #4427

### Date discovered 
2023-04-13

### Did you have to do something temporarily
- [x] YES - put a hold on my issue until I get a decision 
- [ ] NO

### Who was involved
@Sebster3 @ExperimentsInHonesty 

### What happens if this is not addressed
We will have to do some jumping through hoops to make the filter work and that potential will be a problem later

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

#### Roll out plan
- Figure out what pages call the tools data
  - use the tools data
  - how they use it
  - what will need to change when we move to yml array
- Identify Issues that need to be made 
     - P: An issue to make a template & Spreadsheet 
        - E: Issue to make the project file changes issue (this issue assigns the person who will make all the project issues and gives them the template and spreadsheet to use)
           - Issues made from the template that changes the data in the project pages(fb) (many issues)
   - E: Create Issue to make the issues for changing the identified files from `figuring out which pages call the tools data` 
      - Create the issue (fb) for each (non project.md) that needs a change
-  Final process
   - Confirm that all the backend changes on the feature branch have not changed the way anything looks
   - merge the feature branch into the main
   - release dependency on #4427 and update the issue so that it reflects the current changes.

Make the parent issues (dont make the issues for each project file.  That will be done by the person who gets that issue assigned).

**Comment by ExperimentsInHonesty** [comment]
- @Sebster3 I noticed you are waiting for the merge team to move your issue #4525 forward.  I added a time sensitive label and a note for the merge team.  I will also add the issue the dev/pm meeting.

**Comment by t-will-gillis** [comment]
It appears that #4525 addresses this ER in full. Since that issue is "Closed as Completed", this ER should also be closed.
