### ISSUE TITLE
Refactor the Privacy Policy to use markdownify and a yml file

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4527]
### Overview
We want to refactor the body of the Privacy Policy page to use a yml file for its contents/wording so that it will be easier to edit the contents of the Privacy Policy page in the future.

### Details
- Only the body of the Privacy Policy page will be refactored to use a yml file for its contents/wording.

  <details>
    <summary>Click here to see the body of the Privacy Policy page marked in a red rectangle</summary>

    ![privacy_-policy-body](https://user-images.githubusercontent.com/31293603/232429223-3e6c6e52-c8e6-4984-af88-3278f89308a2.png)

  </details>

### Action Items
- [x] Understand how the Letter from the Executive Director is implemented on the About page using a yml file and markdownify. (See the `About Page Files and Links to Get You Started` section in the `Resources/Instructions` section below. You may need to do additional research beyond the links and files provided.)
- [x] In the `_data/internal` directory, create a new file called `privacy-policy.yml` that contains the contents/words of the body of the Privacy Policy page
- [x] Refactor the body of the Privacy Policy page to use the contents in the `privacy-policy.yml` file and markdownify
- [x] Make sure the page looks good in desktop, tablet, and mobile views

#### About Page Files and Links to Get You Started
- About page's Letter from the Executive Director: https://www.hackforla.org/about/#letter
- [_includes/about-page/about-card-executive-letter.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-executive-letter.html)
- [_data/internal/executive_letter.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/executive_letter.yml)
- [_sass/components/_about.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_about.scss)

#### Privacy Policy Page Files and Links to Get You Started
- Privacy Policy page: https://www.hackforla.org/privacy-policy
- [pages/privacy-policy.html](https://github.com/hackforla/website/blob/gh-pages/pages/privacy-policy.html)
- [_sass/components/_privacy-policy.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_privacy-policy.scss)
- `Notes from assigned developer` in #2555 
- [HFLA Figma - Policy Page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17845%3A137765)
- [Content(Google Doc)](https://docs.google.com/document/d/19x1KsMTU-QBdopiV08HSBQ0i4g1ChrcPZ8ZXmUK50cY/edit#heading=h.1kvk4qkoxhzw)

#### Other Resources
- [_data/internal](https://github.com/hackforla/website/tree/gh-pages/_data/internal)
- [Liquid template language used by Jekyll](https://jekyllrb.com/docs/liquid/)
- [Hack for LA's Site Architecture wiki page](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)

**Comment by drakenguyen4000** [comment]
ETA: 5/9/23
Availability: M-F 7-9pm PST.  S-Su 10am-8pm

**Comment by drakenguyen4000** [comment]
Hi @JessicaLucindaCheng , I was able to make the necessary changes but I noticed that the font sizes for paragraphs and headers were different due to the missing class and id when using the yml file.  Was I supposed to also figure out how to match the font size?

**Comment by JessicaLucindaCheng** [comment]
@drakenguyen4000 

> Hi @JessicaLucindaCheng , I was able to make the necessary changes but I noticed that the font sizes for paragraphs and headers were different due to the missing class and id when using the yml file. Was I supposed to also figure out how to match the font size?

Yes
