### ISSUE TITLE
Update Project Profile: Guides Team

### ISSUE THREAD

**Issue by edwardsarah** [hackforla/website#4529]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
The Guides Team project page needs to be updated so that project team information is up to date. 

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/guides-team.md` file and find the `leadership` variable.
- [x] Remove the following members and their information
  - [x] Bukola Ogunleye
  - [x] Prakhar Singh 
- [x] Change Bonnie's title to Agile Coach
- [x] Verify the changes by viewing the [Guides Team project page](https://www.hackforla.org/projects/guides-team) on your local environment and include a screenshot with your pull request

### Resources
- [guides-team.md](https://github.com/hackforla/website/blob/gh-pages/_projects/guides-team.md)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by jdingeman** [comment]
### Project Name

Guides Team

### Project Card URL

guides-team.md

### Update the Title?

NO

### Title

_No response_

### Update the Description?

NO

### Description

_No response_

### Update the Image?

NO

### Image

_No response_

### Update the Technologies?

NO

### Technologies

_No response_

### Update the Partner(s)?

NO

### Partners

_No response_

### Update the Tools?

NO

### Tools

_No response_

### Update GitHub Link?

NO

### GitHub Link

_No response_

### Update Slack Link?

NO

### Slack Link

_No response_

### Update Test Site Link?

NO

### Test Site Link

_No response_

### Update Demo Site Link?

NO

### Demo Site Link

_No response_

### Update Site Link?

NO

### Site link

_No response_

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Bukola Ogunleye, Prakhar Singh

### Add person(s) and info to Leadership?

NO

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

_No response_

### Project Status

Active

**Comment by Ahtaxam** [comment]
@edwardsarah can i work on it to update file ?

**Comment by codinghorizons** [comment]
i. I am available 1 hour starting at 6 pm on Tuesdays and Thursdays
ii. I think this will be completed by 6/7/2023

**Comment by codinghorizons** [comment]
1. No progress
2. No difficulties. I just haven't put enough time into it.
3. I will be available at least 30 minutes each workday.
4. It should be completed by July 6th

**Comment by roslynwythe** [comment]
Hi @codinghorizons please leave an update using the outline presented in the above comment.  Or if you will not be able to continue working on this issue, please let us know.

**Comment by adrianang** [comment]
- Availability: 
    - F, 6 PM - 10 PM (PST) (Week of 6/18)
    - SuMTThF, 6 PM - 10 PM (PST) (Week of 6/25)
- ETA: I plan on finishing this issue by Friday, 6/30 at 10 PM.
