### ISSUE TITLE
ER: Filters on project page

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4530]
### Emergent Requirement - Problem
On the current homepage and Projects page, I can't see all the filter categories unless I do one of the following:
- Scroll all the way through all the projects
- Or collapse the Program Area filter in order to see the Status filter category or be able to see the `View all` in the Languages/Technologies filter category

To see the problem I am seeing, view the https://www.hackforla.org/projects/ page using Developer Tools and inspect it at 1024 x 659 and look at the filters on the left side while scrolling down the page.

<details>
  <summary>Click here to see the problem with not being able to see all the filters while scrolling</summary>
  <img src="https://user-images.githubusercontent.com/31293603/234155930-b1dabfdb-1c47-4164-9df4-ccee4e40fab1.gif" alt="">

</details>

### Issue you discovered this emergent requirement in
- Not applicable

### Date discovered 
2023-Apr-17

### Did you have to do something temporarily
- [x] YES
- [ ] NO

Scroll all the way through the projects or collapse a filter category

### Who was involved
@JessicaLucindaCheng 

### What happens if this is not addressed
It's not user friendly

### Resources
- https://www.hackforla.org/projects/

### Recommended Action Items
- [x] Discuss with Stakeholder Rep (Bonnie) potential solutions
- [x] Make a new issue
- [x] Discuss with team

**Comment by ExperimentsInHonesty** [comment]
We should make a new issue to fix it so that it operates the same way as REI and Amazon (pined to the top)

Also filter should be pinned to content
![image](https://user-images.githubusercontent.com/37763229/234152975-f524a3c0-d9a1-4edc-a84b-f0672c1b9198.png)
![image](https://user-images.githubusercontent.com/37763229/234153027-bd5488af-08fd-406c-b522-2277be8d6ad0.png)

**Comment by chrismenke45** [comment]
Availability: 8am-12pm weekdays
ETA: 4/28 EOD

**Comment by Adastros** [comment]
Availability (PST): 10 - 11:30 PM 03MAY2023
ETA (PST): 11:30 PM 03MAY2023

**Comment by Adastros** [comment]
- Issue for ER can be found in issue #4593

**Comment by Adastros** [comment]
Issue is done drafting and ready for prioritization. Closing ER

**Comment by Anahisv23** [comment]
Hi @JessicaLucindaCheng @Adastros, I'm working on issue #4593. My peers and I had a question regarding the issue. The issue states that the search bar needs to be pinned on viewports width above 767px (desktop view). Is pinning the search bar for viewports below 767px (mobile view) for the homepage and project page something we want to address in this issue or in another issue? Thank you!

**Comment by ExperimentsInHonesty** [comment]
> Hi @JessicaLucindaCheng @Adastros, I'm working on issue https://github.com/hackforla/website/issues/4593. My peers and I had a question regarding the issue. The issue states that the search bar needs to be pinned on viewports width above 767px (desktop view). Is pinning the search bar for viewports below 767px (mobile view) for the homepage and project page something we want to address in this issue or in another issue? Thank you!

@Anahisv23 Good question.  We are going to address the mobile separately in another issue

**Comment by ExperimentsInHonesty** [comment]
Notes for person making new ER

- [ ] We need to make a new issue to answer how we want the filter to behave when it's in mobile

### How we want it to behave
   - It will freeze the filter and search at the top as you scroll down. 
   - The applied filters will only be visible when you open the filter hamburger menu
   - see REI.com website

### What we need in order to make the new ER
- GIF of mobile of current site behavior
- Screenshot of REI
- revised viewport width below 767px

Once this comment has been made into an ER, then reassign `Adastros` to this issue, and close it.

**Comment by Anahisv23** [comment]
> > Hi @JessicaLucindaCheng @Adastros, I'm working on issue #4593. My peers and I had a question regarding the issue. The issue states that the search bar needs to be pinned on viewports width above 767px (desktop view). Is pinning the search bar for viewports below 767px (mobile view) for the homepage and project page something we want to address in this issue or in another issue? Thank you!
> 
> @Anahisv23 Good question. We are going to address the mobile separately in another issue

Gotcha. Thank you for the clarification!

**Comment by ExperimentsInHonesty** [comment]
Mobile view when filter you arrive at the page
![image](https://github.com/user-attachments/assets/66188b9e-db31-4654-a9ac-8a8e4dce7f02)

Mobile view when you scroll down the page
![image](https://github.com/user-attachments/assets/483a4273-7a83-455d-8818-7c76882277d2)

**Comment by ExperimentsInHonesty** [comment]
- We created a new mobile issue for this, which completes this ER https://github.com/hackforla/website/issues/7525
