### ISSUE TITLE
ER from TLDL: Pep talk wiki page

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4538]
TLDL stands for Task List Dev Leads.

### Emergent Requirement - Problem
**Issue Description**
Write an issue to have a pep talk wiki page saying how to deal with not knowing the language/tech stack so that new developers don't get discouraged and quit. The pep talk wiki page should include the following:
- Give examples of how to use current knowledge and applying it. For example, if you understand how if statements work in a different programming language, in Liquid it is similar.
- Not knowing the programming languages or tech stack is normal. It usually occurs for developers starting a new job and you learn as you go.
- It's okay if you need to spend some time understanding the existing codebase or understanding a new programming language/technology before you start coding for an issue.
- Employers often hire people who don't know a specific language if you are able to communicate on a resume and during the hiring process that you are willing to get up to speed on a new language, because many concepts are similar enough across languages.

### Who was involved
- @JessicaLucindaCheng
- @ExperimentsInHonesty 
- `@SAUMILDHANKAR`   

### What happens if this is not addressed
Some new developers get discouraged and quit.

### Recommended Action Items
- [x] Search and check 
  - [x] If an open issue exists that addresses this ER
  - [x] If a closed issue exists that has already addressed this ER
- [x] If an open issue doesn't exist and this ER wasn't already fixed by a closed issue, make a new issue to write a pep talk wiki page
  - [x] Include this as an Action Item:
    ```
    - [ ] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)
    ```   

### Potential solutions [draft]

**Comment by ExperimentsInHonesty** [comment]
Employers often hire people who don't know a specific language if you are able to communicate on resume and during hiring process, that you are willing to get up to speed on a new language, because many concepts are similar enough across languages.

**Comment by chrismenke45** [comment]
ETA: 6/2 EOD
Availability: 8am-12pm weekdays

**Comment by chrismenke45** [comment]
Issue #4756 created. Still a draft.

**Comment by chrismenke45** [comment]
Issue #4756 ready for review

**Comment by chrismenke45** [comment]
- Issue #4756 ready for prioritization
