### ISSUE TITLE
Integrate Donation Circle Component with Join Us Donate include

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4544]
### Dependency
- [x] #3983 
- [x] #4263

### Overview

We need to integrate the Donation Circle Component with the Join Us Donate include so that we have a consistent presentation of that component across the site.  

### Details

- The display of functional text within an image is not WCAG compliant and so the Donation Circle graphic has been replaced with an HTML/CSS component.  
- In this issue, the newly implemented Donation Circles HTML component will be integrated into the Join Us Donate card include and styles will be updated as necessary so that the appearance of the Join Us page is maintained in both mobile and desktop views.   

### Action Items
- [x] The new Donation CIrcles HTML component is located at `_includes/donation/donation-circles.html` and will replace the graphic `/assets/images/join-us/donation-graphic.svg`.   In `_includes/join-donate-card.html` replace the corresponding `<img>` tag with the liquid tag `{% include 'filename' %}` where 'filename' is relative to the `_includes` folder.  
- [x] The SCSS for styling the new component is located at `_sass/components/_donate-components.scss`.  Update scss classes as needed so that the component styles are independent of the target pages, and the appearance of the modified Join Us page matches the appearance of the current page, at both mobile and desktop screen sizes.  
- [x] Changes to `_includes/donation/donation-circles.html` may be necessary, for instance adding ID or classes for the purpose of targeting styles.  

#### Merge Team
- [x] In Epic #4492, check off the dependency under "Creating/Integrating New Issues".  If all of the dependencies under that heading have been merged, then release dependencies on all the issues listed under "Clean Up". 

### Resources/Instructions
- HfLA Join Us Page: [webpage](https://hackforla.org/join) and [html](https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html)
- wiki page [Standardized Components](https://github.com/hackforla/website/wiki/Standardized-Components)
- This issue is part of the Epic #4492
- [Liquid](https://jekyllrb.com/docs/liquid/) in Jekyll

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe Overall, good job writing this issue! Please change the following:

- [x] In the Overview, you said the "animated donation gif", which is a little confusing to me. Are the donation circles supposed to be animated? Also, I thought the donation circles were supposed to be in HTML/SCSS not a gif? Please clarify.
- [x] I'm a little confused about the `design to implement in the new component image` because the words in the image you provided and the words in the Requirement section don't match. Please clarify if necessary once Bonnie answers your question: <https://github.com/hackforla/website/issues/4263#issuecomment-1515487035>.

**Comment by roslynwythe** [comment]
> @roslynwythe Overall, good job writing this issue! Please change the following:
> 
> * [  ] In the Overview, you said the "animated donation gif", which is a little confusing to me. Are the donation circles supposed to be animated? Also, I thought the donation circles were supposed to be in HTML/SCSS not a gif? Please clarify.

**@JessicaLucindaCheng You're right, I'm starting to get confused between the issues.  The design in this issue is not animated and it is not a graphic, it is pure HTML/CSS.**  Thank you very much for bringing this to my attention.   

> * [  ] I'm a little confused about the `design to implement in the new component image` because the words in the image you provided and the words in the Requirement section don't match. Please clarify if necessary once Bonnie answers your question: [Create Donation Circle Component and Integrate with Donate Page  #4263 (comment)](https://github.com/hackforla/website/issues/4263#issuecomment-1515487035).

**Since the component will have already been created by the time this issue is taken up, there is no need for the text under Requirements or the screenshot, so I've deleted those.**

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe LGTM! Thanks for making the changes.

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by jenny-alexander** [comment]
Availability: 05/24 to 05/26 11:00 a.m. - 2:00 p.m.
ETA: 06/26 5:00 PM DST
