### ISSUE TITLE
Program-Areas: Images for Project Cards Overlap Corners of Parent Element

### ISSUE THREAD

**Issue by Adastros** [hackforla/website#4551]
### Overview

As developers, we want to ensure that child images within elements do not overlap parts of the parent element. On the program-areas page, we need to fix the images in the project cards to prevent them from overlapping the corners of the parent element.

#### Current State
<details>

<summary>Up close Screenshot - Jobs for Hope</summary>

![image](https://user-images.githubusercontent.com/48114590/233815616-2a168b2b-d536-4c1e-aed5-dabe8ec2ca1c.png)

</details>

<details>

<summary>Up close Screenshot - Spare</summary>

![image](https://user-images.githubusercontent.com/48114590/233815699-a9feae33-b4f4-4bee-9841-a16abb891a16.png)

</details>

#### Future State

<details>

<summary>Up close Screenshot - Jobs for Hope</summary>

![image](https://user-images.githubusercontent.com/48114590/233815872-c26419de-7306-45b5-932d-7acbc3222056.png)

</details>

<details>

<summary>Up close Screenshot - Spare</summary>

![image](https://user-images.githubusercontent.com/48114590/233815899-c7c54214-4edd-4d38-a01c-d125ea4079a5.png)

</details>

### Action Items

- [x] Update the styling for the project cards so that the images don't overlap the corners of the parent element
- [x] Test your updates and verify that all project cards on the program-areas page don't exhibit the issue

### Resources/Instructions

- [Program Areas Page](https://www.hackforla.org/program-areas)
- [Reference the Program Areas Figma Wire Frame](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464-0&t=YltnTrogQNxFO74V-0)

**Comment by se7en-illa** [comment]
Availability: M-F 12:00 - 8:00pm ET
ETA: EOD 5/2/23

**Comment by roslynwythe** [comment]
Hi @se7en-illa please leave an update using the outline presented in the comments, or if you do not wish to continue work on this project, please let us know.

**Comment by Adastros** [comment]
Removing @se7en-illa due to inactivity and moving issue back to prioritized backlog.

**Comment by JpadillaCoding** [comment]
i. Availability: wednesday-friday 8am-8pm CT, saturday-sunday 5pm-5am CT
II. ETA: saturday.

**Comment by JpadillaCoding** [comment]
I have a blocker, the css changes I make aren't reflecting on my local host using docker. Here's what I've done. 
-Testing out that I have the right div selected by making solid red borders
-ran docker-compose up 
-open up localhost:4000 (I can see the website)
-on inspect, the changes I make aren't reflecting or on the website

Things I've attempted:
-ran the local host with VsCode extension live reload(wasn't very helpful because of liquid)
-make other divs border red

I may have a misunderstanding on how Docker works or have set something up wrong.

**Comment by JpadillaCoding** [comment]
1. Progress: complete. Waiting on merge
2. Blockers: none
3. Availability: sunday 2pm-5am
4. ETA: complete
