### ISSUE TITLE
Events: Fix Second Paragraph of Events Page to Prevent Text from Appearing Under Double Arrows

### ISSUE THREAD

**Issue by Adastros** [hackforla/website#4552]
### Overview

As developers, we want to ensure that text on the website matches the Figma wire frame and isn't overflowing into unintended areas. We need to update the styling for the second paragraph on the Events page to prevent it from appearing under the double arrows.

### Details

<details>

<summary>Current State - Image</summary>

![image](https://user-images.githubusercontent.com/48114590/233815406-53b4930f-fbbc-4107-b369-88e92925f2a5.png)

</details>

<details>

<summary>Current State - GIF</summary>

![GIF](https://user-images.githubusercontent.com/48114590/233815023-0a92d403-00f6-4a70-9849-4facfb9db5e2.gif)

</details>

<details>

<summary>Future State - Desktop View Screenshot</summary>

![image](https://user-images.githubusercontent.com/48114590/233815181-dcd1c766-0d04-4924-a341-43a21c6767d3.png)

</details>

<details>

<summary>Future State - Mobile View Screenshot</summary>

<img src="https://user-images.githubusercontent.com/48114590/235588296-1753feef-59c9-4f1e-9ed7-15fe146af416.png" width=200px>

</details>

### Action Items

- [x] Update the styling for the second paragraph so that the text doesn't appear under the double arrows at all breakpoints
- [x] Test the changes at various viewport widths and verify that that there aren't any unintended side effects due to the changes

### Resources/Instructions

- [Events Page](https://www.hackforla.org/events/)
- [Reference Events Page Figma Wire Frame](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=22656-129293&t=useljIOXWMdZ4wv1-0)
- [Reference _layout.scss for the breakpoints](https://github.com/hackforla/website/blob/gh-pages/_sass/variables/_layout.scss)

**Comment by ExperimentsInHonesty** [comment]
@Adastros I think the future state image needs to show the smallest viewport to show the words not appearing under the arrow.  Or am I missing something?

**Comment by Adastros** [comment]
Hi @ExperimentsInHonesty, you did not miss anything. I missed adding an image for the smallest viewport for the future state. I'll add it to this issue

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by graycodesnu** [comment]
Availability: Evenings 5/9-5/11
ETA: By 5/12

**Comment by graycodesnu** [comment]
Provide Update
1. Progress: I've made little progress, but know the files I need to target to resolve this issue.
2. Blockers: Was sick for most of last week until now. Otherwise, none code-wise yet.
4. Availability: Evenings 5/14-5/17
5. ETA: 5/17

**Comment by graycodesnu** [comment]
Removing myself from this issue, as I got personally busy and won't be able to finish. I also don't have much experience with Sass and want to learn more about it through my own projects vs. affecting HFLA code. 

For the next dev to pick this issue up: I believe header-container-content.html, _layout.scss, and/or _events.scss are the files that may need to be updated. They're all linked to the /events page.

**Comment by thedvo** [comment]
Availability: Evenings 5/30-6/2
ETA: 6/1

**Comment by thedvo** [comment]
i. Availability: 5/30-6/1 evenings after 4pm
ii. ETA: 6/1 latest
