### ISSUE TITLE
Fix  of display of filters on WINS page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4557]
### Overview
We need to restore the original "drop-down" Role and Team filter menus on the WINS page, which have changed due to recent updates to a shared SCSS file.  The original SCSS classes will be restored with new names and  the HTML will be updated accordingly. 

### Action Items
- [x] Checkout the` gh-pages` branch then run `git reset --hard 70288eaed010f0a996132113c96588e27c7ea2fa` in order to restore the original version of the SCSS file in the working directory tree.  
- [x] Make a copy of `_sass/elements/_dropdown_filters.scss` named `_sass/elements/_old_dropdown_filters.scss`
- [x] Restore the current `gh-pages` using `git pull upstream gh-pages` then create an issue branch
- [x] Add an `@import` statement to `_sass/main.scss` so that the new SCSS file is included in the site's CSS
- [x] In `_sass/elements/_old_dropdown_filters.scss`, prepend "old-" to the beginning of each class.  
- [x] Update the HTML in `_includes/ wins-filter-template.html` to reference class names with the "old-" prefix.
- [x] Using Docker, test the WINS page locally to ensure that its appearance matches the screenshots shown below in the Resources section at mobile and desktop screen widths, and that the filters are functional at mobile and desktop screen widths.  Check the Projects and Home Pages as well to ensure that the appearance and functionality of the Project filters has not changed.  

### Resources/Instructions
<details>
<summary>Original appearance of the WINS page (tablet/desktop screen widths)</summary>

![image](https://user-images.githubusercontent.com/5314153/234180595-4909e51e-b32e-4b90-896b-dcca37a90a70.png)

</details>
<details>
<summary>Original appearance of the WINS page (mobile screen width)</summary>

![image](https://user-images.githubusercontent.com/5314153/234190280-ff7c1e60-bd83-4e48-893f-e6f6d92d2b77.png)

</details>
<details>
<summary>Current appearance of the WINS page on page load (after PR# 4280) tablet/desktop screen widths</summary>

![image](https://user-images.githubusercontent.com/5314153/234187411-3b657a2f-2115-4cf0-bd49-f2e25a52d0b3.png)

</details>
<details>
<summary>Current appearance of the WINS page on page load (after PR# 4280) mobile screen widths</summary>

![image](https://user-images.githubusercontent.com/5314153/234190746-ff7cc915-3583-418d-8635-9977cd380126.png)

</details>

- SCSS classes for styling the drop down menus are stored in `_sass/elements/_dropdown_filters.scss` 
- HTML markup for the drop down menus is stored in `_includes/wins-page/wins-filter-template.html`
- WINS page [live](http://hackforla.org/wins) [ | on GitHub code repository](https://hackforla.slack.com/archives/C0271FFEV0E/p1682243133731619)
- [Projects page](https://hackforla.org/projects)
- Changes to the original SCSS classes can be found in #4280

**Comment by Josiah-O** [comment]
I am reviewing this.

**Comment by ExperimentsInHonesty** [comment]
@Josiah-O in can't be moved to the prioritized backlog because it didn't have a milestone and it is time sensitive and didnt get put in the proper place in the prioritized backlog.

**Comment by Josiah-O** [comment]
@ExperimentsInHonesty Thanks for the update and correction.

**Comment by Josiah-O** [comment]
> @Josiah-O in can't be moved to the prioritized backlog because it didn't have a milestone and it is time sensitive and didnt get put in the proper place in the prioritized backlog.

Thanks for the update and correction.

**Comment by Jaretzbalba** [comment]
Availability: Weekdays 10 - 12 pm
ETA: EOD 5/4
