### ISSUE TITLE
ER from TLDL: Separate labeling for Technologies chip

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4562]
TLDL stands for Task List Dev Leads.

### Emergent Requirement - Problem
**Issue Description**
- Currently, as of writing this ER, when a technology or language is chosen, the red chip is named "Technologies:".
<img width="251" alt="chip-technologies" src="https://user-images.githubusercontent.com/31293603/234139018-6dfde7e4-e9af-41b9-8bd1-bc3f31b038fe.png">

- Make an issue: When choosing any language from the tech/lang filter, the chip name should appear as “Language:” with the language on the [hackforla.org/projects](http://hackforla.org/projects) page. If a technology is chosen, the chip name should appear as "Technology:" with the technology.
- The issue made from this ER will have a Dependency section with the issue written from this #4563.

### Who was involved
- @JessicaLucindaCheng
- `@SAUMILDHANKAR`   

### What happens if this is not addressed
The chip names will say "Technologies:" when a language or technology is chosen. This may be confusing to some visitors to our site.

### Resources
https://www.hackforla.org/projects/

### Recommended Action Items
- [ ] Search and check 
  - [ ] If an open issue exists that addresses this ER
  - [ ] If a closed issue exists that has already addressed this ER
- [ ] If an open issue doesn't exist and this ER wasn't already fixed by a closed issue, make a new issue 

### Potential solutions [draft]

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by JessicaLucindaCheng** [comment]
@Hritik1503 
In order to work on an issue, you need to be a member of Hack for LA. (There are no fees to join.) Please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.

**Comment by christinaor** [comment]
Availability: Wed 5/10
ETA: 10pm EST

**Comment by ExperimentsInHonesty** [comment]
@christinaor Thank you for making the issues.  @roslynwythe is looking at them now.  I am going to close this ER as complete.

**Comment by ExperimentsInHonesty** [comment]
- This issue that got made from this ER is here: https://github.com/hackforla/website/issues/4648
