### ISSUE TITLE
ER from TLDL: Chip label from plural to singular

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4563]
TLDL stands for Task List Dev Leads.

### Emergent Requirement - Problem
**Issue Description**
- Make an issue to rename all the labels on the search chips to be singular: Technology instead of Technologies and Program instead of Programs on the [hackforla.org/projects](http://hackforla.org/projects) page
- Currently, it looks like this:
  <img width="233" alt="chip-plural-filter-label" src="https://user-images.githubusercontent.com/31293603/234140699-2d3a90bb-29b3-41e0-88d4-80f950a5d861.png">

### Who was involved
- @JessicaLucindaCheng
- `@SAUMILDHANKAR`   

### What happens if this is not addressed
The chips will be labeled with the plural of the word (i.e. Programs, Technologies). This could be confusing since only one filter item is listed on each chip.

### Resources
- http://hackforla.org/projects

### Recommended Action Items
- [x] Search and check 
  - [x] If an open issue exists that addresses this ER
  - [x] If a closed issue exists that has already addressed this ER
- [x] If an open issue doesn't exist and this ER wasn't already fixed by a closed issue, make a new issue 

### Special notes
This issue will interact with the programming of the filter, so its either a medium or large issue because it requires the person to identify how the programming works and how it will be affected by the change before changing.

### Potential solutions [draft]

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by ExperimentsInHonesty** [comment]
@Hritik1503, we have an onboarding process for new developers.  Please see https://github.com/hackforla/website#contributing

**Comment by christinaor** [comment]
Availability: Wednesday 5/10
ETA: 10pm EST

**Comment by christinaor** [comment]
- I created a new issue to address this ER: #4647
