### ISSUE TITLE
Integrate the "In-Kind" component with the Join Us page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4565]
### Dependency
- [x] #4457

### Overview
We need to incorporate the new "In-Kind" component with the Join Us page, in order to provide a consistent appearance of donation-related elements across the site.  

### Details

1. The Join Us page currently includes a heading "How to help us continue to do Impactful Work" which appears after the "Donation Circles" and is depicted in Resources under the heading "Current Appearance".   The HTML is contained in `_includes/join-donate-card.html`.  
2. Replace the heading "How to help us continue to do Impactful Work" along with the unordered list beneath it with the heading "Provide In-Kind Software & Services" followed by the "In-Kind" component.  The desired appearance is shown in Resources under the heading "Final Appearance".  
3. Changes to the HTML and CSS layout are required, in order to center the "Donation Circles", the heading "Provide In-Kind Software & Services", and the "In-Kind" components within the entire width of the card.  That is, these elements must be removed from their current div/row placement in the grid, and should be placed in new div/rows that spans both columns of the grid so they are centered in the card.  

### Action Items
- [x] Open the files `_includes/join-donate-card.html` and `_sass\components\_join-us.scss`.  Move the "Donation Circles" (`div.donate-components-items`) into a new div (row), then modify the SCSS so that the "Donation circles" component is centered within the entire width of the card
- [x] Remove the heading ""How to help us continue to do Impactful Work" along with the `<ul>` beneath it.  
- [x] Below the "Donation Circles", add a new div (row), containing the heading "Provide In-Kind Software & Services" (centered) then reference the "In-Kind" component using the liquid tag 
```
{% include 'filename /donation/in-kind.html %}
```
- [x] The "Donation Circles" element, along with the heading "Provide In-Kind Software & Services" and the "In-Kind" component should all be centered within the entire width of the card, however the paragraph text within the In-Kind component should remain left-justified.  If necessary, html elements can be added to the "In-Kind" component and CSS classes specific to the "In-Kind" component can be added to `_sass/components/_donate-components.scss`.  If either the component or component styles are modified, ensure that the appearance of the Donate page is unchanged.  

#### Merge Team
- [ ] In Epic #4492, check off the dependency under "Creating/Integrating New Components" then release the dependency on #4455, and move that issue to `New Issue Approval` with `Ready for Prioritization` label

### Resources/Instructions
<details><summary>Current Appearance</summary>

![image](https://github.com/hackforla/website/assets/5314153/19e5b90c-8fb1-4397-89ae-9a02454ea6f8)

</details> 

<details><summary>Final appearance - center the "Donation Circles" and "Provide In-Kind Software & Services" sections within the card sections</summary>

![image](https://github.com/hackforla/website/assets/5314153/4bee40ab-fae8-4fc2-b88d-51addff28a1f)

</details> 

- HfLA Join Us Page: [webpage](https://hackforla.org/join) and [html](https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html)
- "In-Kind" component [HTML](https://github.com/hackforla/website/blob/gh-pages/_includes/donation/in-kind.html)
- The "In-Kind" component was developed in Issue #4457
- [Donate Card - Join Us Page version](https://github.com/hackforla/website/blob/gh-pages/_includes/join-donate-card.html)
- [HfLA Donate Page](https://hackforla.org/donate) 
- This issue is part of the Epic #4492

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe if this issue will change the look of the page, then a screenshot should be be provided of the current and future states.  If the changes will not result in a visual change, then please add that info to the issue.

**Comment by JpadillaCoding** [comment]
i. Availability: friday-sun 5pm-5am
ii. ETA: sunday 8pm
