### ISSUE TITLE
Review Inactive Members

### ISSUE THREAD

**Issue by chrismenke45** [hackforla/website#4567]
**Inactive Members:**

cnk
benrempel
mmogri
RyanCahela
frankstepanski
jqg123
glenflorendo
HiThereImCam
aricforrest
angelenelm
DonaldBrower
averdin2
mchavezm
greylaw89
luiderek
BrianCodes33
Steph0088
traycn
juliansmith0
anteroa
abuna1985
giroz
angietechcafe
TroyMalaki
jond34
NamanhTran
riddle015
jessdvdv
aalieu
geedtd
brianf4
GLRJr
DwightDiesmo
A-BMT02
anthonysim
akibrhast
stellaaparkk
ethant3
jnmrles
Mattre7
fernandoqueue
abenipa3
gold-o
ysjiang18
erniep278
mdhailwood1
arghmatey
poorvi4
alan-zambrano
ldaws003
elpen84
JasonY188
sena-ji
Pauljsyi
rolzar
Unity7
usaboo
JohnJBarrett22
braguda
gdtzn17
MicahBear
Lalla22
chrisfoose
patrickohh
codessi
h3nry-m
AzaniaBG
1anya1
ojafero
its-chowtime
rdpfeifle
shantanushende
skarakaya1
robertestrada
Requiem-of-Zero
hang-justin
JackRichman
christina245
scorbz9
lopezpedres
HackforLABot
chelseybeck
jenjen26
StephenTheDev1001
sonalinajera
scarter31191
trishajjohnson
jbialkin98
alexandrastubbs
booyouon
daniellex0
AaronoKwok
maryjng
jpandh
abdiaz2018
qiqicodes
edeneault
luke-karis
linds-fonnes
bfirestone23
vickiychung
SZwerling
pattshreds
JijiTheCreator
alexeysergeev-cm
ememercy21
JimGeist
nicolettedmabeza
sydneywalcoff
nathan944
Zhu-Joseph
adrian-zaragoza
Gorck1416
lytravis
Satenik-Ba
troywzhu
pdimaano
Johnnie007
GRISONRF
neevliberman
Richey24
ericvennemeyer
Georgema20
Emmettlsc
Abrosss
attali-david
eodero
harshitasao
ktlevesque19
Carlos-A-P
ahoang94
mgodoy2023
anonymousanemone
bzzz-coding
Hector-Torres000
chrismenke45
JasonUranta
andyarensman
Josiah-O
tunglinn
KayodeAlabi
greg-nice
JayBarbanel
seantokuzo
kyrakwak
lindseyindev
elizabethhonest
elvisEspinozaN
AnyaStewart
gstemmann
iilashi
juleanrod
PMKnight
royalbai
jch1013
Stephen-Parent
summerharveyux
KBWells77
vanessavun
Claudiahamilton-png
erinzz
wiltsai
tamalatrinh
dionw412
hangjoyce
DeitchDustin
mccormackstudio
jlu9d2
pjpatel021
cwvivianlin
Benji-Montgomery
matt-arofin
varyad
carolemlago
vmaineng
Khadijahibidapo
phuongv8
sherririllingux
callmelazarus
DmitriiTsy
PeterSYoo
ychang49265
jojochen25
lilyarj
esantiano
palomasoltys
Olanrewaju-Ak
jyaymie
EmilyTat
oliviaywangn
Alsuang
RobenusW
michaelmagen
hellorachelschwartz
olivioso
LilyLuo001
srandolph2
AsherEngelberg
clayton1111
raswani2023
shimahoush
alice-milmac
mariareeves
kpmunnelly
nehasyed97
JolleenI
MatthewBozin
str-xjua24
Suman2795
arora-aryan
hpweisberg
GitPeebles
neonPurple
ccortega2023
vivian9w
Thinking-Panda
anjolaaoluwa
vraer
yeskatr
myceey69

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by chrismenke45** [comment]
This issue was accidentally created while reviewing PR #4545.  I just closed it because it is not required here.
