### ISSUE TITLE
ER: Compile a list of projects with broken links on their page

### ISSUE THREAD

**Issue by bootcamp-brian** [hackforla/website#4568]
### Emergent Requirement - Problem
On a number of pages for the individual projects (example: [https://www.hackforla.org/projects/work-for-la](https://www.hackforla.org/projects/work-for-la)) have links in the "Project Overview" and "Resources" cards to the sites for that project that take you to an error page.
<details>
  <summary>The error page that shows up for Work for LA project:</summary>
    
  ![site cannot be reached error](https://user-images.githubusercontent.com/113788952/234721270-fd12c54c-2a5f-41ff-810f-124b862bfb9d.png)

</details>

We need to put together a list of these projects so that we can address the issue and decide what to do about these broken links.

### Issue you discovered this emergent requirement in
- Was not working on an issue at the time of discovery, just browsing the site.

### Date discovered 
April 26, 2023

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@bootcamp-brian 

### What happens if this is not addressed
We will have links that do not work on the website and that would make the organization look less professional.

### Resources
- [Hack for LA projects page](https://www.hackforla.org/projects/)
<details>
  <summary>Visual example of broken link locations:</summary>
    
  ![broken-link-locations](https://user-images.githubusercontent.com/113788952/234722535-f785e27a-e584-42b9-9a89-5293abcf84f3.png)

</details>

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
- First create an issue to find all the broken links and put a list of the projects with them together and deliver that to leadership. Then write another issue to create additional issues to remove the links while leadership investigates why those websites are not working and what, if anything, should be done about those project pages.

**Comment by jdingeman** [comment]
Hey @bootcamp-brian, if you know of more than just Work for LA's links that are broken, this could be an epic. Did you notice any others by chance or was it just the Work for LA project?

#### Possible Issue Plan
1. Audit issue to check that all links on each project page are working and link to what is expected.
2. Epic issue (if necessary) that holds all issues for each link that is not working to either remove or correct (somehow)
    - Dependency is the audit issue
3. Each issue can be made into a good first issue front end with explicit instructions

**Comment by bootcamp-brian** [comment]
@jdingeman Yeah, there were a couple more I noticed. The Engage project and the HelloGOV ones don't work either. I also just noticed that the site link is also on their cards on [the projects page](https://www.hackforla.org/projects/) too.

**Comment by drakenguyen4000** [comment]
ETA:  5/3/23
Availability: M-F 6pm - 8pm

**Comment by ExperimentsInHonesty** [comment]
- #4594 was created, but the potential solutions draft was only 1/2 correct...  Adding this to the dev agenda to discuss.

The First part is correct
> First create an issue to find all the broken links and put a list of the projects with them together and deliver that to leadership.

~The second part is overreaching.  We don't compound bugs by changing code.  We find out why the bug is happening, and then we fix that or make new issues to fix.  Each project should have its own investigation and resolution in a separate issue.~
>Then write another issue to create additional issues to remove the links while leadership investigates why those websites are not working and what, if anything, should be done about those project pages.~

**Comment by ExperimentsInHonesty** [comment]
@bootcamp-brian @drakenguyen4000 I miss read the issues. So ignore the part I put in strike through above.  I have reopened the issue that @drakenguyen4000 made and revised it.
