### ISSUE TITLE
Fix SDG image grid on About Us page to render in Firefox

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4574]
### Overview
As developers we need to modify the CSS styles applied to the SDG image grid in the Sustainability section of the About Us page, so that layout renders correctly in the Firefox browser.  

### Action Items
- [x] Refer to the screenshots in the Resources section for a comparison of the appearance of the SDG image grid in the Firefox browser versus the appearance of the same elements in the Chrome browser.  Note that some images do not render in the Firefox browser. 
- [x] Open the HTML for the SDG image grid layout at [_includes/about-page/about-card-sustainability.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-sustainability.html) and the SCSS at [_sass/components/_about.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_about.scss)
- [x] Resolve any ambiguous or incorrect styles in the CSS grid layout, so that the appearance of the SDG image grid in Firefox matches the appearance in Chrome.  
- [x] If it is not possible to create a consistent cross-browser appearance using the CSS grid layout mechanism, implement the same design using a different layout mechanism.  

### Resources/Instructions
[MDN: CSS Grid Layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout)
[Figma Design - About Us page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=17652-136588&t=GcTOgclyRrXUrH5)
About Us page: [live](https://hackforla.org/about) | [GitHub](https://github.com/hackforla/website/blob/gh-pages/pages/about.html)
[About Us Sustainability Card Include](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-sustainability.html)
- This issue was created as a result of #4572

**Comment by EdASalazar** [comment]
Wed-Friday 10 am - 6 pm
4 hours a day. 
Sat-Sunday Noon - 4 pm
ETA EOD Thursday

**Comment by EdASalazar** [comment]
I was able to get the Docker up and running and see where the issue is. Tomorrow, 4/4/23, I'll start working on the CSS. If I can't resolve the issue on my own I'll log into the office hours.

**Comment by EdASalazar** [comment]
I think I figured out the issue. Here is a similar [issue](https://stackoverflow.com/questions/41667881/flexbox-items-not-displaying-correctly-on-firefox).  Essentially it has to do with how Chrome and Firefox render the "justify-item: stretch". 

Chrome will give the images in the grid a default height but Firefox doesn't. I think this causes the images in Firefox to "Stretch" outside of the bounds of the container. 

We could either remove the "justify-item: stretch" from CSS. This doesn't seem to affect the appearance of the page in Chrome and makes both Firefox and Chrome render the same. (At least as my eyes can tell.)

We can also add a height to the images. This seems the like the better solution. A height of 140px seems to work. 

Going with defining the height for the images. Will discuss with a lead if removing "justify-item: stretch" is a better solution. I'm not completely sure if the "stretch" is necessary.
