### ISSUE TITLE
Remove credit for unused solidarity svg

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4578]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
Currently, the website credits have an item for the solidarity-pana.svg in [donate.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/donate.yml), however this image is no longer used anywhere in the site. We need to remove the credit so that we don't have a credit for a file that is not actually used.

### Action Items
- [x] In your local IDE, navigate to `_data/internal/credits`
- [x] Delete `donate.yml`
- [x] Using Docker, check that the Credits page remains the same in mobile, tablet, and desktop views as on the current website 

### Resources/Instructions
- ER associated with this issue: https://github.com/hackforla/website/issues/4531
- [Credits page](https://www.hackforla.org/credits/)

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by jenny-alexander** [comment]
Availability: Will work on this Wed May 10 2023.
ETA: Wed May 10 2023.

**Comment by ExperimentsInHonesty** [comment]
I just read this issue. Not sure how it got past my screen originally and made it into the prioritized backlog, but this issue is about two separate things.  Its about removing an image file and about removing a yml file.  Adding to dev/pm agenda

**Comment by jenny-alexander** [comment]
- @ExperimentsInHonesty - The issue for removal of the issue file is #4579

**Comment by ExperimentsInHonesty** [comment]
@jenny-alexander Thanks for clearing that up.  I see what happened there.
