### ISSUE TITLE
Delete unused solidarity svg

### ISSUE THREAD

**Issue by jdingeman** [hackforla/website#4579]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
Currently, the website credits have an item for the [solidarity-pana.svg](https://github.com/hackforla/website/blob/gh-pages/assets/images/donate/solidarity-pana.svg), however this image is no longer used anywhere in the site. We need to delete this image so that we don't have extraneous assets in our codebase.

### Action Items
- [x] In your local IDE, navigate to `assets/images/donate`
- [x] Delete `solidarity-pana.svg`

### Resources/Instructions
- ER associated with this issue: https://github.com/hackforla/website/issues/4531
- [Credits page](https://www.hackforla.org/credits/)

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by Mayank2808sharma** [comment]
Availability: 4PM IST
ETA: within 30 minutes

**Comment by Mayank2808sharma** [comment]
How should I raise PR?
should I just raise it or have to do something more?
