### ISSUE TITLE
Fix of Languages/Technologies Filters on Projects and Homepage

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4587]
### Overview
We need to fix a bug affecting the project filters on the Projects and Home pages so that website visitors are provided accurate results from their selections.

### Details
On the [Projects](https://www.hackforla.org/projects/) and [Homepage](https://www.hackforla.org/#), the Project list can be filtered via various selections. It can be seen that some projects will not show up when they should when the "Languages/Technologies" filter is used. For example, if someone is searching for projects that match a.) the Program Area "Diversity / Equity / Inclusion" and that also b.) use CSS, the [Write for All](https://www.hackforla.org/projects/writeforall) project will not be displayed even though it meets these two criteria. See the following screenshot for an example. 
<details><summary>Example Screenshot</summary>
<p>

![Screenshot-2023-04-30-211338](https://user-images.githubusercontent.com/40799239/235406659-b052d71a-a929-4c5b-94e6-b907f6e82cbc.gif)

</p>
</details> 

### Action Items
- [x] Determine which projects this bug affects (so far, it appears to affect at least the [Write for All](https://www.hackforla.org/projects/writeforall) and [BallotNav](https://www.hackforla.org/projects/ballot-nav) projects and likely more)
- [x] Confirm that the bug coincides with projects that do not have "Technologies" listed
- [x] Note: In the [/current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js) file, the filter code includes on lines 27-28 `else if (filterName == 'technologies' )` then use the `filterTitle = 'languages / technologies'`. From these lines, it appears that if a project card doesn't have the technologies attribute, then it is ignored. 
- [x] Change code as needed, then confirm with Docker that filter is working correctly.

### Resources/Instructions
- ER associated with issue: #4389 
- [Projects](https://www.hackforla.org/projects/) and [Homepage](https://www.hackforla.org/#)
- [/current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- [/projects](https://github.com/hackforla/website/tree/gh-pages/_projects) folder

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by t-will-gillis** [comment]
Hello @Hritik1503 - thank you for your interest. In order to work on an issue you first need to be a member of Hack for LA. Please feel free to check out the [getting started](https://www.hackforla.org/getting-started) page for information on how to join.

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis @hackforla/website-merge The overview on this issue is not clear enough.  Move the current overview text to details and write a new overview that uses this format
We need to do X for Y reason
It should be short and easy to understand

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge @t-will-gillis I don't think this is a small issue.  Usually small issues are prescriptive but they have larger changes.  Medium issues define the problem and define a solution without telling the person how to code it. Large issues specify a problem and the person gets to research and propose a solution or solutions.

**Comment by t-will-gillis** [comment]
Hi @ExperimentsInHonesty - I had originally changed this to Complexity: Small from Complexity: Medium because I incorrectly thought this issue would only take a half hour, and that the minor bug to be fixed was found exactly at line 27 in ‘current-projects.js.’ 

I spent a few hours today to trace which lines of code were causing the bug, and in the process found a couple more bugs elsewhere. I will do a PR for this issue ~and create a new issue/ER for the other bugs.~

Update 2/28/24: I believe that the bugs I mentioned previously were minor, and that I incorporated fixes into the PR.

**Comment by t-will-gillis** [comment]
Available: 5/14 evening
ETA: 5/14 e.o.d.
