### ISSUE TITLE
ER: Possible duplicate audit wiki issues

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4589]
### Emergent Requirement - Problem
I noticed there might be possible duplicate issues about auditing the wiki

### Issue you discovered this emergent requirement in
- #1992 
- #2676 

### Date discovered 
2023-05-01

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@JessicaLucindaCheng 

### What happens if this is not addressed
We may have duplicate issues for auditing the wiki and the result is the exact same work being done twice.

### Recommended Action Items
- [ ] Read through each issue and determine if they are duplicates
  - [ ] If they are duplicates, 
    - [ ] Determine which issue to keep open and close the other one with a comment
    - [ ] If necessary, move any relevant info from the issue you closed to the one that stayed open

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by JessicaLucindaCheng** [comment]
@Hritik1503
In order to work on an issue, you need to be a member of Hack for LA. (There are no fees to join.) Please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.

**Comment by ExperimentsInHonesty** [comment]
- closed https://github.com/hackforla/website/issues/1992, which leaves https://github.com/hackforla/website/issues/2676 open
