### ISSUE TITLE
Improvements to GHA 'Add Update' Label

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4590]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As developers, we need to ensure that the GHA involving the `To Update !` label creates clear comments and directions for the team to follow.

### Action Items
- [x] In the [update-instructions-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/update-instructions-template.md) file, add an additional sentence after '...3) put up a request for assistance on the #hfla-site channel.' 

```
Please note that including your questions in the issue comments - along with screenshots, if applicable- will help us to help you. [Here](https://github.com/hackforla/website/issues/1619#issuecomment-897315561) and [here](https://github.com/hackforla/website/issues/1908#issuecomment-877908152) are examples of well-formed questions.
```
- [x] Testing GitHub Actions: After making the changes, confirm that the GitHub action works as intended. The hyperlinks for 'Here' and 'here' above may need to be edited.
- [x] Merge Team and Leads: Release dependency on https://github.com/hackforla/website/issues/1976 . May need to rewrite links that have expired since issue was written.

Note that you might want to do something outside the scope of the above pseudo-code. If so, be sure to leave comments in your PR or on this issue that justifies your reasoning. If you feel you need guidance, be sure to reach out! We cannot foresee whether this issue is solvable, or what hard decisions have to be made, but we would love to hear and help you!

### Resources/Instructions
- [schedule-fri-0700.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-fri-0700.yml)
- [add-label.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/add-label.js)
- [update-instructions-template.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/update-instructions-template.md)

Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)

#### Additional resources:
[Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
[Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)
[GitHub GraphQL](https://docs.github.com/en/graphql)

**Comment by angieyan** [comment]
Availability: 8pm-9pm May 1; 10-11:30am May 2
ETA: EOD May 3, 23

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by angieyan** [comment]
@Hritik1503 you should assign yourself from the top right gear of assignees.
