### ISSUE TITLE
Remove blank roles from WINS filter options

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4592]
### Overview
As developers we need to prevent the display of blank role filter options (checkboxes) on the WINS page, so that the page does not appear as if something is broken or missing.   

### Details
The problem is depicted in the screenshot in the Resources section below.  The filter options are generated dynamically from the displayed WINS data.   The code should be modified so that even if a WINS submission with a blank role is displayed, it will not cause a blank role option checkbox to be displayed.   

### Action Items
- [x] Update the JavaScript in `assets/js/wins.js` so that blank role filter options (checkboxes) are not displayed. 

### Resources/Instructions
<details><summary>Screenshot depicting a blank role checkbox</summary>

![image](https://user-images.githubusercontent.com/5314153/235605760-d02f2ad5-1dd2-4e04-9742-00df4f8c7b99.png)

</details> 

- [JavaScript for WINS page - GitHub](https://github.com/hackforla/website/blob/gh-pages/assets/js/wins.js)
- WINS page [GitHub](https://github.com/hackforla/website/blob/gh-pages/pages/wins/wins.html) | [webpage](https://hackforla.org/wins)

**Comment by Hritik1503** [comment]
I am interested to work on this issue under Quine. So please assign me this task to me.

**Comment by roslynwythe** [comment]
@Hritik1503 You must be a member of Hack for LA to be assigned to our issues.  If you would like to join Hack for LA, please see https://www.hackforla.org/getting-started.

**Comment by pdimaano** [comment]
Availability: Weekday evenings
ETA: 5/19/23
