### ISSUE TITLE
Fix projects with broken site links

### ISSUE THREAD

**Issue by drakenguyen4000** [hackforla/website#4594]
### Overview
We need to remove links from project.md files where their links no longer resolve and we don't know if the owners are going to fix them.  So that we don't have broken links from our site.

#### Details  
We have a number of links on the cards project cards (Projects page, Homepage and in the individual projects' pages) that don't resolve to websites anymore.

Some of the projects are not owned by HfLA (completed projects on this list)
And other projects used resources from volunteers that HfLA had no control over (on hold projects on this list).

Example: 
On https://www.hackforla.org/projects/work-for-la there are two links to [Site](http://www.workfor.la/) which should resolve to workfor.la but gives the following error page:
<img src="https://user-images.githubusercontent.com/25872681/235823880-04e7d2fb-db0d-4a3e-81de-ff2a61ff1a8c.png"  width=300px>

### Action Items
- [x] Create a template and issue making level 1 issue for issues to comment out the site link for the following projects.  The template should have a `complexity: small` label
   - [x] WorkForLA 
      - https://www.hackforla.org/projects/work-for-la 
   - [x] HelloGOV
      - https://www.hackforla.org/projects/hellogov
   - [x] Jobs for Hope
      - https://www.hackforla.org/projects/jobs-for-hope
- [x] Create an issue to comment the site link & test link in the following project
   - [x] Engage
      - https://www.hackforla.org/projects/engage

### Resources/Instructions
Associated ER:  #4568

**Comment by drakenguyen4000** [comment]
Availability: 5pm-8pm M-F PST

**Comment by ExperimentsInHonesty** [comment]
@drakenguyen4000 ~This issue will not be approved.~

~I read the ER and notice the instructions are in draft, not approved.  We do not want to hide any of the page, there was a bug (not sure what) that was keeping the pages from displaying (temporarily) but it has been fixed now.  I can see the pages.  I am closing this issue.~

**Comment by ExperimentsInHonesty** [comment]
@drakenguyen4000 I have rewritten the issue and reopened it.

**Comment by arfgit** [comment]
i. Availability: M-F 12pm - 5pm
ii. ETA: EOD Friday 06/02

**Comment by arfgit** [comment]
Progress: Haven't started yet
Blockers: None
Availability: M-F 12pm - 5pm
ETA: EOD Friday 06/02

**Comment by arfgit** [comment]
Progress: Almost done
Blockers: None
Availability: M-F 12pm - 5pm
ETA: EOD Tuesday 06/13

**Comment by ExperimentsInHonesty** [comment]
@arfgit It turns out that this issue had a small label, and we have fixed that.  It might have been bigger than you expected.  If you are having trouble with this issue, please reach out to the merge team.  In the meantime, please give us an update.

**Comment by arfgit** [comment]
Progress: Almost done
Blockers: None
Availability: M-F 12pm - 5pm
ETA: EOD Tuesday 06/27
Note: Sorry for the delay I have been busy with work, but can finish this up for tomorrow

**Comment by arfgit** [comment]
Progress: Issues have been created.
Blockers: None
Availability: N/A
ETA: Completed.

Issues can be found at: https://github.com/hackforla/website/issues/4923 and https://github.com/hackforla/website/issues/4924

**Comment by ExperimentsInHonesty** [comment]
@arfgit good job making those issues.  See the notes I left you on them.
