### ISSUE TITLE
Change input validation settings on WINS form to prevent invalid URL entries

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4595]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
As developers we need to update input validation settings on the LinkedIn URL and GitHub URL fields of the "Share your WINS" form, so that invalid URLs are not accepted.     

### Action Items
- [x] On your personal or your development Google Drive, create a new test Google Form with two questions: GitHub URL and LinkedIn URL.  In the Response settings of the Form, link to a new spreadsheet for storing responses.  
- [x] For both the LinkedIn and GitHub URL fields, open the question settings, click the arrow next to Text, and select Regular Expression.  Provide a case-insensitive Regular Expression for matching each specific expected URL.
  - [x] For both URLs, the protocol portion of the URL should match `http://`, `https://`, or it could be blank.
  - [x] For the GitHub URL, the remainder of the URL should start with `www.github.com/` or `github.com/`
  - [x] For the LinkedIn URL, the remainder of the URL should start with `www.linkedIn.com/in/` or `linkedIn.com/in/`
  - [x] Both URLs should end with the profile descriptor, optionally followed by `/`
- [x] Test by submitting the form with various inputs.  Verify that only the URL patterns described above can be submitted and that the responses in the test Sheet are correct.   
- [x] Configure draft [error messages](https://support.google.com/docs/answer/3378864?hl=en)  to guide users who have entered invalid responses
   - [ ] Get sign off from product on the error messages.
- [x] Demonstrate the regular expressions for dev lead. 

#### Merge Team/Dev Leads
- [x] Before closing this issue, 
   - [x] Update the production Google Form with the regular expressions and error messages for the GitHub and LinkedIn URLs.  
   - [x] Test form validation with various inputs.  Submit a test form, then verify the submitted data for the Github and Linked URLS in the response Sheet matches the current formats.  Find the automatically generated GitHub issue with title "Review Needed - New Wins Form Submission", add the "Ignore:Test" label, make a comment and close as Not Planned.  

### Resources/Instructions
- [Share Your WINS form](https://docs.google.com/forms/d/e/1FAIpQLSeTiFjtxKbYgrJHAdFUovXlE55BdwwUQ9NePOXRY2q-h-w1tg/viewform)
- This issue was created as a result of #4185
- Google helpfile on form regex and error messages https://support.google.com/docs/answer/3378864?hl=en

**Comment by roslynwythe** [comment]
@JessicaLucindaCheng @jdingeman On this issue, I'm not sure how specific we want to make the regular expression.  Should the LinkedIn URL have to start with "https://www.linkedin.com/in/"  and the GitHub URL have to start with "https://github.com/" ? And once I've incorporated your input into the issue, do you think it is ready for product?

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe 

> @JessicaLucindaCheng @jdingeman On this issue, I'm not sure how specific we want to make the regular expression. Should the LinkedIn URL have to start with "https://www.linkedin.com/in/" and the GitHub URL have to start with "https://github.com/" ? And once I've incorporated your input into the issue, do you think it is ready for product?

I agree with the LinkedIn URL having to start with "https://www.linkedin.com/in/" and the GitHub URL having to start with "https://github.com/". I have a few questions:
- What if they put in "http://" instead of "https://"? 
- What happens if they don't put in the https or http part, such as "www.linkedin.com/in/" or "github.com"?

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe There should be some more steps.  This does not need to be tested on our actual or even a copy of our form... that will make testing it take longer.  Please add steps where they create a new test form and then get the regex working on that, and signed off on before they get access to our form.

**Comment by roslynwythe** [comment]
@JessicaLucindaCheng Thank you for making some great points!  I modified the Action Items so that the protocol portion of the URL can be 'http://', 'https://' or blank, and the `www` before the domain name is optional as well.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe re the http vs https
How is the page code interpreting and or rationalizing the urls being provided. (e.g., Is it taking everything with http and transforming it into https? etc.)

What I am getting at is, that we should clean the url string before it gets to the data store, if at all possible. So if we want to store just the username for  inkedin and github that is ok.  if we want to store the whole string, then the string should be formatted with https: without the www even though linkedin allows either with or without the www.

- https://www.linkedin.com/in/bonnieawolfe
- https://linkedin.com/in/bonnieawolfe

But at the same time, we don't want to make it hard for the person entering the info, so we might accept all that you propose

- http://linkedin.com/in/bonnieawolfe
- https://linkedin.com/in/bonnieawolfe
- http://www.linkedin.com/in/bonnieawolfe
- https://linkedin.com/in/bonnieawolfe

And then we would need a script after the fact that cleans the data turning it into either (my preference being just the username)

- https://linkedin.com/in/bonnieawolfe
- bonnieawolfe

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe there should be an action item to draft an [error message](https://support.google.com/docs/answer/3378864?hl=en) after the validation is working and then bring it to a team meeting to dog food it with other devs with test cases.

**Comment by roslynwythe** [comment]
- This issue to add validation to the wins form can proceed.  In addition see  #4671 which includes issues to update the code behind the wins-form (response) spreadsheet to add new fields to hold only the GitHub/LinkedIn profile, and issues to update wins.js to reconstruct URLs based on the profile.

**Comment by brianf4** [comment]
**Availability**: Sunday - Friday 10 am - 8 pm
**ETA**: Friday - EOD

**Comment by brianf4** [comment]
Here is the Google Form with the input validation settings: https://forms.gle/vvcsr9ijgYBBFAsQ7

As well as the Google Sheet for the responses that went through/allowed: https://docs.google.com/spreadsheets/d/1eMUxEMOC-Py0twk-CkEPNDQLoiqgLzpOU42f3LETL9Q/edit?usp=sharing

**Regex expression for both input**:

- ^([Hh][Tt][Tt][Pp][Ss]?://)?([Ww][Ww][Ww]\.)?[Gg][Ii][Tt][Hh][Uu][Bb]\.[Cc][Oo][Mm]/[A-Za-z0-9-]+/?$
- ^([Hh][Tt][Tt][Pp][Ss]?://)?([Ww][Ww][Ww]\.)?[Ll][Ii][Nn][Kk][Ee][Dd][Ii][Nn]\.[Cc][Oo][Mm]/[Ii][Nn]/[A-Za-z0-9-]+/?$

**Valid GitHub URL examples**:

- https://github.com/fakeuser123/
- https://www.github.com/johndoe-123/
- http://github.com/username_with-dashes/
- https://github.com/camelCaseUser/
- https://github.com/brianf4/
- https://github.com/Asalz20/

**Valid LinkedIn URL examples**:

- https://www.linkedin.com/in/fake-user-123/
- https://linkedin.com/in/janedoe-456/
- http://linkedin.com/in/some_user/
- https://www.linkedin.com/in/camelCaseUser/
- https://www.linkedin.com/in/brian-fuentes-18ab62182/
- https://www.linkedin.com/in/alex-salazar-dev/
- https://linkedin.com/in/alex-salazar-dev/

**Invalid GitHub URL examples**:

- https://github.com/.git
- https://www.github.com/.test
- http://github.com/
- https://www.example.com/
- ftp://github.com/user123/

**Invalid LinkedIn URL examples**:
- https://linkedin.com/in/.test
- https://www.linkedin.com/in/.git
- http://linkedin.com/in/
- https://www.example.com/
- ftp://linkedin.com/in/user123/

**Error Message**: "Invalid GitHub/LinkedIn URL"

<img width="776" alt="Screenshot 2023-10-03 at 12 19 28 PM" src="https://github.com/hackforla/website/assets/28875356/c3b1d617-8831-4dd9-a686-dc740f4b8197">

**Comment by roslynwythe** [comment]
Thanks @brianf4 -  This looks good to me but I'd like to give the merge team a few days to test the form as well.

**Comment by t-will-gillis** [comment]
@brianf4 @roslynwythe I tried different variations and tried to think of an exception to trip up the regex. So far everything looks good to me.

**Comment by roslynwythe** [comment]
Thank you @brianf4 for great work on this issue.  The regular expressions you created will help to ensure that our Wins form recieves valid URLs.
