### ISSUE TITLE
Update a credit file for composite images

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4606]
### Overview
We need to add some info to the credit for an image because it is a composite image. We do this so that we give credit to all the image authors.  

### Details
This will require creating separate credits for each image

#### Details
The three images involved are 
- [Diversity, Equity, Inclusion](https://github.com/hackforla/website/blob/feature-homepage-launch/assets/images/program-areas/diversity-equity-inclusion.png) - composite image
- [Team Hands Middle Photo](https://burst.shopify.com/photos/team-hands-middle?q=matthew+henry+diversity) (the main image)
- ["Progress" Pride Flag](https://progress.gay/pages/terms-of-use) (the image we are using in the composite image)

On the redesigned homepage on the feature-homepage-launch branch, the Diversity, Equity, Inclusion image is a composite image.  The original image was altered by removing images from the laptop cover, and then adding the "Progress" pride flag. However, on the Credits page, the credit for Diversity, Equity, Inclusion only provides credit to one image's artist and doesn't provide credit to the other artist.  Here is what It looks like now
<details>
<summary>Current credit</summary>

<img src="https://user-images.githubusercontent.com/31293603/222930633-16709c05-81e6-4a7a-b1f0-86621ac0e511.png" width=300px>
</details>

<details>
We will be replacing the current credit with these credit files. 

<summary>Proposed future credit files</summary>

1 composite image - filename `diversity-equity-inclusion-composite.yml` 
```
---
title: Diversity, Equity, Inclusion
title-link: https://github.com/hackforla/website/blob/gh-pages/_data/internal/credits/diversity-equity-inclusion-composite.yml
content-type: image
used-in: Homepage
provider: HfLA composite image
image-url: /assets/images/program-areas/diversity-equity-inclusion.png
provider-link: (Replace with link to this file, so that people can see the comments)
# If an image was altered, please give the name of the HfLA designer that altered the image
compiled-by: Kristine Eudey
# If an image was altered, please give the LinkedIn URL of the HfLA designer that altered the image
compiled-by-link: https://www.linkedin.com/in/kristine-eudey/
alt: '4 people doing Ready Break! over laptop with progress pride flag'
# alteration: 'edited to remove images from the laptop cover, and then add the "Progress" pride flag'
# This image is a composite image.  If this image is used, credit must be provided to the author of each of the images used in the composite as well as the person who altered it.  
# See the following credits: 
#   main image: [Replace with the url to the credits yml file for the main image]
#   secondary image: [Replace with the urls to the credits yml file for the secondary image]
---
```

2 main image - filename '`diversity-equity-inclusion-main.yml`
```
---
title: Team Hands Middle Photo
title-link: https://burst.shopify.com/photos/team-hands-middle?q=matthew+henry+diversity
content-type: image
used-in: Diversity, Equity, Inclusion (HfLA composite image)
artist: Matthew Henry
provider: Burst
provider-link: https://burst.shopify.com/
image-url: 
alt: '4 people doing Ready Break! over laptop'
---
```

3 secondary image - filename `diversity-equity-inclusion-secondary.yml`
```
---
title: "Progress" Pride Flag
title-link: https://progress.gay/pages/terms-of-use
content-type: image
used-in: Diversity, Equity, Inclusion (HfLA composite image)
artist: Daniel Quasar
provider: Progress.gay
provider-link: https://progress.gay/
image-url: 
alt: '"Progress" Pride Flag'
---
```
</details>

### Action Items
- [x] Work on this issue will be merged into hackforla/feature-homepage-launch.  For information about working on a feature branch, see https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch
- [x] Based on "Proposed future credit files" above, create three new credits files in the `_data/internal/credits/` folder, using the specified filenames
- [x] Delete `_data/internal/credits/diversity-equity-inclusion.yml`
- [x] Update `pages/credits.html` to display the new variables `compiled-by` and `compiled-by-link` 
- [x] Obtain the images for the "main" and "secondary" images from the dev lead, and add those to the folder `assets/images/credits`
- [x] Edit `diversity-equity-inclusion-main.yml`, populating the `image-url` field with a relative url to the "main" image
- [x] Edit `diversity-equity-inclusion-secondary.yml`, populating the `image-url` field with a relative url to the "secondary" image 

### Resources/Instructions
1. [Credits page](https://www.hackforla.org/credits/)
2. file on the homepage branch: https://github.com/hackforla/website/blob/feature-homepage-launch/_data/internal/credits/diversity-equity-inclusion.yml

**Comment by ExperimentsInHonesty** [comment]
talk to merge team to discuss potential options

In the future there may be altered images. Options

1. We can make a new section for that
OR
1. We can indicate an image is a Composite where it says Provider
    1. We can then put every other image in the regular credits, and where it says Used In, we can reference the name of the composite image and its actual provider.

**Comment by ExperimentsInHonesty** [comment]
<details>
<summary>Original wording of this issue</summary>

### Overview
We need to add some info to the credit for an image because it is a composite image. We do this so that we give credit to all the image authors.

#### Details
We have never done this before, so it might take some working till we figure out how it will actually look once implemented and if that is going to work.  For instance, 
- the Proposed future credit wording below has "&" which was added to make it shorter and clearer than using the word "and", but might now work well with our code
[Diversity, Equity, Inclusion](https://burst.shopify.com/photos/team-hands-middle?q=matthew+henry+diversity) & ["Progress" Pride Flag](https://progress.gay/pages/terms-of-use)
- part of the title has quotes that are supposed to be rendered as quotes, they are part of the name.
["Progress" Pride Flag](https://progress.gay/pages/terms-of-use)

On the redesigned homepage on the feature-homepage-launch branch, the Diversity, Equity, Inclusion image is a composite image. However, on the Credits page, the credit for Diversity, Equity, Inclusion only provides credit to one image's artist and doesn't provide credit to the other artist.  Here is what It looks like now
<details>
<summary>Current credit</summary>

<img src="https://user-images.githubusercontent.com/31293603/222930633-16709c05-81e6-4a7a-b1f0-86621ac0e511.png" width=300px>
</details>

<details>
<summary>Proposed future credit wording</summary>

**Name:** [Diversity, Equity, Inclusion](https://burst.shopify.com/photos/team-hands-middle?q=matthew+henry+diversity) & ["Progress" Pride Flag](https://progress.gay/pages/terms-of-use)
**Used in:** Homepage
**Artist:** Matthew Henry &  Daniel Quasar
**Provider:** [Burst](https://burst.shopify.com/) & [Progress.gay](https://progress.gay/)
**Altered by:** Kristine Eudey
</details>


### Action Items
[ready for dev lead to add some action items and details about working on a feature branch]
- [ ] Create or update a page for the wiki that explains how to format credits on composite images.


### Resources/Instructions
1. [Credits page](https://www.hackforla.org/credits/)
2. file on the homepage branch: https://github.com/hackforla/website/blob/feature-homepage-launch/_data/internal/credits/diversity-equity-inclusion.yml
</details>

We decided that any image that is a composite of 2 or more images, gets the following treatment

I need to rewrite this issue above to have these instructions and see the  the related issue with more notes: https://github.com/hackforla/website/issues/4607

1 composite image
Name: Civic Tech Infrastructure
Used in: Homepage
Compiled by: [YOUR NAME](YOUR LINKED OR PORTFOLIO LINK)
Provider: HfLA composite image

2 main image
Name: [man looking at marketing analytics](https://unsplash.com/photos/unRkg2jH1j0)
Used in: Civic Tech Infrastructure (composite image)
Artist: Adeolu Eletu
Provider: [Unsplash](https://unsplash.com/)

3 Hammer & Wrench
Name:
Used in: Civic Tech Infrastructure composite image
Artist:
Provider:

4 Saw
Name:
Used in: Civic Tech Infrastructure composite image
Artist:
Provider:

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge I have re written the issue above.  It needs a review and some action items to be written.  I think because its the first ever composite image credit solution and its on the homepage branch, we should not try to break this into smaller issues.

**Comment by roslynwythe** [comment]
Note [comment](https://github.com/hackforla/website/issues/4607#issuecomment-1541143884) for a method of aligning the text in the credits

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty I created issue #5895.  Please advise re: next step.

**Comment by A-Wu5** [comment]
1) Availability: ~7-9 PM M-F
2) ETA: Nov. 24

**Comment by A-Wu5** [comment]
1. Not much, was out for the past two weeks
2. N/A
3. Sat/Sun 9-5
4. Dec. 5

**Comment by A-Wu5** [comment]
1. Replaced the diversity-equity-inclusion.yml file with the 3 files requested above.
2. I'm having trouble with docker; It's giving me an error about a key it can't find, so I can't see what the website locally
3. M-F 3-5PM
4. Dec. 15

**Comment by A-Wu5** [comment]
1. Fixing items suggested in the pull request #6026.
2. N/A
3. M-F 1PM - 3PM
4. 1/25/24

**Comment by jphamtv** [comment]
Progress Pride Flag by Daniel Quasar:

![Progress Pride Flag by Daniel Quasar](https://github.com/hackforla/website/assets/4952258/23031d6d-f57d-4ea3-847b-6e15fb08c611)

Style Guide https://cdn.shopify.com/s/files/1/0589/1676/5845/files/HowToUse-ProgressPrideFlag-DanielQuasar.pdf?v=1629073782

**Comment by ExperimentsInHonesty** [comment]
This issue had the wrong orientation on the images provided to the developer, so we have resolved that on issues
- #6286 
- #6296
