### ISSUE TITLE
Update Slack link on Project Profile: Access the Data

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4642]
### Overview
As developers, we need to ensure our project's details are up to date on the HackforLA website. We need to correct the Slack link for AJ Price on the [Access the Data Project Page](https://www.hackforla.org/projects/access-the-data).

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the [access-the-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md) file, then find the `leadership` variable and the values for AJ Price.  
- [x] Update the Slack link for AJPrice from 
`slack: 'https://hackforla.slack.com/team/D02USE0EPSS'`
to 
`slack: 'https://hackforla.slack.com/team/U02UZ5BK8UB'`

### Resources
- [Hackforla.org Website markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md)
- [HFLA wiki on project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [How to find Slack IDs](https://github.com/hackforla/admin/wiki/Slack:-Find-a-Slack-ID)
- This issue is a result of ER #4660

**Comment by 93Belen** [comment]
Availability: Tuesday, Thursday and Sunday from 7am to 5pm
ETA: Tuesday by 6pm
