### ISSUE TITLE
Update chip labels from plural to singular

### ISSUE THREAD

**Issue by christinaor** [hackforla/website#4647]
### Dependency
- [x] #4960

### Overview
Currently, chip label prefixes for the "Technologies" and "Tools" filter groups are pluralized even if only one filter item is listed under the label. This can be confusing to users, so we want to update the chip label prefixes to "Technology" and "Tool"

### Action Items

- [x] Check the current state of search chip labels under Applied Filters on the [Projects page](https://www.hackforla.org/projects/).
  - [x] Apply some of the filters to see how the current chips appear under Applied Filters.
- [x] Explore `assets/js/current-projects.js` and understand how the programming of the filters and chips work.  
  - [x] Change the chip label prefix "Technologies" to "Technology" 
  - [x] Change the chip label prefix "Tools" to "Tool"
  - [x] Using docker, test changes on both [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js) and [current-projects-check.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects-check.js)
- [x] Release dependency on #4648 

### Resources/Instructions

-  Chip labels can be found on the [Projects page](http://hackforla.org/projects)
- [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- [current-projects-check.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects-check.js)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)
- See associated ER for this issue: #4563

**Comment by Gauravvpnd** [comment]
Hey, I want to work on this issue can you please explain me a little?

**Comment by christinaor** [comment]
Hi @Gauravvpnd ! These issues are open to Hack for LA developers. Please visit the [Hack for LA website](https://www.hackforla.org/) to find out how you can contribute.

**Comment by ExperimentsInHonesty** [comment]
The program areas chip will remain `Programs:`

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty I added a dependency and modified the Action Items to reflect the fact that after #4960 is completed, projects and projects-check will both share the code file `current-projects.js` and updated the issue so it changes the "Technologies" prefix to "Technology" and the "Tools" prefix to "Tool"

**Comment by LukeLowrey2** [comment]
Availability: Friday Jan 12 & Saturday Jan 13 9am-11am, Monday Jan 15 & Tuesday Jan 16 12pm-2pm

ETA: Wednesday Jan 17 EOD

**Comment by LukeLowrey2** [comment]
Update: Understanding code 

Availability: Sunday Jan 21 9am-11am, Monday Jan 22 11am-2pm, Tuesday Jan 23 10am-12pm

ETA: Tuesday Jan 23 EOD

**Comment by LukeLowrey2** [comment]
Update: I'm removing myself from this issue because I got personally busy and can't finish. There isn't any progress I can give to future assignees on this issue.

**Comment by irais-valenzuela** [comment]
Availability for this week: Monday, Tuesday, Thursday 11am - 4pm
My estimated ETA for completing this issue: Thursday

**Comment by irais-valenzuela** [comment]
Hello, I have a blocker more like a question. I've updated the chip label names (the variable filterName) in the filterTagComponent function in assests/js/currentProjects.js from "technologies" and "tools" to singular names of "technology" and "tool". The change is also reflected in the UI as well. 

Here's the code for it: 
   `function filterTagComponent(filterName,filterValue){
      // made a copy of filterName 
      let copyOfFilterName = filterName
      // copyOfFilterName getting reasssigned to either "tool" or "technology" using it later within span tag
      if (copyOfFilterName === "tools") copyOfFilterName = "tool"
      else if (copyOfFilterName === "technologies") copyOfFilterName = "technology"
      return `<div
                  data-filter='${filterName},${filterValue}'
                  class='filter-tag'
              >
                  <span tabindex="0" role="button" aria-label="Remove ${filterValue} Filter">
                  ${filterName === "looking" ? "Role" : copyOfFilterName.length > 0 ? copyOfFilterName : filterName}: ${filterValue} 
                  </span>
              </div>`
  }`
  
I'm curious if I also have to change the data-filter attribute in the div to also have the singular label name of either "technology" or "tool" or if I should leave that as the plural form of technology and tool. The branch I'm working on is called "plural-to-singular-chip-labels-4647" if needed. 
  
 Any assistance is appreciated. Thank you.

**Comment by roslynwythe** [comment]
@irais-valenzuela Assuming you have tested the filters and everything works fine, you don't have to change the data-filter attribute.  But thanks for checking!

**Comment by irais-valenzuela** [comment]
Hi, I'm trying to finish testing my changes on my localhost but I'm unable to start the server. I keep getting errors like this: 
`> [+] Running 1/0
>  ✔ Container hfla_site  Created                                                                                                                                       0.0s 
> Attaching to hfla_site
> hfla_site  | ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-musl]
> hfla_site  | Configuration file: /srv/jekyll/_config.yml
> hfla_site  |            Cleaner: Removing /srv/jekyll/_site...
> hfla_site  |            Cleaner: Removing ./.jekyll-metadata...
> hfla_site  |            Cleaner: Nothing to do for .sass-cache.
> hfla_site  | ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux-musl]
> hfla_site  | Configuration file: _config.yml
> hfla_site  | Configuration file: _config.docker.yml
> hfla_site  |             Source: .
> hfla_site  |        Destination: /srv/jekyll/_site
> hfla_site  |  Incremental build: enabled
> hfla_site  |       Generating... 
> hfla_site  |   Liquid Exception: Liquid syntax error (line 112): Tag '{% - for project in visible_projects -%}' was not properly terminated with regexp: /\%\}/ in assets/js/current-projects.js
> hfla_site  | jekyll 3.9.2 | Error:  Liquid syntax error (line 112): Tag '{% - for project in visible_projects -%}' was not properly terminated with regexp: /\%\}/
> hfla_site  | /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:132:in `raise_missing_tag_terminator': Liquid syntax error (line 112): Tag '{% - for project in visible_projects -%}' was not properly terminated with regexp: /\\%\\}/ (Liquid::SyntaxError)
> hfla_site  |    from /usr/gem/gems/liquid-4.0.3/lib/liquid/block_body.rb:24:in `parse'
> hfla_site  |    from /usr/gem/gems/liquid-4.0.3/lib/liquid/document.rb:10:in `parse'
> hfla_site  |    from /usr/gem/gems/liquid-4.0.3/lib/liquid/document.rb:5:in `parse'
> hfla_site  |    from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:132:in `parse'
> hfla_site  |    from /usr/gem/gems/liquid-4.0.3/lib/liquid/template.rb:116:in `parse'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:13:in `block in parse'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:49:in `measure_time'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/liquid_renderer/file.rb:12:in `parse'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:121:in `render_liquid'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:79:in `render_document'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/renderer.rb:62:in `run'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/site.rb:479:in `render_regenerated'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/site.rb:472:in `block in render_pages'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/site.rb:471:in `each'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/site.rb:471:in `render_pages'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/site.rb:192:in `render'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/site.rb:71:in `process'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/command.rb:28:in `process_site'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:65:in `build'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/build.rb:36:in `process'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `block in start'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `each'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:93:in `start'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/lib/jekyll/commands/serve.rb:75:in `block (2 levels) in init_with_program'
> hfla_site  |    from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
> hfla_site  |    from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
> hfla_site  |    from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
> hfla_site  |    from /usr/gem/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
> hfla_site  |    from /usr/gem/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
> hfla_site  |    from /usr/gem/gems/jekyll-3.9.2/exe/jekyll:15:in `<top (required)>'
>    from /usr/gem/bin/jekyll:25:in `load'
>    from /usr/gem/bin/jekyll:25:in `<main>'
> hfla_site exited with code 1
`

This is the main error:  Liquid Exception: Liquid syntax error (line 112): Tag '{% - for project in visible_projects -%}' was not properly terminated with regexp: /\%\}/ in assets/js/current-projects.js
Any assistance is appreciated. Thank you.

**Comment by irais-valenzuela** [comment]
Availability for this week: Thursday 1pm - 6pm, Friday 11am-4pm
My estimated ETA for completing this issue: Friday
