### ISSUE TITLE
Separate Technologies chip into Technology and Language chips

### ISSUE THREAD

**Issue by christinaor** [hackforla/website#4648]
### Dependency

- [x] #4647 
- [x] #6298 

### Overview
In the project page filters, we need to separate technologies from languages so that each technology or language will have their own "Technology" and "Language" chip label, respectively. This separation in filters will help avoid confusion for users when they are searching for projects on the Hack for LA website.

#### Details
- Currently, all Technology/Language filters chosen on the project page will render chips labeled as "Technology", even if the chosen filter points to a programming language (screenshot 1).
<details><summary>Screenshot 1 -  the current chip for a language</summary>
<p>
<img width="251" alt="chip-technologies" src="https://github.com/hackforla/website/assets/37763229/a1463774-fb83-4513-903b-b3ef8a1962cb">

</p>
</details> 

- The Language/Technology filter, will remain in its current form (see screenshot 2).  You are only changing the name on the chip when the item chosen is a Language.

<details><summary>Screenshot 2  -the Language/Technology filter</summary>
<p>

![image](https://github.com/hackforla/website/assets/37763229/90d083c2-191e-41a2-89e4-fadd05eb6969)

</p>
</details> 

### Action Items

- [x] Investigate `current-projects.js` and `current-projects-check.js` to understand the programming of the filters and how they are executing.
- [x] Fix the technology and language filters on the [Projects page](https://www.hackforla.org/projects/) so the labels are separated.
  - [x] Test that "Language" is rendered on the chip when a language is selected and "Technology" for a selected technology.

### Resources/Instructions

- Chip labels can be found on the [Projects page](http://hackforla.org/projects)
- [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)
- See associated ER for this issue: #4562

**Comment by christinaor** [comment]
- I created a new issue for this ER: #4562

**Comment by Gauravvpnd** [comment]
> 

Hey i want to work on this issue hope you assigned me this

**Comment by ExperimentsInHonesty** [comment]
@christinaor please add back in the images from the ER and make the details clearer.

For instance, when I read the issue, I had to go back to the ER to see that you were talking about if I choose Javacript and AWS they both show up as
Technologies: AWS
Technologies: Javascript

Instead of 
Technology: AWS
Language: Javascript

**Comment by christinaor** [comment]
Progress: Edited the issue so the issue is clearer and included the image from the ER. @ExperimentsInHonesty Let me know if it's still not clear enough though!
Blockers: N/A
Availability: Weekdays 8pm-10pm EST

**Comment by ExperimentsInHonesty** [comment]
@christinaor - yes, the update helped.  

FYI - I also updated the screenshot, now that the filters are singular.

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge I moved this out of the icebox and updated an image, please review.  If it's ready to prioritize, add the label please.

**Comment by luisitocanlas** [comment]
i. Availability: 3/8/24 ~ 3/15/24
ii. ETA: EOD 3/15/24
