### ISSUE TITLE
Update Resource Card logic to test resource names using case-insensitive matching

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4659]
### Overview
As developers, we need to modify the logic that generates project resource cards, in order to create robust code that will display the project resource icons properly even if the name of the GitHub resource is declared with an incorrect case in a project markdown file. 

### Details
The correct string to specify the GitHub resource in the front matter of a project markdown file is 
`- name: GitHub`  

The Resources section below includes a screenshot depicting the error that occurs when the resource name has incorrect case , for example, as 

`- name: Github`

In this issue the logic will be modified so that the icon and heading in the resource card section of each project page will be displayed in a consistent manner regardless of the case of the liquid `name` variable.  

### Action Items
- [x] Open a sample project markdown file, for example the [website project markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md) and locate the `links` array and the line `- name: GitHub` which assigns the value `GitHub` to the liquid `name` variable.
- [x] Open the file `_includes/resource-card.html` and read the HTML and liquid tags to understand how the liquid variable `name` is used to select the displayed svg icon and display the `GitHub` heading.   
- [x] Change the code so that regardless of case, if `name` matches `github`, the GitHub icon is displayed and the header text is transformed to `GitHub`.  
- [x] The GitHub resource name may have been corrected in all project files by the time this issue is addressed, so for local testing purposes it may be necessary to edit a project markdown file, entering a value of `name` with incorrect case, in order to confirm that the appearance of the resource section of the corresponding project webpage is correct.  Do not add any project file modifications to the commit.  

### For Reviewers/Merge Team
- [x] The GitHub resource name may have been corrected in all project files by the time this issue is addressed, so for local testing purposes it may be necessary to edit a project markdown file, entering a value of `name` with incorrect case, in order to confirm that the appearance of the resource section of the corresponding project webpage is correct.  

### Resources
<details><summary>GitHub resource card on a project page (incorrect icon)</summary>

![image](https://github.com/hackforla/website/assets/5314153/fc8a1b9e-908a-4b9b-b00d-9edea6ab0515)

</details> 
<details><summary>GitHub resource card on a project page (correct icon)</summary>

![image](https://github.com/hackforla/website/assets/5314153/fd64e92d-8479-4ea2-ad8d-fb3ff1702cda)

</details>

- [sample project markdown file - for the website project ](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)
- [sample project webpage - for the website project](https://www.hackforla.org/projects/website)
- [HFLA wiki on project.md files](https://github.com/hackforla/website/wiki/project.md-file-template)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [Liquid Conditional Tags](https://shopify.dev/docs/api/liquid/tags/conditional-tags)
- This is the code which reads the `links` array and renders the resource cards: [resource-card.html](https://github.com/hackforla/website/blob/gh-pages/_includes/resource-card.html)
- This issue was created as a result of #4660

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty an alternate solution to this problem would be to change the code in https://github.com/hackforla/website/blob/gh-pages/_includes/resource-card.html so that it uses a case-insensitive string comparison.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty - An alternative solution would be to simply update the [Access the Data project markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md) and change line 68 to  ` - name: GitHub`

Please advise if you would prefer that.

**Comment by ExperimentsInHonesty** [comment]
This issue will get revised to reflect that we are going to implement this solution to catch future wrongly capitalized references, but in the meantime we are going to make another smaller issue to fix it manually in the accessthedata.md file and the person working on this issue, should break it locally and then test their solution.

**Comment by EdASalazar** [comment]
I will have 3 hours a night W-F.
Saturday and Sunday I should have 4 hours to work on it.
Hopefully, I'll have the issue resolved by the next meeting on Tuesday the 30th.

**Comment by EdASalazar** [comment]
Made a branch and looking at the issue. I think I have it figured out. Going to work on it tomorrow. Hopefully it'll be done
