### ISSUE TITLE
Undebate hotfix. to looking for

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#466]
### Overview
Undebate has changed what they are looking for.

### Action Items
Update this field
- [ ] Looking for: Node, React, UI/UX, Marketing/Branding/Social Media

### Resources/Instructions
https://www.hackforla.org/projects/undebate
[/projects/undebate.md ](https://github.com/hackforla/website/blob/gh-pages/_projects/undebate.md)

**Comment by cnk** [comment]
These edits are already in place.
