### ISSUE TITLE
ER: Errors on the Access the Data project page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4660]
### Emergent Requirement - Problem
There are two errors in the Access the Data project data
- The Slack link for AJ Price is incorrect
- The icon for the GitHub resource is incorrect (see screenshot below under Resources)

### Issue you discovered this emergent requirement in
- #4566

### Date discovered 
5/3/23

### Did you have to do something temporarily
- [ ] YES
- [x ] NO

### Who was involved
@roslynwythe 

### What happens if this is not addressed
The Slack link for AJ Price is a bad link, and the icon for the GitHub resource is the generic "link" icon, which still works but it is a bit confusing and not consistent with the presentation of the GitHub resource on other project pages

### Resources
<details><summary>GitHub resource card on Access the Data page (incorrect icon)</summary>

![image](https://github.com/hackforla/website/assets/5314153/fc8a1b9e-908a-4b9b-b00d-9edea6ab0515)

</details> 
<details><summary>GitHub resource card on other project pages (correct icon)</summary>

![image](https://github.com/hackforla/website/assets/5314153/fd64e92d-8479-4ea2-ad8d-fb3ff1702cda)

</details>

### Recommended Action Items
- [ ] Make a new issue - #4642 and #4659
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
The incorrect Github icon is caused by the fact that access-the-data.md contains the markdown `- name: Github` however the code that uses the name property does a case-sensitive test for `name==GitHub`.  So we could either change the markdown to capitalize the 'h' or else change the code to do a case-insensitive test.

**Comment by ExperimentsInHonesty** [comment]
The issues have been resolved.  I am closing this ER
