### ISSUE TITLE
Change alt text to enable proper screen reader pronunciation of "Hack for LA"

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4669]
### Overview
As developers, we must ensure that the Hack for LA website is accessible to users of screen readers in order to achieve our goal of inclusivity.  In this issue, we will replace the value of the alt text for the website project image so that it will be pronounced correctly by screen readers.    

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the website project markdown file `_projects/website.md`, then find the `alt` variable.  
- [x] Change the value of the `alt` variable from
`Hackforla.org Website` 
to
`Hack for LA Site`
- [x] Do not modify any other instances of `hackforla.org`
- [x] Confirm the change in the browser on the [Hack for LA Current Projects Page](https://www.hackforla.org/projects) 

### Resources/Instructions
 
<details><summary>The Website Project Image on the Current Projects page (circled)</summary>

![image](https://github.com/hackforla/website/assets/5314153/c4be6cf4-dfdf-4efc-9f30-b235422ba33f)

</details> 

- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- [Hack for LA Website Project Markdown File](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)

**Comment by pushkar-2804** [comment]
I want to contribute @roslynwythe
I am in SSOC'23

**Comment by Mayank2808sharma** [comment]
Availability: Mon- Fri(9 Am to 5 PM)
ETA: within half a hour
