### ISSUE TITLE
Navigate to `.github/ISSUE_TEMPLATE/pre-work-template--dev.md`

### ISSUE THREAD

**Issue by DevRishiJain** [hackforla/website#4682]

**Comment by wanyuguan** [comment]
@DevRishiJain This issue has not been added to the project board and doesn't have a detailed description. The title doesn't provide us with enough information about what you plan to do with this issue. Please reply.

**Comment by roslynwythe** [comment]
@DevRishiJain it appears that this issue was created in error so we're closing it as not planned.
