### ISSUE TITLE
Update the GitHub resource name for the Access the Data Project

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4685]
### Overview
As developers we must correct the GitHub resource name in the Access the Data project file, so that the GitHub icon and heading are displayed correctly.  

### Action Items
- [x] Open the Access the Data project markdown file at `_projects/access-the-data.md` and  locate the `links` array and the line `- name: Github` which assigns the value `Github` to the liquid variable `name`   
- [x] Change 
`- name: Github` 
to 
`- name: GitHub`
- [x] To test the change locally, view the Resources section of the [Access the Data Project Page](https://www.hackforla.org/projects/access-the-data).  The GitHub resource should appear as depicted in the screenshot labelled "GitHub resource card on the Access the Data project page - correct"

### Resources/Instructions
<details><summary>GitHub resource card on the Access the Data project page - incorrect</summary>

![image](https://github.com/hackforla/website/assets/5314153/fc8a1b9e-908a-4b9b-b00d-9edea6ab0515)

</details> 
<details><summary>GitHub resource card on the Access the Data project page - correct</summary>

![image](https://github.com/hackforla/website/assets/5314153/fd64e92d-8479-4ea2-ad8d-fb3ff1702cda)

</details>

- [Access the Data project markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md)
- [Access the Data project webpage](https://www.hackforla.org/projects/access-the-data)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- This is the code which reads the `links` array and renders the resource cards: [resource-card.html](https://github.com/hackforla/website/blob/gh-pages/_includes/resource-card.html)
- This issue was created as a result of #4660

**Comment by AHP15** [comment]
Availability for this week: 6 hours
My estimated ETA for completing this issue: is 30 min

**Comment by one2code** [comment]
**Review ETA:**5/23/23
**Availability:** 4-5PM EST, 8-10PM EST on 5/23/23, and all day 5/24/23 if necessary.
