### ISSUE TITLE
Update the status of Design Systems project

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4687]
### Overview
We need to change the status of a project while it's on administrative hold so that new people joining Hack for LA don't try to look at its resources.

### Action Items
- [x] Open the Design Systems project markdown file at `_projects/design-systems.md` and change the status to On-Hold
- [x] Change 
`status: Active `
to 
`status: On-Hold `
- [x] To test the change locally, view the chip on the top of the Design Systems project page.

### Resources/Instructions
<details><summary>It currently looks like this</summary>

![image](https://github.com/hackforla/website/assets/37763229/e1ef0b9f-ee87-4095-bd3a-950e91ce9620)

</details> 
<details><summary>It should look like this</summary>

![image](https://github.com/hackforla/website/assets/37763229/1220e0aa-4ee9-430e-9efe-8229d9eb54d7)

</details>

- [Access the Data project markdown file](https://github.com/hackforla/website/blob/gh-pages/_projects/design-systems.md)
- [Access the Data project webpage](https://www.hackforla.org/projects/design-systems)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)

**Comment by 93Belen** [comment]
Availability: Thursday and Sunday from 7am to 6pm
ETA: 5/19/23 by 6pm
