### ISSUE TITLE
Website Element Removal: Project Team Meetings Page

### ISSUE THREAD

**Issue by agosmou** [hackforla/website#4699]
### Prerequisite

1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
Remove the COVID Notification banner as seen on https://www.hackforla.org/project-meetings
The element will be removed by removing the HTML and SCSS associated with it

#### Remove HTML
- [x] Navigate to /website/pages/project-meetings.html and delete lines 20-22
```
<div class='covid-notification-banner'>
    <p class='meetings-message'>All meetings are currently online due to COVID19.</p>
</div>
```

#### Remove SCSS
- [x] Navigate to /website/_sass/components/_project-meetings.scss and delete lines 1-15
```
.covid-notification-banner {
    background-color: $color-gold;
    width: 100%;
    display: flex;
    justify-content: center;
    align-content: center;

    p {
        text-align: center;
        font-weight: bold;
        margin: 0;
        padding: 15px 0;
    }
}
```

- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 3 in the Resources/Instructions section below)

### Resources/Instructions

1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/pages/project-meetings.html
2. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_sass/components/_project-meetings.scss
3. Webpage: https://www.hackforla.org/project-meetings

**Comment by DevRishiJain** [comment]
Availability: 5/25
ETA: EOD 5/25

**Comment by JessicaLucindaCheng** [comment]
Moving this back to QA because
1) This issue was taken out of the New Issue Approval, so it
  a) didn't get approval from a PM and 
  b) didn't get a milestone
2) It also has a `ready for dev lead` label on it, so it may not have even been reviewed/approved by a dev lead either.
3) The HackforLABot moved it to Done without QA because the issue was labeled incorrectly.
    - Explanation: 
      - The bot moved it correctly based on the "Feature: Refactor CSS" and "Feature: Refactor HTML" labels. 
      - However, this issue was labeled incorrectly because there are visual changes to the website, so the "Refactor" labels shouldn't have been used.
