### ISSUE TITLE
Update the "Our Projects" page Wire Frame in Figma to match recent updates 

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4703]
### Overview
We want our Figma design pages to accurately reflect the website and our website to accurately reproduce the visual framework of the Figma design pages. Several related issues have improved the appearance of the Projects filter feature, and we need to make sure these changes are reflected in the Figma pages.

### Action Items

- [ ] Review recent issues that changed the location of the Filters Sidebar (beginning #4753, #4769, #4770)
- [ ] Note that the search bar will be added in an upcoming issue (#4136)
- [ ] If needed, update the current Figma design to reflect the current site conditions

### Resources
- [HfLA Figma Design Pages](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?type=design&t=4cifcd4UZuBgGi4V-0)
- [HfLA Figma 'Our Projects'](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?type=design&node-id=24096-281035&t=VKusUEJkqxHM4Llw-0)
- [Projects](https://www.hackforla.org/projects)
- [Homepage](https://www.hackforla.org/)

**Comment by t-will-gillis** [comment]
Holding on this issue until [discrepancy per 4136 ](https://github.com/hackforla/website/issues/4136#issuecomment-1558599739) is resolved: PR 4694 and orig issue 4593 move the red filter label to top of project list to match behavior of REI pages, however this may not be the intent.

**Comment by wanyuguan** [comment]
@t-will-gillis This issue will need to be updated with details from #4593

**Comment by t-will-gillis** [comment]
It appears that Figma has already been updated since this issue was written. Closing this issue as Resolved.
