### ISSUE TITLE
ER: Update labels not applied on Open Issues with Closed PR

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4704]
### Emergent Requirement - Problem
Currently, when issues are linked to a PR, the bot no longer adds/ edits update labels (eg `To Update !` and `2 weeks inactive`). Normally this is not a problem since PRs get tracked well, but when a PR is closed this issue might no longer have any tracking.

### Issue you discovered this emergent requirement in
- #2065 

### Date discovered 
- 5/21/23

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@t-will-gillis 

### What happens if this is not addressed
There is the potential for the open issue to be untracked since the labels will no longer be updating.

### Resources
[add-label.js](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/add-label.js)

### Recommended Action Items
- [ ] Make a new issue
- [x] Discuss with team: This is definitely an 'edge case' and this may not be worth the effort to fix?
- [ ] Let a Team Lead know

### Potential solutions [draft]
- This might be solved by editing the [add-label.js](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/add-label.js) file.

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis We are going to fix this edge case.  So this ER can be turned into an issue

**Comment by t-will-gillis** [comment]
Closing this ER: new issue created [4839](https://github.com/hackforla/website/issues/4839).
