### ISSUE TITLE
Fix width of dropdown list on Wins page

### ISSUE THREAD

**Issue by cng008** [hackforla/website#4706]
### Overview
We need to adjust the width of the dropdown lists in the [Wins Page](https://www.hackforla.org/wins) so that it is aligned with the width of the input on desktop and mobile.

### Action Items

- [x] Locate the `_sass/elements/_old_dropdown_filters.scss` file
- [x] Change the width to `100%` for `ul.old-filter-list li ul`
- [x] Change the width to `100%` for `@media #{$bp-below-tablet}`
- [x] To test the change locally, open the drop-downs in the [Wins Page](https://www.hackforla.org/wins)

### Resources/Instructions
<details>
<summary>Wins page - desktop view BEFORE</summary>

![desktop-before](https://github.com/hackforla/website/assets/92824407/81a6497d-f131-40d1-96e2-cefa24d2165b)

</details>

<details>
<summary>Wins page - desktop view AFTER</summary>

![desktop-after](https://github.com/hackforla/website/assets/92824407/6d0aa398-4e27-4cd4-a07b-d4bdfb7ed4b7)

</details>

<details>

<summary>Wins page - mobile view BEFORE</summary>

![mobile-before](https://github.com/hackforla/website/assets/92824407/e3d6e1c1-7b92-4d8f-a128-901ab76064cf)

</details>

<details>

<summary>Wins page - mobile view AFTER</summary>

![mobile-after](https://github.com/hackforla/website/assets/92824407/e4749c21-689b-40ab-a3cf-49c8dc2b5daa)

</details>

- [Currently deployed Wins page](https://www.hackforla.org/wins)
- This issue was created as a result of #4705 
- #4608

**Comment by piwuxk** [comment]
Can you asign me this issue i would be able to fix this.

**Comment by rdhmdhl** [comment]
availability: 5-9pm weekdays, anytime on the weekends
ETA: tonight
