### ISSUE TITLE
fix blank list in drop down menu of 'role' in 'wins page'

### ISSUE THREAD

**Issue by ghost** [hackforla/website#4707]
### Overview

We need to remove the blank list in drop down menu of 'role' in 'wins page'.This affects the overall visual appearance and user experience of the website.

### Action Items

- [ ] Locate the required list
- [ ] Remove the blank list

### Resources/Instructions

- Wins page
https://www.hackforla.org/wins/?role=UX+Researcher+&+Lead+UX+Researcher

![Screenshot 2023-05-28 220637](https://github.com/hackforla/website/assets/131276821/0e5e9cee-0c77-45fc-96e2-50ef37983c55)

**Comment by vishnubansal001** [comment]
I want to work on this issue please assign this to me

**Comment by wanyuguan** [comment]
@piwuxk It looks like you have started this issue but forgot to add it to the project board, so I added it for you. Please don't forget to add the labels you need. 

I know you're still drafting this issue and probably planning to add a screenshot of the current problem. Screenshots make it easier for other developers to see and understand the problem.

**Comment by ghost** [comment]
@wanyuguan I added the screenshot of the issue.

**Comment by ExperimentsInHonesty** [comment]
- Hi @kr-piyush There is already an issue for this problem https://github.com/hackforla/website/issues/4592. So I will be closing this issue and adding a duplicate label
