### ISSUE TITLE
ER: Request for Update of Hack for LA's Current GHA's Documentation

### ISSUE THREAD

**Issue by karengcecena** [hackforla/website#4728]
### Emergent Requirement - Problem
- The current [Hack for LA's Current GHA's Documentation](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions) is missing a lot of the GHAs currently found in the website repository.
- I believe it would be beneficial to 1) organize the GHA to be in the same order as presented within the github-actions folder and also add the GHA that are missing. 

#### This is the current structure of the GHA Documentation: 

move-closed-issues
- sort-closed-issues.js

pr-instructions
- create-instructions.js
- post.comment.js

trigger-issue
- /add-missing-labels-to-issue
    - check-labels.js
    - post-labels-comment.js
- /add-preliminary-comment
    - check-label-preliminary-update.js
    - preliminary-update-comment.js

trigger-pr
- set-pr-labels.js

trigger-schedule
- /add-update-label-weekly
    - add-label.js
- /github-data
    - get-project-data.js
- /list-inactive-members
    - comment-issues.js
    - create-new-issue.js
    - get-list.js
- /trim-contributers
    - contributors-data.js

utils
- find-linked-issue.js
- obtain-labels.js

#### These are the current GitHub actions and what I think they correspond to: 

[add update label weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly)
* add-label.js in trigger-schedule/add-update-label-weekly

[github data](https://github.com/hackforla/website/wiki/GHA:-github-data)
* get-project-data.js in trigger-schedule/github-data
* I really like how this one stated the js folder first thing in the summary

[issue trigger](https://github.com/hackforla/website/wiki/GHA:-issue-trigger)
* uses obtain-labels.js in utils folder
* I think it is supposed to be about check-labels.js and post-labels-comment.js in trigger-issue/add-missing-labels-to-issue
    * I think the documentation could be a lot stronger/ more specific about each .js file

[lint-scss](https://github.com/hackforla/website/wiki/GHA:-lint-scss)
* it is part of .stylelintrc.json in https://github.com/hackforla/website/blob/gh-pages/.stylelintrc.json and is part of the [lint-scss.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/lint-scss.yml) file in workflow

[move closed issues](https://github.com/hackforla/website/wiki/GHA:-move-closed-issues)
* sort-closed-issues.js in move-closed-issues

[pr instructions](https://github.com/hackforla/website/wiki/GHA:-pr-instructions)
* create-instructions.js and post.comment.js in pr-instructions

[pull request trigger](https://github.com/hackforla/website/wiki/GHA:-pull-request-trigger)
* [pull-request-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/pull-request-trigger.yml) in workflow

[set pr labels](https://github.com/hackforla/website/wiki/GHA:-set-pr-labels)
* [set-pr-labels.yaml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/set-pr-labels.yaml) in workflow
* set-pr-labels.js in trigger-pr

[update team members](https://github.com/hackforla/website/wiki/GHA:-update-team-members) (NOT FOUND?)
* [update-team-members.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/update-team-members.yml) in workflow WHICH IS NOT FOUND
* https://github.com/hackforla/website/tree/gh-pages/github-actions/github-data WHICH IS NOT FOUND

[vrms data](https://github.com/hackforla/website/wiki/GHA:-vrms-data)
* [vrms-data.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/vrms-data.yml) in workflow
* https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json

[wr pr instructions](https://github.com/hackforla/website/wiki/GHA:-wr-pr-instructions)
* [wr-pr-instructions.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/wr-pr-instructions.yml) in workflow

[wr pull request trigger](https://github.com/hackforla/website/wiki/GHA:-wr-pull-request-trigger)
* [wr-pull-request-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/wr-pull-request-trigger.yml) in workflow

[wr set pr labels](https://github.com/hackforla/website/wiki/GHA:-wr-set-pr-labels)
* [wr-set-pr-labels.yaml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/wr-set-pr-labels.yaml) in workflow

Deprecated GHAs

[no-labels-template.md](https://github.com/hackforla/website/issues/2898)
* in trigger-issue/add-missing-labels-to-issue

#### That leaves these within github-actions without any sort of documentation: 

trigger-issue
- /add-preliminary-comment
    - check-label-preliminary-update.js
    - preliminary-update-comment.js

trigger-schedule
- /list-inactive-members
    - comment-issues.js
    - create-new-issue.js
    - get-list.js
- /trim-contributers
    - contributors-data.js

utils
- find-linked-issue.js

#### These are also In the Workflow Folder but not in the documentation: 
- [schedule-daily-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-daily-1100.yml)
- [schedule-fri-0700.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-fri-0700.yml)
- [schedule-monthly.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-monthly.yml)
- [schedule-thu-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-thu-1100.yml)

### Issue you discovered this emergent requirement in
- #4469 

### Date discovered 
- 04/20/2023

### Did you have to do something temporarily
- [X] YES
- [ ] NO

### Who was involved
- n/a

### What happens if this is not addressed
- A lot of time is wasted with missing issues on the documentation. I had to go to the website code specifically and search through each GHA to try and complete my issue. I feel like it would be more beneficial for everyone to have the documentation be up to date with some re-organization to make it easily understandable. 

### Resources
- n/a

### Recommended Action Items
- [X] Make a new issue
- [X] Discuss with team
- [X] Let a Team Lead know

### Potential solutions [draft]

Create an issue that has someone: 
#### 1) Order the GHA Documentation - I think an order that would make sense could be something like: 

/gitub-actions 
- [move closed issues](https://github.com/hackforla/website/wiki/GHA:-move-closed-issues)
- [pr instructions](https://github.com/hackforla/website/wiki/GHA:-pr-instructions)
- [issue trigger](https://github.com/hackforla/website/wiki/GHA:-issue-trigger) (maybe rename to trigger-issue)
- [set pr labels](https://github.com/hackforla/website/wiki/GHA:-set-pr-labels) (maybe rename to trigger-pr)
- /trigger-schedule (create an umbrella title to put these two under based on their organization in the code)
    - [add update label weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly)
    - [github data](https://github.com/hackforla/website/wiki/GHA:-github-data)

/.github/workflows
- [lint-scss](https://github.com/hackforla/website/wiki/GHA:-lint-scss)
- [pull request trigger](https://github.com/hackforla/website/wiki/GHA:-pull-request-trigger)
- [vrms data](https://github.com/hackforla/website/wiki/GHA:-vrms-data)
- [wr pr instructions](https://github.com/hackforla/website/wiki/GHA:-wr-pr-instructions)
- [wr pull request trigger](https://github.com/hackforla/website/wiki/GHA:-wr-pull-request-trigger)
- [wr set pr labels](https://github.com/hackforla/website/wiki/GHA:-wr-set-pr-labels)
- [update team members](https://github.com/hackforla/website/wiki/GHA:-update-team-members) (NOT FOUND?)

#### 2) Add the missing GHA:

trigger-issue
- /add-preliminary-comment
    - check-label-preliminary-update.js
    - preliminary-update-comment.js

trigger-schedule
- /list-inactive-members
    - comment-issues.js
    - create-new-issue.js
    - get-list.js
- /trim-contributers
    - contributors-data.js

utils
- find-linked-issue.js

#### 3) Add the missing workflows:
- [schedule-daily-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-daily-1100.yml)
- [schedule-fri-0700.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-fri-0700.yml)
- [schedule-monthly.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-monthly.yml)
- [schedule-thu-1100.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-thu-1100.yml)

**Comment by roslynwythe** [comment]
- Created epic #4819

**Comment by roslynwythe** [comment]
- see #4819
