### ISSUE TITLE
ER: Change paragraph in header section from h2 to p HTML tag

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4752]
Note: This issue came from the [Task List Dev Leads](https://docs.google.com/spreadsheets/d/1qEiDFUKPCVH3JNzGQSKl_HMl9vqNv8Z9gGrvw9MyYvU/edit#gid=0).

### Emergent Requirement - Problem
In `_includes/events-page/header-container-content.html`, the paragraph in the header section is a h2 header but should be a p HTML element.

https://github.com/hackforla/website/blob/3a5c1479d7a51730fa39a2aeab2e5c2435f7b42d/_includes/events-page/header-container-content.html#L5-L9

### Who was involved
- @JessicaLucindaCheng
- `@SAUMILDHANKAR`   

### What happens if this is not addressed
The Events page doesn't follow W3C accessibility guidelines.

### Resources
- [Events page](https://www.hackforla.org/events/)
  - [pages/events.html](https://github.com/hackforla/website/blob/gh-pages/pages/events.html) 
    - [_includes/events-page/header-container-content.html](https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/header-container-content.html)
- [W3C Web Accessibility Initiative: Page Structure](https://www.w3.org/WAI/tutorials/page-structure/)

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
For `_includes/events-page/header-container-content.html`, write an issue for changing the paragraph in the header section from using h2 (`<h2 class="header-desc">...</h2>`) to p HTML tag on the Events webpage.

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty I was testing what would happen to the styling when the h2 became p and the line height was different for desktop view (screen width: 1440px ). See the following for comparison:
- Live site: https://www.hackforla.org/events/
- Temporary test site: https://jessicalucindacheng.github.io/events/

Is the change in line height okay? Or should I add something about fixing the line-height to match the current website's?

Edit:
**Answer from Bonnie:** The changed line height is okay as is because it matches the line height of other paragraphs on the website.

**Comment by w1ld-r** [comment]
- Created #6633
