### ISSUE TITLE
Revert red filter tags on "Projects" and "Home Page" to prior location 

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4753]
### Overview
The placement of the red filter tags on the "Projects" and "Home Page" was unintentionally changed with a recent pull request. We need the red filter tags to revert to their original placement so they do not interfere with the future placement of a search bar. 

### Action Items

- [x] The red filter tags should revert to their original location prior to merging issue #4694
- [x] The message 'Applied Filters' should also return to its original location prior to merging issue #4694.
- [x] All other changes made with the PR, scrolling behavior, centering, etc. should remain as it is currently.

### Resources/Instructions
- [Projects](https://www.hackforla.org/projects/)
- [Home Page](https://www.hackforla.org/)
- #4694 
- #4593

**Comment by agosmou** [comment]
Assigned myself to revert some changes I made previously

i. 5/30
ii. 5/30 EOD
