### ISSUE TITLE
Update "Sort by UI/UX Issues" Card to highlight Prioritized Backlog Column

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4762]
### Overview
We will highlight the Prioritized Backlog column in the page that is displayed when links on Project Board "Sort by UI/UX" card are activated, to remind users to focus on the Prioritized Backlog column and discourage them from self-assigning issues from other columns.

### Action Items
- [x] Locate the [Sort by UI/UX card](https://github.com/hackforla/website/projects/7#card-65609351) then click `Edit note`
- [x] For each link in the `Sort by UI/UX` card, append the string `#column-7198257` to the end of the URL
- [x] Verify that each link results in the correct filtered view with the `Prioritized Backlog` column highlighted
- [x] Move this item to the Questions/In Review column for review

**Comment by JpadillaCoding** [comment]
Provide Update
1. Progress- just started
2. Blockers- none at this moment
3. Availability- Saturday: 8am-3pm, sunday-thusday: 8am-8pm
4. ETA- Monday 8pm

**Comment by roslynwythe** [comment]
Great job @JpadillaCoding thank you for updating the links to highlight the Prioritized Backlog column, and also bringing the "good first issue" link error to my attention and fixing that.  We appreciate your time and effort!
