### ISSUE TITLE
Plan for how to manage security alerts on repo

### ISSUE THREAD

**Issue by ye-susan** [hackforla/website#477]
### Overview
Let's create a plan for managing security alerts on the repo that all site-managers receive, so we can create a process for handling them and know how to proceed when this happens again. 

### Action Items
Create plan for handling security alerts from github
Create process (and possibly assign leaders/point-people for these issues to handle or to guide us on what to do)
Add this to the repo's README/wiki to document the procedure(s)

### Details
As a new volunteer(and novice dev) - I saw the security alert from github relating to the http-client's vulnerability today so I thought it might be safer if I merged this. But I also assumed that it would just affect my own fork of my repo - since I thought an action like this would require a PR approval from another hfla member/manager. But thank goodness (and thanks for Bonnie) I was able to revert the changes.
Perhaps this could be something we discuss in our next team meeting to figure out what to do when the next security update comes around.

**Comment by ExperimentsInHonesty** [comment]
@cnk to add a page to our wiki for developers with guidance on how to deal with automated security warnings.  Also to look at configuring the bot to provide guidance only, not PRs.

**Comment by cnk** [comment]
I created a page documenting our process and linked to it from the Web Developer page on our wiki.

https://github.com/hackforla/website/wiki/Security-Updates
