### ISSUE TITLE
ER: The projects filters sidebar cuts off text from the largest filter on "Projects" and "Homepage"

### ISSUE THREAD

**Issue by agosmou** [hackforla/website#4770]
### Emergent Requirement - Problem
- On the [Projects](https://www.hackforla.org/projects/) and [Homepage](https://www.hackforla.org/) the Filters sidebar cuts off text from the largest filters on some tablets and phones. See link: https://github.com/hackforla/website/pull/4760#issuecomment-1571329647 
- Examples:
  <img width="204" alt="i-phone" src="https://github.com/hackforla/website/assets/40799239/a924c2d9-19a0-489b-8562-06f6be9e8425">   <img width="390" alt="tablet" src="https://github.com/hackforla/website/assets/40799239/6f2127b5-6af8-4542-b75d-721177b7ce6c">

### Issue you discovered this emergent requirement in
- #4753 

### Date discovered 
06/01/23

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@agosmou @t-will-gillis @roslynwythe 

### What happens if this is not addressed
N/A

### Recommended Action Items
- [ ] Make a new issue
- [x] Discuss with team
- [x] Let a Team Lead know

### Potential solutions [draft]
- Do nothing- the filter message can still be read and this only affects two filters. 
- Truncate text (note this will not work well with "Diversity / Equity / Inclusion")
- Adjust `min-wdth` of filters - might help "Diversity / Equity / Inclusion" in some cases, but not "Amazon Cognito..."
- Remove the word: "technology" from the red filter item to shorten text or widen the sidebar.

**Comment by ExperimentsInHonesty** [comment]
We need three issues from this problem

1. an issue to edit the home unite us projet.md file to split Amazon Cognito / OIDC / OAuth2 into three separate technology items
2. an issue to increase the size of the filter side bar to be wide enough to display `Diversity / Equity / Inclusion x`
3. add some text to the project update issue template to say that no single technology or tool name can be longer than 30 characters

**Comment by roslynwythe** [comment]
New Issues:
- #4782 
- #4784 
- #4785
