### ISSUE TITLE
ER: update the project update issue template

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#4778]
### Dependency
- [ ] https://github.com/hackforla/website/issues/5630

### Emergent Requirement - Problem
We need to add a link to this [comment](https://github.com/hackforla/website/issues/1686#issuecomment-1558322101) to the bottom of the [Project Profile Card review and update](https://github.com/hackforla/website/issues/new?assignees=&labels=P-Feature%3A+Project+Info+and+Page%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+Size%3A+Small%2C+size%3A+0.5pt%2C+time+sensitive&projects=&template=project-profile-card-review-and-update.yml&title=Update+Project+Profile%3A+%5BProject+Name%5D) Issue template.  

When an issue is submitted, using the issue template, I will click on the link to the comment which has another template that I can use to rewrite the issue so that its ready for dev lead review.

### Issue you discovered this emergent requirement in
- #1686

### Date discovered 
2023-05-22

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@

### What happens if this is not addressed
The dev leads have to keep reformatting the issues, and that leads to longer time to change the website for the projects updates.

### Recommended Action Items
- [x] Make a new issue to update the https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml file
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
Make this text show up during and after the issue is created.  Probably have to put it into a text box or something...  The form uses a yml file format... https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml

```
This issue is an ER, a new issue (for developers) will get created from your request.  It will use templates from this issue https://github.com/hackforla/website/issues/5630.  At some point this will possibly become a template, and this comment will get updated.  If the issue is closed when you go to use it, look at the bottom of the issue for a link to the template or WIKI page that replaces it.
```

**Comment by JessicaLucindaCheng** [comment]
To Dos
- [ ] Create the template as an actual issue template
- [ ] Then edit this ER to make it `ready for issue making`
- [ ] Then remove `Draft` and add `ready for issue making` label

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng I think something is better than nothing.  So we could release this update by taking off the dependency.  I updated the text that would appear on the bottom of the ER to this.  If you agree, remove the dependency and add a ready for prioritization label.

>This issue is an ER, a new issue (for developers) will get created from your request.  It will use templates from this issue https://github.com/hackforla/website/issues/5630.  At some point this will possibly become a template, and this comment will get updated.  If the issue is closed when you go to use it, look at the bottom of the issue for a link to the template or WIKI page that replaces it.

**Comment by ExperimentsInHonesty** [comment]
- This issue is replaced with this https://github.com/hackforla/website/issues/7596
