### ISSUE TITLE
Review Inactive Members

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4779]
**Inactive Members:**

cnk
kurikurichan
averdin2
abuna1985
amath95
akibrhast
ethant3
KazushiR
anthonypz
HackforLABot
chelseybeck
daniellex0
Skydodle
MattPereira
d-perez-8
jenny-alexander
ericvennemeyer
Abrosss
mgodoy2023
anonymousanemone
bzzz-coding
Hector-Torres000
JasonUranta
andyarensman
tunglinn
KayodeAlabi
greg-nice
JayBarbanel
seantokuzo
kyrakwak
lindseyindev
elizabethhonest
elvisEspinozaN
AnyaStewart
gstemmann
iilashi
juleanrod
Jaretzbalba
PMKnight
adevlinb
royalbai
Stephen-Parent
summerharveyux
KBWells77
vanessavun
Claudiahamilton-png
zzhoje
erinzz
wiltsai
tamalatrinh
dionw412
hangjoyce
DeitchDustin
mccormackstudio
jlu9d2
matthewmpan
pjpatel021
cwvivianlin
Benji-Montgomery
93Belen
matt-arofin
varyad
carolemlago
vmaineng
Khadijahibidapo
phuongv8
sherririllingux
callmelazarus
DmitriiTsy
arcan9
PeterSYoo
ychang49265
jojochen25
lilyarj
esantiano
palomasoltys
Olanrewaju-Ak
jyaymie
borgesthainara
EmilyTat
oliviaywangn
Alsuang
RobenusW
michaelmagen
hellorachelschwartz
olivioso
LilyLuo001
srandolph2
AsherEngelberg
clayton1111
raswani2023
shimahoush
alice-milmac
mariareeves
kpmunnelly
nehasyed97
JolleenI
MatthewBozin
str-xjua24
Suman2795
bootcamp-brian
arora-aryan
hpweisberg
GitPeebles
neonPurple
ccortega2023
vivian9w
Thinking-Panda
jeristella
yeskatr
myceey69

**Comment by t-will-gillis** [comment]
Unintentional test- closing

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis If you are done with this test issue, please move this to the done column and so that it will get removed from the board when I archive
