### ISSUE TITLE
Update Home Unite Us Project File to split up long technology name

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4782]
### Overview
We need to split the technology item `Amazon Cognito / OIDC / OAuth2` from the "Home Unite Us" project page into three separate items, so that the name will not be truncated on the filter tag when the filter is activated the Projects page.  

### Action Items
- [x] Observe the existing syntax of the [front matter block](https://jekyllrb.com/docs/front-matter/) inside of the `_projects/home-unite-us.md` file and find the `technology` array
- [x] Replace the line 
```
  - Amazon Cognito / OIDC / OAuth2
```
with these three lines:
```
- Amazon Cognito
- OIDC
- OAuth2
```
- [x] Using Docker, view the Projects Page and confirm that the appearance and functionality of the new technology items is correct on the project card for Home Unite Us

### Resources/Instructions
<details><summary>Screenshot showing truncation of the current technology item</summary>

![image](https://github.com/hackforla/website/assets/5314153/c210bfa0-e220-4832-975d-496257dbbebe)

</details> 

- [home-unite-us.md](https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md)
- [HfLA Projects Page](https://hackforla.org/projects)
- [Jekyll Docs on front matter](https://jekyllrb.com/docs/front-matter/)
- This issue is a result of #4770

**Comment by matthewmpan** [comment]
Availability: M-F 12-5PM
ETA: 6/14 EOD

**Comment by ExperimentsInHonesty** [comment]
@matthewmpan Please move this issue to the in progress column
