### ISSUE TITLE
Widen filter div to prevent truncation of filter names

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4784]
### Overview
In the CSS for the filter element, we need to widen the div with class `filtersDiv` in order to prevent truncation of filter names when displayed on a filter tag, for tablet and smaller desktop screen sizes. 

### Action Items
- [x] In the file `_sass/elements/_dropdown_filters.scss`, change
```
.filtersDiv {
  min-width:282px;
}
```
to
```
.filtersDiv {
  min-width:330px;
}
```
- [x] Using Docker, browse to the HfLA Projects page, then activate the filter item `Diversity / Equity / Inclusion` under the heading `Program Areas`.  Confirm that the filter item name is not truncated and the full filter tag (including the `×` symbol) is visible from screen widths of 768 px - 1250 px.  

### Resources/Instructions
- This issue is a result of #4770
<details><summary>Screenshot depicting truncation of "Diversity / Equity / Inclusion"</summary>

![image](https://github.com/hackforla/website/assets/5314153/7e56bfcc-b381-44c5-a6f5-5bec33eb8dcb)

</details> 

[HfLA Projects Page](https://hackforla.org/projects)

**Comment by kiwookim** [comment]
Availability: W-F 9A-5PM
ETA: 6/23 EOD

**Comment by ExperimentsInHonesty** [comment]
@kiwookim Please move this issue to the in progress column

**Comment by kiwookim** [comment]
I made a mistake on the first PR related to this issue, so I closed it and made another PR for it.
Thank you.
