### ISSUE TITLE
Update "Project Profile Review and Update" template to document max length of technology name

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4785]
### Dependency
- [x] #4786

### Overview
We need to inform users of the `Project Profile Card Review and Update` template, to limit the length of technology item names to 26 characters, in order to avoid truncation of the filter tag on the Project Page.  

### Action Items
- [x] Open the file `.github/ISSUE_TEMPLATE/project-profile-card-review-and-update.yml` and locate the string `label: Technologies`
- [x] Change the line:
```
label: Technologies
```
to 
```
label: Technologies (maximum 26 characters)
```
- [x] After committing the change to your issue branch, follow these [instructions](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) for testing the new template.  

### Resources
- This issue is a result of #4770

**Comment by ExperimentsInHonesty** [comment]
during the meeting we decided that the # of characters should not be longer than 30 but that was based on the programs labels.  So for technologies it would need to be shorter. No more than 26 characters.

**Comment by romainyvernes** [comment]
Availability: M-F all day
ETA: 10/16
