### ISSUE TITLE
Fix JS bug in Projects page that causes incorrect checkbox state

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4787]
### Overview
We need to fix a JavaScript bug that is causing filter checkboxes to remain in the checked state even after the filter has been cleared by the user clicking on the filter tag.  

### Action Items
- [x] Note that filters belong to one of three groups:  `Program Areas`, `Languages/Technologies`, and `Status`.  To reproduce the problem, you must select filters from more than one group.  For example, select `Citizen Enagement` and `AWS` , then clear the `AWS` filter by clicking on the `AWS` filter tag.  Note that even after the `AWS` filter is cleared, the `AWS` checkbox remains in the checked state.  This sequence is shown in the animated gif in the Resources section below.  
- [x] Open the JavaScript file `_assets/js/current-projects.js`.  The problem may stem from the fact that in the function `updateCheckBoxState(filterParams)`, checkboxes are updated only if they belong to the same group of filters as is currently displayed.   Update the code so that all checkboxes are updated regardless of which group they belong.  

### Resources
<details><summary>Animated gif showing `AWS` checkbox still checked after filter tag cleared</summary>

![project filter checkbox bug take 11](https://github.com/hackforla/website/assets/5314153/82934e8d-c028-420b-ac36-aaf9f52b5dba)

</details> 

- [HfLA Project Page](https://hackforla.org/projects)
- [JS for HfLA Projects Page](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- This issue was created from ER #4781

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe is this a backend issue?

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe please replace the image on the issue with an animated gif showing what happens now.

**Comment by roslynwythe** [comment]
> @roslynwythe is this a backend issue?

Yes @ExperimentsInHonesty I believe it is a JavaScript bug on line 322 of the function `updateCheckBoxState(filterParams)`.

**Comment by roslynwythe** [comment]
> @roslynwythe please replace the image on the issue with an animated gif showing what happens now.

Thank you for the excellent suggestion @ExperimentsInHonesty, I've replaced the image with an animated gif.

**Comment by bphan002** [comment]
i. Friday June 16th. 

ii Tuesday June 20th
