### ISSUE TITLE
Update "Sort by Front End" Card to highlight Prioritized Backlog Column

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4793]
### Overview
We will highlight the Prioritized Backlog column in the page that is displayed when links on Project Board "Sort by Front End" cards are activated, to remind users to focus on the Prioritized Backlog column and discourage them from self-assigning issues from other columns.

### Action Items
- [x] Locate the [Sort by Front End card](https://github.com/hackforla/website/projects/7#card-63001626) then click `Edit note`
- [x] Delete the text and link for "2nd"
- [x] For each remaining link in the `Sort by Front End` card, append the string `#column-7198257` to the end of the URL
- [x] Verify that each link results in the correct filtered view with the `Prioritized Backlog` column highlighted
- [x] Move this item to the Questions/In Review column for review

**Comment by dakahn93** [comment]
Availability for this week: 6hr
My estimated ETA for completing this issue: 6/20/23

**Comment by vincentdang** [comment]
i. Availability: I can work on this during weekdays or Sunday evenings.
ii. ETA: within the next 4 days.

**Comment by vincentdang** [comment]
Update: all columns seem to work fine except the code for [Large] column for some reason, the code is unfinished and incomplete.  @roslynwythe

**Comment by roslynwythe** [comment]
Hi @vincentdang it looks like you are running into a limitation on the total number of characters in a card.  I created a new Action Item in this issue to delete the text and link to "2nd", since we are no longer creating "good second issues".  Hopefully once those characters are removed, it will be possible to recreate the link for "Large".  If there is still not enough space, please delete the text and link to "Fun" and again try to recreate the link for "Large".  Thank you.  If you need assistance please send me a DM on Slack.

**Comment by vincentdang** [comment]
@roslynwythe what is the code/link for the "Large" option?

**Comment by roslynwythe** [comment]
> @roslynwythe what is the code/link for the "Large" option?

Hi @vincentdang this is the link for "Large" 
```
[Large](https://github.com/hackforla/website/projects/7?card_filter_query=label%3A%22role%3A+front+end%22+label%3A%22complexity%3A+large%22#column-7198257)

**Comment by vincentdang** [comment]
Update: it is done. will be put into questions/review bucket.
@roslynwythe

**Comment by roslynwythe** [comment]
Great job @vincentdang - thank you!
