### ISSUE TITLE
ER: Change h2 {margin-top: 48px;} SCSS to only apply on Privacy Policy page

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#4794]
### Emergent Requirement - Problem
- In _sass/components/_privacy-policy.scss [^1], within the `@media #{$bp-desktop-up}`, on lines 52-54, this is the SCSS:
  ```
    h2 {
      margin-top: 48px;
    }
  ```
  - This SCSS snippet above should **only** be applied to the Privacy Policy page [^2]. 
- Currently, the SCSS snippet above is being applied to h2 HTML elements across the Hack for LA website when the screen is desktop width, which is a problem. Examples of the problem are on each project's detailed page (e.g. 311 Data [^3]) and the Join Us page [^4].
  <details>
    <summary>Click here to see a gif showing the problematic gap on the 311 Data page and Join Us page</summary>
    <img src="https://github.com/hackforla/website/assets/31293603/b39f6203-14dc-4208-9961-1efd53bd341a" alt="">
  </details> 

### Issue you discovered this emergent requirement in
- Not applicable

### Date Discovered 
2023-Jun-09

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@JessicaLucindaCheng 

### What happens if this is not addressed
The large gap above h2 elements will remain and may look a bit weird to visitors/viewers of the site.

### Recommended Action Items
- [x] Make a new issue to fix the problem discussed in the "Emergent Requirement - Problem" section above

### Resources
[^1]: _sass/components/_privacy-policy.scss: https://github.com/JessicaLucindaCheng/website/blob/gh-pages/_sass/components/_privacy-policy.scss
[^2]: Privacy Policy page: https://www.hackforla.org/privacy-policy
[^3]: 311 Data page: https://www.hackforla.org/projects/311-data
[^4]: Join Us page: https://www.hackforla.org/join

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-pm I have completed writing this ER. However, can I get a PM to review and approve this ER before a developer writes the issue for it? Thank you.

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng This is ready to make an issue!

**Comment by chrismenke45** [comment]
ETA: 6/23 EOD
Availability: 8am-12pm M-F

**Comment by chrismenke45** [comment]
An issue has been created for this ER #4864 (still a draft)

**Comment by chrismenke45** [comment]
Issue #4864 Ready for Product to review

**Comment by t-will-gillis** [comment]
- Closing this ER because issue #4864 and subsequent PR #4945 were created to address the concern.
