### ISSUE TITLE
Need to make UI Design for Cards

### ISSUE THREAD

**Issue by MohamedMafaz** [hackforla/website#4795]
### Overview
Hey there! Our website home page isn't look professional. I'd like to redesign the complete home page UI. If you don't like to change the complete UI. I can simply change the card design into something nice. Please assign me this issue. I'm a Professional UI UX Designer and getting into front end development

**Comment by ExperimentsInHonesty** [comment]
Hi @MohamedMafaz thank you for your interest in redesigning the website.  We have a redesigned website we will be pushing soon.  Here is a mockup 
![image](https://github.com/hackforla/website/assets/37763229/3b7fdb1f-f1df-4782-983f-59a260fab873)


If you are interested in helping with other design tasks, please join our organization https://www.hackforla.org/getting-started
