### ISSUE TITLE
Refactor Tools data for access-the-data.md

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4798]
### Dependencies
- [x] #4860
- [x] #4861 

### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [access-the-data.md](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Figma, Photoshop, Google Drive
```
to
```
tools:
  - Figma
  - Photoshop
  - Google Drive
```
ADDED NOTE 8/6/23: Refer also to issue #4818 for additional edits.

  - [x] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

**Comment by Tomomi-K1** [comment]
Availability for this week: Monday to Friday until 5pm.
My estimated ETA for completing this issue: Pull Request is created

**Comment by ExperimentsInHonesty** [comment]
### Other
I have to double check this because the tools listed are different than what appears on the site, so there may have been a change in the interim

**Comment by Tomomi-K1** [comment]
@ExperimentsInHonesty, It looks like changes to the tools are made in [this pull request]( https://github.com/hackforla/website/pull/5121#issue-1829955380), issue[#4818](https://github.com/hackforla/website/issues/4818#issue-1753379595).
