### ISSUE TITLE
Refactor Tools data for green-earth-os.md

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4806]
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [green-earth-os.md](https://github.com/hackforla/website/blob/gh-pages/_projects/green-earth-os.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Google sheets, Google forms, Figma, FigJam
```
to:
```
tools:
  - Google sheets
  - Google forms
  - Figma
  - FigJam
```
  - [ ] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

**Comment by tiffchannn** [comment]
1. **Availability:** Weekdays from 11am - 4:30pm PST
2. **ETA:** 1-2 days, since this is my first issue I've worked on

**Comment by tiffchannn** [comment]
I have clarifying questions about what visual changes (if any) I'm supposed to see when making the requested changes.

Here's what I've done:
* Within _projects > green-earth-os.md: changed `tools: Google sheets, Google forms, Figma, FigJam` to 
```
tools:
  - Google sheets
  - Google forms
  - Figma
  - FigJam`
```

When reloading the website page, I don't see any visual changes to the Green Earth OS card. Please see the screenshot.

I'm working on the `refactor-tools-data-green-earth-4806` branch on my forked repo.

Any help is greatly appreciated! :)
 
<img width="1792" alt="Screenshot 2023-07-28 at 11 12 19 AM" src="https://github.com/hackforla/website/assets/61890477/76a40d90-7e57-4ed1-82d5-7beb324f09dd">

**Comment by ExperimentsInHonesty** [comment]
### Make an ER to change 
````
- [ ] Change 
```
tools:
  - Google sheets
  - Google forms
  - Figma
  - FigJam
```
to
```
tools:
  - Google Sheets
  - Google Forms
  - Figma
  - FigJam
```
````
