### ISSUE TITLE
Refactor Tools data for home-unite-us.md

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4808]
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [home-unite-us.md](https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: Figma, AWS, Nginx, Docker, Style Components, Zoom, GitHub, Google Drive, Docs, Sheets, Slides
```
to
```
tools:
  - Figma
  - AWS
  - Nginx
  - Style Components
  - Zoom
  - GitHub
  - Google Drive
  - Docs
  - Sheets
  - Slides
```

Do not include docker even though it is in the current tools list, because it is actually categorized under languages, which is delivered by pulling the language for a repo from the GitHub API.
  - [x] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

**Comment by Jmmcclo2023** [comment]
Availability: 7/30 3pm - 10pm EDT
ETA:  7/30

**Comment by Jmmcclo2023** [comment]
Progress Update
Progress - This issue is nearly completed. The changes have been made to the correct file. Just need to make sure the changes work on the website with Docker, then make the pull request.
Blockers - The main difficulty of this issue was just GitHub confusion.  It took longer than expected to understand how to use GitHub correctly with this issue.
Availability - Daily 4pm-6pm & 8pm - 10pm EDT
ETA - 8/2
Pictures - N/A

**Comment by ExperimentsInHonesty** [comment]
### should get moved to the Technologies section
- AWS
- Nginx

### Other
Need to find out what they mean by style components
