### ISSUE TITLE
Refactor Tools data for open-community-survey.md

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4811]
### Dependency
  - [x] #4860 
  - [x] #4861 
 
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to revise the filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to include a dropdown for "Tools", so that we can see where we might need to move project values from `tools` to `technologies`, and vice versa. In order for the filter to work properly, we need to refactor the `tools` data in the .md file from a string to a list.
### Action Items
  - [x] Refer to the [open-community-survey.md](https://github.com/hackforla/website/blob/gh-pages/_projects/open-community-survey.md) file and find the entry for `tools:`
  - [x] Change the `tools` data from:
```
tools: 'ArcGIS surveys, Figma, Google Docs, Zoom'
```
to:
```
tools:
  - ArcGIS surveys
  - Figma
  - Google Docs
  - Zoom
```
  - [x] Confirm that the Tools data on all project pages is rendered correctly
### Resources/Instructions
  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page
  - This issue is part of an epic: #4777

**Comment by yffu** [comment]
Progress: 
reviewed open-community-survey.md entry for tools
changed the tools data
verify the tools data displaying on all projects pages for the open community survey card
Blockers: @t-will-gillis question: the tools displays as a string representation of a list, and not a comma separated list - is this OK? EDIT (07/26) resolved with updates to current-projects-check.js
Availability for this week:  6+ hours this week. After 5PM PST to answer questions about this issue.
My estimated ETA for completing this issue: Beginning of next week (08/01)
Pictures (optional):
open-community-survey.md change
![refactor-tools-data-4811_2](https://github.com/hackforla/website/assets/5543388/b21b1535-be16-4660-8642-10591dbce816)
before change
![refactor-tools-data-4811_0](https://github.com/hackforla/website/assets/5543388/7aef809b-b307-4923-b227-46378d9acd93)
after change
![refactor-tools-data-4811_1](https://github.com/hackforla/website/assets/5543388/0f61d805-660c-4585-8b45-5a81fc7f5acc)
