### ISSUE TITLE
Fix bug with GHA where Update labels do not get applied to Issues with Closed PRs

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4839]
### Overview
 Our Project Board uses a GHA automation that adds a `2 weeks inactive` label on idle issues, reminding us to check on the developer's status. We need to address a recently discovered [edge condition](https://github.com/hackforla/website/issues/4704) in which open issues attached to closed PRs do not trigger the automation. 

### Action Items

- [x] Review the [schedule-fri-0700.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-fri-0700.yml) file and especially the associated [add-label.js](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/add-label.js) file.
- [x] In the js file, review the conditions and understand how they trigger the GHA. We need to retain the automation's current functionality. Note that currently when an issue is linked to an open PR, the label-updating ceases since we our focus shifts to the PR review process.
- [x] Create a new functionality to address the condition where a. the issue is still open, but b. the linked PR is closed for whatever reason without merging. In this case, the automation should resume updating the issue labels. 

### Resources/Instructions

- #4704
- Never done GitHub actions? [Start here!](https://docs.github.com/en/actions)
- [Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
- [GitHub Complex Workflows doc](https://docs.github.com/en/actions/learn-github-actions/managing-complex-workflows)
- [GitHub Actions Workflow Directory](https://github.com/hackforla/website/tree/gh-pages/.github/workflows)
- [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows)
- [Workflow syntax for GitHub Actions](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions)

**Comment by LRenDO** [comment]
Availability: 6/24 7/2
ETA: 7/3

**Comment by LRenDO** [comment]
## Progress Report
### Progress:
  - Understood the functionality of the GHA by looking through 
    - the associated files
    - Github Scripts and API documentation
    - logs for the Schedule Friday 700 GHA
  - Discovered a TypeError bug in the logs related to date formatting for the comment which causes the postComment function to fail 
  - Set up a private testing environment with mock issues and pull requests
  - Located the relevant lines of code for this bug and the bug I discovered
### Blockers: None currently. On 7/2 I plan to:
  - Fix the bug
  - Test the solution
  - See if there is already open issue or ER for the TypeError bug I found
### Availability: 
7/2
### ETA: 
7/3

**Comment by t-will-gillis** [comment]
Hi @LRenDO fyi we saw the TypeError yesterday and it has been fixed. Please see #4899 fixes #4898 . Is this what you were seeing?

**Comment by LRenDO** [comment]
> Hi @LRenDO fyi we saw the TypeError yesterday and it has been fixed. Please see #4899 fixes #4898 . Is this what you were seeing?

@t-will-gillis Yep, it is! Must have pulled things down before y'all got to it. I'll sync things up here locally before I start work on Sunday. Thanks for linking the issues and fixes, so I didn't have to go digging!
