### ISSUE TITLE
ER: Event information is missing from the Website Project Page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4857]
### Emergent Requirement - Problem
- After merge of PR #4817 it was noted that no events are displayed on the Website Project page.  It was confirmed that problem is due to the change in the project title in that PR.  

### Date discovered 
June 18, 2023

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
Website project meeting details will not be displayed on the project page.

### Recommended Action Items
- [ ] Make a new issue - #4874
- [ ] Discuss with team
- [ ] Let a Team Lead know

**Comment by ExperimentsInHonesty** [comment]
This issue has been resolved by #4874
