### ISSUE TITLE
Refactor project page to fix any formatting issues with new tools data format

### ISSUE THREAD

**Issue by ronaldpaek** [hackforla/website#4859]
### Dependency

- [x] #4427 

### Overview

This task involves refactoring the code referencing page.tools to align with the newly implemented data format for tools. The modifications aim to ensure correct display, accommodating spaces in the new data structure.

### Action Items

- [x] Refer to [project.html](https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html) and locate where tools is being referenced
- [x] Refactor this code since tools till now be an Array so we need to map over every value
```
{% if page.tools %}<p><strong>Tools: </strong>{{ page.tools }}</p>{% endif %}
```
to
```
{% if page.tools %}
<p id='tools'>
    <strong>Tools: </strong>
    {% for tool in page.tools %}
    {{ tool }}{% if forloop.last == false %},{% endif %}
    {% endfor %}
</p>
{% endif %}
```
Making this change will ensure tools section renders correctly with the new data format of tools
- [x] Once the change is made, confirm that Tools data is rendering correctly/ as before on individual project pages.

<details>
<summary>Click here to see pictures of the tools list</summary>
<br>
<img src="https://github.com/hackforla/website/assets/95109313/523ad3de-c47b-41b1-9bfc-e12f8168549d.png">
<br>

</details>

### Resources/Instructions

- [Projects](https://www.hackforla.org/projects/) page
- [Liquid template language](https://shopify.github.io/liquid/)
- This issue is part of an epic: #4427

**Comment by ldietz08** [comment]
Availability: M-F 4pm-6pm
ETA: 6/29
