### ISSUE TITLE
Change h2 margin on Privacy Policy Page

### ISSUE THREAD

**Issue by chrismenke45** [hackforla/website#4864]
### Overview
The h2 selector in  [_sass/components/_privacy-policy.scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_privacy-policy.scss) applies a rule to the margin property that is being applied to all \<h2\> elements in the HFLA website. We need to change this so the styling only affects the  \<h2\> elements [privacy policy page](https://www.hackforla.org/privacy-policy).

### Action Items
- [x] Update lines 52-54 (within the ```@media #{$bp-desktop-up}```) in the [scss](https://github.com/hackforla/website/blob/gh-pages/_sass/components/_privacy-policy.scss) file to only target \<h2\> elements on the [privacy policy page](https://www.hackforla.org/privacy-policy)
- [x] Review the other pages on the site to confirm the change didn't affect any other pages in a negative way.

### Resources/Instructions
- The [Privacy Policy HTML file](https://github.com/hackforla/website/blob/gh-pages/pages/privacy-policy.html) has classes unique to the privacy policy page that you can use to update the selector.
- This is an issue for ER #4794

**Comment by chrismenke45** [comment]
This is an issue for ER #4794

**Comment by angelenelm** [comment]
- Availability: Mon-Fri, 12PM-5PM PST
- ETA: EOD Friday July 14th
