### ISSUE TITLE
ER: Broken links on "Projects Team Meetings" page

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4868]
### Emergent Requirement - Problem
Several of the links to individual projects on the [project-meetings](https://www.hackforla.org/project-meetings) page are to https://www.hackforla.org/undefined, for example the link for  "Tech Work Experience", "Youth Justice Nav", "Ballot Nav", "Tables", and "People Depot."

### Issue you discovered this emergent requirement in
- n/a

### Date discovered 
June 20, 2023

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@chelseybeck 

### What happens if this is not addressed
It looks unprofessional for our website to have broken links, not to mention the user is not getting the info they need.

### Resources
- [project-meetings.html](https://github.com/hackforla/website/blob/gh-pages/pages/project-meetings.html)
- [project-meetings.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/project-meetings.js)

### Recommended Action Items
- [x] #4906
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
- This likely is not going to be an issue for website to work on, since it appears that this issue might be due to missing project data inputs to the VRMS interface.

**Comment by t-will-gillis** [comment]
I spoke with @MattPereira earlier today, and we believe that for "Youth Justice Nav" and "Ballot Nav", the broken links might be fixed if the PM enters the project's URL in the PMs' interface with VRMS. I have sent Slack messages to the PMs for both projects asking if they can look into this. I have also sent a Slack to a member of "People Depot"- it would be that same fix if the PMs have a URL (People Depot's GitHub?) to enter on the PMs' interface with VRMS.

@ExperimentsInHonesty Who are the contacts for the remaining two entries with broken links: "Tech Work Experience" (six meetings listed)  and "Tables" (meetings Fri 1-2)?

**Comment by MattPereira** [comment]
![Screenshot from 2023-06-24 11-56-54](https://github.com/hackforla/website/assets/73561520/85ffec11-ff05-4ad2-9976-52963115164b)

![image](https://github.com/hackforla/website/assets/73561520/7a1b777b-df02-4fb3-99e7-f61ce00cf6fc)

**Comment by MattPereira** [comment]
@t-will-gillis 

You can test that the fixed ones work on the https://www.hackforla.org/project-meetings page

### Fixed
- Youth Justice Nav
- Ballot Nav

For the other three projects I pointed the vrms `hflaWebsiteUrl` to where they will work once the website team creates a markdown file in the `_projects` collection for each of the projects below:

### Website Team Can Finish Fix From Here
- Tables - https://www.hackforla.org/projects/tables
- Tech Work Experience - https://www.hackforla.org/projects/tech-work-experience
- People Depot - https://www.hackforla.org/projects/people-depot

**Comment by t-will-gillis** [comment]
Update for remaining three:
- "Tech Work Experience" Issue #2288 will create project card for website to render; link will be active when this issue is complete
- "Tables" and  "People Depot." #4906 is created to add a redirect to the respective projects GitHub accounts until the projects have functioning pages
