### ISSUE TITLE
ER: Named Anchor Links in CONTRIBUTING.md Table of Contents do not work

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4869]
### Emergent Requirement - Problem
Links in the Table of Contents of CONTRIBUTING.md that reference the corresponding section headings are not working.  There is a mismatch between the named anchor in the ToC links and the anchor ids in the section headings, which are dynamically generated during the markdown-to-HTML conversion.  

### Details
It appears that the markdown-to-HTML converter is prepending the characters 'user-content' to each section heading anchor id, which is causing the mismatch.  Assuming the conversion is `krakdown`, I have found configuration options that could resolve the problem, but I have not been able to determine how/where to set the options for the GitHub build.  The action log for 'page build and deployment' does not list CONTRIBUTING.md but it does list a configuration file ` /github/workspace/./_config.yml` which may contain the conversion options, but how is this file accessed/modified ???

### Issue you discovered this emergent requirement in
- #

### Date discovered 
6/19/2023

### Did you have to do something temporarily
- [ ] YES
- [x] NO - however testing the browser reveals that if the characters `user-content` is removed from the `id` attribute of the anchor in the section heading, the links from the Table of Contents work.  

### Who was involved
Bonnie Wolfe

### What happens if this is not addressed
Named anchors links to specific sections of CONTRIBUTING.md do not work.  

### Recommended Action Items
- [ ] Make a new issue   #5062
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
Options:
  - Configure the Markdown to HTML converter settings in to remove the string `user-content` from the beginning of the `id` attribute of each section heading.  
  - Modify the links in the Table of Contents to match the section heading anchor ids.

**Comment by AlimurtuzaCodes** [comment]
Can I work on this issue?

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty it appears that we need to access the configuration options for the markdown-to-HTML conversion of CONTRIBUTING.md which takes place in the GitHub build.  I believe those options are likely contained in `/github/workspace/./_config.yml` but I have no idea how to access or modify those files.  Please advise.

**Comment by roslynwythe** [comment]
No change changes were made but the bug has somehow resolved and the links in the ToC of https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md are working fine.  The problem was most likely with the GitHub markdown viewer and has been resolved.  Closing as not planned.
