### ISSUE TITLE
Update CONTRIBUTING.md to reflect updated Pull Request Template

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4870]
### Overview
We need to update CONTRIBUTING.md to reflect the changes in the Pull Request template.  

### Action Items
- [x] Navigate to CONTRIBUTING.md
- [x] Edit section 3.1.b to reflect the changes in the [Pull Request template](https://github.com/hackforla/website/blob/gh-pages/.github/pull_request_template.md)
- [x] Check your changes in your remote repository

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Pull Request template](https://github.com/hackforla/website/blob/gh-pages/.github/pull_request_template.md)

**Comment by whitneywind** [comment]
availability: 5-6pm tonight and 10-12 tomorrow morning
eta: tomorrow
