### ISSUE TITLE
Edit name of Website project in VRMS to delete trailing space

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4874]
### Overview
We need to remove the trailing space from the name of the Website Project in VRMS in order to display event information on the Website project page.  

### Action Items
- [x] In VRMS, delete the trailing space from the name of the Website project, or write an issue to update the logic so that trailing spaces are ignored.  

### Resources/Instructions
- This issue was created as a result of #4857
<details><summary>Website Project page missing Meeting Information</summary>

![image](https://github.com/hackforla/website/assets/5314153/3f78fb16-3120-48ef-9169-595918146a5c)

</details> 

<details><summary>Correct Display of Meeting Information on Website Project Page</summary>

![image](https://github.com/hackforla/website/assets/5314153/887d0228-d08f-4c20-8b68-c601f494aecd)

</details>

**Comment by ExperimentsInHonesty** [comment]
I have updated the project name in VRMS.  I think it would be worth opening a ticket at VRMS to ask them to automatically trim trailing spaces in any field

**Comment by roslynwythe** [comment]
> I have updated the project name in VRMS. I think it would be worth opening a ticket at VRMS to ask them to automatically trim trailing spaces in any field

See https://github.com/hackforla/VRMS/issues/1402
