### ISSUE TITLE
Revise Project Home Page Getting Started drop-down

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#488]
### Overview
The Getting Started Drop-Down of the Project Home Page should not be visible for completed projects. In place of the Getting Started drop down button, the user is to be shown the following message:  "If you would like to talk to us about this completed project, please reach out to team@hackforla.org". 

### Action Items
- [ ] Create revised mockup of Project Home Page to reflect completed project

### Resources/Instructions
https://www.hackforla.org/projects/work-for-la
https://www.hackforla.org/projects/heart
https://www.hackforla.org/projects/metro-ontime

**Comment by xiosantaella** [comment]
Created a revised mockup of Project Home Page that replaces Getting Started Drop-Down with "Learn More" element

**Comment by xiosantaella** [comment]
https://www.figma.com/file/AWRnpjfjzGBViEZePzyiFM/HFLA-Project-Home?node-id=0%3A1

**Comment by ExperimentsInHonesty** [comment]
@xio, please show mockup for all three completed projects and remove getting started section and figure out sizing of the text

**Comment by ExperimentsInHonesty** [comment]
@xio, please show mockup for all three completed projects and remove getting started section and figure out sizing of the text
