### ISSUE TITLE
Update "Sort by Product" card in Project Board

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4884]
### Overview
We will highlight the Prioritized Backlog column in the page that is displayed when the link on the "Sort by Product" card is activated, to remind users to focus on the Prioritized Backlog column and discourage them from self-assigning issues from other columns.  We will also delete the "2nd" link since there are no issues with the "good second issue" label.  

### Action Items
- [x] Locate the [Sort by Product card](https://github.com/hackforla/website/projects/7#card-67094895) then click `Edit note`
- [x] append the string `#column-7198257` to the end of the "All Issues" URL
- [x] Save the note
- [x] Verify that clicking the "All Issues" link results in filtering the Project Board for the 'role: product' label,  with the `Prioritized Backlog` column highlighted
- [x] Move this item to the Questions/In Review column for review

**Comment by angelenelm** [comment]
- Availability: M-F 10AM - 5PM PST
- ETA: EOD Friday, August 4, 2023

**Comment by roslynwythe** [comment]
Hi @angelenelm I need to make a change to this issue.  Please re-read the issue carefully and message me on Slack if you have any questions.  I apologize for the inconvience if you have already started on it.

**Comment by angelenelm** [comment]
I haven't been able to get to it yet, so no problem!
ETA: EOD Friday, August 18

**Comment by LRenDO** [comment]
Hi @angelenelm! This looks great! 

- The link correctly highlights the product backlog column
- It still properly filters the issues with the product role
- The issues was moved to the correct column

Great work and thanks for taking the time to contribute!
