### ISSUE TITLE
Update "Sort by Back-end Issues" card

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4885]
### Overview
We will highlight the Prioritized Backlog column in the page that is displayed when links on the "Sort by Back-end Issues" card are activated, to remind users to focus on the Prioritized Backlog column and discourage them from self-assigning issues from other columns.  We will also delete the "2nd" link since there are no issues with the "good second issue" label.  

### Action Items
- [x] Locate the [Sort by Back-End Issues card](https://github.com/hackforla/website/projects/7#card-65620159) then click `Edit note`
- [x] For each link in the `Sort by Back-end Issues` card, append the string `#column-7198257` to the end of the URL
- [x] Remove the "2nd" link text and link
- [x] Verify that each link results in the correct filtered view with the `Prioritized Backlog` column highlighted
- [x] Move this item to the Questions/In Review column for review

**Comment by yujioshiro** [comment]
Availability: 8/4 6-8pm, 8/5 4-6pm
 ETA: 8/4 EOD

**Comment by yujioshiro** [comment]
All of the links in the "Sort by Back-end Issues" card have been updated to reflect the changes described in this issue.
I confirmed that clicking on each link correctly filters and highlights the issues in the prioritized backlog.

Two things I noticed:
1. The order of the "Sort by Back-end Issues" card isn't intuitive. It goes from All > Good First Issue > Small > Medium > Fun > Large. My suggestion would be to go All > Good First Issue > Small > Medium > Large > Fun, but happy to discuss.
2. The language used in the different "Sort by..." cards is not consistent. You can see in the screenshot that for the front-end card, the "good first issue" is referred to as "1st."
![image](https://github.com/hackforla/website/assets/19900334/cc405db2-f7ed-476a-9d06-fb27e0c26832)

**Comment by roslynwythe** [comment]
Thank you @yujioshiro for completing the required improvements to the "Sort by Back-end Issues" card and for pointing out the inconsistency between those cards.  I'm closing this issue as completed, and any further changes to the cards will be in a new issue.
