### ISSUE TITLE
Update Instructions Posted when GitHub Actions applies update labels

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4887]
### Overview
We need to update the comment posted when the "update labels" ("Update To!" and "2 weeks inactive") are applied, in order to advise developers that if they require help, the issue should be placed in the "Questions/In Review" column so that merge team/dev leads can provide assistance in an effective and efficient manner. 

### Action Items
- [x] Become familiar with [HfLA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions),  [HfLA's GitHub Actions wiki page](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions) and [Add Update Label Weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly)
  - [x] If you have not already done so, create a copy of the Project Board into your own repo ([Tip 6: Creating your own Project Board](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions#tip-6-creating-your-own-project-board))
- [x] On your issue branch, open the file `github-actions/trigger-schedule/add-update-label-weekly/update-instructions-template.md`
- [x] In the second paragraph, replace 
```
1) place your issue in the developer meeting discussion column and ask for help at your next meeting,
```
with
```
1) place your issue in the `Questions/In Review` column of the Project Board and ask for help at your next meeting,
```
- [x] After committing changes to your issue branch, push the branch to your fork, make it the default branch, add the update labels in your repository, and test the [Add Update Label Weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly) job with a test issue.  

### Resources/Instructions
[Comment template for the Add Update Label to Issues Weekly job ](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/update-instructions-template.md)
The [Add Update Label Weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly) job can be found in [Schedule-Fri-0700](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-fri-0700.yml)

**Comment by ronaldpaek** [comment]
1.  Available Sunday, July 9th
2. ETA: Hope to be done by Monday, July 10th

**Comment by ronaldpaek** [comment]
@roslynwythe do u still want it to have the updated message even if it's not 2 week inactive status, like if they haven't provided an update within 7 days?

<img width="1013" alt="CleanShot 2023-07-09 at 21 30 56@2x" src="https://github.com/hackforla/website/assets/95109313/6ba2167f-4f20-4f01-a443-22f8e97163e2">

**Comment by roslynwythe** [comment]
@ronaldpaek Yes, please update the message associated with the "To Update !" message.  Thank you.
