### ISSUE TITLE
Audit Automation/GHAs for use of "prework" label 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#4888]
### Overview
We need to audit HfLA GitHub Actions and any other automations for references to the label `prework`, in order to prepare for replacing it with the label `Complexity: Prework`  

### Action Items
- [x] Become familiar with the resources describing the HfLA GHA archtecture[^1] and GitHub Actions[^2]
- [ ] Audit all HfLA GitHub Actions and any other automations for use of the label `prework`.  Do not rely exclusively on wiki documentation for locating GHAs, because it is not complete; instead audit workflows, scripts and actions in `.github/workflows` and `github-actions` folders.  
- [ ] Write a comment in this issue describing each instance in which a GHA will require modification to work if the label `prework` is replaced.  Then move this issue to `Questions/In Review` and add the label `ready for dev lead`

### Resources/Instructions
[^1]:[Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)
[^2]:[HfLA GitHub Actions](https://github.com/hackforla/website/wiki/HfLA-GitHub-Actions)

**Comment by antho-zng** [comment]
ETA: Tues 9/26 EOD
Availability: M–F 9–5pm ET

**Comment by antho-zng** [comment]
Hi @roslynwythe! Just wanted to clarify that I have the right understanding of the issue: to do this audit, I'm looking through all the automated scripts/actions within `.github/workflows` and `github-actions` and looking for anything that uses the `prework` label. Does that sound right?

At the moment, I've run `Cmd + F` of "prework" on my local copy of the website repository (and confirmed that it's up-to-date with the upstream `hackforla/website` gh-pages branch), and I'm not finding any instances of the `prework` label in either `.github/workflows` or `github-actions`. The only results coming up are three pre-work template `.md` files inside `.github/ISSUE_TEMPLATE`.

Is there anything I'm misunderstanding about the issue or the approach? This is my first time working with GHA so guidance would be super helpful! Thank you!

**Comment by roslynwythe** [comment]
@lateral-neck-stretch I think that your apprach is correct.  For some reason I believed that there were some dependencies on the prework label but I was wrong.  I will close this as completed so you will receive full credit, but I suggest that you should complete another Medium issue before progressing to a Large issue.  Please contact me on Slack if you wish to discuss.  Also in the future, please don't forget to move issues into the "In Progress" column upon assignment.  Thanks
