### ISSUE TITLE
ER: Need a template for adding new project to the website

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4901]
### Emergent Requirement - Problem
We need a template to facilitate the process of adding new projects to our website, for example "People Depot" or "Tables".

### Issue you discovered this emergent requirement in
- n/a

### Date discovered 
- Discussed at dev meeting 6/26/23

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty @JessicaLucindaCheng @roslynwythe 

### What happens if this is not addressed
Without the template, each time we add a new project we will be spending time we don't need to be

### Recommended Action Items
- [x] Make a new issue
- [x] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
Possible solutions include:
- [x] Editing the existing template for "Issue: Project Profile Card review and update" to include the option of creating a new project card. 
  - The advantage for this option is that all of the info is already arranged.
  - Could the issue template be automated? Might be worth exploring...
- [ ] ~Creating a new template that is based in part on the "Issue: Project Profile Card review and update"~

**Comment by ExperimentsInHonesty** [comment]
We should use the same template that is already in use.  

Changes that need to be made
1. Add hero image box
2. change existing image text box to long text box so that an image can be added (it's currently not working)
3. Add a choice in name of project
    1. `new project`
5. Add a choice to project card url
    1. `new project`

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis This is ready if you want to make the issue for it.  if not anyone on the merge team can pick up the issue making task.

**Comment by t-will-gillis** [comment]
@ExperimentsInHonesty created issue #5857 for addressing the comments from this ER. Closing this ER.
