### ISSUE TITLE
Add redirect for broken links on "Project Team Meetings" page

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#4906]
### Overview
On our [project-meetings](https://www.hackforla.org/project-meetings) and [events](https://www.hackforla.org/events/) pages the hrefs to "People Depot" and "Tables" link to an undefined page "https://www.hackforla.org/projects/people-depot". We want the href for "People Depot" and "Tables" to link to each project's GitHub account until they have pages in the _projects folder.

### Action Items
The API_ENDPOINT for data on the project meetings page comes from VRMS. The query to VRMS returns an "event" object, and `event.hflaWebsiteUrl == "" ` for both "People Depot" and "Tables" since neither has a project page on the website.

- [x] In the file [api-events.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/utility/api-events.js) we want to redirect the links for "People Depot" and for "Tables" by inserting the following  code after `if (event) {` on Line 35 and before `let eventHtml;` on Line 36:

```
// If a project doesn't have an hflaWebsiteUrl, redirect to the project's GitHub page
if (event.hflaWebsiteUrl == "") {
  event.hflaWebsiteUrl = event.githubUrl
}
```
- [x] Near the end of the same file in `function display_object(item)`, we need to query the githubUrl from VRMS by adding the following entry in `const rv_object` after the `hflaWebsiteUrl`:
```
githubUrl: item.project.githubUrl,
```
- [x] Confirm that this link and the others work correctly on the  [project-meetings](https://www.hackforla.org/project-meetings) and [events](https://www.hackforla.org/events/) pages. 
### Resources/Instructions

<details>
<summary>Screenshot showing current link when "People Depot" is selected on "Project Meetings" page</summary>

![peopledepot1b](https://github.com/hackforla/website/assets/40799239/f85bde2f-a6e0-4d28-9014-7f17b0bd25dd)

</details>
<details>
<summary>Screenshot showing current link when "People Depot" is selected on "Events" page </summary>

![peopledepot2](https://github.com/hackforla/website/assets/40799239/c7d05cb7-a344-4225-ba05-44f4f104b84c)

</details>

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis Thanks for making this issue
1. Please add animated gif of how to see the problem on both pages
2. Please add the `feature: events` label since it affects both pages

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis I had a brainstorm and I went into VRMS and I deleted the url for the project page so that 
hflaWebsiteUrl":"https://www.hackforla.org/projects/people-depot"
should now show up as hflaWebsiteUrl":""
in the vrms data.  

I won't know until tomorrow if that worked that way...
so now that I have done that change at vrms, could you change the code above, to simply look for any hflaWebsiteUrl where the value is "" and then use the github url for that project instead.  That would make this code more useable long term.

**Comment by t-will-gillis** [comment]
@ExperimentsInHonesty I removed the previous code that was specific for "People Depot" and replaced it with the more general code as shown. 

Note that this works for "People Depot" and would return the correct url for some of the other projects, but in the future it may add the wrong url for a project because the GitHUb repo names are not consistent. For example:
- the "People Depot" GitHub url follows the pattern "https://github/hackforla/" + "peopledepot", and projects like "Civic Tech Jobs" and "Write for All" are similar; however:
- "Lucky Parking", "Food Oasis", and others add dashes between each word so the ending of the url is  + "lucky-parking",  + "food-oasis", and so on. 

But again, the code above works for "People Depot" and does not cause any issues presently. 

Also- Does "Tables" have any website to link to?

**Comment by t-will-gillis** [comment]
@ExperimentsInHonesty As discussed in today's meeting, this has been refactored to pull the project's GitHub URL from VRMS whenever the project's HfLA URL == "". It looks a lot cleaner now. 

The last thing that is needed: could you clear the hflaWebsiteUrl for "Tables" in VRMS? Right now hflaWebsiteUrl = "https://www.hackforla.org/projects/tables" instead of ""

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis I cleared the value in the hflaWebsiteUrl = on vrms.io

**Comment by yffu** [comment]
i. Availability: After 5 PT Daily
ii. ETA: 07/29 (Sat)

**Comment by yffu** [comment]
Have a blocker/question, wondering if someone could help:

2. Blockers: 
on project-meetings page there's an underscore after the project name
![add-redirect-for-broken-links-4906_0](https://github.com/hackforla/website/assets/5543388/60980e7c-af69-49e6-9432-7be509edcc64)

on events page there is "All Teams"
![add-redirect-for-broken-links-4906_2](https://github.com/hackforla/website/assets/5543388/dac7ba79-2029-4470-b1cd-8882044cbf27)

working on the 'add-redirect-for-broken-links-4906' branch on my forked repo.

I was thinking to change the project-meetings underscore to match the events page "All Team" but wanted to check. Thanks in advance for your help!

**Comment by t-will-gillis** [comment]
Hey @yffu - Good question- thanks for asking! 

The short answer is that this needs to be changed in VRMS, which we don't have access to. I will ask Matt P. or Bonnie if they can edit this.

Here's the long answer: project managers for each project enter details about their meetings into the VRMS app. The "Project Meetings" (and "Events") pages are querying data from VRMS- see [api-events.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/utility/api-events.js). Here is the object data that the page receives from VRMS:  

See lower left: People Depot and Community of Practice: Engineering  

![Screenshot 2023-07-29 094119](https://github.com/hackforla/website/assets/40799239/6f1ffb43-e55a-40db-af2e-210030f114aa)

So the underscore on the "Project Meetings" page is coming from the entry for "dsc" in People Depot's VMRS.

**Comment by t-will-gillis** [comment]
@MattPereira could you edit People Depot's VMRS entry for "dsc" in their Thursday 4-5 meeting? Currently it there is an underscore, so could this be changed to a blank "" or maybe "Weekly meeting" ? Last I heard, no one at People Depot has access to VMRS...

**Comment by MattPereira** [comment]
@t-will-gillis got u fam its a blank string now `""`

also i'll reach out to fang to ensure he has access

**Comment by yffu** [comment]
Thanks for the answer @t-will-gillis. It makes sense that it's from vrms so that it's flexible. Much appreciate the explanations and the examples in the screenshots.
