### ISSUE TITLE
Update "No Results" Component to be Reusable Across Filters

### ISSUE THREAD

**Issue by chrismenke45** [hackforla/website#4912]
### Overview
The "No Results" Component that shows when to many filters have been applied on the Toolkit Page needs to be updated so it can be reused on other filters

### Action Items
- [ ] Create reusable "No Results" component in the [assets/js/elements folder](https://github.com/hackforla/website/tree/gh-pages/assets/js/elements) that takes in list of all filters being applied and returns a component that lists them out and explains no results match all those filters.
- [ ] Include this script in [toolkit.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/toolkit.js)
- [ ] Implement the included function in [toolkit.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/toolkit.js) (No visual changes should have occurred)

### Resources/Instructions
- [Instructions](https://github.com/hackforla/website/issues/4769#issuecomment-1592092127) on how to implement the no results message to match toolkit page message

**Comment by chrismenke45** [comment]
This is one of the issues for ER #4769

**Comment by chrismenke45** [comment]
I am taking a break from HFLA and will not be able to complete this issue.

**Comment by Adastros** [comment]
Closing this issue since issue #4903 addresses the same issue and was completed.
