### ISSUE TITLE
ER: Update Zoom Link on Meetings and Agendas Wiki Page

### ISSUE THREAD

**Issue by LRenDO** [hackforla/website#4918]
### Emergent Requirement - Problem
The Zoom link for the Sunday All Team Meeting is incorrect on the [Meetings and Agendas](https://github.com/hackforla/website/wiki/Meetings-and-Agendas) page.

### Issue you discovered this emergent requirement in
- No connected issue. It was discovered when trying to log into Sunday Meeting

### Date discovered 
6/29/23

### Did you have to do something temporarily
- [ ] YES
- [X] NO

### Who was involved
@roslynwythe

### What happens if this is not addressed
Developers that use the [Meetings and Agendas wiki page](https://github.com/hackforla/website/wiki/Meetings-and-Agendas) to find the meeting link will not be able to access the meeting if they do not have a Google Calendar invite (invite list gets full periodically) or if they still have the old link.

### Resources
- [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
In the "Website Team Meeting (all roles)" section of the [Meetings and Agendas](https://github.com/hackforla/website/wiki/Meetings-and-Agendas#website-team-meeting-all-roles) replace

`[Zoom](https://us02web.zoom.us/j/4451450308?pwd=U0JobzZqN0xGSXBUUkRsNlB5YzJiQT09)`

with

 `[Zoom](https://us02web.zoom.us/j/82177492860?pwd=UGNYdmJXMXgvVmZiSGtETTR4VGV6Zz09)`. 

This change should be made according to the instructions in the [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) page.

Though we are not currently making changes to the old wiki, in this instance it may be prudent to make the edit since the old wiki is linked to the [Project Board Meeting Info Card](https://github.com/hackforla/website/projects/7#card-80841329) and developers have reached out recently to get this link in Slack and in other meetings. However, if we plan to change the link on the card and the new wiki is going to be updated soon, editing the old wiki may not be necessary.

**Comment by LRenDO** [comment]
Hi @roslynwythe! I know we are typically not changing the old wiki, but I thought in this case, it might be prudent since developers have been asking if the link has changed in Slack and in other meetings.  I included two options for this issue. The first with changing the old wiki and the second without.  Please let me know which one I should create and if any changes need to be made to it. Thanks!

# Draft Issue
### Option 1 - Change Old Wiki and Record Update for New Wiki
### Overview
We need to update the Zoom link for the Sunday All Roles Team Meeting on the [Meetings and Agendas](https://github.com/hackforla/website/wiki/Meetings-and-Agendas) page, so that team members who want to join the Sunday meeting and have the old link or no longer have an invite are able to find the correct link and attend the meeting.

We are currently moving the wiki to a new repo and would not normally update the old wiki. However, for this update we will edit the old wiki as well as provide the updates for the new wiki according to the instructions for [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/)

### Action Items
- [ ] In the "Website Team Meeting (all roles)" section of the [Meetings and Agendas](https://github.com/hackforla/website/wiki/Meetings-and-Agendas#website-team-meeting-all-roles) replace 
`[Zoom](https://us02web.zoom.us/j/4451450308?pwd=U0JobzZqN0xGSXBUUkRsNlB5YzJiQT09)` 
with 
`[Zoom](https://us02web.zoom.us/j/82177492860?pwd=UGNYdmJXMXgvVmZiSGtETTR4VGV6Zz09)`
- [ ] Copy the entire [Meetings and Agendas](https://github.com/hackforla/website/wiki/) page including the edit just made and save the page
- [ ] Paste the page into a comment on below (on this issue)
- [ ] Add a link to the comment just posted to the `Content to be Added/Edited in New website-wiki Repo` section of the [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki#content-to-be-addededited-in-the-new-website-wiki-repo).
- [ ] Change the project board column for this issue to the `Questions / In Review` column
- [ ] Add `ready for dev lead` label to this issue

### Resources/Instructions
- [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/)

### Option 2 - Record Update for New Wiki Only
### Overview
We need to update the Zoom link for the Sunday All Roles Team Meeting on the [Meetings and Agendas](https://github.com/hackforla/website/wiki/Meetings-and-Agendas) page, so that team members who want to join the Sunday meeting and have the old link or no longer have an invite are able to find the correct link and attend the meeting.

We are currently moving the wiki to a new repo and are not updating the old wiki. Refer to [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/) for instructions.

### Action Items
- [ ] Copy the entire [Meetings and Agendas](https://github.com/hackforla/website/wiki/) page (Clicking the edit button in the upper right will allow you to copy the markdown. Close out the window or click back to avoid saving inadvertent changes the page.)
- [ ] Paste the page into a comment on below (on this issue)
- [ ] In the `Website Team Meeting (all roles)` section of the comment you created, replace 
`[Zoom](https://us02web.zoom.us/j/4451450308?pwd=U0JobzZqN0xGSXBUUkRsNlB5YzJiQT09)` 
with 
`[Zoom](https://us02web.zoom.us/j/82177492860?pwd=UGNYdmJXMXgvVmZiSGtETTR4VGV6Zz09)`
- [ ] Add a link to the comment just posted to the `Content to be Added/Edited in New website-wiki Repo` section of the [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki#content-to-be-addededited-in-the-new-website-wiki-repo).
- [ ] Change the project board column for this issue to the `Questions / In Review` column
- [ ] Add `ready for dev lead` label to this issue

### Resources/Instructions
- [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/)

**Comment by roslynwythe** [comment]
Hi @LRenDO this looks good.  Please proceed with writing the issue that you outlined in Option 1.  Or if you do not wish to create the new issue, no problem, just unassign yourself from this ER.  Thank you.

**Comment by LRenDO** [comment]
- @roslynwythe thanks! Created the issue #4931. Added ready for product label to the issue.

**Comment by roslynwythe** [comment]
Hi @LRenDO Please put the new issue on the Project Board so that it becomes visible to Bonnie.  Our zoom meeting links may be changing shortly so she may want to hold off on the issue until the new link is available.

**Comment by LRenDO** [comment]
@roslynwythe thanks for catching that. It's all set. Sounds good.

**Comment by roslynwythe** [comment]
Hi @LRenDO it would also be a good idea to include a "Prerequisites" section.   Sometimes I forget but we've been adding this section especially to our good first issues, because we have been getting some developers self-assigning to good first issues who are not associated with Hack for LA.  Here it is: 
```
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.
```

**Comment by LRenDO** [comment]
- @roslynwythe  Good call. Updated in #4931.

**Comment by LRenDO** [comment]
- The associated issue #4931 was updated to reflect the change that we now want to remove all of the Zoom links rather than update them [see request for revision](https://github.com/hackforla/website/issues/4931#issuecomment-1639077809).
