### ISSUE TITLE
Update design of Home Page and global elements

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#492]
### Overview
Update design of Home Page and revise global elements. A new Projects page is to be created and the current Projects section of the home page will be redesigned. This design update is an opportunity to introduce revisions to style elements found on the website globally, including navigation bar, footer, margins and spacing, and font colors and weights.

### Action Items
- [ ] Create wireframe for updated home page
- [ ] Create mockup for updated home page

### Resources/Instructions
https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205

**Comment by ExperimentsInHonesty** [comment]
duplicate
