### ISSUE TITLE
Comment out broken Test Site link for Engage project

### ISSUE THREAD

**Issue by arfgit** [hackforla/website#4924]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to comment out the non-functional "Test Site" for the Engage project to prevent users from encountering dead links on our site.

### Details
The Engage project has links that are currently leading to non-existent pages. This includes the "Test Site" link. This issue aims to temporarily hide this link from the website's visitors until we have the correct and functioning links in place.

### Action Items
- [x] Go to the [engage.md](https://github.com/hackforla/website/blob/gh-pages/_projects/engage.md) file in the GitHub repository.
- [x] Identify the lines containing (_**only**_) the "Test Site" link.
- [x] Comment out both the line beginning with ` - name: ...` as well as the line with `   url: ...` so the "Test Site" link will not be rendered on the live website. In Markdown, this can be done by placing a '#' at the start of each line. If you are using VSCode, you can highlight the line(s) to be commented out, then select 'Ctrl/Cmd' + '/' to automatically insert the '#'s.
- [x] Confirm that both links are no longer visible on the live site by running the site locally on Docker and provide before and after screenshots.

### Resources/Instructions
[Engage](https://www.hackforla.org/projects/engage) project page
Associated ER: https://github.com/hackforla/website/issues/4594

**Comment by ExperimentsInHonesty** [comment]
@arfgit If you are ready for a dev lead or merge team member to review this issue to see if its ready for prioritization, then add the `ready for dev lead` label.  If you are a member of the merge team and believe this issue is ready for prioritization and needs no further review, add the `ready for prioritization` label.

**Comment by brianf4** [comment]
i. **Availability**: Tuesday - Thursday (Mornings)
ii. **ETA**: 1-3 days
