### ISSUE TITLE
ER: Modify the current GitHub Actions PR comment

### ISSUE THREAD

**Issue by SAUMILDHANKAR** [hackforla/website#5002]
### Emergent Requirement - Problem
Currently, CodeQL blocks merging a PR only if the severity level of security alerts is high/critical/error. To see a complete list of alerts generated because of a PR, a reviewer can use a custom link to view them. It would be really useful for the reviewers if we can add this info in the comment generated by GitHub actions when a PR is created.

### Issue you discovered this emergent requirement in
- In PR #4886, the CodeQL alerts generated because of this PR can be viewed using the link https://github.com/hackforla/website/security/code-scanning?query=pr%3A4886+is%3Aopen which follows the format ```https://github.com/hackforla/website/security/code-scanning?query=pr%3A[REPLACE WITH PR#]+is%3Aopen```. This info should be made available in [this comment](https://github.com/hackforla/website/pull/4886#issuecomment-1608567409).

### Date discovered 
6/26/2023

### Did you have to do something temporarily
- [ ] YES
- [X] NO

### Who was involved
@roslynwythe @t-will-gillis @SAUMILDHANKAR 

### What happens if this is not addressed
- It would result in extra work for PR reviewers to see the additional CodeQL alerts generated because of a PR.

### Resources
For more information about GitHub code scanning, check out [the documentation](https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning).
[Code Scan Results](https://github.com/hackforla/website/security/code-scanning)
[GitHub Actions](https://docs.github.com/en/actions)

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team
- [x] Let a Team Lead know

### Potential solutions [draft]
Add a template URL like ```https://github.com/hackforla/website/security/code-scanning?query=pr%3A[REPLACE WITH PR#]+is%3Aopen```, in the file: https://github.com/hackforla/website/blob/gh-pages/github-actions/pr-instructions/pr-instructions-template.md

**Comment by SAUMILDHANKAR** [comment]
@roslynwythe This ER is ready for PM approval. Please let me know if more information is required. Also, I have added this to the project board (ER). Hope that is fine. Thanks for your guidance.

**Comment by roslynwythe** [comment]
The issue described is not necessary at this time, since code annotations will be displayed for all members of website-write.
