### ISSUE TITLE
COP page, Engineering section: Update meeting day

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5003]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to update the information for the Engineering Community of Practice (COP) so that visitors to the website can find accurate and up-to-date information.

### Action Items
- [x] In your IDE, find the _data/internal/communities/engineering.yml file [^1] and make the following change:
  - [x] Change
    ```
    meeting-times: Wednesdays 6:00-7:00 pm PT
    ```
    to
    ```
    meeting-times: Thursdays 6:00-7:00 pm PT
    ```
- [x] Using Docker, verify the changes by checking the Engineering section of the COP page [^2] in mobile, tablet, and desktop views

### Resources/Instructions
- Original request copied into this comment for future reference: https://github.com/hackforla/website/issues/4948#issuecomment-1639479285
[^1]: Directory to find the page once you have it in your IDE: `_data/internal/communities/engineering.yml`
[^2]: COP page: https://www.hackforla.org/communities-of-practice

**Comment by MattChau01** [comment]
i. Availability: Friday & Saturday
ii. ETA: EOD Saturday

**Comment by MattChau01** [comment]
Hi team,

I created a pull request for this issue: https://github.com/hackforla/website/pull/5112

i. I will be available via Slack on Saturday and free on Monday.
ii. Issue is completed.
