### ISSUE TITLE
Audit for img tags ending with a slash in file: _includes/about-page/about-card-metrics.html

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5018]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.  In this issue we will audit a single code file for all instances of img HTML tags ending with a slash, and will record each instance found in a spreadsheet.  

### Action Items
- [x] Open the sheet HfLA-Website: img Tag Audit spreadsheet[^1]
- [x] In your local IDE, navigate to Resource[^2]
- [x] Audit Resource[^2] to find any and all instances of img HTML tags ending with a slash (<img.../>) 
- [x] For each instance found in Resource[^2], create a new row in the `img with Ending Slash` sheet
   - [x] Enter **_includes/about-page/about-card-metrics.html** into the `Path to file` column of the spreadsheet
   - [x] Copy the img tag (with brackets) into the `Line of Current Code` column
- [x] After all instances have been recorded in the sheet, add the `ready for dev lead` label to this issue and move it to the `Questions/In Review column`

### For merge team/dev lead
- [x] After reviewing the issue
   - [x] Remove the `ready for dev lead` label and apply the `Ready for Prioritization` label.
   - [x] Open #4922 and check off this issue in the Dependencies section. 
  
### Resources/Instructions
[^1]: [HfLA-Website: img Tag Audit (Roll out plan #4362)](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0)
[^2]: **_includes/about-page/about-card-metrics.html**

[^3]: [`DR: img tag` documentation comment](https://github.com/hackforla/website/issues/4363#issuecomment-1493176038)

This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0) and resulted from Epic #4922 and Rollout #4362

**Comment by whitneywind** [comment]
Availability: 7/26 afternoon
ETA: 7/26

**Comment by LRenDO** [comment]
Hi @whitneywind! Thanks for taking the time to find these tags! It looks like you got most of them. I believe the one on line 25 didn't make it to the spreadsheet though. Please add it to the spreadsheet and then add back the `ready for dev lead` label.  Thanks!

**Comment by whitneywind** [comment]
@LRenDO Ah, not sure how I missed that. Got it now. Thank you!

**Comment by LRenDO** [comment]
@whitneywind Looks good! Thanks for adding it in and for taking the time to contribute to the website!

**Comment by ExperimentsInHonesty** [comment]
@LRenDO You added a `Ready for Prioritization` label to this issue in the Questions and Review column.  Usually I don't see issues with that label in this column (usually its because an issue has been drafted and the tech lead is ready for product to review it and put it in the prioritized backlog.   Since this issue is already being worked on, what do you think is the next step for this issue?

**Comment by LRenDO** [comment]
Hi @ExperimentsInHonesty! I added the`ready for prioritization` label per the instructions for the merge team on this issue after reviewing the issue. If the instructions for the merge team are incorrect or incomplete, I'm happy to change whatever needs to be changed.  It did seem strange that it said `ready for prioritization`, but this is my first non-pull request issue with a dependency so I thought I just missed something.

**Comment by LRenDO** [comment]
@ExperimentsInHonesty Spoke with @roslynwythe at the dev meeting today. The plan is close the issue and to update the template. Thanks!

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty @LRenDO I apologize, my instruction was incorrect.  I've since fixed the instructions in the template and in the outstanding issues.

**Comment by LRenDO** [comment]
All good! And thanks for taking the label off @roslynwythe. I missed it when I closed the issue.
