### ISSUE TITLE
Audit for img tags ending with a slash in file: _includes/about-page/about-card-executive-letter.html

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5019]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.  In this issue we will audit a single code file for all instances of img HTML tags ending with a slash, and will record each instance found in a spreadsheet.  

### Action Items
- [x] Open the sheet HfLA-Website: img Tag Audit spreadsheet[^1]
- [x] In your local IDE, navigate to Resource[^2]
- [x] Audit Resource[^2] to find any and all instances of img HTML tags ending with a slash (<img.../>) 
- [x] For each instance found in Resource[^2], create a new row in the `img with Ending Slash` sheet
   - [x] Enter **_includes/about-page/about-card-executive-letter.html** into the `Path to file` column of the spreadsheet
   - [x] Copy the img tag (with brackets) into the `Line of Current Code` column
- [x] After all instances have been recorded in the sheet, add the `ready for dev lead` label to this issue and move it to the `Questions/In Review column`

### For merge team/dev lead
- [ ] After reviewing the issue
   - [ ] Remove the `ready for dev lead` label and close the issue.  
   - [ ] Open #4922 and check off this issue in the Dependencies section. 
  
### Resources/Instructions
[^1]: [HfLA-Website: img Tag Audit (Roll out plan #4362)](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0)
[^2]: **_includes/about-page/about-card-executive-letter.html**

[^3]: [`DR: img tag` documentation comment](https://github.com/hackforla/website/issues/4363#issuecomment-1493176038)

This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0) and resulted from Epic #4922 and Rollout #4362

**Comment by JanineSooThow** [comment]
Availability for this week: Tuesday, Thursday
My estimated ETA for completing this issue: Hopefully by Friday 11th August (New Zealand time)

**Comment by JanineSooThow** [comment]
Hi everyone, I can't find "Resource" in my IDE(VS Code) as per the action item instructions. I am just wondering if this has been renamed or changed by any chance? 
There is a folder called "resources" under the "_design-system" folder but I am not sure if this is the one. I have looked in every folder and file for "Resource" (So I hope I am not going blind :D ) Thank you so much!

**Comment by JanineSooThow** [comment]
question answered on Slack channel - changed status back to "In Progress"

**Comment by JanineSooThow** [comment]
Provide Update
1. Progress: completed the issue - See row 47 in the "img with ending Slash sheet", added the label "Ready for dev lead" to this issue and moved it to the "questions/in review column"

Please let me know if I have done this correctly, thank you!

**Comment by roslynwythe** [comment]
Hi @JanineSooThow Thank you for providing the information regarding the img tag in the spreadsheet.  I'll close this issue as completed.  

Thank you also for leaving the above comment.  However the first part of that comment, about how long it took you to finish the pre-work, actually should be posted in your pre-work issue, so for the sake of completeness, please cut out that portion of your comment and paste it into a new comment in your pre-work checklist.   The update part was perfect!

**Comment by roslynwythe** [comment]
Hi @JanineSooThow Thank you for providing the information regarding the img tag in the spreadsheet.  I'll close this issue as completed.  

Thank you also for leaving the above comment.  However the first part of that comment, about how long it took you to finish the pre-work, actually should be posted in your pre-work issue, so for the sake of completeness, please cut out that portion of your comment and paste it into a new comment in your pre-work checklist.   The update part was perfect!
