### ISSUE TITLE
img Tag Refactor: includes/about-page/about-card-accomplishments.html 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5027]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.  

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-accomplishments.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img src="/assets/images/about/wins-card-mobile.svg" alt="Wins card: contributors' names, teams and roles, and testimonials of their accomplishments." />
```
to
```
<img src="/assets/images/about/wins-card-mobile.svg" alt="Wins card: contributors' names, teams and roles, and testimonials of their accomplishments.">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  **Only change the single instance specified above**.  Do not leave any blank spaces before the closing bracket.  
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-accomplishments.html
2. Webpage(s): https://www.hackforla.org/about/#accomplishments
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

**Comment by roslynwythe** [comment]
Hi @ExperimentsInHonesty I added this Action Item to resolve confusion I have noted in recent PR reviews:

- [ ] The file may contain more than one instance of an img tag with a closing slash.  **Only change the single instance specified above**.  Do not leave any blank spaces before the closing bracket.

**Comment by jnomad21** [comment]
i.  I am working on this now and available now
ii. I will have this completed in the next 20 minutes
