### ISSUE TITLE
Setup Google Analytics on website

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#503]
### Overview
Setup Google Analytics on website. This includes implementation of code snippets, deciding on metrics to track, and set up of the dashboard.

Repeated visits to the various sections of the website will skew dashboard data and impede the team's ability to get an accurate picture of user behavior. GA provides a mechanism to exclude individual IP addresses from data collection. See instructions below.

### Action Items
- [x] Choose an analytics tool (e.g. Google Analytics, Matomo)
- [x] Implement analytics tool with website
- [x] Collect team members' IP address and exclude from dashboard analytics
- [x] Set up the GA dashboard to collect data of interest
- [x] Move #128 to the prioritized backlog

### Resources/Instructions
**Google Analytics**

Exclude IP address instructions: https://support.google.com/analytics/answer/1034840?hl=en

GA account setup: https://support.google.com/analytics/answer/1008015?hl=en
Tag setup: https://support.google.com/analytics/answer/1008080

**Matomo**
https://matomo.org
https://github.com/matomo-org/matomo/issues/13016

**Comment by ashlingam** [comment]
@wesrowe It turns out that Hotjar's free tier caps users at 3 funnels and doesn't allow page-specific recordings (only the default home page). Can Google Analytics service our needs entirely? If not, I looked into Mixpanel and their free tier appears to be more generous, including funnels and recordings by segment. Also, do we already have a Google Analytics account set up, or do we need to create one?

**Comment by wesrowe** [comment]
@harishlingam I don't believe there is a GA account already for the HfLA website. Might as well created a new one.
As for hotjar -- honestly, for the use cases I'm aware of GA would be adequate for understanding user behavior on our site. Recordings are typically useful at the margins, and we're not there yet. GA would be good to focus on as a next step.

**Comment by ashlingam** [comment]
@wesrowe That makes sense Wes. A new member of our team suggested looking at Matomo, an open-source GA alternative: https://matomo.org/get-matomo/, but the advantages it offers don't appear to be relevant to us. I will bring up getting GA set up in our next meeting.

**Comment by harishlingam** [comment]
Matomo JavaScript Tracking code: 


<script type="text/javascript">
  var _paq = window._paq || [];
  /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
  _paq.push(['trackPageView']);
  _paq.push(['enableLinkTracking']);
  (function() {
    var u="https://harishlingam.matomo.cloud/";
    _paq.push(['setTrackerUrl', u+'matomo.php']);
    _paq.push(['setSiteId', '1']);
    var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
    g.type='text/javascript'; g.async=true; g.defer=true; g.src='//cdn.matomo.cloud/harishlingam.matomo.cloud/matomo.js'; s.parentNode.insertBefore(g,s);
  })();
</script>

**Comment by ashlingam** [comment]
**Google Analytics code snippet:**

> 
> <script async src="https://www.googletagmanager.com/gtag/js?id=UA-167506267-1"></script>
> <script>
>   window.dataLayer = window.dataLayer || [];
>   function gtag(){dataLayer.push(arguments);}
>   gtag('js', new Date());
>   gtag('config', 'UA-167506267-1');
> </script>

**Comment by ashlingam** [comment]
A Google Analytics account has been created for HFLA under the webadmin@hackforla.org account. The GA snippet is to be pasted as the first item into the HEAD tag of every page we want to track.

**Comment by ExperimentsInHonesty** [comment]
Remove full story and replace with GA code https://github.com/hackforla/website/issues/503#issuecomment-633163692

**Comment by ExperimentsInHonesty** [comment]
If stable, next week, exclude these ips from GA
Bonnie: 107.184.87.14
CNK: 66.215.74.250 - same 6/14
Yuiko: 172.91.110.17
Stella: 47.136.122.181
Susan:  24.24.137.226
Ruben: 172.113.122.208
Danielle: 104.175.48.39
Josh B: 76.168.134.2

**Comment by ashlingam** [comment]
@wesrowe 

View: I have created a View titled "Master View." In the event something goes awry, the administrator can revert to the Master View to restore all reporting.

[Acquisition Report](https://analytics.google.com/analytics/web/#/report/trafficsources-overview/a167506267w233696729p219257270/): Under All Traffic > channels, I have added a Secondary dimension of Source/Medium. This will likely be a preferred view, until such time when UTM parameters are set, in which case the Source/Medium view would be preferred.

[Conversions Report](https://analytics.google.com/analytics/web/#/report/conversions-goals-overview/a167506267w233696729p219257270/): I have created conversion goals for all major pages, buttons, and social media links currently found on the website. Please add/remove conversion goals as a better picture emerges about what to track/not track.

**Comment by ashlingam** [comment]
At some point in the future, UTM tracking may be useful to track incoming traffic sources to the website. This requires the use of UTM URLs. For example, if the team wanted to measure the number of visitors arriving at the home page from the Hack for LA Facebook page, UTM tags would serve this purpose. 

UTM tags fall into one of four categories:
(1) Where is the traffic coming from?
(2) What type of traffic is it?
(3) What is the name of the marketing campaign you have created?
(4) What is the name or code associated with your marketing content?

Google provides the following tool to build campaign URLs: https://ga-dev-tools.appspot.com/campaign-url-builder/

The tracking link generated by this tool is then pasted in your creative content (e.g. blog post, Facebook post, Instagram post, etc.). Anytime someone clicks this link, this activity is recorded by Google Analytics.

**Comment by ashlingam** [comment]
@ExperimentsInHonesty 

The Google Analytics [Dashboard](https://analytics.google.com/analytics/web/#/dashboard/sAEuy9YsSIax7DbuH3iBpw/a167506267w233696729p219257270/) may be incorporated into the HFLA Organizational Dashboard via Google Data Studio. I would recommend doing so once a clearer picture of most valuable data has emerged. This way, all analytics information is consolidated in one place.

**Comment by ashlingam** [comment]
It may be appropriate to have the incoming digital marketer or product manager build a guide page for Google Analytics. A skeleton outline of topics to cover is begun here: https://github.com/hackforla/website/wiki/Digital-Marketing-Overview

**Comment by ExperimentsInHonesty** [comment]
Do your IPs match?  Yes or No answer.  If no, please also provide new ip, so we can see if there is a pattern.
@cnk @yuikomajima @leestella748 @ye-susan @ruben1s @DanielekPark 

Last week's ips
Bonnie: 107.184.87.14 - yes
CNK: 66.215.74.250 - yes
Yuiko: 172.91.110.17 - yes
Stella: 47.136.122.181 - 47.136.122.53 - same as last week on the third check
Susan:  24.24.137.226 - yes
Ruben: 172.113.122.208 - yes
Danielle: 104.175.48.39 - yes
Kian: 47.147.143.207 - yes
Hannah: 192.168.86.35 - yes
Eric: 98.184.221.144
Leo: 192.168.1.14

**Comment by ExperimentsInHonesty** [comment]
@harishlingam is there a reason to leave hotjar code on the website.  Does it do anything that we are not going to do via GA?

Please mention @ye-susan in your reply

**Comment by ExperimentsInHonesty** [comment]
Will coordinate with ops team and potentially John Ritchey on GA configuration.

**Comment by ashlingam** [comment]
1. Progress - Filters have been created for each of the above IP addresses.
2. Blocks - None
3. Availability - n/a
4. ETA - n/a

**Comment by ashlingam** [comment]
To add/remove IP address filters, please see instructions here: https://support.google.com/analytics/answer/1034823

Steps: (1) Click the Gear icon -> (2) Under View select the drop down, then select "All Web Site Data" -> (3) Click on Filters

**Comment by harishlingam** [comment]
@ye-susan @ExperimentsInHonesty I think it's worthwhile to leave the Hotjar code in place. Despite the restrictions on the free tier, 100 of 300 recordings still remain, and old recordings may be deleted to make way for new ones. 

Hotjar account credentials:
Username: webadmin@hackforla.org
Password: certyh-3xozcE-kargev

**Comment by ExperimentsInHonesty** [comment]
Find ga password for developer and move hotjar user/pass to secure folder

**Comment by ExperimentsInHonesty** [comment]
@harishlingam - sorry to bother you with this, but I have no idea where the Google Analytics password is.  Do you?

**Comment by ExperimentsInHonesty** [comment]
@ExperimentsInHonesty will email @harishlingam to see if I can get credentials

**Comment by harishlingam** [comment]
@ExperimentsInHonesty Here are the login credentials for GA:

Username: webadmin@hackforla.org
Password: pezmuq-jaJja6-suhbyn

**Comment by alexandrastubbs** [comment]
Log-in information spreadsheet has been added to HFLA Site team folder. GA log-in information is available there.

**Comment by alexandrastubbs** [comment]
We should create a guide for how to use GA on any project site. Good project for a special project coordinator. 

Follow up with Bonnie on this.

**Comment by alexandrastubbs** [comment]
@harishlingam sorry to bother you again - in order to log-in to GA, there is a second layer of identification confirmation that involves a text message to the number on file. Would you be able to go in and change the phone number to mine? 201-572-1361. From there I can leave as is or change to whoever will be using the account the most. Let me know!

**Comment by alexandrastubbs** [comment]
@harishlingam disregard, Bonnie was able to help update settings. Thanks!

**Comment by alexandrastubbs** [comment]
Progress - Working on learning GA.
Blocks - None
Availability - n/a
ETA - TBD, aiming for 8/16

**Comment by alexandrastubbs** [comment]
Added Hotjar log-in information to the Google Sheet for log-ins.

**Comment by alexandrastubbs** [comment]
Check status of this issue: https://github.com/hackforla/civic-opportunity/issues/35

**Comment by alexandrastubbs** [comment]
Progress: none yet 
Blocks: was moving this week
Availability: some time this week to start digging in 
ETA: tbd, hoping to have a better idea of what needs to be done this week

**Comment by Samhitha444** [comment]
- [ ] All the links in this issue will need to be checked to see if we have access
- https://github.com/hackforla/website/issues/128
  - [ ] Have access, its located in ____
  - [x] public
- [Exclude internal traffic](https://support.google.com/analytics/answer/1034840?hl=en)
  - [ ] Have access, its located in ____
  - [x] public
- [Set up Analytics for a website and/or app](https://support.google.com/analytics/answer/1008015?hl=en)
  - [ ] Have access, its located in ____
  - [x] public
- [Set up the Analytics Google tag](https://support.google.com/analytics/answer/1008080)
  - [ ] Have access, its located in ____
  - [x] public
- https://matomo.org/
  - [ ] Have access, its located in ____
  - [x] public
- https://github.com/matomo-org/matomo/issues/13016
  - [ ] Have access, its located in ____
  - [x] public
 -   https://matomo.org/get-matomo/
  - [ ] Have access, its located in ____
  - [x] public
- https://analytics.google.com/analytics/web/#/report/trafficsources-overview/a167506267w233696729p219257270/
  - [ ] Have access, its located in ____
  - [x] public
- https://analytics.google.com/analytics/web/#/report/conversions-goals-overview/a167506267w233696729p219257270/
  - [ ] Have access, its located in ____
  - [x] public
- [Campaign URL Builder](https://ga-dev-tools.appspot.com/campaign-url-builder/)
  - [ ] Have access, its located in ____
  - [x] public
 - [Digital Marketing Overview](https://github.com/hackforla/website/wiki/Digital-Marketing-Overview)
  - [ ] Have access, its located in ____
  - [x] public
- [Create and manage view filters](https://support.google.com/analytics/answer/1034823)
  - [ ] Have access, its located in ____
  - [x] public
- [ Google Analytics and Mixpanel Modeling Analysis #35 ](https://github.com/hackforla/civic-opportunity/issues/35)
  - [ ] Have access, its located in ____
  - [x] public
