### ISSUE TITLE
img Tag Refactor: Join Us page - banner-icon.svg

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5030]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/join-us.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="header-hero-image" src="/assets/images/join-us/banner-icon.svg" alt="" />
```
to
```
<img class="header-hero-image" src="/assets/images/join-us/banner-icon.svg" alt="">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  **Only change the single instance specified above**.  Do not leave any blank spaces before the closing bracket.  
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: [INSERT LINK TO FILE]
2. Webpage(s): https://www.hackforla.org/join
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

**Comment by LukeLowrey2** [comment]
Availability: Saturday 7-29-2023, Sunday 7-30-2023, and Tuesday 8-1-2023
ETA: Tuesday 8-1-2023

**Comment by LukeLowrey2** [comment]
Progress: 
- Created new branch titled "change-join-us-banner-img-slash-5030"
- Deleted old banner img tag "<img class="header-hero-image" src="/assets/images/join-us/banner-icon.svg" alt="" />
- Added new banner image tag "<img class="header-hero-image" src="/assets/images/join-us/banner-icon.svg" alt="">

Blockers: Setting up the commit to be pushed. I would like to know proper protocol when creating a pull request 
- What branch I should be on 
- When to pull upstream

Availability: Sunday 7-31-2023 10am-1pm PT, Tuesday 8-1-2023 3pm-6pm PT

ETA: Tuesday 8-1-2023

<img width="1469" alt="Screen Shot 2023-07-29 at 1 48 03 PM" src="https://github.com/hackforla/website/assets/89051599/93b2bdeb-30fc-42ba-8e4f-1573c5d21f66">

**Comment by LukeLowrey2** [comment]
Progress:
-Pull request for LukeLowrey2:change-join-us-banner-img-slash-5030 has been created


Availability: 
-Tuesday 8-1-23 3-4pm PT

ETA: 
-Tuesday 8-1-2023

**Comment by LukeLowrey2** [comment]
Progress:
-Action items finished in this issue 
-Pull request was created
-Unfortunately I did not add to the pull request description or input the issue number in the pull request after it was created
- I am currently not seeing the pull request (LukeLowrey2:change-join-us-banner-img-slash-5030) in the pull request section for update
-Keeping the team informed of my mistake and wanting to know further steps

Blockers
-Not sure what the next steps are in getting this issue completed and would like further clarification 

Availability 
- Friday 8/11 9am-11am
- Sunday 8/13 9am-12pm
- Tuesday 8/15 5pm-7pm

ETA:
-Depending on clarification of next steps

Apologies for my mistake and looking forward to correction
