### ISSUE TITLE
img Tag Refactor: Join Us page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5031]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `pages/join-us.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="join-us-card-img" src="/assets/images/join-us/partner-with-us-icon.svg" alt="" />
```
to
```
<img class="join-us-card-img" src="/assets/images/join-us/partner-with-us-icon.svg" alt="">
```
- [x] The file may contain more than one instance of an img tag with a closing slash.  **Only change the single instance specified above**.  Do not leave any blank spaces before the closing bracket.  
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html
2. Webpage(s): https://www.hackforla.org/join
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

**Comment by bilalshaikh292** [comment]
Heyy Is the issue Still Open I would like to contribute ?

**Comment by roslynwythe** [comment]
Hi our issues are only open to Hack for LA members.   Please see
https://hackforla.org/join.  You don't have to live in L.A to join!

**Comment by bilalshaikh292** [comment]
ok @roslynwythe , I am Not From US .I would like to Contribute If Possible ,If there is any way Please Let me know.

**Comment by roslynwythe** [comment]
Yes @bilalshaikh292 you are welcome to join Hack for LA even if you are not from the U.S. but you will you should attend an onboarding session.  Please see https://www.hackforla.org/join

**Comment by roslynwythe** [comment]
@Josiah-O is there a reason this issue was not moved into the Prioritized Backlog?
