### ISSUE TITLE
Research and proposals for project filter implementation

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#506]
### Overview
Research and proposals for project filter implementation

### Dependency
implementation of the filter #254

### Action Items
- [x] Look at existing site architecture
- [x] Create wiki page documenting existing site architecture (Susan) (moved to issue #529)
- [x] Perform research (i.e. literature, online resources, dev team members) (Tyler) (#254)
- [x] Formulate proposals for implementation (Susan, Tyler and Cnythia)

**Comment by ye-susan** [comment]
The wiki for [Structure  of Project Cards and Project Pages](https://github.com/hackforla/website/wiki/Structure-of-Project-Cards-and-Project-Pages) is up

**Comment by ye-susan** [comment]
1. Progress: Still writing draft of rest of the site's architecture (so far just the project cards and project pages are up)
2. Blocks: none at this time, although any feedback is appreciated - especially on how detailed the wiki should be
2. ETA: Aiming to finish 5/24

**Comment by ye-susan** [comment]
Created new [issue #529](https://github.com/hackforla/website/issues/529), just for the wiki documentation. I'll be updating on my progress in that issue instead.

**Comment by ExperimentsInHonesty** [comment]
Un - icebox this when issue #254 update of is completed.
