### ISSUE TITLE
ER: update Lucky Parking and Citizen Engagement info

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#5098]
### Emergent Requirement - Problem
We need to create two new issues 

### Issue you discovered this emergent requirement in
- #4151

### Date discovered 
2023-07-25

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@Josiah-O @ExperimentsInHonesty

### What happens if this is not addressed
The information is not accurate

### Resources
- https://github.com/hackforla/website/blob/c4fc57243f0a4c87061f814e01eeb1f83aeb9c70/pages/citizen-engagement.html#L49-L54

![ALWATER VILLAGE 1](https://github.com/hackforla/website/assets/37763229/4ff4ecb3-99ad-450f-8c53-e8ef52818414)

Project file: https://github.com/hackforla/website/blob/gh-pages/_projects/lucky-parking.md

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]

A new issue will need to be created 
# Issue 1

### Overview
We need to add the logo for Atwater Village to the Citizen Engagement page so that we accurately represent the relationships the projects have.

- The following page will have to be updated
  - https://github.com/hackforla/website/blob/gh-pages/_data/internal/partners.yml with the partner name under Citizen Engagement
- The image for Atwater Village will have to be uploaded to 
   - https://github.com/hackforla/website/tree/gh-pages/assets/images/partners

# Issue 2 - 

### We need to add the partner Atwater Village to the Lucky Parking project, so that it can accurately show its partnerships

- [x] Add Atwater Village to Partnership field. This issue has already been written: #5809

**Comment by JessicaLucindaCheng** [comment]
- Issue 2 has already been written: #5809
- Issue 1 still needs to be written

**Comment by A-Wu5** [comment]
1. Tues - Fri 11AM-1PM
2. Today

**Comment by marioantonini** [comment]
i. Availability: Fr-Sat 10am-2pm
ii. ETA: 5/11/2024

**Comment by marioantonini** [comment]
@ExperimentsInHonesty 
Issue 1 was already created #6474 and fixed with merged PR #6505 so I decided to close this issue.
Let me know if I need to do anything specific outside of any automation that is already in place.
