### ISSUE TITLE
Audit for img tags ending with a slash in file: _includes/press.html

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5099]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.  In this issue we will audit a single code file for all instances of img HTML tags ending with a slash, and will record each instance found in a spreadsheet.  

### Action Items
- [x] Open the sheet HfLA-Website: img Tag Audit spreadsheet[^1]
- [x] In your local IDE, navigate to Resource[^2]
- [x] Audit Resource[^2] to find any and all instances of img HTML tags ending with a slash (<img.../>) 
- [x] For each instance found in Resource[^2], create a new row in the `img with Ending Slash` sheet
   - [x] Enter **_includes/press.html** into the `Path to file` column of the spreadsheet
   - [x] Copy the img tag (with brackets) into the `Line of Current Code` column
   - [x] Copy the img tag (with brackets) into the `Desired Line of Code` column but remove the trailing slash and any blank spaces before the closing bracket (>)
- [x] After all instances have been recorded in the sheet, add the `ready for dev lead` label to this issue and move it to the `Questions/In Review column`

### For merge team/dev lead
- [x] After reviewing the issue
   - [x] Remove the `ready for dev lead` label and close the issue.  
   - [x] Copy the issue number, then find the corresponding item in the Dependencies section of Epic #4922.  Replace the current text with `#[ISSUE NUMBER]`
  
### Resources/Instructions
[^1]: [HfLA-Website: img Tag Audit (Roll out plan #4362)](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0)
[^2]: **_includes/press.html**

[^3]: [`DR: img tag` documentation comment](https://github.com/hackforla/website/issues/4363#issuecomment-1493176038)

This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0) and resulted from Epic #4922 and Rollout #4362

**Comment by Ris345** [comment]
Availability: Weds 10pm-11pm, Thursday 7pm-9pm 
ETA: 08/21/23

**Comment by t-will-gillis** [comment]
@Ris345 - It appears that you have already completed two `Complexity: Small` issues. As noted on your "Prework Checklist", you should proceed with a `Complexity: Medium` after completing one `Complexity: Small` issue. Therefore, you are being unassigned from this issue.

**Comment by raviteja4117** [comment]
Availability for this week: Tuesday, Thursday
My estimated ETA for completing this issue: Hopefully by Friday 1st September

**Comment by LRenDO** [comment]
Hi @raviteja4117!

You did a great job adding all the instances of the img tag that needs the / removed on in press.html.  You have also added the correct label and moved the issue to the correct column to be reviewed.

I have a small request and a bit of clarification.
- [x] Please add `Home` to the `Page(s) on website (if applicable)` column in the row you added in the [spreadsheet](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0)
- [x] Ping me here with a comment once it's added
- It looks like you have created a pull request #5416 where you removed the slash from the file.  You did a great job with the PR there. However, it is beyond the scope of this issue.  Another issue in the future will be created for actually removing the tag.  For that reason, I will go ahead and close #5416 without merging.

**Comment by raviteja4117** [comment]
Hi @LRenDO 

Thank you for your feedback and guidance. I've added "Home" to the Page(s) on the website column for the row in the spreadsheet as requested. It's all set now! Thank you

**Comment by LRenDO** [comment]
Hi @raviteja4117! Looks great thanks for making the changes and taking the time to contribute to the website!
