### ISSUE TITLE
Prototype new styling for project home page banner images 

### ISSUE THREAD

**Issue by KianBadie** [hackforla/website#510]
### Overview
The way the banner images are displayed on project home pages currently have some issues in terms of cropping/zooming in. Prototype new styling rules to better display these images on mobile and desktop (desktop being the trickier of the two).

### Action Items
- [x] Apply mobile styling rules described [here](https://github.com/hackforla/website/issues/255#issuecomment-608226848) by @ddfridley to banner images
- [x] Post screenshots of mobile styling rules
- [x] Experiment with changing pixel dimensions of banner images to something more dynamic with desktop (em, vh, vw, ...)
- [x] Post screenshots of dynamic styling rules

### Resources/Instructions
- Original issue: #255 
- Attempt at summarizing above issue: https://github.com/hackforla/website/issues/255#issuecomment-623010067

**Comment by KianBadie** [comment]
Here are some initial before and after shots. There is room to fiddle around with the "after" shots (2nd images) to make them display better. Sorry again for lagging on this specific issue and not getting much done with it this week. I can have another go at it this week and and be more intentional with allocating time to it, because I do have a desire to work on this issue. But I think it is the second week I didn't produce anything on this specific issue, so if anyone wanted to assign it to someone else or if someone else really wanted to pick this up for quicker results or other reasons I would understand!

### Home Unite Us
![before-home-iphone6](https://user-images.githubusercontent.com/18221058/82138566-4256c600-97d6-11ea-9181-22041356e366.png)
![after-home-iphone6](https://user-images.githubusercontent.com/18221058/82138564-41259900-97d6-11ea-9929-e98bf0a82a58.png)

### Undebate
![before-undebate-iphone6](https://user-images.githubusercontent.com/18221058/82138572-4b479780-97d6-11ea-88a9-5f6fae0d91f4.png)
![after-undebate-iphone6](https://user-images.githubusercontent.com/18221058/82138571-4aaf0100-97d6-11ea-8115-26cfe97986b2.png)

### Civic Tech Index
![before-civic-iphone6](https://user-images.githubusercontent.com/18221058/82138591-6ca88380-97d6-11ea-88f5-48b3dd34ef4c.png)
![after-civic-iphone6](https://user-images.githubusercontent.com/18221058/82138589-6ca88380-97d6-11ea-9343-ceaab94a9a33.png)

**Comment by KianBadie** [comment]
So I did some fiddling around and reached some improvements:
- The images we asked for project banners were 1500x700px, which is a 2.14 aspect ratio. For mobile, I altered David's rules a bit by making the width 100vw (100% width of screen) and the height 46vw (46% width of screen). This resulted in a ratio around 2.14 across all phone screens that had much less image alterations compared to the original format
## New
![new-styling](https://user-images.githubusercontent.com/18221058/82624072-9545ca00-9b96-11ea-84e5-6e74f237ca8d.gif)
## Old
![old-styling](https://user-images.githubusercontent.com/18221058/82624080-9971e780-9b96-11ea-9866-1ee6feaf6a2d.gif)
- I tried keeping the same rules on desktop view to try to maintain the same ratio. However, at fullscreen, 46vw took up the size of the whole screen. It did keep the nicer ratio when the screen size shrunk though: 
## New
![new](https://user-images.githubusercontent.com/18221058/82624980-d048fd00-9b98-11ea-80b9-2cd38257ad65.gif)
## Old
![old](https://user-images.githubusercontent.com/18221058/82624996-d6d77480-9b98-11ea-8a28-9ef6425f3ae9.gif)
- To fix how large the image is on fullscreen, I made a max height of 75vh (75% height of screen). Which brings us back to where we started on full screen. But as the screen shrinks, that's when the benefits kick in. 
## Final Result
![final](https://user-images.githubusercontent.com/18221058/82625382-ce336e00-9b99-11ea-9568-5c5f4488f50d.gif)

Overall this will result in the pictures being smaller in most screen dimensions, as the picture resizes to maintain the styling rules. However, the new styling rules are more dynamic and reduce image altering, as you can see in the gifs.

**Comment by KianBadie** [comment]
This issue made me realize something. Initially, we asked for 1500x700px images because that is around the dimensions of the homepage hero image. However, the home page hero image has some cropping issues as well. When I said that 1500x700px should be the dimensions of the hero images for the project home pages, I did not know about this issue. That makes me think that the banner image issues are also a result of the dimensions themselves. Keeping the ratio on large screens would mean having really big images to maintain the ratio. Maybe a just as wide but shorter image would have been more friendly to work with. I'm sorry for the mishap!

We can try to work with what we have though, as I would imagine asking for new images with new dimensions could be a pain for teams.

**Comment by ExperimentsInHonesty** [comment]
@KianBadie will put in a pull request, @cnk will review it.
