### ISSUE TITLE
img tag refactor on donate-gif-text include 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5101]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/donation/donate-gif-text.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img
  class="donation-gif"
  src="/assets/images/about/hfla-donate.gif"
  alt=""
  />
```
to
```
<img class="donation-gif" src="/assets/images/about/hfla-donate.gif" alt=""/>
```
**- [ ] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.**
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/donation/donate-gif-text.html
2. Webpage(s): https://www.hackforla.org/donate, https://www.hackforla.org/join
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

**Comment by DorianDeptuch** [comment]
Availability: 7/30 6pm - 10pm, 7/31 afternoon
ETA: 7/31 evening

**Comment by DorianDeptuch** [comment]
Hi @roslynwythe,

In the description of the issue, the code describing the image tag is the same in the before and after code blocks. Did you mean to update the image tag to the following code instead?:

```
<img class="donation-gif" src="/assets/images/about/hfla-donate.gif" alt="">
```
