### ISSUE TITLE
Create 2FA Guide Page

### ISSUE THREAD

**Issue by daniellen00** [hackforla/website#511]
### Overview

All members of Hack for LA need to have 2FA in their Github. Most new members need instructions for doing this. Create page for website.

### Dependency 

[Guide template](https://github.com/hackforla/website/issues/514) 

### Action Items

- [x] UX Writing
   - [x] Review existing guide and other resources
   - [x] Organize the wording and define elements that should be on page
   - [x] Sign off
- [x] UI Mockup
   - [x] Design mockup
   - [ ] Coordinate with VRMS team about requirement for stats
   - [x] Sign off
- [ ] Development -Implement mockup:
   - [ ] Create new guide collection 
   - [ ] Create a guide template
   - [ ] Make it work for the 2FA content
   - [ ] Link from Getting Started guide

### Resources/Instructions

[VRMS Figma](https://www.figma.com/file/9c6pxjImN8MjHAZLH7zxYm/VRMS-Mocks?node-id=22816%3A0)
[2FA Instructions](https://github.com/hackforla/governance/issues/20)
[Google Doc Draft](https://docs.google.com/document/d/1Qc6OAorCbhKRQC_8570SHl6ad27cHjXD4dbjeiBYXX0/edit#)

### Resume

UX Writing: 

- Evaluated existing materials, identified and located missing information, created new presentation recommendations to reduce security compliance time and improve onboarding experience. 
- Communicate to funders, potential volunteers, and other interested stakeholders the specific value delivered by Hack for LA membership to workforce development goals.  

UI Mockup: 

- Design security compliance guide to improve new member onboarding and expand website assets.
- Communicate to funders, potential volunteers, and other interested stakeholders the specific value delivered by Hack for LA membership to workforce development goals.

Developers:

- Create a new collection in Jekyll / GitHub Pages to organize and deliver guide content to website
- Used Liquid and Vanilla JS to create new website content
- Integrate data from API to display real-time statistics of GitHub 2FA security compliance at initial onboarding to increase awareness of membership value

**Comment by daniellen00** [comment]
@ExperimentsInHonesty for UX Writing sign-off

**Comment by ExperimentsInHonesty** [comment]
This will be the first of many guides.  So like the project homepages and project cards, we will probably want some standardization, so that we can build from mark down files (like we have for the projects) to feed this design.

**Comment by yuikomajima** [comment]
Please see initial mockup here: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=695%3A3802

**Comment by ExperimentsInHonesty** [comment]
Make this whole page but leave off the vrms stats.  We will add them later.

**Comment by ExperimentsInHonesty** [comment]
go ahead and put the new mockup in this figma file tab: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=695%3A0

**Comment by ExperimentsInHonesty** [comment]
it looks like the action item is for me to review this and see if there are any changes required.  Also the next developer who has to do this @hannahlivnat should review it as well, and see if it makes sense to her, since she is doing this now.

**Comment by ExperimentsInHonesty** [comment]
@unassigned Hannah.  Mockup looks good.  Ready for Dev.

**Comment by ExperimentsInHonesty** [comment]
@alexandrastubbs made a suggestion to improve the 2FA app instructions (in case you already have one).

**Comment by ruben1s** [comment]
Update: I'm working on it.

**Comment by ruben1s** [comment]
Update: 
![screencapture-0-0-0-0-4000-guide-pages-2FA-2020-07-12-11_15_47](https://user-images.githubusercontent.com/33906590/87253576-27e54580-c431-11ea-8d5e-551f1f3fde38.png)
![screencapture-0-0-0-0-4000-guide-pages-2FA-2020-07-12-11_16_07](https://user-images.githubusercontent.com/33906590/87253579-2b78cc80-c431-11ea-8734-e5580942636f.png)

    Good: Finished 2FA page. 

    Bad: Had to tweak scss on page.

**Comment by ruben1s** [comment]
Updated git link scss.
![screencapture-0-0-0-0-4000-guide-pages-2FA-2020-07-12-11_45_00](https://user-images.githubusercontent.com/33906590/87254141-44837c80-c435-11ea-992b-6712f9c9bc0f.png)

**Comment by ExperimentsInHonesty** [comment]
new url: https://www.hackforla.org/guide-pages/2FA.html
