### ISSUE TITLE
ER: Events page link problem

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#5115]
### Emergent Requirement - Problem
On our [project-meetings](https://www.hackforla.org/project-meetings) and [events](https://www.hackforla.org/events/) pages the link to Access the data goes to their github instead of the project page on the hack for la website https://www.hackforla.org/projects/access-the-data

### Issue you discovered this emergent requirement in
- #4906

### Date discovered 
2023-07-30

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty @wanyuguan 

### What happens if this is not addressed
It dosen't fit with our current site experience and keeps people from seeing all their meetings, sdgs, etc.

### Resources
- https://www.hackforla.org/project-meetings
- https://www.hackforla.org/events/ 
- https://www.hackforla.org/projects/access-the-data

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
Figure out why this link is different than all the rest and return it to normal function

**Comment by t-will-gillis** [comment]
As of 8/7/23, the links for "Access the Data" on both the "Events" and the "Project Meetings" page are correct and directing to `https://www.hackforla.org/projects/access-the-data`.  Therefore closing this as 'resolved' 

![Screenshot 2023-08-07 100049](https://github.com/hackforla/website/assets/40799239/63cf40ef-4197-487b-83f3-34f8dd24a18c)
![Screenshot 2023-08-07 100055](https://github.com/hackforla/website/assets/40799239/bdde9faa-1631-473c-8b83-2eaa77b32819)
