### ISSUE TITLE
Communities of Practice information updates: Data Science

### ISSUE THREAD

**Issue by salice** [hackforla/website#5131]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to update the information for the Data Science Community of Practice (COP) so that visitors to the website can find accurate and up-to-date information.

### Action Items
- [x] In your IDE, find the _data/internal/communities/data-science.yml file [^1] and make the following change:
  - [x] Change
    ```
    meeting-times: Thursdays 8:00-9:00 pm PT
    ```
    to
    ```
    meeting-times: Mondays 7:00-8:00 pm PT
    ```
- [x] Using Docker, verify the changes by checking the Data Science section of the COP page [^2] in mobile, tablet, and desktop views

### Resources/Instructions
- Original request copied into this comment for future reference: https://github.com/hackforla/website/issues/5131#issuecomment-1666903729
[^1]: Directory to find the page once you have it in your IDE: `_data/internal/communities/data-science.yml`
[^2]: COP page: https://www.hackforla.org/communities-of-practice

**Comment by JessicaLucindaCheng** [comment]
# Original Request 
### Requestor
Sophia Alice (GitHub handle: salice) 
### Request
Update Meeting Time for Data Science CoP: it is now on Mondays at 7 PM PDT

**Comment by JessicaLucindaCheng** [comment]
@salice I have updated the issue for the meeting time to be updated on the [Communities of Practice page](https://www.hackforla.org/communities-of-practice). 

However, to update the meeting time on the [Events page](https://www.hackforla.org/events/), please see the [VRMS User Guide](https://github.com/hackforla/VRMS/wiki/User-Guide). The HackforLA.org website gets the meeting times from the updates made to the project's meeting data in vrms.io to update the Events page.

**Comment by ExperimentsInHonesty** [comment]
@salice please connect with @JackHaeg to change the meeting time in vrms.

**Comment by ha-bach** [comment]
Availability: anytime.
ETA: should be 2 days.
