### ISSUE TITLE
Create 'Anatomy of a Good GitHub Issue' Page

### ISSUE THREAD

**Issue by daniellen00** [hackforla/website#514]
### Overview

Members of Hack for LA often create new GitHub Issues in project repos. Many new and current members need instructions for doing this in a standardized format. Create page for website.

### Dependency 
Guide template (no issue started yet)

### Action Items

- [x] UX Writing
   - [x] Review existing guide and other resources
   - [x] Organize the wording and define elements that should be on page
   - [x] Sign off 
- [ ] UI Mockup
   - [x] Design mockup
   - [x] Coordinate with VRMS team about requirement for stats
   - [x] Sign off
   - [x] check dependency status.  If dependency not cleared, put in icebox
- [ ] Development - Implement mockup:
   - [ ] Create guide based on template (see dependency)
   - [ ] Add to guide collection
   - [ ] Link from Toolkit homepage

### Resources/Instructions

[Github's Markdown Guide](https://guides.github.com/features/mastering-markdown/)
[Example of a Good Issue](https://github.com/hackforla/website/issues/511)
[Google Doc Draft](https://docs.google.com/document/d/16gsR6eeg13T26biIO-m__WKWhlcodix97DbkE2zudiU/edit#)
[GitHub's About Labels](https://help.github.com/en/github/managing-your-work-on-github/about-labels)
[GitHub Assignees](https://help.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users)
[GitHub's Milestones](https://help.github.com/en/github/managing-your-work-on-github/assigning-issues-and-pull-requests-to-other-github-users)

### Resume

UX Writing: 

- Evaluated existing materials, identified and located missing information, created new presentation recommendations to standardize GitHub Issues and improve GitHub onboarding experience. 
- Communicate to funders, potential volunteers, and other interested stakeholders the specific value delivered by Hack for LA membership to workforce development goals.  

UI Mockup: 

- Design GitHub Issue guide to improve member GitHub experience, streamline new member onboarding, and expand website assets.
- Communicate to funders, potential volunteers, and other interested stakeholders the specific value delivered by Hack for LA membership to workforce development goals.

Developers:

- Add to collection in Jekyll / GitHub Pages to organize and deliver guide content to website
- Use Liquid and Vanilla JS to create new website content
- Integrate data from API to display real-time statistics of GitHub membership at initial onboarding to increase awareness of HfLA membership value

**Comment by daniellen00** [comment]
Figma link: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=745%3A999

**Comment by daniellen00** [comment]
@ExperimentsInHonesty for review of ux writing and Figma layout (plus Development Action Items phrasing in this Issue)

**Comment by ExperimentsInHonesty** [comment]
@daniellen00 
I think we need to say something about the menu (for formatting vs using markdown)
Maybe right at the top where you have the link to markdown we could put a screenshot of the menu and let them know they have the option to write markdown or use the formatting menu

Also rounded corners

@harishlingam mentioned looking at the hack nights page or getting started for overall formatting.  Look at font weights and sizing

team agrees with pink background.

**Comment by ExperimentsInHonesty** [comment]
![Screen Shot 2020-05-31 at 11 37 17 AM](https://user-images.githubusercontent.com/37763229/83360087-77652b80-a333-11ea-8934-94164fcdc50b.png)

**Comment by ExperimentsInHonesty** [comment]
@daniellen00 Great job with the options.

@yuikomajima and the team did a little iteration on one of the pages for the top nav.  She is going to finish the top image, and this is all ready to go to development.

**Comment by ExperimentsInHonesty** [comment]
Please see mockups here: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=695%3A3802

**Comment by ye-susan** [comment]
1.  Progress: ~80% done with Github Issues Page (but not 'template-izing' it yet)
2.  Blocks: Need to figure out how to make this page into a working template 
3.  Availability: Open
4.  ETA: 6/30 for html page, TBD for template
