### ISSUE TITLE
img Tag Refactor: CONTRIBUTING.md  giphy-downsized-large.gif

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5146]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, open 'CONTRIBUTING.md' and navigate to Section 3.1.b
- [x] Remove the ending slash in the img HTML tag by changing
```
<img src="https://media.giphy.com/media/WT7SDqqKLWnjC1ppHV/giphy-downsized-large.gif" />
```
to
```
<img src="https://media.giphy.com/media/WT7SDqqKLWnjC1ppHV/giphy-downsized-large.gif">
```
**- [ ] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket. 
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/roslynwythe/website/blob/test-CONTRIB/CONTRIBUTING.md)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md
2. Webpage(s): https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md
3. This issue is part of #6453

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty we had planned to make all these img Refactor issues `good first issues` but since changes to CONTRIBUTING.md cannot be tested locally in the usual manner, it is a bit more complex than usual good first issues.  Do you think it still qualifies as a `good first issue`?  If so, please review the template and prioritize.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe Could it be checked in a comment on the issue or pull request?  Also, yes, make it a small or medium at your discretion

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty Could we instruct the dev to delete the pr instructions comment created by the bot, and add a comment something like this:

Want to review this pull request? Take a look at [this documentation](https://github.com/hackforla/website/wiki/How-to-Review-Pull-Requests) for a step by step guide!  However in step 3, simply view the changes by browsing to the address:

https://github.com/roslynwythe/website/blob/test-CONTRIB/CONTRIBUTING.md

**Comment by ExperimentsInHonesty** [comment]
Note for an example 
https://github.com/t-will-gillis/website/blob/fix-bug-sch-thursday-inactive-4768/CONTRIBUTING.md
https://github.com/t-will-gillis/website/tree/fix-bug-sch-thursday-inactive-4768

**Comment by roslynwythe** [comment]
- I created issue #5165 so that pr instructions will provide guidance how to preview changes in CONTRIBUTING.md, and made this issue dependent on that issue.  If we should decide to go ahead with this issue before #5165 is ready, add this Action Item:
- [ ] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.  
```
For Reviewers: Do not test changes locally, rather test changes at [REPLACE WITH TEST URL]
```
Also, add the text "(also store the test URL for use in a later step)" to the end of the Action Item "Changes to CONTRIBUTING.md cannot be tested locally..."

**Comment by roslynwythe** [comment]
This issue is not needed.  The slash no longer appears in the referenced img tag.

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe I saw you closed this issue as not planned but then you added the ready for prioritization label. I'm confused.

**Comment by Kle012** [comment]
i. Availability: 06/26/2024 1PM-5PM
ii. ETA: 06/26/2024 5PM
