### ISSUE TITLE
Update Project Profile: Access the Data Technologies

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#5151]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need the information that we present for each of our projects to be consistent to make it easier for user to find the information they are searching for. Currently, the project filter on both our Homepage and Projects page our "Languages/ Technologies" filter shows two choices for the same technology: "AWS" and "Amazon Web Services (AWS)".

### Action Items
Note that "Access The Data" is the outlier in using "Amazon Web Services (AWS)" to describe the technology.
- [x] Go to the [Access The Data](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md) markdown page and identify the `technologies:` section. Replace `Amazon Web Services (AWS)` with `AWS`.
- [x] Confirm that each page showing the filters as well as the project page show that the change was made successfully and that no unanticipated changes occurred.

### Resources/Instructions
[Homepage](https://www.hackforla.org/)
[Projects](https://www.hackforla.org/projects/) page
[Access The Data](https://www.hackforla.org/projects/access-the-data) project page

**Comment by allison-truhlar** [comment]
Availability: T-Th 9-5pm ET
ETA: Wed EOD
