### ISSUE TITLE
Feasibility and DR: use of CodeQL for VS Code

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5180]
### Overview
We should consider whether to adopt the policy that developers should install the "CodeQL for VS Code" extension.  Currently the default branch of the repository is scanned weekly and the changed files in each Pull Request are scanned, however there are advantages to recieving alerts prior to initiating the Pull Request process.  

### Action Items
- [x] Become familiar with the repository level CodeQL scanning implemented in #4886
- [x] Consider whether HfLA developers should install the CodeQL for VS Code extension.
- [x] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki)
- [x] Following the instruction in [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki), write a draft DR with your recommendation in a comment in this issue.  
- [x] Move this issue to Questions/In Review and add the `ready for dev lead` label. 

### Resources/Instructions
- #4886
- [CodeQL for Visual Studio Code](https://codeql.github.com/docs/codeql-for-visual-studio-code/)](https://codeql.github.com/docs/codeql-for-visual-studio-code/)

**Comment by kiran98118** [comment]
i. Availability: I am available on Sunday, Tuesday, Wednesday, Friday and Saturday (10 am to 5pm)
ii. ETA: 11-02-2024

**Comment by ExperimentsInHonesty** [comment]
@kiran98118 It looks like you forgot to move this to the in progress column on the board.  I will move it for you.

**Comment by kiran98118** [comment]
Thank you Bonnie.

**Comment by LRenDO** [comment]
Hi @kiran98118! 

It looks like you have moved this because you are finished with the issue and it is ready for review. However, I don't see a draft DR in a comment on this issue or a link to a DR on the [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) page. If I've missed it, please let me know. Otherwise, please add the DR according to the instructions on the  [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) page. Feel free to ping me if you have any questions. I am moving this back to the `In Progress (actively working)` column for now. Please move it back to `Questions / In Review` once you've completed the DR and add the `ready for dev lead` label.

Thanks for taking the time to contribute!

**Comment by kiran98118** [comment]
Draft DR: Recommendation to adopt CodeQL for VS Code extension 


- HfLA developers should install the "CodeQL for VS Code" extension to enable real-time code analysis and security vulnerability detection within their local development environment.

- The extension will provide immediate feedback and alerts on potential issues, allowing developers to address them before submitting a Pull Request.

- This proactive approach complements the existing repository-level and Pull Request-level CodeQL scanning, further enhancing the overall code quality and security posture of the project.

- Early detection and resolution of code issues and vulnerabilities, reducing the risk of introducing defects or security vulnerabilities into the codebase.

- Improved developer productivity by addressing potential issues locally, minimizing the need for rework after the Pull Request review process.
- Establish coding guidelines and standards that incorporate the CodeQL analysis findings and recommendations.


- Gather feedback from HfLA developers on their experience with the "CodeQL for VS Code" extension and address any concerns or issues that arise.

**Comment by roslynwythe** [comment]
- Thank you @kiran98118 for your analysis.  A problem with CodeQL has become apparent in #5234 and I would like to ask you about it.  The problem is that on GitHub, CodeQL fails to scan any file that contains non-JS code, includeing liquid statements that appear in many of our JS files.  Do you happen to know if the same will occur in the "CodeQL for VS Code" extension, and if there is a workaround?

**Comment by kiran98118** [comment]
@roslynwythe 

CodeQL only supports C/C++, C#, Go, Java/Kotlin, JavaScript/TypeScript, Python, Ruby, Swift languages. If the code you're attempting to scan is not written in one of the supported languages, the CodeQL scan will fail automatically. This behavior is also observed when using the CodeQL extension within Visual Studio (VS). The tool does not have the capability to analyze or process code written in languages that are not explicitly supported by the CodeQL platform.

**Comment by roslynwythe** [comment]
Thank you @kiran98118 for your analysis and recommendation.
