### ISSUE TITLE
img Tag Refactor: _includes/events-page/right-col-content.html - org-projects.png

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5187]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/events-page/right-col-content.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="step-img-2" src="../assets/images/hack-nights/org-projects.png" alt="" />
```
to
```
<img class="step-img-2" src="../assets/images/hack-nights/org-projects.png" alt="">
```
- [x] **The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.**
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 1 in the Resources/Instructions section below)

### After your PR is merged
- [x] go to this issue https://github.com/hackforla/website/issues/5040
   - [x] Check off 5187 on the issue
   - [x] Close the issue as completed (button at bottom)
- [x] go to this issue https://github.com/hackforla/website/issues/4362
  - [x] Check off 5040 in the dependency of this issue 
  - [x] move the issue from icebox to the new issue approval column
### Resources/Instructions
1. Webpage(s): https://www.hackforla.org/events
2. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe This has an `Complexity: Extra Large` label. Is this supposed to have a `good first issue` label?

**Comment by roslynwythe** [comment]
> @roslynwythe This has an `Complexity: Extra Large` label. Is this supposed to have a `good first issue` label?

@JessicaLucindaCheng I'm not sure why @Josiah-O added the `Complexity: Extra Large` label.  This happened on a number of these issues.   I'm removing the `Complexity: Extra Large` label.

**Comment by ramitaarora** [comment]
Availability: 9am-2pm weekdays
ETA: Thurs Feb 15 EOD

**Comment by ExperimentsInHonesty** [comment]
@ramitaarora Congrats! This issue is the last issue in a huge epic.   I updated the Actions Items to add something for you to do on this issue after its merged so we can close out the epic and move its roll-out plan forward.

**Comment by JessicaLucindaCheng** [comment]
I'm reopening this issue because the issue isn't fixed yet. I still see it here: https://github.com/hackforla/website/blob/634dc2c9d99eb4f65879d00df4df35feafa32933/_includes/events-page/right-col-content.html#L8

**Comment by marioantonini** [comment]
i. Availability: Fri, Sat, Sun 12-2pm
ii. ETA: Fri Mar 8
