### ISSUE TITLE
img Tag Refactor: _includes/about-page/about-card-donations.html - hfla-donate.gif

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5188]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to change an img HTML tag ending with a slash (<img.../>) to an img tag without an ending slash (<img...>) so that the codebase is consistent with how we use img HTML tags.

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-donations.html`
- [x] Remove the ending slash in the img HTML tag by changing
```
<img class="donation-gif-box-shadow" src="/assets/images/about/hfla-donate.gif" alt="Video guide on how to donate for Hack for LA" />
```
to
```
<img class="donation-gif-box-shadow" src="/assets/images/about/hfla-donate.gif" alt="Video guide on how to donate for Hack for LA">
```
**- [ ] The file may contain more than one instance of an img tag with a closing slash.  Only change the single instance specified above.  Do not leave any blank spaces before the closing bracket.**
- [ ] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-donations.html
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: img Tag Audit spreadsheet's img with Ending Slash tab](https://docs.google.com/spreadsheets/d/1cq8iLOYQkAbho2GsRAxVJYgjxDeJ9KLdx2NuL4G6vu4/edit#gid=0), which is part of #4362

**Comment by kiran98118** [comment]
I. I am available on weekdays 11 am to 5pm
2. 17th aug 2023

**Comment by kiran98118** [comment]
Need help
2. Blockers: The content is different than what is provided in the overview. so, I am not sure where to make changes. I could not find the required image tag as mentioned in the description. I guess the code base is updated.

**Comment by roslynwythe** [comment]
Hi @kiran98118 I apologize for the delay in responding.  I sometimes just filter for issues with "ready for dev lead" and so I had missed it.  You are correct in concluding that this issue is no longer valid.  If you are looking for a similar issue please contact me in Slack.
