### ISSUE TITLE
ER: Move Dev Lead to the first position of all the Devs on HackforLA.org website

### ISSUE THREAD

**Issue by Josiah-O** [hackforla/website#5191]
### Emergent Requirement - Problem

Roslyn's name shows at the bottom of the leadership list, she should show up right after Bonnie's listing on the Website team page.

### Issue you discovered this emergent requirement in
- #5057 

### Date discovered 
2023-08-13

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@Josiah-O @ExperimentsInHonesty 

### What happens if this is not addressed
Its confusing for new members

### Resources
https://www.hackforla.org/projects/website
https://github.com/hackforla/website/blob/gh-pages/_projects/website.md

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

**Comment by t-will-gillis** [comment]
Created issue #5316 to address this ER
