### ISSUE TITLE
ER: Move AWS and Nginx to technologies section on Home Unite Us

### ISSUE THREAD

**Issue by Josiah-O** [hackforla/website#5192]
### Emergent Requirement - Problem

AWS and Nginx appears in the Tools Section of Home Unite Us project file, we need to move them to Technologies
### Issue you discovered this emergent requirement in
- #4808 

### Date discovered 
2023-08-13

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@Josiah-O @ExperimentsInHonesty 

### What happens if this is not addressed
Filters don't work as well.

### Resources
https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md
https://www.hackforla.org/projects/

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

**Comment by t-will-gillis** [comment]
Issue #5342 created to address this ER
