### ISSUE TITLE
ER: Correct Capitalization for Google Forms and Abbreviate UsabilityHub

### ISSUE THREAD

**Issue by Josiah-O** [hackforla/website#5193]
### Emergent Requirement - Problem

Change capitalization for 'Google Forms' and Abbreviate 'UsabilityHub

### Issue you discovered this emergent requirement in
- #4805 

### Date discovered 
2023-08-13

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@Josiah-O @ExperimentsInHonesty 

### What happens if this is not addressed
The filters on the project page dont work well (have same information called by different names)

### Resources
https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md
https://www.hackforla.org/
https://www.hackforla.org/projects/
https://github.com/hackforla/website/issues/4777

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
- [ ] Change
```
  - Google forms
```
to
```
  - Google Forms
```
- [ ] Change
```
  - Usabilityhub.com surveys
```
to
```
  - UsabilityHub
```

**Comment by t-will-gillis** [comment]
Created issue #5324 to address this ER.
