### ISSUE TITLE
ER: Refactor Google Workspace List for Individual Services for Tech Work Experience (TWE)

### ISSUE THREAD

**Issue by Josiah-O** [hackforla/website#5194]
### Emergent Requirement - Problem
The aggregation of Google Workspace tools under a single listing reduces clarity. There's a need to individually list each service for better manageability and reference.  We need to fix it on the Tech Work Experience project file

### Issue you discovered this emergent requirement in
- #4913 

### Date discovered 
2023-08-13

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@Josiah-O @ExperimentsInHonesty 

### What happens if this is not addressed
The filters on the project page don't work as well (have same information called by different names)

### Resources
https://github.com/hackforla/website/blob/gh-pages/_projects/tech-work-experience.md
https://www.hackforla.org/
https://www.hackforla.org/projects/
https://github.com/hackforla/website/issues/4777

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
- [ ] Change
```  
- Google Workspace (Sheets, Docs, Forms, Mail Merge, Calendar)
```
to
```
  - Google Sheets
  - Google Docs
  - Google Forms
  - Google Calendar
  - Mail Merge
```

**Comment by t-will-gillis** [comment]
Issue #5323 created to address this issue.
