### ISSUE TITLE
ER: Revise Projects Meeting page to have more info

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#5195]
### Emergent Requirement - Problem
The Projects Meeting page doesn't have enough info on it

### Issue you discovered this emergent requirement in
- #4906 was reviewing it but not really related.

### Date discovered 
2023-08-13

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
The page is not very useful to our users

### Resources
- https://github.com/hackforla/website/blob/gh-pages/assets/js/utility/api-events.js
- https://www.hackforla.org/project-meetings
- https://www.hackforla.org/events/ (the events page displays the `event name` but not the `description`.

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Overview
We need to add Meeting Name to the Projects Meeting page, so that its a better experience for users and we can use the page to check all the meeting info, is conforming to standards

### Action Items
- [ ] Add Event name from the Jason object so that a meeting with Description will look like this:
``` 5:00pm - 6:00pm, All, 2nd week```
which is `start time` - `end time`, `event name`, `description`

**Comment by t-will-gillis** [comment]
Hi @ExperimentsInHonesty - here is a screenshot of the Project Meetings page, including the `event.meetingName` plus a comma if `event.dsc` != "". Is this what you were thinking it should look like? Thanks  

![Screenshot 2023-08-29 142937](https://github.com/hackforla/website/assets/40799239/85d37185-c4df-4a37-8b48-97dbdcf3e7ba)

**Comment by t-will-gillis** [comment]
- Issue #5345 addresses this ER.
