### ISSUE TITLE
Prototype API failure behavior

### ISSUE THREAD

**Issue by cnk** [hackforla/website#520]
Issue #405 made our project meeting schedule dynamic by pulling from the VRMS API. We need to decide what the page looks like if we do not get any data from VRMS. 

At the moment we still list all the days of the week but say "no meeting scheduled".

**Comment by ExperimentsInHonesty** [comment]
@cnk Can’t we save the last version we got and display that instead if no new version is available?

**Comment by cnk** [comment]
I don't think so. We might be able to cache on during the nightly rebuild. But even then, it is possible that we would get nothing when doing that call. So we need to know what the page looks like with no meeting data.
