### ISSUE TITLE
ER: Refactor Tools data for civic-tech-index.md

### ISSUE THREAD

**Issue by Josiah-O** [hackforla/website#5246]
### Emergent Requirement - Problem
There is a discrepancy in the representation of the name of the tool being used, leading to potential confusion or misrepresentation.

### Issue you discovered this emergent requirement in
- #4800 

### Date discovered 
2023-08-13

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@Josiah-O @ExperimentsInHonesty 

### What happens if this is not addressed
Its confusing for new members, the accurate tool name won't be represented.

### Resources

- [Homepage](https://www.hackforla.org/)
- [Projects Page](https://www.hackforla.org/projects/)
- This issue is part of an epic: Create new issues to refactor Tools data in project md files  #4777 

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]

-  [ ] Change
```
  - Usability Hub
 ```
to
```
  - UsabilityHub
```

**Comment by t-will-gillis** [comment]
Issue #5341 addresses this ER
