### ISSUE TITLE
Store images for Wiki pages

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#525]
### Ice Box
Keep in the icebox and add images to it when necessary

### Overview
This issue will store images for Wiki pages (https://github.com/hackforla/website/wiki) as a permanent store of images

### Action Items
- [x] Transfer images from #529 to this issue, as comments in the issue.
- [x] leave this issue open in the icebox when done using.

**Comment by ye-susan** [comment]
![image](https://user-images.githubusercontent.com/49918375/82394556-39e0d400-99fe-11ea-99a2-5cf3525a5f56.png)

![image](https://user-images.githubusercontent.com/49918375/82393021-2469ab00-99fa-11ea-88a9-7b3c4766d073.png)

![image](https://user-images.githubusercontent.com/49918375/82394442-e9697680-99fd-11ea-9862-d6835e81ed66.png)

![image](https://user-images.githubusercontent.com/49918375/82394297-837cef00-99fd-11ea-9355-3b49235bebaf.png)

**Comment by ye-susan** [comment]
![image](https://user-images.githubusercontent.com/49918375/82748391-4777c000-9d56-11ea-89d2-5a089db78286.png)

![image](https://user-images.githubusercontent.com/49918375/82748435-ae957480-9d56-11ea-88db-51b800164214.png)

![image](https://user-images.githubusercontent.com/49918375/82748453-d71d6e80-9d56-11ea-8376-d5d857264668.png)

![image](https://user-images.githubusercontent.com/49918375/82748464-eef4f280-9d56-11ea-8b43-19c1d8220e44.png)

![image](https://user-images.githubusercontent.com/49918375/82748487-1350cf00-9d57-11ea-825f-635f05dfa217.png)

![image](https://user-images.githubusercontent.com/49918375/82748558-be618880-9d57-11ea-9ddc-8e7393af0323.png)

**Comment by ye-susan** [comment]
![image](https://user-images.githubusercontent.com/49918375/82958812-2936dd80-9f6b-11ea-9c00-3e380554c76a.png)
![image](https://user-images.githubusercontent.com/49918375/82959127-db6ea500-9f6b-11ea-975d-bff9d31fc210.png)
![image](https://user-images.githubusercontent.com/49918375/82959194-fccf9100-9f6b-11ea-8a8d-a6d4a62ca42f.png)
![image](https://user-images.githubusercontent.com/49918375/82959291-3a341e80-9f6c-11ea-853c-9c101afd6546.png)

![image](https://user-images.githubusercontent.com/49918375/82959339-533ccf80-9f6c-11ea-9d6a-0a42c98acd53.png)

![image](https://user-images.githubusercontent.com/49918375/82959406-78c9d900-9f6c-11ea-8693-ad6f9301d9ad.png)
![image](https://user-images.githubusercontent.com/49918375/82959466-a31b9680-9f6c-11ea-8074-6738279c9cf6.png)
![image](https://user-images.githubusercontent.com/49918375/82959493-b3cc0c80-9f6c-11ea-8913-a6137544a8b9.png)
![image](https://user-images.githubusercontent.com/49918375/82959595-f1309a00-9f6c-11ea-8c2f-8b44005a847c.png)

**Comment by ye-susan** [comment]
![image](https://user-images.githubusercontent.com/49918375/82959675-26d58300-9f6d-11ea-860e-20cdabdba570.png)
![image](https://user-images.githubusercontent.com/49918375/82959750-58e6e500-9f6d-11ea-9de7-b01d3722657c.png)
![image](https://user-images.githubusercontent.com/49918375/82959871-ae22f680-9f6d-11ea-9711-b37f491daf69.png)
![image](https://user-images.githubusercontent.com/49918375/82959892-c135c680-9f6d-11ea-8805-0d288855ac8d.png)

**Comment by ye-susan** [comment]
![image](https://user-images.githubusercontent.com/49918375/83339948-a6be5e80-a287-11ea-8e5f-2d3344c681cd.png)

![image](https://user-images.githubusercontent.com/49918375/83339970-ec7b2700-a287-11ea-8b09-fbfd8ab87c9d.png)

![image](https://user-images.githubusercontent.com/49918375/83339985-0caae600-a288-11ea-9af2-182a5af21590.png)

![image](https://user-images.githubusercontent.com/49918375/83370867-72c16700-a375-11ea-955b-79a6672c6307.png)

**Comment by ye-susan** [comment]
![image](https://user-images.githubusercontent.com/49918375/86847713-9c9b3700-c061-11ea-9be9-27753e729542.png)

![image](https://user-images.githubusercontent.com/49918375/86847740-af157080-c061-11ea-829e-3fa1ad5edf60.png)

![image](https://user-images.githubusercontent.com/49918375/86416674-72bbcc00-bc7f-11ea-8add-47c92c66639f.png)

![image](https://user-images.githubusercontent.com/49918375/86416685-7a7b7080-bc7f-11ea-99de-087ce01be6ec.png)

**Comment by ghost** [comment]
<img width="603" alt="openRolesDemo" src="https://user-images.githubusercontent.com/58455740/86554282-06043400-bf02-11ea-9b86-2fe6b7065ebe.png">
<img width="288" alt="openRolesExample" src="https://user-images.githubusercontent.com/58455740/86554284-07cdf780-bf02-11ea-8ed6-5713a010d0b6.png">

**Comment by alexandrastubbs** [comment]
![HFLA ](https://user-images.githubusercontent.com/66918724/87251956-80badb00-c43d-11ea-97a3-8c2c76aced21.png)

**Comment by ExperimentsInHonesty** [comment]
![meeting invite image](https://user-images.githubusercontent.com/37763229/125548181-b3a1c82c-f99a-4a7e-9d97-2c4ce23f9e47.png)

**Comment by Sihemgourou** [comment]
@ExperimentsInHonesty does this issue belong on in progress column ? Its seems the assignee was working on it a long time ago

**Comment by ExperimentsInHonesty** [comment]
![screencapture-hackforla-org-2022-04-05-12_15_42](https://user-images.githubusercontent.com/37763229/161832703-c1bd974b-29fc-4231-91c9-8e33982fa5bd.png)

**Comment by ExperimentsInHonesty** [comment]
![screencapture-hackforla-org-about-2022-04-05-14_51_50](https://user-images.githubusercontent.com/37763229/161855857-c597fb9e-c5df-417d-a6a4-8d635f47db39.png)
