### ISSUE TITLE
ER: Refactor deprecated event property in JS files

### ISSUE THREAD

**Issue by StephenTheDev1001** [hackforla/website#5264]
### Emergent Requirement - Problem
We want to refactor code that uses the deprecated Window: Event Property  in  `current-projects.js` file to avoid errors/bugs in future browser versions.

### What happens if this is not addressed
We would be using a deprecated method. If this issue isn't addressed, code may become fragile and may not work properly in all browsers.

### Resources
[current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
[window: event property](https://developer.mozilla.org/en-US/docs/Web/API/Window/event)
### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
#5289

**Comment by StephenTheDev1001** [comment]
@roslynwythe @JessicaLucindaCheng I want to do something very similar to [this](https://github.com/hackforla/website/issues/4362) and I want to use your issue as a guide. I've only found 7 instances of this, so I would prefer to do an abridged version of what you guys did with img slash. What would you recommend I do differently and any general tips for me?

**Comment by StephenTheDev1001** [comment]
After further research, there's not enough cases to justify creating an epic. It's just a single issue

**Comment by roslynwythe** [comment]
Hi @StephenTheDev1001 please take a look at the ER issue template (`New Issue`, then `Emergent Request`) and make sure that your issue contains all of the same elements, such as the  "Issue you discovered this emergent requirement in".  Also, usually we close an ER when the resulting issue is prioritized.  Have you created an issue, or do you plan to?  It's ok if you don't want to write the issue, I just need to know.

**Comment by roslynwythe** [comment]
@StephenTheDev1001 let's leave the ER open until the issues are prioritized.  Please provide a link to the Epic.

**Comment by ExperimentsInHonesty** [comment]
@StephenTheDev1001 I agree with @roslynwythe that this issue is labled as an er, but dosent have the information required for an ER, because its formatted as an issue.  It can remain an issue, but we will still need some of that info, and the title should get renamed.

Mainly what we need documented, is what happens if we don't make this change.  That will help us pick a milestone.

**Comment by StephenTheDev1001** [comment]
@ExperimentsInHonesty @roslynwythe I rewrote the ER. After further research, there's not enough cases to justify creating an epic. It's just a single issue #5289
