### ISSUE TITLE
ER: Move items from Tools to Technologies in hellogov.md

### ISSUE THREAD

**Issue by Josiah-O** [hackforla/website#5268]
### Emergent Requirement - Problem
Items that are supposed to be under technologies section are under tools, we need to change this.

### Issue you discovered this emergent requirement in
- #4807 

### Date discovered 
2023-08-13

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@Josiah-O @ExperimentsInHonesty @wanyuguan 

### What happens if this is not addressed
The technologies will be represented as tools and the filters on the project page don't work.

### Resources
[Project Check Page](https://www.hackforla.org/projects-check)
[HfLA Homepage](https://www.hackforla.org/)
[Projects Page](https://www.hackforla.org/projects/)
#4777 

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
- [ ] Move these items from tools to technologies
```
  - Mongo
  - Angular
  - Node
```

**Comment by t-will-gillis** [comment]
Just a quick comment- the other projects are using `MongoDB` and `Node.js` as opposed to `Mongo` and `Node`. For consistency, I am changing these so that all projects match.

**Comment by t-will-gillis** [comment]
Issue #5340 address this ER
