### ISSUE TITLE
ER:  Capitalize Tool Data for green-earth-os.md

### ISSUE THREAD

**Issue by wanyuguan** [hackforla/website#5269]
### Emergent Requirement - Problem
Tool data in green-earth-os.md needs to be capitalized in order for the Tools filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to render properly.

### Issue you discovered this emergent requirement in
- #4806 

### Date discovered 
2023-08-13

### Did you have to do something temporarily
- [ ] YES
- [X] NO

### Who was involved
@wanyuguan @Josiah-O @ExperimentsInHonesty 

### What happens if this is not addressed
Tools data for GreenEarthOS project will not be displayed correctly in the Tools filter menu on the [projects-check](https://www.hackforla.org/projects-check) page. 

### Resources
[Project Check Page](https://www.hackforla.org/projects-check)
[HfLA Homepage](https://www.hackforla.org/)
[Projects Page](https://www.hackforla.org/projects/)
#4806 

### Recommended Action Items
- [X] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
- [ ] Change 
```
tools:
  - Google sheets
  - Google forms
  - Figma
  - FigJam
```
to
```
tools:
  - Google Sheets
  - Google Forms
  - Figma
  - FigJam
```

**Comment by ShambhavII-Singh** [comment]
Hello! I would like to work on this. Could you assign this issue to me? Thanks!

**Comment by t-will-gillis** [comment]
Issue #6020 has been created to address this issue, therefore closing this ER.
