### ISSUE TITLE
ER: Remove '1Password' From Tools Data in website.md and tech-work-experience.md Files

### ISSUE THREAD

**Issue by wanyuguan** [hackforla/website#5271]
### Emergent Requirement - Problem
'1Password' needs to be removed from tools data in website.md and tech-work-experience.md files since 1Password is not considered as a tool. 

### Issue you discovered this emergent requirement in
- #4813 

### Date discovered 
2023-08-13

### Did you have to do something temporarily
- [ ] YES
- [X] NO

### Who was involved
@wanyuguan @Josiah-O @ExperimentsInHonesty 

### What happens if this is not addressed
Tools data will be incorrect in website.md and tech-work-experience.md files if 1Password is included. It will cause the Tools filter menu on the [projects-check](https://www.hackforla.org/projects-check) page to display inaccurate tools (with 1Password included). 

### Resources
[Project Check Page](https://www.hackforla.org/projects-check)
[HfLA Homepage](https://www.hackforla.org/)
[Projects Page](https://www.hackforla.org/projects/)
#4813 

### Recommended Action Items
- [X] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
2 issues to do the following for the website.md and tech-work-experience.md files
````
- [ ] Remove
```
  - 1Password
```
````

**Comment by LiQuiD-404** [comment]
@wanyuguan I would love to work on this issue. Could you assign me this issue?

**Comment by connortessaro** [comment]
Availability: sep 2 12pm-4pm
ETA: 15min-30min

**Comment by roslynwythe** [comment]
New issues: 
- #5681
- #5680
