### ISSUE TITLE
Refactor HTML to resolve linter error: _includes/about-page/about-card-accomplishments.html 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5281]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Value of attribute [class] must be in double quotes"

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-accomplishments.html`
- [x] Change the line of code
```
<div class='card-primary page-card-lg page-card--about'>
```
to
```
<div class="card-primary page-card-lg page-card--about">
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [ ] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-accomplishments.html
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

**Comment by ajb176** [comment]
i. 6am - 10am PST
ii. Tuesday EOD
