### ISSUE TITLE
Remove Ability to Highlight Filter Drop-down Arrow

### ISSUE THREAD

**Issue by Adastros** [hackforla/website#5282]
### Overview

We need to remove the ability to highlight the filter dropdown arrow. This will prevent users from accidentally highlighting the arrow if they click it in rapid succession.

### Details

<details>
<summary>Dropdown Arrow Highlighting on Click</summary>

![2023-08-28 22-50-15](https://github.com/hackforla/website/assets/48114590/86eb65d2-ba45-44e2-b9d3-dfcfb8f9d934)

</details>

### Action Items

- [x] Update the `labelArrow` class in the `_dropdown_filters.scss` file so that users can't highlight the filter drop-down arrows on the home, projects, and toolkit pages

### Resources/Instructions
- This issue was created per #5233 
- [Home Page](https://www.hackforla.org/#)
- [Projects Page](https://www.hackforla.org/projects/)
- [Toolkit Page](https://www.hackforla.org/toolkit/?)
- [_dropdown_filters.scss file](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_dropdown_filters.scss)

**Comment by kristinstockley** [comment]
Availability: Monday, 9/18 and Tuesday, 9/19
ETA: By EOD Tuesday, 9/19
