### ISSUE TITLE
Continuous Development of Wiki for Site Architecture

### ISSUE THREAD

**Issue by ye-susan** [hackforla/website#529]
### Overview
Research and document HFLA's site architecture.

### Action Items
- [x] Create wiki page documenting existing site architecture
- [x] Include screenshots
- [x] Research and document any API we're using (separate wiki for endpoints, related to issue #270)
- [x] Update documentation for any new features --i.e. master calendar

**Comment by ye-susan** [comment]
![image](https://user-images.githubusercontent.com/49918375/82392972-0bf99080-99fa-11ea-921a-b305f7647ad7.png)

![image](https://user-images.githubusercontent.com/49918375/82393021-2469ab00-99fa-11ea-88a9-7b3c4766d073.png)

![image](https://user-images.githubusercontent.com/49918375/82393097-5b3fc100-99fa-11ea-862e-0f4ed8125a78.png)

**Comment by ye-susan** [comment]
Update: new wiki page is up - [Hack for LA's Site Architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)
Still need to expand on projects section, styling section, and add more details about the APIs we're using

**Comment by ye-susan** [comment]
![image](https://user-images.githubusercontent.com/49918375/82748391-4777c000-9d56-11ea-89d2-5a089db78286.png)

![image](https://user-images.githubusercontent.com/49918375/82748435-ae957480-9d56-11ea-88db-51b800164214.png)

![image](https://user-images.githubusercontent.com/49918375/82748453-d71d6e80-9d56-11ea-8376-d5d857264668.png)

![image](https://user-images.githubusercontent.com/49918375/82748464-eef4f280-9d56-11ea-8b43-19c1d8220e44.png)

![image](https://user-images.githubusercontent.com/49918375/82748487-1350cf00-9d57-11ea-825f-635f05dfa217.png)

![image](https://user-images.githubusercontent.com/49918375/82748558-be618880-9d57-11ea-9ddc-8e7393af0323.png)

**Comment by ye-susan** [comment]
Status: Updated Hack for LA's Site Architecture page, and added [Guide to the Project Layout File](https://github.com/hackforla/website/wiki/Guide-to-the-Project-Layout-File) 
To Do: 
- document JS scripts in project layout
- add more images
- add styling section

**Comment by ExperimentsInHonesty** [comment]
@ye-susan can you provide a little more status report
1. Progress (see https://github.com/hackforla/website/issues/529#issuecomment-633193987)
2. Blocks
3. Availability
4. ETA

**Comment by ye-susan** [comment]
1. Progress: 80% finished with site architecture, just need styling section. Added a wiki for Project.html Layout file like the wiki we have for project.md files. Still need to add documentation for project-meetings.html for the calendar.   
2. Blocks: I have some questions about the scripts used in project.html layout
3. Availability: free 
4. ETA: 5/27

**Comment by ye-susan** [comment]
![image](https://user-images.githubusercontent.com/49918375/82958812-2936dd80-9f6b-11ea-9c00-3e380554c76a.png)

**Comment by ye-susan** [comment]
![image](https://user-images.githubusercontent.com/49918375/82959675-26d58300-9f6d-11ea-860e-20cdabdba570.png)
![image](https://user-images.githubusercontent.com/49918375/82959750-58e6e500-9f6d-11ea-9de7-b01d3722657c.png)
![image](https://user-images.githubusercontent.com/49918375/82959871-ae22f680-9f6d-11ea-9711-b37f491daf69.png)
![image](https://user-images.githubusercontent.com/49918375/82959892-c135c680-9f6d-11ea-8805-0d288855ac8d.png)

**Comment by ExperimentsInHonesty** [comment]
Adding @ampers-and to comments and questions review.

**Comment by ye-susan** [comment]
![image](https://user-images.githubusercontent.com/49918375/83339948-a6be5e80-a287-11ea-8e5f-2d3344c681cd.png)

![image](https://user-images.githubusercontent.com/49918375/83339970-ec7b2700-a287-11ea-8b09-fbfd8ab87c9d.png)

![image](https://user-images.githubusercontent.com/49918375/83339985-0caae600-a288-11ea-9af2-182a5af21590.png)

**Comment by ye-susan** [comment]
1. Progress: 100% finished with site architecture. Just starting on new wiki for API endpoints
2. Blocks: clarifying questions about our API endpoints and the JSON file that was mentioned in issue #270
3. Availability: Sun - Wed
4. ETA: 6/3

**Comment by ExperimentsInHonesty** [comment]
@ye-susan I tried to find details about how our redirect is structured:
https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture#redirect-files
but it didn't have information on how the redirect works.  See #553 for some of that related info, and also feel free to talk to me about the redirects if there is anything that is unclear.

**Comment by ExperimentsInHonesty** [comment]
@ye-susan please move images from this issue to issue #525 so that we can keep all the images for the wiki in one place and keep it open while closing this issue when you are done.  I think you can cut and paste the code that calls them direct from this issue and paste that code into 525, keeping you from having to change anything at the wiki end.

**Comment by ye-susan** [comment]
@ExperimentsInHonesty Thanks for the feedback, Bonnie. I've just edited the [Redirect section](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture#redirect-files) to include a description of how the code is pulling from the markdown files. In the styling section, I also talk about how the [sass layout](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture#layouts) folder is styling the redirect layout, as well as distinguishing between the two [main.scss](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture#mainscss-and-normalizescss-files) files. 

All the images have been copied to issue 525.

**Comment by ExperimentsInHonesty** [comment]
Hi @ye-susan on this page: https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture#redirect-files please change
donate.md: links to donorbox.org
to
donate.md: links to https://www.codeforamerica.org/donate

**Comment by ye-susan** [comment]
Thanks Bonnie, I've change the link to the correct one

**Comment by ashlingam** [comment]
@ampers-and @jbubar Please review the documentation on this Wiki page: https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture

**Comment by ExperimentsInHonesty** [comment]
@jbubar re your comment last night, about how cool the site architecture is.  Was this insight gained by reading the wiki, or by exploring the site?

**Comment by ExperimentsInHonesty** [comment]
@hannahlivnat @ethanh256  - Task for all new developers - Please review the documentation on this Wiki page: https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture
and tell us if there are improvements that could further your understanding and the understanding of the people who come after you.

**Comment by ghost** [comment]
@ye-susan Just to double-check before I start working on the style section, do I click the "edit" button within the wiki page and get started in there, or should I be creating a draft in a different spot and submitting that draft to be added to the wiki page?

**Comment by ye-susan** [comment]
@hannahlivnat I don't think there's a draft option unfortunately, so I just edit offline in VS code and paste it straight onto the wiki when I'm finished

**Comment by eb46** [comment]
@ye-susan great job putting this all together! I like how detailed the folder descriptions are, specifically the Includes folder. I don't have anything to add at the moment but I'm sure I'll get some ideas once I start using it.

**Comment by ghost** [comment]
@ExperimentsInHonesty @ye-susan During our Tuesday night meeting, we talked about adding a section to the style page of the wiki that detailed where different sass components/variables /etc. could be found. I was reading through the style section, and it seems like Susan has already written this out pretty well. Screenshot included below. Do we want to go more in-depth than this within the wiki? 

![Screen Shot 2020-06-27 at 4 08 48 PM](https://user-images.githubusercontent.com/54752231/85933838-7e2e8200-b890-11ea-86d1-03189864ed23.png)

**Comment by ghost** [comment]
@ye-susan just read through the new guide page section that you posted. Very clear and easy to understand, particularly with the visuals. I think it looks great!

**Comment by jbubar** [comment]
@ExperimentsInHonesty @ye-susan @alexandrastubbs 
I am really impressed with the [site architecture page](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)! It is definitely one of the most important pages on the wiki. I really appreciate all of the educational links. I learned a lot form it. My one thought is that this page is not easily accessed through the wiki. I found it on the readme pretty easily but it was buried pretty deep in the webdev page on the wiki. not sure if this is on purpose

## Other thoughts about other wiki pages:
### [Introduction to the project page](https://github.com/hackforla/website/wiki/Introduction-to-the-Project)
- I don't feel too strongly about this, but here is my thought. We don't need to talk about the redesign… I don't know if anyone remembers the old site design
[Joining the Hfla website team page](https://github.com/hackforla/website/wiki/Joining-the-HackforLA.org-website-team)
- Product owner link (step 5) does not work
- Harish is no longer the PM
- What is this? "*6. Review [INSERT SLIDE DECK or VIDEO THAT SHOWS HOW WE USE THE PROJECT BOARDS IN GITHUB TO MANAGE WORKFLOW]. *This step is under development."

### [Template of a project.md file page](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)
- Needs to be updated with the changes to looking for

**Comment by alexandrastubbs** [comment]
1. @alexandrastubbs and @ExperimentsInHonesty will review what needs to be on the product owner link. Update PM as well. Make an issue for # 6 on introduction page. 

2. @jbubar will make a link in the resources page to the site architecture wiki. 

3. @ethanh256 update looking for in the template of a project.md file.

**Comment by jbubar** [comment]
added site architecture link to the [resources page](https://github.com/hackforla/website/wiki/resources) in the wiki under web developer
