### ISSUE TITLE
Another Rename parameter to e on api-actionnetwork.js

### ISSUE THREAD

**Issue by StephenTheDev1001** [hackforla/website#5293]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
Rename events passed as a function parameter to `e` to have consistency throughout the JS files

### Action Items
- [ ] In your local IDE, navigate to `assets/js/api-actionnetwork.js`
- [ ] Rename `event` parameter to `e` by changing
```
  contactFormBtn.addEventListener("click", function (event) {
      event.preventDefault();
```
to
```
 contactFormBtn.addEventListener("click", function (e) {
      e.preventDefault();
```
- [ ] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website 

### Resources/Instructions
This issue is part of #5290

### For Dev Leads/Merge Team

- [ ] After merge, check #5290 to see if all the dependencies have been merged. If all dependencies are merged, close #5290.

**Comment by StephenTheDev1001** [comment]
@WayneTsai45 Thank you for your interest in this issue, but it is not ready for work yet and it is marked as a "Good first Issue". You have already completed an img slash issue before, so we would like to leave this one for another contributor. We are working on creating more challenging issues for you and others.

**Comment by LukeLowrey2** [comment]
ETA: Sunday 8/27 10am
Availability: Friday 8/25 10am-12pm

**Comment by StephenTheDev1001** [comment]
@LukeLowrey2 Thank you for your interest in this issue, but it is not ready for work yet and it is marked as a "Good first Issue". You have already completed an img slash issue before, so we would like to leave this one for another contributor. We are working on creating more challenging issues for you and others.
