### ISSUE TITLE
ER: Tools data needs spaces

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5309]
### Emergent Requirement - Problem
The Tools data is currently displaying without a space after each comma for all the projects that have a Tools field. 

Example of problem:
<img width="205" alt="No spaces tools" src="https://github.com/hackforla/website/assets/31293603/6c696114-5ccf-4d38-b280-a7cffc69d5e6">

### Issue you discovered this emergent requirement in
- N/A. I was looking at this page on the website: https://www.hackforla.org/projects/

### Date discovered 
August 25, 2023

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@JessicaLucindaCheng 

### What happens if this is not addressed
It makes the website look less professional.

### Resources
- https://www.hackforla.org/projects/

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
-

**Comment by t-will-gillis** [comment]
Hi @JessicaLucindaCheng - I traced this bug back; it was introduced by unneeded (and unnoted) changes made to [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js) by PR #4942 fixes #4136. 

I will look at either reverting the relevant code or otherwise fixing it...

**Comment by JessicaLucindaCheng** [comment]
@t-will-gillis Great! Thanks for looking into it! Did you want to assign yourself to this ER since you are working on it?

**Comment by t-will-gillis** [comment]
@JessicaLucindaCheng thanks, will do!

eta: 8/27/23

**Comment by t-will-gillis** [comment]
Issue #5321 addresses this issue.
