### ISSUE TITLE
Create initial spell check configuration file

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5313]
### Overview
As developers introducing the use of the VSCode Code Spell Checker extension, we need to provide a folder-level configuration file `cspell.json` in the `website` folder, which will establish site spell check settings.

### Action Items
- [x] You must use VS Code as your local text editor to install the VS Code extension for spell checking your codebase,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] Create a new file `cspell.json` in the website (root) folder. 
- [x] Copy/paste the following:
```
{
    "version": "0.2",
    "language": "en",
    // words - list of words to be always considered correct
    "words": [
        "collabathon"   
    ],
    "ignorePaths": [
        "node_modules",
        ".github"
    ]
}
```
- [x] Save the file then test the VSCode Spell Checker extension:
  - [x] Open a few files in .github/workflows and confirm that no spell check errors appear
  - [x] Open the file `_includes/about-page/about-card-sustainability.html` 
    - [x] Confirm that the term `Collabathon` is not marked as an error or unknown word
    - [x] Confirm that the term `Undebate` is marked as an unknown word
 - [x] Add/Commit the file `cspell.json` and proceed with a Pull Request in the usual manner

### Resources/Instructions
[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty this is a basic configuration file and will be filled out with additional words, paths, and exclude patterns in subsequent issues.

**Comment by erinzz** [comment]
Avail M-F 9-5
ETA: 9/11 EOD

**Comment by roslynwythe** [comment]
Hi @erinzz please update the ETA on this issue.  This issue is time-sensitive and I would like to help in any way that I can so please send me a Slack DM if you run into any problems.  Thank you!
