### ISSUE TITLE
Update Project Profile: Access the Data Leadership

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#5315]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want the information that we present for each of our projects to be up to date. There are recent personnel changes with the Access the Data project that need to be reflected on our website.

### Action Items
- [x] Go to the [Access The Data](https://github.com/hackforla/website/blob/gh-pages/_projects/access-the-data.md) markdown page and identify the `leadership` section. For both individuals listed, remove the entirety of their entry from `-name: ...` through `picture: ...`
  - [x] Deepa Mohan
  - [x] Jason Yung
- [x] Confirm on Docker that the individuals have been removed and no unexpected changes have occurred on the Access the Data project page.

### Resources/Instructions
[Access The Data](https://www.hackforla.org/projects/access-the-data) project page
This issue initiated by #5238

**Comment by meru-a** [comment]
Availability: In the evening & on weekends
ETA: EOD 09/03

**Comment by t-will-gillis** [comment]
Hello @pearlescence-m if you are working on this issue, please remember to move this to the "In progress (actively working)" column. If not, please un-assign yourself. Thanks!
