### ISSUE TITLE
Remove inline styling throughout site

### ISSUE THREAD

**Issue by KianBadie** [hackforla/website#532]
### Overview
There are files in the site that have inline styling. Remove the inline styling and create styling classes in the appropriate scss files.

### Action Items
- [ ] Move inline styles in files in the _includes folder to classes in appropriate scss file:
   - [x] resource-card
   - [ ] hacknights: just style for background img
   - [x] project card
- [x] Move inline styles in files in _layouts folder to classes in appropriate scss file:
   - [x] project
   - [x] redirect
- [x] Move inline styles in root directory to classes in appropriate scss file:
   - [x] getting-started

**Comment by KianBadie** [comment]
For the inline styles in the hacknights section 
```
{%- for item in hacknights -%}
            <div class="location">
                <div class="location-img" style="background-image: url({{ item.image | absolute_url }})"></div>
                <div class="location-details">
                    <h3>{{ item.title }}</h3>
                    {{ item.event_date }}
                    <div>
                        Onboarding: <em>{{ item.onboarding }}</em>
                    </div>
                </div>
            </div>
{%- endfor -%}
```

I don't feel it is much worth it to remove the inline styling. The inline styling here is utilizing the Jekyll loop/variables. The styling can't be added to a class because Jekyll is determines "{{ item.image | absolute_url }}" in this file rather than the file containing the styling rules. You can avoid in line styling by setting an html element attribute containing the result of "{{ item.image | absolute_url }}", and then using javascript to loop through those elements setting the background image attributes to the values of the element attributes you created with the Jekyll loop. But at that point, I feel like it doesn't solve the problem that inline style creates. 

But if there is some benefit I am missing, please let me know.

**Comment by ExperimentsInHonesty** [comment]
@KianBadie will put a pull request in.  @ye-susan will review it.
