### ISSUE TITLE
Fix bug with display of Tools data on Homepage and Projects page

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#5321]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We want our website to demonstrate professionalism and attention to detail to our visitors. On the homepage and Projects page, a bug was recently introduced that removes the spaces between entries in the Tools data. 

<details>
<summary>Screenshot of existing Tools data on project card, no spaces between entries</summary>

![Screenshot 2023-08-28 195937](https://github.com/hackforla/website/assets/40799239/d70354e7-05ee-4e51-8cda-97739a733979)

</details>

### Action Items

- [x] Refer to [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js), which is the code for the rendering of the project data on the two HfLA webpages.
- [x] Towards the end of the file, within the `projectCardComponent()` function, there is code to render the tools data when it exists. 
  - [x] The indentation of the `<div class="project-tools">` needs to match the indentation of the other `<div>`s in this section.
  - [x] The line which includes `${ project.tools }` should be refactored in a similar fashion as for `project.languages` and `project.technologies`, so that a comma and a space are added between the each entry when joining the tools data into a list string
- [x] Confirm with Docker on your local repo that the Tools data renders as expected on the two webpages, and review and compare the rest of the pages to confirm that no other unexpected changes/ deletions/ etc. have been made.

### Resources/Instructions
[Hompage](https://www.hackforla.org/)
[Projects](https://www.hackforla.org/projects/) page
This issue was initiated by #5309

**Comment by t-will-gillis** [comment]
Hello @erinzz I am unassigning you from this issue because you have not completed a `Complexity: Small` issue yet. There currently are small issues available on the Project Board.

**Comment by davidwiese** [comment]
Availability: August 30 12-4pm
ETA: August 31 4pm
