### ISSUE TITLE
Refactor Projects-Check page Tools 

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#5322]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
For the [Projects-Check](https://www.hackforla.org/projects-check/) page, the code that renders each projects' Tools data has  complexity that is no longer needed. This code should be simplified so that it is consistent with adjacent code.

### Details
While implementing a series of issues for changing our projects' tools data from a string to a list/array structure, there was a brief period of time when the code for the Projects Check page needed to be able to render correctly regardless of the data type. Now that these issues are complete, we are able to simplify this code.

### Action Items

- [x] Refer to [current-projects-check.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects-check.js), which is the code for rendering each projects' data on the Project Check page.
- [x] Towards the end of the file, within the `projectCardComponent` function, there is code to render the tools data when it exists. 
  - [x] The line which includes `${ project.tools }` should be refactored in a similar fashion as for `project.languages` and `project.technologies`, so that a comma and a space are added between the each entry when joining the tools data into a list string
- [x] Confirm with Docker on your local repo that the Tools data renders as expected (that is, as before) and review and compare the rest of the pages to confirm that no other unexpected changes/ deletions/ etc. have been made. Provide screenshots of 'before' and 'after' to demonstrate.

### Resources/Instructions
[Projects Check](https://www.hackforla.org/projects-check/) page

**Comment by antho-zng** [comment]
Availability: M–F 9–5pm ET
ETA: 9/18 EOD (by 5pm ET)
