### ISSUE TITLE
Edits to Tools data for Tech Work Experience

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#5323]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
On the filters for Tools data on the homepage and Projects page, and on the individual project pages, the goal is to provide users with granularity on the filters so they can find the information more easily. On the Tech Work Experience page, we want to separate the entry for Google Workspace into its individual components.

### Action Items

- [x] Go to the [Tech Work Experience](https://github.com/hackforla/website/blob/gh-pages/_projects/tech-work-experience.md) markdown page and find the entry under `tools:`
- [x] Replace the line:
```
 - Google Workspace (Sheets, Docs, Forms, Mail Merge, Calendar)
```
with:
```
- Google Sheets
- Google Docs
- Google Forms
- Google Mail Merge
- Google Calendar
```
- [x] Confirm with Docker on your local repo that the Tools data has been changed and is shown correctly, and that no other changes have occurred, including the Tech Work Experience page, homepage, and Projects pages.

### Resources/Instructions
[Tech Work Experience](https://www.hackforla.org/projects/tech-work-experience) project page
[Hompage](https://www.hackforla.org/)
[Projects](https://www.hackforla.org/projects/) page
[Projects Check](https://www.hackforla.org/projects-check/) page
This issue was initiated by #5194

**Comment by kabszac** [comment]
Availabilty - Monday to saturday
ETA- wednesday 20/09/23
