### ISSUE TITLE
Edits to Tools data for Food Oasis

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#5324]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We want our website to demonstrate professionalism and attention to detail to our visitors. On the Food Oasis project, we need to make edits so that we are displaying text in a consistent manner.

### Action Items
- [x] Go to the [Food Oasis](https://github.com/hackforla/website/blob/gh-pages/_projects/food-oasis.md) markdown page and find the entry under `tools:`
- [x] Replace the line:
```
 - Google forms
```
with:
```
- Google Forms
```
- [x] Replace the line:
```
  - Usabilityhub.com surveys
```
with:
```
  - UsabilityHub
```
- [x] Confirm with Docker on your local repo that the Tools data has been changed and is shown correctly, and that no other changes have occurred, including the Food Oasis page, homepage, and Projects pages.

### Resources/Instructions
[Food Oasis](https://www.hackforla.org/projects/food-oasis) project page
[Hompage](https://www.hackforla.org/)
[Projects](https://www.hackforla.org/projects/) page
[Projects Check](https://www.hackforla.org/projects-check/) page
This issue was initiated by #5193

**Comment by sayeedkhannabil** [comment]
i. Availability: Today: 17 September
ii. ETA: Today: 17 September
