### ISSUE TITLE
ER: Rename events passed in as a parameter to e

### ISSUE THREAD

**Issue by StephenTheDev1001** [hackforla/website#5326]
### Emergent Requirement - Problem
Rename events passed as a function parameter to `e` to have consistency throughout the JS files

### What happens if this is not addressed
Our codebase will have naming inconsistencies. We may soon run out of "Good First Issue"s for new members.

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
#5290

**Comment by roslynwythe** [comment]
@StephenTheDev1001 Bonnie did not want to pursue this.  I should have explained that this sometimes happens, and that to avoid the wasted effort of writing the issue, it is a good idea to just describe the issue briefly in the "Potential solutions (draft)" section.  Then it can go through the approval process (dev lead -> PM) and you can go ahead and write the issue.

**Comment by roslynwythe** [comment]
@StephenTheDev1001 Bonnie did not want to pursue this.  I should have explained that this sometimes happens, and that to avoid the wasted effort of writing the issue, it is a good idea to just describe the issue briefly in the "Potential solutions (draft)" section.  Then it can go through the approval process (dev lead -> PM) and you can go ahead and write the issue.
