### ISSUE TITLE
ER: Use VRMS data to update the meeting times on the CoP page

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5328]
### Emergent Requirement - Problem
Currently, the meeting times on the _Communities of Practice_ (CoP) page [^1] are manually updated in the yml files under _data/internal/communities [^2]. This can make the meeting times out of date with the meeting times on the _Events_ page [^3].

### Issue you discovered this emergent requirement in
- #5132

### Date discovered 
2023-Aug-06

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@JessicaLucindaCheng 

### What happens if this is not addressed
We have to continue manually editing the CoP yml files to update meeting times.

### Recommended Action Items
- [x] Make 2 new issues. See "Potential solutions [draft]" section
- [x] Discuss with team
- [x] Let a Team Lead know

### Potential solutions [draft]
1. Write an issue with "Complexity: Large" to start pulling the meeting time from the VRMS data similar to how the project's pages [^4] using the VRMS data from `_data/external/vrms_data.json` [^5].
2. Write another issue with a "Complexity: Small" label needs to be written that adds the note below to the "Communities of Practice information updates" form's template [^6] "Resources" section. Also, add a "Dependency" section at the top of the issue and add a link to the issue you wrote in 1 above. 
```
If you need to update your meeting times, names, dates, or frequency, please see the [VRMS User Guide](https://github.com/hackforla/VRMS/wiki/User-Guide). The HackforLA.org website gets the meeting times from the updates made to each Community of Practice's meeting data in vrms.io
```

### Resources
[^1]: [Communities of Practice (CoP) page](https://www.hackforla.org/communities-of-practice)
[^2]: [_data/internal/communities](https://github.com/hackforla/website/tree/gh-pages/_data/internal/communities)
[^3]: [Events page](https://www.hackforla.org/events/)
[^4]: https://www.hackforla.org/projects/311-data
[^5]: https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json
[^6]: [.github/ISSUE_TEMPLATE/communities-of-practice-information-updates.yml](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/communities-of-practice-information-updates.yml?plain=1)
- #7072
- #7273

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-pm After the CoP page's meeting times are updated using VRMS data, is the following wording what you want to be added to the "Resources" section of the [Communities of Practice information updates form](https://github.com/hackforla/website/issues/new?assignees=&labels=role%3A+product%2CP-Feature%3A+Communities+of+Practice%2Ctime+sensitive%2CComplexity%3A+Missing%2Csize%3A+missing&projects=&template=communities-of-practice-information-updates.yml&title=Communities+of+Practice+information+updates%3A+%5BINSERT+NAME+OF+Community+of+Practice%5D)?

> If you need to update your meeting times, names, dates, or frequency, please see the [VRMS User Guide](https://github.com/hackforla/VRMS/wiki/User-Guide). The HackforLA.org website gets the meeting times from the updates made to each Community of Practice's meeting data in vrms.io

I wasn't sure if this was the correct process for CoP leads to update their meeting times in VRMS.

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng YES

**Comment by ExperimentsInHonesty** [comment]
@JessicaLucindaCheng I made changes to item 1 under potential solutions and added Resources 5 to indicate the location of the VRMS data.  We are trying to get away from pull the data directly from VRMS live and instead pull it from our own data store (which pulls it nightly from VRMS).

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 

> @JessicaLucindaCheng I made changes to item 1 under potential solutions and added Resources 5 to indicate the location of the VRMS data. We are trying to get away from pull the data directly from VRMS live and instead pull it from our own data store (which pulls it nightly from VRMS).

Good catch! Sorry, I missed that. Thanks for making the edits!

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe 

I addressed Bonnie's comment and I made some minor edits to clarify the anticipated complexity of the issues under "Potential Solutions". It is ready for you to review to see if it is `ready for prioritization`. Thanks.

**Comment by ExperimentsInHonesty** [comment]
Here is an example ER and the Large issue that was created from it
- ER: https://github.com/hackforla/website/issues/6687
- Large issue: https://github.com/hackforla/website/issues/6775

**Comment by del9ra** [comment]
i. Availability: Monday-Friday 10AM - 3PM
ii. ETA: June 30

**Comment by t-will-gillis** [comment]
@del9ra @JessicaLucindaCheng Just want to confirm. I merged #7169 fixes #7072 which addresses Item 1 above. Is there supposed to be an issue for Item 2 as well?  

<img width="704" alt="Screenshot 2024-08-10 125651" src="https://github.com/user-attachments/assets/904be17f-b196-479d-86cd-5b452bda659a">

**Comment by del9ra** [comment]
> @del9ra @JessicaLucindaCheng Just want to confirm. I merged #7169 fixes #7072 which addresses Item 1 above. Is there supposed to be an issue for Item 2 as well?
> 
> <img alt="Screenshot 2024-08-10 125651" width="704" src="https://private-user-images.githubusercontent.com/40799239/356835708-904be17f-b196-479d-86cd-5b452bda659a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzOTQ4MDgsIm5iZiI6MTcyMzM5NDUwOCwicGF0aCI6Ii80MDc5OTIzOS8zNTY4MzU3MDgtOTA0YmUxN2YtYjE5Ni00NzlkLTg2Y2QtNWI0NTJiZGE2NTlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDE2NDE0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ODMzYWZjZTdjMzVhMjU0NTdlMjExMjg0ZWI3ZGNjODQ3MDJhOGM5MWEyM2RhZTJlZmEyMThiMjQwZDkzYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vm-ub1rVm1yVODk97XCLSWwbyog1eIOBP1Y1V0ympYk">

Hi Will @t-will-gillis , I created a small issue for item 2 https://github.com/hackforla/website/issues/7273

**Comment by del9ra** [comment]
Closing this ER. 2 issues created: small and large

**Comment by del9ra** [comment]
Closing this ER. 2 issues created: small https://github.com/hackforla/website/issues/7273 and large https://github.com/hackforla/website/issues/7072
