### ISSUE TITLE
Home page style corrections

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#533]
### Overview
Make home page stylistic corrections

### Action Items
- [x] Change color of page captions (e.g. "Press", "Get in Touch") from red to black
- [x] Vertically center button descriptors within Get In Touch container with buttons

### Resources/Instructions
<img width="189" alt="Screen Shot 2020-05-23 at 3 29 03 PM" src="https://user-images.githubusercontent.com/21990572/82739980-24272380-9d0a-11ea-8d5e-e72532138216.png">
<img width="403" alt="Screen Shot 2020-05-23 at 3 29 13 PM" src="https://user-images.githubusercontent.com/21990572/82739983-2a1d0480-9d0a-11ea-87d7-b227679863c9.png">

**Comment by leonelRos** [comment]
@harishlingam I have changed both captions colors. let me know if this looks good to proceed to make the PR. Thanks

<img width="896" alt="Screen Shot 2020-05-26 at 11 31 21 AM" src="https://user-images.githubusercontent.com/50648001/82937097-6dfb4e00-9f44-11ea-9fa1-940c8ffda756.png">
<img width="936" alt="Screen Shot 2020-05-26 at 11 31 34 AM" src="https://user-images.githubusercontent.com/50648001/82937123-75baf280-9f44-11ea-84d2-1a9d68f15bd9.png">

**Comment by leonelRos** [comment]
@harishlingam  I aligned the letters vertically and also they are between the size of the button as you can see in the first image below. 

<img width="718" alt="Screen Shot 2020-05-26 at 2 03 56 PM" src="https://user-images.githubusercontent.com/50648001/82950236-cbe66080-9f59-11ea-95ff-825104e109e0.png">

<img width="712" alt="Screen Shot 2020-05-26 at 2 04 31 PM" src="https://user-images.githubusercontent.com/50648001/82950249-d43e9b80-9f59-11ea-955e-3e3636dc2f35.png">

**Comment by ExperimentsInHonesty** [comment]
@leonelRos 
- [x] removing About from the menus
- [x] replacing the about in mobile with Connect
- [x] replacing Contact Us with Connect on Top menu
- [x] Make the Anchor for connect go to "Want to know more about.... "
- [x] remove Get In Touch subtitle.

**Comment by leonelRos** [comment]
@harishlingam  @ExperimentsInHonesty  
I removed the "About" from the navbar, replaced with "Connect". I also replace the mobile version with "Connect" and the anchor starts at "Want to know more about... "


<img width="1028" alt="Screen Shot 2020-06-06 at 8 26 11 PM" src="https://user-images.githubusercontent.com/50648001/83959628-fd9dd800-a833-11ea-809b-522b9a85c785.png">

<img width="157" alt="Screen Shot 2020-06-06 at 8 27 10 PM" src="https://user-images.githubusercontent.com/50648001/83959634-1d350080-a834-11ea-8dc0-64549a9374b6.png">
