### ISSUE TITLE
Comment out broken Site link on Engage project

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#5330]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to comment out the non-functional "Site" link for the Engage project to prevent users from encountering dead links on our site.

### Details
The Engage project has links that are currently leading to non-existent pages. This includes the main "Site" link. This issue aims to temporarily hide this link from the website's visitors until we have the correct, functioning links in place.

### Action Items
- [x] Go to the [engage.md](https://github.com/hackforla/website/blob/gh-pages/_projects/engage.md) file in the GitHub repository.
- [x] Identify the lines containing **only** the "Site" link.
- [x] Comment out both the line beginning with ` - name: ...` as well as the line with `   url: ...` so the "Site" link will not be rendered on the live website. In Markdown, this can be done by placing a '#' at the start of each line. If you are using VSCode, you can highlight the line(s) to be commented out, then select 'Ctrl/Cmd' + '/' to automatically insert the '#'s.
- [x] Confirm that the "Site" link is no longer visible on the live site by running the site locally on Docker and provide before and after screenshots.

### Resources/Instructions
[Engage](https://www.hackforla.org/projects/engage) project page
Associated ER: https://github.com/hackforla/website/issues/4594

**Comment by erinzz** [comment]
Availability: M - F 9-6 PM 
ETAL: 8/30 EOD
