### ISSUE TITLE
Project and Toolkit Filter Options Are Cut-off at Bottom of Screen When Viewed on a Mobile Screen

### ISSUE THREAD

**Issue by Adastros** [hackforla/website#5333]
### Overview

We need to prevent the projects and toolkit filter options from being cut-off at the bottom of the screen when viewed on a mobile screen.

### Details
When the filters options overflow `<ul>` within the filter, the cancel and apply filter buttons at the bottom of the screen cover the last few options on the list. 

<details>
<summary>Before overflow - Status options are visible</summary>

![image](https://github.com/hackforla/website/assets/48114590/34982efa-7fa2-4f69-976b-c4aaec6838d9)

</details>

<details>
<summary>After overflow - the "On Hold" Status option is covered by the cancel and apply buttons</summary>

![image](https://github.com/hackforla/website/assets/48114590/460926f7-6ff7-4322-b1d7-38064d32762c)

</details>

### Action Items

- [x] Within the `_dropdown_filters.scss` file, update the styling for the mobile version of the filter so that the cancel and apply buttons at the bottom of the filter do not cover the filter tags.
- [x] Once a solution is implemented, verify that the issue does not appear on the home, projects, and toolkit pages.

### Resources/Instructions

- This issue was created per #5233 
- [Home Page](https://www.hackforla.org/#)
- [Projects Page](https://www.hackforla.org/projects/)
- [Toolkit Page](https://www.hackforla.org/toolkit/?)
- [_dropdown_filters.scss file](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_dropdown_filters.scss)

**Comment by Jfong1218** [comment]
Availability: Tuesday 11/7 12:00 - 3:00 pm Monday 11/13 12:00 - 3:00 pm 
ETA: next week EOD 11/13

**Comment by Jfong1218** [comment]
This issue is taking me longer so I will need some more time to work on it 
availability Monday Tuesday 11/20 - 11/21 in the afternoon.

**Comment by Jfong1218** [comment]
Took sometime but it seems like there are no easy fix that I can find. In order for the Cancel and Apply button to not cover the content of the filter list. I've tried changing the position of the div from fixed to absolute as well as relative but they don't seem like good fixes. 
I would suggest changing it to Position:Sticky, that way the position will work with the filter list collapsed or fully extended. Only draw back with this method is the button will be halfway up the page when the filters are all collapsed.
<img width="502" alt="截圖 2023-11-21 下午5 01 22" src="https://github.com/hackforla/website/assets/109251936/efe316af-a891-404d-9d5f-575366aca2b2">
<img width="410" alt="截圖 2023-11-21 下午5 01 28" src="https://github.com/hackforla/website/assets/109251936/a8746242-1544-4e76-8338-23942b3aaa4b">

Can I get some feedback if this is an acceptable fix? or can i get some pointers on how to approach this problem? I believe I'd have to edit some parent and child scss properties.

**Comment by Adastros** [comment]
Hi @Jfong1218, if you inspect the `<ul>` tag and change the existing padding to include bottom padding, you can get it to look like the screenshots below. I think that would be the easiest solution. On how much padding to add, I would try to get it the filter to match the [figma designs](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=532%3A1454&mode=dev) as much as possible. 

I do see the problems with changing the positions of the buttons. It would probably require restructuring the HTML elements on the page to get it to work, but that would be outside the scope of the issue. 

<details>
<summary>ul tag to inspect</summary>

![image](https://github.com/hackforla/website/assets/48114590/7caf1dd4-a6ca-4cb9-a89e-bad78d86980b)

</details>

<details>
<summary>After bottom padding is added</summary>

![image](https://github.com/hackforla/website/assets/48114590/5fdfb9a0-395c-4282-896a-7804a9175076)

</details>

Let me know if you have any other questions or need more help!

**Comment by Jfong1218** [comment]
Thanks Danny! I was able to identify and fix the problem per your instructioins.
