### ISSUE TITLE
Move items from Tools to Technologies in hellogov.md

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#5340]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
For each Hack for LA project listed on our webpages, we need to ensure that the data entries for Tools, Technologies, etc. are appropriate for each category. On the HelloGOV project, there are some entries under Tools that should move to Technologies.

### Action Items

- [x] Locate the HelloGOV markdown file in the website/_projects/ folder.
- [x] Locate the section `tools: ...` For this particular project, we want all of the "Tools" listed to be categorized as "Technologies" instead. Also, some of the entries need minor revisions as shown.
- [x] Therefore, replace:
```
tools:
  - Mongo
  - Angular
  - Node
```
with:
```
technologies:
  - MongoDB
  - Angular
  - Node.js
```
- [x] Provide before and after screenshots of the relevant web pages showing that the change was made successfully with no unintended effects. Also, confirm that the side filter displays the correct information.

### Resources/Instructions
[hellogov.md](https://github.com/hackforla/website/blob/gh-pages/_projects/hellogov.md)
[Hello GOV](https://www.hackforla.org/projects/hellogov) project page
[Hack for LA](https://www.hackforla.org/) homepage
[Projects](https://www.hackforla.org/projects/) page
This issue is initiated by ER #5268

**Comment by t-will-gillis** [comment]
Removing `Ready for Prioritization` and moving to "Prioritized Backlog"

**Comment by segbuniwe** [comment]
Availability for this week: I will be available for ~6-10 hours this week to work on this issue.
My estimated ETA for completing this issue: I plan to complete this issue one week from now, so by Friday, September 22nd, if not earlier.

**Comment by segbuniwe** [comment]
How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings? 

It has taken me about ~6-7 hours to complete all the prework material and a good first issue. I have not yet been able to attend a meeting, but I hope to attend a Sunday meeting soon.
