### ISSUE TITLE
Move Nginx from Tools to Technologies in home-unite-us.md

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#5342]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
For each Hack for LA project listed on our webpages, we need to ensure that the data entries for Tools, Technologies, etc. are appropriate for each category. On the Home Unit Us project page, there is an entry under Tools that should move to Technologies.

### Action Items

- [ ] Locate the Home Unite US markdown file in the website/_projects/ folder.
- [ ] Locate the section `tools: ...` 
- [ ] From `tools: ` select the following entry:
```
  - Nginx
```
- [ ] MOVE only this entry to `technologies: `
- [ ] Provide before and after screenshots of the relevant web pages showing that the change was made successfully with no unintended effects. Also, confirm that the side filter displays the correct information.

### Resources/Instructions
[home-unite-us.md](https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md)
[Home Unite Us](https://www.hackforla.org/projects/home-unite-us) project page
[Hack for LA](https://www.hackforla.org/) homepage
[Projects](https://www.hackforla.org/projects/) page
This issue is initiated by ER #5192

**Comment by t-will-gillis** [comment]
Removing `Ready for Prioritization` and moving to "Prioritized Backlog"

**Comment by sakibian** [comment]
Availability for this week: 08:00 AM to 06:00 PM (GMT+6) 
My estimated ETA for completing this issue: 9/18/23
