### ISSUE TITLE
Revise Projects Meeting page to include more info

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#5345]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
We want the information presented on our webpages to provide pertinent information for visitors. The Project Meetings page needs to provide additional data so that meeting times and descriptions are more useful.

### Action Items
The VRMS database stores relevant information such as start and end time, days of the weeks, descriptions, etc. surrounding each project's meetings. Our website queries VRMS for data in order to create meeting schedules on the Events and Project Meetings pages. This can be seen by reviewing the api-events.js file.
- [x] Open the [api-events.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/utility/api-events.js) file and locate the `insertEventSchedule()` function. 
- [x] Review the current Events and Project Meetings pages. 
<details>
<summary>Screenshot from Events page</summary>

![Screenshot 2023-08-29 211212](https://github.com/hackforla/website/assets/40799239/7f3654ec-0361-4b5a-8b44-27482d5a6e30)

</details>

-  Note that each meeting listed on the Events page displays: `start` - `end`, an href to `hflaWebsiteUrl` displaying `name`, and `meetingName`. 

<details>
<summary>Screenshot from Project Meetings page</summary>

![Screenshot 2023-08-29 211248](https://github.com/hackforla/website/assets/40799239/b8f01e06-ec1e-4f20-8f3c-2bd34d8085ce)

</details>

- Each meeting on the Project Meetings page displays: `start` - `end`, an href to `hflaWebsiteUrl` displaying `name`, and `dsc`.   
- [x] Pseudocode: In the api-events.js file, insert `meetingName` before `dsc`. Note that **_only_** when `dsc` is **_not_** an empty string, a comma needs to be inserted between, for example:  
  
"3:00 pm - 4:00 pm [SomeProject]() meetingName, description"
"5:00 pm - 6:00 pm [OtherProject]() meetingName"
- [x] Hint: the relevant code can be found on lines 42-46.
- [x] Confirm on your local repo that the meeting information is shown correctly on the Project Meetings page and that no other, unexpected changes have occurred on this as well as on the Events page.

### Resources/Instructions
[Project Meetings](https://www.hackforla.org/project-meetings) page
[Events](https://www.hackforla.org/events) page

This issue was initiated by ER #5195

**Comment by mshirk2** [comment]
ETA: 6pm, Mon 11/13
Availability: 10-6pm (PT), Weekdays
