### ISSUE TITLE
Create Outstanding Hero Images

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#535]
### Overview
Upload outstanding hero images for the projects below. Create hero images using the associated hex color codes. The images are to be 1500 x 700 with corresponding alt image text.

### Action Items
- [ ] Create hero image for Not Today: #006DEF
- [ ] Create hero image for Jobs  for Hope: #A5B2CA
- [ ] Create hero image for Shared Housing: #D9E0EC
- [ ] Create hero image for Spare: #A5B2CA

**Comment by yulia-kh** [comment]
<img width="1045" alt="Screen Shot 2020-05-30 at 6 54 15 PM" src="https://user-images.githubusercontent.com/13112628/83342686-1263f400-a2a7-11ea-892d-2acd018a5af6.png">
<img width="1042" alt="Screen Shot 2020-05-30 at 6 53 27 PM" src="https://user-images.githubusercontent.com/13112628/83342680-06783200-a2a7-11ea-95b0-320b469465ae.png">
<img width="1042" alt="Screen Shot 2020-05-30 at 6 53 48 PM" src="https://user-images.githubusercontent.com/13112628/83342682-0d9f4000-a2a7-11ea-809a-1c83e3094f4e.png">
<img width="1046" alt="Screen Shot 2020-05-30 at 6 53 59 PM" src="https://user-images.githubusercontent.com/13112628/83342684-109a3080-a2a7-11ea-8996-ff50767163a8.png">

**Comment by ExperimentsInHonesty** [comment]
Please change jobsforhope to #843d78
