### ISSUE TITLE
Refactor HTML: _includes/about-page/about-card-platform.html - Workforce Development

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5365]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Tag must be paired; missing `</span>`"

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-platform.html`
- [x] Change the line of code
```
            <div class="sub-card-head"><span class="sub-head-image"><img src="/assets/images/about/platform-header-elements/workforce-development.svg" alt=""></span><span class="sub-head-text color-dodgerblue">Workforce Development</div>
```
to
```
            <div class="sub-card-head"><span class="sub-head-image"><img src="/assets/images/about/platform-header-elements/workforce-development.svg" alt=""></span><span class="sub-head-text color-dodgerblue">Workforce Development</span></div>
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 1 in the Resources/Instructions section below)

### Merge Team
- When this issue is completed, 
   - [x] check off the issue in #5279
   - [x] leave this comment on the issue #5279
````
@roslynwythe this is the last issue in this epic.  Please add the following to the next PM/Dev agenda
```
- [ ] BW: we are finished with this epic, do we need to re-run the linter to see if there are any additional HTML errors it catches?
```
````
### Resources/Instructions
1. Webpage(s): https://www.hackforla.org/about
2. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

**Comment by angela-lee1** [comment]
Availability: 2/13 6pm-10pm 
ETA: 2/15 EOD

**Comment by ExperimentsInHonesty** [comment]
@awlFCCamp I have unassigned you from this issue (because you already have done two good first issues and need to move on to a small size issue.  I have reopened your prework where I will send you a link to find a new issue.

**Comment by evan-ishibashi** [comment]
Availability for this week: 2/13 5pm - 7pm 
My estimated ETA for completing this issue: 2/13
(commenting after the pr was made)

**Comment by evan-ishibashi** [comment]
How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?
1 Hour to get to the first good issue, about to head into the 1 hour meeting soon

**Comment by angela-lee1** [comment]
I may not fully understand the question, you probably need more than an hour for the pre-work.
    On Tuesday, February 13, 2024 at 08:37:32 PM CST, Evan Ishibashi ***@***.***> wrote:  
 
 


How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?
1 Hour to get to the first good issue, about to head into the 1 hour meeting soon

**Comment by evan-ishibashi** [comment]
@awlFCCamp 
I realize that the estimate needs more context. I completed a lot of the earlier steps during the onboarding meeting, which took a couple of hours. I've also had prior experience with git and github branching, so that might have taken less time. So realistically it probably is closer to 2 - 3 in total. I was just estimating the time it took when I started working on the checklist. thanks

**Comment by ExperimentsInHonesty** [comment]
@awlFCCamp please move the notes about "How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?" to the prework issue where they belong.

Also, I have moved this issue to in progress.  When you self assign future issues, please remember to move them to the in progress column. 👍

**Comment by ExperimentsInHonesty** [comment]
Evan is assigned to this issue.  So its his issue.  All other comments are irrelevant. @awlFCCamp please unsubscribe to this issue so that you don't keep getting notifications for it.  Open the issue, and click un ubsubscribe button.
