### ISSUE TITLE
Refactor HTML: _includes/about-page/about-card-platform.html - Inclusivity

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5373]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We want to update an HTML tag to resolve the linter error "Tag must be paired; missing `</span>`"

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-platform.html`
- [x] Change the line of code
```
<div class="sub-card-head"><span class="sub-head-image"><img src="/assets/images/about/platform-header-elements/inclusivity.svg" alt=""></span><span class="sub-head-text color-blueviolet">Radical Inclusivity</div>
```
to
```
<div class="sub-card-head"><span class="sub-head-image"><img src="/assets/images/about/platform-header-elements/inclusivity.svg" alt=""></span><span class="sub-head-text color-blueviolet">Radical Inclusivity</span></div>
```
- [x] Using Docker, check the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below)

### Merge Team
- [x] When this issue is completed, check off the issue in #5279

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-platform.html
2. Webpage(s): https://www.hackforla.org/about
3. This issue is tracked in [HfLA-Website: HTML linter audit spreadsheet](https://docs.google.com/spreadsheets/d/1P6o_ofzfIUPizfhpFmF9p92SNZrpAIEnWNyErWwpRiA/edit#gid=0), and #5279

**Comment by Autisticturtle3** [comment]
Availability for this week: 10 hours
My estimated ETA for completing this issue: 1 hour
How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?: less than 1 hour
Provide Update

Progress: finished
Blockers: None
Availability: 10 hours
ETA: less than 1 hour
