### ISSUE TITLE
 Homepage: filters section for big screen should have fix position and stick to left side

### ISSUE THREAD

**Issue by ratishjain12** [hackforla/website#5375]
### Overview

Want to make filters section stick to left for big screens

### Action Items

- [ ] For large desktop screens, position the filter section so that it "sticks" to the left side of the screen

### Resources/Instructions

![Screenshot 2023-08-30 223427](https://github.com/hackforla/website/assets/43003421/d7a8d76a-f327-4963-9ca5-72241c6a2c55)

**Comment by roslynwythe** [comment]
Thank you @ratishjain12 for creating this issue.   We need to apply a `Complexity` and `size` labels to it.   Please advise, how much development time (in hours) do you expect this issue to take, and do you have any specific recommendations or strategy you could share about how the change would be accomplished?

**Comment by ratishjain12** [comment]
Hey @roslynwythe the strategy would be simply using position sticky for the big screen so when user scrolls the sidebar sticks to left, it wouldn't take many hours I can solve it within a day or so

**Comment by ExperimentsInHonesty** [comment]
@ratishjain12 I don't understand the need for the menu to  stick to the left side of screen.  All the pages on the site are center aligned.  Did you mean that it should visible as the user scrolls?  If you did mean that the page should left align, could you explain why you think that would benefit users?

**Comment by ratishjain12** [comment]
I believe if we make the side nav/filters section sticky user would not have to scroll above everytime to choose filters , by making it fixed/sticky on the left user would not have to scroll @ExperimentsInHonesty

**Comment by ExperimentsInHonesty** [comment]
- @ratishjain12 there is already an issue that addresses your suggestion, which was made a few months earlier than this issue was created https://github.com/hackforla/website/issues/4593
