### ISSUE TITLE
Update Project Profile: LA TDM Calculator

### ISSUE THREAD

**Issue by Biuwa** [hackforla/website#5381]
### Project Name

LA TDM Calculator

### Project Card URL

tdm-calculator.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Moji Momoh

Name: James Higgs

### Add person(s) and info to Leadership?

NO

### Project Status

Active

**Comment by t-will-gillis** [comment]
Two issues created #5393, #5394 above to address this ER
