### ISSUE TITLE
ER: Update Project Profile: Guides Team

### ISSUE THREAD

**Issue by edwardsarah** [hackforla/website#5407]
### Dependency
- [x] #5584
- [x] #5623
- [x] #5624 

### Project Name

Guides Team

### Project Card URL

guides-team.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Shawn Wong

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Rhoda Michael
GitHub Handle: the-techgurl
Role: UX Research Lead
Slack Member ID: U05JS9NLNQJ

Name: Sarah Levine
GitHub Handle: levines2017
Role: Product Manager
Slack Member ID: U05RWQJ8YKU

### Project Status

Active

**Comment by JessicaLucindaCheng** [comment]
# Original request from edwardsarah 

### Project Name

Guides Team

### Project Card URL

guides-team.md

### Update the Title?

NO

### Title

_No response_

### Update the Description?

NO

### Description

_No response_

### Update the Image?

NO

### Image

_No response_

### Update the Technologies?

NO

### Technologies

_No response_

### Update the Partner(s)?

NO

### Partners

_No response_

### Update the Tools?

NO

### Tools

_No response_

### Update GitHub Link?

NO

### GitHub Link

_No response_

### Update Slack Link?

NO

### Slack Link

_No response_

### Update Test Site Link?

NO

### Test Site Link

_No response_

### Update Demo Site Link?

NO

### Demo Site Link

_No response_

### Update Site Link?

NO

### Site link

_No response_

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Shawn Wong

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Rhoda Michael
GitHub Handle: the-techgurl
Role: UX Research Lead
Slack Member ID: U05JS9NLNQJ

Name: Sarah Levine
GitHub Handle: levines2017
Role: Product Manager
Slack Member ID: U05RWQJ8YKU

### Project Status

Active

**Comment by JessicaLucindaCheng** [comment]
For writing issue(s):
- Availability: 1.5 h
- ETA: Tue, Sep 26, 2023

**Comment by JessicaLucindaCheng** [comment]
The following issues address the items in this request:
- #5584
- #5623
- #5624

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-pm Since "Update Project Profile" issues are becoming ERs and we are sometimes writing multiple new issue(s) from one request, how are we handling UAT now? Are we going to ask for approval for each individual issue, which can be a lot of issues? Are we going to ask for approval in a comment on the original request, which will limit how often we ask for approval from the requestor?

Ans: Going to ask for approval in a comment on the original request
- [x] Put the resultant issues in the Dependency section
- [x] For each issue in dependency, have an action item about moving the issue to the `Questions/In Review` column
- [x] Add a `ready for dev lead` label
- [x] Unassign myself
- [x] Move this to the Ice Box

**Comment by JessicaLucindaCheng** [comment]
@dev lead
Once the issues in the Dependencies section have been merged, please contact edwardsarah to approve the changes on the [Guides Team page](https://www.hackforla.org/projects/guides-team).

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issues in the Dependency section have been merged, please contact the person who opened this ER to approve the changes on the [Guides Team page](https://www.hackforla.org/projects/guides-team).

**Comment by JessicaLucindaCheng** [comment]
@edwardsarah Please let us know if the changes made to the [Guides Team page](https://www.hackforla.org/projects/guides-team) match what you requested by adding a comment to this issue. Thank you.

**Comment by edwardsarah** [comment]
Yes, the Guides team page now matches the changes I requested. Thanks!
