### ISSUE TITLE
remove mention of CfA - about.html

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5408]
### Overview
We need to remove mention of CfA from the Hack for LA homepage, under the heading "Want to know more about Hack for LA?"

### Action Items
- [x] In your local IDE, navigate to `_includes/about.html`
 replace this text:
```
	<p>
      We bring together civic-minded volunteers to build digital products, programs and services with community partners and local 
      government to address issues in our LA region. Hack for LA is a project of <a href="https://www.codeforamerica.org" rel="noopener" target="_blank">Code for America</a> and is it's 
      official Los Angeles chapter. 
    </p>
```
with
```
	<p>
      We bring together civic-minded volunteers to build digital products, programs and services with community partners and local 
      government to address issues in our LA region. Hack for LA is a project of <a href="https://www.civictechstructure.org/" rel="noopener" target="_blank">Civic Tech Structure, Inc.</a>
    </p>
```
- [x] Using Docker, view the webpage and confirm that the text under the heading "Want to know more about Hack for LA?" has been updated, and the rest of the page is unchanged.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/about.html
2. Webpage(s): https://www.hackforla.org/#press

**Comment by innith** [comment]
> 
> 
> Hi @innith, thank you for taking up this issue! Hfla appreciates you :)
> 
> Do let fellow developers know about your:-
> i. **Availability:** (When are you available to work on the issue/answer questions other programmers might have about your issue?)
> ii. **ETA:** (When do you expect this issue to be completed?)
> 
> You're awesome!
> 
> P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)
> 

 I have lately realised that my past 2 pull requests were not merged or closed , I won't be taking up any other issue from now on, untill the previous issues gets closed or merged , thank you .

**Comment by YolandaHaynes** [comment]
Availability: M-F from 6-9pm pst.
ETA: end of day 8/18.
