### ISSUE TITLE
remove mention of CfA - sponsors on homepage

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5409]
### Overview
We need to remove mention of CfA from the list of sponsors on the Hack for LA homepage. 

- [x] In your local IDE, navigate to `_includes/sponsors.html`
- [x] remove these lines:
```
            <a href="https://www.codeforamerica.org" target="_blank" alt="Code for America">
                <img src="/assets/images/sponsors/code-for-america.svg" title="Code for America">
            </a>
```
- [x] Using Docker, view the webpages and confirm that "Code for America" has been removed from sponsors, and the rest of the page is unchanged.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/sponsors.html
2. Webpage(s): https://www.hackforla.org/

**Comment by pradeeptosarkar** [comment]
@roslynwythe raised PR no. 5446. pls check. thanks

**Comment by ortegaa32** [comment]
Availability for this week: 1 - 3 PM everyday
My estimated ETA for completing this issue: 3 PM 09/07/23

**Comment by ortegaa32** [comment]
Provide Update
1. Progress: I removed the lines from the relevant file.
2. Blockers: Despite removing the lines from the file, the CfA sponsor doesn't get removed from the webpages. I suspect that it may be due to the pages HTML files but I am not sure.
3. Availability: 1-3PM everyday
4. ETA: 09/13/23

**Comment by roslynwythe** [comment]
Hi @ortegaa32 Are you previewing the changes locally?  To do that, you must run `docker-compose up` and then browse to:  http://localhost:4000/ and http://localhost:4000/about/#sponsors.  Please contact me directly on Slack.  

Also, after self-assigning an issue, please change the column to `In Progress`.  I've done that for this issue.  Thanks
