### ISSUE TITLE
remove mention of CfA from Brigade Organizer's Playbook project info

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5411]
### Overview
We need to remove mention of CfA from the Brigade Organizer's Playbook list of partners and description.

### Action Items
- [x] In your local IDE, navigate to `_projects/brigade-organizers-playbook.md` 
- [x] replace
```
partner: Code for America (CfA), CfA National Advisory Council, Code for Boston, Code for Charlottesville
```
with
```
partner: Code for Boston, Code for Charlottesville 
```
- [x] replace
```
description: Each of the 80+ Code for America Brigades is an experiment which generates valuable learnings and new effective processes and practices. However, Brigades and other civic tech volunteer organizations need not start from scratch. This project aims to improve existing structures and create new ones that make it easier to share replicable processes and practices so that organizers and members can iterate on each others work, improving outcomes for the whole network.  The original project was started as part of the Code for America National Advisory Council with Hack for LA as the volunteer staffing partner.
```
with
```
description: Civic tech volunteer organizations often start building from scratch, which uses up valuable resources (time, labor and momentum).  This project aims to improve existing structures and create new ones that make it easier to share replicable processes and practices so that organizers and members can iterate on each other's work, improving outcomes for the civic tech ecosystem.
```
- [x] Using Docker, confirm that the changes are reflected on the Brigade Organizer's Playbook project webpage, and the surrounding elements are unchanged.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/brigade-organizers-playbook.md
2. Brigade Organizer's Playbook project webpage(s): https://www.hackforla.org/projects/brigade-organizers-playbook

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty I wasn't sure if  "CfA National Advisory Council" should remain in the list of partners.

**Comment by LiQuiD-404** [comment]
@roslynwythe I would like to work on this issue. Could you assign me this issue? 
Estimated Time Required: 15-20mins
Issue will be fixed by 2 September 2023

**Comment by LiQuiD-404** [comment]
@innith I am already working on this issue. Please do not assign yourself issues without asking

**Comment by innith** [comment]
> oh! I understand , You should have assigned it yourself, If you wish to contribute, please read [ this](https://github.com/hackforla/.github/tree/main/profile/README.md), so If you wish to contribute to hfla , you can become a member by following [these steps](https://www.hackforla.org/getting-started) , as I did, I should have informed you about this process before assigning it my self, any way I hope this helps you.

**Comment by roslynwythe** [comment]
@innith This issue is not yet approved or prioritized so I must unassign you.  Please only self-assign issues from the Prioritized Backlog column.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe yes, Thanks for pointing that out.  I revised to remove and I added a sentence that explains the history in the description.

**Comment by agutiernc** [comment]
Availability: 9/6/23
ETA: EOD on 9/6/23
