### ISSUE TITLE
Create Organizational Dashboard page

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#542]
### Overview
Create Organizational Dashboard page to house analytics collected from surveys. Initially, the dashboard will house data from the remote onboarding, new member, and project leader surveys, but eventually, expand to include the visualized results from the other surveys in our repertoire.

Instructions to remove the vertical scrollbar have been included below. Please add/remove vertical scrollbar depending on UX considerations.

### Action Items
- [x] Design and populate Google Data Studio dashboard
   - [x] Create dashboard in Google Data Studio
   - [x] Get feedback on dashboard
   - [x] Create dashboard page and insert GDS dashboard via iframe 
   - [x] Revise dashboard
   - [x] Refine page UI in Figma
   - [x] Sign off
- [x] Review feasibility with Kian
- [x] Review with Design team which of the two designs work best with our current design schema and if we are going to leave off the white band at bottom?
- [x] Development
   - [x] Implement page design with Iframe from Figma mockups.  Note Figma mock up missing while band at bottom.  Decision will have already been made to include or not include it.
   - [ ] Show version with scroll bar to Bonnie
      - [ ] decide to remove scroll bar (creating a lot of white space), or leave.
   - [x] complete page.

### Resources/Instructions

Figma https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=811%3A1003

#### Desktop Embed:

<iframe width="1200" height="1800" src="https://datastudio.google.com/embed/reporting/16J9XI19pQejSDNFvjl_V3ZezJ502rM_a/page/qx6RB" frameborder="0" style="border:0" allowfullscreen></iframe>
  
#### Mobile Embed:

<iframe width="350" height="2000" src="https://datastudio.google.com/embed/reporting/1xNlu1xcL5y6jh95lX3xr0zb2FCqD92Gm/page/gIfSB" frameborder="0" style="border:0" allowfullscreen></iframe>

#### Remove Vertical Scrollbar Instructions:

https://www.sitepoint.com/community/t/removing-vertical-scrollbar-in-iframe/22495

#### Read More: 

https://support.google.com/datastudio/answer/7450249?hl=en
[How to export one chart at a time from google sheets (provides html)](https://support.google.com/docs/answer/1047436?co=GENIE.Platform%3DDesktop&hl=en)

Something you probably wont need, but good to have
[direct access to google studio page - its what is being embeded](https://datastudio.google.com/u/0/reporting/16J9XI19pQejSDNFvjl_V3ZezJ502rM_a/page/e1JSB)

Link to spreadsheet that feeds the website dashboard: https://docs.google.com/spreadsheets/d/1sIhdPzSpMNn7ZwGftiCbgMRtF-84ziJgmr8EjsC_yK8/edit#gid=1185333001

**Comment by ashlingam** [comment]
1. Progress - Initial dashboard created with pages for Website Performance and Brigade Analysis. Remaining survey data needs to be integrated.
2. Blocks - None
3. Availability - Through 6/3, then exit project.
4. ETA - 6/3

**Comment by jbubar** [comment]
Did not make any progress. Had a busy week. I am available for a few hours Thurs and over the weekend. I can get this done by our next meeting on Sunday

**Comment by efrenmarin45** [comment]
**Progress:** I was able to implement the web embedding to a new dashboard page. Still need to do a mobile version but should be done before the end of the week 7/26/20. 
**Blocks:** No
**Availability:** All week
**ETA:** Friday-Saturday

**Comment by efrenmarin45** [comment]
**Progress:** Web and mobile views have been implemented and are working as intended in reference to the Figma files.
**Blocks:** No
**Availability:** All week
**ETA:** I am done, just need someone to review my PR

**Comment by alexandrastubbs** [comment]
@efrenmarin45 can you share screenshots of the above by pasting them into this issue?

**Comment by efrenmarin45** [comment]
![webView](https://user-images.githubusercontent.com/51544521/88485843-140c0a00-cf2e-11ea-9acf-e21b29464a9e.gif)

**Comment by efrenmarin45** [comment]
![mobileView](https://user-images.githubusercontent.com/51544521/88485884-7533dd80-cf2e-11ea-83e2-9dc62cad5119.gif)

**Comment by alexandrastubbs** [comment]
Looks great!!

**Comment by Samhitha444** [comment]
- [ ] All the links in this issue will need to be checked to see if we have access
- https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=811%3A1003
  - [ ] Have access, its located in ____
  - [x] public
- [Removing vertical scrollbar in iframe](https://www.sitepoint.com/community/t/removing-vertical-scrollbar-in-iframe/22495)
  - [ ] Have access, its located in ____
  - [x] public
- [Save or publish your chart](https://support.google.com/datastudio/answer/7450249?hl=en)
  - [ ] Have access, its located in ____
  - [x] public
- https://support.google.com/docs/answer/1047436?co=GENIE.Platform%3DDesktop&hl=en
  - [ ] Have access, its located in ____
  - [x] public
- [Hack for LA | Organizational Dashboard - Desktop](https://datastudio.google.com/u/0/reporting/16J9XI19pQejSDNFvjl_V3ZezJ502rM_a/page/e1JSB)
  - [ ] Have access, its located in ____
  - [x] public
- https://docs.google.com/spreadsheets/d/1sIhdPzSpMNn7ZwGftiCbgMRtF-84ziJgmr8EjsC_yK8/edit#gid=1185333001
  - [x] Have access, its located in ALL Hack for LA projects > hackforla.org website > surveys > data workbook
  - [x] public 
 - [Copy of Survey Data Workbook](https://docs.google.com/spreadsheets/d/1Rgx9E73JZjUMo3VdsMwHZzBwVUtcUwEqvKdb7Kja2Yk/edit?gid=1185333001#gid=1185333001)
  - [ ] Have access, its located in ____
  - [x] public
