### ISSUE TITLE
remove mention of CfA from Civic Tech Index project page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5426]
### Overview
We need to remove mention of CfA from the list of partners on the Civic Tech Index project page.  

### Action Items
- [x] In your local IDE, navigate to `_projects/civic-tech-index.md`
- [x] Remove the line:
 ```
partner: Code for America, Yale OpenLab and many more.
```
- [x] Using Docker, confirm that the "Partner" list has been removed from the Civic Tech Index Project page, and the rest of the page is unchanged.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-index.md
2. Civic Tech Index Project Webpage: https://www.hackforla.org/projects/civic-tech-index

**Comment by kabszac** [comment]
Availability : available 
ETA: 1 hour
