### ISSUE TITLE
Remove mention of CfA from Events page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5427]
### Overview
We need to remove mention of CfA from the Events page

### Action Items
- [x] In your local IDE, navigate to `_includes\events-page\header-container-content.html`
- [x] replace
```
  <h2 class="header-desc">
       Hack for LA is the Los Angeles brigade of
       <a href="http://brigade.codeforamerica.org/" target="_blank">Code for America</a>,
       a network of civic-minded technologists who contribute their skills
       toward using the web as a platform for local government and community
       service.
  </h2>
```
with
```
  <h2 class="header-desc">
      Hack for LA was incubated in the Code for America Brigade Network and continues the valuable work under Civic Tech Structure, 
      Inc. a network of civic-minded technologists who contribute their skills toward using the web as a platform for local government 
      and community service.”
 </h2>
```
- [x] Using Docker, confirm that the changes are reflected on the Events webpage, and the surrounding elements are unchanged.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/header-container-content.html
2.  Events webpage(s): https://www.hackforla.org/events

**Comment by imsoumya18** [comment]
@roslynwythe Can you please assign me the task? I want to contribute to this

**Comment by imsoumya18** [comment]
@roslynwythe I have created a PR #5445

**Comment by liamtirney** [comment]
Availability: Mon 9/18 and Tues 9/19
ETA: Tues 9/19
