### ISSUE TITLE
Remove mention of CfA from the Civic Tech Infrastructure program area description

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5428]
### Overview
We need to remove mention of CfA from the Civic Tech Infrastructure program area description.

### Action Items
- [x] In your local IDE, navigate to `_data/internal/program-areas/civic-tech-infrastructure-card.yml`
- [x] Replace:
```
description: >
  Hack for LA is creating replicable blueprints for processes and practices to be 
  shared across Code for America brigades and support other similar organizations 
  around the world.
``` 
with:
```
description: >
  Hack for LA is creating replicable blueprints for processes and practices to be shared with other similar organizations around the world
```
- [x] Using Docker, confirm that on the Program Areas webpage, the description under "Civic Tech Infrastructure" has been updated, but other elements are unchanged.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_data/internal/program-areas/civic-tech-infrastructure-card.yml
2. Program Areas webpage: https://www.hackforla.org/program-areas

**Comment by antho-zng** [comment]
Availability: M–F 9–6pm ET
ETA: 9/3 EOD

**Comment by roslynwythe** [comment]
@lateral-neck-stretch This issue was not approved nor prioritized and has no milestone, therefore it is not ready to be assigned.

**Comment by robertnjenga** [comment]
Availability: 9a-12p PT
 ETA: Today: 19 September
