### ISSUE TITLE
Remove mention of CfA from the Join Us page - donation gif text

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5447]
### Overview
We need to remove mention of CfA from the Join Us page

### Action Items
- [x] In your local IDE, navigate to '_includes/donation/donate-gif-text.html'
- [x] Replace 
```
 <p>Hack for LA takes donations through Code for America.</p>  
    <ol>
      <li>
        Please follow this link to the Code for America
        <a href="https://www.codeforamerica.org/donate" target="_blank" rel="noopener noreferrer">donation form.</a>
      </li>
      <li>
        To make a donation please select <strong>Hack for LA</strong> under the brigades
        listed.
      </li>
    </ol>            
  </div>
  <img class="donation-gif" src="/assets/images/about/hfla-donate.gif" alt="">
  <p class="donation-footer" id='donation-footer'>*100% of donated proceeds go directly to Hack for LA when option is selected.</p>
``` 
with
```
 <p>Hack for LA takes donations through Civic Tech Structure.</p>  
    <ol>
      <li>
        Please follow this link to the Civic Tech Structure Stripe
        <a href="https://donate.stripe.com/bIY9Cpcg8dihfIc5kl" target="_blank" rel="noopener noreferrer">donation form.</a>
      </li>
    </ol>            
  </div>
  <img class="donation-gif" src="/assets/images/about/hfla-donate.gif" alt="">
  <p class="donation-footer" id='donation-footer'>*100% of donated proceeds are tax deductible.</p>
```
- [x] Replace the graphic of the donation form:
```
 <img class="donation-gif" src="/assets/images/about/hfla-donate.gif" alt="">
```
with a graphic of the new donor form found below in Resources.  
- [x] Add a drop shadow to the new donor form graphic
- [x] Make the donor form graphic clickable, linking to:
```
<a href="https://donate.stripe.com/bIY9Cpcg8dihfIc5kl" target="_blank" rel="noopener noreferrer">
```

- [x] Using Docker, confirm that the change has been made on the Join us page, and the rest of the page is unchanged.  

### Resources/Instructions
<details><summary>donor form graphic</summary>

<img src="https://github.com/hackforla/website/assets/37763229/bd4c5383-6e50-4c58-bc04-1144c29d01bb" width=200px>
</details> 

1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/donation/donate-gif-text.html
2. Join Us webpage: https://www.hackforla.org/join

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I updated the text a bit.  Turns out we don't have DonorBox yet.  We can use this though 
https://donate.stripe.com/bIY9Cpcg8dihfIc5kl

where we make an image of what it looks like on mobile and add a drop shadow around it.  And make it clickable, incase they do think they are donating there.
<details><summary>Mobile image of donor page</summary>

<img src="https://github.com/hackforla/website/assets/37763229/bd4c5383-6e50-4c58-bc04-1144c29d01bb" width=200px>
</details>

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe please go ahead and re-write the issue to make the image change.  I added the link into the text already.

**Comment by YolandaHaynes** [comment]
Availability: Mon (6-8pm pst), Wed (6-8pm), Thur (5-8pm pst). Sat (5pm-10pm), 
ETA: 10/02
