### ISSUE TITLE
Change to donation gif header on Join Us page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5448]
### Overview
We need to change the header text on the Join Us page donation gif

### Action Items
- [x] In your local IDE, navigate to `_includes/join-donate-card.html`
- [x] Replace
```
    <h3 class="title6 page-card--large-icon-header-secondary">Make a donation to Hack for LA</h3>
```
with 
```
<h3 class="title6 page-card--large-icon-header-secondary">Make a donation</h3>
```
- [x] Using Docker, confirm that the change has been made on the Join us page, and the rest of the page is unchanged.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_includes/join-donate-card.html
2. Join Us webpage: https://www.hackforla.org/join

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty Not sure if you wanted this change but you seemed to mention a change to the header text in  https://docs.google.com/document/d/1fgNAtd_l0NPRGLbAR4sWIyWi2fP-PYCg5OqLxnXmpZE/edit

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I do want the change.

**Comment by nirbhaykr87** [comment]
please assign this task to me.

**Comment by KamakshiOjha** [comment]
Hey, can you please assign me this issue.

**Comment by efranzener** [comment]
Availability for this week: Wed-Friday 7pm-9pm PST
My estimated ETA for completing this issue: Wed September 20 by 9pm PST
