### ISSUE TITLE
Javascript error on CivicTechIndex page

### ISSUE THREAD

**Issue by cnk** [hackforla/website#547]
### Overview
When you go to https://www.hackforla.org/projects/civic-tech-index you see an error in the JavaScript console. 

`Uncaught Type Error: Cannot read property 'split' of undefined  at civic-tech-index:807`

### Detail about problem
The "Uncaught TypeError"  is happening because there is a line in the list of contributors that is NOT a GitHub user object. Instead it is the string  "Cannot read property 'forEach' of undefined". That is getting inserted because https://api.github.com/repos/civictechindex/database/contributors does not return any data. 

### Action Items 
We need to update the data retrieval script to deal with projects that do not yet have contributions.

### Resources
There are two errors on the page.  Ignore the one that says "A cookie associated...", because it happens on all project pages.

**Comment by ExperimentsInHonesty** [comment]
If by contributions you mean PRs, and you are referring to the following repository: https://github.com/civictechindex/website it does have contributions.  If you are talking about something else, please elaborate

**Comment by cnk** [comment]
No I am referring to this empty repository: https://github.com/civictechindex/database

It has no contributors so https://api.github.com/repos/civictechindex/database/contributors does not return any data and that is causing an error message to be included in the GitHub data we use in the HackForLA website
