### ISSUE TITLE
replace mention of "good second issue" in prework issue template - dev

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5476]
### Overview
We need to replace mention of "good second issue" in the developer's prework issue template

### Action Items
- [x] In your IDE open `.github/ISSUE_TEMPLATE/pre-work-template--dev.md`
 - [x] Replace
```
- Good first issue (one per person)
- Good second issue (one per person)
```
with
```
- Good first issue (two per person)
```
- [ ] Refer to these [instructions](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) for testing and preparing the Pull Request. 

### Resources/Instructions
- This issue is part of #4432

**Comment by YolandaHaynes** [comment]
Availability: Th 5-9
ETA: EOD 9/14
