### ISSUE TITLE
replace mention of "good second issue" in prework issue template - design

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5477]
### Overview
We need to replace mention of "good second issue" in the designer's prework issue template

### Action Items
- [x] In your IDE open `.github/ISSUE_TEMPLATE/pre-work-template---design.md`
 - [x] Replace
```
- Good first issue (one per person)
- Good second issue (one per person)
```
with
```
- Good first issue (two per person)
```
- [ ] Refer to these [instructions](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) for testing and preparing the Pull Request. 
 
### Resources/Instructions
- This issue is part of #4432

**Comment by allison-truhlar** [comment]
Availability: M-F, 10-12pm ET
ETA: Monday 9/18 EOD
