### ISSUE TITLE
Add new variable github-handle for member Niven Prasad in 100-automations.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5504]
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/100-automations.md` in the IDE
- [x] Replace:
```
- name: Niven Prasad
```
with
```
- name: Niven Prasad
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.  

### Merge Team
- [x] Release the dependency of this issue in #5441 
- [ ] After the last dependency has been released, close #5441

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md
Webpage: https://www.hackforla.org/projects/100-automations
- This issue is part of #5441

**Comment by roslynwythe** [comment]
@Justin-Arakaki Please note the second Action Item has been modified (by removing the hypen before `github-handle`) and a new Action Item has been added.  I apologize for the error in the original issue.

**Comment by kwangric** [comment]
Hi @Justin-Arakaki! If you are still working on this issue, please provide an update with the template above. If you can no longer complete the issue, or if we don't hear from you by 10/23/23, you will be un-assigned from the issue. Thanks!

**Comment by jlevot** [comment]
i. Availability: 01/10/24
ii. ETA: 01/10/24
