### ISSUE TITLE
Add new variable github-handle for member Camila Arias in 100-automations.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5505]
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/100-automations.md` in the IDE
- [x] Replace:
```
- name: Camila Arias
```
with
```
- name: Camila Arias
  github-handle: 
```
- [x] Do not use a tab to indent "github-handle". YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.  

### Merge Team
- [ ] Release the dependency of this issue in #5441 
- [ ] After the last dependency has been released, close #5441

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md
Webpage: https://www.hackforla.org/projects/100-automations
- This issue is part of #5441

**Comment by KyleA99** [comment]
Availability for this week: Available to address any comments from reviewers.
   My estimated ETA for completing this issue:  Issue completed, pending review.

**Comment by KyleA99** [comment]
How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?

5-7 hours roughly

**Comment by roslynwythe** [comment]
@KyleA99 Please note the second Action Item has been modified (by removing the hypen before `github-handle`) and a new Action Item has been added.  I apologize for the error in the original issue.
