### ISSUE TITLE
Add new variable github-handle for member Olivia Chiong in 100-automations.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5506]
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/100-automations.md` in your IDE.  
- [x] Replace:
```
- name: Olivia Chiong
```
with
```
- name: Olivia Chiong
  github-handle: 
```
- [x] Do not use a tab to indent "github-handle". YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.  

### Merge Team
- [ ] Release the dependency of this issue in #5441 
- [ ] After the last dependency has been released, close #5441

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md
Webpage: https://www.hackforla.org/projects/100-automations
- This issue is part of #5441

**Comment by crystallyyy** [comment]
Availability for this week: It's Thursday so I have about 3 hours available this week and next week I'll have 10 hours available.
My estimated ETA for completing this issue: I should be done in less than a week, so by 9/28.

**Comment by roslynwythe** [comment]
@crystallyyy Please note that this issue has been edited.  The second Action Item has been modified (by removing the hypen before `github-handle`) and a new Action Item has been added to warn against the use of a Tab character.  Thank you.
