### ISSUE TITLE
Add new variable github-handle for member Muhi-Dean Othman in 100-automations.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5507]
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/100-automations.md` in the IDE
- [x] Replace:
```
- name: Muhi-Dean Othman
```
with
```
- name: Muhi-Dean Othman
  github-handle: 
```
- [x] Do not use a tab to indent "github-handle". YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.  

### Merge Team
- [ ] Release the dependency of this issue in #5441 
- [ ] After the last dependency has been released, close #5441

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md
Webpage: https://www.hackforla.org/projects/100-automations
- This issue is part of #5441

**Comment by abhayguptas** [comment]
Hey @roslynwythe, Hope you are doing well. My self Abhay, I'm ready to solve this asap. I am ready to push changes and open PR. Please assign it to me.
Thanks !

**Comment by ExperimentsInHonesty** [comment]
@professorabhay.  Thanks for your interest.

### Prerequisite for working on this issue
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

**Comment by sornekian** [comment]
Availability: Weeknights 7-11pm
ETA: 12/26/23 8pm

**Comment by ExperimentsInHonesty** [comment]
@samuelusc I am moving this issue to the in progress column, since you are working on it. On future issues please move the issue after you self assign.

**Comment by samuelusc** [comment]
@roslynwythe Thank you. I will do that next time.

**Comment by samuelusc** [comment]
i. Availability: I am going to work with it during the week. 
ii. ETA: Expect that it can be done by next Thursday or Sunday.

**Comment by samuelusc** [comment]
1. Progress: has created pull request and waitting for PR review.
2. Blockers: Waitting for PR review
3. Availability: 20 hours
4. ETA: After the pr review
