### ISSUE TITLE
Add new variable github-handle for member Audrey Kim in 100-automations.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5508]
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/100-automations.md` in the IDE
- [ ] Replace:
```
- name: Audrey Kim
```
with
```
- name: Audrey Kim
  github-handle: 
```
- [ ] Do not use a tab to indent "github-handle". YAML doesn't allow tabs; it requires spaces.
- [ ] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.  

### Merge Team
- [ ] Release the dependency of this issue in #5441 
- [ ] After the last dependency has been released, close #5441

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md
Webpage: https://www.hackforla.org/projects/100-automations
- This issue is part of #5441

**Comment by abhayguptas** [comment]
Hey @roslynwythe, Hope you are doing well. My self Abhay, I'm ready to solve this asap. I am ready to push changes and open PR. Please assign it to me.
Thanks !

**Comment by TusharP05** [comment]
Can you please assign this issue to me?

**Comment by tonyvang** [comment]
**Availability for this week**: I'll be available this evening 2023-09-22, tomorrow morning 2023-09-23, and I'll be checking Slack periodically.
**My estimated ETA for completing this issue**: I hope to have completed this issue by end-of-day Sunday.

**How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?**

~9 hours, including attending onboarding meeting, website dev, office hrs, & full team meetings, reading wiki & setting up DE.

**Comment by tonyvang** [comment]
Replacing
```
- name: Audrey Kim
```

with
```
- name: Audrey Kim
- github-handle:
```

Results in separation of Kim's block into two, one with the name, the other with the image and a blank "Name" field (see FIG 1).

Removing the dash from github-handle and matching its indentation to other nested info in Kim's block results in a visibly unchanged page from live site at time of this message (see FIG 2).

```
  - name: Audrey Kim
    github-handle: 
```

Will review & pull request tomorrow.

<details>
<summary> FIG 0 - local, pre-work this issue </summary>

![Screenshot (2)](https://github.com/hackforla/website/assets/67331818/73cb4942-1c29-47ce-a313-604400d801dd)
</details>

<details>
<summary> FIG 1 </summary>

![Screenshot (12)](https://github.com/hackforla/website/assets/67331818/56cb17ce-49fb-4450-9a09-d4241b713701)
</details>

<details>
<summary> FIG 2 </summary>

![Screenshot (13)](https://github.com/hackforla/website/assets/67331818/c4cad0b8-b1f1-47f9-a94a-fe6706e6ca33)
</details>

**Comment by TusharP05** [comment]
I have already pulled a request and the changes are not making visible changes in my local machine. The code is working as it should be.

**Comment by tonyvang** [comment]
Hi TusharP05, sorry for the confusion. I wasn't reviewing your pull request, I just completed onboarding last week and started working on this issue as part of my pre-work developer checklist, because I saw it was still in the prioritized backlog and no one had self-assigned per [the contributing guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md). My comment was just documenting my own work. I don't mean to step on any toes if you meant to claim this issue; if we're duplicating work then worst comes to worst we both have pull requests.

**Comment by TusharP05** [comment]
Yeah I have already made the necessary changes!

**Comment by roslynwythe** [comment]
@tonyvang you are 100% correct in your analysis and I apologize for the error.  I have updated the issue accordingly.  Thank you!

**Comment by TusharP05** [comment]
But the code is not making any changes in my local machine when I am
running it-

[image: image.png]

[image: image.png]

TUSHAR PARAKH
