### ISSUE TITLE
Add new variable github-handle for member Jason Brown in 100-automations.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5509]
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/100-automations.md` in the IDE
- [x] Replace:
```
- name: Jason Brown
```
with
```
- name: Jason Brown
  github-handle: 
```
- [ ] Do not use a tab to indent "github-handle". YAML doesn't allow tabs; it requires spaces.
- [ ] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.  

### Merge Team
- [ ] Release the dependency of this issue in #5441 
- [ ] After the last dependency has been released, close #5441

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md
Webpage: https://www.hackforla.org/projects/100-automations
- This issue is part of #5441

**Comment by abhayguptas** [comment]
Hey @roslynwythe, Hope you are doing well. My self Abhay, I'm ready to solve this asap. I am ready to push changes and open PR. Please assign it to me.
Thanks !

**Comment by aramattamara** [comment]
Availability for this week: 09/20
My estimated ETA for completing this issue: 9/20 around 4PM

**Comment by roslynwythe** [comment]
@aramattamara Please note the second Action Item has been modified (by removing the hypen before `github-handle`) and a new Action Item has been added.  I apologize for the error in the orginal issue.
