### ISSUE TITLE
Revise Donate button page redirect

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#551]
### Overview
Look at Donate button page redirect. Currently, clicking the Donate button flashes a "This page is redirecting..." before landing on the Code for America donate page. We would like to mask this transition by setting the display time to 0 sec.

### Dependency
#553 

### Action Items
- [x] Change wording in this file: gh-pages/_layouts/redirect.html to 
   - [x] from: "This page has moved to"
   - [x] to: "We are connecting you to an outside resource"

### HOLD till dependency is released.
- [ ] Look at Donate button page direct coding and set transition time to 0 seconds if possible

**Comment by ExperimentsInHonesty** [comment]
do not need to do the work on hold because it turns out it was already set to zero.
