### ISSUE TITLE
remove mention of CfA - sponsors on about us

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5511]
### Overview
We need to remove mention of Code for America from the list of sponsors, which appears on the "About Us" page  

### Action Items
- [x] In your local IDE, navigate to `_includes/about-page/about-card-sponsors.html`
- [x] remove these lines:
```
            <a href="https://www.codeforamerica.org" target="_blank" alt="Code for America">
                <img src="/assets/images/sponsors/code-for-america.svg" title="Code for America">
            </a>
```
- [x] Using Docker, view the webpages and confirm that "Code for America" has been removed from sponsors, and the rest of the page is unchanged.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_data/internal/sponsors.yml
2. Webpage(s): https://www.hackforla.org/, https://www.hackforla.org/about/#sponsors

**Comment by akhilender-bongirwar** [comment]
Hey @roslynwythe , I would like to work on this issue. Can you please assign me.

**Comment by abhayguptas** [comment]
Hey @roslynwythe, Hope you are doing well. My self Abhay, I'm ready to solve this asap. I am ready to push changes and open PR. Please assign it to me. 
Thanks !

**Comment by roslynwythe** [comment]
> Hey @roslynwythe, Hope you are doing well. My self Abhay, I'm ready to solve this asap. I am ready to push changes and open PR. Please assign it to me. Thanks !

Hi @professorabhay our issues are only open to members of Hack for LA, but you don't have to live in L.A to join.  Please see https://www.hackforla.org/join

**Comment by djbradleyii** [comment]
Availability: M-F 11am - 5pm PST
ETA: EOD Tomorrow 11/28/23

**Comment by djbradleyii** [comment]
Adding this to get used to the process.

Update (Standup)
1. Progress - Task completed
2. Blockers - None
3. Availability - M-F 11am - 5pm PST
4. ETA - EOD 11/28
