### ISSUE TITLE
Update Project Team Meetings page

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#552]
### Overview
Update Project Team Meetings page. Incorporate styling elements from Hack Nights Page-Online team meetings section, including vector graphic. Reference style elements from other pages as appropriate.

### Action Items
- [ ] UI/UX
   - [ ] Update Project Team Meetings page to current style guidelines
- [ ] Development
   - [ ] revise the current page 

### Resources/Instructions
https://www.hackforla.org/project-meetings

**Comment by yuikomajima** [comment]
Here's 2 options for this page. I played around with the hero as we spoke about left aligning the body.

figma file: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=925%3A1

**Comment by ExperimentsInHonesty** [comment]
Team decided on left image  (center align) because right image (left align requires a redesign of other pages.  Left aligned is probably preferable in the future but we will address when we have sass components setup.

**Comment by ghost** [comment]
Is there a style guide for the website where I'd be able to find the specific icon or image used within the banner in the design? I've looked through the images in the assets section and wasn't able to find that particular image.

**Comment by ExperimentsInHonesty** [comment]
@hannahlivnat which image specifically are you looking for?

**Comment by ye-susan** [comment]
@hannahlivnat are you talking about this one?
![image](https://user-images.githubusercontent.com/49918375/84743746-3a21b000-af67-11ea-91bd-a4ccdb5582ef.png)

If you highlight the entire image in Figma, and have the right-side bar opened, there's an option to export the image, You can then save it to the assets folder

**Comment by ghost** [comment]
Yes, that's exactly what I was looking for! I see what the issue was with Figma, I hadn't logged in so it wasn't displaying the right-bar. Thank you for letting me know about that feature!

**Comment by ghost** [comment]
I have the SCSS complete for the project-meetings page. As screen-size gets larger (~ 1400px and above), I wasn't sure whether the image and text seemed a bit too spaced out. 

I've included a screenshot of the banner at 900px and the banner at 1400px. Let me know what you think. 

<img width="942" alt="Screen Shot 2020-06-17 at 6 46 14 PM" src="https://user-images.githubusercontent.com/54752231/84968726-09a75680-b0cc-11ea-8863-39967a9c8fa2.png">

<img width="1593" alt="Screen Shot 2020-06-17 at 6 50 16 PM" src="https://user-images.githubusercontent.com/54752231/84968747-13c95500-b0cc-11ea-9f46-419fe03a7190.png">

**Comment by ghost** [comment]
Unless changes need to be made to the >1400px screen size, I just need to add an href to the onboarding link and I'll be ready to make a pull request.

**Comment by ghost** [comment]
From decision in Sunday meeting on responsive sizing of project-meetings banner and text, I've attached screenshots of the updated mobile and larger desktop view. Link to getting-started page is also added. Let me know if you'd like me to make any other changes to the responsive views! @alexandrastubbs @ye-susan @yuikomajima 

![Screen Shot 2020-06-21 at 11 34 23 AM](https://user-images.githubusercontent.com/54752231/85232457-cdb60f00-b3b3-11ea-8903-9ee525432f41.png)
![Screen Shot 2020-06-21 at 11 37 01 AM](https://user-images.githubusercontent.com/54752231/85232460-cf7fd280-b3b3-11ea-903d-f2b83b45a161.png)

**Comment by ExperimentsInHonesty** [comment]
@hannahlivnat looks good to me.

**Comment by ghost** [comment]
Great, pull request has been put in and Ruben is reviewing

**Comment by ghost** [comment]
Hey @ExperimentsInHonesty, Ruben merged the pull request! Should I close this issue or leave it to you or @alexandrastubbs to close?
