### ISSUE TITLE
Run VSCode Code Spell Checker on _includes/about-page/about-card-metrics.html

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5520]
### Overview
We need to audit HfLA codebase files for spelling errors using the VSCode Code Spell Checker extension in order to ensure site quality.  Results will be categorized as misspellings, false positives in the HfLA spelling audit spreadsheet[^1] and will be resolved in later issues.  

### Action Items
- [x] You must use VS Code as your local text editor and install the `Code Spell Checker` VS Code extension[^2]  
- [x] Do not change any configuration settings or make any spell corrections
- [x] Open the file '_includes/about-page/about-card-metrics.html' and note any Code Spell Checker errors
- [x] Locate the file in column A ("File") of the "Page Audit" sheet.  In the column labelled "Result Summary", select the appropriate option:  `No errors` or `At least one error`.  
- [x] If at least one error was reported, copy/paste each cSpell message into a separate row in the `Results` sheet
- [x] In each new row, select the appropriate value: `misspelling` or `false positive` from the "Result type" column.  A false positive is a term that is not a misspelling, but it is not recognized by the spell checker because it is a technical term, abbreviation, acronym, URL or proper noun (name of a person, place or organization).  
- [x] Move this issue to the Questions/In Review column and apply the label 'ready for dev lead`

### Merge Team
- [x] After this issue is closed, release the dependency on this issue in #5248
- [ ] After the last dependency has been released, close that issue. 

### Resources/Instructions
- This issue is part of #5248
[^1]: [HfLA spelling audit spreadsheet - Results](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=69989048)
[^2]:The recommended installation method is to install Code Spell Checker directly from the VS Code text editor, and those instructions can be found [here](https://code.visualstudio.com/learn/get-started/extensions). The extension can also be installed via the VS Code Marketplace website [here](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

**Comment by raviteja4117** [comment]
Availability for Next Week: Tuesday, Thursday
My estimated ETA for completing this issue: Hopefully by Friday 22nd September

**Comment by LRenDO** [comment]
Hi @raviteja4117! Great job with this issue! It looks like there are errors on my end too! You also did a great job with moving the issue to the right column and adding the correct label. 

I do have one request. 
- [x] On the `Results` sheet of the spreadsheet please add all three instances (even though they are the same word) of the error message found in the `Problems` list in VS Code. 

Once it's completed, you can ping me here in a comment to let me know and add the `ready for dev lead` tag back to the issue. Thanks for working on this issue!

**Comment by raviteja4117** [comment]
Hi @LRenDO  Thank you for your response, I have completed the tasks and added them to the sheet. Thank you

**Comment by LRenDO** [comment]
Hi @raviteja4117! Looks good! Thanks for making the updates!

**Comment by LRenDO** [comment]
Hi @raviteja4117! Looks good! Thanks for making the updates!
