### ISSUE TITLE
Bug fix?  css file discrepancy discovered during redirect research

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#553]
### Overview
Figure out discrepancy between main.css and main.scss. It looks like the file being referred to in redirect.html is main.css, but there is no main.css file anymore, there is only main.scss located /assets/css/main.scss

### Action Items
Discussion of team
- [ ] how are any of our redirects still working
- [ ] what breaks if we change the reference in redirect.html

### Resources/Instructions
Image of redirect.html
![Screen Shot 2020-05-31 at 1 40 16 PM](https://user-images.githubusercontent.com/37763229/83362225-67a21300-a344-11ea-8522-5288b1f9ef82.png)

**Comment by cnk** [comment]
The file /assets/css/main.css is created from /assets/css/main.scss when GH pages does it's build step. If you look at any file on the live site it loads main.css.

**Comment by ExperimentsInHonesty** [comment]
Thanks for the explainer.  So no bug after all.  @ye-susan is this explained in the wiki?

**Comment by ye-susan** [comment]
@ExperimentsInHonesty Yes, explanation on how the primary main.scss is used to generate the site in the _site folder and how it differs from main.scss in the layouts folder is located in the [Styling section](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture#styling-files) of the wiki

**Comment by ExperimentsInHonesty** [comment]
@ye-susan thanks
