### ISSUE TITLE
Run VSCode Spell Checker on _includes/donate-card.html

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5531]
### Overview
We need to audit HfLA codebase files for spelling errors using the VSCode Code Spell Checker extension in order to ensure site quality.  Results will be categorized as misspellings, false positives in the HfLA spelling audit spreadsheet[^1] and will be resolved in later issues.  

### Action Items
- [x] You must use VS Code as your local text editor and install the `Code Spell Checker` VS Code extension[^2]  
- [x] Do not change any configuration settings or make any spell corrections
- [x] Open the file '_includes/donate-card.html'and note any Code Spell Checker errors
- [x] Locate the file in column A ("File") of the "Page Audit" sheet.  In the column labelled "Result Summary", select the appropriate option:  `No errors` or `At least one error`.  
- [ ] If at least one error was reported, copy/paste each cSpell message into a separate row in the `Results` sheet
- [ ] In each new row, select the appropriate value: `misspelling` or `false positive` from the "Result type" column.  A false positive is a term that is not a misspelling, but it is not recognized by the spell checker because it is a technical term, abbreviation, acronym, URL or proper noun (name of a person, place or organization).  
- [x] Move this issue to the Questions/In Review column and apply the label 'ready for dev lead`

### Merge Team
- [x] After this issue is closed, release the dependency on this issue in #5248
- [ ] After the last dependency has been released, close that issue. 

### Resources/Instructions
- This issue is part of #5248
[^1]: [HfLA spelling audit spreadsheet - Results](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=69989048)
[^2]:The recommended installation method is to install Code Spell Checker directly from the VS Code text editor, and those instructions can be found [here](https://code.visualstudio.com/learn/get-started/extensions). The extension can also be installed via the VS Code Marketplace website [here](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

**Comment by kezzaam** [comment]
Availability: Sunday-Thursday around an hour each day - I have flexible working hours.
ETA: Wednesday 20th September - 11pm PST

**Comment by kezzaam** [comment]
I ran the spell checker on _includes/donate-card.html and there were no errors found. 
I have updated the spreadsheet to reflect this.

**Comment by kezzaam** [comment]
Status: waiting on dev lead to check this issue

**Comment by LRenDO** [comment]
Hi @kezzaam! Great job with this issue! It looks like there are no errors on this page on my end too!  You also did a great job with moving the issue to the right column and adding the correct label. Thanks for contributing to this epic!
