### ISSUE TITLE
Create Issue Template for VSCode Spell Check Audit Issues

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5540]
### Overview
We need to create a GitHub issue template for VSCode Spell Check Audit Issues so that issues can be created efficiently.  

### Action Items
- [x] Create a new file `.github/ISSUE_TEMPLATE/spell-check-audit.md` with YAML frontmatter:
```
---
name: spell check audit web page
about: 'For checking spelling on a code file that contains text displayed on the website'
title: 'Run VSCode Spell Checker on [INSERT FILE HERE]'
labels: 'Feature: Administrative, Complexity: Small, ready for dev lead, role: back
  end/devOps, role: front end, size: 0.5pt'
assignees: ''

---
```
- [x] The body of the issues should come from this [template](https://github.com/hackforla/website/issues/5248#issuecomment-1685247438)
- [x] Refer to these [instructions](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) for testing and preparing the Pull Request. 

### Resources/Instructions
[Manually creating a single issue template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)
- This issue is part of #5248

**Comment by tesiahwang** [comment]
Availability: flexible
ETA: 9/16/2023
