### ISSUE TITLE
Create Issue Template for adding github-handle to leadership member data in project file

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5541]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create an issue template for creating an issue that adds the variable `github-handle` for a member of the leadership team in a project file. 

### Action Items
- [x] Create a new file `.github/ISSUE_TEMPLATE/add-github-handle.md` with YAML frontmatter:
```
---
name: github-handle in project file
about: 'For adding github-handle to member data in a project file'
title: 'Add github-handle for [INSERT NAME] in [INSERT PROJECT FILE]'
labels: 'P-Feature: Project Info and Page, good first issue, ready for dev lead, role: back
  end/devOps, role: front end, size: 0.25pt'
assignees: ''

---
```
- [x] The body of the issues should come from this [template](https://github.com/hackforla/website/issues/5441#issuecomment-1716198393)
- [x] Refer to these [instructions](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) for testing and preparing the Pull Request. 

### Resources/Instructions
[Manually creating a single issue template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)
- This issue is part of #5441

**Comment by JanineSooThow** [comment]
Availability: Tuesdays, Thursday Afternoon and Friday morning 
ETA: Friday 13th October 2023

**Comment by JanineSooThow** [comment]
Hi all, I am really confused if I am following this correctly? I created the issue template by following these instructions that were given https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository 

After creating the issue template, I have made a branch for it https://github.com/JanineSooThow/website/blob/5541-create-issue-template-for-adding-github-handle-to-leadership-member-data-in-project-file/.github/ISSUE_TEMPLATE/add-github-handle.md Can someone please verify I am doing the right thing before I test and prepare the PR? Thank you

**Comment by roslynwythe** [comment]
Hi @JanineSooThow I think you are definitely on the right track.  I cannot tell how many steps you completed in the [instructions](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) that were provided in the last Action Item, but the intention is to demonstrate the new issue template by actually creating a new issue in your repository, and that requires that you make the issue branch the default branch on your fork, and that you enable issue creation in your repository settings.   Please let me know if a specific step in the instructions is causing a problem.  Thank you!

**Comment by roslynwythe** [comment]
@JanineSooThow I apologize but I need to make a change to the template.  I have updated the issue with a "Prerequisite" section, so you will have to make that addition.  Thank you 

Also Janine if you need assistance, please put the `ready for dev lead` label on the issue; that makes it easier for me to find.  Thanks

**Comment by JanineSooThow** [comment]
ETA: Wednesday 25th October 2023
Available: Mondays

**Comment by JanineSooThow** [comment]
@roslynwythe Hello Roslyn, apologies for late reply! I have updated the template with the "Prerequisite" section, however I am stuck on this part in the instructions  (this is where I am up to on the Action item "From the Issues page, click "New Issue" then locate the template updated by your issue, and click "Get Started" to open the issue template."). 

I have made my issue branch the default branch as per the instructions.

I have created the labels but I am unable to locate the template updated by my issue as per the instructions. Should I just go to "open a blank issue?" and then copy and paste everything from my URL below into this and then add the labels? 

 This is my URL https://github.com/JanineSooThow/website/blob/5541-create-issue-template-for-adding-github-handle-to-leadership-member-data-in-project-file/.github/ISSUE_TEMPLATE/add-github-handle.md

Apologies for the confusion. Thank you so much!

**Comment by roslynwythe** [comment]
Hi @JanineSooThow  In order to be recognized as an issue template, the markdown file that you create must start with the front matter section as provided in the first Action Item.  Front matter is a snippet of [YAML](http://yaml.org/) placed between two triple-dashed lines at the start of a file.  I don't see that front matter section in your file.  Perhaps it was deleted when the Prerequisite section was added.  I apologize if my instructions were unclear.  

The goal is that in your repo, you will be able to click "New Issue" and see the new "GitHub handle in project file" issue template.  But that will require that you make the issue branch the default branch in your repo,   So follow the instructions that are linked in the last Action Item:  [instructions](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024)

**Comment by roslynwythe** [comment]
Hi @JanineSooThow if you would like to continue working on this issue, please provide a progress update.  If my previous message was unclear, I could be available to meet to discuss as well.  If I don't hear from you in the next week (11/14/2023), I'll have to unassign you.

**Comment by JanineSooThow** [comment]
Hi @roslynwythe apologies for the delay, I have finished the issue however I am not sure if I have done it correctly as it has certainly been a while! :D I have added you as one of the reviewers in my PR. If you can take a look and please give me feedback it will be great! Thank you kindly :)

**Comment by aswutmaxcy** [comment]
Availability for this week: Open 8am - 6pm EST M-F
My estimated ETA for completing this issue: 1hr

**Comment by aswutmaxcy** [comment]
How many hours did it take you to finish the pre-work up to and including adding your initial ETA and availability for your good first issue, including attending your first meetings?

A few hours, there are no meetings this week until Sunday (March 10)
