### ISSUE TITLE
Create Issue Template for Updates to CONTRIBUTING.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5547]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a GitHub issue template for updates to CONTRIBUTING.md so that issues can be created efficiently and so that we can provide developers with special instructions for previewing changes to CONTRIBUTING.md.  

### Action Items
- [x] Create a new file `.github/ISSUE_TEMPLATE/update-CONTRIBUTING.md` with YAML frontmatter:
```
---
name: update CONTRIBUTING.md
about: 'For making updates to CONTRIBUTING.md'
title: 'Update CONTRIBUTING.md Section [INSERT SECTION #]'
labels: 'Feature: Wiki, Complexity: Small, role: back
  end/devOps, role: front end, size: 0.5pt'
assignees: ''

---
```
- [x] The body of the issues should come from this [template](https://github.com/hackforla/website/issues/5547#issuecomment-1722424996)
- [x] Refer to these [instructions](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) for testing and preparing the Pull Request. 

### Resources/Instructions
[Manually creating a single issue template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)
- This issue is part of #5441

**Comment by roslynwythe** [comment]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
[INSERT BRIEF DESCRIPTION OF THE UPDATE]

### Action Items
- [ ] In your local IDE, navigate to `CONTRIBUTING.md`
- [ ] Replace
```
[INSERT LINE OF CURRENT CODE HERE]
```
with
```
[INSERT DESIRED LINE OF CODE HERE]
```
- [ ] With CONTRIBUTING.md still open, make a note of the section in which the replaced content appears, so that you will know where to look in the document to preview the change.  
- [ ] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [ ] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.  
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)

**Comment by erinzz** [comment]
Availability: M-F 9-5 
ETA: 9/21 EOD
