### ISSUE TITLE
Refine HackforLA page titles

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#556]
### Overview
The pages on the HfLA site should have unique names that make sense for the content that is on them.  This currently does not seem to be the case.

### Action Items
- [ ] Figure out why the titles are not showing up correctly on the following pages (likely different reasons)
   - [ ] Static HTML pages 
      - [ ] https://www.hackforla.org/project-meetings (currently just says "Hack for LA")
      - [ ] https://www.hackforla.org/getting-started (currently just says "Hack for LA")
   - [ ] On all the following redirect pages (currently says "Twitter_Logo_Blue")
      - [ ] https://www.hackforla.org/survey4
      - [ ] https://www.hackforla.org/survey3
      - [ ] https://www.hackforla.org/survey6
      - [ ] https://www.hackforla.org/donate
   - [ ] Check the other redirects
      - [ ] conduct.md
      - [ ] github.md
      - [ ] meetup.md
      - [ ] nationalday.md
     - [ ] slack.md

### Resources/Instructions
I used this site to find these pages: https://www.xml-sitemaps.com/

**Comment by ye-susan** [comment]
fixes #561
