### ISSUE TITLE
Remove card explaining the changes with removal of the "good second issue" labels

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5587]
### Dependency 
- [x] #4510
- [ ] #4432

### Overview
We need to remove the card "Removal of 'Complexity: good second issue' label" from the `Onboarding infos/links` column when it is no longer required. 

### Action Items
- [ ] On the Project Board, in the `Onboarding infos/links` column, locate the card titled "Removal of 'Complexity: good second issue' label".
- [ ] From the card menu (3 dots in top right corner) select the option 'Delete note'
- [ ] Move this issue to "Questions/In Review" and add the label "ready for dev lead"

**Comment by ExperimentsInHonesty** [comment]
done
