### ISSUE TITLE
Remove "good second issue" from CONTRIBUTING.md Section 2.1

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5588]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to remove references to "good second issue" from CONTRIBUTING.md in order to avoid confusion, since we are no longer creating issues with the label `Complexity: good second issue'.  

### Action Items
- [x] In your local IDE, navigate to `CONTRIBUTING.md` and locate Section 2.1
- [x] Replace
```
2. `Complexity: Good second issue`
  *  Self-assign an issue with the `Complexity: Good second issue` label. 
  * Complete steps in [**2.7 Working on an issue**](#27-working-on-an-issue) to create a solution for the issue
  * Complete steps in [**3.1 How to make a pull request**](#31-how-to-make-a-pull-request) to get your solution reviewed by the `website-merge` team
  * Once your pull request is merged, you can work on your next issue.

Progress through issues with increasing complexity in the following order:
  1. Good first issue
  2. Good second issue
  4. Small 
  5. Medium 
  6. Large
```
with
```
2. Repeat #1 with a new `good first issue`

Progress through issues with increasing complexity in the following order:
  1. Good first issue (x2)
  2. Small 
  3. Medium 
  4. Large
  5. Extra Large
```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather review changes at [REPLACE WITH TEST URL]
```

### For Merge Team
- [ ] Resolve the dependency on this issue in #4506.  If all dependencies have been resolved, close that issue.  

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue is part of #4506

**Comment by robertnjenga** [comment]
Availability: 10a-2p
ETA: 10/3/2023
