### ISSUE TITLE
Updating the looking for on various project

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#559]
### Overview
Project Engage, Food oasis and Website would like an update on what they are looking for

### Action Items
See spreadsheet for changes (green and red)
https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/edit#gid=0

**Comment by ExperimentsInHonesty** [comment]
@jbubar - in looking at the related pull request #569, I see comments by cnk, but I don't see any additional updates from you.  Maybe I am reading this incorrectly. 

Please update with the following information
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
Hi @ethanh256 and @jbubar - some of this information is old already.  i.e. roles filled.  Slack me and I will give you an update and you can change the pull request and update the spreadshet.

**Comment by ExperimentsInHonesty** [comment]
met with Ethan last night and reviewed the order of operations for updating cards.  First we are going to accept this pull request #558 , and then redo all of the looking for to match the spreadsheet.

**Comment by ExperimentsInHonesty** [comment]
@ethanh256 is going to do update today.

**Comment by alexandrastubbs** [comment]
1. Update current project needs spreadsheet
2. Update project.md template file in the wiki

**Comment by ghost** [comment]
Fixed: looking for sections of https://github.com/hackforla/website/wiki/Template-of-a-project.md-file and https://github.com/hackforla/website/wiki/Guide-to-the-Project-Layout-File

Project Needs Google Spreadsheet updated.

Issue closed.
