### ISSUE TITLE
Add "Westside" to list of words in Code Spell Checker configuration file

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5618]
### Overview
We need to update the Code Spell Checker configuration file with false positive terms so that they are no longer marked as errors. 

### Action Items
- [x] You must use VS Code as your local text editor to install the VS Code extension for spell checking your codebase,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] Do not change any configuration settings or make any spell corrections
- [x] Open the file `cspell.json`
- [x] Replace the line
```
  "words": [
```
with
```
  "words": [
      "Westside",
```
- [x] Save `cspell.json` and then test the change by opening `'_includes/events-page/our-locations-content.html'` and confirming that no Code Spell Checker errors/messages are displayed.  
- [x] No docker testing is required.  Create a Pull Request in the usual manner, with changes only to `cspell.json`.   

### Resources
[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

**Comment by nikunjgupta609** [comment]
Mam,
Please assign me to this issue.  @ExperimentsInHonesty

**Comment by kevin31yu** [comment]
Availability for this week: 8 hrs
My estimated ETA for completing this issue: 10/20/23
