### ISSUE TITLE
Create Survey Reporting Dashboard Guide Page

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#562]
### Overview
Create Survey Reporting Dashboard guide to walk users through the process of linking a Google Form to a spreadsheet, processing and cleaning the spreadsheet, and finally visualizing the data in Google Data Studio.

### Action Items
- [x] UI
   - [x] Collect screenshots for all phases of process
   - [x] Draft copy explaining all steps in each phase of process
   - [x] Create Figma mockup for desktop
   - [x] Embed instructional copy in mockup
   - [x] Annotate Figma mockup with callout arrows
   - [x] Create Figma mockup for mobile
   - [x] Adjust all screenshots, copy, and arrows to mobile proportions
- [ ] Development
   - [ ] Create new guide page titled "reporting-dashboard"
   - [ ] Implement desktop and mobile mockups on website
   - [ ] Link Survey Reporting Dashboard guide page on Toolkit page

### Resources/Instructions
Final mockups: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=986%3A1158

**Comment by ashlingam** [comment]
@ExperimentsInHonesty @wesrowe I have made a guide page for building a survey reporting dashboard. Google Data Studio has its limitations (is not as full-featured as a tool like Tableau) and may compete with UI design considerations when implemented. However, it may be a worthwhile tool for UX research/design on some project teams.

**Comment by wesrowe** [comment]
@harishlingam an impressive piece of tutorial writing!

**Comment by ghost** [comment]
@daniellen00 and I did design hand-off mid-week after she consolidated and adjusted several elements, such as arrows, for consistency. I got started on the development side this weekend.

**Comment by ghost** [comment]
I have the content and basic layout complete for the desktop version of the page, starting to work on the more detailed positioning of the arrows and captions. I have a time constraint for the next couple weeks - I'm working on my final project for G.A. until the end of July 21st!

**Comment by ExperimentsInHonesty** [comment]
ETA is 2 weeks.

**Comment by ghost** [comment]
@ye-susan @ruben1s -- Added the overlay image and arrow styles into the _guide-pages.scss file to be pushed up when I make a pull request for the survey-reporting-dashboard. Since there are three different arrow sizes in my project, I was thinking of adding in mix-ins for the medium to large arrow sizes as well. I could do something like...

`.medium-arrow-right-overlay(($top, $left: default-value) {
   @include arrow-right-overlay($top, $left);
   width: medium-arrow-width-needed;
}
`

![Screen Shot 2020-07-12 at 1 27 56 PM](https://user-images.githubusercontent.com/54752231/87255897-8e735f00-c443-11ea-91a8-973c52c83a79.png)

![Screen Shot 2020-07-12 at 1 21 03 PM](https://user-images.githubusercontent.com/54752231/87255788-a4cceb00-c442-11ea-8e82-91bc6d6d9351.png)

**Comment by ruben1s** [comment]
That is good. More dynamic equals better.

**Comment by ghost** [comment]
I'm about 70% done with the desktop version of the site, anticipating this project being complete by following Sunday pending the mobile version.

**Comment by ghost** [comment]
Desktop and mobile of survey reporting page complete, once they are reviewed by the team during Sunday's meeting I'll submit a pr

**Comment by alexandrastubbs** [comment]
@hannahlivnat can you please include screenshots for mobile & desktop in this issue?

**Comment by ghost** [comment]
@alexandrastubbs here they are, thank you for sharing that tool with me!

![screencapture-localhost-4000-guide-pages-survey-reporting-dashboard-guide-2020-07-26-10_10_59](https://user-images.githubusercontent.com/54752231/88485115-78c46600-cf28-11ea-8700-217b0d39c85f.png)
![screencapture-localhost-4000-guide-pages-survey-reporting-dashboard-guide-2020-07-26-10_11_42](https://user-images.githubusercontent.com/54752231/88485117-7bbf5680-cf28-11ea-9c68-f6aaeb04e077.png)
