### ISSUE TITLE
Fix broken CoP redirect

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5622]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to change https://www.hackforla.org/cop to redirect to the _Communities of Practice_ (CoP) page [^1] so that it redirects to the expected page on the website.

### Action Items
- [x] In your IDE, open the `redirections/cop.md` [^2], and make the following change:
  - [x] Change
    ```
    redirect_to: /communities-of-practice/
    ```
    to
    ```
    redirect_to: /communities-of-practice
    ```
- [x] Using Docker, check https://www.hackforla.org/cop will redirect to _Communities of Practice_ (CoP) page [^1]

### Resources/Instructions
- This issue is a result of https://github.com/hackforla/website/issues/5329#issuecomment-1738852984 
[^1]: [_Communities of Practice_ (CoP) page](https://www.hackforla.org/communities-of-practice)
[^2]: File to open in your IDE: `redirections/cop.md`

**Comment by dineshsk98** [comment]
i. Availability: Completed
ii. ETA: Completed

**Comment by dineshsk98** [comment]
Update
1. Progress - Completed
2. Blockers - waiting for #5640 to be merged.
3. Availability - N/a
4. ETA - Completed

**Comment by ExperimentsInHonesty** [comment]
@dineshsk98 ill let you keep this issue.  But in future please do not take issues from the New Issue Approval column.  Only select issues from the Prioritized Backlog.  Even if you have to wait for something to be available.

**Comment by dineshsk98** [comment]
> @dineshsk98 ill let you keep this issue. But in future please do not take issues from the New Issue Approval column. Only select issues from the Prioritized Backlog. Even if you have to wait for something to be available.

I will remember to do that next time. Sorry and thank you.
