### ISSUE TITLE
ER: Update Project Profile: Expunge Assist

### ISSUE THREAD

**Issue by amejiamesinas** [hackforla/website#5627]
### Dependency
- [x] #5752 
- [x] #5753 
- [x] #5754 
- [x] #5755 
- [x] #5756 
- [x] #5757
- [x] #5759 
- [x] #5760
- [x] #5761 
- [x] #5762
- [x] #5763 
- [x] #5919 

### Project Name

Expunge Assist

### Project Card URL

expunge-assist.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Thomas Demoner
- [x] Name: Jamie Siu
- [x] Name: Sheron Virani
- [x] Name: James Shin

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Analicia Mejia Mesinas 
GitHub Handle: amejiamesinas
Role: Product Manager, UX Research
Slack Member ID: U04J34E73CG

- [x] Name: Lane Mitchell
GitHub Handle: lmitch10
Role: Product Manager, Development
Slack Member ID: U052LEP0BSN

- [x] Name: Curtis Barber 
GitHub Handle: CBx3000
Role: Product Manager, Content
Slack Member ID: U05RZAETCQ4

- [x] Name: Sydney Walcoff
Github handle: sydneywalcoff
Role: Development, Team Lead
Slack Member ID: U02P0A49XL4

- [x] Name: Anita Morales
Github handle: anitadesigns
Role: UX Design, Team Co-lead
Slack Member ID: U03F43PFR3K

- [x] Name: Justin Yeh
GitHub handle: jyehllow
Role: UX Design, Team Co-lead
Slack Member ID: U03PNBDLXL1

- [x] Name: Samantha Hyler
GitHub handle: SamHyler
Role: UX Content, Team Lead
Slack Member ID: U025XR6MY6S

### Project Status

Active

**Comment by JessicaLucindaCheng** [comment]
Issue Writing
Availability: 6 hours
ETA: Sunday, October 22, 2023

**Comment by JessicaLucindaCheng** [comment]
All the issue for this ER has been written and links to those issues have been added to the Dependency section.

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issues in the Dependency section have been merged, 
- [x] Close this ER
- [x] Move this ER to the UAT column
- [x] Contact the person who opened this ER to approve the changes on the [Expunge Assist page] (https://www.hackforla.org/projects/expunge-assist) and add a `ready for stakeholder` label
- [x] Once the changes have been accepted by the author of this ER, remove the `ready for stakeholder` label and add a `ready for product` label. Also, leave a comment that this ER is ready for further UAT and QA by product.

**Comment by roslynwythe** [comment]
@amejiamesinas All issues have been completed.  Please review the changes on the [Expunge Assist page](https://www.hackforla.org/projects/expunge-assist).

**Comment by JessicaLucindaCheng** [comment]
@amejiamesinas Please let us know if the changes made to the [Expunge Assist](https://www.hackforla.org/projects/expunge-assist) page match what you requested by adding a comment to this issue. Thank you.

Edit: Left this Slack message on Feb. 5, 2024, about it as well: https://hackforla.slack.com/archives/CN8NXTPK5/p1707177859632849

**Comment by amejiamesinas** [comment]
Hi! Thank you. Yes, changes requested match changes made. However, our team will be submitting a new issue, as we have had some changes on our team since the new year. Thanks.

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-pm The changes requested have already been accepted by the author of this issue. This issue is now ready for you to UAT and QA.
