### ISSUE TITLE
update prework issue instructions regarding calendar invites

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5629]
### Overview
We must update the instructions provided in the prework issue regarding calendar invites, in order to avoid confusion. 

### Action Items
- [x] Open the file `.github/ISSUE_TEMPLATE/pre-work-template--dev.md` in your IDE
- [x] Remove the line:
```
- [ ] Also, confirm with a merge team member or a technical lead that they have added you to the Google Calendar invites for our Zoom meetings
```
- [x] Refer to these [instructions](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) for testing and preparing the Pull Request. 

### Resources/Instructions
[Manually creating a single issue template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)

**Comment by agutiernc** [comment]
Availability: Weekday Afternoon/Evening
ETA: EOD on 10/06
