### ISSUE TITLE
update prework issue instructions regarding team roster

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5631]
### Overview
We need to update the prework instructions regarding the team roster to avoid confusion

### Action Items
- [x] Open the file `.github/ISSUE_TEMPLATE/pre-work-template--dev.md` in your IDE
- [x] replace
```
- [ ] (Once added to the Drive) Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0)
```
with
```
- [ ] Add yourself to the [team roster](https://docs.google.com/spreadsheets/d/11u71eT-rZTKvVP8Yj_1rKxf2V45GCaFz4AXA7tS_asM/edit#gid=0)
```
- [x] Refer to these [instructions](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) for testing and preparing the Pull Request. 

### Resources/Instructions
[Manually creating a single issue template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)

**Comment by Tomomi-K1** [comment]
Availability: Wed 5-8pm, Thurs 1-4pm, Fri 12-3pm
ETA: 10/4 6pm.
