### ISSUE TITLE
update prework issue instructions regarding GitHub teams

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5632]
### Overview
We need to update the prework instructions regarding the github teams to avoid confusion

### Action Items
- [x] If issue https://github.com/hackforla/website/issues/4944 is closed DO NOT WORK ON THIS ISSUE, instead move this issue to the Questions column, and add the `ready for dev lead label`
- [x] Open `.github/ISSUE_TEMPLATE/pre-work-template--dev.md` in your IDE
- [x] remove
```
- [ ] After you have finished adding yourself to the roster, let a merge team member or a technical lead know you have added yourself to the roster and would like to be added to the `website-write` and `website` teams on GitHub
```
- [x] Refer to these [instructions](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) for testing and preparing the Pull Request.

**Comment by tkozek** [comment]
Availability5-9 PST M-F

**Comment by tkozek** [comment]
Blockers: Unable to find the relevant code to edit

**Comment by t-will-gillis** [comment]
Unassigning @tkozek 
- was not in "Prioritized Backlog"
- otherwise, was abandoned

**Comment by del9ra** [comment]
i. Availability: Tuesdays - Thursdays 1-4 PM
ii. ETA: 10PM 06/07/2024
