### ISSUE TITLE
update prework issue instructions regarding website-write team

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5633]
### Overview
We need to remove outdated and confusing instructions from the prework issue template

### Action Items
- [x] Open the file `.github/ISSUE_TEMPLATE/pre-work-template--dev.md` in your IDE
- [x] replace
```
- [ ] Once added to the website-write team:
  - [ ] Self Assign this issue (gear in right side panel)
  - [ ] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label (gear in right side panel)
  - [ ] Add this issue to the Project Board under the Projects section (gear in right side panel)
```
with
```
- [ ] Self Assign this issue (gear in right side panel)
- [ ] Add the "role: front end" or "role: back end" or both label(s) to this issue and remove the "role missing" label (gear in right side panel)
- [ ] Add this issue to the Project Board under the Projects section (gear in right side panel)
```
- [x] Refer to these [instructions](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) for testing and preparing the Pull Request. 

### Resources/Instructions
[Manually creating a single issue template for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/manually-creating-a-single-issue-template-for-your-repository)

**Comment by kmalap05** [comment]
I would like to do this task.
Assign it to me with a tag of Hacktoberfest 2023.

**Comment by ExperimentsInHonesty** [comment]
@kmalap05 We don't accept code submissions from outside the team.  The team is open to all members, but there is an onboarding process from Hack for LA.  Feel free to sign-up for our next onboarding here here: https://www.meetup.com/hackforla/events/

**Comment by GRK1998** [comment]
i. Availability: 9 to 5 Monday to Friday  
ii. ETA: 11 Oct Wednesday
