### ISSUE TITLE
ER: vrms-data github action does not gracefully fail when vrms request fails

### ISSUE THREAD

**Issue by jaasonw** [hackforla/website#5650]
### Emergent Requirement - Problem
When the request to the VRMS API fails and returns an error, meeting times are overwritten and replaced with a "503 Service Temporarily Unavailable" HTML file instead of retaining the previous meeting times

### Issue you discovered this emergent requirement in
- https://github.com/hackforla/website/commit/694f279009090cd9713835a8e4e9d12042f54175 created by [vrms-data.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/vrms-data.yml)

### Date discovered 
10/2/2023

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@

### What happens if this is not addressed
The team meetings page will be unavailable for at least 24 hours

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team
- [x] Let a Team Lead know

**Comment by t-will-gillis** [comment]
Messaged with @jaasonw earlier to understand the bug, when it occurred, etc. Jason gave very helpful suggestions for the fix- thank you again, Jason.

~I will write an issue to address the bug-~

Jason says that he can write up the issue-

**Comment by roslynwythe** [comment]
I asked @t-will-gillis about this and he stated "the vrms-data.yml file is not updated with the dependabot changes yet... the commit log shows that vrms-data.json was overwritten with the 503 error, which isn't ideal, but at the same time the data wasn't lost because it was all regenerated."

**Comment by ExperimentsInHonesty** [comment]
@jaasonw please go ahead and make the issue for this now.

**Comment by jaasonw** [comment]
should i close this issue too?

**Comment by JessicaLucindaCheng** [comment]
@jaasonw Yes, you can close this issue with a comment linking to the issue you wrote for this ER.

**Comment by jaasonw** [comment]
new relevant issue: https://github.com/hackforla/website/issues/5691
