### ISSUE TITLE
add instructions for workstation spell checking using npm package

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5652]
### Dependency
- [x] #4101

### Overview
As developers of the Hack for LA website, we want to align on the tools we're using to keep the codebase as free as possible of misspellings so our reputation and the quality of our code is maintained. The recommended method of local spell checking is to use the VSCode Code Spell Checker extension, but for developers who do not use VSCode, we need to provide guidance for use of the corresponding npm package, `cspell`

### Action Items
- [x] In `CONTRIBUTING.md`, section 1.7 add instructions for local codebase spell checking for users who do not use VSCode.  
- [x] Provide instructions for installation and use of the [cspell npm package](https://www.npmjs.com/package/cspell)
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Ensure that the linkage from the first action item links correctly to the second action item's instructions.
- [x] Create a pull request in the usual manner, but after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
[cspell npm package](https://www.npmjs.com/package/cspell)

### Merge Team
- [ ] After this issue is completed, change the instructions in the pre-work checklist from 
```
Complete steps 1.1 - 1.6 in [Part 1: Setting up the development environment within Contributing.md]
``` 
to 
```
Complete steps 1.1 - 1.7 in [Part 1: Setting up the development environment within Contributing.md]
```

### Resources/Instructions

- [Code Spell Checker VS Code extension](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
- [Installing VS Code extensions](https://code.visualstudio.com/learn/get-started/extensions)
- [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)

### Related Issues
- This issue is part of an epic https://github.com/hackforla/website/issues/4349

**Comment by robertnjenga** [comment]
Availability: Mon-Fri 10a-2p
ETA: 11/14/2023
