### ISSUE TITLE
Add instructions concerning Google Analytics snippet to Wiki

### ISSUE THREAD

**Issue by ashlingam** [hackforla/website#567]
### Overview
We have implemented Google Analytics on our website. Please add instructions concerning the implementation of Google Analytics snippet to Wiki. References #503.

Google Analytics code snippet:

> <script async src="https://www.googletagmanager.com/gtag/js?id=UA-167506267-1"></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'UA-167506267-1'); </script>

### Action Items
- [x] Add instructions concerning Google Analytics snippet to wiki

**Comment by ye-susan** [comment]
Hi @ExperimentsInHonesty, just to clarify - are we using GA along with Hotjar (since we still have the Hotjar code in place), or are we replacing Hotjar?

**Comment by ye-susan** [comment]
The [Wiki](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture#api-endpoints) has been updated with GA
