### ISSUE TITLE
ER: Project's Check page not working

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#5677]
### Emergent Requirement - Problem
The https://www.hackforla.org/projects-check page does not work, it is cutting off languages at the least, All the lists seems to be the same length, which is improbable.  And the language list is longer on the projects page

### Issue you discovered this emergent requirement in
- #3487

### Date discovered 
2023-10-08

### Did you have to do something temporarily
- [x] YES, move issue to the icebox
- [ ] NO

### Who was involved
@ExperimentsInHonesty @Josiah-O 

### What happens if this is not addressed
We can't use the project's check page

### Resources
<details><summary>Screenshot of projects-check page, Technologies and Languages lists (16 items)</summary>

![image](https://github.com/hackforla/website/assets/37763229/4382a678-e50a-464f-8ba7-fd22cdb1cbca)
</details> 

<details><summary>Project's page. Languages/Technologies list (71 items)</summary>

 Adobe CC (1)
 Amazon Cognito (1)
 Angular (1)
 AWS (7)
 Azure App Service (1)
 Babel (1)
 Batchfile (1)
 CKAN (1)
 Code Climate (1)
 CSS (20)
 Cypress (1)
 Dart (1)
 Django (2)
 Django REST Framework (1)
 Docker (7)
 Dockerfile (12)
 ESLint (1)
 Express (4)
 FastAPI (1)
 Figma (3)
 Flask (1)
 Flutter (1)
 GeoPandas (1)
 GitHub Actions (2)
 GitHub Pages (3)
 Google Apps Script (1)
 HCL (3)
 HTML (23)
 Insomnia (1)
 JavaScript (22)
 Jekyll (2)
 Jest (1)
 jQuery (1)
 Jupyter Notebook (5)
 Kotlin (1)
 Leaflet (1)
 Makefile (4)
 Mako (2)
 Mapbox (3)
 Markdown (2)
 Material-UI (2)
 MDX (2)
 Microsoft SQL Server (1)
 Miro (2)
 mkdocs (1)
 MongoDB (5)
 MongoDB Atlas (1)
 Nginx (1)
 Node.js (8)
 NoSQL (1)
 OAuth2 (1)
 Objective-C (1)
 OIDC (1)
 PLpgSQL (3)
 PostGIS (1)
 PostgreSQL (7)
 Postman (1)
 Prefect (1)
 Procfile (2)
 Python (9)
 React (13)
 React Testing Library (1)
 Redis (1)
 Redux (2)
 SCSS (10)
 Shell (14)
 Swift (1)
 TSQL (1)
 TypeScript (7)
 VRMS API (1)
 Webpack (1)
</details> 

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

**Comment by roslynwythe** [comment]
- @ExperimentsInHonesty this problem will be resolved by #4960

**Comment by ExperimentsInHonesty** [comment]
I agree this is resolved!  Closing
