### ISSUE TITLE
Remove '1Password' From Tools Data in website.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5679]
### Overview
'1Password' needs to be removed from tools data in website.md since 1Password is not considered as a tool.

### Action Items
- [x] Open `_projects/website.md` in your IDE
- [x] In the `tools` section, remove the line:
```
  - 1Password
```
- [x] Using docker, confirm that the Tools menu on the Projects-Check page no longer displays and the Website Project Page no longer displays, but that these pages are unchanged otherwise.  

### Resources/Instructions
[Project Check Page](https://www.hackforla.org/projects-check)
[HfLA Homepage](https://www.hackforla.org/)
[Projects Page](https://www.hackforla.org/projects/)

**Comment by danvgar** [comment]
@roslynwythe I took a look at this issue and don't see a _projects/ directory, nor a website.md. Is this issue already taken care of?

**Comment by danvgar** [comment]
> @roslynwythe I took a look at this issue and don't see a _projects/ directory, nor a website.md. Is this issue already taken care of?

Disregard, just found it. Not sure why it wasn't showing up in any of my searches in my IDE or Github. Sorry for the spam!

**Comment by danvgar** [comment]
@roslynwythe I've taken a look at this issue and [website.md](https://github.com/hackforla/website/blob/f0e0f68f0509f32aad3b4fc6541bf18c01bc8bae/_projects/website.md?plain=1#L122) doesn't include 1Password in the markdown. It also does not appear on any of the Project pages ([Project Check Page](https://www.hackforla.org/projects-check) | [HFLA Homepage](https://www.hackforla.org/) | [Projects Page](https://www.hackforla.org/projects/) ).

The only portion of the website it shows up is in the Toolkit page, which is unrelated to this issue. See below screenshot
I believe this issue can be closed, but let me know if I've missed anything. Thank you!

<img width="802" alt="Screenshot 2024-02-01 at 5 16 24 PM" src="https://github.com/hackforla/website/assets/124107401/7aff4f56-b3e4-4187-a69a-b61ec52a7108">

**Comment by roslynwythe** [comment]
@danvgar I apologize, this issue was created in error.  It is a duplicate of #5680. 

I noticed that you have already completed two `good first issues` so next please assign yourself to a `Complexity: Small`.  Thank you.

**Comment by danvgar** [comment]
> @danvgar I apologize, this issue was created in error. It is a duplicate of #5680.
> 
> I noticed that you have already completed two `good first issues` so next please assign yourself to a `Complexity: Small`. Thank you.

Thank you, Roslyn! Apologies to bump this one, this was shortly before I realized that I was looking in the wrong column of the Project Board for `good first issue`s.
