### ISSUE TITLE
Remove '1Password' From Tools Data in tech-work-experience.md 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5681]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
'1Password' needs to be removed from tools data in tech-work-experience.md  since 1Password is not considered as a tool.

### Action Items
- [x] Open `_projects/tech-work-experience.md` in your IDE
- [x] In the `tools` section, remove the line:
```
  - 1Password
```
- [x] Using docker, confirm that on the [Project Check Page](https://www.hackforla.org/projects-check), the Tools menu no longer includes `1password`, and the [Tech Work Experience Project Page](https://www.hackforla.org/projects/tech-work-experience) no longer displays `1Password` under Tools, but that both pages are otherwise unchanged.  

### Resources/Instructions
[Project Check Page](https://www.hackforla.org/projects-check)
[HfLA Homepage](https://www.hackforla.org/)
[Projects Page](https://www.hackforla.org/projects/)
[Tech Work Experience Project Page](https://www.hackforla.org/projects/tech-work-experience)
- This issue resulted from #5271

**Comment by sornekian** [comment]
When removing "1Password" from the tech-work-experience.md file, the Tech Work Experience Project Page updated but the Project Check page was unaffected.
