### ISSUE TITLE
Update vrms-data.yml to fail when the VRMS API fails to return a valid response

### ISSUE THREAD

**Issue by jaasonw** [hackforla/website#5691]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview

When the request to the VRMS API fails and returns an error, meeting times are overwritten and replaced with a "503 Service Temporarily Unavailable" HTML file instead of retaining the previous meeting times

### Action Items
- [x] Validate that the github action fails incorrectly
  - [x] Update `.github/workflows/vrms-data.yml` commenting out `if: github.repository == 'hackforla/website'` to allow the github action to run locally on your fork
  - [x] Replace `https://www.vrms.io/api/recurringevents` with `https://httpstat.us/503` to validate that the github action fails incorrectly and push the commit to validate that the github action fails incorrectly and overwrites the json file in `_data/external/vrms_data.json`
  - [x] Undo the changes to `_data/external/vrms_data.json`
- [x] Update `.github/workflows/vrms-data.yml` to retry the request n times if it fails and terminate if it still fails to update. Adding `--retry` and `--fail` to the curl parameters should accomplish this. I've included links to the man pages for both below
- [x] Validate that the changes now no longer overwrite `_data/external/vrms_data.json` and the github action indicates a failed run
- [x] Replace `https://httpstat.us/503` with `https://www.vrms.io/api/recurringevents`
- [x] Verify the github action still runs correctly with the vrms api
- [x] Uncomment the `if: github.repository == 'hackforla/website'` you commented in the earlier step

### Resources/Instructions

1. https://curl.se/docs/manpage.html#-f
2. https://curl.se/docs/manpage.html#--retry
3. https://httpstat.us/ returns HTTP status codes, useful for debugging

relevant issue: https://github.com/hackforla/website/issues/5650

**Comment by roslynwythe** [comment]
Thank you @jaasonw for writing this issue.  It looks like you have provided some useful information to the developer who takes on the issue, which is great so that it can be fixed quickly.  I see that it has a `Draft` label.  Does that mean that you are still in the process of writing it?  

I do have a few suggestions.  Would it be possible for you to add an Action Item that provides guidance for testing the completed issue?  That will also help reviewers.  Also for a `Complexity: Medium` issue I usually suggest a size of 1 pt, and for "Project", please select "Project Board".  The issue will automatically be placed in "New Issue Approval".  Also when an issue is ready for the initial dev lead review, please apply the "ready for dev lead" label so that it will come to my attention.  Once I approve it, it will go to Bonnie for prioritization and then you can close the ER issue.  Thanks again for spotting this bug!!

**Comment by jaasonw** [comment]
I'm actually not sure how I would test this as it involves the vrms api in production returning an error code. The way I tested it in my command line was to send a curl request to https://httpstat.us/503, so really, the only way I can think of to test it is to push a commit replacing the URL with https://httpstat.us/503 and observe its behavior. I've updated the issue with instructions for it. It's not the most elegant unless there's a good way to debug github actions locally; it's the only way I can think of.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe can I hide the prior two comments?

**Comment by kevin31yu** [comment]
i. Availability: 12/3 - 12/4 (8 hrs total)
ii. ETA: 12/4

**Comment by kevin31yu** [comment]
Provide Update

Progress: Replace https://www.vrms.io/api/recurringevents with https://httpstat.us/503 to validate that the github action fails incorrectly and pushed the commit.

Blockers: The github action is not running so the file `_data/external/vrms_data.json` is not changing.

**Comment by kevin31yu** [comment]
Provide Update

Progress: Manually ran the github action `Update VRMS data` on the branch `kevin31yu/website/tree/Update-vrms-data-yml-to-fail-5691`.

Blockers: Received error message `Error: Input required and not supplied: token` for the code `Run actions/checkout@v4`.

**Comment by kevin31yu** [comment]
![Uploading Capture.PNG…]()

**Comment by kevin31yu** [comment]
![Capture](https://github.com/hackforla/website/assets/118224034/25eca911-19b7-4e69-b29e-a1d254de12a6)

**Comment by t-will-gillis** [comment]
Hey @kevin31yu The error you are seeing is referring to line 18- As I am reading through the issue description above, I don't see any instructions about setting up your secrets/access tokens, which is something you definitely need to do to test GHAs.   

<details><summary>screenshot</summary><img width="919" alt="Screenshot 2023-12-06 083621" src="https://github.com/hackforla/website/assets/40799239/91d185a9-e8ab-4881-bc52-377f896ebe26"></details>  

Please take a look through [Hack for LAs GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions) and especially line 7 for setting up your personal access token, and this should get you past this error.

Feel free to message me or anyone on the merge team if you have additional questions
