### ISSUE TITLE
Update CONTRIBUTING.md Section 2.7.f i SSH for Mac

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5693]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
In [CONTRIBUTING "i. Setting up SSH keys for Mac"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-setting-up-ssh-keys-for-mac) we need to clarify the instructions used for setting up an SSH key for Mac in Section 2.7.f i in order to avoid confusion. 

### Action Items
- [x] In your local IDE, open CONTRIBUTING.md and navigate to Section 2.7.f i "Setting up SSH Keys for Mac"
- [x] Replace
```
4. Next you need to add your ssh key to your ssh agent.
```
with
```
4. Next you need to add your ssh key to your ssh agent.  In the command below, replace `id_ed25519` with the filename (without file extension) you provided in the previous step.
```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING "i. Setting up SSH keys for Mac"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-setting-up-ssh-keys-for-mac)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue resulted from #4559

**Comment by ChrisKildunne** [comment]
Availability: Weekday Evenings
ETA: Just made the PR should be done by end of day :)

**Comment by ChrisKildunne** [comment]
Progress: I have made the changes to the contributing.md
Blockers: I am continuously running into formattiong issues every *** gets switched to --- in my remote branch. I have disabled extentions and toggled of format on save in vs code. Due to this I believe I am running into merge conflicts.
Availability: I have about an hour every evening to work on this.

**Comment by ajb176** [comment]
I'm just guessing here, but you may need to restart VS Code or your computer. 

Try restarting your computer after double checking to make sure you've disabled all the extensions. Then pull from upstream and open the file in a text editor like notepad (to see if the files match the upstream files). If you don't see the issue in a different editor, at least you know it's a VSCode issue and not an issue updating the local repository. 

If you open the file in VSCode and you're still seeing the edits, I can suggest re-installing but if you don't want to do that you'll probably have to do some googling.

**Comment by ajb176** [comment]
If all else fails, you can just use a different editor to edit the file and figure things out with VSCode later
