### ISSUE TITLE
Update CONTRIBUTING.md Section 2.7.f ii SSH for Windows

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5694]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
In [CONTRIBUTING - 2.7.f ii "Setting up SSH keys for Windows"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#ii-setting-up-ssh-keys-for-windows) we need to clarify the instructions in order to avoid confusion. 

### Action Items
- [x] In your local IDE, navigate to `CONTRIBUTING.md` Section 2.7.f i "Setting up SSH Keys for Windows"
- [x] Replace
```
4. Next you need to add your ssh key to your ssh agent.
```
with
```
4. Next you need to add your ssh key to your ssh agent.  In the command below, replace `id_ed25519` with the filename (without file extension) you provided in the previous step.
```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING - 2.7.f ii "Setting up SSH keys for Windows"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#ii-setting-up-ssh-keys-for-windows) 
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue resulted from #4559

**Comment by jleung7158** [comment]
i. Availability: M-T after 2PM, W-F after 7PM
ii. ETA: 1 week!
