### ISSUE TITLE
Update CONTRIBUTING.md Section 2.7.f ii SSH for Windows - creating folder

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5695]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
In [CONTRIBUTING - 2.7.f ii "Setting up SSH keys for Windows"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#ii-setting-up-ssh-keys-for-windows) we need to provide instructions for creating the folder `~/.ssh` prior to using `ssh-keygen` in order to avoid confusion for developers creating their initial SSH key.

### Action Items
- [x] In your local IDE, open CONTRIBUTING.md and navigate to "Section 2.7.f ii. Setting up SSH Keys for Windows"
- [x] Replace 
<pre><code>
##### **ii. Setting up SSH Keys for Windows**
1. You have to set up SSH keys in order to contribute to github remotely. First check if you have any keys set up already.
```bash
ls -al ~/.ssh
``` 
</code></pre>
with 
<pre><code>
##### **ii. Setting up SSH Keys for Windows**
1. You have to set up SSH keys in order to contribute to github remotely. First check if you have any keys set up already.
```bash
ls -al ~/.ssh
```
If the folder ~/.ssh does not exist, create it using
```bash
mkdir ~/.ssh
```
</code></pre>
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING - 2.7.f ii "Setting up SSH keys for Windows"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#ii-setting-up-ssh-keys-for-windows) 
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue resulted from #4559

**Comment by rankdjr** [comment]
Progress: Creating branches and working through tasks according to CONTRIBUTING.md documentation workflow
Blockers: none
Availability: 4-6 hrs
ETA: 12/8/23
