### ISSUE TITLE
Update CONTRIBUTING.md Section 3.1.b vi

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5696]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
### Overview
In [CONTRIBUTING.md "vi.  after pull request is submitted/merged"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#vi-after-pull-request-is-submittedmerged) we need to remove duplicate statements about removing an issue branch following PR merge, in order to avoid confusion. 

### Action Items
- [x] In your local IDE, navigate to CONTRIBUTING.md 3.1.b, under "vi. After pull request is submitted/merged"
- [x] Remove the lines
<pre><code>
Now you can move on to your next issue and create a new branch. (This ensures you don’t accidentally include the changes from your previous branch in your new branch)

From here, once your pull request is approved and merged you can pull the recent merge from the Hack For LA repository and delete your local branch:

```bash
git pull upstream gh-pages
git branch -d update-give-link-2093
```

Managing branches this way will keep the commit logs cleaner on the Hack For LA repository, versus merging your completed feature branches into your local repo.
</pre></code>

- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING.md "vi.  after pull request is submitted/merged"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#vi-after-pull-request-is-submittedmerged)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue resulted from #4559

**Comment by roslynwythe** [comment]
As stated in the Overview, this section https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#vi-after-pull-request-is-submittedmerged contains some duplicate instructions.  I applied `ready for product` because there were several options about which language to retain so I thought PM should take a look.  Thanks

**Comment by ExperimentsInHonesty** [comment]
I'll add this to the agenda today.  But I am fine with @roslynwythe 's judgement and if needed the wisdom of the merge team.

**Comment by james-aguirre** [comment]
Availability:  5PM-7PM M-F.
ETA: 12/2/2023
