### ISSUE TITLE
Update CONTRIBUTING.md Section 2.7.a

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5697]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
In [CONTRIBUTING.md 2.7.a Working on an issue (1): Verify current branch is gh-pages](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27a-working-on-an-issue-1-verify-current-branch-is-gh-pages) we need to clarify the instructions by removing mention of pushing local commits.  

### Details
2.7.a the statements "IMPORTANT: Before you push your local commits to your repository, sync your fork to the main ..." and "You can also sync your fork directly ..." along with the "Click here to see..." are confusing because this section provides instructions for getting started on an issue. The issue branch has not even been created yet so instructions relating to pushing local commits seems out of place. Instead, write "update gh-pages with upstream changes" and provide the full command git pull upstream gh-pages.

### Action Items
- [x] In your local IDE, open `CONTRIBUTING.md and navigate to "2.7.a Working on an issue (1): Verify current branch is gh-pages"
- [x] Replace (be sure to include the `<details>..</details>` block)
<pre><code>
**IMPORTANT:** Before you push your local commits to your repository, sync your fork to the main Hack For LA website repository. `git pull upstream` will ensure that your local repository is up-to-date with the main site:

```bash
git pull upstream
```

You can also sync your fork directly on GitHub by clicking "Sync Fork" at the right of the screen and then clicking "Update Branch"

<details>
  <summary><strong>Click here</strong> to see how to sync the fork on GitHub</summary>
  <img src="https://docs.github.com/assets/cb-49937/images/help/repository/update-branch-button.png" />
</details>
</code></pre>

with
<pre><code>
Update your gh-pages branch with upstream changes

```
git pull upstream gh-pages
```

</pre></code>
- [x] With CONTRIBUTING.md still open, make a note of the section in which the replaced content appears, so that you will know where to look in the document to preview the change.
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue resulted from #4559

**Comment by roslynwythe** [comment]
Requesting PM approval because this change was not included in the ER.  The relevant section can be found at https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue under the subheading "2.7.a Working on an issue (1): Verify current branch is gh-pages".  This section is describing the preparation for creating an issue branch and so the instructions about pushing local commits to the repository is not relevant and I personally recall finding it confusing.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe This issue looks good to me.  I reorganized the top part (to move the top part under `### Details`.  I think this issue is ready to prioritize if you are done with it.

**Comment by jtw007** [comment]
Availability: 2/1 afternoon, 2/5, 2/6 (Mon and Tues) mornings and afternoons
ETA: later today, 2/5 (Mon) at latest
