### ISSUE TITLE
Update CONTRIBUTING.md Section2.7.b - making sure devs checkout gh-pages first

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5698]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
In the instructions in  [CONTRIBUTING.md 2.7.b "Working on an issue (2): Create a new branch where you will work on your issue"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue), we need to ensure that the developer has checked out the `gh-pages` branch prior to proceeding to create the issue branch, and that after making files changes, the developers uses caution when using `git add` to prevent inclusion of unwanted files in the subsequent commit.  

### Action Items
- [x] In your local IDE, open CONTRIBUTING.md and navigate to "Working on an issue (2): Create a new branch where you will work on your issue"
- [x] Replace:
```
The `git checkout` command will create and change to a new branch where you will do the work on your issue.  In git, the checkout command lets you navigate between different branches.  Using the `-b` flag you can create a new branch and immediately switch into it. 

For example,if we creating a new issue branch off [Update ‘Give’ image credit link and information - #2093](https://github.com/hackforla/website/issues/2093):
```
with
```
If you have not already done so, run `git checkout gh-pages` to switch the working directory to the `gh-pages` branch and then update `gh-pages` with upstream changes as described above in Section 2.7.a. 

Using the `-b` flag you can also use the `git checkout` command to create a new branch and immediately switch into it.  

For example,if we creating a new issue branch for [Update ‘Give’ image credit link and information - #2093](https://github.com/hackforla/website/issues/2093):
```
- [x] Replace:
```
When you've finished working on your issue, follow the steps below to prepare your changes to push to your repository.
```
with
```
We urge developers to be cautious using `git add`.  In general it is not advisable to use `git add -all` or `git add .`.  Rather, run `git status`, examine the output carefully, and then add only those files specifically related to the current issue.  This will ensure that no extraneous files are included in the subsequent commit.  

When you've finished working on your issue, follow the steps below to prepare your changes to push to your repository.
```

- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
 [CONTRIBUTING.md 2.7.b "Working on an issue (2): Create a new branch where you will work on your issue"](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27b-working-on-an-issue-2-create-a-new-branch-where-you-will-work-on-your-issue)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue is part of #4559

**Comment by roslynwythe** [comment]
- Applying "ready for product" because the ER #4559 did not originally call for this change; it is a suggestion attempting to prevent devs from basing new issue branches on previous issue branches.

**Comment by roslynwythe** [comment]
Hi @ExperimentsInHonesty I added "ready for product" because I added instructions warning developers to be careful using `git add --all`, to prevent inclusion of unwanted files in commits.

**Comment by jphamtv** [comment]
Availability for this week: Monday-Friday 12–2 PM, 8–10 PM (PST) 
My estimated ETA for completing this issue: 10 PM 11/26/23
