### ISSUE TITLE
attribute appears to be superfluous in `_guidepages/2FA.html` 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5712]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
Determine whether or not an empy class attribute in `_guidepages/2FA.html` is superflous, and if so, remove it.    

### Action Items
- [x] In your local IDE, navigate to `_guidepages/2FA.html` at or near line 50, and note the line of code
```
<div class=''>

```
- [x] Determine whether the class attribute is superflous (unnecessary).  
  - [x] If so, remove it, then perform local testing using docker to ensure that the behavior and appearance of the page is unchanged, and then proceed to create a Pull Request
  - [ ] If the HTML should remain as-is, explain in a comment in the issue, then move the issue to Questions/In Review and apply the 'ready for dev lead' label.  

### Resources/Instructions
1. For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_guidepages/2FA.html
2. Webpage: https://www.hackforla.org/guide-pages/2FA

**Comment by LukeLowrey2** [comment]
Availability: Wednesday 10/25/23 10am-12pm, Thursday 10/26/23 10am-12pm, Sunday 10/29/23 9am-12pm, Monday 10/30/23 11am-1pm

ETA:  Monday 10/30/23 EOD

**Comment by LukeLowrey2** [comment]
Progress: I found the superfluous empty class attribute in _guide-pages/2FA.html at line 50. I deleted the empty class attribute. I saw no changes to behavior or appearance when testing locally.

Blockers: No blockers

Availability: Sunday 10/29/2023 9am-11am, Monday 10/30/2023 9am-11am

ETA: Issue is complete and waiting on pull request approval

**Comment by roslynwythe** [comment]
Great job @LukeLowrey2 please proceed with pull request.  Thank you.

**Comment by LukeLowrey2** [comment]
Blocker: Unable to work around an unwanted file change in the pull request. I will be asking for assistance at the next meeting I can attend.

Availability: Tuesday 11/7/23 5pm-7pm
