### ISSUE TITLE
Add new variable github-handle to member Eric Cho in 311-data.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5713]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/311-data.md` in your IDE
- [x] Replace:
```
- name: Eric Cho
```
with
```
- name: Eric Cho
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.   

### For Merge Team
- [ ] Release the dependency for this issue in #5441.  If all the dependencies have been completed, close that issue.  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/311-data.md
Project Webpage: https://www.hackforla.org/projects/311-data
- This issue is part of #5441

**Comment by kevin31yu** [comment]
Availability for this week: 8 hrs
My estimated ETA for completing this issue: 10/23/2023
