### ISSUE TITLE
Add new variable github-handle to member Salima Yacoubi in civic-tech-jobs.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5715]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/civic-tech-jobs.md ` in your IDE
- [x] Replace:
```
- name: Salima Yacoubi 
```
with
```
- name: Salima Yacoubi 
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.   

### For Merge Team
- [ ] Release the dependency for this issue in #5441.  If all the dependencies have been completed, close that issue.  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Project Webpage: https://www.hackforla.org/projects/civic-tech-jobs
- This issue is part of #5441

**Comment by Anahisv23** [comment]
i. Availability: Jan 10 from 11am - 4pm
ii. ETA: Jan 10 from 11am - 4pm

**Comment by iancooperman** [comment]
Availability: Jan. 12 from 5pm to 9pm, Jan. 13 from 10am to 9pm
ETA: Jan. 12

**Comment by iancooperman** [comment]
Progress: Technically not started. See blocker.
Blockers: Prasadh Palanichamy does not appear to be mentioned in `311-data.md`. Cannot replace what does not exist.
Availability: Sat 1/13, 10am-9pm
ETA: Sat 1/13, provided that clarification on blocker is given.
Pictures: N/A

**Comment by roslynwythe** [comment]
@iancooperman I have updated the issue with the name of a new member.

**Comment by iancooperman** [comment]
In that event, it would appear that the needed change has already been made. Sanju Venugopal already has a `github-handle` variable. Maybe this can just be closed as not planned?

**Comment by roslynwythe** [comment]
Hi @iancooperman I apologize for the error.  Please see the edited issue for the new name.
