### ISSUE TITLE
Project Slack links: Civic Tech Jobs

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5716]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to edit the Slack link for the project so that we have continuity between project Slack links.

### Action Items
- [x] In `_projects/civic-tech-jobs.md`, for the Slack `url` under the `links` section, change 

From:
```
url: https://hackforla.slack.com/messages/C02509WHFQQ
```
To:
```
url: https://hackforla.slack.com/archives/C02509WHFQQ
```
- [x] Ensure that clicking the Slack link resolves to the new address at the following places:
  - [x] On the [Projects page](https://www.hackforla.org/projects/), the Slack link under the `Links` field for the project's card
  - [x] On the Civic Tech Jobs page (https://www.hackforla.org/projects/civic-tech-jobs),
    - [x] the Slack link under the `Links` field in the Project Overview section
    - [x] the Slack link in the Resources section 
- [x] Once your pull request is merged, go to #4564 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4564 to **Questions / In Review** column and add a **ready for dev lead** label to it

### Resources/Instructions
- Directory to find the page once you have it in your IDE: `_projects/civic-tech-jobs.md`
- [Projects page](https://www.hackforla.org/projects/)
- Project page URL: https://www.hackforla.org/projects/civic-tech-jobs
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md?plain=1
- This issue is tracked in #4564

**Comment by ChrisKildunne** [comment]
i. Availability: Weekday Evenings
ii. ETA: Before 12/7
