### ISSUE TITLE
ER: GHA needs to add `size: missing`

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5717]
### Emergent Requirement - Problem
github-actions bot is not adding `size: missing` label when an issue is created without a size label.

### Issue you discovered this emergent requirement in
- #5716

### Date discovered 
2023-Oct-16

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@JessicaLucindaCheng 

### What happens if this is not addressed
When an issue is created without a size label, it will not have a `size: missing` label.

### Resources
- List of size labels: https://github.com/hackforla/website/labels?q=size

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
Write an issue to update the GHA to add the `size: missing` label for issues created without a size label of some sort. See resources for a list of size labels.

**Comment by t-will-gillis** [comment]
Issue #6022 created to address this ER, therefore closing this.
