### ISSUE TITLE
Prevent User from Scrolling the Home, Project, or Toolkit Page when Scrolling through Mobile Version of the Filter 

### ISSUE THREAD

**Issue by Adastros** [hackforla/website#5730]
### Overview

We need to prevent the user from unintentionally scrolling through the Home, Project, or Toolkit page when scrolling through the mobile version of the filter. 

### Details
<details>
<summary>Watch how the scrollbar moves when the filter overlay is active and how scrolling moves the position of the page behind the filter overlay</summary>

![2023-10-16 23-00-37](https://github.com/hackforla/website/assets/48114590/5dcf8256-d159-483a-8ee3-28fb671e38a0)
</details>

### Action Items

- [x] Update the styling and JavaScript code for the projects and toolkit filters as needed to prevent the page scrollbar from moving when the filter overlay is present on the mobile view

### Resources/Instructions

- This issue was created per #5233 
- [Home Page](https://www.hackforla.org/#)
- [Projects Page](https://www.hackforla.org/projects/)
- [Toolkit Page](https://www.hackforla.org/toolkit/?)

**Comment by tesiahwang** [comment]
Availability: flexible
ETA: 11/10/2023
