### ISSUE TITLE
Componentize the website

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#577]
### Overview
We need to make the website more modular easier to design and develop new content.   We are going to start with reusable components

### Action Items
- [x] UI/UX
   - [x] Create a new page in Figma that is all the component examples that make up a webpage on our site.
      - [x] Headers: different layout types
      - [x] etc.
  - [x] Review with Design team to determine ideal choices
     - [x] Create style guide.
- [x] Development
   - [x] scss files for web components (e.g., headers, white box in body, etc.
   - [x] see notes from https://github.com/hackforla/website/pull/720 regarding removing mixins vs bootstrap (decision has not been made but can be discussed).

### Resources/Instructions
[Main figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205)

**Comment by daniellen00** [comment]
Currently working on this- will have a draft ready for comments/edits

**Comment by daniellen00** [comment]
**Progress:** Completing this- It's taking longer than expected because the website changed compared to the Figma pages, so I have been "inspecting Element" on the site to find new measurements.
**Blocks:** Limited time
**Availability:** Thursday, Friday, Saturday, Sunday
**ETA:** Trying to finish by tomorrow 6/6

**Comment by daniellen00** [comment]
First draft: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1695%3A13302

Still need to adjust several parts, but getting there!

**Comment by ExperimentsInHonesty** [comment]
@ye-susan will coordinate with @daniellen00 to get consistency - so that page title and other heading names are changed to be what is reflected in the existing typograph scss https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_typography.scss

**Comment by daniellen00** [comment]
Utilized Sass Github folders for consistency between website and Figma per Susan's suggestion, and consulted with her on questions.

Also discussed [Storybook option](https://swizec.com/blog/build-a-new-design-system-in-a-couple-afternoons/swizec/9444) (via Cynthia) for a 'living style guide' with Susan. Will consult with the developers about this more today.

**Comment by daniellen00** [comment]
Determined with Susan that Storybook and other automatic component generating programs like Styleguidist/Docz won't work for the site after all (mostly because they're React-focused).

**Comment by daniellen00** [comment]
Plan after weekly meeting discussion: I will work with @ye-susan to create a Figma file with all of the website components that will match up with a corresponding Github wiki page.

**Comment by daniellen00** [comment]
Progress: I had very limited time this week because of a final class project, but Susan and I discussed the logistics of creating a living style guide / component library page, and I did additional research. I'll have much more time this week to move forward with Susan.

**Comment by ye-susan** [comment]
Progress: Also limited time this week, but I've laid out some of the typography and components of the project page onto a demo Component page.

**Comment by alexandrastubbs** [comment]
Dependency: need to discuss designs across website currently between product and designers

**Comment by daniellen00** [comment]
Will discuss working with UX Designers on Style Guide after weekly website meeting.

**Comment by daniellen00** [comment]
Small to large components ('atoms' to 'organisms' in atomic design): https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1695%3A13302

**Comment by daniellen00** [comment]
Progress: Added class names for all of the components (via Inspect Element) for existing site pages

Blocks: Had limited time this week because of final project

Availability: Will have more time this week to organize everything.

**Comment by daniellen00** [comment]
Deliverable: List all of the final components and class names, with accompanying notes re: changes developers should make

**Comment by daniellen00** [comment]
Progress: Listed components and class names for comparison. Would like to discuss with @ye-susan before providing notes for recommended changes.

**Comment by daniellen00** [comment]
Progress: Finished 'CSS dump' for all components, continuing to work on recommendations for first phase of standardizing main site components (buttons, page card, etc). Will attend Developers meeting this Tuesday to finalize.

Blocks: Limited time this past week

**Comment by daniellex0** [comment]
Update: I didn't have enough time to work on this because of an unexpectedly slammed week, but will work on it this week and attend Dev meeting to discuss recommendations.

**Comment by daniellex0** [comment]
Progress: Currently getting into the weeds with naming conventions, but hopefully [survey](https://app.usabilityhub.com/do/7d339e2d2c8c/6585) and further discussion will provide direction. Will attend dev meeting again this week and try to lock down recommendations.

Blocks: limited time this past week, and fear of making wrong decisions for the future of the site!

**Comment by daniellex0** [comment]
Progress: Created classname rules for buttons with feedback from dev team- will wait to hear feedback at website team meeting before creating Github issue to make changes.

Blocks: limited time

**Comment by daniellex0** [comment]
Next steps: Add Button section to Style Guide file in Figma with all standards/class names. Then create Github issue to enact changes across the site.

**Comment by daniellex0** [comment]
Status: I didn't get to work on this because this insane election week took over my life and psyche, but I will finish it asap now that I am back to normal

**Comment by daniellex0** [comment]
Progress: Added Button Section to Style Guide in Figma.

Next steps: Do more testing on class changes, run any questions by Dev Meeting on Tue. Discuss Style Guide layout/Figma functionality with Yuiko. Continue onto other components.

**Comment by daniellex0** [comment]
Progress: Finished recommended changes to standardize buttons across site. Just have a few questions and should be ready to implement

Next steps: Move onto next components

**Comment by daniellex0** [comment]
Progress: Finished recommendations for standardizing page cards- just need to run some questions by team.

Next steps: Start implementing changes to buttons and page cards across site. Move onto standardizing heading sizes, and then finish component library with class names.

**Comment by daniellex0** [comment]
Progress: Implemented page card changes across site (after some struggle). Currently in the middle of standardizing the remaining page elements (headers, page card spacing, etc)

Next steps: Finish standardizing headers, page card spacing, and work on component library/class names. Make everything presentable and understandable.

**Comment by daniellex0** [comment]
Progress: Designed most of designer-facing component library / style guide, but still need to add more components and standardize more (typography, etc), plus finalize more class names.

Next Steps: Finish component library / style guide and wire it up on Figma, work on developer-facing design system documentation, implement changes on site.

**Comment by daniellex0** [comment]
Progress: Added more components to library, finalized typography and text rules, made progress on standardizing header/page layouts, started drafting explainer for developers and dev notes on Communities of Practice page.

Next Steps: Finish standardizing header/page layouts, add mobile/tablet versions of components, finalize class names for all components, wire up reusable components on Figma, finish developer-facing design system documentation,  implement changes on site.

**Comment by daniellex0** [comment]
Progress: Researched and designed standard UI grid system, learned how to wire up the Figma components from Yuiko, made progress with adding mobile elements to design system, made progress with standardizing header/page layouts including mobile, made progress on standardizing class names, continued drafting documentation/explanations.

Next steps: Finish header/page layouts standardization (mobile), finalize class names, wire up reusable components on Figma and clean Figma design system, finish developer-facing design system documentation, implement changes on site.

**Comment by daniellex0** [comment]
Progress: Researched developer-facing design system documentation, made progress with standardizing class names, , continued drafting documentation/explanations, continued finessing design system (type scale, colors, added option for dev-facing addition to Figma file, etc)

Next steps: Finalize developer-facing design system documentation, finalize header/page layouts standardization/templates, wire up reusable components on Figma and clean Figma design system, implement changes on site.

**Comment by daniellex0** [comment]
Progress: Added CSS and context screenshots to all components in Figma design system page, made progress with implementing button changes on site, continued drafting documentation/explanations, continued finessing design system

Next steps: Finish implementing button changes and push by Tue dev meeting, finalize developer-facing design system documentation, finalize header/page layouts standardization/templates, implement changes on site, wire up reusable components on Figma and clean Figma design system.

**Comment by daniellex0** [comment]
Progress: Created [pull request](https://github.com/hackforla/website/pull/944) to standardize buttons across the site, created [new wiki page](https://github.com/hackforla/website/wiki/Standardized-Components) called Standardized Components as dev-facing documentation about design system, worked on editing newer Figma pages to be consistent with design system, continued working on standardizing cards/finessing design system.

Next steps: Need to connect new wiki page with Site Architecture (elements section), finish standardizing new Figma pages + card components + typography for new developers on team, finalize header/page layouts standardization/templates, implement card standardization on site, wire up reusable components on Figma and clean Figma design system.

**Comment by pawan92** [comment]
@daniellex0 Could you update please
Progress:
Blockers:
Availability:
ETA:

**Comment by daniellex0** [comment]
**Progress:** Button standardization has been implemented across the site. Finished updating the new pages that are going into development for consistency with design system (& wrote guidelines for devs working on them), started creating issues for developers to standardize other pages on site with specific guidelines (Toolkit page), met with new designers to walk through design system and site layout, continued working on standardizing cards and layouts, worked on standardizing page card code across the site, connected new wiki page with Site Architecture wiki (elements section)

**Next Steps:** Implement page card standardization across site, meet with designers for Oskar's figma presentation, finalize standardizing headers/layouts/cards, finalize typography classes and implement, standardize all pages on site, wire up reusable components on Figma and edit all Figma files to be consistent with website/design standards.

**Comment by pawan92** [comment]
@daniellex0 Any updates?
Progress:
Blockers:
Availability:
ETA:

**Comment by daniellex0** [comment]
Progress: Close to finished with standardizing cards and page layouts (finished adding mobile), joined Oskar's presentation about Figma this week and I implemented Figma Styles based on design system/am starting to implement components, close to finished standardizing page card code across the site.

Next Steps: Finish implementing page card standardization across site, finish layouts and cards, standardize remaining new pages for devs, finish 'wiring up' design system via Figma components and auto layout, audit responsive typography on site, standardize all pages on site and Figma, work with a dev on a wiki about creating new page.

**Comment by daniellex0** [comment]
Progress: Audited responsive typography on website, started wiki for developers working on new pages, provided feedback to devs that are working on new pages and learned a lot based on their designs, especially about headers, for standardizing layouts (hoping to discuss with them after to get feedback). Met with Oskar to learn about auto layout and componentizing on Figma- extremely helpful. Nearly finished with standardizing cards and layouts, close to finished standardizing page card code across the site.

Blockers: Had limited time this week, but I'll have much more time this week.

Next Steps: Standardize responsive typography based on audit, finish wiki for developing new pages and get devs' feedback/edits/additions, work on implementing auto layout and componentize design system on Figma, finish implementing page card standardization across site, finish standardizing layouts and cards based on devs' work on new pages, standardize remaining new pages for devs, standardize all pages on site and Figma.

**Comment by daniellex0** [comment]
Progress: Standardized responsive typography based on audit, created issue (assigned to Martha) for creating new page template wiki and am continuing to work on the connected overall new page wiki, standardized designs of existing problematic pages on site and created issues with detailed instructions for devs to implement/standardize them, working on implementing auto layout and componentizing design system on Figma, working on implementing page card standardization across site based on feedback from developers working with these components, nearly finished standardizing layouts and cards based on devs' work on new pages.

Next Steps: finish wiki for developing new pages with Martha's template and get devs' feedback/edits/additions, finish implementing auto layout and componentizing design system/adding notes and documentation links for devs on Figma, continue discussing standard components/layouts with developers working on new pages and finish implementing page card standardization across site based on feedback, finish standardizing layouts and cards based on devs' work on new pages, finish standardizing all pages on site (typography classes, mobile layouts) and Figma.

**Comment by daniellex0** [comment]
Progress: Coordinating with Martha on her issue for creating new page template wiki (and continuing to work on the connected overall new page wiki), spoke with a professional product designer in charge of design system to get better understanding of industry standards in collaborating with devs, did a lot of research about Storybook and Zeroheight (but decided to back off, may not be right for this project, and just diffuses the 'single source of truth), continued standardizing designs of existing problematic pages on site creating issues with detailed instructions for devs to implement/standardize them, working on implementing auto layout and componentizing design system on Figma (attended Oskar's presentation), working on implementing page card standardization across site based on feedback from developers working with these components, nearly finished standardizing layouts and cards based on devs' work on new pages.

Next Steps: finish wiki for developing new pages with Martha's template and get devs' feedback, finish implementing auto layout and componentizing design system/adding notes and documentation links for devs on Figma, continue discussing standard components/layouts with developers working on new pages and finish implementing page card standardization across site based on feedback, finish standardizing layouts and cards based on devs' work on new pages, finish standardizing all pages on site (typography classes, mobile layouts) and Figma.

**Comment by daniellex0** [comment]
Progress: Coordinating with Martha on her issue for creating new page template wiki (and continuing to work on the connected overall new page wiki), did more research about Zeroheight (still not sure if this might be a good option- waiting to hear about Julia's experience with it at Home Unite Us)), continued standardizing designs of existing problematic pages on site creating issues with detailed instructions for devs to implement/standardize them, working on implementing auto layout and componentizing design system on Figma (attended Oskar's final presentation), working on implementing page card standardization across site based on feedback from developers working with these components, nearly finished standardizing layouts and cards based on devs' continuing work on new pages.

Next Steps: add documentation to everything (especially for new team members), finish wiki for developing new pages with Martha's template and get devs' feedback, finish implementing auto layout and componentizing design system/adding notes and documentation links for devs on Figma, finish implementing page card standardization across site based on feedback, finish standardizing layouts and cards based on devs' work on new pages, finish standardizing all pages on site (typography classes, mobile layouts) and Figma.

**Comment by daniellex0** [comment]
Progress: Continued standardizing designs of existing problematic pages on site by creating issues with detailed instructions for devs to implement/standardize them, Coordinating with Martha on her issue for creating new page template wiki (and continuing to work on the connected overall new page wiki), working on implementing auto layout and componentizing design system on Figma, working on implementing page card standardization across site based on feedback from developers working with these components, nearly finished standardizing layouts and cards based on devs' continuing work on new pages.

Next Steps: add documentation to everything (especially for new team members), finish wiki for developing new pages with Martha's template and get devs' feedback, finish implementing auto layout and componentizing design system/adding notes and documentation links for devs on Figma, finish implementing page card standardization across site based on feedback, finish standardizing layouts and cards based on devs' work on new pages, finish standardizing all pages on site (typography classes, mobile layouts) and Figma.

**Comment by tarang100** [comment]
Please provide an ETA as part of your status update

**Comment by daniellex0** [comment]
Progress: Started documentation and 'Start Here' section - as well as categorizing the design system more clearly - so that new designers can onboard more easily, added image guidelines, added standard screen sizes, working on implementing auto layout and componentizing design system on Figma, nearly finished standardizing layouts and cards based on devs' continuing work on new pages.

Next Steps: As soon as the Join Us page goes live I'll implement page card standardization across site, keep adding documentation for new team members, finish wiki for developing new pages with Martha's template, finish implementing auto layout and componentizing design system/adding notes and documentation links for devs on Figma, finish standardizing layouts and cards based on devs' work on new pages, finish standardizing all pages on site (typography classes) and Figma.

ETA: 3 weeks

**Comment by daniellex0** [comment]
Progress: Standardized page cards across the site- PR is in for review. Continued standardizing pages on site,  documentation and 'Start Here' section, working on implementing auto layout and componentizing design system on Figma, close to finished standardizing layouts and misc cards.

Next Steps: Keep adding documentation for new team members (training scheduled for 3/30), finish wiki for developing new pages with Martha's template, finish implementing auto layout and componentizing design system/adding notes and documentation links for devs on Figma, finish standardizing layouts / misc cards / typography classes, finish standardizing all pages on site and Figma.

ETA: 3 weeks

**Comment by daniellex0** [comment]
Progress: PR is still in for review for standardized page cards (will hopefully be approved this week). Continued standardizing pages on site, documentation and 'Start Here' section, working on implementing auto layout and componentizing design system on Figma, close to finished standardizing layouts and misc cards. Meeting with Oskar on Monday to go over componentizing on Figma, and with new UX team members on Tuesday to review documentation.

Next Steps: Keep adding documentation for new team members (training scheduled for 3/30), finish wiki for developing new pages with Martha's template, finish implementing auto layout and componentizing design system/adding notes and documentation links for devs on Figma, finish standardizing layouts / misc cards / typography classes, finish standardizing all pages on site and Figma.

ETA: 2 weeks

**Comment by daniellex0** [comment]
Progress: PR for standardizing page cards has been approved, and the changes are merged. Drafted documentation for new designers using the design system. Oskar componentized many of the reusable components on Figma. I added most of these components connected to the design system to all other pages on Figma. Continued standardizing pages on site. Working on implementing auto layout and finishing componentizing design system on Figma.

Next Steps: Focus on developer documentation- finish wiki for developing new pages with Martha's template, finish adding notes and documentation links for devs on Figma, finish standardizing layouts / misc cards / typography classes, finish implementing auto layout and componentizing design system.

ETA: 1.5 weeks

**Comment by daniellex0** [comment]
Progress: Finished documentation for new designers using the design system. Joined dev meeting to discuss standardizing CSS. Continued standardizing pages on site. Working on implementing auto layout and finishing componentizing design system on Figma.

Next Steps: Meeting this week with Candace and Qiqi to go over dev-facing documentation of design system. Finish wiki for developing new pages with Martha's template, finish adding notes and documentation links for devs on Figma, finish standardizing layouts / misc cards / typography classes, finish implementing auto layout and componentizing design system.

ETA: 1.5 weeks

**Comment by daniellex0** [comment]
Progress: Met with Qiqi and Candace to discuss working on dev documentation of the design system and next steps to finish componentizing, met with Oskar to continue working on implementing auto layout and finishing componentizing design system on Figma, continued adding remaining pieces to design system including new components from new pages.

Next Steps: Finish dev documentation, finish finish standardizing layouts / misc cards / typography classes, finish implementing auto layout and componentizing design system.

ETA: 2 weeks (there is more to the dev documentation than expected because other new reusable components will be added)

**Comment by daniellex0** [comment]
Progress: Met with Qiqi and Candace to continue dev documentation discussion, continued adding remaining pieces to design system including new components from new pages.

Next Steps: Finish dev documentation, finish standardizing layouts / misc cards / typography classes, finish implementing auto layout and componentizing design system.

ETA: 2 weeks (there is more to the dev documentation than expected because we are hoping to reorganize the wiki and test some automatic component generating tools)

**Comment by qiqicodes** [comment]
@daniellex0 Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by daniellex0** [comment]
Progress: Continued adding remaining pieces to design system including documentation.

Blockers: Waiting for Bonnie to return to ask about reworking the wiki, having a dedicated webpage for components, etc. Also busy schedules.

Next Steps: Finish dev documentation, finish standardizing layouts / misc cards / typography classes, finish implementing auto layout and componentizing design system.

ETA: 2 weeks

**Comment by daniellex0** [comment]
Progress: Standardized more mobile versions of pages, created dev issues that will help with wrapping up the design system, continued adding remaining pieces to design system including documentation.

Blockers: Waiting for dev agreement about reworking the wiki, having a dedicated webpage for components, etc. Also busy schedules.

Next Steps: Finish dev documentation, finish standardizing layouts / misc cards / typography classes, finish implementing auto layout and componentizing design system.

ETA: 2 weeks

**Comment by daniellex0** [comment]
Progress: Made progress with dev documentation of DS now that there us agreement about wiki redesign, standardized more mobile versions of pages on site, created more dev issues that will help with wrapping up the design system, continued adding remaining pieces to design system including documentation.

Blockers: Waiting for agreement about having a dedicated webpage for components, etc. 

Next Steps: Finish dev documentation, finish standardizing layouts / misc cards / typography classes, finish implementing auto layout and componentizing design system.

ETA: 2 weeks

**Comment by daniellex0** [comment]
Progress: Moving forward with wiki sidenav with expandable arrows, deciding not to use Storybook for dev documentation because it is too complicated to implement (even with React, not to mention without)- dedicates webpage is looking like best option, standardized more mobile versions of pages on site, created more dev issues that will help with wrapping up the design system, continued adding remaining pieces to design system including documentation.

Blockers: agreement about having a dedicated webpage for components

Next Steps: Finish dev documentation, finish standardizing layouts / misc cards / typography classes, finish implementing auto layout and componentizing design system.

ETA: 2 weeks

**Comment by daniellex0** [comment]
Progress: Got final feedback from devs about sidenav reorganization and their blessings to move forward with some edits; created issue for it to be implemented. Got approval from Bonnie to create a dedicated webpage for documenting reusable components. Standardized more mobile versions of pages on site, created more dev issues that will help with wrapping up the design system, continued adding remaining pieces to design system including documentation.

Next Steps: Design dedicated webpage for components, finish dev documentation, finish standardizing layouts / misc cards / typography classes, finish componentizing design system throughout the Figma.

ETA: 2 weeks

**Comment by daniellex0** [comment]
Progress: Ideating webpage for documenting components. Finalizing wiki sidebar before implementing this week with Candace. Helped create more dev issues that will help with wrapping up the design system, continued adding remaining pieces to design system.

Next Steps: Continue ideating and designing dedicated webpage for components, finish dev documentation, implement wiki sidebar this week with Candace, work on documentation in general with Candace this week, finish standardizing layouts / misc cards / typography classes, finish componentizing design system throughout the Figma.

ETA: 2 weeks

**Comment by daniellex0** [comment]
Progress: Wiki sidebar has gone live, and getting good feedback. Currently designing webpage for documenting components. Met with devs interested in implementing the component library webpage to give them the history and overview about the design system.

Next Steps: Finish designing dedicated webpage for components, finish dev documentation, finish standardizing layouts / misc cards / typography classes, finish componentizing design system throughout the Figma.

ETA: 2 weeks

**Comment by daniellex0** [comment]
Progress: Met with Kristin to discuss the designs for the component library webpage, and she designed a great layout to follow. I will implement the layout for the rest of the components early this week. 

Next Steps: Finish designing dedicated webpage for components, meet with devs to discuss rest of design system steps and implementing component library webpage, finish dev documentation, finish standardizing layouts / misc cards / typography classes, finish componentizing design system throughout the Figma.

ETA: 2 weeks

**Comment by daniellex0** [comment]
Progress: Met with developers to discuss and get feedback on the component library webpage, and how to implement it. I will implement the layout for the rest of the components early this week. Colors have been standardized into variables throughout the site in a current PR by Stanley. I made a first issue for standardizing heading classes as a test- once implementation looks good, I will make issues to standardize the rest.

Next Steps: Finish designing dedicated webpage for components by tonight, continue coordinating with devs to make sure they have what the need to implement component library webpage, finish dev documentation, finish standardizing layouts / misc cards / typography classes, finish componentizing design system throughout the Figma.

ETA: 2 weeks

**Comment by daniellex0** [comment]
Progress: Finished designing dedicated webpage for components and met with developers to discuss and get more feedback. Sarah is now in charge of implementing the designs, and once she builds the structure will assign others. 

Next Steps: Finish coordinating with devs to make sure they have what the need to implement component library webpage, finish dev documentation, and finish any loose ends in designer side on Figma.

ETA: 7/22
