### ISSUE TITLE
ER: Update Project Profile: 311 Data

### ISSUE THREAD

**Issue by rayneng** [hackforla/website#5786]
### Dependency
- [x] #5854
- [x] #5855 
- [x] #5856
- [x] #5860

### Project Name

311 Data

### Project Card URL

311-data.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Image?

NO

### Update the Technologies?

YES

### Technologies (maximum 26 characters)

- [x] React, Redux, Material-UI, DuckDb, HuggingFace, Github Pages, Mapbox

### Update the Partner(s)?

NO

### Update the Tools?

YES

### Tools

- [x] Google Suite, Figma, Github, Zoom, Observable

### Update GitHub Link?

No

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Eric Cho

- [x] Name: Prasadh Palanichamy

- [x] Name: Michael Criste

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Edwin Jue
GitHub Handle: edwinjue
Role: Engineering Lead
Slack Member ID: U03SUUZMFEV

- [x] Name: Holly Worthen
GitHub Handle: hworthen
Role: UX Research Lead
Slack Member ID: U03RPBE9DL6

- [x] Name: Ryan Chase
GitHub Handle: ryanfchase
Role: Project Manager, Developer
Slack Member ID: U052L9R6ETD

- [x] Name: Sanju Venugopal
GitHub Handle: sanjumv
Role: Product Manager
Slack Member ID: U05KFTD3AKA

- [x] Name: Anna Kim
GitHub Handle: annaseulgi
Role: UX Design Lead, Product Manager
Slack Member ID: U05JKGV3F4N

- [x] Name: Christopher Cotton
GitHub Handle: CottonChristopher
Role: Product Manager
Slack Member ID: U05MQ8CB2S1

- [x] Name: Bethlehem Berhane
GitHub Handle: bberhane
Role: Product Manager
Slack Member ID: U05QV9AKPNU

- [x] Name: Ahmed Awadalla
GitHub Handle: ahmedsalah0130
Role: Product Manager
Slack Member ID: U05Q80JEGG4

### Project Status

Active

**Comment by ExperimentsInHonesty** [comment]
@ryanfchase it looks like in this change request, you have indicted the following changes
- github url
- technologies
- Personnel changes

### github url change request
I deleted it because it was exactly the same as the old one, so no change needed
current GitHub link
https://github.com/hackforla/311-data
new GitHub link
https://github.com/hackforla/311-data

### technologies
I want to confirm that you don't need any of the old technolgies not included in your list
New tech
> React, Material-UI, DuckDb, HuggingFace, Github Pages

old tech (minus the ones above)
Redux, Mapbox, AWS, FastAPI, Redis, PostgreSQL, Prefect, Docker, Figma, Adobe CC, Miro

I am assuming you are still using figma, are you also still using docker, etc.?  Please edit the comment at the top to revise your technologies change request.  If unable to access the edit, please revise in a comment below.

### Personnel changes
We accept these changes and will start making issues for this.

**Comment by ExperimentsInHonesty** [comment]
@ryanfchase it looks like the hero image of the map inside the laptop got replaced with a version of the map with no laptop.  We can use that, but I don't recommend it.

old hero 
<img src="https://github.com/hackforla/website/blob/gh-pages/assets/images/projects/311data-beta.png?raw=true" width=600px>
new hero
<img src="https://user-images.githubusercontent.com/1448719/233575938-ce84a530-39ff-484e-a848-56121a40fe51.png" width=600px>

**Comment by ExperimentsInHonesty** [comment]
@ryanfchase We are going to go ahead with this issue and have you open a new issue for the hero change.  Since we have not received an updated image, I don't want to delay this issue any further.

**Comment by annaseulgi** [comment]
@bonniewolfe design team has been working on it since the meeting you mentioned it (I believe it was one or two Wednesdays ago). It is already a created issue under the 311 project board. We are hoping to be done with it soon!

https://github.com/hackforla/311-data/projects/10#card-90986428

**Comment by JessicaLucindaCheng** [comment]
Issue Writing
- Availability: 1.5 hour
- ETA: Monday, November 6, 2023

**Comment by annaseulgi** [comment]
@ryanfchase hero image + mockup


![geojango-maps-Z8UgB80_46w-unsplash (1) 2](https://github.com/hackforla/website/assets/140572118/33b24021-3b74-4614-8b44-c7263d4dd0d5)

![Screen Shot 2023-11-06 at 11 39 45 AM](https://github.com/hackforla/website/assets/140572118/ffa98ae4-f3b3-418c-a72c-ef6124f01bce)

**Comment by JessicaLucindaCheng** [comment]
All the issues have been written and added to the Dependency section.

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issues in the Dependency section have been merged, 
- [x] Review the ER and double check all the changes requested have been made
- [x] Move this ER to the UAT column
- [x] Contact the person who opened this ER to approve the changes on the [311 Data page](https://www.hackforla.org/projects/311-data).
- [x] Remove the `ready for dev lead` label and add a `ready for stakeholder` label
- [ ] Once the changes have been accepted by the person who opened this ER, close this ER and move this ER to QA column

**Comment by JessicaLucindaCheng** [comment]
@ryanfchase 
Please let us know if the changes made to the [311 Data page](https://www.hackforla.org/projects/311-data) match what you requested by adding a comment to this issue. Thank you.

Edit: Posted a message to Ryan in the 311 Data Slack channel asking about this on Monday, January 8, 2024.

**Comment by rayneng** [comment]
This is looking correct, thanks all!

**Comment by JessicaLucindaCheng** [comment]
@ pm
This issue is ready for you to UAT some more and QA.

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-pm The changes requested have already been accepted by the author of this issue. This issue is now ready for you to UAT and QA.
