### ISSUE TITLE
Updating NST's project card

### ISSUE THREAD

**Issue by ghost** [hackforla/website#579]
### Overview
Minor updates to NST project card

### Action Items

- [x]  Change spelling of 'Ben Swedlow' to 'Ben Swerdlow'
- [x] Add Ethan Hopkins to project leads as PM

**Comment by ExperimentsInHonesty** [comment]
@ethanh256 Can you post a screen shot of what the changes look like on your local copy here?

**Comment by ghost** [comment]
@ExperimentsInHonesty 


**Before changes:**
<img width="942" alt="Screen Shot 2020-06-20 at 5 25 25 PM" src="https://user-images.githubusercontent.com/58455740/85214040-0a81f780-b31b-11ea-9f7e-4e02a0085beb.png">

**After changes:**
<img width="935" alt="Screen Shot 2020-06-20 at 5 24 57 PM" src="https://user-images.githubusercontent.com/58455740/85214033-f76f2780-b31a-11ea-9bf8-74ae0447ae32.png">
