### ISSUE TITLE
Update Project Profile: Lucky Parking (Update Tools)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5791]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `tools` variable and change the following:

**From:**
```
  - Jupyter Notebooks
  - Google Colab
```
**To:**
```
  - pnpm
  - GitHub
  - Storybook
  - Google Colab
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
  - [x] the project's card on the Projects' page [^3]
- [ ] Once your pull request is merged, go to #4909 and
  - [ ] Check off this issue under the _Dependency_ section
  - [ ] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #4909
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking
[^3]: Projects page URL: https://www.hackforla.org/projects/

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 
- See this comment: https://github.com/hackforla/website/issues/4909#issuecomment-1784204383

**Comment by Anahisv23** [comment]
Availability: Nov 16 from 1 - 4PM
ETA: Nov 16 from 1- 4PM
