### ISSUE TITLE
Update Project Profile: Lucky Parking (Add Partner: Atwater Village)

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#5809]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to keep project information up to date so that visitors to the website can find accurate information.

### Action Items
- [x] In your IDE, open the `_projects/lucky-parking.md` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `partner` variable and change the following:

**From:**
```
partner: Department of Neighborhood Empowerment
```
**To:**
```
partner: Department of Neighborhood Empowerment, Atwater Village
```
- [x] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request:
  - [x] Lucky Parking page [^2]
  - [x] the project's card on the Projects' page [^3]
- [x] Once your pull request is merged, go to #4909 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #4909 to **Questions / In Review** column and uncheck the **Dependency label**.
    - <details>
        <summary>Click here to see how to uncheck the <b>Dependency label</b></summary>
        <img src="https://github.com/hackforla/website/assets/31293603/6f53f4d4-7d2c-45f8-8534-9936fc9adee8" width="300px">
      </details>

### Resources/Instructions
- This issue was initiated by #4909 and #5098
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Project detailed info page URL: https://www.hackforla.org/projects/lucky-parking
[^3]: Projects page URL: https://www.hackforla.org/projects/

**Comment by DakuwoN** [comment]
I am available everyday Monday - Friday after 3PM Eastern, and Saturday all day. I should have this done by Thursday.

**Comment by DakuwoN** [comment]
Can someone please move this over on the kanban board to in progress please? I forgot to do it and I am on my phone. If not I will do it when I get back to my PC. I'm a try to do it on my phone...

**Comment by ExperimentsInHonesty** [comment]
@DakuwoN I moved the issue for you.  Thanks for letting us know you needed some help.

**Comment by DakuwoN** [comment]
Thank you so much @ExperimentsInHonesty I will finish this issue tomorrow!

**Comment by DakuwoN** [comment]
Having problems getting Docker to work... it won't open, I reinstalled, etc etc.... 
I made the changes, but I can't get the before and after images because Docker is not opening correctly, been trying to debug for almost 2 hours, I will try again tomorrow.

**Comment by DakuwoN** [comment]
Yeah, if I can't get this Docker to work, I will unfortunately have to unassign myself from this.

**Comment by DakuwoN** [comment]
I completed the action items that I checked off. I can't preview or test what I've done because I am having Docker issues on my PC.
![dockerror](https://github.com/hackforla/website/assets/78394982/523e6db9-a42c-4811-b687-8e8937e335a8)
Each time I open Docker, I get this error, I tried everything.... Reset to Factory Settings, Re-install, followed the troubleshooting steps, this all worked before, now since they updated, I believe it does not so well anymore.

**Comment by roslynwythe** [comment]
@DakuwoN Some possible solutions are described in https://forums.docker.com/t/an-unexpected-error-was-encountered-while-executing-a-wsl-command/137525.  Also have you tried posting a question in #hfla-site?

**Comment by DakuwoN** [comment]
I believe I did a while ago but I will post one again.

**Comment by DakuwoN** [comment]
Thank you @roslynwythe 😊

**Comment by LRenDO** [comment]
Hi @DakuwoN! Thanks for working on this issue. If you're still working please add an update. If you're not able to continue to working on it, leave us a comment to let us know.  If we don't hear from you in the next week, we will remove you from the issue. Thanks!

**Comment by jtw007** [comment]
Availability: 1/24, 1/25 morning and afternoon
ETA: 1/25
