### ISSUE TITLE
ER: Communities of Practice information updates: UI/UX Community of Practice

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/website#5824]
### Dependency
- [x] #5874 

### Remove person(s) and info from CoP file?

NO

### If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:

Name:

### Add person(s) and info to CoP file?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Peter Gwon
Title: Co-lead
GitHub Handle: pogwon
Slack Member ID: U051F68PG2C

**Comment by ExperimentsInHonesty** [comment]
I approve this change.  This is ready for making an issue to implement.

**Comment by JessicaLucindaCheng** [comment]
Issue Writing
- Availability: 1.5 hour
- ETA: Monday, November 6, 2023

**Comment by JessicaLucindaCheng** [comment]
The issue has been written for the requested changes and added to the Dependency section of this issue.

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issue in the Dependency section has been merged, 
- [ ] Close this ER
- [ ] Move this ER to the UAT column
- [ ] Contact the person who opened this ER to approve the changes on the UI/UX section of the [Communities of Practice page](https://www.hackforla.org/communities-of-practice)
- [ ] Once the changes have been accepted by the person who opened this ER, move this ER to QA column

**Comment by JessicaLucindaCheng** [comment]
@Aparna1Gopal Please let us know if the changes made to the UI/UX section on the [Communities of Practice page](https://www.hackforla.org/communities-of-practice) match what you requested by adding a comment to this issue. Thank you.

**Comment by Aparna1Gopal** [comment]
@JessicaLucindaCheng Thank You! This looks good! The changes made to the UI/UX section on the Communities of Practice page matches the request.

**Comment by JessicaLucindaCheng** [comment]
@ product
This is ready for product to UAT and QA.

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-pm The changes requested have already been accepted by the author of this issue. This issue is now ready for you to UAT and QA.
