### ISSUE TITLE
ER: Communities of Practice information updates: Engineering

### ISSUE THREAD

**Issue by MicahBear** [hackforla/website#5825]
### Dependency
- [x] #5876

### Remove person(s) and info from CoP file?

YES

### If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:

Name: Harrison Katz

### Add person(s) and info to CoP file?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Zeke Arany-Lucas
Title: Co-Lead
GitHub Handle: [@ZekeAranyLucas](https://github.com/ZekeAranyLucas)
Slack Member ID: U062KFUJFU5

**Comment by ExperimentsInHonesty** [comment]
I approve this change. Sending to dev lead/merge team to make an issue for implementation,

**Comment by JessicaLucindaCheng** [comment]
Issue Writing
- Availability: 1.5 hour
- ETA: Monday, November 6, 2023

**Comment by JessicaLucindaCheng** [comment]
The issue for the requested changes is written and has been added to the Dependency section in this issue.

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issue in the Dependency section has been merged, 
- [x] Move this ER to the UAT column
- [x] Contact the author of this ER to approve the changes on the Engineering section of the [Communities of Practice page](https://www.hackforla.org/communities-of-practice)
- [x] Remove the `ready for dev lead` label and add a `ready for stakeholder` label
- [ ] Once the changes have been accepted by the person who opened this ER, close this ER and move this ER to the QA column

**Comment by JessicaLucindaCheng** [comment]
@MicahBear Please let us know if the changes made to the Engineering section on the [Communities of Practice page](https://www.hackforla.org/communities-of-practice) match what you requested by adding a comment to this issue. Thank you.

**Comment by MicahBear** [comment]
Looks great 👍🏼

**Comment by JessicaLucindaCheng** [comment]
@ product
This is ready for product to UAT and QA.

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-pm The changes requested have already been accepted by the author of this issue. This issue is now ready for you to UAT and QA.
