### ISSUE TITLE
Replace icon-slack-color.svg with icon-slack.svg in Resource Cards

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5826]
### Dependencies
- [x] #5819 

### Overview
We need to modify the liquid code in the Resource card section of the project files to include `_includes/svg/icon-slack.svg` instead of `_includes/svg/icon-slack-color.svg` and to separate the code that includes the github icon from the slack icon.

### Action Items
- [x] Open the file `_includes/resource-card.html` in your IDE and understand how the html/liquid code generates the list of resource card icons and links.
- [x] Replace
```
            {% if lowercaseName == 'github' or name == 'Slack' %}
                {% include {{ name | prepend: 'svg/icon-' | append: '-color.svg' | downcase }} %}
```
with
```
            {% if lowercaseName == 'github' %}
                {% include svg/icon-github-color.svg %}
            {% elsif lowercaseName == 'slack' %}    
                {% include svg/icon-slack.svg %}
```
- [x] Using docker to test the local changes on a sample project page (for example, `/projects/access-the-data`), confirming that the appearance and behavior of the Slack icon in the Resource Card section matches the appearance and behavior on the current website (for example, https://www.hackforla.org/projects/access-the-data) at all screen sizes.  Perform testing in Chrome, Firefox, and Safari browsers.  

### Resources/Instructions
- This issue is part of ER #5758
- [Introduction to Liquid Templating](https://shopify.github.io/liquid/basics/introduction/)
- [Sample Project Page - Access the Data](https://www.hackforla.org/projects/access-the-data)

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I moved this into the new issue review column because the dependency is resolved. Please add a ready for prioritization label if it's ready.

**Comment by aqandrew** [comment]
Availability for this week: 3-4 hours today, Wednesday, Thursday
My estimated ETA for completing this issue: 1 hour
