### ISSUE TITLE
Refactor communities of practice page to replace slack-self-invite.svg with icon-slack.svg 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5827]
### Overview
We need to store only a single Slack icon SVG file in the codebase, and use CSS to render the SVG in various colors throughout the website.  In this issue, we modify the Communities of Practice page, replacing the current image with the inline SVG `_includes/svg/icon-slack.svg`, and modifying the CSS with a fill color so that the rendered graphic matches the appearance of the current image. 

### Action Items
- [x] Open `pages/communities-of-practice.html` in your IDE and identify the 'img' tag with src `assets/images/communities-of-practice/slack-self-invite.svg`.  Also identify the rendered image in the current [Communities of Practice webpage](https://www.hackforla.org/communities-of-practice)
- [x]  Replace the `img` tag identified in the previous step with a liquid tag `{% include 'filename' %}` that will reference the file `_includes/svg/icon-slack.svg`.  Note that in the liquid include tag syntax, `filename` is relative to the `_includes` folder, so `_includes` should not be part of the filename.  
- [x] In `_sass/components/_communities-of-practice.scss`, within the specification for the class `header-self-invite--communities`, remove the nested specification for the  class `self-invite-img`
- [x] In `_sass/components/_communities-of-practice.scss`, within the specification for the class `header-self-invite--communities`, set the color of the icon by adding these lines:
```
svg.icon {
    path {
      fill: #fa114f;
    }
    margin-top: 15px;
    margin-right: 27px;
    width: 24px;
    height: 24px;
  }
```
- [x] The margins, height and width specified in the above CSS are only approximate and will require adjustment.  Using docker, view the local web page and adjust the styles as needed so that the appearance of the Slack icon matches the appearance in the current webpage. 

### Resources/Instructions
[Communities of Practice HTML](https://github.com/hackforla/website/blob/gh-pages/pages/communities-of-practice.html)
[Communities of Practice webpage](https://www.hackforla.org/communities-of-practice)
- This issue resulted from #5758

**Comment by aadilahmed** [comment]
i. Availability: Monday-Friday 9-5 pm
ii. ETA: 1/21 EOD
