### ISSUE TITLE
Refactor communities of practice page to replace slack-join-meeting-channel.svg with icon-slack.svg

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5829]
### Overview
We need to store only a single Slack icon SVG file in the codebase, and use CSS to render the SVG in various colors throughout the website.  In this issue, we modify the Communities of Practice page, replacing an `img` element with a liquid include tag referencing `_includes/svg/icon-slack.svg` and modifying CSS as needed to maintain the current appearance. 

### Action Items
- [x] Open `pages/communities-of-practice.html` in your IDE and identify the 'img' tag with src `assets/images/communities-of-practice/slack-join-meeting-channel.svg`, and identify the rendered image in the current [Communities of Practice webpage](https://www.hackforla.org/communities-of-practice)
- [x]  Replace the `img` tag identified in the previous step with a liquid tag `{% include 'filename' %}` that will reference the file `_includes/svg/icon-slack.svg`.  Note that in the liquid include tag syntax, `filename` is relative to the `_includes` folder, so `_includes` should not be part of the filename.  
- [x] The size and layout styles of the icon will require modification.  Use docker to view the local page and modify the CSS in `_sass/components/_communities-of-practice.scss` as needed so that the appearance of the icon in the local page matches the current webpage.  Confirm the appearance of the graphic and the behavior of the associated hyperlink is unchanged from the current webpage.  

### Resources/Instructions
[Communities of Practice HTML](https://github.com/hackforla/website/blob/gh-pages/pages/communities-of-practice.html)
[Communities of Practice webpage](https://www.hackforla.org/communities-of-practice)
- This issue resulted from #5758

**Comment by aadilahmed** [comment]
i. Availability: Monday-Friday 9-5 pm
ii. ETA: ~~11/10 EOD~~ 11/12 EOD
