### ISSUE TITLE
Refactor "Getting Started" page to replace slack-join-meeting-channel.svg with icon-slack.svg

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5830]
### Overview
We need to store only a single Slack icon SVG file in the codebase, and use CSS to render the SVG in various colors throughout the website.  In this issue, we modify the "Getting Started" page, replacing an `img` element with a liquid include tag referencing `_includes/svg/icon-slack.svg` and modifying CSS as needed to maintain the current appearance. 

### Action Items
- [x] Open `pages/getting-started.html` in your IDE and identify the 'img' tag with src `assets/images/getting-started/proj-4.png`, and identify the rendered image in the current [Getting Started webpage](https://www.hackforla.org/getting-started)
- [x]  Replace the `img` tag identified in the previous step with a liquid tag `{% include 'filename' %}` that will reference the file `_includes/svg/icon-slack.svg`.  Note that in the liquid include tag syntax, `filename` is relative to the `_includes` folder, so `_includes` should not be part of the filename.  
- [x] The size and layout styles of the icon will require modification.  Use docker to view the local page and modify the CSS in `_sass\components/_getting-started-page.scss` as needed so that the appearance of the icon in the local page matches the current webpage. 

### Resources/Instructions
[Getting Started HTML](https://github.com/hackforla/website/blob/gh-pages/pages/getting-started.html)
[Getting Started webpage](https://www.hackforla.org/getting-started)
- This issue resulted from #5758

**Comment by agutiernc** [comment]
Availability: ~11/04-06~ 11/11-11/12
ETA: EOD of ~11/06~ 11/12
