### ISSUE TITLE
Refactor GHA: move formatComment function to `github-actions/utils` 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5831]
### Dependencies
- [x] #5166 

### Overview
We need to move the function `formatComment` from `github-actions\trigger-issue\add-missing-labels-to-issues\post-labels-comment.js` to `github-actions/utils` in order to promote resuse of the function.  In subsequent issues, other github actions scripts will reference `formatComment` from the new folder location.  

### Action Items
- [x] move the declaration for the function `function formatComment({ replacementString, placeholderString, filePathToFormat, textToFormat })` from the file `github-actions\trigger-issue\add-missing-labels-to-issues\post-labels-comment.js` to a new file `github-actions/utils/format-comment.js`.  Also move the comment statements preceding the function declaration, that describe the function parameters, and move all of the statements comprising the function
- [x] In  `github-actions\trigger-issue\add-missing-labels-to-issues\post-labels-comment.js`, add a "require" statement to import the formatComment function from the new file.  For a sample statement see `github-actions/trigger-schedule/add-update-label-weekly/add-label.js`
- [ ] Perform testing in your fork of the website repository to ensure that the functionality of "Add Missing Labels to Issues" is unchanged.  Guidance on testing can be found in Hack for LA's GitHub Actions[^1] and in the comments of #5166 (**FILL IN LINK TO COMMENT **)

### Resources/Instructions
[Hack for LA's GitHub Actions](https://github.com/hackforla/website/wiki/Hack-for-LA's-GitHub-Actions)

**Comment by Chrisklangley** [comment]
Availability: M-F 5:30-9pm
ETA :  12/15/23 EOD

**Comment by roslynwythe** [comment]
This issue is being closed because a larger issue exists that includes the consolidation of `format-comment.js`.  See #3750
