### ISSUE TITLE
Add "redirections/" to "ignorePaths" array in cspell.json

### ISSUE THREAD

**Issue by freaky4wrld** [hackforla/website#5846]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to populate the spell check configuration file with file paths that should be excluded from spell checking, 

### Action Items
- [x] You must use VS Code as your local text editor and use the `Code Spell Checker` Extension for this issue,  The recommended installation method is to install Code Spell Checker directly from the VS Code text editor[^1].  The extension can also be installed via the VS Code Marketplace website[^2]
- [x] In VSCode, navigate to `cspell.json`
- [x] Add the path `redirections/`to the end of the array `ignorePaths`
- [x] Save 'cspell.json` and test the update by confirming that files in the specified path are not spell checked.  

### Merge Team
- [x] Release the dependency on this item in #5450
- [ ] When the last dependency is released, close #5450 as completed.  

### Resources/Instructions
[Introduction to JSON](https://www.json.org/json-en.html)
[Code Spell Checker](https://streetsidesoftware.com/vscode-spell-checker/)
This issue is part of #5450

[^1]: [Installing Code Spell Checker from the VS Code text editor](https://code.visualstudio.com/learn/get-started/extensions)
[^2]:[Code Spell Checker - VS Marketplace](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)

**Comment by jphamtv** [comment]
Hi @freaky4wrld, I'm adding a 'Draft' label as it looks like it's not complete yet. The 3rd Action Item needs to be completed, and the following prerequisite needs to be added to the top for all 'good first issues':

```
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
```

When ready for review, remove the 'Draft' label and add the 'ready for dev lead' label back. Thanks!

**Comment by patelbansi3009** [comment]
Availability for this week: Fully available
My estimated ETA for completing this issue: By the end of Friday 04/26/24
