### ISSUE TITLE
Create a Guide: Updating Team Pages on HFLA Site 

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#587]
### Overview

The team pages on the HFLA site get outdated relatively quickly with information changing frequently - leaders, meeting times, open roles, etc. We need a guide, to live in the 'toolkit hub', that provides detailed instructions for team leaders to feel empowered to update team pages on their own. 

### Action Items

- [ ] Content Collection
   - [ ] Gather instructions needed to create the following updates: 
       - [ ] Update leadership display 
       - [ ] Change meeting times 
       - [ ] Update team description
       - [ ] Change status (active, rebooting, onhold, completed)
       - [ ] Change links (link itself & link display)
       - [ ] Update resources
       - [ ] Change team name 

- [ ] UI/UX 
   - [ ] Updating team page guide 
       - [ ] Create mockups for desktop & mobile 
       - [ ] Collect feedback & revise accordingly
       - [ ] Get sign off
       - [ ] Hand off to dev
  - [ ] Add module to Toolkits page to drive to 'updating team page guide' 
       - [ ] Create mockups for desktop & mobile 
       - [ ] Collect feedback & revise accordingly
       - [ ] Get sign off
       - [ ] Hand off to dev

- [ ] Development
   - [ ] Implement final mockup for 'updating team page guide'
   - [ ] Implement final mockup for module on toolkit page 
   - [ ] Obtain code review
   
- [ ] This guide issue needs to be updated on our [Guide Tracking sheet](https://docs.google.com/spreadsheets/d/1omYkR_WeploNuOkF3Pqsg6DhIdej5SS2EBbG9FRefbA/edit?usp=sharing)

### Resources/Instructions

[Google doc for instruction/content collection](https://docs.google.com/document/d/1rI76ZpZzDYI3v3Pk9Ef_CqtXKFwj9Gi26X9pOlM_Ol0/edit?usp=sharing)

**Comment by alexandrastubbs** [comment]
@ExperimentsInHonesty new issue created for updating team pages. Collecting info in the linked google doc. Feel free to add in information/instruction or point me in the direction of where to find instructions on how to update these fields - I would be happy to learn some of this myself.

**Comment by ExperimentsInHonesty** [comment]
@alexandrastubbs the google doc must not be in the website google drive because its giving me an a request for access.  Please move the file.

**Comment by alexandrastubbs** [comment]
Apologies, @ExperimentsInHonesty - new link [here](https://docs.google.com/document/d/1rI76ZpZzDYI3v3Pk9Ef_CqtXKFwj9Gi26X9pOlM_Ol0/edit?usp=sharing) and updated above.

**Comment by pawan92** [comment]
@ExperimentsInHonesty has not worked on the issue. ETA unknown

**Comment by tarang100** [comment]
We are reconsidering making this because of the difficulty in monitoring updates

**Comment by IAgbaje** [comment]
- [ ] This guide issue needs to be updated on our [Guide Tracking sheet](https://docs.google.com/spreadsheets/d/1omYkR_WeploNuOkF3Pqsg6DhIdej5SS2EBbG9FRefbA/edit?usp=sharing)
