### ISSUE TITLE
Create project card for Civic Opportunity Project

### ISSUE THREAD

**Issue by rfambro2** [hackforla/website#588]
### Overview
Provide collateral for the HackforLA website

### Dependency
UI Designer Needed for Image hackforla/civic-opportunity#3 

### Action Items
- [x]   Gather items
  - [x]  600 x 400 image
     - [x]  Alt image text
  - [x] 1500 x 700 hero image (please do not put project title on hero image)
     - [x]  Alt image text
  - [x]  Name of project
  - [x]  A blurb about your project
  - [x]  Links (github, slack channel url, Testing Site, Live Site, etc.)
  - [x]  Any resources for a Getting Started link (a link to a wiki, readme(s) or both)
  - [x]  What you are looking for skills wise
  - [x]  Partner(s)
  - [x]  Location
  - [x]  Status
- [ ]   Add project Card to website

### Resources/Instructions
See project cards on the hackforla.org website for examples

**Comment by jbubar** [comment]
![Screen Shot 2020-07-09 at 2 12 48 AM](https://user-images.githubusercontent.com/53061723/87021666-57265900-c18a-11ea-830f-8344e4e43500.png)
![Screen Shot 2020-07-09 at 2 12 56 AM](https://user-images.githubusercontent.com/53061723/87021675-5988b300-c18a-11ea-97a9-0c4b7cf58e8b.png)
![Screen Shot 2020-07-09 at 2 13 06 AM](https://user-images.githubusercontent.com/53061723/87021681-5ab9e000-c18a-11ea-8e1c-d9ca9533c490.png)
![Screen Shot 2020-07-09 at 2 16 41 AM](https://user-images.githubusercontent.com/53061723/87021682-5b527680-c18a-11ea-859a-3c35b86a1ab1.png)

**Comment by jbubar** [comment]
Made the project card using the [template](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)
blocks: PDF icon, and the resources picture
Availability: Saturday evening

Questions: 
what do you think? 
Is the pdf icon ok?
What is the identification number for github api?
Would you like me to look into changing the img for the pdf under resources? (last img)

**Comment by jbubar** [comment]
@alexandrastubbs @ExperimentsInHonesty 
Who should I ask to review this?

**Comment by rfambro2** [comment]
@jbubar - This looks great! Here's a link to the [ReadMe](https://github.com/hackforla/civic-opportunity/blob/master/README.md) which may have a bit more updated information on it for your reference as well. I shot you a Slack message to address some of your other questions.

**Comment by ExperimentsInHonesty** [comment]
@jbubar - opps looks like we forgot to provide you with the leadership details. 
![Screen Shot 2020-07-09 at 9 18 32 PM](https://user-images.githubusercontent.com/37763229/87116064-c30bce80-c229-11ea-960a-45c162a069e6.png)

I'll gather that info and post it here as a comment and let you know.

**Comment by ExperimentsInHonesty** [comment]
- name: Ray Fambro
    role: Product Manager
    links:
      slack: 'https://app.slack.com/team/U015QPJS34M'
      github: 'https://github.com/rfambro2'
    picture: https://avatars.githubusercontent.com/rfambro2

**Comment by jbubar** [comment]
Made the changes requested.
- added the leadership details // thank you Bonnie
- found the repository id for github api
- changed the pdf icon to the one suggested by @rfambro2 

waiting on feedback from Ray before submitting a pull request. We are communicating on slack. 

I have time tonight to finish this. 
![Screen Shot 2020-07-11 at 6 36 31 PM](https://user-images.githubusercontent.com/53061723/87237050-0a1ece80-c3a6-11ea-83b2-efbcff511992.png)

**Comment by jbubar** [comment]
I have a couple of questions/thoughts about the PDF:
1. Could we add an icon to replace the link icon (blue arrow) for all links that end in ".pdf"?
2. if I click the PDF link, it automatically downloads. would it be possible to host it on the Hack4LA website?
3. is there an icon library that we use for the website? I just embedded a png img (green arrow) but I am not sure if that is the best way.

![Screen Shot 2020-07-11 at 6 31 38 PM](https://user-images.githubusercontent.com/53061723/87237111-e14b0900-c3a6-11ea-9a70-e2b8462b836d.png)

**Comment by ExperimentsInHonesty** [comment]
@jbubar unclear about why there is an icon next to the text.  That is not standard and specifically does not fit with the rest of our links as you can see from the picture you provided.  Then the icon above should either be a pdf logo or the image from the project card.  That decision will need be decided by product (me and alex) and design (Yuiko, Stella and Danielle) after we poll the whole development team for feedback since whatever gets decided affects all projects with this new type of asset.  We can do this at tomorrow’s meeting

**Comment by jbubar** [comment]
Ok. I understand now. Misunderstood the instructions.
![Screen Shot 2020-07-11 at 6 53 02 PM](https://user-images.githubusercontent.com/53061723/87237181-ec526900-c3a7-11ea-9e38-37d3d2c71274.png)

Here is what I originally put before talking to ray. 
![Screen Shot 2020-07-11 at 6 34 09 PM](https://user-images.githubusercontent.com/53061723/87237161-a5647380-c3a7-11ea-8e15-074a248cfaaa.png)
Happy to talk about it tomorrow

**Comment by ExperimentsInHonesty** [comment]
@jbubar i get why you thought it was the pm you should talk to.  But we need to maintain uniformity across all pages, and the pms have no idea what our style guide is, so they can’t answer those types of questions.  The note in parentheses was about using a pdf icon instead of the link icon.

**Comment by ExperimentsInHonesty** [comment]
And before you ask... we don’t actually have a style guide and we totally need one, and it’s in progress.

**Comment by rfambro2** [comment]
@jbubar @ExperimentsInHonesty - Sorry Josh. I was just trying to be proactive. Didn't mean to overstep. Thanks so much for your work on this!

**Comment by ExperimentsInHonesty** [comment]
@jbubar what is the status on finishing this up.  Where we left off in the meeting was that it was going to say Overview and show the project image (like the wiki does on this page)
![Screen Shot 2020-07-17 at 10 29 07 AM](https://user-images.githubusercontent.com/37763229/87814350-6d7e8580-c818-11ea-9857-f6ef37f851e1.png)
https://www.hackforla.org/projects/311-data

**Comment by jbubar** [comment]
![screencapture-0-0-0-0-4000-projects-civic-opportunity-2020-07-18-11_12_51](https://user-images.githubusercontent.com/53061723/87859142-b0f3f500-c8e7-11ea-8b4a-ee5b5a491e8c.png)
![Screen Shot 2020-07-18 at 11 14 28 AM](https://user-images.githubusercontent.com/53061723/87859183-134cf580-c8e8-11ea-8088-63e34b9721ff.png)

**Comment by jbubar** [comment]
Let me know if you want the 'Project One Page' in the getting started section.
The pull request that I opened does not have the project one page in the getting started section.

**Comment by alexandrastubbs** [comment]
Change 'Project One Page' to 'Overview'. Can include in Getting Started as well. 

Kian will review pull request.
