### ISSUE TITLE
Add new variable github-handle to member Jenn Wu in civic-tech-jobs.md 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5881]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team.  Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.  

### Action Items
- [x] Open the file `_projects/civic-tech-jobs.md` in the IDE
- [x] Replace:
```
  - name: Jenn Wu 
```
with
```
  - name: Jenn Wu 
    github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes.  The project webpage URL can be found below under Resources.   

### For Merge Team
- [x] Release the dependency for this issue in #5441.  If all the dependencies have been completed, close that issue.  

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template
https://jekyllrb.com/
Project Markdown File: https://github.com/hackforla/website/blob/gh-pages/_projects/civic-tech-jobs.md 
Project Webpage: https://www.hackforla.org/projects/civic-tech-jobs
- This issue is part of #5441

**Comment by kolhesatish** [comment]
I am starting to work on this issue.

**Comment by jonnyoe** [comment]
Availability: Saturday 2-6pm, Sunday 5pm-8pm, Monday 3pm-6:30pm
ETA: By Tuesday

**Comment by jonnyoe** [comment]
Hang on. I was signed up for DevOps and not the website so I'm not in the repository and maybe other things like the drive? This may take me longer unless I should re-assign myself

**Comment by aconstas** [comment]
Availability for this week: 2/21 (Wednesday) - 2/24 (Saturday)
My estimated ETA for completing this issue: 2/22 (Thursday)
