### ISSUE TITLE
Correction on 311-data.md page: Sanju Venugopal

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#5921]
### Overview
While reviewing an unrelated PR, I noticed that the entry for "Sanju Venugopal" misspelled their name. 

### Action Items

- [x] Change "Saju Venugopal" to "Sanju Venugopal"

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis ~Are you planning on working on this.  If yes, go ahead and move this to the in progress.  If not, please unassign yourself and add the `ready for prioritization` label~ Never mind.  I realized that you did a pr.
