### ISSUE TITLE
Update project.md file with new location format

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#593]
### Overview
We need to update the the "looking for" in each file 

### Action Items
- [x] Edit every project markdown file (actually a yaml file but they have .md file extension) 

Currently formatted this way
``` 
location: Downtown LA, Remote
```

Change the format to this
```
location:
  - Downtown LA
  - Remote
```
  - [x] Make sure to add Remote to all projects with the status "Active"

- [x] update the Template in the wiki
- [x] submit PR with the words Fixes [followed by the # and then this issue number].  I recommend asking for Susan as your reviewer since she is the one waiting on the change.
- [x] put a comment on #593 when the pull request is approved to let Susan know the dependency is released. 

### Resources/Instructions
[Template-of-a-project.md-file in the wiki](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)
[location of project files](https://github.com/hackforla/website/tree/gh-pages/_projects) or /_projects in your local copy

**Comment by Adeola-Adesoba** [comment]
Hi, can I help with the new location format?

**Comment by efrenmarin45** [comment]
> Hi, can I help with the new location format?

Thank you for the offer, but I finished this up earlier in the day but was having issues with my github authentication to push. All good now though.
