### ISSUE TITLE
Review Software Development Lifecycle 

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#594]
### Overview
Review the [PDF](https://drive.google.com/file/d/1emxhYv9N6KuCVrG-gnqkqHdGnjhm_Qvb/view) of the HFLA Software Development Lifecycle with the site development team and collect feedback. 

### Action Items
Once reviewed, update issue #178

**Comment by ExperimentsInHonesty** [comment]
Will not be worked on here.  Have created a new issue on Product Management repo
