### ISSUE TITLE
ER: Sponsor section on About Us page is hardcoded 

### ISSUE THREAD

**Issue by djbradleyii** [hackforla/website#5948]
### Dependency
- #6819

### Emergent Requirement - Problem
The Sponsor section on the Home page uses a separate data source (_includes/sponsors.html) 
There is also this data source which isn't being used within the app (https://github.com/hackforla/website/blob/gh-pages/_data/internal/sponsors.yml)

### Issue you discovered this emergent requirement in
- #5511

### Date discovered 
11/28/23

### Did you have to do something temporarily
- [ ] YES
- [ X] NO

### Who was involved
@roslynwythe @djbradleyii 

### What happens if this is not addressed
Different sources of truth will make updates confusing

### Resources
Webpage(s): https://www.hackforla.org/, https://www.hackforla.org/about/#sponsors

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe  will decide what needs to be done, and add that decision to potential solutions draft. 
then this issue can go into the ER to make issues column, level 2 as a medium issue.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty Data stored in https://github.com/hackforla/website/blob/gh-pages/_data/internal/sponsors.yml would be more likely to be reusable in various contexts so let us consider if that data structure is sufficient:
```
- name: Los Angeles Cleantech Incubator
  link: https://laincubator.org/
  img_url: /assets/images/sponsors/laci.svg
  position: 2
``` 
If so, I'll create issues to update the homepage and the About Us sponsor card

**Comment by ExperimentsInHonesty** [comment]
- This issue is being replaced by #6819
