### ISSUE TITLE
Unable to join Slack Engineering  and  #tdm-calculator channel 

### ISSUE THREAD

**Issue by nelsonuprety1** [hackforla/website#5949]
### Overview

The slack channel link for Engineering and tdm-calculator is not letting me join the chanell

### Action Items

I am unable to join the 2 channels that i have mentioned in the title. Is it possible to mention proper link which will help me to join the channel. [](url)
<img width="1440" alt="Screenshot 2023-11-29 at 18 12 39" src="https://github.com/hackforla/website/assets/25173636/307f9115-1b0f-4b28-b7d2-7690315a49a6">

<img width="1440" alt="Screenshot 2023-11-29 at 18 13 49" src="https://github.com/hackforla/website/assets/25173636/e202f46c-8876-4954-bebf-996476c7b1f9">

<img width="748" alt="Screenshot 2023-11-29 at 18 14 10" src="https://github.com/hackforla/website/assets/25173636/a2e7033a-440e-4608-9f44-79f9b7e5b34e">

These are some of the images which might help. 
Thank You.

### Resources/Instructions

Please provide proper links so that i can join or if possible please invite me to the slack channel.

**Comment by JessicaLucindaCheng** [comment]
@nelsonuprety1 I'm sorry you are having trouble joining our Slack channels. I see you are not a member of Hack for LA yet (it's free to join) and we usually send out an invite to Hack for LA's Slack during our onboarding sessions. Have you attended one of our onboarding sessions yet? If not, you can sign up for one of our upcoming onboarding sessions here: https://www.meetup.com/hackforla/events

**Comment by nelsonuprety1** [comment]
Hi @JessicaLucindaCheng thank you for the reply. Yes, I don't think I am a member of Hack for LA and I also haven't attended the onboarding sessions. Today I am going to join the LinkedIn onboarding session. Thank you.

**Comment by JessicaLucindaCheng** [comment]
@nelsonuprety1 Hack for LA's next onboarding is in January; the onboardings are titled, "Hack for LA Civic Tech Volunteer Intro and ONBOARDING (online)" on Meetup.

**Comment by nelsonuprety1** [comment]
@JessicaLucindaCheng so that means I am unable to join the slack channel to contribute till January?

**Comment by JessicaLucindaCheng** [comment]
@nelsonuprety1 Yes. Hack for LA takes December off, except for workshops sometimes and the holiday party.

**Comment by samuelkhong** [comment]
Looks like the question is resolved.

**Comment by ExperimentsInHonesty** [comment]
@samuelkhong Thanks for brining this challenge that perspective Hack for LA members are experiencing when they click on slack links on our website.

We have opened an Emergent Request to address the issue. 
- https://github.com/hackforla/website/issues/6129
