### ISSUE TITLE
Create sitemap for HfLA site

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#595]
### Overview
We need a sitemap so that we can see what pages we have and where we are adding new ones.

### Action Items
- [x] Product
   - [x] Define the pages and their status for the sitemap
- [x] Design
- [x] Create sitemap in figma for 
   - [x] pages
      - [x] Homepage (live
      - [x] Getting Started (live)
      - [x] ToolKit (in design)
      - [x] Guide: 2FA (in development)
      - [x] Guide: Survey Reporting Dashboard Guide (in development)
      - [x] Guide: Create a Kanban Project Board from our Template (ready for ideation)
      - [x] Guide: Using Kanban Project Boards for Team Effectiveness (ideation)
      - [x] Projects (ideation)
      - [x] Project Homepages (live)
      - [x] Metrics Dashboard (in development)
      - [x] HackNight page (in development)
      - [x] Wins page (in design)
      - [x] Credits page (ready for development)
  - [x] links (internal)
     - [x] connect 
     - [x] press 
  - [x] links (external)
     - [x] donate 
     - [x] meetup 
     - [x] slack
     - [x] facebook
     - [x] github
     - [x] medium
- [x] Product
   - [x] Refine
   - [x] Signoff
- [x] Development
   - [x] Create framework for page using this design https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3164%3A18
      -  The site map image is an image that should be clickable to see a larger version. Do not remake the content of the image.  It is designed to be able to be swapped out when the site is updated.

#### page status types:
1. ready for ideation
2. ideation
 3. ready for design
4. in design
5. ready for development
6. in development
7. live
8. live and [one of the status types above]

####  link status types:
1. link (internal)
2. link (external)

**Comment by ExperimentsInHonesty** [comment]
posted this in slack to @yuikomajima 
ok, I know this is going to sound crazy.. but while looking at this I couldn’t help but see how this could easily be made into a collection and actually display on the website.  Meaning, if you designed out all the different ways that the images could display and their parent id, it could be built automatically 
```
name of page:
short description of page: (if we want that)
status:
parent page:
```

**Comment by yuikomajima** [comment]
OK @ExperimentsInHonesty I have a much more simplified one right now here: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1558%3A13110

We can make it the way you had mentioned, but just so we are on the same page, is this sitemap's purpose for our internal team to discuss what needs to be designed, or to be put on the website so users can navigate to pages?

**Comment by ExperimentsInHonesty** [comment]
[discussion via slack between @yuikomajima and @ExperimentsInHonesty](https://docs.google.com/document/d/17FRUaj-gcT-2WmOELKK-8t371KBzy6OavqsF4vTt8xc/edit) for those who want to read the whole thing.

Summary of discussion:
@yuikomajima will create a sitemap in figma that conveys the status types above and will also make a prototype of what that might look like if displayed dynamically on the site at some point.

#### The potential benefits of public version are:
- visitors can easily see where the website project is going (potential new team members, supporters of org, other brigades, etc).
- project teams will be able to see where the site that represents them is headed, providing opportunity to suggest more valued priorities, or approval for current prioritization.

**Comment by yuikomajima** [comment]
I updated the sitemap accordingly: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1558%3A13110

**Comment by alexandrastubbs** [comment]
@yuikomajima can we make the following updates to the sitemap: 

1. New additions to the About Us page 
2. Reflect that the new About Us page will have the Connect 
3. Remove Connect from menu
4. Add each of the sub-sections (team meeting times, events, locations) to the Hack Nights section

**Comment by alexandrastubbs** [comment]
@yuikomajima please provide an update on this issue

1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by ExperimentsInHonesty** [comment]
@yuikomajima I updated the site map with all the guides that were not listed and a current menu and future menu.  I also added utilized a version of the horizontal split card on the live pages that are changing and the idea that you had to put the status of the cards on the card to distinguish them from the other stages where the site is not live.
https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3129%3A20734

I see that you added some new color ways, I am curious to see how they would look on the sitemap.

**Comment by alexandrastubbs** [comment]
@ExperimentsInHonesty updated the menu (this should not change any of the page titles on the pages themselves, only the way they appear on the menu)

**Comment by alexandrastubbs** [comment]
We have done a first draft of the site map page (https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3164%3A18) which is where this will live. 

Can you replace the header image and the images/icons for each section as needed? @yuikomajima

**Comment by yuikomajima** [comment]
Updated - https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/?node-id=3164%3A18

**Comment by ExperimentsInHonesty** [comment]
@yuikomajima This is perfect! I am moving this to development.

**Comment by alexandrastubbs** [comment]
@yuikomajima we attempted to add the donate button to the site map as it looks on site (a button), but in doing so we realized that we don't know where the site map that is reflected on the site map page is coming from. It is not the same one that you see [here](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3148%3A74). It would be best if we could have the most up to date site map reflected in that Figma link so that we have one source of truth. Can you update it as needed and then drop it in the [mock of sitemap page figma file](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3164%3A18)?

**Comment by yuikomajima** [comment]
Hmm I think I actually never updated the sitemap and left to what was created before. I just updated it to [the sitemap](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3374%3A20867) dated 10/22/2020bordered in red. 

[Figma file to sitemap page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3374%3A21124)

**Comment by ExperimentsInHonesty** [comment]
@yuikomajima ok thanks!  This looks perfect.  I am sending this off to development.

**Comment by ItsLaszlo** [comment]
1. Progress: Currently have the layout of the page done. Need to add the css
2. Blockers: None as of yet.
4. ETA: By next Sunday meeting 1/31.

**Comment by pawan92** [comment]
@martham0 Could you please update:
Progress:
Blockers:
Availability:
ETA:

**Comment by ItsLaszlo** [comment]
Progress: The sitemap page has been finished. Need someone to review.
ETA: 2/2

**Comment by ItsLaszlo** [comment]
The page is done here is a preview of the site.

Web View:
![Screen Shot 2021-02-09 at 7 08 59 PM](https://user-images.githubusercontent.com/69860036/107459294-b8405180-6b0a-11eb-9ed2-9d49aac12921.png)
![Screen Shot 2021-02-09 at 7 09 13 PM](https://user-images.githubusercontent.com/69860036/107459301-ba0a1500-6b0a-11eb-9cdf-445744e94e5a.png)
![Screen Shot 2021-02-09 at 7 09 33 PM](https://user-images.githubusercontent.com/69860036/107459305-bbd3d880-6b0a-11eb-9cab-dbdc93bdca06.png)

Mobile View:

![Screen Shot 2021-02-09 at 7 10 48 PM](https://user-images.githubusercontent.com/69860036/107459360-de65f180-6b0a-11eb-9915-b3afd57246dd.png)
![Screen Shot 2021-02-09 at 7 10 58 PM](https://user-images.githubusercontent.com/69860036/107459365-e0c84b80-6b0a-11eb-95c5-be34b7b3f176.png)
![Screen Shot 2021-02-09 at 7 11 05 PM](https://user-images.githubusercontent.com/69860036/107459369-e2920f00-6b0a-11eb-8408-80b45d93e935.png)
