### ISSUE TITLE
ER: Remove Code for America mentions from Hack for LA website

### ISSUE THREAD

**Issue by Rabia2219** [hackforla/website#5953]
### Dependency
- #5968
- #5958
- #5959
- #5960
- #5963
- #5965
- #5972
- #6242
- #6199

### Emergent Requirement - Problem

We need to remove any leftover Code for America mentions from the Hack for LA website so that they no longer appear as our fiscal sponsor.

### Issue you discovered this emergent requirement in
- None. Reviewing for Bonnie

### Date discovered 
2023-12-01

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty @Rabia2219 

### What happens if this is not addressed
People will still think we are associated with Code for America and not Civic Tech Structure, which makes it hard to fundraise, and we committed to removing their info from our site, so it's a compliance issue.

#### Items to change
- [redirections/codeforamerica.md](https://github.com/hackforla/website/blob/gh-pages/redirections/codeforamerica.md?plain=1#L4) - unknown what this does or why we have it.  Look into it.
- [pages/privacy-policy.html](https://github.com/hackforla/website/blob/gh-pages/pages/privacy-policy.html#L15) - fix this reference to say Civic Tech Structure, Inc.
  ```
  HackforLA.org is an informational website managed by Hack for LA which is a project of Code for America Labs, Inc. ("Code for America", "we", "us", "our").
  ```
- [pages/about.html](https://github.com/hackforla/website/blob/gh-pages/pages/about.html#L14) - remove reference on https://www.hackforla.org/about/ page 
   ```
   Hack for LA is a project of [Code for America](https://www.codeforamerica.org/) and its official Los Angeles chapter. 
   ```
- [assets/images/sponsors/code-for-america.svg](https://github.com/hackforla/website/blob/gh-pages/assets/images/sponsors/code-for-america.svg?plain=1) - in use on sponsors partners include .yml files
   - [_data/internal/partners.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/partners.yml#L6) - uses code-for-america.svg
   - [_data/internal/sponsors.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/sponsors.yml#L4) - uses code-for-america.svg
- [pages/join-us.html](https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html#L20) - Addressed by #5934
- [_includes/about-page/about-card-sponsors.html](https://github.com/hackforla/website/blob/gh-pages/_includes/about-page/about-card-sponsors.html#L4) - This is the alt text for the image used in the mobile navigation and it needs to be changed from 
   ```
    alt="Make your donation for Hack for LA Brigade on codeforamerica.org/donate. Choose the amount and select the payment frequency, then enter 'Hack for LA' under 'if your donation is for a Brigade, please select the Brigade Name(Optional)'."></span>Sponsors
   ```
   to
   ```
   alt=""
   ```
- [_config.yml](https://github.com/hackforla/website/blob/gh-pages/_config.yml#L25) - change from
   ```
   # which then redirects to `github.com/hackforla/website` and `https://www.codeforamerica.org/donate` respecitively
   ```
   to
   ```
   # which then redirects to `github.com/hackforla/website` and `https://www.hackforla/donate` respectively
   ``` 
- [github-actions/trigger-schedule/github-data/get-project-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/github-data/get-project-data.js#L11) - this references `https://github.com/codeforamerica/brigade-playbook`, and the url has changed to `https://github.com/hackforla/bop`, not sure what else will need to be changed.
- [_projects/brigade-organizers-playbook.md](https://github.com/hackforla/website/blob/gh-pages/_projects/brigade-organizers-playbook.md?plain=1#L47) - revise to point to the correct wiki.  Change
   ```
   url: 'https://github.com/codeforamerica/brigade-playbook/wiki'
   ```
   to
   ```
   url: 'https://github.com/hackforla/bop/wiki'
   ```
#### Items that are fine the way they are
- [_includes/code-of-conduct-page/CODEOFCONDUCT.md](https://github.com/hackforla/website/blob/gh-pages/_includes/code-of-conduct-page/CODEOFCONDUCT.md?plain=1#L2) - this is fine, it just mentions CfA as being the place where we forked the Code of Conduct from.
- [_includes/events-page/header-container-content.html](https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/header-container-content.html#L6) - this is fine, it references our being inspired by CfA.
   - [_data/internal/accomplishments.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/accomplishments.yml#L2) - this is fine, it refers to an event in the past.

### Recommended Action Items
- [x] Make a new issues
- [ ] Discuss with team
- [ ] Let a Team Lead know

**Comment by roslynwythe** [comment]
Regarding [github-actions/trigger-schedule/github-data/get-project-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/github-data/get-project-data.js#L11), the code works because although the repo url has changed (and redirected), the id is unchanged.  We have two options: 1) just to avoid confusion we could edit the comment in the js to reflect the new url, or 2) if we could tag https://github.com/hackforla/BOP then it could be removed from the untaggedRepoIds array.

**Comment by ExperimentsInHonesty** [comment]
We need to keep the Code for America logo around, so that we can add it back to the site under some header which indicates former partners/sponsors.  
- [x] make another issue to move the logo /assets/images/sponsors/code-for-america.svg](https://github.com/hackforla/website/blob/gh-pages/assets/images/sponsors/code-for-america.svg) to another file folder for former sponsors/partners 
- [x] make a one new issue to create a yml file that has the following data and put it in that file folder
   ```
   - name: Code for America
     image: /assets/images/sponsors/code-for-america.svg
     link: https://www.codeforamerica.org/
   ```
- [ ] new ER needs to get made for design to figure out where to put this content and that ER should contain links to the image (logo) and data (yml file) in our codebase that we will later reuse.

**Comment by roslynwythe** [comment]
> We need to keep the Code for America logo around, so that we can add it back to the site under some header which indicates former partners/sponsors.
> 
> * [x]  make another issue to move the logo /assets/images/sponsors/code-for-america.svg](https://github.com/hackforla/website/blob/gh-pages/assets/images/sponsors/code-for-america.svg) to another file folder for former sponsors/partners
> * [x]  make a one new issue to create a yml file that has the following data and put it in that file folder
>   ```
>   - name: Code for America
>     image: /assets/images/sponsors/code-for-america.svg
>     link: https://www.codeforamerica.org/
>   ```
> * [ ]  new ER needs to get made for design to figure out where to put this content and that ER should contain links to the image (logo) and data (yml file) in our codebase that we will later reuse.

@ExperimentsInHonesty The new folder you describe will contain both images files and data (yml) files pertaining to former sponsors/partners.  I'm not certain where that folder should be located.  Also I assume that in the yml file, the path to code-for-america.svg should reflect the new location.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I wasn't thinking that the files would be in the same folder.  I was thinking they would be here
assets/images/former-sponsors-partners/code-for-america.svg (new folder)
website/_data/internal/former-sponsors-partners.yml (new file)

**Comment by roslynwythe** [comment]
- See #6242
- See #6199

**Comment by ExperimentsInHonesty** [comment]
## remaining items on this ER


### Make two issues
- [ ] make an issue to remove Code for America from this wiki page https://github.com/hackforla/website/wiki/Introduction-to-the-Project
- [ ] make an ER needs to get design to figure out where to put the former part partner/sponsor content and that ER should contain links to the image (logo) and data (yml file) in our codebase that we will later reuse. which can be found in 
   - [ ] https://github.com/hackforla/website/issues/6242
   - [ ] https://github.com/hackforla/website/issues/6199

### Add the links to this ER and wrap it up
- [ ] provide the links to the issues by editing this comment to add the links
- [ ] close this ER

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I am ready to prioritize this (into the issue making column), if you agree, add a ready for prioritization label for me.  If not, please leave a comment

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I was just going back over this to get it ready and noticed this comment.  How did we solve?

https://github.com/hackforla/website/issues/5953#issuecomment-1839740454

> Regarding [github-actions/trigger-schedule/github-data/get-project-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/github-data/get-project-data.js#L11), the code works because although the repo url has changed (and redirected), the id is unchanged. We have two options: 1) just to avoid confusion we could edit the comment in the js to reflect the new url, or 2) if we could tag https://github.com/hackforla/BOP then it could be removed from the untaggedRepoIds array.

**Comment by roslynwythe** [comment]
- @ExperimentsInHonesty Thank you for tagging the [BoP repo](https://github.com/hackforla/BOP).  I created issue #6786 to clean up get-project-data.js.
