### ISSUE TITLE
Remove Code for America from Privacy Policy intro

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5958]
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to remove mention of Code for America from the Privacy Policy

### Action Items
- [x] In your local IDE, navigate to `pages/privacy-policy.html`
- [x] Replace:
 ```
HackforLA.org is an informational website managed by Hack for LA which is a project of Code for America Labs, Inc. ("Code for America", "we", "us", "our").
``` 
with
```
HackforLA.org is an informational website managed by Civic Tech Structure, Inc.
```
- [x] Using Docker, confirm that the change has been made on the Privacy Policy page, and the rest of the page is unchanged.  

### Resources/Instructions
1. Privacy Policy webpage: https://www.hackforla.org/privacy-policy
2. This issue was created from #5953

**Comment by eshan-one** [comment]
Hi @roslynwythe Can you assign me this issue? I would like to work on it!

**Comment by t-will-gillis** [comment]
HI @sornekian As mentioned on the previous issue, you have already completed several `good first issue`s - please proceed with `Complexity: Small`

**Comment by iancooperman** [comment]
Availability for this week: Sat-Sun 10am-9pm, Mon-Fri 5pm-9pm
My estimated ETA for completing this issue: Monday, 1/8/2024.
