### ISSUE TITLE
Remove Code for America from About Us intro

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5959]
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to replace the mention of Code for America from the "About Us" page

### Action Items
- [x] In your local IDE, navigate to `pages/about.html`
- [x] replace these lines:
 ```
        <p class="sub-p">
            Hack for LA is a project of <a class="header-link--about" href="https://www.codeforamerica.org/" target="_blank">Code for America</a> and its official Los Angeles chapter.
        </p>
``` 
- [x] with:
 ```
        <p class="sub-p">
            Hack for LA is a project of <a class="header-link--about" href="https://www.civictechstructure.org/" target="_blank">Civic Tech Structure</a>.
        </p>
``` 
- [x] Using Docker, confirm that the change has been made on the "About Us" page, and the rest of the page is unchanged.  

### Resources/Instructions
1. "About Us" webpage: https://www.hackforla.org/about
2. This issue was created from #5953

**Comment by ExperimentsInHonesty** [comment]
I revised the instruct ructions to replace/revise the text rather than remove it

**Comment by nelsonuprety1** [comment]
Hello @roslynwythe i have created a pull request #6070 fixing this issue. Please kindly do check it. Thank You.
