### ISSUE TITLE
Remove mention of Code for America from alt text on About Us page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5963]
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to remove mention of Code for America from the alt text attribute on the "Sponsors" icon, which appears in mobile view on the left side of the Sponsors card when the card is collapsed.  

### Action Items
- [x] In your IDE, navigate to `_includes/about-page/about-card-sponsors.html`
- [x] Locate the img tag with src `/assets/images/about/section-header-elements/sponsors.svg` and change the alt attribute to: 
 ```
alt=""
``` 
- [x] Using Docker, confirm that the alt text has been updated and that otherwise, the appearance and behavior of the page is unchanged in mobile and full screen sizes.  See the Resources section below for screenshot and link.  

### Resources/Instructions
<details><summary>"Sponsors" icon in mobile view</summary>

![image](https://github.com/hackforla/website/assets/5314153/72bc9835-8a50-4689-9257-cb0e9e70898f)

</details> 

- "About Us" webpage: https://www.hackforla.org/about
- This issue was created from #5953

**Comment by YolandaHaynes** [comment]
Availability: M-F 6-9pm pst
ETA: 01/07/2024
