### ISSUE TITLE
replace Code for America link in comment in _config.yml

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5965]
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to remove the Code for America link from a comment in _config.yml in order to avoid confusion. 

### Action Items
- [x] In your local IDE, navigate to `_config.yml`
- [x] Replace:
 ```
# which then redirects to `github.com/hackforla/website` and `https://www.codeforamerica.org/donate` respecitively
``` 
with
```
# which then redirects to `github.com/hackforla/website` and `https://www.hackforla/donate` respectively
``` 

### Resources/Instructions
- This issue was created from #5953

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty Please advise what the `Feature` label should be applied

**Comment by Deepkha** [comment]
Can you please review my pr and merge it?

**Comment by anthonypz** [comment]
Availability for this week: 12-4 PM PST, Mon-Fri
My estimated ETA for completing this issue: End of Day 01/08/2024
