### ISSUE TITLE
update "/codeforamerica" redirect to point to Hfla donate page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5968]
### Prerequisites

1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview
We need to update the redirect so that requests for https://www.hackforla.org/codeforamerica/ are redirected to https://www.hackforla.org/donate

### Action Items
- [x] In your local IDE, navigate to `redirections/codeforamerica.md`
- [x] Replace:
 ```
# https://www.hackforla.org/codeforamerica/ redirects to -> https://www.codeforamerica.org/donate
layout: redirect
title: CodeForAmerica
permalink: /codeforamerica/
redirect_to: https://www.codeforamerica.org/donate
``` 
with
```
# https://www.hackforla.org/codeforamerica/ redirects to -> https://www.hackforla.org/donate
layout: redirect
title: CodeForAmerica
permalink: /codeforamerica/
redirect_to: https://www.hackforla.org/donate
```
- [x] Using Docker, confirm that `/codeforamerica`  redirects to https://www.hackforla.org/donate

### Resources/Instructions
- This issue was created from #5953

**Comment by Jung-GunSong** [comment]
Hi, to answer the following questions:

i. I am available throughout the week can work on this issue for hours a day if needed.
ii. This is my first issue, but if things go well, hopefully I can complete this by either this or next week.

If there's anything else needed please let me know!
