### ISSUE TITLE
Investigate the Pros and Cons of moving babel.js to the build process

### ISSUE THREAD

**Issue by freaky4wrld** [hackforla/website#5979]
### Dependency

 https://github.com/hackforla/website/issues/5926

### Overview

The recent CodeQL alert raises a SRI on the external links provided to the files `_layouts/default.html and _layouts/default.html`, in the issue we want to investigate the pros and cons of moving `babel.js` to the build apart from the external link. 
As of current status `babel.js` is currently sourced from the cloudflare CDN, we would like to know your suggestion for a solution. 

### Action Items

- [x] Read the CodeQL queries
      - https://github.com/hackforla/website/security/code-scanning/36
      - https://github.com/hackforla/website/security/code-scanning/37
- [x] Investigate the pros of moving `babel.js` to the build and comment it down in the issue
- [x] Investigate the cons of moving `babel.js` to the build and comment it down in the issue
- [x] Recommend a directory structure for storing original and transpiled code
- [x] Once the pros and cons are found add the label `ready for dev lead`, and move this issue to `Questions/In Review` column  so that it can be further discussed by the senior devs
 

### Resources/Instructions

- #5297
- https://github.com/hackforla/website/security/code-scanning/36
- https://github.com/hackforla/website/security/code-scanning/37
- https://babeljs.io/docs
- https://medium.com/@prevaj_29198/do-we-need-babel-in-every-project-19b083ab4f06
- https://medium.com/@codingstorytime/set-up-a-build-environment-using-babel-and-webpack-172110681b1

**Comment by roslynwythe** [comment]
@freaky4wrld thank you for writing this issue.  It looks good and I just have a few minor suggestions:

1) In the Overview please mention that babel is currently sourced from the cloudflare CDN.  
2) Let's ask the developer to give a few recommendations about a build solution.  For instance:  currently our javascript files reside in assets/js.  To implement a build solution, would we create two subdirectories "src" and "public" to hold the original and the transpiled javaScript?  The medium article includes webpack in the build; is that required?
3) In the last action item please ask the developer to move the issue into the "Questions/In Review" column.

**Comment by freaky4wrld** [comment]
@roslynwythe the desired changes are made please check :)

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty this author of this issue @freaky4wrld has requested that he remain assigned to the issue so that he can work on it once you have prioritized it.

**Comment by ExperimentsInHonesty** [comment]
@freaky4wrld I have moved this issue to in progress.

**Comment by freaky4wrld** [comment]
ETA: EOD 1/9/2024
Availability: Evenings

**Comment by freaky4wrld** [comment]
The issue spotlighted the need for `babel.js`, although modern web-browser are adopting `babel` in their environment, but there's a need for using babel in `website` as it is a container-display for all the `hfla-projects/vision/teams.....` and has a future scope for further advancement of the codebase.

### The cons of moving `babel.js` to the build
- Firstly it is a lot of extra work to do, where the developer had to keep in mind the correct configuration of the current status of the project and making babel ready for the build, `any misconfiguration can lead to blunder`
- Adding it to the build would increase the complexity of the project and can increase the latency by increasing the build-time.
- In our project we are using babel from the CDN which is transpiling our code in real-time, moving `babel` to the build might slow-down the development experience, as the developers won't benefit from instant transpilation.
- There might be a scope of certain libraries and tools to not function correctly in the babel environment.

### The pros of moving `babel.js` to the build
- Firstly and most importantly it solves the `CodeQL queries`, by removing the dependance on the CDN and improves the security
- Moving `babel` to the build process can deliver optimized and transpiled code to the client, reducing the need for client-side transpilation. This can lead to faster load times and improved performance for end-users.


### Directory Structure
```
project-root/
|-- assets/
|   |-- js/
|   |   |-- original/
|   |   |   |-- elements
|   |   |   |-- utility
|   |   |   |-- github-actions
|   |   |   |-- other-js-files....

|   |   |   |-- transpiled/
|   |   |   |   --transpiled-js-files
|       |-- ...

|-- build/
|   |-- (transpiled output goes here)
|-- node_modules/
|-- package.json
|-- babel.config.js
|-- other project files...

```
Well I'm no expert for selecting the file architecture of the project, do correct me if I'm wrong.

**Comment by roslynwythe** [comment]
> The issue spotlighted the need for `babel.js`, although modern web-browser are adopting `babel` in their environment, but there's a need for using babel in `website` as it is a container-display for all the `hfla-projects/vision/teams.....` and has a future scope for further advancement of the codebase.
>
@freaky4wrld Thank you for your analysis.  This comment will address the first paragraph (quoted), and I'll leave separate comments regarding the remaining paragraphs.
- I believe we are using Babel to do transpiling (to convert newer language syntax such as arrow functions into ES5 code) and polyfilling (adding missing methods, properties, or APIs) for the benefit of older browsers.  I agree that Babel would not be necessary if we did not support older browsers, and if we want to support older browsers,   are ways of “working around” the need for Babel (see https://blog.logrocket.com/why-you-dont-need-babel/) but I don't understand your sentence "modern web-browser are adopting `babel` in their environment".  How would that work?
- I don't understand your comment "there's a need for using babel as it is a container-display for all the `hfla-projects/vision/teams..`.  Please provide a file path for a sample file that you are referring to.

**Comment by roslynwythe** [comment]
> The issue spotlighted the need for `babel.js`, although modern web-browser are adopting `babel` in their environment, but there's a need for using babel in `website` as it is a container-display for all the `hfla-projects/vision/teams.....` and has a future scope for further advancement of the codebase.
> 
> ### The cons of moving `babel.js` to the build
> * Firstly it is a lot of extra work to do, where the developer had to keep in mind the correct configuration of the current status of the project and making babel ready for the build, `any misconfiguration can lead to blunder`

@freaky4wrld I would like more detail about the effort, complexity and risk.  If possible, consult with devOps CoP for advice about how much extra work it would be and what the risks are.  At a minimum, I imagine it would require adding the new npm commands to the Dockerfile, resulting in a new Docker image, and we would all have to download the new Docker image.  Do you agree?  I am not certain if there are other changes we would have to make pertaining to the GitHub build.  I would welcome your opinion on that.    

Thank you for considering the risk involved in modifying the build.  Is that risk related to the dependency versions, becoming out of date or incompatible, or other factors?  

> * Adding it to the build would increase the complexity of the project and can increase the latency by increasing the build-time.

I assume you are referring to the file structure.  Referring to your file structure diagram, are you certain that we would have to move our current source from its current location `assets/js`?  And why would GitHub actions folder be moved? 

> * In our project we are using babel from the CDN which is transpiling our code in real-time, moving `babel` to the build might slow-down the development experience, as the developers won't benefit from instant transpilation.

I believe there is a VS Code extension to do Babel conversion "on save" but I'm not sure we need "instant transpilation": don't we always do a local build before testing?  So if we incorporate Babel (or webpack) into the local build, then how would it slow down the dev experience?

> * There might be a scope of certain libraries and tools to not function correctly in the babel environment.
Interesting.  Please provide links to any reports or discussion of such issues
> 
> ### The pros of moving `babel.js` to the build
> * Firstly and most importantly it solves the `CodeQL queries`, by removing the dependance on the CDN and improves the security
> * Moving `babel` to the build process can deliver optimized and transpiled code to the client, reducing the need for client-side transpilation. This can lead to faster load times and improved performance for end-users.
> 
> ### Directory Structure
> ```
> project-root/
> |-- assets/
> |   |-- js/
> |   |   |-- original/
> |   |   |   |-- elements
> |   |   |   |-- utility
> |   |   |   |-- github-actions
> |   |   |   |-- other-js-files....
> 
> |   |   |   |-- transpiled/
> |   |   |   |   --transpiled-js-files
> |       |-- ...
> 
> |-- build/
> |   |-- (transpiled output goes here)
> |-- node_modules/
> |-- package.json
> |-- babel.config.js
> |-- other project files...
> ```
> 
> Well I'm no expert for selecting the file architecture of the project, do correct me if I'm wrong.

**Comment by freaky4wrld** [comment]
> > The issue spotlighted the need for `babel.js`, although modern web-browser are adopting `babel` in their environment, but there's a need for using babel in `website` as it is a container-display for all the `hfla-projects/vision/teams.....` and has a future scope for further advancement of the codebase.
> 
> @freaky4wrld Thank you for your analysis. This comment will address the first paragraph (quoted), and I'll leave separate comments regarding the remaining paragraphs.
> 
> * I believe we are using Babel to do transpiling (to convert newer language syntax such as arrow functions into ES5 code) and polyfilling (adding missing methods, properties, or APIs) for the benefit of older browsers.  I agree that Babel would not be necessary if we did not support older browsers, and if we want to support older browsers,   are ways of “working around” the need for Babel (see https://blog.logrocket.com/why-you-dont-need-babel/) but I don't understand your sentence "modern web-browser are adopting `babel` in their environment".  How would that work?
> * I don't understand your comment "there's a need for using babel as it is a container-display for all the `hfla-projects/vision/teams..`.  Please provide a file path for a sample file that you are referring to.

Hey @roslynwythe maybe there's a conflict between what was I thinking and what I wrote, sorry I didn't re-read my comments, well regarding to the statement in the `bullet-point-1` I instead want to write, that modern browsers are adopting `es6 syntax` and if we try to analyse the browsers our customers are using (as mentioned in the article) we can remove our dependancy on `babel`.

And on the `bullet-point-2` I was trying to conclude that the files using babel, i.e. `default-markdown.html` and `default.html` and if I'm not wrong that they are a showcasing page rendered on the website, with different content on it, maybe I'm wrong with my choice of words..... sorry again

**Comment by freaky4wrld** [comment]
> > The issue spotlighted the need for `babel.js`, although modern web-browser are adopting `babel` in their environment, but there's a need for using babel in `website` as it is a container-display for all the `hfla-projects/vision/teams.....` and has a future scope for further advancement of the codebase.
> > ### The cons of moving `babel.js` to the build
> > 
> > * Firstly it is a lot of extra work to do, where the developer had to keep in mind the correct configuration of the current status of the project and making babel ready for the build, `any misconfiguration can lead to blunder`
> 
> @freaky4wrld I would like more detail about the effort, complexity and risk. If possible, consult with devOps CoP for advice about how much extra work it would be and what the risks are. At a minimum, I imagine it would require adding the new npm commands to the Dockerfile, resulting in a new Docker image, and we would all have to download the new Docker image. Do you agree? I am not certain if there are other changes we would have to make pertaining to the GitHub build. I would welcome your opinion on that.
> 
> Thank you for considering the risk involved in modifying the build. Is that risk related to the dependency versions, becoming out of date or incompatible, or other factors?
> 
> > * Adding it to the build would increase the complexity of the project and can increase the latency by increasing the build-time.
> 
> I assume you are referring to the file structure. Referring to your file structure diagram, are you certain that we would have to move our current source from its current location `assets/js`? And why would GitHub actions folder be moved?
> 
> > * In our project we are using babel from the CDN which is transpiling our code in real-time, moving `babel` to the build might slow-down the development experience, as the developers won't benefit from instant transpilation.
> 
> I believe there is a VS Code extension to do Babel conversion "on save" but I'm not sure we need "instant transpilation": don't we always do a local build before testing? So if we incorporate Babel (or webpack) into the local build, then how would it slow down the dev experience?
> 
> > * There might be a scope of certain libraries and tools to not function correctly in the babel environment.
> >   Interesting.  Please provide links to any reports or discussion of such issues
> > 
> > ### The pros of moving `babel.js` to the build
> > 
> > * Firstly and most importantly it solves the `CodeQL queries`, by removing the dependance on the CDN and improves the security
> > * Moving `babel` to the build process can deliver optimized and transpiled code to the client, reducing the need for client-side transpilation. This can lead to faster load times and improved performance for end-users.
> > 
> > ### Directory Structure
> > ```
> > project-root/
> > |-- assets/
> > |   |-- js/
> > |   |   |-- original/
> > |   |   |   |-- elements
> > |   |   |   |-- utility
> > |   |   |   |-- github-actions
> > |   |   |   |-- other-js-files....
> > 
> > |   |   |   |-- transpiled/
> > |   |   |   |   --transpiled-js-files
> > |       |-- ...
> > 
> > |-- build/
> > |   |-- (transpiled output goes here)
> > |-- node_modules/
> > |-- package.json
> > |-- babel.config.js
> > |-- other project files...
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Well I'm no expert for selecting the file architecture of the project, do correct me if I'm wrong.

- I haven't got to catch-up with members in devOp CoP, so I'm still working on that, I had a single discussion with @fyliu where he emphasised on moving `babel` to the `build`, but no deep conversation involved. 
Well according to me apart from the changes in `Docker-image` we would have to make changes in the files as well, like we might `bundle the transpiled code` and want to use `webpack` then there might be a lot of time consumed to maybe configuring `webpack with babel` (this is a personal difficulty I noticed others might differ) and as of my knowledge we are not using the latest version of `babel (i.e babel-7)`, I haven't really worked on that but can bring the issue up during the discussion with a member of `devOps CoP`
- Yes with my limited scope of knowledge I was referring to risk related to the dependency versions, becoming out of date or incompatible
- Maybe I'm not sure with the file structuring, I was unaware about the `github-actions` functionality at the time of commenting this, but now conclude there's no need to transpile the `github-actions` folder. And as of the `asset/js` folder I would say there's no need to move it to a new location, that would result into a lot of changes to be done in files using those js files, maybe we can create a `dist/js` folder with all the transpiled and bundled code (not sure if we want bundling), and an additional `babel.config.js`
- I'm not sure about the extension of `VS-code`, I can look into it if you provide me with the name in my Slack....

Lastly as we have an issue for approval regarding the use of `integrity-attribute` this could work as a temporary work-around till the time we can discuss and research on it more.

**Comment by freaky4wrld** [comment]
## Revised comments 

### The cons of moving `babel` to build
- chance of misconfiguration while making changes to the codebase in order to move `babel` to the build, as we might need `bundler and webpack` for this
- maybe we might make some processes a bit complex that would lead to latency as the browser
- adding extra content to the build would probably make the build a bit slow as well
- there's a scope of certain libraries and tools to not function correctly in the babel environment

### The pros of moving `babel` to build
- most importantly it solves the CodeQL queries, by removing the dependance on the CDN and improves the security
- build process can deliver optimized and transpiled code to the client, reducing the need for client-side transpilation. This can lead to faster load times and improved performance for end-users.

Lastly for the file structure we can create a `dist/js` folder with all the transpiled and bundled code (not sure if we want bundling), and an additional `babel.config.js`.
Also on the complexity and work to do while doing the whole process, I haven't got anything useful except the suggestion on the emphasis on moving `babel to the build` and remove the `dependency from external environment`

**Comment by roslynwythe** [comment]
Thank you @freaky4wrld - please see my comments below

> ## Revised comments
> ### The cons of moving `babel` to build
> * chance of misconfiguration while making changes to the codebase in order to move `babel` to the build, as we might need `bundler and webpack` for this
> * maybe we might make some processes a bit complex that would lead to latency as the browser

I'm having trouble imaging this, could you provide an example?

> * adding extra content to the build would probably make the build a bit slow as well
> * there's a scope of certain libraries and tools to not function correctly in the babel environment

I'm not understanding this.   Would a library function correctly if babel ran in the browser, but not if babel ran in the build? Isn't the resulting code the same?
> 
> ### The pros of moving `babel` to build
> * most importantly it solves the CodeQL queries, by removing the dependance on the CDN and improves the security
> * build process can deliver optimized and transpiled code to the client, reducing the need for client-side transpilation. This can lead to faster load times and improved performance for end-users.
> 
> Lastly for the file structure we can create a `dist/js` folder with all the transpiled and bundled code (not sure if we want bundling), and an additional `babel.config.js`. Also on the complexity and work to do while doing the whole process, I haven't got anything useful except the suggestion on the emphasis on moving `babel to the build` and remove the `dependency from external environment`

Please clarify the last sentence.  Are you saying that your suggestion is to move babel to the build?

Also I wonder if there is a "pro" or a "con" relating to maintainabilty - is there a more efficient process for accomodating babel upgrades in one scenario over the other?

**Comment by freaky4wrld** [comment]
@roslynwythe here's my comments to your questions above : 
- To your first question, we are relying on `babel` version that is not latest using a specific version that is `6.something` and for our application that is up and running we might be using some tools/libraries or modules that go incompatible with the version we are currently using. Also in order to incorporate babel, there might be a dependency on webpack and bundler as well, as a result of which the build gets added with more files that would slow down the process.
- To your second question, I was referring to third-party tools and libraries that we are using currently, or maybe as the application grows and we incorporate some more third-party tools and libraries there's a possibility of them producing errors with the current version of babel we are using.
- Yes I'm suggesting to move `babel` to the build to reduce our dependence on external resources
- Lastly you can refer to this [ChatGPT](https://chat.openai.com/share/e31ce4a6-3422-45b9-a41b-60be787c21fd) prompt for further clarifications. My findings on this issue are based on `ChatGPT and some articles` have no experience with the above technology.... all I can think of are edge cases where our current `babel` version can fail some of our features and produce errors.

**Comment by freaky4wrld** [comment]
## Revised Comments

### Cons

- Use of babel in production for a non-Node.js environment is not the typical setup and would require a custom GitHub action for GitHub pages buid/deployment in place of our current standard GitHub Pages build/deployment.  This will increase the chance of misconfiguration in GitHub Pages.  Also the change to GitHub build will have to be reflected in the local docker build, raising the risk of issues there.  If the behavior of babel in the docker build does not match that in the GitHub build, we risk introducing problems that will not be reproducable during local testing.
- For production builds, babel is most commonly implemented within webpack so we should consider the pros/cons of webpack before implementing babel in the build.  The choice to use webpack will affect the directory structure.
- adding extra content to the build would probably make the build a bit slow as well.

### Pros

- most importantly it solves the CodeQL queries, by removing the dependance on the CDN and improves the security.
- As part of the GitHub build, with proper configuration, babel/webpack will be included in dependabot reports of outdated or insecure packages.
- build process can deliver optimized and transpiled code to the client, reducing the need for client-side transpilation. This can lead to faster load times and improved performance for end-users.

**Comment by roslynwythe** [comment]
Thank you @freaky4wrld for an excellent analysis.
