### ISSUE TITLE
Create project card for 100 Automations

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#599]
### Overview
Provide collateral for the HackforLA website

### Action Items
- [x]   Gather items
  - [x]  600 x 400 image
     - [x]  Alt image text
  - [x] 1500 x 700 hero image (please do not put project title on hero image)
     - [x]  Alt image text
  - [x]  Name of project
  - [x]  A blurb about your project
  - [x]  Links (github, slack channel url, Testing Site, Live Site, etc.)
  - [x]  Any resources for a Getting Started link (a link to a wiki, readme(s) or both)
  - [x]  What you are looking for skills wise
  - [x]  Partner(s)
  - [x]  Location
  - [x]  Status
- [ ]   Add project Card to website

### Resources/Instructions
The content for this issue are located in the issue here: https://github.com/100Automations/Website/issues/2

**Comment by alexandrastubbs** [comment]
@drubgrubby can you please update this issue?

**Comment by drubgrubby** [comment]
I had some GitHub issues bringing this to the finish line.  I believe they have been resolved and this is ready to merge.
