### ISSUE TITLE
Run VS Code Spell Checker on pages/projects-page.html

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#5996]
### Overview
We need to audit HfLA codebase files for spelling errors using the Code Spell Checker extension in VS Code in order to ensure site quality. Results will be categorized as misspellings or false positives in the HfLA spelling audit spreadsheet[^1] and will be resolved in later issues.  

### Action Items
- [x] You must use VS Code as your local text editor and install the `Code Spell Checker` VS Code extension[^2]  
- [x] Do not change any configuration settings or make any spell corrections
- [x] Open the file 'pages/projects-page.html' and note any Code Spell Checker errors
- [x] Locate the file in column A ("File") of the "Page Audit" sheet. In the column labeled "Result Summary", select the appropriate option: `No errors` or `At least one error`.
- [ ] If at least one error was reported, copy/paste each cSpell message into a separate row in the `Results` sheet
- [ ] In each new row, select the appropriate value: `misspelling` or `false positive` from the "Result type" column. A false positive is a term that is not a misspelling but is not recognized by the spell checker because it is a technical term, abbreviation, acronym, URL or proper noun (name of a person, place or organization).
- [x] Move this issue to the Questions/In Review column and apply the label `ready for dev lead`

### Merge Team
- [x] After this issue is closed, release the dependency on this issue in #5248
- [ ] After the last dependency has been released, close that issue

### Resources/Instructions
- This issue is part of #5248
[^1]: [HfLA spelling audit spreadsheet - Results](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=69989048)
[^2]: The recommended installation method is to install Code Spell Checker directly from the VS Code text editor, and those instructions can be found [here](https://code.visualstudio.com/learn/get-started/extensions). The extension can also be installed via the VS Code Marketplace website [here](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

**Comment by nelsonuprety1** [comment]
@roslynwythe Hi, in the audit sheet provided  the projects-page.html file is not mentioned in the File column and there is no any mention of Results summary tab. I did run the spell check and found no errors. So please take a look at the spreadsheet and let me know. Thank You.

**Comment by nelsonuprety1** [comment]
@roslynwythe @t-will-gillis 
Also i am unable to raise any PR without any changes. So, please let me know what should i do next in this case as well. Thank You.

**Comment by LRenDO** [comment]
Hi @nelsonuprety1! 

It looks like `pages/projects-page.html` is in line 56 of the "Page Audit" sheet of the [spreadsheet](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit?pli=1#gid=1277680545). 

For now, I am moving this back to the `in progress (actively working)`. When you're done with the audit you can just move it back to the `Questions / In Review` column and add the `ready for dev lead` label again. Since there is no PR associated with this type of issue, moving it and adding a label is the way we move it into the review process. Feel free to ping me here or on Slack if you need any help or clarification.

**Comment by nelsonuprety1** [comment]
@LRenDO thank you for the suggestion and spreadsheet. I have updated as per your suggestion. Thank you

**Comment by t-will-gillis** [comment]
Hey @nelsonuprety1 Thank you for reviewing this issue and noting 'No Errors' on the "Page Audit". I am closing this issue as completed.
