### ISSUE TITLE
White list h4la.netlify.com domain for calendar API

### ISSUE THREAD

**Issue by jjandoc** [hackforla/website#6]
Calendar API requests are getting blocked. I assume it's just a matter of white-listing the domain at h4la.netlify.com. We should also ensure that `localhost` and `*.hackforla.org` are white-listed.

**Comment by ctsexton** [comment]
Done - have white-listed those but currently the site is just using an API key I set up in my personal account. Might be more appropriate to set one up in a Hack for LA account?

**Comment by jjandoc** [comment]
@matikin9 is there a good account we can use for setting up a H4LA-owned api key

**Comment by thekaveman** [comment]
@jjandoc @matikin9 was there ever any change with this, or still under @ctsexton account?

**Comment by matikin9** [comment]
I never got around to it but I should do that from my account.

**Comment by abregorivas** [comment]
Who has access to white list "localhost:4000"

**Comment by abregorivas** [comment]
hackforla.org is already whitelisted. Unless a new domain is added this issue is closed.
