### ISSUE TITLE
HFLA Site Members Complete 2FA Set-up

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#600]
### Overview
A few HFLA site team members do not yet have 2FA enabled and need to get it enabled. 

### Action Items
- [x] @leonelRos to set-up 2FA
- [x] @jbubar to set-up 2FA

### Resources/Instructions
Guide for setting up 2FA: https://github.com/hackforla/governance/issues/20

**Comment by leonelRos** [comment]
@alexandrastubbs  I will set it up this week! Thanks

**Comment by leonelRos** [comment]
@alexandrastubbs  I just enable my 2FA

**Comment by jbubar** [comment]
@alexandrastubbs I enabled 2FA. Sorry about that. Thanks for your patience

**Comment by alexandrastubbs** [comment]
Both Josh & Leo have completed.
