### ISSUE TITLE
ER: Update Project Profile: Access the Data

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/website#6018]
### Dependency (Issues that need to be completed in order to close this ER and complete these [action items](https://github.com/hackforla/website/issues/6018#issuecomment-1878062475))
- [x] #6064 
- [x] #6065 

### Project Name

Access The Data

### Project Card URL

access-the-data.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: AJ Price
- [x] Name: Aparna Gopal
- [x] Name: Judson Lester
- [x] Name: Tony Delgado Willis
- [x] Name: Jason Yung

### Add person(s) and info to Leadership?

NO

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name:
GitHub Handle:
Role:
Slack Member ID:

### Project Status

- [x] On Hold

**Comment by parag477** [comment]
Can you assign this to me

**Comment by JessicaLucindaCheng** [comment]
@parag477
> Can you assign this to me

In order to work on an issue, you need to be a member of Hack for LA. (There are no fees to join.) Please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.

**Comment by JessicaLucindaCheng** [comment]
Issue Writing Availability
- Availability: 3 hours
- ETA to complete writing all issues: Friday, January 5, 2024

**Comment by JessicaLucindaCheng** [comment]
All issues have been written for this ER and have been added to the Dependency section.

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issue(s) in the Dependency section are merged, 
- [x] Close this ER
- [x] Move this ER to the UAT column
- [x] ~Contact the author of this ER to approve the changes on the [Access the Data](https://www.hackforla.org/projects/access-the-data) page and add a `ready for stakeholder` label~
- [x] Once the changes have been accepted by the author of this ER, remove the `ready for stakeholder` label and add a `ready for product` label. Also, leave a comment that this ER is ready for further UAT and QA by product.

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-pm
Since AJ is no longer part of the Access the Data project anymore and there are no other leadership members for the project because the project is on hold, I have skipped contacting Access the Data leadership for UAT.

Thus, I am passing this to you for UAT approval and QA.

**Comment by JessicaLucindaCheng** [comment]
This issue has been in UAT for a long time, so I am moving this to QA.
