### ISSUE TITLE
Edits to Tools data on `home-unite-us.md`

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6019]
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview

The Tools data for the "Home Unite Us" project pages list some Google tools without including the word "Google". We need to edit these entries to match other project pages and the filter data on the "Homepage" and "Projects" pages.

### Action Items

- [x] Refer to [home-unite-us.md](https://github.com/hackforla/website/blob/gh-pages/_projects/home-unite-us.md) and find the entry for `tools:`
- [x] Change the `tools:` data from:
```
  - Figma
  - Style Components
  - Zoom
  - GitHub
  - Google Drive
  - Docs
  - Sheets
  - Slides
```
to:
```
  - Figma
  - Style Components
  - Zoom
  - GitHub
  - Google Drive
  - Google Docs
  - Google Sheets
  - Google Slides
```
- [x] Confirm that the Tools data on all project pages is rendered correctly. 

### Resources/Instructions

  - [Homepage](https://www.hackforla.org)
  - [Projects](https://www.hackforla.org/projects/) page

**Comment by jtkabenni** [comment]
Availability: 3-5 hours this week/weekend 
ETA: Friday EOD

**Comment by freaky4wrld** [comment]
ETA: EOD 6/1/24
