### ISSUE TITLE
Edits to Tools data for `green-earth-os.md`

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6020]
### Prerequisites
  1. You must be a member of Hack for LA to work on an issue. If you have not joined yet, please follow the steps on our [Getting Started](https://www.hackforla.org/getting-started) page.
  2. Please make sure you have read our Hack for LA [Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) before you claim/start working on an issue.

### Overview

The entries for the Tools data on the "Green Earth OS" project have inconsistent capitalization. Tool data in `green-earth-os.md` needs to be capitalized in order for the Tools filter menu on the projects-check page to render properly.

### Action Items

- [x] Refer to [green-earth-os.md](https://github.com/hackforla/website/blob/gh-pages/_projects/green-earth-os.md) and find the entry for `tools:`
- [x] Change the `tools:` data from:
```
tools:
  - Google sheets
  - Google forms
  - Figma
  - FigJam
```
to:
```
tools:
  - Google Sheets
  - Google Forms
  - Figma
  - FigJam
```
- [x] Confirm that the tools data renders correctly on the Homepage, Projects, and Green Earth OS pages.

### Resources/Instructions

[Homepage](https://www.hackforla.org/)
[Projects](https://www.hackforla.org/projects/) page
[Projects Check](https://www.hackforla.org/projects-check) page
[Green Earth OS](https://www.hackforla.org/projects/green-earth-os) page
This issue was initiated by ER #5269

**Comment by sornekian** [comment]
i. Weeknights 7-11pm
ii. 12/30/2023 5pm
