### ISSUE TITLE
GHA `issue-trigger.yml` needs to add a check for the `size: missing` label

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6022]
### Overview

The `issue-trigger.yml` GHA does not check whether a newly created issue has a `size` label. We need to update this GHA so that the `size: missing` label is added to issues created without a size label.

### Action Items

Refer to `issue-trigger.yml`, `check-label.js`, and `post-labels-comment.js` to review the intended functions of this GHA. Note that `check-labels.js` checks whether a newly created issue has required labels corresponding to 'Complexity', 'role', and/or 'Feature'. If not, the bot adds the labels `Complexity: Missing`, `role: missing`, and/or `Feature: Missing`.   

On `check-labels.js`:
- [x] Line 2, add 'size' to REQUIRED_LABELS 
- [x] Line 3, add add 'size: missing' to LABEL_MISSING   

On `post-labels-comment.js`:
- [x] Replace:
```
  'Complexity: Missing': 'Complexity',
  'role missing': 'Role',
  'Feature Missing': 'Feature'
```
with:
```
  'Complexity: Missing': 'Complexity',
  'role missing': 'Role',
  'Feature Missing': 'Feature',
  'size: missing': 'Size'
```
- [x] Review the remainder of both files to check whether any additional logic is needed for the bot to review a newly created issue for the presence of a size label and add the `size: missing` label if not. 
- [x] Test the GHA in your own repo by creating issues both with and without a size label to ensure that the automation is working properly: i.e. labels are added when needed, and the issue comment is formatted as a list with .

### Resources/Instructions

[issue-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/issue-trigger.yml)
[check-label.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/check-labels.js)
[post-labels-comment.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-issue/add-missing-labels-to-issues/post-labels-comment.js)
This issue was initiated by ER #5717

**Comment by djbradleyii** [comment]
Availability: M-F 10-5pm
ETA: EOD Friday, January 5th

**Comment by t-will-gillis** [comment]
Hey @djbradleyii Thanks for picking up this issue. FYI It has the `Draft` label because it was not quite ready yet. It needs more information about how to test the GHA- I will add that now.

**Comment by djbradleyii** [comment]
I believe there was information on how to test the GHA. I tested it on my local repo which is why I added the screen shot confirming that the label was added.

**Comment by t-will-gillis** [comment]
Ah ok, great! Thanks for the response

**Comment by ExperimentsInHonesty** [comment]
- @djbradleyii It looks like Will gave you some very easy to accomplish changes to make to your PR so that it can get merged.  Please take care of those.  https://github.com/hackforla/website/pull/6085
