### ISSUE TITLE
Refactor JavaScript so that Events page sources meeting data from vrms_data.json

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6023]
### Overview
We need to refactor the JavaScript that generates the list of meetings on the Events page, so that it retrieves meeting data from the file `data/external/vrms_data.json`, in order to reduce the latency and improve the reliability of the Events page.  For testing purposes, a new page `events-check` will be created that will maintain the behavior of the current `events` page.

#### Details
The project pages currently sources meeting data from `data/external/vrms_data.json` and so elements of that code can be refactored so that functions can be called from the Events page as well.  

### Action Items
- [x] Copy `events.html` then rename the copy to `events-check.html` and change the permalink to `/events-check`
- [x] Copy `events.js` then rename the copy `events-check.js` and update `events-check.html` to reference the renamed file
- [x] Copy `_includes/events-page/right-col-content.html` then rename the copy to `_includes/events-page/right-col-content-check.html` and update `events-check.html` to reference the renamed file 
- [x] Copy `assets/js/right-col-content.js` then rename the copy `assets/js/right-col-content-check.js` and modify `_includes/events-page/right-col-content-check.html` to reference the renamed file 
- [x] Confirm that the appearance and meeting data on `/events-check` are identical to `/events`
- [x] Open the file `assets/js/project.js` in your IDE and understand the code used to display project meetings.  If there is code that can be shared between the project and events pages, move those elements to a new file `assets/js/utility/vrms-events.js`.  
- [x]  If code was moved to `assets/js/utility/vrms-events.js`, refactor the code in `assets/js/project.js` to reference function(s) in the new file, and perform testing to confirm that functionality on the Project page[^2] is unchanged. 
- [x] Refactor the code in `assets/js/right-col-content.js` and `_includes/events-page/right-col-content.html` to reference the function(s) in `assets/js/utility/vrms-events.js` and perform testing to confirm that functionality on the Event page[^1] is unchanged. 

### Resources/Instructions
[^1]:[Events webpage](https://www.hackforla.org)
[^2]:[Project page - sample](https://www.hackforla.org/projects/311-data)
[^3]:[Project Meetings page](https://www.hackforla.org/project-meetings)

### Merge Team
- [x] Release dependency on #6059, move that issue to New Issue Approval and apply "ready for dev lead" label

**Comment by pravintargaryen** [comment]
@roslynwythe assign this to me

**Comment by njackman-2344** [comment]
Availability: Thursday 2/1 7pm-10pm, Friday 2/2 5pm-10pm, Saturday 2/3 3pm-7pm, Sunday 2/4 12pm-4pm

ETA: Monday 2/12 EOD PST

**Comment by njackman-2344** [comment]
Progress: Moved code and created new file. I want to do some more tests but the code works as is in Docker.

Blockers:  what tests and how much refactoring to do... Get a second person to bounce ideas.

Availability: This weekend and Monday: 8 hours

ETA: Wednesday 2/14 EOD

**Comment by ExperimentsInHonesty** [comment]
Hi @njackman-2344.   I'm possibly going to increase the scope of this issue.  I am leaving a note for the dev lead here and you will see the discussion

Hi @hackforla/website-merge I realized we are having the events page refactored in this issue, so that it doesn't pull the data directly from VRMS.  However, it would be helpful to have a page so that we can visually test the VRMS data when we need to.  So should we increase the scope of this issue to make a copy of the current events page and call it events-check so that we can use it much like we use the projects-check page (a different view on the data that makes it easy to do manual verification).   Later, we can strip anything off the page that we don't need.

- I was working on this issue when I realized it might be helpful.  https://github.com/hackforla/website/issues/6278

**Comment by njackman-2344** [comment]
1. 2 of 3 completed. Will refactor code.
2. Wanted to be sure if any changes beforehand with merge team. But I will go ahead.
3. Will work on through the weekend and next week.
4. ETA: 3/11 EOD

**Comment by ExperimentsInHonesty** [comment]
@njackman-2344 it has been decided that we are going to increase the scope of this issue.  Please make sure that your PR includes taking the current copy of events page and call it events-check and making sure the script that pulls directly from VRMS instead of the https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json file is what provides the data to the new events-check page.

**Comment by ExperimentsInHonesty** [comment]
p.s. thank you for your patience while we sorted that out.

**Comment by njackman-2344** [comment]
1. copied events.js and html to events-check. refactoring needed. 
2. Have question on vrms api data into events-check and vrms json into events.
3. Weeknights - 6 hours
4. ETA-Sunday 24th
5. No visual changes

**Comment by w1ld-r** [comment]
- @bonniewolfe I spoke with @roslynwythe about this ticket and thought it could possibly be combined with this ER: https://github.com/hackforla/website/issues/6544

Just wanted to give you a heads up, happy to help if I can! Thanks 😄

**Comment by roslynwythe** [comment]
Thank you @gaylem for the suggestion.  I added the fourth action item so that the Project Meetings code will share the code utility that will be created for use in the Events page.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty the previous assignee removed their assignment so I moved the item into New Issue Approval and added two Action Items:
- The first Action Item, for implementing your suggestion to maintain the current events page functionality in a new `events-check` page.
- the event retrieval process has recently been a topic of discussion because of some recent CodeQL-related PRs.  We have two very sharp reviewers @gaylem and @aqandrew who have made valuable suggestions.  @aqandrew wrote #6544 which suggests consolidating the duplicate code between the Project Meetings and Events pages.  I thought we could add the refactoring of project-meetings.js to this issue and that can be found in the fourth action item.  If you prefer, though, we could remove that fourth Action Item and manage the refactoring of Project Meetings in a separate issue

**Comment by aqandrew** [comment]
In all fairness, @ajb176 is a sharp reviewer too! They correctly identified the bug in in #5473 and wrote the implementation that I used for #6536

**Comment by roslynwythe** [comment]
- @ExperimentsInHonesty @aqandrew  this issue has been updated to create the "/events-check" page and also to make use of existing code behind the Projects page, to refactor the Events page, in order to enable the Events page to source data from vrms-data.json.  Issue #6059 will address the Project Meetings page.

**Comment by irais-valenzuela** [comment]
Availability for this week: Wednesday - Friday
My estimated ETA for completing this issue: Friday

**Comment by ExperimentsInHonesty** [comment]
@irais-valenzuela I will move this issue to the in progress column, in the future, please remember to do that after you self assign.

**Comment by irais-valenzuela** [comment]
Availability for this week: Monday, Thursday, & Friday
My estimated ETA for completing this issue: Friday

**Comment by roslynwythe** [comment]
@irais-valenzuela in answer to your question - if you search for the variable `vrmsData` in project.js, you'll see code that retrieves the event data from the `_data/external/vrms_data.json file` and displays it using a few helper functions for sorting and formatting.  I'm guessing that at some that code could be used to render events on the events page.  If so, I suggest moving the reusable functions to a new file then refactoring.  If necessary, you can update `_includes/events-page/right-col-content.html` so that the HTML matches the HTML on the projects page more closely, but that is optional.

**Comment by irais-valenzuela** [comment]
@roslynwythe Thanks this is helpful! Is the idea to replace the API request made on ./utility/api-events.js to get meeting data for the right-col-content.html page with the vrmsData retrieval used in projects to get meeting data?

**Comment by roslynwythe** [comment]
> @roslynwythe Thanks this is helpful! Is the idea to replace the API request made on ./utility/api-events.js to get meeting data for the right-col-content.html page with the vrmsData retrieval used in projects to get meeting data?

Yes, exactly.  It is inefficient to make API calls to VRMS when the meeting data has already been retrieved and stored into `vrms-data.json`.  But for the sake of testing, we would like a page `/events-check` that continues to retrieve meeting data via API.

**Comment by irais-valenzuela** [comment]
Progress: I figured out what code can be shared between both event.js and project.js. I'm currently familiarizing myself with Jekyll and Liquid to figure out how to get data using liquid. Will continue working next week 4/29-5/3
Blockers:
Availability: Monday, Wednesday, Friday
ETA: Friday
