### ISSUE TITLE
ER: Past events are displayed on the Events page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6024]
### Emergent Requirement - Problem
Past events from VRMS appear on the Events page, for example on 1/1/2024 the following events appear:
- LinkedIn Workshop (Part 1) - date 12/06/2023
- LinkedIn Workshop (Part 2) - date 12/07/2023
- Holiday Party - date 12/09/2023
- test event  - date 2023-11-08

### Issue you discovered this emergent requirement in
- #

### Date discovered 
1/1/2024

### Did you have to do something temporarily
- [ ] YES
- [ ] NO

### Who was involved
@roslynwythe

### What happens if this is not addressed
display of past events will cause confusion especially since some events (such as the holiday party) do not link to the appropriate URL.

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
- Events with the project name "Hack4LA" should not be displayed on the Events page.

**Comment by djbradleyii** [comment]
![screencapture-hackforla-org-events-2024-01-08-17_50_40](https://github.com/hackforla/website/assets/52722401/ddbb8839-00bb-4436-b14e-65370da0b3d8)

**Comment by roslynwythe** [comment]
Created #6082

**Comment by roslynwythe** [comment]
- Created https://github.com/hackforla/website/issues/6082 to resolve issue
