### ISSUE TITLE
HFLA Team Needs Update

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#603]
### Overview
We need to keep the Hack For LA Website card up to date so that we can onboard new team members. 
### Action Items 
- [x] Product 
  - [x] Gather the changes
     - [x] Looking for
     - [x] Team leads on this page. Please add the following information:
        - [x] Who to remove/or revise
        - [x] Who to add
           - [x] Name
           - [x] Role
           - [x] Slack member ID
           - [x] Github handle
- [x] Development
   - [x] Update looking for on HFLA Site card to include newest needs:      
     - [x] UX researcher 
   - [x] Update the spreadsheet 
   - [x] Add a screenshot to this issue as a comment
       - [x] Submit a PR
- [ ]  Product 
   - [ ]  Sign off on screenshot and accept PR 

### Resources
- [Current Project Needs Spreadsheet](https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/edit#gid=0)
- [Website MarkDown File](https://github.com/hackforla/website/blob/gh-pages/_projects/website.md)

**Comment by ExperimentsInHonesty** [comment]
We need to revise the team leads on this page.  Please add the following information:
- [x] Who to remove/or revise
- [x] Who to add
   - [x] Name
   - [x] Role
   - [x] Slack member ID
   - [x] Github handle

**Comment by ExperimentsInHonesty** [comment]
- [x] Revise 
   - [x] Bonnie's title to be: Agile Coach / Stakeholder Rep
   - [x] Kian's title to be: Technical Advisor
 - [x] Remove
    - [x] Alex
 - [x] Add
    - [x] David Rubinstein
       - [x] role: tech lead
       - [x] slack member id: U015FP47R5G
       - [x] github handle: drubgrubby
    - [x] Danielle Nedivi
       - [x] role: Design Lead
       - [x] slack member id: U013U4VN8V7
       - [x] github handle: [ask her which one to use]

**Comment by IAgbaje** [comment]
- [x] Add
  - [x] Ibraheem Agbaje
    - [x]  role: Product Manager
    - [x] slack member id: U01FKL1DN48
    - [x] github handle: [@IAgbaje]

**Comment by pawan92** [comment]
- [x] add
   - [x] Pawan Murthy
   - [x] Product Manager
   - [x] Slack member ID: U01FMQTN8MU 
   - [x] github handle: [@pawan92 ]

**Comment by ahdithebomb** [comment]
Add
 

- [x] Ahdithan Uthayakumar
  - [x] role: Product Manager 
  - [x] slack member id: U01FDAPULJE
  - [x] github handle: [**@ahdithebomb** ]

**Comment by munaz77** [comment]
Add
 

- [x] Munas Musthafa
  - [x] role: Product Manager 
  - [x] slack member id: U01F6KA8094
  - [x] github handle: [**@munasmusthafa** ]

**Comment by tarang100** [comment]
- [x] Add
   - [x] Tarang Gupta
   - [x] Role: Product Manager
   - [x] Slack member ID: U01FN9BAYTY 
   - [x] Github handle: [@tarang100 ]

**Comment by abenipa3** [comment]
Hello everyone:

I updated the HFLA Team page card with the following:

- Added UX Researcher (Category: UI/UX) to HFLA's newest needs.
- Revised roles for Bonnie and Kian.
- Removed Alex
- Added the new team leads: David, Danielle, Ibraheem, Pawan, Ahdithan, Munas, and Tarang.

Please see below for the screenshots:
![image](https://user-images.githubusercontent.com/38295612/103485856-43ad2100-4dae-11eb-85d7-ddb5337cac4c.png)
![image](https://user-images.githubusercontent.com/38295612/103486505-43635480-4db3-11eb-9bec-6e307676ce2d.png)

**Comment by ahdithebomb** [comment]
Need to make the following modifications. 
- [x] Need to add Cynthia's GitHub handle, and slack member ID, include Technical Advisor as role  
- [x] Remove Munas's card as he is no longer involved

**Comment by abenipa3** [comment]
Files modified and commit merged. 

Please see more details here #901. Screenshots included below:
![image](https://user-images.githubusercontent.com/38295612/103488810-b45f3800-4dc4-11eb-8c9f-682746c6ad6c.png)
![image](https://user-images.githubusercontent.com/38295612/103488674-79103980-4dc3-11eb-9876-b269a3abe0ef.png)

**Comment by abenipa3** [comment]
Hi @ExperimentsInHonesty , this pull request was merged. Just waiting for your approval to close this issue. Thank you!
