### ISSUE TITLE
Update Readme with Commit Naming Language

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#605]
### Overview
Currently, commit names are often not clear or descriptive. We need to provide instructions on naming best practices. 

### Action Items
- [x] @jbubar to update the [readme file](https://github.com/hackforla/website#readme)
- [x] product team to review  

### Resources/Instructions
Examples of closed pull requests: https://github.com/hackforla/website/pulls?q=is%3Apr+is%3Aclosed

**Comment by jbubar** [comment]
Updated the Readme file to include a request to name their pull request descriptively

**Comment by alexandrastubbs** [comment]
Review of instructions to come in the future. All good for now.
