### ISSUE TITLE
ER: Communities of Practice information updates: Engineering (remove Alejandro Gomez)

### ISSUE THREAD

**Issue by MicahBear** [hackforla/website#6060]
### Dependency
- [x] #6074 

### Remove person(s) and info from CoP file?

YES

### If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Alejandro Gomez

### Add person(s) and info to CoP file?

NO

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name:
Title:
GitHub Handle:
Slack Member ID:

**Comment by JessicaLucindaCheng** [comment]
Issue Writing
- Availability: 1.5 hours
- ETA: Monday, January 8, 2024

**Comment by JessicaLucindaCheng** [comment]
An issue has been written to address this ER and has been added to the Dependency section.

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issue(s) in the Dependency section are merged, 
- [x] Close this ER
- [x] Move this ER to the UAT column
- [x] Contact the author of this ER to approve the changes on the [Communities of Practice](https://www.hackforla.org/communities-of-practice) page and add a `ready for stakeholder` label
- [x] Once the changes have been accepted by the author of this ER, remove the `ready for stakeholder` label and add a `ready for product` label

**Comment by JessicaLucindaCheng** [comment]
@MicahBear 
Please let us know if the changes made to the [Communities of Practice](https://www.hackforla.org/communities-of-practice) page match what you requested by adding a comment to this issue. Thank you.

**Comment by MicahBear** [comment]
Looks great 👍🏼

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-pm The changes requested have already been accepted by the author of this issue. This issue is now ready for you to UAT and QA.
