### ISSUE TITLE
Update code behind Events page so events with project names "test" and "Hack4LA" are not displayed

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6082]
### Overview
We need to update the code behind the Events page so that events with project names "test" and "Hack4LA" are not displayed in the right column, because those events do not represent regular project meetings.   

### Action Item
- [x] Open the file `assets/js/utility/api-events.js` in your IDE and update the code so that events are not displayed if their project name is "test" or "Hack4LA".  Suggestion: update the function 'filterDataFromApi'.  
- [x] Test changes locally using Docker.  Confirm that the following events do NOT appear in the right column:
   - [x] LinkedIn Workshop (part 1) Tuesday at 6 pm
   - [x] LinkedIn Workshop (part 2) Wednesday at 6 pm
   - [x] 2024 Holiday Party Saturday at 6 pm
   - [x] Mtesty face at Wednesday at 10 pm
- [x] Confirm that display of other other team/project events is consistent with the live [Events web page](https://www.hackforla.org/events)
  
### Resources/Instructions
[Events web page](https://www.hackforla.org/events)
<details><summary>Screenshot displaying "test" and "Hack4LA" project events (which should NOT be displayed) </summary>

![screencapture-hackforla-org-events-2024-01-08-17_50_40](https://github.com/hackforla/website/assets/52722401/ddbb8839-00bb-4436-b14e-65370da0b3d8)
</details> 
This issue resulted from #6024

**Comment by Anahisv23** [comment]
i. Availability: Wednesday January 24 from 1 - 4pm 
ii. ETA: Wednesday January 24 from 1 - 4pm

**Comment by nelsonuprety1** [comment]
@roslynwythe please check the #6146 PR for the fix of this issue. Thank You.

**Comment by roslynwythe** [comment]
Hi @Anahisv23 please provide an update on your progress and an updated ETA.

**Comment by Anahisv23** [comment]
i. Availability: Wednesday January 24 from 1 - 8pm
ii. ETA: Wednesday January 24 from 1 - 8pm

**Comment by roslynwythe** [comment]
@nelsonuprety1 I need to unassign you from this issue because @Anahisv23 is already working on it.
