### ISSUE TITLE
HFLA Wiki Updates

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#610]
### Overview
[Introduction to Project](https://github.com/hackforla/website/wiki/Introduction-to-the-Project) and [Joining the HackforLA.org Website Team](https://github.com/hackforla/website/wiki/Joining-the-HackforLA.org-website-team) wikis are missing some information and outdated at points. Issue #529 provides some backgroound.

### Action Items
- [x] [Move HFLA One Sheeter](https://docs.google.com/document/d/1hIAKyJwDHknPjn7I-RmZeCu_RkK-Zw4YNBA_-Ygqdoc/edit) to the Intro to Project page 
- [x] Update PM from Harish to Alex on [Joining the HackforLA.org Website Team](https://github.com/hackforla/website/wiki/Joining-the-HackforLA.org-website-team) page
- [x] Add in slide deck on how we use project boards in GitHub to [Joining the HackforLA.org Website Team](https://github.com/hackforla/website/wiki/Joining-the-HackforLA.org-website-team) page
- [ ] Create a 'How to' article for how we use Kanban board 

### Resources/Instructions
[How we set up Kanban boards deck](https://docs.google.com/presentation/d/1LHtvnHb35Sw7cHzk8RYJG4a1U9RblZepsC3wL7ZEpV0/edit#slide=id.g5e46fb07f1_0_1)

**Comment by alexandrastubbs** [comment]
Test this link:  Slack our PM [Alex](https://hackforla.slack.com/team/U015KCAN676) with your Gmail address.

**Comment by alexandrastubbs** [comment]
For Kanban board, create 'how we use them' document and a reference to one in progress. Alex working on this. 

1. Progress - slide deck is added, but need to add a how we use them doc
2. Blocks - none
3. Availability - Mon, Tues, Wed
4. ETA - updates to wiki by EOD Tuesday, outline for article by Sunday 7/26

**Comment by alexandrastubbs** [comment]
PM has been updated and one-sheeter has been moved to Intro to Project Wiki. I removed the screenshot of our site because it was too small and not legible. I believe including a link to site prominently at the start of the page should suffice. Link for screenshot below in case we need it. 

Will work on Kanban article next. 

![Screenshot of HFLA Homepage](https://user-images.githubusercontent.com/66918724/87251956-80badb00-c43d-11ea-97a3-8c2c76aced21.png)

**Comment by alexandrastubbs** [comment]
1. Progress - everything complete except for Kanban board article
2. Blocks - none
3. Availability - Mon, Tues, Wed
4. ETA - outline for article by Sunday 8/2

**Comment by alexandrastubbs** [comment]
Progress - Working on this, some things came up during the week
Blocks - None
Availability - n/a
ETA - Aiming for 8/9

**Comment by alexandrastubbs** [comment]
Working on How To article, draft can be found [here](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit?usp=sharing).

**Comment by alexandrastubbs** [comment]
Progress: made some progress on the google doc draft 
Blocks: moving this past week
Availability: Mon-Thurs
ETA: end of this week!

**Comment by alexandrastubbs** [comment]
Moving Kanban progress to Issue #209 

Dependency: #209

**Comment by shaswa** [comment]
- [ ] We need to update the [introduction to the project](https://github.com/hackforla/website/wiki/Introduction-to-the-Project)
- [ ] Make sure there is a link to the onesheet
- [ ] Review for any additional updates
