### ISSUE TITLE
ER: Communities of Practice information updates: UI/UX CoP

### ISSUE THREAD

**Issue by Aparna1Gopal** [hackforla/website#6101]
### Dependency (Issues that need to be completed in order to close this ER and complete these [action items](https://github.com/hackforla/website/issues/6101#issuecomment-1902637660))
- [x] #6104 

### Remove person(s) and info from CoP file?

NO

### Add person(s) and info to CoP file?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Leo Peng
Title: Co-lead
GitHub Handle: leopeng101
Slack Member ID: UPDM52A94

**Comment by JessicaLucindaCheng** [comment]
### For Issue Writing
**Availability:** 1.5 hours
**ETA:** Sunday, January 14, 2024

**Comment by JessicaLucindaCheng** [comment]
@Aparna1Gopal You requested that Leo Peng's role be "UX Designer" but this differs from the "Co-Lead" roles listed for the other UI/UX CoP leads on the [Communities of Practice](https://www.hackforla.org/communities-of-practice) page. So, did you want Leo Peng's role to be "UX Designer" or "Co-Lead"? Thanks.

**Comment by Aparna1Gopal** [comment]
@JessicaLucindaCheng Thanks for catching this! We would like Leo Peng's role to be 'Co-Lead' - as listed for the other UI/UX CoP leads on the [Communities of Practice](https://www.hackforla.org/communities-of-practice) page.

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issue(s) in the Dependency section are merged, 
- [x] Close this ER
- [x] Move this ER to the UAT column
- [x] Contact the author of this ER to approve the changes on the [Communities of Practice](https://www.hackforla.org/communities-of-practice) page and add a `ready for stakeholder` label
- [ ] Once the changes have been accepted by the author of this ER, remove the `ready for stakeholder` label and add a `ready for product` label. Also, leave a comment that this ER is ready for further UAT and QA by product.

**Comment by JessicaLucindaCheng** [comment]
@Aparna1Gopal 
Please let us know if the changes made to the [Communities of Practice](https://www.hackforla.org/communities-of-practice) page match what you requested by adding a comment to this issue. Thank you.

**Comment by Aparna1Gopal** [comment]
@JessicaLucindaCheng This is perfect! Thank You!

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-pm The changes requested have already been accepted by the author of this issue. This issue is now ready for you to UAT and QA.
