### ISSUE TITLE
Add new variable github-handle to member Leah Ellis in civic-tech-jobs.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6110]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/civic-tech-jobs.md` in the IDE
- [x] Replace:
```
- name: Leah Ellis 
```
with
```
- name: Leah Ellis 
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/civic-tech-jobs

- This issue is part of #5441.

**Comment by duojet2ez** [comment]
@roslynwythe This issue's title is "Add github handle for Holly Worthen" but the instructions specify Leah Ellis. Should I add for Leah Ellis?

**Comment by duojet2ez** [comment]
1. Progress - This task is basically done.. however, there's a discrepancy between the title and the instructions. Title says "add github handle for Holly Worthen" and the instructions say add a handle for "Leah Ellis". I've added the handle to Leah Ellis. Am I set with this to make a pull request? @roslynwythe 
2. Blockers: see above
3. Availability: Wed, Thurs, Fri, Sat, Sun 
4. ETA: It is complete just waiting on advisement 
5. Pictures none

**Comment by jphamtv** [comment]
Hey @duojet2ez, great catch on the title discrepancy. You're absolutely correct. Thanks for bringing that to our attention and following the instructions to add Leah Ellis's handle. Since you've completed the task as outlined, feel free to go ahead and submit the pull request. Appreciate your thoroughness and attention to detail and apologies for the confusion.
