### ISSUE TITLE
ER: Update Project Profile: 311 Data 

### ISSUE THREAD

**Issue by bberhane** [hackforla/website#6114]
### Project Name

311 Data

### Project Card URL

311-data.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

YES

### Hero Image

Hero image:
![image](https://github.com/hackforla/website/assets/143574036/249f682e-b8e2-4a41-835d-ed3c8cf17dff)

Screen capture of the Hero Image figma section:
![image](https://github.com/hackforla/website/assets/143574036/c3d88d4f-95d9-4ffb-b158-28619ac66b5d)

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

NO

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name:

### Add person(s) and info to Leadership?

NO

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name:
GitHub Handle:
Role:
Slack Member ID:

### Project Status

Active

**Comment by ExperimentsInHonesty** [comment]
I have added this to the agenda of the 311 team to talk about reasons and solutions.

**Comment by ExperimentsInHonesty** [comment]
I opened some new issue for them to resolve this.  They will open a new ER when they are ready
- overview https://github.com/hackforla/311-data/issues/1528#issuecomment-1975760387
- https://github.com/hackforla/311-data/issues/1608
- https://github.com/hackforla/311-data/issues/1692
