### ISSUE TITLE
Implement `SRI` check on the external `babel links`

### ISSUE THREAD

**Issue by freaky4wrld** [hackforla/website#6120]
### Overview

Implement SRI checks for the `babel.js` script tag in 'default-markdown.html' and 'default.html' to address CodeQL alert 36 and 37, enhancing script integrity and mitigating potential vulnerabilities.

### Action Items

- [x] Implement SRI check by adding `integrity` and `crossorigin` attribute to the `<script>` links in the files `_layouts/default-markdown.html` and `_layouts/default.html`
- [x] Do remember to make the attribute `crossorigin="anonymous"` specifically as we don't want to share our credentials with the server
- [x] For `integrity` attribute use the [SRI Generator](https://www.srihash.org) paste the url `https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/6.26.0/babel.js` and generate an `SHA-384` hash, we are using a specified version of `babel (6.26.0)`
- [x] Paste the generated hash in the `integrity` attribute of the both the files, the browser will automatically check for the integrity of the external link, `this feature of browser is only in the modern ones, older browsers have no support for SRI`.
- [x] Test the changes are by 
   - [x] Firstly starting the build with `docker-compose up` and checking if any errors are generated during the build process
   - [x] Next you can go to the browser-console by pressing `CTRL/CMD + SHIFT + I` and check for any `JavaScript related errors`
   - [x] Lastly you can go to the `Network Console` and reload the web page, then inspect the network requests to confirm that the `babel.js` script is loaded successfully.
   - [x] Test a JavaScript intensive page such as `/projects` or `/wins` in`at least two browsers`

### Resources/Instructions

- Hash generator: https://www.srihash.org
- CodeQL queries: https://github.com/hackforla/website/security/code-scanning/36 and https://github.com/hackforla/website/security/code-scanning/37
- SRI article: https://developer.mozilla.org/en-US/blog/securing-cdn-using-sri-why-how/

**Comment by roslynwythe** [comment]
Great job @freaky4wrld writing this issue.  I have a few suggestions:

- We don't usually call out specific line numbers in issues, because line numbers can change, causing confusion. 
- I suggest the labels: `Complexity: Medium`, `size: 1pt', `Feature: Code Alerts`, and `role: frontend`, but if you feel the labels should be different, please let's discuss.  
- Please add an Action Item regarding testing, and if possible, provide the developer with guideance for testing.  Perhaps the successful loading of babel could be confirmed in developer tools?

**Comment by freaky4wrld** [comment]
> Great job @freaky4wrld writing this issue. I have a few suggestions:
> 
> * We don't usually call out specific line numbers in issues, because line numbers can change, causing confusion.
> * I suggest the labels: `Complexity: Medium`, `size: 1pt', `Feature: Code Alerts`, and `role: frontend`, but if you feel the labels should be different, please let's discuss.
> * Please add an Action Item regarding testing, and if possible, provide the developer with guideance for testing.  Perhaps the successful loading of babel could be confirmed in developer tools?

Changes requested are done, please have a final look again and ping me if changes are still to be made

**Comment by roslynwythe** [comment]
@freaky4wrld Thank you for adding the test Action Items.  I have a few suggestions:
- In the second bullet point, I would replace "check for SRI related errors" with "check for any JavaScript errors"
- I suggest changing the last bullet to "test a JavaScript intensive page such as `/projects` or `/wins` in at least two browsers"

This is very minor but I think it would be good to move "(Subresource Integrity)" from the title to the Overview and then to shorten the title you can delete "in the files _layouts/default-markdown.html and _layouts/default.html".  Thank you!

**Comment by freaky4wrld** [comment]
> @freaky4wrld Thank you for adding the test Action Items. I have a few suggestions:
> 
> * In the second bullet point, I would replace "check for SRI related errors" with "check for any JavaScript errors"
> * I suggest changing the last bullet to "test a JavaScript intensive page such as `/projects` or `/wins` in at least two browsers"
> 
> This is very minor but I think it would be good to move "(Subresource Integrity)" from the title to the Overview and then to shorten the title you can delete "in the files _layouts/default-markdown.html and _layouts/default.html". Thank you!

The changes specified are done

**Comment by roslynwythe** [comment]
Great job @freaky4wrld thank you for creating this issue.  I've hidden our comments and applied the `ready for prioritization label.

**Comment by nelsonuprety1** [comment]
Availability: Wed 24 January, 2024
ETA: Wed 24 January, 2024

**Comment by nelsonuprety1** [comment]
Please check the PR #6152  for this fix.
