### ISSUE TITLE
Add github-handle for Bitian Zhang in civic-tech-jobs.md 

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6123]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/civic-tech-jobs.md` in the IDE
- [x] Replace:
```
- name: Bitian Zhang
```
with
```
- name: Bitian Zhang
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/civic-tech-jobs

- This issue is part of #5441.

**Comment by Brayheart** [comment]
Hi github actions!

This is my first contribution to Hack for LA! I will be available to work on this issue from 8am - 12pm PST M-F. I anticipate to have this closed out by next Friday, March 2nd.

**Comment by Brayheart** [comment]
The only part of this I'm not clear on is how to release the dependency for this issue. I checked the box for "add github-handle for Bitian Zhang in civic-tech-jobs.md  #6123" if that's what was needed.
