### ISSUE TITLE
Update Communities of Practice: Engineering (Standardize capitalization of "Co-lead")

### ISSUE THREAD

**Issue by JessicaLucindaCheng** [hackforla/website#6137]
### Prerequisites
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. You have already read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to standardize the capitalization of "Co-lead" for the Engineering Community of Practice so that it matches the capitalization of "Co-lead" for the other communities of practice and make the page look professional. 

### Action Items
- [x] In your IDE, open the `_data/internal/communities/engineering.yml` file
- [x] Observe the existing syntax of the front matter block [^1] in the file
- [x] Find the `leadership` variable. Then, for each person, change the L in "Co-Lead" to be lowercase, so the result is "Co-lead". Thus, change the following for each person

**From**
```
    role: Co-Lead
```
**To**
```
    role: Co-lead
```
- [ ] Verify the changes by viewing the following in your local environment and include before and after screenshots with your pull request: the Engineering section on the Communities of Practice page [^2]

### Resources/Instructions
[^1]: [Info about the front matter block](https://jekyllrb.com/docs/front-matter/)
[^2]: Communities of Practice page URL: https://www.hackforla.org/communities-of-practice

**Comment by Chrisklangley** [comment]
i. Availability: weekdays 6:30pm -9pm
ii. ETA: 1/29/24 EOD
