### ISSUE TITLE
ER: Add the Tools data to the Languages/Technologies filters

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#6150]
### Emergent Requirement - Problem
We refactored all the tool data so that we could include it in the Languages/Technologies section, of the projects and homepage, by revising it to be Languages/Technologies/Tools.  We didn't add it there yet, and I can't find the issue to do so, so if you are trying to search for UsabilityHub, you won't find it in the languages/Technology section.

### Issue you discovered this emergent requirement in
- https://github.com/hackforla/website/issues/5246
- https://github.com/hackforla/website/issues/4777

### Date discovered 
2024-01-24

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
People are missing a lot of filter options and projects will keep trying to get us to add that info to technologies or languages.

<details><summary>Tools list</summary>
<p>
 ArcGIS surveys (1)
 AtlasTI (1)
 Calendly (2)
 FigJam (2)
 Figma (13)
 GitHub (4)
 GitHub Wiki (1)
 Google Analytics (3)
 Google Calendar (1)
 Google Colab (1)
 Google Data Studio (1)
 Google Docs (7)
 Google Drive (2)
 Google Forms (3)
 Google Mail Merge (1)
 Google Sheets (5)
 Google Slides (1)
 Google Suite (2)
 HackforLA.org guides (1)
 Hotjar (1)
 LinkedIn (1)
 Miro (2)
 Mplus (1)
 Observable (2)
 Otter.ai (3)
 Photoshop (1)
 SPSS (1)
 Sketch (1)
 Storybook (1)
 Style Components (1)
 UsabilityHub (2)
 Zeplin (1)
 Zoom (8)
 paper prototyping (1)
 phone calls (1)
 pnpm (1)
 video production (1)
 whiteboard / paper & pencil (1)
</p>
</details> 

### Resources
https://www.hackforla.org/projects-check/ (it's separated out on this page by design)
https://www.hackforla.org/projects/
https://www.hackforla.org/

### Recommended Action Items
- [x] Make a new issue
- [x] Discuss with team
- [x] Let a Team Lead know

**Comment by ExperimentsInHonesty** [comment]
I left complexity missing on here, because I don't know the size of the issues that it will make.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty Just to confirm, the projects-check page will remain unchanged (with Technologies, Languages and Tools in separate filter groups) but on the projects page, Tools will be incorporated into Languages/Technologies/Tools.

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe Yes.  The purpose of that page, is to be able to easily manually check if something seems categorized, which is why we separate them.

>@ExperimentsInHonesty Just to confirm, the projects-check page will remain unchanged (with Technologies, Languages and Tools in separate filter groups) but on the projects page, Tools will be incorporated into Languages/Technologies/Tools.

**Comment by roslynwythe** [comment]
- Created issue #6196
