### ISSUE TITLE
Add github-handle for Evan Stalker in brigade-organizers-playbook.md

### ISSUE THREAD

**Issue by raviteja4117** [hackforla/website#6155]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/brigade-organizers-playbook.md` in the IDE
- [x] Replace:
```
- name: Evan Stalker
```
with
```
- name: Evan Stalker
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
Project Webpage: https://www.hackforla.org/projects/brigade-organizers-playbook

- This issue is part of #5441.

**Comment by Ayrh1** [comment]
Availability:Friday 7pm to 11pm 
ETA: Friday by 11pm

**Comment by t-will-gillis** [comment]
Hey @Ayrh1 - I am unassigning you from this issue and closing PR #6507. You have already completed three `first good issue`s. Since you have done a `Complexity: Small`, you need to work on a `Complexity: Medium` next.

**Comment by duojet2ez** [comment]
Progress: Just started this today so no progress
Blockers: None yet
Availability: A few hours this week
ETA: Either thursday april 11 or friday april 12

**Comment by duojet2ez** [comment]
Progress: PR created

**Comment by JackCasica** [comment]
Hi ~ I'll be reviewing this PR today ~
Availability: (04/14)
ETA: EOD (04/14)
