### ISSUE TITLE
ER: Communities of Practice information updates: [Ops]

### ISSUE THREAD

**Issue by chelseyklein** [hackforla/website#6159]
### Dependency
- [x] #6166

### Remove person(s) and info from CoP file?

YES

### If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Jason Ebueng

### Add person(s) and info to CoP file?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Chelsey Beck
Title: Co-lead
GitHub Handle: chelseybeck
Slack Member ID: U01J93AQKSS

- [x] Name: Ernie Pelayo
Title: Co-lead
GitHub Handle: erniep278
Slack Member ID: U046MDSM3PA

**Comment by JessicaLucindaCheng** [comment]
Issue Writing
- **Availability:** 1.5 hours
- **ETA:** Sunday, January 28, 2024

**Comment by JessicaLucindaCheng** [comment]
- #6166 was written to address this ER.

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issue(s) in the Dependency section are merged, 
- [x] Close this ER
- [x] Move this ER to the UAT column
- [x] Contact the author of this ER to approve the changes on the [Communities of Practice](https://www.hackforla.org/communities-of-practice) page and add a `ready for stakeholder` label
- [x] Once the changes have been accepted by the author of this ER, remove the `ready for stakeholder` label and add a `ready for product` label. Also, leave a comment that this ER is ready for further UAT and QA by product.

**Comment by roslynwythe** [comment]
@chelseybeck please review changes on the  [Communities of Practice](https://www.hackforla.org/communities-of-practice) page

**Comment by chelseyklein** [comment]
@roslynwythe changes look great, thanks!

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-pm The changes requested have already been accepted by the author of this issue. This issue is now ready for you to UAT and QA.
