### ISSUE TITLE
Test Adblocker on HfLA Site and Footer

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#616]
### Overview
We need to ensure that adblockers are not blocking our code from showing up to ensure that visitors to the site are able to see content on the footer. 

### Action Items
Developer
- [x] Install Adblocker (see link below)
   - [x] Try to replicate issue by turning blocker on (no special settings)
- [x] If issue is confirmed, check to see if we can update code to avoid this happening again 
- [x] If code change is not possible or does not resolve, add the social information back to the header/navigation of the site

### Resources
[Adblocker Google Chrome extension](https://chrome.google.com/webstore/detail/ad-blocker/kacljcbejojnapnmiifgckbafkojcncf). 

### Visuals
Screenshot of what it looks like here: 
![Screen Shot 2020-07-19 at 3 43 46 PM](https://user-images.githubusercontent.com/66918724/87883622-b2e8b180-c9d6-11ea-9f9f-1408d94697ed.png)

**Comment by ExperimentsInHonesty** [comment]
see the footer on this page which is not being blocked: https://www.vera.org/events

Also, @drubgrubby thinks it's possible that its because we added the donate button so the ad blocker is seeing the footer as an ad.

**Comment by drubgrubby** [comment]
Please see comments on PR #779 
https://github.com/hackforla/website/pull/779#issue-503008456
https://github.com/hackforla/website/pull/779#issuecomment-708094318
