### ISSUE TITLE
Self Onboarding Updates on Getting Started page: Wins

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#618]
### Overview
We need to link out to the new Wins page from the copy block in the Self Onboarding section of the Getting Started page so that visitors can learn about the cool accomplishments of our members. 

### Action Items

Product
- [ ] Create wording for page

Development
- [ ] Development update with new links and copy

### Resources

[Getting Started page](https://www.hackforla.org/getting-started)
Wins page: #162 
https://hackforla.org/wins
https://www.linkedin.com/company/hack-for-la/people/?viewAsMember=true

**Comment by ExperimentsInHonesty** [comment]
change title from onboard to Getting to know us
temporarily removing the onboarding video
adding the wins

**Comment by ahdithebomb** [comment]
**Proposed Changes**

- [ ] **Step 1 Change Name from Onboard -->  To Get Informed** 
   - [ ]  I think it makes more sense to have step 1 be re-worded as more of a new prospective member comes to the page and learns about what is HfLA, the types of people involved, and some of the wins that the volunteers have achieved since joining. This provides a well-rounded perspective for members to make an informed decision. 
   - [ ] Convert the paragraph form to either numbered or bullet points. 


- [ ] **Move the Remote Onboarding Survey to the very end** 
    - [ ] It makes more sense to move this to the very end of the page. Reason being, the onboarding isn't complete until a new member is on a respective project/team. This way by moving it we will be to gather better feedback on the entire onboarding process moving forward.

**Comment by ahdithebomb** [comment]
Progress: I made some initial proposed changes to the wins page.
Blocks: Getting feedback/clarity if I am on the right track or not. 
Availability: Primarily end of next week/weekend. 
ETA: End of this upcoming week.

**Comment by ahdithebomb** [comment]
The same updates apply as of Sunday.

**Comment by ahdithebomb** [comment]
Progress: Didn't have a chance to identify any net new ideas. 
Blocks: None
Availability: Weeknights and weekend. 
ETA: End of this upcoming week.

**Comment by ahdithebomb** [comment]
Progress: No Progress
Blocks:  Quarter-end at work 
Availability: Weekends
ETA: 2/21.

**Comment by ahdithebomb** [comment]
Proposed Changes 
- [ ] Step 3 Include the Time Commitment in the Getting Started  
 I  think it makes more sense to have the high-level time commitment needed from volunteers be displayed earlier on the page. We can add that it may vary by skill-set and project, however this way I think people find out if this is something they can be apart of earlier rather than later.

**Comment by ahdithebomb** [comment]
Progress: No updates since Sunday
Blocks: N/A
Availability: TBD
ETA: TBD

**Comment by ahdithebomb** [comment]
Progress: Same Updates apply since last week
Blocks: N/A
Availability: TBD
ETA: TBD

**Comment by ExperimentsInHonesty** [comment]
@ahdithebomb we have decided to put everyone through the onboarding process for a while and stress the time commitment more there.  Also, I think we are going to open things up to people who have less time but keep them on the community of practice if they don't have enough time to join a project

> Step 3 Include the Time Commitment in the Getting Started
> I think it makes more sense to have the high-level time commitment needed from volunteers be displayed earlier on the page. We can add that it may vary by skill-set and project, however this way I think people find out if this is something they can be apart of earlier rather than later.

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 I think it makes sense to incorporate some of the suggestions that @ahdithebomb was indicating in his suggestion to update the getting started.... but we we are moving to the join us replacing that.  So having a link to wins in the "Volunteer to Work on a Project" section of the join us page instead.  In the future we could also have a "get to know our volunteers stories" section and link to that.

> I think it makes more sense to have step 1 be re-worded as more of a new prospective member comes to the page and learns about what is HfLA, the types of people involved, and some of the wins that the volunteers have achieved since joining. This provides a well-rounded perspective for members to make an informed decision.

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 @Olivia-Chiong lets add people answering the onboarding survey to their first attendance at a Community of Practice meeting.

@daniellex0 Lets add the link to filling out the survey to the bottomish area of the Getting Started page.

I'll leave this issue in review in case you want clarification.

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 you added the help wanted tag.  Can you specify the help this issue requires?

**Comment by daniellex0** [comment]
@ExperimentsInHonesty Sorry, that tag was added last week and you responded at last Sunday's meeting. Removing it now.

**Comment by daniellex0** [comment]
Progress: Added survey to bottom of CoP readme

Next Steps: Figuring out how to add link to Wins in Join page

ETA: Next meeting (4/4)
