### ISSUE TITLE
Update CONTRIBUTING.md Section 2.7.f

### ISSUE THREAD

**Issue by elliot-d-kim** [hackforla/website#6185]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
In [2.7.f Working on an issue (6): Handling SSH authorization errors](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27f-working-on-an-issue-6-handling-ssh-authorization-errors), we need to clarify the instructions so new contributors with existing SSH keys know to skip the entire section.

### Details
Hack for LA sees many beginner developers join who may have already created SSH keys on previous beginner projects without necessarily learning what SSH keys are and whether new keys are required for new projects or if existing ones suffice. Thus, instructions should be more explicit that those with SSH keys already connected to their GitHub should skip 2.7.f.

### Action Items
- [x] In your local IDE, navigate to `CONTRIBUTING.md`
- [x] Replace
```
#### **2.7.f Working on an issue (6): Handling SSH authorization errors**

**IMPORTANT:** If you are a windows user then you have to install git bash, but if you are a Mac user you only need to use your terminal. Download git bash for windows here
[Git Bash](https://git-scm.com/downloads)
```
with
```
#### **2.7.f Working on an issue (6): Handling SSH authorization errors**

If you already have an SSH key that connects your computer with your GitHub account, you can skip this section (2.7.f).

**IMPORTANT:** If you are a Windows user then you have to install git bash, but if you are a Mac user you only need to use your terminal. Download Git Bash for Windows here:
[Git Bash](https://git-scm.com/downloads)
```

- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)

**Comment by anilstha1** [comment]
assign this to me

**Comment by andyphancode** [comment]
Availability for this week: Throughout week
My estimated ETA for completing this issue: By 6/7/24 EOD

**Comment by ExperimentsInHonesty** [comment]
@andyphancode I have moved this issue to the In Progress column for you.  Please remember to do that in future when you assign an issue.  Thanks!

**Comment by andyphancode** [comment]
> @andyphancode I have moved this issue to the In Progress column for you. Please remember to do that in future when you assign an issue. Thanks!

Thank you! @ExperimentsInHonesty
