### ISSUE TITLE
Update CONTRIBUTING.md Section 2.7.f

### ISSUE THREAD

**Issue by elliot-d-kim** [hackforla/website#6187]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
In [2.7.f Working on an issue (6): Handling SSH authorization errors](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27f-working-on-an-issue-6-handling-ssh-authorization-errors), we need to clarify the instructions so contributors using Windows know to run the commands on Git Bash.

### Details
Instructions should be more explicit that Windows users must not only install Git Bash but also open Git Bash and run the commands there (instead of PowerShell, etc.). Without explaining what Git Bash is and only directing to install it, beginner developers may attempt to run the given commands in PowerShell, etc. which will produce an error without relevant or helpful indicators as to where the developer went wrong.

### Action Items
- [x] In your local IDE, navigate to `CONTRIBUTING.md`
- [x] Replace
<pre><code>
##### **ii. Setting up SSH Keys for Windows**

1. You have to set up SSH keys in order to contribute to github remotely. First check if you have any keys set up already.

```bash
ls -al ~/.ssh
```
</pre></code>
with
<pre><code>
##### **ii. Setting up SSH Keys for Windows**

1. You have to set up SSH keys in order to contribute to github remotely. First check if you have any keys set up already. Open Git Bash and run:

```bash
ls -al ~/.ssh
```
</pre></code>
- [x] With CONTRIBUTING.md still open, make a note of the section in which the replaced content appears, so that you will know where to look in the document to preview the change.
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)

**Comment by jtw007** [comment]
Availability: tomorrow and Thursday early and late afternoon 
ETA: Thursday at latest

**Comment by roslynwythe** [comment]
@jtw007 I have to unassign you from this issue, because it has not been approved or prioritized.  Please self-assign issues only from the "Prioritized Backlog" column.

**Comment by roslynwythe** [comment]
@elliot-d-kim Great job writing this issue.  It is well written and will be helpful to future developers.  Just to outline our process for approving and prioritzing issues: after writing an issue, the author should apply the label "ready for dev lead".  That will bring the issue to my attention, and after my review I will apply the label "ready for prioritization" or "ready for product", both of which are addressed by a PM.   Thank you!!

**Comment by JackCasica** [comment]
Availability: This evening.
ETA: End of day.
