### ISSUE TITLE
ER: Update the Communities of Practice information updates Issue Template

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#6188]
### Emergent Requirement - Problem
We should start allowing the CoP to edit what kind of leadership  the CoP has.

### Issue you discovered this emergent requirement in
- #4239

### Date discovered 
2024-01-27

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
It's harder for CoP leadership to ask for a change.

### Resources

- Page on HfLA website where changes appear: https://www.hackforla.org/communities-of-practice
- Issue template for making changes
  - [New Issue: Communities of Practice information updates ](https://github.com/hackforla/website/issues/new?assignees=&labels=role%3A+product%2CP-Feature%3A+Communities+of+Practice%2Ctime+sensitive%2CComplexity%3A+Missing%2Csize%3A+missing&projects=&template=communities-of-practice-information-updates.yml&title=Communities+of+Practice+information+updates%3A+%5BINSERT+NAME+OF+Community+of+Practice%5D)
  - [File: communities-of-practice-information-updates.yml](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/communities-of-practice-information-updates.yml)
  - issue templates directory: [.github/ISSUE_TEMPLATE](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)

### Recommended Action Items
- [x] Make 2 issues
- [ ] Discuss with team
- [ ] Let a Team Lead know

#### Issue 1 (small issue)
```
### Overview
We need to revise the Leadership Type on the Communities of Practice page, so that we only have two types across all the CoPs (less confusion for people onboarding).

### Action Items
Replace all instances of `Peer` to be `Community`  
- [ ] Edit the iu/ux.yml file 
- [ ] Edit the engineering.yml file 

### Resources
- https://www.hackforla.org/communities-of-practice
- location of files that need to be edited data/internal/communities
```
#### Issue 2 (Medium)
````
### Overview
We need to update the issue template for `Communities of Practice information updates` so that there are options for Leadership Type

#### Details
<details><summary>Currently has no option to edit</summary>

![image](https://github.com/hackforla/website/assets/37763229/adcf4419-c643-4289-a822-99c4826d15f5)
</p>
</details> 

<details><summary>Example of how the yes/no drop downs work</summary>
<p>

![image](https://github.com/hackforla/website/assets/37763229/84dabc36-d6aa-4ee5-85d3-c507af18cadc)

</p>
</details> 

### Action Items
Edit the issue template 
- [ ] Change Leadership Type: NO to have a YES/NO dropdown
- [ ] Add the following text under that
   ```
   If YES on Change Leadership Type, choose the Leadership Type; if NO, leave the field with the NA value:
   ```
- [ ] Add a dropdown with the following values, with the NA value being a default value
   - N/A
   - Mentor Led
   - Community Led




### Resources
- Issue template for making changes
  - [New Issue: Communities of Practice information updates ](https://github.com/hackforla/website/issues/new?assignees=&labels=role%3A+product%2CP-Feature%3A+Communities+of+Practice%2Ctime+sensitive%2CComplexity%3A+Missing%2Csize%3A+missing&projects=&template=communities-of-practice-information-updates.yml&title=Communities+of+Practice+information+updates%3A+%5BINSERT+NAME+OF+Community+of+Practice%5D)
  - [File: communities-of-practice-information-updates.yml](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/communities-of-practice-information-updates.yml)
  - issue templates directory: [.github/ISSUE_TEMPLATE](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)
  ````

**Comment by ExperimentsInHonesty** [comment]
Going to ask the CoP leads if they prefer peer or community led

**Comment by ExperimentsInHonesty** [comment]
the CoPs would like the options to be

- Mentor Led
- Community Led

**Comment by ExperimentsInHonesty** [comment]
@MarcosG119 don't forget to let us know your availability and ETA on making these issues.

**Comment by A-Wu5** [comment]
1. Sat-Sun 7pm-9pm
2. ETA: Sun EOD

**Comment by A-Wu5** [comment]
Linked Issue 1: #6861

**Comment by A-Wu5** [comment]
Linked Issue 2: #6862

**Comment by jphamtv** [comment]
Hey @A-Wu5, great work creating the issues. I reviewed them and they both look good.
