### ISSUE TITLE
Create yml data file for former-sponsors-partners

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6199]
### Overview
We require a means of storing data relating to former sponsors and partners.  In this issue we will create the file and populate it with data pertaining to Code for America.  

### Action Items
- [x] Open your IDE to `_data/internal` then create a new file `former-sponsors-partners.yml`
- [x] Paste this content:
```
- name: Code for America
  image: /assets/images/former-sponsors-partners/code-for-america.svg
  link: https://www.codeforamerica.org/
```

### Resources/Instructions
- This issue resulted from #5953

**Comment by aconstas** [comment]
**Availability**: 2/25 all day
**ETA for completion**: 2/25 (by end of day)
