### ISSUE TITLE
removed unused file current-projects.js

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6200]
### Overview
As developers we need to remove the unused file `assets/js/current-projects-check.js` in order to keep the codebase clear and avoid confusion.  

### Action Items
- [x] Open your IDE to `assets/js` and delete the file `current-projects-check.js`

### Resources/Instructions
- The need for the file https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects-check.js was obviated by #5978

**Comment by JackCasica** [comment]
Availability: Today,  tomorrow morning, and afternoon. 
ETA: Today
