### ISSUE TITLE
ER: Section 2.7e of CONTRIBUTING.md has code that will not work in terminal

### ISSUE THREAD

**Issue by danvgar** [hackforla/website#6209]
### Section 2.7e of CONTRIBUTING.md has code that will not work in terminal
 - [L705-710](https://github.com/hackforla/website/blob/f0e0f68f0509f32aad3b4fc6541bf18c01bc8bae/CONTRIBUTING.md?plain=1#L705) of the CONTRIBUTING.md include bash code that is not executable in a terminal. This forces new members to type the code out by hand rather than copy-and-pasting, which is not in line with the documentation standard of the rest of the document. 
 - Copy and pasting the code into the terminal will result in errors due to the comments below

#### Current screenshot below:

<img width="1022" alt="Screenshot 2024-02-01 at 6 22 52 PM" src="https://github.com/hackforla/website/assets/124107401/ecedd1f2-8db5-43b9-bdbf-bc9d85afec92">

### Issue you discovered this emergent requirement in
- #6047 

### Date discovered 
 - Feb 1, 2024

### Did you have to do something temporarily
- [X] YES
- [ ] NO

### Who was involved
@danvgar 

### What happens if this is not addressed
 - New members will be delayed in onboarding due to unnecessary confusion or requesting help in slack. 

### Resources
 - [Section 2.7e of CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream)

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Overview
The code block for _incorporating upstream changes_ at [2.7.e Working on an issue (5): Incorporating changes from upstream](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27e-working-on-an-issue-5-incorporating-changes-from-upstream) of `website/CONTRIBUTING.md` utilizes bash comments that may not run successfully on some operating systems or machines when copy-and-pasted. The comments need to be removed from this code block, and rewritten after the code-block for explanation purposes. .

### Action Items
- [ ] Open `website/CONTRIBUTING.md` in your IDE
- [ ] Go to section "2.7.e Working on an issue (5): Incorporating changes from upstream"
- [ ] At each line of code, remove all text after and inclusive of the `#` symbols. These are comments that prevent the code from executing properly. 
```
```bash
git checkout upstream-gh-pages # Move to the branch you want to merge with.
git pull  # This updates your tracking branch to match the gh-pages branch in this repository
git checkout gh-pages  # Move back to your gh-pages branch
git merge upstream-gh-pages  # Merge to bring your gh-pages current.```
```
- [ ] Replace the code block and subsequent text with the below 

~~~
1. Move to the branch you want to merge with.
```bash
git checkout upstream-gh-pages 
```

2. Update your tracking branch with the latest changes from the `gh-pages` branch in this repository
```bash
git pull  
```

3. Move back to your gh-pages branch
```bash
git checkout gh-pages  
```

4. Merge your changes back into your `gh-pages` branch.
```bash
git merge upstream-gh-pages
```
~~~

- [ ] With CONTRIBUTING.md still open, make a note of the section in which the replaced content appears, so that you will know where to look in the document to preview the change.
- [ ] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [ ] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
- [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- #6209

**Comment by ExperimentsInHonesty** [comment]
Don't each of these commands have to be run, and then wait for the response before you run the next? If so, each line of code must have its own copy block.

**Comment by danvgar** [comment]
> Don't each of these commands have to be run, and then wait for the response before you run the next? If so, each line of code must have its own copy block.

That's a good question, I feel like I have run multi-line commands before but it would be good to test and verify. I see no reason they couldn't be separate code blocks as well just for reliability

**Comment by danvgar** [comment]
> > Don't each of these commands have to be run, and then wait for the response before you run the next? If so, each line of code must have its own copy block.
> 
> That's a good question, I feel like I have run multi-line commands before but it would be good to test and verify. I see no reason they couldn't be separate code blocks as well just for reliability

Update, just confirmed you can run blocking multi-line commands on the terminal, ending each line with `&& \` to signal to the terminal to execute the command and wait for completion prior to trying the next command

Example:

```bash
git status && \
git add . && \
git commit && \ 
git push
```

**Comment by ExperimentsInHonesty** [comment]
@danvgar 
Please rewrite this so that each line is on its own copy block.

**Comment by danvgar** [comment]
> @danvgar Please rewrite this so that each line is on its own copy block.

Happy to, @ExperimentsInHonesty ! Just to clarify, which of the below two things are you asking me to do?
1. Rewrite this ER with more clear instructions so that it can be turned into an Issue for someone else to pick-up
2. Treat this ER as an Issue already and go update the CONTRIBUTING.md

**Comment by roslynwythe** [comment]
@danvgar please update the ER with more clear instructions, then apply the "ready for dev lead" label.  Thanks!

**Comment by danvgar** [comment]
I'm back from my PTO and will jump on turning this ER into an issue by EOW Sun Mar 3. Thank you @roslynwythe !

**Comment by danvgar** [comment]
> @danvgar please update the ER with more clear instructions, then apply the "ready for dev lead" label. Thanks!

@roslynwythe ER has been updated with a draft issue and is ready for review. `ready for dev lead` label has been added.

**Comment by danvgar** [comment]
> > > Don't each of these commands have to be run, and then wait for the response before you run the next? If so, each line of code must have its own copy block.
> > 
> > 
> > That's a good question, I feel like I have run multi-line commands before but it would be good to test and verify. I see no reason they couldn't be separate code blocks as well just for reliability
> 
> Update, just confirmed you can run blocking multi-line commands on the terminal, ending each line with `&& \` to signal to the terminal to execute the command and wait for completion prior to trying the next command
> 
> Example:
> 
> ```shell
> git status && \
> git add . && \
> git commit && \ 
> git push
> ```

@ExperimentsInHonesty I've tested the code block made in the ER's proposed solution's section and can confirm it runs each line successively without the need for `&& \` or separate code blocking.

**Comment by roslynwythe** [comment]
Hi @danvgar In this https://github.com/hackforla/website/issues/6209#issuecomment-1953353185 Bonnie had asked for each command to be in its own copy block.  I don't see those changes in the "Potential Solutions [draft]" section of this issue, but perhaps you made those changes in a new issue.  If so, please provide a link to that issue.  Thanks!

**Comment by danvgar** [comment]
> Hi @danvgar In this [#6209 (comment)](https://github.com/hackforla/website/issues/6209#issuecomment-1953353185) Bonnie had asked for each command to be in its own copy block. I don't see those changes in the "Potential Solutions [draft]" section of this issue, but perhaps you made those changes in a new issue. If so, please provide a link to that issue. Thanks!

I will be updating this by EOD Thu June 13!

**Comment by danvgar** [comment]
> Hi @danvgar In this [#6209 (comment)](https://github.com/hackforla/website/issues/6209#issuecomment-1953353185) Bonnie had asked for each command to be in its own copy block. I don't see those changes in the "Potential Solutions [draft]" section of this issue, but perhaps you made those changes in a new issue. If so, please provide a link to that issue. Thanks!

@roslynwythe @ExperimentsInHonesty The draft has been updated with code blocks separated out. Let me know your thoughts

**Comment by roslynwythe** [comment]
@danvgar great job writing this ER it is ready for prioritization.  If you would like to write the issue, please remain assigned and make a comment for @ExperimentsInHonesty letting her know.  Thank you!

**Comment by ExperimentsInHonesty** [comment]
@danvgar this is excellent.  I am going to add a time sensitive label to this and put it in progress.  I am assuming you want to make the issue.  If you don't want to make the issue remove your assignment and re-ad the ready for prioritization label to it and move it to the ER column.

**Comment by danvgar** [comment]
> @danvgar this is excellent. I am going to add a time sensitive label to this and put it in progress. I am assuming you want to make the issue. If you don't want to make the issue remove your assignment and re-ad the ready for prioritization label to it and move it to the ER column.

@ExperimentsInHonesty Yep, happy to create the issue this week!

**Comment by danvgar** [comment]
Issue has been created, this ER may be closed!
