### ISSUE TITLE
The Hack for LA website bot removed me!

### ISSUE THREAD

**Issue by angela-lee1** [hackforla/website#6213]
The Hack for LA website bot removed me!
I am responding to Issue #6211 because I want to come back.
Please add me back to the 'website-write' team, I am ready to work on an issue now.

## Dev Leads
This member was previously on the 'website-write' team and is now asking to be reactivated. Please see the referenced issue.

_Originally posted by @awlFCCamp in https://github.com/hackforla/website/issues/6211#issuecomment-1924251094_

**Comment by t-will-gillis** [comment]
Hey @awlFCCamp You are added back to 'website-write'
