### ISSUE TITLE
ER: Inconsistencies in CONTRIBUTING.md

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6218]
### Emergent Requirement - Problem
The changes to `CONTRIBUTING.md` per issue #5697 and its related PR #6206 lead to a couple of inconsistencies that I unfortunately noticed after I merged the PR:
- [ ] Line 533 is missing a colon at the end, which similar lines provide.
- [ ] Lines 535-537: Throughout the `CONTRIBUTING.md` document, all of the commands (e.g. `git checkout gh-pages`, `git commit -m "your message here"`, etc.) are shown in Markdown as `bash` rendered. To be consistent, the commands demonstrated by these lines should be the same, e.g.:
~~~suggestion
```bash
git pull upstream gh-pages
```
~~~

### Issue you discovered this emergent requirement in
- #5697 
- #6206

### Date discovered 
2/2/24

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@t-will-gillis 

### What happens if this is not addressed
Code is inconsistent

### Resources
https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#27-working-on-an-issue

### Recommended Action Items
- [X] Make a new issue
- [x] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
See above

**Comment by Dartis4** [comment]
Availability: I'll be working on this issue on Monday and possibly Tuesday throughout the day.
ETA: Hopefully by the end of the day Monday.

**Comment by t-will-gillis** [comment]
Created issue #6684 to address this ER, closing.
