### ISSUE TITLE
ER: Update two files with Slack IDs

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#6224]
### Emergent Requirement - Problem
We use the name of some Slack channels, and for others we use the ID.  We are standardizing on the ID.  Find each page that uses a name instead of an ID and replace it.

### Issue you discovered this emergent requirement in
N/A

### Date discovered 
2024-02-04

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty @roslynwythe 

### What happens if this is not addressed
nothing, the links are just not standardized.

### Resources
Notes from an agenda
we have references to https://hackforla.slack.com/messages/hfla-site/ in the contributing file https://github.com/hackforla/website/blob/6b06f0c0a87a4b4c64bd0be634dbc16af95ff025/CONTRIBUTING.md?plain=1#L308 which seem to resolve.
we have reference to https://hackforla.slack.com/messages/admin on the join https://github.com/hackforla/website/blob/6b06f0c0a87a4b4c64bd0be634dbc16af95ff025/pages/join-us.html#L43 and that seems to resolve just fine.  but are non standard.

### Recommended Action Items
- [x] Make 2 new issues
  - The contributing issue should be the small one because of the testing it requires.
  - The join issue should be a good first issue.
- [x] Discuss with team
- [ ] Let a Team Lead know

**Comment by Happyashbunny** [comment]
Hey there, I am interested on working on this issue, can you please elucidate on it a little more.

**Comment by ExperimentsInHonesty** [comment]
the contributing issue should be the small one because of the testing it requires.
the join issue should be good first issue

**Comment by marioantonini** [comment]
i. Availability: Fr-Sat 10am-2pm
ii. ETA: 5/11/2024

**Comment by marioantonini** [comment]
Created 2 issues: 
- #6847
- #6848 
Both of them I assigned the label `good first issue` since I do not believe additional testing besides making sure the link still references the Slack channel needs to be done. If this is not the case, feel free to let me know here.

@roslynwythe @ExperimentsInHonesty I do have a question for moving forward with this issue. Do I list the issues created as dependencies, so that once they get approved this can be closed? Do I just close this? Or what is the best way to proceed?

**Comment by marioantonini** [comment]
- Split issue #6848, adding #6858

**Comment by ExperimentsInHonesty** [comment]
Three issues have been created
- #6847
- #6848
- #6858

**Comment by ExperimentsInHonesty** [comment]
@marioantonini Please revise issues the following issues with the changes we made to #6847 (overview, add the archives in to the link, remove the link to that epic, change the title, add milestone).
- #6848
- #6858

After you have revised those issues, go ahead and add the `ready for prioritization` label to the issues, and close this issue.

**Comment by ExperimentsInHonesty** [comment]
For future reference, this ERs scope got expanded to fix the messages to archives change in the Slack links.  Because it would have made an unresolvable merge conflict if we had made separate issues to change it.

**Comment by marioantonini** [comment]
Closing this issue as the following issues have been revised:
- #6848 
- #6858
