### ISSUE TITLE
Correct misspelling in alt text in Communities of Practice page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6232]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.  In this issue a misspelling in the "alt text" of an image on the Community of Practice page will be corrected.  

### Action Items
- [x] For the file `/pages/communities-of-practice.html`, correct the spelling from "commmunity" to "community", so

  ```
   <img class="header-hero-image" src="/assets/images/communities-of-practice/comm-prac-header.svg" alt="commmunity of practice header" />
  ```
  becomes
  ```
   <img class="header-hero-image" src="/assets/images/communities-of-practice/comm-prac-header.svg" alt="community of practice header" />
  ```
- [x] Use Docker to test changes locally, in both desktop and mobile views

### Resources
Website page with issue: https://www.hackforla.org/communities-of-practice
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/pages/communities-of-practice.html

**Comment by shrinjayshresth1** [comment]
Can i work on this issue @roslynwythe?

**Comment by DeniseLewis1** [comment]
Availability for this week: 4/3 12:00PM - 3:00PM & 4/4 12:00PM - 3:00PM
My estimated ETA for completing this issue: By 3:00PM on 4/4
