### ISSUE TITLE
Correct Misspelling in _guide-pages/survey-reporting-dashboard-guide.html

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6233]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
Our website needs to be free of misspellings so that our reputation for quality is maintained.  

### Action Items
- [ ] For the file `_guide-pages/survey-reporting-dashboard-guide.html`, locate the text:
```
To create a chart, whether direclty in Google Sheets
```
  and correct the spelling from "direclty" to "directly", so that it reads
```
To create a chart, whether directly in Google Sheets
```
- [ ] Use Docker to test changes locally, in both desktop and mobile views

### Resources
Website page with issue: https://www.hackforla.org/guide-pages/survey-reporting-dashboard-guide
File on GitHub: https://github.com/hackforla/website/blob/gh-pages/_guide-pages/survey-reporting-dashboard-guide.html

**Comment by JessicaLucindaCheng** [comment]
@roslynwythe The formatting in this issue looks weird. Can you please fix it?

Once you fix the formatting, you can add the `Ready for Prioritization` label back on. Thank you.

**Comment by roslynwythe** [comment]
Thank you @JessicaLucindaCheng.  I corrected the formatting.
