### ISSUE TITLE
Move Code for America svg to new folder assets/images/former-sponsors-partners

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6242]
### Overview
We need to move the Code for America graphic file into a new folder to be used for storing images related to former sponsors and partners. 

### Action Items
- [x] Create a new folder `/assets/images/former-sponsors-partners`
- [x] Copy the file `code-for-america.svg` from `/assets/images/sponsors/` into the new folder
- [x] Delete the file `/assets/images/sponsors/code-for-america.svg`

### Resources/Instructions
- This issue was created from #5953

**Comment by angela-lee1** [comment]
Availability: 6:00 pm -10:00 pm 3/2
ETA: EOD 3/2
