### ISSUE TITLE
Fix "alt" text values in project.md files

### ISSUE THREAD

**Issue by KianBadie** [hackforla/website#625]
### Overview
For a couple of project.md files, the text value of the "alt" text produces errors in how the alt text is actually produced on the website (see image bellow). Verify that alt text is correct on the site for each project and if not, fix the "alt" text in the project.md cards so that it is correct. 

Another route could be to change the way Jekyll incorporates the alt text in the _includes/project-card.html. Maybe putting it in quotes would help. I think this would still require editing the Project.md files though to fix other undesirable outputs though. Just double check the produced alt text if you do it this way too.

### Action Items
- [x] Change alt text values on project cards relative to this issue
- [ ] (Not required, but may be useful) Change the way _include/project-card.html incorporates alt text
- [x] Verify all project cards produce correct alt text on the website.

### Resources/Instructions
- To verify the alt text, you can inspect the element and see in the DOM a attribute named "alt" for that image. Here is an incorrect example (Civic Tech Index):
![Screenshot from 2020-07-20 21-45-59](https://user-images.githubusercontent.com/18221058/88137415-56d18900-cba0-11ea-9e37-c125b77e4018.png)
Here is a picture of a correct example (Engage):
![Screenshot from 2020-07-21 22-20-59](https://user-images.githubusercontent.com/18221058/88137491-7b2d6580-cba0-11ea-9e35-74de63d1686d.png)
- I know 311 Data, Civic Tech Index, and Civic Opportunity Project produce incorrect alt text for sure, so that can be a starting point. Refer to project.md files like Engage to see correct implementation.

**Comment by drubgrubby** [comment]
Kian suggested a better fix so I made a new branch and PR.  #662 - which is in Draft mode - is the first one that should not be merged.  Just want to confirm the preferred way to "delete" un-merged PR before I try to do that.
