### ISSUE TITLE
Improve the drop downs on Wins page to avoid unnecessary wrapping 

### ISSUE THREAD

**Issue by Thinking-Panda** [hackforla/website#6272]
### Overview
We need to adjust the display of the dropdowns on Wins page so the project names do not wrap to the next line. 
<details>
<summary>Current appearance of the Wins page (tablet screen widths)</summary>

![ER6225](https://github.com/hackforla/website/assets/122488603/def341e4-35df-4c42-af9d-ac7d257dca75)

</details>

### Action Items
- [x] Locate the file  `_sass\elements\_old_dropdown_filters.scss`
- [x] Make necessary changes to the `scss` file  so the project names do not wrap to the next line. Pay particular attention to media queries that affect layout in the range between mobile and desktop views. When possible, media queries should be based on the breakpoints found in `/_sass/varaibles/_layout.scss`
- [x] Using Docker, test the Wins page locally in various viewport sizes. Please ensure that the project names do not wrap in tablet, desktop and large desktop sizes.

### Resources/Instructions

- SCSS classes for styling the drop down menus are stored in `_sass/elements/_old_dropdown_filters.scss` 
- [Wins Page](https://www.hackforla.org/wins/)
- This issue resulted from https://github.com/hackforla/website/issues/6225

**Comment by Thinking-Panda** [comment]
@bonniewolfe 
`Bonnie says: If @mademarc has not done a medium size issue yet, please assign him to this issue when its ready`

**Comment by roslynwythe** [comment]
Hi @Thinking-Panda great job writing this issue.  I have a few suggestions:
- Along with the second action item I would add "Pay particular attention to media queries that affect layout in the range between mobile and desktop views.  When possible, media queries should be based on the breakpoints found in `/_sass/varaibles/_layout.scss`
- Along with the third action item, please mention that testing should be performed for mobile, tablet, desktop and large desktop sizes.

**Comment by ExperimentsInHonesty** [comment]
@Thinking-Panda Have you had a chance to update this draft with Roslyn's comments yet.  I don't see any activity in this issue for the last 2 weeks

**Comment by Thinking-Panda** [comment]
@ExperimentsInHonesty I have updated the action items based on Roslyn's comment.

**Comment by Thinking-Panda** [comment]
@mademarc Whenever possible please update your availability, and ETA for this issue. Thanks!

**Comment by mademarc** [comment]
Hey @Thinking-Panda  here is the info below regarding this issues:

i. Availability: 03/19/2024

ii. ETA: 04/09/2024

**Comment by mademarc** [comment]
Progress: gonna work on a assigned medium issue coming up and need to re install docker/git on my local machine 1st.

Blockers: No Blockers

Availability: 03/27/2024
ETA: 04/23/202

**Comment by ExperimentsInHonesty** [comment]
@mademarc When I assigned you this issue it was with the understanding that you were ready to start working on it. If you still have not started working on it and are not going to be ready for a week or more, I would like you to unassign this issue and add the ready for prioritization label and put it back into the new issue approval column.  Otherwise, we will expect an update.

**Comment by mademarc** [comment]
Hey @bonniewolfe Thanks for the message and i shall start doing this By next week ASAP as you can see on my current update status

**Comment by mademarc** [comment]
Progress: Going to start working  a assigned medium issue ASAP coming up next week and i just need to re install docker/git on my local machine 1st.

Blockers: No Blockers

Availability: 04/09/2024
ETA: 04/26/202

**Comment by ExperimentsInHonesty** [comment]
@mademarc I am unassigning you from the issue.  When you have your development environment back up and are ready to work on issues, you can message in the hfla-site slack channel for help finding one.

**Comment by gdkoo** [comment]
**Availability**: Wednesday and Thursday evening
**ETA**: April 17

**Comment by mademarc** [comment]
Hey @bonniewolfe Thank you for the notice and the heads up. That said i shall your suggestions/recommendations once i have my development environment back up on my end.

**Comment by gdkoo** [comment]
Hi @ExperimentsInHonesty and @roslynwythe:  Adjustments were made following the recommendations from [issue 6225](https://github.com/hackforla/website/issues/6225) to increase the breakpoint of the existing media query that creates two columns to fill the page to prevent wrapping. 

Wrapping occurs from 659 px up to 1002px, but neither are defined breakpoints in `_sass/variables/_layout.scss `, so I adjusted the media query to apply to a max breakpoint of the browser defined laptop size- 1024px. It made more sense to me than using the arbitrary number 1002px, or the `screen-desktop-large` which would mean the columns would always fill the page even when it's not necessary. Let me know if that works and I will submit the PR.

**Comment by gdkoo** [comment]
**Progress:** Made changes and ready to submit PR. 
**Blockers:** It wasn't clear at first the scope of changes that needed to be made (new media queries, what type of formatting). I looked back at the initial ER to find instructions to simply change the breakpoint for the existing media query in the file.  The range of screen sizes where wrapping occurs are not covered by the defined breakpoints in `_sass/variables/_layout.scss ` and includes sizes smaller than tablet and up to desktop. 
**Availability:** Evenings
ETA: By the of the week
**Pictures:** 
Desktop view after changes:
<img width="1108" alt="desktop-nowrap" src="https://github.com/hackforla/website/assets/110444314/6f035769-69bb-4a6c-9d6c-79e11cc8a871">
Tablet view after changes: 
<img width="879" alt="tablet-nowrap2" src="https://github.com/hackforla/website/assets/110444314/8499851b-79fe-4b86-89a3-7e9a1fee19af">
