### ISSUE TITLE
ER: Modify JavaScript so Ruby and Svelte are included in the Filter on Projects page

### ISSUE THREAD

**Issue by jphamtv** [hackforla/website#6274]
### Emergent Requirement - Problem
Ruby and Svelte languages are being excluded from the 'Languages / Technologies' filter on the Project page. 

### Issue you discovered this emergent requirement in
- #5978

### Date discovered 
12-27-23

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@t-will-gillis 

### What happens if this is not addressed
Users will not be able to filter projects by Ruby language or Svelte framework. This may be a minor issue since the related projects are not currently active. 

### Resources
[assets/js/current-projects.js ](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
[Projects page](https://www.hackforla.org/projects/)
[Home page](https://www.hackforla.org/#)
[See comments where the issue was found](https://github.com/hackforla/website/pull/5978#pullrequestreview-1797662017)

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
Modify the code so they are included in the 'Languages / Technologies' filter on the Projects and Home pages.

### Action Items
- [ ] Replace the following code:
```
'technologies': [...new Set(sortedProjectData.map(item => (item.project.technologies && item.project.languages?.length > 0) ? [item.project.languages, item.project.technologies].flat() : '').flat() ) ].filter(v=>v!='').sort(),
```
- [ ] With:
```
'technologies': [
    ...new Set(
        sortedProjectData.map(item => {
            let combined = [];
            if (item.project.languages?.length > 0) {
                combined = combined.concat(item.project.languages);
            }
            if (item.project.technologies?.length > 0) {
                combined = combined.concat(item.project.technologies);
            }
            return combined;
        }).flat()
    )
].filter(v => v).sort(),

**Comment by jphamtv** [comment]
Hi @ExperimentsInHonesty - I've prepared the ER you requested. As discussed in last Monday's meeting, I created the issue before understanding the correct process order (ER first, then create an Issue if approved). If this ER is approved, the issue is ready at #6071.

**Comment by roslynwythe** [comment]
- Thank you @jphamtv for writing issue #6071.  It looks great and is ready for prioritization, and so this ER can be closed as completed.
