### ISSUE TITLE
Regularize existing tems in "Technologies"

### ISSUE THREAD

**Issue by cnk** [hackforla/website#628]
One project has a / between technologies.
We have several variations on React - consolidate to one
Move SQL (PostgreSQL) to just PostgreSQL

<img width="222" alt="Screen Shot 2020-07-22 at 10 16 16 AM" src="https://user-images.githubusercontent.com/5952/88207547-cf6a3100-cc04-11ea-97c4-7b8cb10b002a.png">

**Comment by alexandrastubbs** [comment]
Raudel to work on this once he is set up in GitHub.

**Comment by rblaz001** [comment]
I wrote a Python script that creates a spreadsheet listing projects with their technologies. This way I can know what .md files need to be updated.

**Seven projects contain a list of technologies**

![project_technology_list](https://user-images.githubusercontent.com/35281980/88508280-41d76a00-cf93-11ea-826f-73c3cf470614.png)

**Here are the projects listed by technology**

![sorted_by_technology](https://user-images.githubusercontent.com/35281980/88508290-4865e180-cf93-11ea-848a-1753c95f9ca8.png)

Ideas for Regularization:

- Change all instances of **React** to **ReactJS**.
- As mentioned by @cnk, change entries containing technologies separated by **'/'** in to separate entries.
- Change entry containing **Flask (Sanic)** to separate entries.
- Move **SQL (PostgreSQL)** to just **PostgreSQL**.

I'm unsure about **Node (MERN)** entry. Edit: **MERN** is a technology stack so should I just add entries for **MongoDB**, **Express**, **ReactJS**, and **Node.js**?

Any thoughts before I move forward?

@ExperimentsInHonesty

**Comment by cnk** [comment]
I like all your ideas for regularization.

**Comment by rblaz001** [comment]
Finished regularization of technologies for current build. I have not created a PR because there are pending PRs that add technologies to other projects and they need to be regularized as well.

The pending PRs I'm referring to are: #630 #634 #635 #636 #637 #638 #639

![Screenshot from 2020-07-27 10-19-22](https://user-images.githubusercontent.com/35281980/88571582-b988b180-cff2-11ea-9239-ea73818a97ea.png)

**Comment by rblaz001** [comment]
Included regularization for recent merged pull requests.

- Mongo changed to MongoDB
- Node changed to Node.js
- React changed to ReactJS
- Azure App Service for Containers changed to Azure App Service

Note: The "Technology" filter list is starting to get really long.

![Screenshot from 2020-07-27 19-49-54](https://user-images.githubusercontent.com/35281980/88614776-53794a00-d045-11ea-8c89-a86e2e302eb6.png)
