### ISSUE TITLE
Food Oasis project page update

### ISSUE THREAD

**Issue by hanapotski** [hackforla/website#6284]
### Overview
The Food Oasis project page needs to be updated
### Action Items
- [ ] Update the [Food Oasis project page](https://www.hackforla.org/projects/food-oasis) and add these devs to the `Current Project Team`:
```
Andy Arensman - Full Stack Engineer
Belen Garcia Martinez - Full Stack Engineer
June Zhao - Full Stack Engineer
Krista Strucke - Full Stack Engineer
Qiqi Zheng - Full Stack Engineer
Saumil Dhankar - Full Stack Engineer
```

**Comment by roslynwythe** [comment]
I've asked the Food Oasis team to submit an issue using the template "Project Profile Card Review and Update".
