### ISSUE TITLE
ER: Update Project Profile: Food Oasis

### ISSUE THREAD

**Issue by qiqicodes** [hackforla/website#6285]
### Dependency
- [x] #6312 
- [x] #6310
- [x] #6311 

### Project Name

Food Oasis

### Project Card URL

food-oasis.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Seiko Igi
- [x] Name: Stacey Rebekah Scott
- [x] Name: Erin Dean

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Andy Arensman
GitHub Handle: andyarensman
Role: Full Stack Engineer
Slack Member ID: U04PFGPR19Q

- [x] Name: Belen Garcia Martinez
GitHub Handle: 93Belen 
Role: Full Stack Engineer
Slack Member ID: U056TQ9UA3C

- [x] Name: June Zhao
GitHub Handle: junjun107
Role: Full Stack Engineer
Slack Member ID: U03UWG0EP7V

- [x] Name: Krista Strucke
GitHub Handle: kurikurichan
Role: Full Stack Engineer
Slack Member ID: U04PHV2HUF6

- [x] Name: Qiqi Zheng
GitHub Handle: qiqicodes
Role: Full Stack Engineer
Slack Member ID: U01LM6SE70A

- [x] Name: Saumil Dhankar
GitHub Handle: saumildhankar
Role: Full Stack Engineer
Slack Member ID: U02AG2K2BB3

### Project Status

Active

**Comment by JessicaLucindaCheng** [comment]
Issue Writing
- Availability: 6 hours
- ETA: Sunday, February 18, 2024

**Comment by JessicaLucindaCheng** [comment]
@qiqicodes I didn't see a Slack ID for June Zhao. Can you please confirm this is June's Slack profile: https://hackforla.slack.com/team/U03UWG0EP7V? Thank you.

**Comment by qiqicodes** [comment]
> @qiqicodes I didn't see a Slack ID for June Zhao. Can you please confirm this is June's Slack profile: https://hackforla.slack.com/team/U03UWG0EP7V? Thank you.

yes June's slack ID is U03UWG0EP7V

**Comment by qiqicodes** [comment]
Can we remove the following from the team?
- Seiko Igi
- Stacey Rebekah Scott
- Erin Dean

**Comment by JessicaLucindaCheng** [comment]
> Can we remove the following from the team?
> 
> * Seiko Igi
> * Stacey Rebekah Scott
> * Erin Dean

Yes, I have included them in your request to be removed from the Food Oasis page.

**Comment by qiqicodes** [comment]
> > Can we remove the following from the team?
> > 
> > * Seiko Igi
> > * Stacey Rebekah Scott
> > * Erin Dean
> 
> Yes, I have added them to your request.

Thanks Jessica.

**Comment by JessicaLucindaCheng** [comment]
All issues have been written for this request and have been added to the Dependency section.

**Comment by JessicaLucindaCheng** [comment]
@ Website Team dev lead
Once the issue(s) in the Dependency section are merged, 
- [x] Close this ER
- [x] Move this ER to the UAT column
- [x] Contact the author of this ER to approve the changes on the [Food Oasis](https://www.hackforla.org/projects/food-oasis) page and add a `ready for stakeholder` label
- [x] Once the changes have been accepted by the author of this ER, remove the `ready for stakeholder` label and add a `ready for product` label. Also, leave a comment that this ER is ready for further UAT and QA by product.

**Comment by JessicaLucindaCheng** [comment]
@qiqicodes 
Please let us know if the changes made to the [Food Oasis](https://www.hackforla.org/projects/food-oasis) page match what you requested by adding a comment to this issue. Thank you.

**Comment by JessicaLucindaCheng** [comment]
@hackforla/website-pm The changes requested have already been accepted by the author of this issue. This issue is now ready for you to UAT and QA.

**Comment by JessicaLucindaCheng** [comment]
This issue has been in UAT for a long time, so I am moving this to QA.
