### ISSUE TITLE
ER: Update code behind Events page so events with project names that contain "test" are not displayed

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#6289]
### Emergent Requirement - Problem
Tests that VRMS are doing are still showing up on the events page.  We can fix that by filtering them out.

### Issue you discovered this emergent requirement in
-none

### Date discovered 
2024-02-05

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
We sometimes will have VRMS test projects show up on the events page

### Resources
@roslynwythe said: 
- There was an issue to cover this, but it didn't explicitly state that "test" might be a substring #6082
- The current code will filter out an event if the project name begins with "test" (case-insensitive). Should I proceed with an ER to change that logic, so an event will be filtered if "test" appears anywhere in the project name? 
@ExperimentsInHonesty says:  yes, let's do that (this is that ER).

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

**Comment by freaky4wrld** [comment]
- @ExperimentsInHonesty issue #6369 has been created for the ER feel free to edit and suggest changes

**Comment by freaky4wrld** [comment]
- Progress: The issue is corrected and has a dependency
- Availability: Evenings

**Comment by elliot-d-kim** [comment]
I think a parallel problem exists on the [Project Meetings](https://www.hackforla.org/project-meetings) page. Under Wednesday, the last item is "10:00 pm - 11:00 pm [Testing](http://localhost:4000/project-meetings/updated_website.com/test34) Test-EventName, Testing." I didn't find an ER or issue specific to the Project Meetings page, should these be rolled into one issue or should I create a new ER/issue that mirrors this one?

**Comment by elliot-d-kim** [comment]
Additionally, all the 'Admin team' links are https://www.hackforla.org/undefined.

**Comment by freaky4wrld** [comment]
- Progress: The issue is corrected and has a dependency
- Blockers: Waiting it to be reviewed
- Availability: Evenings
