### ISSUE TITLE
ER: The SDG target on the project page needs to be left aligned

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#6290]
### Emergent Requirement - Problem
The SDG target text on the project page needs to be left aligned and its currently center aligned.

### Issue you discovered this emergent requirement in
- #5809 

### Date discovered 
2024-02-13

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
it looks bad

### Resources
https://www.hackforla.org/projects/lucky-parking
<details><summary>screenshot of lucky parking</summary>

![image](https://github.com/hackforla/website/assets/37763229/1aae34aa-87a6-41c7-8b70-0749c7952101)
 
</details> 

https://www.hackforla.org/projects/311-data
<details><summary>Screenshot of 311-data</summary>

![image](https://github.com/hackforla/website/assets/37763229/e55a2d2d-8374-4eda-8371-a1c4ca79d7d2)

</details> 

FYI - not all project pages have SDGs

https://github.com/hackforla/website/blob/5b404ce3fb88c762373e68ec0272af2c5313dac4/_includes/program-area-pages-cards.html lines 35-39 seem to reference the content, but I looked up the classes and could not find references to those classes in any sass files.

### Recommended Action Items
- [x] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

**Comment by t-will-gillis** [comment]
- Issue #6683 created for this ER, issue is resolved.
