### ISSUE TITLE
Replace Team Hands Middle image in Credits page on Feature Homepage Launch branch

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6296]
### Overview
We need to replace the "Team Hands Middle" graphic on the Credits page, within the feature homepage branch.  The new graphic file should simply replace the existing file, so the filename and references to the image will be unchanged.  

### Action Items
- [x] Work on this issue will be merged into hackforla/feature-homepage-launch.  For information about working on a feature branch, see https://github.com/hackforla/website/wiki/How-to-work-off-of-a-feature-branch
- [x] Download the "New image" from the Resources section below, then rename it `/team-hands-middle.jpg` and save it in the folder `/assets/images/credits`
- [x] Using Docker, view the Credits page (/credits) and confirm that the appearance of the credit for the "Team Middle Hands" image (text and image) matches the "Current appearance of the Credit for the Team Middle Hands image" screenshot below, except for the rotation of the image

### Resources/Instructions
<details><summary>New Image</summary>

![team-hands-middle](https://github.com/hackforla/website/assets/5314153/41ab77d4-53d8-422d-a6bc-4272c2446d21)

</details> 

<details><summary>Current appearance of the Credit for the Team Middle Hands photo</summary>

![image](https://github.com/hackforla/website/assets/5314153/627dd2d3-0f99-4c36-8081-e26e5e13a8de)

</details> 

Style Guide https://cdn.shopify.com/s/files/1/0589/1676/5845/files/HowToUse-ProgressPrideFlag-DanielQuasar.pdf?v=1629073782

**Comment by evan-ishibashi** [comment]
i. Availability: Today, Feb 17th, Afternoon
ii. ETA: Today, Feb 17th, by eod

**Comment by evan-ishibashi** [comment]
@roslynwythe Can you provide the style guide link? I'm assuming the photo should comply with the guide since I was not requested to make any edits to the photo itself. Just wanted to double check to make sure. Thanks!

**Comment by roslynwythe** [comment]
@evan-ishibashi thank you for noticing this.  
Style Guide https://cdn.shopify.com/s/files/1/0589/1676/5845/files/HowToUse-ProgressPrideFlag-DanielQuasar.pdf?v=1629073782

**Comment by ExperimentsInHonesty** [comment]
@evan-ishibashi I am moving this issue to the in progress column, since you are working on it. On future issues please move the issue after you self assign.

**Comment by LRenDO** [comment]
Hi @evan-ishibashi!  Thanks for working on this issue. If you're still working on it, please add an update. If you're not able to continue to working on it, leave us a comment to let us know. If we don't hear from you soon, we will remove you from the issue. Thanks!

**Comment by evan-ishibashi** [comment]
Apologies on the delay here!

Progress: Re-work the PR since the last one included all historical commits
Blockers: Need to revisit operating on a feature branch, and get that squared away
Availability: Couple hours tonight and tomorrow
ETA: Tomorrow EOD

**Comment by ExperimentsInHonesty** [comment]
This issue didn't automatically close because it was on a feature branch.
