### ISSUE TITLE
Continuation: Update chips labels from plural to singular

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6298]
### Overview
Currently, chip label prefixes for the "Program Areas" and "Languages" filter groups are shown as "Programs" and "Languages" even though singular filter items are listed for either label. This can be confusing to users, so we want to update the chip label prefixes to "Program" on and "Language" respectively. (See related issue #4647.)

### Action Items

- [x] Check the current state of search chip labels under Applied Filters on the [Projects](https://www.hackforla.org/projects/) and [Projects-Check](https://www.hackforla.org/projects-check/) pages.
  - [x] Apply some of the filters to see how the current chips appear under Applied Filters.
- [x] Explore `assets/js/current-projects.js` and understand how the programming of the filters and chips work.  
  - [x] Change the chip label prefix "Programs" to "Program" (on Projects page).
  - [x] Change the chip label prefix "Languages" to "Language" (on Projects-Check page).
  - [x] Using Docker, confirm that both pages display correctly when applying various selections.  
  
Merge team: when complete
- [x] Release dependency on #4648 

### Resources/Instructions

- Chip labels can be found on the [Projects page](http://hackforla.org/projects)
- [current-projects.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects.js)
- [current-projects-check.js](https://github.com/hackforla/website/blob/gh-pages/assets/js/current-projects-check.js)
- [Jekyll Front Matter](https://jekyllrb.com/docs/front-matter/)
- See associated ER for this issue: #4563 
- and #6297

**Comment by jtw007** [comment]
Availability: tomorrow and Wednesday morning and early afternoon
ETA: Thursday at latest
