### ISSUE TITLE
Securing `wins.js` from XSS vulnerability due to innerHTML

### ISSUE THREAD

**Issue by freaky4wrld** [hackforla/website#6303]
### Overview

As developers we aim to protect JavaScript files from XSS vulnerabilities, preventing malicious script injections that can compromise user security.

### Action Items

- [x] Open the file `assets/js/wins.js` in your IDE
- [x] Search the instances of `innerHTML` in the file.
- [x] Replace the instances of the `innerHTML` property with `textContent` , using the `createElement` method for creating DOM elements where necessary
- [x] Use Docker to test the [Wins page](https://www.hackforla.org/wins) at mobile, table, and desktop screen sizes

### Resources/Instructions

- https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement
- https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent
- https://medium.com/front-end-weekly/javascript-innerhtml-innertext-and-textcontent-b75ec895cbe3
- https://github.com/hackforla/website/blob/gh-pages/assets/js/wins.js
- https://www.hackforla.org/wins
- This issue resulted from #5654

**Comment by freaky4wrld** [comment]
- @roslynwythe created a issue for option 1 for the ER #5654, please check and suggest changes

**Comment by roslynwythe** [comment]
Thank you @freaky4wrld - looks good to me.

**Comment by danvgar** [comment]
Happy to take on this issue. Just assigned it to myself and will provide an update by EOW.

**Comment by ExperimentsInHonesty** [comment]
@danvgar I am moving this issue to the in progress column, since you are working on it. On future issues please move the issue after you self assign.

**Comment by danvgar** [comment]
> @danvgar I am moving this issue to the in progress column, since you are working on it. On future issues please move the issue after you self assign.

Ah sorry, thank you for catching that, @ExperimentsInHonesty !

**Comment by danvgar** [comment]
Apologies, I've been sick on-and-off the past week and have not been able to sit with this. I expect it to be completed by EOW Sun Mar 17, if not sooner!
