### ISSUE TITLE
Citizen Engagement

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#632]
### Overview
We need a page for the Citizen Engagement Projects so that we can guide interested citizens and Neighborhood Councils to our Citizen projects with the purpose of increasing engagement.

### Action Items
- [x] Product
   - [x] Identify requirements for page
      - [x] Summary of what our Citizen Engagement Portfolio is about
      - [x] How to get involved paragraph and email citizen-engagement@hackforla.org
      - [ ] Project info
         - [x] Description (can use project.md file)
         - [x] Image (can use project.md file)
         - [x] Links to One Sheet
         - [x] Links to Home page (urls below in resources)
         - [x] Links to products  website (311, FOLA, engage)
         - [x] SDG details and links 
            - 16.7 Engage
            - 16.8 311-data.org
            - 2.1 FOLA
    - [x] Collect as much relevant information as possible at this juncture
- [x] UX/UI
   - [x] Review with Product and discuss where this page might live (the about page possibly)
   - [x] Create mockup
   - [x] Get signoff from product
- [x] Development
   - [x] review mockups and get any initial questions answered
   - [x] build (page should be called citizen-engagement
   - [x] integrate into site

#### Projects that are part of the Citizen Engagement Portfolio
[311-data project](https://www.hackforla.org/projects/311-data)
[Food Oasis](https://www.hackforla.org/projects/food-oasis)
[Engage](https://www.hackforla.org/projects/engage)
[Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3625%3A0)
[Lucky Parking](https://www.hackforla.org/projects/lucky-parking)

#### Links to Products Websites
[311 Data](http://311-data.org/)
[Food Oasis](https://foodoasis.la/)
[Engage](https://sm.engage.town/)

#### User Centered Design Workshops
We have partnered with the [Department of Neighborhood Empowerment](https://www.empowerla.org) and [Super by Design](https://superbydesign.io) to bring user-centered design to the Neighborhoods of the City of Los Angeles.

#### SDGs Info 
[SDGs on the Mayor's site](https://sdg.lamayor.org/)
16.7 (Engage): Ensure responsive, inclusive, participatory and representative decision-making at all levels
16.8 (311-data.org): Broaden and strengthen the awareness and participation of City and local communities, especially those traditionally underserved and marginalized, in the institutions of local and global governance
- Image for [16](https://sdg.lamayor.org/sites/g/files/wph1131/f/styles/medium/public/E_SDG%20goals_icons-individual-rgb-16.png?itok=5DJaP0I6)

2.1 (FOLA): By 2030, end hunger and ensure access by all people, in particular the poor and people in vulnerable situations, including infants, to safe, nutritious and sufficient food all year round
- Image for [2](https://sdg.lamayor.org/sites/g/files/wph1131/f/styles/medium/public/E_SDG%20goals_icons-individual-rgb-02.png?itok=rdRbP1RQ)

#### Citizen Engagement
[Google Drive](https://drive.google.com/drive/u/0/folders/1zKKBX0kfzE-v2Rfp4KRuntsGmyFhu15a)

User centered design deck - https://docs.google.com/presentation/d/1OCu3T80hHokqsswgbOPrR8Kp65dI5guZ-ZQaKpwj9O0/edit#slide=id.ga392a9252c_1_0

**Comment by johnr54321** [comment]
**About H4LA Citizen Engagement Portfolio:**
We at Hack for LA are volunteers that believe in building technology and analyzing data to make it easier to participate effectively in your community. Here, you'll find a series of products that we have built or are building to make that happen.

**How to Get Involved**
Whether you have a new idea, want to submit feedback to participate in guiding the next iteration of an existing tool, or want to start programming with us, please contact us at citizenengagement@hackforla.org

**Our Partners**
None of what we do would be possible without the generous support of many organizations throughout out our communities.  A big thank you to:
- [Mayor Eric Garcetti's Open Data Project](https://data.lacity.org)  
- [Los Angeles Department of Neighborhood Empowerment](https://www.empowerla.org)  
- [Code for America](https://www.codeforamerica.org/)  
- Neighborhood Council Members across the City of Los Angeles
- Volunteers across the USA and the world!

**Comment by johnr54321** [comment]
One pagers should be linked here: https://github.com/hackforla/product-managment/issues/3

**Comment by ExperimentsInHonesty** [comment]
@johnr54321 let's put the logos of all the NCs that have participated on the page.

**Comment by johnr54321** [comment]
![palms-logo-final-hires-300x240](https://user-images.githubusercontent.com/20999589/89002821-f1258100-d2b2-11ea-8462-64d67340c6a1.png)
![Voices Neighborhood Council](https://user-images.githubusercontent.com/20999589/89002828-f4207180-d2b2-11ea-882f-9cabf9eabb15.jpg)
<img width="47" alt="Empowerment Congress Central Area Neighborhood Development Council (ECCandDC)" src="https://user-images.githubusercontent.com/20999589/89002837-f682cb80-d2b2-11ea-91a0-1e758f4a39e1.png">
![EPNC-LOGO-COLOR](https://user-images.githubusercontent.com/20999589/89002841-f84c8f00-d2b2-11ea-93e3-79c52452fc50.gif)
![Mar Vista Community Council](https://user-images.githubusercontent.com/20999589/89002844-fa165280-d2b2-11ea-8bec-c7a7ad8043ff.png)
![Mid-City Neighborhood Council](https://user-images.githubusercontent.com/20999589/89002848-fd114300-d2b2-11ea-82da-585d9cd33179.png)
![EPNC-LOGO-COLOR](https://user-images.githubusercontent.com/20999589/89002874-09959b80-d2b3-11ea-9f06-d76c40c6f139.png)

**Comment by johnr54321** [comment]
@ExperimentsInHonesty Here you go.  Please assign to get people started.

**Comment by ExperimentsInHonesty** [comment]
@alexandrastubbs  christina will take this on she needs to be added to the project

**Comment by ExperimentsInHonesty** [comment]
@christina245 see component audit in figma for header styles - recommend using the same one as getting-started or project team meetings or credits

**Comment by alexandrastubbs** [comment]
@christina245 this is where you should put your work in progress: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3625%3A0

I have invited you to edit the Figma, you should see an email in your inbox.

**Comment by christina245** [comment]
Got it! Can someone share the Google docs with me?

**Comment by christina245** [comment]
Got it! Can someone share the Google docs with me?

**Comment by alexandrastubbs** [comment]
Confirming google doc has been shared.

**Comment by christina245** [comment]
I've added 4 of the projects and rewrote their descriptions to better fit the message of the page. Each card has the SDG it meets. I've also added cards for the partners and workshops.

**Comment by ltung05** [comment]
Add more description to the "User-Centered Design Workshops"

Change "Our Partners" to "Organizations We Worked with" or similar wording

[Slide deck for design thinking workshop from brigade congress](https://docs.google.com/presentation/d/1OCu3T80hHokqsswgbOPrR8Kp65dI5guZ-ZQaKpwj9O0/edit#slide=id.ga392a9252c_1_0)

@ExperimentsInHonesty will find the url for the video

**Comment by pawan92** [comment]
@christina245 Could I have access to those google docs as well?

**Comment by pawan92** [comment]
@ExperimentsInHonesty Checked the video is not ready in the cfa channel/brigade conference content.

**Comment by pawan92** [comment]
@christina245 Change "Our Partners" to "Organizations We Worked with" or similar wording

**Comment by IAgbaje** [comment]
@pawan92 , Please remind us what the to-do item is for this issue.

**Comment by pawan92** [comment]
@IAgbaje There were 2 things that had to be done for this:
- [ ] Change "Our Partners" to "Organizations We Worked with" or similar wording
- [ ] Add more description to "User centered Design Workshop" 

I modified both of those on Figma design and would love some feedback

**Comment by pawan92** [comment]
@christina245 Please provide an update:
1. Progress: 
2. Blocks: 
3. Availability: 
4. ETA:

**Comment by christina245** [comment]
We've decided to add some more content:

- [ ] add an Impact section 
- [ ] reach out to the team members of the projects to get a better understanding of the project to see what else would be important to include on the page

**Comment by ahdithebomb** [comment]
@ExperimentsInHonesty  will provide a slide deck for the User Center Design Workshop for Empower LA. 
@christina245  will rework the card for UXDCW to include the deck.

**Comment by christina245** [comment]
The UXDCW card has been reworked. I just need the video to add to the bottom left hand corner from @ExperimentsInHonesty or if anyone else has it.

**Comment by pawan92** [comment]
@christina245 Could you please update:
Progress:
Blockers:
Availability:
ETA:

**Comment by tarang100** [comment]
@christina245 will add the link to  the deck with the speakers notes

**Comment by christina245** [comment]
> @christina245 will add the link to the deck with the speakers notes

This has been added.

**Comment by daniellex0** [comment]
Slide deck: https://docs.google.com/presentation/d/1tfYUw0RrPOlhxAVDgMBzpuLSqliMLcw0Y1tCKGtLXOA/edit

Video: https://www.youtube.com/watch?v=TgAqb5jcSoY&list=PL65XgbSILalVD81qt-I_vfUJLEjhfdmXh&index=6

(^ both for initiative 1)

Open Community Survey (the project):

**Initiative 1** Los Angeles Department Of Neighborhood Empowerment website redesign Community Survey and Feature Prioritization Workshop

Community Survey - EmpowerLA.org Website Redesign (not ready) https://docs.google.com/document/d/1rGPHNzKv-fXr6_yc0PKDtX2TdrcB6AezUatbp9yLf18/edit

**Initiative 2** Los Angeles Neighborhood Council websites feature prioritization survey

Community Survey - Neighborhood Council Websites (ready) https://docs.google.com/document/d/1-1JHqX2JiZjaba19JM2svf8KKdVDuuCT01oXEVsQltU/edit

*Above are also one-sheet links for each of these (Christina: read these links and see if there's any info from those that you want to pull into this page):

**Comment by christina245** [comment]
Created a new version of the page with the proper dimensions.

**Comment by christina245** [comment]
Still need access to the document for initiative 1!

**Comment by ExperimentsInHonesty** [comment]
@christina245 I just changed the permissions for the Inative 1 doc (I changed to anyone can view), but there is nothing in it.  I will add a dependency on the issue https://github.com/hackforla/product-management/issues/77 where we are working on it to let you know when its completed.

Is there another way to communicate that this is a video other than this image?  It's a lot of black
![Screen Shot 2021-03-01 at 10 57 13 AM](https://user-images.githubusercontent.com/37763229/109544924-fd5a0280-7a7c-11eb-8d48-20ad0f0e17b5.png)

Make the The Open Community Survey a card like the rest of the projects on this page

But also keep the designs you made on the side, and we will talk about what is next for the other iterations of OCS

**Comment by tarang100** [comment]
@christina245 Please provide status update

**Comment by christina245** [comment]
I've changed the screencap and added a card for the Open Community Survey

**Comment by daniellex0** [comment]
Needs to be reviewed with Bonnie for direction

**Comment by Sihemgourou** [comment]
Update: 

- [x] Created a new issue for Ali (about Finding right SDG for projects)
- [x] Still cleaning this issue

**Comment by Sihemgourou** [comment]
@ExperimentsInHonesty could you remind me to which repo and which Ali I should send the issue please  ?
