### ISSUE TITLE
ER: have the meeting data be more relevant, depending on what page it appears on

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#6320]
### Emergent Requirement - Problem
We are not displaying all the meeting data that people need or expect when they come to different pages on the site

### Issue you discovered this emergent requirement in
- #5195 

### Date discovered 
2024-02-18

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
confusion from the users and PMs of those teams, wondering why the data does not show up on their project profile page

### Resources
- [Events page](https://www.hackforla.org/events/)
- [TDM Calculator project page](https://www.hackforla.org/projects/tdm-calculator)
- [project-meetings page](https://www.hackforla.org/project-meetings)
- 
### Recommended Action Items
- [x] Make 2 new issues
   - [x] add the links for the issues to the bottom of this issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

#### Issue 1 - Medium
- Currently the Events page has Day, Time, Name of Project, Name of Meeting
   - Add asterisk if it's not weekly
   - At the bottom of the Online Project Team Meetings card, add the following text 
     ```
     *This meeting is not weekly, check project link for more details.
     ```
#### Issue 2 - medium
- Currently any Project Info page (e.g., TDM Calculator) has Day, Time, Name of Meeting
   - Add description

### Special notes
- The data for all these pages should be coming from the JSON data stored on our repo, not from the VRMS API directly.
- an example of how to get all the meeting data required
  - Currently, the project-meetings](https://www.hackforla.org/project-meetings page has all the data, no change is necessary

### Issues made from this ER
- #6920
- #6930

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge Can someone from the merge team review this ER and if you think it is ready for issue making, please add a `ready for prioritization` label.

**Comment by Thinking-Panda** [comment]
Availability: Weekdays
ETA 5/30/24

**Comment by Thinking-Panda** [comment]
@ExperimentsInHonesty
-  I am working on issue 1. When it says `*This meeting is not weekly, check project link for more details.` . do you mean the Onboarding meeting or the meetings that don't happen 1-7 of each month? I checked a few of the project pages and didn't find any specific mention on meetings that are not weekly.
 - Is that information/description added by the issue 2 in this ER?
 - In Issue 2, What is the description to be added? Will the dev be making changes to `_data/external/vrms-data.json`?
 - Is issue 1 dependent on issue 2?

**Comment by Thinking-Panda** [comment]
A few projects have a description already. For instance Home Unite US- `PM/Org` "alternating week", Civic Tech Jobs-`All` "3rd week". but the description is not displayed on the website.

**Comment by Thinking-Panda** [comment]
@ExperimentsInHonesty Never mind, I understand the issues now.

**Comment by t-will-gillis** [comment]
Both issues made from this ER have been merged; closing this ER
