### ISSUE TITLE
ER: Communities of Practice information updates: Ops

### ISSUE THREAD

**Issue by chelseyklein** [hackforla/website#6354]
### Dependency
- [x] #6372

### Remove person(s) and info from CoP file?

NO

### If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:

Name:

### Add person(s) and info to CoP file?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Nayan Bhatt
Title: Co-lead
GitHub Handle: freaky4wrld
Slack Member ID: U05TZLLJAUV

- [x] Name: Zoey Zhang
Title: Co-lead
GitHub Handle: abbyz123
Slack Member ID: U06DT2CA92T

**Comment by JessicaLucindaCheng** [comment]
### Issue Writing
- **Availability:** 6 hours
- **ETA:** Sunday, February 25, 2024

**Edit:** Completed writing the issue for the requests in this ER. See Dependency section.

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issue(s) in the Dependency section are merged, 
- [x] Close this ER
- [x] Move this ER to the UAT column
- [x] Contact the author of this ER to approve the changes on the [Communities of Practice](https://www.hackforla.org/communities-of-practice) page and add a `ready for stakeholder` label
- [ ] Once the changes have been accepted by the author of this ER, remove the `ready for stakeholder` label and add a `ready for product` label. Also, leave a comment that this ER is ready for further UAT and QA by product.

**Comment by JessicaLucindaCheng** [comment]
@chelseybeck Please let us know if the changes made to the [Communities of Practice](https://www.hackforla.org/communities-of-practice) page match what you requested by adding a comment to this issue. Thank you.

Edit: Left a Slack message on April 12, 2024 in the ops channel
