### ISSUE TITLE
Update documentation: fix broken links

### ISSUE THREAD

**Issue by joey-ma** [hackforla/website#6355]
### Overview
Context: `hackforla/ops` is hoping to set up GHA for adding update labels weekly. While grooming the issue, we found that `hackforla/website`'s Wiki could be useful. However, there were broken links in the Wiki page. It's best to have correct information and links for all documentation.

Summary: _We need to update the broken links in Wiki page [GHA: add update label weekly](https://github.com/hackforla/website/wiki/GHA:-add-update-label-weekly) for better documentation._

### Action Items
- [x] find the correct links for the "Workflow" section: (broken links as of writing this issue)

> **Workflow:**
> - [add-update-label-weekly.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/add-update-label-weekly.yml)  
> - [add-label.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/add-update-label-weekly/add-label.js)

> **Supporting Files/Folder:**
> [add-update-label-weekly](https://github.com/hackforla/website/tree/gh-pages/github-actions/add-update-label-weekly)
> File: https://github.com/hackforla/website/blob/gh-pages/github-actions/add-update-label-weekly/add-label.js references
> https://github.com/hackforla/website/blob/gh-pages/github-actions/add-update-label-weekly/update-instructions-template.md (same folder)
> https://github.com/hackforla/website/blob/gh-pages/github-actions/utils/find-linked-issue.js (utils folder)

- [ ] clone `hackforla/website`'s Wiki: `https://github.com/hackforla/website.wiki.git`
- [ ] make corrections in file `GHA:-add-update-label-weekly.md`
- [ ] submit PR for approval.

### Resources/Instructions
The correct/corresponding links (permalinks) should be:
- [schedule-fri-0700.yml](https://github.com/hackforla/website/blob/9913ae68a679067f006dfcd4055e23cd009b5474/.github/workflows/schedule-fri-0700.yml)
- [add-label.js](https://github.com/hackforla/website/blob/9913ae68a679067f006dfcd4055e23cd009b5474/github-actions/trigger-schedule/add-update-label-weekly/add-label.js)

Even though the file name has been changed from `add-update-label-weekly.yml` to `schedule-fri-0700.yml`, I believe it is the right GitHub Actions file since it's correctly referencing the `add-label.js`.

**Comment by joey-ma** [comment]
```md
<!-- lines 7-9 -->
### Workflow: 
- [schedule-fri-0700.yml](https://github.com/hackforla/website/blob/9913ae68a679067f006dfcd4055e23cd009b5474/.github/workflows/schedule-fri-0700.yml)
- [add-label.js](https://github.com/hackforla/website/blob/9913ae68a679067f006dfcd4055e23cd009b5474/github-actions/trigger-schedule/add-update-label-weekly/add-label.js)

<!-- lines 15-20 -->
### Supporting Files/Folder: 
- [add-update-label-weekly](https://github.com/hackforla/website/tree/gh-pages/github-actions/trigger-schedule/add-update-label-weekly)
    * File: https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/add-label.js references
      * https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/update-instructions-template.md (same folder)
      * https://github.com/hackforla/website/blob/gh-pages/github-actions/utils/find-linked-issue.js (utils folder)
      * https://github.com/hackforla/website/blob/gh-pages/github-actions/utils/get-timeline.js (utils folder)
```

I would push it if I have the correct permission, but I think I'll need to be onboarded to be a contributor for the `hackforla/website` team first.
![image](https://github.com/hackforla/website/assets/86270711/e9c3f840-e534-4a5a-929a-7ae1169df85e)

Just saw this [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki).  
Maybe I can look at this closer another day.

**Comment by t-will-gillis** [comment]
Hey @joey-ma Thank you for looking at this. The wikis for the GHAs need work, desperately, and as you saw the process is complicated by not having the new wiki pages fully functioning yet. 

There is an existing issue #4856 for updating the previous "add update label weekly" gha, now named `schedule-friday.yml`. I believe we should continue with the previous issue since that one has additional specifics to complete, and close this one. I added a link to your comments on the previous issue so that whoever works on that issue will be able to reference your work. 

Please let me know if you have questions or comments about the ghas and/or the wiki. Thank you again!
