### ISSUE TITLE
ER: Update Project Profile: Guides

### ISSUE THREAD

**Issue by edwardsarah** [hackforla/website#6364]
### Dependency
- [x] #6373 

### Project Name

Guides Team

### Project Card URL

guides-team.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Sarah Levine

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Ayma Rahman
GitHub Handle: aymarmsba
Role: Product Manager
Slack Member ID: U06C183Q2HL

### Project Status

Active

**Comment by JessicaLucindaCheng** [comment]
### Issue Writing
- **Availability:** 6 hours
- **ETA:** Sunday, February 25, 2024

**Edit:** An issue has been written for this request. See Dependency section.

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issue(s) in the Dependency section are merged, 
- [x] Close this ER
- [x] Move this ER to the UAT column
- [x] Contact the author of this ER to approve the changes on the [Guides Team](https://www.hackforla.org/projects/guides-team) page and add a `ready for stakeholder` label
- [ ] Once the changes have been accepted by the author of this ER, remove the `ready for stakeholder` label and add a `ready for product` label. Also, leave a comment that this ER is ready for further UAT and QA by product.

**Comment by JessicaLucindaCheng** [comment]
@edwardsarah 
Please let us know if the changes made to the [Guides Team](https://www.hackforla.org/projects/guides-team) page match what you requested by adding a comment to this issue. Thank you.

**Comment by JessicaLucindaCheng** [comment]
This issue has been in UAT for a long time, and we got no response from the author, so I am moving this to QA.
