### ISSUE TITLE
Update CONTRIBUTING.md 2.1 Hack for LA contributor expectations

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6375]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to update Section 2.1 of CONTRIBUTING.md to accurately describe Hack for LA contributor expectations

### Action Items
- [x] Browse to [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md) and open for editing (click the pencil icon with tooltip "Edit this file")
- [x] Locate Section 2.1 and replace
```
In order to join [another project within Hack for LA](https://www.hackforla.org/projects/) or work on a `Complexity: Small`/`Complexity: Medium`/`Complexity: Large` label issue within this repo, you need to complete the following:
```
with
```
In order to work on a `Complexity: Small`/`Complexity: Medium`/`Complexity: Large` label issue within this repo, you need to complete the following:
```
- [x] Content will be added at the end of Section 2.1.  Replace:
```
<sub>[Back to Table of Contents](#table-of-contents)</sub>
```
with 
```
Prior to joining [another project within Hack for LA](https://www.hackforla.org/projects/), developers should gain the following experience:
* Setting up your local environment from a CONTRIBUTING file
* Completing the above series of issues at least up to `Complexity: Large` 
* Resolving Merge Conflicts
* Reviewing other people's Pull Requests
* Create or improve documentation for other developers
* Mentor other developers
* Create new issues

In addition, backend engineers should complete issues that provide experience with the following:
* API requests
* Cron Job Scripting
* CRUD operations

<sub>[Back to Table of Contents](#table-of-contents)</sub>
```
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
[CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
[Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)

**Comment by aidanwsimmons** [comment]
i. Availability: weekdays - afternoons/evenings
ii. ETA: (hoping to finish by end of today(2/27).  Should be done tomorrow otherwise
