### ISSUE TITLE
Updates to `inactive-members.md` file

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6395]
### Overview
We need to make minor edits to the verbiage on the issue generated by the `schedule-monthly.yml` workflow to clarify the description and explanations. Note: since these changes are to verbiage only, this issue **does not require testing** of the GHA.

### Action Items
- [x] The current message to members about how to become active again is unclear. So that the message on the [inactive-member.md](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/list-inactive-members/inactive-members.md) template is more clear, add to the bottom of the list in `### How you can remain active`:  
  ```
  - If you are newly onboarded, that you are assigned to your "Pre-work checklist" and you have cloned the HfLA website repo to your personal repo.
  ```  
  
- [x] In the following section, replace:

  ```
  If you have been inactive in the last 30 days (using the above measurements), you can become active again by doing at least one of the above actions. The bot will automatically remove you from next month's list.  
  ```
  with:
  ```
  If you have been inactive in the last 30 days (using the above measurements), you can become active again by doing at least one of the above actions. If you do not do at least one of the above actions, the bot will automatically remove you from the 'website-write' team in the next 30 days.  
  ```  

### Resources/Instructions
- This issue is associated with #6193

**Comment by angela-lee1** [comment]
Availability:3/19 3/20
ETA: EOD 3/21

**Comment by t-will-gillis** [comment]
Hey @awlFCCamp Thanks for working on this issue! Please remember to move any issues you are working on to the "In progress (actively working)" column...
