### ISSUE TITLE
Edits to `create-new-issue.js` 

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6396]
### Overview
As part of refactoring, the inactive member data generated during `contributors-data.js` will be saved as a temporary file rather than an artifact because this makes it easier to import the previous month's data into the workflow. Thus we need to change the artifact download into a readFileSync() of the temp file, along with other minor edits. Note: this issue does not require testing of the GHA- final testing will be included with #6193. 

### Action Items
In [create-new-issue.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/list-inactive-members/create-new-issue.js):
- [x] Line 2, insert the line `var fs = require('fs');`
- [x] Replace:
```
let inactiveLists = JSON.parse(artifactContent);
```  
with:  
```
  const filepath = 'github-actions/utils/_data/inactive-members.json';
  const rawData = fs.readFileSync(filepath, 'utf8');
  let inactiveLists = JSON.parse(rawData);
```  

- [x]  Before `const issue = await createIssue()...`, add:
```  
const inactiveWithOpen = parseInactiveOpen(inactiveLists['cannotRemoveYet']);
```  

- [x] The following code is mostly unreferenced and extraneous, therefore replace:
```  
  const issueId = issue.id;
  const issueNumber = issue.number;
  // Get project id, in order to get the column id of `New Issue Approval` in `Project Board`
  const projectId = await getProjectId(owner, repo);
  // Get column id, in order to create a project card in `Project Board` and place in `New Issue Approval`
  const columnId = await getColumnId(projectId);
  // Create the project card, which links to the issue created in createIssue() above
  await createProjectCard(issueId, columnId);
```  
with:  
```  
const issueNumber = issue.number;  

```
- [x] Replace:  
```  
const commentBody = `**Review Inactive Team Members:** #` + issueNumber;
```  
with:  
```  
const commentBody = `**Review Inactive Team Members:** #` + issueNumber + inactiveWithOpen;
```
- [x] Add a semicolon to the end of the line at `let thisIssueNumber = ...`
- [x] Before `module.exports = main;` insert:
```  
const parseInactiveOpen = (inactiveOpens) => {
  if(Object.keys(inactiveOpens).length === 0){
    return '';
  } else {
    let inactiveOpen = '\r\n\nInactive members with open issues:\r\n';
    for(const [key, value] of Object.entries(inactiveOpens)){
      inactiveOpen += ' - ' + key + ': # ' + value + '\r\n';
    }
    return inactiveOpen;
  }
};
```  
- [x] Delete the entirety of this section since we are no longer using these functions:  

```  
const getProjectId = async (owner, repo) => {
  // Get all projects for the repo
  let projects = await github.rest.projects.listForRepo({
    owner,
    repo,
  });
  // Select project with name `Project Board` then access the project `id`
  let projectId = projects.data.filter((project) => {
    return (project.name = "Project Board");
  })[0].id;
  return projectId;
};

const getColumnId = async (projectId) => {
  // Get all columns in the project board
  let columns = await github.rest.projects.listColumns({
    project_id: projectId,
  });
  // Select column with name `New Issue Approval` then access the column `id`
  let columnId = columns.data.filter((column) => {
    return column.name === "New Issue Approval";
  })[0].id;
  return columnId;
};

const createProjectCard = async (issueId, columnId) => {
  const card = await github.rest.projects.createCard({
    column_id: columnId,
    content_id: issueId,
    content_type: "Issue",
  });
  return card.data;
};  

```  

### Resources/Instructions
- This issue is a dependent for #6193

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis are you still working on this draft? If you are please assign this to yourself

**Comment by marioantonini** [comment]
i. Availability: F, M, T 2-6pm
ii. ETA: EOD Monday March 18

**Comment by t-will-gillis** [comment]
Hey @marioantonini FYI I added one item to the Action Items list  (it is the last item about removing the three functions getProjectId(), getColumnId(), and createProjectCard()).

**Comment by marioantonini** [comment]
@t-will-gillis main's last argument 'artifactContent' is not used, so removing it. Is there a reason to using var instead of const for loading 'fs'?

**Comment by t-will-gillis** [comment]
Hey @marioantonini good catch with the 'artifactContent', thanks! Regarding 'var fs' versus 'const fs': you're right, it should be 'const', thank you again.
