### ISSUE TITLE
ER: Footer sticks above fold on desktop & mobile

### ISSUE THREAD

**Issue by w1ld-r** [hackforla/website#6397]
### Emergent Requirement - Problem

The footer is sticking above the fold on the `feature-homepage-launch` branch. 

This is a problem because it covers a substantial amount of content, especially on mobile devices. I noticed it on Chrome, Firefox, and Safari. 

### Issue you discovered this emergent requirement in

- PR: https://github.com/hackforla/website/pull/6390
- Issue: https://github.com/hackforla/website/issues/6286

### Date discovered 

2024-02-28

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved

@LRenDO and @ramitaarora 

### What happens if this is not addressed

The footer is rather large and covers up a substantial amount of content. This is particularly problematic on mobile, as it prevents the user from viewing the page on smaller devices. If deployed, it will create an undesirable user experience.

![screenshot_2024-02-28_at_4 59 01___pm](https://github.com/hackforla/website/assets/76500899/ae4f7209-f391-4a9c-9838-5dac93c947df)

### Resources

This describes the desired behavior, but the solution didn't work for me locally: https://www.freecodecamp.org/news/how-to-keep-your-footer-where-it-belongs-59c6aa05c59c/

### Recommended Action Items
- [x] Make a new issue
- [x] Discuss with team
- [x] Let a Team Lead know

### Potential solutions [draft]

I was able to fix the issue locally by removing the 'position' attribute completely from .main-footer in _sass/components/_footer.scss

**Comment by ExperimentsInHonesty** [comment]
@gaylem this is great. Thanks for making this ER.  If you are done writing it, please add the ready for dev lead label, so the merge team can review it.

**Comment by w1ld-r** [comment]
@ExperimentsInHonesty Just added the label. Thanks for the heads up!

**Comment by ExperimentsInHonesty** [comment]
@gaylem please copy the Slack conversation into a comment below, since we will loose that shortly.  Add the ready for dev lead label back when you are finished.

**Comment by w1ld-r** [comment]
Hey @ExperimentsInHonesty, I just read over the thread and it didn't add much to the issue that isn't already stated here, so I removed the reference to it from the description and added the ready for dev lead label back in.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty should this be addressed?

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe yes, definitely.    I am going to prioritize this so that an issue can get made.

**Comment by w1ld-r** [comment]
- Created #6637
