### ISSUE TITLE
The Hack for LA website bot removed me!

### ISSUE THREAD

**Issue by blaycoder** [hackforla/website#6444]
The Hack for LA website bot removed me!
I am responding to Issue #6211 because I want to come back.
Please add me back to the 'website-write' team, I am ready to work on an issue now.

_Originally posted by @blaycoder in https://github.com/hackforla/website/issues/6211#issuecomment-1987155150_

**Comment by t-will-gillis** [comment]
Hey @blaycoder  Welcome back- you are added to the 'website-write' team. As Bonnie mentioned on your "[Pre-work Checklist](https://github.com/hackforla/website/issues/5500#issuecomment-1943120238)",

> If you want to come back to the team and pick up where you left off, then please go ahead and self assign a [small issue from the prioritized backlog](https://github.com/hackforla/website/projects/7?card_filter_query=-label%3A%22role%3A+dev+leads%22++label%3A%22role%3A+front+end%22+label%3A%22complexity%3A+small%22#column-7198257).
