### ISSUE TITLE
Fix project filter display on mobile Safari 

### ISSUE THREAD

**Issue by ye-susan** [hackforla/website#645]
### Overview
The project filters do not display correct on the mobile version of Safari, so we'll have to create a workaround for mobile phones for displaying the project filters

### Action Items

- [x]  Hide filters on mobile Safari (issue #646 )
- [ ]  Render project filters on touchscreens without using :hover (which causes some inconsistency in performance on some browsers like Safari)

**Comment by ye-susan** [comment]
Progress: created PR #675 

Please note, this solution has potential to still be buggy in that there may be double clicks when we test on different devices (it works fine on my regular browser)-- but I still want to test this solution out first since it's less verbose than my other fix. If there are bugs when we test on different devices, I'll re-do these changes with the more verbose solution.

**Comment by ExperimentsInHonesty** [comment]
@ye-susan @leonelRos this sounds good to me.  Go ahead and push it, so that we can test during meeting across everyones devices.
