### ISSUE TITLE
Bug fix and minor edits `get-timeline.js`

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6459]
### Overview
The utility function `get-timeline.js` has a bug that needs to be fixed. While making this change, we can also add comments and change a variable name for clarity. Note: this issue **_does not_** require testing of a GHA.

### Action Items

Open the file [get-timeline.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/utils/get-timeline.js):
- [x] In the try...catch statement, revise the console.log() to match the 'err' parameter.
- [x] Replace all four instances of `arra` with the more descriptive `timelineArray`. 
- [x] For the function comments, replace:  
```
/**
 * Function that returns the timeline of an issue.
 * @param {Number} issueNum the issue's number
 * @returns an Array of Objects containing the issue's timeline of events
 * /
```  
with:  
```
/**
 * Function that returns the timeline of an issue
 * @param {Object} g                      - github object from actions/github-script
 * @param {Object} c                      - context object  from actions/github-script
 * @param {Number} issueNum               - the issue number
 * @returns {Object} timelineArray        - an array containing the timeline of issue events
 */
```

### Resources/Instructions
This issue is a dependent for #6193

**Comment by angela-lee1** [comment]
Availability:3/16 3/17
ETA: EOD 3/18
