### ISSUE TITLE
Create new file `inactive-members.json`

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6460]
### Overview
We are adding a new functionality to the `schedule-monthly.yml` GHA: before we remove inactive members from the 'website-write' team, we want to be sure that the bot sent a notification in the previous month. Otherwise, there are some members that could be removed from the 'website-write' team without receiving the  30 day warning. Note: this issue **_does not_** require testing of the `schedule-monthly.yml` GHA.  

### Action Items
- [x] Locate the directory `github-actions/utils/`
- [x] Create a new directory/file under the `utils` directory and name it: `_data/inactive-members.json`
- [x] Copy the contents of [this file](https://github.com/t-will-gillis/website/blob/edits-6193-consolidate-3-13/github-actions/utils/_data/inactive-members.json) into `inactive-members.json`.

### Resources/Instructions
This issue is a dependent for #6193

**Comment by vincendp** [comment]
i. Availability: Flexible - 1-2 hours everyday
ii. ETA: Tomorrow night latest
