### ISSUE TITLE
ER: Update Project Profile: Guides Team

### ISSUE THREAD

**Issue by edwardsarah** [hackforla/website#6466]
### Dependency
- [x] #6509 

### Project Name

Guides Team

### Project Card URL

guides-team.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

NO

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: 

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Mary Gabrielian
GitHub Handle: marygabrielian
Role: Product Manager
Slack Member ID: U06KMNL8ETY

### Project Status

Active

**Comment by Ayrh1** [comment]
Availability: Monday Evening: 7pm -9pm, Tuesday -> Open
ETA: Monday Evening 7pm - 9pm

**Comment by ExperimentsInHonesty** [comment]
@Ayrh1I have removed you from this issue and explained why in your prework issue https://github.com/hackforla/website/issues/6342#issuecomment-2005540568

**Comment by JessicaLucindaCheng** [comment]
### Issue Writing
- **Availability:** 6 hours
- **ETA:** Saturday, March 23, 2024

### Edit: Update
- Issue has been written and added to the Dependency section of this ER.

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issue(s) in the Dependency section are merged, 
- [x] Close this ER
- [x] Move this ER to the UAT column
- [x] Contact the author of this ER to approve the changes on the [Guides Team](https://www.hackforla.org/projects/guides-team) page and add a `ready for stakeholder` label
- [ ] Once the changes have been accepted by the author of this ER, remove the `ready for stakeholder` label and add a `ready for product` label. Also, leave a comment that this ER is ready for further UAT and QA by product.

**Comment by gdkoo** [comment]
Hi @JessicaLucindaCheng, the dependency issue has been merged and this ER is now in Questions/In Review. Would you like me to complete the tasks in the comment above?

**Comment by JessicaLucindaCheng** [comment]
@gdkoo 

> Hi @JessicaLucindaCheng, the dependency issue has been merged and this ER is now in Questions/In Review. Would you like me to complete the tasks in the comment above?

No, it's for a dev lead (Merge Team member or the Technical Lead). Thanks for asking. :smile:

**Comment by LRenDO** [comment]
Closing per [instructions](https://github.com/hackforla/website/issues/6466#issuecomment-2016723798) as dependencies are complete.

**Comment by LRenDO** [comment]
Hi @edwardsarah! When you're able, please review and approve or request changes for the [Guides Team](https://www.hackforla.org/projects/guides-team) page update. Thanks!

**Comment by JessicaLucindaCheng** [comment]
@edwardsarah Please let us know if the changes made to the [Guides Team](https://www.hackforla.org/projects/guides-team) page match what you requested by adding a comment to this issue. Then, remove the `ready for stakeholder` label and add the `ready for dev lead` label. Thank you.

**Comment by JessicaLucindaCheng** [comment]
This issue has been in UAT for a long time, and we got no response from the author, so I am moving this to QA.
