### ISSUE TITLE
Resolve "Potentially unsafe external link" in `_includes/current-guides.html`

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6484]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We need to fix a potentially unsafe external link by adding the attribute `rel="noopener noreferrer"`.  The problem and the solution is similar the those detailed in https://github.com/hackforla/website/security/code-scanning/3, however the instance addressed by this issue did not result in a CodeQL alert.  

### Action Items
- [x] Open the file `_includes/current-guides.html` in your IDE
- [x] Replace
```
                        <a href="{{item.resource-url}}" class="toolkit-flex-item-status" target="_blank">
```
with
```
                        <a href="{{item.resource-url}}" class="toolkit-flex-item-status" target="_blank" rel="noopener noreferrer">
```
- [x] Using Docker, check the url `/toolkit` and check that the page remains the same in mobile, tablet, and desktop views as on the current website (See 2 in the Resources/Instructions section below).  Refer to the Resources/Instructions section for a screenshot of the hyperlink modified in this issue (highlighted in yellow).  Confirm that link still works.  

### Merge Team
- [ ] When this issue is completed, check off the issue in #5129
  
### Resources/Instructions
<details><summary>hyperlink modified in this issue</summary>

![image](https://github.com/hackforla/website/assets/5314153/d527d17f-0ee8-4f81-a757-65793a42aaa2)

</details> 

1. [GitHub CodeQL documentation](https://codeql.github.com/docs/codeql-overview/about-codeql/)
2. Webpage: https://www.hackforla.org/toolkit
3. This issue is part of #5129

**Comment by DakuwoN** [comment]
Hello, I am available Monday - Friday after 1:30PM Eastern and Weekends anytime.
I will have this issue complete by Sunday.

**Comment by ExperimentsInHonesty** [comment]
@DakuwoN In future, please do not take issues from the new issue approval column.  Only from the prioritized backlog.

**Comment by DakuwoN** [comment]
I'm sorry @ExperimentsInHonesty it's been so long, and I even re read the onboarding documents, I expect some other mistakes as well. Sorry again. Won't happen again.
