### ISSUE TITLE
Run VS Code Spell Checker on .github/ISSUE_TEMPLATE/img-tag-refactor.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6487]
### Overview
We need to audit HfLA codebase files for spelling errors using the Code Spell Checker extension in VS Code in order to ensure site quality. Results will be categorized as misspellings or false positives in the HfLA spelling audit spreadsheet[^1] and will be resolved in later issues.  

### Action Items
- [x] You must use VS Code as your local text editor and install the `Code Spell Checker` VS Code extension[^2]  
- [x] Do not change any configuration settings or make any spell corrections
- [x] Open the file '.github/ISSUE_TEMPLATE/img-tag-refactor.md' and note any Code Spell Checker errors
- [x] Locate the file in column A ("File") of the "Page Audit" sheet. In the column labeled "Result Summary", select the appropriate option: `No errors` or `At least one error`.
- [x] If at least one error was reported, copy/paste each cSpell message into a separate row in the `Results` sheet
- [x] In each new row, select the appropriate value: `misspelling` or `false positive` from the "Result type" column. A false positive is a term that is not a misspelling but is not recognized by the spell checker because it is a technical term, abbreviation, acronym, URL or proper noun (name of a person, place or organization).
- [x] Move this issue to the Questions/In Review column and apply the label `ready for dev lead`

### Merge Team
- [ ] After this issue is closed, release the dependency on this issue in #5248
- [ ] After the last dependency has been released, close that issue

### Resources/Instructions
- This issue is part of #5248
[^1]: [HfLA spelling audit spreadsheet - Results](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=69989048)
[^2]: The recommended installation method is to install Code Spell Checker directly from the VS Code text editor, and those instructions can be found [here](https://code.visualstudio.com/learn/get-started/extensions). The extension can also be installed via the VS Code Marketplace website [here](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

**Comment by aswutmaxcy** [comment]
Hello,

I'll be available 8-4 EST M-F and should be done with this EoD 3/21/24.
Will update if ETA needs to be updated.

**Comment by aswutmaxcy** [comment]
I couldn't get the code spell checker to work on some files, it seemed to only work on certain directories, others it seemed to ignore. I'm not 100% on which ones it's ignoring or not.

I'm using the extension on VScode on win11, I tried using it on remote WSL connection as well with the same results.

How do I get code spell checker to run on the file above? ('.github/ISSUE_TEMPLATE/img-tag-refactor.md)

**Comment by aswutmaxcy** [comment]
an update to my previous comment:

I removed ln 20 ".github" in the file cspell.json temporarily to let Code Spell Checker spell check the file img-tag-refactor-on-website.md

After which I found no errors and added the line back, updated my local repo, didn't push or commit, and updated the audit excel sheet.

**Comment by roslynwythe** [comment]
Thank you @aswutmaxcy, you are absolutely correct and it would not be possible to spell check that markdown template without the process you describe.  I do apologize for the confusion and I will clarify that in any future issues that audit spelling on templates within the .github folder.  Thank you for noting your results in the spreadsheet.
