### ISSUE TITLE
Project Slack links: Tech Work Experience

### ISSUE THREAD

**Issue by marioantonini** [hackforla/website#6515]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md).

### Overview
We need to edit the Slack link for the project so that we have continuity between project Slack links.

### Action Items
- [x] In `_projects/tech-work-experience.md`, for the Slack `url` under the `links` section, change 

From:
```
url: 'https://hackforla.slack.com/messages/C01VAUPU788'
```
To:
```
url: 'https://hackforla.slack.com/archives/C01VAUPU788'
```
- [x] Ensure that clicking the Slack link resolves to the new address at the following places:
  - [x] On the [Projects page](https://www.hackforla.org/projects/), the Slack link under the `Links` field for the project's card
  - [x] On the [Tech Work Experience page](https://www.hackforla.org/projects/tech-work-experience),
    - [x] the Slack link under the `Links` field in the Project Overview section
    - [x] the Slack link in the Resources/Instructions section 
- [x] Once your pull request is merged, go to #4564 and
  - [x] Check off this issue under the _Dependency_ section
  - [x] If all the issues in the _Dependency_ section are checked off, move #4564 to **Questions / In Review** column and add a **ready for dev lead** label to it

### Resources/Instructions
- Directory to find the page once you have it in your IDE: `_projects/tech-work-experience.md`
- [Projects page](https://www.hackforla.org/projects/)
- Project page URL: https://www.hackforla.org/projects/tech-work-experience
- Click on the filename below to see the source file code:
https://github.com/hackforla/website/blob/gh-pages/_projects/tech-work-experience.md?plain=1
- This issue is tracked in #4564

**Comment by urvishp13** [comment]
Availability for this week: Late mornings, early afternoons
My estimated ETA for completing this issue: 1 week

**Comment by urvishp13** [comment]
I have a blocker. The URL is not changing when clicking the Slack link in the Projects page.

So far, I have: 
* Updated the Slack link in the `_projects/tech-work-experience.md` file (there is only one place to update it)
* Checked to see if the URL is changing to `https://hackforla.slack.com/archives/C01VAUPU788` when clicking on the Slack links in the 3 places listed in this issue. The URL is changed to the new one when clicking the Slack links from within the Tech Work Experience page.

I am working on the `tech-work-experience-slack-link-6515` branch on my forked repo.

**Comment by tony1ee** [comment]
Hi @urvishp13 have you tried 
- restart/redeploy the docker container for the site
- disable/clear browser cache before reloading the Projects page for testing

**Comment by urvishp13** [comment]
Hi @tony1ee,

Restarting the docker container was the trick. Thanks.
