### ISSUE TITLE
Update Project Meeting page text and Events page text

### ISSUE THREAD

**Issue by A-Wu5** [hackforla/website#6539]
### Overview

Update text for attending project meetings to clarify that people can attend any team meetings only if that team has an open role.

### Action Items

- [x] In your local editor, go to `pages/project-meetings.html`
- [x] Replace the old text: 

> Please review the listing of project team meeting times to find a project that fits your schedule.
            You are welcome to attend a project team meeting after you have completed <a href="/getting-started">Onboarding</a>.
            Details about a team's meeting can be obtained in each team's slack channel.

with the new text below:

```
We have teams that meet at various times. You are welcome to attend a project team meeting after you have completed Onboarding, and if the team currently has an open role. You can find open roles at the end of the <a href="https://www.hackforla.org/getting-started" target="_blank">Onboarding</a>.
```

- [x] Go to `_includes/event-page/right-col-content.html` complete the same step as above.
- [x] Verify that the changes have been correctly made by checking the projects meeting and events page locally and provide screenshots.
    - [x] Verify that the changes have been made correctly in desktop screen size.
    - [x] Verify that the changes have been made correctly in tablet screen size.
    - [x] Verify that the changes have been made correctly in mobile screen size.

### Resources/Instructions

1. Project meetings page: [https://www.hackforla.org/project-meetings/](https://www.hackforla.org/project-meetings/)
2. Events page: [https://www.hackforla.org/events/](https://www.hackforla.org/events/)

Issue initialized for #6162

**Comment by roslynwythe** [comment]
Hi @A-Wu5 this looks good, please just add that testing should be done in both mobile and desktop screen sizes.

**Comment by A-Wu5** [comment]
Hi @roslynwythe, I've updated the issue accordingly. Thank you for the feedback!

**Comment by DeniseLewis1** [comment]
Availability: Wednesday, 4/17 - Friday, 4/19
ETA: By end of day Friday
