### ISSUE TITLE
Bug fix! Issues labeled `Complexity: Prework` in "New Issue Approval" should not unassign devs who self-assign

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6555]
### Overview
The GitHub Action that unassigns dev from issues self-assigned from the "New Issue Approval" column as described by issue #4821 needs additional exceptions not stated in the original issue. 

### Details
We need to provide these additional exceptions to the automation: 
- If the issue includes the `Complexity: Prework` label, the automation should post the standard comment (and NOT unassign the dev)
- Otherwise, per [J and Bonnie's note](https://github.com/hackforla/website/issues/6555#issuecomment-2058078988) below, If the issue assignee matches the issue author, and the issue is not labeled `Draft`, the automation should post a note reminding the author/assignee that there should be a `Draft` label on the this (and NOT unassign the dev)
### Action Items
- [x] Refer to the previous issue #4821 and PR #6502 for the previous action items and code solution.
- [x] Add an exception to the functionality to omit issues with the `Complexity: Prework` label. (Note: Closed issue #6556 may have useful info.)
- [x] Modify `unassign-from-NIA.md`:
```  
<!-- Template for a notification to the assignee that they will be unassigned because the issue is in the "New Issue Approval" column -->

Hi @${issueAssignee}, HfLA appreciates your interest in this issue, but please note that it is in the  **"New Issue Approval"**  column of the Project Board because it has not been finalized, approved, or prioritized, and so it is not ready for assignment. For this reason, you have been unassigned from this issue. Please remember to assign issues only from the  **"Prioritized Backlog"**  column.  

The only exceptions to this rule are if you are writing an issue and the `Draft` label is applied, or if you are self-assigning to your "Pre-work Checklist" (the issue includes the `Complexity: Prework` label).   
```  
- [x] Add new code to check for the case when there is no `Draft` or `Complexity: Prework` label, but the issue assignee matches the issue author, and if this is the case post a comment such as:
```  
<!-- Template for a reminder notification when the issue assignee is also the issue author that the issue should have a `Draft` label -->

Hi @${issueAssignee}, we notice that you are assigned to an issue that you authored. Please remember to add the `Draft` label to this issue while you are working on it. 
```

### Previous issues associated 
- #4821 
- #6502 
- #6556

**Comment by t-will-gillis** [comment]
- Keeping this issue open temporarily as a reminder that team needs to discuss how to proceed with a revision to issue #4821

**Comment by ExperimentsInHonesty** [comment]
@t-will-gillis This issue is in the prioritized backlog.  If that is the appropriate spot, please add a ready for prioritization label to it and add to our agenda.

**Comment by ExperimentsInHonesty** [comment]
As pointed out by @jphamtv 
- if the user is the author they get to stay assigned but should get a reminder to add a draft label
- if the issue is a prework the author stays assigned no matter where its located.

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty @t-will-gillis this issue has `ready for dev lead` but I'm not sure what to do with it.

**Comment by roslynwythe** [comment]
- @ExperimentsInHonesty @t-will-gillis this issue has `ready for dev lead` but I'm not sure what to do with it.  PR #6556 says that it fixes this issue and that the exception for prework issues has already been implemented.  So do we need a new issue to implement this change:
> * if the user is the author they get to stay assigned but should get a reminder to add a draft label

**Comment by t-will-gillis** [comment]
Hi @roslynwythe I will be reworking this issue this afternoon

**Comment by marioantonini** [comment]
i. Availability: Th 6-9, F 9-4pm
ii. ETA: Friday EOD

**Comment by marioantonini** [comment]
Update:
1. Availability: Weekend 2-5
2. ETA: Sunday EOD

**Comment by t-will-gillis** [comment]
Hey @marioantonini your message was:

> Working on issue 6555, sorry I could not get to it sooner, but stuff came up. However, I am not totally clear on the full picture. If someone self assigns an issue, and it does not have the 'Complexity: Prework' label and it also does not have the 'Draft' label, as far as I can tell, there is no way to discern wether it should show the "Remember to add draft label" or unassign the person and post the appropriate message. Is this something that we can discuss here in slack or at tonight's meeting?

Let me know if I am missing something, of course: The way I am thinking about this is that when the automation determines that the someone assigned themselves to an issue from the NIA column without the draft/prework labels, as a last step before removing the person's assignment from the issue, the automation can check if the author of the issue (`context.payload.issue.user.login`) is the person being assigned, and if so post the other message instead of removing the self-assignment.

**Comment by marioantonini** [comment]
@t-will-gillis but the other message only applies to the draft label. And most (not sure if all) Prework issues are created by the same person that then self assgin themselves, and so according to this statement:
> the automation can check if the author of the issue (context.payload.issue.user.login) is the person being assigned, and if so post the other message instead of removing the self-assignment.

New people (assigning themselves to their Prework issue) would get the wrong message if they haven't assigned the proper label.

**Comment by t-will-gillis** [comment]
@marioantonini 
>New people (assigning themselves to their Prework issue) would get the wrong message if they haven't assigned the proper label.

If I understand your comment, this should not happen because the "Pre-work Checklist" template has the `Complexity: Prework` label pre-selected. Is this what you are referring to?

**Comment by marioantonini** [comment]
@t-will-gillis yes!!! That little bit of information I did not know, should get this done between today and tomorrow.

**Comment by marioantonini** [comment]
1. Progress: Almost done with code
2. Blockers: Might need someone that is not me to create an issue on my fork to do some tests.
3. Availability: Fri: 10am-4pm, Sat: 6-9pm
4. ETA: Once I can get the "issue created by someone else in my fork" sorted out, a couple of hours after that.
