### ISSUE TITLE
ER: Update Project Profile: Website

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#6558]
### Dependency
- [x] #6632 

### Project Name

Hackforla.org Website

### Project Card URL

website.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Anjola Jaiyeola

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Kelly Chuang
GitHub Handle: kellyc9
Role: Product Manager
Slack Member ID: U06REBB5K4M

### Project Status

Active

**Comment by JessicaLucindaCheng** [comment]
# Issue Writing
- **Availability:** 1.5 hours
- **ETA:** Friday, April 12, 2024

**Edit:** Issue has been written and added to the Dependency section of this issue.

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issue(s) in the Dependency section are merged, 
- [x] Close this ER
- [x] Move this ER to the UAT column
- [x] Contact the author of this ER to approve the changes on the [Hack for LA Site](https://www.hackforla.org/projects/website) page and add a `ready for stakeholder` label

**Comment by JessicaLucindaCheng** [comment]
@ExperimentsInHonesty 
Please let us know if the changes made to the [Hack for LA Site](https://www.hackforla.org/projects/website) page match what you requested by adding a comment to this issue.

**Comment by JessicaLucindaCheng** [comment]
This issue has been in UAT for a long time, and we got no response from the author, so I am moving this to QA.
