### ISSUE TITLE
The Hack for LA website bot made a mistake as I have done PRs recently!

### ISSUE THREAD

**Issue by colin-macrae** [hackforla/website#6563]
The Hack for LA website bot made a mistake as I have done PRs recently!
I am responding to Issue #6554 because I have been active.
See my Issue #{_list issue_} or my review in PR #{_list PR_}

## Dev Leads
This member believes that the bot has made a mistake by placing them on the "Inactive Member" list. Please see the referenced issue.

_Originally posted by @colin-macrae in https://github.com/hackforla/website/issues/6554#issuecomment-2036097327_

**Comment by t-will-gillis** [comment]
Please see the following- the message you received was a mistake. Sorry for the confusion https://github.com/hackforla/website/issues/6554#issuecomment-2035093861
