### ISSUE TITLE
Status dropdown - On Hold count/card-pull mismatch

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/website#657]
### Overview
On the Status dropdown under "Current Projects" the number next to "On Hold" shows as "(7)", which I'm assuming is the count of how many cards == "On Hold".  However, when you select On Hold only three cards are displayed.  

### Screen Shots
![e80L9XrGRc6wYlRHEf6mww_thumb_243e](https://user-images.githubusercontent.com/68244054/88843943-bf1efc80-d196-11ea-8055-ff4aed987e58.jpg)

**Comment by ExperimentsInHonesty** [comment]
i believe the bug is because of hide:true and we need to look at the JS and figure out what needs to be added so that we can make sure that anything that has hide true doesn't end up in the filter.
