### ISSUE TITLE
311 Data Project Page Updates

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#658]
### Overview
The website needs to keep the 311 project page up-to-date so that incoming volunteers can see the current status (meeting times, technologies, etc) and that team leads are getting credit for their positions. 

### Note
This information will be collected monthly

### Action Items

**Information gathering** 
- [ ] Hfla website PM to send note to project team lead to check if any changes need to be made (can consist of any inaccurate info on the project page)
  - [ ] Project Team Leads (is not up to date as of July 29, 2020)
- [ ] Project team lead to provide most up-to-date information as a comment on this issue

**Development**
- [ ] Dev team to make updates to the project page based off team lead notes 

### Resources/Instructions
[311 Project Page](https://www.hackforla.org/projects/311-data)

**Comment by johnr54321** [comment]
Hi there.  A few updates:
1. Our regular team meeting is changing from 7pm on Tuesdays to 6pm on Thursdays.
2. Front end lead is now Adam Kendis
3. Back end lead is now Jake Mensch
4. UX lead is now Dana Chen
5. Our app web address is https://www.311-data.org
6. Please update the card on the projects page to use our social media image.

**Comment by ExperimentsInHonesty** [comment]
@johnr54321 
please provide slack ID (not handle) and github handle for the leaders.

**Comment by danarchen** [comment]
slack id: U0112KZPV6C
github: danarchen

**Comment by adamkendis** [comment]
Slack ID: USNAHR0KE
github: adamkendis

**Comment by johnr54321** [comment]
Jake:
Slack ID: ULJAWB8M8
Github: jmensch1

**Comment by johnr54321** [comment]
@ExperimentsInHonesty Let us know if you need anything else. Please assign to the appropriate person. Thanks!
