### ISSUE TITLE
Update CONTRIBUTING.md Section 2.7.d with correct upstream branch

### ISSUE THREAD

**Issue by danvgar** [hackforla/website#6581]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
The readability and accuracy of our CONTRIBUTING.md documentation is crucial for ensuring a smooth onboarding process for new members. The current documentation in Section 2.7d does not provide an upstream branch for the user to pull from prior to pushing their code, and results in an error because a branch was not specified. We need to update this code to include the correct upstream branch.

### Action Items
- [x] In your local IDE, navigate to `CONTRIBUTING.md`
- [x] Replace

~~~
**IMPORTANT:** Before you push your local commits to your repository, sync your fork to the main Hack For LA website repository. `git pull upstream` will ensure that your local repository is up-to-date with the main site:

```bash
git pull upstream
```
~~~

with

~~~
**IMPORTANT:** Before you push your local commits to your repository, sync your fork to the main Hack For LA website repository. `git pull upstream gh-pages` will ensure that your local repository is up-to-date with the main site:

```bash
git pull upstream gh-pages
```
~~~

- [x] With CONTRIBUTING.md still open, make a note of the section in which the replaced content appears, so that you will know where to look in the document to preview the change.
- [x] Changes to CONTRIBUTING.md cannot be tested locally, rather they must be tested after pushing the issue branch to your fork of the repository.  Push your issue branch in the usual manner, but before creating the Pull Request, check your updates using this test URL.  Also store the test URL for use in a later step:
```
https://github.com/[REPLACE WITH GITHUB HANDLE]/website/blob/[REPLACE WITH NAME OF ISSUE BRANCH]/CONTRIBUTING.md
```
   (for example: https://github.com/bonniewolfe/website/blob/issue-branch-1234/CONTRIBUTING.md)
- [x] Create a pull request with your changes.  In the Pull Request, after the "Why did you make the changes" section, add this line to help reviewers, replacing the text in brackets (and the brackets) with the test URL from the previous Action Item.
```
For Reviewers: Do not review changes locally, rather, review changes at [REPLACE WITH TEST URL]
```

### Resources/Instructions
- [CONTRIBUTING.md](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)
- [Getting started with writing and formatting on GitHub](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github)
- This issue is part of #6208

**Comment by Ruizmichael** [comment]
i. Availability: 6/3-6/5
ii. ETA: 6/5

**Comment by Ruizmichael** [comment]
i. Availability: 6/6
ii. ETA: 6/6

**Comment by jphamtv** [comment]
Hi @Ruizmichael - Please provide an update on your progress with this issue. If you're no longer able to work on it, let us know so we can make it available to other developers to work on. Thanks!

**Comment by dcotelessa** [comment]
i. Availability: 7/1
ii. ETA: 7/1
