### ISSUE TITLE
ER: Update Project Profile: Civic Tech Jobs

### ISSUE THREAD

**Issue by kcoronel** [hackforla/website#6583]
### Dependency
- [x] #6636
- [x] #6638 
- [x] #6639
- [x] #6640
- [x] #6641 

### Project Name

Civic Tech Jobs

### Project Card URL

civic-tech-jobs.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: [Salima Yacoubi Soussane](https://hackforla.slack.com/team/U03HUJM7YCX)
- [x] Name: [Sabrina Heasley](https://hackforla.slack.com/team/U05GDBDPEDR)
- [x] Name: [Jen Chung](https://hackforla.slack.com/team/U02A6H5PVAA)
- [x] Name: [Melinda Sukosd](https://hackforla.slack.com/team/U03T1G9F46P)
- [x] Name: [Jenn Wu](https://hackforla.slack.com/team/U05JS3V38TV)
- [x] Name: [Tin Wei Chung](https://hackforla.slack.com/team/U03P6Q6FSQ5)
- [x] Name: [Gabriel Vicencio](https://hackforla.slack.com/team/U03P33ZNPGW)
- [x] Name: [Matt Pereira](https://hackforla.slack.com/team/U045XKKB5DH)
- [x] Name: [Sarah Sanger](https://hackforla.slack.com/team/U02M686LYET)
- [x] Name: [Nga Do](https://hackforla.slack.com/team/U05JS3BS9FD)

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

- [x] Name: Lu Feng
GitHub Handle: fenglugithub
Role: UI/UX Lead 
Slack Member ID: U03NV47TG4X

- [x] Name: Kanika Chotani
GitHub Handle: kchotani
Role: Product Manager
Slack Member ID: U02E7ATACAV

- [x] Name: Jimmy Juarez
GitHub Handle: JimmyJuarez10
Role: Developer Lead 
Slack Member ID: U062FQ7UXQE

- [x] Name: Armon Brown
GitHub Handle: stanarmon
Role: UX/UI Designer
Slack Member ID: U06J0UCAWHE

- [x] Name: Carmen Mak
GitHub Handle: CarmenMM1
Role: UX/UI Designer
Slack Member ID: U06313EMD41

- [x] Name: Brenda Njemanze
GitHub Handle: brendasdesign
Role: UX/UI Designer
Slack Member ID: U06MWMRSCJW

- [x] Name: Manju Chawla
GitHub Handle: itsmanjuchawla
Role: UX Researcher 
Slack Member ID: U06E9T37H9A

### Project Status

Active

**Comment by JessicaLucindaCheng** [comment]
# Issue Writing
- **Availability:** 6 hours
- **ETA:** Friday, April 12, 2024

**Comment by JessicaLucindaCheng** [comment]
# Issue Writing
- **Progress:** Wrote 2 issues for some of the requested changes. I still need to write some more issues for the rest of the changes requested.
- **Blockers:** None
- **Availability:** 2 hours
- **ETA:** Sunday, April 14, 2024

## Update
- **Progress:** All issues have been written for this ER and have been added to the Dependency section.

**Comment by JessicaLucindaCheng** [comment]
@ dev lead
Once the issue(s) in the Dependency section are merged, 
- [x] Close this ER
- [x] Move this ER to the UAT column
- [x] Contact the author of this ER to approve the changes on the [Civic Tech Jobs](https://www.hackforla.org/projects/civic-tech-jobs) page and add a `ready for stakeholder` label
- [ ] Once the changes have been accepted by the author of this ER, remove the `ready for stakeholder` label and add a `ready for product` label. Also, leave a comment that this ER is ready for further UAT and QA by product.

**Comment by LRenDO** [comment]
Hi @kcoronel! These updates to the [Civic Tech Jobs](https://www.hackforla.org/projects/civic-tech-jobs) page are complete. Please let us know if it's all set or if anything needs to be changed.
- [x] #6636
- [x] #6638 
- [x] #6639
- [x] #6640
- [x] #6641

**Comment by JessicaLucindaCheng** [comment]
This issue has been in UAT for a long time, and we got no response from the author, so I am moving this to QA.
