### ISSUE TITLE
100 Automations project card update

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#659]
### Overview
We need to make some changes to the 100automations.md file to update what displays on the webiste

### Action Items
- [ ] Add meeting time: (I have sent this info to VRMS already)
   - [ ] Wednesdays: 4:30-5:30 Management Meeting
   - [ ] Satudays 2:00pm-4:00pm Team Meeting
- [x] Change under looking for:  "content writer" to be Content Writer"
- [x] Change under looking for:  "designer" to "UI/UX designer"
- [x] The repository does not seem to be showing up because we provide the url http://github.com/100automations instead of http://github.com/100automations/website. - please change

### Resources/Instructions
[project homepage](https://www.hackforla.org/projects/100-automations)
[100 automations project card /_projects/100automations.md](https://github.com/hackforla/website/blob/gh-pages/_projects/100-automations.md)

**Comment by ExperimentsInHonesty** [comment]
It looks like the readme is not showing up in the getting started section.  I thought that was supposed to happen automatically, could someone look into what the logic is for the getting started section?

**Comment by jbubar** [comment]
![Screen Shot 2020-08-16 at 9 35 16 AM](https://user-images.githubusercontent.com/53061723/90339163-e69e0380-dfa3-11ea-947d-eeebf83c8cee.png)
Changed ReadMe to Readme, so that it works with the liquid code on _layouts/projects.html lines 118 and 176

**Comment by alexandrastubbs** [comment]
@jbubar, Is the 'ReadMe' to 'Readme' spelled out clearly enough in the wiki? Specifically, are there references to the capitalization that is required? (It has been an issue before)

**Comment by KianBadie** [comment]
This might be useful, but maybe we could change how to field is read to be more lenient on case sensitivity. So that "readme", "Readme", or "ReadMe". Unless you guys want a consistent naming convention, which I feel like is also a really good thing. 

If you want to ignore case sensitivity in Liquid, refer to [this](https://shopify.github.io/liquid/filters/downcase/)
