### ISSUE TITLE
Run VS Code Spell Checker on page-card.md 

### ISSUE THREAD

**Issue by irais-valenzuela** [hackforla/website#6591]
### Overview
We need to audit HfLA codebase files for spelling errors using the Code Spell Checker extension in VS Code in order to ensure site quality. Results will be categorized as misspellings or false positives in the HfLA spelling audit spreadsheet[^1] and will be resolved in later issues.  

### Action Items
- [x] You must use VS Code as your local text editor and install the `Code Spell Checker` VS Code extension[^2]  
- [x] Do not change any configuration settings or make any spell corrections
- [x] Open the file '_design-system/components/page-card.md' and note any Code Spell Checker errors
- [ ] Locate the file in column A ("File") of the "Page Audit" sheet. In the column labeled "Result Summary", select the appropriate option: `No errors` or `At least one error`.
- [ ] If at least one error was reported, copy/paste each cSpell message into a separate row in the `Results` sheet
- [ ] In each new row, select the appropriate value: `misspelling` or `false positive` from the "Result type" column. A false positive is a term that is not a misspelling but is not recognized by the spell checker because it is a technical term, abbreviation, acronym, URL or proper noun (name of a person, place or organization).
- [ ] Move this issue to the Questions/In Review column and apply the label `ready for dev lead`

### Merge Team
- [x] After this issue is closed, release the dependency on this issue in #5248
- [ ] After the last dependency has been released, close that issue

### Resources/Instructions
- This issue is part of #5248
[^1]: [HfLA spelling audit spreadsheet - Results](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=69989048)
[^2]: The recommended installation method is to install Code Spell Checker directly from the VS Code text editor, and those instructions can be found [here](https://code.visualstudio.com/learn/get-started/extensions). The extension can also be installed via the VS Code Marketplace website [here](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker).

**Comment by nssensalo** [comment]
i. Availability: 8-5 weekdays
ii. ETA: By Friday  5/31

**Comment by nssensalo** [comment]
I have two blockers:

1. The file I am spell checking is comprised of mostly "Lorem ipsum" text. So there are many spelling "errors". 
2. I cannot locate the file in the spelling audit spreadsheet.

* I pulled from gh-pages to get the current version.
* I installed the code spell checker in VSC
* opened the file: "_design-system/components/page-card.md"
*my created feature branch: "run-spell-checker-6591" , however no changes have been made or pushed.

Can someone clarify if I am to infact spell check "Lorem ipsum" text? 
And help me locate the file in the spell  audit spreadsheet?

Thanks a bunch!

**Comment by t-will-gillis** [comment]
Hey @nssensalo answering the 2nd item first, the file is referenced on Line 97.

For the 1st item, I think you are questioning about whether  'lorem ipsum' etc. should really be included in the Spell Check- If so, I agree that it should not. Good call and thanks for bringing this up. I believe that since this is a component that will be edited, this file should likely be on the "ignore/Paths"/ [excluded paths](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=1299740856) list. 
@roslynwythe would you agree?

**Comment by nssensalo** [comment]
@t-will-gillis, @roslynwythe   Following up on the conversation. Should I add this file to the excluded paths tab in the excel ? And be assigned another file to spellcheck?

**Comment by ExperimentsInHonesty** [comment]
@nssensalo I moved your question to the questions column, and added the ready for the merge team label.  I recommend you also post in the slack channel.

**Comment by t-will-gillis** [comment]
Hi @nssensalo Yes please add to the "ignore/Paths"/ [excluded paths](https://docs.google.com/spreadsheets/d/1c2C9zUF_LsLGrnJN_LAlPV4UObz-nYffJyOiB_M6oI0/edit#gid=1299740856) list, and then this will be complete

**Comment by t-will-gillis** [comment]
Hey @nssensalo Thank you for working on this issue! I see that you added this file to the "ignore/Paths" list. 

I am closing this issue as completed- you are good to go with your next issue.
