### ISSUE TITLE
ER: change a label on the spell check issue template

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#6615]
### Emergent Requirement - Problem
The template for fixing spelling errors using VS code has the wrong label.

### Issue you discovered this emergent requirement in
- any spelling issue

### Date discovered 
2024-04-09

### Did you have to do something temporarily
- [x] YES, manually fix all the issues made from this template to add the spelling label and remove the administrative label.
- [ ] NO

### Who was involved
@ExperimentsInHonesty 

### What happens if this is not addressed
issues are not labeled properly.

### Resources
- Issue template: [Spell check audit web page](https://github.com/hackforla/website/issues/new?assignees=&labels=Complexity%3A+Small%2C+Feature%3A+Administrative%2C+ready+for+dev+lead%2C+role%3A+back+end%2FdevOps%2C+role%3A+front+end%2C+size%3A+0.5pt&projects=&template=spell-check-audit.md&title=Run+VS+Code+Spell+Checker+on+%5BINSERT+FILE+HERE%5D)
- file to edit: .github/ISSUE_TEMPLATE/spell-check-audit.md
   - see file in repo gui: https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/spell-check-audit.md

### Recommended Action Items
- [x] Make a new issue
- [x] Discuss with team
- [x] Let a Team Lead know

### Potential solutions [draft]
make an issue to have someone update the label to replace Feature: Administrative with feature: spelling

**Comment by urvishp13** [comment]
**Availability:** 1-6pm 5/17/24
**ETA:** 5/17/24

**Comment by urvishp13** [comment]
Made the issue. It's still in Draft form as the images guiding the issue assignee are not appearing.

The issue number of the issue created for this ER is #6857

**Comment by urvishp13** [comment]
**Blockers:** 

1. How do I get the images for the dropdowns in the created issue to show? Originally, they appeared when previewing the draft, but on subsequent tries, they stopped appearing.
2. What labels do I put for the issue created?

The issue number of the issue created for this ER is https://github.com/hackforla/website/issues/6857

**Comment by urvishp13** [comment]
**Update:** Fixed the problem with the images now showing up in the dropdowns. Turns out it was an HTML elements spacing issue.

**Comment by urvishp13** [comment]
**Update:** I found the Wiki on information about labels and added them to the issue I created.

**Comment by roslynwythe** [comment]
- Thank you @urvishp13 for creating the issue and referencing issue #6857.  This ER is now complete!
