### ISSUE TITLE
Change paragraph from <h2> to <p> on header-container-content.html

### ISSUE THREAD

**Issue by w1ld-r** [hackforla/website#6633]
### Overview

In `_includes/events-page/header-container-content.html`, the paragraph in the header section is an `<h2>` header but should be a `<p>` HTML element. Using the correct element helps browsers and assistive technologies understand the structure of the content, which is important for accessibility according to the W3C accessibility guidelines.

### Details

https://github.com/hackforla/website/blob/3a5c1479d7a51730fa39a2aeab2e5c2435f7b42d/_includes/events-page/header-container-content.html#L5-L9

### Action Items

- [x] Change the `<h2>` tag to a `<p>` tag on the Events webpage
- [x] Review the changes in the browser to confirm no bugs were introduced (see [instructions](https://github.com/hackforla/website/wiki/How-to-review-Pull-Requests#Step3))
- [x] Push your changes to your private branch and submit a pull request

### Resources/Instructions

- [Events page](https://www.hackforla.org/events/)
  - [pages/events.html](https://github.com/hackforla/website/blob/gh-pages/pages/events.html) 
    - [_includes/events-page/header-container-content.html](https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/header-container-content.html)
- [W3C Web Accessibility Initiative: Page Structure](https://www.w3.org/WAI/tutorials/page-structure/)

**Comment by luisitocanlas** [comment]
i. Availability: 29 April ~ 3 May
ii. ETA: EOD 3 May
