### ISSUE TITLE
Project Pages Getting Started Link 

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#664]
### Overview
We need the 'Getting Started' link on each of the projects pages to go to the Getting Started page on the HfLA website so that prospective members are able to quickly begin the on-boarding process.

### Action Items
Development 
- [x] Update the link in the logic for the projects pages 

### Resources/Instructions
The link currently goes [here](https://github.com/hackforla/getting-started) but it **should** go [here](https://www.hackforla.org/getting-started)
Example of project page where this is occurring: https://www.hackforla.org/projects/100-automations
Logic is on [this page](https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html ), line 104

Screenshot of the link under discussion: 

<img width="1430" alt="Screen Shot 2020-08-02 at 10 41 08 AM" src="https://user-images.githubusercontent.com/66918724/89125719-7b860480-d4ae-11ea-92e6-51a7d85a6705.png">

**Comment by drubgrubby** [comment]
Done. PR #669
