### ISSUE TITLE
Delete unused Slack svg file

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6648]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started) and attend an onboarding session.
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).

### Overview
We have refactored HTML/CSS throughout the site to use a single version of the Slack icon and in this issue we will remove the unused svg file from the codebase.  

### Action Items
- [x] In your IDE, delete the file `https://github.com/hackforla/website/blob/gh-pages/_includes/svg/icon-slack-color.svg`
- [x] Don't forget to use `git add` to stage the deletion and `git commit` to commit the change
- [x] Proceed with a pull request in the usual manner

### Resources/Instructions
- This issue resulted from #5758

**Comment by vaishnavbalodhi** [comment]
Please assign me this issue.

**Comment by Beatriz-G** [comment]
Availability:  Tuesday-Thursday 9am-5pm
ETA: End of day Wednesday 4/17
