### ISSUE TITLE
Create wiki page: how to change the fill color of an svg

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6654]
### Overview
We require a wiki page to describe our strategy for reusing svg icons across the website by changing the fill color via CSS.  

### Details
- So far the strategy has been implemented for the icon: `_includes/svg/icon-slack.svg` so focus on the Slack icon for examples
- Key elements are:
   - The goal is to store a single svg of each icon type and to apply a fill color when needed using CSS
      - CSS in `sass/elements/_icons.scss` specify that svg elements with class `.icon` within the project resource section are displayed with their "native" color, but those outside the project resource section will have a default `fill` color based on the current text color.  The interior color of an svg is changed using the "fill" attribute.  
     - The preferred HTML structure is to "wrap" the svg graphic file in an outer `svg` element which allows the outer svg to specify attributes specific to the instance such as the svg-specific attribute `viewBox` for scaling/positioning, aria attributes for accessibility, and class specifications for color.   For an example see #6141

### Action Items
- [ ] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki).  Following the process given in [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) when completing the remaining Action Items.  
- [x] Create a draft of the new wiki page in a comment in this issue.  
- [x] For review, move this issue to the "Questions/In Review" column and apply the label "ready for merge team".  
- [x] After approval, copy the link to the draft wiki page into the table in [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) 

### Resources/Instructions
- This issue resulted from #5758 and that ER contains links to several issues which implement the strategy described above. 
- SCSS for icons:  https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_icons.scss

**Comment by Maarimar** [comment]
Availability: 05/09-05/11
ETA: 05/11

**Comment by Maarimar** [comment]
### **Bellow is the draft of the new wiki page that explains how to customize the color of an SVG icon using CSS.** 



# How to Customize the Fill Color of an SVG Icon

While each icon type has a single SVG source file, you can control its displayed color using CSS. Here's how:

 **Default Color Behavior:**

- Icons within the project resource section inherit their native color defined in the SVG itself.

- Icons outside the project resource section inherit the default fill color based on the surrounding text color.

**Customizing Color Outside Project Resources:**

1. Wrap the SVG: Encase the original SVG within an outer SVG element.

2. Apply a Class: Assign a class to the outer SVG element to target it with specific CSS styles. This allows you to control the fill color without modifying the original SVG.

**Example Code Snippet:**

```
<svg role="img"  viewBox="0 0 100 100"  aria-labelledby="titleID">
   <title id="titleID">GitHub</title>
   {% include svg/icon-github-color.svg %}
<svg>
```
By following these guidelines, you can effectively reuse SVG icons with dynamic color control while ensuring accessibility for all users.

**Comment by roslynwythe** [comment]
Hi @Maarimar this looks very nice, but I have a tiny issue with the example code that you selected.  Was that sample code found in the HfLA website codebase?  Please use this example instead:
```
<svg role="img"  viewBox="0 0 100 100"  aria-labelledby="titleID">
   <title id="titleID">GitHub</title>
   {% include svg/icon-github-color.svg %}
<svg>
```
When that is complete please move this issue into "Questions/In Review" and apply the label "ready for dev lead".  Thank you!

**Comment by Maarimar** [comment]
Hi! @roslynwythe it was an example from the code base. It was created here #6141. I have no problem changing it for the one you provided instead.

**Comment by roslynwythe** [comment]
@Maarimar thank you for creating this wiki page.  I went ahead and added the link to [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) and checked that box so this issue is complete!

**Comment by roslynwythe** [comment]
@Maarimar thank you for creating this wiki page.  I went ahead and added the link to [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) and checked that box so this issue is complete!
