### ISSUE TITLE
Create wiki page providing guidance how to test the WINS page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6680]
### Overview
We need to document the test/review process for ensuring that the various elements of the WINS webpage are still working after a change.  

### Action Items
- [x] We are currently in the process of moving the old wiki to the new [website-wiki repo](https://github.com/hackforla/website-wiki), so we will not be making any changes or additions to the old wiki at this time. Thus, we will be adding wiki content through a different process now. Read [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki).  Follow the process given in [How to Contribute to the Wiki](https://github.com/hackforla/website/wiki/How-to-Contribute-to-the-Wiki) when completing the remaining Action Items.  
- [x] Create list of items that should work
- [x] Create a list of steps for replicating how each is working (add under resources sublist below)
- [x] Get signoff from dev and product leads

### Resources/Instructions
[WINS webpage](https://hackforla.org/wins)

#### List of items that should work and can be tested
- "Share your wins" button
- "Role" and "Team" dropdown menus
- LinkedIn/GitHub icons in each WIN (if provided)
- badges under the quote in each WIN
- "see more" link on the bottom of each WIN
- the "x" button to close the WIN modal after clicking "see more"

#### How to Test Each Item
- "Share your wins" button should open a new tab to "Share your wins" Google form
- "Role" and "Team" dropdown menus should expand on hover
    - checkboxes in the dropdown menus should filter the displayed WINS to display only those that are associated with the checked criteria
    - hovering off the dropdown menus should make the previously displayed menu disappear. If hover back into the space the dropdown was in within a certain time frame, that dropdown menu should reappear as expanded
    - after checking/unchecking criteria in the dropdown, clicking anywhere on the page should make the dropdown menu disappear
- if the posted WIN has a LinkedIn and/or GitHub icon, the associated icon should open a new tab to LinkedIn/GitHub
- all the badges underneath the quote in the WIN should be hoverable with a tooltip displayed on hovering saying what the badge means
- the "see more" link on the bottom right hand corner of the WIN should open a modal for the associated WIN. It should show in full detail all the contents of the WIN
    - from within the "see more" modal, the LinkedIn and GitHub links should open to a new tab to the corresponding website
    - the "x" button on the modal should close the modal and take the user back to the previous (filtered) WINS page

**Comment by urvishp13** [comment]
Availability for this week: 4/23/24 12pm - 6pm
My estimated ETA for completing this issue: EOD

**Comment by urvishp13** [comment]
**List of Items that Should Work**

- "Share your wins" button
- "Role" and "Team" dropdown menus
- LinkedIn/GitHub icons in each WIN (if provided)
- badges under the quote in each WIN
- "see more" link on the bottom of each WIN
- the "x" button to close the WIN modal after clicking "see more"

**How to Test Each Item**

- "Share your wins" button should open a new tab to "Share your wins" Google form
- "Role" and "Team" dropdown menus should expand on hover
    - checkboxes in the dropdown menus should filter the displayed WINS to display only those that are associated with the checked criteria
    - hovering off the dropdown menus should make the previously displayed menu disappear. If hover back into the space the dropdown was in within a certain time frame, that dropdown menu should reappear as expanded
    - after checking/unchecking criteria in the dropdown, clicking anywhere on the page should make the dropdown menu disappear
- if the posted WIN has a LinkedIn and/or GitHub icon, the associated icon should open a new tab to LinkedIn/GitHub
-  all the badges underneath the quote in the WIN should be hoverable with a tooltip displayed on hovering saying what the badge means
- the "see more" link on the bottom right hand corner of the WIN should open a modal for the associated WIN. It should show in full detail all the contents of the WIN
    - from within the "see more" modal, the LinkedIn and GitHub links should open to a new tab to the corresponding website
    - the "x" button on the modal should close the modal and take the user back to the previous (filtered) WINS page

**Comment by urvishp13** [comment]
**Blocker:** I have completed all the Action Items except the last one. What do I need to do to make sure the dev and product leads review my draft for the wiki/additions to this issue?

**Comment by roslynwythe** [comment]
Thank you @urvishp13 for providing a useful resource for developers and reviewers testing the WINS page.
