### ISSUE TITLE
Change alignment of SDG card in project page.

### ISSUE THREAD

**Issue by Thinking-Panda** [hackforla/website#6683]
### Overview
As developers, we need to change the alignment of the text in the SDG card in order to improve readability.

### Action Items
- [x] Open the file `_sass\components\_project-page.scss` in the IDE.
- [x] Make changes to the file so that the text in the gray area of the SDG card is left aligned.
- [x] Using Docker, confirm that the text is left aligned.

### Resources/Instructions
- https://www.hackforla.org/projects/lucky-parking
<details><summary>screenshot of lucky parking</summary>

![image](https://github.com/hackforla/website/assets/37763229/1aae34aa-87a6-41c7-8b70-0749c7952101)
 
</details> 

- https://www.hackforla.org/projects/311-data
<details><summary>Screenshot of 311-data</summary>

![image](https://github.com/hackforla/website/assets/37763229/e55a2d2d-8374-4eda-8371-a1c4ca79d7d2)

</details> 

- FYI - not all project pages have SDGs
- This issue resolves ER #6290.

**Comment by JackCasica** [comment]
i. Availability: Tomorrow, All day
ii. ETA: Tomorrow, EOD

**Comment by Thinking-Panda** [comment]
@JackCasica Thank you for working on this issue. In future, once you assign yourself to an issue, move it to the "In Progress" column in the project board. Thanks!
