### ISSUE TITLE
ER: Event Page "Our Events" Section Unexpected Behavior When Resizing

### ISSUE THREAD

**Issue by tony1ee** [hackforla/website#6687]
### Emergent Requirement - Problem
When browsing the events page, interacting with the boxes in the "Our Events" section followed by resizing the window can lead to  unexpected behavior, including extra character in the title, or even loss of content.

#### Steps to reproduce the issue

1. make the browser window narrow enough (width <768 in Chrome developer mode) so cards in "Our Events" section will be displayed stacked in a single column
2. Open Events Page at https://www.hackforla.org/events/
3. interact with the arrow by each card to fold/unfold cards
4. resize/widen browser window so cards appear side by side (width >=768 in Chrome developer mode)
5. issue reproduced:
&nbsp; a. if card was folded before resizing, the content of the card will not display after resizing
&nbsp; <details show image> <img width="553" alt="image" src="https://github.com/hackforla/website/assets/16524851/c25b8f5b-cb65-4424-8ef9-a0d9eae6b9d3"> </details>
&nbsp; b. if card was unfolded before resizing, there will be an extra symbol `∟` (`U+221F`) displayed next to the title
&nbsp; <details show image><img width="427" alt="image" src="https://github.com/hackforla/website/assets/16524851/6380d90c-c513-4a85-8f28-d1249869ecf9"> </details>

### animated GIF to reproduce the issue
![1](https://github.com/hackforla/website/assets/16524851/53113b75-de9e-407d-87fc-d527e806593c)

![2](https://github.com/hackforla/website/assets/16524851/f69d1f7e-dde2-4a23-b52b-3acc61cc2a13)

### Issue you discovered this emergent requirement in
- N/A

### Date discovered 
04/19/2024

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@tony1ee 

### What happens if this is not addressed
Website visitor will experience inconvenience and frustration for this unexpected behavior, which could negatively impact growth and retention.

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

**Comment by roslynwythe** [comment]
Thank you @tony1ee for this report.  I think we will want an animated git to demonstrate the problem.

**Comment by tony1ee** [comment]
@roslynwythe certainly! the description has been updated with animated GIF showing steps to reproduce the problem.

**Comment by roslynwythe** [comment]
@tony1ee This looks very good and is ready for prioritization.  I know that you had expressed interest in writing issues and you have completed an `Issue Making: Level 1` issue, perhaps you would like to write the issue to complete this ER?  If so, please go ahead and self-assign this ER.  

If not, please hide this comment.

**Comment by tony1ee** [comment]
**Availability**: Sat 8-10 PM, Sun 4-10 PM
**ETA**: EOD 04/28/2024

**Comment by ExperimentsInHonesty** [comment]
@tony1ee I moved this issue into the In Progress column. In the future, please move any issues you are assigned or self-assigned to that column.

**Comment by tony1ee** [comment]
closed as completed as #6775 fixed it
