### ISSUE TITLE
Refactor codeql.yml file

### ISSUE THREAD

**Issue by w1ld-r** [hackforla/website#6691]
### Overview

We need to refactor the `codeql.yml` file by moving the issue creation steps into a separate workflow so that developers don't receive confusing errors when they test CodeQL issues.

### Details 

Since we released the changes in https://github.com/hackforla/website/issues/5059, developers picking up CodeQL issues have encountered errors related to incorrect tokens and rate limiting. Since the three steps added by the changes in said issue aren't needed to test CodeQL issues, we need to refactor to ensure they do not block PR reviews and testing.

We want to refactor for the following reasons:

1. These errors seem to be confusing developers and result in a lot of unnecessary troubleshooting. 
   - One error is "Input required and not supplied: github-token." Right now, our documentation isn't up to speed and many devs don't know how to set up their `HACKFORLA_ADMIN_TOKEN` correctly. 
   - The other error happens when the CodeQL workflow runs and hits the GitHub API rate limit. This requires the dev to wait about an hour and run the workflow again. This is not an ideal situation for testing CodeQL issues, since the steps that hit the rate limit are not required for testing CodeQL issues.
   - Another error occurs because the developer does not have their Issues tab activated in their personal repo.
3. The errors may be preventing the CodeQL scan from running properly locally, which prevents people from testing properly.
4. We need to be able to test properly and confirm that when CodeQL alerts are resolved, they switch from Open to Closed.

### Action Items

- [ ] Separate the last three steps out of the codeql.yml file into a separate issue creation workflow.
- [ ] Modularize the workflows to minimize duplicate code
- [ ] Make the issue creation workflow triggered by a manual run only
- [ ] Test the above and ensure that the codeql.yml workflow scans issues and generates alerts as expected
- [ ] Test the above and ensure that the issue creation workflow generates issues and adds all labels as expected
- [ ] Demonstrate that when CodeQL issues are resolved locally, that their state/status switches from Open to Closed (this can be done using an existing CodeQL issue after the above changes are deployed)

### Resources/Instructions

- https://github.com/hackforla/website/issues/5059
- https://github.com/hackforla/website/pull/6503
- This is an issue where the testing concerns first arose: https://github.com/hackforla/website/pull/6651

**Comment by elliot-d-kim** [comment]
A scope question: this addresses the issues found affecting the CodeQL workflow, but I'm curious if the subsequent errors produced by the 'Issue trigger' workflow (at least partially due to no project board in contributors' forks) would also fall into the domain of this ticket. I think they could be separated, since the CodeQL workflow can be in a completely resolved state prior to addressing the errors in the Issue trigger workflow (in my testing).

Unless the refactor you have in mind happens to address both at once?

**Comment by w1ld-r** [comment]
> A scope question: this addresses the issues found affecting the CodeQL workflow, but I'm curious if the subsequent errors produced by the 'Issue trigger' workflow (at least partially due to no project board in contributors' forks) would also fall into the domain of this ticket. I think they could be separated, since the CodeQL workflow can be in a completely resolved state prior to addressing the errors in the Issue trigger workflow (in my testing).
> 
> Unless the refactor you have in mind happens to address both at once?

Hey @elliot-d-kim What errors are you seeing in the issue trigger workflow? Do you mean with `issue-trigger.yml`? The only issue there that I'm seeing is on my personal repo, the "missing" labels aren't being added. Do you have screenshots of the error you're seeing?

**Comment by roslynwythe** [comment]
@gaylem As we discussed, I support the idea of separating the issue making part of codeql.yml into a separate workflow, since issue creation does not have to run in the context of a push or PR.

**Comment by ExperimentsInHonesty** [comment]
@gaylem Issues cannot be prioritized until the following is true
1. All comments have be processed and any relevant info added to the top part of the issue, and the comments hidden.
2. The Overview needs to be worded as We need to do X for Y reason.  Where X = what we are doing, and Y= why we are doing it.
    So instead of 
    >Since we released the changes in https://github.com/hackforla/website/issues/5059, developers picking up CodeQL issues have encountered errors related to incorrect tokens and rate limiting. Since the three steps added by the changes in said issue aren't needed to test CodeQL issues, we need to refactor to ensure they do not block PR reviews and testing.
    
    It should say something to the effect of 
    ```
    we need to refactor codeql.yml to ensure [whatever is blocking] do not block PR reviews and testing.
    ```
I know the temptation is to provide a lot of detail in the overview, but it's really designed
1. to be something you can read in a millisecond and then read more under details or action items if you need more.  This allows the issue to be prioritized easily.
2. a definition of done, so that we can validate the results of the issue against that summary.

**Comment by elliot-d-kim** [comment]
@gaylem Yes, I was talking about errors that `issue-trigger.yml` runs into.

<details>
<summary>Error in Add-Issue-To-Project-Board</summary>

![Error in Add-Issue-To-Project-Board](https://github.com/hackforla/website/assets/106627338/35d2df50-9d3e-4a6c-8304-1488d0feecbf)

</details>

<details>
<summary>Error in Add-Missing-Labels-To-Issues</summary>

![Error in Add-Missing-Labels-To-Issues](https://github.com/hackforla/website/assets/106627338/3161b51a-c6ad-412f-85bb-20402e6abc2d)
</details>


<details>
<summary>Several of these errors</summary>

![Several Issue Trigger Errors](https://github.com/hackforla/website/assets/106627338/c6989d47-3747-4c73-836c-199a279126d0)

</details>

I also received a bunch of emails about these jobs failing.

If issue generation is performed according to a fixed schedule by a cron job (+ manual triggers), wouldn't the workflow run periodically on contributors' forks as well, generating these errors? Would it be possible to do push/cron + manual on the main branch and only manual on forks?

**Comment by w1ld-r** [comment]
Hey @elliot-d-kim, thanks for sharing this. I'm not seeing the errors you shared, so I'm thinking there might be something off with your setup. Do you have a `TEAMS` and a `HACKFORLA_PA_BOT` token set up in your personal repo? These are needed for the `issue-trigger.yml` workflow to run. Here are the scopes: 

```
  * to match the `HACKFORLA_BOT_PA_TOKEN` select:
    * public_repo (under 'repo')
    * admin:org_hook 
  * to match the `HACKFORLA_ADMIN_TOKEN` select:
    * public_repo (under 'repo')
    * admin:org_hook 
    * write:org (under 'admin:org')
```

Let me know if that resolves those errors for you.

Regarding the workflow runs, that's a good point. I personally think we should only run the issue creation workflow manually for now. Push isn't really necessary for this use case, and if we set the branch to the `gh-pages` branch, it will still run on private repos since devs have that branch, too. I updated the instructions to reflect this and will push a new commit for it, but let me know if you have any additional thoughts. Thanks for your help!!
