### ISSUE TITLE
Add github-handle for Ryan Mayott in engage.md

### ISSUE THREAD

**Issue by sakibian** [hackforla/website#6732]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/engage.md` in the IDE
- [x] Replace:
```
- name: Ryan Mayott
```
with
```
- name: Ryan Mayott
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/   
Project Webpage: https://www.hackforla.org/projects/engage

- This issue is part of #5441.

**Comment by santiseccovidal** [comment]
Availability for this week: Wednesday-Friday-Sunday
My estimated ETA for completing this issue: Finished

**Comment by santiseccovidal** [comment]
Blockers: Issue in 2.7.d Working on an issue (4): Pulling from upstream before you push

Hi I tried following the instruction:
---------
IMPORTANT: Before you push your local commits to your repository, sync your fork to the main Hack For LA website repository. git pull upstream will ensure that your local repository is up-to-date with the main site:

git pull upstream

You can also sync your fork directly on GitHub by clicking "Sync Fork" at the right of the screen and then clicking "Update Branch"
---------
I did the last option via GitHub webpage.
Now I encounter this when I try doing "git pull upstream"

![Screenshot 2024-05-13 121859](https://github.com/hackforla/website/assets/53095957/5aa463ed-0cdc-4e48-ba7a-e2ca330a1c69)

Yet my repository in GitHub looks like this:

![Screenshot 2024-05-13 122012](https://github.com/hackforla/website/assets/53095957/f9ed3a36-b894-44f0-8fe4-6ad71543638b)

I don't remember if there were changes when I used "Sync Fork".
What are the next steps I could follow?

**Comment by t-will-gillis** [comment]
Hey @santisecco! From our Slack conversation earlier and you successfully posting your PR, it appears you are good to go. If so, you can remove the `Status: Helped Wanted` label. If not, please feel free to send another message and I can help you out. Thanks!

**Comment by santiseccovidal** [comment]
Thanks @t-will-gillis
