### ISSUE TITLE
Add github-handle for Virginia Wu in food-oasis.md

### ISSUE THREAD

**Issue by sakibian** [hackforla/website#6737]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/food-oasis.md` in the IDE
- [x] Replace:
```
- name: Virginia Wu
```
with
```
- name: Virginia Wu
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [ ] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/    
Project Webpage: https://www.hackforla.org/projects/food-oasis

- This issue is part of #5441.

**Comment by Panipopomango** [comment]
i. Thursdays after 4pm
ii. a month

**Comment by ExperimentsInHonesty** [comment]
@Panipopomango I will move this issue to the in progress column.  In future, please do that on any issues you get assigned or self assign.

Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by ExperimentsInHonesty** [comment]
@Panipopomango I am removing you from this issue.  You can pick up a new issue from the prioritized backlog when you are ready.

**Comment by cchrizzle** [comment]
i. Progress: Replaced "- name: Virginia Wu" with "- name: Virginia Wu
  github-handle: " as requested

ii. Blockers: "git pull upstream gh-pages" results in the following errors:
"fatal: 'upstream' does not appear to be a git repository
fatal: Could not read from remote repository."

iii. Availability: an hour to an hour and a half a day.

iv. ETA: As soon as I figure out the errors.

**Comment by Thinking-Panda** [comment]
@cchrizzle Please follow the steps in [CONTRIBUTING.md](https://github.com/hackforla/website/blob/2e3c45fede99e61f479548ccca3f0dda83e351db/CONTRIBUTING.md#14b-clone-repo-2-verify-origin-remote-url) to check if you have an upstream remote set up.

**Comment by cchrizzle** [comment]
@Thinking-Panda Got it, thank you! Submitted my commit for review.
