### ISSUE TITLE
Updates to Toolkit & 2FA Pages

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#674]
### Overview
We need to update the URLs on the Toolkit page to include the correct links for the existing guides. 

### Action Items

Here are the URLs that need to appear on this page: 
- [x] Github issues: https://www.hackforla.org/guide-pages/github-issues
- [x] 2FA page: https://www.hackforla.org/guide-pages/2FA.html
- [x] Survey Reporting Dashboard page: https://www.hackforla.org/guide-pages/survey-reporting-dashboard-guide

Other changes from pull request comments: 
- [x] I would put the svg's in the includes file so it can be implemented in 1 line of code on the toolkit page, which would increase the readability of the code.
- [x] I think it is important to take out inline styling and move it to scss file, or reuse existing classes in place.

**Comment by ruben1s** [comment]
I have a pull request pending.
![screencapture-0-0-0-0-4000-toolkit-2020-08-08-18_09_14](https://user-images.githubusercontent.com/33906590/89722871-dd110c00-d9a3-11ea-9d5f-9abaf7b5c7a0.png)
![screencapture-0-0-0-0-4000-toolkit-2020-08-08-18_09_36](https://user-images.githubusercontent.com/33906590/89722878-e9956480-d9a3-11ea-820c-685c554eb588.png)
![screencapture-0-0-0-0-4000-toolkit-2020-08-08-18_09_52](https://user-images.githubusercontent.com/33906590/89722881-ec905500-d9a3-11ea-935b-0afecfc19330.png)

**Comment by ruben1s** [comment]
Here are my updates in my recent pull request. 
-All links go to correct place.
-scss file was created.
-svg was stored in seperate place
-mobile view was optimized




![screencapture-0-0-0-0-4000-toolkit-2020-08-09-12_53_16](https://user-images.githubusercontent.com/33906590/89740666-8eb14b00-da3f-11ea-843a-ac25bc69ecab.png)



![screencapture-0-0-0-0-4000-toolkit-2020-08-09-12_53_44](https://user-images.githubusercontent.com/33906590/89740668-9670ef80-da3f-11ea-8490-654a0132c265.png)
