### ISSUE TITLE
To update the tdm calculator landing page : [TDM Calculator]

### ISSUE THREAD

**Issue by Parisajf** [hackforla/website#6765]
### Project Name

LA TDM Calculator

### Project Card URL

---New Project---

### Update the Title?

YES

### Update the Description?

YES

### Description

We need to update the Team members of the TDM calculator Landing Page

Landing Page: https://www.hackforla.org/projects/tdm-calculator
Roster:https://accounts.google.com/InteractiveLogin?continue=https://docs.google.com/spreadsheets/d/13joo1xyUJfMeQ3hGD9sVM_ChE9iMy85UTXPmEkOiMaM/edit&followup=https://docs.google.com/spreadsheets/d/13joo1xyUJfMeQ3hGD9sVM_ChE9iMy85UTXPmEkOiMaM/edit&ltmpl=sheets&osid=1&passive=1209600&service=wise&ifkv=AaSxoQzRTjyVoHuaBhXcW_1nl3RaO0iKX6vB2pHt8aCQC7REck7LJ75-ylWRFUBymmql4cQlxzVBxA#gid=103729280

### Update the Hero Image?

NO

### Update the Image?

YES

### Image

team member pictures will be updated

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

YES

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: update the leaders based on the latest[ Roster](https://accounts.google.com/InteractiveLogin?continue=https://docs.google.com/spreadsheets/d/13joo1xyUJfMeQ3hGD9sVM_ChE9iMy85UTXPmEkOiMaM/edit&followup=https://docs.google.com/spreadsheets/d/13joo1xyUJfMeQ3hGD9sVM_ChE9iMy85UTXPmEkOiMaM/edit&ltmpl=sheets&osid=1&passive=1209600&service=wise&ifkv=AaSxoQzRTjyVoHuaBhXcW_1nl3RaO0iKX6vB2pHt8aCQC7REck7LJ75-ylWRFUBymmql4cQlxzVBxA#gid=103729280)

### Add person(s) and info to Leadership?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name:
GitHub Handle:
Role:
Slack Member ID:

### Project Status

Active

**Comment by ExperimentsInHonesty** [comment]
@Parisajf I am closing this issue because the inputs are not conforming to the standards expected.  I would like you to add this to the agenda for Thursday, and we can walk through this together.
