### ISSUE TITLE
Identify where the label: `ready for dev lead` is being used

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#6783]
### Overview
We need to document where the ready for dev lead label is referenced so that we can make a plan to change some of the issues and GHAs to use `ready for merge team` instead.

### Action Items
- [x] Create a spreadsheet called `Ready for merge team and dev lead rationalization`, in the folder (Resource 1.01) and add the link to Resource 2.01 below
- [x] Add the following columns
   - Column 1: location
   - Column 2: location_type
   - Column 3: merge_team_can_handle
   - Column 4: notes
- [x] Identify all the places that there are references to `ready for dev lead` (Resource 1.02) and add the URL into column 1 (in the code base, should be a URL)
- [x] Add location type to column 2 (GHA, WIKI, Issue Template, open issues)
- [x] Add a note to indicate what the purpose of the ready for dev lead label is
- [x] Move this issue to the Questions column and add the `Ready for dev lead label`

#### Merge team action items
- [ ] clear the dependency on #6784

#### Resources for creating this issue
- 1.01 [Google Drive: Tech Leads and Merge Team folder](https://drive.google.com/drive/folders/1Z2HdqlZ8Kd7Dnc8vf463X2gKhqmxlGPc)
- 1.02 [GitHub search of repo:hackforla/website "ready for dev lead"](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+%22ready+for+dev+lead%22&type=code)

#### Resources gathered during the completion of this issue
- 2.01 Spreadsheet: [Ready for merge team and dev lead rationalization](https://docs.google.com/spreadsheets/d/1aLfyfhjzOvGoxEKB-Bn7bvOCQZuG0W6xdgKE0mY69Q8/edit#gid=0)

**Comment by urvishp13** [comment]
**Availability:** 1-4pm 4/30/24, 12-3pm 5/2/24
**ETA:** End of this week

**Comment by ExperimentsInHonesty** [comment]
@urvishp13 I just checked out the spreadsheet and I have the following notes

### FYI - I changed some formatting and some content
For background information about good spreadsheet formatting, see https://github.com/hackforla/product-management/wiki/Google-Sheets
- changed the column header from notes to notes_summary (I really liked how succinct you were in your notes, and I want to keep that).
- added the column header notes_detail (I added this column, so I could write my review and share it with the merge team)
- On some of your notes_summary, changed 
   - from: `review the completed template once issue is submitted`
   - to: `review the issue created from the template`
- added data validation to two columns: merge_team_can_handle and location_type
- froze the top row, so that it would stay visible when you scroll down
- wrapped the content in all the columns, so that if it overflows the content does not get cut off
- top aligned the whole sheet, then bottom aligned the top row
- removed the extra rows to the right
- removed extra rows at bottom, but left you 110 rows for the open issues and wiki you will be adding

### Please make these changes
- [x] replace the commit number in the URLs with `gh-pages`
- [x] add the [open issues](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+%22ready+for+dev+lead%22++&type=issues&state=open) that the issue asks for
   - of the 98 issues I see when I go there, you can add the following notes to all the `Resolve CodeQL Alert` issues
      - notes_summary: 
         ```
         recommendation to dismiss the alert
         ```
      - notes_detail: 
         ```
         later if we decide Merge Team can handle this, it will need to be changed manually on this open issue, but will be addressed for future alerts by changing /github-actions/trigger-issue/create-codeql-issues/issue-body.md?plain=1#L13 if necessary.
         ```
- [x] add the [wiki pages](https://github.com/search?q=repo%3Ahackforla%2Fwebsite+%22ready+for+dev+lead%22&type=wikis) that the issue asks for

**Comment by urvishp13** [comment]
@ExperimentsInHonesty I have made the requested additions/changes. There were 2 queries of the 98 issues in the link you provided that didn't have anything to do with the `ready for dev lead` label so I didn't put them in the spreadsheet.

**Comment by urvishp13** [comment]
**Blocker:** @roslynwythe can you close this issue as discussed in last Thursday's meeting.

**Comment by roslynwythe** [comment]
Thank you @urvishp13 for compiling the spreadsheet
