### ISSUE TITLE
Remove BoP from untaggedRepoIds in get-project-data.js

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6786]
### Dependency
- [x] #6643

### Overview
We need to remove the [BOP repo](https://github.com/civictechindex/BOP) from the list of untagged repos in `get-project-data.js` and to perform testing to confirm that language and contributor data are still pulled from repository and displayed on the BOP project page.  

### Details
In the past, the BOP repo was was identified as an "untagged" repo in `github-actions/trigger-schedule/github-data/get-project-data.js` and was located at https://github.com/codeforamerica/brigade-playbook.   It has now been moved to the Civic Tech Index organization and has been tagged with the topic tag `hack-for-la`.  

`github-actions/trigger-schedule/github-data/get-project-data.js` runs as part of `.github/workflows/schedule-daily-1100.yml` and updates the file `_data/external/github-data.json` with contributor and language data for each project.  

### Action Items
- [x] In `github-actions/trigger-schedule/github-data/get-project-data.js` remove the id `277577906` from the `untaggedRepoIds` array.
- [x] Remove the comment containing the id `277577906`
- [x] This code runs as part of a GHA workflow that updates the file `data/external/github-data.json`, and testing should be performed to verify that after update, data stored in github-data.json is unchanged and that the language and contributor data stored on the [BOP project page](https://www.hackforla.org/projects/brigade-organizers-playbook) are unchanged.   It will be necessary to test the code in your fork of the hackforla/website repository.  Testing will require a token which is described in "Tip 7" in https://github.com/hackforla/website/issues/6537#issuecomment-2041147335.  For further testing guidance, see [GitHub Actions- "Schedule Daily 1100" workflow](https://github.com/hackforla/website/issues/6643#issuecomment-2132043028)

### Resources/Instructions
- Revised: Tip 7 Using Personal Access Tokens to test in your own repository - https://github.com/hackforla/website/issues/6537#issuecomment-2041147335
- See [GitHub Actions- "Schedule Daily 1100" workflow](https://github.com/hackforla/website/issues/6643#issuecomment-2132043028) for specific instructions for testing
- [BOP project page](https://www.hackforla.org/projects/brigade-organizers-playbook)

**Comment by t-will-gillis** [comment]
Hi @roslynwythe I added `ready for dev lead` and put this in "New Issue Approval" only so it does not get lost, but of course feel free to label or move it as you think...

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe the BOP repo just got moved today to another org, its in the same org as Civic Tech Index
https://github.com/civictechindex/BOP

**Comment by mrodz** [comment]
i. **Availability:** 9AM-8PM MTWThFSSn
ii. **ETA:** Before 6/26/24

**Comment by mrodz** [comment]
I did not mean to close this issue. When did I a merge on my own fork I accidentally used a closing keyword, which closed it here. I am terribly sorry.

**Comment by jphamtv** [comment]
@mrodz I don't see a question here, so I'm moving this back to the In Progress column. If you have a specific question about this issue:

1. Please comment with your question
2. Move the issue back to the Questions / In Review column

Note: The Questions / In Review column is for specific asks when you're stuck or when an issue can't be reviewed and closed with a PR. In your case, I see you're addressing this with a PR.

Thanks!
