### ISSUE TITLE
Manage truncation of contributors name in filter tag on toolkit page

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6787]
### Overview
As developers we need to provide a visual cue when a contributor's name is truncated within a filter tag on the Toolkit page.  This occurs at medium-to-large screen sizes for some contributor names.  

### Action Items
- [x] The suggested approach is to use the CSS style `text-overflow: ellipsis` on the containing block element, so that if text overflows, the hidden text is represented by an ellipsis ('…')

### Resources/Instructions
https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

<details><summary>Screenshot of current truncation of name "Ahdithan Uthayakumar Tarang Gupta"

</summary>

![image](https://github.com/hackforla/website/assets/5314153/e56b7fbf-eff4-4e8d-a408-bac9c7457911)

</details> 

Toolkit [webpage](https://www.hackforla.org/toolkit) | [HTML](https://github.com/hackforla/website/blob/gh-pages/pages/toolkit.html) | [include](https://github.com/hackforla/website/blob/gh-pages/_includes/current-guides.html) | [JavaScript](https://github.com/hackforla/website/blob/gh-pages/assets/js/toolkit.js)

- This issue resulted from #5233

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty Is this the strategy you had in mind?  And should we check all filter tags for truncation, or just the filter tags representing contributor names?

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe All other columns should have a limit to the characters, and only people's names should be as long as they need with visible truncation (...)
- full name will appear on the card itself 
- if you ctrl-F or cmd-F and search for the full name it must highlight the name on the filters (is that even possible)?

**Comment by roslynwythe** [comment]
> @roslynwythe All other columns should have a limit to the characters, and only people's names should be as long as they need with visible truncation (...)
> 
> * full name will appear on the card itself

I don't see the name of the contributor on the card.  Should I make an ER for that?  Will we need a designer ?

> * if you ctrl-F or cmd-F and search for the full name it must highlight the name on the filters (is that even possible)?

Yes when I do ctrl-F it does highlight the name on the filters.  

This issue is ready for prioritization, unless you feel it needs more guidance re: implementation?

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe 

> I don't see the name of the contributor on the card. Should I make an ER for that? Will we need a designer ?

It's a future feature that will arrive with the cards when they are different (another design team is working on that)

Bonnie: 
> if you ctrl-F or cmd-F and search for the full name it must highlight the name on the filters (is that even possible)?

Roslyn:
> Yes when I do ctrl-F it does highlight the name on the filters.

Bonnie:
What I mean was if the name is truncated, how will it be responsive to someone searching the persons whole name using the traditional ctrl-f when what it shows on the screen is ...

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty based on this [test page](https://bug-93709-attachments.webkit.org/attachment.cgi?id=157699) I believe cntrl-F will highlight the name on the filter even if a portion of it is hidden by ellipsis.

**Comment by aadilahmed** [comment]
i. Availability: 9-5 pm Monday-Friday
ii. ETA: EOD 6/23/24
