### ISSUE TITLE
Update 100Automations Project File

### ISSUE THREAD

**Issue by NivenPrasad** [hackforla/website#680]
### Overview
We need to update the 100Automations file to reflect a variety of changes.

### Action Items
- Add Camila Arias to Project Card
  - Role: UI/UX Designer
  - Full name: Camila Arias
  - Slack ID: U018S4VQK3M
  - GitHub handle: CamilaArias
- Update Slack channel details

**Comment by ExperimentsInHonesty** [comment]
already addressed on #800
