### ISSUE TITLE
Update data in `inactive-members.json` file

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6837]
### Overview
The file `github-actions/utils/_data/inactive-members.json` was not updated this month due to a hiccup in the automation, therefore the data needs to be manually updated. Note that although this issue involves a GitHub Action, testing the GHA is not required.

### Action Items
- [x] Copy the entire content of this file [inactive-members.json](https://github.com/t-will-gillis/website/blob/update-monthly-workflow/github-actions/utils/_data/inactive-members.json)
- [x] and paste into/replace the entire contents of [inactive-members.json](https://github.com/hackforla/website/blob/gh-pages/github-actions/utils/_data/inactive-members.json)

### Resources/Instructions
- Part of the `schedule-monthly.yml` workflow

**Comment by moazDev1** [comment]
Availability: 5/22 5PM - 10PM
ETA: 5/22 EOD
