### ISSUE TITLE
ER: discrepancies in meeting data sourced from API calls to VRMS vs. `vrms-data.json`

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6838]
### Emergent Requirement - Problem
Two discrepancies were noted:
1. meeting data sourced from API calls to VRMS (`/events-check`) do NOT show Civic Tech Jobs DEV meeting Wed 5-6 pm, but that meeting is displayed on pages using `vrms-data.json` as a data source (`/projects/civic-tech-jobs` or `/events`)
2. meeting data sourced from API calls to VRMS (`/events-check`) show Civic Tech Jobs DEV meeting Fri 2-4 pm, but that meeting is NOT displayed on pages using `vrms-data.json` as a data source (`/projects/civic-tech-jobs` or `/events`)

Note: Currently `/project-meetings` uses API calls to VRMS but will be modified in the near future to use `vrms-data.json`

### Issue you discovered this emergent requirement in
- #6815

### Date discovered 
5/7/2024

### Did you have to do something temporarily
- [ ] YES
- [ ] NO

### Who was involved
@roslynwythe 

### What happens if this is not addressed
Erroneous/incomplete meeting data may be displayed on the website

### Resources

<details><summary>Screenshot of Civic Tech Jobs meetings in VRMS </summary>

taken on 2024-06-02

<img src="https://github.com/hackforla/website/assets/37763229/80f91c40-8cfd-48f1-9862-3cbd18f37a93" width=400px>
</details> 

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
Create an issue to identify the source of the discrepancy
- if the source is front end code that retrieves or displays meeting data, create a front end issue to fix
- if the source is back end code that retrieves or stores meeting data, create a back end issue to fix
- if the source is VRMS, hand off to that team

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I added a screenshot of the meetings in VRMS for CTJ. is this issue ready for me to prioritize?

**Comment by roslynwythe** [comment]
The discrepancies noted in this ER are no longer evident.
