### ISSUE TITLE
Update to Civic Tech Index Page

### ISSUE THREAD

**Issue by jsachsman** [hackforla/website#684]
### Overview
Please replace Arun as Product Manager with myself.

### Action Items
Please change **from**:
  - name: Arun Prakash
    role: Product Manager
    links:
      slack: 'https://app.slack.com/team/U015GPCKUFK'
      github: 'https://github.com/arunprakash87'
    picture: https://avatars.githubusercontent.com/arunprakash87

**To**:
  - name: Jonathan Sachsman
    role: Product Manager
    links:
      slack: 'https://app.slack.com/team/U018CSDL5FZ'
      github: 'https://github.com/jsachsman'
    picture: https://avatars.githubusercontent.com/jsachsman

### Resources/Instructions
https://raw.githubusercontent.com/hackforla/website/gh-pages/_projects/civic-tech-index.md

**Comment by ghost** [comment]
Made a PR: #713

**Comment by ExperimentsInHonesty** [comment]
@ethanh256 Add a screen shot of what it looks like locally, and slack into the Civic Tech Index channel asking jonathan sachsman to approve.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/58455740/92332047-acb69f00-f02f-11ea-827b-7f0138a403e1.png)

**Comment by jsachsman** [comment]
Hi @ethanh256 thanks so much. We should have asked for one more change - can you change

**name**: Bonnie Wolfe
**role**: Acting PM (Project looking for a new PM)

to 

**name**: Bonnie Wolfe
**role**: Technical Product Manager

**Comment by ghost** [comment]
@jsachsman Updated
