### ISSUE TITLE
Fix Capitalization of "Slack" in `_communities-of-practice.scss`

### ISSUE THREAD

**Issue by tony1ee** [hackforla/website#6845]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to fix the following line of code to correctly capitalize "Slack" when it's used to refer to the app or the company in our code and content.
https://github.com/hackforla/website/blob/612389d3c6d6b6b86b179185096b489115cd55f2/_sass/components/_communities-of-practice.scss#L133

### Action Items
- [x] Open the file `website/_sass/components/_communities-of-practice.scss` in your code editor
- [x] On Line 133, replace `slack` with `Slack`.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.
- [x] Create a pull request with your changes

### For Merge Team
- [ ] Release the dependency for this issue in ER #6163. If all the dependencies have been completed, close that issue.

### Resources/Instructions
Project Page: https://www.hackforla.org/communities-of-practice
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_sass/components/_communities-of-practice.scss

This issue is part of ER #6163.

**Comment by deepak-getpu** [comment]
Availability: 15 hours
ETA: By this week.
