### ISSUE TITLE
Standardize Slack channels references using ID and archives: join-us

### ISSUE THREAD

**Issue by marioantonini** [hackforla/website#6847]
### Overview

We need to fix our reference to the admin Slack channel in the join us file to use the channel ID instead of the channel name, so that if the name of the channel gets changed, the link will still work.  We are also changing the link to use archives instead of messages.

### Action Items

- [x] In your IDE open the file `pages/join-us.html`
- [x] Look for the line that references the slack channel `admin` by name `https://hackforla.slack.com/messages/admin`
- [x] Change the following:
**From:**
```
Connect with our leadership team on the <strong>#admin</strong> <a href="https://hackforla.slack.com/messages/admin"
```
**To:**
```
Connect with our leadership team on the <strong>#admin</strong> <a href="https://hackforla.slack.com/archives/C01Q24YF56J"
```
- [x] Ensure that clicking the Slack link resolves to the admin channel in Slack at the following places:
  - [x] On the [Join Us page](https://www.hackforla.org/join), the Slack link to the admin channel in the `Advise Us` card

### Resources/Instructions
- https://github.com/hackforla/website/blob/gh-pages/pages/join-us.html
- On the Slack desktop app, you can right-click on a channel name, select `View channel details` and find the Channel ID in the bottom of the details pane. The admin channel ID is: `C01Q24YF56J`
- This issue resulted from #6224 and aligns with #4535

**Comment by roslynwythe** [comment]
@marioantonini Please provide more guidance to the developer about which webpage should be used for testing/review.  Also, this is optional but I usually like to provide the Section number in CONTRIBUTING.md just to make it easier to find the relevant area to test/review.  

When writing issues, we typically assign ourselves and apply the label `Draft` so I will apply those.   When you are done with your modifications, you can remove `Draft` and remove your assignment, then add the label 'ready for product`

**Comment by marioantonini** [comment]
@roslynwythe added further actions to provide more guidance as well as extra references linked to the issue.
