### ISSUE TITLE
Configure Dependabot to exclude 'patch' version updates

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6849]
### Overview
The Dependabot is currently configured to check for updated dependencies, and if a new version is available to create a PR. The current config checks for all version updates regardless of size. We need to modify the configuration file to reduce the frequency of the Dependabot updates and exclude 'patch' version update.

### Action Items
Reference the "Resources/ Instructions" below for information regarding Semver and Dependabot version updates.
- [x] Locate the [dependabot.yml](https://github.com/hackforla/website/blob/gh-pages/.github/dependabot.yml) file
- [x] Modify the configuration file as needed so that the Dependabot ignores Semver 'patch' version updates, but continues to generate PRs for 'major' and 'minor' updates
- [x] Add ignore statement ( IMPORTANT NOTE this syntax needs to be verified)
```
ignore:
   update-types: ["version-update:semver-patch"]
```  
- [ ] Important note: confirm that this **does not apply to security updates and patches**, only to version updates.

### Resources/Instructions
- [Introduction to Semantic Versioning](https://www.geeksforgeeks.org/introduction-semantic-versioning/) from Geeks for Geeks
- [About Dependabot version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates)
- [Configuring Dependabot version updates](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates#enabling-dependabot-version-updates)  

This issue was initiated by ER #6797

**Comment by JackCasica** [comment]
Availability: May 20, 2024 (Monday)
ETA: May 20, 2024 (Monday)

**Comment by JackCasica** [comment]
Looking at the [dependabot 2.0 yml schema](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/dependabot-2.0.json), this syntax  does appear to be correct: 
> `ignore:
   update-types: ["version-update:semver-patch"]`



Additionally, per the [`ignore` documentation](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#specifying-dependencies-and-versions-to-ignore), the `ignore.update-types` configuration only affects Dependabot version updates, and not security updates, meaning we can safely set up these ignore configurations for patch updates.
> When used alone, the ignore.versions key affects both Dependabot updates, but the ignore.update-types key affects only Dependabot version updates.
