### ISSUE TITLE
Change QA Validation URL in `add-github-handle` issue template

### ISSUE THREAD

**Issue by tony1ee** [hackforla/website#6850]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to change the URL for QA validation in `add-github-handle` issue template so it defaults to `code` instead of `preview`. 

### Action Items
- [x] Open the file `.github/ISSUE_TEMPLATE/add-github-handle.md` in your code editor
- [x] Replace 
```
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/[INSERT-PATH-TO-PROJECT-FILE]  
```
with
```
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/[INSERT_PROJECT_FILE]?plain=1
```
- [x] Push your issue branch to your fork of the website repository, as described in [Section 3.1.a of CONTRIBUTING doc](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#31a-push-all-changes-to-your-issue-branch), for example:  `git push --set-upstream origin test-update-labels-1234`  
- [x] The response from the push command will include the URL for creating a pull request. Copy/Paste the URL for creating the Pull Request for later.  
- [x] Browse to your fork of the website repository and click Settings 
  <details><summary>Screenshot of Repository Settings</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/8ecf2e55-2187-4ab9-acf1-2fd7548291a1)

  </details> 
- [x] Change the default branch to the new issue branch
  <details><summary>Screenshot of Default Branch Setting</summary>

  ![image](https://github.com/hackforla/website/assets/5314153/945fe02e-035f-4215-9c25-1d46c209d8c0)

  </details> 
- [x] Further down on the settings page under Features, check the Issues checkbox
  <details><summary>Screenshot of Issues Checkbox</summary>

  ![image](https://github.com/hackforla/website/assets/16524851/563fc427-ba07-4e47-9440-2580bbfcad52)

  </details> 

- [x] From the Issues page, click "New Issue" then locate the template updated by your issue, and click "Get Started" to open the issue template. 
- [x] Copy the URL of the issue creation page as [URL OF ISSUE TEMPLATE] and save for later use.  
- [x] Verify the changes of the issue template.
- [x] Complete the Pull Request process by visiting the URL saved from the push command.
- [x] In the PR copy/paste this text immediately before the section "Screenshots of Proposed Changes Of The Website"
```
 ### For Reviewers
- Use this URL to check the updated issue template: [URL OF ISSUE TEMPLATE]
```
- [x] Replace the text in the square brackets (as well as the square brackets) with the URL of the updated issue template
- [x] Submit your pull request with your changes for review
- [x] After PR is merged, be sure to follow the steps above to change your default branch back to `gh-pages` and to disable Issues feature

### Resources/Instructions
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/add-github-handle.md?plain=1
This issue is made for ER #6771.

**Comment by Kle012** [comment]
i. Availability: 05/15/2024 3PM-5PM
ii. ETA: within 2 weeks

**Comment by tony1ee** [comment]
Hi @Kle012, just want to let you know that this issue is not yet approved to be taken and there might be changes before it is approved. We don't want to see our contributors' effort go to waste, I suggest you un-assign yourself and move it back to **New Issue Approval** and only take issues from Prioritized Backlog, where issues are approved and ready to be taken.

**Comment by Kle012** [comment]
Thank you, I have moved the issue back and unassigned myself

**Comment by ino-iosdev** [comment]
ETA: EoD
