### ISSUE TITLE
Update Project Profile: Expunge Assist

### ISSUE THREAD

**Issue by sylvia-nam** [hackforla/website#6859]
### Project Name

Expunge Assist

### Project Card URL

expunge-assist.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

NO

### Update the Image?

NO

### Update the Technologies?

NO

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

NO

### If YES on remove person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name:

### Add person(s) and info to Leadership?

NO

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name:
GitHub Handle:
Role:
Slack Member ID:

### Project Status

Active

**Comment by sylvia-nam** [comment]
Request adding [PDF](https://drive.google.com/file/d/1KFQlBA2yBdv1rgvpjJAlCMDz1reGaQ3S/view?usp=drive_link) of Project One sheet to this repo: https://github.com/hackforla/product-management/tree/master/project-one-sheets.

This follows [instructions](https://github.com/hackforla/expunge-assist/issues/379#issuecomment-2113932818) from Bonnie at PM-Org meeting on 2024-5-17

**Comment by ExperimentsInHonesty** [comment]
@sylvia-nam all the pms have permission to add the document to that repo, because it's the product-management repo.  Please ask your pms to do that part.

**Comment by ExperimentsInHonesty** [comment]
@sylvia-nam also, the data format should be

YYYY-MM-DD
its currently 2024-5-17 and needs to be 2024-05-17 

This is the instruction across our entire org, that dates are always that format for consistency.  The standard comes from the international Standards Organization https://www.iso.org/iso-8601-date-and-time-format.html

**Comment by sylvia-nam** [comment]
@amejiamesinas here's the [PDF](https://drive.google.com/file/d/1Sl0FsFU9cq5RO5K4dDtGbhKDep1CQOwl/view?usp=drive_link) One Sheet for the PM repository

**Comment by ExperimentsInHonesty** [comment]
- I am closing this issue and moving the details to https://github.com/hackforla/website/issues/6579
