### ISSUE TITLE
Revise "Peer Led" Leadership Type in Community of Practice Page to "Community Led"

### ISSUE THREAD

**Issue by A-Wu5** [hackforla/website#6861]
### Overview

We need to revise the Leadership Type on the Communities of Practice page, so that we only have two types across all the CoPs (less confusion for people onboarding).

### Action Items
- [x] Navigate to `_data/internal/communities` in your local IDE
- [x] Replace all instances of `Peer Led` to be `Community Led`  in the `.yml` files :
    - [x] Edit the `engineering.yml` file 
    - [x] Edit the `ui-ux.yml` file
- [x] See that the changes have been correctly made locally and provide screenshots 

### Resources
- Page where visual changes occur: https://www.hackforla.org/communities-of-practice
- [data/internal/communities/engineering.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/communities/engineering.yml)
- [data/internal/communities/ui-ux.yml](https://github.com/hackforla/website/blob/gh-pages/_data/internal/communities/ui-ux.yml)

Initialized by ER #6188

**Comment by mrodz** [comment]
i. **Availability:** 4PM-8PM MTWThF
ii. **ETA:** 4:30PM/EOD
