### ISSUE TITLE
Add 'Leadership Option' to Issue Template for CoP Information Update 

### ISSUE THREAD

**Issue by A-Wu5** [hackforla/website#6862]
### Overview
We need to update the issue template for `Communities of Practice information updates` so that there are options for Leadership Type

#### Details
<details><summary>Currently has no option to edit</summary>

![image](https://github.com/hackforla/website/assets/37763229/adcf4419-c643-4289-a822-99c4826d15f5)
</p>
</details> 

<details><summary>Example of how the yes/no drop downs work</summary>
<p>

![image](https://github.com/hackforla/website/assets/37763229/84dabc36-d6aa-4ee5-85d3-c507af18cadc)

</p>
</details> 

### Action Items
Edit the issue template 
- [x] Change Leadership Type: NO to have a YES/NO dropdown
- [x] Add the following text under that
   ```
   If YES on Change Leadership Type, choose the Leadership Type; if NO, leave the field with the NA value:
   ```
- [x] Add a dropdown with the following values, with the NA value being a default value
   - N/A
   - Mentor Led
   - Community Led

### Resources
- Issue template for making changes
  - [New Issue: Communities of Practice information updates ](https://github.com/hackforla/website/issues/new?assignees=&labels=role%3A+product%2CP-Feature%3A+Communities+of+Practice%2Ctime+sensitive%2CComplexity%3A+Missing%2Csize%3A+missing&projects=&template=communities-of-practice-information-updates.yml&title=Communities+of+Practice+information+updates%3A+%5BINSERT+NAME+OF+Community+of+Practice%5D)
  - [File: communities-of-practice-information-updates.yml](https://github.com/hackforla/website/blob/gh-pages/.github/ISSUE_TEMPLATE/communities-of-practice-information-updates.yml)
  - issue templates directory: [.github/ISSUE_TEMPLATE](https://github.com/hackforla/website/tree/gh-pages/.github/ISSUE_TEMPLATE)

Initalized from ER #6188

**Comment by DrAcula27** [comment]
- **Availability**: weekdays 5pm - 8pm Pacific time, _starting Monday June 10, 2024_

- **ETA**: June 14, 2024

How to test issue template: https://github.com/hackforla/website/issues/4786#issuecomment-1670584024
- NOTE: do not need to create the labels in my repo

**Comment by DrAcula27** [comment]
@A-Wu5 @roslynwythe I have some questions/blockers:
- **Blocker:** I have followed the instructions [here](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) (minus creating the labels per @roslynwythe during our office hours yesterday) up until this step: `From the Issues page, click "New Issue" then locate the template updated by your issue, and click "Get Started" to open the issue template.`
  - I don't see the issue template named `Communities of Practice information updates`
- **Question:** Do you know if I need to make the dropdown fields required fields?
- **Question:** Should the text below the "Change Leadership Type" dropdown be a description field within the dropdown?

**Comment by roslynwythe** [comment]
@DrAcula27 
> @A-Wu5 @roslynwythe I have some questions/blockers:
> 
> * **Blocker:** I have followed the instructions [here](https://github.com/hackforla/website/issues/4786#issuecomment-1670584024) (minus creating the labels per @roslynwythe during our office hours yesterday) up until this step: `From the Issues page, click "New Issue" then locate the template updated by your issue, and click "Get Started" to open the issue template.`
>   
>   * I don't see the issue template named `Communities of Practice information updates`

I assume that in your fork of the website repo (`https://github.com/DrAcula27/website`), you made the issue branch `leadership-option-6862` the default, and enabled issues.  I am curious, if you go back to specifying `gh-pages` as the default, and then create a new issue, do you see the `Communities of Practice information updates` template?  If so, then it would seem that some change you made in the template is causing a problem.  If not, then we will have to ask Jessica for help, because she has more experience working with issue templates.  

> * **Question:** Do you know if I need to make the dropdown fields required fields?

Based on examination of the current file, it appears that fields with "Yes" or "No" options are all required, so I would say yes, make it required. 

> * **Question:** Should the text below the "Change Leadership Type" dropdown be a description field within the dropdown?

I don't understand the question - what text are you referring to? Are you referring to the values listed in the 3rd action item?  I envision the  "Change Leadership Type" dropdown to be similar to the "Remove person(s) and info from CoP file?" which appears in a later field.

**Comment by DrAcula27** [comment]
@roslynwythe and @JessicaLucindaCheng 
With `gh-pages` as the default branch, the `Communities of Practice information updates` issue template shows up as the 7th one down. What kind of edits to the template would cause it to not show up on my feature branch? Below shows the changes I made to the file so far:

#### Results of `git diff HEAD^ -- .github/ISSUE_TEMPLATE/communities-of-practice-information-updates.yml`
```yml
   - type: markdown
     attributes:
       value: "Change Description: NO"
-  - type: markdown
+  - type: dropdown
+    attributes:
+      label: "Change Leadership Type"
+      options:
+          - "YES"
+          - "NO"
+      description: "If YES on Change Leadership Type, choose the Leadership Type; if NO, leave the field with the NA value:"       
+    validations:
+      required: true
+  - type: dropdown
     attributes:
-      value: "Change Leadership Type: NO"
+      label: "Leadership Type"
+      options:
+        - "N/A"
+        - "Mentor Led"
+        - "Community Led"
+      default: "N/A"
+      description: "Select the type of leadership if applicable."
   - type: markdown
     attributes:
       value: "Change Slack Link: NO"
```

**Comment by JessicaLucindaCheng** [comment]
@DrAcula27 

> @roslynwythe and @JessicaLucindaCheng With `gh-pages` as the default branch, the `Communities of Practice information updates` issue template shows up as the 7th one down. What kind of edits to the template would cause it to not show up on my feature branch? Below shows the changes I made to the file so far:
> 
> #### Results of `git diff HEAD^ -- .github/ISSUE_TEMPLATE/communities-of-practice-information-updates.yml`
...

Try fixing the errors shown when viewing the code in your [forked repo's branch](https://github.com/DrAcula27/website/blob/leadership-option-6862/.github/ISSUE_TEMPLATE/communities-of-practice-information-updates.yml?plain=1). Let me know if that works.

**Comment by DrAcula27** [comment]
@JessicaLucindaCheng and @roslynwythe 

First, thank you for pointing out those errors; I had not noticed them before!
- I was able to resolve those errors. [Here](https://github.com/DrAcula27/website/issues/new?assignees=&labels=role%3A+product%2CP-Feature%3A+Communities+of+Practice%2Ctime+sensitive%2CComplexity%3A+Missing%2Csize%3A+missing&projects=&template=communities-of-practice-information-updates.yml&title=Communities+of+Practice+information+updates%3A+%5BINSERT+NAME+OF+Community+of+Practice%5D) is the link to my revision of the template. Let me know your thoughts!
