### ISSUE TITLE
Enhance Guide Page Template Responsiveness

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#688]
### Overview
We need to update the template for the guide/how to pages to be more responsive so that they adapt to the content of varying guide pages. 

### Dependency
Design system

### Action Items

Development
- [ ] Set content module to fixed width of 800 pixels max (see image a below)
- [ ] Update header to be more responsive to the amount of content it holds (see image b below)

### Resources/Instructions
[Getting Started Page](https://www.hackforla.org/guide-pages/github-issues)
[2FA Page](https://www.hackforla.org/guide-pages/2FA.html)
[Survey Reporting Dashboard Guide Page](https://www.hackforla.org/guide-pages/survey-reporting-dashboard-guide)

### Images

(a) 
![Screen Shot 2020-08-18 at 12 18 52 PM](https://user-images.githubusercontent.com/66918724/90538800-091f5080-e14d-11ea-920a-5aabf964d39a.png)

(b)
![Screen Shot 2020-08-18 at 12 19 41 PM](https://user-images.githubusercontent.com/66918724/90538844-1ccab700-e14d-11ea-9cc0-62914689ab4f.png)

VS 

![Screen Shot 2020-08-18 at 12 19 30 PM](https://user-images.githubusercontent.com/66918724/90538857-22280180-e14d-11ea-9818-9d83f9b94892.png)

**Comment by cnk** [comment]
This may be a solved problem. The red callouts on this page move with the window size. Check how that page is making this work.  https://www.hackforla.org/guide-pages/survey-reporting-dashboard-guide.html
