### ISSUE TITLE
Team Meetings Page Time Zone Update

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#690]
### Overview
We need to display the time and time zone in a format that is understandable to the user so that they can easily understand what time a team meeting occurs and if that time suits their schedule. 

### Action Items

Development 
- [x] Identify & resolve the bug causing midnight (or 12:00 am) to show as 0:00 am (screenshot below)
- [x] Add in the time zone next to the time (be sure this is responsive to where the user's browser is reflecting)

### Resources/Instructions
[Project Team Meetings page](https://www.hackforla.org/project-meetings)

![Screen Shot 2020-08-18 at 1 27 44 PM](https://user-images.githubusercontent.com/66918724/90545505-bf3b6800-e156-11ea-8e01-91478b3ec13a.png)

**Comment by drubgrubby** [comment]
Completed:
1) Text showing the users time zone has been added above the calendar listings.
2) The bug that showed midnight at 0:00 has been fixed.

**Comment by drubgrubby** [comment]
This shows the time zone text at the top, and that the time=0:00 has been fixed (see VRMS):

<img width="753" alt="Screen Shot 2020-09-11 at 1 02 32 AM" src="https://user-images.githubusercontent.com/68244054/92966674-d3f4de00-f42c-11ea-8d8a-a9788c9ff1e0.png">

This is the alternate/default text if the browser can't find a time zone:

<img width="727" alt="Screen Shot 2020-09-11 at 5 11 26 AM" src="https://user-images.githubusercontent.com/68244054/92966769-fc7cd800-f42c-11ea-89dc-98ca04e6a0c4.png">

**Comment by alexandrastubbs** [comment]
https://github.com/hackforla/website/pull/726#issuecomment-694529839
