### ISSUE TITLE
Mobile Responsiveness on Engage project page: Eli Selkin card text is displayed with wrong margin

### ISSUE THREAD

**Issue by ha-bach** [hackforla/website#6902]
### Overview

In the Engage project page, the text for Eli Selkin's card does not have the same visual margin as the other cards when displayed in phone portrait view.

![image](https://github.com/hackforla/website/assets/37560463/4d4d06db-5302-4e21-9a10-836947165b9c)

### Design:

- [ ] Check the mobile responsiveness of this page (use your mobile to do it ;) )
- [ ] If there is any bug/any inconsistency or problem, however small or large, edit this issue and list the bug with screenshots in the Overview section above. _You have more than one bug? duplicate this issue and create one issue per bug. 
- [ ] List all the changes to implement to correct the bug (eg: resizing..) in the development action items below. (don't hesitate to create 1 checkbox for each changes)
- [ ] Put the issue(s) in the review column to check the feasibility with the devs. 

### Development

- [ ] Implement the following changes : '_list your changes here_ '
- [ ] Ensure that the correction doesn't break any other pages that is connected to the one your changing. For that, check  [the sitemap](https://www.hackforla.org/sitemap.xml)

### Resources/Instructions

Page where bug is observed: https://www.hackforla.org/projects/engage (in the Current Project Team section.)

**Comment by ExperimentsInHonesty** [comment]
@muninnhugin You drafted this issue.  Is this part of an ER?

**Comment by ha-bach** [comment]
Hi! It’s not, I just found a bug and not sure where to report it.

**Comment by ExperimentsInHonesty** [comment]
Bonnie said: 
>@muninnhugin You drafted this issue. Is this part of an ER?

Ha Bach said:
>Hi! It’s not, I just found a bug and not sure where to report it.

@muninnhugin got it.  This is the template we use ([Emergent Request](https://github.com/hackforla/website/issues/new?assignees=&labels=Complexity%3A+Missing%2C+ER%2C+Feature+Missing%2C+role+missing%2C+size%3A+0.25pt&projects=&template=emergent-request.md&title=ER%3A+%5Breplace+with+info+%5D+)).  Please remake this issue as an ER and you can close this issue as unplanned with a link to the ER you created instead.

**Comment by ha-bach** [comment]
> Bonnie said:
> 
> > @muninnhugin You drafted this issue. Is this part of an ER?
> 
> Ha Bach said:
> 
> > Hi! It’s not, I just found a bug and not sure where to report it.
> 
> @muninnhugin got it. This is the template we use ([Emergent Request](https://github.com/hackforla/website/issues/new?assignees=&labels=Complexity%3A+Missing%2C+ER%2C+Feature+Missing%2C+role+missing%2C+size%3A+0.25pt&projects=&template=emergent-request.md&title=ER%3A+%5Breplace+with+info+%5D+)). Please remake this issue as an ER and you can close this issue as unplanned with a link to the ER you created instead.

Got it, thank you for following up with me!

**Comment by ha-bach** [comment]
Closing this issue as 

> Bonnie said:
> 
> > @muninnhugin You drafted this issue. Is this part of an ER?
> 
> Ha Bach said:
> 
> > Hi! It’s not, I just found a bug and not sure where to report it.
> 
> @muninnhugin got it. This is the template we use ([Emergent Request](https://github.com/hackforla/website/issues/new?assignees=&labels=Complexity%3A+Missing%2C+ER%2C+Feature+Missing%2C+role+missing%2C+size%3A+0.25pt&projects=&template=emergent-request.md&title=ER%3A+%5Breplace+with+info+%5D+)). Please remake this issue as an ER and you can close this issue as unplanned with a link to the ER you created instead.

Closing this issue as per discussion, I will post the link for the ER here once I create it.

**Comment by ha-bach** [comment]
New ER created: #7089

**Comment by kgold2018** [comment]
- this issue is a dublicate of #7089
