### ISSUE TITLE
ER: duplicate GitHub icons and inconsistent locations

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6903]
### Emergent Requirement - Problem
We have 4 slack icons in the code base, all with different names and locations.  We should only have one of each color, that we use everywhere.

### Issue you discovered this emergent requirement in
- #1900 

### Date discovered 
2023-10-23

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@jefflueck @ExperimentsInHonesty 

### What happens if this is not addressed
- redundancy in code
- hard to change out the icon for any new icon

### Resources
- Refer to #5758 for resolution of Slack icons

list of icons:
-  assets/images/technologies-icons/github-icon-1.svg:
   -  used in ? nowhere?
- _includes/svg/icon-github-color.svg (black and white)
   -  used in: [_includes/resource-card.html](https://github.com/hackforla/website/blob/63a016af0d506d2a562e110bc524fa278c3cd7a0/_includes/resource-card.html#L12)
-  _includes/svg/icon-github-small.svg
   - used in [_data/internal/toolkitresources.yml](https://github.com/hackforla/website/blob/63a016af0d506d2a562e110bc524fa278c3cd7a0/_data/internal/toolkitresources.yml#L22)
- /assets/images/wins-page/icon-github-small.svg
   - used in [assets/js/wins.js](https://github.com/hackforla/website/blob/63a016af0d506d2a562e110bc524fa278c3cd7a0/assets/js/wins.js#L293), 
- assets/images/communities-of-practice/icon-github-small.svg 
   -  used in [pages/communities-of-practice.html](https://github.com/hackforla/website/blob/63a016af0d506d2a562e110bc524fa278c3cd7a0/pages/communities-of-practice.html#L85)
-  _includes/svg/icon-github.svg (how is it used on dark background?) 
   - used in [_data/navigation/social.yml](https://github.com/hackforla/website/blob/63a016af0d506d2a562e110bc524fa278c3cd7a0/_data/navigation/social.yml#L32)
-  [assets/images/wins-page/wins-badges/github.svg](https://github.com/hackforla/website/blob/63a016af0d506d2a562e110bc524fa278c3cd7a0/assets/images/wins-page/wins-badges/github.svg?plain=1)
   - used in [assets/js/wins.js](https://github.com/hackforla/website/blob/63a016af0d506d2a562e110bc524fa278c3cd7a0/assets/js/wins.js#L293)

<details><summary>_includes/svg/icon-github.svg</summary>

![image](https://github.com/hackforla/website/assets/5314153/f0c4742d-0c10-4435-9d20-4d96deddfe5d)

</details> 
<details><summary>_includes/svg/icon-github-color.svg</summary>

![image](https://github.com/hackforla/website/assets/5314153/73a8bffd-483d-4123-bab4-1bf64cd5434d)

</details> 

### Recommended Action Items
- [ ] Make a new issue as described below

### Potential solutions [draft]
The proposed strategy is to retain `_includes/svg/icon-github.svg` and remove all others
- #6908 
- #6909
- #6910
- #6911

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe This ER needs a reference to the Slack issue where this is being done, since there is good guidance in that issue that might be reusable here

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe It looks like you already made all these issues, so can I close this ER?

**Comment by roslynwythe** [comment]
> @roslynwythe This ER needs a reference to the Slack issue where this is being done, since there is good guidance in that issue that might be reusable here

Done
