### ISSUE TITLE
Remove unused GitHub icon

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6908]
### Overview
We need to remove the unused file `assets/images/technologies-icons/github-icon-1.svg` in order to maintain clean file folders.  

### Action Items
- [x] Remove the file `assets/images/technologies-icons/github-icon-1.svg`
- [x] Add/Commit the change and proceed with a PR in the usual manner. 

### Resources/Instructions
- This issue resulted from #6903

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty Files in the folder `assets/images/technologies-icons` appear to be unused.  Should they be deleted?

Also I noticed that the github bot removed the `ready for product` label.  Do you have any idea why that might have happened?

**Comment by harith-aaron** [comment]
Can you assign me? I am ready to do it now.

**Comment by roslynwythe** [comment]
> Can you assign me? I am ready to do it now.

@harith-aaron No, the issue is only available to members of Hack for LA.  Please see https://www.hackforla.org/join for information about becoming a member.

**Comment by samuelusc** [comment]
i. Availability: I will be working on it on Monday, Thursday and Friday.
ii. ETA: It is estimated to be done before next weekend.

**Comment by roslynwythe** [comment]
@samuelusc I need to remove your assignment on this issue because it has not been approved nor prioritized.  That is why it was in the "New Issue Approval" column.  Developers should only assign issues that are in the "Prioritized Backlog" column.

**Comment by samuelusc** [comment]
@roslynwythe Understood. Thanks for the clarification.

**Comment by ino-iosdev** [comment]
ETA: End of June 6
