### ISSUE TITLE
Update Resource card on Project pages to use `icon-github.svg`

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6909]
### Overview
We need to update the code that renders the "Resources" card on the project pages, to reference the GitHub graphic file  `_includes/svg/icon-github.svg`, and also to remove `_includes/svg/icon-github-color.svg`.  These changes will eliminate a duplicate GitHub graphic file, resulting in a cleaner codebase. 

### Action Items
- [x] Update `_includes/resource-card.html` and `_sass/components/_project-page.scss` if needed, so that the"Resources" card on the project pages references the graphic file `_includes/svg/icon-github.svg` in place of the current file `_includes/svg/icon-github-color.svg`
- [x] Remove the file `_includes/svg/icon-github-color.svg` 
- [x] Use Docker to preview a sample Project page such as `/projects/311-data` to ensure that the appearance and behavior is unchanged from the current page.  

### Resources/Instructions
- #6654
- This issue resulted from #6903

**Comment by ha-bach** [comment]
Working on this issue!
Availability: Friday, Saturday, Wednesday
ETA: end of Saturday
