### ISSUE TITLE
Update "External Resources" card on Toolkit page to use `icon-github.svg`

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6910]
### Overview
We need to update the code that renders the "External Resources" section on the Toolkit page, to reference the GitHub graphic file  `_includes/svg/icon-github.svg`, and also to remove `_includes/svg/icon-github-small.svg` .  These changes will eliminate a duplicate GitHub graphic file, resulting in a cleaner codebase. 

### Action Items
- [x] Update `_data/internal/toolkitresources.yml` and `_sass/components/_toolkit.scss`  if needed, so that the"External Resources" card on the [Toolkit webpage](https://www.hackforla.org/toolkit) references the graphic file `_includes/svg/icon-github.svg` in place of the current file `_includes/svg/icon-github-small.svg` 
- [x] Remove the file `_includes/svg/icon-github-small.svg` 
- [x] Use Docker to preview the Toolkit page (`/toolkit`) to confirm that the appearance and behavior of the GitHub icon is unchanged

### Resources/Instructions
[_data/internal/toolkitresources.yml](https://github.com/hackforla/website/blob/63a016af0d506d2a562e110bc524fa278c3cd7a0/_data/internal/toolkitresources.yml#L22)
[Toolkit webpage](https://www.hackforla.org/toolkit)
- This issue resulted from #6903

**Comment by aidanwsimmons** [comment]
Availability: weekday afternoons, weekend mornings
ETA: Monday EOD
