### ISSUE TITLE
Update Team Meeting data on the Events page to show meeting frequency

### ISSUE THREAD

**Issue by Thinking-Panda** [hackforla/website#6920]
### Overview
Currently the Online Project Team Meeting section of Events page has Day, Start Time, End Time, Name of Project, and Name of Meeting. As some of the meetings do not happen weekly (like Onboarding), we need to mark those meetings and add a message to visit project page for more information.

### Action Items
- [x] Analyze and understand the data in `_data/external/vrms_data.json`
- [x] Update Team Meeting data on the Events page to add asterisk to the end of "Name of Meeting" if it's not weekly.
- [x] Add the following text to the end of the "Online Project Team Meetings" section.
     ```
     *This meeting is not weekly, check project link for more details.
     ```
- [x] Using Docker, check the changes on your local machine 

### Resources/Instructions
- [Event Page](https://www.hackforla.org/events/)
- [JSON Data File](https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json)
- [Js File](https://github.com/hackforla/website/blob/gh-pages/assets/js/right-col-content.js)
- [HTML File](https://github.com/hackforla/website/blob/gh-pages/_includes/events-page/right-col-content.html)
- This issue was created from #6320

**Comment by colin-macrae** [comment]
Availability: Evenings 
ETA (updated): Th, Jun 13th.

**Comment by Thinking-Panda** [comment]
@colin-macrae Thank you for working on this issue. Please move the issue to the "In progress" column on the project board.

**Comment by colin-macrae** [comment]
Hi @Thinking-Panda - What's the best way for me to find out the frequency of meetings (in order to find out which ones are not weekly).  I didn't see anything about frequency in the json data nor on the meeting pages.  Many thanks, Colin

**Comment by Thinking-Panda** [comment]
@colin-macrae The meeting frequency is mentioned under  "description" in the JSON file.

**Comment by colin-macrae** [comment]
Hi @Thinking-Panda , thank you!  Many of those "description" properties have no values, and many don't mention anything about frequency.  So, here is what I'll do, and please do let me know if I should do differently: 

- For all empty values for "description", I will do nothing 
- For all which do not explicitly say meetings are not weekly, I will do nothing 
- For all which explicitly say meetings are not weekly, I will make the requested changes (asterisk etc..)

Does that sound right?  Thanks again, Colin

**Comment by Thinking-Panda** [comment]
Hi @colin-macrae , that's right. The key "description" has a value only when the meeting is not weekly.

**Comment by colin-macrae** [comment]
Hi @Thinking-Panda - Okay, and just to be extra sure, the event in the pic below is not weekly since the description key has a value  (even though there is no mention of frequency).  I'll make the prescribed changes to all which are like this one, and no changes to those with no values.  Pls kindly confirm.  Many thanks! 

![image](https://github.com/hackforla/website/assets/122063836/59ac4dc1-5ce0-4cc9-a132-6c39948b34d7)

**Comment by Thinking-Panda** [comment]
@colin-macrae the "description" in `line 210` is not the description of the event. It is the description of the project. Scroll a little further to see the  event description with no value. Hope this helps.

**Comment by colin-macrae** [comment]
@Thinking-Panda , got it!  So many descriptions for each object 🤣.  I see that now, and thanks for your patience.  ETA is before Thursday (will update above).  Thanks again!

**Comment by colin-macrae** [comment]
Unfortunately I had to unassign myself from this issue for a couple of reasons.  

First, I have not used the technologies required to complete the issue and either A) the instructions were a bit vague or B) my inexperience with the site, this file system, and this frontend tech represented a blocker.  I tried to get help through dev office hours on Thursday but there was no one there while I waited, from 7-7:10pm.  Aside from that I'm traveling out of the country in a couple days and I wouldn't be able to revisit it after today, probably for a few weeks.  

I'll look for another issue to pick up, explore moving to a React project, and review some PRs.  Many thanks.

**Comment by colin-macrae** [comment]
@Thinking-Panda , if you want to add these to the issue action items, it could prevent a lot of double work.  I've compiled the the list of teams whose meetings are not weekly (by looking throgh all the `vrms_data.json` file), despite not making changes to the code: 

onboarding - new prosp. members 
home unite us - all 
civic tech jobs - all 
civic tech jobs - pm/org 
food oasis -  all 
la tdm calculator - stakeholder 
food oasis - uxr team 
311 data - leads 
expunge assist - all 
expunge assist  - pm/org 
civic tech jobs - leads

**Comment by terrencejihoonjung** [comment]
ETA: 6/17/24, 11:59pm PST
Availability: 7pm - 12am PST, everyday

**Comment by terrencejihoonjung** [comment]
1. Progress: I've modified the JSON file to include a "isWeekly" key with their corresponding boolean value. I've also implemented conditional rendering of the asterisk depending on whether isWeekly is false. 
2. Blockers: I'm having some issues with isWeekly showing up as "undefined" even though the JSON file is valid and contains the appropriate data. My docker is also displaying the website in the incorrect format, so I will have to go to office hours to fix that u
3. Availability: 7pm - 12am PST, everyday
4. ETA: 6/21/24, 11:59pm PST

**Comment by t-will-gillis** [comment]
Reopening this issue: The previous solution relies on direct edits to `vrms-data.json`. These edits are over-written by the daily workflow run of  "Update VRMS Data".

**Comment by t-will-gillis** [comment]
@terrencejihoonjung Please let us know if you would like to keep working on this issue- thanks!

**Comment by terrencejihoonjung** [comment]
updated ETA: 7/3/24, 11:59pm PST
updated availability: 7pm - 12am PST, weekdays
