### ISSUE TITLE
ER: Proposed edits to Pull Request template

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6929]
### Emergent Requirement - Problem
Many of the same errors appear in PRs, and some of these errors might be adverted by making minor changes to the PR template. Please see below

### Issue you discovered this emergent requirement in
- #6916 

### Date discovered 
6/2/24

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@t-will-gillis 

### What happens if this is not addressed
We will continue to have errors needing to be addressed in PR reviews.

### Resources
[pull_request_template.md](https://github.com/hackforla/website/blob/gh-pages/.github/pull_request_template.md)

### Recommended Action Items
- [x] Make a new issue
- [x] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
- To address a problem where devs do not link an issue to "Fixes: #   ":
  -  Add comment above "Fixes " line:  
  ```<!-- Important! Add the number of the issue you worked on after Fixes #  -->```
  - We could also incorporate this [workflow in the Lucky Parking project](https://github.com/hackforla/lucky-parking/blob/main/.github/workflows/compliance.yaml) that posts a message if the dev doesn't link an issue. Probably would need to be integrated with [set-pr-labels](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-pr/set-pr-labels.js)
- To address the case when devs forget to add spaces after the tics in the 'what did you do and why' sections, add single space after each tic mark so that dev is beginning with the space already
- Additionally, add a comment after the "What did you do.." and the "Why did you do it" that says:  
  ```<!-- Note: add lines if needed, and remove any unused lines -->```
- To address the case where devs fail to remove the code after "Screenshots.." , modify the notes to:  
  ```  
  <!-- Notes: 
  - If there are no visual change to the website, delete all of the script below and replace with "- No visual changes" or similar
  - If your images are too big, use the <img src="" width="" length="" />  syntax instead of ![image](link) to format the images
  - If images are not loading properly, you might need to double check the syntax or add a newline after the closing </summary> tag 
  -->  
  ```  

[Example of propsed PR Template](https://github.com/t-will-gillis/website/blob/PR-template-propr/.github/pull_request_template.md)

**Comment by ExperimentsInHonesty** [comment]
I think these will make great additions to the PR template!

**Comment by t-will-gillis** [comment]
Created issues to change PR template, as well as `CONTRIBUTING.md` to match:
- #7133 
- #7134 
- #7137 
- #7138 
- #7139 
Closing ER
