### ISSUE TITLE
Lucky Parking Project Overview and Leadership Update

### ISSUE THREAD

**Issue by gregpawin** [hackforla/website#693]
### Overview
The Lucky Parking Project Leadership was recently updated but several major changes have happened and need updating. Also, the project overview information needs to be updated.

- [ ] Project Overview info needs to be updated
- [ ] Project Leadership info needs to be updated

### Resources/Instructions
**Project Overview**
```
Project Description: Visualization of parking data to assist in understanding of the effects of parking policies on a neighborhood by neighborhood basis in the City of Los Angeles.

Open roles:
Data Analyst/Data Scientist (data cleaning)
Early UI/UX product development
Experienced Frontend Software Engineer (Mapbox experience)
Experienced Backend Software Engineer

Partner: Department of Neighborhood Empowerment 

Tools: Jupyter Notebooks, Google Colab, AWS, React-JS, Node-JS

Languages: Python, JavaScript, SQL
```
This includes all of the current team so previous info can be discarded (Title:Name \n Slack \n Git):
**Project Leadership**
``` 
Product Owner / Data Science Lead: Greg Pawin
https://app.slack.com/team/UUEQF3AJG
gregpawin

Full-Stack Developer Lead: Matthew Ginther
https://app.slack.com/team/U013GNM93U1
mg78856

Full-Stack Developer: David Kim
https://app.slack.com/team/U3MNUEQJ3
hyomiTheTech

Full-Stack Developer: Sam Guan
https://app.slack.com/team/U0173AHJ004
samreality4

```

**Comment by ExperimentsInHonesty** [comment]
@gregpawin If I might suggest a little rewrite, since the city hasn't asked us for our help in this area yet.

Visualization of parking data to assist in understanding of the effects of parking policies on a neighborhood by neighborhood basis in the City of Los Angeles.

**Comment by gregpawin** [comment]
Made suggested change. Ready to go.
