### ISSUE TITLE
Update Project Info Page to show Meeting Description

### ISSUE THREAD

**Issue by Thinking-Panda** [hackforla/website#6930]
### Overview
We need to add meeting description to the Project Info pages to keep users informed of the meeting frequency.

### Action Items
- [x] Analyze and understand the data in `_data/external/vrms_data.json`
- [x] Make changes to `project.js` to show the meeting description on the Project Info page.
- [x] Using Docker, check the website on your local machine.

### Resources/Instructions
- [Project Info Page for LA TDM Calculator](https://www.hackforla.org/projects/tdm-calculator)
- [JSON Data File](https://github.com/hackforla/website/blob/gh-pages/_data/external/vrms_data.json)
- [Js File](https://github.com/hackforla/website/blob/gh-pages/assets/js/project.js)
- Refer to the [Project Meetings Page](https://www.hackforla.org/project-meetings ) that shows all the meeting data
- Note: The data for Project Info pages should be coming from the above mentioned JSON data file and not from the VRMS API.

**Comment by lukewangm** [comment]
Availability: until EOD and tomorrow.

ETA: completed issued, awaiting review.
