### ISSUE TITLE
Add github-handle for Roland Abregorivas in heart.md

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6940]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started Page](https://www.hackforla.org/getting-started).
2. Before you claim or start working on an issue, please make sure you have read our [How to Contribute to Hack for LA Guide](https://github.com/hackforla/website/blob/7f0c132c96f71230b8935759e1f8711ccb340c0f/CONTRIBUTING.md).
   
### Overview
We need to create a single variable `github-handle` to hold the github handle for each member of the leadership team. Eventually `github-handle` will replace the `github` and `picture` variables, reducing redundancy in the project file.

### Action Items
- [x] Open the file `_projects/heart.md` in the IDE
- [x] Replace:
```
- name: Roland Abregorivas
```
with
```
- name: Roland Abregorivas
  github-handle: 
```
- [x] Do not use a tab to indent `github-handle`. YAML doesn't allow tabs; it requires spaces.
- [x] Using docker, confirm that the appearance of the project webpage is unchanged at all screen sizes. The project webpage URL can be found below under Resources.

### For Merge Team
- [x] Release the dependency for this issue in #5441. If all the dependencies have been completed, close that issue.

### Resources/Instructions
https://github.com/hackforla/website/wiki/project.md-file-template  
https://jekyllrb.com/  
For QA to validate change: https://github.com/hackforla/website/blob/gh-pages/_projects/heart.md?plain=1
Project Webpage: https://www.hackforla.org/projects/heart

- This issue is part of #5441.

**Comment by jennisung** [comment]
Hi @jennisung, thank you for taking up this issue! Hfla appreciates you :)

Do let fellow developers know about your:-
i. Availability: (When are you available to work on the issue/answer questions other programmers might have about your issue?): I'm available today Sunday, and some time at night(EST) on Monday and Tuesday.
ii. ETA: (When do you expect this issue to be completed?): Currently pushed into github, I'm waiting for someone review my changes.

You're awesome!

P.S. - You may not take up another issue until this issue gets merged (or closed). Thanks again :)

**Comment by ExperimentsInHonesty** [comment]
@jennisung I am going to move this issue to the in progress column, don't forget to do that, in the future, when you are the assignee of an issue.
