### ISSUE TITLE
Create Project Card for Civic Tech Structure

### ISSUE THREAD

**Issue by MasSamH** [hackforla/website#695]
### Overview
Provide collateral for the HackforLA website

### Action Items

- [x] See issue from Civic Tech Infrastructure Project repository with details - https://github.com/codeforamerica/brigade-playbook/issues/9
- [ ] Add a screen shot to this issue of what the card looks like locally before submitting the PR

**Comment by ExperimentsInHonesty** [comment]
@ethanh256 please add a screen shot to this issue of what the card looks like locally

**Comment by ExperimentsInHonesty** [comment]
Working with team on the other related issue: https://github.com/codeforamerica/brigade-playbook/issues/9#issuecomment-683448928

**Comment by ExperimentsInHonesty** [comment]
@ethanh256 I have updated the information at the bottom of this issue.  Can you confirm that you have everything you need now?  https://github.com/codeforamerica/brigade-playbook/issues/9

**Comment by ghost** [comment]
![new screenshot](https://user-images.githubusercontent.com/58455740/93383176-1d23a400-f818-11ea-8334-6cf8f706a755.png)
<img width="357" alt="Screen Shot 2020-09-16 at 12 28 51 PM" src="https://user-images.githubusercontent.com/58455740/93383241-33c9fb00-f818-11ea-8f8e-aaba19c9aec3.png">

@ExperimentsInHonesty @KianBadie New fixes, issue fixed by updates to pull request #729

**Comment by ExperimentsInHonesty** [comment]
@KianBadie I am sorry the slack channel we provided  for CfA should have been https://cfa.slack.com/archives/C019RCM15FE

**Comment by ExperimentsInHonesty** [comment]
@ExperimentsInHonesty will add a blank issue to the repo a github.com/hackforla/civic-tech-structure/ so that all contributors can comment and get credit for working on issue.

**Comment by MasSamH** [comment]
Team meeting times and another addition to card to follow https://github.com/codeforamerica/brigade-playbook/issues/9#issuecomment-698453537 @GlowingEmber

**Comment by ExperimentsInHonesty** [comment]
I am closing this issue.  I will open a new one for the changes to project card.  I have also opened a ticket at VRMS for the meeting time addition.
