### ISSUE TITLE
ER: Problems with Daniel Ridge workflows

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6967]
### Emergent Requirement - Problem

In the Daniel Ridge Bot repo [check-ghpages-versions](https://github.com/danielridgebot/check-ghpages-versions),  the production workflows `Check Github Pages Gem Version and Open New Issue on Change` and `Check Ruby Version and Open New Issue on Change` have not behaved as expected.  The behavior may be related to these warnings:

- <i>The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

- Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.</i>

In addition, the secret name in the workflows does not match the name of the secret in repository settings.  

### Issue you discovered this emergent requirement in
- #6266

### Date discovered 
6/6/2024

### Did you have to do something temporarily
- [ ] YES
- [ ] NO

### Who was involved
@roslynwythe @gaylem @MarcosG119 

### What happens if this is not addressed
The workflow will not work even if the issue is completed with the addition of the keepalive.  

#### Workflows
- https://github.com/danielridgebot/check-ghpages-versions/blob/main/.github/workflows/check-gh-pages-version.yml
- https://github.com/danielridgebot/check-ghpages-versions/blob/main/.github/workflows/check-ruby-version.yml

#### Blog
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

### Recommended Action Items
- [ ] Make a new issue 
- [ ] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
see Recommended Action items

**Comment by roslynwythe** [comment]
- #6979

**Comment by ExperimentsInHonesty** [comment]
@roslynwythe I am closing this ER since it seems like the issue you made resolves the issue above.
