### ISSUE TITLE
Updates to Daniel Ridge workflows

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#6979]
### Overview
As developers we need to update the deprecated `set-output` command in the Daniel Ridge workflows and update the version of Node, in order to comply with GitHub recommendations and ensure the continuing operation of the workflows.  There is also an issue with the secret that must be resolved.  

### Details
- The Daniel Ridge Bot repo [check-ghpages-versions](https://github.com/danielridgebot/check-ghpages-versions) contains the scheduled workflows  `check-gh-pages-version.yml` and `check-ruby-version.yml` which automatically check the dependencies for the Docker image, and generate issues in the ops repository (github.com/hackforla/ops) if an update is required.  
- The workflow had stopped running due to inactivity in the repository.    #6266 was created to add a "keepalive" step to prevent the workflow from stopping in the future
- However, even when the repository is active, the workflows do not behave as expected.  See the Resources/Instructions section for a screenshot of a log depicting the current behavior.  In addition, the following warnings are observed:

   - _The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands_

  - _Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/_</i>

- Based on this comment https://github.com/danielridgebot/check-ghpages-versions/pull/21#issuecomment-2110968610, the secret name referenced in the workflows is incorrect and needs to be updated.  

### Action Items
- [x] Fork and clone the repository [check-ghpages-versions](https://github.com/danielridgebot/check-ghpages-versions).  
- [x] Based on the guidelines in [GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands), update `.github/workflows/check-gh-pages-version.yml` and `.github/workflows/check-ruby-version.yml` so that the result of the step 'Check for modified files is set using Environment files instead of `set-output`
- [x] Based on the guidelines in [GitHub Actions: Transitioning from Node 16 to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/) update the code to remove dependencies on Node 16.  This will require replacing `actions/checkout@v3` with `actions/checkout@v4`
- [x] create a PAT in your repository, then a secret called test_Daniel_Ridge_PAT and modify each workflow to use that secret in place of GH_TOKEN: ${{ secrets.Daniel_Ridge_PAT }}
- [x] As described in [How To Use section of the Keep-Alive Workflow documentation](https://github.com/marketplace/actions/keepalive-workflow#how-to-use), workflow permissions must be set.  Go to repository settings, Click on Actions > General. Update the "Workflow permissions" to "Read and write permissions". Click on save. 
- [x] Test by running `.github/workflows/check-gh-pages-version.yml` and verify that the appropriate issues were created
- [x] Restore the original secret
- [x] Create a PR in https://github.com/danielridgebot/check-ghpages-versions.  Put this issue in "Questions/In Review" and apply the label "ready for dev lead".  

### Resources/Instructions
<details><summary>GHA log showing failed run</summary>

![image](https://github.com/hackforla/website/assets/5314153/514f6dac-d09e-4a77-8e14-d7d7244ff9be)

</details> 

[Check Github Pages Gem Version and Open New Issue on Change](https://github.com/danielridgebot/check-ghpages-versions/blob/main/.github/workflows/check-gh-pages-version.yml)

[Check Ruby Version and Open New Issue on Change](https://github.com/danielridgebot/check-ghpages-versions/blob/main/.github/workflows/check-ruby-version.yml)

[check-gh-pages-version.yml](https://github.com/danielridgebot/check-ghpages-versions/blob/main/.github/workflows/check-gh-pages-version.yml)

[check-ruby-version](https://github.com/danielridgebot/check-ghpages-versions/blob/main/.github/workflows/check-ruby-version.yml)

[GitHub blog post - GitHub Actions: Deprecating save-state and set-output commands](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands)

[GitHub Actions: Transitioning from Node 16 to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/)

- This issue resulted from #6967

**Comment by andyphancode** [comment]
Availability: Throughout 6/15/24 - 6/18/24
ETA: EOD 6/17/24

**Comment by andyphancode** [comment]
Pull request created at https://github.com/danielridgebot/check-ghpages-versions/pulls

**Comment by roslynwythe** [comment]
- See #https://github.com/danielridgebot/check-ghpages-versions/pull/23
