### ISSUE TITLE
HfLA website repository wants to change its license type

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#699]
### Overview
The Hack for LA organization is seeking to add the appropriate licences to all projects.  You are receiving this issue because you contributed code to our repository.  If you disagree with the gpl-2.0 license being added.  Please let us know what pull request you submitted (provide a link to the pr in the comments of this issue), and we will remove the code.

We will add the licence on September 27, 2020.

### Resources
[gpl-2.0.en.html](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html)

### Contributors
@cnk @abregorivas @leonelRos @ExperimentsInHonesty @KianBadie @thekaveman @ruben1s @ddrosario @jbubar @ye-susan @yulia-kh @drubgrubby @stu562 @charlottesauce @hannahlivnat @GlowingEmber @efrenmarin45 @parkderick @kathyfregoso @heylittlehouse @joshuazrobins @alexandrastubbs @ctsexton @vepkenez @GeorgeSu @harishlingam @sena-ji @McRawly @zempo @andrewyin1994 @breyell @bingr001 @emillipede @joelparkerhenderson @Excursionpreneur @sarL3y @matikin9 @5HAD0W-P1R4T3 @rblaz001 @RyanCahela @Slayer-39 @StephenVNelson @tmax818 @writeforall

**Comment by cnk** [comment]
The endpoint to get all the contributors who need to be notified of this change: 

https://docs.github.com/en/rest/reference/repos#list-repository-contributors
