### ISSUE TITLE
Project Board Migration: refactoring of "Pull Request Trigger" workflow

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6997]
### Dependency
- [x] #6995 
### Overview
Many of our workflows need to be refactored due to the forced migration from the Project Board (classic) to the Project Board- Beta (PBB). This issue addresses changes that we need to make in order to ensure that our "Pull Request Trigger" workflow works as it did previously.

### Action Items
- [x] In [pull-request-trigger.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/pull-request-trigger.yml) remove the entirety of the job "Move-New-PRS-To-Project-Board", that is lines 14 through 26.  (The "Default workflows" will do this now.)
- [x] In same file, delete the remaining jobs. Currently, the workflow removes PRs from the board that either are or are not merged. The PBB "Default workflows" can auto-archive PRs that match this description. Post-migration, we will decide whether these PRs need to be auto-removed as well. 
- [x] Leave "Hello World" as a placeholder.

### Post migration issues needed:
- [ ] Confirm: Need issue for action that will remove merged && unmerged + closed PRs from Project Board- in the new PBB these PRs are auto-archived but still exist in the project.
### Resources/Instructions
- [Sunset notice for Projects (classic)](https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/)
- This issue initiated by #6993

**Comment by ExperimentsInHonesty** [comment]
- [x] Need to move after pr actions to the epic

```
- [ ] Post migration issues needed after #6997 is closed
   - [ ] Confirm: Need issue for action that will remove merged && unmerged + closed PRs from Project Board- in the new PBB these PRs are auto-archived but still exist in the project.
   ```
