### ISSUE TITLE
Project Board Migration: refactoring of "Schedule Friday 0700" workflow 

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#6998]
### Dependency
- [x] https://github.com/hackforla/website/issues/6995
### Overview
Many of our workflows need to be refactored due to the forced migration from the Project Board (classic) to the Project Board- Beta (PBB). This issue addresses changes that we need to make in order to ensure that our "Schedule Friday 0700" workflow works as it did previously.

### Action Items
The "Schedule Friday 0700" workflow needs to be refactored to remove references to 'column' and refer instead to the PBB's 'status'.
- [x] In [schedule-fri-0700.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-fri-0700.yml) remove the "IN_PROGRESS_COLUMN_ID". 
- [x] Then in [add-label.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/add-update-label-weekly/add-label.js), refactor this file to function on the PBB, referencing 'status' == "In Progress (actively working)" instead of 'column'. The refactoring needs to use GraphQL.
### Post migration issues needed:
- [ ] Refactor `add-label.js` to use GraphQL and 'status'.
- [ ] **_Important Note_**: the GraphQL queries/ operations must be modularized to avoid unnecessary repetition.

### Resources/Instructions

- [Sunset notice for Projects (classic)](https://github.blog/changelog/2024-05-23-sunset-notice-projects-classic/)
- This issue initiated by #6993

**Comment by ExperimentsInHonesty** [comment]
- [x] Need to move after pr actions to the epic

```
- [ ] Post migration issues needed after #6998 is closed
   - [ ]  Refactor add-label.js to use GraphQL and 'status'.
   - [ ]  Important Note: the GraphQL queries/ operations must be modularized to avoid unnecessary repetition.
```
