### ISSUE TITLE
Resolve the incorrect background on the HfLA home page

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#700]
### Overview
The homepage coloring & layout is not correct. We need to update the page so that it reflects its original design and what exists in the Figma. 

### Action Items

Development 
- [ ] Identify the bug or error that is causing the issue with the homepage background 
- [ ] Update the background on the homepage and compare with Figma 
- [ ] Review with product 

### Resources/Instructions
[Homepage](https://www.hackforla.org/#)
[Figma Homepage](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=352%3A205)

### Images 

What the page looks like now: 
![Screen Shot 2020-08-23 at 2 59 22 PM](https://user-images.githubusercontent.com/66918724/90986490-49b60a00-e551-11ea-86da-62474a6b6c43.png)

What the page is supposed to look like: 
![Screen Shot 2020-08-23 at 2 58 01 PM](https://user-images.githubusercontent.com/66918724/90986494-55a1cc00-e551-11ea-9239-a0dc54289764.png)

**Comment by ExperimentsInHonesty** [comment]
@Excursionpreneur Please provide an update
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by alexandrastubbs** [comment]
@Excursionpreneur Please provide an update
1. Progress
2. Blocks
3. Availability
4. ETA

**Comment by alexandrastubbs** [comment]
@sena-ji any progress on this?

**Comment by sena-ji** [comment]
> @sena-ji any progress on this?

Discussed the issue with Danielle! Will get it fixed soon.

**Comment by sena-ji** [comment]
@alexandrastubbs @ExperimentsInHonesty I got the background for the press section to be white. But I am having difficulty adding a white background to the others beyond the press section.

![image](https://user-images.githubusercontent.com/42919318/96522448-3f01b380-1228-11eb-889e-d77ac266e6f0.png)

I believe the boxes are placed on top of the default background (beige-ish color). So I will go ahead and ask Kian for some help at the developers meeting tomorrow.

**Comment by sena-ji** [comment]
@alexandrastubbs @ExperimentsInHonesty @KianBadie 
Found the root of the issue with the dev team. In the _guide-pages.scss file, there is a style rule at the top:
body {
  background-color: $color-pink;
}
There is a page that relies on this rule -> On the toolkit page below the picture where it says "Development Design Project Management Professional Development", 2FA for the bottom half of the page, and building a survey for the bottom half as well. We decided to get rid of it and just add the beige color to the individual components that need it.

**Comment by alexandrastubbs** [comment]
@sena-ji looks like @KianBadie said there is additional work to be done on the PR, #790. Please provide an update when this is resolved!

**Comment by sena-ji** [comment]
@alexandrastubbs Sorry this issue is taking a while. I went through all of the pages to identify the ones that need fixing. I am almost done with the exception of one page that I need help with. Will ask the developers for their opinion at the developers meeting!
