### ISSUE TITLE
update spell check config file to ignore members' names

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#7010]
### Overview
We need to update the code spell check configuration file so that the spell checker excludes lines matching `- name: ` from checking, in order to reduce the number of false positives ("unknown word").  

### Action Items
- [x] Open the configuration file `cspell.json` in your IDE
- [x] Find an instance in which an individual's name is flagged as an "unknown word", for example the line `- name: "Saasha Gilkes"` in `_guide-pages/how-to-set-reminders-in-slack.md`
- [x] Using https://cspell.org/configuration/patterns/ as a reference, add a configuration setting so that lines matching `- name: ` are excluded from spell checking
- [x] Save the configuration file and confirm that instances such as `- name: "Saasha Gilkes"` in `_guide-pages/how-to-set-reminders-in-slack.md` are no longer flagged as "unknown word".  
- [x] Add and commit `cspell.json` and prepare a Pull Request in the usual manner.  

### Resources/Instructions
https://cspell.org/configuration/patterns/

- This issue resulted from #7004

**Comment by vanessasinam** [comment]
Availability: Mon-Fri 1pm-5pm EST
ETA: 06/27/2024

**Comment by vanessasinam** [comment]
Progress: Completed. Awaiting review.
