### ISSUE TITLE
Update Website Project Description

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#708]
### Overview
We need to update the description for the HfLA Website team on the project card and project page to reflect our newest mission and objectives. 

### Action Items
Product 
- [ ] Sign off on copy (recommended copy below)

Development 
- [ ] Update the copy reflected on site (both on project card and project page)

Current copy: 

_The hackforla.org website is our organization's way of communicating with new volunteers, stakeholders, and donors. This project is a good place to start for new volunteers looking to polish their git protocol skills (branches, separation of concerns, etc.). We are currently in a redesign phase, using CI/CD in the run up to demoing the new version at Code for America's Summit 2020 in Washington, D.C._

New copy: 

_The hackforla.org website is our organization's way of communicating with volunteers, stakeholders, and donors. This project is a good place to start for new volunteers looking to polish their git protocol skills (branches, separation of concerns, etc.). We currently have two development paths: growth (building out new pages and guides) and optimization (taking inventory of our code and design systems) to ensure we are consistently delivering value to our users while being scalable in our approach to building the site._

### Resources/Instructions
[Project page where HfLA Website Team card lives](https://www.hackforla.org/#projects)
[HfLA Project Page](https://www.hackforla.org/projects/website)

**Comment by alexandrastubbs** [comment]
@ExperimentsInHonesty please let me know if the copy above is accurate

**Comment by drubgrubby** [comment]
updated website.md file to reflect changes to project description
