### ISSUE TITLE
Update "Schedule Monthly" workflow to account for July, Dec. breaks

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#7083]
### Overview
The "Schedule Monthly" workflow[^1] currently does not account for the July break, so devs who do not contribute during the month will be listed as "inactive" by the bot and potentially removed. We want the workflow to account for the July break.

### Action Items
- [x] In `schedule-monthly.yml`[^2] , adjust the cron job to account for the July break by skipping the currently scheduled run on August 1st:  
  ```  
      - cron:  0 11 1 2-7,9-12 *
  ```  
- [x] Same file, update the comment near line 3:
  ```  
  # This action runs at 11:00 UTC/ 4:00 PDT on the first day of every month except January and August.
  ```  

- [x] In `get-contributors-data.js`[^3] lines 16 and 17, the variables `oneMonth` and `twoMonths` are set to "2" and "3" respectively on the February 1st run to account for the December break. Add the same logic for the September 1st run to account for the July break. Replace:  
  ```  
  // Set date limits: we are sorting inactive members into groups to warn after 1 month and remove after 2 months.
  // Since the website team takes off the month of December, the January 1st run is skipped (via `schedule-monthly.yml`).   
  // The February 1st run keeps the 1 month inactive warning, but changes removal to 3 months inactive (skipping December).
  let today = new Date();  
  let oneMonth = (today.getMonth() == 1) ? 2 : 1;            // If month is "February" == 1, then oneMonth = 2 months ago
  let twoMonths = (today.getMonth() == 1) ? 3 : 2;           // If month is "February" == 1, then twoMonths = 3 months ago
  ```  
  with:
  ```  
  // Set date limits: we are sorting inactive members into groups to notify after 1 month and remove after 2 months.  
  // Since the teams take off December and July, the Jan. 1st and Aug. 1st runs are skipped (via `schedule-monthly.yml`). 
  // The Feb. 1st and Sept. 1st runs account for skipped months: 'oneMonth' & 'twoMonths' = 2 & 3 months respectively
  let today = new Date();
  let oneMonth = (today.getMonth() === 1 || today.getMonth() === 8) ? 2 : 1;
  let twoMonths = (today.getMonth() === 1 || today.getMonth() === 8) ? 3 : 2;
  ```  

- [x] NOTE: Although this file is a GitHub Action, testing is not required for this issue. 

### Resources/Instructions
[^1]: ["Schedule Monthly" and "WR-Schedule Monthly"](https://github.com/hackforla/website/issues/6399#issuecomment-2118484360) wiki
[^2]: [schedule-monthly.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-monthly.yml)
[^3]: [get-contributors-data.js](https://github.com/hackforla/website/blob/gh-pages/github-actions/trigger-schedule/list-inactive-members/get-contributors-data.js)

**Comment by t-will-gillis** [comment]
Hi @mSharifHub Un-assigning you from this issue because it appears that you still need to complete two `good first issues`. If you believe this is an error, let me know which issues you have completed. Otherwise please complete two `good first issues` before working on issues with greater complexity. 

Update:
@mSharifHub FYI issues #7102 and #7103 are currently available.

**Comment by melissam640** [comment]
i. Availability: M-F
ii. ETA: EOD

**Comment by mSharifHub** [comment]
sounds good. Assigned to one of the first good issues
