### ISSUE TITLE
ER: Test event on Events page

### ISSUE THREAD

**Issue by ha-bach** [hackforla/website#7090]
### Emergent Requirement - Problem
There is a test event on the Events page that I'm not sure if we meant to display to the public.

It is the event schedule for Wednesday 10pm - 11pm.

![image](https://github.com/hackforla/website/assets/37560463/98440213-22c5-4d25-bd7b-49ab743a63e5)

### Issue you discovered this emergent requirement in
- none (I saw it while reviewing an Events page PR, but it has been in the website code before this PR)

### Date discovered 
07/07/2024

### Did you have to do something temporarily
- [ ] YES
- [x] NO

### Who was involved
@muninnhugin 

### What happens if this is not addressed
No major effect, just a test event is displayed in the public version of the website

### Recommended Action Items
- [ ] Make a new issue
- [ ] Discuss with team
- [ ] Let a Team Lead know

**Comment by ExperimentsInHonesty** [comment]
@muninnhugin This ER is already addressed in an open issue 
- https://github.com/hackforla/website/issues/6369
