### ISSUE TITLE
Update spell check `cspell.json` to ignore members' github handles

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#7099]
### Overview
We need to update the code spell check configuration file so that the spell checker excludes lines matching `github-handle: ` from checking, in order to reduce the number of false positives ("unknown word"). Currently, specific GitHub handles are included only in the `guides-team.md` project, in the future all projects will include this information.

### Action Items
- [x] Open [guides-team.md](https://github.com/hackforla/website/blob/gh-pages/_projects/guides-team.md?plain=1) in your IDE. Note that on this project, the `github-handle: ` for many of the members has been provided (eg. line 24) and cSpell is flagging the member's handle as an "Unknown word". 
- [x] Next, open the configuration file [cspell.json](https://github.com/hackforla/website/blob/gh-pages/cspell.json) in your IDE, and  
- [x] refer to the CSpell reference esp. the [Exclude/ Include Patterns](https://cspell.org/configuration/patterns/) for information on how to add to the configuration settings so that lines matching `github-handle: ` are excluded from spell checking.
- [x] (Note: see link to 7073 below. This PR made similar adjustments to `cspell.json` to exclude lines beginning with `- name:`. The solution for this issue should be similar.)
- [x] Save the configuration file and confirm that instances such as `github-handle: aymarmsba` in `guides-team.md` are no longer flagged as "Unknown word(s)".  
- [x] Add and commit `cspell.json` and prepare a Pull Request in the usual manner.  

### Resources/Instructions
- Previous issue #7073 
- This issue resulted from #7004

**Comment by handshek** [comment]
Availability: 6 AM to 11 AM weekdays
ETA: before 16-JUL-24 e.o.d
