### ISSUE TITLE
Update "Schedule Friday" workflow to account for July, Dec. breaks

### ISSUE THREAD

**Issue by t-will-gillis** [hackforla/website#7101]
### Overview
The "Schedule Friday" workflow currently runs every Friday of the year. Since the Website team takes off during July and December, devs should not get reminders to post updates on their issues. Therefore, the cron job on the "Schedule Friday" workflow needs to be adjusted so that the workflow does not run in these months. 
### Details
Note that for the first Friday of January and of August, this job might identify someone as `2 weeks inactive` even though two weeks have not elapsed.
### Action Items
- [x] In `schedule-fri-0700.yml`[^2] , adjust the cron job to account for the July and December breaks by skipping the schedule runs in these two months. Change:  
  ```  
      - cron:  '0 7 * * 5'
  ```  
  to:
  ```  
      - cron:  '0 7 * 1-6,8-11 5'
  ```  
- [x] Same file, add a new comment before `on:` on line 3:
  ```  
  # This action runs at 7:00 UTC/ 0:00 PDT (midnight) every Friday, except during July and December.
  ```  

- [x] NOTE: Although this file is a GitHub Action, testing is not required for this issue. 

### Resources/Instructions
[^1]: [schedule-fri-0700.yml](https://github.com/hackforla/website/blob/gh-pages/.github/workflows/schedule-fri-0700.yml)

**Comment by daras-cu** [comment]
**Availability:** Sat-Monday all day
**ETA:** Saturday 7/13 end of day
