### ISSUE TITLE
HFLA Logo covers text on tablet display

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/website#717]
### Overview
On iPad (and I'm assuming other tablet) displays, the HFLA logo covers up some of the page text or page heading. 

### Action Items
A decision needs to be made on how to address the issue.  The two things that come to mind are, a) making the logo smaller, or b) moving the text lower.

### Resources/Instructions
I'm guessing the fix on this will be on _header.scss and/or _header-nav.scss.

### Show & Tell
<img width="552" alt="Screen Shot 2020-09-04 at 11 36 24 AM" src="https://user-images.githubusercontent.com/68244054/92275250-a4315d80-eea3-11ea-85fc-48eeedb8f17c.png">

<img width="468" alt="Screen Shot 2020-09-04 at 11 36 36 AM" src="https://user-images.githubusercontent.com/68244054/92275266-ad222f00-eea3-11ea-84c5-75f650dc1c71.png">

**Comment by ExperimentsInHonesty** [comment]
@drubgrubby can you try making a branch that has the logo smaller for everything but desktop?

**Comment by drubgrubby** [comment]
@ExperimentsInHonesty - As you requested, I made a branch with a smaller logo for tablet.  As you can see, the logo no longer covers up the content.  I think it looks better.

My inclination is to wait until the hamburger nav gets merged (which should be very soon) before merging this.  It works on some of the same css and I think it will be cleaner to do it that way.  


<img width="557" alt="Screen Shot 2020-09-16 at 7 51 36 PM" src="https://user-images.githubusercontent.com/68244054/93414524-55e26e00-f856-11ea-82b7-13fc72895f64.png">

<img width="520" alt="Screen Shot 2020-09-16 at 7 51 23 PM" src="https://user-images.githubusercontent.com/68244054/93414513-4d8a3300-f856-11ea-9bd6-bf8d975053c0.png">

<img width="869" alt="Screen Shot 2020-09-16 at 7 54 39 PM" src="https://user-images.githubusercontent.com/68244054/93414617-81fdef00-f856-11ea-886b-5107f2886624.png">

**Comment by alexandrastubbs** [comment]
@drubgrubby You last comment on this said this: 

> My inclination is to wait until the hamburger nav gets merged (which should be very soon) before merging this. It works on some of the same css and I think it will be cleaner to do it that way.

Has that happened yet? If it has not, is there an issue we should be watching for the associated dependency?

**Comment by drubgrubby** [comment]
Not waiting on anything.  Just line it up for me and I'll do it as soon as about us page is done. Should be a quick one.
