### ISSUE TITLE
ER: Communities of Practice information updates: Ops

### ISSUE THREAD

**Issue by sudhara** [hackforla/website#7294]
### Dependency
- [x] https://github.com/hackforla/website/issues/7566

### Change Leadership Type

YES

### Leadership Type

Community Led

### Remove person(s) and info from CoP file?

YES

### If YES on remove person(s) edit the below to provide the information required. If NO, delete the template in the field below:

Name: Ernie Pelayo
Name: Nayan Bhatt
Name: Zoey Zhang

### Add person(s) and info to CoP file?

YES

### If YES on add person(s), edit the below to provide the information required. If NO, delete the template in the field below:

Name: Sudha Raamakrishnan
Title: Ops PM
GitHub Handle: sudhara
Slack Member ID: U07FJRNN9MK

Name: Alex English
Title: DevOps CoOp Practice Lead
GitHub Handle: ale210
Slack Member ID: U078B1S0XDM

Name: Ryan Sakuma
Title: CoOp Practice Lead
GitHub Handle: RSkuma
Slack Member ID: U078U294XB6

**Comment by ExperimentsInHonesty** [comment]
- This ER will be addressed with this issue https://github.com/hackforla/website/issues/7497

**Comment by ExperimentsInHonesty** [comment]
- I gave instructions to add slack links without the proper link URL.  Created a new issue to solve https://github.com/hackforla/website/issues/7566

**Comment by JessicaLucindaCheng** [comment]
This issue's Dependency has been completed and the requested changes have been made, so I'm closing this issue. Also, putting a `ready for product` label so the product can do a final QA on this ER.
