### ISSUE TITLE
ER: Update Project Profile: Civic Tech Jobs

### ISSUE THREAD

**Issue by kcoronel** [hackforla/website#7314]
### Dependency
- https://github.com/hackforla/website/issues/7515

### Project Name

Civic Tech Jobs

### Project Card URL

civic-tech-jobs.md

### Update the Title?

NO

### Update the Description?

NO

### Update the Hero Image?

NO

### Update the Image?

NO

### Update the Technologies?

YES

### Technologies (maximum 26 characters per technology name)

Technologies: React, Express, Node.js, Docker, PostgreSQL, Django, Figma

### Update the Partner(s)?

NO

### Update the Tools?

NO

### Update GitHub Link?

NO

### Update Slack Link?

NO

### Update Test Site Link?

NO

### Update Demo Site Link?

NO

### Update Site Link?

NO

### Remove person(s) and info from Leadership?

NO

### Add person(s) and info to Leadership?

NO

### Project Status

Active

**Comment by kcoronel** [comment]
@JessicaLucindaCheng checking in on this issue - thank you so much!

**Comment by ExperimentsInHonesty** [comment]
@kcoronel I was creating an issue for these changes and realized that you have the following technologies listed: 
 Microsoft SQL Server, Azure App Service

We need to discuss the usage of those applications.  Please book a time.  

I am going to split this issue into two issues and push the leadership changes through, so we can keep this open to talk about the technology changes.

**Comment by ExperimentsInHonesty** [comment]
Originally this issue had both leadership and technology changes, the leadership changes have been moved to a new issue to speed them through the process faster.
- The new issue for all the leadership changes is #7490

**Comment by kcoronel** [comment]
@ExperimentsInHonesty my apologies, I didn't confirm this with our Dev team. But they have let me know that we do not use Microsoft SQL Server -- we use PostgreSQL. And we don't use Azure - we plan to use AWS. 

I've updated the above.

**Comment by ExperimentsInHonesty** [comment]
@kcoronel confirming that we are changing 

**From:**
```
technologies: 
  - Django
  - Django REST Framework
  - React
  - Webpack
  - Babel
  - PostgreSQL
  - Docker
  - GitHub Actions
```
**To:**
```
Technologies: 
  - React
  - Express
  - Node.js
  - Docker
  - PostgreSQL
  - Django
  - Figma
```

Or in other words
Remove 
  - Django REST Framework
  - Webpack
  - Babel
  - GitHub Actions

Add 
  - Express
  - Node.js
  - Figma

**Comment by kcoronel** [comment]
@ExperimentsInHonesty confirming that the above is accurate

**Comment by ExperimentsInHonesty** [comment]
- @kcoronel, thanks.  We prioritized https://github.com/hackforla/website/issues/7515

**Comment by t-will-gillis** [comment]
- Issue #7515 is completed
