### ISSUE TITLE
#### Onboard Venkatasai Poorna Tushara Chada 2024-08-19

### ISSUE THREAD

**Issue by Tusharachada1406** [hackforla/website#7316]
#### Onboard Venkatasai Poorna Tushara Chada 2024-08-19
- [ ] Google Drive
   - [ ] Add to drive as Manager
- [ ] Roster
  - [ ] Send link
  - [ ] Team member adds themselves
  - [ ] Check for Public
- [ ] GitHub Teams
     - [ ] Add GitHub Handle to read team
        - [ ] Change membership to maintainer
     - [ ] Add to GitHub Handle to write team
        - [ ] Change membership to maintainer
     - [ ] Add to GitHub Handle to PM team
        - [ ] Change membership to maintainer
- [ ] Figma
  - [ ] invite
  - [ ] acceptance
- [ ] 1password 
     - [ ] invitation
     - [ ] acceptance
     - [ ] add to vaults
       - [ ] hackforla.org website vault
       - [ ] Zoom vault
           - [ ] send them a link to the zoom spreadsheet and confirm that they have editing rights.  If they don't, add them to the project management community of practice drive.
- [ ] Train how to 
   - [ ] login to team email account
   - [ ] setup chrome extension shortcut (chrome profile for email account)
   - [ ] use zoom spreadsheet, vault and accounts
   - [ ] calendar invite
- [ ] Gmail
   - [ ] set up forwarder to add personal email address
   - [ ] set up filter to forward all incoming mail from website@hackforla.org to personal email
- [ ] HFLA Project team
   - [ ] Add to HFLA website project page https://www.hackforla.org/projects/website  by opening a new issue
- [ ] VRMS
   - [ ] Add PM Admin Access on VRMS

**Comment by ExperimentsInHonesty** [comment]
I am closing this issue, because it should not have been opened.  We already have an #2688 onboarding issue for product
