### ISSUE TITLE
Update Looking for on various projects

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#733]
### Overview
We need to update what the projects are looking for on the website based on what they have asked for so that vistors can find the projects that need them easily.

### Action Items
- [ ] Go to the spreadsheet
- [ ] Make the changes identified in red and green to the project cards
- [ ] Move the red items to the deleted section below and updated date
- [ ] Change the green items to white and add an updated date
- [ ] Provide a screenshot (in this issue) of each project card impacted 

### Resources/Instructions
[Current project needs spreadsheet](https://docs.google.com/spreadsheets/d/1xnrwTL4kCFhecLQmXwFWVPyWjgc3DC6aQYWq8ZF_QDI/)

**Comment by alexandrastubbs** [comment]
@ruben1s can you share an update? is this all complete?

**Comment by KianBadie** [comment]
@alexandrastubbs I believe pr #781 fixes this. If it does, I will review today and if it looks good I will merge it.

**Edit**: @alexandrastubbs my apologies, I was not able to get to reviewing @ruben1s's pr today, but I will have more time tomorrow.

**Comment by ruben1s** [comment]
I have a PR for this issue @alexandrastubbs

**Comment by alexandrastubbs** [comment]
This has been completed per https://github.com/hackforla/website/pull/781
