### ISSUE TITLE
"Undefined" associated with BallotNav Meeting Time

### ISSUE THREAD

**Issue by KianBadie** [hackforla/website#735]
### Overview
There seems to be an undefined field associated with a BallotNav meeting time on Thursday (see screenshots below). It shows up both on the BallotNav's [project home page](https://www.hackforla.org/projects/ballot-nav) and on the [project meetings page](https://www.hackforla.org/project-meetings). Needs to be troubleshooted as to where the undefined value is coming fromm.

### Action Items
- [ ] Troubleshoot meeting time data to pinpoint cause of undefined data
- [ ] Touch base with VRMS team to see if there is anything they see with their BallotNav data

### Resources/Instructions
- [File](https://github.com/hackforla/website/blob/gh-pages/_data/vrms_data.json) of our meeting time data
- [VRMS project home page](https://www.hackforla.org/projects/vrms), which contains the slack contact info for VRMS leadership

**Comment by alexandrastubbs** [comment]
See comment in VRMS issue: https://github.com/hackforla/VRMS/issues/271#issuecomment-694531432

**Comment by clockwerkz** [comment]
I believe this is on our end (vrms).. just need to figure out what property the page uses to fill out that info..

**Comment by clockwerkz** [comment]
It's the "description" property in the recurringevent document. I missed adding it to the document for the Thursday recurringevent.

**Comment by KianBadie** [comment]
@clockwerkz that's good to hear, thank you! Will close this issue because the `undefined` behavior is now gone (I'm assuming it is because you fixed it).
![Screenshot from 2020-09-17 15-51-25](https://user-images.githubusercontent.com/18221058/93536430-d019fd80-f8fd-11ea-9c16-e5670c2bef0a.png)
![Screenshot from 2020-09-17 15-51-42](https://user-images.githubusercontent.com/18221058/93536435-d14b2a80-f8fd-11ea-9c0d-589154dce4f1.png)
