### ISSUE TITLE
HelloGov update

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#738]
### Overview
We need to update HelloGov status so that people are not confused when they come to the website.

### Action Items
- [x] Development
  - [x] Change status to: Completed
  - [x] Remove content in looking section

### Resources/Instructions
https://github.com/hackforla/website/blob/gh-pages/_projects/hellogov.md

**Comment by rbajaj1997** [comment]
Hi @ExperimentsInHonesty! 
Where should the status be visible?

**Comment by rbajaj1997** [comment]
Hi @ExperimentsInHonesty! Presently I see the status for HelloGov is Active. What do we need to update it to?

**Comment by sena-ji** [comment]
https://github.com/sena-ji/website/commit/ff046e3b8e643ee710a995e4d149377a49dd255c

I finished the commit and Cynthia accepted the change @ExperimentsInHonesty.
I can't find the pull request, so I hope this is sufficient enough!
