### ISSUE TITLE
Update NotToday on website

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#739]
### Overview
We need to update Not Today status so that people are not confused when they come to the website.

### Action Items
- [x] Development
  - [x] Change status to: On Hold
  - [x] Remove content in looking section

### Resources/Instructions
https://github.com/hackforla/website/blob/gh-pages/_projects/nottoday.md

**Comment by alexandrastubbs** [comment]
@sena-ji any updates on this?

**Comment by sena-ji** [comment]
@alexandrastubbs Sorry I haven't gotten any time to work on this issue since I got assigned to it. I will get it done by Friday.
