### ISSUE TITLE
Update Civic Tech Structure Card

### ISSUE THREAD

**Issue by MasSamH** [hackforla/website#746]
### Overview

We need to add another member of our team 

### Action Items

- [ ] Thad to add his details

### Resources/Instructions
https://www.hackforla.org/projects/civic-tech-structure

**Comment by thadk** [comment]
I put my details in: https://github.com/hackforla/website/issues/695#issuecomment-698454897

**Comment by thadk** [comment]
I put my details in: https://github.com/hackforla/website/issues/695#issuecomment-698454897 and specifically https://github.com/codeforamerica/brigade-playbook/issues/9#issuecomment-698453537 — thanks @GlowingEmber

**Comment by KianBadie** [comment]
@MasSamH Added @thadk to the card that links to @thadk's GitHub and the BOP CFA Slack link. Going to merge [this](https://github.com/hackforla/website/pull/755) pull request once I get a confirmation.

![Screenshot from 2020-09-28 18-01-20](https://user-images.githubusercontent.com/18221058/94500631-b2c61880-01b4-11eb-8e64-386f9687cb78.png)

**Comment by MasSamH** [comment]
Hi Bonnie, are you okay to grant permission to Kian for the pull request to
get the card live?

Thanks Sam

**Comment by KianBadie** [comment]
@MasSamH I actually have the ability to merge, and was looking for a confirmation from yourself! Thank you very much, I will now merge this.
