### ISSUE TITLE
How to Write an Issue

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#747]
### Overview
REPLACE THIS TEXT -Text here that clearly states the purpose of this issue in 2 sentences or less.

- This is where we put the user story, typically written in the format of _'We need xxx so that xxx'_

### Action Items
REPLACE THIS TEXT -If this is the beginning of the task this is most likely something to be researched and documented.

REPLACE THIS TEXT -If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

- [ ] First, we separate out any steps based on the group owning them, i.e. UI/UX, Product, Dev

- [ ] Next, we list out action steps in the order that they need to be taken 

### Resources/Instructions
REPLACE THIS TEXT -If there is a website which has documentation that helps with this issue provide the link(s) here.

- This is where we add any & all available resources. Do not shy away from adding things. If you think your audience already has it or might not need it, don't let that stop you. Add it anyway! It is very time effective to have all resources available in a single place.

**Comment by ahdithebomb** [comment]
@ExperimentsInHonesty  will upgrade @ahdithebomb, @Munasmusthafa, @pawan92, @ltung05 permissions.

**Comment by ahdithebomb** [comment]
@ahdithebomb will make a template for this.
