### ISSUE TITLE
Review and fix accessibility issues using chrome extension "WAVE" tool.

### ISSUE THREAD

**Issue by abregorivas** [hackforla/website#75]
Steps:
1. add WAVE chrome extension: https://chrome.google.com/webstore/detail/wave-evaluation-tool/jbbplnpkjmmeebjpijfedlgcdilocofh

2. visit gh-page live site https://hackforla.github.io/website/
3. click the extension and review the red flags.
4. Run the same steps for the development site (localhost). Ensure that the chrome extension has the "Allow access to file URLs" enabled.
5. Fix each issue and rerun test until no red flags appear.
6. Commit your changes and make a pull request.

**Comment by abregorivas** [comment]
This feedback comes from Drew de Rosario and each section should be reviewed.
 
Best Practices
- Links to cross-origin destinations are unsafe
	https://developers.google.com/web/tools/lighthouse/audits/noopener
	- when using target=_blank we need to add rel="noopener" to the tag
		ensures that new page runs in a separate process
- Browser errors were logged to the console
	this will fix itself when we get images running

Performance
- Eliminate render blocking resources
	- main.css and babel.js are blocking
		both are located in head.html
		need to add async to tags
		https://developers.google.com/web/tools/lighthouse/audits/blocking-resources
- Minify JavaScript
	- consider minifying babel.js to reduce size
		https://developers.google.com/speed/docs/insights/MinifyResources

Accessibility
- Color Contrast
	<h4 class project-title>  not enough color contrast
 	<a> tags - white background and red foreground
	also buttons
- Form Elements
	do not have associated labels
	https://dequeuniversity.com/rules/axe/3.2/label
		e.g. type="text" on all forms. buttons are self labeling
- Links do not have discernible names
	correcting this will help screen readers
	https://dequeuniversity.com/rules/axe/3.2/link-name
		e.g. use aria-label="to describe what the link is"

**Comment by thekaveman** [comment]
@abregorivas this seems like a duplicate/extension of #64 - can we consolidate notes/tracking of accessibility testing into either this issue or that one (and close the one that isn't needed).

**Comment by abregorivas** [comment]
Closing issue and added Drew's feedback to issue #64

**Comment by ExperimentsInHonesty** [comment]
This issue replaced issue #64 which has now been closed

**Comment by ExperimentsInHonesty** [comment]
- light the way image description needs changing
  - It currently says "no parking sign" . 
  - It should say "Veteran returned from service to civilian life"
- work for la  image description needs changing
  - It currently says "building of city la department"
  - it should say "Los Angeles City Hall building"

**Comment by ExperimentsInHonesty** [comment]
I posted a comment in slack about how the image now appears when you send someone the link
![Screen Shot 2019-05-10 at 6 02 39 PM](https://user-images.githubusercontent.com/37763229/57563053-0d579e00-734e-11e9-9bbd-61ef25d24a6a.png)

**Comment by ExperimentsInHonesty** [comment]
PR request104 by Drew fixes the project light the way and work for la websites image description.  Only thing left is updating the image in the open graph tag.  This issue is being moved to the 2.x project development board
