### ISSUE TITLE
ER: Skills Issue link to PRs that require review

### ISSUE THREAD

**Issue by roslynwythe** [hackforla/website#7528]
### Emergent Requirement - Problem
Section 9 of the Skills Issue template contains a problematic link to ` "good first issue" PRs that require review`.  The link includes a filter for 'review required'.  Currently  the `ghpages` branch is configured to require only 1 reviewer, however in fact HfLA generally requires the approval of two reviewers before merging Pull Requests. Therefore the use of the 'review required' term in the filter is too restrictive, because it excludes PRs that already have a single reviewer, but require a second reviewer.

#### 9 - GOOD FIRST ISSUE (GFI) PULL REQUEST REVIEWS
Now that you have two merged `good first issue` PRs, you are eligible to review [good first issue PRs, Review Required](https://github.com/hackforla/website/pulls?q=is%3Apr+is%3Aopen+label%3A%22good+first+issue%22+review%3Arequired) from other people who are following in the same journey path as you.

<details><summary>Setting for required reviews</summary>

![image](https://github.com/user-attachments/assets/da3d1710-6b64-4cef-aee8-779a1af3fea2)

</details> 

### Issue you discovered this emergent requirement in
Not an issue.  It was raised in Thursday office hours on 9/27/2024when a developer mentioned that the above link resulted in an empty list of PRs.  

### Date discovered 
9/27/2024

### Did you have to do something temporarily
- [ ] YES
- [ ] NO

### Who was involved
@roslynwythe @DrAcula27 

### What happens if this is not addressed
Developers will believe that there are no "good first issue" PRs available to review, potentially delaying their progress and creating confusion.  

### Recommended Action Items
- [x] Make a new issue
- [x] Discuss with team
- [ ] Let a Team Lead know

### Potential solutions [draft]
- Update the branch protection settings for `ghpages` so that 2 reviews are required.   OR
- Create an issue to update the link (filter) to remove "review required"

**Comment by roslynwythe** [comment]
@ExperimentsInHonesty please advise re: potential solutions.

**Comment by ExperimentsInHonesty** [comment]
I added 2 reviews required to the branch settings.
