### ISSUE TITLE
Add conditional so our GitHub actions only run on the main fork

### ISSUE THREAD

**Issue by cnk** [hackforla/website#756]
If we allow GitHub actions to run on all forks, then when developers go to sync their fork with the hackforla/website repo, there are often conflicting commits that really don't matter (two identical copies of vrms_data.json with different commit SHAs). The README tells everyone to disable GitHub actions on their fork - which works but requires an extra, manual step.

Change our current 3 GitHub actions to only run on the hackforla/website repository by adding an if statement per https://github.community/t/stop-github-actions-running-on-a-fork/17965/2

**Comment by ExperimentsInHonesty** [comment]
@hit1st Please provide an update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by hit1st** [comment]
@ExperimentsInHonesty my apologies.  I have been unable to work on this issue until today.

**Comment by jbubar** [comment]
We merged this yesterday. I checked it out today and it appears not to break anything, which is good! However I am not convinced that it did anything in the first place. 

Here is my fork before I pushed the upstream changes
![Screen Shot 2020-12-09 at 2 25 13 PM](https://user-images.githubusercontent.com/53061723/101696495-0bbef200-3a2b-11eb-936b-60a89fa6af9b.png)

Here is my fork after I pushed the upstream changes to origin gh-pages
![Screen Shot 2020-12-09 at 2 27 43 PM](https://user-images.githubusercontent.com/53061723/101696508-0feb0f80-3a2b-11eb-8acc-87e197939238.png)

**Comment by jbubar** [comment]
I reopened this issue just to have a discussion about it. 
If you look at [other people forks](https://github.com/hackforla/website/network/members), you can see that they either do not have gh-actions enabled or it is disabled automatically. I think this might be a github feature. 


Here is what it said on my fork when I enabled github actions. For me, this was the default. 
![Screen Shot 2020-12-09 at 2 37 27 PM](https://user-images.githubusercontent.com/53061723/101697122-12019e00-3a2c-11eb-9c96-da76f5bd6c36.png)

**Comment by hit1st** [comment]
That's interesting.  I don't even have an actions tab on my fork.

<img width="1646" alt="Screen Shot 2020-12-09 at 6 52 23 PM" src="https://user-images.githubusercontent.com/22206381/101715181-d5e03480-3a4f-11eb-8a23-c5b164f51083.png">

**Comment by hit1st** [comment]
After reviewing https://github.community/t/stop-github-actions-running-on-a-fork/17965/2 
Here is a screenshot
<img width="723" alt="Screen Shot 2020-12-09 at 10 34 51 PM" src="https://user-images.githubusercontent.com/22206381/101730865-a17c7080-3a6f-11eb-99fe-80bebcef5c1c.png">
It seems to me that adding the conditional to the actions in the hackforla/website repo is only one step.  Every forked repo that has actions enabled will have to change the conditional from:
 
  if: github.repository == 'hackforla/website'
to
  if: github.repository != 'hackforla/website'

in order for actions not to run on forked repos.

I think disabling actions in settings of forked repos accomplishes the same thing, and they are disabled by default.

**Comment by jbubar** [comment]
@cnk Can you look at this issue? In the developer meeting, we were leaning towards closing it. It appears that github actions are disabled on people forks by default.

**Comment by pawan92** [comment]
Dev team all in agreement on closing this issue. Different peoples repo behave differently.
