### ISSUE TITLE
Address Onboarding Improvements Suggestions

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#765]
### Overview
We need to address the suggestions for how to improve onboarding that are collected in the onboarding survey. 

### Action Items
- [ ] Review the suggestions and bucket based off of theme
- [ ] Identify next steps for resolving suggestions 
- [ ] Identify method to share updates or lack of updates to those who suggested

### Resources/Instructions
[Survey suggestions](https://www.hackforla.org/dashboard) - very bottom of page

**Comment by daniellex0** [comment]
Progress: Team esearched onboarding experiences, from POV of both volunteers and PM's. We synthesized research in Miro board.

Next steps: Finalize how to enact research findings and improve onboarding experience.

**Comment by daniellex0** [comment]
Progress: Presented onboarding research findings to Bonnie, discussed action items and next steps.

Next steps: Enact action items from research.

**Comment by daniellex0** [comment]
Progress: Ideated and sketched potential layouts for new Open Roles page with UX/UI team, continued working on research action items

Next steps: Finish ideating and designing Open Roles page, and enacting action items from research.

**Comment by daniellex0** [comment]
Progress: Completed user testing of Open Roles page designs, and have a [mockup](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=5326%3A26395) (with some options/questions) ready for review.

Next Steps: Get approval or edits for mockup. Verify feasibility of all features on development side. Finalize page and send to development.

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 please annotate the updates from our last meeting

**Comment by daniellex0** [comment]
Progress: Mockup for Open Roles / Volunteer Opportunities page is close to finished- progress is tracked in #1135 . New onboarding slideshow is now being utilized. UX team attended onboarding last week and will again this week to track progress and continue interviewing volunteers.

Next Steps: Finish Volunteer Opportunities page and send to development. Start work on homepage.
