### ISSUE TITLE
Remove redundant reference to current-projects-check.js in current-projects-check.html

### ISSUE THREAD

**Issue by mugdhchauhan** [hackforla/website#7779]
### Prerequisite
1. Be a member of Hack for LA. (There are no fees to join.) If you have not joined yet, please follow the steps on our [Getting Started page](https://www.hackforla.org/getting-started).
2. Please make sure you have read our **[Hack for LA Contributing Guide](https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md)** before you claim/start working on an issue.

### Overview
As developers we need to remove the reference to the deleted file `assets/js/current-projects-check.js` in order to keep the codebase clear and avoid confusion.

### Action Items

- [ ]  For the file `_includes/current-projects-check.html` remove the following lines of code (lines 21-23):

```html
<script src="/assets/js/current-projects-check.js">

</script>
```

### Resources/Instructions
- Website page with issue: https://www.hackforla.org/projects-check/
- File on GitHub: https://github.com/hackforla/website/blob/gh-pages/_includes/current-projects-check.html
- #3487
- #6200
- #6243
- #5978 
- See associated ER for this issue: #7778

**Comment by t-will-gillis** [comment]
- Please see [the notes](https://github.com/hackforla/website/issues/7778#issuecomment-2515220175) on #7778

**Comment by t-will-gillis** [comment]
This issue is superseded by #7780-  Closing as not planned
