### ISSUE TITLE
The Hack for LA website bot removed me!

### ISSUE THREAD

**Issue by jmarinit** [hackforla/website#7796]
The Hack for LA website bot removed me!
I am responding to Issue #7790 because I want to come back.
Please add me back to the 'website-write' team, I am ready to work on an issue now.

## Dev Leads
This member was previously on the 'website-write' team and is now asking to be reactivated. Please see the referenced issue.

_Originally posted by @jmarinit in https://github.com/hackforla/website/issues/7790#issuecomment-2522276491_

**Comment by t-will-gillis** [comment]
Hey @jmarinit You have been added back to the 'website-write' team and we are reopening your Skills Issue #7217
