### ISSUE TITLE
Create project groups based on Impact Area

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#795]
### Overview 

We would like to create 'Impact Areas' that help illustrate what civic initiatives our projects are benefitting. 

### Action Items 

Product
- [ ] Create the buckets/impact areas 
- [ ] Identify placement opportunities to highlight these impact areas across site

### Resources 
[SDGs to reference](https://sdg.lamayor.org/#:~:text=Los%20Angeles%20SDG%20data%20reporting%20platform&text=The%20SDGs%20build%20on%20the,among%20other%20global%20development%20challenges.)

Agreed upon impact areas:

1. Justice (name tbd)
2. Citizen engagement

**Comment by ExperimentsInHonesty** [comment]
duplicate
