### ISSUE TITLE
Complete Credits Page

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#796]
### Overview 

We need to add the remaining images to the credits page, as it is currently about half way complete. 

### Action Items 
- [x] Edit each of the existing md files to add title-link and related URL
   - [x] Commit
- [x] Make md files for each of the other images we are using across the site and put them in this issue 
   - [x] Create them in branch and commit

### Resources 

[Figma File to reference](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1074%3A0)
[Existing credits page](https://www.hackforla.org/credits)
Credits MD files: https://github.com/hackforla/website/tree/gh-pages/_credits

sample md file
```
---
title: Email
title-link: "https://thenounproject.com/search/?q=email&i=3378569"
content: icon
used-in: Getting Started
artist: Hadi Sucipto
provider: Noun Project
provider-link: 'https://thenounproject.com/'
image-url: /assets/images/getting-started/join-1.png
alt: "Image of Email"
type: icon
---
```

**Comment by ExperimentsInHonesty** [comment]
@yuikomajima will make a zip file with all the images

**Comment by jbubar** [comment]
In the developer meeting today we discovered that some of the svgs' are in the html files directly. So I opened this issue to fix it. #917

**Comment by jbubar** [comment]
@ExperimentsInHonesty @daniellex0 On the figma it lists the artist as "stories", and I just wanted to check its accuracy with you both before i merged.
![Screen Shot 2021-01-06 at 11 52 46 AM](https://user-images.githubusercontent.com/53061723/103813924-b3711500-5015-11eb-916d-f0f6b8304c7c.png)

**Comment by ItsLaszlo** [comment]
Created md files in credits for the remaining icons used across the site. However, I did not make them for 3 of the icons(Issue #917) due to them being embedded directly into the svg tag. 

Waiting for confirmation on the above to merge.

**Comment by daniellex0** [comment]
@martham0 Yeah that should be fine, stories is apparently the name of the organization that put these images on Freepik and I don't see any specific names beyond that- https://www.freepik.com/stories
