### ISSUE TITLE
Add credits to the footer

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#797]
### Overview 

We need to link to the credits page from the footer so that visitors to our site can see where we are sourcing our imagery & iconography from. 

### Dependancy
Privacy Policy

### Action Items 

Design 
- [ ] Re-design footer so that it includes credits link
- [ ] Get approval on new design 

Development 
- [ ] Update the footer to reflect new design 

### Resources 
[Credits page](https://www.hackforla.org/credits)

**Comment by alexandrastubbs** [comment]
@yuikomajima we would love if you could take a pass at the new footer design if you have a chance. Let us know if you have any questions.

**Comment by yuikomajima** [comment]
Mockups: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/?node-id=3417%3A3

**Comment by ExperimentsInHonesty** [comment]
@yuikomajima is there a reason why we are getting rid of 
![Screen Shot 2020-10-25 at 1 01 45 PM](https://user-images.githubusercontent.com/37763229/97117643-47436e00-16c2-11eb-8f4c-0f4305de7298.png)

Also, we probably need to have a privacy policy on the site.  So what about moving the credits the bottom left.  Something like this:
Privacy Policy | Credits

**Comment by ExperimentsInHonesty** [comment]
design accepted

**Comment by ExperimentsInHonesty** [comment]
Here is an example of shopify's footer https://www.shopify.com/
![Screen Shot 2020-11-07 at 2 01 38 PM](https://user-images.githubusercontent.com/37763229/98452180-c80e5b00-2101-11eb-8fed-81fff026a5f9.png)

**Comment by ExperimentsInHonesty** [comment]
moved the acceptance box to the current requirement.  Please note that it also references the privacy policy.  So the new design can be used but it the privacy policy is not yet done, publish it with that link hidden or don't add the link.

**Comment by ExperimentsInHonesty** [comment]
Replaced by #1323 1323
