### ISSUE TITLE
Create & tag for Summit Milestone and Brigade Congress Milestone

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#798]
### Overview 

In an effort to get ahead of future big events, we need to create milestones and their corresponding roadmaps that will get us to completion. 

### Action Items 

Product 
- [ ] Create milestones
- [ ] Tag appropriate, existing issues to milestones 
- [ ] Create new, necessary issues to tag to milestones 

### Resources
[Milestones](https://github.com/hackforla/website/milestones)
*Add in any dates for the events*

**Comment by ExperimentsInHonesty** [comment]
We will not be focusing on external event milestones for this project, because this project has no funding.  We will save the organizations dated milestones for community or government projects.
