### ISSUE TITLE
Update Wiki with Team Meeting Information

### ISSUE THREAD

**Issue by alexandrastubbs** [hackforla/website#799]
### Overview 

Add new language to the readme that informs about what the Hack for LA Website team does and when it meets. 

### Action Items 

- [ ] Add new language under the 'Website' portion of readme
- [x] Link to the Team Meetings card on the project board 

### Resources
[Hack for LA Team Wiki](https://github.com/hackforla/website/wiki/Joining-the-HackforLA.org-website-team)
[Read me where new content will live](https://github.com/hackforla/website)
[Team Meeting card](https://github.com/hackforla/website/projects/7#column-11381714)

**Comment by alexandrastubbs** [comment]
Proposed language to build from: 

This site is responsible for helping all members get involved and finding their place within the Hack for LA community. The Hack for LA website helps to communicate the volunteer journey and each project's mission and goals. We'd love to have you on the team. Please review the team meeting times and make sure that they work for your schedule.

**Comment by ahdithebomb** [comment]
Progress: N/A
Blockers:  Need additional clarification for Step 1. 
ETA: Will be complete before next HfLA Website PM meeting.

**Comment by ahdithebomb** [comment]
I included the team meeting times and made it the first call-out on the wiki.

**Comment by ahdithebomb** [comment]
https://github.com/hackforla/website/wiki/Joining-the-HackforLA.org-website-team

**Comment by ahdithebomb** [comment]
Progress: I updated the meeting times into markdown table form. 
Blocks: N/A
Availability:  Flexible next weekend depending on the additional changes that need to be made based on feedback. 
ETA: TBD

**Comment by ahdithebomb** [comment]
The same updates apply as of Sunday.

**Comment by ahdithebomb** [comment]
Progress: Meeting table is finalized. 
Blocks:  Communication/Coordination with the other PMs. 
Availability: Flexible next weekend depending on the additional changes that need to be made based on feedback.
ETA: End of this upcoming week.

**Comment by ahdithebomb** [comment]
Progress: No New Updates
Blocks: Communication/Coordination with the other PMs,  Approval from @ExperimentsInHonesty 
Availability: Flexible next weekend depending on the additional changes that need to be made based on feedback.
ETA: End of this upcoming week.

**Comment by ahdithebomb** [comment]
Reword the project definition. 
Update the read me with a link to the wiki with a list of bullets. 
Update the Introduction to the Project from the refreshed one sheeter.

**Comment by ahdithebomb** [comment]
@pawan92 @tarang100 @IAgbaje @ahdithebomb will go through and clean up the Introduction to the Project page by the next Team Meeting on Sunday.

**Comment by ahdithebomb** [comment]
Progress: No New Updates
Blocks: Not quite clear what needs to be updated based on a conversation with @pawan92  @tarang100 
Availability: Flexible next weekend depending on the additional changes that need to be made based on feedback.
ETA: TBD

**Comment by ahdithebomb** [comment]
Progress: Same as Sunday
Blocks: Need assistance to better understand what exactly needs to be updated from @ExperimentsInHonesty. 
Availability: Weekends. 
ETA: TBD

**Comment by ahdithebomb** [comment]
Progress: Same as last week
Blocks: Need assistance to better understand what exactly needs to be updated from @ExperimentsInHonesty.
Availability: Weekends
ETA: TBD

**Comment by tarang100** [comment]
**Update**

Took an update from Ahdi on Slack. He said that he couldn't make any progress as he did not get a chance to seek clarity from Bonnie, on the course of action for this issue

**Comment by tarang100** [comment]
**Update**
Working on reviewing the issues labelled as 'Feature : Wiki' and identifying that are duplicates or can be clubbed together for streamlining the issue resolution process. Should be able to finish this task by the next team meeting

**Comment by qiqicodes** [comment]
@tarang100 Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:
