### ISSUE TITLE
Update 100 Automations Project card

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#800]
### Overview

We need to update the 100 Automations project to reflect its current logo and so that its brand identity can be consistent across all platforms.

### Action Items
- [x] change 600x400 image out with the image listed under resources
- [x] change alt text to read: 100 Automations logo depicted as a 1 and two intermeshed gears surrounded by a open left bracket,  forward slash and closing right bracket to indicate the 100 automations are in code, followed by the word Automations.
- [x] change the hero image out with the larger image listed under resources
- [x] Add a new person to leadership
Camila Arias
Role: UI/UX Designer
Slack ID: U018S4VQK3M
GitHub handle: CamilaArias
- [x] Update Slack channel to #100automations

### Resources
600x400 card image
![100automations](https://user-images.githubusercontent.com/37763229/97095808-f592d900-1618-11eb-9794-5584a0b97b33.png)
1500x700 hero image
![100automations-hero](https://user-images.githubusercontent.com/37763229/97096801-2594a900-1626-11eb-9755-a735ff025478.png)

**Comment by ExperimentsInHonesty** [comment]
@hisergiorojas Hi Sergio, I had another change for this issue.  I see you have not yet put in a PR for this.  So here is a sentence to add to the description: 

> We will be using JAMstack and a static site generator for building this website.

Also, if you could add to the looking for:
```
   - category: Development
     skill: Static Site Architect
```

**Comment by ExperimentsInHonesty** [comment]
@hisergiorojas can you provide an update on your progress?

**Comment by hisergiorojas** [comment]
I finished with the issue I just need to make a pull request.
