### ISSUE TITLE
Onboarding video doesn't work

### ISSUE THREAD

**Issue by combinatorist** [hackforla/website#803]
This link gives a "down for maintenance" heroku page: https://github.com/hackforla/website/blob/gh-pages/getting-started.html#L53 (maybe undebate is down ... ?)

**Comment by ExperimentsInHonesty** [comment]
@combinatorist yep, it broke.  we plan to replace it, but have not done so.  Thanks for the reminder.

**Comment by combinatorist** [comment]
Cool - FWIW, I was interested in the video itself in case you have it
somewhere else I could access it or just email it or something ... :)

**Comment by ltung05** [comment]
Produce a new video for the self onboarding process.

Transcribe the original video (only what Bonnie said) and spread the recording across multiple PMs.

otter.ai

[Original Onbaroding Video](https://cc2020.enciv.org/hackforla-projects)

@ExperimentsInHonesty will send the link to the next onboarding session

**Comment by ltung05** [comment]
https://us02web.zoom.us/rec/play/EFWVbX5WWqCG42hkGzWVoef-iXnFTH1mrQW5w4JLqidNeZfezbld_n2hWhab0-fyaNiuPkhA12zQicfy.c-Z7rUyTO51h3oKs

Audio File for Onboarding Meeting 12/14/2020

I Will transcribe the conversation and combine it with my meeting notes and work with @ExperimentsInHonesty

**Comment by ahdithebomb** [comment]
@ExperimentsInHonesty  sent @ltung05 the link for the audio.

**Comment by ltung05** [comment]
**Progress:** The transcript has been uploaded, see the following link:
https://otter.ai/u/sJ3Ghmp4JeZaeZ4DG2HceFKbrZk
**Blocks:** Lack of time last week, will compile meeting notes and highlight key findings in this transcript for the new video.
**Availability:** Should be available most of next week.
**ETA:** End of the upcoming week

**Comment by ltung05** [comment]
**Progress:** The transcript has been highlighted, summarized some key takeaways and topics we can speak to with the new introduction video, see attached.
**Blocks:** Need to brainstorm with @ExperimentsInHonesty on how long the new video should be, sequences/topics/information we should cover
**Availability:** Should be available most of next week.
**ETA:** TBD

[20201215 Onboarding.docx](https://github.com/hackforla/website/files/5744352/20201215.Onboarding.docx)

**Comment by ltung05** [comment]
@ExperimentsInHonesty & @ltung05 to review this issue on Tuesday PMs meeting

**Comment by ltung05** [comment]
@ltung05 converted word doc to google doc:
https://docs.google.com/document/d/1k0HYLcEhqAWLliokM_FRfva-vRjz0uEgFRCeaNFZb1k/edit

@ExperimentsInHonesty suggested making this 5-minute video, @ltung05 will review the document once again and extract more key points from the meeting, as well as analyzing the original onboarding video to come up with topics to talk about in the new video.

**Comment by ltung05** [comment]
@ltung05 not available to join the meeting this Sunday, will update Bonnie on Tuesday about this issue.

**Comment by ltung05** [comment]
Updated with comments and ideas we can develop on for the new onboarding video, to be discussed with Bonnie for the next step:
https://docs.google.com/document/d/1k0HYLcEhqAWLliokM_FRfva-vRjz0uEgFRCeaNFZb1k/edit

**Comment by ltung05** [comment]
@ltung05 to keep working on the document prior to reviewing it with @ExperimentsInHonesty on 1/11/2021

**Comment by ltung05** [comment]
Document finished. @ExperimentsInHonesty to test this format with the onboarding session tonight and receive updated feedbacks from the meeting. @ExperimentsInHonesty will record the meeting and @ltung05 will use Otter to pick up the comments again and see if we can further improve this document.

Also discussed splitting the video into several shorter versions and/or adding a transcript for newcomers to download so they can choose to watch a video or read the transcript before joining the in-person onboarding session.

**Comment by ltung05** [comment]
New onboarding session (on 1/12/2021) audio file provided by @ExperimentsInHonesty:
https://us02web.zoom.us/rec/play/DiaB1eOFE9pn4ws5SMY_ShMlkjhFMlEQnts5Cx-CAp10AYUyC_NtxETRbzVOFMrfbIkT8nQjVzZkvSvG.WWWgFmP_gosod-RZ

@ltung05 to transcribe and extract information from it

**Comment by ltung05** [comment]
**Progress:** Was busy with interview prepping and home project last week. Working on this today after the team meeting.
**Blocks:** N/A
**Availability:** Will be busy for the upcoming week but will dedicate time for this task
**ETA:** Will be done before Wednesday PM meeting

**Comment by ltung05** [comment]
Still working on extracting the transcript, will arrange a separate meeting with Bonnie upon completion.

**Comment by ltung05** [comment]
Progress: Adding comments to the original onboarding document, highlighted in yellow
Blocks: Time!
Availability: Available besides Monday and Tuesday
ETA: I will finish adding comments today and arrange a separate meeting with @ExperimentsInHonesty to review

**Comment by ltung05** [comment]
The onboarding procedure is documented:
https://docs.google.com/document/d/1k0HYLcEhqAWLliokM_FRfva-vRjz0uEgFRCeaNFZb1k/edit

@ExperimentsInHonesty turned this over to the UI/UX team, they will help create a slide deck from here on.

**Comment by ExperimentsInHonesty** [comment]
[New slides](https://docs.google.com/presentation/d/127UC7q5JOgc5oPev4bbEdydchany-rVBkPRn4w6DMek/edit#slide=id.g10c55e2c17c_0_0) were created from this video. 
We no longer use the video
