### ISSUE TITLE
Clean up the _data/navigation/main.yml

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#819]
### Overview 
We need to remove the unused icons for our nav bar and standardize the use of quotes in the menu, to close out our updating of the menu from the old format to the new.

### Details
- [x] Remove unnecessary lines of code for each of the nav items:
   - [x] Remove the svg's from the repo if they are not used elsewhere on the site
- [x] Identify if we need the single quote for menu items to work.  If we don't need any quotes, then remove them.  It's possible that we do need the quotes on the items that link to anchors within the site.  If we do need them there, then make a recommendation if we should have them only there or on all.  
  - [x] revise file to meet approved recommendation
  - [x] revise wiki to have standards info

#### Recommendation
standardize the navigation links found on _data/navigation/main.yml to have single quotes.

Example:
```yml
- name: Events
  link: '/events'
  list_class_name:   # unnecessary
  icon: /svg/icon-hacknights.svg  # unnecessary
```
Delete the last two lines
```diff
    - name: Events
      link: '/events'
-     list_class_name:
-     icon: /svg/icon-hacknights.svg
```
>Notice that the link has single quotes for the /#about and no quotes for the /toolkit. The second part of this issue is to standardize this.
>```yml
>- name: Connect
>  link: '/#about'
>  list_class_name:
>  icon: /svg/icon-about.svg
>
>- name: Toolkit
>  link: /toolkit
>  list_class_name:
>  icon: /svg/icon-wrench.svg
>```

links to the icons:
[_includes/svg/icon-hacknights.svg](https://github.com/hackforla/website/blob/gh-pages/_includes/svg/icon-hacknights.svg)
[_includes/svg/icon-press.svg](https://github.com/hackforla/website/blob/gh-pages/_includes/svg/icon-press.svg)
[_includes/svg/icon-about.svg](https://github.com/hackforla/website/blob/gh-pages/_includes/svg/icon-about.svg)
[_includes/svg/icon-wrench.svg](https://github.com/hackforla/website/blob/gh-pages/_includes/svg/icon-wrench.svg)

**Comment by ExperimentsInHonesty** [comment]
ldkfsldkfjlkdjflskjflksdjflkdfj

**Comment by ExperimentsInHonesty** [comment]
@hisergiorojas Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by hisergiorojas** [comment]
It's is recommended to use quotes on string with a special character such as '#'

**Comment by ltung05** [comment]
@drubgrubby please provide a review of the above suggestion and directions for proceeding

**Comment by drubgrubby** [comment]
@ltung05 I believe this was the page that Sergio's recommendation came from: https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml

It says: Use quotes if your value includes special characters, (e.g. :, {, }, [, ], ,, &, *, #, ?, |, -, <, >, =, !, %, @, \).

Since some of the links on the menu are to specific places on the page, and hence use the '#' character, this would suggest we use quotes.  

Additionally, a number of "jekyll cheatsheets" and other resources I looked at such as https://devhints.io/jekyll use single quotes for links. 

Therefore: 
I recommend we standardize the navigation links found on _data/navigation/main.yml to have single quotes.

Example: `link: '/#projects'`

**Comment by pawan92** [comment]
@hisergiorojas standardize the navigation links found on _data/navigation/main.yml to have single quotes.

**Comment by jbubar** [comment]
Kenneth @kenman79 is interested in taking on this issue. He can assign himself once he has been added to the github

**Comment by pawan92** [comment]
@KenMan79 
1. Progress: None
1. Blockers: computer problems
1. Availability: good
1. ETA: 1/10/21

**Comment by ExperimentsInHonesty** [comment]
@KenMan79 is still having computer issues.  He sent me this on slack to add to the issue comments and asked me to remove him from the issue while he gets his computer sorted out.

```
- name: Events
  link: "/events"
# the link attribute should be changed to  "/hack-nights-page" after page issues have been resolved
- name: Projects
  link: "/#projects"
- name: Press
  link: "/#press"
- name: Connect
  link: "/#about"
- name: Toolkit
  link: /toolkit
# - name: Contact Us
#   link: "/#contact"
#   list_class_name: hide-mobile
#   icon:
- name: Wins
  link: /wins
```

**Comment by mcspach** [comment]
@evancchen Can you please leave an update:
Progress:
Blockers:
Availability:
ETA:

thanks

**Comment by KenMan79** [comment]
Awesome
