### ISSUE TITLE
Wins Page See More Bug

### ISSUE THREAD

**Issue by efrenmarin45** [hackforla/website#827]
**Overview**
While on the live Wins page, if an entry requires the user to use the 'see more' function, the pop up is of another win and not the one intended. See below for example:

You select an entry
![Screen Shot 2020-12-05 at 11 06 24 PM](https://user-images.githubusercontent.com/51544521/101273923-be9eff80-374e-11eb-8448-2cfdf23451d0.png)

Click See More and this comes up
![Screen Shot 2020-12-05 at 11 06 40 PM](https://user-images.githubusercontent.com/51544521/101273933-cc548500-374e-11eb-9cbf-bd40c6b6c726.png)

I tried on different browsers and the results were the same.

**Comment by jbubar** [comment]
Great find!
This is my bad! 
I will fix it right now.
