### ISSUE TITLE
Project Page mobile view needs some help.

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#830]
### Overview 
We are in need of a css wizard to fix a few problems on the mobile view of the projects section on the main page
![Screen Shot 2020-12-06 at 12 08 32 AM](https://user-images.githubusercontent.com/53061723/101275158-50f7d100-3758-11eb-8228-c5c518828127.png)

### Details
- [x] `.project-header` and `.project-pitch` need space between them.
- [x] The styling on the filter list needs to be reimagined so that the text does not overlap the label arrow(down carrot thingy)

**Comment by pawan92** [comment]
@martham0 Could you please update:
Progress:
Blockers:
Availability:
ETA:

**Comment by ItsLaszlo** [comment]
> Progress: Complete. Waiting on approval.
> Blockers: none
> Availability: N/A
> ETA: Complete

**Comment by y20s** [comment]
@jbubar will comment on pr with required changes
