### ISSUE TITLE
Create Program Areas page

### ISSUE THREAD

**Issue by munaz77** [hackforla/website#833]
### Overview

We need to create a program area page so that people can browse by topic area.

### Action Items

Product

- [x] To define the program areas required.
- [x] Write a header text.

Design

- [x] Use communities of practice as base the template replacing the team members with project links based on project display from events page location view.

Development

- [ ] Reach out to @daniellex0 (@ daniellenedivi on slack) to go over which reusable components to use and how
- [x] Reference new [template for developing a new page](https://github.com/hackforla/website/wiki/How-to-create-a-page-on-Hack-for-LA-website) on the HfLA site (via @martham0 )
- [x] Develop the program area page based on the Figma file
   - [x] Create .md file(s) for anyone to add or remove projects / edit program area descriptions over time

UX Writing

- [ ] Finish writing copy for the page

### Resources

[Figma of program area page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4452%3A21046) (final design in pink rectangle)

[Template / wiki for developing a new page on the HfLA site](https://github.com/hackforla/website/wiki/How-to-create-a-page-on-Hack-for-LA-website)

[Doc with program areas](https://docs.google.com/document/d/1YPcbq9OsE5i1KKXsYExxuKZmnAuWLItvQfukaKFrujo/edit)

**Comment by yuikomajima** [comment]
Took a pass at the desktop version here: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/?node-id=4452%3A21046

I added just the program area that have projects under them for now. Heart seems like it's a project, not a program area. There are projects that are not on the site that we'd need photos for and project pages. There were also some projects on the site that are not reflected in the doc, which I've not added to the mockups since i thought maybe those were no longer active.

**Comment by ahdithebomb** [comment]
There is a typo in the Hack For LA Card 
![Screen Shot 2020-12-20 at 12 08 22 PM](https://user-images.githubusercontent.com/44422322/102723357-1e9fb500-42bc-11eb-89b1-9c6985c43439.png)

**Comment by ahdithebomb** [comment]
**Projects on hold**
- [ ] New Schools Today
- [ ] Jobs for Hope 
- [ ] Spare 

Citizen Engagement 
- [x] 311 Data
- [x] Engage
- [x] Food Oasis
- [x] Lucky parking

**Civic Tech Infrastructure** 
- [x] 100 Automations
- [x] Civic Opportunity Project 
- [x] Civic Tech Index
- [x] Civic Tech Structure
- [x] VRMS 

**Under Development** 
- [x] Home Unite us
- [x] LA TDM Calculator
- [ ] Not Today 

**Environment** 
- [x] LA TDM Calculator
- [x] Public Tree Map 
- [x] Rail Stats LA
- [x] Climate Collabathon - Not on website

**Vote/Representation** 
- [x] Ballotnav
- [x] Undebate 
- [x] Hello Gov
- [ ] Community Survey - Not on website

**DEI** 
- [x] Write for All 

**Workforce Dev**
- [x] Hack for LA Website 
- [x] Work for LA 
- [x] Streaming- Not on website 

**Justice** 
- [x] Record Clearance Project/ Statement Maker 
- [x] Heart 
- [ ] Racial Justice - Not on Website 

**Not on the website** 
- [ ] Climate Collabathon
- [ ] Racial Justice 
- [ ] Community Survey
- [ ] Streaming

**Comment by ahdithebomb** [comment]
@yuikomajima please add the following 

- [ ] Add Program Area (Name:Justice)
   - [ ]  Record Clearance Project
   - [ ] Heart
   - [ ]  Racial Justice - Not on Website
   - [ ] Juvenile Justice:Know your rights 

- [ ] Add Community Survey Project to Vote/Representation Program Area

- [ ] Add Not Today Project to Under Development Program Area

- [ ] Please alphabetized the Program Area

**Comment by ahdithebomb** [comment]
We are going to create a new issue to evaluate the project Program Area against the USDG's to see if it is appropriate to add to this page.

**Comment by yuikomajima** [comment]
ok the above updates made here: https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4452%3A21047

**Comment by ExperimentsInHonesty** [comment]
@yuikomajima do we have to credit any of the images on the credits page?

**Comment by yuikomajima** [comment]
the photography is all from unsplash which is free stock photos so i think we are fine.

**Comment by ahdithebomb** [comment]
Design accepted, Thank You.

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 are you able to signoff on this page?  Meaning are the boxes the right size, etc.  I want to send to development. https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4452%3A21046 (edited) 

the wording can come during development

**Comment by daniellex0** [comment]
@ExperimentsInHonesty Sorry I missed this note- yes, signing off on this. It's ready to develop.
