### ISSUE TITLE
2020 Q4 Project Profile Card Updates

### ISSUE THREAD

**Issue by Olivia-Chiong** [hackforla/website#838]
### Overview
Quarterly tracking issue for Project Profile cards on website

### Details

- [x] Create new column for Project Profile cards tracking
- [x] Create template for project cards 
- [x] At next meeting, get Product Managers to select 3-5 projects to manage
- [x] Each Product Manager should create an issue for each project
   - [x] Move the Project Cards for each Project to the Product Management Repository
      - [ ] If you are unable to transfer the issue to the Project Management Repository then please ask Bonnie to add your Github to the Product Management Repository
   - [x] Assign the issue to the product manager
       - [ ] If they are not in the dropdown list, ask Bonnie to add them to the list https://github.com/hackforla/product-management/issues/41
   - [x] Contact the product manager of that project and get the information required
   - [ ] Once the Product Manager for that project provides an update, please transfer the issue back to the Website Repository
      - [ ] Move the issue to the Prioritized Backlog
      - [ ] Add the labels 'good first issue' and 'front-end'
- [ ] This issue should be closed at the end of the quarter and a new issue started for 2021 Q1

### Assignments

- [ ] Tarang #867 https://github.com/hackforla/website/issues/889
- [ ] Ahdi #879 
- [ ] Pawan #885 

### Need to Add

- [ ] 100 Automations 
- [ ] [VRMS](https://github.com/hackforla/product-management/issues/91) 
- [ ] Write for All

### Resources

See website for list of projects
Product manager will be asked for updates quarterly

**Comment by Olivia-Chiong** [comment]
@ExperimentsInHonesty Please provide list of projects that require update for Q4

**Comment by Olivia-Chiong** [comment]
@ExperimentsInHonesty I've updated the template with title template and need you to review and commit the changes please.

**Comment by ExperimentsInHonesty** [comment]
This is what remains
https://github.com/hackforla/product-management/issues?q=is%3Aopen+is%3Aissue+label%3A%22feature%3A+project+profile+card%22
As of 2/24
![Screen Shot 2021-02-24 at 2 54 36 PM](https://user-images.githubusercontent.com/37763229/109076932-3fb3c600-76b0-11eb-8a55-78eeae57eccd.png)

Write for all  - the project must be reowned by the org
VRMS - Bonnie needs to meet with Adam and add another product manager to the team
Ballot Nav - waiting for it to be done - stuck in the website teams queue
TDM - Waiting for stakeholder signoff

**Comment by ExperimentsInHonesty** [comment]
**Status update 3/1/21**

Write for All - sent Joel at text today.

TDM - Waiting for resolution of #1144 and then signoff by TDM PM on https://github.com/hackforla/product-management/issues/37

VRMS - Bonnie to meet with Adam 3/3/21 at 4:30 - need to another product manager to the team 3/3/21

BallotNav - stuck in the website team's queue https://github.com/hackforla/website/issues/1021

**Comment by VJ1285** [comment]
@ExperimentsInHonesty - everything looks for the TDM calculator. I will also close issue #1144.

**Comment by shaswa** [comment]
TDM:  #1119 
VRMS: Bonnie added a new PM
BallotNav: Still in priortized backlog
Write for all: Bonnie still needs to meet with Joel
