### ISSUE TITLE
Create a complete list of HfLA partners

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/website#844]
### Overview
The about-us page has a "Partners" section where images/logos for HfLA's partners are displayed.  In order to insure that proper attribution is given, we need a complete and accurate list of HfLA partners.

### Action Items
- [x] Compile a list of all partners from the Hack for LA website
- [ ] Inquire of all HfLA projects who their partners are.
- [x] Make a list, preferably one that includes logos and URLs of their websites
- [x] Put that list somewhere that website team designers and developers can access
- [x] Tell them where you put it. 
- [x] Once this list is signed off on, release dependency on #863, moving it to the topish of the prioritized backlog

### Resources
https://www.hackforla.org/about-us 
(This page may be renamed to about, so the link will be: https://www.hackforla.org/about )

**Comment by tarang100** [comment]
**Update**

1. The partners mentioned below have been sourced from each Project's Profile Card on the HfLA Website
2. The logos have been sourced from the official website (hyperlinked in the name) of each partner
3. For the partners that do not have logos provided next to them, the logo for that partner(s) has already been provided in the projects mentioned above or the logos could not be sourced

**List of Projects and their Partners** 

- 100 Automations - No partner listed
- 311 Data - [EmpowerLA](https://empowerla.org/)
![image](https://user-images.githubusercontent.com/75314672/107114404-89687800-688b-11eb-8101-9e55724cff78.png)

- BallotNav - [Code for America](https://www.codeforamerica.org/), Other Brigades
![image](https://user-images.githubusercontent.com/75314672/107115206-fa5e5e80-6890-11eb-87ee-eb2893b4783c.png)

- Civic Opportunity - Partner undisclosed
- Civic Tech Index - [Code for America](https://www.codeforamerica.org/), [Yale OpenLab](https://openlab.yale.edu/), and many more
![image](https://user-images.githubusercontent.com/75314672/107115429-b409ff00-6892-11eb-9b6a-04b769da874b.png)

- Civic Tech Structure - [Code for America](https://www.codeforamerica.org/) and its Brigades
- Engage - [City of Santa Monica](https://www.santamonica.gov/)
![image](https://user-images.githubusercontent.com/75314672/107115583-ad2fbc00-6893-11eb-9b5e-5d6de02f6e1d.png)

- Food Oasis - [Foodcycle LA](https://www.foodcyclela.org/), [Food Forward](https://foodforward.org/), [LA Food Policy Council, 
 Food Waste Prevention and Rescue Working Group](https://www.goodfoodla.org/food-waste), [Los Angeles Regional Food Bank](https://www.lafoodbank.org/)
![image](https://user-images.githubusercontent.com/75314672/107873998-8baa8200-6edc-11eb-80f5-76e91d8fb876.png)
![image](https://user-images.githubusercontent.com/75314672/107874121-5488a080-6edd-11eb-96e4-6aa1c2cce29f.png)
![image](https://user-images.githubusercontent.com/75314672/107874106-3c188600-6edd-11eb-9d8a-e20c75496592.png)
![image](https://user-images.githubusercontent.com/75314672/107874142-800b8b00-6edd-11eb-925c-425e0b8cee61.png)

- HfLA Website - No partner listed
- Home Unite Us - [Safe Place for Youth (SPY)](https://www.safeplaceforyouth.org/), [Point Source Youth (PSY)](https://www.pointsourceyouth.org/)
![image](https://user-images.githubusercontent.com/75314672/107115627-fda71980-6893-11eb-980c-80aaaad7a4c4.png)
![image](https://user-images.githubusercontent.com/75314672/107875518-789caf80-6ee6-11eb-8030-f5fee26aba38.png)

- LA TDM Calculator - [LA Department of Transportation](https://ladot.lacity.org/), [Los Angeles City Planning](https://planning.lacity.org/)
![image](https://user-images.githubusercontent.com/75314672/107117330-b161d680-689f-11eb-9f4f-af6fbe1f16c8.png)
![image](https://user-images.githubusercontent.com/75314672/107875615-02e51380-6ee7-11eb-928d-7d21c627828b.png)

- Lucky Parking - [Department of Neighborhood Empowerment](https://empowerla.org/)
![image](https://user-images.githubusercontent.com/75314672/107114404-89687800-688b-11eb-8101-9e55724cff78.png)

- Public Tree Map - [City of Santa Monica](https://www.santamonica.gov/)
- Record Clearance - [NDICA](https://www.thendica.org/)
![image](https://user-images.githubusercontent.com/75314672/107116074-01886b00-6897-11eb-814a-8be406549651.png)

- Undebate - [EnCiv.org](https://www.enciv.org/), [Ballotpedia.org](https://ballotpedia.org/Main_Page)
![image](https://user-images.githubusercontent.com/75314672/107116876-406cef80-689c-11eb-8d25-4bdf76ce74ce.png)
![image](https://user-images.githubusercontent.com/75314672/107116837-0ef42400-689c-11eb-8d70-3806ba01570e.png)

- VRMS - No partner listed
- Write for All - Seeking partner
- Youth Justice Nav - [UCLA School of Law](https://law.ucla.edu/), [Golden Gate University School of Law](https://law.ggu.edu/)
![image](https://user-images.githubusercontent.com/75314672/107116963-f0daf380-689c-11eb-8a98-dd4823905e66.png)
![image](https://user-images.githubusercontent.com/75314672/107875698-6c652200-6ee7-11eb-9942-eb4abb110623.png)

- Heart - [Los Angeles City Attorney's Office](https://www.lacityattorney.org/), [Los Angeles County District Attorney's Office](https://da.lacounty.gov/)
![image](https://user-images.githubusercontent.com/75314672/107875980-3163ee00-6ee9-11eb-89bc-6dc2ff64d632.png)
![image](https://user-images.githubusercontent.com/75314672/107876028-6a9c5e00-6ee9-11eb-83e4-bdd622e5a037.png)

- HelloGOV - [Digital Defense Fund](https://digitaldefensefund.org/)
![image](https://user-images.githubusercontent.com/75314672/107117085-b1f96d80-689d-11eb-8c4d-86c47349f6f5.png)

- Railstats LA - [LA Metro](https://www.metro.net/)
![image](https://user-images.githubusercontent.com/75314672/107117122-04d32500-689e-11eb-952b-75ba37407389.png)

- Work for LA - [LA City Department of Personnel](https://personnel.lacity.org/)
![image](https://user-images.githubusercontent.com/75314672/107117190-888d1180-689e-11eb-8e4f-4f3b2a4afaf2.png)

- Jobs for Hope - [LA County Homeless Initiative](https://homeless.lacounty.gov/)

- New Schools Today - Seeking partner
- Not Today - Seeking partner
- Spare - [Hope of the Valley](https://www.hopeofthevalley.org/)
![image](https://user-images.githubusercontent.com/75314672/107117260-21239180-689f-11eb-967b-d512c3619dc5.png)

**Comment by jbubar** [comment]
@tarang100 Is this list fully updated? Do you have the links for each of the partners?
We want to assign this to someone, but we are unsure if all of the hyperlinks are there

**Comment by tarang100** [comment]
@jbubar I have updated the partner list based on the information available on the HfLA website, so I think that we should run it by Bonnie before shipping it out for development. Would appreciate your thoughts on this.
As for links to the partners' websites, I have hyperlinked the name of each partner with the respective website. Does that not suffice our purpose?

**Comment by ExperimentsInHonesty** [comment]
@Olivia-Chiong Food Oasis has more partners.  We need to create an issue on the PM repo to identify their partners.  Can be worked on by the person doing the one sheet.

**Comment by ExperimentsInHonesty** [comment]
Home Unite Us has Point Source Youth as a partner

**Update**
Partner information for Home Unite Us has been updated, on the website, as part of the ongoing update of the Project Profile Cards

**Comment by ExperimentsInHonesty** [comment]
LATDM has Los Angeles City Planning as a partner

**Update**
Partner information for LA TDM has been updated, on the website, as part of the ongoing update of the Project Profile Cards

**Comment by ExperimentsInHonesty** [comment]
Youth Justice Nav has two partners
1. UCLA School of Law
2. Golden Gate University School of Law

**Update - Issue created for updating the information on the website**
https://github.com/hackforla/website/issues/1047

**Comment by ExperimentsInHonesty** [comment]
Heart has two partners
1. Los Angeles City Attorney's Office
2. Los Angeles County District Attorney's office

Change what it says on their card from

> LA City Attorney’s Homeless Engagement and Response Team

to 
```
LA City & County Attorney’s Homeless Engagement and Response Team
```
**Update - Issue created for updating the information on the website**
https://github.com/hackforla/website/issues/1048

**Comment by ExperimentsInHonesty** [comment]
Work for LA
Change from 
> Department of Personnel
to
```
LA City Department of Personnel
```
**Update - Issue created for updating the information on the website**
https://github.com/hackforla/website/issues/1049

**Comment by ExperimentsInHonesty** [comment]
@tarang100 You can grab partners from this [deck for Food Oasis](https://docs.google.com/presentation/d/1pKv3Frjcadu6XYBsN55D9OmsnDDGy_gblA1hs_IWiKA/edit).  More to be provided later

**Comment by tarang100** [comment]
Thanks @ExperimentsInHonesty I have made the required updates in my original comment. [Link to comment](https://github.com/hackforla/website/issues/844#issuecomment-774461659)

I have also linked the issues created for making necessary updates to the partner information on the website, in each of the comment above. Also providing a list of issues created, for easy reference
- Youth Justice Nav - #1047 
- Heart  - #1048 
- Work for LA - #1049

**Comment by tarang100** [comment]
@jbubar we have updated the list of partners, it is more detailed now. We can have the developers start working on integrating this into the About page. Please write back with issue number.

**Comment by jbubar** [comment]
@drubgrubby Could you take this on?

**Comment by drubgrubby** [comment]
@tarang100 - The issue for making the partner images into hyperlinks is #863 . I have removed the dependencies tag and added some things to make the issue look clearer, but please take a look at the issue and make (or suggest) any changes you think necessary.  

Just to clarify: The list of partners is this issue.  Correct? This issue is what the developers should use to complete issue #863 .

**Comment by Olivia-Chiong** [comment]
Food Oasis one sheet issue is https://github.com/hackforla/product-management/issues/127

**Comment by tarang100** [comment]
@drubgrubby - Yes you are right, the list of partners given in this issue is to be used for completing issue #863 
Also #863 looks good! I have made minor edits to the issue to make it more detailed. Thanks for the help!

**Comment by tarang100** [comment]
Issue is completed
