### ISSUE TITLE
Is the blank "New Issue" template too complicated?

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/website#854]
### Overview
The new "blank issue" template is very complicated and I feel like I need separate instructions to create a new issue.  (In my opinion) we should either make the template cleaner or simpler, or we should have a no-frills version if you know how a new issue is supposed to go, and just want to make one. 

### Action Items

- [x] Create a simpler "blank issue" template
or
- [x] Create a no-frills new issue template
or
- [x] All of the above

### Resources/Instructions
https://github.com/hackforla/website/issues/new?assignees=&labels=&template=blank-issue-.md&title=

**Comment by ExperimentsInHonesty** [comment]
I reverted back to a prior template, but it still might be too complicated.  Please try it out and let me know.

**Comment by ahdithebomb** [comment]
The current template is pretty straight forward in my thoughts.

However @drubgrubby and I previously talked about possibly having an example issue write-up in the wiki and just having the template list all of the various sections.

**Comment by ahdithebomb** [comment]
Progress: None
Blocks: TBD
Availability: Depending on what's needed
ETA: TBD

**Comment by jbubar** [comment]
I am pretty happy with the 'new issue' template the way it is right now... The only part that I think might benefit from being simplified is:

> ### Action Items
> REPLACE THIS TEXT -If this is the beginning of the task this is most likely something to be researched and documented.
> 
> REPLACE THIS TEXT -If the issue has already been researched, and the course of action is clear, this will describe the steps.  However, if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task.

maybe just 
> REPLACE THIS TEXT - List the research that needs to be done, or the steps to be completed if the actions are clear.  _Note: if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task_.

sorry, it took me so long to share my thoughts on this.

**Comment by ExperimentsInHonesty** [comment]
@jbubar thanks. @drubgrubby can you take a look at what josh has suggested?

**Comment by drubgrubby** [comment]
@ExperimentsInHonesty - I think @jbubar 's changes are great!  It took me a second to process "if the actions are clear", so I'd probably make a small change: 

REPLACE THIS TEXT - List the research that needs to be done, or the steps to be completed if the actions to be taken are clear. 
_Note: if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task._

**Comment by jbubar** [comment]
@drubgrubby @ExperimentsInHonesty That is great! Maybe we take that part out and just have it be 

REPLACE THIS TEXT - List the research that needs to be done, or the steps to be completed.
_Note: if the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task._

**Comment by Oluwafemi-Jegede** [comment]
@tarang100 to make the changes by working with @drubgrubby

**Comment by tarang100** [comment]
**Update**

I have pinged David and Josh to understand what the proposed changes are. Will discuss, make the changes, and update the issue for the next team meeting.

**Comment by drubgrubby** [comment]
This is my proposal for the text of the "New Issue" template.  @jbubar @tarang100 let me know your thoughts. 

---

### Overview
REPLACE THIS TEXT - Clearly state the purpose of this issue in 2 sentences or less.

### Action Items
REPLACE THIS TEXT - List the research to be done, or the steps to be completed.
_Note: If the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task._

### Resources/Instructions
REPLACE THIS TEXT - Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc.

**Comment by jbubar** [comment]
@drubgrubby I like that!

**Comment by tarang100** [comment]
I am on board with this. Looks good @drubgrubby !
Should I make the changes and make a pull request for review?

**Comment by ExperimentsInHonesty** [comment]
Looks good!
