### ISSUE TITLE
About Us -> Make the Metrics card resizing more graceful

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/website#862]
### Overview
The Metrics card in the Metrics section of the about-us page degrades poorly in tablet view.  

In tablet view the cards look different: 
![Screen Shot 2020-12-10 at 1 11 15 PM](https://user-images.githubusercontent.com/68244054/101830362-40917e80-3ae9-11eb-8a53-c4fb120079d4.png)

In full screen the cards look the same: 
![Screen Shot 2020-12-10 at 1 11 30 PM](https://user-images.githubusercontent.com/68244054/101830393-49825000-3ae9-11eb-9735-939fd8ae96cb.png)

### Action Items
Help it handle resizing more robustly

### Resources/Instructions
https://www.hackforla.org/about-us

**Comment by akibrhast** [comment]
@drubgrubby Could you please add the Figma screenshots of the expected looks at different sizes?

**Comment by drubgrubby** [comment]
@akibrhast - Sorry, I didn't get to this yesterday. 

https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692

That's the link to the about-us page design on figma.  The final design is in the green box.  If you have any questions about figma let me know.  You can also ask Danielle ( @daniellex0 ) , who has probably forgotten more about figma than I'll ever know.

**Comment by pawan92** [comment]
@danyc23 Can you please add the labels for status?
Please refer to https://github.com/hackforla/website/wiki/Instructions-for-adding-Status-Labels-to-issues for further understanding on how to add labels

**Comment by danyc23** [comment]
- Tablet view
![Screen Shot 2021-02-21 at 11 27 53 AM](https://user-images.githubusercontent.com/42159475/108636168-71baf300-7438-11eb-9747-5fa1bde3af9b.png)

- Fullscreen
![Screen Shot 2021-02-21 at 11 36 39 AM](https://user-images.githubusercontent.com/42159475/108636283-29500500-7439-11eb-9b4b-2f29478682ef.png)
