### ISSUE TITLE
About us -> Make partner images into hyperlinks

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/website#863]
### Overview
We need to ensure that the Partners' images on the HfLA About Us webpage are hyperlinked to each partner's respective website 

### Action Items
- [x] Refer #844 to find the latest list of partners for all HfLA Projects
- [x] Ensure that the partner images on the about-us webpage are complete. (That it contains the images for all of our partners)
- [x] Make the partner images into hyperlinks

### Resources/Instructions
[HackforLA About-Us Webpage](https://www.hackforla.org/about-us)

The authoritative list of partners is in this issue: https://github.com/hackforla/website/issues/844

### Dependencies
We need to get a comprehensive list of partners.  An issue has already been created for the same: #844

**Comment by drubgrubby** [comment]
@ExperimentsInHonesty -> We need to get the correct hyperlink for each of the partners so we can make their images into hyperlinks on the about us page.  Who should this get assigned to? (By "who" i mean, project manager? Designer? Developer? )

**Comment by drubgrubby** [comment]
The authoritative list of partners can be found on #844

**Comment by drubgrubby** [comment]
@kevinreber - I see that you self assigned this issue.  The issue had dependencies at the time; we were waiting to get complete information about the partners.  That has now been completed.  I'm not sure where you are with your work on this issue, but be sure to go back and check the list of partners to make sure you have everything you need.  Let me know if you have any questions.

**Comment by kevinreber** [comment]
Got it, thanks for the update @drubgrubby! Should have it done by next meeting.

**Comment by kevinreber** [comment]
### Progress
- All anchor elements/links are working

### Blockers
- Should logos be saved as ".png" files or ".svg"?
- Some logos are bigger than others, is there a styling class we should add to each logo? 
![image](https://user-images.githubusercontent.com/42260999/108633838-585f7a00-742b-11eb-82e1-cb120128cb00.png)
- We already have some "older" logos for some of the partners listed in #844, should I overwrite the "older" logo files and replace them with the updated logos in #844? 

1. Ballot Pedia
![image](https://user-images.githubusercontent.com/42260999/108633862-85139180-742b-11eb-9197-1cd4d65704d4.png)

![image](https://user-images.githubusercontent.com/42260999/108633854-7927cf80-742b-11eb-86b0-fa046d98723d.png)

2. LA City Attorney
![image](https://user-images.githubusercontent.com/42260999/108633889-a8d6d780-742b-11eb-9d93-36de006fa8e3.png)
![image](https://user-images.githubusercontent.com/42260999/108633898-b2603f80-742b-11eb-93c9-7d64971d180c.png)

3. Hope of the Valley
![image](https://user-images.githubusercontent.com/42260999/108634004-4af6bf80-742c-11eb-817d-45e4f7b1166a.png)

![image](https://user-images.githubusercontent.com/42260999/108633998-44684800-742c-11eb-8127-22b46582a98c.png)

### ETA
- By next meeting

**Comment by ExperimentsInHonesty** [comment]
@kevinreber Here is update from our meeting
Use SVG if they have it
Use PNG if not SVG exists
Logos will be width bound
Use class name Component-name—page-name (danielle will revise this guidance after you talk)

Q: We already have some "older" logos for some of the partners listed in #844, should I overwrite the "older" logo files and replace them with the updated logos in #844?
A: Yes

[SVG grabber](https://chrome.google.com/webstore/detail/svg-grabber-get-all-the-s/ndakggdliegnegeclmfgodmgemdokdmg?hl=en)
