### ISSUE TITLE
Update Project Profile: LA TDM Calculator, New Schools Today, Lucky Parking

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#885]
### Overview
As a product manager, I need to make sure that all the projects that are listed on the HfLA website are up to date so that my customers(visitors) can get an accurate picture of each of the projects. 

### Action Items 
- [ ] Get updates from the following 3 projects   
    - [x] LA TDM Calculator  https://github.com/hackforla/product-management/issues/37
    - [x] Lucky Parking  https://github.com/hackforla/product-management/issues/43   
    - [x] New Schools Today  https://github.com/hackforla/product-management/issues/44
 

### Action Items per project 
Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
- [ ] title
- [ ] description
- [ ] image
- [ ] leadership
   - [ ] Name 
   - [ ] Role 
   - [ ] Github Handle
   - [ ] Slack Member ID
- [ ] links
  - [ ] Github
  - [ ] Slack
  - [ ] Test Site
  - [ ] Demo Site
  - [ ] Site
- [ ] looking
- [ ] technologies
- [ ] location
- [ ] partner
- [ ] tools
- [ ] status

**Comment by pawan92** [comment]
Update:
LA TDM Calculator: Kevin has updated with information to be updated regarding the project
Lucky Parking: Done
New Schools Today: Project status needs to be changed to "On Hold" Created a ticket for this: https://github.com/hackforla/website/issues/955

**Comment by pawan92** [comment]
Update:
LA TDM Calculator: Reached out to Kevin regarding updating members on page accurately. Waiting for reply.
Lucky Parking: Done
New Schools Today: Project status needs to be changed to "On Hold" Created a ticket for this: https://github.com/hackforla/website/issues/955
