### ISSUE TITLE
Update Project Profile: Public Tree Map, Record Clearance Project, Undebate

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#889]
### Overview
As a product manager, I need to make sure that all the projects that are listed on the HfLA website are up to date so that my customers(visitors) can get an accurate picture of each of the projects. 

### Action Items 
- [ ] Get updates from the following 3 projects   
    - [x] Public Tree Map https://github.com/hackforla/product-managment/issues/46 @ExperimentsInHonesty has reached out.
    - [x] Record Clearance Project https://github.com/hackforla/website/issues/949
    - [x] Undebate  https://github.com/hackforla/website/issues/954

#### Action Items per Project 
- [ ] Create an issue using [Project Profile Card review and update Issue Template](https://github.com/hackforla/website/issues/new?assignees=&labels=Role%3A+Product+Management%2C+Feature+-+Project+Info+and+Page&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D)
- [ ] Initial Reach out to Project  
    - [ ] Go to each individual project page on the HfLA website to locate the name/slack handle of the respective product manager 
     - [ ] Reach out to the Product Manager via slack in their project channel to notify them that their project card needs to be updated

![Screen Shot 2020-12-22 at 1 47 46 PM](https://user-images.githubusercontent.com/44422322/102936084-547b9f80-445c-11eb-8c29-4ec5387e4738.png)

  - [ ] Follow up until we can get the necessary updates 
     - [ ] Check in again on the channel after 2 days (" Is __________ still the project PM?" 
     - [ ] Attend their next team meeting

### Resources/Instructions
- [Project Profile Card review and update Issue Template](https://github.com/hackforla/website/issues/new?assignees=&labels=Role%3A+Product+Management%2C+Feature+-+Project+Info+and+Page&template=project-profile-card-review-and-update.md&title=Update+Project+Profile%3A+%5BProject+Name%5D)
- [Example](https://github.com/hackforla/website/issues/857)
- [Hack for LA Projects](https://www.hackforla.org/#projects)

**Comment by pawan92** [comment]
No response from Emily of public tree map. Discuss with Bonnie at next weeks Hack for LA product meeting what next steps are. 
Ongoing conversation with David Friddly from Undebate

**Comment by tarang100** [comment]
**Progress**

- **_Record Clearance Project:_** Front end development completed and issue closed by Josh Bubar. Daniel Lee (Member of Record Clearance Project) has confirmed that the front end done, is as per his preference
- **_Undebate:_** Project Card completed and moved to Prioritized Backlog for front end development
- **_Public Tree Map_**: No response from Emily on my requests. Since the meeting timings are not available on the Public Tree Map webpage, I requested for them on the Slack channel but did not get an answer. Need to discuss the way forward with Bonnie

**Comment by tarang100** [comment]
This issue completed. Please refer to https://github.com/hackforla/website/issues/964 for updates on the Project Profile for Public Tree Map
