### ISSUE TITLE
Kanban Onboarding Flowchart

### ISSUE THREAD

**Issue by tarang100** [hackforla/website#890]
### Overview
We need a flowchart to visualize how issues move on the board to get new PMs up to speed

### Action Items

- [ ] Product
   - [x] Contact Thad K for Miro Board access
   - [x] Contact Gio to learn about his availability for the Miro lesson (Mention our 4pm EST Tuesday meeting and 2pm EST Sunday meeting)
   - [ ] Coordinate with team if the meeting time is outside the team meetings (Bonnie, Leroy, Ahdi, Pawan)
   - [x] Create a draft flowchart
   - [x] Review with PM Team
   - [x] Revise as necessary
   - [x] Add to the onboarding document

### Resources/Instructions
[Kanban Guide Document](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit)
[Draft Flowchart on Miro](https://miro.com/app/board/o9J_lYkT8vo=/)

**Comment by tarang100** [comment]
- [X] Contact Thad K for Miro Board access - I contacted Thad for Miro Board Access, who was kind enough to provide the same. The link to Miro Board provided by Thad is https://miro.com/app/board/o9J_lZjN3yQ=/
- [X] Contact Gio to learn about his availability for the Miro lesson (Mention our 4pm EST Tuesday meeting and 2pm EST Sunday meeting) - I contacted Gio regarding the Miro lesson, who shared that he is discussing with a person about permissions and it is better to conduct the lesson once he has clarified the same

**Comment by tarang100** [comment]
Link to instructions for setting up Miro Board
https://github.com/hackforla/knowledgebase-content/issues/7

**Comment by ahdithebomb** [comment]
@tarang100  please provide an update on the current status.

**Comment by tarang100** [comment]
**Update**

I have created a draft flowchart for review. The same can be reviewed [here](https://miro.com/app/board/o9J_lYkT8vo=/); also providing an updated image of the flowchart below for reference. The flowchart has also been added to the Kanban Guide Document [here](https://docs.google.com/document/d/11Fe7mNdmPBP5bD_yLJ1C0_I1TmoK47AuHHrdhdDyWCs/edit?disco=AAAALJJVwrg).

![Kanban Onboarding Flowchart](https://user-images.githubusercontent.com/75314672/106801700-1511b700-6688-11eb-975a-cd67df938001.jpg)

**Comment by tarang100** [comment]
Flowchart reviewed with Bonnie in the PM Meeting on 3rd February 2021 and added to the Kanban Guide Document post Bonnie's approval
