### ISSUE TITLE
Onboarding Docker-Users Group Issue 

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#897]
### Overview
We need to provide an easier way for local user accounts to access Docker so that new members can complete the onboarding process. 

### Action Items
- [x] Write a wiki about Windows 10 Home + other editions Docker setup
- [x] Add the appropriate wording and link to the read me file in the repo 

### Resources/Instructions
https://github.com/hackforla/website/wiki/Adding-local-user-accounts-to-the-docker-users-group-on-Windows-10
https://github.com/hackforla/website/blob/gh-pages/README.md

**Comment by rh5140** [comment]
Finished as part of Issue #909
