### ISSUE TITLE
Update Developers' Wiki README 

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#902]
### Overview
- We need to update the Dev README to include details about creating a second branch, in order to prevent the same mistake most new devs have been making.

### Action Items

- [x] UX Writing
   - [x] Update the Readme with details discussed at last dev meeting

### Resources/Instructions

- [Google doc draft](https://docs.google.com/document/d/14IeaRuvQEdAO1JS6m7S9J4MkiSz__71fm55sPIXjyXE/edit#)
- [Dev README](https://github.com/hackforla/website/blob/gh-pages/README.md)

**Comment by ahdithebomb** [comment]
@jbubar will review and @dmcneary + @rh5140 are going to review it while doing their 1st/2nd PRs.
