### ISSUE TITLE
Add project vertical information to project cards: Diversity, Equity & Inclusion 

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#904]
### Overview
We need to add the vertical information to each project for Diversity, Equity & Inclusion so that when we launch the Project Verticals page it will automatically include each project.

### Action Items
Add the Field and Value
```
vertical: 'Diversity, Equity & Inclusion' 
```
to the following projects mark down files
- [ ] Write for All 

### Resources/Instructions
Project files are located at [/gh-pages/_projects](https://github.com/hackforla/website/tree/gh-pages/_projects)
Example of where to put the vertical in the [project card template](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)

**Comment by DanielekPark** [comment]
1. Added the information to the writeforall file
2. Encountered problems with git unsure whether if correct commands were used
3. Currently my time is flexible to address current issue
4. Issue can probably be resolved tomorrow
