### ISSUE TITLE
Add project vertical information to project cards: Environment

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#905]
### Dependencies
GreenEarthOS does not yet exist.  They are working on it: https://github.com/hackforla/GreenEarthOS/issues/3

### Overview
We need to add the vertical information to each project for Environment so that when we launch the Project Verticals page it will automatically include each project.

### Action Items
- [x] Add the Field and Value 
```
vertical: 'Environment' 
```
- [x] to the following projects mark down files
   - [x] LA TDM Calculator
   - [ ] ~Engage~
   - [x] Railstats LA (original name is metro-ontime)
   - [ ] #climate-collabathon
- [x] Add this dependency when the issue is done
```
### Dependencies
climate-collabathon do not yet exist.  
```
- [x] Add this is action item when putting it back in the icebox
```
- [ ] #climate-collabathon
```
### Resources/Instructions
Project files are located at [/gh-pages/_projects](https://github.com/hackforla/website/tree/gh-pages/_projects)
Railstats location : /_projects/metro-ontime.md
Example of where to put the vertical in the [project card template](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)

**Comment by mcspach** [comment]
@ahdithebomb 
I will go ahead and push a branch with the one change I was able to make.
The reason this issue is not able to be completed:
1. There is already a field and value for vertical in Engage, and this doesn't specify whether to replace or add another value. 
2. As of now, there is no file inside of _projects folder for project '#climate-collabathone' OR 'Railstats LA'.

If there is a quick answer I will jump back on and complete the task. 
Thanks.
-Matthew

**Comment by drubgrubby** [comment]
@ahdithebomb  - Engage already has 'Vertical' listed as 'Citizen Engagement'.  Can you please respond to @mcspach and let him know if that should be changed to 'Environment' or left as-is (or let him know who to contact to find out). Thanks.

**Comment by ahdithebomb** [comment]
@mcspach & @drubgrubby this was an error on my end. 
Please disregard engage and continue on.

**Comment by drubgrubby** [comment]
Putting issue in icebox until climate-collabathon and RailstatsLA are created.

**Comment by ExperimentsInHonesty** [comment]
@mcspach There is a file for railstats, it just has the projects old name (which we have to keep).  I updated the details above in the top of the issue, please read there.

**Comment by drubgrubby** [comment]
This has been returned to the icebox until climate collabathon has been created.
