### ISSUE TITLE
Add project vertical information to project cards: Justice

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#906]
### Dependency
Waiting on a Racial Justice Card to be created - Issue needs to be created

### Overview
We need to add the vertical information to each project for Justice so that when we launch the Project Verticals page it will automatically include each project.

### Action Items
Add the Field and Value
```
vertical: 'Justice' 
```
to the following projects mark down files
- [x] Record Clearance Project
- [x] Heart
- [ ] #racial-justice
- [x] #youth-justice-nav

### Resources/Instructions
Project files are located at [/gh-pages/_projects](https://github.com/hackforla/website/tree/gh-pages/_projects)
Example of where to put the vertical in the [project card template](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)

**Comment by pawan92** [comment]
@evancchen 
1. Progress: Unable to install docker
2. Blockers: Computer problem
3. Availability: After wednesday
4. ETA: 1/17/21

**Comment by evancchen** [comment]
There isn't a project markdown file for #racial-justice

**Comment by tarang100** [comment]
After the pull request is approved the issue will need to be put in the prioritized backlog with the dependency of needs racial justice card

**Comment by evancchen** [comment]
Pull request made, waiting for approval

**Comment by drubgrubby** [comment]
After we create a Racial Justice card we need to add vertical: 'Justice' to it.  Until then...
