### ISSUE TITLE
Linking Information on Docker to the ReadMe

### ISSUE THREAD

**Issue by abenipa3** [hackforla/website#909]
### Overview
We need to link Ray's Windows 10 Docker Set-up Wiki Page to the Read-Me so that the future Windows-related errors will be easier to be resolved for onboarding members.

Use the following quote in the readme:
>If you get the error message ('You are not allowed to use Docker, you must be in the "docker-users" group’), the following wiki page will resolve the issue.
> -  [Windows docker-users group error guide](https://github.com/hackforla/website/wiki/Adding-local-user-accounts-to-the-docker-users-group-on-Windows-10)

### Action Items
- [x] Attach the link [Windows docker-users group error guide](https://github.com/hackforla/website/wiki/Adding-local-user-accounts-to-the-docker-users-group-on-Windows-10) in [Step 4: Setting up Docker](https://github.com/hackforla/website/blob/gh-pages/README.md#step-4-setting-up-docker) under the list of links (More on using Docker and the concepts of containerization).

### Resources/Instructions
- [Windows docker-users group error guide](https://github.com/hackforla/website/wiki/Adding-local-user-accounts-to-the-docker-users-group-on-Windows-10) 
- [Step 4: Setting up Docker](https://github.com/hackforla/website/blob/gh-pages/README.md#step-4-setting-up-docker)

**Comment by rh5140** [comment]
I mistook the actual hackforla website repo for my fork of it and approved my pull request without asking anyone to review.  It's "#909 linked docker-users group error guide to README #914" (I didn't realize that the pull request would get its own number and put the issue number at the beginning of my message.) What should I do about this?

I don't think I should be reverting the change and making another pull request only to rerevert it.

**Comment by rh5140** [comment]
Cynthia says the pull request looks fine! Closing the issue now.
