### ISSUE TITLE
Add project vertical information to project cards: Under Development

### ISSUE THREAD

**Issue by tarang100** [hackforla/website#910]
### Overview
We need to add the vertical information to each project for Under Development so that when we launch the Project Verticals page it will automatically include each project.

### Action Items
Add the Field and Value
```
vertical: Under Development
```
to the following projects mark down files
- [x] Home Unite Us
- [x] LA TDM Calculator
- [x] Not Today

### Resources/Instructions
Project files are located at [/gh-pages/_projects](https://github.com/hackforla/website/tree/gh-pages/_projects)
Example of where to put the vertical in the [project card template](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)

**Comment by jbubar** [comment]
Fixed by #942
