### ISSUE TITLE
Markdown file vertical format update 

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#911]
### Overview
We need to update the Vertical values format to include single quotes  so that we maintain a consistent format across the various verticals

### Action Items per Markdown file 
- [x] Update where it currently says vertical:  value to vertical:   'value'  

For Example, if it says the below 
```
vertical: Diversity, Equity & Inclusion 
```
Change it to
```
vertical: 'Diversity, Equity & Inclusion' 
```

### Project Markdown files to update
- [x] 311
- [x] Engage
- [x] Food Oasis
- [x] Lucky Parking
- [x] Civic Tech Index
- [x] 100 Automations
- [x] Civic Opportunity Project
- [x]  Civic Tech Structure
- [x] VRMS

### Resources/Instructions
[Citizen Engagement Vertical Information](https://github.com/hackforla/website/issues/891)
[Civic Tech Infrastructure Vertical Information](https://github.com/hackforla/website/issues/892)

- This is where we add any & all available resources. Do not shy away from adding things. If you think your audience already has it or might not need it, don't let that stop you. Add it anyway! It is very time effective to have all resources available in a single place.

**Comment by pawan92** [comment]
@trtincher 
1. Progress: Work is completed but unsure about submitting a PR
2. Blockers: Questions about submitting a PR
3. Availability: good
4. ETA: 1/10/21
