### ISSUE TITLE
Move svg's to the assets/images

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#917]
### Overview
There are three svg's on the events page that should be moved to the assets/images/events

### Action Items

- [x] Create an events folder in ./assets/images
- [x] copy and paste the svg's into their own files, and name them appropriately
- [x] replace the svg's with img HTML tags and check the events page to make sure it looks the same. https://www.hackforla.org/events
- [x] update the credits page to include those three images

**Comment by martham0** [comment]
There is one more image on the toolkit page that needs to be moved to the assets/images/guides
https://www.hackforla.org/toolkit

**Comment by ItsLaszlo** [comment]
I have created the remaining necessary svg files in the corresponding folders (Hacknights) as well as md files in the credits folder. Only need to link them on the page now.
