### ISSUE TITLE
ReadMe Update: Issue updates & update pull requests

### ISSUE THREAD

**Issue by ItsLaszlo** [hackforla/website#921]
### Overview
The Using Git section is missing a line on writing an issue update after completing said issue. Would also be helpful to add a section about editing code on pull requests after submitting them.

**The possible line to add regarding issue updates:** 

Step 8/9
Make sure to include pictures of any visual changes made to the site and document your edits on the PR so that the reviewer can understand the changes made. 

If you have not submitted a pull request make sure to write a weekly status update on your issue before the Sunday meeting. Follow the format below and add pictures of any visual changes made to the site. 

1. Progress: "Added verticals to all the existing md files. Now need to create the reamining files and add verticals."
1. Blockers: "Changes to the md file changed the CSS. Spacing is off"
1. Availability/Unavailable: "Available on weekdays after 6pm to work on the issue except on Tuesday"
1. ETA: "Will be done by next Sunday meeting"

**The possible line to add regarding editing pull requests:** 

Post pull request

If you find an error in your code or your reviewer asks you to make a change you can edit the code directly from the pull request. Follow the steps below:

 1. Go to your pull request
 2. Go to the tab 'Files changed'
 3. Click the 3 dots next to the corresponding file you need to change 
 4. Click edit file
 5. Start editing your code

<img width="961" alt="Screen Shot 2021-01-10 at 11 00 56 AM" src="https://user-images.githubusercontent.com/69860036/104390225-0d7c4980-54f2-11eb-91a4-89c4651bd193.png">

### Action Items

- [x]  Add to read me

**Comment by ItsLaszlo** [comment]
@ExperimentsInHonesty  Hi Bonnie, can you look this over and let me know whether this would be beneficial to add to the read me. Thanks. 

@jbubar keeping you in the loop

**Comment by pawan92** [comment]
@martham0 Bonnie asked for an update to the details on how to do update on your issue
