### ISSUE TITLE
Add project to website: Youth Justice Nav

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#922]
### Overview
Add the new project Youth Justice Nav to the website

### Action Items
- [x] Make a markdown page called youthjusticenav.md from the content [here](https://github.com/hackforla/YouthJusticeNav/issues/1#issuecomment-752819904)
  - [x] make sure that is formatted to standard
- [x]  add the images from this [comment](https://github.com/hackforla/YouthJusticeNav/issues/1#issuecomment-755835284)
- [x] add a screen shot of the two pages (card on https://hackforla.org home page and page that will appear at https://hackforla.org/projects/youthjusticenav/)
- [x] review with team by posting a comment on their issue with a link to the comment on this issue with the screen shot.  

### Resources/Instructions
https://github.com/hackforla/YouthJusticeNav/issues/1

**Comment by dmcneary** [comment]
Screenshots:
- Home page card:
  ![image](https://user-images.githubusercontent.com/43227293/104113153-a0777280-52ab-11eb-9149-e0498cd1b32e.png)
- Project page:
  ![image](https://user-images.githubusercontent.com/43227293/104113170-d3ba0180-52ab-11eb-9c25-1318d4ee65ec.png)

**Comment by Rankazze** [comment]
Looking good.

**Comment by dmcneary** [comment]
1. Progress: Awaiting review
1. Blockers: none
1. Availability: open
1. ETA: 1/10/21

**Comment by dmcneary** [comment]
Ran into issue with post-merge sync with fork vs. upstream - will add a line clarifying this process in README

**Comment by ExperimentsInHonesty** [comment]
I sign off on the look.  Looking forward to seeing it on the website!
