### ISSUE TITLE
add github avatar photo

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#925]
### Overview
Add github photo for each wins card if they approve..
If they include a github link and give permission to use it, find the photo in the [_data/github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/github-data.json), and replace the default avatar img with it. 
![Screen Shot 2021-01-10 at 12 20 38 PM](https://user-images.githubusercontent.com/53061723/104134442-5ab7ba00-533e-11eb-86a6-14bd075ef507.png)

dependency: @jbubar will update the google form to include permission for github photo
### Action Items

- [x] Read the [wins.html](https://github.com/hackforla/website/blob/gh-pages/wins.html) especially the makeCard function on line 112

- [x] Look at the [_data/github-data.json](https://github.com/hackforla/website/blob/gh-pages/_data/github-data.json) file and to see how you can pull from it.
- [x] Look at line 190 of [_layouts/project.html](https://github.com/hackforla/website/blob/gh-pages/_layouts/project.html) to see how to import the github json file
- [x] add if conditionals to check for permission and presence of github
- [x] place img url from github json on the corresponding card
- [x] make sure the img url is the grey guy

### Resources/Instructions
[google form](https://docs.google.com/forms/d/1ZhyJ98nrscV3c09RT_E_sJXrHkKcUt6_a1qoChH5pQ4/edit)
[google sheet response](https://docs.google.com/spreadsheets/d/1tj6eQlVLFgmskoXouVt87POxYVwR1yWT2vOSQEPyDtg/edit#gid=1106372497)
the wins github issue is #162

**Comment by dmcneary** [comment]
Issue completed. Edited function makeCards to check if permission is granted to use Github profile picture in `wins-data.json`, then searches each project in `github-data.json` for the winner's Github URL in contributors. If found, the user's Github ID is recorded and used to retrieve the profile picture from Github. If the winner's Github URL is not found in contributors, or permission is not granted, the default avatar is displayed.

Screenshots:
![image](https://user-images.githubusercontent.com/43227293/104779729-76530400-5734-11eb-8849-4188f7ff4e79.png)
![image](https://user-images.githubusercontent.com/43227293/104779768-823ec600-5734-11eb-95bc-f9fa4a0397b0.png)

Further issues:
- `height` and `width` properties on `.wins-card-profile-img` will stretch the Github profile picture to an elliptical shape. We can mitigate this simply by deleting these properties from `_wins-page.scss` as both the default avatar and the Github profile picture are about the same size:
![image](https://user-images.githubusercontent.com/43227293/104780079-16a92880-5735-11eb-976f-887353b4aa98.png)
![image](https://user-images.githubusercontent.com/43227293/104780102-20cb2700-5735-11eb-85bd-e8b35d3b791f.png)

**Comment by dmcneary** [comment]
1/17 update for meeting:
Progress: Completed, PR awaiting review
Blockers: none
Availability: open
ETA: finished
