### ISSUE TITLE
Update Project Profile: Civic Opportunity Project 

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#927]
### Overview
As a product manager, I need to make sure that all the projects that are listed on the HfLA website are up to date so that my customers(visitors) can get an accurate picture of each of the projects.

### Project card
 https://www.hackforla.org/projects/civic-opportunity-project

### Action Items

- [x] Civic Opportunity Team Leadership
   - [x] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [x] description
      - [x] image
      - [x] leadership
      - [x] links
         - [x] Github
         - [x] Slack
         - [x] Test Site
         - [x] Demo Site
         - [x] Site
      - [x] looking
      - [x] technologies
      - [x] location
      - [x] partner
      - [x] tools
      - [x] status
- [x] Development
  - [ ] Edit Leadership to add Tan (See information in comment below)

**Comment by rfambro2** [comment]
@tarang100  - This looks fine to me. Sorry for the delay.
