### ISSUE TITLE
Add a project card to the website: open community survey

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#932]
### Overview
We need to add the open community survey project to the website so that we can onboard new people.

### Action Items
- [x] Development
   - [x] see issue for details about project card 
   - [x] Identify if any items are missing
   - [x] Create new assets locally (project.md file and images)
   - [x] take screen shots and add them to issue for stakeholder confirmation
   - [x] put in PR
  
### Resources/Instructions
 - https://github.com/hackforla/community-survey-nc-websites/issues/2
- [Full Page Screenshot Chrome ext](https://chrome.google.com/webstore/detail/gofullpage-full-page-scre/fdpohaocaechififmbbbbbknoalclacl?hl=en)

**Comment by danyc23** [comment]
There is some information missing and wasn't able to include them. The list is below:
- No vertical description in the issue.
- No demo Site link.
- Technologies.
- Languages.
- Tools.

Please, let me know if you have them available so I can make the changes before submitting the PR. @ExperimentsInHonesty

**Comment by danyc23** [comment]
![Screen Shot 2021-02-04 at 3 58 29 PM](https://user-images.githubusercontent.com/42159475/106976859-04a41f80-670e-11eb-9f4f-8109f0c46f98.png)

![Screen Shot 2021-02-04 at 4 09 19 PM](https://user-images.githubusercontent.com/42159475/106976790-e63e2400-670d-11eb-9d93-790b85798b01.png)

**Comment by mcspach** [comment]
vertical: 'Citizen Engagement'
tools: 'ArcGIS surveys, Google Docs, Zoom'

There is no demo site and there is no technologies.
Languages comes from the Github API.

**Comment by danyc23** [comment]
- tools added

![Screen Shot 2021-02-07 at 10 46 22 AM](https://user-images.githubusercontent.com/42159475/107156193-c4bd8200-6931-11eb-814d-f76fc6c6af65.png)

**Comment by ExperimentsInHonesty** [comment]
@danyc23 I saw an update on the PR with reference to this issue and new screen shots, but I didn't see you make the commit for tools and vertical yet.  Please get that added so that its ready for review.

**Comment by ExperimentsInHonesty** [comment]
Updated leadership to remove John, who has stepped down https://github.com/hackforla/community-survey-nc-websites/issues/2#issuecomment-754208495

@danyc23 I reviewed the file and added some notes.  This is the template that the project.md file should adhere to: https://github.com/hackforla/website/wiki/Template-of-a-project.md-file.  Please let us know if you see any discrepancies between files for projects and the template.
