### ISSUE TITLE
Rewording the git flow

### ISSUE THREAD

**Issue by jbubar** [hackforla/website#934]
### Overview
I thought we could use this issue to discuss how to word the git flow.

here is the part that I am thinking of editing:
>### Incorporating changes from upstream
>
>Your fork of this repository on GitHub, and your local clone of that fork, will
>get out of sync with this (upstream) repository from time to time.  (That's what has happend when you see something like "This branch is 1 commit behind hackforla:gh-pages" on the github website version of your hackforla repository.)
>
>One way to keep your fork up to date with this repository is to follow
>these instruction: [Syncing your fork to the original repository via the browser](https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser)
>
>You can also update your fork via the local clone of your fork, using
>these instructions. Assuming you have a local clone with remotes
>`upstream` (this repo) and `origin` (your GitHub fork of this repo):
>
>First, you will need to create a local branch which tracks upstream/gh-pages.  You will only need to do this once; you do not need to do this every time you want to incorporate upstream changes. 
>
>Run the following two commands: 
>
>```bash
>git fetch upstream
>git checkout -b upstream-gh-pages --track upstream/gh-pages
>```
>
>If you have already created the branch upstream-gh-pages, the following commands will incorporate upstream changes: 
>
>```bash
>git checkout upstream-gh-pages # Move to the branch you want to merge with. 
>git pull  # This updates your tracking branch to match the gh-pages branch in this repository
>git checkout gh-pages  # Move back to your gn-pages branch
>git merge upstream-gh-pages  # Merge to bring your gh-pages current. 
>```
>If you do all your work on topic branches (as suggested above) and keep gh-pages free of local modifications, this merge should apply cleanly.
>
>Then push the merge changes to your GitHub fork:  
>
>```bash
>git push
>```

It might be easier to use the following commands.
>```bash
>git checkout gh-pages
>git pull upstream gh-pages
>git push origin gh-pages
>```

@KianBadie showed me this git flow and I have been doing it since.
It appears that new contributors have been a bit confused by what is happening in the current git flow, so I thought I would bring this up

### Action Items
- [ ] come to a consensus about our git flow
- [ ] update the readme

**Comment by KianBadie** [comment]
@jbubar oooh I have been brushing up on my git and I would love to try to put the knew things I learned into practice through this :+1: I'll contribute to this soon.

**Comment by tarang100** [comment]
Most well developed projects move their technical instructions for contributing from a ReadMe to a CONTRIBUTING.md

**Comment by tarang100** [comment]
@jbubar will connect with Cynthia and invite her to a developer team meeting

**Comment by y20s** [comment]
@jbubar And @cnk decided to keep the readme to protect for if someone changes their gh-pages branch
We will be creating a new issue for separating contributing content and the readme. Issue: https://github.com/hackforla/website/issues/962
