### ISSUE TITLE
Add mayor quote portion to bottom of About Us page

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#936]
### Overview
We need to replace the screenshot of the mayor's quote on the bottom of the [About Us page](https://www.hackforla.org/about-us) with code so that it can be visible to search engines, etc. 

Note: The About Us page is in progress and being worked on by @drubgrubby who is on a break right now so please don't edit any of the other code on this page, but this quote portion should definitely save him some extra work.  

### Action Items

Font-End Development
- [x] Read about the [Hack for LA site architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture) (if you haven't already)
- [x] Review the About Us [Figma page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692) (final design in green rectangle) 
- [x] Write code to replace the mayor quote screenshot that is currently on the bottom of the [About Us page](https://www.hackforla.org/about-us) 

### Resources/Instructions
- [Hack for LA site architecture](https://github.com/hackforla/website/wiki/Hack-for-LA's-Site-Architecture)
- About Us page - this is not accessible from the main site nav yet- only through the url https://www.hackforla.org/about-us
- [About Us Figma page](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1803%3A13692) - Final design is in a green rectangle on the bottom. Zoom in with + on keyboard. View the CSS details on the right panel when you select specific elements of the page
- [Hack for LA homepage](https://www.hackforla.org/#) - The About Us mayor quote section is modified from the one in the bottom of the Home page, so you can pull the image and text from here (files: eric_garcetti.md, img url: /assets/images/testimonials/quote-garcetti.jpg, & press.html)

This is the mayor's quote that needs to be developed:

<img width="909" alt="Screen Shot 2021-01-12 at 9 02 18 PM" src="https://user-images.githubusercontent.com/67400366/104408731-893dbc80-5519-11eb-9f95-f40b1a839bf0.png">

**Comment by rh5140** [comment]
1/16 Update

1. Progress: Read site architecture page, downloaded Jekyll. Played Flexbox Froggy to familiarize myself with flexbox. I looked at the About Us Figma page briefly.
2. Blockers: Don't know how to access the part of the CSS w/ the mayor's quote, don't know how I would format the two little quote things in the top corner. Perhaps I need to familiarize myself with the site architecture more.
3. Availability: Not very ;____; Mon, Tue, Thu, Fri evenings should be okay
4. ETA: Unsure

**Comment by rh5140** [comment]
1/18 Update

1. Progress: No change from 1/16, and I'm posting this comment now because I don't expect there to be any change before the Tuesday meeting. The indie game I helped work on releases at noon, so I have spent many hours this weekend getting ready for that :(
2. Blockers: I have not yet had the time to unblock myself regarding the previous blockers :(
3. Availability: Very busy this week :( I switched one of my classes, so I need to do 2 weeks of makeup work. Fortunately, I think after I get caught up, I should be more free since the class I switched out of was taking a lot of my time.
4. ETA: Probably won't be able to focus on issue for another two weeks. I still have no idea at the moment because of (2). I feel like once I have the understanding and the time needed to get started, it would be quick to finish, but I could be totally wrong.

**Comment by daniellex0** [comment]
Note for team: the dependency for this is David R.'s About Us page going live, so this is not a time-sensitive issue

**Comment by pawan92** [comment]
@rh5140  Could you please update:
Progress:
Blockers:
Availability:
ETA:

**Comment by rh5140** [comment]
Sorry for late update :(
Progress: None.
Blockers: Lack of time HAHAHAHA
Availability: Nope :( two midterms this week
ETA: If I still can't find to work on the issue next week, I will ask to be taken off the issue :( I _want_ to be able to work on it but it would be bad if I kept holding onto it when I don't have the time to do it... I will be smarter about choosing classes next quarter.

**Comment by rh5140** [comment]
2/6/2020 Update
I WILL COME TOMORROW!
Progress has not changed at all

Progress: None.
Blockers: Lack of time HAHAHAHA
Availability: Probably much better this week because I got through first round of midterms
ETA: Unfortunately I have done nothing so far so I don't know yet

**Comment by thatguyish** [comment]
Updated mayor quote based on images in figma
<img width="1280" alt="Screen Shot 2021-02-08 at 3 11 58 PM" src="https://user-images.githubusercontent.com/45778144/107291446-30891300-6a36-11eb-9c89-fdc877f97020.png">
<img width="1280" alt="Screen Shot 2021-02-08 at 5 03 10 PM" src="https://user-images.githubusercontent.com/45778144/107291454-34b53080-6a36-11eb-85f5-a835209a8c46.png">
