### ISSUE TITLE
Update Project Profile: Civic Tech Index

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#939]
### Overview
Please review the following information for your project and provide any updates 

### Project card
https://www.hackforla.org/projects/civic-tech-index

### Action Items
Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
- [x] title
- [x] description - refer to changes
- [x] image
- [x] leadership - refer to changes
- [x] links - refer to changes
  - [x] Github
  - [x] Slack
  - [ ] Test Site (N/A)
  - [ ] Demo Site (N/A)
  - [x] Site - update accordingly
- [x] looking - refer to changes
- [x] technologies - refer to changes
- [x] location
- [x] partner
- [x] tools
- [x] status

**Comment by Olivia-Chiong** [comment]
**Update project description with** "Our goal of the project is to create a comprehensive, searchable index of all civic tech open source software projects around the world. We have created the framework and an interest list. We are currently working on building out the website and other marketing tools that demonstrate the power of the index."

**Leadership update**

Bonnie Wolfe
Slack ID: UE1UG1YFP
Github Handle: ExperimentsInHonesty
Role: Agile Coach/Acting Technical Project Manager

Jonathan Shin
Slack ID: U01ASHCHSP2
Github Handle: shinjonathan
Role: Technical Mentor

Olivia Chiong
Slack ID: U01GJC7VC6L
Github Handle: Olivia-Chiong
Role: Product Manager

Gio Sce
Slack ID: U01CU8059BL
Github Handle: giosce
Role: Technical Product Manager

Sean Flores
Slack ID: U012CG71VD1
Github Handle: codewilling
Role: Frontend Developer

Remove Jonathan Sachsman

**Links**: Add Site: http://civictechindex.org/

**looking**: 
remove
Experienced Data Scientist
Database Architect
Video content script writer
UI Designer

Update this role with correct capitalization: 
Front end React developers

unchanged: Fullstack Developer with Node/React knowledge, UX specialist for testing and conducting interviews with stakeholders


**technologies** add this to existing technologies:  ESLint, Code Climate, Cypress

**Comment by pawan92** [comment]
@matthewlee626 Any updates?
Progress:
Blockers:
Availability:
ETA:

**Comment by matthewlee626** [comment]
Completed all the required revisions. I  had some wording confusion that is listed on the PR, which below for convenience.

_Updated all the info; wasn't sure whether leadership that was not mentioned should be removed or left in the list. I ultimately deferred to the latter. All other revisions were quite clear and were updated per specification._

**Comment by matthewlee626** [comment]
@Olivia-Chiong Could you verify that the names not mentioned should be retained?

**Comment by Olivia-Chiong** [comment]
Names not mentioned should be left as is. Thanks!
