### ISSUE TITLE
Update Project Profile: Civic Tech Structure

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#940]
### Overview
Update the Civic Tech Structure project with the information in the comments below

### Project card
https://www.hackforla.org/projects/civic-tech-structure
location of file for changes: _projects/civic-tech-structure.md

### Action Items
Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
- [x] title
- [ ] description
- [x] image
- [ ] leadership
- [x] links
  - [x] Github
  - [x] Slack
  - [x] Test Site - none yet
  - [x] Demo Site - none yet
  - [x] Site - none yet
- [ ] looking
- [ ] technologies
- [x] location
- [x] partner
- [ ] tools
- [x] status

**Comment by ahdithebomb** [comment]
We need to figure out how to CFA/Slack links might work different HfLA Slack links

**Comment by ExperimentsInHonesty** [comment]
In order to display the words CfA Slack: before their name link we need to write some logic that looks at the link to see if its a cfa or a hfla slack link.  Before we do that, we need to do a mockup of how the page will look different.

**Comment by ExperimentsInHonesty** [comment]
Change the description of Civic Tech Structure
The Civic Tech Structure project seeks to improve existing structures and create new ones that make it easier to share replicable processes and practices so that the civic tech community can iterate on each other’s work, improving outcomes for the whole ecosystem. 

Our Civic Tech Structure project is responsible for publishing all of our guides and other reference materials that we hope will help other people and organizations to stand on the shoulders of those who contributed before them.

**Comment by ExperimentsInHonesty** [comment]
The Civic Tech Structure project seeks to improve existing structures and create new ones that make it easier to share replicable processes and practices so that the civic tech community can iterate on each other’s work, improving outcomes for the whole ecosystem.

**Comment by ExperimentsInHonesty** [comment]
Remove existing links:  
Replace with these Links: 
GitHub: https://github.com/hackforla/civic-tech-structure
Overview: https://github.com/hackforla/product-management/blob/master/project-one-sheets/Civic-Tech-Structure-Product-One-Sheet.pdf
README: https://github.com/hackforla/civic-tech-structure/blob/main/README.md


Leadership
Name: Bonnie Wolfe
Role: Executive Director
Slack: https://hackforla.slack.com/team/UE1UG1YFP
Github: experimentsinhonesty

Name: Olivia Chiong
Role: Director of Operations
Slack: https://hackforla.slack.com/team/U01GJC7VC6
Github: olivia-chiong

Remove Partners

Remove
Looking for: UI Designer (brand building), UX Team manager / Lead, UX Researchers (40), UX Designer, UX Team Manager / Lead

Replace with
Looking for: UI/UX Designer (brand building, user experience research and design)
