### ISSUE TITLE
Setting Up SSH keys for new github users

### ISSUE THREAD

**Issue by mdothman** [hackforla/website#947]
### Overview
We need to update the Hack for LA README.md so that it has documentation for setting up ssh keys for users who might run into authorization issues.

### Action Items
- [ ] Discuss with development team where to add text to README.md 
- [ ] Add some text saying something to the effect of: if you experience an SSH error, please let the development lead know, so that we can model your experience fixing it, and add that valuable info into the README.md

##  SSH Keys
In order to gain authorization to push your local changes to your github repo make sure you have git ssh keys set up. Review the [documentation](https://docs.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent) to incorporate.

---
Go to your terminal and type `ssh-keygen` press `enter` a few times to accept defaults (hardly anyone really has a passcode to their github SSH key, but you're welcome to make one.)
* now type `clip < ~/.ssh/id_rsa.pub` 

Follow instructions below on adding the key you have copied

Go to your own GitHub profile and click Settings
![Screen Shot 2021-02-19 at 12 49 18 PM](https://user-images.githubusercontent.com/37763229/108559987-eb27d980-72b0-11eb-84fe-d33ffabb8d67.png)

Then choose 
![Screen Shot 2021-02-19 at 12 50 19 PM](https://user-images.githubusercontent.com/37763229/108560070-0d215c00-72b1-11eb-87ba-5532e7dfb51e.png)

Click on the New SSH Key button
![Screen Shot 2021-02-19 at 12 22 39 PM](https://user-images.githubusercontent.com/37763229/108559817-b0be3c80-72b0-11eb-8c25-744c82882eaf.png)

Input your key on the next screen
![Screen Shot 2021-02-19 at 12 22 51 PM](https://user-images.githubusercontent.com/37763229/108559825-b2880000-72b0-11eb-867e-22bf6d9e8650.png)

**Comment by mdothman** [comment]
## Issue

Setting up SSH keys in order to contribute varies depending on your operating system. I will need to be writing separate instructions for Windows, Mac, and Linux users for setting up ssh keys. I suggest we create a new document called INSTALLATION.md.

## Reasoning

Having access to all programs is crucial for development. In order to ensure our developers have all the necessary tools to create products they should have a guide to refer to. This guide will include all programs needed to contribute to the repository. The guide will also have separate sections for Windows, Mac, and Linux users.

## Conclusion

Without installation guidance a brand new developer may lack necessary tools required for development. This is due to the fact of the massive quantities of programs it takes to get started in development. 

The instructions should include: VS Code, Git Bash, Terminal, Docker, Zoom, Slack, and possibly more. INSTALLATION.md would be a brilliant guide for new users on the 100 Automations website as well.

**Comment by ItsLaszlo** [comment]
Progress: working on a write up 
Blockers: none
ETA: Tuesday 3/16

**Comment by mdothman** [comment]
# Overview

The developer must be aware of using a terminal/console. Windows user will have to install git bash.

## "Terminalogy"

The terminal is a window that contains only text, and is used for executing text based commands. The other names are:

* Console
* Shell
* Command line
* Command prompt

If you are a windows user then you have to install git bash, but if you are a Mac user you only need to use your terminal.

### Git Bash (Windows Users)

Download git bash for windows here

[Git Bash](https://git-scm.com/downloads)

Open git bash on your machine to access the terminal and [set up your ssh keys](#windows).

### Terminal (MAC users)

Your terminal can be found by searching in your Spotlight Search.

![image](https://user-images.githubusercontent.com/56901689/109873992-5d8aa900-7c23-11eb-8f83-ed50f3321946.png)

Then [set up your ssh keys](#mac)

## Setting up SSH keys

### Mac

1. You have to set up SSH keys in order to contribute to github remotely. First check if you have any keys set up already.
   `ls –al ~/.ssh`
2. Then enter the text below into your terminal using your github account email address.
   `ssh-keygen -t rsa -b 4096 -C "your_email@example.com"`
3. You will be asked to enter a file to save the key, press enter, and then enter a passphrase. Then you will need to ensure that your machine and your repository are connected by running the ssh agent.
```eval "$(ssh-agent -s)"```
4. Next you need to add your ssh key to your ssh agent
`ssh-add -K ~/.ssh/id_ed25519`
5. Finally copy the ssh key and add it to your github account by entering the following command. __Don't copy anything else until after you finish the last step, or else you will have to repeat this step.__
`pbcopy < ~/.ssh/id_rsa.pub`
6. Go to your github accounts ssh key settings, and click on the button that says _New SSH key_. Paste the key into the form that pops up.

### Windows

1. You have to set up SSH keys in order to contribute to github remotely. First check if you have any keys set up already.
   `ls –al ~/.ssh`
2. Then enter the text below into your terminal using your github account email address.
   `ssh-keygen -t rsa -b 4096 -C "your_email@example.com"`
3. You will be asked to enter a file to save the key, press enter, and then enter a passphrase. Then you will need to ensure that your machine and your repository are connected by running the ssh agent.
```eval `ssh-agent -s` ```
4. Next you need to add your ssh key to your ssh agent
`ssh-add ~/.ssh/id_rsa`
5. Finally copy the ssh key and add it to your github account by entering the following command. __Don't copy anything else until after you finish the last step, or else you will have to repeat this step.__
`clip < ~/.ssh/id_rsa.pub`
6. Go to your github accounts ssh key settings, and click on the button that says _New SSH key_. Paste the key into the form that pops up.

**Comment by erikaBell** [comment]
Hey @martham0 could you give us an Update.

Progress:
Blockers:
ETA:
Availability:

**Comment by ItsLaszlo** [comment]
Assigning it to @mdothman as he is the one that has written up all the documentation for this.

**Comment by akibrhast** [comment]
Unassigning @mdothman after a slack conversation with him

> I'm not actively working on this, can you please unassign me? - @mdothman

**Comment by akibrhast** [comment]
a

**Comment by akibrhast** [comment]
Our readme currently has no instructions in regards to ssh keys

**Comment by ExperimentsInHonesty** [comment]
@hackforla/website-merge I think we need to add this to the contributing.  Can someone make a ER for it.

**Comment by jdingeman** [comment]
New issue made here:
- https://github.com/hackforla/website/issues/4350
Sending this to Done
