### ISSUE TITLE
Review Meeting Links provided on the HfLA Events and Project Meetings pages

### ISSUE THREAD

**Issue by tarang100** [hackforla/website#950]
### Dependency 
- [x] #3701
- [x] #4252 once this is closed 
  - [ ] and a new issue has been made from it and closed.

### Overview
We need to check every meeting link provided on the Events and Project Meeting pages on the HackforLA Website to ascertain any broken or incorrectly mapped meeting links so that visitors to our website can get the most accurate information

### Action Items

- [x] Please check each meeting link provided on the Events page by clicking on it
- [x] If the link is not working i.e. is broken or leading to a page different than the one mentioned on the Events webpage then please provide correct information in the comments below
- [x] If the link is working as expected i.e. leading the user to the page as mentioned on the Events webpage then please check off the corresponding checkbox below

_All timings mentioned below are in PST_
- [x] Monday, 5:30 pm - 10:30 pm Lucky Parking
- [ ] Monday, 6:30 pm - 6:40 pm Not Today_ (updates)
- [x] Monday, 6:00 pm - 7:00 pm Record Clearance Project Team meeting
- [x] Monday, 7:00 pm - 9:00 pm VRMS
- [ ] Monday, 6:00 pm - 8:00 pm Hack4LA Happy Hour
- [x] Monday, 6:00 pm - 8:00 pm Hack4LA Onboarding
- [ ] Monday, 8:00 pm - 9:00 pm Community of Practice: Software Developers/Front-end Weekly meeting
- [ ] Tuesday, 6:30 pm - 7:30 pm Food Oasis
- [x] Tuesday, 7:00 pm - 8:00 pm Home Unite Us
- [x] Tuesday, 8:00 pm - 8:45 pm Operations Group Weekly Meeting
- [x] Tuesday, 7:00 pm - 7:50 pm Write for All
- [x] Tuesday, 7:00 pm - 8:00 pm Hackforla.org Website Development Team
- [ ] Tuesday, 6:00 pm - 8:00 pm Hack4LA Happy Hour 
- [ ] Tuesday, 5:00 pm - 6:00 pm BallotNav
- [ ] Tuesday, 6:00 pm - 8:00 pm Hack4LA Onboarding
- [ ] Tuesday, 9:00 am - 11:00 am Civic Tech Structure
- [x] Tuesday, 6:00 pm - 7:00 pm Record Clearance Project Design & Research meeting
- [x] Tuesday, 1:00 pm - 2:30 pm Hackforla.org Website PM Meeting
- [ ] Wednesday, 6:30 pm - 9:00 pm Undebate Team Meeting
- [x] Wednesday, 6:00 pm - 7:00 pm Engage
- [x] Wednesday, 7:00 pm - 8:30 pm LA TDM Calculator
- [x] Wednesday, 4:30 pm - 5:30 pm 100 Automations
- [ ] Wednesday, 6:00 pm - 7:00 pm Youth Justice Nav Team Meeting
- [x] Thursday, 7:30 pm - 8:30 pm 311 Data Management Meeting
- [x] Thursday, 6:00 pm - 7:00 pm Civic Tech Index
- [x] Thursday, 8:00 pm - 9:00 pm Food Oasis
- [ ] Thursday, 8:00 pm - 9:00 pm Data Science Team
- [x] Thursday, 6:30 pm - 7:30 pm 311 Data Team Meeting
- [ ] Thursday, 4:00 pm - 5:00 pm Civic Opportunity Project Meeting
- [ ] Thursday, 9:00 am – 11:00 am Civic Tech Structure
- [x] Thursday, 6:00 pm - 7:00 pm Record Clearance Project Dev meeting
- [x] Thursday, 6:00 pm - 6:30 pm 311 Data Data science meeting
- [x] Saturday, 10:00 am - 12:00 pm LA T DM Calculator
- [ ] Saturday, 2:00 pm - 4:00 pm New Schools Today_
- [ ] Saturday, 12:00 pm - 2:00 pm Home Unite Us
- [x] Saturday, 2:00 pm - 4:00 pm 100 Automations
- [ ] Saturday, 11 am - 1 pm Civic Tech Structure
- [x] Sunday, 10:00 am - 12:00 pm Hackforla.org Website
- [ ] Sunday, 12:00 pm - 2:00 pm Hack for LA Marketing Team
- [ ] Sunday, 2:00 pm - 4:00 pm Civic Tech Index
- [ ] Sunday, 9:00 am - 10:00 am Civic Opportunity Project

### Resources/Instructions
[HackforLA Events Webpage](https://www.hackforla.org/events)
[HackforLA Project Meetings](https://www.hackforla.org/project-meetings)

**Comment by tarang100** [comment]
**Update**

Please see the following list for information on Meeting Links _**mapped incorrectly**_ on the HfLA Events Page

   - [ ] Monday 12:30 am - 2:30 am Hack for LA Marketing Team - Leads to [HfLA Website Project Page](https://www.hackforla.org/projects/website)
      - [ ] Time
      - [ ] Name
      - [x] Link resolves to 
      - [ ] Needs to be removed from site
   - [ ] Tuesday 7:00 am - 7:10 am Not Today (updates) - Leads to [Not Today Project Page](https://www.hackforla.org/projects/not-today) but the word 'updates' needs to be checked
      - [ ] Time
      - [ ] Name
      - [ ] Link resolves to
      - [ ] Needs to be removed from site
   - [ ] Tuesday 6:30 am - 8:30 am Hack4LA Happy Hour - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
      - [ ] Time
      - [ ] Name
      - [x] Link resolves to 
      - [ ] Needs to be removed from site
   - [ ] Tuesday 6:30 am - 8:30 am Hack4LA Onboarding - Lead to the [HfLA Project Cards page](https://www.hackforla.org/)
      - [ ] Time
      - [ ] Name
      - [x] Link resolves to 
      - [ ] Needs to be removed from site
   - [ ] Tuesday 8:30 am - 9:30 am Community of Practice: Software Developers/Front-end Weekly meeting - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
      - [ ] Time
      - [ ] Name
      - [x] Link resolves to
      - [ ] Needs to be removed from site
   - [ ] Wednesday 8:30 am - 9:15 am Operations Group Weekly Meeting - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
      - [ ] Time
      - [ ] Name
      - [x] Link resolves to
      - [ ] Needs to be removed from site
   - [ ] Wednesday 6:30 am - 8:30 am Hack4LA Happy Hour - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
      - [ ] Time
      - [ ] Name
      - [x] Link resolves to
      - [ ] Needs to be removed from site
   - [ ] Wednesday 5:30 am - 6:30 am BallotNav - Link is broken
      - [ ] Time
      - [ ] Name
      - [x] Link resolves to https://www.hackforla.org/projects/ballot-nav
      - [ ] Needs to be removed from site
   - [ ] Wednesday 6:30 am - 8:30 am Hack4LA Onboarding - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
      - [ ] Time
      - [ ] Name
      - [x] Link resolves to
      - [ ] Needs to be removed from site
   - [ ] Thursday 6:30 am - 7:30 am Youth Justice Nav Team Meeting - Link is broken
      - [ ] Time
      - [ ] Name
      - [x] Link resolves to
      - [ ] Needs to be removed from site
   - [ ] Friday 8:30 am - 9:30 am Data Science Team - Leads to the [HfLA Website Project Page](https://www.hackforla.org/projects/website)
      - [ ] Time
      - [ ] Name
      - [x] Link resolves to
      - [ ] Needs to be removed from site

**Comment by ExperimentsInHonesty** [comment]
- [ ] Monday 12:30 am - 2:30 am Hack for LA Marketing Team - Leads to the [HfLA Website Project Page](https://www.hackforla.org/projects/website)
   - [ ] Tuesday 7:00 am - 7:10 am Not Today (updates) - Leads to [Not Today Project Page](https://www.hackforla.org/projects/not-today) but the word 'updates' needs to be checked
   - [ ] Tuesday 6:30 am - 8:30 am Hack4LA Happy Hour - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Tuesday 6:30 am - 8:30 am Hack4LA Onboarding - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Tuesday 8:30 am - 9:30 am Community of Practice: Software Developers/Front-end Weekly meeting - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Wednesday 8:30 am - 9:15 am Operations Group Weekly Meeting - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Wednesday 6:30 am - 8:30 am Hack4LA Happy Hour - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Wednesday 5:30 am - 6:30 am BallotNav - Link is broken
   - [ ] Wednesday 6:30 am - 8:30 am Hack4LA Onboarding - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Thursday 6:30 am - 7:30 am Youth Justice Nav Team Meeting - Link is broken
   - [ ] Friday 8:30 am - 9:30 am Data Science Team - Leads to the [HfLA Website Project Page](https://www.hackforla.org/projects/website)

**Comment by ExperimentsInHonesty** [comment]
Change day and time 
**Update**

Please see the following list for information on Meeting Links _**mapped incorrectly**_ on the HfLA Events Page

   - [ ] Monday 12:30 am - 2:30 am Hack for LA Marketing Team - Leads to the [HfLA Website Project Page](https://www.hackforla.org/projects/website)
   - [ ] Tuesday 7:00 am - 7:10 am Not Today (updates) - Leads to [Not Today Project Page](https://www.hackforla.org/projects/not-today) but the word 'updates' needs to be checked
   - [ ] Tuesday 6:30 am - 8:30 am Hack4LA Happy Hour - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Tuesday 6:30 am - 8:30 am Hack4LA Onboarding - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Tuesday 8:30 am - 9:30 am Community of Practice: Software Developers/Front-end Weekly meeting - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Wednesday 8:30 am - 9:15 am Operations Group Weekly Meeting - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Wednesday 6:30 am - 8:30 am Hack4LA Happy Hour - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Wednesday 5:30 am - 6:30 am BallotNav - Link is broken
   - [ ] Wednesday 6:30 am - 8:30 am Hack4LA Onboarding - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Thursday 6:30 am - 7:30 am Youth Justice Nav Team Meeting - Link is broken
   - [ ] Friday 8:30 am - 9:30 am Data Science Team - Leads to the [HfLA Website Project Page](https://www.hackforla.org/projects/website)
Monday 12:30 am - 2:30 am Hack for LA Marketing Team - Leads to the HfLA Website Project Page
 Tuesday 7:00 am - 7:10 am Not Today (updates) - Leads to Not Today Project Page but the word 'updates' needs to be checked
 Tuesday 6:30 am - 8:30 am Hack4LA Happy Hour - Leads to the HfLA Project Cards page
 Tuesday 6:30 am - 8:30 am Hack4LA Onboarding - Leads to the HfLA Project Cards page
 Tuesday 8:30 am - 9:30 am Community of Practice: Software Developers/Front-end Weekly meeting - Leads to the HfLA Project Cards page
 Wednesday 8:30 am - 9:15 am Operations Group Weekly Meeting - Leads to the HfLA Project Cards page
 Wednesday 6:30 am - 8:30 am Hack4LA Happy Hour - Leads to the HfLA Project Cards page
 Wednesday 5:30 am - 6:30 am BallotNav - Link is broken
 Wednesday 6:30 am - 8:30 am Hack4LA Onboarding - Leads to the HfLA Project Cards page
 Thursday 6:30 am - 7:30 am Youth Justice Nav Team Meeting - Link is broken
 Friday 8:30 am - 9:30 am Data Science Team - Leads to the HfLA Website Project Page

**Comment by ExperimentsInHonesty** [comment]
Change day and time 
**Update**

Please see the following list for information on Meeting Links _**mapped incorrectly**_ on the HfLA Events Page

   - [x] Monday 12:30 am - 2:30 am Hack for LA Marketing Team - Leads to the [HfLA Website Project Page](https://www.hackforla.org/projects/website)
   - [ ] Tuesday 7:00 am - 7:10 am Not Today (updates) - Leads to [Not Today Project Page](https://www.hackforla.org/projects/not-today) but the word 'updates' needs to be checked
   - [x] Tuesday 6:30 am - 8:30 am Hack4LA Happy Hour - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Tuesday 6:30 am - 8:30 am Hack4LA Onboarding - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Tuesday 8:30 am - 9:30 am Community of Practice: Software Developers/Front-end Weekly meeting - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Wednesday 8:30 am - 9:15 am Operations Group Weekly Meeting - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Wednesday 6:30 am - 8:30 am Hack4LA Happy Hour - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Wednesday 5:30 am - 6:30 am BallotNav - Link is broken
   - [ ] Wednesday 6:30 am - 8:30 am Hack4LA Onboarding - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Thursday 6:30 am - 7:30 am Youth Justice Nav Team Meeting - Link is broken
   - [ ] Friday 8:30 am - 9:30 am Data Science Team - Leads to the [HfLA Website Project Page](https://www.hackforla.org/projects/website)

**Comment by ExperimentsInHonesty** [comment]
Change day and time 
**Update**

Please see the following list for information on Meeting Links _**mapped incorrectly**_ on the HfLA Events Page

   - [x] Monday 12:30 am - 2:30 am Hack for LA Marketing Team - Leads to the [HfLA Website Project Page](https://www.hackforla.org/projects/website)
   - [ ] Tuesday 7:00 am - 7:10 am Not Today (updates) - Leads to [Not Today Project Page](https://www.hackforla.org/projects/not-today) but the word 'updates' needs to be checked
   - [x] Tuesday 6:30 am - 8:30 am Hack4LA Happy Hour - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Tuesday 6:30 am - 8:30 am Hack4LA Onboarding - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Tuesday 8:30 am - 9:30 am Community of Practice: Software Developers/Front-end Weekly meeting - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Wednesday 8:30 am - 9:15 am Operations Group Weekly Meeting - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Wednesday 6:30 am - 8:30 am Hack4LA Happy Hour - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Wednesday 5:30 am - 6:30 am BallotNav - Link is broken
   - [ ] Wednesday 6:30 am - 8:30 am Hack4LA Onboarding - Leads to the [HfLA Project Cards page](https://www.hackforla.org/)
   - [ ] Thursday 6:30 am - 7:30 am Youth Justice Nav Team Meeting - Link is broken
   - [ ] Friday 8:30 am - 9:30 am Data Science Team - Leads to the [HfLA Website Project Page](https://www.hackforla.org/projects/website)

**Comment by ExperimentsInHonesty** [comment]
- [x] Friday 8:30 am - 9:30 am Data Science Team - Leads to the [HfLA Website Project Page](https://www.hackforla.org/projects/website)
      - [ ] Time
      - [ ] Name
      - [ ] Link resolves to

**Comment by tarang100** [comment]
- #739
- #800
- #801
- #957
- #999
- #693

**Comment by ExperimentsInHonesty** [comment]
![screencapture-hackforla-org-events-2021-02-10-12_11_07 (1)](https://user-images.githubusercontent.com/37763229/107565967-229fd300-6b99-11eb-943b-20a450f34785.png)

**Comment by tarang100** [comment]
Update - Working on the issue
Blockers - None
ETA - Will complete by the end of this week
Availability - Flexible

**Comment by ExperimentsInHonesty** [comment]
@tarang100 Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by tarang100** [comment]
1. Progress - Have not been able to devote time to this issue due to sudden increase in workload at office. Ended up prioritizing to work on more time sensitive issues. Will prioritize this issue now
2. Blockers - None
3. Availability - Flexible
4. ETA - By next week's team meeting

**Comment by ExperimentsInHonesty** [comment]
This page will help you to change your browsers time zone.  We can talk about this next time we talk: https://www.makeuseof.com/tag/trick-websites-changing-user-agent-chrome/

**Comment by qiqicodes** [comment]
@tarang100 Can you let us know your progress in regards to this issue? Thank you =]

Progress:
Blockers:

**Comment by ExperimentsInHonesty** [comment]
Monday

- [ ] 12:00 pm - 1:00 pm Open Community Survey Team Meeting
   - [ ] Time
   - [ ] Name
   - [ ] Link resolves to 
   - [ ] Needs to be removed from site
- [ ] 3:00 pm - 4:00 pm Food Oasis Management
- [ ] 6:00 pm - 7:00 pm Lucky Parking Team Meeting
- [ ] 6:00 pm - 7:00 pm Expunge Assist Team meeting on 1st & 3rd Mondays/PM on all other Mondays
- [ ] 6:00 pm - 8:00 pm Civic Tech Index Team Meeting
- [ ] 6:00 pm - 7:30 pm Onboarding Alternating Mon/Tue. Click for schedule
- [ ] 6:30 pm - 6:40 pm Not Today (updates)
- [ ] 7:00 pm - 9:00 pm VRMS
- [ ] 8:00 pm - 9:00 pm Community of Practice: Software Developers/Front-end Weekly meeting

Tuesday

- [ ] 10:00 am - 11:00 am Brigade Organizers Playbook Core Team
- [ ] 1:00 pm - 2:30 pm Hackforla.org Website PM Meeting
- [ ] 2:00 pm - 3:00 pm Access the Data Team Meeting
- [ ] 5:00 pm - 6:00 pm BallotNav
- [ ] 6:00 pm - 7:00 pm Engage All Team Members
- [ ] 6:00 pm - 7:00 pm Expunge Assist Research & Design meeting
- [ ] 6:00 pm - 7:30 pm Onboarding Alternating Mon/Tue. Click for schedule
- [ ] 6:30 pm - 7:30 pm Food Oasis Development
- [ ] 7:00 pm - 8:00 pm Home Unite Us
- [ ] 7:00 pm - 7:50 pm Write for All™
- [ ] 7:00 pm - 8:00 pm Hackforla.org Website Development Team
- [ ] 8:00 pm - 8:45 pm Operations Group Weekly Meeting

Wednesday
12:30 pm - 1:30 pm Civic Tech Index Product Managers Meeting
4:30 pm - 5:30 pm 100 Automations
5:00 pm - 6:00 pm Engage Product Manager Meeting
6:00 pm - 7:00 pm Community of Practice: UI/UX Weekly meeting
6:00 pm - 7:00 pm Community of Practice: Product Management Weekly meeting
6:00 pm - 7:00 pm Community of Practice: Software Engineering Weekly meeting
6:30 pm - 9:00 pm Undebate Team Meeting
7:00 pm - 8:30 pm LA TDM Calculator
7:00 pm - 8:00 pm Youth Justice Nav Team Meeting
7:00 pm - 8:00 pm GreenEarthOS Team Meeting
Thursday

- [ ] 4:00 pm - 5:00 pm Civic Opportunity Project Meeting
- [ ] 6:00 pm - 7:00 pm Civic Tech Index Team Meeting
- [ ] 6:00 pm - 7:00 pm Food Oasis Team
- [ ] 6:00 pm - 7:00 pm Expunge Assist Dev meeting
- [ ] 6:00 pm - 6:30 pm 311 Data Data science meeting
- [ ] 6:30 pm - 7:30 pm 311 Data Team Meeting
- [ ] 6:30 pm - 7:30 pm VRMS Developers' Meeting
- [ ] 7:30 pm - 8:30 pm 311 Data Management Meeting
- [ ] 8:00 pm - 9:00 pm Data Science Team

Friday

- [ ] 10:00 am - 11:00 am Community of Practice: Product Management Weekly meeting
- [ ] 3:00 pm - 4:00 pm Youth Justice Nav Team Meeting
- [ ] 7:00 pm - 8:00 pm Community of Practice: Marketing Weekly meeting

Saturday

- [ ] 10:00 am - 12:00 pm LA TDM Calculator
- [ ] 11:00 am - 1:00 pm Brigade Organizers Playbook Core Team
- [ ] 12:30 pm - 2:00 pm Home Unite Us
- [ ] 2:00 pm - 4:00 pm New Schools Today
- [ ] 2:00 pm - 4:00 pm 100 Automations

Sunday

- [ ] 9:00 am - 10:00 am Civic Opportunity Project
- [ ] 10:00 am - 12:00 pm Hackforla.org Website
- [ ] 12:00 pm - 2:00 pm Hack for LA Marketing Team
- [ ] 4:00 pm - 5:00 pm Engage All Team Members

**Comment by sheltoG** [comment]
**WIP: Below is the audit checklist for reviewing meeting links on Hfla webpage.**

**Monday**

- [x] 12:00 pm - 1:00 PDT pm Open Community Survey Team Meeting
- [x] 3:00 pm - 4:00 pm Food Oasis Management
- [x] 6:00 pm - 7:00 pm Lucky Parking Team Meeting
- [x] 6:00 pm - 7:00 pm Expunge Assist Team meeting on 1st & 3rd Mondays/PM on all other Mondays
- [x] 6:00 pm - 8:00 pm Civic Tech Index Team Meeting  
- [x] 6:00 pm - 7:30 pm Onboarding Alternating Mon/Tue. Click for schedule
- [x] 6:30 pm - 6:40 pm Not Today (updates)
- [x] 7:00 pm - 9:00 pm VRMS

**Tuesday**

- [x] 10:00 am - 11:00 am Brigade Organizers Playbook Core Team
- [ ] 5:00 pm - 6:00 pm BallotNav
- [x] 6:00 pm - 7:00 pm Engage All Team Members
- [x] 6:00 pm - 7:00 pm Expunge Assist Research & Design meeting
- [x] 6:00 pm - 7:30 pm Onboarding Alternating Mon/Tue. Click for schedule
- [x] 6:30 pm - 7:30 pm Food Oasis Development
- [x] 7:00 pm - 8:00 pm Home Unite Us
- [x] 7:00 pm - 7:50 pm Write for All™
- [x] 7:00 pm - 8:00 pm Hackforla.org Website Development Team
- [ ] 8:00 pm - 8:45 pm Operations Group Weekly Meeting

**Wednesday**

- [x] 12:00 pm - 1:00 pm Hackforla.org Website PM Meeting
- [x] 12:30 pm - 1:30 pm Civic Tech Index Product Managers Meeting
- [x] 5:00 pm - 6:00 pm Home Unite Us Design-Every other Wed
- [x] 5:00 pm - 6:00 pm Engage Product Manager Meeting
- [x] 6:00 pm - 7:00 pm Community of Practice: UI/UX Weekly meeting
- [x] 6:00 pm - 7:00 pm Community of Practice: Product Management Weekly meeting
- [x] 6:00 pm - 7:00 pm Community of Practice: Software Engineering Weekly meeting
- [x] 6:30 pm - 9:00 pm Undebate Team Meeting
- [x] 7:00 pm - 8:30 pm LA TDM Calculator
- [ ] 7:00 pm - 8:00 pm Youth Justice Nav Team Meeting
- [ ] 7:00 pm - 8:00 pm GreenEarthOS Team Meeting

**Thursday**

- [x] 4:00 pm - 5:00 pm Civic Opportunity Project Meeting
- [x] 5:00 pm - 6:00 pm 100 Automations
- [x] 5:00 pm - 6:00 pm Hackforla.org Website UI-UX Meeting
- [x] 6:00 pm - 7:00 pm Civic Tech Index Team Meeting
- [x] 6:00 pm - 7:00 pm Food Oasis Team
- [x] 6:00 pm - 7:00 pm Expunge Assist Dev meeting
- [x] 6:00 pm - 6:30 pm 311 Data Data science meeting
- [x] 6:30 pm - 7:30 pm 311 Data Team Meeting
- [x] 6:30 pm - 7:30 pm VRMS Developers' Meeting
- [x] 7:00 pm - 8:00 pm Hackforla.org Website Back-end Meeting
- [x] 7:30 pm - 8:30 pm 311 Data Management Meeting
- [x] 8:00 pm - 9:00 pm Data Science Team


**Friday**

- [x] 10:00 am - 11:00 am Community of Practice: Product Management Weekly meeting
- [ ] 3:00 pm - 4:00 pm Youth Justice Nav Team Meeting
- [x] 7:00 pm - 8:00 pm Community of Practice: Marketing Weekly meeting

**Saturday**

- [x] 10:00 am - 12:00 pm LA TDM Calculator
- [x] 11:00 am - 1:00 pm Brigade Organizers Playbook Core Team
- [x] 2:00 pm - 4:00 pm New Schools Today
- [x] 2:00 pm - 4:00 pm 100 Automations

**Sunday**

- [x] 9:00 am - 10:00 am Civic Opportunity Project
- [x] 10:00 am - 12:00 pm Hackforla.org Website
- [x] 12:00 pm - 2:00 pm Hack for LA Marketing Team
- [x] 4:00 pm - 5:00 pm Engage All Team Members

**Comment by sheltoG** [comment]
- Opened Issue: Fix URL for Expunge Assist on Hfla Events Page #2167 
- Opened Issue: Remove URL for Community of Practice: Software Developers/Front-end Weekly meeting link on Hfla Events Page #2168

**Comment by ExperimentsInHonesty** [comment]
@sheltoG I moved  
- 2168 to https://github.com/hackforla/VRMS/issues/685
- 2167 to https://github.com/hackforla/VRMS/issues/684
to the vrms board, because hfla just gets the data from them

**Comment by sheltoG** [comment]
Items that have bad links. @ExperimentsInHonesty can you validate which of this projects are active?

1. 5:00 pm - 6:00 pm BallotNav
2. 8:00 pm - 8:45 pm Operations Group Weekly Meeting
3.  7:00 pm - 8:00 pm Youth Justice Nav Team Meeting
4.  7:00 pm - 8:00 pm GreenEarthOS Team Meeting
5.  3:00 pm - 4:00 pm Youth Justice Nav Team Meeting

**Comment by ExperimentsInHonesty** [comment]
1. Active
2. Active Now called Devops or Ops Community of Practie
3. Active
4. Active
5. Active

**Comment by roslynwythe** [comment]
Availability: 3-7 11/7, 1-11 pm 11/8
ETA:  11pm 11/8

**Comment by roslynwythe** [comment]
It's been more than a year since the audit (task) list was generated so it is quite out of date.  If a meeting did not appear on the current Events page, I did not mark the task as completed.  I followed every link on the Events page and found that these links should be updated:

- [x] Monday 5:30 - 6:30 pm Design Systems Weekly Meeting - should link to https://www.hackforla.org/projects/design-systems
- [ ] Tues 5-6 ballot nav - should link to https://www.hackforla.org/projects/ballot-nav
- [ ] wed 7-8 GreenEarthOS team meeting - should link to https://www.hackforla.org/projects/green-earth-os
- [x] wed 7-8 Youth Justice nav - should link to https://www.hackforla.org/projects/youthjusticenav
- [x] Fri 3-4Youth Justice Nav - should link to https://www.hackforla.org/projects/youthjusticenav
- [ ] sun 10-11 testy test - broken link, not sure where it should go

I also thought that I should cross-check the COP meetings against the list at https://github.com/hackforla/website/wiki/Meetings-and-Agendas but I wasn't able to do that because events are not rendering at this time.

**Comment by roslynwythe** [comment]
@tarang100 please advise re: status of this issue and position on Project Board.  Thanks

**Comment by jdingeman** [comment]
@ExperimentsInHonesty please see above comment from @roslynwythe for links that are outdated

**Comment by ExperimentsInHonesty** [comment]
- I am going to stick this issue in the icebox with dependency being the fixing the events page vrms connection #3701 

When this issue comes out of the icebox, I will check to see if changing the data at VRMS fixes the link automatically.
- The change will need to be made at vrms.io
- then checked the next day after data updates

If that does not fix it, this issue should be turned into an issue for development to figure out why the project meeting times don't link to the correct meetings.

**Comment by 7kram** [comment]
When going through the different projects on the events page, "Access the data" takes you to their [website](http://accessthedata.org/) rather than the [project page](https://www.hackforla.org/projects/access-the-data)

**Comment by t-will-gillis** [comment]
All projects links have been fixed as of 8/25/23. Re: #4906. 

@ExperimentsInHonesty Regarding meeting times and the [note above](https://github.com/hackforla/website/issues/950#issuecomment-1317420997), the meeting times shown in the issue above are at least 8 months old- I assume the listed meetings have been edited on multiple occasions since then. Otherwise, it appears that the data from VRMS appears to be working correctly- does there need to be a final review or can this issue be **closed as completed**?

**Comment by t-will-gillis** [comment]
@ExperimentsInHonesty As discussed we discussed in the Monday meeting and above, we have fixed the project links, and the last outstanding issue #5345 (from ER #5195) adds more info to the Project Meetings pages. Closing this as completed.
