### ISSUE TITLE
Update Project Profile: Home Unite Us

### ISSUE THREAD

**Issue by tarang100** [hackforla/website#953]
### Overview
As a product manager, I need to make sure that all the projects that are listed on the HfLA website are up to date so that my customers(visitors) can get an accurate picture of each of the projects.

### Project card
https://www.hackforla.org/projects/home-unite-us

### Action Items
Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
- [x] title
- [x] description
- [x] image
- [x] leadership
  - [x] Member Name
  - [x] Role
  - [x] Slack Member ID
  - [x] Github Handle
- [x] links
  - [x] Github
  - [x] Slack
  - [x] Test Site
  - [x] Demo Site
  - [x] Site
- [x] looking
- [x] technologies
- [x] location
- [x] partner
- [x] tools
- [x] status

**Comment by tarang100** [comment]
**Note for Developers** - Please utilize the information provided in Alex's comment. Link to comment given below https://github.com/hackforla/website/issues/953#issuecomment-761248700

**Comment by drubgrubby** [comment]
@thatguyish - I see that you made a PR for this issue.  Good work.  

Can you please update this issue with a short description of what you did, and a screen-shot showing the updates? Don't forget to add that you opened a ticket at VRMS regarding the time change.

**Comment by thatguyish** [comment]
@drubgrubby  yes indeed 
Added the new png to the assets folder and set the logo to it.
I also added the links for Test  Site and Site
<img width="1280" alt="Screen Shot 2021-02-07 at 10 42 29 AM" src="https://user-images.githubusercontent.com/45778144/107151582-5678bf80-6931-11eb-9970-9e70bbf14af1.png">
I modified Tyler Tome to reflect HUU Tech Lead, added Abby Hipp and Tracy Michelle In Leadership
<img width="1280" alt="Screen Shot 2021-02-07 at 10 42 35 AM" src="https://user-images.githubusercontent.com/45778144/107151650-ac4d6780-6931-11eb-8c3c-98c6c9cde86a.png">
Lastly I updated the looking section technologies, location, partners, and status.
<img width="1280" alt="Screen Shot 2021-02-07 at 10 42 46 AM" src="https://user-images.githubusercontent.com/45778144/107151719-fdf5f200-6931-11eb-84e1-e14eb87dc071.png">

There is also a ticket open at VRMS regarding the meeting time changes.

**Comment by mcspach** [comment]
Bonnie has reached out to Abby, to ask for review and updates of Leadership team and for status change to 'Active'.

**Comment by ExperimentsInHonesty** [comment]
@abbyhipp @alexilee Can you look at the leadership.  It seems like you have indicated additions but not identified people to remove. Please verify all details.  

FYI: The only status available on the site is Active, On-Hold and Completed.  This project is Active.

**Comment by quyenvhle** [comment]
@tarang100 @thatguyish Confirmed that we need to remove people from the leadership team. 

Please remove the following:
- Timothy Malstead
- Arshia Masih
- Sophia Alice
- Carolanne Fuchs
- Peter Plass

The following people are to be kept under leadership:
- Tyler Thome
- Abby Hipp
- Tracy Michelle

In addition, please help us change the project status to 'Active'.

**Comment by jbubar** [comment]
@thatguyish completed a pull request to update this on the site. There is just one thing.
VRMS needs to update the time.
The new meeting times are ([specified earlier in this conversation](https://github.com/hackforla/website/issues/953#issuecomment-761248700)):
>Tue 10:00 pm - 11:00 pm (EDT)
>Sat 3:30 pm - 5:00 pm (EDT)

The current times are: 
>Tue 10:00 pm - 11:00 pm (EDT)
>Sat 3:00 pm - 5:00 pm (EDT)

So it is a small change! :))
I will send this message to the VRMS slack channel

**Comment by jbubar** [comment]
Created an issue in VRMS here https://github.com/hackforla/VRMS/issues/490
Thanks @drubgrubby for informing me

**Comment by jbubar** [comment]
Oops. @thatguyish just informed me that he has already created and issue with vrms. So I went ahead and closed the issue that I created
