### ISSUE TITLE
Update Project Profile: Undebate

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#954]
### Overview
As a product manager, I need to make sure that all the projects that are listed on the HfLA website are up to date so that my customers(visitors) can get an accurate picture of each of the projects.

### Project card
https://www.hackforla.org/projects/undebate

### Action Items

- [ ] Undebate Team Leadership
   - [ ] Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
      - [x] title
      - [ ] description
      - [x] image
      - [ ] leadership
        - [x] Member Name
        - [ ] Role
        - [x] Slack Member ID
        - [ ] Github Handle
     - [ ] links
        - [x] Github
        - [x] Slack
        - [x] Test Site
        - [ ] Demo Site
        - [x] Site
     - [x] looking
     - [x] technologies
     - [x] location
     - [x] partner
     - [x] tools
     - [x] status

**Comment by danyc23** [comment]
Changed the Demo link text to Demo Site for the Undebate profile page
Changed the role text in the Undebate profile page.
Changed the description of the Undebate project on the Undebate profile page.
![Screen Shot 2021-01-28 at 6 10 08 PM](https://user-images.githubusercontent.com/42159475/106228024-50e7e080-619f-11eb-93aa-513f8a8d55e6.png)
![Screen Shot 2021-01-28 at 7 19 29 PM](https://user-images.githubusercontent.com/42159475/106228026-52190d80-619f-11eb-9f48-91e0797d8b37.png)

**Comment by ddfridley** [comment]
Looks Great!

**Comment by pawan92** [comment]
@danyc23  Could you please update:
Progress:
Blockers:
Availability:
ETA:
