### ISSUE TITLE
Update Project Profile: 311 Data 

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#957]
### Overview
Please review the following information for your project and provide any updates 

### Project card
https://www.hackforla.org/projects/311-data

### Action Items
Please check off everything that is ok the way that it is, and if not, please provide the updated information in the comments below:
- [ ] title
- [ ] description
- [x] image
- [x] leadership
- [ ] links
  - [ ] Github
  - [ ] Slack
  - [ ] Test Site
  - [ ] Demo Site
  - [ ] Site
- [ ] looking
- [x] technologies
- [ ] location
- [ ] partner
- [ ] tools
- [ ] status

**Comment by captain-nimo** [comment]
I've already talked with the `311-data` UX team about the background image. Once I get it from them, I'll attach it here.

**Comment by captain-nimo** [comment]
@ahdithebomb, please find the the background image attached here.

![311_Mockup](https://user-images.githubusercontent.com/25173228/106981838-c5d39100-6730-11eb-821b-e2983118aded.png)
