### ISSUE TITLE
Standardize all page cards across the site

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#958]
### Overview
We need to standardize the page cards across the entire HfLA site. This is to ensure visual consistency, and to make it easier and more efficient for developers to insert page cards when creating new pages.

### Action Items
UI/UX

- [x] Audit all page cards on site
- [x] Determine standard page card features (colors, sizes, etc)

Development

 - [x] Determine CSS class names and properties for standardized page cards
 - [x] Implement CSS and HTML changes in the code to standardize page cards on site

### Resources/Instructions
[Design System Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=3464%3A3)
[Design Audit: Edits Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=4272%3A0)
[Standardized Components Wiki ](https://github.com/hackforla/website/wiki/Standardized-Components)

**Comment by pawan92** [comment]
@daniellex0 Could you update please
Progress:
Blockers:
Availability:
ETA:

**Comment by daniellex0** [comment]
Progress: Almost finished with this, but figuring out some responsiveness issues. I prioritized designer-facing aspects of the design system this week because of all of the new designers, while I gauge what works/doesn't work for the devs that are working on new pages/testing my design system classes

Next Steps: Figure out remaining issues and push

**Comment by daniellex0** [comment]
Progress: Close to finished- have been coordinating with the devs that are working on new pages and using this + other reusable components, so I've been able to adjust based on their work. I'm hoping to discuss their experience/feedback in the end and figure out how best to present these components based on that. Also Alyssa's issue may rely on old page cards, so I don't want to change too much before she's done.

Next Steps: Finish remaining loose ends and push

**Comment by daniellex0** [comment]
Progress: A few dependencies are pending (new pages being worked on and Alyssa's issue may rely on old page cards, so I don't want to change too much before she's done). However it's ready to deploy soon and I'm still gathering some feedback/experiences from developers working on new pages (for ex. Travis found a fix for an inconsistency in the margins between page cards on different pages, which will need to be included in the standard code) 

Next Steps: Finish remaining loose ends

**Comment by daniellex0** [comment]
Progress: Dependencies are pending (new pages being worked on and Alyssa's issue may rely on old page cards, so I don't want to change too much before she's done). However it's ready to deploy soon and I'm still gathering some feedback/experiences from developers working on new pages (for ex. Travis found a fix for an inconsistency in the margins between page cards on different pages, which will need to be included in the standardized code)

Next Steps: Finish loose ends and push

**Comment by daniellex0** [comment]
Progress: Dependencies are still pending (new pages being worked on and Alyssa's issue may rely on old page cards, so I don't want to change too much before she figures her page out). However it's ready to deploy soon and I'm still gathering some feedback/experiences from developers working on new pages (for ex Martha suggested this week not to include standard padding, because this varies page by page)

Next Steps: Finish and push

**Comment by daniellex0** [comment]
Progress: Dependencies still pending but I will try to finish this before the Tue dev meeting regardless because it is affecting new pages being built.

Next Steps: Finish and push before Tuesday

**Comment by tarang100** [comment]
@daniellex0 please provide status update

**Comment by daniellex0** [comment]
Progress: I am waiting on the Join Us page to go live (should happen today) - so that I can standardize all of the pages cards, including that new pages (since it relies on reusable page card component). 

Next Steps: If the Join Us page goes live, I will finish this by Tuesday's dev meeting.

**Comment by ExperimentsInHonesty** [comment]
@daniellex0 
Please provide update
1. Progress
2. Blockers
3. Availability
4. ETA

**Comment by daniellex0** [comment]
@ExperimentsInHonesty There is a pull request above ^. Just waiting on reviews/approval/merge
