### ISSUE TITLE
Standardize Toolkit Page with CSS Fixes

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#960]
### Overview
We need to standardize the CSS styling of the Toolkit Page so that it will be more consistent with the rest of the HfLA website.

### Action Items
Front-End Development
- [ ] Review the HfLA site architecture
- [ ] Review the CSS fixes on the Toolkit page file on Figma
- [ ] Implement the CSS fixes on the Toolkit page's .scss file 

### Resources/Instructions
[Toolkit page Figma file (edits to the right of the screen in pink rectangle)](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=5892%3A0)

**Comment by pawan92** [comment]
@TeddyTelanoff  Could you please update:
Progress:
Blockers:
Availability:
ETA:
