### ISSUE TITLE
About us: Recalculate navigation links

### ISSUE THREAD

**Issue by drubgrubby** [hackforla/website#967]
### Overview
When the page is loaded in mobile view the link locations are calculated based on the location of the closed accordion.  If the page is then expanded to desktop the navigation links do not highlight correctly when scrolling. 

As you can see on the below image, the highlighted link is "Partners" but the displayed section is "Platform"

<img width="1168" alt="Screen Shot 2021-01-24 at 7 55 01 PM" src="https://user-images.githubusercontent.com/68244054/105659657-22f05c80-5e7e-11eb-849f-e5cae8d1d365.png">

### Action Items
Create an event listener that recalculates the link locations on resize or orientation change. 

### Resources/Instructions
https://www.hackforla.org/about-us

**Comment by qiqicodes** [comment]
Progress: Fixed basic issue, aligning the highlighted link in the sticky navigation bar to the content with corresponding id after resize or orientation change . Currently adding a feature that remembers the selected highlighted link in desktop mode and transfer to the corresponding location in mobile mode, and vice versa.

Blockers: Need to figure out how to write the eventListener for the feature desired. Also need to figure out how to make it cross-browser compatible. And want to check in with the team if there are other suggestions.

Availability: Open.

ETA: Desire to merge by 2/21/21 (It may take longer considering the complexity).

Current Chrome Output:
(Images are captured after resizing from mobile view to desktop view on responsive mode. Each capture shows the corresponding content along with the change in highlighter link.)

**Hack for LA Platform**
<img width="702" alt="Screen Shot 2021-02-14 at 6 35 23 PM" src="https://user-images.githubusercontent.com/68657634/107899879-704b7100-6ef4-11eb-8d5a-31b713debe33.png">

**Sustainability**
<img width="697" alt="Screen Shot 2021-02-14 at 6 35 45 PM" src="https://user-images.githubusercontent.com/68657634/107899887-76415200-6ef4-11eb-9282-1e2b2160c5b8.png">

**Accomplishments**
<img width="701" alt="Screen Shot 2021-02-14 at 6 36 37 PM" src="https://user-images.githubusercontent.com/68657634/107899892-79d4d900-6ef4-11eb-9429-d7e9c590d6b9.png">

**Metrics**
<img width="697" alt="Screen Shot 2021-02-14 at 6 36 50 PM" src="https://user-images.githubusercontent.com/68657634/107899894-7c373300-6ef4-11eb-9b1e-bdfeba3c9971.png">

**Partners**
<img width="697" alt="Screen Shot 2021-02-14 at 6 37 03 PM" src="https://user-images.githubusercontent.com/68657634/107899898-7fcaba00-6ef4-11eb-9f8f-159671256f37.png">

**Make a Donation**
<img width="698" alt="Screen Shot 2021-02-14 at 6 37 16 PM" src="https://user-images.githubusercontent.com/68657634/107899901-81947d80-6ef4-11eb-845a-38e2c0ad8412.png">

**Sponsors**
<img width="702" alt="Screen Shot 2021-02-14 at 6 37 27 PM" src="https://user-images.githubusercontent.com/68657634/107899907-835e4100-6ef4-11eb-8fe7-6053c92a8720.png">

**News**
<img width="700" alt="Screen Shot 2021-02-14 at 6 37 36 PM" src="https://user-images.githubusercontent.com/68657634/107899911-85c09b00-6ef4-11eb-97ec-895b026e434a.png">

**Comment by jbubar** [comment]
@drubgrubby @akibrhast The bug I found in this pr #1073 was just when you refresh the page after having clicked on a menu item
for example '/about-us#donations'
If you click on a menu item and then refresh the page does not calibrate correctly, does not have to do with mobile view..
Seems like @qiqicodes is already on that, but I though I would make a comment anyways. 😄

**Comment by drubgrubby** [comment]
@qiqicodes - I merged the fix for the accordion bug this past week.  It shouldn't impact any of the work that you're doing on this, but just to be safe I recommend updating the branch you're working on to make it current to make sure there are no conflicts.  Let me know if you have questions about how to do that.  (You may have done it already).

**Comment by qiqicodes** [comment]
Thank you @jbubar @drubgrubby for looping me in the pr #1073. The helpful information regarding the variable used for tracking the state between mobile and desktop is much appreciated. I am currently working on the feature at the moment. 

And in regards to the conflict, there is no conflict.

**Comment by pawan92** [comment]
@qiqicodes Can you please add the labels for status?

**Comment by qiqicodes** [comment]
@pawan92 I'm working on the label at the moment

**Comment by qiqicodes** [comment]
**Progress:** Fixed basic issue, highlighted link in the sticky navigation bar aligns to the content with corresponding id after resize or orientation change. I can create a pr to merge the my code to the gh-pages. 

Still working the feature that remembers the selected highlighted link in desktop mode and transfer to the corresponding location in mobile mode, and vice versa. 

**Blockers:** Should I move new feature under another issue? 

Needed to figure out what is causing the browser to behave the way it is. Need to figure out how to write the eventListener for the feature desired. 

**Availability:** Open on M/Tu/Th/F evening & Saturday morning & late night.

**ETA:** Desire to merge the new feature by 2/27/21 (It may take longer considering the complexity).
