### ISSUE TITLE
Order Issues on the Project Board Columns based on function

### ISSUE THREAD

**Issue by tarang100** [hackforla/website#969]
### Overview

- We need to arrange all Issues on the HfLA Website Project Board based on the function, in order to speed up discussions during the weekly team meetings
- We need to adhere to the following order when arranging Issues for Project Board columns titled as "Ice Box", "Prioritized Backlog", "In Progress", and "Links / Questions / In Review"
   - Development
   - Design
   - Product Management
- We do not need to arrange the Issues for the Project Board columns titled "Team Meetings", "Done", and "Project Profile Cards"

### Action Items

- [x] Drag and Drop all Product Management Issues to the bottom of each of the specified columns
- [x] Drag and Drop all Design Issues above the Product Management Issues for each of the specified columns
- [x] Drag and Drop all Development Issues above the Design Issues for each of the specified columns
- [ ] Identify how many good first issues are available to picked up in the prioritized backlog by discipline (e. FE, BE, Design)

### Resources/Instructions
[Link to the Project Board for HackforLA Website repository](https://github.com/hackforla/website/projects/7)

**Comment by tarang100** [comment]
Since all new issues, irrespective of the creator or the label, are automatically added to the bottom of the columns, regular review of the Project Board is necessary to maintain the sanctity of the above-mentioned structure. As PMs it is our responsibility to do these reviews and add a comment below to specify when was the Project Board last arranged and by who.

**Comment by tarang100** [comment]
Project Board arranged by @tarang100 on 03rd Feb 2021 at 23:01 (IST) / 9:32 (PST)

@pawan92 please review and arrange the Project Board before Sunday's meeting

**Comment by pawan92** [comment]
Project board arranged by @pawan92 on Feb 6 2021 11:30AM EST

@IAgbaje Please review and arrange the project board before tuesday meeting

**Comment by ahdithebomb** [comment]
Project Board updated by @ahdithebomb  on Feb 13 2021 10:37 PST

**Comment by tarang100** [comment]
Project Board arranged by @tarang100 on 17th Feb 2021 at 23:58 (IST) / 10:28 (PST)

@pawan92 please review and arrange the Project Board before Sunday's meeting

**Comment by shaswa** [comment]
Project Board arranged by @shaswa on Mar 10th 12:20 pm (EST) / 9:20 am (EST)
@Oluwafemi-Jegede Please review and arrange the project board before sunday meeting

**Comment by Oluwafemi-Jegede** [comment]
Project Board arranged by @shaswa on Mar 14th, 5:55 pm (GMT+1) / 12:55 pm (EST)
@shaswa  Please review and arrange the project board before Wednesday meeting

**Comment by tarang100** [comment]
Project Board arranged by @tarang100 on 17th March 2021 at 22:30 IST
@shaswa please arrange the board before Sunday's meeting

**Comment by shaswa** [comment]
Project Board arranged by @shaswa on 21st March 2021 at 5:00 EST
@Oluwafemi-Jegede  please arrange the board before Wednesday's meeting

**Comment by tarang100** [comment]
Project Board arranged by @tarang100 on 24th March 2021 at 22:55 IST
@Oluwafemi-Jegede  please arrange the board before Sunday's meeting

**Comment by Oluwafemi-Jegede** [comment]
Project Board arranged by @Oluwafemi-Jegede  on 4th April 2021 at 5:54 GMT+1
@tarang100  please arrange the board before Wednesday's meeting

**Comment by ExperimentsInHonesty** [comment]
@tarang100 did you organize the board for todays meeting?

**Comment by Oluwafemi-Jegede** [comment]
Project Board arranged by @Oluwafemi-Jegede on 11th April 2021 at 5:18 GMT+1
@tarang100 please arrange the board before Wednesday's meeting

Apologies @ExperimentsInHonesty I will not be able to attend the meeting, because I have an Emergency

**Comment by Oluwafemi-Jegede** [comment]
Project Board arranged by @Oluwafemi-Jegede on 14th April 2021 at 6:22 GMT+1
@tarang100 please arrange the board before Sunday's meeting

**Comment by Oluwafemi-Jegede** [comment]
Project Board arranged by @Oluwafemi-Jegede on 18th April 2021 at 5:55 pm GMT+1
@tarang100 please arrange the board before Wedneday's meeting
