### ISSUE TITLE
Change .page-card classname

### ISSUE THREAD

**Issue by daniellex0** [hackforla/website#976]
### Overview
We need to change the current .page-card classname (that is attached to the About Us page) to any different temporary name so that page cards can be standardized across the site.

### Action Items

- [x] Change .page-card classname in sass > elements > _cards.scss file to any other name

### Resources/Instructions
[Cards scss file](https://github.com/hackforla/website/blob/gh-pages/_sass/elements/_cards.scss)

**Comment by drubgrubby** [comment]
At Danielle's request, I commented out the page-card class.  The about-us page was not using this class. 

A Pull Request has been created.
