### ISSUE TITLE
Gh-pages environment variable research

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#98]
## Overview
To determine if there is a way to replicate obfuscation available in frameworks like react and vue, with a combination of environment variables and storing secrets

## resources:

- https://gist.github.com/nicolashery/5756478
- https://developer.github.com/actions/managing-workflows/storing-secrets/

**Comment by ExperimentsInHonesty** [comment]
@ExperimentsInHonesty & @ddrosario need to talk about where we are on this research.

**Comment by ddrosario** [comment]
It looks like the way to store secrets on GitHub is through GitHub Actions. GitHub Actions is in public beta. I still have not received a key, but we should probably put this on hold till Actions exits beta and is fully supported. 

https://developer.github.com/actions/

**Comment by ExperimentsInHonesty** [comment]
It is possible to use Github secret keys and github actions.  We are using it in various places on the website.  See WIKI for details.
