### ISSUE TITLE
Wins Page Badge Icon Visibility 

### ISSUE THREAD

**Issue by ahdithebomb** [hackforla/website#981]
### Overview
We need to modify the wins page so that there is at least a single badge is visible on the wins page per individual without having to double click on a person. 

### Action Items
- [x] First, the UX/UI team will figure out what's possible. 
- [x] Next, need to align and finalize/coordinate across stakeholders what the new badge will look like.
- [x] Once designed is finalized please update #1203 with design and remove dependency

### Resources/Instructions
[Wins Page](https://www.hackforla.org/wins)
[Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0)

**Comment by daniellex0** [comment]
Progress: Options posted on [Figma](https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0)

**Comment by daniellex0** [comment]
Progress: Design ready for final review - https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=1209%3A0

**Comment by pawan92** [comment]
@daniellex0 Can you please add the labels for status?

**Comment by daniellex0** [comment]
Progress: Created [usability hub a/b test](https://app.usabilityhub.com/do/e4438a764178/a36d) to run final designs by users 

Next Steps: Deploy a/b test on HfLA slack, and follow up with another one re: colors

**Comment by tarang100** [comment]
@daniellex0 Please message in the Admin Slack channel with the wording you would like at channeled so that we can post it in the general

**Comment by daniellex0** [comment]
Progress: I have a new design on Figma for a few sections on the Project page including the missing timezone, and need to have @ExperimentsInHonesty approval first : https://www.figma.com/file/0RRPy1Ph7HafI3qOITg0Mr/Hack-for-LA-Website?node-id=7891%3A0

Next steps: Get approval or edits

**Comment by daniellex0** [comment]
@tarang100 Sorry I had to adjust part of the test because of usability hub limitations, so I'll get review today and then post it on the Admin channel

**Comment by daniellex0** [comment]
**Progress:** The results are in, and people definitely prefer the icons over the circle badges:

<img width="500" alt="Screen Shot 2021-03-21 at 2 48 57 AM" src="https://user-images.githubusercontent.com/67400366/111900489-10168600-89f0-11eb-8c1f-6026881e7430.png">

Some of the reasons they gave:

- "More consistent with overlay, cleaner look. (Circles draw too much attention and compete with the text for focus)"
- "The circle icons seem a bit distracting with the circular profile pictures. I think this view makes them seem more unified with the card element."
- "Bigger icons, lighter feeling on first impact"
- "I like the variation among the shapes compared to the circles. If there was color involved, my opinion may change."
- "better visibility"

**Next Steps:** Consult with Bonnie about whether this is ready for development, or if there should be any more adjustments or a/b testing

**Comment by akibrhast** [comment]
Bonnie approved character limit. And add a section to be like, is there anything you would like this list to have that we missed?

**Comment by daniellex0** [comment]
An issue to develop this is currently being worked on: #1313

**Comment by akibrhast** [comment]
@daniellex0 can we close this ? Since there is an issue to develop this is currently being worked on?

**Comment by daniellex0** [comment]
@akibrhast sure, that's fine by me 👍
