### ISSUE TITLE
Update the TDM Calc project card

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#989]
### Overview
We need to update the TDM calc project so that it properly represents the current state of leadership and open roles, etc so that new people coming to the site can join the project or get current status.

### Action Items
- [x] Development
   - [x] See issue https://github.com/hackforla/product-management/issues/37 for update details

### Resources/Instructions
_projects/tdm-calculator.md

**Comment by akibrhast** [comment]
## Overview
Fixes #1008 

## Action Items
1.  [request](https://github.com/hackforla/product-management/issues/37#issuecomment-761925373) 
2.  [request](https://github.com/hackforla/product-management/issues/37#issuecomment-772230227)

- [x] Update Title
- [x] Update Blurb
- [x] Update Partner
- [x] Update Technologies
- [x] Update Leadership

**Comment by akibrhast** [comment]
Please take a look and let me know if it can be merged, or if there are things I could improve upon ?

@drubgrubby

**Comment by drubgrubby** [comment]
@akibrhast - Looks good on first glance.  We will look at it more closely at the meeting today.  If you can take a screen-shot of the changes and put them in the issue so we can see that the changes are showing up (and possibly make it faster to review) that would be good. Nice work. (Also, you might want to check the checkbox under "action items" at the top of this issue. )

**Comment by akibrhast** [comment]
![image](https://user-images.githubusercontent.com/32349001/107155036-2686e780-6944-11eb-8566-86aa7b1976db.png)

![image](https://user-images.githubusercontent.com/32349001/107155095-79f93580-6944-11eb-9acd-df70651efee8.png)
