### ISSUE TITLE
Update Project Profile: BallotNav

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/website#999]
### Overview
We want the BallotNav project to have a link to their project overview (one sheet) so that people who want to an overview of the project have access to one quickly.

### Project card
https://github.com/hackforla/website/tree/gh-pages/_projects/ballot-nav.md

### Action Items
- [ ] Add link to Overview document in card.
- [ ] Confirm that it is showing up at the bottom
- [ ] Add a screenshot to this issue in the comments

#### Resources/Instructions
- BallotNav Overview URL to link to: https://github.com/hackforla/product-management/blob/master/project-one-sheets/BallotNav-Project-One-Sheet.pdf
- Project card location: _projects/ballot-nav.md
- [BallotNav page on hackforla website, where you can take and match the screenshot](https://www.hackforla.org/projects/ballot-nav)
- [Template for what a project.md file format](https://github.com/hackforla/website/wiki/Template-of-a-project.md-file)
- What it should look like when you get it done
![Screen Shot 2021-02-02 at 9 19 29 PM](https://user-images.githubusercontent.com/37763229/106702000-79574c80-659c-11eb-8d0c-0934d51d1e9e.png)

**Comment by jbubar** [comment]
issue was completed and merged with pr #1020
